### ISSUE TITLE
formatter.formatCurrency causing StringIndexOutOfBounds exception

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#1004]
This is caused by this:
s = s.substring(0, s.lastIndexOf("."));
and when there is no "." in the string

**Comment by bradmac** [comment]
Shouldnt it return null? NaN is not the same as zero

**Comment by tuzzmaniandevil** [comment]
But the toDecimal method returns 0 when the supplied object is null?

**Comment by bradmac** [comment]
It probably shouldnt, but now its being used we cant change it. But best to do the right thing for new functionality
