### ISSUE TITLE
When user uses contact us entry form system creates an account for him 

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#101]
When user uses contact us entry form system creates an account for him and put him into contacts group.
I've send two messages and it registered two accounts for me. Is it correct?

**Comment by bradmac** [comment]
It will create a profile for the email address if it is not already present. If the email address matches an existing profile it should link the contact request to the existing profile. So you should not ever get 2 accounts for one email address.

**Comment by Uafinder** [comment]
Understood, thanks
