### ISSUE TITLE
Funnels

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1019]
Implement funnels for marketing analytics and lead management
- a Funnel is an inverse tree of Goals. Each goal has a next goal except the terminal goal
- a goal is attained when it is the current goal for a lead and one or more of its triggers are satisfied
- a Lead represents someone in a pipeline, possibly with an attached profile

**Comment by bradmac** [comment]
Functional now, but needs more UI work to be useable

**Comment by ducdhm** [comment]
@bradmac Let me take care of UI :)

**Comment by bradmac** [comment]
I just got some great feedback from the client today, so got a better idea of what it needs to be. I'll write some notes later...

**Comment by bradmac** [comment]
This has been extended and superseded by the journey builder
