### ISSUE TITLE
No possibility to change add to group parameter in contactus app settings

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#102]
![image](https://cloud.githubusercontent.com/assets/1945230/5873630/1bff11c6-a301-11e4-8a7b-6af1d48111d4.png)

When you select it once you can't change it back to Contacts group or to blank.

**Comment by tuzzmaniandevil** [comment]
"When you select it once you can't change it back to Contacts group or to blank." - Added option for None, If set to none it will use the default group "contacts" unless overridden by header meta addToGroup tag.

**Comment by Uafinder** [comment]
Well, if you change "Group to add contact to" to any group, press save, refresh page and then change it back to "None" - manage apps page become unavailable and contact us page produces an error.
![image](https://cloud.githubusercontent.com/assets/1945230/5987757/06be13d4-a946-11e4-9faf-7f831d89b8f0.png)

![image](https://cloud.githubusercontent.com/assets/1945230/5987759/0f7df2a0-a946-11e4-80ff-968e6a9e7783.png)

**Comment by bradmac** [comment]
Fixed in QA

**Comment by Uafinder** [comment]
YEap, looks ok!
