### ISSUE TITLE
Product Categories, New Feature

### ISSUE THREAD

**Issue by JPearcey** [Kademi/kademi-dev#1020]
Hi Kademi,

I would like to request a new feature for organising products that are bought in your online store.

We would like a field in admin to be able to select/enter a sub-category, which would then feed through to the store pages menu.

Please let me know if there are any further requirements or questions you have about this.

Cheers
JP

**Comment by bradmac** [comment]
:+1: 

There's been a few requests for sub-categories.

**Comment by tuzzmaniandevil** [comment]
a Category and select a "Parent Category", so it chooses which category it sits under.
This has been implemented in the Reward store and eCommerce store for the default templates.
