### ISSUE TITLE
Question about variables on certificate creation

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1028]
When i use regular editor
![image](https://cloud.githubusercontent.com/assets/1945230/11453566/ddcf55d0-9618-11e5-974e-ba39da166918.png)
When i switch to source:
![image](https://cloud.githubusercontent.com/assets/1945230/11453576/f7f351be-9618-11e5-925d-4b78c117a335.png)

There is no variables are visible in regular mode. Why?

**Comment by tuzzmaniandevil** [comment]
This is because Ckeditor  tries to parse the template code as html, so it used to replace quotes `"` with `&quote; ` which caused parsing errors.
A fix has to declare templating code as protected source so this wouldn't happen.
