### ISSUE TITLE
Manually create trigger fails

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#103]
![image](https://cloud.githubusercontent.com/assets/1945230/5892511/0b1c0808-a4ca-11e4-9a16-4effe9c1f726.png)
It gives next error
![image](https://cloud.githubusercontent.com/assets/1945230/5892516/1e8ebd18-a4ca-11e4-90a2-bd59080992fa.png)

**Comment by bradmac** [comment]
Fixed

**Comment by Uafinder** [comment]
looks like when you create any trigger now it creates it ok, but wrote a message
![image](https://cloud.githubusercontent.com/assets/1945230/5947591/1ff63288-a747-11e4-831b-08e15654db0a.png)

**Comment by bradmac** [comment]
1. Fixed
2. The "add trigger" button is only displayed when viewing trigger timers for an auto-email. Go into an email trigger, go to the triggers tabs, then select "Enable event delay", then a button is displayed to "View queued triggers". If you click on that you can then manually add trigger timers.

**Comment by Uafinder** [comment]
Yeap. Looks ok!
