### ISSUE TITLE
Missed fields or wrong table headers eCommerce

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1036]
Main eCommerce page contains Groups and Currency columns.
![image](https://cloud.githubusercontent.com/assets/1945230/11456767/71c11cfa-969c-11e5-979b-5813180c00a8.png)
However we can't specify such parameters on the stores edit page:
![image](https://cloud.githubusercontent.com/assets/1945230/11456776/bac53f12-969c-11e5-99e6-e2aa91ba35e4.png)
![image](https://cloud.githubusercontent.com/assets/1945230/11456777/c026f69e-969c-11e5-9006-56d03a55b8a2.png)
![image](https://cloud.githubusercontent.com/assets/1945230/11456779/cb27a494-969c-11e5-8e38-1a7989d842cf.png)
Are they missed or should they be there at all?

**Comment by ducdhm** [comment]
@Uafinder Currency is new feature of store and is developing.

**Comment by tuzzmaniandevil** [comment]
I have removed the fields from the table.
