### ISSUE TITLE
 show a warning when using an invalid email address

### ISSUE THREAD

**Issue by mamun4343** [Kademi/kademi-dev#1037]
For example check the image below:

![untitled](https://cloud.githubusercontent.com/assets/3419573/11462258/cb5fcfa6-9776-11e5-9a04-08baf4a39925.png)

**Comment by bradmac** [comment]
Should check that the domain of the from address matches a website domain.

**Comment by tuzzmaniandevil** [comment]
It now validates the "Target" email address to make sure it matches the website domain, It also checks to see if the website domain is empty
