### ISSUE TITLE
Auctions websockets do not identify organisation

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#104]
In the AuctionWebsockets class we have code like this:

    public void onClosing(Auction auction){
        this.websocketApplication.broadcast("auctionBid", auction.getName(), "{}");
    }

Where the application broadcasts the auction is closing to all websocket clients listening to a socket with the auction name. However, auction names are only required to be unique within an organisation. So if 2 different Kademi customers each had an auction with the same name their users would receive notifications about the other.

To solve this problem the ID of the websocket should include the organistaion ID as well as the auction name

**Comment by tuzzmaniandevil** [comment]
Fixed
