### ISSUE TITLE
Cannot add to group

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1041]
http://rspca-sa.admin.olhub.com/websites/rspca-sa-campaign/version1/#panel_groups-tab

Cannot add to group

**Comment by ducdhm** [comment]
Let me take care of this issue. Got same issue in some instance.

@paddyow TIP: Just turn off Sales Data App in Application menu ;)

**Comment by ducdhm** [comment]
@bradmac I double-checked it on locally env, there is no bug. It's weird!

**Comment by bradmac** [comment]
@ducdhm can you capture the ajax request to the server with the response. Also check the logs page on the server. Put any error messages here on the issue

**Comment by ducdhm** [comment]
Fixed on beta. Will deploy soon!
