### ISSUE TITLE
sometimes when we try to save a file 400: bad request  occur

### ISSUE THREAD

**Issue by mamun4343** [Kademi/kademi-dev#1044]
plz, check image below

![mf7weltzc15e5owe-xjf6euqbc8stqj-7cba75526ac6597c88a62f8c55409829d6e86c45](https://cloud.githubusercontent.com/assets/3419573/11463549/2b24dd1c-9788-11e5-9905-127589dd53bd.jpg)

**Comment by bradmac** [comment]
Good idea to check the logs page on the server at the time, and find the error message. That will help identify the problem

**Comment by tuzzmaniandevil** [comment]
I've tried to reproduce locally and on prod, no luck. I have seen it happen a few times as well, when it happens again i'll dig through the server logs to find the issue

**Comment by tuzzmaniandevil** [comment]
@mamun4343 Have you experienced this again? I haven't expreienced or been able to reproduce it

**Comment by mamun4343** [comment]
@tuzzmaniandevil  It's ok now. working just fine.
