### ISSUE TITLE
New app: Import social stream from facebook

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1045]
Kademi gives companies complete visibility of profile activity, our clients can see all of the interactions between their brand and the end customer including emails, sms, contact forms, web history, etc. The one major missing piece is social interactions when customers use the brand's social media pages.

Initially we will solve this problem for facebook.

For this issue, a Kademi client should see all facebook interactions with each user profile with the client's facebook account.

When this is enabled for a client they can setup multiple facebook accounts for the client's brands. Then the kademi server should regularly poll those facebook accounts to extract new interactions (like/comment/share/mention). 

For each interaction, attempt to locate a kademi profile and store that interaction connected to the profile. This information should be stored in a table, and also in elasticsearch through a new appindexer.

**Comment by tuzzmaniandevil** [comment]
@bradmac What about using this library to help?
http://projects.spring.io/spring-social/

**Comment by bradmac** [comment]
Looks good. Only thing i'm not sure about is whether it supports multiple connections for different customers, it seems intended for a single set of credentials per instance.

**Comment by bradmac** [comment]
Done a while ago.
