### ISSUE TITLE
Text Editor not working on for group emails

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#1048]
http://admin.mercedes.olhub.com/groupEmails/dp-enrollment-email(1)-2/#messages-tab

**Comment by ducdhm** [comment]
The content of EDM is not loaded in text editor :)

**Comment by Keegan01** [comment]
Normally when use the other option, it fills up the text editor which allows me to edit text. I have looked at another eDM and the text editor is not wokring

**Comment by Keegan01** [comment]
@ducdhm do you see the issue? I would like to have this fixed today.

**Comment by bradmac** [comment]
Resolved with #1049
