### ISSUE TITLE
Auctions App: AuctionViewerRole doesnt work when applied to organisation

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1050]
Permissions do not appear to be correctly applied when selecting an organisation. To resolve this i had to create a role based on the website repo.

Seen in starrewards

**Comment by tuzzmaniandevil** [comment]
@bradmac Tested locally and on sandbox, all seems fine.
What error did you see?

**Comment by bradmac** [comment]
The problem is that when this permission is granted within the context of an organisation (not website), in starrewards, users cannot access auctions. They get a permission error.

**Comment by bradmac** [comment]
But applying the permission to a repo (ie a website) works

**Comment by tuzzmaniandevil** [comment]
Fixed
