### ISSUE TITLE
Ability to ignore email items, which should exclude them from EDM statistics

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1051]
This will be used for test emails. Once ignored they should be excluded from totals for
 - email counts
 - open rate
 - click through rate

Note that we must not delete the email item because we need an immutable record for auditing.

Notify Lee@Flat Earth when done.

**Comment by tuzzmaniandevil** [comment]
This has been implimeneted for Automation emails.

**Comment by bradmac** [comment]
I was thinking just do it from the main email history page - http://kademi.admin.olhub.com/emails/

Having it on each individual history page is a nice to have, but on the main history page is a must have

**Comment by tuzzmaniandevil** [comment]
:+1:  It's now on the main email history page

**Comment by tuzzmaniandevil** [comment]
I think this should be good to go.
