### ISSUE TITLE
Add Analytics with date range to Automation

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1052]
http://cpaaustralia.admin.olhub.com/autoEmails/

Client has asked if you can choose a date range as there are lots of test emails prior to the campaign going live which gives incorrect data.

BM: Also see this issue - https://github.com/Kademi/kademi-dev/issues/1051

**Comment by bradmac** [comment]
I think we might need to split the page into 2 parts, either tabs or sections, so that first we have an analytics view with date filtering and export, etc. The second part has the list of jobs with management functions

**Comment by tuzzmaniandevil** [comment]
I like the tab idea personally, the main tab being analytics, so your first view is what's going on with the triggers with filters and CSV export. then the current page on another tab.

**Comment by tuzzmaniandevil** [comment]
I added some basic stuff for now.
So there is now 2 tabs, defaults to Analytics, that has the date range selector and CSV download and a basic histogram of fired triggers
