### ISSUE TITLE
Auditing phase 2

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1054]
- limit number of records displayed initially (currently killing my browser)
- implement restore points

Extension to
https://github.com/Kademi/kademi-dev/issues/918

**Comment by tuzzmaniandevil** [comment]
Limited to 1000 records for now.
This needs Kademi-vfs to be deployed.

**Comment by tuzzmaniandevil** [comment]
Is this what you were after?

![auditrecords](https://cloud.githubusercontent.com/assets/3378330/11517947/3dae9b2e-98f2-11e5-933c-2d1494cb3e2d.png)

**Comment by tuzzmaniandevil** [comment]
I've deployed VFS 1.6.8
