### ISSUE TITLE
eCommerce store checkout not working on chrome

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#1059]
It seems to be missing the cardnumber and cardcvn fields when serializing the fields,it works fine on firefox

**Comment by bradmac** [comment]
Have a look at the js code. It should be creating an ajax request programmatically, so should be easy to see why those fields are blank.

**Comment by ducdhm** [comment]
@tuzzmaniandevil Can you double check again? Make sure you use also default template of storeCheckout.html of bs335. It works normally in my side (Windows7 - Latest Chrome)

**Comment by tuzzmaniandevil** [comment]
@ducdhm I was using bs335 and default pages, nothing was edited. Will test again.

**Comment by tuzzmaniandevil** [comment]
It's working now again, must of been my browser cache.
