### ISSUE TITLE
Removing SMS gateway config causes page error

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#106]
Added SMS gateway configs to the SMS App under Applications.  
Removed SMS gateway configs and saved.

Now when you visit Applications, the page produces (Internal Server Error (500))
http://admin.asmidemo.olhub.com/manageApps

The Applications page cannot be accessed now since removing the config.

**Comment by tuzzmaniandevil** [comment]
Fixed

**Comment by Uafinder** [comment]
Looks like this happens not only with SMS Gateway function. I've create a limit for sending SMS, saved it, then go back and delete it, then saved it. Now Manage applications page produces 500 error.
Is there a possibility that some other apps will cause such errors?

**Comment by Uafinder** [comment]
Is it connected to 102? Looks like error gone here too.

**Comment by bradmac** [comment]
Yes, the problem was with settings being removed (ie set to blank), and affected any app settings which needed to change a setting to an empty value
