### ISSUE TITLE
Allow user to update meta tags like keyword, description without editing page source code

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#1060]

**Comment by bradmac** [comment]
We could incorporate that into the Info tab of the Quick Edit menu on edit web pages.

Slightly longer term i would like to remove the content editor from quick edit, and just make it a properties page

**Comment by tuzzmaniandevil** [comment]
:+1:  Would be cool to edit any data/parameter params.

**Comment by bradmac** [comment]
:+1:

**Comment by ducdhm** [comment]
@bradmac So, we will have an item on dropdownlist of each page named "Edit Properties" and will show all properties/parametters of page, right?

**Comment by bradmac** [comment]
Yes, sounds good. Sort of like windows with the properties dialog

**Comment by bradmac** [comment]
We cannot change the json structure in FileResource for this feature.
