### ISSUE TITLE
Add support for requirejs in KodeJS apps

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1066]
Can probably use this:

https://github.com/jrburke/r.js/

Note we will probaby need some custom way to resolve a path to a resource

I think we might need to implement the 'importScripts' method:
https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/importScripts

**Comment by tuzzmaniandevil** [comment]
importScripts is now implemented.
I also overrode nashorns "load" method so it works for Kademi's VFS as well.

**Comment by bradmac** [comment]
Think this is done now ... ?
