### ISSUE TITLE
SMS Test: validate email address

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1078]
On the send group SMS screen, the user can send a test to a particular recipient.

Currently there appears to be a bug where if the user enters something which does not locate a profile (eg if they mistakenly enter a phone number) then the test function sends to their own profile

This form should:
 - validate that the recipient is an email address
 - if the email address does not locate a profile display an error message

**Comment by mamun4343** [comment]
@tuzzmaniandevil  also its still showing "enter recipient number", it should be "enter recipient mail"
see img below

![untitled](https://cloud.githubusercontent.com/assets/3419573/11618025/a3601f04-9cfa-11e5-89a8-cc65fb42ad67.png)
