### ISSUE TITLE
Automation Trigger: Not showing Email History

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#1080]
Please notify Lee at FlatearthDirect when done

**Comment by tuzzmaniandevil** [comment]
Is showing correctly, Only shows last 7 days of emails by default.

**Comment by bradmac** [comment]
Howabout we change it to show the most recent 100 records?

**Comment by tuzzmaniandevil** [comment]
:+1:

**Comment by tuzzmaniandevil** [comment]
Done :-)
If no date range is specified it will now show the most recent 100 records.
