### ISSUE TITLE
Scheduled Emails: Change "Test" to work the same as group emails

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#1082]
At the moment fires the scheduled job, it should only send a test email to the currently logged in user or to a specified email address

**Comment by hoanglinhlan** [comment]
http://lantest07.admin.kademi-prod.com/scheduledEmails/07schedulemail001/#configuration-tab
after send test, it's showing green message "test send" but I don't give any mail

**Comment by hoanglinhlan** [comment]
hi @gonzalon 
please re-check, I still dont get any test mail

**Comment by gonzalon** [comment]
Seems ok
