### ISSUE TITLE
Integrate KEditor with EDM's

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1086]
We want the end result to be responsive email content. Note this will not use boostrap because we need to use inline css.

**Comment by ducdhm** [comment]
:+1:

**Comment by ducdhm** [comment]
Done with minimum features. Will be added more soon!

Features:
 * Set background for EDM
 * Set padding (top, bottom, left, right) for EDM
 * Set background for EDM body
 * Set padding (top, bottom, left, right) for EDM body
 * 3 snippets with 1 col, 2 cols and 3 cols. 2 cols and 3 cols can be responsive
