### ISSUE TITLE
add membership

### ISSUE THREAD

**Issue by mamun4343** [Kademi/kademi-dev#1087]
i think organization dropdown would be better from the current searching method.

check attachment
![untitled](https://cloud.githubusercontent.com/assets/3419573/11714019/ebf1fe7e-9f9b-11e5-900d-6c2e3d0e5d43.png)

**Comment by bradmac** [comment]
We can use a dropdown (ie a select box) because many customers have thousands of organisations in their database.

**Comment by bradmac** [comment]
Eg healthhub has about 2000.

**Comment by bradmac** [comment]
Although i guess we could make it conditional. The template could check how many orgs there are, and display a select box if less then about 20. What do you think?
