### ISSUE TITLE
edit module issue

### ISSUE THREAD

**Issue by mamun4343** [Kademi/kademi-dev#1088]
when i try to edit any module by click on  edit button. its showing weird. see attachment

![untitled](https://cloud.githubusercontent.com/assets/3419573/11714085/5863f382-9f9c-11e5-86c8-be81fa062495.png)

**Comment by bradmac** [comment]
It looks like the editor template hasnt been properly integrated with bs335.

@ducdhm can you look at this, after other high priority issues?
