### ISSUE TITLE
Litle bug with bs335   viewBlogs.html template  

### ISSUE THREAD

**Issue by mamun4343** [Kademi/kademi-dev#1090]
i see a extra $tag(black marked)
![untitled](https://cloud.githubusercontent.com/assets/3419573/11726284/cc7037f4-9fe2-11e5-974a-7a0a4a19609c.png)

**Comment by ducdhm** [comment]
@mamun4343 Can you give me link? Also admin console link?

**Comment by mamun4343** [comment]
@ducdhm   
Login user: http://admin.advancedclean.olhub.com/manageUsers/120129492/
frontend url: http://advancedclean.olhub.com/blogs/

**Comment by ducdhm** [comment]
Fixed on stock template and bs335
