### ISSUE TITLE
Custom Apps: Impliment MailBox so custom apps can handle emails

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#1091]
This will allow custom apps to act as an inbox, capture emails, forward emails, autoreply to emails or to run scripts on email content.

**Comment by tuzzmaniandevil** [comment]
@bradmac Could you give me a hand with this?

**Comment by bradmac** [comment]
:+1:

**Comment by tuzzmaniandevil** [comment]
Basic implementation done. Example:
```
controllerMappings
        .mailboxController()
        .enabled(true)
        .storeMail('storeMail')
        .build();
        
function storeMail(page, to, msg){
    log.info('storeMail - Page={},To={}, Msg={}', page, to, msg);
    
    var db = getOrCreateUrlDb(page);
    
    var d = {
        subject: msg.subject,
        text: msg.text
    };
    
    
    
    securityManager.runAsUser(to.user, function(){
       db.createNew("email_" + (new Date()).getTime(), JSON.stringify(d), "email"); 
    });
}
```

**Comment by tuzzmaniandevil** [comment]
EmailApp needs an option to NOT capture incoming emails.
This prevents custom apps from capturing emails if the email domain matches a website and the user matches a profile.

**Comment by tuzzmaniandevil** [comment]
I've implemented the emailApp settings https://github.com/Kademi/kademi-dev/issues/1091#issuecomment-163836472

**Comment by tuzzmaniandevil** [comment]
Ok this should be good to go now.
