### ISSUE TITLE
Cant manually fire trigger timers from the main trigger timer page

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1092]
On the main trigger timer page, eg http://rspca-sa.admin.olhub.com/autoEmails/timerTriggers.html ,  when you select trigger timers the green play icon button is still disabled, so you cannot fire them

But this works correctly on indivudual trigger timer pages, eg http://rspca-sa.admin.olhub.com/autoEmails/118635385/timerTriggers.html

We should be able to fire from the main trigger timers page

**Comment by tuzzmaniandevil** [comment]
All done
