### ISSUE TITLE
Email tracking and forwarding in lead management app

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1095]
A lead management user (ie a sales person) should be able to forward an email received from a lead to a special email address and have it automatically recorded against the lead.

They should be able to choose an address for recording emails received from the lead, and also for emails sent to the lead.

They should also be able to send emails to a special address which are recorded and then forwarded. These emails should have their contents adjusted, so that auto-login tokens and edm id's are appended to links, as well as standardised templating.

**Comment by bradmac** [comment]
Additional features:
- add auto-login tokens for links to kademi websites
- attachments should be removed from email and made available securely through the website, with an auto-login token
- there should be some way to inform the sales consultant when a lead has opened or viewed a link or attachment

**Comment by tuzzmaniandevil** [comment]
- add auto-login tokens for links to kademi websites - **Done**

**Comment by tuzzmaniandevil** [comment]
- there should be some way to inform the sales consultant when a lead has opened or viewed a link or attachment - **Done**

**Comment by tuzzmaniandevil** [comment]
- attachments should be removed from email and made available securely through the website, with an auto-login token - **Moved to issue #2176**

**Comment by tuzzmaniandevil** [comment]
@hoanglinhlan Do test the login token, you will need to do it on AWS as you need to send an email to the server to be able to test it.

**Comment by hoanglinhlan** [comment]
passed
