### ISSUE TITLE
Implement expression based delays for automations

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1096]
Currently automations can fire immediately, or be delayed by a fixed amount.

But we need the ability for automations to fire after a variable delay. For example, if someone registers for something on a certain day, we might want them to be reminded 3 days before the day. In this case the expression might be

formatter.addDays(profile.fields.registerDate, -3)

Please notify Leonard when ready

**Comment by tuzzmaniandevil** [comment]
Done,

The expression can return a Date object or a string that can be parsed into a date.
The following variables are available:
- rootFolder
- profile
- event
- organisation
- formatter
- timerFireAt - The time calculated by the "Fire the next event after:" and "Specify Timer Time" field
- user
- request


So here is an example for Leonard:
```
return formatter.addDays(user.fields.registerDate, -3)
```
