### ISSUE TITLE
Fixed expiration date policy for reward points

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1097]
Reward points have an expiry date which is set when they are created. Currently it can be set to some time interval, eg 12 months after being awarded.

We also need the ability for reward points to expire on a specified date. For example, reward points might expire 31/3/2016

It might be useful to support expressions, so that we can have rolling fixed end dates

This is required for the Mercedes project before end of Jan 2016

**Comment by tuzzmaniandevil** [comment]
@bradmac We do support a specific date already. 
![screenshot from 2015-12-15 10 03 47](https://cloud.githubusercontent.com/assets/3378330/11793910/31a2a976-a313-11e5-814c-baa20589de41.png)

**Comment by bradmac** [comment]
Cool!
