### ISSUE TITLE
Prevent disabling of core apps

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1099]

**Comment by ducdhm** [comment]
:+1: Sometime our users don't know which apps are important and they turned off some important apps. Then they crash the system and can not login anymore

**Comment by ducdhm** [comment]
Maybe we can move them to separate panel at top with title "Core apps" just let users can change settings of these apps.

**Comment by bradmac** [comment]
I've just removed the switch for these apps. We still want a full redesign of the apps pages, but that can wait for another day :)
