### ISSUE TITLE
Add support for embedding audio files in content editor

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1108]

**Comment by anhnt** [comment]
There will be a button like following screenshot. @bradmac can you have a look at this plugin?
![embed audio](https://cloud.githubusercontent.com/assets/735555/12412796/4850cf44-bebc-11e5-8566-3079d433b4e9.png)

**Comment by anhnt** [comment]
Just switch to use jwplayer to allow older browser can play media

**Comment by anhnt** [comment]
Needs to support bs320 theme
