### ISSUE TITLE
Add ability to acknowledge/hide a contact request on manageContacts page

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#111]
- Add the ability to acknowledge a contact request which will hide it from the list making contact requests easier to manager. 
- Add a button to view all previously acknowledged requests.

**Comment by Uafinder** [comment]
1. It doesn't remember users choice about show or hide acknowledged requests after page refreshing. It's setup to hide them by default.

2. Button which show/hide requests begin to work incorrect after second pushing. E.g. when you push it once - button label is changing ok, acknowledged requests appear in the list, when you push it for the second time button label doesn't change. However, it hides  acknowledged requests.

**Comment by tuzzmaniandevil** [comment]
"1. It doesn't remember users choice about show or hide acknowledged requests after page refreshing. It's setup to hide them by default." - This is correct.

**Comment by tuzzmaniandevil** [comment]
"2. " - Fixed

**Comment by Uafinder** [comment]
1. Understood
2. Fixed - WOrks ok!

Some else:
1. Minor grammar error
![image](https://cloud.githubusercontent.com/assets/1945230/6175450/90c2f14a-b2ff-11e4-903c-d340d363f45a.png)
2. There is a possibility to acknowledge the already acknowledged request. Should be that option when request already acknowledged.
3. I think that will be reasonable to create a possibility to un-acknowledge contact request (e.g. return it to non-acknowledged). How do you think?

**Comment by Uafinder** [comment]
Everything the same!

**Comment by bradmac** [comment]
I think that might have been accidentally made ready to test. Looks like it hasnt actually been worked on.

**Comment by Uafinder** [comment]
Everything the same again. Hrrr!

**Comment by bradmac** [comment]
@tuzzmaniandevil i think this has been done?

**Comment by tuzzmaniandevil** [comment]
Fixed a couple of issues
