### ISSUE TITLE
KChat is showing error "WebSocket is already in CLOSING or CLOSED state."

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#1110]
Please have a look at this site http://ecommerce-demo.olhub.com/
Admin: http://admin.ecommerce-demo.olhub.com/

I've integrated kchat on frontend site so please see console error for detail.

**Comment by tuzzmaniandevil** [comment]
Seems to be an issue with websockets. Even the websockets on the admin logs page doesn't work.

**Comment by anhnt** [comment]
yep looks like it's not ready

**Comment by bradmac** [comment]
Admin logs page seems to work fine, I just checked kademi admin logs, and loaded the kademi website, and i saw the logs appear. So i think websockets generally is working ok.

**Comment by tuzzmaniandevil** [comment]
Fixed
DB Error, column satisfied was an integer, needed to be a boolean.

**Comment by bradmac** [comment]
Still some problems:
https://github.com/Kademi/kademi-demos/issues/42

**Comment by tuzzmaniandevil** [comment]
Replaced with #4594
