### ISSUE TITLE
Add Braintree as a payment provider

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#1114]
API:
https://github.com/paypal/PayPal-Java-SDK

**Comment by bradmac** [comment]
:+1: 

Only slightly tricky bit is implementing instant payment notification, but shouldnt be too hard. I've actually done this before a couple of times.

**Comment by tuzzmaniandevil** [comment]
That is if we use the PayPal JavaScript button, and using custom integration requires us to be PCI DSS complaint. But I found another solution, Braintree, a company by PayPal which accepts PayPal, credit cards and a few other payments. it also does client side tokenization so we don't handle card info directly :-) https://www.braintreepayments.com/

**Comment by tuzzmaniandevil** [comment]
This is now functional and implemented

**Comment by bradmac** [comment]
Wow, that was fast!

Sent with AquaMail for Android
http://www.aqua-mail.com
