### ISSUE TITLE
Subfolder dropdown menu looks not good

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#1116]
![untitled](https://cloud.githubusercontent.com/assets/1289631/11835392/c0ef7684-a405-11e5-994a-fd8838af9537.png)

**Comment by tuzzmaniandevil** [comment]
:+1:  Make it look awesome @ducdhm

**Comment by ducdhm** [comment]
Just made it like program dropdown list (Design by me LOL)

![untitled](https://cloud.githubusercontent.com/assets/1289631/11929603/35115f98-a80f-11e5-80ab-cdda8b43134b.png)
