### ISSUE TITLE
User who already registered with eCommerce demo site cant submit new order

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#1117]
Sometimes user who has already submitted an order using his email cant submit new order with this email again.

Please test using some new email in this site http://ecommerce-demo.olhub.com/ and then using this email again to submit new order.

**Comment by tuzzmaniandevil** [comment]
@bradmac How should we handle this? Look up a profile with the email address and use it if found?

**Comment by bradmac** [comment]
Yep, should be like contact app. Associate with existing profile but don't 
log them in

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by tuzzmaniandevil** [comment]
Cools. :+1:
