### ISSUE TITLE
Minifier: Add the ability to minify JS/CSS/HTML/LESS files

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#1120]
Have an option to compress Less files when generated server side.

Have an app to minify JS, CSS and HTML pages. Should be able to select which files to minify in app options.

**Comment by tuzzmaniandevil** [comment]
The Dynamic CSS App now has an app setting to enable less compression, So compiled less can put put as compressed CSS.

**Comment by tuzzmaniandevil** [comment]
Node Less servers updated on Prod and sandbox. Testing on Sandbox and working :-)

**Comment by tuzzmaniandevil** [comment]
We can maybe use something like https://github.com/yui/yuicompressor to minify CSS and JS files

**Comment by bradmac** [comment]
Note we're already gzipping text files, which has a higher compression rate then minifying

**Comment by bradmac** [comment]
Combining files can have a big performance improvement, though

**Comment by tuzzmaniandevil** [comment]
I see the Dynamic Css app does have some support for combining JS files. If we can do something like
```
$templater.pushJs
```
And
```
$templater.pushCss
```
That will be a really good feature to have. It should help decrease load time a fair bit depending on how many js/Css files gets loaded

**Comment by tuzzmaniandevil** [comment]
I've added the API to do this to the new template engine.

```
$templater.pushJs("/templates/themes/bootstrap335/js/common.js")
$templater.pushJs("/static/js/jquery-1.9.1.js")
    
<script type="text/javascript" src="$templater.combinedJsPath"></script>
```

**Comment by tuzzmaniandevil** [comment]
Css Example:
```
    $templater.pushCss("/static/history/jquery.history.css", "screen")
    $templater.pushCss("/static/bootstrap-msg/0.3/bootstrap-msg.min.css", "all")
    $templater.pushCss("/static/font-awesome/4.4.0/css/font-awesome.min.css", "all")
    
    #foreach( $cssSource in $templater.cssSources.entrySet())
    <link href="/$templater.getCombinedCssPath($cssSource.value)" rel="stylesheet" type="text/css" media="$cssSource.key" />
    #end
```

**Comment by tuzzmaniandevil** [comment]
This is it for stage 1 :-)
