### ISSUE TITLE
Implement versioned custom app

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#1128]
For dependencies purpose.

Start with versioned themes, then look at versioned deps

**Comment by bradmac** [comment]
Now displays in use version:
![screenshot-localhost 8080 2016-08-08 12-26-35](https://cloud.githubusercontent.com/assets/826458/17466394/7de3132e-5d63-11e6-9131-aea24852e5f6.png)

**Comment by bradmac** [comment]
The version can be changed from the settings dialog

![screenshot-localhost 8080 2016-08-08 12-32-09](https://cloud.githubusercontent.com/assets/826458
/17466442/39f01044-5d64-11e6-9295-39468af5a8b8.png)

**Comment by bradmac** [comment]
A notification is displayed when a new version is available

![screenshot-localhost 8080 2016-08-08 14-29-48](https://cloud.githubusercontent.com/assets/826458/17467658/ac63552c-5d74-11e6-9bd7-6913fe53c6ed.png)

To test, find a custom app (eg nvd3-lib) and create a new version in file manager, then re-publish from the app's market place page, eg
http://localhost:8080/manageApps/nvd3-lib/#market-tab

**Comment by hoanglinhlan** [comment]
Failed
Precondition: user-lib/ live version is 2.0.0
**Step**: 
- http://localhost:8080/repositories/user-lib : created new version 2.1.0 
- http://localhost:8080/manageApps/user-lib/#market-tab: re-publish this app
- Publish version 2.1.0

==> notification display wrong and app'version auto change to new live version, refer the img

![image](https://cloud.githubusercontent.com/assets/20508726/18379038/8c732ef6-769a-11e6-9321-32d6a4458df5.png)

**Comment by bradmac** [comment]
@tuzzmaniandevil can you investigate the issue above please?

**Comment by tuzzmaniandevil** [comment]
@hoanglinhlan i've done some fixes, When testing make sure to test across 2 orgs, not in the same org.

**Comment by hoanglinhlan** [comment]
create a new version and publish this on 2 case
case1: app  set on a version that not a publish version (maybe it's an old version) ==> passed
case2: app set on a publish version ==> still failed: system display the app's version is a new version and update avaiable is last version

**Comment by hoanglinhlan** [comment]
my last comment, I set incorrect orgs
Confirm passed
