### ISSUE TITLE
Products CSV import and export

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#113]

**Comment by Uafinder** [comment]
1. Incorrect label of upload window.
![image](https://cloud.githubusercontent.com/assets/1945230/5947062/2bb5aabc-a743-11e4-8d48-c390c12e96f4.png)
2. Uploading doesn't work. I've download a CSV, make some changes to them, copy a string, change there code, title and id and it doesn't imported. It writes that 1 record is updated and no is imported no matter how much records i've add to a CSV file. 
![image](https://cloud.githubusercontent.com/assets/1945230/5947196/f918c50c-a743-11e4-881f-bf8383507c73.png)

**Comment by tuzzmaniandevil** [comment]
"1. Incorrect label of upload window. " - Fixed

**Comment by tuzzmaniandevil** [comment]
"2. Uploading doesn't work. I've download a CSV, make some changes to them, copy a string, change there code, title and id and it doesn't imported. It writes that 1 record is updated and no is imported no matter how much records i've add to a CSV file." - Fixed

**Comment by Uafinder** [comment]
Both fixed. Worked ok.
one question: do we allow users create products with the same codes? If it's correct, then this issue can be closed.
![image](https://cloud.githubusercontent.com/assets/1945230/6009080/3247e86e-ab2f-11e4-9514-9f2fa0871cbe.png)

**Comment by tuzzmaniandevil** [comment]
No we do not allow products with the same code to be loaded.

**Comment by Uafinder** [comment]
So we need to implement a validation on Code field when creating a product via "create product" button and when products are created via CSV.

**Comment by tuzzmaniandevil** [comment]
https://github.com/Kademi/kademi-dev/issues/113#issuecomment-72538530 - Fixed for CSV Upload

**Comment by Uafinder** [comment]
Validation when creating a product via GUI - fixed
Validation when creating a product via CSV doesn't work. System should matches products by Product ID field. If we are uploading a csv which contains a string where product id is empty and product code is doubling with already existed it should mark this string as error and give a description of this error. Am i right?

**Comment by tuzzmaniandevil** [comment]
"Validation when creating a product via CSV doesn't work. System should matches products by Product ID field. If we are uploading a csv which contains a string where product id is empty and product code is doubling with already existed it should mark this string as error and give a description of this error. Am i right?" - Fixed

**Comment by Uafinder** [comment]
Well, validation is working, but it working incorrect:
1. When i want to upload a product details i've upload a string which contains old (const) product id, and provide a new info e.g. code, title, cost, etc. It gives me an error.
2. When i want to upload only a one or two attribute of product i've upload a string which contains old product id and old product code. It gives me a validation error instead.
![image](https://cloud.githubusercontent.com/assets/1945230/6048314/ff460056-acb7-11e4-8cad-a4b2feae4781.png)

**Comment by tuzzmaniandevil** [comment]
Fixed

**Comment by Uafinder** [comment]
Both fixed. Look ok for use
