### ISSUE TITLE
New editor: Content Editor

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#1131]

**Comment by ducdhm** [comment]
![aaa](https://cloud.githubusercontent.com/assets/1289631/11929630/6fa55484-a80f-11e5-8432-ef534c6835f0.png)

![bbbb](https://cloud.githubusercontent.com/assets/1289631/11929838/009cebc2-a811-11e5-8692-3f5d4a601926.png)

**Comment by bradmac** [comment]
Awesome!!

**Comment by bradmac** [comment]
Re-opening, because still needs to be integrated with the video editor.

**Comment by ducdhm** [comment]
Let's move to https://github.com/Kademi/kademi-dev/issues/1138
