### ISSUE TITLE
Points fully used status

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1133]
Points records are marked as fully used when redemptions have been allocated to them equalling their value. For example, if a user has a single 100 point record and then makes a 50 point redemption, and then another 50 point redemption, then the points record will be marked as fully used, and will not be considered for future redemptions.

If an administrator then modifies the points record, increasing its points value, it will give the appearance of available points but it will not be able to be used for redemptions because it is still marked as fully used.

To solve this problem we should
- display the fully used status of points records on the manage points page (perhaps as a badge or label)
- not allow fully used points to be modified

**Comment by anhnt** [comment]
![image](https://cloud.githubusercontent.com/assets/735555/26780855/d5ac5ecc-4a15-11e7-99bd-f92605699799.png)

Finally done

**Comment by bradmac** [comment]
hey @anhnt can you combine this with the expiry col?

If the points is fully used then we dont care about its expiry date, so we can display one or the other

**Comment by anhnt** [comment]
done

**Comment by hoanglinhlan** [comment]
passed
