### ISSUE TITLE
Update snippets for KEditor

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#1142]
@mamun4343 @anhnt @tuzzmaniandevil @bradmac @paddyow Please feel free for comment and add more snippets or send me a link to any snippet which you think it's useful for KEditor. 

*Note: It's can be your own snippet and all classes need to be Bootstrap classes

**Comment by anhnt** [comment]
:+1:

**Comment by anhnt** [comment]
a lot of snippets here and this is an example for team members list http://bootsnipp.com/snippets/featured/responsive-team-profiles-with-social-links-free

**Comment by ducdhm** [comment]
@anhnt Yep, there are a lot of snippets on bootsnipp but we need snippets which have only Bootstrap classes.

**Comment by ducdhm** [comment]
@bradmac Now, please update snippet at `/src/main/webapp/templates/themes/admin2/keditor/snippets.html`

**Comment by ducdhm** [comment]
We have all snippets which we need for our first version. If you have any cool snippets, please create issue for me to add them into KEditor. Thanks
