### ISSUE TITLE
Issue with left menu in admin console

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#1144]
Sometime, when the page is short, left menu will be cut-off at bottom. Impossible to scroll down

**Comment by mamun4343** [comment]
@ducdhm i also see it  when image uploading for any module. Ok button always hidden. No way to scroll.

![untitled](https://cloud.githubusercontent.com/assets/3419573/12016524/2433b0e2-ad76-11e5-8d0b-d87affbdb6b8.png)

**Comment by ducdhm** [comment]
@mamun4343 It's not same problem!
