### ISSUE TITLE
Draft version for KEditor

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#1146]
Let me play with this issue and try to release draft version for it. 
Result of this issue is:
 * New content editor
 * with drag and drop feature like ContentBuilder(CB)
 * editing inline with CKEditor.inline()

**Comment by bradmac** [comment]
Couple of ideas
- as a content author, i want to drag pre-formatted snippets into the content area as rows
- each row should be draggable up and down to reposition, and deletable and copyable
- clicking into a snippet which has been dragged into the content area should activate the editor (ie ck editor) for that snippet. For snippets which have more then 1 section, each section should be its own editor section
- I do not want sections to be forced to have the content type of the original snippet. Eg if i drag a 2 column snippet into the content area with a video on the left and text on the right, i want to be able to delete the video and replace it with text, or to add text above or below. Or i might want to add video or image into the text section, etc.

**Comment by ducdhm** [comment]
@bradmac can you the draft version first and give me feedback?

FYI: embed_video and fuse-image are making cant type spaces in CKEditor in inline mode. I'm investigating the problem...

**Comment by bradmac** [comment]
Woohoo!

**Comment by anhnt** [comment]
I'm playing with those :)

**Comment by ducdhm** [comment]
Almost done. Just need work around with re-position all elements inside content area

**Comment by bradmac** [comment]
looking good!

**Comment by ducdhm** [comment]
Done for draft version with following features:
 * Drag n Drop snippet in content area
 * Section in content area can be editable with CKEditor (Inline mode)
 * Section in content are can be repositionable and deletable
