### ISSUE TITLE
Funnel analytics

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1149]
Visualisation of funnel progress
- show number of leads in each stage, grouped by source
- visualisation as a funnel, entry stages at top, conversion stage at the bottom
- each source is a circle, with its size representing the number of leads for that source at that stage

Later enhancement to allow grouping by other factors, such as team (for lead management), device, etc

**Comment by bradmac** [comment]
Sample data here - https://github.com/Kademi/kademi-dev/tree/master/src/main/webapp/static/scratch/funnels

**Comment by bradmac** [comment]
Visualisation should be done with cola.js - http://marvl.infotech.monash.edu/webcola/

**Comment by ducdhm** [comment]
:+1:

**Comment by bradmac** [comment]
The graph icon in the navbar now gives a drop down of analytics pages, for each funnel.

The analytics page shows the funnel with counts by source. Want to extend that to allow displaying total deal value, acquisition cost, etc
