### ISSUE TITLE
fuse-image plugin does not let CKEditor add space character in Inline Mode

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#1152]

**Comment by ducdhm** [comment]
Code of this plugin is under `/kademi-dev/src/main/webapp/static/ckeditor440/plugins/fuse-image/`

**Comment by anhnt** [comment]
it is working fine for me @ducdhm

**Comment by ducdhm** [comment]
Yeah. After cleaning cache, it's working fine.
