### ISSUE TITLE
LeadMan: Add dashboard search

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1168]
The first thing I need to do when I go into the CRM is search for a company or name.

![crm](https://cloud.githubusercontent.com/assets/2201340/12160090/72e02928-b523-11e5-8fcc-6d438fbe4b9b.png)

**Comment by bradmac** [comment]
Will implement organisations as a seperate issue, so will just have profile search initially

**Comment by bradmac** [comment]
I think its best to have search in the top nav bar, so you can search on any page. Like we have in admin
