### ISSUE TITLE
Shopping cart auto trigger events

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#118]
Also generates trigger events
- checkout completed
- item added to cart

**Comment by Uafinder** [comment]
Minor error: It shows a website number instead of it's name. Should be name!
![image](https://cloud.githubusercontent.com/assets/1945230/6113125/8c5b8a5e-b09d-11e4-8f1e-62537fff9ba9.png)

**Comment by tuzzmaniandevil** [comment]
"Minor error: It shows a website number instead of it's name. Should be name!" - Good Spotting, Now fixed
