### ISSUE TITLE
Search Stream - Enhancement 

### ISSUE THREAD

**Issue by JPearcey** [Kademi/kademi-dev#1181]
Hi Kademi,

On the search stream page in admin, if I scroll down several pages when I click the link "i" it puts the expanded error message at the top of the page.

Can we have it where it appears next to the exception I clicked on, and also highlighting the exception block on the left that was clicked on so we don't lose out place in the time stream.

(admin)/searchStream

Thank You

**Comment by bradmac** [comment]
:+1:
