### ISSUE TITLE
Custom Apps: Implement App dependencies

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#1186]
This is for when an app depends on other apps being enabled.

For example if we have an app called "DailyJokes" and it uses the email app to send emails. Then when DailyJokes get's enabled it should also enable the email app if it's disabled.

**Comment by tuzzmaniandevil** [comment]
It should also not allow users to turn off apps that other apps depend on. For example if "DailyJokes" is enable the user shouldn't be able to disable the email app.

**Comment by tuzzmaniandevil** [comment]
Example in XML:
```
<controllers>
    <source>/APP-INF/app.js</source> 

    <dependencies>
        <dependency>
            <appId>email</appId>
        </dependency>
        <dependency>
            <appId>KongoDB</appId>
            <adminOnly>true</adminOnly>
        </dependency>
    </dependencies>

</controllers>
```

and in JS:
```
controllerMappings
        .dependencies()
        .add('email')
        .add('KongoDB', true)
        .build();
```

**Comment by ducdhm** [comment]
:+1:
