### ISSUE TITLE
My files app create folder bug

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1197]
![image](https://cloud.githubusercontent.com/assets/1945230/12401690/c99f4e0e-be30-11e5-9376-9aaca6ec0588.png)
1. Push new folder
2. Enter name and click create
3. Watch that it's not appears in list

**Comment by bradmac** [comment]
hey @anhnt, want to take this one?

**Comment by anhnt** [comment]
cool :+1:

**Comment by anhnt** [comment]
Fixed this issue. However when click to the folders which is created, get a blank site. Will create new issue for it
