### ISSUE TITLE
Convert email to lower case when registering users

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#121]
Currently there can be a problem if a user registers with different case of an email addresses. We should always convert email to lower case when registering, either through user signup, contact submission, or through admin screens or CSV upload

**Comment by tuzzmaniandevil** [comment]
Done

**Comment by Uafinder** [comment]
1. Converting to lower case doesn't work when you're uploading users from CSV.
![image](https://cloud.githubusercontent.com/assets/1945230/6008627/cb6c2752-ab2b-11e4-8794-24042e35959c.png)
2. Converting to lower case doesn't work when you're creating user via admin screen "add user" button.
![image](https://cloud.githubusercontent.com/assets/1945230/6008664/1221053c-ab2c-11e4-9691-2b2fe108a427.png)
3. Looks like conversion function is interrupts users from signup to front-end sites when they are using Upper case in emails. It shows no messages and doesn't pass user through. When user enters all lower-case - registration is successful.
![image](https://cloud.githubusercontent.com/assets/1945230/6008772/c37f4208-ab2c-11e4-8956-04676de72d88.png)

**Comment by Uafinder** [comment]
1. Still active
![image](https://cloud.githubusercontent.com/assets/1945230/6029186/84ff0efc-abf7-11e4-803e-8f5b1c18abad.png)
2. Still active
![image](https://cloud.githubusercontent.com/assets/1945230/6029214/a93d051c-abf7-11e4-9996-3241d3f969f4.png)
3. Looks fixed.

**Comment by bradmac** [comment]
Ah yes, forgot about the first 2

**Comment by tuzzmaniandevil** [comment]
Seems to be working correctly now

**Comment by Uafinder** [comment]
Both fixed. Works ok.
