### ISSUE TITLE
KCRM - Reassign incoming tasks

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1212]
Should be able to click on an incoming task, open it a re-assign to someone else.

![image](https://cloud.githubusercontent.com/assets/2201340/12469207/adc92984-c024-11e5-9da8-99c1665f9107.png)

**Comment by tuzzmaniandevil** [comment]
Done, Clicking on the green circle with the T will bring up a modal to edit, re-assign and close the task
