### ISSUE TITLE
KCRM: Make the lead sheet awesome

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1216]
For example:
http://kcrm.olhub.com/leads/

The lead sheet should:
- allow a quick view of current leads, showing current status, including current tasks, who is assigned, lead stage, current goal, etc
- allow quick searching to find a lead
- allow quick updates of lead stage, task assignment, etc, with inline editing
- summary stats would be nice

**Comment by tuzzmaniandevil** [comment]
Am I on the right track?

![leadmanawesome1](https://cloud.githubusercontent.com/assets/3378330/12666521/868284c8-c6a6-11e5-82d1-ffc7ca2e4d49.png)

**Comment by tuzzmaniandevil** [comment]
Inline editing supports Deal amount and Stage.
Stage has a limitation where the dropdown lists stages from all funnels.
@Duc can you help with that? It's using DataTables with the Editor plugin

**Comment by bradmac** [comment]
Thats fine, we can live with that for now
