### ISSUE TITLE
Infiniti CRM

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1224]
http://infiniti-crm.olhub.com/dashboard

Make the purple/blue color black across the whole App to match Infiniti branding.

![image](https://cloud.githubusercontent.com/assets/2201340/12534794/a1004dc8-c2a3-11e5-8cfc-4c427eed0efc.png)

**Comment by bradmac** [comment]
Note this needs to be done within the infiniti account as a customisation

http://infiniti.admin.olhub.com

**Comment by ducdhm** [comment]
Done!
