### ISSUE TITLE
Infinite CRM: Update template and colors

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1225]
http://infiniti-crm.olhub.com/dashboard

- Add Infiniti logo
- Make icons in header all off-white #d2d2d2
- Make top bar black
- Update the blue colour to the Infiniti purple 
- Line up the top icons 

![image](https://cloud.githubusercontent.com/assets/2201340/12534848/351928ac-c2a6-11e5-9651-c801b5f2d58d.png)

![image](https://cloud.githubusercontent.com/assets/2201340/12534833/f34e433a-c2a5-11e5-9e4a-421da7b6ef84.png)

**Comment by bradmac** [comment]
Note this needs to be done within the infiniti account as a customisation

http://infiniti.admin.olhub.com

**Comment by ducdhm** [comment]
Done!

**Comment by paddyow** [comment]
Anh please update the Infiniti Demo to have these colours as before.

**Comment by anhnt** [comment]
done
