### ISSUE TITLE
KCRM: Contact links

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1227]
Brad what should happen if someone clicks on the phone icon?
Should we add one for linkedin then add all these fields to the profile page?

![image](https://cloud.githubusercontent.com/assets/2201340/12535740/2b6cc936-c2c8-11e5-9dc1-29619ef7d7c5.png)

**Comment by bradmac** [comment]
Thats from the original template, so not fully integrated. I think we worry about social media links in a later stage

**Comment by bradmac** [comment]
I think the phone link should be able to launch the dialer on mobile
