### ISSUE TITLE
KCRM: Missing an icon

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1232]
Add a tick before the copy in the alert

![image](https://cloud.githubusercontent.com/assets/2201340/12535857/ae14be44-c2cc-11e5-9da1-3733aab4323e.png)

**Comment by tuzzmaniandevil** [comment]
Fixed Icon, but icon it hard coded in Msg.

**Comment by ducdhm** [comment]
I'll do it https://github.com/ducdhm/bootstrap-msg/issues/1 ;)
