### ISSUE TITLE
KCRM: Activity timeline

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1235]
Seems to be missing an icon

Have activities alternate and switch from left to right based on the type i.e. it could show 3 emails on the left, then 1 note added on the right, then 2 website hits on the left......

![image](https://cloud.githubusercontent.com/assets/2201340/12535903/200471d8-c2ce-11e5-9b44-1be099b3262f.png)

**Comment by bradmac** [comment]
Items are arranged with inbound on the left and outbound on the right.

**Comment by bradmac** [comment]
@tuzzmaniandevil so just need to check the missing icon

**Comment by tuzzmaniandevil** [comment]
Icon fixed
