### ISSUE TITLE
Funnel: Add a page view event

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#1236]
Example XML
`<pageViewTrigger path="/index.html" websiteName="infiniti-landingpage"/>`

Also remove the old values from the contactFormTrigger `onSubmitted` and `onViewed`
It's always `onSubmitted` now as `pageViewTrigger` has replaced the `onViewed` option.
So now it looks like this:
`<contactFormTrigger contactFormPath="/contactus" websiteName="infiniti-landingpage"/>`

**Comment by anhnt** [comment]
:+1:
