### ISSUE TITLE
When creating a blog article, make sure the name/url only contains alphanumeric characters and dash's

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#124]
We have changed the cleanup method to remove all non alphanumeric characters except dash's. This is to prevent clashes and issues with when using MVEL templating.

**Comment by tuzzmaniandevil** [comment]
@bradmac Relies on latest Milton Cloud VFS version 1.3.7.

**Comment by Uafinder** [comment]
It looks that you can give any name to article, but it will crop any non-allowed symbols and change spaces and underscores to dashes and put this string as URL address of blog article.
