### ISSUE TITLE
KCRM: source field editing

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1240]
1. When creating a lead, the user should be able to select from the list of sources defined by the funnel, or enter a free text source.

2. The source should be editable on an existing lead, on the Details tab

**Comment by bradmac** [comment]
Also needs integration with the add new lead modal (not quicksnap). Note that the sources should be dependent on the selected funnel

**Comment by tuzzmaniandevil** [comment]
This has been done and is in the BarcelonaFC release
