### ISSUE TITLE
Contact form file uploads are not working

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#125]

**Comment by bradmac** [comment]
Supported in jquery.forms.1.0.5. But need to integrate with this for old IE support

https://github.com/francois2metz/html5-formdata

**Comment by bradmac** [comment]
Brad to test in prod

**Comment by Uafinder** [comment]
Are we talk about "contact us" form? Or where i can upload file?

**Comment by bradmac** [comment]
@tuzzmaniandevil can you create a form Vlad can test with?

**Comment by tuzzmaniandevil** [comment]
@Uafinder  http://contactuspagetest.fuseqa.com/contactus

**Comment by Uafinder** [comment]
Looks ok. File is attached ok!
