### ISSUE TITLE
KCRM: Infiniti Template

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1254]
- Top search should be black and white text and lines (no color)
- Make the analytic graph bars and circles thicker
- Make the first 4 stats i.e. leads.... slightly bolder
- Update colors as per the below image.  Only use these 4 colors throughout the whole App

![image](https://cloud.githubusercontent.com/assets/2201340/12606188/446e64cc-c506-11e5-8f9f-10f8ed410288.png)

**Comment by anhnt** [comment]
done
