### ISSUE TITLE
KCRM

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1259]
The main title should be the leads name not company.  You are dealing with a human not a company to get a sale.  

First Name & Last Name
Company Name (smaller font)
Last comment (truncated) 
Icons to click on to action something 

![image](https://cloud.githubusercontent.com/assets/2201340/12636033/5cd08fb8-c5c4-11e5-8bef-bd0ebb1427a3.png)

**Comment by paddyow** [comment]
updated:  Why are some leads showing first name and others the company name?

**Comment by tuzzmaniandevil** [comment]
If a company is present it will show the company name, otherwise it shows the profiles name.
