### ISSUE TITLE
Global Search causes a 500 error

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#126]
http://vw-test.fuseqa.com/programs/auto-vw/VW/Caddy/p1.html
I've use a global search (right upper corner) and got a 500 error on any search attempt.
![image](https://cloud.githubusercontent.com/assets/1945230/5992445/5c39ea70-aa33-11e4-953a-27e3aa496040.png)
Steps to reproduce.
1. I've login to the vw-test site via "login as" function (user:spiblin120)
2. Go to the first module page of Caddy module.
3. Enter a Caddy word to a search string and press Enter button on the keypad (button near string does nothing).
4. Got an error.

**Comment by bradmac** [comment]
We had to disable elasticsearch on QA because of security problems. So this error is expected for QA.
