### ISSUE TITLE
KCRM: Email and mobile should not be mandatory 

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1260]
Refer to profile and company tabs on a lead.

For example I may have a lead on LinkedIn that I want to chase but have no email of mobile at that  time.

Also on the company tab I only want to add a company name and not their phone or email.

**Comment by bradmac** [comment]
You can have any fields you want, or none, on a lead. But the lead is only linked to a profile if we have at least an email

**Comment by paddyow** [comment]
When I enter the company data, I have to enter an email and phone, but I don't want to. I just want to be able to enter the company name and save.

![image](https://cloud.githubusercontent.com/assets/2201340/12877422/db919e78-ce4d-11e5-8228-95a71fe90b0f.png)

**Comment by tuzzmaniandevil** [comment]
Company tab has been done https://github.com/Kademi/kademi-dev/issues/1319
