### ISSUE TITLE
KCRM: Task page

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1266]
We need an actual task page, because the email links to it. Eg http://kcrm.olhub.com/leads/119142558/119142578

Should show summary info of the lead and the task, and have the task completion modal

**Comment by bradmac** [comment]
There is a page there now, but needs layout

**Comment by tuzzmaniandevil** [comment]
@paddyow Do you have a design/wireframe for this?

**Comment by bradmac** [comment]
@tuzzmaniandevil there's no wireframe, just use your intuition :)

**Comment by tuzzmaniandevil** [comment]
Just needs to made pretty now :-)
