### ISSUE TITLE
Default ecommerce store theme enhancement 

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#1269]
Default store view should look like http://ecommerce-demo.olhub.com/shop/
Default store category: http://ecommerce-demo.olhub.com/shop/CAT-1/

**Comment by anhnt** [comment]
product detail page should be like this http://ecommerce-demo.olhub.com/shop/CAT-1/111601520/ with image zoomout tool

**Comment by bradmac** [comment]
:+1:
