### ISSUE TITLE
KCRM: ability to add lead status when creating lead

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1271]
Must be able to set the lead status when you first create a lead.  This should be mandatory as it sets the lead going in the funnel.

![image](https://cloud.githubusercontent.com/assets/2201340/12693416/4ae7d442-c744-11e5-9dff-0415199bdaa2.png)

**Comment by tuzzmaniandevil** [comment]
@paddyow  By  "Status" do you mean "Stage"?
