### ISSUE TITLE
KCRM: CSV Import/Export of leads

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1276]

**Comment by bradmac** [comment]
Introduced configurable options:
https://github.com/Kademi/kademi-dev/issues/1278

Add something like this to the funnel config after deploy
```
 <customerActivities> <action inbound="true" id="callFrom" text="Call from customer"/> <action inbound="false" id="callTo" text="Call from customer"/> <action inbound="true" id="emailFrom" text="Email from customer"/> <action inbound="false" id="emailTo" text="Email to customer"/> </customerActivities>
````

**Comment by tuzzmaniandevil** [comment]
@bradmac  What columns are needed?

**Comment by bradmac** [comment]
Same as the profile import, plus the following. Note that a funnel should be selected as part of the import process
- source
- stage
- deal amount
- cancelled
- description
- current goal
- last attained date (requires current goal)
- assigned to profile email address
- assigned to organisation ID
- assigned to group
- closed date (which will make the lead closed)
- any extra fields defined by the funnel
