### ISSUE TITLE
KCRM: Voice memo does not work

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1277]
Have tied on PC desktop windows 8
Android

When I click the button no action to record audio starts.

![image](https://cloud.githubusercontent.com/assets/2201340/12700189/4dd2fb58-c813-11e5-80b1-ef5d3baab460.png)

**Comment by tuzzmaniandevil** [comment]
If using Chrome it will only work over HTTPS.
Can you tell me what browsers you used and the version. and if using android what version of android and what browser

**Comment by paddyow** [comment]
Desktop: Chrome Version 48.0.2564.97 m
Mobile: Android 5.1.1

**Comment by tuzzmaniandevil** [comment]
This feature will help with the SSL limitation:
https://github.com/Kademi/kademi-dev/issues/1300
