### ISSUE TITLE
Leaderboard API for data series

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#128]
Developers need to be able to show leaderboards for data series. To do this they need a server side API which can give them a list of participants ranked by their sales data values.

**Comment by bradmac** [comment]
Needs to have amount associated with leaderboard rankings

**Comment by bradmac** [comment]
Add JSON gateway to get rankings via ajax

**Comment by Uafinder** [comment]
Where i can check this?

**Comment by bradmac** [comment]
This is a developer facing feature, so we can probably just close it.
