### ISSUE TITLE
KCRM: New feature for won/lost leads

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1285]
New feature to build for loss leads:
- When a deal is closed need an option to say why it was closed and make this compulsory, this could be drop down values and free text
- Need to show analytics that give managers viability of why deals are being cancelled

This could lead to gamification here, rankings on sales consultants based and wins and losses...

Wins and losses should show in the funnel

**Comment by bradmac** [comment]
Now have a histogram showing Closed leads. Need to modify it to also show Lost (ie cancelled) leads as a multichart.
