### ISSUE TITLE
Implement roles for accessing sales data series and KPI's

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#129]
We need some new roles
 - Sales data viewer: Allows a user to see data series and KPI results within the org or just website
 - Sales data editor: Allows a user to edit data series data
 - KPI editor: Allows someone to create and change KPIs

**Comment by tuzzmaniandevil** [comment]
- "Sales data viewer: Allows a user to see data series results within the org or just website" - Implemented
- "Sales data editor: Allows a user to edit data series data" - Implemented

**Comment by Uafinder** [comment]
Sales Data viewer - Shouldn't allow to pick up date and enter some data. SAve button should be hided. It should have only a read-only view.
![image](https://cloud.githubusercontent.com/assets/1945230/6175680/93ed0638-b301-11e4-9d8d-b92610a4aa8c.png)

Sales Data editor - Should have a possibility to use date pickers for Sales Period.
https://github.com/Kademi/kademi-dev/issues/162
