### ISSUE TITLE
KCRM: Improve files tab

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1291]
- improve display of type, needs to be user friendly name
- give the date uploaded
- need text associated with the file

![screenshot-kcrm olhub com 2016-02-02 15-07-06](https://cloud.githubusercontent.com/assets/826458/12737601/ce39c004-c9be-11e5-890c-e7e31377776c.png)

**Comment by tuzzmaniandevil** [comment]
- Improved type display,
- Added date uploaded

@bradmac  What do you mean by "need text associated with the file"?

**Comment by bradmac** [comment]
When i attach a file, I want to say what it is. Eg "Quote 123 - Stage 1 site development". Should be editable, and independent of the filename
