### ISSUE TITLE
KCRM: When editing a task there is no calendar picker

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1293]
![image](https://cloud.githubusercontent.com/assets/2201340/12770154/0e22d526-ca59-11e5-95f1-fe8c42379d11.png)

http://kcrm.olhub.com/leads/133715393/

**Comment by tuzzmaniandevil** [comment]
@paddyow  There is for me. Please check again, maybe try clear browser cache

![untitled-1](https://cloud.githubusercontent.com/assets/3378330/12771506/ac16636c-ca8e-11e5-886c-ffda8687169c.png)

**Comment by paddyow** [comment]
I cannot see the picker and have tried FF and Chrome.  Are you clicking on the pencil icon to open the modal?

![image](https://cloud.githubusercontent.com/assets/2201340/13108248/d4f2a204-d5ac-11e5-87ce-c3743e70658b.png)

**Comment by tuzzmaniandevil** [comment]
Fixed
