### ISSUE TITLE
KCRM: Email reminder

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1297]
Thinking we need to consolidate this email into something like this. Open to suggestions on this.

Hi Patrick,

**Whoops! It seems you're not keeping your tasks under control. **
**Well done!  You're keeping on top of your tasks.**
**You're amazing!  You have no overdue tasks.**

Tasks due today: 7
Total tasks overdue: 25
Tasks complete: 45%

Here are your top 5 tasks:
1.
2
3.
4.
5.

Click here to see the full list of tasks due.

**Comment by paddyow** [comment]
FYi I got this today:

Tasks due forPatrick Hone
null - due 24349 months ago
Followup - due 27 days ago
Need to followup - due 21 days ago
Followup - due 18 days ago
null - due 6 days ago
null - due 4 days ago
null - due a day ago

**Comment by tuzzmaniandevil** [comment]
The email is now templated: `/theme/apps/leadman/leadManReminder.html`

**Comment by bradmac** [comment]
- should only display one of the summary messages, not all three
- i received the email saying i had 3 over due tasks, but did not list any

**Comment by tuzzmaniandevil** [comment]
Done
