### ISSUE TITLE
Inventory Management

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#1303]
Add an inventory management system to manage products in store.
I should support multiple locations (or warehouses) where a store can select what location to get products from.

Basic admin workflow:
- Create a location
- Add products to location, specify available amount
- Select location in store

Should have an overview of in stock, available and reserved quantity.

Basic website flow:
- On products page, show how many items of the product is available in each location
- On checkout verify stock is available, Maybe location can have an option whether to allow orders if no stock is available
- the product then get's "reserved"
- Once the shopping cart has been marked as fulfilled deduct the product quantity from the location.

SKU's
- each available variant will be linked to a SKU item. For example, a product with a size option of S, M, L and a colour option of black and white would have up to 6 SKU's. 
- Only combinations with a SKU would be available for purchase. For example if there is no SKU item for L + Black, then that would not be available for selection
- Each SKU item will have a stock level in each configured location. A ecommerce or reward store will be configure with a location to check inventory for.
- The add to cart feature will show the stock level for the store location
- Optionally, the add to cart feature will show stock levels in other locations (eg physical shops)

**Comment by tuzzmaniandevil** [comment]
This should be part of the Products app

**Comment by bradmac** [comment]
ProductSku - identifies a particular product and combination of options (optional) identified by a SKU
InventoryLocation - a location where products are kept
ProductInLocation - links a ProductSku to an InventoryLocation, with a quantity
