### ISSUE TITLE
KCRM - Add description to lead stage

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1308]
Add a description field to each lead stage i.e. 

Code = Warm
Description = Warm - Deal in progress

In the dropdown show the description field and not the code so at anytime the description can be changed without having to reassign each code again to each lead.

![image](https://cloud.githubusercontent.com/assets/2201340/12878477/6d275f0a-ce60-11e5-82df-6dd4353fe427.png)

**Comment by tuzzmaniandevil** [comment]
The XML for stage will need to change to support this:
From:
`<stage>cold</stage>`
To
```
<stage>
  <name>hot</name> <!-- Required -->
  <desc>This will be the description</desc> <!-- Optional -->
</stage>
```
