### ISSUE TITLE
Custom fields for data series

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#131]
Allow fields to be defined on a data series in the same way as for groups.

The data series CSV file should provide read/write access to custom fields

**Comment by Uafinder** [comment]
Looks ok to me, and looks like it already deployed on prod, am i right?

Is there should be a validation on "required" parameter when you are uploading sales data via CSV. i'm mean, when our field is required, should we insert data which are not contains it?

**Comment by bradmac** [comment]
No, the required attribute is just for use in templates when generating forms automatically, which we're not currently doing

**Comment by Uafinder** [comment]
If so - works ok.
