### ISSUE TITLE
KCRM: Make quick snap photo look nice

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1321]
Current the upload photo control is an unstyled browse button, even on android. 

Also, need to give upload progress indication.

Probably use this: 
https://commons.wikimedia.org/wiki/File:Mobile-Smartphone-icon.png

**Comment by tuzzmaniandevil** [comment]
![1](https://cloud.githubusercontent.com/assets/3378330/13063189/52bf4b0a-d4aa-11e5-988e-9d677dcfd314.PNG)

![2](https://cloud.githubusercontent.com/assets/3378330/13063190/56d9c2f6-d4aa-11e5-924d-1c86d60bb94b.PNG)
