### ISSUE TITLE
Show administrator toolbar in frontend site when logged-in user is administrator

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#1327]
Hi @bradmac,
Sometime when I'm working on a frontend site which is powered by Kademi but I don't know the admin url of frontend site. Can we do something like administrator toolbar like Wordpress for some quick actions and also link to admin console?

**Comment by anhnt** [comment]
:+1:

**Comment by bradmac** [comment]
I think it would be nice to have an app which adds a management toolbar, but only for logged in users with contenteditor role. Then the management toolbar could allow inline page editing, etc.

**Comment by ducdhm** [comment]
Okay cools! Let me do it

**Comment by anhnt** [comment]
Implemented for bs335. This will look like following:
![toolbar](https://cloud.githubusercontent.com/assets/735555/14173699/bbd2c586-f769-11e5-9357-7774b6ff5fd2.PNG)

**Comment by bradmac** [comment]
@anhnt can you also add the ability to do inline content editing?

If there is a div with the htmleditor class, then have an Edit button in the toolbar which will initialise keditor on the content of that div

Note the page.html template is like this:
```
                <h1>$page.title</h1>
                <div class="contentForm">
                    <div class="htmleditor" id="body">
                        $!{page.body}
                    </div>
                    <br class="Clear" />
                </div>
```

**Comment by bradmac** [comment]
Not sure if this is done already..?

**Comment by anhnt** [comment]
Hey duc could you please help me adding the kedior?

**Comment by ducdhm** [comment]
@anhnt Done. Please continue :)

**Comment by anhnt** [comment]
@ducdhm thanks mate
