### ISSUE TITLE
Cannot rename scheduled task

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#133]
Cannot update the 'name' in the Send Information of a scheduled task.  After I click send, the name does not update.

**Comment by tuzzmaniandevil** [comment]
"Cannot update the 'name' in the Send Information of a scheduled task. After I click send, the name does not update." - Fixed

**Comment by Uafinder** [comment]
Yeah, it renames a task, but:
1. Should it change a link to it?
2. It should also changes name in Scheduled tasks table:
![image](https://cloud.githubusercontent.com/assets/1945230/6029046/89eef234-abf6-11e4-9461-f96945a8c8af.png)
![image](https://cloud.githubusercontent.com/assets/1945230/6029056/9af59e48-abf6-11e4-9119-e7068cddb3be.png)

**Comment by tuzzmaniandevil** [comment]
It was incorrectly named, Changed from "Name" to "Title". There is no need to change the URL. Should al be fixed now.

**Comment by Uafinder** [comment]
Works ok!
