### ISSUE TITLE
Error when deleting in Manage Contact Requests screen

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#1333]
Reported by Claudette from OY

**Comment by bradmac** [comment]
Problem is that when deleting the CR is deleted from the DB, but not the search index. So it still gets displayed on the manage CRs page. But if you try to delete again you get an error, because it has already been deleted

**Comment by bradmac** [comment]
So the problem is that CR is not being removed from the index when deleted

**Comment by bradmac** [comment]
Problem was the missing parent id for routing to the profile shard. Fixed
