### ISSUE TITLE
EDM Editor: CKeditor popup blocks text

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#1335]
![edm1](https://cloud.githubusercontent.com/assets/3378330/13102306/d1fc05ea-d5b1-11e5-8e38-3a9f2d4d3957.png)

**Comment by ducdhm** [comment]
Fixed layout of CKEditor and adjusted style.
![fixed](https://cloud.githubusercontent.com/assets/1289631/13138242/8e4773d2-d658-11e5-94fd-
357120b24856.png)
