### ISSUE TITLE
KCRM: Unable to add a lead

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1338]
When clicking submit and close or create and view, nothing happens.

![image](https://cloud.githubusercontent.com/assets/2201340/13108439/de7ff21c-d5ad-11e5-9a5d-c3f53ee21efd.png)

**Comment by tuzzmaniandevil** [comment]
I just tested it, Seems to work fine. Are you able to clear your browser cache and test again?

**Comment by paddyow** [comment]
Cleared cache and no joy.  Have added the values i entered below:

![image](https://cloud.githubusercontent.com/assets/2201340/13143819/79f76c88-d681-11e5-8783-3c9b7354bc16.png)

**Comment by bradmac** [comment]
The problem is just when using test@kademi.co, because there are a million profiles in the db with that email address. Just use a new one and works fine :)
