### ISSUE TITLE
Add Square,Vertical and horizontal image tags to Auctions.

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#134]
Add the ability to upload an image as either square, vertical, horizontal or freehand and tag then accordingly and allow the template engine to get the best format picture according to the tags with the following properties:
- getImages - Returns a list of all images
- getImages(preferredOrientation) - returns a list of images matching that orientaion
- bestDefaultImageHref		
- bestSquareImageHref	
- bestVerticalImageHref	
- bestHorizontalImageHref

**Comment by tuzzmaniandevil** [comment]
viewAuctions uses a square image by default, if no square image is found it will use the first image it can find. So for it to look good upload a square image :-)

**Comment by Uafinder** [comment]
When uploading images to auction we have a problem now:
1. When image not cropping
![image](https://cloud.githubusercontent.com/assets/1945230/6050592/a2e52442-acc9-11e4-975e-5302fed6135c.png)

**Comment by tuzzmaniandevil** [comment]
"1. When image not cropping" - Fixed

**Comment by Uafinder** [comment]
"1. When image not cropping" - Fixed ---- YES

There is a possibility to ignore a orientation parameter. When you are beginning to upload an image and will change orientation parameter before it will completely load, selection would remain free-hand. I'm not sure how serious it is and if we can ignore it - just close an issue.

**Comment by tuzzmaniandevil** [comment]
"There is a possibility to ignore a orientation parameter. When you are beginning to upload an image and will change orientation parameter before it will completely load, selection would remain free-hand. I'm not sure how serious it is and if we can ignore it - just close an issue." - yup that's not a problem.
