### ISSUE TITLE
KCRM: Data table license popup

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1341]
![image](https://cloud.githubusercontent.com/assets/2201340/13143573/cb1a8ba6-d67f-11e5-868d-9fe0c7b984a8.png)

**Comment by paddyow** [comment]
Guessing data is not loading on this page http://kcrm.olhub.com/leads/ due to the license expiring.

**Comment by tuzzmaniandevil** [comment]
a licence needs to be purchased.

**Comment by bradmac** [comment]
bought license, can you install it please

**Comment by tuzzmaniandevil** [comment]
Done
