### ISSUE TITLE
KCRM: Tooltip prevents left click

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1342]
When you hover over a smaller circle, the tooltip prevents you from clicking on the circle to update the LHS table.

![image](https://cloud.githubusercontent.com/assets/2201340/13143609/05186af8-d680-11e5-923a-835d005c4eeb.png)

**Comment by tuzzmaniandevil** [comment]
This is an issue with the JQuery plugin used. Issue here: https://github.com/Kademi/kademi-funnel-vis/issues/19

**Comment by tuzzmaniandevil** [comment]
Issue fixed, Kademi updated to the latest version of the plugin.
