### ISSUE TITLE
Have JsonDocumentResource implement Map

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#1352]
This will allow easier access from JavaScript will autosaving and easy accessing.
for example.
`jsonResource.test = "This is a test";`
Results in:
`{"test": "This is a test"}`

Also allows the ResourceList to sort Json documents.

**Comment by bradmac** [comment]
@tuzzmaniandevil you need to do something about the autosaving feature. Each update writes to the database, and the index, in a transaction. You definiteily do not want that on every property being set!!

**Comment by tuzzmaniandevil** [comment]
I added a method called saveChanges() that the user needs to call to commit the changes instead of it saving on each update.

**Comment by bradmac** [comment]
how about making it just "save" instead of "saveChanges"?

**Comment by tuzzmaniandevil** [comment]
Done
