### ISSUE TITLE
KCRM: Tidy up task panel

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1354]
From this: 
![image](https://cloud.githubusercontent.com/assets/2201340/13216085/aaab7372-d994-11e5-8265-c2a06ad9c58e.png)

To this:
![image](https://cloud.githubusercontent.com/assets/2201340/13216089/b053b53c-d994-11e5-970b-faeafd07f197.png)

**Comment by anhnt** [comment]
done

**Comment by bradmac** [comment]
@anhnt and please do for stock templates
