### ISSUE TITLE
KCRM:  Hook up website to KCRM

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1355]
All contact forms and Get Kademi: http://www.kademi.co/get-kademi.html

..should create a profile in KCRM and a task to contact the person the same day.

**Comment by bradmac** [comment]
@mamun4343 let me know when you're ready and I'll walk you through it

**Comment by bradmac** [comment]
Eg
```
 <triggers>
   <contactFormTrigger contactFormPath="/get-kademi.html" websiteName="kademi-www"/> 
</triggers>
```

**Comment by mamun4343** [comment]
@bradmac  : all forms hooked up. need your hand for contact person or assignedTo.

**Comment by bradmac** [comment]
OK, just ping me when you're ready
