### ISSUE TITLE
Upgrade phone field validation

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1361]
Create a new version of the forms plugin which adds upgraded phone number field validation.

This should apply to any fields with name, ID or class "phone"

This should use validation from this lib - https://github.com/googlei18n/libphonenumber

There may be a default country code specified in form plugin configuration.

The phone field should be tolerant of different but acceptable formats, eg 123-555, 123 555, 123555, etc. Ideally it should sanitise the field to put it into a standard format including the country code.

**Comment by ducdhm** [comment]
Now you can validate phone input via `class` or `id` is `phone`. You also can use parser method directly:
```javascript
/**
 * @param {String} val Value will be parsed
 * @param {String} phoneRegionCode Default region code (ISO 3166-1 two-letter country code)
 * @param {String} phoneCarrierCode Carrier Code (optional, only valid for some countries)
 * @return {Object}
 */
phoneNumberParser(val, config.phoneRegionCode, config.phoneCarrierCode);
```

Example:
```javascript
var result = phoneNumberParser('0906190121, 'VN', '');

// Result is
/**
 *  {
 *      e164Format: "+841668168889",
 *      error: false,
 *      internationalFormat: "+84 166 816 8889",
 *      isNumberValid: true,
 *      isPossibleNumber: true,
 *      nationalFormat: "0166 816 8889",
 *      numberType: "MOBILE",
 *      originalFormat: "0166 816 8889",
 *      parsingResult: {
 *          country_code: 84,
 *          country_code_source: 20,
 *          national_number: 1668168889,
 *          preferred_domestic_carrier_code: "",
 *          raw_input: "0166 816 8889a"
 *      },
 *      regionCodeForNumber: "VN"
 *  }
 */
```
