### ISSUE TITLE
Missing switches on website App management page

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1372]
Is this the morn now ?

http://astrazeneca.admin.olhub.com/websites/az-patient-support/version1/#panel_apps-tab

![image](https://cloud.githubusercontent.com/assets/2201340/13287137/6f7ef1ea-db40-11e5-9f79-3d966f7575be.png)

**Comment by bradmac** [comment]
Those are core apps, so we've removed the ability to disable them
