### ISSUE TITLE
Need option to download unsubscribes

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#138]
Users need to download unsubs in one list across all groups i.e. from user management.

Users also need to download at a group level i.e. users setup groups to capture lists into, they will then want to download unsubs at this group level whether this is done via groups or manage users.

**Comment by tuzzmaniandevil** [comment]
Implemented ability to download a csv of all unsubcribed users from the manage users page.

**Comment by tuzzmaniandevil** [comment]
"Users also need to download at a group level i.e. users setup groups to capture lists into, they will then want to download unsubs at this group level whether this is done via groups or manage users." - Moving to seperate issue https://github.com/Kademi/kademi-dev/issues/152

**Comment by Uafinder** [comment]
Users need to download unsubs in one list across all groups i.e. from user management.
Done... Works ok!
