### ISSUE TITLE
RB has stange error when tried to search something

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1390]
![image](https://cloud.githubusercontent.com/assets/1945230/13406430/145981fa-df2c-11e5-9e03-054216dbac17.png)
I tried to search "Nurofen".

**Comment by bradmac** [comment]
what browser version is that? Just checked in FF and seems ok

**Comment by Uafinder** [comment]
IE

**Comment by Uafinder** [comment]
Looks just a cache issue... Killed cache and close open browser helps
