### ISSUE TITLE
Errors in firebug console when change page in admin

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1391]
![image](https://cloud.githubusercontent.com/assets/1945230/13406510/92d6e130-df2c-11e5-8c61-b59c9dc91294.png)
When you open any page by clicking it's link, there appears two errors on zopim and kchat. What it could be?

**Comment by bradmac** [comment]
@tuzzmaniandevil can you have a quick look? might be nothing

**Comment by tuzzmaniandevil** [comment]
That just because the websocket isn't being closed. It can be ignored.
