### ISSUE TITLE
KCRM: Add loss reasons to drop down

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1396]
![image](https://cloud.githubusercontent.com/assets/2201340/13419309/e88a63b4-dfb7-11e5-8e5c-f9e3bdebf888.png)

Currently there are no values.  Please add:

Went with another vendor
Project was cancelled
Too expensive 
Kademi was too slow to act

**Comment by mamun4343** [comment]
done! plz check.
