### ISSUE TITLE
Waterco quiz issue

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1398]
Not sure, it could be a core issue
When you have a quiz you could add a lot of questions and check a batch size to select some number of them for random appearance.
Well, if module contains this "batch" option and you have select quiz answers and press submit, it will show you another batch of quiz questions without any warning or message. It will be passed after you push submit for such time which are selected in maximum attempt option.
![image](https://cloud.githubusercontent.com/assets/1945230/13441358/4d3dadce-dfff-11e5-983b-66533d61d0c3.png)

It also sent emails about "having problem" with the quiz. Possible one the Andy's probs.
![image](https://cloud.githubusercontent.com/assets/1945230/13441600/c032a612-e000-11e5-879d-654fa23352a8.png)

**Comment by bradmac** [comment]
Have you tested that the max attempts thing is working correctly?

**Comment by Uafinder** [comment]
yes, it gives you a possibility to click submit only specified times

**Comment by bradmac** [comment]
And is the user correctly informed when they reach the max attempts?

**Comment by Uafinder** [comment]
Nono...
1. Accessing quiz page
2. Seeing 10 questions (batch size)
3. Select any answers
4. Click submit
5. It gives you another batch of 10 questions without any warnings or messages, selected answers are deleted
6. You selected them as well.
7. Click submit
8. It gives you another batch of questions again.
9. You select them as well again (no matter of correct answer or not)
10. Click submit
11. Quiz is passed due the max attempts limit.

**Comment by bradmac** [comment]
related to https://github.com/Kademi/kademi-dev/issues/1656

**Comment by ducdhm** [comment]
New UI
 * When quiz is error
![quiz_error](https://cloud.githubusercontent.com/assets/1289631/15476085/70185bd6-2137-11e6-9f7d-ff9c256b7172.png)

 * When reached maximum attempts
![max_attempts](https://cloud.githubusercontent.com/assets/1289631/15476101/7a8b2abc-2137-11e6-9c1b-8d14ee405595.png)

**Comment by ducdhm** [comment]
New UI
* When quiz is error 
![quiz_error](https://cloud.githubusercontent.com/assets/1289631/15476532/b19451e4-2139-11e6-8f52-e7e2c22ea40c.png)

* When reached maximum attempts
![max_attempts](https://cloud.githubusercontent.com/assets/1289631/15476539/bc15bb76-2139-11e6-9f33-f7746cb20a86.png)

**Comment by Uafinder** [comment]
- See error answers doesn't work
![image](https://cloud.githubusercontent.com/assets/1945230/15683580/cca4d9f8-276b-11e6-9029-18e6151adca8.png)

- when you failed for the all times you give a "reached maximum attempts" message and then give next message:
![image](https://cloud.githubusercontent.com/assets/1945230/15683657/1cd9b1a0-276c-11e6-9308-b03da6ba8823.png)

**Comment by ducdhm** [comment]
@Uafinder Please kindly test it again!

**Comment by mamun4343** [comment]
@Uafinder  Please also check the same for version4-bs335 for waterco .
