### ISSUE TITLE
Waterco hdx5.7 ending issue

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1399]
![image](https://cloud.githubusercontent.com/assets/1945230/13441909/611daefe-e002-11e5-904e-a38b0b09b7cf.png)
When you go from:
http://training.swimart.com.au/programs/HDX15/HDX5/HDX5.7/pcontroller-tuning.html
by clicking "submit" it gives an error.

**Comment by Uafinder** [comment]
Will try to give more info a bit later

**Comment by bradmac** [comment]
Great! Is that reproducible everytime?

**Comment by ducdhm** [comment]
@Uafinder Please kindly double-check again.

FYI: reason is cause js stuff of `swimart.js` file

**Comment by Uafinder** [comment]
Great! It works!
