### ISSUE TITLE
KCRM: Contacts importer part 2

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1403]
Extension to https://github.com/Kademi/kademi-dev/issues/1401

- make import task cancellable
- check validation for progression of wizard steps, ie make sure cant skip past anything
- show a summary of actions to be performed, before doing anything. Ie show number of contacts to add and update. Do this by doing a "dry-run" where the process is executed but no changes are made, the backend will just work out whether it would insert or update.
- show summary statistics on completed tab
- field names in column selector to be user friendly. Add displayName to DestField class

**Comment by anhnt** [comment]
check validation for progression of wizard steps, ie make sure cant skip past anything **done**
field names in column selector to be user friendly. Add displayName to DestField class **done**

**Comment by anhnt** [comment]
:+1: the fix works. Thanks @tuzzmaniandevil
