### ISSUE TITLE
Insert link doesnt work in modules for ckeditor

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1404]
1. Go to the manage module page
2. Go to the completion message
3. Click the link button
4. Click "browse server", a file browsing popup appears
5. Click into websites, and try to get to the module
6. An error appears

There is a specific resource which generates XML content intended for ckeditor. For some reason that is not working for some resources

Let me know if you need a hand :)

**Comment by ducdhm** [comment]
As discussed with Brad, we'll implement new plugin for browsing, uploading and selecting file by using jquery.mselect

**Comment by ducdhm** [comment]
@bradmac For some reason, it's working. Can you double-check again?

**Comment by ducdhm** [comment]
@bradmac The XML which `/fck_connector.html` returns, are not well-formed.
```
<?xml version="1.0" encoding="utf-8" ?>
<Connector command="GetFoldersAndFiles" resourceType="Image">
    <CurrentFolder path="/websites/elearning
/" url="/websites/elearning/" />
    <Folders>
        <Folder name="version1" />
        <Folder name="live-videos" />
    </Folders>
    <Files>
        <File name="Live-is-version1" size="" 
    </Files>
</Connector>
```

Lack of closed tag in `<File>` tag

**Comment by bradmac** [comment]
I think we really need to replace this link dialog. Its horrible looking, and it allows linking to resources on invalid paths. Eg selecting a blog from admin will result in an admin path that wont work in the front end.

Instead we should
- implement a new dialog based on our standard file selector used for images etc
- also, open the module complete editor in contenteditor in the front end, so resources are selected with the front end website path

**Comment by ducdhm** [comment]
@bradmac We'll implement new plugin for link because we can not override dialog without customizing CKEditor Link plugin

**Comment by bradmac** [comment]
:+1:

**Comment by anhnt** [comment]
Modified jquery.mselect to have an option `mselectAll: true` to show all files types.
![image](https://cloud.githubusercontent.com/assets/735555/17361156/2a5be2e4-5999-11e6-87c2-0af6adbba97a.png)
