### ISSUE TITLE
Dashboard messages fail to dissapear

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#141]
User cann dismiss alert, keeps appearing.  Even when the alert is configure to allow the user to dismiss the alert.

http://www.kenwoodresourcecentre.com.au/dashboard

**Comment by paddyow** [comment]
This needs to be actioned soon as the Kenwood website is going live in a few days.  When can this be deployed to prod?

**Comment by bradmac** [comment]
The acknowledge the dashboard alerts require a piece of javascript. This is inserted by the app into the dashboardBottom portlet.

However, it looks like the Kenwood customised dashboard is missing that portlet, so the script doesnt get inserted.

To fix we need the developer to insert the portlet declaration:

#portlets("dashboardBottom")
