### ISSUE TITLE
KCRM: CSV causing issues

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1410]
Went through CSV workflow to upload data, clicked the complete button
User did not get uploaded
Went back to the upload page and got the below dialogue each time

![image](https://cloud.githubusercontent.com/assets/2201340/13486513/b4cf3036-e14c-11e5-9706-e57850a0164f.png)

When I click Import button again, the upload section says Please wait, so cannot select a file anymore

![image](https://cloud.githubusercontent.com/assets/2201340/13486480/80e2479a-e14c-11e5-85ca-1eb1047c6e00.png)

**Comment by bradmac** [comment]
I think this has been resolved now
