### ISSUE TITLE
Manually expire points in a points bucket

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1411]

**Comment by bradmac** [comment]
Expiration and deleting needs to be sensitive to the selected date range.

Also change button labels to match

**Comment by tuzzmaniandevil** [comment]
Should also take into account the search query, So should expire points that are shown on the page

**Comment by AlaaKhalaf94** [comment]
The Expiration is passed , but there is no selected date range.

**Comment by bradmac** [comment]
hi @AlaaKhalaf94, a couple of things
- the points expiration date for a points record is set when the points are created. Setting an expiry date on the bucket does not affect points already issued
- also note that the points expiry process only runs occasionally, i think hourly.

**Comment by AlaaKhalaf94** [comment]
@gonzalon 
Here I've deleted all points to this user then I've added 3000 point to him
http://alaa-test.admin.kademi-prod.com/manageUsers/148682/#pointsBucketTab-tab

After that , I've go there and expire those 3000 points
http://alaa-test.admin.kademi-prod.com/points-buckets/alaastore/?startDate=24%2F07%2F2016&finishDate=24%2F07%2F2017&dataQuery=&startPos=0#points-tab

But in points tab in user profile , these 3000 points is still Available
![capture1](https://user-images.githubusercontent.com/26510030/28512001-9d40f444-7058-11e7-95cb-589784af843b.PNG)

**Comment by bradmac** [comment]
@gonzalon note that when expiring records we dont just mark the record as expired, you also need to create a debit to subtract that number of points.

**Comment by AlaaKhalaf94** [comment]
passed
