### ISSUE TITLE
IE11: Task issues

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1422]
![image](https://cloud.githubusercontent.com/assets/1945230/13507161/1e16fed8-e18a-11e5-93eb-397eaeff07c0.png)

can't cancel task
date created should be a human readable
can't cancel task via button on the leads page
![image](https://cloud.githubusercontent.com/assets/1945230/13507209/5a90a4b8-e18a-11e5-9955-87eb37f47b6e.png)

**Comment by anhnt** [comment]
> can't cancel task
This occurs in all browsers. Trying to fix

> date created should be a human readable
> can't cancel task via button on the leads page
Works for me

**Comment by anhnt** [comment]
As discussed with @bradmac, Delete task button in edit task modal now transforms to Cancel task

**Comment by Uafinder** [comment]
Cancelling works ok
