### ISSUE TITLE
Task calendar pickup bugs

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1423]
![image](https://cloud.githubusercontent.com/assets/1945230/13507437/34b92d18-e18b-11e5-80da-5768e586255c.png)
- Left right arrows doesn't work
- Home button should be pressed twice to select current date/time - that's not obvious
- when calendar opens - it should be in initial state, initial state should be either due date which is saved at the moment or the currect date/time

**Comment by bradmac** [comment]
@anhnt consider using the fuelux date control, if thats better
http://getfuelux.com/javascript.html#datepicker

**Comment by anhnt** [comment]
fuelux datepicker doesnt support timepicker which current dapicker does. will try to fix those bugs

**Comment by bradmac** [comment]
Actually for this use case the time is not required, just the date.

But its ok to use either control, as long as it works!

**Comment by anhnt** [comment]
Should work properly now

**Comment by Uafinder** [comment]
Looks ok
