### ISSUE TITLE
Strange file upload date

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1427]
![image](https://cloud.githubusercontent.com/assets/1945230/13507989/daf799b0-e18d-11e5-801f-b5b3201f7ba7.png)
I've upload it on 3/3/2016

**Comment by anhnt** [comment]
worked just fine for me. could you reproduce this again @Uafinder

**Comment by Uafinder** [comment]
Your welcome :)
![image](https://cloud.githubusercontent.com/assets/1945230/13683561/06827974-e710-11e5-8abc-4a57fe4fa153.png)

**Comment by bradmac** [comment]
@tuzzmaniandevil better have a look at this today, thanks

**Comment by tuzzmaniandevil** [comment]
The timezone of the org wasn't being included when formatting the ISO8601. I've added this now. 
I checked the date being used when a file is uploaded and that is correct.
