### ISSUE TITLE
System creates an empty task when you change creation date

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1428]
![image](https://cloud.githubusercontent.com/assets/1945230/13508309/1abe9d40-e18f-11e5-8eb0-81595406e326.png)
Looks like if you have a task and you will change a date which will not compatible with it system will creates an empty completed task.
I saw it twice, but have no luck to reproduce it further.

**Comment by bradmac** [comment]
i think this was done on another issue
