### ISSUE TITLE
Upload CSV KPI levels doesn't work

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#143]
When you are importing CSV file with KPI levels it writes that no errors, some strings are matched, some are inserted but no data is updated and inserted at all.
![image](https://cloud.githubusercontent.com/assets/1945230/6049616/ceb3c054-acc1-11e4-945d-45509c171315.png)
![image](https://cloud.githubusercontent.com/assets/1945230/6049622/d64af8dc-acc1-11e4-9aaa-e1fcf4ef8b5a.png)
![image](https://cloud.githubusercontent.com/assets/1945230/6049625/dec0226c-acc1-11e4-83bb-af553153b1b8.png)

**Comment by tuzzmaniandevil** [comment]
Fixed

**Comment by Uafinder** [comment]
It works now.
When CSV file contains a string like on the screen (fourth) data is not uploading to system from CSV. All strings with an existing Level ID field are just ignoring.
![image](https://cloud.githubusercontent.com/assets/1945230/6154974/5c5b3560-b238-11e4-8bdf-88afa43779ee.png)

**Comment by tuzzmaniandevil** [comment]
Fixed
