### ISSUE TITLE
Incorrect message when you clean assignment

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1430]
![image](https://cloud.githubusercontent.com/assets/1945230/13508498/eb120dec-e18f-11e5-890f-03d6eed35873.png)

**Comment by anhnt** [comment]
Changed message to 

> The assignment has been changed!

**Comment by bradmac** [comment]
I think we should lose the exclamation mark. Our customers are not as excited about this as we are!

**Comment by anhnt** [comment]
Removed that exclamation mark

**Comment by Uafinder** [comment]
Great
