### ISSUE TITLE
Assignment suggestion

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1431]
![image](https://cloud.githubusercontent.com/assets/1945230/13508583/52a4c9c2-e190-11e5-8b4b-9bdcccbd8e63.png)
When you assign a lead there shouldn't appears UserID, but user nickname or name surname i think, email is also possible

**Comment by anhnt** [comment]
now using firstname and surname

**Comment by Uafinder** [comment]
Yup!
