### ISSUE TITLE
IE11 add new leads and new contacts doesn't work at all

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1433]
Pop-up doesn't open
![image](https://cloud.githubusercontent.com/assets/1945230/13508858/71831406-e191-11e5-8289-5ae8ea9b3355.png)

**Comment by bradmac** [comment]
@anhnt please make sure fixes are applied in kademi core code, not in customisations for infitini

**Comment by anhnt** [comment]
Just moved createModal to masterTemplate.html to allow working in all pages

**Comment by Uafinder** [comment]
Mostly ok, if spot something - will create separate issue.
