### ISSUE TITLE
emailto without sending email

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1435]
![image](https://cloud.githubusercontent.com/assets/1945230/13509933/d78d6e90-e196-11e5-8ec3-a2c1ba822cf4.png)
When lead was successfully closed there appears info about email to the customer, however there no email was send and received by his email address and no info about it in the admin console
![image](https://cloud.githubusercontent.com/assets/1945230/13509979/175eed96-e197-11e5-8eff-731af625cf90.png)

**Comment by tuzzmaniandevil** [comment]
That is generated by the LeadNote class, not an email
