### ISSUE TITLE
Blog/News Feed Reporting 

### ISSUE THREAD

**Issue by Keegan01** [Kademi/kademi-dev#1436]
MyStarRewards needs an option for all commentary to be exported to a CSV.
The fields that need to be exported are:
-The Author ( ie. email address of user)
-Organisation ( Dealership)
-Time 
-Name of Article 
-Content(Commentary)
-Votes

all of which can be found on this page http://admin.mercedes.olhub.com/managePosts

**Comment by bradmac** [comment]
:+1:

**Comment by Keegan01** [comment]
Hey @bradmac do we have much progress on this? Thanks
