### ISSUE TITLE
Delay validity check for ModuleProgressEventTriggerType

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1437]
Possibly not working for completed modules. NPE on the moduleID

See TheFeed

**Comment by bradmac** [comment]
@tuzzmaniandevil can you please investigate this after KCRM issues? Need to check if the delayed validitity check works for completed modules. This was causing an NPE for TheFeed

**Comment by tuzzmaniandevil** [comment]
I found a couple of possible issues that would stop it from working.

**Comment by tuzzmaniandevil** [comment]
I've tested it locally with no problems now.
