### ISSUE TITLE
Copying courses from one version to another doesn't work correctly

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#1438]
When trying to copy a course from one version to another and there is already a course in the new version, when pasting the course it puts the course under the current course instead of next to it

**Comment by bradmac** [comment]
I think we can
1. do an ajax call to check if a resource exists with the same name
2. if so prompt the user for a name to use, then back to step 1
3. Copy it

**Comment by anhnt** [comment]
also fixed the same issue when copying module
