### ISSUE TITLE
KPI saving are change start date

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#144]
Steps to reproduce:
1. Create a KPI
2. Edit it, enter some data and enter today's date.
3. Push save.
4. Go back to edit this KPI and you will see that date will change to (today-1 day).
5. Change some other attribute.
6. Push save
7. Go back to edit this KPI and you will see that date changes to another day to the past.

**Comment by tuzzmaniandevil** [comment]
Should be fixed

**Comment by Uafinder** [comment]
Nope. Still active

**Comment by tuzzmaniandevil** [comment]
Possibly Fixed.

**Comment by Uafinder** [comment]
Yup. Fixed
