### ISSUE TITLE
KCRM: Exception thrown when profile exists 

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1445]
When creating a lead, if a profile exists the lead should be assigned to the existing profile and not throw and exception.

![image](https://cloud.githubusercontent.com/assets/2201340/13622076/1ecc1920-e5d7-11e5-8166-d9d093f211b7.png)

**Comment by bradmac** [comment]
:+1: 
Note that this occurs even after selecting the existing profile from the dropdown list.

**Comment by tuzzmaniandevil** [comment]
Small glitch, was looking for profile in one org and creating it in another.
