### ISSUE TITLE
KCRM: Update mobile breakpoint

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1448]
For mobile breakpoints only, hide the avatar icon and ensure the lead content spans the full width of the panel.

And hide the stats panel on mobile.

![image](https://cloud.githubusercontent.com/assets/2201340/13627336/acaa854c-e604-11e5-935b-501ea5cf13f3.png)

**Comment by anhnt** [comment]
needs to deploy before testing
