### ISSUE TITLE
KCRM:  Contact request not capturing into KCRM

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1451]
When a lead submits a contact form on the Kademi website, we need to capture the contact request into the KCRM profile timeline.  This will then allow the admin user to click on the contact request and see the message.

![image](https://cloud.githubusercontent.com/assets/2201340/13628517/abf5bde8-e60d-11e5-9b09-dc2003732310.png)

**Comment by bradmac** [comment]
The contact request should appear on the timeline.

**Comment by tuzzmaniandevil** [comment]
The reason it wasn't showing is that the Contact Us app was turned off
