### ISSUE TITLE
Table cellpadding/cellspacing not working in html editor. 

### ISSUE THREAD

**Issue by mamun4343** [Kademi/kademi-dev#1452]
some client dont know css. so, All they want is the black  marked area will work well.

see image below..
![untitled](https://cloud.githubusercontent.com/assets/3419573/13628742/defd86bc-e5fe-11e5-8b48-8e64074cf6b1.png)

**Comment by bradmac** [comment]
:+1: the editor should work correctly

**Comment by anhnt** [comment]
Should check if table has cellpadding or cellspacing prop, then do a css workaround
