### ISSUE TITLE
Infiniti: Editing task issues

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1457]
When tried to edit task there is strange thing:
Date quickly changing to that which should be (which was setup before) and message appears that "date is saved". What is this and for what?
![image](https://cloud.githubusercontent.com/assets/1945230/13684328/e5e34f0a-e713-11e5-8208-ebbc9b591fa8.png)

**Comment by bradmac** [comment]
Not sure what you mean. Can you clarify the issue?

**Comment by anhnt** [comment]
got the issue. That means right after open modal. date is saved and throws a alert. will fix that
