### ISSUE TITLE
Infiniti: Minor visual issue while importing CSV contacts

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1459]
![image](https://cloud.githubusercontent.com/assets/1945230/13684599/2aac60ee-e715-11e5-9571-d763cf6d36bb.png)

**Comment by anhnt** [comment]
fixed

**Comment by Uafinder** [comment]
It's back! Wasn't there yesturday
![image](https://cloud.githubusercontent.com/assets/1945230/13930971/e05fec66-efa9-11e5-8c44-95806537e752.png)

**Comment by bradmac** [comment]
probably because of rolled back release

**Comment by anhnt** [comment]
its fuelux wizard bug and only occurs on IE. Just did a workaround for IE11

**Comment by Uafinder** [comment]
Looks ok!
