### ISSUE TITLE
Infiniti/KCRM: Importing CSV contacts

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1460]
There should be validation on file selecting. If there is no file selected it should not allow you to proceed. Now, it gives you a warning message, but gives possibility to pass it.

**Comment by anhnt** [comment]
add validation for steps

**Comment by Uafinder** [comment]
https://github.com/Kademi/kademi-dev/issues/1462
also when open import it's already on the second position

**Comment by anhnt** [comment]
it should work when new deployment gets done

**Comment by Uafinder** [comment]
When you went to the step 5 - complete button, it does nothing. Contact will not be imported.

**Comment by anhnt** [comment]
This issue has been fixed

**Comment by Uafinder** [comment]
The same!

**Comment by bradmac** [comment]
Has not been deployed yet.

**Comment by Uafinder** [comment]
My mistake... it's on sandbox!

**Comment by anhnt** [comment]
hey vlad, could you create me an account in sandbox for testing? Also please provide me your site url? Thanks

**Comment by anhnt** [comment]
@Uafinder: The leadman app needs to have a Sale group (in global app settings) to work with contact importer. I have setup this and its working fine
![vlad](https://cloud.githubusercontent.com/assets/735555/13941216/0e4bd6a8-f018-11e5-92f1-50027373ff5e.PNG)

**Comment by bradmac** [comment]
@anhnt can you add some validation to inform the user if settings are not present?

**Comment by anhnt** [comment]
Now it should show a validation message at first step

**Comment by Uafinder** [comment]
Well, import successful, but:
- there no validation message when no LeadMan setting is setup (and no matter if it's setup at all)
- "complete" button still does nothing...

**Comment by anhnt** [comment]
We need to clarify a point:

- Importer is a service which running on root folder, not website branch, so leadman settings should be present in global app settings, not website app settings.

> validation message appears always

I will update the code to check if a sale group is present in global settings

> "complete" button still does nothing...

This button should reset the wizard and collapse the panel

**Comment by bradmac** [comment]
" leadman settings should be present in global app settings, not website app settings." :+1:

**Comment by Uafinder** [comment]
Let's clarify:
1 BUG - sales group are selected in website app and not selected in global app setings. However i am able to upload contacts.
2 BUG - Complete button does NOTHING. It means that when you push it - nothing is happen and no code are executing.

**Comment by bradmac** [comment]
Guys, probably best for you to two to chat on skype.

**Comment by anhnt** [comment]
@Uafinder The fix hasnt been deployed yet. Please be informed
