### ISSUE TITLE
Infiniti: Leads page sorting icons is bad

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1463]
![image](https://cloud.githubusercontent.com/assets/1945230/13730402/fa2bc5c4-e956-11e5-8878-3d79d58f2627.png)

**Comment by anhnt** [comment]
removed those icons

**Comment by Uafinder** [comment]
Doesn't removed - it's first.
Second - they shouldn't be removed because of this is a part of sorting mechanism

**Comment by bradmac** [comment]
As @Uafinder says, we definitely need those icons.

**Comment by anhnt** [comment]
Restore this icon and change it position. @Uafinder please let me know your thoughts

**Comment by Uafinder** [comment]
They looks pretter right now, so i htink that this is enouth for now
