### ISSUE TITLE
Infinity: company details are not saving

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1466]
![image](https://cloud.githubusercontent.com/assets/1945230/13730463/aa9abad6-e958-11e5-8f75-1194cd20f818.png)
Go to the lead page
Company tab
Enter some info
Save it
Refresh page
There is nothing there

**Comment by anhnt** [comment]
worked fine at my local

**Comment by bradmac** [comment]
@anhnt please try to reproduce on the same site as vlad

**Comment by Uafinder** [comment]
It's happens when you tried to add Company name after lead creation. If lead are created with Company name, it would be fine, but when you tried to add it after - will have no success.

**Comment by anhnt** [comment]
Thanks @Uafinder for the steps. I can reproduce this at the moment...

**Comment by anhnt** [comment]
@bradmac I can fix this issue. But the question is: if there's existing org named Riot and i go to view a lead that doesnt have org, and i updated this lead org with value "Riot", then it will create new org with the same name. Should we add a feature that can search existing org and fill the fields then?

**Comment by bradmac** [comment]
An org search like we do for profiles would be good, so the user can select an existing org if one exists. This is a bit simpler then for profiles, because there is only one field to search on.

**Comment by anhnt** [comment]
Ok will implement that now

**Comment by anhnt** [comment]
done

**Comment by Uafinder** [comment]
Good
