### ISSUE TITLE
Infinity: assigned lead shows like not assigned from userside

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1467]
![image](https://cloud.githubusercontent.com/assets/1945230/13730495/b5523278-e959-11e5-8174-3a02ba25fd48.png)
![image](https://cloud.githubusercontent.com/assets/1945230/13730497/c0168ca4-e959-11e5-9be1-86a53f78f325.png)

**Comment by bradmac** [comment]
probably jsut wrong template code in the second one

**Comment by Uafinder** [comment]
Yup
