### ISSUE TITLE
Infiniti: Leads page search issue

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1468]
![image](https://cloud.githubusercontent.com/assets/1945230/13730512/31af4932-e95a-11e5-8d6b-0001f7a847ca.png)

It works only when you enter something and then push on the search button. It doesn't work as case sensitive or while pressing enter button.
Also, search button hasn't apropriate cursor.

**Comment by bradmac** [comment]
- make auto-search on keypress delay
- change header stats table to be half current height, by putting the 4 stats boxes in a row, with pie chart
- add a clearer X

**Comment by anhnt** [comment]
done. @Uafinder could you please test it

**Comment by Uafinder** [comment]
Looks ok!
