### ISSUE TITLE
Infiniti: calendar type choosing

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1469]
![image](https://cloud.githubusercontent.com/assets/1945230/13730550/ffb79e88-e95a-11e5-9003-5137fd4ff95d.png)
When you choose some type of calendar, you would not be able to choose another one because dropdown will disappear.

**Comment by bradmac** [comment]
What you're actually doing is choosing a specific calendar to look at, instead of having them combined. You can click the back button, or the calendars menu item, to get back to the starting page
