### ISSUE TITLE
Infiniti: There is no voice memo for lead creation in IE

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1471]
![image](https://cloud.githubusercontent.com/assets/1945230/13730625/c046d398-e95c-11e5-941d-542b9166254c.png)
FF

![image](https://cloud.githubusercontent.com/assets/1945230/13730628/cdd6597a-e95c-11e5-9800-6e7009832091.png)
IE

**Comment by bradmac** [comment]
That is correct, not supported in IE and not required on desktops generally.
