### ISSUE TITLE
Infiniti: Strange functionality for register to the event button

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1472]
![image](https://cloud.githubusercontent.com/assets/1945230/13730633/f5baff9a-e95c-11e5-9d64-cb53ebddfdeb.png)
Pushing it causes:
![image](https://cloud.githubusercontent.com/assets/1945230/13730635/0427fe48-e95d-11e5-8ffc-75ae25def8e9.png)
And wht should be here?

**Comment by bradmac** [comment]
Yes, we will need an infiniti customisation to hide the register button

**Comment by anhnt** [comment]
fixed

**Comment by Uafinder** [comment]
yup
