### ISSUE TITLE
KCRM: No source of funnel stage appearing in dropdown when adding a lead

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1474]

**Comment by paddyow** [comment]
Just opened a browser, navigated to KCRM.  Went to add new Agency lead from dropdown.  No source of stage appearing in drop down.  This issue is intermittent. 

![image](https://cloud.githubusercontent.com/assets/2201340/13735558/512a138c-e9ff-11e5-86f0-9b91af572bca.png)

**Comment by bradmac** [comment]
@tuzzmaniandevil this appears to be an intermittent error, something to with the ajax loading.

**Comment by paddyow** [comment]
Update, after I clicked on the create and go to button, the lead page didnt seem to load.

![image](https://cloud.githubusercontent.com/assets/2201340/13735590/af911042-e9ff-11e5-8f42-8051827c7beb.png)

**Comment by bradmac** [comment]
Maybe put try/catch around the piechart code to ensure any error there does not affect the rest of the page

**Comment by tuzzmaniandevil** [comment]
I reproduced it when I logged in from admin (Login as) and the login params were still in the URL. This was because it was using window.location.href instead of window.location.pathname
