### ISSUE TITLE
Cannot download/open group CSV in Safari

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#148]
When a user tries to open a CSV from a group page using Safari Version 8.0.3 (10600.3.18) on a MAC, the CSV file does not open/download, instead it resolves to a web-page which is blank with the exception of the fields beings listed top left in a row.

**Comment by tuzzmaniandevil** [comment]
I don't have a MAC but I think this should fix it.

**Comment by Uafinder** [comment]
Now it looks like this way:
![image](https://cloud.githubusercontent.com/assets/1945230/6155118/81114088-b239-11e4-93e5-72185dd2d261.png)
Is this what expected?
