### ISSUE TITLE
KCRM:  Format the new profile name selector drop down

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1482]
http://kcrm.olhub.com/leads/134307722/ - navigate to profile tab

When assigning a new profile to a lead, then typing in the users first name, the dropdown box isn't wide enough to cover the width of each email address.

![image](https://cloud.githubusercontent.com/assets/2201340/13735915/4c615988-ea03-11e5-9afa-9f9f64409bb9.png)

**Comment by bradmac** [comment]
We are going to refactor implicit search anyway.
