### ISSUE TITLE
KCRM: Analytics page not showing funeel

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1483]
http://kcrm.olhub.com/analytics/agency-sales

Not showing enterprise sales in the drop down
When on the analytics page, the drop down menu items have a blue background color 

![image](https://cloud.githubusercontent.com/assets/2201340/13738187/210f276a-ea17-11e5-873f-f38666f57392.png)

**Comment by anhnt** [comment]
fixed
