### ISSUE TITLE
Infiniti: Event page label

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1484]
![image](https://cloud.githubusercontent.com/assets/1945230/13756306/ff6a3364-ea27-11e5-9d3b-a4b094043599.png)

And, is this page necessary at all?

**Comment by bradmac** [comment]
This page should allow editing event details

**Comment by anhnt** [comment]
what should I do for this issue? Please advice @bradmac

**Comment by anhnt** [comment]
Applied to bs335 theme. needs to update custom viewEvent.html on infiniti-crm after prod release
