### ISSUE TITLE
Infiniti: Question about add contacts and leads when you're public

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1485]
![image](https://cloud.githubusercontent.com/assets/1945230/13756385/559ab772-ea28-11e5-8eb2-6e8febb9bce8.png)
Looks like there is a possibility to add a lead and contacts when you're not logged in. Is it make sence? And what buttons should be available when you are not logged in?

**Comment by bradmac** [comment]
Pages should only be accessible when logged in.
