### ISSUE TITLE
Infiniti: How are the teams work?

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1486]
![image](https://cloud.githubusercontent.com/assets/1945230/13756625/6a26089e-ea29-11e5-8977-7563b183931e.png)

**Comment by bradmac** [comment]
The infiniti account contains organisations for each dealership. Currently that is:
- Hong Kong
- Sydney

A sales consultant has the the sales-consultant group linking them to their dealership. The account you are using links you to Infiniti, not a dealership, so is not correctly setup.

Note that this is the same structure as for Mercedes/StarRewards

A sales consultant may be in multiple dealerships

**Comment by Uafinder** [comment]
Thanks!
