### ISSUE TITLE
Infiniti: create a lead from email

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1487]
Is it works?
I've send a email from vlad@kademi.com to promoted email address, and have no success. Any rules or restrictions?
![image](https://cloud.githubusercontent.com/assets/1945230/13756686/b05c7988-ea29-11e5-89a6-2d8a9e84799e.png)

**Comment by bradmac** [comment]
The from address must be for a sales consultant in the account

**Comment by Uafinder** [comment]
Yup, it works! Thanks!
