### ISSUE TITLE
Admin viewer role issues

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#149]
There is a possibility to edit some content in AdminViewer role. Should be restricted.
![image](https://cloud.githubusercontent.com/assets/1945230/6112777/2138bf50-b09b-11e4-97aa-b1e78a53a604.png)

When you will try to push "edit your first module" you will give an error.
![image](https://cloud.githubusercontent.com/assets/1945230/6112799/500d6042-b09b-11e4-8fcd-322c89492d46.png)

**Comment by bradmac** [comment]
hey @tuzzmaniandevil just need to not show the menu if they dont have access to it

**Comment by Uafinder** [comment]
1. Manage content menu should be disabled at all
2. Edit my first learning module should be either disabled or hided.
3. Organisation details should either unavailable at all or save button there should be hided(or disabled).
![image](https://cloud.githubusercontent.com/assets/1945230/6175113/a88fdf2a-b2fc-11e4-9234-6c075e0ae516.png)

**Comment by Uafinder** [comment]
What are the changes? Looks like the same.

**Comment by bradmac** [comment]
@tuzzmaniandevil could you point @Uafinder at the changes?
