### ISSUE TITLE
KCRM: Creating lead enhancement

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#1497]
when someone is entering a lead they dont know if that person is already a contact or not...
we want them to be able to start typing first name, or surname, email address, and to have a table under those fields which auto-searches based on whatever they've entered.
if they see a user in that list which is the person they want to enter, then they click it. That should set a hidden field, which is there already, with the profile id, and auto-fill the name and email fields
if they dont select a profile, then they just type in those fields and press save

**Comment by anhnt** [comment]
@Uafinder could you help me test this by going to create new lead
![search profile](https://cloud.githubusercontent.com/assets/735555/13801736/731912fe-eb67-11e5-8d3e-878003f6851d.PNG)

**Comment by bradmac** [comment]
@anhnt as discussed
- there should be no "find contact" field, instead the search should be from the inputs
- the table should be below the 4 profile inputs
- i think it would be good UX if you can just click anywhere on the row to select it. remove the select button
- combine first name and surname into a single column in the search results

**Comment by anhnt** [comment]
this has been done as @bradmac mentioned. @Uafinder could you have a test for this please

**Comment by Uafinder** [comment]
Minor thing is spotted:
When you have a contact without a telephone number for example, you search it abd choose it,and want to add a number. But it will not appear in lead and contact profile as well.
![image](https://cloud.githubusercontent.com/assets/1945230/13857675/985194ca-ec83-11e5-9af8-e77ad40d5eea.png)
 Everything else looks great

**Comment by bradmac** [comment]
Needs to save phone number

**Comment by anhnt** [comment]
this should save phone number and surname as well

**Comment by Uafinder** [comment]
Yes, looks ok
BTW
![image](https://cloud.githubusercontent.com/assets/1945230/13905264/bd2da9c2-eec3-11e5-9ebf-050a9d876c8b.png)
![image](https://cloud.githubusercontent.com/assets/1945230/13905270/f13fa24c-eec3-11e5-97c9-c93085ac48c2.png)
Looks more prettier in Infiniti. 
And it should disappear when account is choosen.
![image](https://cloud.githubusercontent.com/assets/1945230/13905274/1772c85e-eec4-11e5-8feb-c9542ec5b177.png)

**Comment by bradmac** [comment]
@anhnt, can you please make the table more compact
 - remove column headings
 - use the .table-condensed class
- use vertical scroll bars to limit max height to about 5 rows worth
- make the table span the width of the modal, ie use the left 2 cols where labels are
- remove table border

**Comment by anhnt** [comment]
this will look like following
![table](https://cloud.githubusercontent.com/assets/735555/13909897/059c2b78-ef4d-11e5-97c4-3a63d21ca9ce.PNG)

**Comment by Uafinder** [comment]
vertical limit is not restricted
![image](https://cloud.githubusercontent.com/assets/1945230/13930873/6c5475c6-efa9-11e5-96ef-b75541424a3a.png)

**Comment by anhnt** [comment]
fixed

**Comment by Uafinder** [comment]
could you confirm that this enhancement searching from contacts? or it searching from contacts which had already leads?
http://vladqasand1.kademi-sandbox.co/custs/
by first link there 8-9 custs
and 6 guys by "vlad" search criteria when lead creation

**Comment by bradmac** [comment]
It should search all profiles with the lead group

**Comment by Uafinder** [comment]
Looks ok!
