### ISSUE TITLE
Remove from group action bug

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#150]
steps to reproduce:
1. Create a trigger, choose some triggers inside.
2. Choose a remove from group action. Select some group.
3. Push save.
4. Refresh.
5. Go back to actions tab, group field is empty again.
![image](https://cloud.githubusercontent.com/assets/1945230/6113226/378062f6-b09e-11e4-8167-e37f281ff238.png)

**Comment by tuzzmaniandevil** [comment]
Fixed, Also fixed the list showing deleted groups.

**Comment by Uafinder** [comment]
Yeap, works fine
