### ISSUE TITLE
Error after deleting KPI levels

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1501]
After deleting a level in a KPI the manage kpi page can no longer be correctly viewed

 <html><body><h1>Invocation of method 'size' in  class org.hibernate.collection.internal.PersistentBag threw exception org.hibernate.ObjectNotFoundException: No row with the given identifier exists: [com.fuselms.db.KPILevel#5697973] at mercedes.admin.kademi-sandbox.co:/theme/apps/salesdata/manageKpi.html[line 294, column 55]</h1><h2><a href='/templates/themes/admin/'>/templates/themes/admin/</a></h2><p>Line: 294, Column: 55</p>Invocation of method 'size' in  class org.hibernate.collection.internal.PersistentBag threw exception org.hibernate.ObjectNotFoundException: No row with the given identifier exists: [com.fuselms.db.KPILevel#5697973] at mercedes.admin.kademi-sandbox.co:/theme/apps/salesdata/manageKpi.html[line 294, column 55]<hr><h3>Template</h3><pre>1: &lt;form name&#61;&quot;frmDetails&quot; action&#61;&quot;&#46;&quot; method&#61;&quot;post&quot; class&#61;&quot;form-horizontal kpi-form&quot;&gt;
2: &lt;div class&#61;&quot;pull-right page-action&quot;&gt;

**Comment by tuzzmaniandevil** [comment]
Level wasn't being removed from list in KPI
