### ISSUE TITLE
URL shortner not loading data

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1504]
http://kademi.admin.olhub.com/shortUrl/

![image](https://cloud.githubusercontent.com/assets/2201340/13801702/b2b5d8f4-eb88-11e5-9f88-b80a6944882f.png)

**Comment by tuzzmaniandevil** [comment]
This was because the searchResponseView in ViewsBuilder hadn't been updated for the new ElastisSearch structure

**Comment by paddyow** [comment]
Has old data been lost since the update?

**Comment by tuzzmaniandevil** [comment]
Just needed to be re-indexed. do the results seem accurate now?

**Comment by bradmac** [comment]
ohhh, pretty

**Comment by paddyow** [comment]
Super sexy!  Closed!
