### ISSUE TITLE
Inline mode for keditor

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#1505]
* Embed keditor by using iframe for blog, module, calendar
 * Support `postMessage` for `contentEditor` for trigger saving content cross-frames
 * Support fullscreen overlay for module pages

**Comment by ducdhm** [comment]
@bradmac Can check add new module page or edit module page (In modal) in Manage this module screen and give me feedback?

Example screenshot
![aaa](https://cloud.githubusercontent.com/assets/1289631/13853727/a394b990-ec9a-11e5-9b67-cf7efadf3192.png)

**Comment by bradmac** [comment]
Looking good! Just a couple of things
- i get funny characters at the top left
![funnychars](https://cloud.githubusercontent.com/assets/826458/13865011/8e42e7ee-ed0b-11e5-9126-d14b83f49d64.png)
- Please add preformatted containers to the top of the container list. Have a couple of common options like image + html
- The edit modal should have options for Save and Save & Close
- Make keditor the default editor (ie attached to Edit and + buttons) for bs335+ only. Easiest way to do this would be to check for bs300 and bs320, else use new edtior

**Comment by bradmac** [comment]
Also, we nee the ckeditor table dialog to be properly integrated with bootstrap. Should have the table class by default, and have options for making striped and bordered

**Comment by bradmac** [comment]
Also, for image editor dialog, please add options for rounded, circle and thumbnail

**Comment by ducdhm** [comment]
[UPDATING]

* i get funny characters at the top left 
-> I dont see it in my local
* Please add preformatted containers to the top of the container list. Have a couple of common options like image + html
-> Done!
* The edit modal should have options for Save and Save & Close
-> Done!
* Make keditor the default editor (ie attached to Edit and + buttons) for bs335+ only. Easiest way to do this would be to check for bs300 and bs320, else use new edtior
* The insert image and video dialogs have broken layout
* Also, we nee the ckeditor table dialog to be properly integrated with bootstrap. Should have the table class by default, and have options for making striped and bordered
* Also, for image editor dialog, please add options for rounded, circle and thumbnail

**Comment by bradmac** [comment]
"i get funny characters at the top left-> I dont see it in my local"
- Have you tried different browsers?

**Comment by ducdhm** [comment]
* Have you tried different browsers?
-> Yep. I checked on FF, Chrome and IE11 on Windows 10. No special characters.

**Comment by bradmac** [comment]
Integrated with calendar events.

@ducdhm can you
 - optimise the calendar event details page to have input fields in 2 cols
 - test both on bs335 and other themes (esp bs300)
