### ISSUE TITLE
Infiniti: If you specified a company name it will shown istead of lead username

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1509]
![image](https://cloud.githubusercontent.com/assets/1945230/13857284/e9e9b0e4-ec81-11e5-9416-5e596015b713.png)

**Comment by bradmac** [comment]
When there is both a company name and profile, it should show both. Eg

Joe Smith (ACME Ltd)

**Comment by anhnt** [comment]
done

**Comment by Uafinder** [comment]
Nope
![image](https://cloud.githubusercontent.com/assets/1945230/13905134/593b32d0-eebf-11e5-8b6b-7ca4739e674e.png)

**Comment by anhnt** [comment]
fixed on lead page

**Comment by Uafinder** [comment]
Look ok!

**Comment by Uafinder** [comment]
It should analize if either provided user fields or not.
![image](https://cloud.githubusercontent.com/assets/1945230/13934692/15af87a2-efbc-11e5-88cc-3eb54192686a.png)

**Comment by Uafinder** [comment]
Ok now
