### ISSUE TITLE
KCRM: Bugs on dashboard (sandbox)

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1515]
![image](https://cloud.githubusercontent.com/assets/1945230/13905303/ada3cbac-eec4-11e5-83bb-67ac0c6ee3d2.png)
Scroll bars
Visual issues with the balls

**Comment by bradmac** [comment]
@anhnt  We need to make the funnel visualisation responsive. But let me know if this is going to be a big job, we can get a freelancer to do it.

@Uafinder What are the issues with the balls?

**Comment by Uafinder** [comment]
@bradmac It shows a circle and a square for one lead. As you can see there light blue circle and square and another one blue square and circle

**Comment by bradmac** [comment]
The "square" is a histogram, showing leads by date along the bottom border. The circles show the number of leads currently

**Comment by anhnt** [comment]
Please check it in next release @Uafinder
