### ISSUE TITLE
KCRM: Problems with inline editing on the leads page

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1519]
- Cannot edit stages
- Need to be able to select assignee
- Enable editing of source

**Comment by Uafinder** [comment]
https://github.com/Kademi/kademi-dev/issues/1529

**Comment by tuzzmaniandevil** [comment]
- Enabled editing source
- Also changed the inline editing so select fields like stage and source only show the data relevent to that lead.

**Comment by tuzzmaniandevil** [comment]
- Enabled editing assignee
