### ISSUE TITLE
KCRM: Dashboard question

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1520]
![image](https://cloud.githubusercontent.com/assets/1945230/13930716/b6985266-efa8-11e5-9888-6eb8f0ea9330.png)
Strange dashboard issue and a lot of empty space
http://vladqasand1.kademi-sandbox.co/dashboard

**Comment by bradmac** [comment]
have another look after next deploy

**Comment by Uafinder** [comment]
Deploy doesn't help

**Comment by bradmac** [comment]
try using the new org location feature to set a location for your org, and child orgs

**Comment by Uafinder** [comment]
![image](https://cloud.githubusercontent.com/assets/1945230/13932550/32debc2c-efb1-11e5-8c0e-3d29d142b9e2.png)

**Comment by bradmac** [comment]
Ah, got it. Thanks :)

**Comment by bradmac** [comment]
@tuzzmaniandevil its accidentally got a hard coded reference to the funnel. I think we can move these stats up a level, and aggregate across all funnels.

**Comment by bradmac** [comment]
Also, can you please make the stats summary panel show
- for a sales consultant, the stats summary should show their personal stats (as it does now)
- for a sales manager, it should show aggregations across the teams they have access to
