### ISSUE TITLE
KRCM: Analytics page question

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1522]
I have several leads in progress, however they are not shown on the analytics page
![image](https://cloud.githubusercontent.com/assets/1945230/13931290/4f0a169a-efab-11e5-8cd9-b7e23ec53ff7.png)
![image](https://cloud.githubusercontent.com/assets/1945230/13931344/8b49f0d0-efab-11e5-9c9f-a96ea4214320.png)
Is this a bug?

http://vladqasand1.kademi-sandbox.co/analytics/sales
vladqas001@mailinator.com
qwerty1

**Comment by bradmac** [comment]
Yes, thats a big. I think the funnel is completely not working at the moment. @anhnt could you get that working again as a priority?

**Comment by Uafinder** [comment]
![image](https://cloud.githubusercontent.com/assets/1945230/14020954/14252a36-f1e2-11e5-98ef-944e7f3e7983.png)

Why the bottom part still empty? Still something bad with this page?

**Comment by bradmac** [comment]
That should display active leads, matching any selected criteria (ie clicking on a group in the funnel applies a filter)

**Comment by anhnt** [comment]
It works now http://vladqasand1.kademi-sandbox.co/analytics/sales. @Uafinder please be noted that users with SaleTeamViewer role can see Analystic Pages

**Comment by Uafinder** [comment]
ok
