### ISSUE TITLE
KCRM: searching

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1523]
![image](https://cloud.githubusercontent.com/assets/1945230/13932732/4195d86c-efb2-11e5-9fbf-3473a2b5813f.png)
For example you are searching for qas008. It shows you a clean correct result. So you wanna to cancel search results and watch a whole list. You should press "x" near the search. But it doesn't reset search results.
![image](https://cloud.githubusercontent.com/assets/1945230/13932783/7eb9e17a-efb2-11e5-8af4-f50696d42c3a.png)

**Comment by anhnt** [comment]
this bug occurs on IE only. Fixed

**Comment by Uafinder** [comment]
Yup, this one is ok.
Another questuin about search criteria: it searching only by name or surname... probably would be great to add a email field as well.

**Comment by bradmac** [comment]
Yes. Also should search by company name.

**Comment by tuzzmaniandevil** [comment]
This page shows profiles, and searches on the following fields:
`"nickName", "firstName", "surName", "phone", "email"`

I tested the searching on the same account as the screenshot above, email serching works fine

**Comment by tuzzmaniandevil** [comment]
I've added orgTitle to the search
