### ISSUE TITLE
KCRM: leads searching

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1524]
![image](https://cloud.githubusercontent.com/assets/1945230/13932830/c1d0af34-efb2-11e5-9a3c-45d6781b9535.png)
You wanna to search a lead by name, surname, company name or email address, but looks like search works only by Name field. And when you are using a space, anything after it will no matter for search (or it could use a "IF" method offcourse).

**Comment by bradmac** [comment]
@tuzzmaniandevil can you please check the search criteria?

**Comment by tuzzmaniandevil** [comment]
Fixed
