### ISSUE TITLE
KCRM: IE side scroll bar covers login dropdown

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1525]
IE
![image](https://cloud.githubusercontent.com/assets/1945230/13934452/f773bc8c-efba-11e5-85ea-97b15a846cbc.png)
FF
![image](https://cloud.githubusercontent.com/assets/1945230/13934476/1e8e07a0-efbb-11e5-926c-4517b209d413.png)
Spot it earlier in Infiniti

**Comment by anhnt** [comment]
fixed

**Comment by Uafinder** [comment]
Ok!
