### ISSUE TITLE
Data series cannot be open (Only PROD)

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#153]
![image](https://cloud.githubusercontent.com/assets/1945230/6134126/b095e8ea-b167-11e4-96a0-8c2175a51fd1.png)
I'm opening an already created Data series and it's open for me blank page.
This bug is seen only on PROD.

**Comment by tuzzmaniandevil** [comment]
Fixed

**Comment by Uafinder** [comment]
Yeap, thanks
