### ISSUE TITLE
KCRM: Dashboard lead text too long.

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1532]
Truncate the text to 200 characters.
Can we also have the text extend the width of the panel?

![image](https://cloud.githubusercontent.com/assets/2201340/13974944/ab939a12-f104-11e5-85b5-8c8d3947d8bb.png)

**Comment by bradmac** [comment]
Rather truncate text, lets use the dotdotdot plugin (or similar) to keep it to a maximum height.

http://dotdotdot.frebsite.nl/

And yes should use the width
