### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#1535]
* Update jquery.forms
 * Update jquery.user
 * Add jquery.module
 * Update jquery.comment

**Comment by ducdhm** [comment]
http://docs.kademi.co/ref/javascript/jquery.forms.html - New style for jquery plugin

**Comment by ducdhm** [comment]
http://docs.kademi.co/ref/javascript/jquery.module.html - jquery.module

**Comment by ducdhm** [comment]
http://docs.kademi.co/ref/javascript/jquery.user.html - jquery.user

**Comment by bradmac** [comment]
Awesome!!

**Comment by ducdhm** [comment]
http://docs.kademi.co/ref/javascript/jquery.comments.html - jquery.comments
