### ISSUE TITLE
Lead doesnt appear when created in lead page

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#1536]
Needs to refresh the page to see new lead http://kcrm.olhub.com/leads/

**Comment by bradmac** [comment]
@anhnt we cant expect our users to have to refresh the page. Please use reloadFragment to reload that parts of the page which have changed - including leads and tasks (tasks can be auto-created when leads are created). 

There are a couple of common methods which you might be able to use

**Comment by anhnt** [comment]
that should show new created lead now
