### ISSUE TITLE
KCRM: Template update

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1537]
Do not use solid colors that don't translate to other themes.  The vertical line is Kademi red but as you can see does not work for the Infiniti theme, it needs to be something like a 50% transparent white line.

![image](https://cloud.githubusercontent.com/assets/2201340/14004620/8c6bdc66-f1af-11e5-828d-3db71a99ccc5.png)

**Comment by bradmac** [comment]
That Kademi red should be a brand colour parameter, and that parameter should have an Infiniti specific value in the infiniti site.

**Comment by anhnt** [comment]
it should use white color with alpha transparent like the PSD now
