### ISSUE TITLE
KCRM: Validation says that there are some necessary fields but no red rectangle

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1546]
![image](https://cloud.githubusercontent.com/assets/1945230/14019897/7718d174-f1dd-11e5-8e16-f8297a175e82.png)

**Comment by anhnt** [comment]
Added client side validation

**Comment by bradmac** [comment]
@anhnt you should not need to add the required attribute, because those inputs have the required class which the forms plugin checks.

**Comment by anhnt** [comment]
added .form-group to enable jquery form validation
