### ISSUE TITLE
Improve scheduled emails page

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1550]
- make enabled/disabled a nice toggle
- show last run date
- show a textual description of the job, like we do for automations

**Comment by ducdhm** [comment]
New UI for Scheduled Email page
![aaaaa](https://cloud.githubusercontent.com/assets/1289631/14277500/9624a2d6-fb4d-11e5-8be5-e7c5d754ab18.png)

**Comment by bradmac** [comment]
Suggestions
- move next run  date into the header area, above the tabs. Include the exact time. Ie "Next run: a day from now, at 13:30"
- Make multiples and frequency a field group like they are in automation delay
- the groups panel should be clearly identified that this is recipients. Possibly put the 2 attachment fields side by side, and move recipients groups into a section below that, with a heading and paragraph of text explaining to add recipient groups
- use ckeditor for the messsage template instead of plain text

**Comment by ducdhm** [comment]
Final UI
![aaaaa](https://cloud.githubusercontent.com/assets/1289631/14305051/c1ddcaac-fbe2-11e5-8dde-f96f325cb276.png)

**Comment by bradmac** [comment]
Just a couple more...
- Make multiples and frequency a field group like they are in automation delay
- Make 'next run' floated top right
- Save should be inside the form details tab

**Comment by ducdhm** [comment]
Finale UI
![2222](https://cloud.githubusercontent.com/assets/1289631/14306006/ae84eac6-fbec-11e5-83e4-759cdbb0ee7f.png)
