### ISSUE TITLE
Public switch for websites

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1551]
- Display public/private info on manage websites page
- Add a public/private switch to the manage website page
- When public status is changed write an event to the streamservice (java)

**Comment by ducdhm** [comment]
New message on stream
![private_public](https://cloud.githubusercontent.com/assets/1289631/14314175/f6e1a132-fc1f-11e5-93a1-194d4ef0f02f.png)

**Comment by bradmac** [comment]
Please make messages like
"Changed website1 access to public"

**Comment by ducdhm** [comment]
![aaa](https://cloud.githubusercontent.com/assets/1289631/14314411/39090f2c-fc21-11e5-9fea-e5dd9adf6edc.png)
