### ISSUE TITLE
KCRM: Add team management functions to the team page

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1561]
SalesManagers (only) should be able to:
- add sales team members (sales consultants and managers)
- remove sales team members (sales consultants and managers)
- modify sales team member profiles by clicking through to their profile page

Note: https://github.com/Kademi/kademi-dev/issues/1558

**Comment by tuzzmaniandevil** [comment]
Team Management:
- User administrator role
- Stand alone app
- configure which groups are team groups
- team page, only show users which have a membership to selected groups
- When creating user add to org from selector, if selector not avail use org from user admin role
- User radio for group select
- basic info when creating
- User ProfilePage to allow user to be edited
