### ISSUE TITLE
Logs page to use polling instead of websockets

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1568]
Persist logs to an ES index for the organisation. Do not support re-indexing.

Logs page should poll from that index to show the live logs page for an org

**Comment by bradmac** [comment]
Logs are now captured in WebStreamingAppender to ES using an AppIndexer in AdminApp. Note it is not-re-indexable, doing a reindex just deletes everything, but thats cool. This is only intended to be transient data.

The logs page is mostly integrated, but needs finishing

**Comment by bradmac** [comment]
- make all filtering server side, doesnt need to filter locally. but when changing a filter should reload from the server with the filters
- remove vertical scroll bar from header row
- make scroll back limit user editable

**Comment by tuzzmaniandevil** [comment]
- make all filtering server side, doesnt need to filter locally. but when changing a filter should reload from the server with the filters **Done**
- remove vertical scroll bar from header row **Done**

**Comment by tuzzmaniandevil** [comment]
- make scroll back limit user editable **Done**
