### ISSUE TITLE
Need any way for admin to see all users uploaded files?

### ISSUE THREAD

**Issue by mamun4343** [Kademi/kademi-dev#1570]
![untitled](https://cloud.githubusercontent.com/assets/3419573/14097985/328b4158-f599-11e5-940c-f82c148248d4.png)

after uploading files from front end.  admin wants to see the uploaded files for all users.

**Comment by anhnt** [comment]
i think its better for admin to see user shared folder instead of view their all files

**Comment by bradmac** [comment]
I think EMC will probably need something customised. Let me have a chat to them

**Comment by bradmac** [comment]
Hey @anhnt, did you already do something for this?

**Comment by anhnt** [comment]
yeah its done https://github.com/Kademi/kademi-dev/issues/1624

**Comment by anhnt** [comment]
For example when My file app is enabled http://admin.anhnt.olhub.com/manageUsers/134070761/#myfilesAppTab-tab

**Comment by bradmac** [comment]
I've had to temporarily disable the code in MyFiles to autocreate repositories. 

This was causing an error when importing users. Needs to be tested on sandbox with a proper db.

**Comment by anhnt** [comment]
@bradmac please let me know when sandbox gets deployed. i will test it then
