### ISSUE TITLE
dashboard is broken

### ISSUE THREAD

**Issue by mamun4343** [Kademi/kademi-dev#1572]
http://nest-vc.admin.olhub.com

see attachment
![untitled](https://cloud.githubusercontent.com/assets/3419573/14106853/eb256158-f5d5-11e5-923e-d0dee5d1c6be.png)

**Comment by bradmac** [comment]
Looks ok to me

**Comment by anhnt** [comment]
also looks ok for me. @mamun4343 can you reproduce it at the moment?

**Comment by mamun4343** [comment]
its ok to me .
@paddyow plz take a look.

**Comment by ducdhm** [comment]
@mamun4343 It's ok for now. So I think you should close this issue. If it happens again, please show us step by step for reproduct!
