### ISSUE TITLE
KCRM: Firefox font and doughnut issues on dahsboard

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1577]
Note incorrect font and white pixels in the doughnut. 

http://kcrm.olhub.com/dashboard

h![image](https://cloud.githubusercontent.com/assets/2201340/14159082/a936cb60-f71f-11e5-83ae-01e74d4e0073.png)

**Comment by bradmac** [comment]
I dont see those white pixels. Probably just something to do with your PC.

**Comment by anhnt** [comment]
looks ok to me as well. The font is correct now since its using Roboto Black

**Comment by anhnt** [comment]
it now uses self-hosted roboto font to make sure text appears with correct font
