### ISSUE TITLE
Firing triggers manually

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1588]
http://admin.minda.olhub.com/autoEmails/121395460/timerTriggers.html

I fired a trigger manually but it did not disappear  from the list of triggers straight away, so I fired it again then got two emails and finally the trigger disappeared form the trigger list.

Once a trigger has fired it should disappear.

**Comment by bradmac** [comment]
No, it doesnt work that way. Firing a trigger means that it is due right now. It will be processed when the queue processor next scans the list of triggers.

It would have been processed shortly after you fired it the first time, and when you did it again that would have caused the trigger to be rescheduled again, and then processed again
