### ISSUE TITLE
KCRM: Team page (sandbox)

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1594]
![image](https://cloud.githubusercontent.com/assets/1945230/14261293/9a6486ee-fab8-11e5-99e9-c64c6f470a13.png)
http://vladqasand1.kademi-sandbox.co/team/
vladqas001@mailinator.com
qwerty1

**Comment by bradmac** [comment]
That is from a new app which needs to be enabled "Team Management"

I've enabled it, but the page is not showing correctly

http://vladqasand1.kademi-sandbox.co/team/

**Comment by tuzzmaniandevil** [comment]
Sorted
