### ISSUE TITLE
KCRM: there no username on the lead analytics page when company name exists

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1598]
![image](https://cloud.githubusercontent.com/assets/1945230/14262262/4d904614-fabd-11e5-93d4-d2ab4db373ef.png)

![image](https://cloud.githubusercontent.com/assets/1945230/14262279/61b9f64e-fabd-11e5-85e7-586faec0dad1.png)

**Comment by bradmac** [comment]
Should use same formatting as the lead page, ie user name followed by org

**Comment by anhnt** [comment]
needs to reindex lead after prod deploy

**Comment by Uafinder** [comment]
Not sure that should be a phone number
![image](https://cloud.githubusercontent.com/assets/1945230/14330577/dd8627d8-fc49-11e5-8ce6-d77048756c35.png)

**Comment by anhnt** [comment]
just removed phone number
