### ISSUE TITLE
KCRM: Inbox link on the dashboard

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1599]
![image](https://cloud.githubusercontent.com/assets/1945230/14262470/4e446670-fabe-11e5-8a12-0405c34bcd0b.png)
Without icon and bad tip text

**Comment by anhnt** [comment]
i think we just dont show icon of those apps like above. this should be done within bs335.leadman.
@bradmac please advise!

**Comment by bradmac** [comment]
Just want to adjust the menu so it has icon like other menu items
