### ISSUE TITLE
Product images folder

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#160]
The manage product screen provides the ability to upload individual images for a product. However, usually administrators will want to upload images in bulk. 

So we need to support webdav integration, where there is a folder that contains product images keyed on the product name/code.

To access this you would navigate to the admin site (eg http://admin.mysite.olhub.com) then open the products-images folder.

For now this capability supports only 1 image file per product. A later enhancement will be to have multiple images per product

**Comment by Uafinder** [comment]
It should be here?
![image](https://cloud.githubusercontent.com/assets/1945230/6254938/e2c08566-b7b4-11e4-969d-40827c515806.png)

**Comment by bradmac** [comment]
No, you only see the product images folder using webdav
![win7-dav](https://cloud.githubusercontent.com/assets/826458/6257547/d981f572-b825-11e4-9489-41fa0b1c83f5.png)

**Comment by Uafinder** [comment]
Thanks for details.
Works ok!
