### ISSUE TITLE
KCRM: when clearning assignment there is invalid pop-up

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1601]
![image](https://cloud.githubusercontent.com/assets/1945230/14262575/ecfc8bda-fabe-11e5-8840-a4db7c37208b.png)

**Comment by anhnt** [comment]
@Uafinder could you help me to reproduce that bug? I created a lead and then clear assignment and there's notification says "Assigned", not like yours

**Comment by anhnt** [comment]
just removed settings of leadman app in website settings, then it works

**Comment by Uafinder** [comment]
Such as i...
Saw it one more time, and then add TakeLead role to user group and then no matter of it's ok.
So, it good for now
