### ISSUE TITLE
KCRM: Searching no matter of assignment of the lead, so you are able to access and do any action to not your lead

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1603]
![image](https://cloud.githubusercontent.com/assets/1945230/14262995/e2c89fa8-fac0-11e5-8ced-2d3c69fe8043.png)
![image](https://cloud.githubusercontent.com/assets/1945230/14263001/e9131028-fac0-11e5-8b14-ee082576f9e5.png)

**Comment by bradmac** [comment]
Need to ensure sales consultant privacy when they do not have team viewer role. 

@tuzzmaniandevil lets discuss
