### ISSUE TITLE
Dynamic components for dashboard builder

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1607]
Here is a minimal list of dynamic components to start using the dashboard builder
- website list (done)
- stream (from admin dash)
- comments/recent posts (maybe from admin dash, or front end dash)
- history (from admin dash)
- email summary stats (from admin dash)
- web hits and bandwidth summary stats (from admin dash)
- KPI (single kpi per component, selectable)
- elearning suggested module
- elearning module list
- reward store categories
- e-com product categories

Also need to allow custom apps to provide dynamic components, ie KPoll and KSurvey. Will come later..

**Comment by ducdhm** [comment]
(y)

**Comment by bradmac** [comment]
@anhnt we just need to finish off these components. Can you please:
- make a nice thumbnail for the snippet list
- create settings panels
- i think we need a height attribute so we can get rows to line up nicely

Components are
- blogList
- recentPoints
- kpi visualisation
- tasks list
- elearning modules

**Comment by bradmac** [comment]
Here's how it looks at the mo
![custom-dash](https://cloud.githubusercontent.com/assets/826458/14415834/63d45822-fff7-11e5-84a0-8b8769748cf8.png)

**Comment by ducdhm** [comment]
https://github.com/Kademi/kademi-dev/issues/1857
https://github.com/Kademi/kademi-dev/issues/1858
https://github.com/Kademi/kademi-dev/issues/1859
https://github.com/Kademi/kademi-dev/issues/1860
https://github.com/Kademi/kademi-dev/issues/1861

Let's move to smaller issues
