### ISSUE TITLE
Consistent use of date selection in admin

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1608]
Kademi admin has quite a few admin screens with a date selector like this:

![dates](https://cloud.githubusercontent.com/assets/826458/14278680/098e515c-fb7d-11e5-88c9-a8c948cb8ca2.png)

Usually when a user is interested in a particular period of time, they will want to continue using that same time period across screens. So we should ensure that the selected date is held in a cookie and applied by default on all screens that use a date picker for reports (but not for form fields!!)

Also, the UX is poor when the date selector appears in different locations. Instead we should have a standard part of the UI framework where the date selector goes. An example of this being done well is with newrelic. Eg:

![newrelic-dates1](https://cloud.githubusercontent.com/assets/826458/14278763/75c91fd2-fb7d-11e5-82ce-05309133b350.png)

![newrelic-dates2](https://cloud.githubusercontent.com/assets/826458/14278767/7acc67c8-fb7d-11e5-8406-463ae1cdc654.png)

We can show the date selector for pages which need it (do not display it on pages that do not need it) just after the bread crumb trail. There will often be a free text search field, and this can also be a standard ui element. Eg:

![kademi-dates](https://cloud.githubusercontent.com/assets/826458/14278927/4ba7c2e8-fb7e-11e5-8403-d4df177806c6.png)

**Comment by bradmac** [comment]
Custom date view
![custom-date](https://cloud.githubusercontent.com/assets/826458/16574034/be1fe3cc-42ce-11e6-9d3f-4acd25529ea7.png)

**Comment by bradmac** [comment]
Custom date handling
![custom-date2](https://cloud.githubusercontent.com/assets/826458/16574042/d8cb715a-42ce-11e6-9447-5ea18aecbb1e.png)

**Comment by ducdhm** [comment]
Done!

**Comment by bradmac** [comment]
I've integrated with the email history page.

@ducdhm can you now please integrate that across all admin pages, including
- dashboard panels
- automation history
- reports
- SMS history
- contact requests
- points buckets, points tab
- shopping carts
- reward points
- audit records
- submissions
