### ISSUE TITLE
Deleted websites and programs|modules appearing in Triggers

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#161]
Deleted websites and programs|modules appearing in Triggers
![image](https://cloud.githubusercontent.com/assets/1945230/6174897/d888d97c-b2fa-11e4-96be-8e1e6ef3b74d.png)
![image](https://cloud.githubusercontent.com/assets/1945230/6174899/e0bb9120-b2fa-11e4-9879-570476e160a8.png)

**Comment by Uafinder** [comment]
Websites - Fixed
Modules and Courses - doesn't fixed. 
![image](https://cloud.githubusercontent.com/assets/1945230/6235416/f55443cc-b6ea-11e4-8905-185892da06c3.png)

**Comment by bradmac** [comment]
Fixed

**Comment by Uafinder** [comment]
Looks ok!
