### ISSUE TITLE
Minor visual issue on users page when user has lot of groups

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1612]
![image](https://cloud.githubusercontent.com/assets/1945230/14329647/2f013b02-fc45-11e5-8ea0-82b5d4a2a80c.png)

**Comment by ducdhm** [comment]
New UI

![aa](https://cloud.githubusercontent.com/assets/1289631/14433266/d8411e8a-0037-11e6-99c1-6289541180bf.png)

**Comment by Uafinder** [comment]
There should be some limit
![image](https://cloud.githubusercontent.com/assets/1945230/14539484/46a7b372-0289-11e6-9f09-d42a9762b61d.png)
It's from mercedes sandbox account

**Comment by bradmac** [comment]
Users will have such a large number of primary memberrships. Usually there is only 1 or 2 primary memberships.
