### ISSUE TITLE
Kademi admin pages couldn't loading (sandbox)

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1613]
For example - going to http://vladqasand.admin.kademi-sandbox.co/
Enter credentials
Push Login
Page refreshes, but nothing happens

Find this in firebug
 ["login success", true]
common.js (line 203)
["login: no afterLoginUrl and no nextHref, so reload"]
common.js (line 203)

Fortunately root admin page is loading and there is a possibility to go further from it

**Comment by bradmac** [comment]
I would expect thats a permission problem. 

You have a profile in that account with your real email address, which is a sales consultant and probably does not have permission to access the admin. If you're logging in with your email address this profile will be selected.

**Comment by Uafinder** [comment]
Yeah, it works. Thanks!
