### ISSUE TITLE
Refactor groups page

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1616]
The manage groups page is extremely slow with a large number of groups. For example, in the w6rb (healthhub) account its 730Kb

This is because of the lists of options generated for each group.

Please move all editing functions (including roles and programs) to the manage group page.

Note that editable sections should be provided by apps. Eg the program/course enrolement should be from the elearning app via portlets

**Comment by ducdhm** [comment]
Other issue in group page:
 * Create an extra field, click on `Profile Identifier`
 * Some controls are disabled
 * Click save and create other extra field
 * Disabled controls are not re-enabled

**Comment by ducdhm** [comment]
New UI:
 * In Groups page
![fireshot capture 21 - manage groups - http___localhost_8080_groups_](https://cloud.githubusercontent.com/assets/1289631/15491683/2d59e74a-219d-11e6-924f-072bfcf7a3c0.png)

 * In Group page
![fireshot capture 22 - manage group_ administrators_ - http___localhost_8080_groups_admin](https://cloud.githubusercontent.com/assets/1289631/15491687/35ba2a58-219d-11e6-94b9-a58ac49d77a3.png)

**Comment by bradmac** [comment]
Adding roles: I get a 404 error when clicking to add a role. Eg:
http://localhost:8080/groups/sales/sales - 404 Not Found
(actual group page is http://localhost:8080/groups/sales/)

Adding programs: No error message, but the enrolement does not display in the panel, including after refreshing the page

**Comment by ducdhm** [comment]
Fixed!
