### ISSUE TITLE
KEditor: E-Learning editor to use same editor for new and existing pages

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1619]
Currently new pages are created in a full screen overlay, but editing pages opens a new tab.

It would be better if both used the overlay, and that should be the default editing editor for supported themes

Also: improve validation for missing title. Currently there is no message if the title is blank, only a red outline. Needs to be obvious.

**Comment by ducdhm** [comment]
New error message

![new_error](https://cloud.githubusercontent.com/assets/1289631/14373996/a815d65c-fd7a-11e5-88c3-45aff8fc37bf.png)

**Comment by bradmac** [comment]
Can you change the error text to "This field cannot be blank. Please enter a page title"
