### ISSUE TITLE
Platform issue with bs335

### ISSUE THREAD

**Issue by mamun4343** [Kademi/kademi-dev#1623]
admin url: http://milton.admin.olhub.com/
Issues:
1.http://milton.io/everyone/dash/    register form not working. 
![untitled](https://cloud.githubusercontent.com/assets/3419573/14372127/7487c5d6-fd5f-11e5-8a99-eb9e1ae558ac.png)

2.We need a new feature, that is, when we are not logged in and try to post anything we see a registerOrlogin form, then after login or register we are getting back to the page which is cool and expected, but we also need to post the comment as well. right now we are just getting back to the current page. 

example front end url : http://milton.io/blogs/brad/implementing-grizzly-in-milton/   

3.After clicking anything which have requiresuser class when not loggedin, in registerOrlogin we fill  or nor ,all the class-holder tags from the page disappear. Plz make sure  we only dissappear the btns with the class.   http://milton.io/everyone/dash/  see here. click any module heading or image when not logged in, we see a  modal. then close the modal without fill up and see. all requiresuser classholder elements/tags/images disappeared.

**Comment by bradmac** [comment]
:+1: 

Note that all of this is standard and should work by default in the bs335 theme.

**Comment by ducdhm** [comment]
#1 Because of a group and folder under root folder of website have same name "everyone". Just change name of group of change name of folder under root folder.

**Comment by ducdhm** [comment]
```
2.We need a new feature, that is, when we are not logged in and try to post anything we see a registerOrlogin form, then after login or register we are getting back to the page which is cool and expected, but we also need to post the comment as well. right now we are just getting back to the current page.

example front end url : http://milton.io/blogs/brad/implementing-grizzly-in-milton/
```
@bradmac I'll create new issue for this feature

**Comment by bradmac** [comment]
@ducdhm if registerOrLogin is a link, then after completing the modal we should go to that link. If its a button then after completing the modal it should re-submit the button click. Similar to what you did with quiz validation.

**Comment by bradmac** [comment]
FYI, I've deleted the folder.

**Comment by ducdhm** [comment]
Ok

**Comment by ducdhm** [comment]
```
2.We need a new feature, that is, when we are not logged in and try to post anything we see a registerOrlogin form, then after login or register we are getting back to the page which is cool and expected, but we also need to post the comment as well. right now we are just getting back to the current page.

example front end url : http://milton.io/blogs/brad/implementing-grizzly-in-milton/

3.After clicking anything which have requiresuser class when not loggedin, in registerOrlogin we fill or nor ,all the class-holder tags from the page disappear. Plz make sure we only dissappear the btns with the class. http://milton.io/everyone/dash/ see here. click any module heading or image when not logged in, we see a modal. then close the modal without fill up and see. all requiresuser classholder elements/tags/images disappeared.
```
New class for these feature is `registerOrLogin`. `requiredsUser` is class which will be hidden if user does not log-in
