### ISSUE TITLE
KCRM not loading

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1626]
There are intermittant times when KCRM does not seem to load the CSS.  When I load KCRM in Chome the page does no seem to full load and omits the CSS.  I then swithed to Firefox and got the same issue where the login screen loaded but without it's CSS.  I opened other websites which seemed to load fine.

I tired firebug but did not see an errors.  This happens often so wondering how I can test this further? 

Chrome:
![image](https://cloud.githubusercontent.com/assets/2201340/14374015/1b4d0726-fd94-11e5-83ff-6845ee9f751c.png)

Firefox:
![image](https://cloud.githubusercontent.com/assets/2201340/14374020/23dfd5e4-fd94-11e5-8cd3-8cb72e6217b4.png)

**Comment by bradmac** [comment]
yep, seen that occasionally too

**Comment by bradmac** [comment]
Was a problem with #parse(..) velocity was caching the template across hosts. I've changed the ThemeAwareResourceLoader to return true for isSourceModified whenever there is no host specified in the template source
