### ISSUE TITLE
Tidy up automation stats

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1633]
Ugly! http://rspca.admin.olhub.com/autoEmails/97863852/

- Do not show labels on the pie graph
- Show max of 6 top items, try to force them into 2 cols so the graph doesnt get pushed too far down

**Comment by tuzzmaniandevil** [comment]
- Do not show labels on the pie graph **Done**

**Comment by tuzzmaniandevil** [comment]
- Show max of 6 top items, try to force them into 2 cols so the graph doesnt get pushed too far down - Can't figure out how to do that.
