### ISSUE TITLE
KCRM: Import contacts mechanism places users in Sales consultants group

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1636]
![image](https://cloud.githubusercontent.com/assets/1945230/14435449/a64e7b78-0020-11e6-8c11-4015dc3c7918.png)

**Comment by bradmac** [comment]
@Uafinder they should be placed in which ever group is configured as the leads group. Can you confirm what the settings are?

**Comment by Uafinder** [comment]
Hmmm... Not sure... Looks like the trouble was because of sales consultant group was selected in the app settings, and leads wasn't.
Should be a validation when importing contacts, not only Sales group, but also on Leads group...
![image](https://cloud.githubusercontent.com/assets/1945230/15920294/68536ebc-2e21-11e6-956f-e34a6288cbd3.png)
![image](https://cloud.githubusercontent.com/assets/1945230/15920337/c8201642-2e21-11e6-9c3d-06c9fa060aed.png)

**Comment by bradmac** [comment]
@tuzzmaniandevil please check the behaviour when there are no options selected. Should use default groups "sales" and "leads", and auto-create groups if required

**Comment by tuzzmaniandevil** [comment]
I've added the functionality so it creates the default groups if nothing is selected
