### ISSUE TITLE
KCRM: When cancelling lead all tasks should be cancelled

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1637]

**Comment by tuzzmaniandevil** [comment]
This already happens. Is that correct?

**Comment by tuzzmaniandevil** [comment]
I tested it locally and it's closing any open tasks linked to the lead when cancelling/closing the lead. @Uafinder Can you retest? If you can reproduce it can you let me know how to do so?

**Comment by bradmac** [comment]
Think this is ok now

**Comment by paddyow** [comment]
This is not resolved.  
I create this lead with 1x task and closed it: http://kcrm.olhub.com/leads/183262316/
The task is still there called closetask  http://kcrm.olhub.com/tasks/

**Comment by tuzzmaniandevil** [comment]
I created a lead, Created a task. Closed the lead and all tasks were closed.
Did the same but cancelled the lead. Same result.

But I noticed the ES index wasn't being updated.
