### ISSUE TITLE
KCRM: Task list disappears 

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1643]
After accepting more than 4 tasks concurrently, the page refreshes and the task list disappears.  The only way to get the list to appear is to manually refresh the page.

![image](https://cloud.githubusercontent.com/assets/2201340/14456431/3a17ea8e-00e8-11e6-86b3-d79814054148.png)

**Comment by anhnt** [comment]
should appear in next release. we've just refactored this leadman app so had some issues
