### ISSUE TITLE
KCRM: Update incoming tasks

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1644]
Add a instant task delete button to incoming tasks.

Add around 120 characters of text taken form the comments field of the enquiry showing the CRM user context of the lead. 

![image](https://cloud.githubusercontent.com/assets/2201340/14456600/0b4cbe86-00e9-11e6-8445-33664efc05e8.png)

**Comment by anhnt** [comment]
this should display last contact request message of lead profile
