### ISSUE TITLE
Automation stats don't make sense

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1648]
For each doughnut, what should each segment add up to? 100%? If so the combined values range from 186 to 200 and something. 

Should these not be a representation of 100%

http://admin.minda.olhub.com/autoEmails/

![image](https://cloud.githubusercontent.com/assets/2201340/14485857/0422f3f0-019d-11e6-9b42-75fbc923ed32.png)

**Comment by bradmac** [comment]
@paddyow can you provide a link?

**Comment by bradmac** [comment]
The numbers are absolute, not percentages
