### ISSUE TITLE
Results page strange content

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#165]
![image](https://cloud.githubusercontent.com/assets/1945230/6176432/870e99bc-b307-11e4-8a38-0cde0f90f6a3.png)

0_o
Start - well it looks to be as it is
End - should be date ,not a amount
Processed date - ?
User name - no such column but data is existed

**Comment by bradmac** [comment]
Fixed. Note this table shows the results for participants, ie the people who have had their results assessed.

**Comment by Uafinder** [comment]
Looks ok
