### ISSUE TITLE
Custom app dev: allow preview with user token (auto login)

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#1650]

**Comment by bradmac** [comment]
@anhnt give me a shout when you start, and we'll go through this together.

But look WebUtils for functions to append auth params to a url. Note that the token is valid only for a specific domain, so the domain used to generate the token must exactly match the domain name used in the URL

**Comment by anhnt** [comment]
To generate login token with given website and profile objects within custom app:

    var domain = formatter.getDomainName(website);
    var loginToken = page.find('/websites/'+website.name).current.getLoginToken(profile);
    var urlWithToken = 'http://' + domain + '/?'+ loginToken;
