### ISSUE TITLE
KCRM: Ability to search on Email

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1651]
Allow user to search on email address.

![image](https://cloud.githubusercontent.com/assets/2201340/14490824/7e9a3b5a-01b8-11e6-97b0-5f33b7ff7b1a.png)

**Comment by tuzzmaniandevil** [comment]
Seems to work with the 'user' part of the email, as soon as I type @ it stops working.

**Comment by bradmac** [comment]
So i guess its currently using the default analyzer, and tokenising

Maybe make it not-analyzed, and use a prefix search? Would also be good to do a suffix search, so can look up by domain name

**Comment by tuzzmaniandevil** [comment]
I've changed email to not_analyzed. and changed the search. Works now :-)
Requires a re-index of leads though.
