### ISSUE TITLE
Reward points AppIndexer

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1652]
We need reward points in elasticsearch to support dashboards and reporting.

This should not be in the profile index (too big) but should contain denormalised profile data including orgs and groups.

Please also create a dynamic component for the dashboard builder displaying a histogram of points earned over time, and a default dashboard widget.

**Comment by tuzzmaniandevil** [comment]
indexer is done, Now on to the widgets :-)

**Comment by tuzzmaniandevil** [comment]
default Dashboard widget done

**Comment by tuzzmaniandevil** [comment]
Component widget moved to a separate issue https://github.com/Kademi/kademi-dev/issues/1670
