### ISSUE TITLE
Reard point debits AppIndexer

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1653]
We need reward point debits (ie redemptions) in elasticsearch to support dashboards and reporting.

This should *not* be in the profile index (too big) but should contain denormalised profile data including orgs and groups.

Should also include data about the product redeemed and the associated points record including the points tag.

Please also create a dynamic component for the dashboard builder displaying a histogram of points earned over time, and a default dashboard widget.

**Comment by tuzzmaniandevil** [comment]
Moved custom dashboard widget to seperate issue
https://github.com/Kademi/kademi-dev/issues/1682
