### ISSUE TITLE
Forms Plugin: Valid email address's fail validation

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#1654]
a Custom just reported that email addresses with an apostrophe wasn't accepted, Also I have noticed that long domains like .fitness also fails.

The plugin needs updating to comply with the correct standard, Look here for details: https://en.wikipedia.org/wiki/Email_address

Notify 3DN when complete.

**Comment by ducdhm** [comment]
@tuzzmaniandevil Can you give me example of error?

**Comment by tuzzmaniandevil** [comment]
![ex1](https://cloud.githubusercontent.com/assets/3378330/14725568/da5eb74a-0870-11e6-967c-ee3b088c5b99.png)
