### ISSUE TITLE
Improve useability of quiz failures when using batches

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1656]
Currently, when a module quiz is configured to use batches, users are not given good visibility of their incorrect results. Instead, the page is reloaded with new questions immediatley.

This leads to frustration, as users think they got them all right.

Instead the process should be:
- display a modal that the quiz was unsuccessfu, how many tries they have remaining
- the user can close the modal to review their quiz answers with errors shown. The quiz is readonly, and cannot be resubmitted in this state
- the user clicks a button to re-attempt the quiz. The quiz is reloaded with new questions, and the user can select answers and submit

Please make this change within bs335 only.

Once complete we can notify Waterco, and suggest upgrading to the new theme.

**Comment by ducdhm** [comment]
Done!
