### ISSUE TITLE
Configurable number of attempts and pass mark for quizes

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#166]
- The quiz editor requires a field to enter the maximum number of attempts users can have.
- Also requires a field to enter a pass mark as a percentage
- After the maximum attempts their mark is recorded and whether they have passed the quiz, and the user continues with the module
- Module progress is **not** to be prevented if the user fails as part of this issue, although that might be added later
- When the module is completed a score is assigned to the learning record which is the average of the percentages of completed quizes
- The module score can be seen on the manage user page, in the new learning records tab

**Comment by Uafinder** [comment]
Looks like no serious bugs here. But need to clarify how is score counted.
For example i have two quiz module. First quiz has 4 attempts and 80 percent. The second has 5 attempts and 20 percent. What is algorithm for score counting here?

**Comment by bradmac** [comment]
The final score should be the average of all final quiz scores. So if a user gets 80% and 20% as their final scores for the 2 quizes, then the module score should be 50%

Note that we expect usually clients who use this feature will probably have a single quiz at the end of the module, although this isnt a requirement.

**Comment by Uafinder** [comment]
Well, if so looks like counting of score works incorrect.
First VW:
![image](https://cloud.githubusercontent.com/assets/1945230/6273967/592d4802-b87c-11e4-9ca3-524985055110.png)
After i complete module it shows me that i've gain 0 score :(
Second is Seat:
http://admin.asmi.olhub.com/websites/asmi-demo/version1/programs/VWAG_1/Seat/Seat1/
It has two quizes with next preferences: First quiz has 4 attempts and 80 percent. The second has 5 attempts and 20 percent. When i successfully complete them both it gives me 66 score.
Why so?
