### ISSUE TITLE
No warning message when want to change website to one which has learning app disabled

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1660]
![image](https://cloud.githubusercontent.com/assets/1945230/14538552/0081bea0-0285-11e6-9f01-a1718ce3ee3c.png)
First site has learning app enabled. Second is not. When you want to change site from first to second it just reloads page and leave you on the first one. Should be a message or some kind.

**Comment by ducdhm** [comment]
New UI:
![aaaaaaa](https://cloud.githubusercontent.com/assets/1289631/15492262/8b020692-21a3-11e6-85f0-9afbcdeead5b.png)

**Comment by bradmac** [comment]
The enabled/disabled logic appears to be reversed.

**Comment by tuzzmaniandevil** [comment]
Sorted
