### ISSUE TITLE
Analitycs page empty and other bugs... Looks like something with funnel

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1661]
![image](https://cloud.githubusercontent.com/assets/1945230/14538793/25abbffe-0286-11e6-85ec-81a897dea216.png)
![image](https://cloud.githubusercontent.com/assets/1945230/14539074/670b9e5a-0287-11e6-938a-551f9b028c44.png)
![image](https://cloud.githubusercontent.com/assets/1945230/14539083/74091600-0287-11e6-9847-18c0d46d333f.png)

**Comment by anhnt** [comment]
you probably need to create funnel.json instead of old xml one. we have recently changed the funnel mechanism

**Comment by bradmac** [comment]
This was reported before the funnel change.

@anhnt can you look at that site and make any necessary updates to have it working. And make sure that if there is a configuration change that @Uafinder knows what that is.

**Comment by anhnt** [comment]
@Uafinder I created funnel.json here http://admin.vladqasand.kademi-sandbox.co/repositories/sales/version1/ which replace old xml one.

Please be noted that creating lead modal has an issue and should work in next sandbox deploy (probably today)

**Comment by anhnt** [comment]
http://vladqasand1.kademi-sandbox.co/analytics/sales it works now
