### ISSUE TITLE
Error when dashboard loading

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1664]
![image](https://cloud.githubusercontent.com/assets/1945230/14541104/fa9025fc-0290-11e6-9724-76a56ee33685.png)
Spot it when going down by token from root to mercedes org

**Comment by bradmac** [comment]
Couldnt reproduce. Can you give me steps to reproduce the error?

**Comment by Uafinder** [comment]
1. http://admin.kademi-sandbox.co/organisations/
2. Choose mercedes -> admin dashboard (from dropdown menu)
3. Page loading, then it gives an error and page reloading.

**Comment by tuzzmaniandevil** [comment]
@Uafinder I can't reproduce this. Can you check again?

**Comment by hoanglinhlan** [comment]
Cant reproduce
