### ISSUE TITLE
Limit for downloading users CSV

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1665]
![image](https://cloud.githubusercontent.com/assets/1945230/14541352/3cc1c448-0292-11e6-9777-5a33ff002cd9.png)
Looks like there is a limit on 500 records while downloading users CSV. Looks like it's a limit for viewing it on the page.

**Comment by tuzzmaniandevil** [comment]
I've removed the limit for CSV

**Comment by Uafinder** [comment]
Now it's on limit of 10!

**Comment by tuzzmaniandevil** [comment]
Whoops, My bad. I forgot the default limit for ElasticSearch is 10, changed it to 10,000
