### ISSUE TITLE
User profiles counting question

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1666]
![image](https://cloud.githubusercontent.com/assets/1945230/14541491/e4a5dd48-0292-11e6-8a1b-5d0107944d0b.png)
Why digits are so different?

**Comment by bradmac** [comment]
The top number is the number of profiles, ie users. The numbers on the right are the numbers of memberships. A profile can have 4 memberships to an org, which will add 4 to the count on the right, but only 1 to the profiles count at the top

**Comment by Uafinder** [comment]
Understood, thanks!
