### ISSUE TITLE
EDM editor question

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1667]
![image](https://cloud.githubusercontent.com/assets/1945230/14541739/16142a14-0294-11e6-9b4c-0a03c6e62410.png)
I think grey area should have some areas to show user where he could drag&drop elements.

**Comment by bradmac** [comment]
The whole area is a drop area.

@ducdhm can we add a partially transparent background telling the user "Drop containers here", like what dropzone does?

**Comment by Uafinder** [comment]
Unfortunately, it's not. I've drag it to most places and it's not dropping.

**Comment by bradmac** [comment]
Items cant be absolutely positioned. They align to the top and then stack down the page. So initially you drop near the top of the page.

Maybe useability could be improved by allowing containers to be dropped anywhere, and then they are placed at the end?

**Comment by Uafinder** [comment]
Yeah, probably it would increase usability.

**Comment by ducdhm** [comment]
New UI:
![22222](https://cloud.githubusercontent.com/assets/1289631/14760712/3def83fc-0975-11e6-829c-12e8a5ce4acc.png)
![33333](https://cloud.githubusercontent.com/assets/1289631/14760713/3e12ccea-0975-11e6-8fa3-66e829435301.png)

**Comment by bradmac** [comment]
:+1:
