### ISSUE TITLE
Integrate admin console with Zopim real time chat

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#167]

**Comment by Uafinder** [comment]
![image](https://cloud.githubusercontent.com/assets/1945230/6256242/290990da-b7bf-11e4-9044-81644cd7a6aa.png)

**Comment by Uafinder** [comment]
Looks ok for now.

**Comment by Uafinder** [comment]
![image](https://cloud.githubusercontent.com/assets/1945230/6274876/484bc4f8-b883-11e4-8793-29ed8c9ab74f.png)

**Comment by bradmac** [comment]
Can you clarify what the problem is?

**Comment by Uafinder** [comment]
This is a floating problem which causes changing a chat label (language) for Zopim chat. I've spot it twice. First time it had disappeared by itself.
The second still there.
![image](https://cloud.githubusercontent.com/assets/1945230/6335583/2baeadae-bba5-11e4-9805-0988d17c9e6d.png)

**Comment by Uafinder** [comment]
Still shows incorrect!

**Comment by bradmac** [comment]
i think that was marked ready to test by accident
