### ISSUE TITLE
Reward Points Activity: Add Component widget for admin dashboard

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#1670]

**Comment by hoanglinhlan** [comment]
component added

**Comment by bradmac** [comment]
Currently this component only works if its used in the same site as the reward store. 

But often it will be used in a reporting site which does not have any reward store.

Please refactor to not require a reward store in the same site.

I suggest changing to use a query or querytable provided by the RewardStoreApp.

**Comment by Uafinder** [comment]
IF this issue dedicated to Points Activity component, so there are some probs...
It's no displaying at all, even on the reward store website
http://version1.vlad20-store.kademi-ci.co/contenteditor?fileName=page2.html&miltonUserUrl=/users/3120a759-575d-4b8e-9b11-11c221a4366f&miltonUserUrlHash=f07dac26-44ea-4ef3-94f8-ef80fa1c0050:pqBz1PudetrWVuY8wiGpsU8cW14
http://version1.vlad20-store.kademi-ci.co/page2.html?miltonUserUrl=/users/3120a759-575d-4b8e-9b11-11c221a4366f&miltonUserUrlHash=7350e3f7-2a3e-4f29-a580-e881946a464a:6miWAuvjgU_GF7NBhTcicCeHTLo
http://vlad-test20.admin.kademi-ci.co/pages/vlad20-store/version1/

**Comment by tuzzmaniandevil** [comment]
@Uafinder The Reporting app is required for that component to work

**Comment by Uafinder** [comment]
I can't see this component outside of reward-store site.
http://version1.vlad23-report.kademi-ci.co/contenteditor?fileName=report.html&miltonUserUrl=/users/2f5ccda6-2de0-4223-a41b-31d380bf3e5c&miltonUserUrlHash=9a820127-62be-4e09-aa4f-b757ea510bae:ujMap5xOdEti53GGBpnribb4s2A
I've enable reporting component, but it doesn't appears.
Is anything else i should know?

**Comment by bradmac** [comment]
@tuzzmaniandevil note that users should not be expected to manually enable dependencies.

So if rewardstore app components only work if the reporting app is enabled, then you should add the reporting app as a dependency so it gets enabled automatically

**Comment by tuzzmaniandevil** [comment]
@Uafinder You need to have the reward store app installed to get the components. i.e. KRewardStore

@bradmac I've added the dependency

**Comment by Uafinder** [comment]
1. No preview when select points bucket
![image](https://user-images.githubusercontent.com/1945230/32225092-9cd139fa-be4c-11e7-8683-51b27d16bf2d.png)

2. Something with timezone
![image](https://user-images.githubusercontent.com/1945230/32225378-a9cdac5a-be4d-11e7-8837-7e5343252a38.png)
![image](https://user-images.githubusercontent.com/1945230/32225417-cc080de2-be4d-11e7-8e3d-eb7bf64d2a58.png)

3. No expired and debit information on graphs
![image](https://user-images.githubusercontent.com/1945230/32225384-b64cd316-be4d-11e7-9345-e75dcf814842.png)

http://version1.vlad26-repo_vlad-test26.kademi-ci.co/123.html?miltonUserUrl=/users/57c381bd-3a46-46a8-8555-5e713e107db8&miltonUserUrlHash=ba084ded-e677-4420-8099-c8c648657e5e:u4M13Ap0Gte3UCLqP3pNJRkr0uc

http://vlad-test26.admin.kademi-ci.co/rewards/points/

**Comment by tuzzmaniandevil** [comment]
3. This checks the "expired" flag on points, Not the reason code on debits. After expiring the points It's now showing results.
![image](https://user-images.githubusercontent.com/3378330/32872116-d63f93d6-cae9-11e7-9920-a7afbb9fad67.png)

**Comment by tuzzmaniandevil** [comment]
1. Fixed - Requires lib update

**Comment by tuzzmaniandevil** [comment]
2. It uses the timezone of your PC/browser, Hence the difference

**Comment by Uafinder** [comment]
Preview is ok

1. Doesn't show outside of store website
For example:
http://version1.vlad58-store_vlad-test58.kademi-ci.co/repo02.html - ok
http://version1.vlad58-repo_vlad-test58.kademi-ci.co/rewstore.html - bad

2. Timezone issue persists:
It's on admin
![image](https://user-images.githubusercontent.com/1945230/33133993-3498a550-cfa7-11e7-96a3-5575a3086819.png)
It's on frontend
![image](https://user-images.githubusercontent.com/1945230/33134140-9deb17e0-cfa7-11e7-8a77-f5efbe647c9d.png)
there is no awarded points on 17 Nov
My local timezone
![image](https://user-images.githubusercontent.com/1945230/33134224-d2e75724-cfa7-11e7-9f29-5f49a074d367.png)
Org timezone
![image](https://user-images.githubusercontent.com/1945230/33134242-e1e22646-cfa7-11e7-9a34-6ff0c8ddd81d.png)

3. Expired points hard to test.

**Comment by bradmac** [comment]
> Expired points hard to test.

@Uafinder do you know you can simulate a time change on the server from the maint page? Note this applies to the entire server.

http://rootorg.admin.kademi-ci.co/maint#utils-tab

![image](https://user-images.githubusercontent.com/826458/33146553-7a154e76-d029-11e7-8c65-0ab222f23a0e.png)

**Comment by Uafinder** [comment]
No, i had not...
Thanks, it will be very useful
Anyway, I just wait for one bug fix and for one day...
Expired points works ok!

So, only 1 and 2 left

**Comment by tuzzmaniandevil** [comment]
@Uafinder Please make sure you update all the libs of a website before testing. Updated the libs and works now

**Comment by bradmac** [comment]
Just to confirm @Uafinder shouldnt need to update libs, the test is to make sure this works with a fresh account.

**Comment by Uafinder** [comment]
1. Report are showing in the editor, but it's empty on the frontend.
![image](https://user-images.githubusercontent.com/1945230/33765997-39cb5606-dc24-11e7-9a77-aac76f3ac2db.png)
![image](https://user-images.githubusercontent.com/1945230/33765999-3f2461ec-dc24-11e7-9a04-58f1e5c8bb1d.png)

2. Dates are still bad
![image](https://user-images.githubusercontent.com/1945230/33766013-4f0bfd9a-dc24-11e7-9bf8-5fb2b849ba6d.png)
![image](https://user-images.githubusercontent.com/1945230/33766023-581cc07c-dc24-11e7-9c7e-561af0d2d1b4.png)
![image](https://user-images.githubusercontent.com/1945230/33766050-724145a4-dc24-11e7-886a-55b9665f29ec.png)

http://vladtest02.admin.kademi-ci.co/points-buckets/points/
http://vladtest02.admin.kademi-ci.co/pages/vlad02repo/version1/
http://version1.vlad02repo-vladtest02.kademi-ci.co/rep2.html

**Comment by bradmac** [comment]
@tuzzmaniandevil looks like nvd3-lib didnt get installed Can you please confirm, and check deps are correct.

**Comment by tuzzmaniandevil** [comment]
All the dependencies look ok, The d3 lib has turned off but the nvd3-lib was on.
@Uafinder Can you please test on a new account? All the libs should be installed correctly

**Comment by Uafinder** [comment]
New account looks good, but it seems still have a problem with time.
So will open another issue to close this one.
https://github.com/Kademi/kademi-dev/issues/4760
