### ISSUE TITLE
Switcing off APPs gives error

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1671]
"Could not change application. Please check your internet connection, and that you have permissions"

http://kademi.admin.olhub.com/manageApps/

When switching off custom Apps like shortUrl and ToDolist the above error appears but still the APP appears to be switched off.

**Comment by tuzzmaniandevil** [comment]
Might be related to #1672. I can't see an error

**Comment by tuzzmaniandevil** [comment]
Tested locally and with the link provided, No error.
