### ISSUE TITLE
APP appearing twice in list

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1672]
http://rspca-sa.admin.olhub.com/manageApps/

Note a custom App is appearing twice in the App page

![image](https://cloud.githubusercontent.com/assets/2201340/14549303/ee6ce9ba-0301-11e6-9506-f85507bc81c6.png)

**Comment by tuzzmaniandevil** [comment]
This is because the app is installed on the parent org (Kademi) and in RSPCA.

**Comment by tuzzmaniandevil** [comment]
Added a check to the RepositoryAppManager, if an app exists and turned on in the parent org, use that app over the locally installed app. if it's turned off on the parent org then use local app.
