### ISSUE TITLE
Manage module screen, edit button for quizes should open the quiz editor in a new screen

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#168]
Currently clicking Edit for a quiz on the manage module page opens a new window with a HTML editor, which is not appropriate for editing quizes

Instead the user should click Edit in Modal to open the quiz editor, but this is not obvious

Clicking the default edit button for  quiz page should open the quiz editor in a new window

**Comment by Uafinder** [comment]
Yeap, looks ok for me!
