### ISSUE TITLE
Calendar Editor has server error unless website is selected

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1681]
http://admin.nest-vc.olhub.com/Calendars/Nest/test#details-tab

![image](https://cloud.githubusercontent.com/assets/2201340/14591212/73825f5e-0550-11e6-94b1-87aa729109e2.png)

**Comment by paddyow** [comment]
If a website is not selected it returns an error.

**Comment by bradmac** [comment]
Need to make calendar mandatory, and display message if not selected

**Comment by tuzzmaniandevil** [comment]
@brad you mean website?

**Comment by bradmac** [comment]
yeah

**Comment by tuzzmaniandevil** [comment]
I've added a warning if no website is selected:
![screenshot from 2016-04-18 12 42 54](https://cloud.githubusercontent.com/assets/3378330/14591324/1d5c6382-0563-11e6-9748-e66c04536f25.png)
