### ISSUE TITLE
Creating group does not close dialogue window 

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1683]
http://admin.minda.olhub.com/groups/
Browser: Firefox
When clicking 'Add' the group is created but the window does not close.

**Comment by ducdhm** [comment]
Fixed in https://github.com/Kademi/kademi-dev/commit/969f3a88275ef36d5fecae6b7d6db181444d4f9b

**Comment by Uafinder** [comment]
Still same (Sandbox)

**Comment by ducdhm** [comment]
@Uafinder It's fixed but not deployed yet!
