### ISSUE TITLE
Can't delete any product

### ISSUE THREAD

**Issue by mamun4343** [Kademi/kademi-dev#1684]
here,
http://admin.emc.olhub.com/products/  

currently products are not deleteable. i see an error when i am trying to delete any. see attachment plz.
![untitled](https://cloud.githubusercontent.com/assets/3419573/14593828/493957ba-0551-11e6-856a-f5e7d2929812.png)

**Comment by mamun4343** [comment]
also contact requests are not delete-able.

**Comment by bradmac** [comment]
It is correct that contact requests are not deletable, but they can be hidden.

Products should be deletable.

**Comment by mamun4343** [comment]
Yep,currently contact requests can be hidden. 
But, products are still not delete able.

**Comment by tuzzmaniandevil** [comment]
Fixed

**Comment by mamun4343** [comment]
@tuzzmaniandevil  still cant delete products. try this.

**Comment by bradmac** [comment]
@mamun4343 just not been deployed yet. The RealMadrid milestone will be closed when its deployed
