### ISSUE TITLE
[URGENT] Can not process KPI data

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#1687]
Step to reproduct:
1. Access `Data series screen`
2. Click on `Process Selected KPI's`
3. Select some KPI data
4. Click on `Start Processing`
5. Nothing happen

**Comment by bradmac** [comment]
Looks like this is a very old bug, since at least Sep 2015.

Mostly use the review KPI's page and i think we should probably remove this button from the manage sales data page.
