### ISSUE TITLE
Email history not showing email sends

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1689]
100 triggers were uploaded here: http://admin.cpaaustralia.olhub.com/autoEmails/40396558/timerTriggers.html

The triggers were getting marked off as being completed

When I go to email history here http://admin.cpaaustralia.olhub.com/emails/
The emails sends were not displaying.  However I did check a few profiles and under the email tab the email was showing as being sent.

I am assuming emails have been sent, if they have not please tell me asap.

**Comment by bradmac** [comment]
Confirmed the email is shown in history when you filter by email address. So i think its just not shown because you're hitting max results. Note there were a lot of emails sent after the one quoted above
