### ISSUE TITLE
Improve manage user screen layout

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#169]
- seperate tabs for key information sets, such as learning, contact requests, points
- first tab to be a summary of key information
- all the functions previously available will still be available, ie change password, change memberships, etc

**Comment by Uafinder** [comment]
1. Is there should be points on the summary tab?
![image](https://cloud.githubusercontent.com/assets/1945230/6235817/f201cf34-b6ed-11e4-8db0-c22276e8d1d5.png)
2. I've placed a contact request right now, but it shows me that i placed it 11 hours ago. When you bring cursor to it, it shows only date.
![image](https://cloud.githubusercontent.com/assets/1945230/6236094/2109241a-b6f0-11e4-97f1-6c18ec505ba3.png)

**Comment by bradmac** [comment]
"Is there should be points on the summary tab?"  - we do want that, but will need to be a seperate task

**Comment by bradmac** [comment]
"I've placed a contact request right now, but it shows me that i placed it 11 hours ago. When you bring cursor to it, it shows only date" - i think that will probably affect any screen that uses the 'time ago' stuff. Can you confirm? If so, could you create a seperate issue which is to correct timezone handling for all timeago screens.

**Comment by Uafinder** [comment]
I don't think so. We have some problems with dates, but it looks like doesn't connected.
Firstly, web activity page correctly shows "time ago" staff. And secondary - those requests which i leave yesterday now show that i leave them 12 hours ago, but new one request shows 11 hours ago. If this was just a timezone trouble - it would show my past requests with "more than 1 day".
![image](https://cloud.githubusercontent.com/assets/1945230/6254090/a2a23322-b7ae-11e4-9ab0-85b65ce4ef25.png)

**Comment by bradmac** [comment]
ok, looks like some sort of bug to do with contact requests
