### ISSUE TITLE
Groups numbers of profiles in a group on the users page does not add up

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1690]
There are 5,156  whch is correct when you go to the Groups page (see dashboard) http://admin.cpaaustralia.olhub.com/groups/

But on the users page http://admin.cpaaustralia.olhub.com/manageUsers/ why does the RG Retention Inside Group has 5072?  Which does not make sense.

![image](https://cloud.githubusercontent.com/assets/2201340/14664468/9effd78c-070e-11e6-9a59-8b5854555070.png)

**Comment by bradmac** [comment]
Re-indexed, and numbers match now
