### ISSUE TITLE
Editing invintation causes tsuch kind of error in content editor

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1695]
![image](https://cloud.githubusercontent.com/assets/1945230/14688298/9caf5b74-074a-11e6-8c34-6be33c57afce.png)

**Comment by ducdhm** [comment]
UI when Calendar App is disabled is:
![test](https://cloud.githubusercontent.com/assets/1289631/15222459/ffb649d4-1899-11e6-9291-9a80aed42894.png)
