### ISSUE TITLE
Minor trigger category bug

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1697]
1. Create a category
2. Move some trigger there
3. Expand the category and watch there is a "no data in table" message appears with recently added trigger. Also 0 triggers counter.
![image](https://cloud.githubusercontent.com/assets/1945230/14688546/c7500468-074b-11e6-8a23-7484c7f87f2c.png)

Also please note for incorrect width of the category table columns
![image](https://cloud.githubusercontent.com/assets/1945230/14688583/fe0dbe14-074b-11e6-836e-2931bc6370ff.png)

**Comment by anhnt** [comment]
all fixed
