### ISSUE TITLE
Email stats 

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1698]
Ignore erroneous emails in db

Please check NA's - http://admin.minda.olhub.com/autoEmails/120044419/

Donut hover stats to show percentages. And if possible show absolute number in brackets as well

Add % sign to percs in panels

day17 - 3, find out why user agent reported as "other"

**Comment by tuzzmaniandevil** [comment]
- day17 - 3, find out why user agent reported as "other" - **The raw user agent for that is "Gmail image proxy"**

**Comment by tuzzmaniandevil** [comment]
- Please check NA's - When I select a wider date range I get data, the date range defaults to the last 7 days. So there is data

**Comment by tuzzmaniandevil** [comment]
- Ignore erroneous emails in db - **Done**

**Comment by tuzzmaniandevil** [comment]
- Add % sign to percs in panels - **Done**

**Comment by tuzzmaniandevil** [comment]
- Donut hover stats to show percentages. And if possible show absolute number in brackets as well - **Done**
