### ISSUE TITLE
Editing webpages with New editor 

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1700]
http://version1.nest.olhub.com/contenteditor?fileName=index.html&miltonUserUrl=/users/patrick-707421&miltonUserUrlHash=96f8eadb-67eb-4c88-a8ce-eeec3ddaf13c:4fSplWzWYhU1E5ttbnZNDTjCrRI

There is no way to save the changes you make to a webpage using the new editor.  Where are the top menu controls?

**Comment by bradmac** [comment]
Control-S will save

Problem is that the site styles are hiding the toolbar buttons. Would be good to make sure the toolbar styles are locked down with !important etc

**Comment by ducdhm** [comment]
@bradmac Yeah. Let me force control styles
