### ISSUE TITLE
weird right arrow 

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#1703]
![weird right arrow](https://cloud.githubusercontent.com/assets/735555/14734789/0c2282ae-0897-11e6-8e06-68191ab74aa0.PNG)
anhcrm.kademi-sandbox.co

**Comment by Uafinder** [comment]
![image](https://cloud.githubusercontent.com/assets/1945230/14831295/c26db498-0bfd-11e6-8bf5-82914fd2e2ef.png)

**Comment by anhnt** [comment]
already fixed
