### ISSUE TITLE
KCRM: Fix funnels

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1708]
http://kcrm.olhub.com/dashboard

Since the platform update KCRM is not usable.

- Get funnels working again - Cold, Warm, Hot, Closed
- Add lost lead reasons again so they appear in the drop down
- Source drop down values needs adding again on the profile page
- Make sure Kademi website is pushing leads through from contact page and get kademi page as per previously

**Comment by bradmac** [comment]
I've integrated this one with the KCRM UI
http://kademi.admin.olhub.com/repositories/agency-sales/version1/texteditor?fileName=funnel.json

**Comment by tuzzmaniandevil** [comment]
Added enterprise-sales:
http://kademi.admin.olhub.com/repositories/enterprise-sales/version1/texteditor?fileName=funnel.json
