### ISSUE TITLE
Dashboard layout breaks when all modules are completed

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#171]
The default dashboard layout breaks when a user has completed all of their modules

**Comment by Uafinder** [comment]
If you mean this one situation - looks ok to me.
![image](https://cloud.githubusercontent.com/assets/1945230/6217535/b6a4b56c-b61d-11e4-9227-ff0eb4b79868.png)

**Comment by bradmac** [comment]
Yep, that appears to be working correctly now.
