### ISSUE TITLE
Versions commit history filter works inproperly

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1714]
![image](https://cloud.githubusercontent.com/assets/1945230/14829836/41bdcc0e-0bf6-11e6-8abe-09af058df3fa.png)
![image](https://cloud.githubusercontent.com/assets/1945230/14829848/52659384-0bf6-11e6-9156-f313ac6e901a.png)
If you choosing any filter it will show incorrect info and count of commits will not change

upd. It look like it doesn't check users org timezone

**Comment by tuzzmaniandevil** [comment]
I've adjusted the search to take the timezone into account.
