### ISSUE TITLE
New automation trigger to add value to a data series

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#172]
We need the ability to configure automation triggers to add a record to a data series, taking the value from the event by applying an expression.

For example, we might want a module complete trigger which inserts the module score into a data series to track module scores, as part of KPI tracking.

**Comment by Uafinder** [comment]
I need an example of MVEL expression here

**Comment by bradmac** [comment]
As an example, for a moduleprogress  COMPLETE event, if we wanted to write the final score (ie pass mark) it would use the finalScorePerc property of the ModuleFolder object:

event.attributes.module.finalScorePerc

**Comment by Uafinder** [comment]
Thanks for an example.
I have no success to write data using this trigger. COuld you check if something configured wrong?
