### ISSUE TITLE
Stream log does not make sense

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1720]
http://admin.minda.olhub.com/

1x profile was uploaded via integration.
The profile was created but there was a stream item that said it was removed?  Not sure why this was logged when the profile was added?

![image](https://cloud.githubusercontent.com/assets/2201340/14874301/18f18390-0d42-11e6-990b-f8f0f4519fb9.png)

**Comment by bradmac** [comment]
Check the text in the event handling code, probably just copy and paste prob

**Comment by bradmac** [comment]
duplicate issue
