### ISSUE TITLE
No stats appearing on automation

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1722]
![screenshot-minda admin olhub com 2016-04-28 15-44-25](https://cloud.githubusercontent.com/assets/826458/14874814/2443c33c-0d58-11e6-9e59-c715861befcc.png)

http://minda.admin.olhub.com/autoEmails/120044923/

**Comment by tuzzmaniandevil** [comment]
![screenshot from 2016-05-03 12 09 41](https://cloud.githubusercontent.com/assets/3378330/14971614/fd612ea2-1127-11e6-8e84-4b770ba7433e.png)

I can see stats

**Comment by bradmac** [comment]
Looks good now
