### ISSUE TITLE
Refactor ControllerMappingList to externalise org and repo context

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1728]
ControllerMappingList should not have a reference to a branch, it should only have a reference to a hash

Then the cache key should only be the hash, and should not include the branch:
https://github.com/Kademi/kademi-server/commit/9c31e1799b1895c4324b8b0d21fc760fbadbab5e

The organisation/website/branch context should come from whatever is using the ControllerMappingList

Once a ControllerMappingList is initialised, perhaps set a flag to make it immutable.

**Comment by bradmac** [comment]
Done more.

**Comment by bradmac** [comment]
@Uafinder this change is to optimise how apps/libs are initialised internally. There should be no impact on users. 

The only difference is that after a server restart each version of an app/lib should only need to be initialised once. Previously they were initialised once for each account which used it.

Typically an app or lib will take 300ms to initialise, so an account which has 20 such apps will take 6 seconds to load the first time its accessed after a server restart.

With this change for accounts which are all using the latest versions (so they all have the same versions) accounts after the first will be initialised faster.

**Comment by Uafinder** [comment]
So far so good
