### ISSUE TITLE
Add a way for users to test DKIM settings on a website

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#173]
Add a button on the Mail Settings tab of a website to allow a user to make sure the details are correct and then send a test email to verify all the details are correct.
Also update http://docs.kademi.co/howtos/devs/setting-up-dkim.html

**Comment by tuzzmaniandevil** [comment]
Just need to do the front-end

**Comment by Uafinder** [comment]
Looks ok to me.
