### ISSUE TITLE
content editor minor bugs!

### ISSUE THREAD

**Issue by mamun4343** [Kademi/kademi-dev#1738]
Please check the attachment to ensure where we need some action,
![untitled](https://cloud.githubusercontent.com/assets/3419573/15005498/2e288296-11e7-11e6-8c4d-3163c8673b67.png)

1.**green marked** - navbar need to be narrower .
2. **red marked** - for a long page when we try to edit anything i have to scroll back to top to get the editor. it will be great if we get that editor just above the editing/selected line or nearby.

**Comment by bradmac** [comment]
1. the editor navbar styles should be locked down with !important or equivalent. 
2. perhaps use an affix style component list, like we did for admin menu?

**Comment by ducdhm** [comment]
We already had an issue like that (but I dont remember). I know how to fix it ;)

**Comment by ducdhm** [comment]
Duplicated with https://github.com/Kademi/kademi-dev/issues/1700
