### ISSUE TITLE
Cannot create new website from courses page

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#174]
Create new account
Go to manage course structure
No courses appear
Only option is to add new website which does not work

**Comment by Uafinder** [comment]
Looks like it's just doesn't detect that website is already existed. I've faced this problem on the existed website here:
![image](https://cloud.githubusercontent.com/assets/1945230/6217722/ad387b9c-b61f-11e4-8602-5eb19f8135d2.png)
![image](https://cloud.githubusercontent.com/assets/1945230/6217728/b66f2ae4-b61f-11e4-9ce0-1cd518a17b6e.png)

**Comment by Uafinder** [comment]
Steps to reproduce this problem on QA:
1. Clear your cache
2. http://admin.sporg01.fuseqa.com go here
3. Press Course Structure. It shows you an empty page and create website button which is not working.
4. Go to websites page and realize that website is already created.
5. http://admin.sporg01.fuseqa.com/websites/wweee/version1/programs/p1/c1/
Go here. This is manual address of one on modules.
6. Then it will works ok. Looks like it writes some cookie file after that to successfully access courses and modules pages.
Hope it helps.

**Comment by Uafinder** [comment]
Looks ok now
