### ISSUE TITLE
Support multiple org types selected for organisations

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1743]
Orgs should be taggable with multiple org types, rather then being limited to just one.

Note that existing customers **must not** be affected.

This should continue to use OrgType as the list of available tags. Create a new class OrgTypeTag which links an orgtype to an org. This new association should be used as well as the existing 1 to many in lookup queries.

**Comment by Uafinder** [comment]
Probably would be correct to remove selected elements, because they are controlling from the upper plus controls.

**Comment by bradmac** [comment]
What do you mean?

**Comment by Uafinder** [comment]
oops, forget to add an image, will add it in a moment

**Comment by Uafinder** [comment]
![image](https://cloud.githubusercontent.com/assets/1945230/15885530/71448856-2d60-11e6-9620-2ab8d84aa674.png)
Probably the second option can be removed

**Comment by bradmac** [comment]
:+1:
