### ISSUE TITLE
Blog Article: New content editor breaks existing blogs

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#1746]
You can't edit blogs that were created prior to the new content editor being implemented.

Please add an option to choose which editor to use, the new KEditor or the original CKEditor.

**Comment by bradmac** [comment]
The editor is only used for bs335 sites. But i'm thinking we implement a bs336 theme and then limit the content editor to only that instead

**Comment by tuzzmaniandevil** [comment]
That will be good, I have 2 websites that use the bs335 theme and have blogs. Tuzza Travel is one of them :-/
