### ISSUE TITLE
Blog Article: New content editor breaks when using admin on HTTPS

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#1747]
The content editor won't load when using the admin over https as the content editor loads from a http

**Comment by ducdhm** [comment]
It's backend issue. `?contenteditor` in ManageModulePage.java does not redirect to https if we're using https

**Comment by bradmac** [comment]
but we dont use ManageModulePage for blogs...

**Comment by bradmac** [comment]
@tuzzmaniandevil can you do this one? Just need to make sure redirects use secure if the current page is, so this is a java issue, not js

**Comment by tuzzmaniandevil** [comment]
I tried it, Sadly we don't support HTTPS for versioned websites like https://version1.test.loopbackdns.com
Any suggestions?

**Comment by tuzzmaniandevil** [comment]
All fixed :-)
