### ISSUE TITLE
API to check if user with given email already in group

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#1749]
https://github.com/Kademi/client-emc-eventsapp/issues/7

https://github.com/Kademi/kademi-server/commit/99ae5cad8709b62d784b1d192b7b8b891a9a1e31

**Comment by bradmac** [comment]
@anhnt can you change it to make it more useful. Instead of returning a boolean, return an object representing the membership if it exists, otherwise null.

Use MembershipBean as the object
