### ISSUE TITLE
Visual bug on Review KPI page

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1762]
![image](https://cloud.githubusercontent.com/assets/1945230/15159561/ebf13550-16fd-11e6-8662-396c62bb53f5.png)
Strange checkbox, not sure what should be there

**Comment by bradmac** [comment]
Thats a KPI period. But i think we should enhance the page to indicate months so that is more obvious. And possibly make the table wider (with horizontal scroll) so the kpi period checkbox can be wider

**Comment by bradmac** [comment]
BTW, the KPI period is set to 1 day. This is NOT realistic so we dont need to cater for that. The shortest KPI period we need to worry about is 1 week.
