### ISSUE TITLE
waterco-hydrooxypure issues

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1770]
1. Drop down on the dashboard is bad. It covers some part of header (IE)
![image](https://cloud.githubusercontent.com/assets/1945230/15192768/4f0f32f2-17c3-11e6-96e8-e432eeee0106.png)

2. Email of dealer is the same color as a whole selection so it's not visible...
![image](https://cloud.githubusercontent.com/assets/1945230/15193478/c4645110-17c6-11e6-9b49-d8b8901450f3.png)

3. Org markings don't remove while you chage org from one to another
![image](https://cloud.githubusercontent.com/assets/1945230/15193638/91997c8c-17c7-11e6-9dac-efa7c1b0b17b.png)

4. When radio button "Ask waterco" is selected then receive "validation error"
![image](https://cloud.githubusercontent.com/assets/1945230/15193671/ce81250a-17c7-11e6-9482-07697194097f.png)

5. Waterco NZ is showing on Africa :) Also such as some other orgs
![image](https://cloud.githubusercontent.com/assets/1945230/15193707/f57cda8c-17c7-11e6-80cd-147094990ede.png)

6. I can't check if there is serial number saved anywhere after administrator check it and update if needed. Is there any custom field? If so - where it is?

**Comment by ducdhm** [comment]
Move to here https://github.com/Kademi/client-waterco/issues/16
