### ISSUE TITLE
CSV Import/Export of calendar events

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1776]

**Comment by bradmac** [comment]
Please use the new importer framework

**Comment by hoanglinhlan** [comment]
hey @gonzalon 
why is it "import product"? lol
![image](https://user-images.githubusercontent.com/20508726/27815292-3355bf2a-60ad-11e7-8c86-4141e47a5cb0.png)

**Comment by gonzalon** [comment]
@hoanglinhlan copy & paste :rofl: updated now

**Comment by hoanglinhlan** [comment]
hi @gonzalon 
I have an excel file with base fields 
![image](https://user-images.githubusercontent.com/20508726/27855308-35f23e38-6194-11e7-9dca-5d01f3912ed2.png)

but when I uploaded it, some cell is not showing value 
![image](https://user-images.githubusercontent.com/20508726/27855336-5308b614-6194-11e7-9093-af1a16347238.png)

[events.xlsx](https://github.com/Kademi/kademi-dev/files/1123919/events.xlsx)

**Comment by AlaaKhalaf94** [comment]
passed
