### ISSUE TITLE
cannot edit calendar summary

### ISSUE THREAD

**Issue by mamun4343** [Kademi/kademi-dev#1789]
http://metta.admin.olhub.com/Calendars/matta-events/nest-introduces-hsbc-s-institutional-investors-to-artificial-intelligence-and-ai-focused-startups

here calendar content is not editable.

**Comment by bradmac** [comment]
the themeHeader macro in the customised masterTemplate was missing the $bodyContent callback which renders template dependencies. That meant the contentEditor page was missing its required js files. Added the bodyContent as below

```
<!-- Scripts -->
<script src="/theme/assets/js/plugins.js" type="text/javascript">//</script>
<script src="/theme/assets/js/slides.js" type="text/javascript">//</script>

$!bodyContent
```
