### ISSUE TITLE
Duplicate values shown for lead source, etc

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1792]
https://github.com/Kademi/Infiniti/issues/54

**Comment by bradmac** [comment]
Currently, jquery.funnel.js is displaying aggregation values in the list for each stage:
```
name_set.forEach(function (value) {
    ...
    $('#funnelStages').append(svgElem);
```

There should only be a single set of values from across the whole funnel displayed

**Comment by anhnt** [comment]
also fixed the bug that doesnt reload funnel and graph when new lead created
