### ISSUE TITLE
Reseting module progress causes some problems

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#183]
1. Steps to reproduce:
   -start and finish a module with quiz
   -reset module progress
   -start a module progress and pass all pages to quiz
   -quiz answers are already set up
2.  Steps to reproduce:
   -start and finish a module with quiz
   -check what score you've gain
   -reset module progress
   -start and finish a module again with other quiz pass results
   -check score - it will be the same which was on previous attempt.

**Comment by bradmac** [comment]
"quiz answers are already set up" - that is ok, in my opinion. There is nothing wrong with showing a user what their previous answers were.

**Comment by bradmac** [comment]
"-start and finish a module again with other quiz pass results
-check score - it will be the same which was on previous attempt."

That is a problem
