### ISSUE TITLE
Add name attribute to KPI Levels

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#184]
A KPI is an aggregated measure of a data series, eg "sum of annual vehicle RRP values"

KPI's have levels to categories performance. Eg for sales over $5mil, over 10mil and over 15mil per annum, and rewards will often be driven by the achieved level.

Its often useful to refer to levels by name. For example Bronze=$5mil, Silver=$10m and Gold=$15m. These names should include a code (used by templates etc) and a user friendly name

So for this task we need to
- add a name attribute to levels
- add a title attribute to levels
- extend the KPI API to allow selection of levels by name, and make the name and title available as properties

**Comment by tuzzmaniandevil** [comment]
Ready for Init Test
Still need to add some validation to import CSV

**Comment by Uafinder** [comment]
Yeap, it looks  ok to me
