### ISSUE TITLE
IE8&9 issue

### ISSUE THREAD

**Issue by mamun4343** [Kademi/kademi-dev#1840]
http://www.idhealtheducation.edu.au/professionals/signup

after submit button user is added/registered successfully in backend. But,no success message showing or there is no redirection in IE8 & IE9

**Comment by mamun4343** [comment]
@Uafinder  could you confirm that this is universal or not.

**Comment by bradmac** [comment]
Looks like this problem:
http://blog.degree.no/2012/09/jquery-json-ie8ie9-treats-response-as-downloadable-file/

**Comment by bradmac** [comment]
FYI: http://www.useragentstring.com/pages/Internet%20Explorer/

**Comment by bradmac** [comment]
Should be fixed, but need to test with browserstack after next deploy
