### ISSUE TITLE
Refactor last contact date on lead profiles page

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1848]
Need to make this more efficient. Currently its pulling back all of the email items and then selecting the most recent. Perhaps we store the last contact date on the profile in ES?

```
                                            #if($page.getLastContactDate($p.fields.userName.value))
                                            #set($cd = $page.getLastContactDate($p.fields.userName.value))
                                            <small class="pull-right">Last contact: <abbr class="timeago" title="$formatter.formatDateISO8601($cd, $page.organisation.timezone)">$formatter.formatDateISO8601($cd, $page.organisation.timezone)</abbr></small>
                                            #end
```

**Comment by bradmac** [comment]
We need to use this in a couple of places. Eg
- unsubs page
- lead profiles page
- automation timers (without timers)

So would be good to find some way of doing this efficiently. Possibly ideas..
- add a column to Profile
- create a new table that links to profile
- create a query that looks up last contact efficiently for a set of profiles (eg use max to get the ID)
- store in elasticsearch

**Comment by tuzzmaniandevil** [comment]
We already have EmailItem in ES, if we just add SMS we can use ES as is, because both are child indexers of profile.

**Comment by hoanglinhlan** [comment]
passed
