### ISSUE TITLE
Carousel component for contentEditor

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#1863]
Have a component which displays an image carousel. The user should be able to upload and select images through the component.

**Comment by anhnt** [comment]
![image](https://cloud.githubusercontent.com/assets/735555/17239056/510ffe3c-558b-11e6-955d-b9223fd98896.png)

**Comment by hoanglinhlan** [comment]
1.> I can't change order image
2.> when select image, user want to view full img. Must show full img, remove scrollbar 
![carousel](https://cloud.githubusercontent.com/assets/20508726/17320545/4ec5a9fc-58be-11e6-9430-89f80d995c59.png)

**Comment by anhnt** [comment]
> 2.> when select image, user want to view full img. Must show full img, remove scrollbar 
this one was fixed :)

**Comment by ducdhm** [comment]
> > 2.> when select image, user want to view full img. Must show full img, remove scrollbar 
> this one was fixed :)
I think we just need a button for toogle the Fit or Full size of image

**Comment by hoanglinhlan** [comment]
1. Cant delete image
2. Duplicate component: Click back/next of second component ==> 
*Expect*: the second component change image
*Acutal*: the first component change image.

**Comment by hoanglinhlan** [comment]
3. Add image and upload img in any folder, then save component. Img cant saved in child folder, it saved in root folder

**Comment by bradmac** [comment]
:+1: yep, we need the image saved in the same location as the content. This applies to calendars, blogs, etc, as well as regular file system pages.

**Comment by hoanglinhlan** [comment]
confirm worked
