### ISSUE TITLE
Email history not showing in profile 

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1865]
Go here: http://admin.cpaaustralia.olhub.com/emails/
Copy a recent email address sent the subject (I just have one thing to say…)
Search for the email under Users and note that the email history is not showing in the profile

Note these profiles are created via integration scripts

**Comment by bradmac** [comment]
same email address, different profiles

http://cpaaustralia.admin.olhub.com/manageUsers/168910947
http://cpaaustralia.admin.olhub.com/manageUsers/168910959
