### ISSUE TITLE
Clicking on the (To) email icon should populate email address

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1882]
When the email client opens the To field should have the leads email address
The BCC should have the KCRM email

![image](https://cloud.githubusercontent.com/assets/2201340/15626299/205ad9f8-2505-11e6-9de2-ecfda7110d59.png)

**Comment by bradmac** [comment]
Now sets the to address to the lead, and adds a bcc address to capture it in kcrm
