### ISSUE TITLE
Improve google map component

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1884]
Users should be able to search for a location by entering the address, rather then using embed code.

Although, it would be good to have embed code as an option

**Comment by anhnt** [comment]
![image](https://cloud.githubusercontent.com/assets/735555/17269334/a967b9b4-566f-11e6-9a82-6430362b81c8.png)

**Comment by hoanglinhlan** [comment]
1.  select Manual radio, should keep default map (actual: don't show anything)
2. curently, default ratio is 16:9, so pls high light "16:9" button when the first time open setting tab. 
3. select any ratio button, then hide setting tab, then reopen setting tab, ratio button selected not high light

**Comment by hoanglinhlan** [comment]
4. At the first time open setting, select manual ( do not input anything), then hide setting tab, then reopen this, mapAddress textbox has embed code ==> should keep blank value

**Comment by anhnt** [comment]
all fixed :-)

**Comment by hoanglinhlan** [comment]
confirm fixed ok
