### ISSUE TITLE
Completing a task workflow

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1885]
http://kcrm.olhub.com/leads/155279483/

When clicking on the tick button to complete a task:
![image](https://cloud.githubusercontent.com/assets/2201340/15626339/00b2ea04-2506-11e6-8022-d7dccf764dcf.png)

The user gets the edit task dialogue. It should open immediately as the What happened workflow so they can complete the task.

![image](https://cloud.githubusercontent.com/assets/2201340/15626343/2dafdcb0-2506-11e6-8f97-4a4a202d5996.png)

**Comment by bradmac** [comment]
I'm not sure. Its good to be able to edit or complete the task, and seems unnecessary to have an extra button

**Comment by paddyow** [comment]
There is no extra buttton, I want to remove one from the workflow.  The tick button to me represents completing a task, but it opens the edit window which I then have to click another button to complete the task.  Too many clicks to complete the task.  

The tick button should not open the edit window, it should open the task complete button.

**Comment by bradmac** [comment]
I think its correct as it is. The user does need to be able to edit the task, or to complete it.

**Comment by bradmac** [comment]
Or we have 2 buttons
- Edit
- Complete

But just seems a bit unnecessary to have 2 buttons

**Comment by paddyow** [comment]
The workflow to me feels wrong and confusing in that it displays the wrong info.  This is what I think it should do when you click the tick.

![image](https://cloud.githubusercontent.com/assets/2201340/15917203/d52cb662-2e3d-11e6-84c1-19a213a36bd0.png)

**Comment by bradmac** [comment]
Sure, we can have 3 buttons if you like.
