### ISSUE TITLE
Task completion and conversion rate not showing progress

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1886]
![image](https://cloud.githubusercontent.com/assets/2201340/15626352/73deb6b6-2506-11e6-82af-b20304d49168.png)

http://kcrm.olhub.com/dashboard

**Comment by tuzzmaniandevil** [comment]
One reason is it will only show stats for the last 30 Days. This restriction can be removed or a date selector can be added.
@bradmac thoughts?

**Comment by bradmac** [comment]
Lets make it for the current calendar year for now. Pat might need to make some design suggestions on a date control

**Comment by tuzzmaniandevil** [comment]
Ok done.

**Comment by hoanglinhlan** [comment]
Passed
