### ISSUE TITLE
Social sharing links component for edmEditor

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1894]
See http://kb.mailchimp.com/campaigns/content-blocks/use-social-share-content-blocks

**Comment by ducdhm** [comment]
Do simplest solution:
 * Enable/disable options for Facebook, Google+, Twitter, Instagram
 * Show text or not
 * Link for each social network

**Comment by ducdhm** [comment]
I found a free collection of social icons
![vector-free-social-media-icons](https://cloud.githubusercontent.com/assets/1289631/15743390/40631b32-28ef-11e6-8e9b-003a31f397ab.jpg)

**Comment by ducdhm** [comment]
We're better than MailChimp :dancer: 

![untitled-1](https://cloud.githubusercontent.com/assets/1289631/15798830/3edb05f8-2a71-11e6-85d5-97ec378e9733.png)

**Comment by bradmac** [comment]
:+1: 
whoop!!
