### ISSUE TITLE
KPI's to be associated with a list of groups they get applied to

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#190]
Often a data series will have data which is relevant to different groups, and those different groups will be assessed with different metrics against the same data.

For example, a data series of vehicle sales might include both new and used vehicles, and new car salespeople are assessed against the dollar value of the sales while used car salespeople are assessed against the number of vehicles sold.

So for this issue
- remove the requirement for a data series to be associated with a group
- allow KPI's to be associated with multiple groups
- only KPI's that a user is linked to should be reported on their KPI's page

**Comment by Uafinder** [comment]
So for this issue
- remove the requirement for a data series to be associated with a group
- allow KPI's to be associated with multiple groups

Works OK!

- only KPI's that a user is linked to should be reported on their KPI's page
Where is it that page?
