### ISSUE TITLE
Create user enhancements for admin

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1901]
- Add a button to the menu, accessible from any page
- Allow either selecting an existing organisation or creating a new one, similar to kcrm

**Comment by gonzalon** [comment]
This should be in the top nav?
What's kcrm?

**Comment by bradmac** [comment]
Looks like its not quite integrated correctly

This is what i see on the manage users page:
![image](https://cloud.githubusercontent.com/assets/826458/25509230/c29cf636-2bfa-11e7-9c48-f1ce7933bb68.png)

And this is what i see on the dashboard:
![image](https://cloud.githubusercontent.com/assets/826458/25509237/d6f87a42-2bfa-11e7-89b6-b8273d513bb4.png)

**Comment by hoanglinhlan** [comment]
passed
