### ISSUE TITLE
Comments: Allow Anon users to specify a name, email and maybe custom fields

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#1904]
This is so users can comment but can also provide their email and/or name

Not sure if this should create a profile or just add columns to the Comment class

**Comment by tuzzmaniandevil** [comment]
@bradmac Thooughts?

**Comment by bradmac** [comment]
Yep. I think we can create a profile if a matching one exists (based on email), or link to an existing one (but do not update ).

But do not login the user, as that could gain them access to someone else's profile. So should behave much like a contact form in terms of attaching to a profile without granting access to it.

Should also raise a ProfileActiveEvent
