### ISSUE TITLE
Last user visit get's reset if server restarts

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#1907]
If we do a production update or restart our servers we lose the last time a user logged in which can cause issues if a user is being awarded points for logging in.

Contact Sophie at Merc/Tribe once fixed

**Comment by bradmac** [comment]
I think the best way to do this is:
- create a new AppIndexer called UserVisitAppIndexer, part of the UsersApp
- this should create a record when the UserVisitEvent is fired
- retain the current in memory time check as a performance optimisation
- if the in-memory time check passes, then check the index for the datetime of the last uservisit. If at least 24 hours have passed then fire the event and record a new uservisit doc
- the uservisit  indexer does not need to be re-indexable
