### ISSUE TITLE
EDM Editor: Layout breaks in Outlook

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#1908]
Here is the EDM:
http://tuzzatravel.admin.olhub.com/groupEmails/176174585/#messages-tab

The Email Item:
http://tuzzatravel.admin.olhub.com/emails/176214599

Screenshots:
![screenshot 1](https://cloud.githubusercontent.com/assets/3378330/15665519/a628ad42-275f-11e6-8394-ba3a3ac946c0.png)

![screenshot 2](https://cloud.githubusercontent.com/assets/3378330/15665520/a8bd5bde-275f-11e6-9960-146c66798b7e.png)

![screenshot 3](https://cloud.githubusercontent.com/assets/3378330/15665526/abf63f5a-275f-11e6-8617-025b0bf79bd5.png)

**Comment by bradmac** [comment]
:+1:

**Comment by ducdhm** [comment]
To fixed padding in td: http://stackoverflow.com/questions/21474239/css-padding-is-not-working-in-outlook

**Comment by ducdhm** [comment]
To do for fixing image issue:
- Change from % to px for column
- Change width of image from 100% to px based on column wrapper

**Comment by ducdhm** [comment]
@tuzzmaniandevil You should re-do your EDM again
