### ISSUE TITLE
Mailing lists should have custom fields

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1913]
I want to send out some emails to a group
To do this the option mailing list seems the right option to choose as it's just an email blast
I also need to include some custom fields in the email body from data I import like an ask amount
Currently the mailing list option does not support custom fields

**Comment by bradmac** [comment]
Just use a subscription group. Thats intended for supplementary groups (ie not primary) but with additional fields

A mailing list group is intended for groups where a profile can simply be added or removed, without additional data
