### ISSUE TITLE
Data importer issue

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1914]
I uploaded a CSV with 3 records.  The were all unique except for the mobile numbers which were the same.  When the importer finished it added 1 and updated 2 so guessing it updated the profiles based on the mobile being the same which doesn't not seem right. 

Should the importer ask which field to ID on?

[Data.zip](https://github.com/Kademi/kademi-dev/files/292428/Data.zip)

**Comment by bradmac** [comment]
Kademi uses the email as a unique identifier. If there is no email then it will look for a phone number to key on.

We do not support multiple profiles with the same email address
