### ISSUE TITLE
Cannot load calendar content

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1918]
http://admin.metta.olhub.com/Calendars/metta-events/test-2

Create calendar event content is not loading:
Not Found
The requested URL /Calendars/metta-events/test-2 was not found on this server.

Why is this?  The website was selected...

**Comment by bradmac** [comment]
Its because the metta website has the domain name of metta.co, but Metta have directed the A records to another server, so that page is not being served by Kademi

To resolve, we can remove the metta.co domain name, BUT that will invalidate any emails sent through Kademi from that domain
