### ISSUE TITLE
group duplicates in users manager page

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#1920]
![group](https://cloud.githubusercontent.com/assets/735555/15699143/0043a95e-27f5-11e6-998b-02eba8653151.PNG)
http://admin.mercedes.olhub.com/manageUsers/?q=Paige+Hilder&g

**Comment by ducdhm** [comment]
It's not duplicated. If you show the org of each Group, you'll notice that they're not duplicated

**Comment by bradmac** [comment]
But we should probably avoid listing the same group multiple times
