### ISSUE TITLE
TImezone does not apply to scheduled email

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1928]
http://admin.ccqld.olhub.com/scheduledEmails/cevercontacts-data/#configuration-tab

After the Org timezone has been added the text to say when the scheduled email will next fire seems to be correct:

![image](https://cloud.githubusercontent.com/assets/2201340/15763206/ac526e94-2965-11e6-8a24-10b4efbc0b71.png)

The hour of day to run is still working of NZ time:

![image](https://cloud.githubusercontent.com/assets/2201340/15763217/bcaec102-2965-11e6-97dd-2bb104f95d9c.png)

**Comment by paddyow** [comment]
@bradmac we are still having to offset by two hours to account for NZ time.

![image](https://cloud.githubusercontent.com/assets/2201340/17762188/817f7ec8-6551-11e6-858b-1ca791005eae.png)

**Comment by tuzzmaniandevil** [comment]
Timezone wasn't being applied when calculating the nextRun date

**Comment by hoanglinhlan** [comment]
Passed
