### ISSUE TITLE
Password reset label

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1929]
http://kademi.admin.olhub.com/manageUsers/38715238/#general-tab

When you manually reset the password the label does no update:
![image](https://cloud.githubusercontent.com/assets/2201340/15764977/1850f6f8-2973-11e6-869b-fcb2aa00d99a.png)

**Comment by mamun4343** [comment]
still showing the old date. either remove the date and time or update it. not even updaing time and date after a page reload. seems like that time is static.

**Comment by ducdhm** [comment]
It's not deployed yet. Should check on your local!

**Comment by mamun4343** [comment]
@ducdhm its cool in sandbox, need a deploy
