### ISSUE TITLE
DatabaseUpdateStep: Clear the session after 100 changes to DB

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#1931]

**Comment by tuzzmaniandevil** [comment]
@bradmac Could you give me a hand with this please?

**Comment by bradmac** [comment]
Looks like you've got the right idea. I dont know if you can do session.refresh(org), or if you need to get it again with session.get(id).

You might also need to sort out Pipeline.website, but not sure.

That should be all there is to it. 

Any other pipeline steps which hold references to hibernate objects will break, but thats just a fact of life and scripts need to be written with that in mind. DatabaseTableProvider implementations do not hold references to objects, i think.
