### ISSUE TITLE
Group page minor bugs

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1937]
Invintation text is not full in textboxes of the opt-in list
![image](https://cloud.githubusercontent.com/assets/1945230/15806455/5773394c-2b4c-11e6-8a05-c69acf22b00a.png)

Password policy condition is long causes string wrap, but grey background are placed only on the first string.

**Comment by mamun4343** [comment]
this issue still exist!

**Comment by Uafinder** [comment]
Password policy - ok!
Opt-in...
Select all groups checkbox? And that's all?
![image](https://cloud.githubusercontent.com/assets/1945230/16466339/62f5fc0c-3e4b-11e6-9071-284b185a9fbe.png)

**Comment by anhnt** [comment]
@Uafinder please check this issue for detail https://github.com/Kademi/kademi-dev/issues/1959
We just show groups which are mailing list type for optins

**Comment by Uafinder** [comment]
Understood, thanks
