### ISSUE TITLE
Unsubscribers page causes malfunction for other links of the left panel

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1942]
![image](https://cloud.githubusercontent.com/assets/1945230/15806651/c96da326-2b50-11e6-99c7-c34fa2274126.png)

1. go to the unsubscibers page
2. try to open some other block (manage content, data, e.t.c)

**Comment by tuzzmaniandevil** [comment]
Works ok with me. Please clear your cache and try again :-)

**Comment by bradmac** [comment]
Confirmed it happens here:
http://vlad.admin.olhub.com/unsubscribes/

**Comment by bradmac** [comment]
Error in page output:
Invocation of method 'getGroupSummary' in  class io.milton.cloud.server.apps.admin.ManageUnsubscribesFolder threw exception org.hibernate.exception.SQLGrammarException: could not extract ResultSet

**Comment by bradmac** [comment]
I think the problem occurs where there are no unsubs

**Comment by mamun4343** [comment]
@bradmac  yeah, this problem occurs where there are no unsubs
