### ISSUE TITLE
Group access to website adding weird visualisation

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#1944]
![image](https://cloud.githubusercontent.com/assets/1945230/15806795/7c5190d0-2b54-11e6-93b5-946dffc57951.png)

For example, i have 8 group which should have access to site.
i m opening add/remove groups and checking checkboxes. Then closing this pop-up and see that there are only 6 groups added, but when i m opening add/remove groups there all 8 groups are selected. After page refreshing everything looks fine...

**Comment by bradmac** [comment]
I think we should refactor this feature. Just have an Add button to add a group, and the groups have an X on them to remove. Same as adding/removing groups on profiles

**Comment by anhnt** [comment]
It will look like following
![image](https://cloud.githubusercontent.com/assets/735555/16445038/0e26b940-3e0b-11e6-9f1c-9d75765fff87.png)
