### ISSUE TITLE
Allow a user to specify a MVEL expression to assign points using Automation

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#195]
This will allow a user to user an expression instead of a fixed value to assign reward points.

**Comment by Uafinder** [comment]
Is it here?
![image](https://cloud.githubusercontent.com/assets/1945230/6356074/9856edd6-bc63-11e4-9baf-d0b1d5378bf5.png)

Could you give me an example of MVEL expression for awarding points?

**Comment by bradmac** [comment]
Yes, thats right, in the expression field

**Comment by bradmac** [comment]
Wesley, can you give @Uafinder the expression you're using as an example?

**Comment by tuzzmaniandevil** [comment]
a = 10;
if(formatter.now < formatter.newDate(2015,2,26)){
a = 2500;
}
a;

**Comment by tuzzmaniandevil** [comment]
@Uafinder  That should do it :-)

**Comment by Uafinder** [comment]
Thanks for the example. look ok for me
