### ISSUE TITLE
Delete contact function

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1950]
http://kcrm.olhub.com/custs/

Add a checkbox to the end of each lead row
Add a button to delete all checked leads.  Button name = Delete leads
Have a dialogue open saying: Are you sure you want to delete X selected leads

Buttons in dialogue 
Exit - Closes the dialogue without any action
Delete leads - Deleted the leads

Can there be a deleted leads list?

**Comment by bradmac** [comment]
Note that this page **does not show leads**, it shows contacts. A contact may be associated with zero or more leads.

**Comment by bradmac** [comment]
@paddyow can you confirm that you want this function to delete the **contact**, and all leads related to that contact profile?

**Comment by paddyow** [comment]
The thinking is any given account might have contacts that are no longer needed or spam, so having a tool to remove these helps.  Right now Kademi's CRM has so many contacts that are not needed and need cleaning up.

What if we have:

Select contacts you want to delete
Click delete 
Dialogue popups up with message:  Are you sure you want to delete X contacts?
Then an optional tick box "Delete all leads associated with the selected contacts"

**Comment by bradmac** [comment]
Deleting contacts has to delete any associated leads.

**Comment by paddyow** [comment]
Ok then let's do this:

- Select contacts you want to delete by ticking check boxes on each row
- Click delete button at top of page
- Dialogue popups up with message: Are you sure you want to delete X contacts and all the leads associated with each contact?

**Comment by bradmac** [comment]
:+1:

**Comment by tuzzmaniandevil** [comment]
What would also be good is to restrict this to a certain role. Like the User Administrator role

**Comment by hoanglinhlan** [comment]
passed
