### ISSUE TITLE
No field validation on the Add Lead Dialogue

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1954]
![image](https://cloud.githubusercontent.com/assets/2201340/15857947/6fdf97b2-2d01-11e6-8734-48a1d1621df5.png)

Need to validate minimal fields before a lead can be added including:
- Stage
- First Name

**Comment by bradmac** [comment]
I dont agree with first name. There are plenty of situations where you would only have an email address, or only a phone number, etc

And maybe its best to just have the stage defaulted to the initial stage to minimise clicks

**Comment by bradmac** [comment]
Sp please make stage default to the initial stage
