### ISSUE TITLE
Adding tags to KCRM

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1955]
Thinking we should add tags to leads so end users can segment and filter on their own tagging system.  This seems to be the norm for most CRMs.

Thoughts?

**Comment by bradmac** [comment]
:+1: should be basically the same as for manage profile page. We should also be able to create tags (ie groups with type=tag) on the fly

**Comment by tuzzmaniandevil** [comment]
@anhnt can you fix the styling for this please?

It's completely functional.

**Comment by hoanglinhlan** [comment]
passed
