### ISSUE TITLE
Sort groups alphabetially on manage product page when showing list of groups for related item

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1958]

**Comment by gonzalon** [comment]
@bradmac this is in /products/:id/ or somewhere else? I can't seem to find it

**Comment by bradmac** [comment]
This is just for the groups combo:

![image](https://cloud.githubusercontent.com/assets/826458/25412371/938f8232-2a65-11e7-8e37-a2a8035f6f39.png)

**Comment by hoanglinhlan** [comment]
hi @gonzalon 
list group still not alphabetially and it's showing some empty row 
http://lan-test.admin.kademi.com.au/products/samsung01/#panel_details-tab
![image](https://cloud.githubusercontent.com/assets/20508726/25519779/65318b82-2c23-11e7-884f-0813ee174b35.png)

**Comment by gonzalon** [comment]
hey @hoanglinhlan sorry my bad, I mixed up and sort the wrong combo.
Regarding the blank spaces you see is because the "Title" property of the group is empty.
Should be working fine now.

**Comment by hoanglinhlan** [comment]
work fine now
