### ISSUE TITLE
additional info for groups is not opening. 

### ISSUE THREAD

**Issue by mamun4343** [Kademi/kademi-dev#1960]
see here. http://metta.admin.olhub.com/groups/

upd by Uafinder:
Just the last one group additional info is showing.
Also,

when you opening a category of groups, it opening a list of group with the first group already showed addtional info

![image](https://cloud.githubusercontent.com/assets/1945230/15887895/6d1f2134-2d6d-11e6-9a96-c638bed25d5c.png)

And it can't be collapsed

**Comment by mamun4343** [comment]
also, groups are not movable.

**Comment by Uafinder** [comment]
It happens when you does something with groups, like create a group, or delete a folder. After hard page refresh this bug is gone.

**Comment by anhnt** [comment]
all fixed
