### ISSUE TITLE
Manage organisations map

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1962]
New screen to show organisations on a map, and to allow searching

**Comment by bradmac** [comment]
@ducdhm can you please update the orgFinder plugin, and add features to the new map page
- allow searching by multiple organisation types
- the search text box should be to locate an address (using gmaps api). The lat/lng should be sent as search parameters. The server will then locate orgs within a radius of that location

**Comment by bradmac** [comment]
Note that we will use these same features in front end org search

**Comment by ducdhm** [comment]
New look for this page:
![fireshot capture 23 - organisations map - http___localhost_8080_organisations_map_q a](https://cloud.githubusercontent.com/assets/1289631/15926950/e902a39c-2e68-11e6-90e8-d786b9a28a5d.png)

**Comment by bradmac** [comment]
More for me to do yet

**Comment by ducdhm** [comment]
Oops, I forgot it

**Comment by bradmac** [comment]
The suggestions doesnt seem to work. I entered text "rosario" and it said no results. When i do this on google maps i get the following:
![maps](https://cloud.githubusercontent.com/assets/826458/15949151/5543e0f8-2ef9-11e6-93b1-31be1cbed780.png)

**Comment by bradmac** [comment]
Also, I noticed that its doing an organisation search when i type in the address which is incorrect. It should only do an organisation search when i select an address suggestion (using the lat/lng coordinates of the selected address) or when I click the search button, which should do a keyword search with no lat/lng coordinates

**Comment by ducdhm** [comment]
Done!

**Comment by ducdhm** [comment]
Final UI:

![aaaa](https://cloud.githubusercontent.com/assets/1289631/15953762/96c1ed5a-2ef8-11e6-9ae1-b4cd120be157.png)

**Comment by ducdhm** [comment]
Docs for new version of jquery.orgFinder: http://docs.kademi.co/ref/javascript/jquery.orgFinder-1.0.1.html

**Comment by bradmac** [comment]
@tuzzmaniandevil can you implement geo-location search
- ideally seach by sorting by distance, and show top X results. If we cant do that, then use a query parameter to specify a max radius
- allow for multiple org types to be selected (use OR)
- if a keyword parameter is present also use that in the query

**Comment by tuzzmaniandevil** [comment]
- ideally seach by sorting by distance, and show top X results. If we cant do that, then use a query parameter to specify a max radius - **Done, distance can be passed in as a param, as distance (Double) default is 20 and distanceUnit default is "km", the units supported are** 
 - in or onch
 - yd or yards
 - ft or feet
 - km or kilometers (Default)
 - NM or nmi or nauticalmiles
 - mm or millimeters
 - cm or centimeters
- allow for multiple org types to be selected (use OR) **Done, Needs to be passed in with lat and long params**

**Comment by tuzzmaniandevil** [comment]
I've moved this to a seperate app called "Organisation Locator"
@Duc the API is the same, I've changed the URL for the admin search and moved the admin file to the orgsLocator folder.

a Resource is now available for website integration, the URL is /orgsLocator/ and the template is /theme/apps/orgsLocator/orgsMap.html

Can you please create a front end page? If you need any API added please let me know.

**Comment by ducdhm** [comment]
@tuzzmaniandevil Can you add API for getting list of org types in front-end?

**Comment by bradmac** [comment]
Now available in both admin and website
```
$page.find("/").orgTypes
```

**Comment by mamun4343** [comment]
i dont see map in all accounts.
