### ISSUE TITLE
New feature when re-assigning leads

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1965]
Thoughts....

I have a lead assigned to me, but I want to pass it onto a colleague to look at as I am not sure what to do with the lead.

- I change who the lead is assigned to using the drop down
- It open a dialogue where I can write an optional note then click submit
- This sends an email notification with the note and basic lead info.  The email has a direct link to the lead
- The note also get's added to the notes field in the lead profile

**Comment by bradmac** [comment]
This is just like assigning an issue in github. I do not think we have a special dialog with notes field, thats what the existing notes feature is for (just like github).

Yes, we should have email notification

**Comment by bradmac** [comment]
@tuzzmaniandevil please create a notification email for when a lead is assigned

**Comment by tuzzmaniandevil** [comment]
Done @hoanglinhlan  please test :-)

**Comment by hoanglinhlan** [comment]
passed
