### ISSUE TITLE
Contact request not showing the message

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1966]
http://kcrm.olhub.com/leads/178751099/

Click view
![image](https://cloud.githubusercontent.com/assets/2201340/15918368/7a06d7f2-2e49-11e6-9dec-08b6d13ccb68.png)

This is the contact request: http://kcrm.olhub.com/contactRequests/178751064

It does not include the body message like below.  Please add:
Hi, Thanks for connecting with me. I noticed from your profile that you work in web design, development & Mobil ...

**Comment by bradmac** [comment]
Add the message field, truncated to 200 chars

**Comment by bradmac** [comment]
@tuzzmaniandevil please add the message field to the template

**Comment by paddyow** [comment]
@tuzzmaniandevil  was this done as I cannot see it on Beta of live?

**Comment by bradmac** [comment]
@paddyow check the milestone, this hasnt been deployed yet
