### ISSUE TITLE
Change profile button

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1971]
- Remove Nick Name Field
- Name field: Make sure the dropdown panel conforms to the width of the email address

![image](https://cloud.githubusercontent.com/assets/2201340/15918802/1cf9bfe8-2e4e-11e6-9b2e-c8cc1d0e94f2.png)

Update how the dropdown contacts appear.
- Move the name and email fields closer together
- Add a line inbetween each contact

![image](https://cloud.githubusercontent.com/assets/2201340/15918843/a5701b38-2e4e-11e6-9795-cde8e7edd3ea.png)

**Comment by anhnt** [comment]
![image](https://cloud.githubusercontent.com/assets/735555/16511592/1222c396-3f7c-11e6-8030-bc7f3dd1a544.png)
