### ISSUE TITLE
Dashboard lead (what body content to show)

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1972]
If the lead has no notes show the lead description content (as it currently is)
If the lead has notes, show the most recent note instead

http://kcrm.olhub.com/dashboard

![image](https://cloud.githubusercontent.com/assets/2201340/15919108/591b239c-2e51-11e6-8c60-7eaeaceead56.png)

**Comment by anhnt** [comment]
![image](https://cloud.githubusercontent.com/assets/735555/16495187/8242d9ec-3f16-11e6-80d0-2f2f4d42ac92.png)
