### ISSUE TITLE
Unwanted carriage returns in lead notes

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1973]
http://kcrm.olhub.com/

![image](https://cloud.githubusercontent.com/assets/2201340/15919374/17f3814a-2e54-11e6-9a3c-1f19309c3770.png)

When you add a lead note in the popup dialogue then click 'Create and View', on the lead profile page the copy seems to have carriage returns added.  Remove any carriage returns. 

![image](https://cloud.githubusercontent.com/assets/2201340/15919414/7866026e-2e54-11e6-912a-82076ce66ecc.png)

**Comment by bradmac** [comment]
@anhnt consider using CommentService to process notes when submitted, and then display without <pre>s

**Comment by anhnt** [comment]
cant reproduce. this might be fixed
