### ISSUE TITLE
Cannot save contact information

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1974]
http://kcrm.olhub.com/leads/180200883/

- If I click save I get an error
- If i reduce the amount of characters in the notes field it seems to save, but does not actually save the updated notes

![image](https://cloud.githubusercontent.com/assets/2201340/15919475/0d1e0c62-2e55-11e6-90d0-7f03db0c0a44.png)

**Comment by bradmac** [comment]
- increase size of col in prod
- add increased size to java class
- check why its not saved

**Comment by tuzzmaniandevil** [comment]
I increased the size on BaseEntity notes to 20000. updated and deployed VFS and updated kademi-server with the new VFS version.

**Comment by tuzzmaniandevil** [comment]
There was also a templating issue.

There is three note fields which get's stored in deffirent places. You have the Lead notes, Profile/Customer notes and Org/Company Notes. I've updated the template to reflect this.
