### ISSUE TITLE
Memo recorder

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1980]
@tuzzmaniandevil  what mobile devices supports this feature? I tried it on my Android and it did nothing.

![image](https://cloud.githubusercontent.com/assets/2201340/15920281/e724966e-2e5b-11e6-8ecd-da6ae6153589.png)

**Comment by Uafinder** [comment]
Someone told me that voice memo should be disabled...

**Comment by bradmac** [comment]
It should work on Android and iOS

**Comment by tuzzmaniandevil** [comment]
Yes it's support on IOS and Android but the website needs to be HTTPS or it won't work.

**Comment by bradmac** [comment]
We should probably force https on crm. 

@Uafinder can you please test using https?
