### ISSUE TITLE
Creating new funnel breaks KCRM

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1992]
http://kademi.admin.olhub.com/funnels/

Add new funnel then navigate to KCRM here http://kcrm.olhub.com/dashboard

**Comment by bradmac** [comment]
Looks ok to me. Whats broken?

**Comment by paddyow** [comment]
Create a new funnel called 'Other' here http://kademi.admin.olhub.com/funnels/
Then go here http://kademi.admin.olhub.com/funnels/
Then see Grizley error

**Comment by bradmac** [comment]
Fixed a while back
