### ISSUE TITLE
Emails not capturing into KCRM

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1993]
See this lead http://kcrm.olhub.com/leads/136865592/
I clicked the To field and sent an email which was captured
I then sent 3 more test using this email to-lead-136865592@kcrm.olhub.com
None of the followup emails were captured into KCRM

**Comment by bradmac** [comment]
Confirmed, same with me.

**Comment by bradmac** [comment]
Added logging, will review after next deploy

**Comment by tuzzmaniandevil** [comment]
I've tested this on AWS and locally. both work correctly.

**Comment by tuzzmaniandevil** [comment]
I've re-added the sales role check.

**Comment by paddyow** [comment]
I BCCd an email to this lead http://kcrm.kademi.us/leads/1939430/

Have not recieved the timeline update after 5 mins.

![image](https://cloud.githubusercontent.com/assets/2201340/18632579/7734c260-7ebb-11e6-80da-28d1e9834a09.png)

**Comment by tuzzmaniandevil** [comment]
There was a misconfig on our US cluster. This has now been corrected

**Comment by hoanglinhlan** [comment]
passed
