### ISSUE TITLE
Cannot assign new contact to lead

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1994]
This contact http://kcrm.olhub.com/custs/eddytsang/

Need to be assigned to this lead http://kcrm.olhub.com/leads/132046956/

Cannot find the contact when changing the profile.

**Comment by tuzzmaniandevil** [comment]
I tested it and seems to work fine, @paddyow can you please re-test?

**Comment by bradmac** [comment]
Hey @tuzzmaniandevil i checked in and confirmed there is a problem. Let me know if you cant see it

**Comment by paddyow** [comment]
@tuzzmaniandevil  I just had a look, when I do a search for a profile, it's pulling up profile names from somewhere else, I have no idea where from though.

![image](https://cloud.githubusercontent.com/assets/2201340/16071003/447fa758-331c-11e6-9c7e-484b108a9187.png)

**Comment by tuzzmaniandevil** [comment]
I've fixed the search query and also changed it to use ES instead of DB.

**Comment by hoanglinhlan** [comment]
assign new contact ok
