### ISSUE TITLE
Viewing lead info takes a long time to load page

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#1997]
![image](https://cloud.githubusercontent.com/assets/2201340/16065782/f955e3bc-32f0-11e6-9a54-23a7c762c5aa.png)

http://kcrm.olhub.com/leads/139038643/

Takes 30+ seconds to navigate to the contact request page.

**Comment by bradmac** [comment]
Problem is that the entire list of contact requests is being loaded to find just one

@tuzzmaniandevil please change getChildren in ContactRequestsFolder to return null. Instead implement child(..) to locate the CR by ID and return it

Be sure to check that the loaded CR is for the current organisation and return null if not, to prevent access to CR's from other orgs
