### ISSUE TITLE
Top points balances component

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#1999]

**Comment by bradmac** [comment]
UI:
![top-balances](https://cloud.githubusercontent.com/assets/826458/16101483/4c90d626-33ba-11e6-87a2-b3f7f1928b7a.png)

**Comment by bradmac** [comment]
@ducdhm can i hand over to you to finish off?
- make the limit configurable, instead of days (i copied from recent points component)

**Comment by ducdhm** [comment]
Ok. It's same with My Recent Point :)

**Comment by bradmac** [comment]
Also needs to be contextual, ie to show top balances in whatever organisation the current user is in. Need to change to elasticsearch query to do that.

**Comment by bradmac** [comment]
Is now using profile app indexer. Next is to make it work with org app indexer for team based points, such as will be used in carters

**Comment by bradmac** [comment]
Now works with organisations
