### ISSUE TITLE
Description field should not be mandatory when adding note

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2000]
![image](https://cloud.githubusercontent.com/assets/2201340/16070597/ff3a6d88-3319-11e6-9cf1-f432ba659a65.png)

Adding a new note on a lead then a task in the same window, the description field should not be mandatory

**Comment by mamun4343** [comment]
its working cool, just i see a little bug,

check the attachment.
![untitled](https://cloud.githubusercontent.com/assets/3419573/16375437/4217b0ae-3c7d-11e6-8e7d-56b37396111c.jpg)

when the marks field is empty, then i see a @note.notes in front end. plz replace a default text there.

**Comment by bradmac** [comment]
:+1:

**Comment by ducdhm** [comment]
Can't reproduce it

**Comment by ducdhm** [comment]
Done!
