### ISSUE TITLE
When a lead is cancelled, the tasks are still active

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2001]
http://kcrm.olhub.com/tasks/?type=active

It seems we have lots of active leads, yet they are linked to cancelled leads.

When a lead is cancelled the task should be flagged as cancelled and appear in the cancelled list.

**Comment by bradmac** [comment]
This was resolved in this issue - https://github.com/Kademi/kademi-dev/issues/1637

@paddyow can you confirm if this is still happening, and if so re-open 1637, or if these are just old tasks from before 1637 was done?
