### ISSUE TITLE
$rootFolder variable in edmEditor

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#2003]
Hi @bradmac 
We have issue with `$rootFolder` variable in edmEditor. In edmEditor screen, `$rootFolder` is `OrganisationRootFolder` but when sending email, `$rootFolder` is `WebsiteRootFolder`. If I make dynamic component works in edmEditor, when sending email, the content will be error. And reserve.

What should we do?

**Comment by bradmac** [comment]
@ducdhm can you give me an example of something you want to access in both contexts?

**Comment by bradmac** [comment]
OK, so the best thing to do in this case, and this is probably going to be the usual approach, is to use methods on the app class rather then on resources.

I've added a searchProducts method to the ECommerceApp which has a store parameter. This can be called from the template like this:

```
#set( $prods = $applications.ecommerce.searchProducts($store, null, $category, 'title', false) )
```

That will then work no matter what context its called from

**Comment by ducdhm** [comment]
Yeah, you right. We should use $applications.{applicationName} to do anything with dynamic component :+1:
