### ISSUE TITLE
items not removing from shopping cart

### ISSUE THREAD

**Issue by mamun4343** [Kademi/kademi-dev#2006]
http://carters.kademi-sandbox.co/checkout/  
here, products are not removing after a delete command. 

experienced this as this user http://carters.admin.kademi-sandbox.co/manageUsers/6742554/#commentsTab-tab

**Comment by mamun4343** [comment]
How to generate the issue,
add more then 1o products from different categories.

**Comment by bradmac** [comment]
I cant reproduce the problem described above. But i can see that after adding those 2 items the shopping cart icon correctly says 2 items, but the chekcout page shows 1 item. Removing it leaves the shopping cart icon showing 1 item but no item displaying in the checkout page

I noticed that the ajax methods to add the products differs between the detail page and the list page:

changeItemHrefQuantity: /test-reward/Electronics/6706743/?
quantity	: 1

addItemHref	: /test-reward/Electronics/6706743
addItemQuantity	: 1		

I think this might be the cause. We should probably normalise the href when adding to the shopping cart, eg always have a ? or strip it of no args
