### ISSUE TITLE
Completing a task

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2009]
![image](https://cloud.githubusercontent.com/assets/2201340/16142013/eb8d9256-34a4-11e6-8d99-9759599693e4.png)

When a task is completed, where should the what happened content go?  On the timeline?  If it should it's not working so please assign to be fixed.

**Comment by tuzzmaniandevil** [comment]
That just creates a note when filled out

**Comment by bradmac** [comment]
Notes should appear on the timeline

**Comment by tuzzmaniandevil** [comment]
Found the problem, The note was being created against the current logged in user, not the profile of the lead.

**Comment by tuzzmaniandevil** [comment]
Is should show in the timeline of the lead according to the code. I'll test it.

**Comment by tuzzmaniandevil** [comment]
Just tried it and this is the result, You can see the note "Nothing Happend" and a timeline item showing the note being created:
![screenshot from 2016-08-04 12-56-12](https://cloud.githubusercontent.com/assets/3378330/17386892/dc0b901c-5a42-11e6-814b-490a2f23d6ce.png)

**Comment by tuzzmaniandevil** [comment]
This is the URL I tested it with:
http://test.kademi.com.au/leads/19745247/

**Comment by hoanglinhlan** [comment]
passed
