### ISSUE TITLE
Allow tasks to be re-opened

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2010]
http://kcrm.olhub.com/leads/155065644/

See the task Revisit lead which is closed.

Maybe we add a button called re-open task? But remove the edit icon.

**Comment by bradmac** [comment]
I think we do need to be able to re-open a task, but i dont think we need to make tasks readonly when they're closed.

Kademi tasks are modelled on github issues, and github issues are editable when closed.
