### ISSUE TITLE
Elearning module issue

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#2015]
http://admin.zoetis.olhub.com/websites/zoetis-livestock-reseller/version4/programs/PRODSOLU01/ZOELIV1343/ZOELIV1343/

![module managerment issue](https://cloud.githubusercontent.com/assets/735555/16181886/9afa842a-36ca-11e6-82cf-6174cf996c7e.PNG)

Editing version is not rendered
Cant manage version
Publish button is appearing when its live version

**Comment by anhnt** [comment]
@bradmac can you please do a quick deploy for that?

**Comment by bradmac** [comment]
Patched into prod
