### ISSUE TITLE
Most popular (viewed) products in reward store report

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2018]
Report to show the products and number of views, to be able to find the most and least popular for viewing (but not necessarily purchasing)
- Report histogram should show products page views in the selected date range, ie normal date histogram
- Allow filtering via aggregations/facets by
  - product category
  - user group
  - reward store
- CSV output to show 
  - product title
  - number of views

Table under the graph should show most viewed products, maybe top 20 or so

**Comment by bradmac** [comment]
Please use elasticsearch, not database search

**Comment by diegoperezn** [comment]
@gonzalon could you peer review? Thanks!

**Comment by gonzalon** [comment]
@diegoperezn everything seems ok 👍

**Comment by diegoperezn** [comment]
Thanks!

**Comment by hoanglinhlan** [comment]
Report: https://lan-test.admin.kademi.com.au/reporting/MostPopularProduct?startDate=05%2F03%2F2017&finishDate=05%2F06%2F2017
Reward store: https://lan-test.admin.kademi.com.au/reward-store/c5s-business/#products-tab
Profile: https://lan-test.admin.kademi.com.au/manageUsers/41267184

1: filter by date range isn't work, 
I viewed 2 product a few days ago but the graph showing only 1 product with 2 view if I choose date range is from 3 month ago
2: it's not showing reward stores, groups, categories ( I viewed producs in 2 groups, 2 category ...) 
3: I viewed product "samsung01" more than 2 times but the graph showing product views = 2


Note: cleared cached

**Comment by AlaaKhalaf94** [comment]
Hi @gonzalon ,  When I go to test
I see code in control panel "Invocation of method 'getAggregations' in  class io.milton.cloud.server.apps.reporting.JsonReportPage threw exception Failed to execute phase [query], all shards failed; shardFailures {[dC-M6VDRQfyU4lFzMBtzKg][qa1-log-144702][0]: RemoteTransportException[[dC-M6VD][local[1]][indices:data/read/search[phase/query]]]; nested: IllegalArgumentException[Fielddata is disabled on text fields by default."

http://alaa-test.admin.kademi-prod.com/reporting/MostPopularProduct

**Comment by gonzalon** [comment]
Hey @AlaaKhalaf94 I just reindexed to see what was happening. Now its fine for testing.
If you see the error again try re-indexing again. Thanks

**Comment by AlaaKhalaf94** [comment]
Depending on Lan's comment I completed , and there is no data appear here

https://lan-test.admin.kademi.com.au/reporting/MostPopularProduct?startDate=17%2F07%2F2017&finishDate=23%2F07%2F2017

![capture1](https://user-images.githubusercontent.com/26510030/28497899-bbd038b6-6f9a-11e7-836b-1d72b6b8a861.PNG)

**Comment by bradmac** [comment]
@AlaaKhalaf94 it looks ok to me

![image](https://user-images.githubusercontent.com/826458/28497993-63c8fc2c-6fe8-11e7-9db4-c5406b397f79.png)

**Comment by bradmac** [comment]
What date range are you using?

**Comment by AlaaKhalaf94** [comment]
oh , sorry
I tyr with 3days , 7days and 1mo

passed

**Comment by bradmac** [comment]
This implementation is completely incorrect and unworkable. 

Currently its iterating over all memberships for all users in the account to find groups of the current user. This is the stuff of nightmares, capable of bringing an m4.xlarge db server to its knees:
```
                for (GroupMembership m : t.getOrganisation().getMembers()) {
                    if ( m.getMember().getName().equals(t.getReqUser()) ) {
                        groups.add(m.getGroupEntity().getName());
                    }
                }
```

The reward and category names should not be part of the WebHitAppIndexer



```
        if ( !path.isRoot() && path.getParent() != null
                && StringUtils.isNotEmpty(path.getParent().toString()) ) {
            builder.field("parentUrl", path.getParent().toString());

            String pathList[] = path.getParent().toString().split("/");

            if ( pathList.length == 3 ) {
                builder.field("reward", pathList[1]);
                builder.field("category", pathList[2]);
```

These should be generic path components that could have any meaning to any resource.

**Comment by bradmac** [comment]
Just commenting out the most hideous stuff for now.

**Comment by bradmac** [comment]
@gonzalon please re-implement using a less crap approach

**Comment by gonzalon** [comment]
@AlaaKhalaf94 now we can filter by category and website only. But we now support the views for products in reward stores and e commerce stores.

![image](https://user-images.githubusercontent.com/2773216/33750592-d15ab8f8-dc39-11e7-89be-d550492012bb.png)

**Comment by AlaaKhalaf94** [comment]
passed
