### ISSUE TITLE
Most purchased products in reward store report

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2019]
Report to show the products and number of purchases, to be able to find the most and least popular
- Report histogram should show products by number of purchases in the selected date range, from most popular to least
- Allow filtering via aggregations/facets by
  - product category
  - user group
  - reward store
- CSV output to show 
  - product
  - number of purchases
  - number of views

**Comment by bradmac** [comment]
@gonzalon  Might be related to the other stuff you were doing..

**Comment by gonzalon** [comment]
![image](https://user-images.githubusercontent.com/2773216/33814034-524dc92e-de8c-11e7-8f39-c66bc7de2773.png)

**Comment by AlaaKhalaf94** [comment]
Hi @gonzalon , I can't see  filtering by reward store

![capture1](https://user-images.githubusercontent.com/26510030/34205930-0abc4024-e58d-11e7-970d-8daaeeaa9060.PNG)

And in CSV output there isn't column for number of views

http://fresh08.admin.kademi-ci.co/reporting/MostPurchasedProduct?startDate=14%2F12%2F2017&finishDate=20%2F12%2F2017

**Comment by gonzalon** [comment]
@AlaaKhalaf94 added the views in the CSV, but as the change we made in the other report we are not filtering any more by reward stores, you can filter by the website

**Comment by AlaaKhalaf94** [comment]
passed
