### ISSUE TITLE
Searching on cancelled leads

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2020]
I don't think KCRM search should show cancelled leads.  I had once customer, 2 cancelled leads and 1 active, and had to go through all 3 to find the active lead.

If we show all leads, we should show if they are active or closed in the search result drop down.

Thoughts?

**Comment by bradmac** [comment]
Yep, agree that we should not see cancelled leads by default. But there does need to be a way to see cancelled leads.

So we should have an option on search to show cancelled leads

**Comment by anhnt** [comment]
can we just add a label to each result which shows whether that lead is cancelled or not? and probably just sort that result list to display non-cancelled lead first?

**Comment by bradmac** [comment]
No, we definitely do not want to show cancelled leads by default. For most clients there will be far more cancelled leads then active.

But something like what github has with open/closed issues would be nice

**Comment by anhnt** [comment]
@paddyow will provide a design for that and i will update it then

**Comment by paddyow** [comment]
Hey guys I am thinking this where they can toggle active and closed leads using a drop down in the search box.  A lot of stock libraries use this method.

![image](https://cloud.githubusercontent.com/assets/2201340/16723670/bc265e26-4791-11e6-8804-d2648b8f1386.png)

Bootstrap example here: http://www.bootply.com/gWOb4RcY86

**Comment by anhnt** [comment]
just added a dropdown as design above. @tuzzmaniandevil can you help me with java side please?

**Comment by tuzzmaniandevil** [comment]
@anhnt Java side is done :-)

**Comment by anhnt** [comment]
updated client side. its ready for testing

**Comment by tuzzmaniandevil** [comment]
Tested locally, Looks good. @hoanglinhlan Over to you ;-)

**Comment by hoanglinhlan** [comment]
start test . . . :-)

**Comment by hoanglinhlan** [comment]
Confirm fixed ok 
Dropdown have 3 option: Active / Won/ Lost
Search function working exactly for each option

**Comment by bradmac** [comment]
Hey @paddyow can we remove the active filter from the menu area? We're stuffing way too much into the menu. I think it should just search for active only from the menu, and the user can filter on the leads page.

**Comment by bradmac** [comment]
@anhnt Can you please remove the status selection from the menu?

Also, just noticed that the Calendars menu is hard coded. This should be removed, because apps should add their menus when enabled.

**Comment by anhnt** [comment]
done
