### ISSUE TITLE
Add Job Title to contact in KCRM

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2022]

**Comment by bradmac** [comment]
Note that that this should be part of the company, ie similar to linkedin, where a user has a role to a particular company

So should be a new column or custom field on the membership

**Comment by bradmac** [comment]
@paddyow what do you think about using tags for job title?
Advantages would be
- can then segment on job title, ie send email to all CTO's
- quick to add

But would need to be able to add tags on the fly

**Comment by paddyow** [comment]
From a user experience:
- I want to be able to type and have past job titles appear in a drop down so I can select one if it has been used before
- If the job title does not exist, I want to be able to add it so I can re-use it again

If we use tags I guess all other tags will appear as I start typing?

**Comment by bradmac** [comment]
After talking with @paddyow have decided that for now we should just add a job title text field. This can be an additional column no the Lead table.

This should be an auto-complete text field, pulling a list of job titles from other leads.

@tuzzmaniandevil can you please add the column and simple text field, and an ajax service to get a list of job titles (eg using a terms query on the leads app index), and then hand over to @anhnt to integrate the autocomplete control

**Comment by tuzzmaniandevil** [comment]
I've added the field and API.
@anhnt to access the jobTitle API you use ?jobTitle if you want to add a query use "q"
so for example 
`http://version1.test.loopbackdns.com:8080/leads/1/?jobTitle`
or
`http://version1.test.loopbackdns.com:8080/leads/1/?jobTitle&q=Test`

This will return a JsonResult with an Array in the data, e.g.:
```
{
  "data": [
    "Testing 123"
  ],
  "fieldMessages": [],
  "messages": [],
  "nextHref": "",
  "status": true
}
```

**Comment by anhnt** [comment]
![image](https://cloud.githubusercontent.com/assets/735555/17398815/e98492fe-5a68-11e6-96f6-81ba7df121b3.png)
