### ISSUE TITLE
Add or create company when creating contact in KCRM

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2023]
When adding a new contact in KCRM, we must be able to create a new company or assign a company to the contact.  This will allow the admin user to open a company and see all employees in that company.

Must also be able to assign company from the profile page, for example: http://kcrm.olhub.com/custs/dirlafis/

**Comment by bradmac** [comment]
This is currently available on the lead page, needs to also be on the contact page

**Comment by hoanglinhlan** [comment]
Created or added company success
