### ISSUE TITLE
Disable re-attempt button if quiz is not batched

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#2025]

**Comment by ducdhm** [comment]
Duplicated of https://github.com/Kademi/kademi-dev/issues/2026#event-698531009

**Comment by mamun4343** [comment]
working fine. but, i think we dont need 2 submit button therr. see attachment 
![untitled](https://cloud.githubusercontent.com/assets/3419573/16376154/bd30356a-3c80-11e6-8c42-fbf897c4484d.png)

**Comment by bradmac** [comment]
We've always had 2 buttons. Its because users sometimes think the Next button is only for going to the next page, and not submitting the quiz.
