### ISSUE TITLE
Quiz enhancements

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2026]
- do not show "Re-attempt" button for non-batch quizes
- users should be able to go to a previous page from a quiz. Currently, attempting to navigate away submits the quiz
- remove exclamation marks from result message
- make re-attempt button visuallay different from the normal submit button (ie use brand-success), and place it above and below the quiz

**Comment by ducdhm** [comment]
@Uafinder Can you help me test this issue on Waterco and Swimart?

This user for waterco: http://admin.waterco.olhub.com/manageUsers/27906219/
And this user for swimart: http://admin.swimart.olhub.com/manageUsers/36004087/
