### ISSUE TITLE
Uploader issues

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#2033]
1. When there are a lot of fields in file, upload tool looks poor and buggy.
![image](https://cloud.githubusercontent.com/assets/1945230/16281294/5f052eb2-38cc-11e6-9faf-a6250abae7f1.png)
Dropdowns looks buggy and no idea how it decide to wrap text to the other string.

2. Visual issues - default group text is not full, it could be fixed by moving Removing text a bit closer to it's dropdown list. Removing dropdown also could be a bit wider.
![image](https://cloud.githubusercontent.com/assets/1945230/16282707/9d455eee-38d2-11e6-8724-5e0446e378e7.png)

3. Suggestion: it could be great to filter available fields depends on default group selection. E.g. when you select minda for example it will show only fields in minda group.
![image](https://cloud.githubusercontent.com/assets/1945230/16281682/2cbc29d6-38ce-11e6-949b-bcff9799f985.png)

4. Weird import result
Have such data:
![image](https://cloud.githubusercontent.com/assets/1945230/16281708/4534e660-38ce-11e6-93f9-3b25bad55dd9.png)
Receive such kind:
![image](https://cloud.githubusercontent.com/assets/1945230/16281741/61e39680-38ce-11e6-8020-9df1bf2650f6.png)

5. Data type values are not showing in the import tool and doesn't import at all from Excel files.
![image](https://cloud.githubusercontent.com/assets/1945230/16282116/fce22ba0-38cf-11e6-83c4-a83748e3fea9.png)
![image](https://cloud.githubusercontent.com/assets/1945230/16282134/0f7f2574-38d0-11e6-8613-4c4167e70ab3.png)

6. When "no default group" selected profile is not creating, no matter of this info.
![image](https://cloud.githubusercontent.com/assets/1945230/16282245/9220373e-38d0-11e6-813b-a3798af13948.png)

7. No validation when creating a user with additional mandatory field. It's just creating account without required fields.

8. There are should be a validation on file type when selecting file.
![image](https://cloud.githubusercontent.com/assets/1945230/16282392/420a6214-38d1-11e6-94f9-bfcb99b62bbb.png)

9. Incorrect pop-up - group column is not mandatory.
![image](https://cloud.githubusercontent.com/assets/1945230/16282657/51594068-38d2-11e6-9995-c4b2f31f4315.png)

To be continued...

**Comment by Uafinder** [comment]
10. If file has a lot of strings - it shows only first 50 in the table. Not sure if it's a bug.

11. There no imported users are shown after uppload is fininshed without hard refresh.
![image](https://cloud.githubusercontent.com/assets/1945230/16542183/71ecb79c-40a7-11e6-968c-da618bbf7748.png)

12. There is a possiblity to push Next whch will leads you to next step but without import starting.

**Comment by Uafinder** [comment]
15.Looks like there is no automic profiles indexations after import and new profiles are not showing. I've spot it when i import ~400 users and it says that they was updated. But there was only two visible users, so it very weird.

**Comment by tuzzmaniandevil** [comment]
15. **I tested it with 700 users and worked fine**

**Comment by tuzzmaniandevil** [comment]
14 . **This has been fixed.**

**Comment by tuzzmaniandevil** [comment]
10.If file has a lot of strings - it shows only first 50 in the table. Not sure if it's a bug. **That's fine, It's just so users can see how to assign the culumns, the complete file still get's processed**

**Comment by anhnt** [comment]
> 10.If file has a lot of strings - it shows only first 50 in the table. Not sure if it's a bug.

In frontend code we just show first 50 records. I think we can improve that by adding a dropdown list indicate how many records should be displayed

**Comment by bradmac** [comment]
I think its ok as it is.

**Comment by bradmac** [comment]
Hey @Uafinder can you give us the URL of this account?

**Comment by anhnt** [comment]
1. **This has been fixed**
2. **This has been fixed**

**Comment by anhnt** [comment]
6. If default group is not selected, then user must indicate group column as destination field. Also if no destination field is selected, should alert an error message

**Comment by anhnt** [comment]
12: **this has been fixed**

**Comment by anhnt** [comment]
13.Fields list are not organized at all (there is sorting). **This has been fixed**

**Comment by anhnt** [comment]
11.There no imported users are shown after uppload is fininshed without hard refresh. **This has been fixed**

**Comment by anhnt** [comment]
8. There are should be a validation on file type when selecting file. **This has been fixed**

**Comment by anhnt** [comment]
Hey @tuzzmaniandevil  can you have look at 3, 4, 5, 7 please. I think its java part :)

**Comment by tuzzmaniandevil** [comment]
5 . Data type values are not showing in the import tool and doesn't import at all from Excel files. **Fixed**

**Comment by tuzzmaniandevil** [comment]
3: Suggestion: it could be great to filter available fields depends on default group selection. E.g. when you select minda for example it will show only fields in minda group. **Moved to a seperate issue** #2092

**Comment by tuzzmaniandevil** [comment]
4: Weird import result - **Fixed for xlsx files**

**Comment by hoanglinhlan** [comment]
**Pass**: 1-2-4-5-6-8-9-11
**Fail**: 
7: 
- Organization must always required, but I can import user without Organization ( At Complete step: system report create new user however I can't saw new user in list user)
- on configuration group created an extra field and set require for this. Currently, system allow create new user has not require extra field.

14: Calculating existing profiles doesn't work. Selected profile is on the files, but it counted like new.

**Comment by tuzzmaniandevil** [comment]
14: Calculating existing profiles doesn't work. Selected profile is on the files, but it counted like new. - **This should now be corrected :-)**

**Comment by tuzzmaniandevil** [comment]
7:
- **An organization isn't required when importing users, if no org is provided the admin org is used**
- **The required field is for the front end only, not for admins on the back end**

**Comment by hoanglinhlan** [comment]
.14. fixed/ pass
.7.

- cant import if you do not import org
- about extra require field: cant import. Step3 (import) found new profile, then at step5 (complete): system report create and update was 0 record but I cant saw any warning or error message

**Comment by tuzzmaniandevil** [comment]
@hoanglinhlan With "cant import if you do not import org", Do you mean it won't import unless you specify an org field or it fails when you try to specify an org field?

**Comment by tuzzmaniandevil** [comment]
@hoanglinhlan I did an import this morning without specifying an org field and it worked.

**Comment by tuzzmaniandevil** [comment]
"about extra require field: cant import. Step3 (import) found new profile, then at step5 (complete): system report create and update was 0 record but I cant saw any warning or error message" - **I tested it and it works, Could of been fixed with https://github.com/Kademi/kademi-dev/issues/2178#issuecomment-238119922**
