### ISSUE TITLE
Logging screen is not real-time anymore

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#2035]

**Comment by bradmac** [comment]
Yep, real time just doesnt work in a clustered environment

**Comment by ducdhm** [comment]
@bradmac But instead of setTimeout 5s for each ajax request, we can using long-pulling for it.

**Comment by bradmac** [comment]
Nope, because the data comes from different servers. We can increase the polling frequency, but we cant do it with websockets

**Comment by ducdhm** [comment]
Yeah, I dont hope we can implement websockets like previously, but at least "realtime" is in +/- 1 second

**Comment by bradmac** [comment]
Changed to 1000ms, and added auto scroll to bottom, and added checkbox to tail or not for pausing
