### ISSUE TITLE
Custom app XmlHttpRequest async

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#2036]
From our client:

> When posting request to 3rd server, it keep returning error without waiting the post finished

@tuzzmaniandevil  can you have a look please

**Comment by bradmac** [comment]
@anhnt that doesnt make any sense.

**Comment by siyoyo** [comment]
Hi bradmac, it will not goes here/ or waiting until the process finished:
 http.onreadystatechange 
  
 instead passed it, can you show me the correct code for waiting the post finished?

**Comment by bradmac** [comment]
The XHR object supports syncronous and async modes:

http://www.w3schools.com/ajax/ajax_xmlhttprequest_send.asp

xhttp.open("GET", "ajax_info.txt", true);
xhttp.send();

open(method, url, async) 	Specifies the type of request

method: the type of request: GET or POST
url: the server (file) location
async: true (asynchronous) or false (synchronous)

**Comment by siyoyo** [comment]
I have set it into false Brad, but it doesn't want to wait until the send has finished..

**Comment by anhnt** [comment]
@siyoyo i've tested using synchronous request and its working fine for me. Please have a look at this bit:
`var http = new XMLHttpRequest();
    http.open("GET", 'https://github.com', false); // async = false
    http.setRequestHeader('Content-Type','text/html');
    http.send();
    log.info('http readyState {}', http.readyState);
    log.info('http status {}, responseText {}', http.status, http.responseText);
    return views.jsonObjectView(JSON.stringify({async: false, data: http.responseText}));`

**Comment by anhnt** [comment]
ok, so just use synchronous request as its working now

**Comment by siyoyo** [comment]
Hi Anh, thank you for your help, so the conlusion is: if we set Async off then no need to setup di onreadystatechange.

**Comment by anhnt** [comment]
Yeah, we can ignore onreadystatechange for now to make life simpler
