### ISSUE TITLE
Add group selection to containers

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2038]
Allow editing a list of groups for each container. Containers will only be rendered if there are no groups selected, or the current user is a member of a selected group

**Comment by bradmac** [comment]
@ducdhm can you please add editor support for selecting zero or more groups, and storing as a comma seperated list on a data attribute of the container

**Comment by ducdhm** [comment]
@bradmac I'm done in my side. The rest is yours.

**Comment by bradmac** [comment]
Integrated server side now

![screenshot-version1 ecom1 loopbackdns com 8080 2016-07-07 14-54-44](https://cloud.githubusercontent.com/assets/826458/16641261/ea85fcf0-4452-11e6-965d-ee5fbf7bfc84.png)
