### ISSUE TITLE
Improve validation message for rename file

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2040]
Currently if you try to rename a file to the same name as an existing file you get an generic "sorry" message, but not information about the actual error.

Please add a validation check just prior to renaming which will do an ajax request to check the entered name does not already exist, and if it does display an appropriate message to the user.

Also, please update the form to use a modal with inline validation messages rather then an alert box

**Comment by anhnt** [comment]
![image](https://cloud.githubusercontent.com/assets/735555/16440883/0e2ff58e-3df0-11e6-9f8e-0c25a568adfb.png)
