### ISSUE TITLE
Integrate hazelcast with CacheManager

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2044]
Create an implementation of io.milton.cloud.server.manager.CacheManager for hazelcast, and integrate that with AWS configuration

**Comment by tuzzmaniandevil** [comment]
Hazelcast already implements CacheManager. I've just updated to implement flush

**Comment by bradmac** [comment]
Cache stats are not appearing
http://rootorg.admin.kademi.com.au/maint#cache-tab

**Comment by tuzzmaniandevil** [comment]
I've moved the HazelcastCacheManage to Kademi-server instead of kademi-aws and make some tweaks to the flush method.
