### ISSUE TITLE
Points debit report probs

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2048]
View report here:
http://acb.admin.olhub.com/reporting/pointsDebit

And compare with the cart details here:
http://acb.admin.olhub.com/shopping-carts/185656168/#items-tab

Note the difference in the product descriptions. This is after re-indexing.

**Comment by tuzzmaniandevil** [comment]
This is because a single item can have multiple points debit records.

I've added Facets to the reports. Groups, Orgs and Points Buckets
