### ISSUE TITLE
ES module activity report, graph is incorrect

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2050]
Because there is a zero value and a non-zero value for dates

Eg
http://admin.zoetis.olhub.com/reporting/esModuleBreakdown

**Comment by tuzzmaniandevil** [comment]
Seems to be ok with latest code:
![screenshot from 2016-07-14 16-23-53](https://cloud.githubusercontent.com/assets/3378330/16827947/6d933d4c-49df-11e6-8906-d7b06893b856.png)
