### ISSUE TITLE
Reporting components integrated with custom queries

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2055]
Required components
- table: display hits from an ES query in a table
- date histogram: display an aggregation as a histogram, eg number of page views per day
- pie chart: show an aggregation as pie slices

These components should allow the user to select a saved query (ie from Reporting-Queries) see https://github.com/Kademi/kademi-dev/issues/1822

Those which require an aggregation should allow the user to select an aggregation defined by the selected query.

**Comment by bradmac** [comment]
Completed table and date histo:

![screenshot-carters admin loopbackdns com 8080 2016-07-04 12-06-15](https://cloud.githubusercontent.com/assets/826458/16548351/c7610438-41df-11e6-987f-05730a442222.png)

**Comment by bradmac** [comment]
Here is the dashboard page code:
```
<html>
	<head>
		<meta http-equiv="content-type" content="application/xhtml+xml; charset=UTF-8" />
		<title></title>
	</head>
	<body>
		<section>
			<div class="container-bg">
				<div class="container-content">
					<div class="row">
						<div class="col-sm-6" data-type="container-content">
							<section data-query="logs" data-type="component-dateHistogram" data-agg="byDate">
								<div data-dynamic-href="_components/dateHistogram"></div>
							</section>
						</div>
						<div class="col-sm-6" data-type="container-content">
							<section data-type="component-queryTable" data-query="org-locations.query.json">
								<div data-dynamic-href="_components/queryTable"></div>
							</section>
						</div>
					</div>
				</div>
			</div>
		</section>
	</body>
</html>
```

**Comment by bradmac** [comment]
And here is the saved logs query:
```
{
  "fields": [
    "deviceCategory",
    "reqDate"
  ],
  "query": {
    "match_all": {}
  },
  "size": 10,
  "aggregations": {
    "byDate": {
      "date_histogram": {
        "field": "reqDate",
        "interval": "day"
      }
    }
  }
}
```

**Comment by bradmac** [comment]
@ducdhm can you please implement a pie chart component?

**Comment by bradmac** [comment]
To set this up:
1. Go to the manage search page
2. Click on logs
3. Click save, enter "logs" as the name
4. Go to the reporting page
5. Click on the Queries submenu
6. Edit the "logs" query
7. Enter the code above and run it (which will save it)
8. Now create an admin dashboard for admins with the source code above

**Comment by bradmac** [comment]
I still need to integrate with date range control

**Comment by ducdhm** [comment]
Integrated with date range control!
