### ISSUE TITLE
Organisations filter does not support multiple org types

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#2060]
![image](https://cloud.githubusercontent.com/assets/1945230/16462672/ebb2d346-3e3a-11e6-9cd4-6d634e1f4049.png)

1. Add org to two or more org types
2. Back to the orgs list
3. Firstly, you will not see this in the org list, but that's a minor
4. Choose filter by org types - filter will only show you an org when it's a first in the list.

**Comment by bradmac** [comment]
Yes, this page will need to be upgraded to be similar to manage users. But not yet :)
