### ISSUE TITLE
Much bigger action buttons like Save, etc

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#2061]
Just spot that some buttons are really bigger for others. Is it a new style? 
![image](https://cloud.githubusercontent.com/assets/1945230/16462898/176084b0-3e3c-11e6-8c9e-d5471b1b0e36.png)
![image](https://cloud.githubusercontent.com/assets/1945230/16462912/2ae228ea-3e3c-11e6-849b-b08d28faa547.png)

**Comment by bradmac** [comment]
Yep, i think we have been guilty of having buttons difficult to find. Just makeing them bigger, green, and with an icon helps

**Comment by Uafinder** [comment]
Undarstood, thanks!
