### ISSUE TITLE
Should pages be visible while debits counts not more than it's limit?

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#2064]
![image](https://cloud.githubusercontent.com/assets/1945230/16464212/dd579924-3e41-11e6-8b91-8fae2bf3bf87.png)

**Comment by bradmac** [comment]
Correct, paginator should not be shown in that case

**Comment by anhnt** [comment]
done. @hoanglinhlan let me know if you need a hand to setup test data

**Comment by hoanglinhlan** [comment]
Failed
Limit = 10 row / 1 page
I have 16 row, so we must have 2 page 
![image](https://cloud.githubusercontent.com/assets/20508726/18980947/c9d688d2-8703-11e6-9185-a087b347dd70.png)

**Comment by tuzzmaniandevil** [comment]
Pagination fixed, Tested with 50 records.

**Comment by hoanglinhlan** [comment]
Failed
while I access the page I see many record, but after loading done, I cant see any record

Reward point 
![image](https://cloud.githubusercontent.com/assets/20508726/19417089/aab4e2e2-93cd-11e6-977f-2ff03cd961ec.png)

Point bucket
![image](https://cloud.githubusercontent.com/assets/20508726/19417128/b78a2940-93ce-11e6-87ea-70703e8e2800.png)

https://www.youtube.com/watch?v=Z1SSeEGFDvg

**Comment by tuzzmaniandevil** [comment]
@hoanglinhlan Looking at the daterange in your screen shots, They don't include the dates of the records thats probably why they are dissapearing. Can you please retest?
