### ISSUE TITLE
Expired column always empty on points tab (points bucket)

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#2066]
![image](https://cloud.githubusercontent.com/assets/1945230/16464986/517f3a3e-3e45-11e6-8267-ef21e59ef200.png)

You can select either value of days or expiration date. Result will be the same - expiration date will be empty.

**Comment by anhnt** [comment]
works for me locally. need to test on prod

**Comment by anhnt** [comment]
works on prod as well http://admin.anhnt.olhub.com/points-buckets/anh-test/#debits-tab
Can you confirm @Uafinder

**Comment by Uafinder** [comment]
Not sure if i right, here is steps:
1. Setup expiration date for points bucket
![image](https://cloud.githubusercontent.com/assets/1945230/16593929/76ef4354-42f0-11e6-89dd-64715cbf385c.png)
2. Award some points to a user
![image](https://cloud.githubusercontent.com/assets/1945230/16593998/dae38cda-42f0-11e6-9b61-9d04f31ad9f2.png)
3. Watch that there is no expiration date
![image](https://cloud.githubusercontent.com/assets/1945230/16594025/00b2f4a0-42f1-11e6-8dc8-e681134107d9.png)

**Comment by bradmac** [comment]
The expiry date for a points record only gets set when that points record expires. That means in the example above the points records will only expire after 21/7/2016
