### ISSUE TITLE
Valid for days and choose an expiration date fields cannot be specified at the same time

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#2067]
![image](https://cloud.githubusercontent.com/assets/1945230/16465069/ad77edc2-3e45-11e6-945c-55966d1a2a3e.png)
there should be some kind of validation, or some sort.

**Comment by anhnt** [comment]
Now when **Valid for days** field has value, the **Choose an expiry date** field will be disabled and has empty value. If you want to enable **Choose an expiry date** and set value for it, just clear value of **Valid for days**

**Comment by hoanglinhlan** [comment]
passed
