### ISSUE TITLE
points upload couldn't add new points record

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#2069]
![image](https://cloud.githubusercontent.com/assets/1945230/16465353/e522e802-3e46-11e6-8c08-b62756d3da2c.png)
I am uploading a valid CSV file and receive message that it can't match my points by ID, which means it should add it i think

**Comment by bradmac** [comment]
No, if you give an explicit row ID then it will look for that row to update. If you want to insert the id needs to be blank
