### ISSUE TITLE
kcrm: event label color on dashboard

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#2071]
![image](https://cloud.githubusercontent.com/assets/1945230/16466173/cc86da84-3e4a-11e6-9570-65f4ec9eec86.png)
The red label on the blue background makes my eyes to feel unlucky :)
How do you think, should it be changed?

**Comment by bradmac** [comment]
@paddyow please suggest appropriate brand colours (for this and other themes)

**Comment by paddyow** [comment]
The blue is correct, make the red text white.

**Comment by bradmac** [comment]
Hey @paddyow the text is red because its a link, and the link colour is by default the @brand-primary colour. We cant change each page for each theme, so really we need a colour pallette that works together.
