### ISSUE TITLE
Queued triggers stats vary 

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2081]
http://admin.rspca-sa.olhub.com/autoEmails/ (RSPCA SA) Folder

I took screenshots over 5 mins and noticed that queued trigger numbers would vary as I refresh the screen.

Screenshot 1:
![image](https://cloud.githubusercontent.com/assets/2201340/16572323/cc695ce8-42aa-11e6-81e4-bfe56203c329.png)

Screenshot 2:
![image](https://cloud.githubusercontent.com/assets/2201340/16572331/d847a06a-42aa-11e6-95de-628d34c83103.png)

Screenshot 3:
![image](https://cloud.githubusercontent.com/assets/2201340/16572334/dd2ad840-42aa-11e6-88d7-e18de228ea70.png)

**Comment by bradmac** [comment]
Yes, because items in the queue will be getting processed.

**Comment by bradmac** [comment]
But its a bad sign that its retrying so many
