### ISSUE TITLE
Allow filtering by form type on contact requests page

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2084]
The manage contact requests page should have filter options like on manage users, to restrict by form type.

http://localhost:8080/manageContacts/

![image](https://cloud.githubusercontent.com/assets/826458/25785598/f00fca72-33d8-11e7-81b5-871325897f79.png)

**Comment by gonzalon** [comment]
@diegoperezn Can you review it please?

**Comment by bradmac** [comment]
@gonzalon the form paths stuff is wrong.

Currently you're doing a DB query across all customers.
```
    public List<String> getFormTypes(){
        return ContactRequest.findFormPaths(SessionManager.session());
    }
```

This means customers are seeing form paths from other customers!

ALSO, this should not be using a DB search at all, it should be using Elasticsearch

There is already a call to ES on /contactRequestSearch so please just add an aggregation to that

**Comment by gonzalon** [comment]
Updated

**Comment by bradmac** [comment]
Cant see any form paths appearing..

![image](https://cloud.githubusercontent.com/assets/826458/26080598/70fafc18-3a1b-11e7-911f-c5080129e370.png)

**Comment by bradmac** [comment]
Note that the correct data is returned in the JSON response:

![image](https://cloud.githubusercontent.com/assets/826458/26080635/9d8c0010-3a1b-11e7-8270-5977787ca2c3.png)

**Comment by hoanglinhlan** [comment]
it still doesn't show form types
https://lan-test.admin.kademi.com.au/manageContacts/?search=&startDate=29%2F05%2F2016&finishDate=29%2F05%2F2017&acked=false

**Comment by gonzalon** [comment]
@hoanglinhlan the data doesn't have any form type in that request =/
![image](https://cloud.githubusercontent.com/assets/2773216/26562188/b0742cd2-449a-11e7-90c4-d83978540d3a.png)

**Comment by bradmac** [comment]
@hoanglinhlan please quote the contact pages you were using to test with, and confirm that contact requests are being created

**Comment by hoanglinhlan** [comment]
set contact path and checked 
passed
