### ISSUE TITLE
Bulk update organisation geo-location

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2085]
Currently when you edit an organisation you can specify an address. You can then search google maps for it and select a location to set the organisation geo-location (ie coordinates)

But there is no way to do that in bulk. A client will be loading a list of 100+ organisations with addresses and it would be good if there was a way to automatically set the geo-location for all of them.

Please create a custom app (available in the syd cluster) which lists all organisations and provides a button which will query google maps for each organisation that has an address, and set its geo-location to be the first matching result

**Comment by anhnt** [comment]
http://waterco.admin.kademi.com.au/orgGeolocation/
