### ISSUE TITLE
Existing profiles when uploading data

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2086]
@bradmac when it says Existing Profiles - does this mean in the data file or in the Kademi account?

![image](https://cloud.githubusercontent.com/assets/2201340/16610553/427f512c-439f-11e6-9933-8586cdcaf232.png)

**Comment by bradmac** [comment]
New profiles: rows where no existing profile was found, so a new one will be created
Existing profiles: rows where an existing profile was found, so will be updated
