### ISSUE TITLE
Import button

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2087]
http://admin.developer.olhub.com/manageUsers/

Step 3: Import

User should not be able to click the Next button as this does nothing and becomes confusing.  The only button they should press is the Import button to move on.

![image](https://cloud.githubusercontent.com/assets/2201340/16610605/a27ac7be-439f-11e6-86ba-7f72e53a8f79.png)

**Comment by bradmac** [comment]
I think the next button should do the same thing as "Import now"

**Comment by Uafinder** [comment]
Looks like validation was added. User can press next button, but he will see a warning message.
So probably it can be closed
