### ISSUE TITLE
Data not importing

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2089]
Data did not import with the following:

This admin account: http://admin.developer.olhub.com/manageUsers/
This data: [Excel1.xlsx](https://github.com/Kademi/kademi-dev/files/349268/Excel1.xlsx)
This group: http://admin.developer.olhub.com/groups/dt1/members/
This config:
![image](https://cloud.githubusercontent.com/assets/2201340/16610768/bd1e191c-43a0-11e6-8dc9-436ef996cce0.png)

**Comment by paddyow** [comment]
Note I updated the emails in the Excel document so they don't append a number after the .com and is failed.

**Comment by Uafinder** [comment]
Well, it looks validation works on the email mask. When email contains a digit after "com" import fails. But if  digits were removed import was successful.

**Comment by bradmac** [comment]
So @Uafinder are you saying there is no problem to resolve?

**Comment by Uafinder** [comment]
As far as i understand there was a problem with importing those xls file. I've succeed several times.
