### ISSUE TITLE
Make bs336 page templates compatible with content editor

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2095]
Eg, here is the profile page template

![profile-editor](https://cloud.githubusercontent.com/assets/826458/16754281/2261c67c-4845-11e6-80cb-29eec180b586.png)

**Comment by bradmac** [comment]
Using a new templater so we dont need velocity template tags in the template. They get stripped out when saving from the editor

**Comment by bradmac** [comment]
Have done:
- theme/home.html
- theme/page.html
- theme/apps/user/profile.html
- theme/apps/user/dashboard.html

**Comment by anhnt** [comment]
Signup app is done

**Comment by anhnt** [comment]
closing it and move to https://github.com/Kademi/kademi-dev/issues/2301
