### ISSUE TITLE
Customer journey builder: Use content editor look and feel

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2112]
The node palette should have the same layout as the content editor, ie flush right, full height, with a visual for each node and hover text description. Should only be one list though (ie not 2 lists for containers and components.

Node details should show in a side panel form like component settings do, instead of navigating away from the main page to edit details. Note that we will also need a full details links which will show a full page for the node, so we can edit email content and see stats, etc

**Comment by bradmac** [comment]
Note that we need 2 forms for each node
- brief settings for the side panel
- full page details

To do this we can use a standard parameter, eg
http://localhost:8080/funnels/nurture2/action-9bae81?renderSettings

This will be checked in the template, and if present only render the basic settings, and the funnel page will extract that section with a standard ID or class.

If that parameter is not present then render the full page

**Comment by ducdhm** [comment]
Just need update form details for each of node type

FYI: The element which is loaded in Details panel in Right Panel need `id="frmDetails"`
