### ISSUE TITLE
Timeout value to be specified in multiple units

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2115]
Currently the timeout value is just in minutes, and this is the value that gets stored.

Most users will specify the value in days, but it would also be good to allow entry as weeks, months and years.

**Comment by bradmac** [comment]
The Goal class now has 2 properties
- timeoutMultiples
- timeoutUnits

These can be used together to make user friendly intervals like 2 days, 3 weeks, etc.

The timeoutUnits should be displayed with user friendly text values like "Day", "Week". But the coded values should be standardised. I suggest we use the values used by moment.js:
http://momentjs.com/docs/#/durations/

Key 	Shorthand
years 	y
months 	M
weeks 	w
days 	d
hours 	h
minutes 	m

**Comment by ducdhm** [comment]
See in EmailResultGoal node as example.

**Comment by ducdhm** [comment]
@hoanglinhlan Please ask me if you have any questions when testing

**Comment by hoanglinhlan** [comment]
passed
