### ISSUE TITLE
Component attributes are not initialized at the first time 

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#2119]
ComponentBean.add(allComponents,
            "signup/components", "registerForm",
            "Display signup form",
            ComponentBean.att("show-optins", "true").add("show-orgs", "true")

those attributes are null when first load

**Comment by ducdhm** [comment]
@anhnt You should add it in html. It will be added if you drag and drop it

**Comment by ducdhm** [comment]
There are 2 cases:
1. Component is ready in html. Based on data-* attribute of HTML tag to getting attributes
2. Component is added by drag and drop. Attributes of component will be default value in Java code

**Comment by bradmac** [comment]
:+1:

**Comment by anhnt** [comment]
This is the case: when user wants to edit stock template in content editor: 

**user/register.html**

    <section>
            <div class="container-bg">
                <div class="container-content">
                    <div class="row">
                        <div class="col-sm-12" data-type="container-content">
                            <section data-type="component-registerForm">
                                <div data-dynamic-href="_components/registerForm"></div>
                            </section>
                        </div>
                    </div>
                </div>
            </div>
        </section>

so keditor should load all attributes with default values for it which are defined in java. We definitely dont want to manually set it by adding `data-attr ` in html code. It should be loaded from server

**Comment by bradmac** [comment]
@anhnt the component is already placed, so whatever attributes it defines will be used. Best thing is just to set whatever attributes you want in the stock template

**Comment by anhnt** [comment]
:+1:
