### ISSUE TITLE
Cannot delete blog category

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2124]
http://kademi.admin.olhub.com/blogs/kb/

![image](https://cloud.githubusercontent.com/assets/2201340/16860940/b1f46196-4a7f-11e6-8049-b988968f1ae3.png)

Unable to scroll down.  The dropdown seems to open in the nested window and not the parent.

This also happens on the manage website page when you click on the bottom row dropdown button.
http://kademi.admin.olhub.com/websites/

![image](https://cloud.githubusercontent.com/assets/2201340/16860957/d4523a60-4a7f-11e6-940f-444003bc5444.png)

**Comment by gonzalon** [comment]
The push fix "Category" and "Tag" in the blog editing.

Couldn't reproduce the one in /websites

**Comment by hoanglinhlan** [comment]
confirm it's work now 
Cant reproduce this issue
