### ISSUE TITLE
Show points transactions on organisation page

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2128]

**Comment by bradmac** [comment]
Needs a tidy up. Hide balance calculator by default

**Comment by bradmac** [comment]
Eg
http://carters.admin.kademi.com.au/organisations/11512357/edit

![screenshot-carters admin kademi com au 2016-08-03 14-38-29](https://cloud.githubusercontent.com/assets/826458/17352080/fcbe4658-5987-11e6-8b6e-65dde443faa5.png)

**Comment by hoanglinhlan** [comment]
passed
