### ISSUE TITLE
viewTriggerTimers page is still using its own date range selector

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2129]
Should be using the common date range selector

See apps/email/viewTriggerTimers.html

**Comment by hoanglinhlan** [comment]
all page is ok, but in autions page I could'n saw the timer 
Pls check again

**Comment by anhnt** [comment]
there's no timer in auction page. i think you mean the date range picker @hoanglinhlan

**Comment by hoanglinhlan** [comment]
@anhnt yeap, It's mean the date range picker

**Comment by anhnt** [comment]
closing it now https://github.com/Kademi/kademi-dev/issues/2152
