### ISSUE TITLE
Wrong URL when click view website 

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2132]
http://lan.admin.olhub.com/websites/
**Desc**:
On Manage websites: click on Eye button to view Website 
On Configure pages: click on "View website" button 

**Expect**: show dashboard page (ex: http://version1.lanhl.olhub.com/dashboard)
**Actual**: show page http://version1.lanhl.olhub.com

**Comment by bradmac** [comment]
I think the view button on both should go to the home page. The configure page has a dropdown with options for other pages
