### ISSUE TITLE
Off for public switch for website missed color

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#2133]
![image](https://cloud.githubusercontent.com/assets/1945230/16925001/bfd018ac-4d2a-11e6-907c-4a747e8a41a0.png)

![image](https://cloud.githubusercontent.com/assets/1945230/16925062/1313216c-4d2b-11e6-8b7f-4823aebc5d85.png)

**Comment by bradmac** [comment]
I think thats ok. The neutral colour is good, a red would be overpowering.
