### ISSUE TITLE
Points balance report

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2134]
- histogram showing distribution of balances. Maybe log distribution?
- filter on screen by range
- filter by parent org
- export to csv

Note: see points balance component

**Comment by bradmac** [comment]
@tuzzmaniandevil please sort detailed items by points balance.

**Comment by tuzzmaniandevil** [comment]
Done

**Comment by hoanglinhlan** [comment]
1: filter by parent org ==> not yet done, It should be like on manage users page
2: excessive "report entity" dropdown
3: Point balance display incorrect
![image](https://cloud.githubusercontent.com/assets/20508726/19720657/51450a4c-9b99-11e6-8159-717066dbbb1f.png)

4: filter by range not working: I have 2 items in range 0-100 but after select range 0-100, the system display 0 items
![image](https://cloud.githubusercontent.com/assets/20508726/19720755/ad483b84-9b99-11e6-9781-b93855f1ed33.png)

**Comment by AlaaKhalaf94** [comment]
Hi @gonzalon 
Can you give me links to test, where can I see these?

**Comment by bradmac** [comment]
@AlaaKhalaf94 this is on the Reports page, the Points Ballance Report

![image](https://user-images.githubusercontent.com/826458/28411955-a83c49da-6d96-11e7-8bfe-2d861fc9ba48.png)

**Comment by AlaaKhalaf94** [comment]
http://alaa-test.admin.kademi-prod.com/reporting/pointsBalance?term-range=&term-orgs=watch

1- Filter by range shows wrong information
![capture3](https://user-images.githubusercontent.com/26510030/28418117-454e68c2-6d63-11e7-8139-7f1fec91a89a.PNG)
![capture4](https://user-images.githubusercontent.com/26510030/28418120-4921719c-6d63-11e7-980e-de1c69b7f9c7.PNG)

2- Filter by parent org does not work
![capture5](https://user-images.githubusercontent.com/26510030/28418188-8e57b9c4-6d63-11e7-9653-907a1da1e91f.PNG)

And I delete all records from points buckets ,to test clearly then I make re-index
but there are some records I can not delete them , please chick
Points Buckets: http://alaa-test.admin.kademi-prod.com/points-buckets/
re-index: http://alaa-test.admin.kademi-prod.com/manageSearch/

http://alaa-test.admin.kademi-prod.com/manageSearch/rewardpoints/
![capture6](https://user-images.githubusercontent.com/26510030/28418389-2f7664cc-6d64-11e7-939a-6897601258e2.PNG)

http://alaa-test.admin.kademi-prod.com/manageSearch/rewardEntries/
![capture7](https://user-images.githubusercontent.com/26510030/28418404-41087504-6d64-11e7-860d-d1f3545cccb9.PNG)

http://alaa-test.admin.kademi-prod.com/manageSearch/rewardstore/
![capture8](https://user-images.githubusercontent.com/26510030/28418437-5deb7b9e-6d64-11e7-948a-5b5655244713.PNG)

**Comment by AlaaKhalaf94** [comment]
@gonzalon Everything is as it is !

Note : I've clear caches

**Comment by gonzalon** [comment]
@AlaaKhalaf94 I just test it, fixed another bug, and everything seems to be working fine.
After deploy, could you please test it in a new account?

**Comment by AlaaKhalaf94** [comment]
passed
