### ISSUE TITLE
Blog post content editor is broken 

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#2136]
![image](https://cloud.githubusercontent.com/assets/735555/16937652/107a05e0-4d9b-11e6-9cab-1c45edf6ac97.png)

**Comment by bradmac** [comment]
Fixed.

**Comment by bradmac** [comment]
@hoanglinhlan please check that blog article editing and web page editing are working correctly with the drag/drop editor.

**Comment by hoanglinhlan** [comment]
![image](https://cloud.githubusercontent.com/assets/20508726/18460668/915294e2-799d-11e6-982b-2a84472c9bb6.png)
confirm drag/drop editor worked ok
