### ISSUE TITLE
GUI: wrong responsive on kademi.co

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2138]
http://www.kademi.co/
do not scroll down 
wrong responsive: refer img kademi.co.responsive01.png
wrong responsive when click button search kademi.co.responsive01.png
<img width="960" alt="kademi co responsive01" src="https://cloud.githubusercontent.com/assets/20508726/16942981/56cf895c-4dc3-11e6-909c-e3d8ddde48c4.png">
<img width="960" alt="kademi co responsive02" src="https://cloud.githubusercontent.com/assets/20508726/16942982/56d4f86a-4dc3-11e6-9539-02a96768051e.png">

**Comment by mamun4343** [comment]
@hoanglinhlan this is fixed! please check!
