### ISSUE TITLE
Loss parent category after refresh page

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2139]
http://emc.admin.olhub.com/categories/
**Desc**: step
- Edit a category, set parent category for this. 
- Refresh page

**Expected**: keep parent category
**Actual**: their update was gone ( parent category set none)

**Comment by bradmac** [comment]
Seems to only happen when parent category has special characters in its code

**Comment by hoanglinhlan** [comment]
Confirm set and save parent category ok
