### ISSUE TITLE
Be able to filter leads

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2140]
On the leads page be able to filter by tags

(BM: removed dashboard filtering requirement)

**Comment by tuzzmaniandevil** [comment]
@anhnt Can you do the UI please? Currently i'm using this http://davidstutz.github.io/bootstrap-multiselect/

**Comment by bradmac** [comment]
hey guys, dont use any fancy stuff. just do it the same as on the manage users page

**Comment by bradmac** [comment]
@anhnt it would be good to make this a pulldown filter list like github uses on the issues page so we have maximum screen area for displaying leads. But use the same display styles as manage users etc.

**Comment by anhnt** [comment]
just added a dropdown like following:
![image](https://cloud.githubusercontent.com/assets/735555/17132515/51f06152-534c-11e6-8944-e295975b10ea.png)

@tuzzmaniandevil please check my skype message for detail. The ES query is not working correctly at the moment.

**Comment by bradmac** [comment]
@anhnt please use a similar layout as github issues:
![screenshot-github com 2016-07-26 21-20-12](https://cloud.githubusercontent.com/assets/826458/17132821/84163f82-5377-11e6-9243-f1dbdbd224bb.png)

Also please remove the stats panel

**Comment by bradmac** [comment]
And please add a couple of extra filtering options for assigned to and source. So we can then filter by
- team
- tags
- assigned to
- source

**Comment by tuzzmaniandevil** [comment]
@anhnt Woops you are right :-) https://github.com/Kademi/kademi-dev/issues/2140#issuecomment-235209823 is now fixed

**Comment by tuzzmaniandevil** [comment]
@Brad should those filters also be multi select?

**Comment by bradmac** [comment]
Yes

**Comment by tuzzmaniandevil** [comment]
@anhnt I've done the Java side, Use the following params:
 - assigned to - assignedTo = Should be an array of profile id's
 - source to - sources = Should be an array of sources

We all ready filter by team and tags

**Comment by anhnt** [comment]
@hoanglinhlan its ready for testing now. can you please help :)

**Comment by hoanglinhlan** [comment]
Source dropdown has not any value 
![2140_sourcevalue](https://cloud.githubusercontent.com/assets/20508726/17168422/896e90ca-540c-11e6-97c5-5f28af1b9ab5.png)

**Comment by anhnt** [comment]
fixed in latest commit

**Comment by hoanglinhlan** [comment]
**Question**: When I creating a new lead, Source item is not require, so in list lead we have some lead what has blank source. ==> how to filter only leads have blank source

**Comment by anhnt** [comment]
i think source should be required

**Comment by bradmac** [comment]
@anhnt The source cannot be required. This is sort of like a milestone in github issues, the user should be able to search for leads with no source. @tuzzmaniandevil might need to add server side support for searching for leads with no source

**Comment by hoanglinhlan** [comment]
@tuzzmaniandevil

**Comment by tuzzmaniandevil** [comment]
Added an option called "NOSOURCE", When we get a source with that name we will include leads that don't have a source.
@anhnt Please can you add a static option with the value "NOSOURCE" to the Sources dropdown? And maybe with the text: "Leads with no source"

**Comment by anhnt** [comment]
done 
![image](https://cloud.githubusercontent.com/assets/735555/26614853/f8ebcf94-45ec-11e7-9ae6-32418369d785.png)
