### ISSUE TITLE
Edit funnel properties

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2143]
Extension to https://github.com/Kademi/kademi-dev/issues/1627

Users need to be able to edit funnel properties in the funnel management screen
- title;
- leadsGroup;
- defaultInitialGoal;
- sources;
- stages; // a sequential list of stages, eg cold->warm->hot
- extraFields
- lostReasons
- customerActivities; // a list of suggested activities for customer acvtiies, each call, email, etc
- funnelTesters; // a set of rules for test accounts to be handled differnty for testing purposes

These can be dealt with later
- closedActions; // actions to execute when a lead is closed, ie won
- cancelledActions; // actions to execute when a lead is cancelled, ie lost

**Comment by bradmac** [comment]
Couple of changes
- please make the group a select box with a list of groups
- remove "Default Initial Goal"

**Comment by bradmac** [comment]
Stages are not saving. 
- add a stage
- save
- refresh page
- stages list is empty

**Comment by ducdhm** [comment]
Done!

**Comment by hoanglinhlan** [comment]
passed
