### ISSUE TITLE
Jouney Builder: Cannot edit decision choices

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2146]
The decision node has an expression property. Just allow entering a MvelExpression, which is just a textarea

Each choice is an expression and a key. The key should be internally generated and not user editable. The choice expression should be

**Comment by ducdhm** [comment]
@bradmac Please help me add handler for custom type. Example: Type of `expression` is `Expression` button the value which I POST to server is `String`

**Comment by ducdhm** [comment]
Done!
