### ISSUE TITLE
JSON database: Could not save utf8 string

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#2150]
I created a record with following json string:
`{"title": "Nguyễn Tuấn Anh"}`

but it saved as following:
`{"title": "Nguy?n Tu?n Anh"}`

test url: http://admin.anh.kademi.com.au/jsondb/anhapiDB/utf8test

**Comment by gonzalon** [comment]
Seems this is working for me, @anhnt can you confirm?

![image](https://user-images.githubusercontent.com/2773216/33973424-ac95ae3a-e0e7-11e7-8218-f93bc91ad364.png)

**Comment by anhnt** [comment]
Looks great now
