### ISSUE TITLE
Error when updating quantity in checkout page

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#2151]

**Comment by ducdhm** [comment]
Seems like it's server side issue. Example:
 * Current quantity is 23
 * I change to 24
 * **Expected**: 24
 * **Actual**: 47

**Comment by bradmac** [comment]
No, its front end. If you refresh the page you actually see the correct value displayed.

Removing the call to trigger('change') in line 98 of checkout.js fixes it, but then editing the text box directly doesnt work.

So i think the logic just needs to be refactoring slightly.

**Comment by ducdhm** [comment]
@bradmac Can you double-check again? I used the same code with ecommerce-demo site and it's working (http://ecommerce-demo.olhub.com/storeCheckout/)

```
No, its front end. If you refresh the page you actually see the correct value displayed.

Removing the call to trigger('change') in line 98 of checkout.js fixes it, but then editing the text box directly doesnt work
```
It's cached value, not real value of input. If you dont trigger the change event of input, when you press `-` or `+`, it's just update value only on input, not on server

**Comment by bradmac** [comment]
@ducdhm I'm pretty sure it is a front end issue. The server side just sets the quantity its given, and I confirmed that the front end does submit the correct value.

Refreshing the front end shows the correct value, so its not just caching

**Comment by bradmac** [comment]
If you think it is server side, just put a breakpoint in ShoppingCartResource line 166 and verify if the correct quantity is being used

**Comment by bradmac** [comment]
```
            } else if (parameters.containsKey("changeItemHrefQuantity")) {
                String itemHref = WebUtils.getRawParam(parameters, "changeItemHrefQuantity");
                Integer quantity = WebUtils.getParamAsInteger(parameters, "quantity");
                updateItemQuantity(itemHref, quantity);
```

And you can check the final value being written to the cookie in line 408
```
        items = String.join(",", itemHrefs);   <<-- check this
        byte[] enc = Base64.encode(items.getBytes(WebUtils.UTF8));
        items = new String(enc);
        HttpManager.response().setCookie("shoppingCart", items);
```

**Comment by ducdhm** [comment]
@bradmac At line 394, it's adding current quantity with update quantity
```
               boolean b = false;
                for (String s : itemHrefs) {
                    if (s.startsWith(itemHrefClean + ITEM_HREF_SEPERATOR)) {
                        itemHrefs.remove(s);
                        Integer hrefCount = f.toInteger(s.substring(s.lastIndexOf(ITEM_HREF_SEPERATOR) + 1));
                        String it = itemHrefClean + ITEM_HREF_SEPERATOR + (hrefCount + quantity);
                        itemHrefs.add(it);
                        b = true;
                        break;
                    }
                }
```
