### ISSUE TITLE
Manage Auctions page to support filtering by date range

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#2152]

**Comment by anhnt** [comment]
I implemented feature which allows filtering auctions by global date range. At the moment it is filtered by field ```createdDate```

**Comment by hoanglinhlan** [comment]
it's not working now
I choose 7 day ago from date range but in autions table, it's showing autions from 3 month ago
https://lan-test.admin.kademi.com.au/auctions/?state=closed
![image](https://user-images.githubusercontent.com/20508726/27169603-b951e7b2-51d4-11e7-8199-9564e2f5c5da.png)
