### ISSUE TITLE
Product image upload error

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2155]
Customer uploaded these images:

![austww12m](https://cloud.githubusercontent.com/assets/2201340/17233873/09452442-5577-11e6-824f-08397271e2e6.jpg)
![farmtrader12m](https://cloud.githubusercontent.com/assets/2201340/17233874/09460164-5577-11e6-85a0-662afaba7bf7.jpg)

Here: http://emc.admin.kademi.com.au/product-images/

And got this error but the images were uploaded.

![error](https://cloud.githubusercontent.com/assets/2201340/17233892/2e684d30-5577-11e6-9c3e-5db352075419.png)

Please try to re-create.

**Comment by hoanglinhlan** [comment]
hi @paddyow 
I re-produced with lastest version of source code (commit 4d6e76f), and it's a bug.

**Comment by ducdhm** [comment]
@paddyow If you want to upload photo for a product, there is 2 ways
1. Access **Product Images** page and upload a photo. Make sure photo name is **SAME** with productId
2. Access **Product Detailed** page and upload a photo.

In your case, you did the first way but the file name is **09452442-5577-11e6-824f-08397271e2e6**. There is no product with id like this.

**Comment by ducdhm** [comment]
@paddyow You can hover the image for seeing the error message and get more details

**Comment by bradmac** [comment]
@ducdhm  i think the name that you saw is generated by github. Its not the actual name of the file

**Comment by ducdhm** [comment]
@hoanglinhlan Please confirm is this issue fixed or not

**Comment by hoanglinhlan** [comment]
I just test with comment by Duc. it's ok

**Comment by paddyow** [comment]
I just uploaded this image (in the ZIP) by dragging it:

[test.zip](https://github.com/Kademi/kademi-dev/files/405990/test.zip)

To here: http://emc.admin.kademi.com.au/product-images/

Got the red cross on the image:

![image](https://cloud.githubusercontent.com/assets/2201340/17469158/212c7832-5d72-11e6-8c88-d052dd310763.png)

**Comment by bradmac** [comment]
@paddyow the image is called "test.jpg" but there is no product with code "test"

**Comment by paddyow** [comment]
Just tried another file name test135p.jpg and it still failed.

**Comment by bradmac** [comment]
It needs to match a product code.

**Comment by paddyow** [comment]
Aha! Done worked :) Maybe we add some text saying: "Image file names much match an existing product with the same name or the image will not be uploaded." @bradmac

**Comment by bradmac** [comment]
@ducdhm can you please
- Add the following copy above the dropzone: "Please upload image files with the same name as the product code you want them attached to, with an extension. For example, to upload an image to product with SKU ABC-123 you could upload a file called "ABC-123.png"
- Display errors below the dropzone, as well as on hover on the dropzone icons

**Comment by ducdhm** [comment]
It's ok for you?

![222222222222222222222222](https://cloud.githubusercontent.com/assets/1289631/17469794/db715274-5d60-11e6-8795-563d93d32feb.png)

**Comment by ducdhm** [comment]
New finale UI:
![4444444444444](https://cloud.githubusercontent.com/assets/1289631/17469978/ae64ce9e-5d62-11e6-975e-53e958dfdb90.png)

**Comment by hoanglinhlan** [comment]
worked pass
