### ISSUE TITLE
Cannot edit org type

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2156]
- Create an organisation type
- Create an organisation
- Click to edit the organisation
- There is no field to change the organisation type

**Comment by anhnt** [comment]
can add or remove org type here
![image](https://cloud.githubusercontent.com/assets/735555/17283478/1f5a5db8-57db-11e6-81b4-31471d4c836b.png)

**Comment by hoanglinhlan** [comment]
confirm fixed
