### ISSUE TITLE
Cannot add team member using teams app

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2157]
- logged in here http://vtlcrm.kademi.com.au/team/ as this user http://vtl.admin.kademi.com.au/manageUsers/19834783/
- Attempted to add a new team member
- Got error
![screenshot-vtlcrm kademi com au 2016-08-01 13-58-07](https://cloud.githubusercontent.com/assets/826458/17281386/16332890-57f0-11e6-889f-ddd8c38112c5.png)

**Comment by tuzzmaniandevil** [comment]
This is because no group was selected, and no groups are showing on the modal because no team groups have been setup :-)

**Comment by bradmac** [comment]
OK, we need a meaningful error message.

**Comment by tuzzmaniandevil** [comment]
Though I just found a bug when selecting the team groups.

**Comment by tuzzmaniandevil** [comment]
I've added a field error. So will tell you that a group is now required :-)

**Comment by bradmac** [comment]
And there should be a meaningful error that the app is not configured, if configuration is missing

**Comment by tuzzmaniandevil** [comment]
Added an alert to the modal saying:
`No team groups have been configured, Please configure Teams groups in the admin console.`

**Comment by hoanglinhlan** [comment]
I created success ( mess: member added)
but I can't see this member in table
![teampage-newmember](https://cloud.githubusercontent.com/assets/20508726/17324866/b7d28212-58d2-11e6-9aa0-68b5e4c49c58.png)

**Comment by tuzzmaniandevil** [comment]
Very weird as no team groups have been setup. So could be a caching issue for you. I see this which is correct:
![screenshot from 2016-08-03 11-03-13](https://cloud.githubusercontent.com/assets/3378330/17348378/e692a824-5969-11e6-8993-cf24ccf23fcc.png)

and after setting up the team groups I see this:
![screenshot from 2016-08-03 11-04-42](https://cloud.githubusercontent.com/assets/3378330/17348411/2102bf30-596a-11e6-92f3-07b18d15d0f0.png)
And
![screenshot from 2016-08-03 11-04-56](https://cloud.githubusercontent.com/assets/3378330/17348421/2fc813b2-596a-11e6-84ca-0c94cb3c9a9e.png)

@hoanglinhlan  Please can you re-test?

**Comment by tuzzmaniandevil** [comment]
Found the reason as to why user's weren't showing up. Incorrect query when searching for users.

**Comment by hoanglinhlan** [comment]
Fixed :+1:
