### ISSUE TITLE
Error displaying donut map in KCRM

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2158]
- logged in as this user http://vtl.admin.kademi.com.au/manageUsers/19834783/#summary-tab
- to this KCRM http://vtlcrm.kademi.com.au/dashboard
- there is an error displayed in the map on the dashboard
- js logs say the gmaps key is invalid. 

I dont know where the key is configured

**Comment by ducdhm** [comment]
Now we have variable name `$googleMapKey` in `masterTemplate.html` for config gmap key

**Comment by ducdhm** [comment]
Deployed!

**Comment by hoanglinhlan** [comment]
Display donut ok
