### ISSUE TITLE
Uploading organisations CSV did not update orgs index

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2159]
Saw issue in this account:
http://vtl.admin.kademi.com.au/

- I manually created 4 orgs (3 regions and 1 dealer), and then uploaded a spreadsheet of dealers. 
- Checked the search index page and saw only 4 items in the orgs index
- Reindexed and all 15 appeared

**Comment by tuzzmaniandevil** [comment]
Fixed, Also fixed it when an org is removed it wasn't removing it from the index.
