### ISSUE TITLE
Create record via history tab

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#216]
1. When you click here
![image](https://cloud.githubusercontent.com/assets/1945230/6491781/3669f6da-c2b8-11e4-8c1f-97ce133ff58f.png)
you've got this modal window, which should be not KPI edit level modal.
![image](https://cloud.githubusercontent.com/assets/1945230/6491809/8b97d64a-c2b8-11e4-98a9-bd4b6d3fad92.png)

2. Additional field doesn't save when you saving record.

**Comment by bradmac** [comment]
@tuzzmaniandevil fixed the extra field saving problem a while ago, i just fixed the title now
