### ISSUE TITLE
Leads org search is using the wrong setting

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2160]
When logged in as this user:
http://vtl.admin.kademi.com.au/manageUsers/19834783/#summary-tab

This returns no results:
http://vtlcrm.kademi.com.au/leads?orgSearch=dealer

But there are several organisations beginning with 'dealer' and with the org type specified for leads in the leadman settings.

It appears the org search is searching for the sales org type instead of lead org type.

**Comment by bradmac** [comment]
Also updated when creating a lead

**Comment by hoanglinhlan** [comment]
confirm work ok
