### ISSUE TITLE
Tags list should be in one row

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2167]
Please move the list of tags up to be in a row with the add tags button
![screenshot-vtlcrm loopbackdns com 8080 2016-08-02 11-21-44](https://cloud.githubusercontent.com/assets/826458/17311983/76149038-58a3-11e6-90c2-f7dafbbf015b.png)

**Comment by ducdhm** [comment]
New UI: ![bbbbbbbb](https://cloud.githubusercontent.com/assets/1289631/17339512/78e1878a-5916-11e6-81a2-1eaec6570f20.png)
