### ISSUE TITLE
KCRM menu layout breaks on medium resolution

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2168]
![screenshot-vtlcrm loopbackdns com 8080 2016-08-02 11-28-12](https://cloud.githubusercontent.com/assets/826458/17312088/40acdf4e-58a4-11e6-905e-ab53e4d13927.png)

**Comment by ducdhm** [comment]
Navbar in breakpoints: 
![aaaaaaaaaaaaaaaaaaaaaaaaa333333333](https://cloud.githubusercontent.com/assets/1289631/17340126/1e48cb28-5919-11e6-8869-195161033c5c.png)
