### ISSUE TITLE
KCRM Funnel does not count leads without a source

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2169]
I have 3 leads loaded, where only one has a selected source. But on the analytics page it only shows 1 lead in the funnel

![screenshot-vtlcrm loopbackdns com 8080 2016-08-02 12-28-53](https://cloud.githubusercontent.com/assets/826458/17313075/b9fd114a-58ac-11e6-9091-ec8d5f025cc3.png)

All 3 leads are in the returned json. From firebug:

stages  
    [Object { sources=[0],  name="cold",  count=2,  more...}, Object { sources=[1],  name="warm",  count=1,  more...}, Object { sources=[0],  name="hot",  id=null,  more...}]

```
Object { sources=[0],  name="cold",  count=2,  more...}

Object { sources=[1],  name="warm",  count=1,  more...}

Object { sources=[0],  name="hot",  id=null,  more...}
```

**Comment by hoanglinhlan** [comment]
Failed
I have 5 lead 
![image](https://cloud.githubusercontent.com/assets/20508726/19418387/1002ac82-93ed-11e6-9469-109677b2ca04.png)

But Wrap shows 4 lead 
![image](https://cloud.githubusercontent.com/assets/20508726/19418397/3bf5b1e0-93ed-11e6-947f-9b671755b424.png)

**Comment by hoanglinhlan** [comment]
And still does not count leads without a source
