### ISSUE TITLE
KCRM Lead page banner image should be flush left and top

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2170]
![screenshot-vtlcrm loopbackdns com 8080 2016-08-02 12-24-45](https://cloud.githubusercontent.com/assets/826458/17313258/2463062e-58ae-11e6-9f47-0e420f47e21d.png)

There should be no gap to the top or sides of the banner image. The image should have inner padding so the buttons and avatar icon inside the image stay where they are now, ie are vertically aligned with controls below the image

**Comment by ducdhm** [comment]
New UI: 
![aa](https://cloud.githubusercontent.com/assets/1289631/17317550/3d954c24-58a9-11e6-9088-a012b3dd7b83.png)

**Comment by bradmac** [comment]
Perfect

**Comment by hoanglinhlan** [comment]
confirm fixed
