### ISSUE TITLE
KCRM dashboard map does not show stats from sub-teams

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2171]
A sales manager should see stats from the teams under them. For example, for VTL the head of sales should see donuts representing each office with its number of leads. But currently it looks like this, because its not including sub-teams, ie an empty map

![screenshot-vtlcrm kademi com au 2016-08-02 15-25-16](https://cloud.githubusercontent.com/assets/826458/17316129/867e03ba-58c5-11e6-878d-376780b896d7.png)

It should look like this (for 2 sub-teams in NZ), with donuts

![screenshot-vtlcrm loopbackdns com 8080 2016-08-02 15-27-19](https://cloud.githubusercontent.com/assets/826458/17316149/a37a89fc-58c5-11e6-9de6-cb4d520c0dd4.png)

**Comment by hoanglinhlan** [comment]
passed
