### ISSUE TITLE
Data Uploader - No records imported

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2178]
http://uploader-test.admin.kademi.com.au/manageUsers/

[Inside.xlsx](https://github.com/Kademi/kademi-dev/files/402969/Inside.xlsx)

- I uploaded the attached as an Excel and CSV.
- There are 42 records
- Kademi says there are 236 records which is incorrect

![image](https://cloud.githubusercontent.com/assets/2201340/17423249/bb6e7daa-5afc-11e6-87aa-6d43dc07a505.png)

I ran the import and no profiles were created.

**Comment by paddyow** [comment]
[Inside - Small.xlsx](https://github.com/Kademi/kademi-dev/files/402974/Inside.-.Small.xlsx)

I then ran an import with a file that had less columns, and it imported.

@hoanglinhlan can you test why the first file which had more columns failed to upload.

**Comment by anhnt** [comment]
i've tested the large data file and see lots of  NPE when using this bit:

`TableManager.DestField df = getDestField(mappedField.getKey(), destFields);`

Also java.lang.IndexOutOfBoundsException in TableManager.java:72

And it didnt notice that if excel row is empty. my case it said there are 194 records which is not correct

@tuzzmaniandevil can you have a look please

**Comment by tuzzmaniandevil** [comment]
@anhnt That has now been fixed :-) See https://github.com/Kademi/kademi-server/commit/44c0e2ff4ebde0ead0ad014630e017d115d73878
