### ISSUE TITLE
Data uploader: Unsubscribe

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2179]
@bradmac your comments would be appreciated.

See below workflow to unsubscribe:
- Upload a file
- I should not have to choose a group to unsubscribe a profile from an account
- I should be able to choose at least one field to match on, any record that matches should be unsubscribed
- I should only be able to choose only unique IDs like SMS and email - these are the only fields that a profile would need to be unsubscribed on

Can you confirm the current process.

![image](https://cloud.githubusercontent.com/assets/2201340/17423508/79bcbe2e-5afe-11e6-8309-6a5ae2b35f37.png)

**Comment by bradmac** [comment]
"I should not have to choose a group to unsubscribe a profile from an account" - True

**Comment by bradmac** [comment]
"I should be able to choose at least one field to match on, any record that matches should be unsubscribed" - Yes, you should be required to select at least one field which can be used to match, ie userid, email or phone

**Comment by bradmac** [comment]
"I should only be able to choose only unique IDs like SMS and email - these are the only fields that a profile would need to be unsubscribed on" - i dont think we need to bother with that rule at this point

**Comment by anhnt** [comment]
Now on remove/unsubscribe mode, the default group should not be mandatory, instead of that we check the des fields to have at least on of [Email, Phone, UserId] and then do the next action
