### ISSUE TITLE
Data Uploader: Importing profiles for unsub does not add up

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2180]
http://uploader-test.admin.kademi.com.au/manageUsers/

[Inside - Unsibscribe.xlsx](https://github.com/Kademi/kademi-dev/files/402988/Inside.-.Unsibscribe.xlsx)

I uploaded the attached Unsub list
Group: Inside
Mode: Unsub all
Fields: I matched on only the email

![image](https://cloud.githubusercontent.com/assets/2201340/17423625/7194ffbc-5aff-11e6-936f-eb1e0cd92274.png)

It then tells me there are 10 new profiles found.  Unsure where this number comes from?

![image](https://cloud.githubusercontent.com/assets/2201340/17423652/add19d3c-5aff-11e6-95bb-98666e0301b0.png)

After importing, nothing happens.

Connected to #2179

**Comment by bradmac** [comment]
"It then tells me there are 10 new profiles found. Unsure where this number comes from?" - This is the number of "new" profiles in the file. Ie profiles which are not in the database

**Comment by bradmac** [comment]
"After importing, nothing happens." - After importing the unsubscribed profiles should be unsubscribed.

**Comment by bradmac** [comment]
@tuzzmaniandevil please look into why profiles are not being unsubscribed

**Comment by tuzzmaniandevil** [comment]
There was a null pointer exception. GroupManager.unsubscribe was referencing KademiSecurityManager.currentUser(); which in this context there is no current user. So it's now wrapped around using KademiSecurityManager.asUser and the profile of the user who uploaded the file.

Also fixed another issue with an IndexOutOfBoundsException in TableManager.
