### ISSUE TITLE
Data uploader:  Format type not clear

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2181]
![image](https://cloud.githubusercontent.com/assets/2201340/17423731/8895ebc6-5b00-11e6-906e-637c6601a456.png)

Understanding is that CSV, XLS and XLSX are supported.  I have been able to upload with all 3 formats.

Should the button either be updated to show.

(Upload CSV, XLS, XLSX)

Or 

(Upload file)

And validate those three formats.

**Comment by bradmac** [comment]
yes

**Comment by anhnt** [comment]
it has already been validated. just updated button label
