### ISSUE TITLE
Data uploader: Updating a profile

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2182]
http://uploader-test.admin.kademi.com.au/manageUsers/

When wanting to update a profile, it seems I have to match all fields available or the profiles will not get updated. 

@bradmac  can you confirm if this was the intention.  If so there is no visible pompt for the end user to do this.

![image](https://cloud.githubusercontent.com/assets/2201340/17423896/1a22d10c-5b02-11e6-8faa-8e0ff1c64a6f.png)

**Comment by bradmac** [comment]
No. The uploader will match on the following fields in order, if they are present in the file
- userid
- email
- phone

The uploader never matches on firstname/surname
