### ISSUE TITLE
2x triggers created from 1 record

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2184]
I uploaded this file:

[Triggers CSV.zip](https://github.com/Kademi/kademi-dev/files/405958/Triggers.CSV.zip)

Here http://admin.rspca-sa.olhub.com/autoEmails/118632491/timerTriggers.html?startDate=02/08/2016&finishDate=08/08/2016

And it created 2x records, onc which fired and anther queued for later:

![image](https://cloud.githubusercontent.com/assets/2201340/17468548/42116054-5d6c-11e6-91d4-f8c4c08fa0dc.png)

**Comment by bradmac** [comment]
The first trigger, which has already been processed, was created yesterday at 10:30am

The second trigger which is waiting, was created today about 10 mins ago.

You can see this on the profile page - http://admin.rspca-sa.olhub.com/manageUsers/191635932/

**Comment by bradmac** [comment]
Note that yesterday's timer was created manually:

"Automation timer started 01-DAY1-VIDEOSTORY1

Created manually by: patrick-707421/53337434
Processing started 08/08/2016 12:55
1 attempts
Processed at 08/08/2016 12:55"

**Comment by paddyow** [comment]
This was in the CSV:

CreatedAt	        FireAt
7/08/2016 8:02	8/08/2016 8:02

Why were two triggers created?

**Comment by paddyow** [comment]
[Triggers CSV (2).zip](https://github.com/Kademi/kademi-dev/files/405987/Triggers.CSV.2.zip)

This file was uploaded.

The trigger timer started and completed, but no email fired.

http://admin.rspca-sa.olhub.com/manageUsers/195402053/
