### ISSUE TITLE
Cannot download an email history based on my date range

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2187]
http://admin.minda.olhub.com/emails/

If I choose a date range of 1 Jan 2016 to present day, then export to CSV, it does not give me data for that date range.

**Comment by paddyow** [comment]
@bradmac  would be good to get this fixed for the olhub release as a customer will need to pull complete list.

**Comment by bradmac** [comment]
@tuzzmaniandevil as discussed, lets convert this to use ES

**Comment by tuzzmaniandevil** [comment]
CSV export now uses ES

**Comment by tuzzmaniandevil** [comment]
Changed page to use ES as well

**Comment by hoanglinhlan** [comment]
passed
