### ISSUE TITLE
Create new module: Error message not meaning

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2188]
Create new module in case website has not course. 
system show error message not meaning. Refer img
![newmodule](https://cloud.githubusercontent.com/assets/20508726/17477810/9f91ad7c-5d91-11e6-9323-11001ad90a4a.png)

**Comment by ducdhm** [comment]
@bradmac We can use JS for checking at least a course does exist or not :)

**Comment by bradmac** [comment]
Sounds good!

**Comment by ducdhm** [comment]
Error message:
![fireshot capture 31 - p2 - http___localhost_8080_websites_local_version1_programs_p2_](https://cloud.githubusercontent.com/assets/1289631/17525823/aa3174a8-5e8e-11e6-8ccc-90a41b500dc3.png)
