### ISSUE TITLE
Manual multiple unsubscribes

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2189]
Be able to select multiple profiles from the manage users page then using the drop down action an unsubscribe.

Needs dialogue alert to say you are about to unsubscribe X profiles before they are unsubscribed.

![image](https://cloud.githubusercontent.com/assets/2201340/17499611/dedf3b9a-5e11-11e6-8430-56bf16c1d244.png)

**Comment by hoanglinhlan** [comment]
passed
