### ISSUE TITLE
Data uploader: Unsubscribe process shows incorrect profile numbers

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2191]
Upload this data into a new group group:
[Inside.xlsx](https://github.com/Kademi/kademi-dev/files/407949/Inside.xlsx)

Re-upload the above data but choose the unsubscribe option and key on the email address only.

Note the results below.  It says 42 existing profiles which is correct. Not sure why it says 195 profiles found?

![image](https://cloud.githubusercontent.com/assets/2201340/17500255/32ee438e-5e17-11e6-897f-ee79b71ba268.png)

**Comment by tuzzmaniandevil** [comment]
That's because the excel file has 237 rows, 194 of them are just empty rows.

**Comment by tuzzmaniandevil** [comment]
I've added a check to make sure an excel row isn't empty before storing it.

**Comment by tuzzmaniandevil** [comment]
This will also fix #2193
