### ISSUE TITLE
Data uploader: Profile numbers incorrect

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2193]
Might be relating to #2191

Upload this data: 
[Inside.xlsx](https://github.com/Kademi/kademi-dev/files/407961/Inside.xlsx)

To here: http://uploader-test.admin.kademi.com.au/manageUsers/

Into the 'Inside' Group.
Key on First Name, Last Name, Email, Mobile, RG Amount

The number of profiles is incorrect:
![image](https://cloud.githubusercontent.com/assets/2201340/17500445/f9a98bae-5e18-11e6-9161-c5f7dbcbdb0d.png)

**Comment by tuzzmaniandevil** [comment]
Fixed in #2191
