### ISSUE TITLE
Data uploader:  Progress Bar

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2194]
Uploading 20,000 profiles took around 3 to 4 mins. 

Add progress bar as the data is initially uploaded.

Would be good to have one as the data gets imported as well.

![image](https://cloud.githubusercontent.com/assets/2201340/17500742/6e7947ce-5e1b-11e6-98b3-f6583cc2cf13.png)

**Comment by bradmac** [comment]
Hey @anhnt please have a look at this. If its a big job we can push back to the next milestone

**Comment by paddyow** [comment]
http://uploader-test.admin.kademi.com.au/manageUsers/

Uploaded this file:
[Outside3.xlsx](https://github.com/Kademi/kademi-dev/files/408094/Outside3.xlsx)

Into this group: http://uploader-test.admin.kademi.com.au/groups/Outside4/members/

When all the lines have finished processing the upload takes about another 2 to 3 minutes to complete.  It will be important that the upload process accounts for the extra time at the end if it can.

**Comment by anhnt** [comment]
![image](https://cloud.githubusercontent.com/assets/735555/17504860/cf8c7c10-5e26-11e6-8c8e-760d4fba17f9.png)
Its now showing a progress bar to indicate process status. when import is done, there should be a text saying that "Reindexing profiles..." because we need to reindex data after import.

**Comment by bradmac** [comment]
@anhnt can you adjust the progress bar so it ends at 90% for line processing?

**Comment by anhnt** [comment]
done as @bradmac comment

**Comment by paddyow** [comment]
@Anh can we add this to the file upload as well?
