### ISSUE TITLE
Data uploader:  Cannot go back to an upload in progress

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2195]
If I start an upload then navigate away, but then try to start another upload I just get a server error.

A user should be able to start an upload, navigate away then go back to the upload tool and see their last upload in progress. Stage 4 in the process should appear again.

A user should not be able to run 2 simultaneous uploads.

**Comment by anhnt** [comment]
@bradmac please also return total profiles which was found when uploading excel
Currently import status returns
```
{"data":{"statusInfo":{"createdDate":{"date":8,"hours":16,"seconds":8,"month":10,"timezoneOffset":-420,"year":116,"minutes":21,"time":1478596868894,"day":2},"cancelled":false,"complete":false,"cancelledDate":null,"completedDate":null,"stateData":""},"state":{"createdProfiles":256,"errorProfiles":0,"unsubbedProfiles":0,"updatedProfiles":1,"removedProfiles":0,"resultHash":null},"status":"Processing line 258"},"fieldMessages":[],"messages":["Processing line 258"],"nextHref":"","status":true}
```

**Comment by hoanglinhlan** [comment]
passed
