### ISSUE TITLE
Problem addding video to module pages

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#220]
From Andy "video upload issue - new module page, upload vid, save, then it wont play. I then have to edit the page in HTML mode, delete the vid and reload from the list of uploaded vid. Save the page and then it plays"

**Comment by bradmac** [comment]
Vlad, can you please confirm if you can reproduce the bug?

**Comment by Uafinder** [comment]
Nope, i can't reproduce it.
Could we have more info: OS, browser, file type, possibly a codec?

**Comment by bradmac** [comment]
Its the pages in this module, you can see the videos he's uploaded:
http://admin.waterco.olhub.com/websites/waterco/waterco88/programs/ST/ST1/ST1.1/

Andy was using Chrome40 on Win7
