### ISSUE TITLE
Added product with variant is not showed in Checkout page

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#2200]

**Comment by ducdhm** [comment]
@tuzzmaniandevil Hey wes, please kindly help me investigate and fix this issue

**Comment by ducdhm** [comment]
@bradmac I have a suggestion, instead of store shopping cart in cookie with plain string, we can using JSON string for better manipulation. Example: 
Instead of
```
/my-reward-1/CAT-4/25/?param-aa=ffff/?aa=ffff|1,/my-reward-1/CAT-4/25/?param-aa=/?|1
```

we can use like
```
[{"h":"/my-reward-1/CAT-4/25/?param-aa=ffff","q":1},{"h":"/my-reward-1/CAT-4/21/?","q":1}]
```

What do you think?

**Comment by bradmac** [comment]
We should continue using hrefs

**Comment by tuzzmaniandevil** [comment]
There were some issues parsing and storing the href on the server side.

**Comment by tuzzmaniandevil** [comment]
Also changed the bs335 checkout page to show variants.

**Comment by hoanglinhlan** [comment]
passed
