### ISSUE TITLE
Allow nesting components

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#2201]
Currently when i create new web page with theme/page template, then using content editor to drag and drop a dynamic component, it is not rendered in the frontend site view because it is inside **pageBody** component

**Comment by ducdhm** [comment]
Instead of pageBody **component**, we can make it pageBody **container**

**Comment by bradmac** [comment]
I think it should be a component, because when the user is designing a template they will place the body content component inside a container.

It should be ok to just change the rendering logic to handle nested components. We dont need to change the editor.
