### ISSUE TITLE
Profiles to have a home admin organisation

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2202]
Profiles should remain linked to their organisation even when all groups are removed

Profiles may be linked to other organisations through group memberships, and they will no longer be visible when all groups are removed from those orgs.

Key security information should only be editable within the home admin organisation

**Comment by bradmac** [comment]
When a profile is removed from its home admin org, its "enabled" status is set to false.

Be sure to set all profiles enabled status from the /maint page first! This also sets their home admin org.

Next steps
- add option to manage users search page to display disabled profiles. The search service now has a boolean "enabled" parameter, which is true by default. Send enabled=false to show disabled profiles
- Add a switch to the profile page to enable/disable the profile.

**Comment by bradmac** [comment]
@ducdhm would you mind doing the 2 features above?

**Comment by bradmac** [comment]
Have now added a toggle switch on the manage user page to enable/disable

**Comment by Uafinder** [comment]
Works ok for me...
One thing: when you remove account, it moves to disabled and all groups are disappeared. Is it ok?
And one more about toggle switch: would be great to change cursor on it... now it's for typing, need to be like hand (for picking up)

**Comment by bradmac** [comment]
Disabling a profile should not remove all groups. Admins should be able to just turn a profile off, then turn it back on, and the profile should be the same as it was before.

**Comment by bradmac** [comment]
Ah, ok, now i understand. Yes removing a user should disable it and remove all group memberships. It can still be viewed by showing disabled users

Disabling a user does not remove groups
