### ISSUE TITLE
Apply same parsing function to eCommerce as reward store.

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#2203]

**Comment by tuzzmaniandevil** [comment]
@hoanglinhlan This issue was to fix the bug when adding a product that has a variant.
Before if you added a product with a variant, it shouldn't show on the checkout page, also if the variant had a cost associated with it the final cost wouldn't reflect this.

The shopping cart should be able to have products in it that has no variant, a variant with no additional cost and a variant that has an additional cost.

**Comment by hoanglinhlan** [comment]
passed
