### ISSUE TITLE
e-com tab on admin profile page is displaying results for current user

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2204]
Should display for the profile being viewed

This shows transactions which the logged in administrator (NOT the user dd) made:

![screenshot-localhost 8080 2016-08-10 11-25-38](https://cloud.githubusercontent.com/assets/826458/17536991/35b79fe4-5eed-11e6-96ed-9924335473da.png)

**Comment by bradmac** [comment]
@hoanglinhlan please verify that the current transactions are displayed on a profile page, and that they are not the transactions for the logged in user

**Comment by hoanglinhlan** [comment]
passed
