### ISSUE TITLE
Blog article publish date picker is not showing

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#2206]
![image](https://cloud.githubusercontent.com/assets/735555/17541704/314245aa-5eec-11e6-9a8c-241b3d15720b.png)
actually it is the embargo date. there's another issue when publishing article with embargo date. It is currently using only date value, so time is set to 0:00. That field should be formatted as date and time

**Comment by anhnt** [comment]
Hi @bradmac, the datepicker is working now but i think we need to parse Embargo with date and time.
Any suggestion?

**Comment by bradmac** [comment]
Yes, please use date and time. The underlying field is of type timestamp so supports date and time.

**Comment by hoanglinhlan** [comment]
pass/ worked ok
