### ISSUE TITLE
Create bs336.leadman theme

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#2207]

**Comment by anhnt** [comment]
should name it as LeadMan

**Comment by anhnt** [comment]
hey @hoanglinhlan , just ping me when you're ready to test this one

**Comment by hoanglinhlan** [comment]
CSS error
![image](https://cloud.githubusercontent.com/assets/20508726/18466969/36d972ee-79c8-11e6-9a4a-ad5b4dabff67.png)

**Comment by anhnt** [comment]
works fine for me
