### ISSUE TITLE
Data Uploader: Order of options

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2213]
![image](https://cloud.githubusercontent.com/assets/2201340/17581968/671bba02-5fec-11e6-9693-ed9e54afaabb.png)

Feel the order should be:
- Select what you want to do first.
- Then the row
- The the optional group

If remove or unsub if selected, the group drop down should hide or lock as it's not needed.

@bradmac thoughts.

**Comment by anhnt** [comment]
its cool at the moment
![image](https://cloud.githubusercontent.com/assets/735555/26190268/c2a6603a-3bd2-11e7-86ea-0c927bc19369.png)

**Comment by hoanglinhlan** [comment]
passed
