### ISSUE TITLE
Data Uploader: Profile not created properly

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2215]
I uploaded this file:
[New batch.xlsx](https://github.com/Kademi/kademi-dev/files/412768/New.batch.xlsx)

- It created one record with an email outsidddde2222222b@mailintor.com
- That profile is in the group http://uploader-test.admin.kademi.com.au/groups/Outside/members/
- But the profile has not been created if you search for it.

I then did it again with this file:
[New batch2.xlsx](https://github.com/Kademi/kademi-dev/files/412771/New.batch2.xlsx)

To the same group and selected fields, start data, status, plan and email then uploaded.

Same thing happened again.

**Comment by paddyow** [comment]
Note that I created this group http://uploader-test.admin.kademi.com.au/groups/new-batch/

Which has all the custom fields to match the Excel doc.  Even if you upload to this group, you get the same error.

**Comment by bradmac** [comment]
Worked locally. Will review again when AWS indexing problem is resolved.

**Comment by hoanglinhlan** [comment]
Confirm add profile successfuly. Search by email: "outsidddde2222222b"
![2215](https://cloud.githubusercontent.com/assets/20508726/17655171/1174ec36-62d5-11e6-9276-b2ea6cb6a596.png)
