### ISSUE TITLE
Creating custom fields

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2216]
http://uploader-test.admin.kademi.com.au/groups/new-batch/

I need to setup a group and apply custom fields, but I don't know what fields Kademi supports out of the box as I could use some of these instead i.e. First Name.

@brad maybe we should list the fields we support in the Extra fields section?

**Comment by bradmac** [comment]
Just add text in an alert box which has standard fields in a list
- firstName
- surName
- phone
- email
- nickName
- birthDate
