### ISSUE TITLE
Blog components

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2217]
Please update blog components as follows
- blogArticleDetailComponent.html - this should be renamed to blogArticleHeaderComponent, and only contain title, date and tags. It should not contain the body or image
- move the image to a separate component, with configurable orientation
- the body of a blog article should be displayed with the pageBodyComponent. This should not need a special blog component
- the comments section should use a standard comments component from the ForumsApp. It should not need a special blogs component

**Comment by anhnt** [comment]
Update tag and category components

**Comment by hoanglinhlan** [comment]
passed
