### ISSUE TITLE
Video issues

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#222]
1. Strange error (video uploaded successfully)
![image](https://cloud.githubusercontent.com/assets/1945230/6514732/4627f4ca-c38d-11e4-8268-29c9d998cd38.png)

2. When video is just upoaded in preview pane it isn't showing its' duration - shows Nan.
![image](https://cloud.githubusercontent.com/assets/1945230/6514807/f92f33a8-c38d-11e4-8596-9daf74bd0791.png)

3. Randomly video player shows "live broadcast" label instead of duration.

**Comment by bradmac** [comment]
1. Is a problem - i'll look into it
2. We can ignore this, it just doesnt know the duration until after the streaming format has been generated
3. "Live broadcast" displays when its generating the streaming format. Once the streaming format has been generated it no longer displays that message
