### ISSUE TITLE
Reward Store Components

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2220]
- rewardStoreCategoryNameComponent: Use a generic page title component instead, similar to pageBodyComponent. Ensure null handling so there is nice output when there is no title, instead of outputting template code
- rewardStoreCategorySearchBoxComponent: use a generic search component instead. The generic search component should have an option to search only the current directory, or search whole site. For this page it should search current directory
- rewardStoreCategoryProductsComponent: ensure null handling so we do not output template code when editing the template in the content editor. Move js into an app provided js file (ie in app dependencies). Move the css file referenced in this component to an app css dependency. Move inline css into the css file.
- please make sure page js is not loaded when using the content editor. Currently the infinite scrolling js  gets run, but this cant work in the editor, and causes an error.

**Comment by anhnt** [comment]
i created a component called searchBox which is from search app. when use this, please make sure search app is enabled.

**Comment by hoanglinhlan** [comment]
passed
