### ISSUE TITLE
Allow pages to be rendered as PDF

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2222]
Extend the AltFormat framework to allow rendering HTML pages as PDF.

This will be done by appending an alt format identifer string, eg
To render this page - http://version1.elearning336.loopbackdns.com:8080/index.html

Use this url - http://version1.elearning336.loopbackdns.com:8080/index.html-alt.pdf

**Comment by tuzzmaniandevil** [comment]
:+1:
