### ISSUE TITLE
Data uploader: issue 

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2224]
Data uploader
•	Cant set date field with formats: 15-Jul-16 / 7/15/2016 / … If I choose format cell for date field in excel file is text, I can see date field updated but the update value is not a value in excel file (excel value: 7/15/2016 ==> date filed value after import/update: 7/3/2017)
•	When I update profile with all extra field (10 field), some field not updated
•	When I update profile, if I selected 2 column are email, and first column have email invalid, system find new profile, importing but in step 5: system showing report have 1 error.
![extrafield](https://cloud.githubusercontent.com/assets/20508726/17654119/a9df5ada-62c9-11e6-8885-03c46fcdc88c.png)
[ExtraField.xlsx](https://github.com/Kademi/kademi-dev/files/417449/ExtraField.xlsx)

**Comment by bradmac** [comment]
Fixed. Now validating the birthdate field.

Note that Kademi currently only supports date formats dd/mm/yyyy

**Comment by hoanglinhlan** [comment]
Created a new profile with only email
Update profile: Choose email and birthday (7/12/1942 ) in spreadSheet
==> 
**Expect**: step 3 find 1 existing profile and update profile 
**Acutal**: step 3 find 1 new profile (???) and create a new profile with old email. so, we have 2 profile with only one email: 1 profile has birthday, 1 profile has not birthday

Note: currently, system dont validate birthday in the future, should we need validate ???

continue...

**Comment by hoanglinhlan** [comment]
[ExtraField.xlsx](https://github.com/Kademi/kademi-dev/files/438556/ExtraField.xlsx)

Can't set value for extraField has more than one option (extraField01 and 06)

**Comment by hoanglinhlan** [comment]
I just rechecked, some row in excel file has space (it mean value for extraField is "extra01-1 " but in list define value must "extra01-1". 
Pls ignore this case

**Comment by hoanglinhlan** [comment]
However, should we need trim the string??

**Comment by bradmac** [comment]
Yes, i think we should add string trimming

**Comment by bradmac** [comment]
Added trimming

**Comment by hoanglinhlan** [comment]
Fixed pass
