### ISSUE TITLE
User manager: Users should be able to search using email domains

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2226]
Currently, system can search the list profile by nick name, phone, local-part ( name of mailbox). But, system cant search by domain mail.
**Expect**: Users should be able to search using email domains

**Comment by tuzzmaniandevil** [comment]
The search was only doing a prefix search, So I changed it to do a prefix and postfix search, i.e. `.*TEXT.*`

**Comment by bradmac** [comment]
Hey @tuzzmaniandevil i dont think we should do it that way. Thats going to smash ES performance wise.

What i would suggest is either
- use some sort of special or custom tokeniser
- change the appindexer to store an additional field which is the email split into personal and domain parts.

**Comment by tuzzmaniandevil** [comment]
@bradmac It's using a WildCard query so should be a performance hit, We can do a custom tokeniser/Extra index field if it will make it faster

**Comment by bradmac** [comment]
I think adding an extra field in the index for the domain would be good. Thats something we might want to report on in some cases

**Comment by tuzzmaniandevil** [comment]
added a new field called `emailDomain`  and added it to the fields it searches in. a Re-index will be needed

**Comment by hoanglinhlan** [comment]
passed
