### ISSUE TITLE
Dynamic Nodes in Journey Builder

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#2227]
Data from server for each of nodes should be in JS. Example:
```javascript
JBApp.nodes['nodeType'] = {
    // Node information
};
```

**Comment by anhnt** [comment]
cant wait to see it :)

**Comment by bradmac** [comment]
OK, done.

Now to add this to an app, implement JourneyBuilderApplication

See EmailApp for an example

The JourneyBuilderApplication requires a single method called nodeTypes to be implemented. Eg:
```
    @Override
    public List<NodeType> nodeTypes() {
        List<NodeType> list = new ArrayList<>();
        list.add(new NodeTypeBean("emailAction", "email/jb/sendEmailNodeType.js"));
        return list; 
    }
```

The first argument for NodeTypeBean is the name of the node type, as it appears in json. The second is the path to the js fragment to be merged into the handlers js file.

@ducdhm you can put anything you need in those handlers files. Currently its just placeholder code.

There is a base file added to the js output before the handlers. This is theme/apps/funnels/journeyBuilderHandlers.js

The merged handlers file is available under the funnel. Eg for a funnel named "nurture":
http://localhost:8080/funnels/nurture/jb-handlers.js

**Comment by ducdhm** [comment]
`Decision` and `Timer` node is not belong to any apps so I made it to be node type of FunnelApp

**Comment by bradmac** [comment]
:+1:
