### ISSUE TITLE
File is FTPd at incorrect time

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2229]
http://admin.rspca-sa.olhub.com/integration/#history-tab

![image](https://cloud.githubusercontent.com/assets/2201340/17692403/fca9a5cc-63dc-11e6-9547-2832a22bc256.png)

7 hours difference from 3pm schedule to 8pm upload time.

![image](https://cloud.githubusercontent.com/assets/2201340/17692415/0811578e-63dd-11e6-96cf-d2d420720eb2.png)

Note the org time is set to Sydney.

**Comment by bradmac** [comment]
And please fix the "$exec.source" template code

**Comment by bradmac** [comment]
Here's one thing i can see wrong. In PipelineSchedule.timerFireAt we have this code:
```
        Calendar c = Calendar.getInstance();
        c.setTime(trigger.getStartDate());
        int hour = c.get(Calendar.HOUR_OF_DAY);
        int min = c.get(Calendar.MINUTE);
        cal.set(Calendar.HOUR_OF_DAY, hour);
        cal.set(Calendar.MINUTE, min);
```

That is not setting the org timezone on the calendar used to get the fire at hour and minute.

**Comment by tuzzmaniandevil** [comment]
I'm made the changes to the time and added a null check to the $exec.source template

**Comment by tuzzmaniandevil** [comment]
I added a unit test to check 3 time zones. Pacific/Auckland, Australia/South and America/Los_Angeles. All of then are now correct

**Comment by tuzzmaniandevil** [comment]
The time showing on the Integration history and execution results page didn't take into account the timezone, so the time showing was the NZ time.
