### ISSUE TITLE
Blog file upload needs progress bar

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#223]
Large files of over 100mb take time and need to see visibility of it's progress.

Multiple file uploads would be good at the same-time.

**Comment by bradmac** [comment]
Please add ajax progress support to get file upload progress client side only. I'm not sure if we're using our jquery.forms plugin, but if so we should add a progress callback

https://stackoverflow.com/questions/4856917/jquery-upload-progress-and-ajax-file-upload
https://stackoverflow.com/questions/23219033/show-a-progress-on-multiple-file-upload-jquery-ajax

**Comment by gonzalon** [comment]
@bradmac the change is made, now the jquery form supports a onProgress callback.
The last version was 1.1.2 so I added the 1.1.3 but we were using 1.1.1 ATM
Should I replace 1.1.2? Seems that is not being use

**Comment by bradmac** [comment]
Yes, please update the admin to use your 1.1.3. The 1.1.2 version is probably used in front end sites, so it should not be changed

**Comment by hoanglinhlan** [comment]
passed
