### ISSUE TITLE
Allow searching for disabled profiles on manage users

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2230]
Extension to https://github.com/Kademi/kademi-dev/issues/2202

The manage users page now does not show disabled (aka removed) users by default. Please add an option to show only disabled users. Perhaps a toggle switch or checkbox under the search box?

The search service now has a boolean "enabled" parameter, which is true by default. Send enabled=false to show disabled profiles

**Comment by ducdhm** [comment]
New UI:
![55555555555](https://cloud.githubusercontent.com/assets/1289631/18016558/2f391f6e-6bf7-11e6-8b4e-64b5eab13a2d.png)

**Comment by bradmac** [comment]
@ducdhm i think it would be better to have a lighter UI, i think the switch is overkill.

how about just having a link like github issues has for open/closed issues? We dont need to show counts. I think these could go under the search box, about the buttons

![open-closes](https://cloud.githubusercontent.com/assets/826458/18023813/fd5c2922-6c51-11e6-93c0-cb9856004950.png)

**Comment by ducdhm** [comment]
Update UI:
![a](https://cloud.githubusercontent.com/assets/1289631/18040815/1c65167c-6ddc-11e6-845a-a71ce151b5e0.png)

**Comment by hoanglinhlan** [comment]
Confirm fixed pass
