### ISSUE TITLE
checkout page - order summary: total product incorrect

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2231]
login by any account
**step**:
- login by account 1: add some product to cart then logout
- login again by account 2, then go to checkout page 

**expect**: order summary must be empty
**actual**: order summary count product thats selected by account 1

**Comment by bradmac** [comment]
Shopping cart cookies should be per user. The simplest option is just to use a cookie name which includes the userid. That way users will not see each other's carts.
