### ISSUE TITLE
Pipeline is using NZ time but displaying local time

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2232]
http://admin.rspca.olhub.com/integration/#history-tab

- The account timezone is Sydney
- The FTP schedule is set for 3pm
- The last FTP upload under history for the 17/8/16 shows 3pm
- The end point of the file sent on the 17/8/16 to Listens FTP is 1pm so using NZ time

Confirm the update tomorrow will fix this.

**Comment by bradmac** [comment]
yes, that is fixed

**Comment by paddyow** [comment]
:)
