### ISSUE TITLE
Cannot edit header section when building an EDM

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2236]
Chrome: Version 52.0.2743.116 m

Video: https://youtu.be/NY1f4e8HibQ

**Comment by hoanglinhlan** [comment]
Add container wrong 
![image](https://cloud.githubusercontent.com/assets/20508726/18242355/1d3f6bf2-7380-11e6-92ba-124246a4da51.png)

**Comment by hoanglinhlan** [comment]
passed
