### ISSUE TITLE
Email history does not show

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2238]
http://twoprovidores.admin.kademi.com.au/emails/

Page loads, flashes the email history for 1 split second then hides it.

Chrome:  Version 52.0.2743.116 m

**Comment by bradmac** [comment]
@tuzzmaniandevil is this the issue you fixed earlier today?

**Comment by tuzzmaniandevil** [comment]
No. Thats the date selector. @paddy change the selected date and the emails will show

**Comment by bradmac** [comment]
@paddyow I dont see the problem. Although i think there is a problem sending emails, they all say pending

**Comment by tuzzmaniandevil** [comment]
@bradmac the "pending" is the issue I fixed earlier

**Comment by tuzzmaniandevil** [comment]
@paddyow can you confirm that you just needed to change the date range?

**Comment by paddyow** [comment]
Ok so this looks fine now.  However I did notived the pages has 10 pages, but only one page of emails.

**Comment by bradmac** [comment]
@tuzzmaniandevil can you please have a look at the pagination control? We should get this nailed on this page, and then we can staart using it on all list pages

**Comment by tuzzmaniandevil** [comment]
Sorted :-)

**Comment by hoanglinhlan** [comment]
passed
