### ISSUE TITLE
Using hash URL for product photos, article photos, etc...

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#2240]

**Comment by bradmac** [comment]
Hey @ducdhm are you going to make this change? Its just a matter of updating Kademi templates similar to Carters

**Comment by ducdhm** [comment]
@bradmac Yes. I'll do it ;)

**Comment by ducdhm** [comment]
@hoanglinhlan Did you test with each page of auction, blog, reward store and ecommerce store? Include checkout pages, components for contentEditor and edmEditor?

**Comment by hoanglinhlan** [comment]
Blog/Reward store/Ecommerce store:  Pass
Checkout page for reward store: pass
Checkout page for ecommerce store: Fail 
![image](https://cloud.githubusercontent.com/assets/20508726/20224765/a80cd72a-a872-11e6-891d-d3b5bd726af7.png)

**Comment by ducdhm** [comment]
Checkout page fail is **Reward Store** not **E-commerce**. Take a look at your screenshot, the price is Pts not currency. Please be carefull in next time when you check/test

**Comment by hoanglinhlan** [comment]
passed

**Comment by ducdhm** [comment]
@hoanglinhlan Did you test Auction?

**Comment by hoanglinhlan** [comment]
hi @ducdhm 
I checked Auction, it's pass
