### ISSUE TITLE
Add new page to have option for folder default page

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2241]
When creating a html page, users often want to create a folder default page. For example, to have a page at /myfolder/ they need to create a file at /myfolder/index.html

But it is not user friendly to expect users to type in the correct file name. Instead, we should give the user an option on the new page dialog:
![screenshot-localhost 8080 2016-08-18 15-52-40](https://cloud.githubusercontent.com/assets/826458/17761537/fe5795ac-655b-11e6-86ac-0f89d1106ca1.png)

**Comment by ducdhm** [comment]
2 radio buttons:
 1. Default folder page
 2. File name

**Comment by ducdhm** [comment]
New UI:
![222222222222](https://cloud.githubusercontent.com/assets/1289631/17994387/421fc68e-6b82-11e6-9afd-cad97b74e975.png)

**Comment by bradmac** [comment]
I just used it and it produced a file with name "index-html.html", which is not found when going to the website root, ie - http://version1.w1.loopbackdns.com:8080/

Instead it is accessed on http://version1.w1.loopbackdns.com:8080/index-html.html

Please ensure the file is created with the name "index.html"

**Comment by ducdhm** [comment]
@bradmac The value of `name` input should is `index` instead of `index.html` (without extension). I fixed it!
