### ISSUE TITLE
Integration: Double entry in history

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2243]
1x FTP line item  (correct)
2x /integration/LP1.xml items which are being created by the email schedule here: http://admin.rspca-sa.olhub.com/scheduledEmails/listen-data/

Only 1x email is being sent, but 2 lines items under history. Wondering if this is correct or an error displaying the history?

![image](https://cloud.githubusercontent.com/assets/2201340/17763268/da7ca01a-655a-11e6-96de-3d46e8218ebd.png)

**Comment by bradmac** [comment]
There is one history item for the FTP job in the schedule, and there is also a pipeline execution history for each recipient sent from the scheduled email.
