### ISSUE TITLE
Review document: User manager

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2246]
http://docs.kademi.co/programs/admin/users/manage-users/pintroduction.html

@mamun4343

**Comment by hoanglinhlan** [comment]
http://docs.kademi.co/programs/admin/users/sendemail/pintroduction.html

**Comment by mamun4343** [comment]
@hoanglinhlan  also check this
http://docs.kademi.co/programs/admin/elearning/rew3/pintroduction.html
