### ISSUE TITLE
Allow showing non-editable section in keditor

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#2249]
when we just want to show a text placeholder on dynamic component instead of velocity code
![image](https://cloud.githubusercontent.com/assets/735555/17852338/063f3b66-6891-11e6-9bd3-3668cceb250e.png)

**Comment by bradmac** [comment]
Note that this does happen already for many components, such as blogPageArticlesComponent.

**Comment by ducdhm** [comment]
@anhnt Please check it!

**Comment by anhnt** [comment]
works great thanks mate
