### ISSUE TITLE
Build process: Do not download from oracle

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2251]
Currently the JDK gets downloaded from oracle for each build.

Please investigate if we can use a local storage option instead, such putting the file in S3

**Comment by tuzzmaniandevil** [comment]
It uses apt to install java and the unlimited policy files. Any reason why you want to change this? We can use S3 if you want

**Comment by bradmac** [comment]
Its just that the oracle download isnt really part of the apt ecosystem, and i dont think we can necessarily rely on it being there. And generally, the less external dependencies the better. Its also a possible (though unlikely) attack vector

It we can easily move it to S3 then lets do that. If its going to take more then a couple of hours then leave it.
