### ISSUE TITLE
User importer: make error rows availablefor download

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2252]
Often, when an admin uploads a spreadsheet of profiles many of them will fail to import. Its important the admin can get a list of failures, so they can correct them and re-upload

So what we should do is
- as the importer progresses,add any failed rows to an in memory list, with the error reason added as a first column
- if there are errors, when the importer completes, store the list as a csv
- if there are errors, show the user a link to download the csv

**Comment by bradmac** [comment]
New UI
![screenshot-localhost 8080 2016-08-23 16-49-45](https://cloud.githubusercontent.com/assets/826458/17880655/abe8258a-6951-11e6-9bd6-40a7cadcc804.png)

**Comment by bradmac** [comment]
Also, have hopefully improved status information. Should now be a message during the lengthy search index update phase after records are inserted

**Comment by bradmac** [comment]
Ready to test!

**Comment by hoanglinhlan** [comment]
[emailError.xlsx](https://github.com/Kademi/kademi-dev/files/431919/emailError.xlsx)
**_Case1_**. Import this file. Default group vaue is any group. 
**Expect**: 

1. import 3 profile   
-. 01outsidec3@mailintor.jj
-. 01outsidec8@mailintor.com
-. 01outsidec9@mailintor.com
2. error file have 6 incorrect profile

**Actual**:  import 6 new profile and show profiles: 1 -4 -5 in error file 

**_Case2_**: Clear data then Import this file. select "no default group" and choose group column in Spreadsheet

**Expect**: 
.1. import 2 profile 
-. 01outsidec3@mailintor.jj
-. 01outsidec9@mailintor.com

.2. error file have 7 incorrect profile

**Actual**: complete notice: import 6 profile and show profiles: 1 -4 -5 in error file but I cant search profile 01outsidec8@mailintor.com.

==> I think we should validate all data, not only email. ex: destination field must be do not blank

**Comment by hoanglinhlan** [comment]
dont clear data. Re-produce case 1 after case 2
==> duplicate profile 
![image](https://cloud.githubusercontent.com/assets/20508726/17886518/60255eec-694c-11e6-9081-3ea248d448d3.png)

**Comment by bradmac** [comment]
I've added extra validation on the email address, and added a check to only import rows if they're valid (that was missing).

I've also added a display on step 3 to show invalid rows.

I could not reproduce the problem with duplicated profiles. If you see that again please let me know.

**Comment by hoanglinhlan** [comment]
Case 1: pass
Case 2: pls recheck 
duplicate profile: cant re-produce

**Comment by bradmac** [comment]
Added a validation check for group name field.

**Comment by hoanglinhlan** [comment]
Confirm fixed :D
