### ISSUE TITLE
User importer: Move mode to step before selecting columns

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2253]
Currently step 2 is bloated with copy describing the mode, and the column selection and default group. Please split these into 2 steps

Step 2: Select mode and default group
Step 3: Map columns. Only show group if "auto" mode is selected. If no default group is selected on step 2, then a group column is mandatory
Step 4: Import
...

**Comment by anhnt** [comment]
i've done splitting select mode and map columns into 2 steps. there is issue when i selected remove mode then the record validation is saying: groupName is invalid and couldnt remove any record
@bradmac please have a look on this tomorrow. thanks

**Comment by hoanglinhlan** [comment]
5 case: 
.1.  Step2: No default group. Step 3: dont select group colum in Spreadsheet
=> **Expect**: Show message: Please indicate group field in data table

.2.  Step2: No default group. Step 3: select group colum with group name not existed 
=> **Expect**:  At step 4: find error profile and show message: groupName is invalid

.3.  Step2: No default group. Step 3: select group colum with group name existed 
=> **Expect**: import successful

.4. Step2: Select any group. Step3: dont select group colum in SpreadSheet
=> **Expect**: import successful

.5. Step2: Select any group. Step3: select group colum in SpreadSheet
=> **Expect**: import successful. All profile created buy group name depends on each row at step 3

All Pass
