### ISSUE TITLE
Variant image enhancements

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2257]
- after an image has been selected for a variant, we need to be able to unselect it, so there is no variant image
- currently its possible to select a product image as a variant image. But we would also like to be able to upload an image which is set as the variant image, but not added to the product image list

**Comment by tuzzmaniandevil** [comment]
- after an image has been selected for a variant, we need to be able to unselect it, so there is no variant image **Done**

**Comment by tuzzmaniandevil** [comment]
- currently its possible to select a product image as a variant image. But we would also like to be able to upload an image which is set as the variant image, but not added to the product image list **Done**

**Comment by Uafinder** [comment]
Everything looks fine, one thing: would be great to add a possibility to uncheck checkbox while selecting an image for the variant.
For example, you want to change image for the variant, you are accessing images from the list, and current image is not selected there. And there is no possibility to remove it from there.
