### ISSUE TITLE
Deleting contact requests does not remove them from index

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2259]
For example see here:
http://admin.oceanyouth.kademi-beta.co/manageContacts/

Delete an old test entry and it is initially removed from the page. Then refresh the page and it appears. But then re-index and go back to the page and its gone.

So appears to be getting deleted from teh DB, but not the index.

**Comment by tuzzmaniandevil** [comment]
Backported a fix to olhub.com

The issue seems to be the constructor on DefaultIndexedItemUpdatedEvent when not specifying a transaction. ie `SessionManager.session().getTransaction()` doesn't work
