### ISSUE TITLE
Group membership application enhancements

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2260]
See GroupMembershipApplication
- add columns to record whether it was accepted or rejected, and by who, and the date of processing
- show created and accepted/rejected events on profile timeline

**Comment by diegoperezn** [comment]
Hi @tuzzmaniandevil!
In this issue I added 3 columns on GroupMembershipApplication: 

- SubscriptionAction applicationResultState; 
- Date applicationResultDate;
- Profile applicationRusultProfile;

Thanks!

**Comment by hoanglinhlan** [comment]
passed
