### ISSUE TITLE
Calendar invitation enhancements

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2261]
Attendance restriction
- calendar to have optional list of groups with access. If none selected then access is not limited by group
- if groups are selected, then only allow registration from profiles in at least one selected group
- when creating an invitation email, set recipient groups to those defined for the calendar (if any)

Follow up emails
These should only be generated when the admin clicks something because they can be large and slow.
- on a manage event page, where groups are specified on the calendar, show profiles which are elligible for attendance (ie are in the group(s)) but have not submitted an attendance. 
- make this list available in a mailto link, where the addresses are in the bcc field, so admins can directly email people who havent responded

**Comment by hoanglinhlan** [comment]
hi @diegoperezn 
I clicked to add/remove group button nothing happen
Please check

**Comment by diegoperezn** [comment]
@hoanglinhlan It is working in http://carterstest.admin.kademi.com.au/Calendars/

**Comment by bradmac** [comment]
@hoanglinhlan I just checked in http://lan-test.admin.kademi.com.au/Calendars/NewYork/ and it seems to work ok

**Comment by hoanglinhlan** [comment]
https://lan-test.admin.kademi.com.au/Calendars/CalendarTest/
1: I choose normal-user and  c5s-manager group but I still access to event with others group 
(group c5s-user, profile https://lan-test.admin.kademi.com.au/manageUsers/46391155/#general-tab
2: nothing happen when I click to Mail user in elligibleProfiles page
https://lan-test.admin.kademi.com.au/Calendars/CalendarTest/elligibleProfiles-event

**Comment by diegoperezn** [comment]
1. You have access to the event but you are not allowed to register on it. Right now the error is wrong in that environment but seems to be that a JSs lib update is needed, The backend is sending the correct error ([{field: "groupCalendarRequired", message: "Calendar and user group validation"}]). @bradmac 
2. Regarding this, do you have more info about it? I test it in chrome and is working.
![captura de pantalla 2017-05-05 a las 11 36 43](https://cloud.githubusercontent.com/assets/26150017/25729082/3840d89e-3187-11e7-9425-59cc8a377050.png)

**Comment by hoanglinhlan** [comment]
@diegoperezn 
about 2 
[Mail user button.zip](https://github.com/Kademi/kademi-dev/files/1040556/Mail.user.button.zip)
please view my record video

**Comment by tuzzmaniandevil** [comment]
@hoanglinhlan Do you have an email client installed like Outlook or thunderbird? The link will only work if there is an application to handle the mailto.

I tested it and words fine with Thunderbird
