### ISSUE TITLE
My transactions list should show transactions from related organisations for org type points buckets

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2263]

**Comment by bradmac** [comment]
hey @hoanglinhlan, to test this you need to
- create an organisation based points bucket, linked to an org type like "rewards org"
- create an organisation with that org type
- create a profile linked to that organisation
- award points to the organisation
- view the profile in admin and verify you see the points on the Points tab
- create some debits for the profile (might need to setup a reward store and make a purchase)
- verify that the purchase appears as a debit on the profile admin page

**Comment by hoanglinhlan** [comment]
on Profile page: points show on the Points tab => passed
verify that the purchase appears as a debit on the profile admin page => passed
