### ISSUE TITLE
FTP fired but no file was sent

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2264]
Client said the below file was not sent to Listen, but records show it was.  Is there any further  information from our end to check if this was or was not sent?

http://admin.rspca-sa.olhub.com/integration/199276973

**Comment by bradmac** [comment]
Looks like it wasnt sent. Here is an example of a successful run:

http://admin.rspca-sa.olhub.com/integration/198339039

```
Information

CONNECT-SUCCESS: at null : Successfully connected to server: __
```

**Comment by bradmac** [comment]
@tuzzmaniandevil can you please look into this first thing? There's 2 things to look at
- why is it not being processed? I would guess there is an error during pipeline execution
- why is the problem not being logged? The result of every pipeline execution should be recorded

**Comment by tuzzmaniandevil** [comment]
I've added logging and extra steps to make sure errors get logged in the pipeline execution step. This will need to be backported to olhub

**Comment by bradmac** [comment]
We're getting "connection refused" on the provided FTP connection details.

**Comment by tuzzmaniandevil** [comment]
Some further details, Testing the FTP using implicit over TLS has this result:
![screenshot from 2016-08-26 15-43-45](https://cloud.githubusercontent.com/assets/3378330/17993475/31d19a9c-6ba4-11e6-8043-71511324b8e8.png)

Testing the FTP using explicit over TLS has this result:
![screenshot from 2016-08-26 15-44-08](https://cloud.githubusercontent.com/assets/3378330/17993481/3a6afe0a-6ba4-11e6-97f6-fb784d2e3faf.png)

**Comment by tuzzmaniandevil** [comment]
@paddyow Please can you send those screenshots to listen, it seems to be a certificate issue on their end

**Comment by tuzzmaniandevil** [comment]
Btw I used this site to test it: https://ftptest.net/

**Comment by tuzzmaniandevil** [comment]
Sorry, I tested it with the wrong port numbers.
