### ISSUE TITLE
Content Editor: Adding an <i> tag in the content editor get's removed

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#2265]
If I try and add a `<i>` tag to use font awesome icons in the content editor using CKEditor, CKEditor removes the `<i>` tag, We have had this problem before in our standard CKEditor impl that was fixed by adding:
````
CKEDITOR.dtd.$removeEmpty['i'] = false;
````

**Comment by hoanglinhlan** [comment]
passed
