### ISSUE TITLE
Contact form component: make thank you text configurable option

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2269]
Currently the contact form allows content to be edited in a page at a special path. But since we now have a component framwork with configuration options, the thank you text should be made a configurable option

AND the thank you text should be displayed in an appropriately styled box. I would suggest an alert panel

**Comment by hoanglinhlan** [comment]
1. after send message, system redirect to /contactus page and show the code 
`{
data: null,
fieldMessages: [ ],
messages: [ ],
nextHref: "",
status: true
}
`
2. At admin site, contact request not increase

**Comment by anhnt** [comment]
cant reproduce
