### ISSUE TITLE
Data uploader /user Importer:  Error SpreadSheet in step 3 and Error file need a header

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2270]

**Comment by bradmac** [comment]
@hoanglinhlan so can you please clarify..
- "Error SpreadSheet in step 3" - I dont understand what the problem is. Can you provide details?
- "Error file need a header" - do you mean that it should have a header row? If so i dont think that is needed currently.

**Comment by hoanglinhlan** [comment]
hi 
it's mean we need add a header row for error Spreadsheet that you show in step3 and header row for error file. 
I think it not a big problem. However, if we do it, really convenient for users. That the reason I added label enhancement, it's not a bug. Maybe we do it in the next time

**Comment by bradmac** [comment]
OK. Moving back to milestone after next.

**Comment by hoanglinhlan** [comment]
passed
