### ISSUE TITLE
Data uploader /user Importer: Must disable import button if spreadsheet has not any valid profile 

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2271]
![image](https://cloud.githubusercontent.com/assets/20508726/17998825/70d7f4ec-6ba0-11e6-8d14-8b59cdaf823a.png)

**Comment by bradmac** [comment]
Please change "There is no valid row in the file" to "There are no valid rows in the file"

**Comment by diegoperezn** [comment]
Done!

**Comment by hoanglinhlan** [comment]
passed
