### ISSUE TITLE
Add a PDF parser framework.

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#2272]
This will allow custom apps to parse and manipulate PDF files.

Use PdfBox https://pdfbox.apache.org/

to access use:

```
var pdf = fileManager.parsePDF('yourHashHere');

// Your actions

var newHash = pdf.save();
pdf.close; // Finished with the old PDF, so close it.
```

An example of generating thumbnails of the pages:

```
var pdf = fileManager.parsePDF('yourHashHere');

var pageCount = pdf.numberOfPages;

for(var i = 0; i < pageCount; i++){
    var imageHash = pdf.generatePageImage(i, 150, 'png');
    log.info('Page {} Image hash: {}', i + 1, imageHash);
}

pdf.close; // Finished with the PDF, so close it.
```

**Comment by bradmac** [comment]
Its best if we dont require custom apps to clean up resources by closing them. Often developers wont close the resource and that can cause resource depletion and crash the server.

Probably the best way of doing that is to parse the document to a bean which does not hold the pdf document internally, instead it reads its content (ie fields) when parsed, and just holds the content in memory.

Similarly, its better for operations like generatePageImage to be on a service class like fileManager. Those operations should do what they need to do, and then close and release resources.

**Comment by tuzzmaniandevil** [comment]
Unfortunately a bean won't work, You need to have the PDF "open" to be able to make modifications to it. but I agree the framework should handle the closing of resources. So I've moved the `generatePageImage` to the file manager as recommended, with `parsePdf`  I came up with an idea, Why not wrap it? Here is a JS example:
```
fileManager.parsePdf('yourHashHere', function(pdf){
    // Make you PDF modifications in here
});
```

and in Java it looks like this:
```
    public void parsePDF(byte[] bytes, Consumer<PdfDocument> callback) throws IOException {
        if (bytes != null) {
            PdfDocument pdf = new PdfDocument(bytes, null, blobStore, hashStore);

            callback.accept(pdf);

            pdf.close();
        }
    }
```

**Comment by bradmac** [comment]
You could wrap it like that, and that might be the way to go. But another approach is 
- parse it to a bean, so you only need the open document to retrieve fields etc, and then you close it
- have service methods which perform operations, and these open the document, do what they need to do, and then close it

So you never need a "live" instance of the pdf. Just use and release.

**Comment by bradmac** [comment]
@tuzzmaniandevil can we close this?
