### ISSUE TITLE
Group subscription goal in journey builder

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2276]
Part of https://github.com/Kademi/kademi-dev/issues/2227

**Comment by bradmac** [comment]
@ducdhm I've added GroupGoal and groupGoalNode.js following the same pattern as for other nodes. It is appearing in the editor, but if i add a group goal and then reload it doesnt display

Can you have a look please?

**Comment by bradmac** [comment]
And can you also add a dropdown for selecting the group?

**Comment by bradmac** [comment]
Groupgoal is working now. Just need to add a select box for the group

**Comment by hoanglinhlan** [comment]
passed
