### ISSUE TITLE
Antisamy: Allow for class attributes

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#2282]

**Comment by bradmac** [comment]
Yep, class attribute looks safe:

https://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet#Bonus_Rule_.234:_Use_the_X-XSS-Protection_Response_Header

"Safe HTML Attributes include: align, alink, alt, bgcolor, border, cellpadding, cellspacing, class, color, cols, colspan, coords, dir, face, height, hspace, ismap, lang, marginheight, marginwidth, multiple, nohref, noresize, noshade, nowrap, ref, rel, rev, rows, rowspan, scrolling, shape, span, summary, tabindex, title, usemap, valign, value, vlink, vspace, width"

**Comment by ducdhm** [comment]
@hoanglinhlan You can download this tool for checking security https://sourceforge.net/projects/zaproxy/

**Comment by tuzzmaniandevil** [comment]
I've also added span as a safe tag :-)
