### ISSUE TITLE
Cant search reward product by content

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#2284]
Please reproduce this bug when searching with term: MJVM2X/A which is from this product: http://carters.kademi.com.au/trade-reward/technology-and-accessories/computers/20507852/

**Comment by anhnt** [comment]
This is query builder code:
`var q = {
            "multi_match": {
                "query": query,
                "fields": ["title", "content"]
            }
        };`

**Comment by tuzzmaniandevil** [comment]
There was a bug when converting HTML to plain text. So the indexed content ended up being incorrect.

**Comment by hoanglinhlan** [comment]
passed
