### ISSUE TITLE
FunnelBuilder Editing Email templates doesn't work correctly

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#2286]
When I try add containers and components using the EDM editor it looks all wrong
![screenshot from 2016-08-31 10-22-22](https://cloud.githubusercontent.com/assets/3378330/18109438/5f87aa0c-6f65-11e6-8835-26fac8b48ba4.png)

![screenshot from 2016-08-31 10-23-47](https://cloud.githubusercontent.com/assets/3378330/18109418/44b93dee-6f65-11e6-8e37-cb2fc3f139c9.png)

**Comment by ducdhm** [comment]
Reason is `height` of `container-content` is `50px`. It's should `min-height`

**Comment by ducdhm** [comment]
Seem like this screen is loading web snippets instead of edm snippets

**Comment by bradmac** [comment]
Thats because the resource being edited is a html file. I can look into this tomorrow if you like.

**Comment by ducdhm** [comment]
@bradmac Ok. Please help me this issue. Thanks.

**Comment by bradmac** [comment]
Done. Now the edmeditor is editing the ManageSendEmailResource action itself, rather then the html file holding the content. The ManageSendEmailResource class returns true for is("email") and is("edm") so should support the correct set of components

**Comment by bradmac** [comment]
@ducdhm can you check please?

**Comment by ducdhm** [comment]
@bradmac It works. Thanks!
