### ISSUE TITLE
Multiple-choice for quiz

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#2289]
Currently, `Multiple-choice` in quiz is `Single choice`

**Comment by bradmac** [comment]
:+1: 
Definitely a nice to have feature.

**Comment by ducdhm** [comment]
Hi @bradmac, we need thid feature for https://github.com/Kademi/client-ward6-reach/issues/38

**Comment by bradmac** [comment]
Done
![screenshot-localhost 8080 2016-11-29 10-42-23](https://cloud.githubusercontent.com/assets/826458/20687307/dbeb3e40-b620-11e6-9ce1-2777890ead63.png)

**Comment by bradmac** [comment]
Front end
![screenshot-version1 w1 loopbackdns com 8080 2016-11-29 10-45-35](https://cloud.githubusercontent.com/assets/826458/20687360/07c0f8fc-b621-11e6-8e08-d545bb8776e6.png)

**Comment by hoanglinhlan** [comment]
Fail
step:
On admin, select 2 answer for multiple select question
on frontEnd, select 2 correct answer for multiple select and another answer then submit 
Expect: display error about wrong answer
Actual: display popup confirm detail

**Comment by bradmac** [comment]
Fixed

**Comment by hoanglinhlan** [comment]
passed
