### ISSUE TITLE
SMS can be sent twice

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2291]
After the Send button is pressed, it can be pressed again and the same message sent again.

After the button is pressed the end user must not be allowed to send the SMS message again.

![image](https://cloud.githubusercontent.com/assets/2201340/18116220/42c25ab0-6f89-11e6-947c-a112563c6cce.png)

**Comment by bradmac** [comment]
@anhnt can you please ensure the send button is disabled when clicked

**Comment by hoanglinhlan** [comment]
passed
