### ISSUE TITLE
Not choosing an SMS gateway

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2292]
If the account has 2x gateways setup and the user does not choose a gateway, what happens?  Will it send the SMS to both gateways resulting in the end user receiving 2x SMS messages?

If so we should probably make choosing one gateway mandatory.

![image](https://cloud.githubusercontent.com/assets/2201340/18116584/5dabdb96-6f8c-11e6-98d2-72ea4e7438ea.png)

**Comment by bradmac** [comment]
Please make the provide mandatory

**Comment by anhnt** [comment]
That field is already mandatory

**Comment by hoanglinhlan** [comment]
passed
