### ISSUE TITLE
Kademi logging

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2293]
Adding the API key to the clicksend APP created a lot of logging. leadman, braintree etc.  Is this normal?

![image](https://cloud.githubusercontent.com/assets/2201340/18116737/a3bc1bd6-6f8d-11e6-974d-8dd71482274c.png)

**Comment by bradmac** [comment]
I cant see why that would happen, worth a look!

**Comment by bradmac** [comment]
Cant see any problem, probably just a result of setting up the site
