### ISSUE TITLE
Find and replace

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2296]
Would be good to have a find and replace feature in the code editor.

**Comment by ducdhm** [comment]
@paddyow yes, you can. Just press `Ctrl + H` for replace, `Ctrl + F` for searc

**Comment by paddyow** [comment]
@ducdhm is that a common key command that devs will know?  Ctrl F is.  If not we should make this known or have an icon in the search to show the replace fields.

**Comment by bradmac** [comment]
Would be best to have a popup window with a list of keyboard shortcuts
