### ISSUE TITLE
CX Journey Builder: Not extending right

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2298]
There should always be at least 200px of space to the right of the most right node

![screenshot-nzi admin kademi com au 2016-09-01 09-58-54](https://cloud.githubusercontent.com/assets/826458/18147912/eb6a8c5e-702a-11e6-9c07-185b14c51350.png)

**Comment by ducdhm** [comment]
New UI (Bonus: Dotted grid background)
![666666](https://cloud.githubusercontent.com/assets/1289631/18306555/9aa2e398-7516-11e6-839b-8f3013d4f483.png)

**Comment by hoanglinhlan** [comment]
![image](https://cloud.githubusercontent.com/assets/20508726/18341876/4e9d45d6-75d6-11e6-99b9-46533186fcdb.png)

passed
