### ISSUE TITLE
Make theme template editable with content editor

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2300]

**Comment by bradmac** [comment]
Mostly done. Need to add menu editing to the new menu component

**Comment by bradmac** [comment]
Menu editor is now functional, albeit basic. Created an issue to make it more awesomer
https://github.com/Kademi/kademi-dev/issues/2305

**Comment by bradmac** [comment]
To test this...

1. first go to the website manager, theme tab. And click on the "defaultThemeTemplate" item in "Content viewing and authoring"
2. Then edit the base template layout in the content editor

1. Open template editor
![template-ed](https://cloud.githubusercontent.com/assets/826458/18234763/48b790f6-7363-11e6-83a5-1b3829070d3a.png)

2. Edit layout mostly with menu and template body components
![template-ed2](https://cloud.githubusercontent.com/assets/826458/18234774/8e41740c-7363-11e6-8eb1-54b2d2ce4d4a.png)

**Comment by hoanglinhlan** [comment]
Failed 
![image](https://cloud.githubusercontent.com/assets/20508726/19464910/5a2165d6-952a-11e6-8f10-efcf2fb071d5.png)

**Comment by ducdhm** [comment]
@hoanglinhlan It's your local less server's problem

**Comment by bradmac** [comment]
I've created an account for Lan on kademi.us to use

**Comment by bradmac** [comment]
@hoanglinhlan please retest on the kademi.us account

**Comment by hoanglinhlan** [comment]
recheck on the kademi.us passed
