### ISSUE TITLE
KToolbar is clashing with site menu in componentised theme

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2302]
KToolbar uses a fixed position at the top of the page, but so does the site navbar, meaning they site on top of each other

See extras.less line 30 and ktoolbar.less line 3

Temporarily removed navbar-fixed-top in menuComponent.html

Please update so that the menu and ktoolbar work together when fixed

Related to https://github.com/Kademi/kademi-dev/issues/2300

**Comment by anhnt** [comment]
![image](https://cloud.githubusercontent.com/assets/735555/20000365/afcaa2f4-a2a9-11e6-9eda-082d932ca0c0.png)
![image](https://cloud.githubusercontent.com/assets/735555/20000375/bb722280-a2a9-11e6-959b-0ffff2b2682c.png)

Can you guys share your thoughts about above new ktoolbar please @ducdhm @bradmac @tuzzmaniandevil @mamun4343 @paddyow

**Comment by bradmac** [comment]
👍  Perfect!

**Comment by ducdhm** [comment]
It's great 👍  and IMHO, i think we can move setting icon to LHS or RHS of toolbar

**Comment by bradmac** [comment]
i think the middle is good. if its to the right it will get in the way of the user menu, on the left will sit over the brand logo.

**Comment by anhnt** [comment]
thanks guys :) @hoanglinhlan please test on both bs335 and bs335 theme

**Comment by hoanglinhlan** [comment]
passed
