### ISSUE TITLE
Make menu editor awesome

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2305]
We now have a menu component which allows editing menus
- logo editing
- change the path and text for app provided menus
- hide app provided menus
- add custom menu items
- delete custom menu items
- re-order all menu items by drag/drop

BUT this is still not completetly awesome. To be fully awesome we need
- better logo editing, including image upload
- control navbar options, eg inverse, left, right, etc
- sub-menus, ie dropdown
- when adding a custom menu, ability to select a resource (eg a blog, calendar event, or file) or just enter text
- REMOVE the menu editor from the website manager

Here are screen shots of EXISTING functionality which should be modified

![menu1](https://cloud.githubusercontent.com/assets/826458/18234751/be4c0d66-7362-11e6-9104-c571afd9d710.png)

![menu2](https://cloud.githubusercontent.com/assets/826458/18234754/c6a6291a-7362-11e6-8bcb-1256227d7942.png)
![menu3](https://cloud.githubusercontent.com/assets/826458/18234755/c6aa752e-7362-11e6-8e74-59bfa9a54a5f.png)

Note that the menu configuration is now stored in /theme/menu.json. This is what gets edited from the menu editor.

Here is an example json:

```
{
    "items": [
        {
            "id": "menuDashboard",
            "text": "Dashboard",
            "href": "/dashboard",
            "ordering": 0,
            "parentId": "menuRoot",
            "custom": false,
            "hidden": false
        },
        {
            "id": "menu-custom-9508",
            "text": "ABC",
            "href": "/abc",
            "ordering": 1,
            "parentId": "menuRoot",
            "custom": true,
            "hidden": false
        },
        {
            "id": "menu-mycalendars",
            "text": "Calendars",
            "href": "/Calendars",
            "ordering": 2,
            "parentId": "menuRoot",
            "custom": false,
            "hidden": false
        },
        {
            "id": "menu-custom-1185",
            "text": "hhh",
            "href": "/hhh",
            "ordering": 3,
            "parentId": "menuRoot",
            "custom": true,
            "hidden": false
        }
    ]
}
```

**Comment by ducdhm** [comment]
```
* when adding a custom menu, ability to select a resource (eg a blog, calendar event, or file) or just enter text
```
Remaining thing. Will do in next milestone!

**Comment by anhnt** [comment]
Can you add option of toggling visibility of login menu item? @ducdhm

**Comment by ducdhm** [comment]
```
Can you add option of toggling visibility of login menu item? @ducdhm
```
@anhnt Done!
