### ISSUE TITLE
Content Editor: Should be able to set text color with paragraph component

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#2308]
As discussed, rather then add the colour widget we should incorporate additional bootstrap components such as the jumbotron

**Comment by ducdhm** [comment]
I think we can do it with CKEditor?

**Comment by bradmac** [comment]
Yes we can, I'm just not sure if we should. 
When users can set colours directly the site always ends up looking like a mess. Its better if they use components and styles from the pallette.
I spoke to @anhnt about his situation and we decided he will add some bootstrap components to the content editor component list.

**Comment by anhnt** [comment]
should use bootstrap default style
