### ISSUE TITLE
Menu editor and component to support sub menus

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2312]
Related to https://github.com/Kademi/kademi-dev/issues/2305

**Comment by bradmac** [comment]
Add a sub menu item like so..
![submenu1](https://cloud.githubusercontent.com/assets/826458/18257992/44d1ef04-7421-11e6-8dfb-8ae437c6eeeb.png)

And it displays thusly..

![submenu2](https://cloud.githubusercontent.com/assets/826458/18257996/53cb5ca2-7421-11e6-95db-1dfb060c40ab.png)

**Comment by ducdhm** [comment]
@bradmac Should we allow 2-levels menu?

**Comment by hoanglinhlan** [comment]
currently, I cant add sub menu item

**Comment by bradmac** [comment]
Should be just 2 levels. Ie
- Services
 - Cloud technology
 - Consulting
- Products
 - Product 1
 - Product 2

**Comment by hoanglinhlan** [comment]
1: 
![image](https://cloud.githubusercontent.com/assets/20508726/18829815/42f9668e-8408-11e6-9c45-c107805ca7ff.png)

It is difficult to distinguish hide menu and visibility menu => Should be change color for hide menu, Maybe gray button 

2: 
![image](https://cloud.githubusercontent.com/assets/20508726/18830287/4a64ea18-840a-11e6-8a61-5ec46409da7c.png)
when I hover to hide/visibility button, I can see two tooltip with two opposition meaning. Then its difficult to choose hide or visibility menu.

3: theme bs335-leadman
![image](https://cloud.githubusercontent.com/assets/20508726/18830570/7504f334-840b-11e6-8652-7f9e885f4099.png)
Menu label has white color

**Comment by bradmac** [comment]
"3: theme bs335-leadman" <- we have no live bs335 leadman clients, and any new clients will use bs336+. So dont need to worry about that.

**Comment by ducdhm** [comment]
New UI:

![hidden_item](https://cloud.githubusercontent.com/assets/1289631/19200761/ec6a969e-8cf4-11e6-8410-f5c34f3409fb.png)
![new_edit](https://cloud.githubusercontent.com/assets/1289631/19200762/ec70944a-8cf4-11e6-91ad-8a54d1b68987.png)
