### ISSUE TITLE
Add edit template and theme links to ktoolbar

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2313]
This is to make it easier for admins to understand the relationship between pages, page templates and theme templates, and to make it easier to find them.

From viewing a page they can open an editor for either one.

![screenshot-version1 lp loopbackdns com 8080 2016-09-06 13-50-31](https://cloud.githubusercontent.com/assets/826458/18259532/02e94836-7439-11e6-9574-a5e30fb8b008.png)

**Comment by hoanglinhlan** [comment]
New links still not display 
http://lan-testing.admin.kademi.us/websites/quickadd/version1/#panel_theme-tab
http://version1.quickadd.kademi.us/profilepage.html

**Comment by ducdhm** [comment]
Fixed on local

**Comment by hoanglinhlan** [comment]
passed
