### ISSUE TITLE
add new page: File name created wrong 

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2318]
**Step**
1. Set title for new page
2. Selected Default folder page
3. Save and close

**Expect**: create new file: index.html
**Actual**: create new file 	2016_8_6_124.html

**Comment by ducdhm** [comment]
@hoanglinhlan It'll happen when you already have index.html page

**Comment by ducdhm** [comment]
Ahh, I found the way to reproduce

**Comment by hoanglinhlan** [comment]
Create a new page: 
File name - choose Default folder page: 2 case 
- case1: index.html existed, file name has created date.
- case2: index.html not existed, file name is index.html
File name - dont choose Default folder page: create file with name that use input

passed
