### ISSUE TITLE
Calendar event component improvements

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2321]
- use a standard breadcrumb component instead of a calendar specific one
- move all js and css out of the component, and into dependencies.  This should allow for multiple event components in one page
- make calendar and event selection available in settings. If none selected then the template should attempt to use the current page.
- remove components for administration of events, ie add event button and hidden editor. This will all be done in the backend.

**Comment by anhnt** [comment]
We need to test this by:

- Edit native calendar templates which in calendar app
- Drag/drop those components to any page with settings

**Comment by hoanglinhlan** [comment]
passed
