### ISSUE TITLE
Integrate custom apps with the journey builder

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2324]
Allow adding through controller mappings. Eg

```
controllerMappings.addNodeType("kfeedbackSubmittedGoal", "kfeedback/jb/kfeedbackSubmittedGoalNode.js"); // responds to a funnel event with id kfeedbackSubmittedGoal
controllerMappings.addActionNodeType("kfeedbackSendRequest", "kfeedback/jb/kfeedbackSendRequest.js", "sendFeedbackRequest"); // invoke js which will send an email

```

That will register a goal node type with the journey builder. The app can then trigger the goal as complete by firing a corresponding event.

**Comment by bradmac** [comment]
Note that custom app goals will all be of the same json type of "customGoal". So we need to differentiate between different node types by some other ID.

Custom nodes will be registered in the journey builder with a unique ID (eg kfeedbackSubmittedGoal) but will use the json type of "customGoal". Nodes have a  nodeType property to hold the unique identifier of the node type.

I've added  this method to journeyBuilder.js to get a node type object either from the typename or from the node.nodeType property if necessary
```
    getNodeType: function (node, typeName) {        
        var nodeType = JBNodes[typeName];
        if( nodeType == null ) {
            flog("getNodeType try", node.nodeType);
            if( node.nodeType ) {
                nodeType = JBNodes[node.nodeType];
            }
        }
        flog("getNodeType", node, typeName, "nodeType=", nodeType);
        return nodeType;
    },
```

**Comment by bradmac** [comment]
@ducdhm can you finish up please? Its mostly working now, but connections drag from the top left corner, and they dont appear after the bind

**Comment by ducdhm** [comment]
Done!

**Comment by bradmac** [comment]
Also, need to support actions.

I've added RepoAppAction which has json type "customAction". It has properties appId and jsMethod which must be set. These should be populated from the app provided js (somehow)

**Comment by bradmac** [comment]
@ducdhm could you create a custom action as part of kfeedback which emails a selected survey? When done please create documentation in docs.kademi.co showing how to create custom goals and actions

**Comment by ducdhm** [comment]
Ok

**Comment by bradmac** [comment]
Realised the approach implemented above is all screwy. Should use the nodeType property to identify the NodeType, and then get the jsMethod from that.

**Comment by bradmac** [comment]
@ducdhm should be ok to finish off now. Custom actions are basically the same as for custom goals

**Comment by bradmac** [comment]
Related - https://github.com/Kademi/kademi-dev/issues/2587

**Comment by ducdhm** [comment]
@anhnt done this issue in other issue
