### ISSUE TITLE
Event Calendar: display date time error

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2328]
- Create event for a calendar
- go to event detail page 
=> Date and time display error

![image](https://cloud.githubusercontent.com/assets/20508726/18303759/e3a38560-7508-11e6-87b0-0bfc1932aa70.png)

**Comment by bradmac** [comment]
Looks like the server is not correctly parsing the date when creating hte event.

**Comment by anhnt** [comment]
It was the daterangepicker config. now it will look like following:
```    {
          timePicker: true,
          timePickerIncrement: 15,
          timePicker12Hour: false,
          locale: {
              format: 'DD/MM/YYYY HH:mm'
          }
    }```

**Comment by hoanglinhlan** [comment]
passed
