### ISSUE TITLE
Event Calendar: 404 error when click Link of guest in attending 

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2330]
- Register an event then add a guest
- Click to any guest link in list attending

==> system show 404 error. Maybe the reason is that the guest is not a member so I think we should display a more reasonable notice

**Comment by bradmac** [comment]
Most likely there is just a js error. Clicking the link should show a modal.

**Comment by hoanglinhlan** [comment]
Passed
