### ISSUE TITLE
Cant change avatar

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2331]
Cant change profile's avatar

**Comment by bradmac** [comment]
@hoanglinhlan is that in admin profile page or front end? Is there an error? And what theme did you see this with?

**Comment by hoanglinhlan** [comment]
@bradmac  that is in admin profile page. it's an error.

**Comment by hoanglinhlan** [comment]
![image](https://cloud.githubusercontent.com/assets/20508726/18307146/4d1e9038-7519-11e6-9968-acf7d83367a1.png)
when I click crop or save, system show popup with error message. I tried with many image( jpg, png, big size, small size ...) but system always show error message

**Comment by ducdhm** [comment]
@bradmac @hoanglinhlan It's correct because it's locally kademi in Window. Cropping image doesnt work on Window

**Comment by bradmac** [comment]
Yep, depends on linux utilities

**Comment by ducdhm** [comment]
@bradmac But I got other issue with it. I can not save the uploaded image (without cropping). It's happening on local and prod, too

**Comment by bradmac** [comment]
Admin works when using crop, but there is an error when saving without cropping

**Comment by bradmac** [comment]
Fixed upload without crop

**Comment by hoanglinhlan** [comment]
change avatar worked
