### ISSUE TITLE
Event Calendar: FrontEnd - Display description wrong

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2332]
Dont fill content for event then go to frontEnd. This event display description wrong 

![image](https://cloud.githubusercontent.com/assets/20508726/18305638/addcea34-7512-11e6-9150-e3046f48fbe6.png)

**Comment by anhnt** [comment]
couldnt reproduce

**Comment by hoanglinhlan** [comment]
@anhnt : Pls re-check 
http://version1.bs335-leadman-web.kademi.us/Calendars/M2M%20show/
http://lan-testing.admin.kademi.us/Calendars/M2M%20show/m2m-euro-show#details-tab

**Comment by anhnt** [comment]
Do we support bs335.leadman theme anymore? can you please advise @bradmac

**Comment by anhnt** [comment]
As discussed with Brad, we now just use Leadman theme for testing with lead management app. I will fix this issue for bs335 though
