### ISSUE TITLE
JourneyBuilder: Move rule editing to the decision node

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#2338]
On decision node settings panel, display a list of choices (ie transitions). The use can click each one to open the rule editor for that choice. This will replace clicking on a transition.

The user cannot change transitions from this settings panel, they can only edit the rules for the current transitions

**Comment by ducdhm** [comment]
wont do it

**Comment by ducdhm** [comment]
New UI: 
![qqqqqqqqqqqqqq](https://cloud.githubusercontent.com/assets/1289631/18344226/98ab765c-75e0-11e6-911f-8ab779b6ccb6.png)

**Comment by bradmac** [comment]
@ducdhm could you remove the "send email" part from the rule text? Just having the icon and the node label would be perfect. And just reduce the indentation by about half of the rules lists

**Comment by ducdhm** [comment]
@bradmac Ok.

**Comment by ducdhm** [comment]
Done!

**Comment by hoanglinhlan** [comment]
1. Should highlight button selected
2. Cant choose condition
![image](https://cloud.githubusercontent.com/assets/20508726/18499587/84147282-7a6a-11e6-8476-72b74600c067.png)

**Comment by ducdhm** [comment]
```
1. Should highlight button selected
```
Fixed

```
2. Cant choose condition 
```
It's default behavior of query builder. You can check original of this at http://querybuilder.js.org/demo.html. And IMO, I think it's right behavior, if you have only 1 rule or group, you dont need choose condition is `AND` or `OR`

**Comment by bradmac** [comment]
"if you have only 1 rule or group, you dont need choose condition is AND or OR" :+1:

**Comment by hoanglinhlan** [comment]
1: passed 
2: +1
