### ISSUE TITLE
Integrate custom apps with content editor

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2339]
Custom apps should be able to provide components

**Comment by bradmac** [comment]
@anhnt can you finish integrating kfeedback app?
https://github.com/Kademi/kademi-app-kfeedback/tree/master/kfeedback/admin/theme/apps/kfeedback

What i would like to do is
- the kfeedbackEmail component settings should allow the user to select a survey. 
- the component will then generate the email snippet in the EDM

Then please document the component editor integration process in a module on docs.kademi.co

**Comment by anhnt** [comment]
Document: http://docs.kademi.co/programs/dev/d3/app-4/padding-component-to-content-editor.html

**Comment by bradmac** [comment]
Couple of things
- please add an opening slide which says what the module is teaching
- please remove the black background on source snippets. Use default pre style
- add an explanation of why we need separate components for email and web

**Comment by anhnt** [comment]
done http://docs.kademi.co/programs/dev/d3/app-4/
