### ISSUE TITLE
Journey builder: Save website wrong when setting email node

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2340]
**Step**:
1. Create a funnel, add send email node 
2. Edit setting in email node: set a website and save
3. then go to email manage of this node 
4. select others website and save 
5. check setting node 

**Expect for each step:**  
3. tab send information, value of website dropdown is the website selected in step 2
5. in setting node, value of website dropdown is the website selected in step 4

**Comment by tuzzmaniandevil** [comment]
Fixed, @hoanglinhlan Please re-test

**Comment by hoanglinhlan** [comment]
passed
