### ISSUE TITLE
Journey builder: Assign-to step

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2346]
Create a new journey node which will allow assignment of the lead.

Leads can be assigned to and or all of:
- organisation
- group
- sales person

**Comment by tuzzmaniandevil** [comment]
:+1:

**Comment by bradmac** [comment]
Hi @hoanglinhlan, with this feature you should check that a group, organisation OR profile can be assigned to.

Note that the list of available organisations shown only lists organisations which have the org type specified as the sales org type in the leadman app settings.

**Comment by hoanglinhlan** [comment]
passed
