### ISSUE TITLE
Make profile timeline limited by selected date range

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2347]
Use the common date range selector to filter the displayed date range on profiles.

Add a "Show more" button at the bottom of the timeline which loads and appends items for the preceding time period

**Comment by bradmac** [comment]
Raised to a p0

**Comment by bradmac** [comment]
@Uafinder i think this is ok now. What i did is removed journey transitions from the profile timeline. These are still shown on the timeline for a lead, but only those specifically for the current lead.

So this reduces the number of items in the timeline hugely, and performance seems ok now, even without a date range filter.

**Comment by Uafinder** [comment]
Yeah, looks much better
