### ISSUE TITLE
Reset password issue 

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2348]
1. Cant access reset password site
http://www.kademi.co/

- Login then click Forgotten password
- Open reset password link 

**Expect**: access this site, display reset pass area and customer can reset pass success
**Actual**:  Cant access this site

**Comment by hoanglinhlan** [comment]
2. Dont received reset pass email
at admin domain, when I choose forfot password. I dont received any email for reset pass

**Comment by bradmac** [comment]
Looks like the queue processor was stopped. Restarted last night and seems to work ok now. @hoanglinhlan please confirm

**Comment by hoanglinhlan** [comment]
send email still slowly. I choose forgot password 5mins ago but I dont receive any email

**Comment by bradmac** [comment]
Thats probably not slow, its probably not being sent

**Comment by hoanglinhlan** [comment]
yeap and I cant see that email in email history

**Comment by hoanglinhlan** [comment]
ops, just received reset mail. So I think it slowly

**Comment by bradmac** [comment]
thats crazy slow, there is no reason why it should take longer then 60secs

**Comment by tuzzmaniandevil** [comment]
@hoanglinhlan  I've fixed a couple of null pointer exceptions, please re-test

**Comment by hoanglinhlan** [comment]
confirm passed
