### ISSUE TITLE
Fix admin dashboard builder

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2349]
Currently when i open the admin dashboard builder (http://localhost:8080/dashboards/) i see the content editor, but i cant drop layouts into the page. I see a large number of js errors.

```
TypeError: i.options is undefined
```

**Comment by ducdhm** [comment]
Can you double-check again? I dont see any error message log. Maybe it's fixed in other issues?

**Comment by bradmac** [comment]
Yep, works fine now
