### ISSUE TITLE
Journey Builder: Add to group settings does not re-display selected group

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2354]
- Add a "Add to Group" node to a funnel
- open the settings panel
- select a group
- press Save on the settings panel
- open the settings panel again
- the same group should be re-displayed, but is not

I checked the json and confirmed that it is saving the selected value, just not redisplaying

**Comment by ducdhm** [comment]
@bradmac Can you check again? It works normally in my side

**Comment by bradmac** [comment]
Looks good to me
