### ISSUE TITLE
Saving an email

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2356]
As I created an email for a journey, I intuitively clicked on the top save button, and not the save button in the email editor resulting in me losing my email.  
- Maybe we only have one save button that saves all email data and returns back to the builder
- Or two options, save and save and exit

![image](https://cloud.githubusercontent.com/assets/2201340/18468460/6ea6c0b8-79e7-11e6-888f-efb5487aa4a4.png)

**Comment by bradmac** [comment]
True. I think we should not use an iframe for email editor. It should be part of the page, and use the page save button

**Comment by ducdhm** [comment]
I think we can use embedded mode of KEditor instead of iframe link to EDM Editor page like current. I'll create edmEditor plugin for it

**Comment by ducdhm** [comment]
We have new approach for edmEditor for journey email. So just close it
