### ISSUE TITLE
Show tasks in chronological order

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2357]
Most recent due at the top

![image](https://cloud.githubusercontent.com/assets/2201340/18469091/1056322a-79ea-11e6-8b63-94f16922b439.png)

**Comment by hoanglinhlan** [comment]
confirm passed

**Comment by paddyow** [comment]
This is working however I feel completed tasks should appear under active tasks.   Below you will see how completed tasks are appearing at the top, but I want my most recent active task to appear at the very top.

![image](https://cloud.githubusercontent.com/assets/2201340/19264126/37fc1ac6-8feb-11e6-8c9d-7c41e9bb60b0.png)

**Comment by bradmac** [comment]
i think this is sorted now as we've changed the layout to show pending tasks seperately
