### ISSUE TITLE
Adding extra funnel stage warm

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2361]
http://clickstartdigital.admin.kademi.com.au/funnels/customerform/#properties-tab

I created 2x funnel stages but by default it's adding warm when I do not want a warm stage.

**Comment by bradmac** [comment]
I dont know what you mean? Where does it say "warm"? Maybe a screen shot would help.

**Comment by paddyow** [comment]
http://clickstartdigital.admin.kademi.com.au/funnels/customerform/#properties-tab
These funnel stages are defined in the admin
![image](https://cloud.githubusercontent.com/assets/2201340/18478505/e4f7d996-7a14-11e6-82c9-afa280f0e6d2.png)

This is what you see in KCRM
http://clickstart-digital-crm.kademi.com.au/analytics/customerform

![image](https://cloud.githubusercontent.com/assets/2201340/18478528/f6b154aa-7a14-11e6-860d-5a03b9f1b416.png)

**Comment by bradmac** [comment]
@paddyow  That will be because there are leads in the hot and warm stages. Just edit or delete them
