### ISSUE TITLE
Lead not showing in funnel

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2362]
http://clickstart-digital-crm.kademi.com.au/leads/21968328/

Stage: In progress

Is not appearing in the funnel here http://clickstart-digital-crm.kademi.com.au/analytics/customerform

**Comment by bradmac** [comment]
This lead - http://clickstart-digital-crm.kademi.com.au/leads/21968328/ (test@kademi.co) is in the leadform funnel.

But you are looking at the customerform funnel in the analytic page link above

**Comment by paddyow** [comment]
Paul Barry is in the Customer Funnel http://clickstart-digital-crm.kademi.com.au/leads/21975707/
Stage: In progress

He is not appearing in the In Progress funnel section here http://clickstart-digital-crm.kademi.com.au/analytics/customerform

**Comment by bradmac** [comment]
500 error here - http://clickstart-digital-crm.kademi.com.au/analytics/customerform?asJson&aggr=assignedToOrg.id&filters=&stage=

**Comment by bradmac** [comment]
500 should be fixed now.

Next issue i can see is that incorrect leads are displaying at the bottom of the analytics page. They are not being filtered by the funnel.

**Comment by bradmac** [comment]
And wasnt applying org filtering properly, just all over the place really. Should be correct now.

**Comment by bradmac** [comment]
![screenshot-version1 kcrm loopbackdns com 8080 2016-09-14 15-12-53](https://cloud.githubusercontent.com/assets/826458/18498847/ff0fd95e-7a8d-11e6-9bd1-812c3eec50c3.png)

**Comment by hoanglinhlan** [comment]
refer #2169
