### ISSUE TITLE
Allow creating new tags from the add tag button

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2363]
![image](https://cloud.githubusercontent.com/assets/2201340/18476825/dac0e32e-7a0e-11e6-87b5-61da20282a2f.png)

**Comment by bradmac** [comment]
Create groups in the backend

**Comment by paddyow** [comment]
Lets add a feature that enables the user to create Tags from that button with ease.

**Comment by diegoperezn** [comment]
@gonzalon Could you code review?

**Comment by bradmac** [comment]
@diegoperezn as discussed, please apply changes to the versioned repository lib code. We should never make changes to static web assets, and will completely remove them at some point

**Comment by bradmac** [comment]
@hoanglinhlan i think this is ready to test. Please assign to me if any problems

**Comment by hoanglinhlan** [comment]
passed
