### ISSUE TITLE
Cannot define the source for a form submit in the funnel builder.

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2365]
There is no where to set the source when a form is submitted.

![image](https://cloud.githubusercontent.com/assets/2201340/18477182/1c06bdd0-7a10-11e6-9d81-ca7c9022620b.png)

**Comment by bradmac** [comment]
@ducdhm please ensure all goals have a common editable fields:


    protected String stageName; // for flattening analytics into a sequential series of stages, not sure if we need it

    protected BigDecimal cost; // acquisition cost

    protected BigDecimal probability; // probablility of converting this goal

    protected String source; // the source of the lead this goal indicates, ie facebook or google ads

**Comment by hoanglinhlan** [comment]
passed
