### ISSUE TITLE
Lead timeline issue

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2366]
http://clickstart-digital-crm.kademi.com.au/leads/21976518/

When I complete a task in KCRM:
![image](https://cloud.githubusercontent.com/assets/2201340/18477768/2553df4c-7a12-11e6-8b7f-c5879ff0944d.png)

It appears as a contact in the lead timeline:
![image](https://cloud.githubusercontent.com/assets/2201340/18477796/44619f1e-7a12-11e6-961f-ad338e67fa5e.png)

Should appear as a task complete icon with relevant text.

**Comment by bradmac** [comment]
Tasks are now shown on the timeline when created. And when completed that adds another item to the timeline

![screenshot-version1 kcrm loopbackdns com 8080 2016-09-14 13-07-25](https://cloud.githubusercontent.com/assets/826458/18496720/49ca009e-7a7c-11e6-979a-1d0669f44d43.png)
