### ISSUE TITLE
Email timeline events not appearing

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2368]
http://clickstart-digital-crm.kademi.com.au/leads/21976518/

When an email is sent to a profile it appears in the Kademi Admin.
http://clickstartdigital.admin.kademi.com.au/manageUsers/21976508/#summary-tab

Does not appear in KCRM timeline:
http://clickstart-digital-crm.kademi.com.au/leads/21976518/

**Comment by bradmac** [comment]
That was because the email app was disabled for the kcrm site, and the email app provides email items to the timeline. I've enabled it now
