### ISSUE TITLE
Funnel Timer Goal not working

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2369]
http://clickstartdigital.admin.kademi.com.au/funnels/leadsform/#journeyBuilder-tab

I created a timer goal of 24 hours & also tried 1 day but the 2nd email always fires within minutes.

Profile http://clickstartdigital.admin.kademi.com.au/manageUsers/21974945/#summary-tab

**Comment by bradmac** [comment]
Wasnt applying units correctly.

**Comment by hoanglinhlan** [comment]
passed
