### ISSUE TITLE
Switching funnel does not update stage drop down

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2371]
http://clickstart-digital-crm.kademi.com.au/leads/21975623/

So I have 2x funnels, both have different stages.
If i change the funnel using the drop down, the stage drop down options does not update.  
i can then choose a stage in the wrong funnel. This then adds that stage to the wrong funnel.

![image](https://cloud.githubusercontent.com/assets/2201340/18500427/ac1492ce-7a8a-11e6-8235-86d25442882d.png)

![image](https://cloud.githubusercontent.com/assets/2201340/18500457/ea73c83c-7a8a-11e6-8cad-e59ec2191bd3.png)

**Comment by bradmac** [comment]
Just change the funnel, save, then refresh the page.

**Comment by paddyow** [comment]
But a customer will not do that therefore they will encounter the same problem I did.  We cannot ask our customers to refresh a page after they have reconfigured a drop down.

**Comment by bradmac** [comment]
Will look into it some time in the future. Not a priority
