### ISSUE TITLE
Kademi KCRM tasks look incorrect on dashboard

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2373]
http://kcrm.kademi.us/dashboard

The information in the task panel looks different (lacking info) and the delete icon is in the take task button.

Is this due to the import going wrong?

![image](https://cloud.githubusercontent.com/assets/2201340/18504393/6d0e1f76-7aa5-11e6-95f0-d60d151ecfa2.png)

![image](https://cloud.githubusercontent.com/assets/2201340/18504670/da3a98b2-7aa6-11e6-9e01-8d4e7134a486.png)

This is how a task should look:
![image](https://cloud.githubusercontent.com/assets/2201340/18504656/c79ead1a-7aa6-11e6-87ad-8d5ad916159e.png)

**Comment by paddyow** [comment]
This looks like an import issue. Creating a new task looks fine.

**Comment by tuzzmaniandevil** [comment]
I've re-imported the tasks after fixing some bugs. @paddyow please re-check
