### ISSUE TITLE
Completing task causes error page

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2375]
NB I have cleared my cache;
http://clickstart-digital-crm.kademi.com.au/leads/22009517/

Create a new task

Click the tick button
![image](https://cloud.githubusercontent.com/assets/2201340/18505167/607cec3e-7aa9-11e6-9b7b-0a11bf450146.png)

Click the next green tick button
![image](https://cloud.githubusercontent.com/assets/2201340/18505186/7e76135a-7aa9-11e6-8b44-27e384fbbc87.png)

Add some copy then click Done
![image](https://cloud.githubusercontent.com/assets/2201340/18505206/911b57f4-7aa9-11e6-8a23-2360b18cd07f.png)

I then get this error page
![image](https://cloud.githubusercontent.com/assets/2201340/18505217/9ef4c338-7aa9-11e6-8edb-0353565ebbf4.png)

**Comment by bradmac** [comment]
Should be solved now
