### ISSUE TITLE
Change KCRM timeline in desktop

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2376]
When at a desktop break-point the timeline is squashed and the arrows are hidden.

![image](https://cloud.githubusercontent.com/assets/2201340/18505377/4c0b5898-7aaa-11e6-8f36-2ec523d5eb32.png)

I say at all breakpoints we have the icons down the LHS of the panel creating more room for the information in the panel. 

![image](https://cloud.githubusercontent.com/assets/2201340/18505358/330ca6ee-7aaa-11e6-93ad-e9c99a860ff2.png)

**Comment by bradmac** [comment]
this is just the standard timeline component, probably not worth spending time on it
