### ISSUE TITLE
Define Group Property

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2377]
Add option upon group creation to choose it's type i.e. primary or tag.  Otherwise creating lots of tags means opening each group and then defining it;s property which can take a long time.

![image](https://cloud.githubusercontent.com/assets/2201340/18511311/5d310552-7ac6-11e6-9c1a-4b7d90796c8c.png)

**Comment by bradmac** [comment]
@ducdhm i think this can be done with a front end change. If you need backend support please ping me.

**Comment by ducdhm** [comment]
New UI:

![newui](https://user-images.githubusercontent.com/1289631/28810382-b670f02a-76b3-11e7-990d-31f606fc5c2d.png)
