### ISSUE TITLE
Tag/optin group icon

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2378]
http://clickstartdigital.admin.kademi.com.au/groups/

Feel this should be a different icon.  As tags will be used a lot for segmentation then we should probably show a tag like icon.  We should also update the text at the end of the row not to show mailing list but 'Tag/Opt-in Group'.

![image](https://cloud.githubusercontent.com/assets/2201340/18511500/67f11c38-7ac7-11e6-9231-41d1b0e50627.png)

![image](https://cloud.githubusercontent.com/assets/2201340/18511507/818f67ee-7ac7-11e6-8cad-49170d5f8a6c.png)

**Comment by hoanglinhlan** [comment]
passed
