### ISSUE TITLE
Adding source issue

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2380]
http://clickstartdigital.admin.kademi.com.au/repositories/leadsform/version1/texteditor?fileName=funnel.json

When manually adding the source for the lead funnel:
![image](https://cloud.githubusercontent.com/assets/2201340/18512059/9b7a5de6-7aca-11e6-841c-f04119d5a9fd.png)

I get this error:
![image](https://cloud.githubusercontent.com/assets/2201340/18512067/a4e432c6-7aca-11e6-9e84-fb9e30f5350c.png)

I also need to set the source on this funnel to Payment Online:
http://clickstartdigital.admin.kademi.com.au/repositories/customerform/version1/texteditor?fileName=funnel.json

Not sure what I have done wrong.  Can you please fix up.

**Comment by bradmac** [comment]
The source attribute on a goal has in the past been an expression, which is evaluated to extract a parameter from a cookie or request parameter. "Website" was not a valid expression, so it was producing an error message.

I have changed this so now source is treated as a template, so you can have plain text like Website, but we can also use template code if we need to extract a field from the request.

**Comment by bradmac** [comment]
The source still needs to be integrated with the UI, but this is on this issue - https://github.com/Kademi/kademi-dev/issues/2365

So will close this one.
