### ISSUE TITLE
Assigning profile to lead group does not show lead in KCRM

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2382]
I added the below profile into the Lead group.
http://kademi.admin.kademi.us/manageUsers/1973945/#general-tab

I presumed it would appear in KCRM http://kcrm.kademi.us/dashboard

Is this correct?  If not what am I doing wrong?

**Comment by bradmac** [comment]
You created a profile, but that profile does not have any associated leads, so you will not see any leads for it.

You can see that profile on the profiles page - http://kcrm.kademi.us/custs/?q=testgroup2%40kademi.co&g
