### ISSUE TITLE
Make group memberships editable

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2384]
The manage profile page allows group memberships to be added and deleted. 

![screenshot-clickstartdigital admin kademi com au 2016-09-15 13-39-20](https://cloud.githubusercontent.com/assets/826458/18535643/1c4c6f8e-7b4a-11e6-8e32-238f8be34f72.png)

However, we also want users to be able to edit a membership. This should allow the organisation of the membership to be changed.

We want the user interface to remain quite clean the way it is now. I think adding an edit button beside the current X (for delete) will get messy. Instead maybe just have a 3 bars icon (http://fontawesome.io/icon/bars/) which opens a modal, which allows editing and delete?

**Comment by anhnt** [comment]
done 
![image](https://cloud.githubusercontent.com/assets/735555/26243784/46831a62-3cb7-11e7-9dff-59761fd5bdb4.png)

**Comment by bradmac** [comment]
:+1:

**Comment by hoanglinhlan** [comment]
passed
