### ISSUE TITLE
Content Editor: Create Accordion Component

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#2385]
http://getbootstrap.com/javascript/#collapse-example-accordion

This layout is helpful for building FAQ content

**Comment by bradmac** [comment]
:+1:

**Comment by ducdhm** [comment]
:+1:

**Comment by anhnt** [comment]
Done

**Comment by bradmac** [comment]
:+1:

**Comment by anhnt** [comment]
Need to display first accordion item content and hide all other item content when export this component to html
