### ISSUE TITLE
Theme checker page

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2387]
Have a page which shows all bootstrap components and styles to check the theme integration

**Comment by bradmac** [comment]
![screenshot-localhost 8080 2016-09-16 17-06-21](https://cloud.githubusercontent.com/assets/826458/18575842/027322b0-7c30-11e6-90ba-3d0008cd8c62.png)

**Comment by bradmac** [comment]
Eg

![screenshot-version1 kcrm loopbackdns com 8080 2016-09-16 17-07-23](https://cloud.githubusercontent.com/assets/826458/18575852/15c1b110-7c30-11e6-80bc-958d1b966a87.png)

**Comment by hoanglinhlan** [comment]
![image](https://cloud.githubusercontent.com/assets/20508726/18827140/6eb8745c-83fb-11e6-8fc6-bae00c90d42e.png)

My website display normaly but when theme checker page display with many wrong 
+. Theme: bootstrap335.leadman 
+. List apps seted on status: 
- User dashboar
- Funnels and lead management
- Lead management
- Team Management

**Comment by bradmac** [comment]
Only use theme checker with the Bootstrap marketplace theme (ie 336+).

Its not going to work properly with the old theme architecture
