### ISSUE TITLE
Cannot search for profile

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2388]
http://kcrm.kademi.us/leads/2013106/

I created a lead without an email , which is fine as I do not have an email yet.  But when I searched for the profile based on his name, it did not appear in the search.

Need to be able to search for leads based on their name where they might not have an email.

**Comment by bradmac** [comment]
I think its probably not creating the profile, because in the past a profile required an email address. But now we can have profiles without emails, so we can create the profile always

**Comment by bradmac** [comment]
Please confirm if this is still an active issue, it may have been resolved

**Comment by diegoperezn** [comment]
Its working fine

![captura de pantalla 2017-05-19 a las 11 58 15](https://cloud.githubusercontent.com/assets/26150017/26228064/83e841f2-3c8a-11e7-8ca7-ade352420e8a.png)

**Comment by hoanglinhlan** [comment]
it's work now
