### ISSUE TITLE
Inverse option for container and components

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#2394]
Support inverse style for
 * Container
 * Column container
 * Jumbotron component
 * ... 

Add default inverse style in `extra.less`

**Comment by anhnt** [comment]
breadcrum and navbar

**Comment by ducdhm** [comment]
@anhnt Please continue with other components which you want/need

**Comment by anhnt** [comment]
breadcrumb is done

**Comment by anhnt** [comment]
I think its enough for now. Will reopen if we have new component which needs inverse
