### ISSUE TITLE
Content editor: HTML editor components should have format and style dropdowns

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2395]
Should have the same ability as the previous generation editor:
![screenshot-version1 w1 loopbackdns com 8080 2016-09-19 21-42-08](https://cloud.githubusercontent.com/assets/826458/18627949/ffa28c18-7eb1-11e6-8675-7201500d9f87.png)

Also, the font family, size and colour options should be removed to encourage content editors to use theme provided styles

Applies to all components which have a ckeditor toolbar

See themes/bootstrap335/styles.js for style definitions

**Comment by ducdhm** [comment]
Update UI:
![fireshot screen capture 006 - edit_ gallery_html - version1_milestone_loopbackdns_com_8080_contenteditor_filename gallery_html miltonuserurl _users](https://cloud.githubusercontent.com/assets/1289631/18679342/6e18b01e-7f89-11e6-84ab-339bc57ea06d.png)

**Comment by hoanglinhlan** [comment]
A Component still doesnt has format and style dropdowns: Accordion

**Comment by hoanglinhlan** [comment]
confirm fixed
