### ISSUE TITLE
Cannot add profile to Group

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2396]
This group http://kademi.admin.kademi.us/groups/agency-campaign-1/members/

When adding manually or using the Profile uploaded.  See below adding manually.

![image](https://cloud.githubusercontent.com/assets/2201340/18630151/f2f38638-7ead-11e6-8517-3908d83c7737.png)

**Comment by paddyow** [comment]
Might relate to #2405 and #2404

**Comment by tuzzmaniandevil** [comment]
This has been sorted :-)
