### ISSUE TITLE
KCRM leads have not been imported correctly

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2397]
See this lead on OLHUB http://kcrm.olhub.com/leads/198787609/
See this lead on US http://kcrm.kademi.us/leads/1938763/

This seems to be the correct lead however:
1) The notes did not get moved across
2) The task did not get moved across

This lead on OLHUB http://kcrm.olhub.com/leads/147954214/
This lead on US http://kcrm.kademi.us/leads/1939525/

Same issue where tasks, notes etc have not been moved across

http://kcrm.olhub.com/leads/131452831/
http://kcrm.kademi.us/leads/1938695/

No notes, no tasks. Also the lead name on OLHUB says John Cairns (Pfizer Hong King)  on US says 	
john.cairns

**Comment by paddyow** [comment]
Will this require all profiles to be moved across again?

**Comment by tuzzmaniandevil** [comment]
This issue https://github.com/Kademi/kademi-dev/issues/2410 will sort it out, But all leads will need to be deleted and re-imported

**Comment by tuzzmaniandevil** [comment]
I've re-imported leads. http://kcrm.kademi.us/leads/2266281/

**Comment by tuzzmaniandevil** [comment]
@paddyow please recheck
