### ISSUE TITLE
KCRM: Notes CSV Export/Import

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#2400]

**Comment by hoanglinhlan** [comment]
Export: should add Lead info
Import: not working. System show message: uploaded successfully but it not add new note or update exist notes

**Comment by diegoperezn** [comment]
@bradmac here do you want to change the import to a wizard or just add the that lan is asking for?

**Comment by bradmac** [comment]
@diegoperezn this isnt actually an important feature, so quickest is best

**Comment by hoanglinhlan** [comment]
seem like it's still not working 
http://lan-test.admin.kademi.com.au/funnels/
to check it
Please export file and edit (all data of lead profile) then upload
