### ISSUE TITLE
Content Editor Sidebar elements should not be affected by theme 

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#2402]
Please see button in sidebar

![image](https://cloud.githubusercontent.com/assets/735555/18700961/44339266-8004-11e6-9140-eb6284563d12.png)

**Comment by bradmac** [comment]
Have a look at the bootstrap button styles here
http://getbootstrap.com/css/#buttons-sizes

I think the "Events Portfolio" button should probably be a large button. But the "change background" button should be normal size

**Comment by bradmac** [comment]
As discussed, i think a correctly implemented theme will work fine with side bar controls. So we can close this issue for now.
