### ISSUE TITLE
Cannot send email to profile using compose button

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2404]
http://kademi.admin.kademi.us/manageUsers/2124015/#emailAppTab-tab

![image](https://cloud.githubusercontent.com/assets/2201340/18707671/89c15968-803a-11e6-9037-f7aae355d727.png)

**Comment by tuzzmaniandevil** [comment]
Same issue as #2396 so also sorted

**Comment by paddyow** [comment]
Still not working.  See profile http://kademi.admin.kademi.us/manageUsers/2156360/#emailAppTab-tab

![image](https://cloud.githubusercontent.com/assets/2201340/18750223/9a8f43d4-811d-11e6-939e-d663b87a97ca.png)

I also have a journey built here which adds profiles to a group then fires an email which isnt sending http://kademi.admin.kademi.us/funnels/agency-sales/#journeyBuilder-tab

**Comment by tuzzmaniandevil** [comment]
@paddyow That is a seperate issue, That's because the domain hasn't been verified by AWS yet. Will do that today

**Comment by tuzzmaniandevil** [comment]
@paddyow please retest
