### ISSUE TITLE
Cannot upload profiles into group - has import error

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2405]
This file 
[Test data.xlsx](https://github.com/Kademi/kademi-dev/files/484731/Test.data.xlsx)

Into this group http://kademi.admin.kademi.us/groups/agency-campaign-1/members/

![image](https://cloud.githubusercontent.com/assets/2201340/18707929/a22535aa-803b-11e6-851b-a6f57c4ba096.png)

![image](https://cloud.githubusercontent.com/assets/2201340/18707945/ae6f4378-803b-11e6-8d2d-88483e154311.png)

![image](https://cloud.githubusercontent.com/assets/2201340/18707953/b7a2c280-803b-11e6-8e79-7c9733138eac.png)

![image](https://cloud.githubusercontent.com/assets/2201340/18707963/c65b31ae-803b-11e6-8cde-74ec9ead6219.png)

**Comment by tuzzmaniandevil** [comment]
This has also been fixed
