### ISSUE TITLE
Add title setting to visualisation components

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2409]
The pie chart and date histogram components should have a title property which displays in the panel heading.
![screenshot-version1 demo-dash loopbackdns com 8080 2016-09-22 15-19-13](https://cloud.githubusercontent.com/assets/826458/18736114/126a0588-80d8-11e6-86f0-771c41e9b89a.png)

**Comment by ducdhm** [comment]
Done!

**Comment by bradmac** [comment]
Also, queryTableComponent too please

**Comment by hoanglinhlan** [comment]
passed
