### ISSUE TITLE
Lead Importer: Add Profile First name, Surname, Phone and job title

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#2410]

**Comment by hoanglinhlan** [comment]
1: list item import has not phone 
![image](https://cloud.githubusercontent.com/assets/20508726/20172035/003dcf5c-a766-11e6-855a-1ee231867cc4.png)

2: set value wrong, I chose "Lead profile job title" but after imported the value set to phone 

3: import sucessful but system hasn't any information 
![image](https://cloud.githubusercontent.com/assets/20508726/20172177/8b03d654-a766-11e6-9836-8590b2c82ca3.png)

**Comment by hoanglinhlan** [comment]
4: import successful and I can find the new lead in Leads page 
http://version1.leadman.kademi.us/leads/?query=&leadType=active
but on leads in admin, I cant see it 
http://lan-testing.admin.kademi.us/funnels/emailpurchase/#lead-tab

**Comment by tuzzmaniandevil** [comment]
1: Sorted
2: Sorted

@ducdhm please check 3 and 4

**Comment by hoanglinhlan** [comment]
passed
