### ISSUE TITLE
Page setting panel for contentEditor

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#2412]
After discuss with @bradmac, so there is conclusion:
- A button for open page setting panel on modal
- In modal, can edit page title, page properties...

**Comment by bradmac** [comment]
Well 2 things:
- yes, users should have the ability to do this
- but no, whatever it is you're trying to achieve should be achieved through the style and component pallette.

Lets chat later

**Comment by bradmac** [comment]
Please go ahead and build the UI, then assign back to me to implement server side.

Should be basically the same as the current page property editor, just POST a bunch of inputs to the page being edited.

**Comment by ducdhm** [comment]
@bradmac Front-end stuff is done. Need implementation from server side

**Comment by bradmac** [comment]
@ducdhm how about just POSTing to the resource? ie just post to the filename

Note however, that this should only be enabled for editing web pages. Not for blog articles, calendar events, etc.

**Comment by ducdhm** [comment]
@bradmac Ok. Dont worry about blog article or calendar events, they're using inline/iframe mode contentEditor for now :)

**Comment by ducdhm** [comment]
Everything is working normally! But just an issue, how can I remove a meta or data/param?

**Comment by bradmac** [comment]
i dont think we can at the moment, but i think thats ok

**Comment by ducdhm** [comment]
Ok. So we can remove it in textEditor atm. So close it.
