### ISSUE TITLE
Make singleValue query component more awesome

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2413]
See templates/apps/reporting/singleValueComponent.html

This component is to display a single number from a query aggregation, such as the number of users, or the highest balance. The metric can be linked to another page, usually a query page

Please make the following updates to the settings panel
- allow selection of the aggregation the same as for the pieChart component
- allow selection of a font-awesome icon using this - https://itsjaviaguilar.com/fontawesome-iconpicker/
- allow selection of the page to link to, by selecting from the list of queries, which should create a path like /queries/my-query .Or, the user should be able to enter a user to link to as free text

**Comment by ducdhm** [comment]
New UI:
![new_ui](https://cloud.githubusercontent.com/assets/1289631/26233705/73f2a252-3c89-11e7-98a7-08c5a02d2311.png)
