### ISSUE TITLE
Cannot send test email when editing email

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2415]
http://kademi.admin.kademi.us/funnels/agency-sales/emailAction-31c1bd#messages-tab

If I click the Send Test email I get the error:

Sorry, we couldnt send the test. Please contact the administator to help find the problem.

If I put in a recipient I get the error:

Sorry, we could not process your request
Sorry, there appears to be a problem with the network or server. Please check your internet connection. If you're connected ok this might be a glitch in the system. - error 

![image](https://cloud.githubusercontent.com/assets/2201340/18779332/f0c20702-81bb-11e6-98f5-b082bd8306aa.png)

**Comment by hoanglinhlan** [comment]
passed
