### ISSUE TITLE
Emails: Choice of editors

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2416]
Update: 
Allow email authors to enter content as html (using edm editor) or text (using plain text editor) or both. HTML and text content should be stored separately.
- If only text is provided the email is sent as text only
- If only html is provided, text should be generated from the html and the email sent with both forms
- If both are provided each will be used, ie do not generate text from html

The editor page should show readonly forms of both (probably using tabs) with an edit button which opens either a new tab or a full screen editor in an overlay

Original:
I need to create an email that looks like it has been sent from my email client.  For this I need the email width to be 100% and not a fixed width in pixels.

Have the option to set width in percent and pixels.

![image](https://cloud.githubusercontent.com/assets/2201340/18779653/407f6fe0-81bd-11e6-9639-904c09b4c876.png)

**Comment by bradmac** [comment]
I think just use it as it is.

**Comment by paddyow** [comment]
@bradmac it's an increasing case that customers are now creating emails that look like they have been sent from an email client like Outlook, therefore the email template needs to have a 100% width.  If we don't put this option in the only way for a customer to manage the content is edit the HTML, and if they then save the email in the new editor it sets the width to be absolute again.

**Comment by bradmac** [comment]
@paddyow i understand that, and we do want to allow this. But this enhancement will take a while so best to use what we have for now.

**Comment by bradmac** [comment]
@ducdhm can you please update the UI to allow editing of both text and html. I'll take care of the backend.

**Comment by ducdhm** [comment]
@bradmac Sure! I'll touch it soon

**Comment by bradmac** [comment]
Next milestone :)

**Comment by anhnt** [comment]
duplicated of https://github.com/Kademi/kademi-dev/issues/3406

**Comment by bradmac** [comment]
Closing as duplicate
