### ISSUE TITLE
Edit line height value in EDM template

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2417]
I want to be able to edit the exact value of the line height property including a negative value.

![image](https://cloud.githubusercontent.com/assets/2201340/18779964/a87c468a-81be-11e6-9b29-dbc1e0c6a53d.png)

**Comment by bradmac** [comment]
@paddyow a negative line-height doesnt make any sense. And i think using a pre-defined list of values is appropriate.
