### ISSUE TITLE
Cannot switch to text editing view

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2418]
http://kademi.admin.kademi.us/funnels/agency-sales/emailAction-31c1bd#messages-tab

![image](https://cloud.githubusercontent.com/assets/2201340/18780207/c0614006-81bf-11e6-8a7a-e5b42e8bf981.png)

Editor view does not finish loading.

![image](https://cloud.githubusercontent.com/assets/2201340/18780220/d0126d2c-81bf-11e6-8a5b-a98af10d5bd1.png)

**Comment by bradmac** [comment]
Looks like a js issue when loading the page.

**Comment by hoanglinhlan** [comment]
switch to text editing view worked
