### ISSUE TITLE
Multiple profiles

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2419]
http://kademi.admin.kademi.us/manageUsers/?q=test2%40kademi.co&g&enabled=true

I have been uploading profiles via the profile tool, then removing them from the group they were uploaded to, then uploading the same profile with the same email again via the profile tool.

This creates multiple instances of profiles, where they do not have any membership.

Is this correct?

![image](https://cloud.githubusercontent.com/assets/2201340/18780473/13453e52-81c1-11e6-91fb-774798bad095.png)

**Comment by paddyow** [comment]
When you remove the last subscription you get the below warning.  i think we updated this so the profile does not need a membership, if so the warning needs to be updated. 

![image](https://cloud.githubusercontent.com/assets/2201340/18782256/dc7e9834-81c8-11e6-9d91-39c4b0d3ddad.png)

**Comment by bradmac** [comment]
@tuzzmaniandevil please ensure that 
- if a profile exists within an account (ie is linked by membership or its homeAdminOrg property), and it is not deleted/disabled, then it will be located and updated from an upload, NOT creating a new profile
- remove the warning message on removing last membershiup

**Comment by tuzzmaniandevil** [comment]
I've adjusted the UserDao to also check admin org. and adjusted the imported to only return enabled profiles.

**Comment by tuzzmaniandevil** [comment]
I've removed the warning from the manage profile page

**Comment by bradmac** [comment]
@tuzzmaniandevil please backport to olhub.com

**Comment by Uafinder** [comment]
- warning message successfully removed
- import via upload tool still creating duplicate profiles, when existed profile has no membership
![image](https://cloud.githubusercontent.com/assets/1945230/19450123/d7941fc4-94b0-11e6-91df-fc5994a52b84.png)

**Comment by tuzzmaniandevil** [comment]
Added a fix

**Comment by hoanglinhlan** [comment]
passed
