### ISSUE TITLE
Cannot see image in email template

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2420]
![image](https://cloud.githubusercontent.com/assets/2201340/18780670/0be04502-81c2-11e6-89e9-7529f61c8537.png)

I pasted my email signature into the header of an email template.  The image appeared in the email template straight away.  After a browser refresh the image disappears but is still in the source code and get's included when the email is sent.  You can see the image has an absolute image path so should appear when editing the email template.

![image](https://cloud.githubusercontent.com/assets/2201340/18780653/eee330ae-81c1-11e6-9a41-bcd184b5bea1.png)

Here is an example http://kademi.admin.kademi.us/funnels/agency-sales/emailAction-26dff7#messages-tab

This is the source http://kademi.admin.kademi.us/repositories/agency-sales/version1/texteditor?fileName=emailAction-26dff7-content.html

**Comment by paddyow** [comment]
Note also the LinkedIn Image is not appearing when editing the template.

<a href="http://au.linkedin.com/in/enscape" style="text-decoration:none;color:#333333"><img alt="View Patrick Hone's profile on LinkedIn" border="0" height="25" src="https://static.licdn.com/scds/common/u/img/webpromo/btn_viewmy_160x25.png" width="160"> </a

**Comment by paddyow** [comment]
I also noticed the image was getting a 1px height and width, still when I removed this and refreshed the editor view, the image still did not appear.

**Comment by bradmac** [comment]
@ducdhm please investigate

**Comment by hoanglinhlan** [comment]
passed
