### ISSUE TITLE
No way to insert image when editing section in EDM editor.

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2421]
I need to insert an image between paragraph copy.  Need option to upload and insert image.

![image](https://cloud.githubusercontent.com/assets/2201340/18781045/84bc08ca-81c3-11e6-85f2-a89887555e65.png)

**Comment by bradmac** [comment]
Hey @ducdhm really need the insert image toolbar button. Please make sure this uses the useHash parameter like the old editor does.

**Comment by ducdhm** [comment]
@bradmac I think we should separate them. In EDM, it's not really is HTML block. It's just text block. If you want to insert photo, we need drag and drop photo component.

**Comment by bradmac** [comment]
@ducdhm as discussed please add the image toolbar button to the ckeditor toolbar. This should function the same as the previous email editor, where images use hash based paths.

but @paddyow please just split the text and use the image component for the time being, or edit the text directly in the text editor.

**Comment by hoanglinhlan** [comment]
Failed 
1: Add two text Component, I cant add image for second text component, Add image popup is blank. 
see Image 
![image](https://cloud.githubusercontent.com/assets/20508726/19334956/e10e8d3a-9129-11e6-8ec5-8886009b8816.png)
2: Image style is not working. I choose "circle image" but image still doesn't has style in the test mail
3: where is the image save? After add and save an image, I cant find it in other image toolbar

**Comment by hoanglinhlan** [comment]
4: How can I choose an exist image in an any repository?

Test done

**Comment by ducdhm** [comment]
1, 2, 3 are fixed!
```
4: How can I choose an exist image in an any repository?
```
EDM is belong to a website so you just can choose image from the repo of website which EDM is in

**Comment by hoanglinhlan** [comment]
Cant remove folders 
https://lan-test.admin.kademi.com.au/groupEmails/40321913/edmeditor?fileName=index.html&useHash=true

**Comment by ducdhm** [comment]
Can't reproduce. I can delete folder normally.
