### ISSUE TITLE
Help page broken or needs to be created

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2422]
http://kademi.admin.kademi.us/funnels/agency-sales/emailAction-31c1bd#messages-tab

![image](https://cloud.githubusercontent.com/assets/2201340/18781133/d8c3147c-81c3-11e6-9460-9cb92f11f8b2.png)

**Comment by bradmac** [comment]
Has not been created yet. @mamun4343 can you please create this page?

**Comment by mamun4343** [comment]
done!
http://docs.kademi.co/ref/screens/theme/apps/funnels/sendEmail.html  check here.

**Comment by bradmac** [comment]
:+1:
