### ISSUE TITLE
Moving the JB canvas

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2423]
Clicking and dragging on the JB blank canvas space should show a hand icon then scroll the canvas on both axis.

![image](https://cloud.githubusercontent.com/assets/2201340/18781655/1181187a-81c6-11e6-9856-832f7debc937.png)

**Comment by ducdhm** [comment]
Already fixed in other issue

**Comment by hoanglinhlan** [comment]
passed

**Comment by ducdhm** [comment]
Already done!
