### ISSUE TITLE
Cannot use breadcrumb on the funnel text edit view.

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2424]
http://kademi.admin.kademi.us/repositories/agency-sales/version1/

When editing a funnel:
![image](https://cloud.githubusercontent.com/assets/2201340/18781795/aa143a54-81c6-11e6-865e-c5e47a32779e.png)

There is no way to go back one level using the breadcrumb trail.  You have to go to the master LHS Menu or click the browser back button.

![image](https://cloud.githubusercontent.com/assets/2201340/18781728/5ac1e4b0-81c6-11e6-8d0a-3eb056df707a.png)

**Comment by bradmac** [comment]
Thats correct, the edit button takes you to the file manager which is not related to funnels
