### ISSUE TITLE
Cannot edit Hex colour under source view

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2425]
When I edit the source view of a content section in an email template, if I try to change the HEX color of the hyperlink manually then save the source code, it will not  update it, it always reverts back to the value set in the RHS properties window.

I think we should be able to update this. Thoughts?

![image](https://cloud.githubusercontent.com/assets/2201340/18783079/2931272e-81cd-11e6-9e86-f13733454d03.png)

**Comment by ducdhm** [comment]
It's fixed in new gen of edmEditor!
