### ISSUE TITLE
Cannot delete JB node connection

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2429]
Certain positions of the connector will not allow you to delete it when clicking on the red cross.

The below example is one such position.  If the connector is moved horizontal it can then be deleted.

![image](https://cloud.githubusercontent.com/assets/2201340/18787085/9f6be516-81e4-11e6-8ff7-b08a1da6063d.png)

**Comment by bradmac** [comment]
Pushing this back to the next milestone because we can live with it for a while

**Comment by hoanglinhlan** [comment]
passed
