### ISSUE TITLE
When nodes won't connect in the JB

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2433]
Nodes can connect but won't always work.  For example a timer goal after an email results goal does not seem to do anything.

Maybe when a user tries to connect two nodes that will not work we don't allow this and highlight the connecting node in red.

![image](https://cloud.githubusercontent.com/assets/2201340/18825410/9348640c-840b-11e6-98da-79c85767fec5.png)

**Comment by bradmac** [comment]
A timer goal will work after an email result goal. If you think it doesnt please  give an example
