### ISSUE TITLE
Issue with failed email in JB

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2435]
So I uploaded a profile into this group http://kademi.admin.kademi.us/groups/agency-campaign-1/members/

Started profile on this journey http://kademi.admin.kademi.us/funnels/agency-sales/#journeyBuilder-tab

I purposely created a false email failed2@kademi.co

First issue:  Task from failed email did not create task in KCRM after it had failed.
![image](https://cloud.githubusercontent.com/assets/2201340/18829250/c94c245e-841e-11e6-915e-1dfde0d948a3.png)

I noticed the email said failed http://kademi.admin.kademi.us/manageUsers/2299685/#emailAppTab-tab

But  also noticed in the timeline it looks like it was delivered, not failed.  Maybe it should be red. http://kademi.admin.kademi.us/manageUsers/2299685/#summary-tab

![image](https://cloud.githubusercontent.com/assets/2201340/18829346/2c3b9f68-841f-11e6-95d8-63c5fe25c0f4.png)

this is the lead with no task http://kcrm.kademi.us/leads/2299691/

**Comment by tuzzmaniandevil** [comment]
An event wasn't being fired if an email failed because of a permanent bounce, This has been corrected

**Comment by hoanglinhlan** [comment]
pass
