### ISSUE TITLE
No Name appearing in contacts

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2436]
http://kcrm.kademi.us/custs/
If a contact only has a First Name, then show the First Name in the contacts list and not 'No Name'.

![image](https://cloud.githubusercontent.com/assets/2201340/18836877/2c58de86-8445-11e6-83c3-808309b719fc.png)

![image](https://cloud.githubusercontent.com/assets/2201340/18836862/1da4e1f0-8445-11e6-9475-9c6250458f0a.png)

**Comment by hoanglinhlan** [comment]
passed
