### ISSUE TITLE
Tag appearance

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2439]
Show the group name not the code.

![image](https://cloud.githubusercontent.com/assets/2201340/18839518/9ef31b7e-844e-11e6-8950-f3035b266c4a.png)

**Comment by bradmac** [comment]
Looks like it should be doing that now
```
$formatter.firstNotNull($group.title, $group.name)
```

**Comment by tuzzmaniandevil** [comment]
@bradmac That was for the tags dropdown, not displaying selected tags. I've added a fix

**Comment by paddyow** [comment]
We want to show the Group Title not the Code .

![image](https://cloud.githubusercontent.com/assets/2201340/18866782/c8d78092-84e4-11e6-857d-1e92bb696c68.png)

**Comment by hoanglinhlan** [comment]
Passed
