### ISSUE TITLE
Tags show under user management

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2440]
http://kademi.admin.kademi.us/manageUsers/?q=&g&enabled=true

It would be good to see Tags and not just Primary Groups as it helps manage tags and add them to selected groups of profiles much easier.  Otherwise you need to change the group type to primary group, then back to tag.

Make Tag color different.

![image](https://cloud.githubusercontent.com/assets/2201340/18842019/0367defc-8457-11e6-97fb-d3099a5529c7.png)

**Comment by bradmac** [comment]
No, it gets much too busy on that screen. Its ok for 2-3 tags with short names, but frequently we have many more tags then that, and often with longer names. 

Just use filtering instead. We might want to allow inverse filtering (ie users NOT in "have met")
