### ISSUE TITLE
Contact importer not working correctly

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2441]
http://kcrm.kademi.us/custs

I imported this file [Test Upload.xlsx](https://github.com/Kademi/kademi-dev/files/493616/Test.Upload.xlsx)

Matched on First Name and Last Name but they were not added to the profile
![image](https://cloud.githubusercontent.com/assets/2201340/18843139/ecbbe1d6-845a-11e6-937f-abee84adf8ac.png)

Importer said 0 new profiles
![image](https://cloud.githubusercontent.com/assets/2201340/18843156/f9737272-845a-11e6-8de5-1670d8f34781.png)

But actually created one after it was imported 
![image](https://cloud.githubusercontent.com/assets/2201340/18843163/ff84c4ea-845a-11e6-88bb-ab86dc049fc4.png)

**Comment by tuzzmaniandevil** [comment]
Session was being flushed before saving the profile.

**Comment by Uafinder** [comment]
Importer still says 0 profiles found.
![image](https://cloud.githubusercontent.com/assets/1945230/19419593/9c3865c0-93e3-11e6-8dd2-431a908a5a0d.png)

**Comment by tuzzmaniandevil** [comment]
The was an incorrect validation error, I've also added a table to show if there are any invalid records

**Comment by hoanglinhlan** [comment]
1: input contact with invalid email but the system dont show it

**Comment by tuzzmaniandevil** [comment]
I've added a validation check.

@ducdhm Please can you change the way it shows the invalid records to be like the manage users importer?

**Comment by hoanglinhlan** [comment]
import with 2 row: first row is valid, second row has invalid email
1: it's showing wrong Data status: New profiles found: 1, existing profiles found: 0, invalid records: 2 ==> invalid record should be 1 
2: at step 5, I cant find the way to download or see invalid record. It's not showing any invalid record

**Comment by hoanglinhlan** [comment]
passed
