### ISSUE TITLE
Lead importer

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2442]
There is nowhere in KCRM to upload a spreadsheet, create a contact and a lead at the same time.

There should be the option to:
- Upload a file of contacts
- Create a contact
- Create a lead and optionally assign a funnel + tags + source
- Optionally create a task for all leads uploaded

At the moment you can only upload a file and create contacts.

**Comment by paddyow** [comment]
Should it not copy what we have in Kademi http://kademi.admin.kademi.us/funnels/agency-sales/#lead-tab

![image](https://cloud.githubusercontent.com/assets/2201340/18844925/c659f75a-8462-11e6-9908-0ce1d9c9ca70.png)

**Comment by bradmac** [comment]
Please create a lead importer wizard in the front end of LeadMan.

**Comment by gonzalon** [comment]
Please test with the latest leadman lib 1.7.0

**Comment by AlaaKhalaf94** [comment]
passed
