### ISSUE TITLE
Adding tags to leads

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2443]
When creating a lead, need an option to add 1 or more tags.

![image](https://cloud.githubusercontent.com/assets/2201340/18844633/63a097aa-8461-11e6-968d-c33f94464043.png)

**Comment by diegoperezn** [comment]
Could you code review please?

**Comment by bradmac** [comment]
@ducdhm can you please review?

**Comment by bradmac** [comment]
![image](https://cloud.githubusercontent.com/assets/826458/26472908/714ff4c8-41fc-11e7-8728-cd63d401420e.png)

**Comment by ducdhm** [comment]
I dont see any button for adding tag.

**Comment by bradmac** [comment]
@mkhoudary this is done on the lead page:
![image](https://user-images.githubusercontent.com/826458/27164479-aea68216-51e1-11e7-863c-da511672a6dc.png)

But we also want to be able to add tags when a lead is created. Can you please add the same thing to the create lead modal?

**Comment by mkhoudary** [comment]
This is done..

**Comment by hoanglinhlan** [comment]
passed
