### ISSUE TITLE
Email Note too big

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2446]
http://kcrm.kademi.us/leads/2335455/

Captured email to customer is taking up too much space in the notes section:
- There seems to be a lot of white space that is getting captured, not sure if this is email client specific
- The email content should be truncated to maybe 1 paragraph with the option to open the email to see more

![image](https://cloud.githubusercontent.com/assets/2201340/18865837/8a46ec2c-84e0-11e6-8515-3d4ebe06c3ee.png)

**Comment by bradmac** [comment]
- We should trim white space when creating any note.
- Notes should be limited in height with a button to expand to see all. Probably use the dotdotdot.js plugin

**Comment by anhnt** [comment]
![image](https://cloud.githubusercontent.com/assets/735555/26616029/c6eb4872-45f5-11e7-97e9-64d427659ddc.png)

**Comment by hoanglinhlan** [comment]
I cant create new note, after I click to "new note" button the page scroll up to top page 
profile login frontEnd: https://lan-test.admin.kademi.com.au/manageUsers/74497161/#summary-tab
http://hattonfake.kademi.com.au/leads/74649436/

**Comment by anhnt** [comment]
fixed by upgrading leadman theme & leadman-lib

**Comment by hoanglinhlan** [comment]
passed
