### ISSUE TITLE
Cant see the new contact on contact page in lead man

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2447]
create a new contact on contact page 

*expect*: contact page display this new contact 
*actual*: must re-index to see the new contact on contact page

**Comment by tuzzmaniandevil** [comment]
Tested locally and on Syd server:
1. Created new contact from `/custs/` page
    - Nickname - Peter
    - First name - Simon
    - Surname - Peter
    - Email - simon@peter.com
2. Refreshed page and contact was there

I did not have to reindex
![screenshot from 2016-09-28 11-59-34](https://cloud.githubusercontent.com/assets/3378330/18895041/10a1d088-8573-11e6-96f4-68cf7439ab13.png)

@hoanglinhlan Please re-test, If you can reproduce the problem please provide steps to do so

**Comment by hoanglinhlan** [comment]
Cant reproduce
