### ISSUE TITLE
Cannot upload file with more than one group

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2448]
http://kademi.admin.kademi.us/manageUsers/upload

[agency test upload.xlsx](https://github.com/Kademi/kademi-dev/files/495269/agency.test.upload.xlsx)

Tried uploading a file with more than one group column, then a single column with comma separated groups.

Anh confirmed this is not supported.  Would be great to allow multiple columns with a field 'Group' to assign the profile to more than one group.  This will allow for easy tagging.

**Comment by bradmac** [comment]
Expected behaviour is that if there are multiple group columns, then profiles will be added to whichever is not blank.

**Comment by bradmac** [comment]
![image](https://cloud.githubusercontent.com/assets/826458/25161828/3a110d00-2512-11e7-9597-0bfe7bcd06a4.png)

[test-user-upload.xlsx](https://github.com/Kademi/kademi-dev/files/931640/test-user-upload.xlsx)

**Comment by bradmac** [comment]
@hoanglinhlan can you please give the users import tool a thorough test?

**Comment by hoanglinhlan** [comment]
passed

**Comment by hoanglinhlan** [comment]
current, I cant import profile with more than one group
https://lan-test.admin.kademi-prod.com/tableUploaders/usersUploader

![image](https://user-images.githubusercontent.com/20508726/27114683-70bd61ba-50ef-11e7-9b05-9ccba4736e13.png)

[users-lanTest-au.xlsx](https://github.com/Kademi/kademi-dev/files/1073466/users-lanTest-au.xlsx)

**Comment by tuzzmaniandevil** [comment]
Added support for a comma separated list. So you can either select multiple Group columns, or have a comma separated list, or both!

**Comment by hoanglinhlan** [comment]
passed
