### ISSUE TITLE
Profile Tool - Updating profiles

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2449]
http://kademi.admin.kademi.us/manageUsers/upload

I uploaded a file with 709 records.  I then uploaded the same file several times to assign the profiles to more than one group.  Each time the results says there are new profiles to be added when there were not.

![image](https://cloud.githubusercontent.com/assets/2201340/18872343/48083966-84fd-11e6-9ed6-81433a80c469.png)

@bradmac should I send Lan the file and get her to try and recreate this issue?

**Comment by bradmac** [comment]
@tuzzmaniandevil can you investigate please?

**Comment by tuzzmaniandevil** [comment]
The importer wasn't handling mixed cased emails correctly.

**Comment by bradmac** [comment]
@tuzzmaniandevil please backport to olhub.com

**Comment by tuzzmaniandevil** [comment]
Backported and running on beta

**Comment by Uafinder** [comment]
I've checked mixed cases email records... looks ok...
