### ISSUE TITLE
Adding profiles to groups

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2450]
http://kademi.admin.kademi.us/manageUsers

When the Add to Group windows appears, allow the selection of more than one group.

![image](https://cloud.githubusercontent.com/assets/2201340/18873791/6d3fb310-8504-11e6-92a3-e2415ec53390.png)

**Comment by anhnt** [comment]
![image](https://cloud.githubusercontent.com/assets/735555/21218003/633acdda-c2e1-11e6-8d80-4cbde18584cc.png)

**Comment by bradmac** [comment]
Nice!

Please change the text message to be "groups"

**Comment by anhnt** [comment]
Done :-)

**Comment by hoanglinhlan** [comment]
passed
