### ISSUE TITLE
Local Less Compiler: Override ReaderFactory to append .less if missing

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#2451]

**Comment by bradmac** [comment]
Also note that it appears that semi-colons are considered invalid in mixin argument lists, but commas are ok

Eg
Netbeans says this is invalid:
.make-bg(@bg; @color: lighten(@@bg, 43%); @link: lighten(@bg, 52%); @muted: lighten(@bg, 26%); @navlinkbg: darken(@bg, 8%)) {

But this is ok:
.make-bg(@bg, @color: lighten(@bg, 43%), @link: lighten(@bg, 52%), @muted: lighten(@g, 26%), @navlinkbg: darken(@bg, 8%)) {

**Comment by tuzzmaniandevil** [comment]
No longer valid as we have changed Less compilers
