### ISSUE TITLE
Improve UI and UX of content editor

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#2455]
Hey guys,
Let's discuss about our content editor and write down the disadvantage of our tool which you got. I need your feedbacks for improving UX for content editor.

@paddyow I need your magic hand for making UI of content editor more awesome

Linked issues:
 * https://github.com/Kademi/kademi-dev/issues/2281

**Comment by bradmac** [comment]
Definitely need categories, as discussed on another keditor issue i think. What i would like to see is
- components have a list of tags
- at top of keditor toolbar the user can select from the list of tags to filter the list. 
- the user also has a search box which will filter by tag, name or component title

**Comment by hoanglinhlan** [comment]
- Are components sorted by order in lists? If yes, what order? By name or by user usage?
- Components will be displayed as they are now (with thumb images) or with names only? (I find it very hard to tell what component based on images). We can let images display when users hover on components'names

**Comment by bradmac** [comment]
@hoanglinhlan 
- components are current displayed in the order they are provided by apps. That means they are grouped by app
- i think components should have some sort of preview image. The problem at the moment is we just have a screenshot of the component, instead we should have a proper icon for each component.

**Comment by ducdhm** [comment]
https://github.com/Kademi/kademi-dev/issues/2281

**Comment by ducdhm** [comment]
> - components have a list of tags
> - at top of keditor toolbar the user can select from the list of tags to filter the list.
> - the user also has a search box which will filter by tag, name or component title
Done!
