### ISSUE TITLE
Reward categories list component for dashboard

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#2456]
Need for Coke

**Comment by ducdhm** [comment]
https://github.com/Kademi/client-emc-cca/issues/2

**Comment by bradmac** [comment]
@ducdhm we already have this in the rewardStoreDashboardComponent component.

We only want one component so please remove either yours or the original.

**Comment by ducdhm** [comment]
@bradmac They have different look n feel. Here is one which I have created 

![rewardstorecategorieslist 1](https://cloud.githubusercontent.com/assets/1289631/18946131/bd16c550-8657-11e6-9c76-a33b96e0a578.png)

**Comment by bradmac** [comment]
ok, cool
