### ISSUE TITLE
EDM Editor: Add unsub link Component

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2457]
Using this http://$page.closest('website').domainName/profile?$page.model.login does not work.

What do I use in the body of the email if there is an unsub in the email template?

**Comment by tuzzmaniandevil** [comment]
Where are you creating this email? Group Email, Automation, Funnel ?

**Comment by bradmac** [comment]
That will be a funnel in Kademi US - http://kademi.admin.kademi.us/funnels/agency-sales/#journeyBuilder-tab

**Comment by tuzzmaniandevil** [comment]
I've added a unsubscribe link component to the editor :-)

**Comment by hoanglinhlan** [comment]
passed
