### ISSUE TITLE
Journey timers do not seem to be working as expected

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2460]
http://kademi.admin.kademi.us/funnels/agency-sales/#journeyBuilder-tab

I have delays in the journey @ 7 days and 24 hours.  I am using an accelerator of 7 which should adjust the emails  @ 7 days to send after 1 day if the value is divided. 

At the moment the emails send concurrently with no delay.

**Comment by bradmac** [comment]
The problem was that the delay value was being converted from blank to zero, and that value of zero was being used instead of the accelerator.

I've made an update to a value of zero is ignored, and we have an issue in the next milestone to improve the UI of this section
