### ISSUE TITLE
<link rel="template" /> is not working

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#2461]
In login page, I added `<link rel="template" href="/theme/blank"/>` but it's still loading layout of `defaultThemeTemplate`

**Comment by ducdhm** [comment]
Need for Coke (https://github.com/Kademi/client-emc-cca/issues/1)

**Comment by tuzzmaniandevil** [comment]
The HTML wasn't being parsed so no template link was being found.
