### ISSUE TITLE
Body class of template is not append when rendering

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#2462]
Example in login page, `<body class="login-page">`, when rendering, the class of body should contains `login-page`

**Comment by ducdhm** [comment]
Need for Coke (https://github.com/Kademi/client-emc-cca/issues/1)

**Comment by bradmac** [comment]
As discussed please combine body classes from page, page template and theme template in the same way as in HtmlTemplateRenderer. Then edit masterTemplate in bootstrap theme to use this.

Ideally have a method on the template which outputs this list, and have the template call that method. But DO NOT lookup templates again, make sure you use the variables already in templating context.

**Comment by ducdhm** [comment]
I checked in my local and it doesnt work

**Comment by ducdhm** [comment]
Works perfectly!
