### ISSUE TITLE
Cannot change image in EDM editor

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2464]
http://experiment.admin.kademi.us/funnels/nurture1/emailAction-25b65d/#messages-tab

![image](https://cloud.githubusercontent.com/assets/2201340/18949200/adcb563a-867d-11e6-8fb5-6f6fac815a82.png)

![image](https://cloud.githubusercontent.com/assets/2201340/18949211/b7eb0fa2-867d-11e6-90fc-34b528f29cd6.png)

After clicking the upload button and selecting a file, nothing happens.

After the upload window closes the RHS panel has white space added.

![image](https://cloud.githubusercontent.com/assets/2201340/18949251/e85a36cc-867d-11e6-9c87-70a072c22e2c.png)

Checked Chrome and FF

**Comment by ducdhm** [comment]
Fixed in other issue
