### ISSUE TITLE
Getting a link URL for an EDM

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2465]
![image](https://cloud.githubusercontent.com/assets/2201340/18949338/4e97b3ce-867e-11e6-9991-2ccccbd0d082.png)

Need a better way to find a link within an account.  Maybe a file browser to find the file i.e. a PDF and insert the link.

**Comment by bradmac** [comment]
@ducdhm i think this is quite important. Lets discuss

**Comment by bradmac** [comment]
as discussed..
- use mselect to browse files from the admin folder tree
- make sure we get a hash from the selected resource, because admin urls arent accessible from EDMs

**Comment by ducdhm** [comment]
New UI:

![newui](https://user-images.githubusercontent.com/1289631/27724057-32cd2f36-5d9a-11e7-888f-05e2778592ec.png)
