### ISSUE TITLE
EDM fonts not rendering correctly in email client

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2467]
H1 Font
![image](https://cloud.githubusercontent.com/assets/2201340/18950571/db426102-8683-11e6-9ed0-9cd5c330f73e.png)

Not showing correctly in sent email
![image](https://cloud.githubusercontent.com/assets/2201340/18950582/e936ec6a-8683-11e6-9679-cf44888ccdbb.png)

**Comment by ducdhm** [comment]
Enable setting font-size and line-height for heading tags from H1 -> H6 in EDM Settings panel

**Comment by ducdhm** [comment]
Headings settings section in EDM Settings panel

![aaaaaaa](https://cloud.githubusercontent.com/assets/1289631/25040057/69725c5a-2131-11e7-9975-f2b60b14f250.png)
