### ISSUE TITLE
content editor : form block or input blocks are not editable.

### ISSUE THREAD

**Issue by mamun4343** [Kademi/kademi-dev#2468]
Text not editable inside form. 

check this
![untitled](https://cloud.githubusercontent.com/assets/3419573/18953689/705d555c-8671-11e6-8746-0881283cdebc.png)

**Comment by bradmac** [comment]
@ducdhm would it be possible for these to be editable? If not just editing through properties would be ok

**Comment by ducdhm** [comment]
Done!
