### ISSUE TITLE
Font styles are not being encoded correctly

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2469]
Email editor:
![image](https://cloud.githubusercontent.com/assets/2201340/18953894/ef75c3c0-8693-11e6-906f-7662a3d810d2.png)

Mailinator renders the font as a sans-serif even though it looks like it's  Arial and should render fine.
![image](https://cloud.githubusercontent.com/assets/2201340/18953916/0203ce38-8694-11e6-891a-fdecb761976b.png)

To fix this I had to highlight the text, then select Arial.  Should the components that are dragged in have a style selected, otherwise the user has to select the copy, then select a font.

**Comment by ducdhm** [comment]
Already fixed in new EDM Editor
