### ISSUE TITLE
Elastic Search - Add Faceted Search

### ISSUE THREAD

**Issue by jofranklinorchard** [Kademi/kademi-dev#247]
Orchard would like to add faceted search to our site. We can work through the categorisation specs with you.

**Comment by bradmac** [comment]
Hey @skwidge ,for next week...
Need to look at:
 - ContentSearchPage
 - ElasticSearchManager

And integrate with aggregations (formerly facets)
 - http://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations.html
 - http://blog.qbox.io/elasticsearch-aggregations

We'll need to figure out what to aggregrate on:
 - the index
 - content type
 - folder?
 - would be good to put it into the devs space by optionally pulling aggregation values from the template and/or content page

**Comment by bradmac** [comment]
Have implemented tags and categories facets, but not yet index or type, which i'm not sure are required

Here is an example of displaying the facets/aggregations and toggling their selection:
```
<div class="col-md-4">
                    <ul class="nav nav-pills nav-stacked">
                        #foreach($bucket in $page.searchResults.buckets)
                        <li class="$formatter.paramSelected('categories', $bucket.key, 'active')">
                            <a href="$page.href?$formatter.toggleParamVal( 'categories', $bucket.key )">
                                <span class="badge pull-right">$bucket.docCount</span>
                                $bucket.text
                            </a>
                            #if( $bucket.buckets )
                                #foreach($sub in $bucket.buckets)
                                    #set( $arg = $bucket.key + "/" + $sub.key )
                            <li class="$formatter.paramSelected('tags', $arg, 'active')">
                                <a href="$page.href?$formatter.toggleParamVal( 'tags', $arg )">
                                    <span class="badge pull-right">$sub.docCount</span>
                                    - $sub.text
                                </a>
                            </li>
                                #end
                            #end
                        </li>
                        #end
                    </ul>
                </div>
```

And full example here - https://github.com/Kademi/kademi-dev/blob/master/src/main/webapp/templates/apps/search/searchPage.html
