### ISSUE TITLE
Date Range Selector in admin dashboard

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#2472]
At the moment, if I select 1 Year, it stores the actual dates in a cookie. so if I log in a day or two later, the date range is now incorrect. Instead a keyword should be stored. i.e. 1YR then dynamically calculate the date range so it's always correct.

e.g. when select 3 days store start date as '-3d' and end date as 'now'. but still pass the actual dates to the fired event

**Comment by bradmac** [comment]
Note that some server side scripts use the values from cookies. So i think the jquery plugin needs to update the cookie values when the page is loaded.

So probably the keyword value should be stored in addition to the date values

**Comment by tuzzmaniandevil** [comment]
:+1:
