### ISSUE TITLE
Customer emails not firing

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2476]
CSV file uploaded here to the upload endpoint http://admin.rspca-sa.olhub.com/integration/?branch=websites/rspca-sa-campaign/version1#endpoints-tab

[test.zip](https://github.com/Kademi/kademi-dev/files/502349/test.zip)

Profiles are added to the group ok http://admin.rspca-sa.olhub.com/groups/kademi-test-2/members/

Email trigger does not fire http://admin.rspca-sa.olhub.com/autoEmails/118632491/

See example profile where no email is fired http://admin.rspca-sa.olhub.com/manageUsers/207606671/

**Comment by bradmac** [comment]
Fixed in https://github.com/Kademi/kademi-dev/issues/2408
