### ISSUE TITLE
photo uploader visual bug

### ISSUE THREAD

**Issue by mamun4343** [Kademi/kademi-dev#2477]
see this 
![untitled](https://cloud.githubusercontent.com/assets/3419573/19012552/3193293a-87db-11e6-92b7-1e00f360c4ce.png)
i dont see ok or cancel button.
i only see those buttons when i open my console.
![untitled2](https://cloud.githubusercontent.com/assets/3419573/19012557/463490a4-87db-11e6-8b82-da47473ffabb.png)

**Comment by bradmac** [comment]
Can you provide a link to the page where you see that?

**Comment by mamun4343** [comment]
use any content editor for first time. 
such as http://version1.brynnkelly.kademi.us/theme/contenteditor?fileName=home.html&miltonUserUrl=/users/mamun&miltonUserUrlHash=e508b24f-fb8d-4040-b55c-a7025a4530eb:O3Ist_-0HcMnp33kc2slns6emak

**Comment by bradmac** [comment]
Just tried in firefox on linux and seems ok. Maybe a chrome specific issue?

**Comment by mamun4343** [comment]
@hoanglinhlan  can you do a cross browser test. I see this in FF.

**Comment by hoanglinhlan** [comment]
Cant reproduce
