### ISSUE TITLE
contactForm component throwing an error

### ISSUE THREAD

**Issue by mamun4343** [Kademi/kademi-dev#2478]
**ReferenceError: initContactUs is not defined**

![untitled](https://cloud.githubusercontent.com/assets/3419573/19015437/1f5e7e5e-8826-11e6-99bc-0cff941f8a29.png)

**Comment by bradmac** [comment]
Hey @mamun4343, I'm interested to find out what caused the error, and how you solved it?

**Comment by mamun4343** [comment]
it was occuring because of not using stock template and js files.
