### ISSUE TITLE
Products: Change URL from id to specific field

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#2484]
This is to create a more SEO friendly URL, e.g. 
`/store/homeware/6-pack-wine-glasses/`
instead of
`/store/homeware/123455/`

Should derive the path from the title when a product get's created. but should also have an editable field on the manage product page. Make sure to adjust any affected app indexers and integration importers.
- add a field to Product, eg webPath
- add a lookup in ProductsFolder.child() to locate based webPath
- change ProductFolder to use it as its name- same for product in ecom and product in reward

**Comment by Uafinder** [comment]
There should be a validation on the already existed web link to avoid merging two products to a single link
![image](https://cloud.githubusercontent.com/assets/1945230/19450712/2e83ac44-94b3-11e6-96aa-1014b9d43b88.png)
![image](https://cloud.githubusercontent.com/assets/1945230/19450728/3d82859e-94b3-11e6-9562-0a114a5c38ae.png)

**Comment by Uafinder** [comment]
Also:
- there should be added a possibility to add this field via CSV import
- if you import a new product via CSV Web Name field also should be generated automatically

**Comment by hoanglinhlan** [comment]
a validation on the already existed web link : passed
@tuzzmaniandevil 

- there should be added a possibility to add this field via CSV import
- if you import a new product via CSV Web Name field also should be generated automatically

I cant see your implement

**Comment by bradmac** [comment]
Note that we do not require this
- if you import a new product via CSV Web Name field also should be generated automatically

However, we the webname field should be in both imported and exported csv. I believe @tuzzmaniandevil added this just after the name/code field

**Comment by tuzzmaniandevil** [comment]
- there should be added a possibility to add this field via CSV import **@hoanglinhlan I have added this to the products CSV export and import. I've just checked it and it's deployed to syd**

**Comment by hoanglinhlan** [comment]
hi @tuzzmaniandevil 
Pls re-check on au and us server with my file 
http://lan-test.admin.kademi.com.au/products/
http://lan-testing.admin.kademi.us/products/
[products2.xlsx](https://github.com/Kademi/kademi-dev/files/591121/products2.xlsx)

and contact me if you still cant re-play

**Comment by tuzzmaniandevil** [comment]
There was a NullPointerException when creating a product. I've sorted this now.

**Comment by tuzzmaniandevil** [comment]
@hoanglinhlan  FYI The upload only supports CSV files, Not xlsx files

**Comment by hoanglinhlan** [comment]
passed
