### ISSUE TITLE
Menu builder, allow menu items to be selected from font awesome

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2485]
To allow for menus like this:
![screenshot-brynnkelly com 2016-10-03 17-19-11](https://cloud.githubusercontent.com/assets/826458/19027500/93e82f1e-898d-11e6-9c20-456d411e5d9f.png)

**Comment by ducdhm** [comment]
New UI:

![newui](https://user-images.githubusercontent.com/1289631/27697084-7d9ae4cc-5d1d-11e7-9fd8-0dbebd15602c.png)

![newui2](https://user-images.githubusercontent.com/1289631/27697092-80bd28a4-5d1d-11e7-9479-7ac5b96af8ba.png)

**Comment by ducdhm** [comment]
Done!
