### ISSUE TITLE
Group Signup Report

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2486]
This group has 28 members http://admin.rspca-sa.olhub.com/groups/RSPCA-SA-RG/members/

The Group Signup report here http://admin.rspca-sa.olhub.com/reporting/esGroupSignups
 Has 730 members in the group.  Does the report show every member who has been added over time regardless if they were deleted or unsubed?

**Comment by bradmac** [comment]
Yes, it shows all memberships created.
