### ISSUE TITLE
Group signup issue

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2487]
I created this profile today as an example http://admin.rspca-sa.olhub.com/manageUsers/208050803/

They were added to this group http://admin.rspca-sa.olhub.com/groups/RSPCA-SA-RG/members/

They do not appear in the Group Signup Report here http://admin.rspca-sa.olhub.com/reporting/esGroupSignups

I have re-index profiles to see if that helped.

**Comment by bradmac** [comment]
I can see it here - http://admin.rspca-sa.olhub.com/reporting/esGroupSignups?startDate=02%2F10%2F2016&finishDate=+04%2F10%2F2016

Check your date filter.
