### ISSUE TITLE
Profile Upload Tool (dupe field names)

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2488]
Upload a test file here http://admin.rspca-sa.kademi-beta.co/manageUsers/upload
[Reupload - test.xlsx](https://github.com/Kademi/kademi-dev/files/505884/Reupload.-.test.xlsx)

Choose default group: RSPCA-SA-RG

The giving amount field shows two:
![image](https://cloud.githubusercontent.com/assets/2201340/19032757/5d53fd9c-89a7-11e6-8da4-81561f90b9b7.png)

The group has only 1 http://admin.rspca-sa.kademi-beta.co/groups/RSPCA-SA-RG/

![image](https://cloud.githubusercontent.com/assets/2201340/19032771/70f59a54-89a7-11e6-8c31-27b6061acbcc.png)

Is it showing the Name and Text Values by mistake?

**Comment by bradmac** [comment]
The list of fields is displayed for all groups, because you can import into multiple groups. So i would guess that other field exists on another group.
