### ISSUE TITLE
Sending an email to more than 1x contact form request

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2489]
We have this journey http://kademi.admin.kademi.us/funnels/online-sales/#journeyBuilder-tab

We load them into this group http://kademi.admin.kademi.us/groups/leads/members/

If a customer tries to submit the form more than once, they will not get anther email notification as they are not added to the group again.

How do we work around this?

**Comment by bradmac** [comment]
The intention was that funnels are configurable whether they allow just one per profile, or whether multiple leads would be allowed per profile.

But this seems to have been lost.

What we should do, is to add an option to the "Begin" node for whether it will trigger multiple times for a profile or not
