### ISSUE TITLE
JB: remove profile

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2491]
This node removes a Kademi profile, but should we not have the option to remove a lead as well?

![image](https://cloud.githubusercontent.com/assets/2201340/19040892/b48ea3c6-89d1-11e6-97f2-669c679e84c9.png)

**Comment by bradmac** [comment]
We have a cancel lead action for that, but it hadnt been added to the list. Now added

**Comment by bradmac** [comment]
![screenshot-localhost 8080 2016-10-04 11-14-48](https://cloud.githubusercontent.com/assets/826458/19056131/d84a692e-8a23-11e6-82b6-1e524e52c31b.png)
