### ISSUE TITLE
[olhub.com] Email history page is not showing correctly

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#2497]
Please have a look here http://admin.waterco.olhub.com/emails/

Scroll down and you will see Subject is email address, not correct subject

Also  this automation email is not showing on general email history page above http://admin.waterco.olhub.com/autoEmails/27942838/#history-tab

Also pagination is not working

**Comment by bradmac** [comment]
Also, the search box is not filtering.

**Comment by tuzzmaniandevil** [comment]
Re-indexing seemed to fix the subject issue. I need to remove the search box and fix pagination

**Comment by tuzzmaniandevil** [comment]
I've updated Beta with a fix
