### ISSUE TITLE
KCRM: Followup tasks are not created

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2498]
http://kcrm.kademi.us/leads/2472522/

Create a new task
Complete it and create a followup task in the dialogue window 
The followup tasks is not created

![image](https://cloud.githubusercontent.com/assets/2201340/19113155/16213fbc-8b54-11e6-8096-6d2d9b8886a5.png)

**Comment by tuzzmaniandevil** [comment]
Is was missing the process to create a follow up task

**Comment by hoanglinhlan** [comment]
confirm follow up task created after old task closed
