### ISSUE TITLE
Add options to control which fields are shown in the profileDetailsComponent

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2499]
No current option to choose which fields a customer can see in a profile vs those that might be used for admin purposes only.

The profileDetailsComponent should allow control of which fields are shown, including standard and custom fields.

http://kademi.admin.kademi.us/groups/leads/

![image](https://cloud.githubusercontent.com/assets/2201340/19117668/7d78fcb6-8b65-11e6-9c13-eebfb14883fc.png)

**Comment by anhnt** [comment]
![image](https://cloud.githubusercontent.com/assets/735555/20047602/6e1ffc32-a4e8-11e6-8b6a-74af30d398e0.png)

**Comment by bradmac** [comment]
:+1:

**Comment by hoanglinhlan** [comment]
local test: 
Cant save exclude fields

**Comment by hoanglinhlan** [comment]
passed
