### ISSUE TITLE
Console log improvements - stage 1

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#250]
Developers need visibility of whats happening on the server so they can effectively develop without shell access. To do this need access to logs. We have this at the moment but its a bit crap. Improvements
 - performance optimise browser rendering: instead of adding to a table just add p tags, possibly with fixed width spans for date etc
 - ensure the list is truncated as appropriate
 - add ability to search, like tail -f | grep xx. Filtering should be done in the browser
 - each log should show the user, with a link to their profile page
 - should be able to filter by user

**Comment by tuzzmaniandevil** [comment]
Done :-)
