### ISSUE TITLE
JB: Formate dates nicely

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2500]
http://kademi.admin.kademi.us/manageUsers/2705694/#funnelsTab-tab

Dates should be formatted using timeago, and be relative to the timezone in the account settings

![image](https://cloud.githubusercontent.com/assets/2201340/19118457/28c77640-8b68-11e6-8f1b-dda29996a93e.png)

**Comment by ducdhm** [comment]
New UI:

![newui](https://user-images.githubusercontent.com/1289631/27631462-bac5d114-5c22-11e7-9207-0a7a0adf4707.png)
