### ISSUE TITLE
JB: Timeout did not fire

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2504]
I set a timeout at 5 mins to see if it worked, the subsequent email did not fire.

http://kademi.admin.kademi.us/funnels/agency-sales/#journeyBuilder-tab

![image](https://cloud.githubusercontent.com/assets/2201340/19156134/985cc0cc-8c2c-11e6-9310-0600398fca28.png)

**Comment by paddyow** [comment]
I also noticed that the due date timer was updating real-time with Sydney local time.  I expected this time to be fixed at the point is was due to fire.

![image](https://cloud.githubusercontent.com/assets/2201340/19156288/12e4f40e-8c2d-11e6-8d7b-427442434cab.png)

**Comment by bradmac** [comment]
The timer goal page was incorrectly showing leads which have no timer date as being due. The lead for "moo4" currently has no timer.

**Comment by bradmac** [comment]
The timer is firing, but there must be an error occuring...

**Comment by bradmac** [comment]
The underlying problem is that minutes was not a supported units in the backend. Thats been fixed.

But @paddyow remember there is no need to use low durations for testing, just setup a tester domain

So i've changed the timer to be 7 days, and there is a tester for mailinator, and that works fine.
