### ISSUE TITLE
Less compiler throws error

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#2510]
website admin: http://mindfulness.admin.kademi.us/websites/e-learning/version1/#panel_details-tab
frontend site: http://version1.e-learning.kademi.us/myLearning

I used to see this issue when i was creating bs336 theme and it affected current bs335 one. The less compiler doesnt know the less root folder  so it could not find all less files to compile. This will happen when some app has custom less file like leaner app and is pushed to $templater object

See this file http://mindfulness.admin.kademi.us/repositories/e-learning/version1/theme/texteditor?fileName=masterTemplate.html, line 36. I have to fix this by adding extra param 
`$templater.pushLess("/theme/less/bootstrap.less", "all", 0)`

**Comment by bradmac** [comment]
@anhnt is this still an issue?
