### ISSUE TITLE
KCRM: Email does not show comments

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2511]
When opening an email it does not show the main body of the email.

![image](https://cloud.githubusercontent.com/assets/2201340/19234520/e4d5945c-8f37-11e6-938d-7de51fd3a2e2.png)

![image](https://cloud.githubusercontent.com/assets/2201340/19234525/f0217ad8-8f37-11e6-8760-efc6471e54fe.png)

Needs to show the message as below
![image](https://cloud.githubusercontent.com/assets/2201340/19234548/0e68fb7e-8f38-11e6-9f69-afa36ea5a147.png)

**Comment by bradmac** [comment]
Thats not an email, its a contact request. 

The message is shown in the "Message" field - http://kademi.admin.kademi.us/manageContacts/2845189
