### ISSUE TITLE
Admin Profile name

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2512]
I feel the profile name that appears in the menu bar of the admin should show their first name.  

If not and there is no nickname, we should show their first name. 

![image](https://cloud.githubusercontent.com/assets/2201340/19236553/bf1667b2-8f43-11e6-8211-0545345dd3f7.png)

**Comment by bradmac** [comment]
Its extremely common for sites to allow users to enter a display name, which is seperate from their actual name. And i think that is appropriate. 

But the template should display whatever is available, in order:
- nickname
- first name
- email
- userid

**Comment by tuzzmaniandevil** [comment]
Done, Also made an improvement to the firstNotNull on formatter.
