### ISSUE TITLE
Cancelling a lead via JB

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2513]
When a lead is cancelled via the JB it does not have the usual yellow bar that says it's cancelled and you can click the button cancel lead again.

When a lead is cancelled through the JB it should show the lead as being cancelled in KCRM and show the reason for being cancelled that is set in a field using the JB.

http://kcrm.kademi.us/leads/2855582/

**Comment by tuzzmaniandevil** [comment]
Changed it to use the funnel manager so will do the same as front-end, including updating the index

**Comment by hoanglinhlan** [comment]
passed
