### ISSUE TITLE
Group Email Page: Logs page needs to require a logged in user

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#2523]
probably use the setForceLogin method in the constructor

**Comment by gonzalon** [comment]
@bradmac Where are this logs? The ones I found couldn't access if you werent logged in.

**Comment by bradmac** [comment]
http://localhost:8080/logging

**Comment by gonzalon** [comment]
I think this is already solved!

- If I open it a Incognito browser Im being redirect to the login

-  if I try to access to the api: http://localhost:8080/logging?since=2017-04-26T00%3A29%3A03.301Z&logLevel=&user=&keyword=&size=500 
Got a prompt asking for username / password.

**Comment by bradmac** [comment]
:+1:
