### ISSUE TITLE
Automation trigger add to group not working

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2531]
We have this trigger http://admin.cpaaustralia.olhub.com/autoEmails/40377944/#action-tab

Uploaded a trigger here http://admin.cpaaustralia.olhub.com/autoEmails/40377944/timerTriggers.html (test@kademi.co)

Trigger fired ok but the profile was not added to the selected group which is configured under the Action tab.

Note this is required for an update to the campaign.

**Comment by bradmac** [comment]
What user?

**Comment by paddyow** [comment]
test@kademi.co was sent the email but not added to the group http://admin.cpaaustralia.olhub.com/groups/year2/members/

I just searched for that user but they do not exist?  Should I reindex profiles?

**Comment by paddyow** [comment]
@bradmac can someone check this as this campaign needs updating.

**Comment by bradmac** [comment]
hey @paddyow please try again with a fresh user

**Comment by paddyow** [comment]
I created a new profile, then uploaded test2@kademi.co as a trigger, it fired but was not added to the group.

This is the trigger http://admin.cpaaustralia.olhub.com/autoEmails/40377944/#action-tab

**Comment by paddyow** [comment]
the account needed reindexing.  The profile test2@kademi.co was created http://admin.cpaaustralia.olhub.com/manageUsers/211491345/

The emails were fired but the profile was not added to the group.

**Comment by bradmac** [comment]
Applied patch to web4, so will be used for delayed triggers
