### ISSUE TITLE
Analytic page: Wrap area should have a button to clear filters

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2537]
after select one source, No way to re-select other source 
Before
![image](https://cloud.githubusercontent.com/assets/20508726/19423712/581484e0-944d-11e6-9783-493c2f1d2b83.png)

After
![image](https://cloud.githubusercontent.com/assets/20508726/19423692/15c0d968-944d-11e6-9949-29a42556b2c6.png)

**Comment by bradmac** [comment]
Should have something like what github does for clearing filters on the issues page

**Comment by anhnt** [comment]
we cant do like github because when filtered, there's no data for all sources to display. So just added a button to clear filters

**Comment by hoanglinhlan** [comment]
hi @anhnt 
I cant see the clear filter button 
http://lantest3.admin.kademi-prod.com/manageUsers/93152/#summary-tab
http://003hattonfake001.kademi-prod.com/analytics/003hattonfake001-funnel001?filters=source%3D003sources

![image](https://user-images.githubusercontent.com/20508726/27895631-39979646-623e-11e7-9cdc-20ff62648335.png)

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/27896088-bda1d93a-6241-11e7-991d-0eb3211a3621.png)
it will look like above

**Comment by hoanglinhlan** [comment]
passed
