### ISSUE TITLE
Blog article page show error rendering component

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2540]
Create website with boostrap theme then set Blogs app is on. Go to the Blog article page in frontEnd 
system display error component

Error rendering component: blogPageCategories
class org.apache.velocity.exception.ParseErrorException - Lexical error, Encountered: "$" (36), after : "." at bootstrap-web.loopbackdns.com:/theme/apps/blogs/components/blogPageCategoriesComponent.html[line 2, column 65]

**Comment by anhnt** [comment]
Could not reproduce. Please check your blogs-lib repo to make sure its using latest source code

**Comment by hoanglinhlan** [comment]
look like ok on us server
