### ISSUE TITLE
Duplicate schedules email were sent

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2542]
http://admin.rspca-sa.olhub.com/manageUsers/209879975/#emailAppTab-tab

On the 17/10/2016 it looks like the same email was sent twice.

This is the schedule http://admin.rspca-sa.olhub.com/scheduledEmails/listen-data/

**Comment by paddyow** [comment]
@bradmac wes has looked into this but cannot find a reason for the dupe.

**Comment by bradmac** [comment]
Probably just a one-off. Will investigate if it happens again.
