### ISSUE TITLE
journeyBuilder: impove to easy find a node

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2545]
1- Begin note should a first node in list
2- Should a text box to search nodes by name

**Comment by bradmac** [comment]
:+1:

**Comment by bradmac** [comment]
@ducdhm can we do something about item 1?

**Comment by ducdhm** [comment]
Done!

![newui](https://user-images.githubusercontent.com/1289631/26912400-35ac9740-4c3e-11e7-9bbe-0f6e203058d0.png)

**Comment by bradmac** [comment]
hey @ducdhm could we have the begin node in a different colour?

**Comment by ducdhm** [comment]
Yes @bradmac, maybe begin and end node have same color. Maybe purple :)

**Comment by bradmac** [comment]
:+1:

**Comment by ducdhm** [comment]
And last thing, add fullscreen button for entering fullscreen mode for node editor

**Comment by ducdhm** [comment]
Done!

![newui2](https://user-images.githubusercontent.com/1289631/26919820-2693f604-4c61-11e7-8fce-85c4f9cc5b50.png)
