### ISSUE TITLE
EDM Editor: custom app component is not rendered when generating edm item

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#2546]
Have a look here http://customerfusion.admin.kademi.com.au/groupEmails/25687498/#messages-tab

There's custom edm component for kfeedback app

**Comment by bradmac** [comment]
Thats because EDM's are rendered using the website specified in the send information, but the KFeedback app is not enabled for that website - http://customerfusion.admin.kademi.com.au/websites/feedbacksite/version1/#panel_apps-tab

Please enable the app and try again

**Comment by anhnt** [comment]
worked 👍
