### ISSUE TITLE
Cancel JB trigger from firing

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2548]
Where a lead replies to an email, there needs to be a way to stop them from getting any subsequent followup emails i..e cancel a trigger for a profile/lead.

**Comment by bradmac** [comment]
We will add
- see timers for a lead
- cancel timer
- reschedule timer

**Comment by bradmac** [comment]
![screenshot-version1 crm1 loopbackdns com 8080-2016-10-31-22-31-08](https://cloud.githubusercontent.com/assets/826458/19849865/55824e74-9fba-11e6-8b29-c1ddff04c82c.png)

**Comment by bradmac** [comment]
Use the current goals to
- play: immediately complete the current goal and progress to the selected next action
- pause: clear the current goal timer, so it will not automatically complete
- reschedule: change the due date/time of the timer
- switch goal: select a different goal

**Comment by hoanglinhlan** [comment]
passed
