### ISSUE TITLE
Unsubscribe not working

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2550]
An agency campaign was sent out using the JB - http://kademi.admin.kademi.us/funnels/online-sales/#journeyBuilder-tab

3 customers seem to have unsubscribed here http://kademi.admin.kademi.us/unsubscribes/

After their unsubscribe all profiles were sent another email.  It seems their profile still exists under manage users after the unsub action was performed.

**Comment by bradmac** [comment]
The unsub check wasnt being applied to emails sent from the JB. Should be ok now.

**Comment by hoanglinhlan** [comment]
passed
