### ISSUE TITLE
JB adding image to email template

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2559]
When adding an image to an email, the dialogue is nested under the main frame of the page making it hard to get to without scrolling.

![image](https://cloud.githubusercontent.com/assets/2201340/19582681/5bc9c996-9782-11e6-8880-048f32cbc206.png)

**Comment by bradmac** [comment]
@ducdhm lets have a chat before you do anything. I noticed that the toolbar is being hidden or moved up, and that is probably causing this problem. And i dont think we should do it that way

**Comment by bradmac** [comment]
What i'm thinking is that maybe we should not display the editor at all, initially. Instead we will have buttons for each type of editor to open it, possibly in a full screen modal rather then a new tab.

**Comment by ducdhm** [comment]
New UI:

![fireshot screen capture 009 - send email funnel action - localhost_8080_funnels_myfunnel_emailaction-962223_ sendinfo-t](https://cloud.githubusercontent.com/assets/1289631/19680063/6632ef1c-9ace-11e6-8f90-bfa40cad587e.png)


![fireshot screen capture 008 - send email funnel action - localhost_8080_funnels_myfunnel_emailaction-962223_ sendinfo-t](https://cloud.githubusercontent.com/assets/1289631/19680049/59e972ee-9ace-11e6-9a9e-36355337a47b.png)

**Comment by ducdhm** [comment]
Latest UI:

Send Information tab:
![send_info_tab](https://cloud.githubusercontent.com/assets/1289631/19681429/91c62298-9ad3-11e6-8772-20abecbb927a.png)

Message tab:
![message_tab](https://cloud.githubusercontent.com/assets/1289631/19681439/97b9e608-9ad3-11e6-9ddb-e361017a1cfb.png)

Edit message modal:
![edit_message_modal](https://cloud.githubusercontent.com/assets/1289631/19681447/9e3402f2-9ad3-11e6-993b-9fc89eaa2402.png)

**Comment by hoanglinhlan** [comment]
passed
