### ISSUE TITLE
upload variants doesn't work

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#256]
When you are uploading a correct csv file it gives no errors, no success messages.
![image](https://cloud.githubusercontent.com/assets/1945230/6884750/8bb53e48-d608-11e4-941e-75e1d108bc1e.png)
Csv file for test:
https://drive.google.com/file/d/0B9V2ZH-h_cR2Q3NjYzdMRTE4VkU/view?usp=sharing

**Comment by bradmac** [comment]
Think this is fixed now
