### ISSUE TITLE
Create dashboard: Cant drag and drop container

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2563]
User login is an admin
Create and new dashboard for administrator group
Cant drag and drop container 
![image](https://cloud.githubusercontent.com/assets/20508726/19591036/391ad2ba-979f-11e6-9347-6029ee28430f.png)

**Comment by bradmac** [comment]
Confirmed when running locally. There is a js error when starting drag.

@ducdhm can you look into this please?

**Comment by hoanglinhlan** [comment]
passed
