### ISSUE TITLE
Journey builder: when edit journey every connection line will start from the top left corner

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#2565]
![image](https://cloud.githubusercontent.com/assets/1945230/19606852/663efe2c-97ce-11e6-8caa-0a4b0c4787bf.png)
I'm staring from connection point, but it starts from corner

**Comment by bradmac** [comment]
I've seen that as well, but seems intermittent.

**Comment by ducdhm** [comment]
@Uafinder Can you show me how to reproduce it?

**Comment by Uafinder** [comment]
Looks like this bug appears only when funnel does not contain any connection lines.
For example:
1. Create a funnel
2. Add some blocks
3. Leave a page
4. Return to funnel edition
5. Bug is here
![image](https://cloud.githubusercontent.com/assets/1945230/24081260/1a2a9dce-0cb9-11e7-952e-834ff9282c4d.png)

**Comment by ducdhm** [comment]
@Uafinder I still can't reproduce it :( Can you give me more details? What does "Leave a page" mean?

**Comment by Uafinder** [comment]
Leave the page means that you go to any other page.
How it looks like
https://drive.google.com/file/d/0B9V2ZH-h_cR2UWwxNXpacW51TlU/view?usp=sharing
How achive it
https://drive.google.com/open?id=0B9V2ZH-h_cR2YnRwanlraUprZ2M

**Comment by ducdhm** [comment]
Thank @Uafinder, it happens only FireFox. I'll fix it soon

**Comment by ducdhm** [comment]
Need to deploy!
