### ISSUE TITLE
Do not allow editing password or email of users viewed outside of their home admin org

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2568]
This is to ensure that administrators of lower level accounts cannot take over admins of higher accounts

**Comment by bradmac** [comment]
@hoanglinhlan please check
- the normal case is that a profile is created within an account, and can be completely edited in that account
- when an admin of the root org joins a lower account, the admin's profile page when viewed from the lower account should not allow editing password or other contact details

**Comment by hoanglinhlan** [comment]
your cases passed 
But currently, with 2 user at the same level. User1 can edit the profile of user2.
I think an user should not be allowed to edit the profiles of other users at the same level with him

**Comment by bradmac** [comment]
Any user with Administrator or UserAdministrator should be permitted to change any user details.

Any user who does not have those roles (ie only has AdminViewer) should see an error if they attempt to edit a user

**Comment by bradmac** [comment]
I've looked, and this seems to be right

**Comment by hoanglinhlan** [comment]
re-check 
it's ok
