### ISSUE TITLE
Journey builder fields to allow decisions based on group membership

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2569]

**Comment by bradmac** [comment]
![screenshot-customerfusion admin loopbackdns com 8080 2016-10-24 16-40-41](https://cloud.githubusercontent.com/assets/826458/19633007/5bee2456-9a09-11e6-89b2-01dbd350bbfa.png)

**Comment by paddyow** [comment]
Add the Decision to the journey stop the first task from being created.


![image](https://cloud.githubusercontent.com/assets/2201340/19634156/34130078-9a04-11e6-99a4-dd0c054d196e.png)

**Comment by paddyow** [comment]
Also adding a decision node anywhere on the journey stops the panel for email and SMS from showing any parameters, it just looks blank.

**Comment by hoanglinhlan** [comment]
passed

**Comment by bradmac** [comment]
Fixed

**Comment by hoanglinhlan** [comment]
passed
