### ISSUE TITLE
Calendar: Show Internal server error (500) when View event via menu

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2573]
Click view event via view menu 
![image](https://cloud.githubusercontent.com/assets/20508726/19640464/fdff63f2-9a06-11e6-92c3-f26987a03a5c.png)
Page display Internal Server Error (500)
![image](https://cloud.githubusercontent.com/assets/20508726/19640483/1e77082e-9a07-11e6-9fc3-4b9a07955508.png)

**Comment by bradmac** [comment]
@hoanglinhlan can you please give me a link to the account where you see that problem?

**Comment by hoanglinhlan** [comment]
this bug appears on the us server: http://lan-testing.admin.kademi.us/Calendars/
but currently, I cant reproduce it
