### ISSUE TITLE
KCRM does not show SMS touch points in the lead timeline 

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2574]
Add SMS touch points to the lead timeline like we do for email.

**Comment by bradmac** [comment]
Hey @paddyow that has previously been implemented, so should be working. Can you please give me an example of where SMS's are not being displayed?

**Comment by paddyow** [comment]
SMS appears here in Kademi http://experiment.admin.kademi.us/manageUsers/3364009/#summary-tab

But does not appear in the KCRM timeline here http://ep-kcrm.kademi.us/leads/3364016/

Login to KCRM with this account http://experiment.admin.kademi.us/manageUsers/3264297/#summary-tab

**Comment by bradmac** [comment]
Problem is the SMS app was turned off for the KCRM website

**Comment by bradmac** [comment]
Fixed now
