### ISSUE TITLE
JB: Not sending email body

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#2575]
I have configured a JB and there's some Send Email tasks but it didnt send email body for those EDMs

http://mercury.admin.kademi.us/funnels/nurture/#journeyBuilder-tab

**Comment by bradmac** [comment]
It looks ok to me.

I submitted the contact form here - http://version1.mercury-cust.kademi.us/contactus

This created this lead - http://mercury.admin.kademi.us/manageUsers/3396390/#funnelsTab-tab

Which sent this email - http://mercury.admin.kademi.us/emails/3396399

As you can see that email does have the body as shown here - http://mercury.admin.kademi.us/funnels/nurture/emailAction-d3112a/#messages-tab
http://mercury.admin.kademi.us/emails/3396399

**Comment by bradmac** [comment]
But i did see a bug sending emails with dynamic components, a nullpointer exception
