### ISSUE TITLE
Add the ability to request additional fields for purchasing an item from reward store

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2576]
For some products there are additional fields which must be collected for them to be purchased. For example, when selecting a debit card from a reward store we must collect
- name to appear on card
- the date of birth

This might possibly be an extension to the RelatedProductApplication which currently allows extra fields to be entered on the manage product screen.

The collected data would be stored in the item href in a similar way as variants is currently stored

**Comment by bradmac** [comment]
To test, first add one or more fields to the product on the ordering options tab. You may also include variants. Eg below we have a field called "height" and a variant called "colour"

![screenshot-localhost 8080 2016-12-01 15-49-32](https://cloud.githubusercontent.com/assets/826458/20780149/e5563d4a-b7dd-11e6-9b62-1bfcf230c604.png)

Then add it to a reward store, and view on the front end. The fields are requested when you click add to cart:

![screenshot-w1 loopbackdns com 8080 2016-12-01 15-51-25](https://cloud.githubusercontent.com/assets/826458/20780187/23e00564-b7de-11e6-9a3e-4d0fbee4eff9.png)

After submitting, verify the order details have been captured in the admin:

![screenshot-localhost 8080 2016-12-01 15-52-55](https://cloud.githubusercontent.com/assets/826458/20780217/54156788-b7de-11e6-800b-53db64130b58.png)

**Comment by hoanglinhlan** [comment]
fields not appear after click add to cart
![image](https://cloud.githubusercontent.com/assets/20508726/20780856/020b6f00-b7b1-11e6-8f91-28ec741d54cc.png)

**Comment by hoanglinhlan** [comment]
just clear cached then it's work
