### ISSUE TITLE
JB: "Contact form goal" node missing text in title 

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2578]
in nodes list, name of Node is "Contact form goal"
After drag and dropt, The name of Node is "Contact form"

![image](https://cloud.githubusercontent.com/assets/20508726/19712952/34f70a8e-9b6c-11e6-9d29-7e4637b7b282.png)

**Comment by bradmac** [comment]
Ignoring for now. We are going to change the preview images completely anyway
