### ISSUE TITLE
Shopping cart components for automation

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#2579]
2 components:
- list of purchased product in tablet format
- Purchased information like name, phone, address, etc...

**Comment by ducdhm** [comment]
UI of 2 components

![aaaaaaaaaa](https://cloud.githubusercontent.com/assets/1289631/19879574/bcd6338a-a026-11e6-8076-2f95f39739ff.png)

**Comment by hoanglinhlan** [comment]
passed
