### ISSUE TITLE
KCRM tasks to have multiple outcomes

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2583]
A task definition should allow multiple outcomes to be defined. Each outcome may have a list of lead fields which are required. These will be displayed on the task complete form

Each outcome will be a different out port on the journey builder node

**Comment by bradmac** [comment]
Note that to preserve compatibility i have left the existing node types unchanged, and added a new node type called taskGoal which creates the task on entry, and then waits for its completion

**Comment by bradmac** [comment]
Example funnel with a taskGoal
```
{
  "name" : null,
  "title" : null,
  "leadsGroup" : null,
  "defaultInitialGoal" : null,
  "sources" : null,
  "stages" : null,
  "nodes" : [ {
    "taskGoal" : {
      "nodeId" : "taskGoal1",
      "title" : "My first task",
      "x" : 0,
      "y" : 0,
      "timeoutMultiples" : null,
      "timeoutUnits" : null,
      "timeoutNode" : null,
      "stageName" : null,
      "cost" : null,
      "probability" : null,
      "source" : null,
      "taskName" : "task01",
      "frequency" : null,
      "periodMultiples" : 0,
      "runHour" : null,
      "assignToOrgRule" : null,
      "assignToGroupRule" : null,
      "titleMvel" : null,
      "descriptionMvel" : null,
      "taskOutcomes" : [ {
        "id" : "converted",
        "nextNodeId" : "sendThankyouEmail",
        "title" : "Customer converted",
        "fields" : [ "creditcard", "expiry" ]
      }, {
        "id" : "notConverted",
        "nextNodeId" : "wait-1-week",
        "title" : "Not converted",
        "fields" : null
      } ],
      "description" : "Complete task My first task",
      "timoutTime" : null,
      "name" : "taskGoal1"
    }
  } ],
  "extraFields" : [ {
    "name" : "creditcard",
    "title" : "Credit card",
    "required" : true,
    "aggregate" : false,
    "value" : null
  }, {
    "name" : "expiry",
    "title" : "Expiry date",
    "required" : true,
    "aggregate" : false,
    "value" : null
  } ],
  "lostReasons" : [ ],
  "customerActivities" : null,
  "closedActions" : null,
  "cancelledActions" : null,
  "funnelTesters" : null
}
```

**Comment by bradmac** [comment]
Hey @ducdhm can you please do the front end? This should be basically the same as the existing createTaskAction and taskCompleteGoal put together, but with the abililty to dynamically add out ports for each outcome.

The outcomes represent different results of the task. The example above shows a task for an agent to call a customer and to try to get their credit card details. In this example there are 2 outcomes
- converted, got credit card information, so we want to transition to a thank you email step
- not converted, the customer declined so we want to transition to a timer, which will be followed by a nurture program

**Comment by hoanglinhlan** [comment]
passed
