### ISSUE TITLE
Import and remove user does not work correctly 

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2589]
1: Import hundreds or thousands of user, I always must re-index to get the correct number of profiles.
2: Remove hundreds of user but on manage user page, total number of enable profile would reduce by only 100 proflies.

**Comment by bradmac** [comment]
@hoanglinhlan can you please provide a specific example of the project?

Really, we need to see after an action like an import or a delete, records which either do not show when they should, or they continue to be displayed when they should not.

**Comment by hoanglinhlan** [comment]
Data test
[User.xlsx](https://github.com/Kademi/kademi-dev/files/558068/User.xlsx)

1: import this file ( have 1498 valid profile)
Expect: after import succesful, on search index page, numbs of profile increase 1498. 
Actual: numbs of profile not change, must re-indext to get the correct number 

2: After imported, remove all profile
Expect: all profile removed and numbs of profile updated
Actual: removed only 100 profile and numbs of profile not change

**Comment by tuzzmaniandevil** [comment]
The indexer was updated to push deferred updates for every 100 records, The issue was the method that pushed the updates checks if the transaction has been committed which of course it hasn't been at this point, I've added a force parameter to the method which sorts this outs

**Comment by hoanglinhlan** [comment]
passed
