### ISSUE TITLE
Edit webpages: Changing webpage title will remove file extension and throws error

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#2591]
![image](https://cloud.githubusercontent.com/assets/735555/19844027/afb80bf0-9f5a-11e6-934e-17fe67a73658.png)

I have **index.html** and after changing title and click save, that file now has no extension

**Comment by anhnt** [comment]
also fixed the case user not selected default folder page and entered file without extension
![image](https://cloud.githubusercontent.com/assets/735555/19884722/a8bba174-a04d-11e6-871d-d27348806649.png)

**Comment by anhnt** [comment]
**updated**: Now it will automatically appended `.html` if new filename doesnt end with that.

**Comment by hoanglinhlan** [comment]
passed
