### ISSUE TITLE
Profile upload tool:  Matching on email vs phone

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2598]
[Customers.xlsx](https://github.com/Kademi/kademi-dev/files/570272/Customers.xlsx)

I wanted to upload 2x profiles with different emails but the same mobile, but the tool only inserted one profile because the mobiles matched.

Scenario: If you have a couple who share different email addresses, but the same phone number, (which could be a landline)  it will not create the two profiles.  Currently any upload must have unique emails and phones.

1) We allow unique emails but shared phones 
2) We show which records were not added in the error report

**Comment by bradmac** [comment]
Please add an option to the importer for whether to match on phone number

**Comment by diegoperezn** [comment]
@gonzalon Could you review it please?

**Comment by gonzalon** [comment]
Great 👍

**Comment by hoanglinhlan** [comment]
passed
