### ISSUE TITLE
Remove limit on scheduled email recipients

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#260]
We want to have a limit on the maximum number of users who can receive an auto-triggered email to prevent accidental abuse of the autotriggering system. People often add groups to auto-emails without realising that all emails will go to all recipients.

However, currently this limit applies to scheduled emails as well as auto-emails. This is wrong, because scheduled emails can (sometimes) need to be sent to large groups.

So please change the way the limits are applied so that auto triggered emails are still limited to small groups of recipients (eg < 10) while scheduled emails are able to go to unlimited groups

**Comment by tuzzmaniandevil** [comment]
This has now been resolved
