### ISSUE TITLE
Checkout page: Order Summary display point incorrect

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2600]
http://lan-test.admin.kademi.com.au/shopping-carts/
Login acc: tuoi-au@kademi.co
1.> Add to cart some product with variant 
example: http://version1.bootstrap.kademi.com.au/epp-bucket/Gifts/26786687/
then select iPhone6Plus gold - 16Gb (220 point)
2.> go to checkout page, In order summary, I see only 120 point (product'point) 
Expect: 220 point

**Comment by bradmac** [comment]
hey @hoanglinhlan that user doesnt seem to have access to the bootstrap site. Can you please confirm which user account to test with?

**Comment by ducdhm** [comment]
Fixed. Please test on local

**Comment by hoanglinhlan** [comment]
local test
passed
