### ISSUE TITLE
Video Component: issues

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2605]
sever AU 
**1:** On chrome: Cant select button upload video
**2**: display strange characters
![image](https://cloud.githubusercontent.com/assets/20508726/20045381/3292628c-a4d3-11e6-8d18-612c8044259d.png)
**3**: uncheck show control but controls always showed 
**4**: cant change ratio to 16:9
**5**: border setting dont show in Chrome  ( Firefox display ok) 
![image](https://cloud.githubusercontent.com/assets/20508726/20045435/a02096f2-a4d3-11e6-899c-5bedf93aa228.png)
**6**: and Test border setting on Firefox I cant change setting ( I click to disable border then save then reload page, enable border always checked

**Comment by ducdhm** [comment]
No 2 is fixed so can test on local

No 1, 3, 4, 5, 6 are working normally

**Comment by hoanglinhlan** [comment]
1,2,3, 4,5,6 ok
