### ISSUE TITLE
Improve UX of App list

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#2609]
* Searchable app by name or description
 * Split up into 2 lists: native apps and custom apps
 * Sort by name

**Comment by ducdhm** [comment]
@bradmac what do you think about it?

**Comment by bradmac** [comment]
We want to have a model similar to Android etc. All apps should be installed from the marketplace, including native apps. Our users dont really care whether an app is native or not.

The marketplace is already searchable. We dont need the list of installed apps to be searchable or sortable

**Comment by ducdhm** [comment]
Already applied search feature for apps list
