### ISSUE TITLE
Funnel Properties: Saved details, but when page is reloaded the changes are not present

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2618]
http://lan-testing.admin.kademi.us/funnels/funnel/#properties-tab

**Comment by bradmac** [comment]
I saved that ok. Just had to enter the required fields

**Comment by hoanglinhlan** [comment]
http://lan-testing.admin.kademi.us/funnels/funnel/#properties-tab
Pls recheck on that funnel

**Comment by bradmac** [comment]
This problem occurs when the funnel definition is invalid. This might be because the funnel definition is using an old form of the decision node.

Please re-test with a completely new funnel, and recreate the decision node with the builder

**Comment by hoanglinhlan** [comment]
save and keep data successfully
