### ISSUE TITLE
Event attendees CSV needs organisation column

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#262]
Maggie from ACFE has asked to have the attendees csv include their organisation:

http://admin.acfenz.olhub.com/Calendars/auckland/attendees-cfe-welcomes-jill-collins-from-ird-to-talk-about-business-transformation

- Allow adding custom fields to attendee lists, defined at the calendar level

**Comment by bradmac** [comment]
The user's org is being output correctly. However the ACFE site does not use organisations to manage memberships. If someone registers as being in Deloitte in Auckland their organisation is being set to Auckland Branch and Deloitte is just a custom field.

I think it would be a good exercise to see how we can include organisation creation as part of the member application process.

**Comment by bradmac** [comment]
Please add the ability to create an organisation as part of registration. In this case registration is for administrator approval, so the member's org should only be created when accepted by the admin. We might want to make the organisation creation to be done by the admin as part of acceptance to avoid users creating duplicate orgs

**Comment by skwidge** [comment]
A solution has been implemented for this although it is not perfect yet.
Extra fields can be added to groups in the group administration screen. There is now a checkbox which indicates that the extra field is an organisation select field.

When a new uses is accepted in the dashboard, the administrator has the option of accepting the entered organisation, or selecting an existing one. The user must be expanded for this to be visible.

Currently only the administration organisation and its immediate children are displayed.

For better usability the user application form might prompt a new user with the names of existing organisations. This has no been implemented anywhere yet, but a front end developer familiar with the web services could do this now.

If the organisation does not exist, it will be created. New organisations are indicated in the select by the suffix, " (new)".

**Comment by skwidge** [comment]
Hi Vlad, could you test this

**Comment by skwidge** [comment]
Brad tells me this is not so much test, as implement fo ACFENZ. the extra field 'employerOrg' for the member group needs to be set as an organisation select. This is just a matter or selecting the checkbox.
Prompting the user with existing company names requires an ajax call to a web service  - will look this up and add a comment.
This code is currently committed bu not released, BTW. he next release will have it.

**Comment by bradmac** [comment]
@skwidge - this isnt required - "Prompting the user with existing company names requires an ajax call to a web service - will look this up and add a comment."

If we did that anyone could see who is a member of ACFE, which they dont want. So it should just be a plain text field as it is now.

**Comment by skwidge** [comment]
Fixed up the organisation search

**Comment by skwidge** [comment]
This was finished some time ago
