### ISSUE TITLE
Auction field causes error

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2624]
http://reward-demo.admin.olhub.com/auctions/galaxy-s6-edge-1/

When adding too much copy to the description field you get the error:

Errors
Sorry, we could not process your request
Sorry, there appears to be a problem with the network or server. Please check your internet connection. If you're connected ok this might be a glitch in the system. - error

![image](https://cloud.githubusercontent.com/assets/2201340/20122728/0b8d54ac-a66e-11e6-908c-ec83cb3be8ae.png)

**Comment by bradmac** [comment]
Should add explicit validateion on field length

**Comment by gonzalon** [comment]
Pushed to master

**Comment by hoanglinhlan** [comment]
passed on au server
