### ISSUE TITLE
minor visual bug with lead creation log message

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#2627]
![image](https://cloud.githubusercontent.com/assets/1945230/20149627/cb1fd2d0-a6ba-11e6-9e9b-9237d01a795e.png)

**Comment by bradmac** [comment]
Do you mean the ID?

**Comment by ducdhm** [comment]
I think it's double dotted bottom border in date time of log message

**Comment by Uafinder** [comment]
Sorry for misunderstanding...
It's about "less than a minute ago" timestamp which moves "Lead created" text to the next string...
As well as double dotted selecting for timestamp...

**Comment by ducdhm** [comment]
Fixed!
