### ISSUE TITLE
Google maps app

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2628]
- Create a new lib app, which will be a dependency for apps with google maps integration
- This should have a setting to enter the google maps key, and it should have text explaining how to get one
- The app should include google maps js file(s) as dependencies
- Update apps which use google maps to have this as a dependency (eg leadman, store locator)

**Comment by ducdhm** [comment]
@bradmac How can I append google API key in link to google map js?

**Comment by bradmac** [comment]
@ducdhm not sure of the best approach. Please grab me when youre online to discuss.

**Comment by ducdhm** [comment]
* Google map app is done
 * Added dependencies for Org Locator app

**Comment by ducdhm** [comment]
Need to app dependencies for Leadman app but need to do it first https://github.com/Kademi/kademi-dev/issues/3549

**Comment by anhnt** [comment]
👍

**Comment by anhnt** [comment]
done for leadman

**Comment by anhnt** [comment]
https://github.com/Kademi/kademi-dev/issues/3553

**Comment by anhnt** [comment]
Org Locator app works great
