### ISSUE TITLE
Menu component: On Default template should be chose show user menu  

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2629]
On menu component of default theme template,  show user menu  should have default value  selected

**Comment by bradmac** [comment]
Can you provide a screenshot please?

**Comment by hoanglinhlan** [comment]
I think we should set default selected for that checkbox. Because, almost client must user menu on their website.
![image](https://cloud.githubusercontent.com/assets/20508726/20161876/ec1565cc-a723-11e6-90ea-7a78adda0a5f.png)

**Comment by bradmac** [comment]
Actually, I think it should default to off. You only want a user login for sites with registration, and that is less common then plain websites such as landing pages and microsites.
