### ISSUE TITLE
Ecommerce: checkout page display unnecessary icon 

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2630]
![image](https://cloud.githubusercontent.com/assets/20508726/20165248/1a28801a-a73e-11e6-82ff-d1ce28646efb.png)

**Comment by anhnt** [comment]
enable one of payment apps to make it work

**Comment by ducdhm** [comment]
Currently, you enabled only manual payment app so it's displaying only Manual Payment method

**Comment by hoanglinhlan** [comment]
I think we should only display check icon if User enable  at least one online payment.

**Comment by ducdhm** [comment]
Nope. Manual payment also a payment method

**Comment by hoanglinhlan** [comment]
As discuss 
Only display a blue tick on a card type when a user selects the card type'
So no blue tick will ever be displayed when there are no card types. And we shouldnt default a card type, it should be the user who selects one

**Comment by hoanglinhlan** [comment]
passed
