### ISSUE TITLE
Create new lead: list suggest user display with  undefined data

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2631]
![image](https://cloud.githubusercontent.com/assets/20508726/20170345/6f802b10-a75e-11e6-9257-2f3eb8820594.png)
Create new lead: list suggest user display with  undefined data and display null if phone is blank
http://version1.leadman.kademi.us/leads/
profile: http://lan-testing.admin.kademi.us/manageUsers/3274917/#general-tab

**Comment by diegoperezn** [comment]
@gonzalon Could you take it a look?

**Comment by gonzalon** [comment]
👍

**Comment by hoanglinhlan** [comment]
passed in  itsinsuredqa-crm project but it's doesn't show anything in my test site 
https://lan-test.admin.kademi.com.au/manageUsers/74497161
http://hattonfake.kademi.com.au/dashboard
![image](https://user-images.githubusercontent.com/20508726/26960105-eb6bd198-4cfe-11e7-8b4e-5a478bf879ff.png)

**Comment by gonzalon** [comment]
Seems ok to me:

![image](https://user-images.githubusercontent.com/2773216/33973548-5f26dbaa-e0e8-11e7-9975-cc28767b46d6.png)

**Comment by Uafinder** [comment]
It's ok at the moment...
Fixed earlier...
