### ISSUE TITLE
Upgrade modal plugin of CKEditor

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#2636]
Make this plugin compatible with Bootstrap theme

**Comment by ducdhm** [comment]
New UI:

![wwwwwwwww](https://cloud.githubusercontent.com/assets/1289631/20207227/64f0bbb4-a818-11e6-9125-1f62afcbecb7.png)

**Comment by hoanglinhlan** [comment]
little issue:
Enter the Ok text is "Ok 123" then save. Howerver on frontEnd, it always display "OK".
I think maybe we should remove Ok text on in setting and fix it always display "Ok"

**Comment by ducdhm** [comment]
Fixed! We still need this option because not all of people want it "OK" text. Maybe "Close" or etc..

**Comment by hoanglinhlan** [comment]
passed
