### ISSUE TITLE
Create svg map component with hightlight

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#2637]
Like this for ward6
![image](https://cloud.githubusercontent.com/assets/735555/20204100/486b50d0-a7ff-11e6-8ab6-5bc0a9d371f4.png)

**Comment by anhnt** [comment]
![image](https://cloud.githubusercontent.com/assets/735555/20375821/268e514c-acb4-11e6-8ab8-8db20e93bd8a.png)

**Comment by ducdhm** [comment]
:100:

**Comment by hoanglinhlan** [comment]
local test 
passed
