### ISSUE TITLE
Nullpointer when add profile to administrator group

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2641]
http://lan-testing.admin.kademi.us/manageUsers/3492311/#summary-tab
Click assign this porfile to administrator group then system display error Nullpointer
login account: 
http://lan-testing.admin.kademi.us/manageUsers/2659134/#summary-tab
![image](https://cloud.githubusercontent.com/assets/20508726/20258830/22467dee-aa84-11e6-8824-efed51a5d94c.png)

**Comment by hoanglinhlan** [comment]
It because in send mail node of funnel, I dont choose website 
==> I think we must validate require field on node's setting

**Comment by bradmac** [comment]
Just checked and seems ok now. I think you're right, the real issue is the validation on the email node

**Comment by hoanglinhlan** [comment]
I think we should check it on ticket about validation
