### ISSUE TITLE
journeyBuilder: should validate require field on node's setting 

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2642]
Currently, we dont have validation for require field on node's setting. 
when user dont choose it, funnel works incorrect ( also, feature related still work incorrect).
refer #2641

**Comment by ducdhm** [comment]
@hoanglinhlan There are a lot of nodes atm. And each node are made by different devs so I think when you get error on some nodes, please create issue for fix them.
