### ISSUE TITLE
Featured products

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2644]

**Comment by ducdhm** [comment]
👍 💯

**Comment by bradmac** [comment]
[0.79217.jpg.zip](https://github.com/Kademi/kademi-dev/files/591113/0.79217.jpg.zip)

**Comment by bradmac** [comment]
Actually, i think the best approach is to just have a category called "Featured" and add featured products to it. This could be used with component options which allow filtering by category
