### ISSUE TITLE
Product Sku: add ability to upload images

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#2649]
Currently there is very slow code so needs to be optimized. Look in manageSkus.js

a parameter "skuId" needs to be passed with the image upload and crop.

This is related to #1303

**Comment by bradmac** [comment]
** Please test with a full size data sample **

Best thing to do is to export products from the EMC product library, and import that to test with.

Updates need to be fast, ie no significant delay.

**Comment by bradmac** [comment]
Also, do not reload the entire page after updating a cell, that will definitely be too slow. Either update the state client side, or just reload the row.

**Comment by diegoperezn** [comment]
Look ok for my

**Comment by hoanglinhlan** [comment]
it's still very slowly 
after page loaded, then I click to image upload button, I need wait about 30s to see the popup to upload image.

**Comment by tuzzmaniandevil** [comment]
@hoanglinhlan I can't reproduce, Works find for me. Can you please re-test? If you can reproduce please provide the steps

**Comment by hoanglinhlan** [comment]
please disable upload image button in the case product doesn't has SKU

**Comment by hoanglinhlan** [comment]
passed
