### ISSUE TITLE
Points table pagination is not working on points bucket page

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2650]
Eg - http://cca.admin.kademi.com.au/points-buckets/sec-bucket/?startPos=10&pageSize=10#points-tab

- Clicking forward loses the current tab. It should do a reload on the table
- Also, the pagination control should either be outside the table, or use colspan. Currently its blowing out the width of the points col

**Comment by bradmac** [comment]
Updated on both the points bucket screen and the review points page. Please test both.

**Comment by hoanglinhlan** [comment]
checked on both of cca site and local. 
**On cca site - point bucket:** 
- select  a point bucket then choose point tab, paging has 10 page but I cant see any record
- Clicking forward I see 10 record but paging not highlight any page number
- On CSV file that I exported, I saw 509 record, so I think we should have more than 10 page ( maybe both of forward and back page, then we could display page number from 11 - 20 )

continue ...

**Comment by hoanglinhlan** [comment]
**On cca site - review point:** 
- I cant see any record but after I award point, all record shows then I refesh all record disapear

**On local - point bucket:** 
- If I have < 10 record, I cant see any record on this page. Record appeared and disappeared shortly thereafter

**Comment by bradmac** [comment]
Mostly working, just needs some js fixups for when selecting other criteria.

@anhnt can you please finish this off?

**Comment by anhnt** [comment]
@hoanglinhlan can you test it today?

**Comment by hoanglinhlan** [comment]
local check failed 
1: point tab of point bucket still not display any record 
continue

**Comment by anhnt** [comment]
1: point tab of point bucket still not display any record -> Please choose date range. I just fixed the issue that doesnt update pagination when user enters query

**Comment by hoanglinhlan** [comment]
passed
