### ISSUE TITLE
Code block component

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#2652]

**Comment by ducdhm** [comment]
Please test on your local or AU cluster

**Comment by hoanglinhlan** [comment]
Au server
after fill code source and save, button chage source display incorrect
![image](https://cloud.githubusercontent.com/assets/20508726/20478203/abd1eaa8-b00b-11e6-8190-0b3cef070468.png)

**Comment by ducdhm** [comment]
It's correct behavior. Code Block component is special component for advance users who know about HTML and can create content of component via HTML code

**Comment by hoanglinhlan** [comment]
re-checked
awsome component :D
