### ISSUE TITLE
KCRM stopping a timer

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2654]
http://kcrm.kademi.us/leads/3900971/

This profile is saying waiting for email 3, but they have received email 3.  See here http://kademi.admin.kademi.us/manageUsers/2352930/#emailAppTab-tab

![image](https://cloud.githubusercontent.com/assets/2201340/20467388/dbaa9d50-afda-11e6-9361-41a859f68cfd.png)

**Comment by bradmac** [comment]
That is the current goal, because there is nothing after it in the funnel, ie it has nowhere to go
