### ISSUE TITLE
Line graph not working in Dashboard editor

### ISSUE THREAD

**Issue by jeremy-leys** [Kademi/kademi-dev#2655]
Hi,

The Kademi, the line graph is not working in the Dashboard editor see screen shot below:
https://www.dropbox.com/s/q64pnw1uftiogow/chart-type.PNG

When toggling between line and bar graph, only bar graph seems to work. Tried dragging in a new graph widget and updating and saving a previously setup graph.

**Comment by tuzzmaniandevil** [comment]
Sorted, Was because the theme was using an outdated version of the bootstrap theme
