### ISSUE TITLE
Menu component, Can't upload image

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#2659]
When using the menu component, Clicking the upload logo button does nothing.

http://version1.carters-reporting.kademi.com.au/theme/contenteditor?fileName=defaultThemeTemplate.html

**Comment by ducdhm** [comment]
@tuzzmaniandevil You're creating new theme but you dont use the latest code of contentEditor. That's why you got this error. I have updated template for contentEditor. So it works normally

**Comment by tuzzmaniandevil** [comment]
Yup this is fixed
