### ISSUE TITLE
Reward extra fields

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#266]
Cynthia @ Ward6 has asked for the ability to add extra fields to rewards
- subtitle
- image
- references
- winners

1. Add support for multiple images in the same way as for blog articles and products.
2. Add a subtitle field, plain text
3. Add a HTML field for the winners announcement message
4. Add NVSet which can contain arbitrary additional fields

**Comment by skwidge** [comment]
New fields added. changes committed and pushed up to master.

**Comment by bradmac** [comment]
I cant find these updates anywhere??
