### ISSUE TITLE
Review point page: nothing happen when I click Export to CSV file 

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2662]
Eg: http://cca.admin.kademi.com.au/rewards/points/?startDate=11%2F10%2F2016&finishDate=17%2F10%2F2016&dataQuery=&searchGroup=&searchReward=
1: Click Export to CSV but nothing happen 
2: then refresh this page, the save as popup display

**Comment by bradmac** [comment]
Fixed

**Comment by hoanglinhlan** [comment]
local test
passed
