### ISSUE TITLE
Remove headings from registration form component, and allow control of name fields

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2663]
By having headings in the component, it makes it impossible for the user to control them.

Instead, users should be able to insert headings using normal editor controls.

So please just remove headings from the register form component.

Also, make an option to control if name fields are displayed

BUT please ensure this is done by overriding the component in a lib. Do not change the statically deployed component because that will affect existing sites.

**Comment by anhnt** [comment]
Looks like Brad has done this

**Comment by bradmac** [comment]
cool!

**Comment by hoanglinhlan** [comment]
passed
