### ISSUE TITLE
EDM Editor: Uploading image fails if an image is selected

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#2666]
If I select an image from the left hand column then I try upload a new image, It fails

![screenshot from 2016-11-28 10-12-38](https://cloud.githubusercontent.com/assets/3378330/20651895/561d186a-b553-11e6-8e08-d130ef080bd4.png)

**Comment by ducdhm** [comment]
Already fixed in other issue related to mselect plugin
