### ISSUE TITLE
Scrolling a blog page loses the menu bar

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#267]
When adding extensive content to a blog page in the admin, the child window extends below the bottom of the parent window so the user has to scroll down the parent page losing the menu bar.

![extra_long_resource_item_about_dairy_-_2015-04-01_16 21 14](https://cloud.githubusercontent.com/assets/2201340/6935091/25d9b97a-d88b-11e4-8d99-3a6d53d8481a.png)

**Comment by bradmac** [comment]
I think users can use the fullscreen button on the ckeditor toolbar to solve this problem.

We might also want to think about adding a new tab full screen editor button like what we do for editing elearning and email content
