### ISSUE TITLE
Module completion message is broken in bootstrap theme

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2670]
I created a module with a single quiz page. When successfully completed the quiz, i was prompted to enter my profile details which worked fine.

The module completion message then displayed but it was broken. It appears this has not been updated to work with component templater

![screenshot-version1 w1 loopbackdns com 8080 2016-11-29 10-29-49](https://cloud.githubusercontent.com/assets/826458/20686767/d82d6a8c-b61e-11e6-863f-d3caeb876019.png)

**Comment by anhnt** [comment]
Can you test it today @hoanglinhlan

**Comment by hoanglinhlan** [comment]
passed
