### ISSUE TITLE
Password reset component for EDM editor

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2671]

**Comment by bradmac** [comment]
Hi @anhnt can you please finish this off? Its functional now, but the component editor needs to be done
- appropriate thumbnail image
- please base this on the button component. It looks like there is an ability to extend another component, would be great to extend button. Otherwise just copy it. 
- the link should not be configurable, but the text should be.

**Comment by hoanglinhlan** [comment]
passed
