### ISSUE TITLE
Allow automation triggers to fire files being uploaded to repositories

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2672]

**Comment by bradmac** [comment]
Now supported on automation
![screenshot-localhost 8080 2016-11-30 13-27-33](https://cloud.githubusercontent.com/assets/826458/20734819/dd2ca560-b700-11e6-86ca-f87f967f3fc8.png)

Checked with using the my files app
![screenshot-w1 loopbackdns com 8080 2016-11-30 13-27-51](https://cloud.githubusercontent.com/assets/826458/20734824/e1f9d4be-b700-11e6-94f6-540e380a4e1b.png)

**Comment by bradmac** [comment]
Note that this is needed by Alison at EMC

**Comment by hoanglinhlan** [comment]
passed
