### ISSUE TITLE
Opening a PDF from a resources page in chrome causes the PDF not to render correctly.

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#268]
Loses background images and pages.
Opens fine in FF.

http://version2.zoetis-livestock-reseller.olhub.com/blogs/Resources/startect-detailer/

Might be a Chrome issue:
https://forums.adobe.com/thread/1648828

"Usually a basic PDF is not the issue, but the issue arises with markup. You might consider changing the compatibility setting in your settings file so that PDFs are created with an AA 9 or X compatibility. It may be that the Chrome viewer is not compatible with the newer versions of PDF. The Apple Preview has similar problems, but usually with form fields."

"Changing compatibility settings to Acrobat 5 (PDF 1.4) resolved the issue"

**Comment by bradmac** [comment]
@paddyow can you ask them to try reformatting as in the link above? If still a problem we will look further into it.

**Comment by bradmac** [comment]
Found the problem. Chrome is requesting parts of the file in ranges, but the way files are served through the blogging app (which is different to files served normally from repositories) has not previously implemented range support. 

I've added range support to blog files and works fine now
