### ISSUE TITLE
New client account showing incorrect reporting data

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2685]
http://ward6.admin.kademi.com.au/reporting/UserActivity?startDate=05%2F12%2F2015&finishDate=05%2F12%2F2016&term-orgs=28769712

Active users report shows high numbers yet not in use.

![image](https://cloud.githubusercontent.com/assets/2201340/20869720/c5c9f57e-bacc-11e6-8fa2-993146ad0c31.png)

**Comment by bradmac** [comment]
Seems to be resolved
