### ISSUE TITLE
Update Module Quiz/Survey report

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2694]
http://ward6.admin.kademi.com.au/reporting/ModuleQuizAnswersReport?startDate=05%2F12%2F2016&finishDate=07%2F12%2F2016

Since we added the option to allow multiple answer selection to a quiz question, where there is more than one answer selected for any given question, this data is not getting captured into the report.  

@brad do you think we separate answers by commas where the answer might also have a comma in the sentence, or put each response on a new line?

**Comment by bradmac** [comment]
We really need to keep it on one line. Suggest we seperate in the output using semi-colons.

**Comment by hoanglinhlan** [comment]
it's still doesn't keep answers.

**Comment by tuzzmaniandevil** [comment]
@hoanglinhlan Please can you provide the CSV file you are seeing and the details of how you are testing this please?

**Comment by hoanglinhlan** [comment]
@tuzzmaniandevil 
Sorry Wes
now, it's work on both of my local and au server. I think I forgot clear cached.
