### ISSUE TITLE
SKUs: Error when I set quantity of product to stock on SKU page

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2709]
http://lan-testing.admin.kademi.us/skus/
account: hoanglinhlan@kademi.co
**Step**: 
- Create a product with more than 2 Variant type ( each variant type has more than one variant)
- Create a new inventory 
- Go to SKUs page, set quantity of product to any stock C1S-HKOK or C1S-JP then enter. The system display: " An error occured setting the SKU stock". I try with product that has not variant but it still not working.

Do I miss any setting ?

**Comment by bradmac** [comment]
You should be able to enter anything as a SKU

**Comment by hoanglinhlan** [comment]
#2711

**Comment by tuzzmaniandevil** [comment]
Fixed, The DB had the incorrect constraint.
