### ISSUE TITLE
Product : modal layout display wrong when add more than 2 fields

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2713]
Add more than 2 field for product. 
when I click add to cart, modal layout with fields display wrong
![image](https://cloud.githubusercontent.com/assets/20508726/21128142/208380f2-c12b-11e6-8c75-b8b3ed935c8d.png)

#2714

**Comment by hoanglinhlan** [comment]
http://lan-test.admin.kademi.com.au/manageUsers/41267184/#summary-tab
http://version1.c5s.kademi.com.au/c5s-business/Samsung-Phone/

when I add this product to cart, it's not showing modal to put fileds, just add product to cart

**Comment by ducdhm** [comment]
@hoanglinhlan Can you check at your local first?
