### ISSUE TITLE
CCA's issue: not capturing field after submit order

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2714]
The problem with some profile and for Visa cards (voucher Category)
 ie
http://cca.admin.kademi.com.au/shopping-carts/31308174/#items-tab

**Comment by bradmac** [comment]
Hey @Uafinder we cant reproduce this problem, but there are quite a few clients experiencing it.

Can you investigate please? Note that it seems to affect iOS devices, although we havent been able to reproduce it on them

**Comment by hoanglinhlan** [comment]
@Uafinder There is list browser and device that I checked: Safari, Safari on iPhone5 and iPad Pro, Chrome, FF, Chrome/FF on Android,
