### ISSUE TITLE
Update Quiz for view only enrolements

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2715]
Modify the module page logic so that users with view only enrolements are able to complete quizes and have them marked, ie indicated success or failure.

- The quiz will not be recorded again agaist the user's profile
- Kademi will report the success or failure to the user in the front-end
- The module will not be marked as completed, and no rewards will be issed or certificates awarded

**Comment by bradmac** [comment]
hey @anhnt please update front end code, and back end support is needed just let me know

**Comment by anhnt** [comment]
It looks cool with Paddy requirements so over to you @Uafinder

**Comment by Uafinder** [comment]
When you're has a viewable role for learning, he doesn't see all modules, only the first one. So he can't access a second module directly.
![image](https://user-images.githubusercontent.com/1945230/33881810-a6d8397c-df3e-11e7-87c5-28fefabbc408.png)
![image](https://user-images.githubusercontent.com/1945230/33881817-aa8a210c-df3e-11e7-9aeb-a42eb5eb5204.png)
http://vlad04learn_vladtest04.kademi-ci.co/myLearning
http://vladtest04.admin.kademi-ci.co/websites/
user: userqa02@mailinator.com

**Comment by bradmac** [comment]
The available modules and available courses methods should check for the user's enrolement. If its viewable then it should not apply any pre-requisites, ie all modules and courses should be available.

**Comment by bradmac** [comment]
@anhnt i think this will require a java change. Please let me know if you'd like a hand.

**Comment by anhnt** [comment]
Fixed, please rebuild QA to test

**Comment by Uafinder** [comment]
It looks good for me
