### ISSUE TITLE
Error when save menu component 

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2720]
http://lan-testing.admin.kademi.us/websites/bootstrap/version1/#panel_theme-tab
Create a new website with boostrap theme then edit menu component on defaultThemeTemplate. 
After I saved menu setting, the system display error: `500: <html><body><h1>Internal Server Error (500)</h1></body></html>`
#2718

**Comment by bradmac** [comment]
@ducdhm can you have a look at this please? might need to update libs

**Comment by ducdhm** [comment]
Already fixed: http://lan-testing.admin.kademi.us/websites/bootstrap-test/version1/#panel_theme-tab

**Comment by ducdhm** [comment]
And please make sure: dont name your website special like bootstrap, leadman or something like that.

**Comment by hoanglinhlan** [comment]
passed
