### ISSUE TITLE
Quiz pass mark is not restricting module completion

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2726]
This user has a number of modules which have a single recorded quiz attempt which has failed, for example module 5.2

http://admin.waterco.olhub.com/manageUsers/220943772/#learningAppTab-tab

The quiz in module 5.2 is configured to allow 3 attempts with a pass mark of 100%. So this user should not have been able to complete the module

http://admin.waterco.olhub.com/websites/waterco/201601/programs/HDX15/HDX5/HDX.5.2/#options-tab

Note that this is on olhub, and a backport will be required

**Comment by bradmac** [comment]
Also, it was not marking correctly. When calculating the user's score it was using 
num correct / total number of questions

But what it should be using was
num correct / num asked

So with 3 questions and a batch size of 1, when selecting a correct answer instead of getting 100% I got 33%

**Comment by bradmac** [comment]
@hoanglinhlan I have updated kademi-beta, please retest

**Comment by hoanglinhlan** [comment]
passed
