### ISSUE TITLE
JB: CreateNote Action

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#2728]
This action will create a lead note which is similar to SetField Action

**Comment by tuzzmaniandevil** [comment]
Added and ready for testing :-)

It uses Mvel templating which is slightly different to Mvel expressions.

For example to get the latest message from a contact request you would do the following:
```
Message: @{lead.lastContactRequest.message}
```

**Comment by anhnt** [comment]
works great for me with this bit
`Payment Method: @{request.params.paymentMethod}

Additional information: @{request.params.additionalInfomation}`

**Comment by hoanglinhlan** [comment]
passed
