### ISSUE TITLE
Failed SMS

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2731]
http://admin.rspca-sa.olhub.com/manageUsers/121808555/#summary-tab

Why is the last SMS failed at 3 attempts?  Concerned this is the same or similar issue to before where SMS are not firing and causing the automation to stop.

**Comment by bradmac** [comment]
Sending the SMS itself failed, which is different to the previous issue where the SMS was not being attempted, and it was the trigger which was failing.

This is most likely because the phone number is invalid
