### ISSUE TITLE
Organisation members page shows duplicated users

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2736]
see viewOrg.html, this has:
```
                    #foreach($gm in $page.organisation.members)
                    <tr>
                        #set($p = $gm.member)
```

Users which have multiple memberships are shown multiple times. This should show each user once.

**Comment by ducdhm** [comment]
Example for new UI:
![vieworg](https://cloud.githubusercontent.com/assets/1289631/23541946/04997f82-001d-11e7-80c0-7012b932f5da.png)

**Comment by hoanglinhlan** [comment]
passed
