### ISSUE TITLE
Profile search not working

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2744]
http://ward6.admin.kademi.com.au/manageUsers/?startDate=14/12/2016&finishDate=16/12/2016

Entering a search does not refine the search results.

![image](https://cloud.githubusercontent.com/assets/2201340/21443962/19c5f0a4-c8fd-11e6-9241-4a402ff91d68.png)

**Comment by bradmac** [comment]
I confirmed this problem, but then i did a hard refresh and seems ok.
