### ISSUE TITLE
Improve page title for SEO purpose

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#2745]
Should be applied for all apps like ecommerce, reward store, blog, auction, etc...

**Comment by bradmac** [comment]
Example in viewEvent.html

Note that the title is not evaluated with a full template context, it just does substitution of the page title into the $title tag

```
<html>
    <head>
        <title>Event - $title</title>
    </head>
```

**Comment by tannguyen3489** [comment]
it was applied.
