### ISSUE TITLE
eCommerce: Show exception on category page of frontEnd 

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2750]
#2704 
Create a category with name/code has space ( ie: "abc _01")
The system display exception on category page of frontEnd 

http://version1.chip1stopecom.kademi.us/c1s-store/abc%20_01/
![image](https://cloud.githubusercontent.com/assets/20508726/21449512/7a9219b2-c920-11e6-8790-6ab42fab4bdf.png)

**Comment by bradmac** [comment]
@ducdhm please investigate

**Comment by ducdhm** [comment]
Already fixed in new version of reward and ecommerce libs!
