### ISSUE TITLE
Products component, top purchased products

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2754]
Query the productorders index for the most popular products purchased during the selected date range

Display as a table. Configurable number of products to display

Display the product title and the number of purchases

**Comment by ducdhm** [comment]
Improved issue: https://github.com/Kademi/kademi-dev/issues/new (will do later)

**Comment by hoanglinhlan** [comment]
show Exception 
![image](https://cloud.githubusercontent.com/assets/20508726/21757634/51244c70-d664-11e6-9a66-ccd56deea1b1.png)

**Comment by ducdhm** [comment]
Please test it on AU or your local. US's code is out-of-date. I'll update on US later when have time.

**Comment by ducdhm** [comment]
And make sure Products and Search app are enabled

**Comment by hoanglinhlan** [comment]
1: list product not order by purchased, 
![image](https://cloud.githubusercontent.com/assets/20508726/21792327/8546f3c4-d71b-11e6-80f7-f714f6054799.png)
2: don't put title in setting, title on frontEnd page is p1 although title on Editor is "Top 10 Purchased"

**Comment by ducdhm** [comment]
```
#3: Cant search this component, when I hover to image of this component, nothing happen
```
It's content editor issue, not this component

**Comment by hoanglinhlan** [comment]
passed
