### ISSUE TITLE
Feature to allow ES queries to be transformed into tables

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2767]
The Queries feature allows developers to write elasticsearch queries, which are returned in the native ES format.

This data can then be connected to histograms, tables, pie charts, etc.

But often the data needs to be transformed to align with user expectations, and ES has very limited ability to do ad-hoc transformations.

So a new feature is required which allows any arbitrary data, including ES queries but not limited to them, to be transformed to a regular tabular form for consumption by components.

This should also allow the tabular data to be exported as csv in front end websites.

**Comment by bradmac** [comment]
To get the first part working do the following.

This assumes you have already created a query called "hits by date" with the following code:
```
{
  "query": {
    "range": {
      "reqDate": {
        "gte": "@{formatter.formatDateISO8601( formatter.monthStart(formatter.now) )}",
        "lte": "@{formatter.formatDateISO8601( formatter.monthEnd(formatter.now) )}"
      }
    }
  },
  "aggs": {
    "hits_over_time": {
      "date_histogram": {
        "field": "reqDate",
        "interval": "hour"
      }
    }
  },
  "size": 2
}
```

1. Create controllers.xml in your queries repo. For me this is:
http://localhost:8080/repositories/queries/version1/

2. The controllers.xml should contain this:
```
<controllers>
    <source>/mytable.js</source>
</controllers>
```
3. Create mytable.js in the same directory.
4. Add the following to mytable.js
```
log.info("hello world");

queries.addTableDef("table1", "My first table", "loadHits")
    .addHeader("Date")
    .addHeader("Count");
    
function loadHits(result) {
    var resp = queryService.runQuery("hits by date");
    
    var agg = resp.aggregations.get("hits_over_time");
    var buckets = agg.buckets;
    log.info("buckets = {}", buckets.length)
    result.numRows = buckets.length;
    for( i=0; i<buckets.length; i++) {
        var bucket = buckets[i];
        result.addRow();
        result.addCell(bucket.key);
        result.addCell(bucket.docCount);
        result.flush();
    }
}
```

**Comment by bradmac** [comment]
A simple example to generate hard coded output

```
queries.addTableDef("query-table1", "Example query table", "generateTable");

function generateTable(result) {
    log.info("generateTable");
    for( var i=0; i<100; i++ ) {
        result.addRow();
        result.addCell("a " + i);
        result.addCell("b " + i);
    }
}
```

**Comment by anhnt** [comment]
![image](https://cloud.githubusercontent.com/assets/735555/21606115/f72623a2-d1df-11e6-99a6-6aa4d0055bd7.png)

**Comment by anhnt** [comment]
https://github.com/Kademi/kademi-dev/commit/6feaa1af8a4878224997216d4105c215b3523f20

**Comment by bradmac** [comment]
@anhnt I've done some refactoring
- created reporting-lib, and made it a dependency of ReportingApp
- moved the JS to init-reporting.js
- set parameters (query name and type) into data params on the panel, so it can be read from JS (ie instead of embedding template vars into js)

**Comment by bradmac** [comment]
Can you please just check what i've done.

**Comment by anhnt** [comment]
works great 👍
