### ISSUE TITLE
Company lookup takes too long

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2774]
http://kcrm.kademi.us/leads/2267011/

Click in the company field
Start typing a company name
Can take 5 to 10 seconds before an existing company name appears to select

![image](https://cloud.githubusercontent.com/assets/2201340/21664378/135a82d8-d33a-11e6-8afc-00b9d3d5d592.png)

**Comment by bradmac** [comment]
Confirmed is very slow, 12 secs or so. 

Also, i think the search logic might be wrong. It should just be searching the orgs appindexer, and should be limited to the org type for customer orgs

**Comment by mkhoudary** [comment]
Fixed that, this is my first time using App Indexers, @bradmac I'd appreciate a code review

**Comment by mkhoudary** [comment]
Done

**Comment by hoanglinhlan** [comment]
passed
