### ISSUE TITLE
Improve productListEDM component of rewardstore

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#2787]
* Update layout

Need for Carter EDM

**Comment by hoanglinhlan** [comment]
http://lan-test.admin.kademi.com.au/groupEmails/31531805/#messages-tab
Cant find any products although product existed

**Comment by bradmac** [comment]
Does the account you're testing with have sufficient points? the component only displays products the user can afford

**Comment by hoanglinhlan** [comment]
passed
