### ISSUE TITLE
Webpage editor width

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2796]
http://version1.100things-development.kademi.com.au/programs/100things/c1/m1/contenteditor?fileName=pp2.html&miltonUserUrl=/users/patrick&miltonUserUrlHash=28a002af-d6f9-4b09-836e-6ac690eb753f:V3E8dm1tsTzYBl8ZjfnzD6H04ws

When I edit a page, I want the width to mirror the width of the actual template the content sits inside, this way I have a more realistic view of how the content will look.

@ducdhm what do you think mate?

![image](https://cloud.githubusercontent.com/assets/2201340/21843277/7a75976a-d83e-11e6-9c2b-e6dd683a1c6b.png)

**Comment by anhnt** [comment]
we often have much smaller screen than yours Paddy :)

**Comment by ducdhm** [comment]
I'll implement in https://github.com/Kademi/kademi-dev/issues/2922
