### ISSUE TITLE
Contact report CSV export is not filtering on the contactForm term

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2798]
Eg - http://admin.rspca.olhub.com/reporting/contactRequests.csv?startDate=06%2F01%2F2017&finishDate=%2012%2F01%2F2017&term-groups=&term-contactForm=%2F1.html&term-orgs=40598038

This should limit results to only records with the /1.html contact form, but is instead including all records

**Comment by bradmac** [comment]
Fixed in master. Needs backporting

**Comment by gonzalon** [comment]
Check these:
- EsContactRequestsReport.java
- ReportCsvPage
