### ISSUE TITLE
Default image for Kademi

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#2800]
Example: `/img/non_existing-image` should return default image

Like some websites, they have default image for situation when trying to load a non-existing image. IMHO, I think better we should do like that. And we already have a default image which Paddy bought it.

**Comment by bradmac** [comment]
No, a non existing image should return a 404. There are cases where we allow no image to be selected and a default image is displayed (eg no profile image, no product image), but where a developer has specified an image and it is not found, it should return a 404
