### ISSUE TITLE
Allow user to change avatar via camera

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#2803]
Need for Carters

**Comment by gonzalon** [comment]
What browsers we need to support? 
So far I tested in the latests Chrome and Firefox and working fine, for IE we would need a polyfill as it doesnt support getUserMedia atm.

Also, after the save, the image of the user in the top nav (beside the username) isn't being updated.

**Comment by bradmac** [comment]
The main requirement is to support mobile devices, iOS and Android.

Desktop browsers are a bonus. IE is not required

**Comment by gonzalon** [comment]
For testing in mobile it should be only in **https**, because of browser spec.
So far, Safari is not supporting it, but it should work on Chrome for iOS.

**Comment by ducdhm** [comment]
@gonzalon An issue with camera feature: after show camera zone, there is no way to back normal upload zone.

**Comment by hoanglinhlan** [comment]
after I take a picture, the system showing a message "Please drag a rectangle to crop the image". But after I drag a rectangle and click "crop" button, an error showing 
![image](https://cloud.githubusercontent.com/assets/20508726/25519047/7fd2698c-2c20-11e7-9245-35138bf8025c.png)

**Comment by gonzalon** [comment]
@hoanglinhlan is the normal crop working for you? As I'm testing it in a windows machine the crop functionality doesn't work.

**Comment by hoanglinhlan** [comment]
passed
