### ISSUE TITLE
Web component to display social links

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#2806]
For bosch site

**Comment by anhnt** [comment]
done

**Comment by anhnt** [comment]
this app belongs to Content App and will be available in content-lib 1.0.3

![image](https://user-images.githubusercontent.com/735555/27732893-9a8560f8-5dbd-11e7-91fb-646742ab520e.png)

**Comment by bradmac** [comment]
Updated themes to depend on 1.0.3

**Comment by hoanglinhlan** [comment]
passed
