### ISSUE TITLE
Update pointsUserPanelComponent layout

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2807]
please use the same layout as here
https://github.com/Kademi/client-emc-vtl/issues/9

**Comment by anhnt** [comment]
done

**Comment by AlaaKhalaf94** [comment]
when I add pointsUserPanelComponent , the panel off points does not appear
and the name of user too

![capture3](https://user-images.githubusercontent.com/26510030/27856773-cdb8667e-6177-11e7-9015-8bb75554f27d.PNG)

and I am sure that I select the correct component

![capture1](https://user-images.githubusercontent.com/26510030/27856894-3e4a7c1a-6178-11e7-91ce-88962d3ef6d1.PNG)


this is a site : http://alaa-test.admin.kademi-prod.com/
this is user : http://alaa-test.admin.kademi-prod.com/manageUsers/148677/#summary-tab
this is a page that contain pointsUserPanelComponent : http://alaatest01.kademi-prod.com/newpage03.html

**Comment by AlaaKhalaf94** [comment]
checked

**Comment by anhnt** [comment]
👍
