### ISSUE TITLE
Photo component: Support vertical alignment setting

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#2809]

**Comment by anhnt** [comment]
done

**Comment by hoanglinhlan** [comment]
depend on https://github.com/Kademi/kademi-dev/issues/3177

**Comment by hoanglinhlan** [comment]
I changed from Midle to top then save, the system showing message " File is saved!" but after refresh page, it's alway showing Middle

**Comment by anhnt** [comment]
fixed

**Comment by hoanglinhlan** [comment]
passed
