### ISSUE TITLE
RB and PETED beta issues

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#281]
1. Something wrong with modules completion. Both RB and PETED.
I was not able to finish any module where the quiz existing.
It gives that all questions are answered correct but not finishing module.
![image](https://cloud.githubusercontent.com/assets/1945230/7073416/0c6b0db4-defc-11e4-962e-dfc66c14420e.png)
No possibility to go further.

sss02@mailinator.com
test123

sss04@mailinator.com
test123

2.  Contact us form RB: i don't remember if there was or not any other pointing when fields in contact form is not filled.
![image](https://cloud.githubusercontent.com/assets/1945230/7073812/ad563b34-defe-11e4-9765-d8cfc70d177f.png)
Like here for example
![image](https://cloud.githubusercontent.com/assets/1945230/7073885/1e059afa-deff-11e4-86a9-d02f20dbe506.png)

3. Module progress is not saving. For example i'm starting GORD module, go to the second page. That's a progress. Then go back to the learning page - no progress is visible there.
"choose your already started" mechanism also doesn't show that you're start something.
sss02@mailinator.com
test123

4. Minor visual, don't think that it connected to deploy. But anyway:
![image](https://cloud.githubusercontent.com/assets/1945230/7074085/85f4f9c0-df00-11e4-9023-e7bfae76c15f.png)
sss03@mailinator.com
test123

5. Also, looks like it doesn't show when module is read-only.

**Comment by bradmac** [comment]
"Something wrong with modules completion." - Fixed. there was a new column which hadnt been added to the db

**Comment by bradmac** [comment]
"Contact us form RB: i don't remember if there was or not any other pointing when fields in contact form is not filled." - Thats completely Ward6. I think its just how the form is

**Comment by bradmac** [comment]
"Module progress is not saving." - this works fine for me, using sss02 account. Went to the second page which was recorded and shows as 4% progress

**Comment by bradmac** [comment]
"Minor visual, don't think that it connected to deploy." - not for us to worry about

**Comment by bradmac** [comment]
"Also, looks like it doesn't show when module is read-only." - Thats just the heallthhub template, not our issue

**Comment by bradmac** [comment]
So i think it should be ok to deploy the update now.
