### ISSUE TITLE
Autocomplete fields for promotion forms

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2811]
The competitionFormComponent now has plain text fields for entering product SKU and org id (both are configurable)

We need these to be autocomplete fields, similar to org selection on the group rego page.

I have added ajax methods to retrieve appropriate in a format compatible with twitter typeahead:

Eg
http://version1.bosch.loopbackdns.com:8080/rewards/bosch-1/?searchOrgs=mega
http://version1.bosch.loopbackdns.com:8080/rewards/bosch-1/?searchProducts=a3

Example response to ?searchProducts:
```
[{"tokens":["a1","$200 A La Carte Prepaid Visa","$200 A La Carte Prepaid Visa"],"value":"a1"},{"tokens":["a3","$500 A La Carte Prepaid Visa","$500 A La Carte Prepaid Visa"],"value":"a3"}]
```

**Comment by bradmac** [comment]
![screenshot-localhost 8080 2017-01-17 12-43-14](https://cloud.githubusercontent.com/assets/826458/22002667/a995e568-dcb2-11e6-86b3-0351a6942f1a.png)

**Comment by bradmac** [comment]
![screenshot-version1 bosch loopbackdns com 8080 2017-01-17 12-42-18](https://cloud.githubusercontent.com/assets/826458/22002672/b091c2ce-dcb2-11e6-8150-1fdaaa993f80.png)

**Comment by anhnt** [comment]
done
