### ISSUE TITLE
orgSelectorComponent

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2813]
Create a component which allows the user to select from a organisation from the list of organisations  they have permission on. This selection will be persisted as a cookie and will be used to filter reportingOrgs so that data displayed through the queryservice is automatically filtered.

This component will normally be used alongside the dateRangeComponent

In the settings of the component allow selection of groups. The component should show all organisations which the user has any of the groups for. Eg if you select "branch-manager", an a user has the branch-manager group for organisations CTT and KTT, then the component will show CTT and KTT as options

Making a selection should set a cookie called "selectedOrg"

The component should display the selectedOrg when rendered, if one is selected.

When selected, it should reload the page so components are rendered with the new criteria

**Comment by anhnt** [comment]
![image](https://cloud.githubusercontent.com/assets/735555/22105805/5fe42da4-de78-11e6-8a71-36efd552188f.png)

**Comment by bradmac** [comment]
Hey @anhnt this is using Profile.getMemberships, so it shows ALL organisations a user is linked to

Please use $profile which returns a profilebean, and use the allMemberships method to list only memberships within the current org.

**Comment by anhnt** [comment]
using ```$userResource.profile``` now
