### ISSUE TITLE
Product in reward store resource is not being located by ID when not in a category

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2825]
Eg http://carters.kademi.com.au/trade-reward/21329181

**Comment by diegoperezn** [comment]
Tested on http://carters-test.kademi.com.au and I was not able to reproduce it.

Tested with products that have Gifts category and was removed to get no categary:
http://carters-test.kademi.com.au/trade-reward/BS/
http://carters-test.kademi.com.au/trade-reward/bf/
http://carters-test.kademi.com.au/trade-reward/40026891/

and with a new product: http://carters-test.kademi.com.au/trade-reward/newProduct/

Also tested with the automative category (http://carters-test.kademi.com.au/trade-reward/automotive/), remove all the items in it and the products still being accesible.

http://carters-test.kademi.com.au/jabra-drive-bluetooth-speakerphones/
http://carters-test.kademi.com.au/zapp-4-bike-rack-ergo-grey

Note: Sometimes a re-index is needed to see the changes in the site.

**Comment by bradmac** [comment]
Reproduced the issue
