### ISSUE TITLE
Consolidate querytable handling into jquery.querytable.js

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2827]
Currently the client side code that handles querytables is spread across 2 files
- jquery.queryTable.js
- init-reporting.js

Please move querytable handling code into jquery.queryTable.js so it is self contained

**Comment by anhnt** [comment]
Also added export CSV and pagination for querytable which gets data from raw ES query.

**Comment by anhnt** [comment]
Please re-test this component features as we rewrote the code
