### ISSUE TITLE
CourseFolder: Unable to sort by createdDate or modifiedDate

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#283]
If there is a ResourceList with CourseFolder, we are unable to sort it by either createdDate or modifiedDate, when attempted it throws a NullPointer exception.

**Comment by bradmac** [comment]
Couldnt reproduce the problem:
http://v2-brad.zoetis-livestock-reseller.kademi-beta.co/programs/VWAG_1/

#foreach($course in $curProgram.children.ofType.course.sortByModifiedDate )
course: $course.name
<br/>
#end

Produces this output:
course: VW
course: Seat
course: LOREM

**Comment by bradmac** [comment]
@tuzzmaniandevil when reporting an issue please always give
 - href to the page with the problem, including login
 - if there is a stack trace add it to the issue
