### ISSUE TITLE
Cannot cancel lead or complete task

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2831]
Canceling a lead seems to have a template error in the modal: http://kcrm.kademi.us/leads/8011776/
![image](https://cloud.githubusercontent.com/assets/2201340/22241529/dcbc41dc-e273-11e6-85f2-643ea7984a63.png)

When clicking the tick button for a task, no modal appears.
![image](https://cloud.githubusercontent.com/assets/2201340/22241565/0608bca0-e274-11e6-8246-043346d8aef3.png)

**Comment by bradmac** [comment]
dupissue
