### ISSUE TITLE
Social icons do not appear in EDM footer

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2836]
http://boschptnz.admin.kademi.com.au/groupEmails/34209494/#messages-tab

When dropping social icons into email footer, they do not appear in the email when sent.

![image](https://cloud.githubusercontent.com/assets/2201340/22355755/b85d6fc8-e480-11e6-9fd0-41d8f7cec154.png)

**Comment by ducdhm** [comment]
It's fixed new gen of edmEditor!
