### ISSUE TITLE
Editing templates

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2848]
I needed to edit the parent template to change the footer, but to get to this template I have to navigate away from my body content, through to manage websites, tab, then open the template.  It would be good to create a way to edit a parent template when editing the page body content.

- Maybe the editor can toggle and show/hide the template in situ
- When the template is shown, it could be highlighted slightly differently, but you can still edit it directly

**Comment by bradmac** [comment]
Thats what KToolbar is for :)
