### ISSUE TITLE
Add form to input properties like frontEnd

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2854]
In the case, Email has properties that user need input from FrontEnd. IMO, it will be the best if we have a form to input properties like fronEnd when we send test mail.

**Comment by bradmac** [comment]
Hey @hoanglinhlan sorry, not sure what this relates to. Can you provide a page/screenshot etc to give some context?

**Comment by hoanglinhlan** [comment]
I'll re-open this ticket when I see an example again
