### ISSUE TITLE
Products is automatically duplicated when multi-upload images for product 

### ISSUE THREAD

**Issue by tannguyen3489** [Kademi/kademi-dev#2856]
When I upload multi-images for product, a error upload alert happen. After that, the product will automatically duplicated. Please fix it.
![screenshot 2017-02-09 16-12-43](https://cloud.githubusercontent.com/assets/1665005/22776766/87203784-eee3-11e6-8f36-ba28e6370023.jpg)
![screenshot 2017-02-09 16-11-05](https://cloud.githubusercontent.com/assets/1665005/22776767/8721515a-eee3-11e6-8fb4-0adc0992bd62.jpg)

**Comment by ducdhm** [comment]
Tested only locally, AU and US. It's working normally!
