### ISSUE TITLE
Create component for recently viewed reward store products

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#2857]
Should be able to configure:

- Number of products
- ...

**Comment by bradmac** [comment]
Part of reward store app

**Comment by anhnt** [comment]
![recentlyviewedproducts](https://cloud.githubusercontent.com/assets/735555/26166465/d071623e-3b5d-11e7-84e6-df581be405cf.png)

**Comment by hoanglinhlan** [comment]
passed

**Comment by hoanglinhlan** [comment]
1: it's still showing example data in frontEnd 
2: set number of product =2 but it's showing 5 product 
3: it doesn't show recent viewed product, just showing example data
![image](https://cloud.githubusercontent.com/assets/20508726/26539083/bf6cecf4-4474-11e7-8954-f534f82d4623.png)
http://c5s.kademi.com.au/dashboard?miltonUserUrl=/users/test00nick4/&miltonUserUrlHash=94ba8b4c-07e6-468c-8ccf-d11e1222e615:iBVhcjKcN4QC5U1o0gjj-iWA9lc

**Comment by bradmac** [comment]
@tannguyen3489 can you investigate please? remember, we should only show example data when the component does not have required configuration

**Comment by tannguyen3489** [comment]
@bradmac : let me check it.

**Comment by tannguyen3489** [comment]
@hoanglinhlan : the number config was fixed. Currently, because this component don't have required configurations, the example data will show on this component. 

![image](https://cloud.githubusercontent.com/assets/1665005/26566980/adced522-4521-11e7-89db-fa31c72fe35d.png)

**Comment by tannguyen3489** [comment]
@hoanglinhlan : it was fixed again. It will now show example data, if now data, the no data message will be shown.

**Comment by hoanglinhlan** [comment]
it's alway showing message: "You have no recently viewed items"
https://lan-test.admin.kademi.com.au/manageUsers/48689307
http://c5s.kademi.com.au/dashboard

**Comment by anhnt** [comment]
fixed in rewardstore-lib 1.0.9

tested ok in this site http://version1.c5s-rewardstore001.kademi-prod.com/

**Comment by hoanglinhlan** [comment]
passed
