### ISSUE TITLE
Adding product image creates error popup

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2865]
http://airnz2.admin.kademi.us/products/kettle2/#panel_details-tab

When you add a product image, but do not crop it first, you get the below error message appear.  

You should not have to crop a product image unless required.  

The image does load once the page is refreshed.

![image](https://cloud.githubusercontent.com/assets/2201340/22879478/4fda0780-f232-11e6-85b5-b488aba344bc.png)

**Comment by gonzalon** [comment]
Can´t reproduce

**Comment by hoanglinhlan** [comment]
Cant reproduce
