### ISSUE TITLE
Smoke test for new theme

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#2867]
Checkout branch `admin-new-theme` of `kademi-dev`

**Comment by ducdhm** [comment]
Ping me for guiding setup

**Comment by hoanglinhlan** [comment]
1: new page popup display inccorect 
![image](https://cloud.githubusercontent.com/assets/20508726/22915793/536bb18a-f2ac-11e6-9bb6-6a8c8cbe58bf.png)

2: cant copy new verion web

**Comment by hoanglinhlan** [comment]
3: create new course, the popup missing course description area
![image](https://cloud.githubusercontent.com/assets/20508726/22916100/d591d872-f2ae-11e6-968a-d24dbeccf9e9.png)

**Comment by hoanglinhlan** [comment]
4: module detail / popup select file: cant add folder and select image and cant close popup by OK button
http://localhost:8080/websites/bootstrap-theme/version1/programs/kademi/Kademi-course/Kademi-course/#details-tab

**Comment by ducdhm** [comment]
1, 2, 3 are fixed!

**Comment by hoanglinhlan** [comment]
1: pass
2: failed, I still cant copy version web
3: pass
