### ISSUE TITLE
Edit article: content tab error

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2870]
http://localhost:8080/blogs/technical/my-article/#bodyCopy-tab
![image](https://cloud.githubusercontent.com/assets/20508726/22918772/7621c5fe-f2be-11e6-9ea3-e56c3a2513ff.png)
#2867

**Comment by bradmac** [comment]
thats probably because the blogs app is turned off for that website

**Comment by hoanglinhlan** [comment]
yes, I missing turn on blogs app
