### ISSUE TITLE
AutoEmails-trigger tab: Missing some items

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2874]
![image](https://cloud.githubusercontent.com/assets/20508726/22925882/f4f81392-f2dc-11e6-9adc-e35f50d664b7.png)

http://localhost:8080/autoEmails/36/#triggers-tab

1: missing properties for each Event type
2: I choose period type but it doesn't show
3: missing input text for Specify timer time
4: missing MVEL area

#2867

**Comment by hoanglinhlan** [comment]
I updated new source code, cleared cache and used incognito tab but it's till not work

**Comment by ducdhm** [comment]
Can you check again?

**Comment by hoanglinhlan** [comment]
error build
confirm passed
