### ISSUE TITLE
AutoEmails-trigger tab: XML has content of Expression 

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2875]
![image](https://cloud.githubusercontent.com/assets/20508726/22926132/f33d613c-f2dd-11e6-9195-f6e87d17644b.png)

#2867

**Comment by bradmac** [comment]
Actually we can remove the XML option entirely. That hasnt been used in a long time.

**Comment by ducdhm** [comment]
@bradmac Ok

**Comment by ducdhm** [comment]
Removed!

**Comment by hoanglinhlan** [comment]
passed
