### ISSUE TITLE
Automails: Cant open tabs

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2876]
http://localhost:8080/autoEmails/36/#triggers-tab
Chose 3 fist tabs then chose actions tab but nothing happen 
same issue with recipients tab, email history tab, smsHistory tab

#2867

**Comment by hoanglinhlan** [comment]
I updated new source code, cleared cache and used incognito tab but it's till not work

**Comment by ducdhm** [comment]
Can you check again?

**Comment by hoanglinhlan** [comment]
error build
confirm passed
