### ISSUE TITLE
ScheduleEmails: issues of new admin theme

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2877]
http://localhost:8080/scheduledEmails/schedule-mail-task/#

1: "Fire the next event after" : Cant change period type
2: Doesn't show information of  "Date & Time details" 
![image](https://cloud.githubusercontent.com/assets/20508726/22958584/c16f5df6-f362-11e6-8d1d-a00b16dc25be.png)

4: Message template need a ckeditor ( current, it's only a area text) 
5: ( refer #2878)  in the case User input Start Date (future day) and End date: Display error "500"
![image](https://cloud.githubusercontent.com/assets/20508726/22958930/e881d61a-f364-11e6-8df4-c0653b96d296.png)
 or JSON below

`{
data: null,
fieldMessages: [ ],
messages: [ ],
nextHref: "",
status: true
}`

#2867

**Comment by bradmac** [comment]
"4: Message template need a ckeditor ( current, it's only a area text)" <-- We can ignore that for now, its not an issue related to the theme update.

**Comment by hoanglinhlan** [comment]
passed
