### ISSUE TITLE
ScheduleEmails: Cant save schedule with setup future day for start date and end date 

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2878]
http://lan-test.admin.kademi.com.au/scheduledEmails/schedule-mail-task/#configuration-tab

the system showing error When I save schedule 
case1: select a future day for start date then click save 
case2: select a current day for start date and future day for end date then click save

**Comment by bradmac** [comment]
The problem is the date picker is using US format, MM/DD/YYYY, but the server is expecting NZ format, DD/MM/YYYY

@ducdhm i cant figure this one out, the init code looks right.

kademi.js has this
```
function initDatePicker() {
    $('.date-picker').exist(function () {
        var datePicker = this;

        flog("init datePicker", datePicker, datePicker.datepicker);

        datePicker.datepicker({
            autoclose: true,
            format: 'DD/MM/YYYY'
        });
```

**Comment by hoanglinhlan** [comment]
passed
