### ISSUE TITLE
Point bucket: Cant save point bucket 

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2880]
http://localhost:8080/points-buckets/gggg/?startDate=08%2F02%2F2017&finishDate=14%2F02%2F2017&dataQuery=#details-tab

Input all filed then click save. The system display error "Sorry, we could not process your request ..."

#2867

**Comment by ducdhm** [comment]
@hoanglinhlan You can re-check it again. I have clean your classes folder in target. So you can save it again

**Comment by hoanglinhlan** [comment]
passed
