### ISSUE TITLE
Shopping cart: cant upload csv file 

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2882]
http://lan-test.admin.kademi.com.au/shopping-carts/?&startDate=15/02/2016&finishDate=15/02/2017

it's showing error when I upload csv file
![image](https://cloud.githubusercontent.com/assets/20508726/22961241/2553ee5e-f377-11e6-8936-fa93b41dcdd8.png)

**Comment by bradmac** [comment]
Fixed
