### ISSUE TITLE
Cant copy new verion web

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#2885]
Can you provide more details and screenshot?

**Comment by hoanglinhlan** [comment]
hi @ducdhm 
Step to reproduce: 
1: click copy version 
![image](https://cloud.githubusercontent.com/assets/20508726/22982084/9f530484-f3d0-11e6-9da9-43257ee94e8f.png)
2: input name of new version then click copy
==> the system reload page but When I check in list version, new version is not showing

**Comment by ducdhm** [comment]
https://github.com/Kademi/kademi-dev/issues/2867

**Comment by hoanglinhlan** [comment]
passed
