### ISSUE TITLE
Tablet: Modules detail page: Popup getting cut off 

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2886]
http://localhost:8080/websites/bootstrap-theme/version1/programs/kademi/Kademi-course/Kademi-course/#files-tab
**module page tab**
- popup add quiz 
- popup add page
![image](https://cloud.githubusercontent.com/assets/20508726/22981838/f61770a8-f3cf-11e6-9c10-7fade88c7810.png)
![image](https://cloud.githubusercontent.com/assets/20508726/22981862/074fd8a6-f3d0-11e6-888e-2a06a84e1d1d.png)

**Module detail tab** 
- popup select file
![image](https://cloud.githubusercontent.com/assets/20508726/22982202/03dcebd6-f3d1-11e6-800c-58cf5efd69fc.png)

#2867

**Comment by hoanglinhlan** [comment]
**module page tab**
- popup add page: pass
- popup add quiz: 
![image](https://cloud.githubusercontent.com/assets/20508726/23050178/4540a4aa-f4f3-11e6-9fd4-f32a3ef41a40.png)
![image](https://cloud.githubusercontent.com/assets/20508726/23050248/b08de448-f4f3-11e6-923b-91959acb3d39.png)

**Module detail tab** 
- popup select file: pass

**Comment by ducdhm** [comment]
Fixed!

**Comment by hoanglinhlan** [comment]
passed
