### ISSUE TITLE
tablet: Course manage - Program detail showing wrong

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2889]
http://localhost:8080/websites/bootstrap-theme/version1/programs/kademi/Kademi-course/
actual 
![image](https://cloud.githubusercontent.com/assets/20508726/22982871/ee3305a2-f3d2-11e6-95a0-2057b6e73635.png)

expect
![image](https://cloud.githubusercontent.com/assets/20508726/22982907/0884f0dc-f3d3-11e6-98ce-db2829bbe79f.png)

#2867

**Comment by ducdhm** [comment]
Fixed!

**Comment by hoanglinhlan** [comment]
passed
