### ISSUE TITLE
Template error when viewing queued trigger page

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#289]
http://admin.cpaaustralia.kademi-beta.co/autoEmails/timerTriggers.html

nvocation of method 'getUploadTaskName' in class io.milton.cloud.server.apps.email.ViewTriggerTimersPage threw exception java.lang.NullPointerException at admin.cpaaustralia.kademi-beta.co:/theme/apps/email/viewTriggerTimers.html[line 385, column 41]
/templates/themes/admin2/

**Comment by tuzzmaniandevil** [comment]
Fixed and on Beta.
