### ISSUE TITLE
Module details issue

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#2890]
module detail / popup select file: cant add folder and select image and cant close popup by OK button

**Comment by ducdhm** [comment]
https://github.com/Kademi/kademi-dev/issues/2867

**Comment by hoanglinhlan** [comment]
passed

**Comment by hoanglinhlan** [comment]
Create some folder then remove one of them then upload an image. The system display error 
![image](https://cloud.githubusercontent.com/assets/20508726/23008407/f900ff06-f441-11e6-8dbc-10924636815f.png)

**Comment by ducdhm** [comment]
Fixed!

**Comment by hoanglinhlan** [comment]
passed
