### ISSUE TITLE
Reporting - Points expiring in 90 days: Filter by date range not working 

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2894]
http://lan-test.admin.kademi.com.au/reporting/pointsExpiring
Specification: Returns participants with points expiring in the 90 days following the currently selected period
so,
- if I choose **5 options on endding now**, the report should display participant that has point expiring in the 90 day period after **current date** 
![image](https://cloud.githubusercontent.com/assets/20508726/23011862/c8f1b7c4-f455-11e6-805c-fdf15f4c4630.png)

- if I choose a **period time on custom date**, The report display all participant that has point expiring in the 90 day period after **the end date of the selected date range** ( ie in image is 02/10/2017 ==>  points expiring in the 90 days after  02/10/2017)
![image](https://cloud.githubusercontent.com/assets/20508726/23011894/01ad2ea4-f456-11e6-8c4e-9f608ab3605e.png)

**Currently, the report always display points expiring after current date**

**Comment by bradmac** [comment]
That actually does look correct to me:

![screenshot-lan-test admin kademi com au 2017-02-27 09-35-43](https://cloud.githubusercontent.com/assets/826458/23343428/33d48652-fcd0-11e6-91ec-b76e0b70accc.png)
