### ISSUE TITLE
Reporting- Doesn't show statistic:  Group signups Report

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2896]
![image](https://cloud.githubusercontent.com/assets/20508726/23013993/b0537c66-f45f-11e6-91c2-c53a784612d8.png)

![image](https://cloud.githubusercontent.com/assets/20508726/23013997/b3da9aa4-f45f-11e6-8e20-ae145585f440.png)

#2895

**Comment by ducdhm** [comment]
Fixed!

**Comment by hoanglinhlan** [comment]
passed
