### ISSUE TITLE
Reporting- Doesn't show statistic:  Active users Report

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2897]
![image](https://cloud.githubusercontent.com/assets/20508726/23014126/410ecd82-f460-11e6-9241-ca207160fdb9.png)

![image](https://cloud.githubusercontent.com/assets/20508726/23014114/35ff47d2-f460-11e6-862f-27587ddeebff.png)

#2895

**Comment by ducdhm** [comment]
Done!

**Comment by hoanglinhlan** [comment]
passed
