### ISSUE TITLE
Reporting- Doesn't show statistic: Web activity (beta) Report

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2898]
![image](https://cloud.githubusercontent.com/assets/20508726/23014161/6f6c5564-f460-11e6-87c8-e5f9bbf5a392.png)

![image](https://cloud.githubusercontent.com/assets/20508726/23014174/7d606ffc-f460-11e6-8d1f-29c90dbf27f2.png)

#2895

**Comment by ducdhm** [comment]
Fixed!

**Comment by hoanglinhlan** [comment]
passed
