### ISSUE TITLE
Reporting- Doesn't show statistic: Active users Report

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2899]
![image](https://cloud.githubusercontent.com/assets/20508726/23014359/3fcfb944-f461-11e6-801a-04046a921859.png)

![image](https://cloud.githubusercontent.com/assets/20508726/23014372/49b21cfe-f461-11e6-8e87-76c1214fcc0e.png)

#2895

**Comment by ducdhm** [comment]
Fixed!

**Comment by hoanglinhlan** [comment]
dupicate #2897
