### ISSUE TITLE
Reporting- Doesn't show statistic:  Module activity Report

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2901]
![image](https://cloud.githubusercontent.com/assets/20508726/23014849/3ed40c0a-f463-11e6-98c9-eb6185aa79f6.png)

![image](https://cloud.githubusercontent.com/assets/20508726/23014820/195f14e2-f463-11e6-9db4-cc8884519b26.png)

#2895

**Comment by ducdhm** [comment]
Fixed!

**Comment by hoanglinhlan** [comment]
passed
