### ISSUE TITLE
Reporting- Doesn't show statistic: Module fields Report

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2904]
![image](https://cloud.githubusercontent.com/assets/20508726/23015710/741f1f64-f466-11e6-8704-9e059a0714bd.png)
![image](https://cloud.githubusercontent.com/assets/20508726/23015713/77079e86-f466-11e6-85fe-6af4dea7afda.png)

#2895

**Comment by ducdhm** [comment]
Fixed!

**Comment by hoanglinhlan** [comment]
passed
