### ISSUE TITLE
Reporting- Doesn't show statistic: Module Quiz/Surveys Report

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2905]
![image](https://cloud.githubusercontent.com/assets/20508726/23016093/ecb63524-f467-11e6-911a-9ce5463411d4.png)
![image](https://cloud.githubusercontent.com/assets/20508726/23016096/ee997310-f467-11e6-9a98-9afab06432d2.png)

#2895

**Comment by ducdhm** [comment]
Fixed!

**Comment by hoanglinhlan** [comment]
passed
