### ISSUE TITLE
 Reporting- Doesn't show statistic: Points Debit Report

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2908]
![image](https://cloud.githubusercontent.com/assets/20508726/23017090/82ff89ce-f46b-11e6-8080-c8dd70ac002e.png)

![image](https://cloud.githubusercontent.com/assets/20508726/23017094/87175ad2-f46b-11e6-9f9c-e16b4218790f.png)

#2895

**Comment by ducdhm** [comment]
Fixed!

**Comment by hoanglinhlan** [comment]
passed
