### ISSUE TITLE
Tablet - Certificate detail: Item's position is incorrect

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2911]
http://localhost:8080/certificates/cert_1/?useHash=true
actual
![image](https://cloud.githubusercontent.com/assets/20508726/23050442/f9c1488e-f4f4-11e6-9df3-5fc3d9330d9c.png)

expect
![image](https://cloud.githubusercontent.com/assets/20508726/23050447/ffd16574-f4f4-11e6-822f-cc5db3221c83.png)

#2867

**Comment by ducdhm** [comment]
Fixed!

**Comment by hoanglinhlan** [comment]
passed
