### ISSUE TITLE
Enable dashboard alerts for the admin

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2917]
Alerts should filter down to child orgs

To try this out, go to manage alerts page, click create alert, and select the first option (create admin alert)

Enter details and save. Make sure its enabled.

Now go to the dashboard and you should see it. Login to the admin for a child org and you should also see it. Click the X to acknowledge an alert and it should disappear and not redisplay

**Comment by ducdhm** [comment]
Cools, I'm planing to create an issue about this to you but you did it 💯
