### ISSUE TITLE
Use SweetAlert instead of confirm or alert boxes

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#2919]
https://lipis.github.io/bootstrap-sweetalert/

**Comment by ducdhm** [comment]
@tuzzmaniandevil I discussed with brad about this a long time ago and he rejected it because of it's not blocking UI.

@bradmac What do you think about it again?

**Comment by bradmac** [comment]
Looks ok to me!
```


swal({
  title: "Are you sure?",
  text: "Your will not be able to recover this imaginary file!",
  type: "warning",
  showCancelButton: true,
  confirmButtonClass: "btn-danger",
  confirmButtonText: "Yes, delete it!",
  closeOnConfirm: false
},
function(){
  swal("Deleted!", "Your imaginary file has been deleted.", "success");
});
```

**Comment by ducdhm** [comment]
@paddyow @bradmac So which type of message I'll apply SweetAlert to? Only `alert`, `prompts` and `confirm` method? How about our bootstrap-msg?

Other candidates:
 * http://kamranahmed.info/toast#quick-demos
 * https://nakupanda.github.io/bootstrap3-dialog/

**Comment by bradmac** [comment]
@ducdhm what we're thinking about here is replacing the few places where we currently use alert, prompt and confirm. This doesnt affect bootstrap-msg, I think we would use toast for that.

**Comment by tuzzmaniandevil** [comment]
I've added the SweetAlert files to the admin theme and i'm using it for the new OAuth2 server app. Gives us a chance to have a look at it in practice.

**Comment by ducdhm** [comment]
2 variants of Konfirm which are using in admin.
![variant_1st](https://user-images.githubusercontent.com/1289631/28311780-e189c02c-6bda-11e7-99d1-e7378188a1e2.png)
![variant_2nd](https://user-images.githubusercontent.com/1289631/28311781-e1aac38a-6bda-11e7-9baf-33d2dced97fd.png)

**Comment by ducdhm** [comment]
@paddyow Can you help me uniform them? We need only 1 variant for it in admin console.

**Comment by ducdhm** [comment]
Btw, here is what final decision for our confirm:

![aaa](https://user-images.githubusercontent.com/1289631/28312425-4845fc02-6bdd-11e7-8c86-fcc5eee9ea34.png)
