### ISSUE TITLE
Change admin colours

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2920]
http://rootorg.admin.kademi.com.au/websites/kademico-www/version1/#panel_apps-tab

![image](https://cloud.githubusercontent.com/assets/2201340/23118408/1e42d366-f7a8-11e6-86bb-a445655dadf3.png)
![image](https://cloud.githubusercontent.com/assets/2201340/23118443/42caf1be-f7a8-11e6-9c45-8e869ed69993.png)
![image](https://cloud.githubusercontent.com/assets/2201340/23118464/5ba13626-f7a8-11e6-85e2-190eb2eea7bf.png)

1) Kademi red
2) Kademi green
3) Kademi pale blue

Change the old red and green to the Kademi red and green.

////////////////

http://rootorg.admin.kademi.com.au/websites/learningtest/version1/programs/Test1/Test2/

![image](https://cloud.githubusercontent.com/assets/2201340/23118269/ad2915be-f7a7-11e6-87ba-53add9374070.png)

The module blue should be Kademi blue
The inactive grey should be Kademi dark blue, meaning the Cog Icon needs to change colour

![image](https://cloud.githubusercontent.com/assets/2201340/23118308/cea404e2-f7a7-11e6-9117-f45f8539172a.png)
Modal light greys needs to be the Kademi pale blue

![image](https://cloud.githubusercontent.com/assets/2201340/23118343/e58da74e-f7a7-11e6-96a5-b0a4f46682c9.png)
light grey needs to be the Kademi pale blue

http://rootorg.admin.kademi.com.au/manageRepos/
![image](https://cloud.githubusercontent.com/assets/2201340/23118502/7edc9522-f7a8-11e6-94fa-8d0ec30ba8c8.png)

1) Kademi blue
2) Kademi pale blue

**Comment by hoanglinhlan** [comment]
passed
