### ISSUE TITLE
Update JB

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#2921]

**Comment by ducdhm** [comment]
Node previews:
![duc](https://cloud.githubusercontent.com/assets/1289631/23153914/b905f596-f83d-11e6-8253-2ed9eb9b4413.jpg)

**Comment by bradmac** [comment]
:+1:

**Comment by ducdhm** [comment]
Updated nodes preview list in RHS (No need preview image)
![fireshot screen capture 031 - my-funnel - localhost_8080_funnels_my-funnel_ journeybuilder-tab](https://cloud.githubusercontent.com/assets/1289631/23178358/b1119642-f89c-11e6-9bc8-fb9eead333cd.png)

**Comment by bradmac** [comment]
@paddyow will users be able to figure out what those nodes are? i was thinking we would have descriptive graphics like autopilot does, not just generic font awesome icons

![trade-show-follow-up-journey](https://cloud.githubusercontent.com/assets/826458/23181140/af58ae08-f8d8-11e6-9d6f-6905cbcb1d8e.jpg)

**Comment by hoanglinhlan** [comment]
I think it will be the best if we have a search node

**Comment by ducdhm** [comment]
@bradmac Beside icon property as just class for icon, I'll support icon as url to image for custom icon.
Example:
```
JBNodes['myNode'] = {
    icon: 'clip-one', // for font-based icon like font-awesome, glyphicon, icomoon, clip-one, etc...
    icon: { // for image-based icon
        small: 'path/to/small/icon', // for icon in node
        large: 'path/to/large/icon' // for icon in previewed node
    }
}
```

**Comment by ducdhm** [comment]
Please take a look, we have some nodes which have more than 2 OUT points but in your design, we have place enough for only 2. Please take a look....

![components](https://cloud.githubusercontent.com/assets/1289631/23539247/8dd4ccfe-000c-11e7-9459-2baab98bc1d7.jpg)

![aaaaaa](https://cloud.githubusercontent.com/assets/1289631/23539251/918560de-000c-11e7-8d54-787fb9dddd75.png)
