### ISSUE TITLE
add product's image success but the page showing error message

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2925]
http://lan-test.admin.kademi.com.au/products/iphone9plus%20name/#panel_details-tab
![image](https://cloud.githubusercontent.com/assets/20508726/23160678/f75e5330-f859-11e6-9034-48eec036e85c.png)

**Comment by hoanglinhlan** [comment]
![image](https://cloud.githubusercontent.com/assets/20508726/23160662/ec1f9830-f859-11e6-9f37-c0aa8d952deb.png)

**Comment by ducdhm** [comment]
@bradmac: Server doesnt return JSON when `applyImage: true`. Can you help me double-check?

**Comment by hoanglinhlan** [comment]
passed
