### ISSUE TITLE
Product List EDM Component is not splitting products over rows

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2929]
http://carters.admin.kademi.com.au/groupEmails/32494867/#messages-tab

Opened the email in thunderbird and its generated 5 products, but they are displayed in a single row

**Comment by anhnt** [comment]
Just fixed on carters by appending a ```<br>``` after first 3 products. But we should have proper way to fix it in platform

**Comment by ducdhm** [comment]
Please test on your locally
