### ISSUE TITLE
Date range filtering is not working on email history page

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2931]
Eg http://swimart.admin.kademi.com.au/emails/

**Comment by ducdhm** [comment]
@hoanglinhlan 
Pre-condition for testing is not cookie for pageDatePicker. So simplest, just remove all cookies and retest it

**Comment by bradmac** [comment]
Definitely not working, but possibly not related to the theme changes

**Comment by bradmac** [comment]
Refactored the page to use handlebars for rendering rows from the same response as the analytics
