### ISSUE TITLE
Promotion: error 500 when I save a promotion

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2942]
http://lan-test.admin.kademi.com.au/rewards/hhhhhhhh/#rewardContent-tab
input to area under "This copy will be displayed to the winners." then click save. 
The system show error 500

**Comment by bradmac** [comment]
The rewards and promotions app was turned off the website the promotion was in, and the formsBuilder app was not installed

**Comment by hoanglinhlan** [comment]
confirm it's work
