### ISSUE TITLE
Promotion: always return JSON after save

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2943]
http://lan-test.admin.kademi.com.au/rewards/hhhhhhhh/#checkout-tab
edit or input some filed then save, the system always show JSON
`{
data: null,
fieldMessages: [ ],
messages: [ ],
nextHref: "",
status: true
}
`

**Comment by bradmac** [comment]
The rewards and promotions app was turned off the website the promotion was in, and the formsBuilder app was not installed
