### ISSUE TITLE
Editing categories from manage product page

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2948]
Admin users should be able to add and remove categories on the manage product details page.

The UI should be similar to adding/removing groups on the manage user page:

![screenshot-lan-test admin kademi com au 2017-02-27 09-19-49](https://cloud.githubusercontent.com/assets/826458/23343302/f274e352-fccd-11e6-845e-1c366e849226.png)

Add the tags list above the tabs:

![screenshot-carters admin kademi com au 2017-02-27 09-21-11](https://cloud.githubusercontent.com/assets/826458/23343330/7621b400-fcce-11e6-8940-baf9763807a1.png)

**Comment by bradmac** [comment]
![screenshot-localhost 8080 2017-02-28 14-39-50](https://cloud.githubusercontent.com/assets/826458/23387828/d05b9a44-fdc3-11e6-8f1e-e665320cadb8.png)

**Comment by gonzalon** [comment]
Couldn't reproduce it
