### ISSUE TITLE
Contact request default group should not be set by default

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2949]
Scenario:

- New Kademi account
- Developer sets up contact form using APP
- The contact request APP by default chooses a group (this group could have end user data in it as it was preloaded)
- The dev or someone else tests without knowing this and spams that group time and time again

The group defined in the contact request APP should not be set until someone sets it, meaning no requests will be sent to a group.

**Comment by bradmac** [comment]
The contact us app sends notifications by default to the administrator group.

This is correct operation
