### ISSUE TITLE
Queued triggers page "launch button" doesn't works

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#295]
![image](https://cloud.githubusercontent.com/assets/1945230/7185171/e5741f3e-e469-11e4-98f0-2ecc608713d1.png)

**Comment by tuzzmaniandevil** [comment]
This is correct, the button is disabled here. You need to go into the automation trigger and view the queued triggers from there to be able to force immediate fire

**Comment by Uafinder** [comment]
understood, thanks
