### ISSUE TITLE
Content editor does not remember setting

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2951]
When  I select the image in the bottom panel, configure and de-select 'Full width' then save, it does not remember my selection, so when I go back into the email the tick box for 'Full width' is ticked again and the bottom image looks really big.

![image](https://cloud.githubusercontent.com/assets/2201340/23390968/63005302-fdc5-11e6-8dc9-70407c9dcb98.png)

**Comment by ducdhm** [comment]
Already fixed in other issue
