### ISSUE TITLE
Profile photo needs to be cropped before it is accepted

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2953]
When updating a profile image, if you do not crop it first, the image does not update.

If this is an requirement, the continue button should not be clickable until the crop is applied.

![image](https://cloud.githubusercontent.com/assets/2201340/23392220/43145c56-fdce-11e6-939e-83b2e5a1ddcc.png)

**Comment by bradmac** [comment]
we shouldnt need to crop

**Comment by hoanglinhlan** [comment]
I upload new image then click submit but profile's image not change

**Comment by ducdhm** [comment]
Fixed!
