### ISSUE TITLE
Sms history details on each sms fails

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#296]
When you try to see details a each sms exactly
![image](https://cloud.githubusercontent.com/assets/1945230/7186467/a5a572aa-e472-11e4-8705-7b9d1e129161.png)
it gives you an empty broken page
![image](https://cloud.githubusercontent.com/assets/1945230/7186479/bbd19176-e472-11e4-91c1-3afdaa0470fb.png)

**Comment by tuzzmaniandevil** [comment]
Fixed

**Comment by Uafinder** [comment]
yup, works fine
