### ISSUE TITLE
KEditor doesnt show title of some components

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#2960]

**Comment by ducdhm** [comment]
Issue here is
 * KEditor's using `data-title` attribute from snippets as title of component
 * Some components have `data-title` as a part of dynamic element inside

**Comment by ducdhm** [comment]
@hoanglinhlan You can test with component like topPurchased of Product App

**Comment by hoanglinhlan** [comment]
all components of all apps have desciption
