### ISSUE TITLE
Manage rewards points page should show credit and debit transactions

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2961]
Currently the manage rewards points page only shows reward credit transactions, it does not show debits.

Credits and debits are shown in a single list on the manage user page, on the points tab.

We would like the manage reward points page to work the same way, by showing credits and debits in the same table.

Allow sorting by either amount, date and reward

Note that this page uses the paginator component for pagination.

See 
- Points and PointsDebit classes
- ManagePoints controller
- /theme/apps/learner/managePoints.html

Eg http://localhost:8080/rewards/points/

**Comment by bradmac** [comment]
Have removed the group filter option, since its rarely used and made things more complex.

Also removed the edit button, since we are discouraging our users from using it anyway

**Comment by Uafinder** [comment]
https://github.com/Kademi/kademi-dev/issues/2991
https://github.com/Kademi/kademi-dev/issues/2993

Also,
Allow sorting by either amount, date and reward - sorting absent.

**Comment by bradmac** [comment]
Not doing sorting for now.
