### ISSUE TITLE
The number of organisation's member is counted incorrectly

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2966]
relate #2736 
The number of organisation's member is incorrect on list page:
- RHS (right hand site) of user manage page
- orgnisation manage page

**Comment by ducdhm** [comment]
@bradmac: What do you think about this issue?

**Comment by bradmac** [comment]
Currently its showing the number of memberships, which can be different to the number of users. It would be better to show the number of users, but showing number of memberships is acceptable.

**Comment by bradmac** [comment]
I think we push this back a couple of milestones

**Comment by Uafinder** [comment]
Probably column "memberships" on the organisations manage page should be changed back to "members".
https://github.com/Kademi/kademi-dev/issues/3937

**Comment by bradmac** [comment]
Done

**Comment by Uafinder** [comment]
YEap, works ok
