### ISSUE TITLE
Group members page counts duplicate users

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2967]
![image](https://cloud.githubusercontent.com/assets/20508726/23646826/377e5a32-0345-11e7-8c1d-649a6b075f50.png)

Precondition: members of 1 group but in mutilple orgs
1: on group members page: this members shown multiple times
2: on user manage page and group manage page: number of group's member counts duplicate users

**Comment by tannguyen3489** [comment]
it was fixed.
