### ISSUE TITLE
Module expiry

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#2974]
- modules should have a configurable expiry policy, eg valid for a certain amount of time
- have a module expiry approaching goal, for use with the JB
- module expired goal, for use with the JB
- modules should be unlocked, ie available for re-completion, after the module expiration warning

Required for - https://github.com/Kademi/client-zoetis/issues/71

**Comment by bradmac** [comment]
Also added search screen to the manage module page to list results

**Comment by cheetah100** [comment]
Why am I still receiving emails from this list? I can't see how to unsub.

**Comment by bradmac** [comment]
Now also supports renewal. 

![screenshot-localhost 8080 2017-03-13 12-58-58](https://cloud.githubusercontent.com/assets/826458/23837417/df88cf90-07ec-11e7-918a-3229c25f7036.png)
