### ISSUE TITLE
Cat menu appear behind menu

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#2975]
http://zoetis.admin.kademi.com.au/categories/

![image](https://cloud.githubusercontent.com/assets/2201340/23733186/b0c9bbde-04cb-11e7-9daa-05bad6dabac0.png)

**Comment by bradmac** [comment]
Found it!

![tabby-cat-does-disappearing-act-behind-menu-sign-of-greek-restaurant-ac7g1e](https://cloud.githubusercontent.com/assets/826458/23733400/8c794b48-04dd-11e7-8444-fea427c6dc37.jpg)

**Comment by ducdhm** [comment]
Fix in this commit https://github.com/Kademi/kademi-dev/commit/78ad14832d4230aa2e91a084317864c29add655b
