### ISSUE TITLE
Send email - simulate event error

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#2977]
![image](https://cloud.githubusercontent.com/assets/1945230/23765283/62d5df46-0509-11e7-9362-d1aa11edab67.png)
![image](https://cloud.githubusercontent.com/assets/1945230/23765313/79a1a91c-0509-11e7-8d8e-0100151d2fa7.png)

**Comment by bradmac** [comment]
Looks like there is some js not being initialised

**Comment by ducdhm** [comment]
Fixed
