### ISSUE TITLE
Login page refreshes when user has no assign roles

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#2978]
When user wants to login to the admin console and he is a member of a group which has no role assignment login page refreshes, login credentials clears and there is no message appears.
Should be some message i think.
1
![image](https://cloud.githubusercontent.com/assets/1945230/23765884/6c3e6146-050b-11e7-8de9-aee026b2247d.png)
2
![image](https://cloud.githubusercontent.com/assets/1945230/23765896/77731aac-050b-11e7-8b41-250b6fc0f7d9.png)

**Comment by bradmac** [comment]
Yes, should show the unauthorised message. The login page did used to have template code to check the reason why it was being displayed, ie if the request was not authorised, or if there was just no current user

**Comment by ducdhm** [comment]
It's fixed. Can check in locally but need to deploy for checking on AU or US server
