### ISSUE TITLE
Doubleclick on the create data record causes pop-up windows malfunction

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#2979]
![image](https://cloud.githubusercontent.com/assets/1945230/23766559/02888670-050e-11e7-99ec-f3b81f70aedc.png)
![image](https://cloud.githubusercontent.com/assets/1945230/23766695/913b2332-050e-11e7-8548-6e8989dba53f.png)

Fields become non-editable

![image](https://cloud.githubusercontent.com/assets/1945230/23766573/185e9aca-050e-11e7-8d7c-81bf214a3a0c.png)

**Comment by bradmac** [comment]
@ducdhm can you check if this is a general problem with the forms plugin?

**Comment by ducdhm** [comment]
@bradmac It's new bug from forms plugin but with trigger button outside of form.

**Comment by bradmac** [comment]
Hey @ducdhm this change has broken force complete on the manage profile page

Its created this:
```
<button type="button" type="submit" class="btn btn-sm btn-primary">Set complete</button>
```

See the 2 type attributes

**Comment by bradmac** [comment]
@ducdhm I've fixed that page, but can you please check all other affected pages?
