### ISSUE TITLE
Editing data series record causes incorrect timestamp

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#2981]
![image](https://cloud.githubusercontent.com/assets/1945230/23767242/94d4b132-0510-11e7-8189-e6086c403157.png)

**Comment by bradmac** [comment]
The issue is that the input is a date picker which does not include a time component. So when its saved, the time is set to midnight.

We should change the date picker to a date/time picker.

**Comment by ducdhm** [comment]
Changed to date time picker!

**Comment by hoanglinhlan** [comment]
1: after I created a new record, the date is not showing in record detail page
https://lan-test.admin.kademi.com.au/sales/new-series1/56747212
2: I cant save Sale date and Date entered. The system alway showing an error "we could not process your request"

**Comment by hoanglinhlan** [comment]
passed
