### ISSUE TITLE
Remove date filter from data series page

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#2985]
desided to change date pickup filter
![image](https://cloud.githubusercontent.com/assets/1945230/23769234/71a9d280-0517-11e7-810e-6d862ccb9357.png)
Any choice causing invalid date label
![image](https://cloud.githubusercontent.com/assets/1945230/23769268/8d14a892-0517-11e7-99fc-4f2a5f2aedc2.png)

**Comment by bradmac** [comment]
We need to remove the date range control. All pages should use the common date range selector
