### ISSUE TITLE
Refresh page on the different tab cause general tab fail

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#2986]
![image](https://cloud.githubusercontent.com/assets/1945230/23769446/15c44db4-0518-11e7-9f5d-3e6714d4e6d7.png)
When you refresh page when you are on KPI, Points, Records tabs this cause graph problem.

**Comment by bradmac** [comment]
@tannguyen3489 please have a look, and if its going to be hard lets discuss

**Comment by hoanglinhlan** [comment]
pased
