### ISSUE TITLE
Top SKU component for Data Series

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#2990]
Need for 3M

**Comment by ducdhm** [comment]
Create it as a part of 3M Extra Components

**Comment by bradmac** [comment]
We still need this component...

**Comment by bradmac** [comment]
@tannguyen3489 i think this component has been created within a client account. We would like to have it available as a standard component.

**Comment by ducdhm** [comment]
@tannguyen3489 Please ping me when you do this issue. I'll show you where this component in client account.

**Comment by tannguyen3489** [comment]
I see
