### ISSUE TITLE
Page should be update to review new debit record

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#2991]
For example. i award some points. It shows immediately after submitting. However, when i debit some points it will not show instantly and page should be refreshed to review new record.
![image](https://cloud.githubusercontent.com/assets/1945230/23830836/74ef7ace-071c-11e7-8e0c-a0a3580bfd34.png)
After refresh
![image](https://cloud.githubusercontent.com/assets/1945230/23830837/85107610-071c-11e7-85e5-f415fb11ddfc.png)

**Comment by ducdhm** [comment]
Fixed!
