### ISSUE TITLE
Points removing cause strange bug with doubling records on the screen

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#2992]
I've checked one record and push remove
![image](https://cloud.githubusercontent.com/assets/1945230/23830880/733dcc02-071d-11e7-94d7-1f9663b13729.png)
It's removing record ok, but doubling the remain ones.
![image](https://cloud.githubusercontent.com/assets/1945230/23830884/8da06186-071d-11e7-83a1-2c31ac2d31ec.png)
Refresh heals it

**Comment by ducdhm** [comment]
Fixed!
