### ISSUE TITLE
Point bucket names are not validated when creating

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#2994]
There is a possibility to create many buckets with same names. Not sure if it's correct.
![image](https://cloud.githubusercontent.com/assets/1945230/23830920/7142b1e6-071e-11e7-8352-a090d65d2e01.png)

**Comment by bradmac** [comment]
@Uafinder having the same **title** is ok, as long as the physical name is different for each.

**Comment by Uafinder** [comment]
Ok, understood
