### ISSUE TITLE
Manage points search issues

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#2995]
1. Searching find nothing... i've tried to search by user name, tag, points amount...no luck
2. Strange thing, when i'm searching i doing following steps:
a) enter some text into search field
b) wait for a second to allow context searching if it exists
c) if it is not exists, i press Enter to start searching
d) 
![image](https://cloud.githubusercontent.com/assets/1945230/23831016/b279e038-0720-11e7-90de-8fe35cda41b8.png)
It finds nothing, search complete message appears, but Kademi logo loading still blinking and it doesn't stops.
One more, when Pop-up message "Search complete" appears, Search field is locked and backspace button causes going to the previous page. It making me mad :)

**Comment by bradmac** [comment]
@Uafinder can you provide a link to the page you're testing on?

**Comment by Uafinder** [comment]
http://kademi.admin.kademi.us/rewards/points/

**Comment by bradmac** [comment]
@Uafinder it searches on the orgid if using team points, otherwise user's first name and last name

**Comment by Uafinder** [comment]
Looks ok right now, probably indexing probs.
