### ISSUE TITLE
Points allocation rule: Date started is bigger that finish date by default

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#2996]
![image](https://cloud.githubusercontent.com/assets/1945230/23833282/eb003558-074b-11e7-80c7-3ac63df7ddcd.png)

**Comment by bradmac** [comment]
@tuzzmaniandevil please add validation

**Comment by tuzzmaniandevil** [comment]
When creating a new rule, it was using the wrong dates :-) That's why it was swapped
