### ISSUE TITLE
Points allocation rule: delete button without selecting checkboxes causes no message

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#2999]
![image](https://cloud.githubusercontent.com/assets/1945230/23833593/dcf4cdf2-0750-11e7-8aa7-16f61fefdd97.png)
For example here it is present
![image](https://cloud.githubusercontent.com/assets/1945230/23833643/38bfe180-0751-11e7-9b84-dfe1eb733c9e.png)
The same thing with products page:
![image](https://cloud.githubusercontent.com/assets/1945230/23833673/866b7886-0751-11e7-8503-2a9ba0086bab.png)

**Comment by ducdhm** [comment]
Fixed!
