### ISSUE TITLE
Manage points: no pages, there is no possibility to review points

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#3001]
After some count of points they become not appearing on the page. There is no chance to review a full list.
Also when you delete some points, hidden records does not appear. Only clearing cache resolve last problem.
before clearing cache:
![image](https://cloud.githubusercontent.com/assets/1945230/23834132/e5dfa92e-0759-11e7-8228-ee18fb348aa0.png)
After clearing cache:
![image](https://cloud.githubusercontent.com/assets/1945230/23834143/0bb27c30-075a-11e7-9996-fe81330a1ce3.png)

but after refreshing records hiding again

**Comment by bradmac** [comment]
@Uafinder i think we need to see the account you're looking at. Can you please provide a link?

**Comment by Uafinder** [comment]
Just re-check it again... looks my browser gone rogue...
Will keep an eye on it

**Comment by Uafinder** [comment]
Well, something wrong here.
I add some records, and wanna to debit some points. Complete debit operation but it doesn't appear, even after refresh.
http://vladqasand.admin.kademi.com.au/rewards/points/
vladadm@mailinator.com
