### ISSUE TITLE
Visual bug dashboards menu

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#3003]
When dashboards menu activated manage websites menu is highlighted
![image](https://cloud.githubusercontent.com/assets/1945230/23835222/312fbf10-076c-11e7-812a-d2c3b2739097.png)

**Comment by tuzzmaniandevil** [comment]
The wrong menu item was being set active

**Comment by Uafinder** [comment]
What do you mean?

**Comment by tuzzmaniandevil** [comment]
Its fixed ;-)

**Comment by Uafinder** [comment]
![image](https://cloud.githubusercontent.com/assets/1945230/24081023/603029ca-0cb3-11e7-86ca-dc271118ade0.png)
Not highlighted

**Comment by tuzzmaniandevil** [comment]
Ahh I was missing an "s" haha

**Comment by Uafinder** [comment]
Yup, looks ok
