### ISSUE TITLE
Incorrect message while saving promotion

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#3007]
![image](https://cloud.githubusercontent.com/assets/1945230/23870850/a0b8e14e-0830-11e7-8cd1-e18ca5797909.png)
1. Create a new promotion.
2. Enter something
3. Push save

**Comment by bradmac** [comment]
@Uafinder this is probably a config problem in your account. Can you please provide a link?

**Comment by Uafinder** [comment]
http://vladqasand.admin.kademi.com.au/rewards/promo1/#details-tab

**Comment by bradmac** [comment]
Fixed for that account. Needed to have the formBuilder lib installed manually, which is a known issue with dependencies.

**Comment by bradmac** [comment]
Fixed problem with installing dependencies :)
