### ISSUE TITLE
Cannot create admin domain for Org

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3015]
http://rootorg.admin.kademi.com.au/organisations/Nesst/edit

Adding the admin domain Nesst creates a NULL alert

![image](https://cloud.githubusercontent.com/assets/2201340/23897442/4c856846-0901-11e7-90ea-f87c09b1d5db.png)

**Comment by bradmac** [comment]
worked fine for me

**Comment by paddyow** [comment]
Ahhh ok so it's when you use caps in the admin domain! Has to be all lowercase.
