### ISSUE TITLE
Signup details absent

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#3016]
![image](https://cloud.githubusercontent.com/assets/1945230/23919839/1ee58010-0901-11e7-8b28-fffba367e758.png)

**Comment by bradmac** [comment]
Should be displaying custom fields

**Comment by hoanglinhlan** [comment]
hi @gonzalon 
current, it still doesn't show signup detail
I have a group with custom field: http://lantest3.admin.kademi-prod.com/groups/03c5secom-manage/
and some profile registered on this group (http://lantest3.admin.kademi-prod.com/signupSearch )
however, after I registered, there profile are not in this group and in recent signup page, it doesn't show any data when I click to a row

**Comment by gonzalon** [comment]
@hoanglinhlan 
After registering the user it should be approved, for that you have to be in the role "User Administrator".
Once the user is approved its in the right group, and you can see the data of the extra fields.
