### ISSUE TITLE
Remove decimal places from cart checkout 

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#3018]
Profile
http://lan-test.admin.kademi.com.au/manageUsers/41267184/#pointsBucketTab-tab
site: http://c5s.kademi.com.au/checkout/
![image](https://cloud.githubusercontent.com/assets/20508726/23958192/df36ba00-09d3-11e7-891d-d4fa8d96dd32.png)

**Comment by ducdhm** [comment]
@bradmac What do you think about this issue? I dont think it's bug and need to do something.

**Comment by bradmac** [comment]
I think we should remove decimal places, because points will always be whole numbers

**Comment by bradmac** [comment]
Points in Kademi are always integers, so it would be good to change this to not have decimal points. Note that this is different to ecommerce stores which must allow decimal points

**Comment by bradmac** [comment]
But moving to a later milestone, not urgent

**Comment by hoanglinhlan** [comment]
it's still showing decimal number

**Comment by tannguyen3489** [comment]
@hoanglinhlan : the reason is the lib out updates. I ready to upgrade it for you, please check

**Comment by hoanglinhlan** [comment]
passed
