### ISSUE TITLE
Application settings button bug

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#3023]
When you push settings button to the right of application name screen is become smoother and pop-up window  doesn't showing.
Eway Payment App
Braintree Payment App
SwipeHQ Payment App
Google Recaptcha
Tracking
Lead management
![image](https://cloud.githubusercontent.com/assets/1945230/24082394/9918ae5a-0ccd-11e7-908b-a7d843c5d6bf.png)

**Comment by ducdhm** [comment]
Need to deploiy!
