### ISSUE TITLE
Incorrect message when delete data series

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#3027]
![image](https://cloud.githubusercontent.com/assets/1945230/24163575/a9bee11e-0e73-11e7-8bc3-abebcf4c6db8.png)
1. Delete Data Series
2. Watch on the incorrect message
3. Looks like deletion went wrong, but when you refresh page you will see that it has been deleted.
http://vladqasand.admin.kademi.com.au/sales/
vladadm@mailinator.com

it looks appears only when indexes are not created...

**Comment by ducdhm** [comment]
It's working normally! Seem like it's already fixed in other issue
