### ISSUE TITLE
Warning when creating a debit which will make a balance negative

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3032]
When an administrator creates a points debit, this currently allows an amount greater then the points balance, which can result in a negative balance. 

This does need to be allowed, but our client has asked if a warning can be displayed, and then only proceed with the debit if the user accepts.

Needs to be integrated with the points tab on the manage user page, and also the manage rewards page. When running locally this is:
http://localhost:8080/manageUsers/2/#pointsBucketTab-tab
http://localhost:8080/rewards/points/

**Comment by bradmac** [comment]
Hi @mkhoudary can you please implement this?

**Comment by mkhoudary** [comment]
Done..
Now checking points balance for the user in the given reward:
![image](https://cloud.githubusercontent.com/assets/3704174/24226286/447e2624-0f6e-11e7-8052-713bd2aca0ee.png)

Pressing cancel cancels this operation.

Approving this request gives a result similar to: 
![image](https://cloud.githubusercontent.com/assets/3704174/24226340/94a77cae-0f6e-11e7-9469-950517b190f5.png)

**Comment by bradmac** [comment]
:+1:
