### ISSUE TITLE
Content editing enhancements for products

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3033]
- Make a new app setting to control whether the product management page will use keditor or the current ckeditor
- The current content field (Product.notes) should use the selected editor
- Move this to a new tab
- Add a new content editor tab for the new content field (Product.brief), which will also use the selected editor

**Comment by bradmac** [comment]
@ducdhm I've added a setting to select the editor, from the ProductsApp settings on the applications page

This is used in the product details page:
```
                    #set( $editor = $page.editor )
                    <script type="text/javascript">
                        var editorType = "${editor}";
```

**Comment by ducdhm** [comment]
UI is done. Just an issue with serverside. After saving, all classes of div is removed
