### ISSUE TITLE
Cannot edit promotion text

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3034]
http://zoetis.admin.kademi.com.au/rewards/guidair-double-points/#rewardContent-tab

- When editing text I get no font options
- Text changes do not save

![image](https://cloud.githubusercontent.com/assets/2201340/24184929/91da9208-0f24-11e7-9c0b-d2f5529b16cd.png)

**Comment by ducdhm** [comment]
You can test on Zoetis now

**Comment by paddyow** [comment]
Boom works!
