### ISSUE TITLE
Sending email interface

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3037]
When a group email is sending and we show the below on the email list page, it looks like something has gone wrong, but it has not.
![image](https://cloud.githubusercontent.com/assets/2201340/24225464/bc9bb6d0-0fb4-11e7-9928-2932fb9bde24.png)

Change the colour of the circle to Kademi blue, and make the icon a spinning disc http://fontawesome.io/icon/circle-o-notch/ 

When you navigate to the email page itself:
![image](https://cloud.githubusercontent.com/assets/2201340/24225522/110ac4fe-0fb5-11e7-88ca-b6dd8616945f.png)

I think we move the 'Email sending' box, which looks like a button, but isnt, and move it into the body of the page in a larger Kademi blue circle with spinning disc http://fontawesome.io/icon/circle-o-notch/

![image](https://cloud.githubusercontent.com/assets/2201340/24225566/4769ec14-0fb5-11e7-8494-f54325d66e10.png)

**Comment by tannguyen3489** [comment]
it was fixed.

![screenshot_2017-07-28_14-52-05](https://user-images.githubusercontent.com/1665005/28707907-605ad730-73a4-11e7-979e-b0f3fb30fd02.png)
![screenshot_2017-07-28_14-51-47](https://user-images.githubusercontent.com/1665005/28707909-61792504-73a4-11e7-8610-32b509ea319f.png)
