### ISSUE TITLE
Review SCORM importing

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3049]
- Please create a website on bootstrap theme (bs 336, ie with components) 
- enable the elearning app and create a program, course and module
- find a SCORM 2004 file to import, maybe from here - http://scorm.com/scorm-explained/technical-scorm/golf-examples/
- attempt to import into your module
- ensure the imported module works correctly when viewed in the front end site

**Comment by diegoperezn** [comment]
Remember to change the Length of the "PROP_VALUE" column to 1024 in the "MODULE_STATUS_FIELD"
