### ISSUE TITLE
Update points buckets so points are only rewarded to the target group if selected

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3059]
http://zoetis.admin.kademi.com.au/points-buckets/

This will mean regardless of if module rewards points, or a journey, the points will only be rewarded to profiles in a group when a group is selected.

![image](https://cloud.githubusercontent.com/assets/2201340/24488505/07e1a1aa-1563-11e7-9449-34c0c1f78eee.png)

**Comment by paddyow** [comment]
@hoanglinhlan please check this update has been pushed to dev.  We need to make sure anyone in the Vets group (who should not also be in the reward group) does not get rewarded any points to their profile via the journeys or modules rewards we have setup.

**Comment by hoanglinhlan** [comment]
passed
