### ISSUE TITLE
Update rewardstore lib

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#3060]
All updates will applied in new version for rewardstore-lib

 * Add Point Range List component
 * Add Product Search component
 * Update Category Page and Reward Store Page same layout with Nesst project
 * Add new component which contains Image, Point and Add to Cart button same as Nesst

**Comment by anhnt** [comment]
> Add new component which contains Image, Point and Add to Cart button same as Nesst

Done as rewardProduct component

**Comment by anhnt** [comment]
> Update Category Page and Reward Store Page same layout with Nesst project
done

**Comment by anhnt** [comment]
done 
![image](https://cloud.githubusercontent.com/assets/735555/25036968/cd140242-2120-11e7-8ada-aabef5af0386.png)

**Comment by anhnt** [comment]
oh, need to implement sorting feature

**Comment by anhnt** [comment]
added product sorting component
