### ISSUE TITLE
Password  check message is not clear

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#3061]
Password error message is so generic (at least 6 characters alpha numeric) and if the rules are customized clients might not know exactly what to do, customizing error message would be a good enhancement

**Comment by ducdhm** [comment]
We already have option for customizing password error message. Please look at jquery.forms options
```
...
    passwordErrorMessage: 'Your password must be at least 6 characters and it must contain numbers and letters',
...
```
