### ISSUE TITLE
Add mult-lingual support for product library

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3069]

**Comment by bradmac** [comment]
![image](https://cloud.githubusercontent.com/assets/826458/24575228/481d3ee2-16fc-11e7-8744-fb2badb2756a.png)

**Comment by bradmac** [comment]
![image](https://cloud.githubusercontent.com/assets/826458/24575234/7b43a2d4-16fc-11e7-9c54-337f6ff6c776.png)

**Comment by bradmac** [comment]
Then enter the translated text in the popup. This bit is currently a bit crap.

**Comment by bradmac** [comment]
To support translations on the server side
- implement Translatable on your class, this could be a hibernate entity or a Resource class. 
- Note that the default implementation of getSourceType is the simple name of that class, you might want to override it
- in the example below we're using the product name rather then id, to allow translations to be portable between platforms. Decide for yourself as appropriate

```
@Docs
public class ProductFolder implements Translatable {
    @Override
    public String getSourceType() {
        return Product.class.getSimpleName();
    }

    @Override
    public String getSourceId() {
        return product.getName();
    }
```

To make an input editable, 
- set the translatable class to cause the framework to display the translate button
- set the data-source-field attribute on the input, to tell the framework what property it is
- set data-source-type atttribute either on the input or the form. This needs to be the same as returned by your Translatable implementation
- set the data-source-id attribute either on the input or the form
```
<form role="form" data-source-type="Product" data-source-id="$page.name">
    <div class="form-group">
        <label class="col-sm-2 control-label" for="title">Title</label>
        <div class="col-sm-10 col-lg-4">
            <input type="text" class="form-control required translatable" name="title" data-source-field="title" value="$page.translate('title')" />
        </div>
```

**Comment by bradmac** [comment]
To display a translated field, simply use the translate method on your Translatable implementation. Eg
```
Title: $page.translate('title')
```

Note that in this case it is ProductFolder which implements Translatable. You might choose to implement it on the hibernate class instead

**Comment by bradmac** [comment]
@mkhoudary  and @ducdhm can you guys please review and comment?

**Comment by mkhoudary** [comment]
@bradmac I ran through the backend code, it is good.. Following are my comments:
1- We wouldn't need English to be one of the translations since English will be set as the value in the bean actual fields, unless if you wish to leave bean actual fields for the default language being English, Arabic, French... etc.
2- We shall consider clean up when an entity is deleted, to remove all its translations.
3- We shall consider adding translation backup/restore support.
Other than this it will be a very good start.

**Comment by bradmac** [comment]
One reason for including English is that in some cases a client might find that an easy way to customise default text. Ie I'm thinking we use this framework for admin labels as well as user managed content.

But i would like languages to be dynamically configured, the hard coded list is just a shortcut.

Agree on all points. I'll create issues to action..
