### ISSUE TITLE
Improve translation editor

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3070]
Extension to this - https://github.com/Kademi/kademi-dev/issues/3069#issuecomment-290903692

Please allow editing translation text in a modal. This should load the existing translation text from the translation service at /translations

The input used in the modal should match the target, ie original field. So please check the type of the target and create the corresponding input
- text input (eg 1 line)
- text area (eg multiline)
- html editor (ckeditor, not keditor)

We will handle keditor translation in a separate issue

**Comment by ducdhm** [comment]
UI for textbox
![textbox](https://cloud.githubusercontent.com/assets/1289631/24651238/4bd47c6e-1957-11e7-86b3-5d1e79179d26.png)
![textbox_modal](https://cloud.githubusercontent.com/assets/1289631/24651239/4bd757ae-1957-11e7-9fab-7c94d43dbdbb.png)

**Comment by ducdhm** [comment]
UI for textarea
![textarea](https://cloud.githubusercontent.com/assets/1289631/24651330/9cda3fcc-1957-11e7-85d0-429d036baac7.png)
![textarea_modal](https://cloud.githubusercontent.com/assets/1289631/24651331/9cdecdf8-1957-11e7-8467-55ca2d9f87c3.png)

**Comment by ducdhm** [comment]
UI for CKEditor
![ckeditor](https://cloud.githubusercontent.com/assets/1289631/24651346/a7e6eaaa-1957-11e7-9863-ce984ffa884d.png)
![ckeditor_modal](https://cloud.githubusercontent.com/assets/1289631/24651347/a7e9b05a-1957-11e7-8eac-08140975ba7c.png)

**Comment by bradmac** [comment]
@ducdhm can you remove the word "translate". Otherwise we'll need to translate it :)

Just an icon is cool.

**Comment by ducdhm** [comment]
Done!
