### ISSUE TITLE
Add preferred language to Profile

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3071]
User's profile page should allow selection of a preferred language, selected from the TranslationService.

This should be captured to a new column on Profile.

Registration forms should capture the selectedLangCode and set it as the preferred language

**Comment by mkhoudary** [comment]
I suggest that we create a new entity for user properties, so the profile entity is kept in the same structure, and also we allow other future properties for users to be specified dynamically.

If we decided to keep it in the Profile class I will need access to io.milton.vfs.db.Profile.

**Comment by bradmac** [comment]
It's in the kademi vfs project. I suggest adding it to profile
