### ISSUE TITLE
Add language selection to menu component

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3074]
Extension to 
- https://github.com/Kademi/kademi-dev/issues/3073
- https://github.com/Kademi/kademi-dev/issues/3069#issuecomment-290903692

Front end websites need to allow users to select a language, please add a setting to component config to allow display of language selector, and to display languages from TranslationService.getLanguages if selected. When selected should be recorded in a cookie, the same as for the admin.

**Comment by ducdhm** [comment]
UI is done. Added in menuComponent

**Comment by ducdhm** [comment]
Setting in contentEditor:
![frontend](https://cloud.githubusercontent.com/assets/1289631/24700154/79299e1e-1a20-11e7-99bb-95d29dd38eb9.png)

In Front-end site
![setting](https://cloud.githubusercontent.com/assets/1289631/24700155/792c7b66-1a20-11e7-8192-216e2b3339c8.png)
