### ISSUE TITLE
Implement support for 2 factor authentication

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3098]
- initially in admin only
- based on google authenticator
- initially only applied to users who choose to use it (ie no group policy)

Consider using this:
https://github.com/j256/two-factor-auth

Tasks
- First integrate into the admin profile page, so that a user can connect their profile to a 2FA device
- On login, check if the profile has a 2FA credential set. If so display the 2FA UI as second step of login

You will need to work in these files
- ManageUserPage.java
- templates/apps/admin/profile.html

**Comment by gonzalon** [comment]
@bradmac I ended just changing 
milton-server-ce/src/main/java/io/milton/http/http11/auth/LoginResponseHandler.java

But I dont have access to that repo to push a new branch

**Comment by bradmac** [comment]
please just fork it and send a pull request

**Comment by gonzalon** [comment]
@bradmac 
https://github.com/Kademi/kademi-dev/tree/2fa-implementation
https://github.com/Kademi/kademi-platform/tree/2fa-implementation
https://github.com/miltonio/milton2/pull/88  (Isn't building. Should I look this?)

**Comment by bradmac** [comment]
OK, I've had a look at the pull request and we dont want to do it this way.

Milton does not have 2FA, so the respondJson2FA method should not be part of Milton. Instead, just create a Kademi implementation of ResponseHandler and inject that instead of the default implementation

**Comment by gonzalon** [comment]
I did the change we speak yesterday, but I found another issue.

If we set the dependency for "KademiLoginResponseHandler" to "KademiHttpManagerBuilderEnt" hrough Spring without args.

Then we get a NullPointerException when is trying to set the Buffer and other properties in the init method.

Here:
```
		if (enableCompression) {
			final CompressingResponseHandler compressingResponseHandler = new CompressingResponseHandler(webdavResponseHandler);
			compressingResponseHandler.setBuffering(buffering);
			outerWebdavResponseHandler = compressingResponseHandler;
			showLog("webdavResponseHandler", webdavResponseHandler);
		}
```

I rolled back those changes and in the afterInit method Im trying to set the dependencies by hand (Not a very nice solution!! 👎 ):

```
    @Override
    protected void afterInit() {
        super.afterInit();
        LoginResponseHandler lrh = (LoginResponseHandler) this.loginResponseHandler;
        KademiLoginResponseHandler klrp = new KademiLoginResponseHandler(lrh);
        klrp.setExcludePaths(loginPageExcludePaths);
        klrp.setLoginPage(loginPage);
        this.loginResponseHandler = klrp;
        this.outerWebdavResponseHandler = loginResponseHandler;
        this.webdavResponseHandler = klrp;
        webdavResponseHandler = new DefaultWebDavResponseHandler(webdavResponseHandler, resourceTypeHelper, propFindXmlGenerator);
        log.info("Wrapping the Login Response Handler with {}", KademiLoginResponseHandler.class);
    }
```

But now Im getting this in the console:

> INFO  io.milton.http.ResourceHandlerHelper  - authorisation failed. respond with: io.milton.http.http11.auth.LoginResponseHandler resource: io.milton.cloud.server.apps.orgs.OrganisationRootFolder

**Comment by bradmac** [comment]
Tested with Authy android app - https://play.google.com/store/apps/details?id=com.authy.authy&hl=en

**Comment by bradmac** [comment]
Starting by enabling 2FA on your profile

![image](https://cloud.githubusercontent.com/assets/826458/25300113/70dbe950-274b-11e7-8da0-6e45e90a3fd1.png)

**Comment by bradmac** [comment]
Then configure your authenticator app (eg Authy or Google authenticator) using the QR code which is displayed on the profile page:

![image](https://cloud.githubusercontent.com/assets/826458/25300129/c0c2abd4-274b-11e7-8456-12283d4a4929.png)

Then logout, and login using your normal username and password

The system will display a modal to enter the 2FA key. Get this number from your authenticator app (eg Google Authenticator or Authy)

Enter the 2FA key and you will be logged in.

**Comment by hoanglinhlan** [comment]
passed
