### ISSUE TITLE
Login to admin fails with Safari

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#31]
Reported by Cynthia:

Using Safari (Version 7.0.6 (9537.78.2)), I can’t login on HealthHub (admin panel). The error is: 
[Error] Failed to load resource: the server responded with a status of 400 (Bad Request) (admin.w6rb.olhub.com, line 0)
[Error] SyntaxError: Invalid character: '\0' (jquery.user.js, line 1)
[Warning] Invalid CSS property declaration at: ; (main.css, line 1398)
[Warning] Invalid CSS property declaration at: ; (main.css, line 1411)
[Warning] Invalid CSS property declaration at: \* (main.css, line 4507)
[Error] SyntaxError: Invalid character: '\0' (jquery.user.js, line 1)
[Log] ["Fuse init"](common.js, line 199)
[Log] ["fuse.js: make switch"](common.js, line 199)
[Log] ["initFuseModal"](common.js, line 199)
[Error] TypeError: 'undefined' is not a function (evaluating '$(".login").user')
(anonymous function) (admin.w6rb.olhub.com, line 31)
fire (jquery-1.11.0.js, line 3099)
fireWith (jquery-1.11.0.js, line 3211)
ready (jquery-1.11.0.js, line 3423)
completed (jquery-1.11.0.js, line 3453)

**Comment by bradmac** [comment]
Not sure if this is still an issue, but worth checking out.

**Comment by bradmac** [comment]
@Uafinder could you please confirm if this is an issue?

**Comment by Uafinder** [comment]
Looks ok for me. Checked on Safari 6.1 and 7 in browserstack.
