### ISSUE TITLE
bootstrap-upcrop-image should allow user to upload only 1 photo for cropping

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#3104]

**Comment by ducdhm** [comment]
Need for https://github.com/Kademi/client-carters/issues/270

**Comment by n2lose** [comment]
Fixed.

**Comment by ducdhm** [comment]
@n2lose: https://github.com/Kademi/kademi-dev/commit/6c2c934ad29abfd7a2db88f996c6d7c28e57884a?diff=unified

Issues:
 * `fieldName` is removed.
 * Don't need option for maxFiles in upcrop plugin. It should be in mupload plugin
 * `$.size` is not used
 * Please remove unuseded code at line 123
