### ISSUE TITLE
Exclude param for extra field in product href

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#3113]
Step by step to reproduce
 * Login in website as test user: http://nesst.admin.kademi.com.au/manageUsers/44669440/#summary-tab
 * Access Visagiftcard category: http://www.nesstrewards.com.au/nesst-rewards/visaGiftCard/
 * Add one to cart
 * Enter your DOB in popup and save it
 * Checkout your order successfully
 * Go to your profile and check Reward Store History section
 * Click in link to product in Vissagiftcard and you will see param for extra field. Example: http://www.nesstrewards.com.au/nesst-rewards/visaGiftCard/ICNV75/?`param-date-of-birth=13/05/1989`

Issue here is user can't see product image because it sees `param-...` in URL address and display as a variant.

**Comment by ducdhm** [comment]
Need for https://github.com/Kademi/client-2one2f-nesst/issues/73#event-1041281813

**Comment by tuzzmaniandevil** [comment]
Fixed
