### ISSUE TITLE
Update fuse-image and fuse-video plugins

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#3114]
* Use mselect plugin instead of CKEditor dialog

**Comment by ducdhm** [comment]
Need for https://github.com/Kademi/kademi-dev/issues/2421

**Comment by ducdhm** [comment]
In https://github.com/Kademi/kademi-dev/issues/3106, I added pagePath and basePath in config of CKEditor. When you refactory them, you can get these configs by following:

```
CKEDITOR.plugins.add('fuse-image', {
    init: function (editor) {
        flog(editor.config.basePath, editor.config.pagePath);
    }
};
```

**Comment by anhnt** [comment]
done for fuse-image. please continue with video and audio @ducdhm
