### ISSUE TITLE
Outbid trigger does not fire

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#312]
I setup a trigger here http://admin.mercedes.olhub.com/autoEmails/auction-won-alert%281%29/#triggers-tab

Tested 2 accounts, and outbid each user.  However an email was not fired to the user who was outbid.

**Comment by Uafinder** [comment]
Confirm

**Comment by tuzzmaniandevil** [comment]
This has now been fixed.
I have also added 2 attributes, bid and auction. so to get the auction title you can use @{event.attributes.auction.title}
