### ISSUE TITLE
User manage page: cant remove user

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#3128]
1. open this http://3m.admin.kademi.com.au/manageUsers/
2. search for test
3. select first 2 records
4. click "remove" but nothing happen 
same problem with VTL http://vtl.admin.kademi.com.au/manageUsers/?q=test&g&enabled=true#
https://github.com/Kademi/client-2one2f-3M/issues/81

**Comment by bradmac** [comment]
Fixed
