### ISSUE TITLE
Manage products page: Add column ordering and filtering

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3129]
- allow ordering by selecting a column header for these cols (Code, Title, Supplier, Base Cost)
- filtering on supplier from a dropdown list of supplier orgs
- filtering on free text, which will search code and title

**Comment by bradmac** [comment]
@diegoperezn can you please change the search to use the same automatic search used on the manage users page?

Eg see manageUser.js
```
    $('#user-query').keyup(function () {
        typewatch(function () {
            flog('initSearchUser: do search');
            doSearch();
        }, 500);
    });
```

**Comment by diegoperezn** [comment]
Done!
