### ISSUE TITLE
Make shopping cart persistent in DB

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#3142]
This is to replace the current "Cookie" shopping cart. Should work in a similar way.

After checkout is complete, mark ShoppingCart as complete and link to the Cart.

**Comment by tuzzmaniandevil** [comment]
@hoanglinhlan Please give ECommerce a full end-to-end test as I have refactored a fair bit of code and might have missed something in my testing

**Comment by hoanglinhlan** [comment]
**Profile**: https://lan-test.admin.kademi.com.au/manageUsers/48689307/#general-tab
1: in checkout page, I cant remove or decrease/increase product's quantity
2: seem like order detail has unnecessary row
order https://lan-test.admin.kademi.com.au/shopping-carts/48973569/#items-tab
in frontEnd
![image](https://cloud.githubusercontent.com/assets/20508726/25657883/457398b6-302a-11e7-9666-980b5c1ba304.png)
![image](https://cloud.githubusercontent.com/assets/20508726/25657957/9a796ad4-302a-11e7-9afe-ae5b16db8653.png)

**Comment by bradmac** [comment]
Hi @diegoperezn can you please look into the issues @hoanglinhlan found?

**Comment by diegoperezn** [comment]
Ok @bradmac

**Comment by diegoperezn** [comment]
It would be fixed with a lib update.

**Comment by hoanglinhlan** [comment]
passed
