### ISSUE TITLE
Error when deleting a GroupEmail that has an email_job_attachment

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#3145]
When trying to delete a GroupEmail where test emails have been sent it throws an exception that there are still EmailJobAttachments referencing it

**Comment by bradmac** [comment]
@gonzalon this might already be done and wesley forgot to close, can you please check?

**Comment by gonzalon** [comment]
Can't reproduce, seems to be fixed.

**Comment by hoanglinhlan** [comment]
Cant reproduce
