### ISSUE TITLE
Group Registration: Portlet not showing on admin dashboard

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#3146]
Because the portlet isn't showing, So new registrations can be accepted.

This is effecting Swimart, Please notify Patricia Kucukakyuz when fixed

**Comment by bradmac** [comment]
This requires the user admin permission

**Comment by bradmac** [comment]
Please ensure the portlet shows for users who have the Administrator permission

**Comment by hoanglinhlan** [comment]
passed
