### ISSUE TITLE
Reward store Product EDM component

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3149]
We need a component to generate a single product tile for a selected product, with links.

Please see here for an example - http://carters.admin.kademi.com.au/groupEmails/20924171

**Comment by ducdhm** [comment]
Done!

**Comment by hoanglinhlan** [comment]
hi @ducdhm 
https://lan-test.admin.kademi.com.au/manageApps/#installed-tab
please update  rewardstore-lib to version 1.0.1.
current version of this lib is 1.0.0, so I cant find this component in list component

**Comment by ducdhm** [comment]
I have set hash for it. You can test for now!

**Comment by hoanglinhlan** [comment]
1: background is not work 
2: horizontal is not work 
![image](https://cloud.githubusercontent.com/assets/20508726/26535854/74444b6e-445b-11e7-994b-f591c2a54af3.png)

3: showing null page after I entered when I put backgourd color

**Comment by tannguyen3489** [comment]
it was fixed.
