### ISSUE TITLE
Showing error in event page 

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#3152]
Profile: http://lan-test.admin.kademi.com.au/manageUsers/48603785/#general-tab
Precondition: event has not group
Step: 
- Login to c5s site 
- click to open any event
ie http://c5s.kademi.com.au/Calendars/NewYork/abcbcbc
![image](https://cloud.githubusercontent.com/assets/20508726/25515400/883a475a-2c0e-11e7-9bb9-fe269f7d3089.png)

**Note**: 
that error showing after this profile submit attendanced then I remove it in list People attending of event that profile attendanced

**Comment by bradmac** [comment]
Just from the error message, i think that is not related to the change @diegoperezn made

**Comment by bradmac** [comment]
@hoanglinhlan can you please give the steps to reproduce this error on a new event? I think it is probably due to accepting and then deleting an attendance

**Comment by hoanglinhlan** [comment]
@bradmac 
**Profile**: http://lan-test.admin.kademi.com.au/manageUsers/48689307/#summary-tab
**Event**: http://lan-test.admin.kademi.com.au/Calendars/CalendarTest/event#details-tab
current, I cant reproduce it, because I cant submit attendance. When I submit attendance, the system alway showing JSON 
![image](https://cloud.githubusercontent.com/assets/20508726/25526191/afb57808-2c3c-11e7-868b-8242eda95737.png)
 or JSON 
![image](https://cloud.githubusercontent.com/assets/20508726/25526200/b969b634-2c3c-11e7-8cb0-4dae3a0f047a.png)

then this profile still not attendanced

**Comment by bradmac** [comment]
I've just updated calendar-lib, so now that page is appearing and working correctly

**Comment by hoanglinhlan** [comment]
it's work fine now
