### ISSUE TITLE
Dates not displaying on the manage promotion page

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3155]
I have a promotion with start and end dates specified, and I have confirmed through debugging they are correctly saved.

But when i view the manage promotion page no value is being displayed:

![image](https://cloud.githubusercontent.com/assets/826458/25569867/659fb26e-2e72-11e7-8add-ae06afa56859.png)

Here is the generated html:

```
                                <tr>
                                    <td>Choose a start date</td>
                                    <td>
                                        <div class="form-group">
                                            <div class="col-sm-5">
                                                <div class="input-group">
                                                    <input type="text" name="startDate" placeholder="Start date" data-format="DD/MM/YYYY" value="12/01/2016" class="form-control DateTime" />
                                                    <span class="input-group-addon"> <i class="fa fa-calendar"></i> </span>
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
```

**Comment by bradmac** [comment]
Hey @ducdhm looks like datepicker support in kademi is completely busted. I've been trying to get the current datetimepicker working but it just doesnt display the current value.

Can you please look into this as top priority? And please make sure we have a consistent approach used across all kademi screens that need date and datetime pickers.

**Comment by ducdhm** [comment]
I removed moment-timezone and everything is working fine.
