### ISSUE TITLE
Manage website domain name field referencing Olhub

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3156]
http://kademi.admin.kademi.us/websites/themecheck/version1/#panel_details-tab

Should be setup for AWS.

![image](https://cloud.githubusercontent.com/assets/2201340/25573263/0d3f69c4-2e87-11e7-963c-1e22af29065a.png)

**Comment by tuzzmaniandevil** [comment]
I've removed that bit so it now reads:
`If you have your own domain enter it here - eg www.mycompany.com`
