### ISSUE TITLE
Products import wizard

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3158]
For the manage products page - Eg http://localhost:8080/products/

Similar to  https://github.com/Kademi/kademi-dev/issues/3151

**Comment by hoanglinhlan** [comment]
hi @diegoperezn 
1: Cant upload with Category and Supplier
2: Upload file with product's code existed, the system create a new product ( note: the product code is the unique id, we use this field to find the product)

**Comment by diegoperezn** [comment]
Fixed a little bug with an empty value in category column.

@hoanglinhlan Could you give the environment and url you are testing? I was not able to reproduce there errors

Thanks

**Comment by hoanglinhlan** [comment]
hi @diegoperezn 
this is url that I checked and my csv file
[products.zip](https://github.com/Kademi/kademi-dev/files/977976/products.zip)

https://lan-test.admin.kademi.com.au/products/

**Comment by bradmac** [comment]
@diegoperezn a couple of enhancements required to support the acdelco project

1. Create a new column mapping for variants. The variant type should be defaulted to the column heading. If the column text includes a colon, then parse it and use the first part as the variant type. The rest of the part should be split on comma, and these are the variant values

Examples, assuming a variant type of "weight" and values of "010" and "020"
Example 1: weight: 010, 020
Example 2: 010, 020 (would require a column heading "weight")
Example 3: 010 (would require a column heading "weight")

2. Ensure that category importer can make parent/child relationships

**Comment by bradmac** [comment]
Need to refactor to allow support multiple cols for a single DestField

**Comment by tuzzmaniandevil** [comment]
This is now moved to https://github.com/Kademi/kademi-dev/issues/3347
