### ISSUE TITLE
Categories import wizard 

### ISSUE THREAD

**Issue by diegoperezn** [Kademi/kademi-dev#3164]

**Comment by hoanglinhlan** [comment]
https://lan-test.admin.kademi.com.au/categories/
I can import new Category without Name/code and incorrect parentCategory

**Comment by hoanglinhlan** [comment]
hi @diegoperezn 
please fix my comment

**Comment by AlaaKhalaf94** [comment]
When I try with this record
![capture6](https://user-images.githubusercontent.com/26510030/28315582-b3c7b09e-6bc7-11e7-9349-f46ef4d6abc9.PNG)

it shows me that succeeded in inserted 5 rows
![capture4](https://user-images.githubusercontent.com/26510030/28315666-21c102e4-6bc8-11e7-9694-1eb4c7e62712.PNG)

But actually inserted 9 rows, and succeeded in insert a row without Name
![capture5](https://user-images.githubusercontent.com/26510030/28315716-62319a3c-6bc8-11e7-8543-5267f1fc0117.PNG)

https://lan-test.admin.kademi.com.au/categories/

**Comment by gonzalon** [comment]
@AlaaKhalaf94 its fixed now, but please remember to use the "Upload Categories" button. Not the CSV. Thanks!

**Comment by AlaaKhalaf94** [comment]
passed
