### ISSUE TITLE
Outlook doesnt apply global font setting in EDM editor

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#3165]

**Comment by bradmac** [comment]
If the default style doesnt propogate through the whole email, then maybe we can look at injecting the default with templating? The solution which involves setting important! might not be great, if that means we cant set the font on specific components in the EDM

**Comment by ducdhm** [comment]
Issue for Outlook is: it automatically set default font-family for every tables. So we need define font-family for tds which wrap text

**Comment by ducdhm** [comment]
Fixed!
