### ISSUE TITLE
Implement customer facing proposal screen

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3167]
To support customers reviewing and accepting quotes:
- have a resource to display a proposal at /proposals/[proposalid]
- have a component to display the quotes in the proposal and allow selection of a quote and acceptance
- only display if the current user (normally authenticated by an auth token) matches the customer or vendor

The component should
- display each quote in a tile with heading and total amount
- allow selection of a quote which will highlight that quote
- have a button under the quotes which is enabled when a quote is selected, and that submits an acceptance of the quote, if the proposal hasnt been accepted
- if the proposal has already been accepted, display a message to the user

**Comment by bradmac** [comment]
![image](https://cloud.githubusercontent.com/assets/826458/25688667/402d0328-30d5-11e7-83ef-a1398d4c5b5d.png)

**Comment by bradmac** [comment]
@mkhoudary please improve the screen. The layout is in viewProposalDetailsComponent.html

**Comment by hoanglinhlan** [comment]
passed
