### ISSUE TITLE
Quote/Proposal workflow

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3168]
- add a new property to Proposals and Quotes to allow them to be associated with a lead
- add a button to the lead page in LeadMan to create a quote, and connect it to the current lead
- add a link on the quote page to link to the lead
- add links on the lead page to existing quotes
- add a button to the quote page to allow creating a proposal and linking to this quote
- add a button on the quote page to add another quote to the proposal
- update customer and vendor inputs to use the new jquery plugin userFinder

**Comment by bradmac** [comment]
Have added the lead property to Quote and Proposal.

@mkhoudary please update the screen flow in leadman so that the lead is set when these are created

**Comment by mkhoudary** [comment]
Implemented what's necessary to proceed to goal issue..
- add a new property to Proposals and Quotes to allow them to be associated with a lead [Done]
- add a button to the lead page in LeadMan to create a quote, and connect it to the current lead  [Done]
- add a link on the quote page to link to the lead [Postponed, Can wait]
- add links on the lead page to existing quotes  [Done]
- add a button to the quote page to allow creating a proposal and linking to this quote  [Done]
- add a button on the quote page to add another quote to the proposal  [Done]
- update customer and vendor inputs to use the new jquery plugin userFinder [Postponed, Can wait]

**Comment by bradmac** [comment]
Please add a link from the quote page back to the lead page, if related to a lead

**Comment by mkhoudary** [comment]
Points 1 and 3 are done.. point 2 needs investigation

**Comment by bradmac** [comment]
hey @mkhoudary we definitely dont want brokers to have to explicitly create a proposal. Just create the proposal when the quote is created from this screen.

**Comment by mkhoudary** [comment]
I know @bradmac it is just that customer and vendor are set to quote after creation, so when a quote is created for the first time I don't have the vendor, while I can get the customer from the lead.

I will manage that and let you know.

**Comment by bradmac** [comment]
Hey I just realised there is a mistake with Proposal. It has a vendor field, but each quote will be from a different vendor.

Can you remove that from Proposal, then that makes it easier

**Comment by mkhoudary** [comment]
Yes.. that's exactly what I wanted to discuss.. problem solved this way :-)

**Comment by mkhoudary** [comment]
Point 2 is done

**Comment by mkhoudary** [comment]
@bradmac if you pulled on an older version you need to drop the Vendor Column:
alter table proposal drop column vendor
To get this working.

**Comment by hoanglinhlan** [comment]
passed
