### ISSUE TITLE
Implement proposal acceptance goal

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3169]
Depends on:
https://github.com/Kademi/kademi-dev/issues/3167
https://github.com/Kademi/kademi-dev/issues/3168

Create a new goal which is achieved when a quote associated with the lead is accepted

**Comment by bradmac** [comment]
Created AcceptQuoteGoal in PaymentApp

**Comment by bradmac** [comment]
@mkhoudary this goal has been implemented. Please integrate into itsinsured. Note that it requires the lead on the quote/proposal to match on, so you will need to complete #3168 to be able to test it

**Comment by mkhoudary** [comment]
This can be tested now

**Comment by hoanglinhlan** [comment]
passed
