### ISSUE TITLE
Add count property to GroupInWebsiteFolder

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#317]
The Waza Petition website has a petition form and displays a count of the number of signers. Each submission is a contact request managed through the contact us app.

Currently the count displays a count of contact requests, but that means it shows duplicates.

They have asked if we can somehow display a total which does not include dups. The simplest way to do this is to display the count of members in the group that contacts get added to. But there is currently no API on the GroupInWebsiteFolder

So please add a countOfMembers property, and then notify Jason

**Comment by skwidge** [comment]
Property added, committed and pushed up to master repository. It will go out with next new build.
