### ISSUE TITLE
Unnecessary field in organisation manager page

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#3176]
https://lan-test.admin.kademi.com.au/organisations/
what's mean of textbox name?. I just put an organisation's name then enter but nothing happen
Please remove that field

**Comment by bradmac** [comment]
Looks like its because that cell has id="orgId", and i guess the orgFinder is setup to automatically convert that id.

@ducdhm if thats the case i think we should use a special class

**Comment by ducdhm** [comment]
Fixed!
