### ISSUE TITLE
web page - content editor: Cant see list container and list component 

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#3177]
http://version1.c5s.kademi.com.au/contenteditor?fileName=p2704.html&miltonUserUrl=/users/lan&miltonUserUrlHash=f09c7816-5608-47f3-bbb6-561e9779d958:j4k18P9PVnBf63nENBUmjg2tI_8

![image](https://cloud.githubusercontent.com/assets/20508726/25698427/0567eed8-30e9-11e7-9cdf-189fa378f727.png)

**Comment by bradmac** [comment]
I think your libs probably need to be updated. Please check with Anh or Duc

**Comment by anhnt** [comment]
fixed by upgrading bootstrap theme
