### ISSUE TITLE
Creating and editing webpage templates

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3179]
When wanting to update my website I intuitively went to edit webpages, but the pages I needed to update were not available, instead I had to navigate to Manage Websites, then tab to themes.

As a task, I want all my webpages and templates in one place so I can build my website or webapp without having to navigate to other parts of the admin console.

See example below.  The website pages and templates should be on the same page.

![image](https://cloud.githubusercontent.com/assets/2201340/25728573/57e4e780-3173-11e7-9a6d-31c823fd465a.png)

**Comment by bradmac** [comment]
Not the same page. But we should have a Manage Templates page beside Edit Web pages

**Comment by bradmac** [comment]
OK, so what we want is this:
- update managePages.html
- when being viewed in the root of a website, display 2 columns, Pages and Templates
- the Pages column should show pages (as currently) and also folders (but not /theme)
- clicking a folder opens the folder in managePages.html, which should display as per the current page only layout (ie no templates)
- the Templates column should show the list of templates currently displayed on the theme tab of website manager
- also add a link to the website manager somewhere, maybe the button bar above the pages tab

**Comment by paddyow** [comment]
We also need to add the Rewardstore dashboard template to the mix, as currently it is not available from the list.

**Comment by anhnt** [comment]
done

**Comment by bradmac** [comment]
Hi @anhnt please make a couple of changes

- when being viewed in the root of a website, display 2 columns, Pages and Templates. Not tabs. We want the templates to be obvious to the user
- do not show templates on sub folders. These should only be displayed on the root of the website

**Comment by anhnt** [comment]
done

**Comment by anhnt** [comment]
Templates column content will be hidden when users drilling down inside subfolders

**Comment by hoanglinhlan** [comment]
passed
