### ISSUE TITLE
Allow overriding freight cost in reward stores

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3180]
A client will have multiple reward stores using a single product library, each reward store will be for a different country.

The cost to ship a product will vary depending on the country, but currently the freight cost can only be set once in the product library.

Currently we have the ability to override some values for a product in a reward store, please add a freight cost field:

![image](https://cloud.githubusercontent.com/assets/826458/25729753/8e185220-318b-11e7-91ba-33203c32a1b5.png)

**Comment by hoanglinhlan** [comment]
click to config button, it's showing error 
![image](https://cloud.githubusercontent.com/assets/20508726/25841014/8d5d79b0-34c8-11e7-9077-9fd4bb554287.png)

**Comment by tuzzmaniandevil** [comment]
@hoanglinhlan I don't see that error, I tested locally and seems fine

**Comment by hoanglinhlan** [comment]
@tuzzmaniandevil 
current, it's working wrong. 
Product: http://lantest1.admin.kademi-prod.com/products/63367/#panel_details-tab (by price = 1100)
freight in store is 20: http://lantest1.admin.kademi-prod.com/reward-store/c5s-business/?q=&l=&all=true#products-tab
by price = 1020
![image](https://user-images.githubusercontent.com/20508726/27275414-80bdafb4-5501-11e7-8f6f-4866577426af.png)

but in frontEnd, it's showing 0pts
profile to login: http://lantest1.admin.kademi-prod.com/manageUsers/69705/#general-tab

**Comment by tuzzmaniandevil** [comment]
That's because the margin, GST, Points Multiplier and Client Margin are all 0, Fixed with #3424 
I uptaded QA and checked it

**Comment by hoanglinhlan** [comment]
passed
