### ISSUE TITLE
Ability to create an organisation when creating a profile

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3189]
Often our users want to create a new contact, and to create a new organisation and link the new user to it at the same time. 

So please update the new user form to allow either selecting an existing org (default) or adding a new one. 

When adding a new organisation allow these fields
- org Id
- title
- org type (from dropdown)

![image](https://cloud.githubusercontent.com/assets/826458/25785462/070f74b0-33d5-11e7-92ec-0dfc33b628c9.png)

**Comment by bradmac** [comment]
Note that there was a regression error, when selecting an existing org the user was not being added to it. Fixed.

**Comment by hoanglinhlan** [comment]
passed
