### ISSUE TITLE
Components are not rendering in editor view

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3194]
http://reward-store.kademi.us//theme/apps/rewardstore/contenteditor?fileName=rewardStoreCategory.html&miltonUserUrl=/users/patrick-707421&miltonUserUrlHash=7b4c1b22-e44b-4516-a12b-64c2e0b9e707:B_iRIMJL_7K8-2LYpD5-8c7kxMI

![image](https://cloud.githubusercontent.com/assets/2201340/25796963/d1e808ca-341e-11e7-97a7-c8dfaa72182a.png)

Various templates have this problem
http://reward-store.kademi.us//theme/apps/rewardstore/contenteditor?fileName=rewardStoreCategory.html&miltonUserUrl=/users/patrick-707421&miltonUserUrlHash=b826e14e-ff7f-48c5-92e3-215011776f56:iejEBZB9w41skGH3B7xrMjU4Lzk

http://reward-store.kademi.us//theme/apps/rewardstore/contenteditor?fileName=productDetails.html&miltonUserUrl=/users/patrick-707421&miltonUserUrlHash=11f7c044-d56e-4346-b0c9-6acaf74ded80:icxlF1K-q97VG9TVR76xzTxrmOY

http://reward-store.kademi.us//theme/apps/user/contenteditor?fileName=dashboard.html&miltonUserUrl=/users/patrick-707421&miltonUserUrlHash=eeab81db-bc18-45f7-b99d-bb7d59a1126c:Tnp52izzVF55mH83B-jWMZoIYtA

**Comment by anhnt** [comment]
this has been done by @tannguyen3489
