### ISSUE TITLE
Should Keditors RHS menu adopt the current theme?

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3195]
http://reward-store.kademi.us//theme/apps/user/contenteditor?fileName=dashboard.html&miltonUserUrl=/users/patrick-707421&miltonUserUrlHash=69464df4-aebf-4dc0-b2e6-bf793d516d2b:0O0EAXvWqGTJDtCY36bJga5V6AY

For example updating inputs in a theme, if a customer does something really wacky, it might make Keditor impossible to use.  In our case our update to the styles on inputs have made reading inputs difficult where the copy is getting cut off.

![image](https://cloud.githubusercontent.com/assets/2201340/25797240/b6354efc-341f-11e7-864f-8e3c0caf60d3.png)

**Comment by bradmac** [comment]
Yes, this is correct
