### ISSUE TITLE
List entity in reporting site: should not showing child org

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#3196]
https://lan-test.admin.kademi.com.au/reporting/points
https://lan-test.admin.kademi.com.au/reporting/pointsDebit
https://lan-test.admin.kademi.com.au/reporting/smsHistory
when I click to child org in list entity, the system showing error page

**Comment by diegoperezn** [comment]
@hoanglinhlan We decided to remove the select because is not used anymore

**Comment by hoanglinhlan** [comment]
hi @diegoperezn 
why dont we display any value of Points Buckets / Groups and Organisations ?

![image](https://cloud.githubusercontent.com/assets/20508726/26490904/79fe917a-4237-11e7-9912-410863d3fcc5.png)

**Comment by gonzalon** [comment]
@hoanglinhlan note that you are going to need to re index before testing

**Comment by AlaaKhalaf94** [comment]
passed
