### ISSUE TITLE
showing error in category page 

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#3198]
Profie https://lan-test.admin.kademi.com.au/manageUsers/48689307/#general-tab
http://c5s.kademi.com.au/c5s-business/

![image](https://cloud.githubusercontent.com/assets/20508726/25801369/7d3e82b0-3417-11e7-98d7-b3246daa24a6.png)

**Comment by bradmac** [comment]
Hi @hoanglinhlan looks like the search app is turned off. Please enable it for that site.
