### ISSUE TITLE
Showing error when user choose a product what has extra field 

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#3199]
Profile https://lan-test.admin.kademi.com.au/manageUsers/48689307/#general-tab

FrontEnd page: http://c5s.kademi.com.au/c5s-business/

![image](https://cloud.githubusercontent.com/assets/20508726/25833303/71e279fc-349a-11e7-8357-ea2734b2ed9c.png)

**Comment by bradmac** [comment]
I just checked and seems ok. @hoanglinhlan can you confirm if the issue is still active?

**Comment by hoanglinhlan** [comment]
it's not active now
