### ISSUE TITLE
Gift vouchers

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#32]
Build a vouchers app to support issuing and redeeming gift vouchers

Vouchers are provided by a voucher provider
Vouchers are provided to merchants, who will have redeemers (ie front desk staff) and redemption managers
Vouchers are issued, either sold or as a reward, by the voucher provider to customers
Vouchers are redeemed at the merchant from the customers

Kademi can generate vouchers and unique Ids on the server
Or, vouchers and their ID's can be uploaded in a spreadsheet
Allow a template expression to be used for generated Ids
Vouchers to have an expiry date set when vouchers are created
Auditing of all changes, either from admin or redeemers
	
Redemption usually done through a microsite – logged in access only
Redeemers usually user accounts in sub-organisations

Just type in ID to redeem, integrate with bar code scanners in phase2

Statuses can be set according to permissions
 - Pending (redeemer)
 - Redeemed (redeemer)
 - Issued (voucher provider)

Generate PDF (phase2)	
Reverse redemption (redemption manager)
Redemption Dashboard - shows total value by status
Expiry - Should be able to be redeemed even when expired by redeemer with warning
Put notes on voucher

**Comment by bradmac** [comment]
"Redeeming Organisation Field visible to user when marking voucher as Redeemed. Populated with the user’s main Organisation, but with the ability to edit it to another organisation if appropriate."

DONE

**Comment by Uafinder** [comment]
1. When creating voucher type, system allows you to enter Upper case letters in title, but this should be restricted according to the message below.
2. When editing voucher type, system allows you to enter spaces into Name/Code field. Validation doesn't works on spaces.
3. Incorrect help text when editing voucher type.
![image](https://cloud.githubusercontent.com/assets/1945230/5783829/6fe6dde6-9dcf-11e4-9b06-676fbdc7a2a3.png)

Will continue, tommorow

**Comment by Uafinder** [comment]
Resuming:
4. "vouchers and their ID's can be uploaded in a spreadsheet" (c) Brad
There is no option to upload a spreadsheet, only to export.
5. Vouchers export file should have some name. It's hasn't name at all now and name are generates randomly:
![image](https://cloud.githubusercontent.com/assets/1945230/5792341/73471da8-9f1d-11e4-8917-298f93f2316b.png)
6. When you try to allocate a voucher, it gives you fields for "allocated to" and "notes". Help text says us that both fields are optional, but there is a validation on "allocated to" field. It seems that just an error in help text.
![image](https://cloud.githubusercontent.com/assets/1945230/5792356/e5972b82-9f1d-11e4-8854-a9331cbe33c6.png)
7. When you changing status of a voucher it gives you a window which have "allocate" button. I think that it should be renamed to something like "Change status".
![image](https://cloud.githubusercontent.com/assets/1945230/5792373/3e120caa-9f1e-11e4-92d5-1c995c8a3ffd.png)
8. When you change status of a voucher to anything else (not allocated) it writes a string to a history which tells that voucher was allocated.
9. Vouchers sorting is incorrect. Looks like system sorts them by status and then it should sort them by name.
10. When you create a voucher type you prompted to enter Voucher code and Description. After creation Voucher code field become Name\Code field and Description field become a Title field which are displayed on the voucher type table. I think this incorrect. Should be Name\Code there.
![image](https://cloud.githubusercontent.com/assets/1945230/5792419/07f71a5a-9f20-11e4-9be8-3314afdcc556.png)

**Comment by Uafinder** [comment]
Resuming:
11. At the vouchers table "edited by" column is empty.
![image](https://cloud.githubusercontent.com/assets/1945230/5792475/6f19882e-9f22-11e4-900d-833e9fd1e538.png)
12. When you allocate vouchers to users, should be a validation on existed user. Because it can be allocated to non-existed user.
![image](https://cloud.githubusercontent.com/assets/1945230/5792492/d1ec48c4-9f22-11e4-9a84-ecef19dddb44.png)

**Comment by bradmac** [comment]
"When creating voucher type, system allows you to enter Upper case letters in title, but this should be restricted according to the message below." - No, case doesnt matter, users should be permitted to enter any case

**Comment by bradmac** [comment]
"When editing voucher type, system allows you to enter spaces into Name/Code field. Validation doesn't works on spaces." - Fixed

**Comment by bradmac** [comment]
"Incorrect help text when editing voucher type. " - fixed

**Comment by bradmac** [comment]
"4. "vouchers and their ID's can be uploaded in a spreadsheet" (c) Brad
There is no option to upload a spreadsheet, only to export."
 - Moved to seperate issue https://github.com/Kademi/kademi-dev/issues/79

**Comment by bradmac** [comment]
"5. Vouchers export file should have some name. It's hasn't name at all now and name are generates randomly:" - Fixed

**Comment by bradmac** [comment]
"6. When you try to allocate a voucher, it gives you fields for "allocated to" and "notes". Help text says us that both fields are optional, but there is a validation on "allocated to" field. It seems that just an error in help text." - Fixed. Allocated to should be optional.

**Comment by bradmac** [comment]
" When you changing status of a voucher it gives you a window which have "allocate" button. I think that it should be renamed to something like "Change status"." 

- Yes, fixed. Also should not have allocated to field

**Comment by bradmac** [comment]
"8. When you change status of a voucher to anything else (not allocated) it writes a string to a history which tells that voucher was allocated." - Could not reproduce this problem, seems to write correct history for me.

**Comment by bradmac** [comment]
"Vouchers sorting is incorrect. Looks like system sorts them by status and then it should sort them by name." - Sorting by status is correct. The voucher code is usually random so is not useful for sorting

**Comment by bradmac** [comment]
"When you create a voucher type you prompted to enter Voucher code and Description. After creation Voucher code field become Name\Code field and Description field become a Title field which are displayed on the voucher type table. I think this incorrect. Should be Name\Code there."

 - No, this is correct. The name/code field is usually not very meaningful to users, but forms part of the URL for vouchers. The title/description is the user friendly display name

**Comment by bradmac** [comment]
"11. At the vouchers table "edited by" column is empty." - Fixed

**Comment by bradmac** [comment]
"12. When you allocate vouchers to users, should be a validation on existed user. Because it can be allocated to non-existed user."

- Actually no, this is correct. Gift vouchers will normally be sold to people who are not users in our system. The identifier is optional, and if given is anything that might be used to identify the owner, such as drivers license number, phone number, name, email, etc.

**Comment by bradmac** [comment]
"User side (Voucher Redeemer role): any operation on voucher (Redeem, Allocate, Change status) leeds you to error."

 - Fixed

**Comment by bradmac** [comment]
"14. User side: system shows a first letter for status change. Should be complete words "Allocated" and "redeemed""

 - Fixed

**Comment by bradmac** [comment]
"15. User side (Voucher Supervisor role): there is no possibility to change voucher status to anything else. It writes a permission error:"

 - check that the supervisor group also has the VOUCHER_REDEEMER role. If not they wont be able to process redemptions etc

**Comment by bradmac** [comment]
"16. When you check Vouchers page, it shows you any vouchers which are not in Idle status. But, when you doing search via Vouchers dashboard it shows you all vouchers. I'm not sure that it's correct. Should show all vouchers on voucher page."

 - Yes, this is correct. On the vouchers page we show them recently process vouchers because they should be able to quick find and change a redemption they've just processed. But when searching we need them to be able to locate vouchers which have not been redeemed so they can redeem them.

**Comment by Uafinder** [comment]
1. "When creating voucher type, system allows you to enter Upper case letters in title, but this should be restricted according to the message below." - No, case doesnt matter, users should be permitted to enter any case. - So, we need to fix help text, which tells us that only lower case allowed.
2-7. Fixed
8. Seems like this self-repaired when you fix 7. Or something like that.
9,10,12,15,16. Understood
11,13,14. Fixed

**Comment by Uafinder** [comment]
New ones:
1. User side: when you try to allocate a voucher "allocated to" field is mandatory. You told that it should be optional.
2. User side: when you try to push any of voucher status buttons on dashboard it doesn't change status, just open a selected voucher. I think that it's not correct.
![image](https://cloud.githubusercontent.com/assets/1945230/5804817/f62436a8-a011-11e4-8feb-28547b4d0abd.png)

**Comment by bradmac** [comment]
"So, we need to fix help text, which tells us that only lower case allowed." <- Fixed

**Comment by bradmac** [comment]
"1. User side: when you try to allocate a voucher "allocated to" field is mandatory. You told that it should be optional." 
 - Fixed

"2. User side: when you try to push any of voucher status buttons on dashboard it doesn't change status, just open a selected voucher. " 
 - Fixed, i've just removed those buttons from the dashboard, not really required

**Comment by bradmac** [comment]
". There is no possibility to delete vouchers. Nothing is happen when you push delete." <- Fixed

**Comment by bradmac** [comment]
"There is no possibility to delete a single voucher" <- this is not currently a requirement. Vouchers are created in batch (eg 100 at once), and if there is a need to delete it would probably be to delete in batch. But we'll address this at some stage in the future.

**Comment by bradmac** [comment]
"User side: system shows a first letter for status change."
 - Fixed

**Comment by Uafinder** [comment]
All fixed

**Comment by Uafinder** [comment]
Looks ok to me, one small issue:
1. When you editing a single voucher, buttons change their view after status change.
Before changing:
![image](https://cloud.githubusercontent.com/assets/1945230/5822907/c6efa7da-a0e0-11e4-9574-d9cf87c7d401.png)
After changing:
![image](https://cloud.githubusercontent.com/assets/1945230/5822915/db7998d2-a0e0-11e4-9f5c-7c5c4544841e.png)

**Comment by Uafinder** [comment]
I suggest to close this issue and open a separate ones if we find something new, because it begins hard to track changes here.

**Comment by bradmac** [comment]
I think those things are small enough to ignore.

**Comment by Uafinder** [comment]
ok, closing
