### ISSUE TITLE
Certificate problem for 3DN

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#320]
See this certificate HTML preview:
admin.3dn.olhub.com/websites/idhealth-training/website13/programs/prof/pmh1/mod1/cert_3/

It has a header image - "Certificate of Completion" etc

But see the PDF rendered preview:
http://admin.3dn.olhub.com/websites/idhealth-training/website13/programs/prof/pmh1/mod1/cert_3/certificatePreview.pdf

This should be the same, but does not have the header image.

The image path is hardcoded to a full url:
http://admin.3dn.olhub.com/websites/idhealth-training/website12-forums/programs/prof/pmh1/mod1/cert_3/Cert1header.JPG

Its possible that there is a permissions problem which prevents the image being loaded by the PDF renderer.

**Comment by skwidge** [comment]
This was permissions issue, where images should be visible to anonymous users. The case of the image file suffix was the issue. The check now ignores case.

Committed and pushed up to the master repository. This fix will be available with the next release.
