### ISSUE TITLE
Missing product's title

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#3200]
Profile https://lan-test.admin.kademi.com.au/manageUsers/48689307/#general-tab
FrontEnd page: http://c5s.kademi.com.au/c5s-business/
no way to open product page because it's not showing product's title.
![image](https://cloud.githubusercontent.com/assets/20508726/25833344/c5eb6950-349a-11e7-94e8-9cb47c883ceb.png)

**Comment by anhnt** [comment]
cant reproduce
