### ISSUE TITLE
Add pagination to group members page

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3210]
![image](https://cloud.githubusercontent.com/assets/826458/25888792/9d62c93e-35bb-11e7-996b-fe74181e561d.png)

**Comment by gonzalon** [comment]
@bradmac the pagination is done.
do you want to add the filter in the criteria or should keep it in the js?

**Comment by bradmac** [comment]
Hey @diegoperezn could you peer review please?

**Comment by diegoperezn** [comment]
@bradmac for me is ok!

**Comment by bradmac** [comment]
@gonzalon you will need to implement the password filter server side, otherwise the functionality just does not work:

![image](https://cloud.githubusercontent.com/assets/826458/25974905/80c9894e-36ff-11e7-8e3a-0b9ab93b0fad.png)

**Comment by gonzalon** [comment]
@diegoperezn Can you review it please?

**Comment by hoanglinhlan** [comment]
passed
