### ISSUE TITLE
KCRM: Cancel lead shows incorrect modal content

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3213]
1.
![image](https://cloud.githubusercontent.com/assets/826458/25970048/68d17bda-36eb-11e7-88fc-8ea30bf3036c.png)

2.
![image](https://cloud.githubusercontent.com/assets/826458/25970061/79cc07b6-36eb-11e7-8468-eb3d18498661.png)

**Comment by ducdhm** [comment]
Already fixed!

**Comment by hoanglinhlan** [comment]
passed
