### ISSUE TITLE
Client cannot see or use date range picker in admin

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3214]
![image](https://cloud.githubusercontent.com/assets/2201340/25975295/cb5e6a24-36f0-11e7-9831-7b67a5bd601a.png)

Additionally custom date range picker in 2x custom reports needs to be removed so the main Kademi date picker can be used.

http://zoetis.admin.kademi.com.au/gudair-reports/
http://zoetis.admin.kademi.com.au/completions-reports/

![image](https://cloud.githubusercontent.com/assets/2201340/25975352/21e46df8-36f1-11e7-9c5e-0a08f8206146.png)

Information on client browser:

Web Browser and Platform:
Internet Explorer 11 on Windows 7
Their web browser is up to date!

Their web browser's capabilities:
Is JavaScript enabled? 	
Yes
Are Cookies enabled? 	
Yes
Third-Party Cookies? 	
Error - Please try again
Is Flash Installed? 	
Yes - v25.0.0 	Up to date
Is Java Installed? 	
Yes - v7.0 update 45 	Out of date

More info about their system:
IP Address 	
Location 	Australia, Sydney
(Approximate)
Computer Screen 	1680 x 1050 pixels
24 bit
Browser Window Size 	1384 x 786 pixels
"Do Not Track" Setting 	Not enabled or not supported
Detected Addons 	Microsoft Silverlight
Using Tor? 	No

Their web browser's technical details:
Software Type 	Web Browser 	Hardware Type 	Computer
Browser version (full) 	11 	Operating System version (full) 	NT 6.1
Layout Engine 	Trident 	Trident Version 	7.0
Configured Language 	English 	Java version string 	1.7.0_45
Browser GMT Offset 	+10:00 	Device Pixel Ratio 	1
Geo location 	Yes 	Application Cache 	Yes
CSS Animations 	Yes 	HTML5 Video 	Yes
CSS Box Shadow 	Yes 	CSS 3D Transforms 	Yes
Full Screen 	No 	HTML5 Canvas 	Yes
Session Storage 	Yes 	WebGL 	Yes
Device Orientation Detection 	No 	XHR2 	No
CSS Gradients 	Yes 	CSS Transforms 	Yes
Device Motion Detection 	No 	Indexed DB 	Yes
CSS Transitions 	Yes 	CSS Multiple Backgrounds 	Yes
SVG 	Yes 	Local Storage 	Yes
HTML5 Audio 	Yes 	CSS Font Face 	Yes
Their Web Browser's User Agent:

Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko

**Comment by ducdhm** [comment]
It's working normally! @hoanglinhlan also confirmed about it. Will reopen if we see it again
