### ISSUE TITLE
Quote description field

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3216]
This is done directly from the quote page, NOT from the profile + quote button.

Whenever I type in a value in the Description field, and click on another field, it causes the above error to appear.

![image](https://cloud.githubusercontent.com/assets/2201340/25980951/7184891e-3715-11e7-969e-24f7d87b318f.png)

**Comment by mkhoudary** [comment]
Done..

**Comment by hoanglinhlan** [comment]
passed
