### ISSUE TITLE
Journey builder canvas space

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3222]
There is a lot of canvas on the monitor not being used.  Would be great for the canvas to maximise to the clients screen.
 
![image](https://cloud.githubusercontent.com/assets/2201340/25983303/36a3c0b4-3727-11e7-8c67-604a15c7fcc5.png)

**Comment by bradmac** [comment]
@ducdhm we've spoken about this before, the canvas should expand to fill vertical space.
