### ISSUE TITLE
Example data for dynamic components

### ISSUE THREAD

**Issue by tannguyen3489** [Kademi/kademi-dev#3223]
after drag&drop component, the component must show example data for a client.

**Comment by bradmac** [comment]
I just did blogArticleHeaderComponent, which was not displaying the title or date

**Comment by bradmac** [comment]
Also, the pointsActivity component is not displayed well:
![image](https://cloud.githubusercontent.com/assets/826458/26152723/439940f8-3b5c-11e7-9527-9bc8975fb6e4.png)

**Comment by bradmac** [comment]
Fixed:
![image](https://cloud.githubusercontent.com/assets/826458/26152778/8782ba88-3b5c-11e7-9671-04d305fe56b2.png)

**Comment by bradmac** [comment]
@tannguyen3489 can you please also fix the display for these components. Note that we must not ever display template code like $page.title

![image](https://cloud.githubusercontent.com/assets/826458/26152800/a958236e-3b5c-11e7-83a8-45f66d6e17e6.png)

![image](https://cloud.githubusercontent.com/assets/826458/26152811/b5cbc678-3b5c-11e7-9578-e5c2f71c4b48.png)

![image](https://cloud.githubusercontent.com/assets/826458/26152840/dd85f58a-3b5c-11e7-8f3e-bbd8f0ccf20a.png)

![image](https://cloud.githubusercontent.com/assets/826458/26152859/f09613a8-3b5c-11e7-96b8-e22c9cb8877b.png)

![image](https://cloud.githubusercontent.com/assets/826458/26152872/fb3da230-3b5c-11e7-9f5f-51ff35dd416f.png)

![image](https://cloud.githubusercontent.com/assets/826458/26152894/1ab82dce-3b5d-11e7-9d65-ddd0a004cfb1.png)

**Comment by AlaaKhalaf94** [comment]
This is my site to test : http://alaa-test.admin.kademi-prod.com/
This is a KEditor page : http://version1.alaatest01.kademi-prod.com/contenteditor?fileName=newpage01.html

**component : rewardProductDescription**
there are world "$title"
![capture1](https://user-images.githubusercontent.com/26510030/27828220-b6036c90-60c3-11e7-89b8-3a0e50493973.PNG)

**component : rewardStoreCategoriesList**
it hasnt a sample data , it just appear like this 
![capture3](https://user-images.githubusercontent.com/26510030/27828676-078bc5c4-60c6-11e7-81dd-21ffa9f6e52b.PNG)

**component : forumQuestion**
Component is not transferred as a single piece
Divided in two halves
![capture5](https://user-images.githubusercontent.com/26510030/27828972-b762e148-60c7-11e7-977c-1d82c0d8e4a8.png)

**Comment by AlaaKhalaf94** [comment]
passed
