### ISSUE TITLE
Allow uploading forms as part of registration forms

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3226]
We need to support file uploads in registration forms. Please see screenshot below as an example

![image](https://cloud.githubusercontent.com/assets/826458/26038269/d04373d0-3958-11e7-9837-297ab89394dc.png)

To do this:
- Allow configuring an extra field as a file upload field on manage groups (see below)
- Update the registerFormComponent to display a file input for these fields 
- Update ExtraFieldsUtils.storeExtraFields to store uploaded files into the blobstore, and then to set the field value to the file hash (see GroupRegistrationPage line 311)
- Ensure the file can be downloaded on the pending memberships panel (see screenshot below)
- Ensure the file can be downloaded and uploaded on the profile page (screenshot)

Add field form
![image](https://cloud.githubusercontent.com/assets/826458/26038274/0223c6c0-3959-11e7-91e7-a503ab4e7bff.png)

Pending memberships panel
![image](https://cloud.githubusercontent.com/assets/826458/26038297/87e84df8-3959-11e7-945e-3fce81694d84.png)

Profile page custom fields
![image](https://cloud.githubusercontent.com/assets/826458/26038308/a869c688-3959-11e7-8d94-2ca30e306f39.png)

**Comment by diegoperezn** [comment]
@gonzalon Could you review it please?

**Comment by gonzalon** [comment]
Great 👍

**Comment by hoanglinhlan** [comment]
passed
