### ISSUE TITLE
KCRM cancel and email buttons do not work

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3228]
- Clicking the email button should open a browser with the KCRM BCC email
- Clicking the close lead button opens KCRM in a modal, it should open the cancel lead modal options

![image](https://cloud.githubusercontent.com/assets/2201340/26038768/0ef30aa6-3953-11e7-8b64-4cce712f333a.png)

When you cancel a lead:
![image](https://cloud.githubusercontent.com/assets/2201340/26038772/2f8b26d6-3953-11e7-8975-5c74d5cec0e4.png)

**Comment by mkhoudary** [comment]
Cancel is fixed, waiting next deployment to be applied.. for mail buttons that is strangely not working in windows 10 + chrome.. and this seems like a browser/os bug

**Comment by hoanglinhlan** [comment]
nothing happen after I clicked to email button

**Comment by mkhoudary** [comment]
@hoanglinhlan with email button it's an OS issue, if you have a mail client like thunderbird or outlook it will work..

**Comment by hoanglinhlan** [comment]
just checked after I changed default app
it's work fine
