### ISSUE TITLE
From, to and forward links no longer work in KCRM

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3232]
![image](https://cloud.githubusercontent.com/assets/2201340/26046256/74af8318-3991-11e7-9b1e-11df6c96769d.png)

http://kcrm.kademi.us/leads/12002221/

**Comment by mkhoudary** [comment]
It doesn't work with windows 10 and no default mail client specified..

**Comment by hoanglinhlan** [comment]
confirm after config in default app it's work
