### ISSUE TITLE
How should the Proposal button work?

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3234]
http://itsinsuredqa-crm.kademi.com.au/quotes/

- If I click the button it asks me to choose a series of quotes
- If I choose a group of quotes, then click it, it tells "Quotes must have customer and vendor assigned"

![image](https://cloud.githubusercontent.com/assets/2201340/26052668/8c42ae0c-39a9-11e7-8a57-342c94baba89.png)

**Comment by mkhoudary** [comment]
This was changed since the new proposals page was added.
