### ISSUE TITLE
Cannot create K-feedback survey

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3236]
http://proposals.admin.kademi.us/kfeedback/#!/surveys/detail/

When I click submit, nothing happens and nothing is saved.

![image](https://cloud.githubusercontent.com/assets/2201340/26084217/e5597ea2-3a1d-11e7-8e1a-8df5caaeb7a6.png)

**Comment by anhnt** [comment]
just reindexed that ksurvey db and its working now
