### ISSUE TITLE
Importer for sales data series

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3237]
1. go here - http://localhost:8080/sales/
2. Create a sales data series, eg called "car-sales"
3. go here - http://localhost:8080/sales/car-sales
4. upload data from the drop down at top right

See ManageSalesDataSeriesFolder, SalesDataRecord and SalesDataSeries

**Comment by diegoperezn** [comment]
@gonzalon Could you review it please?

**Comment by bradmac** [comment]
@tuzzmaniandevil please update to new framework

**Comment by tuzzmaniandevil** [comment]
Now under /tableUploaders

**Comment by hoanglinhlan** [comment]
Cant import althought my file doesn't has any error 
http://lantest1.admin.kademi-prod.com/tableUploaders/salesDataUploader
[records.zip](https://github.com/Kademi/kademi-dev/files/1104422/records.zip)

**Comment by hoanglinhlan** [comment]
passed
