### ISSUE TITLE
Points value goal

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3238]
Create a goal which is achieved when the user has reached a certain level of points in a specified points bucket

This should have an option for whether it is cumulative (all points earned regardless of debits) or current balance

**Comment by mkhoudary** [comment]
@bradmac I've got a question:
Say we've added such a node with 100 points cumulative, and the customer has got 100, the event will be fired, when the customer continues having 110, 150, 160 ... etc the event will be fired each time, and its up to the JB designer to act, right?

**Comment by bradmac** [comment]
No, because the journey will have moved on to another node.

**Comment by mkhoudary** [comment]
Done..

**Comment by mkhoudary** [comment]
@bradmac Waiting next deployment
