### ISSUE TITLE
Data series value goal

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3239]
Create a goal which is achieved when a user (or an organisation they're connected to) has achieved a certain value in a specified data series

**Comment by gonzalon** [comment]
1- Implements IndexedItemUpdatedEvent in SalesDataRecodFunnelEvent, and 
2- Fire it on SalesDataApp. 554 - 560

**Comment by gonzalon** [comment]
The events fired in SalesDataApp.java are not called.

**Comment by AlaaKhalaf94** [comment]
Hi @gonzalon , I create this journey : http://alaa5.admin.kademi-ci.co/funnels/journey2/version1/#journeyBuilder-tab
And from "edit details" of goal I set the amount = 50

![capture1](https://user-images.githubusercontent.com/26510030/31667878-59bc42ca-b359-11e7-970a-7abcfd8819fe.PNG)

Then here : http://alaa5.admin.kademi-ci.co/sales/new-series01/#history-tab
I add new record with amount = 60

And the journey doesn't start
What is the wrong with me ?

**Comment by gonzalon** [comment]
Hi @AlaaKhalaf94 it was only firing the events to make it work by the importer, now if you create a record manually it's going to work as well...

![image](https://user-images.githubusercontent.com/2773216/31690354-fb494ea4-b3ee-11e7-9479-a3c682367ce3.png)


![image](https://user-images.githubusercontent.com/2773216/31690378-0c077478-b3ef-11e7-91b9-425b3555ca74.png)

**Comment by AlaaKhalaf94** [comment]
passed
