### ISSUE TITLE
Allow registration forms to create customer organisations

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3240]
- new special field called orgTitle used in GroupRegistrationPage
- for membership applications, store on GroupMembershipApplication, and when accepted find or create a matching org, and add the user to it
- for open groups, find or create immediately and add to it

**Comment by bradmac** [comment]
Please assign to @ducdhm to make an option in registerFormComponent for whether to show the organisation input or not

**Comment by diegoperezn** [comment]
@bradmac  We need to create the field for newOrgProvided (new_Org_Provided) in the GroupMembershipApplication Entity.

Assigned to @ducdhm for the UI and @gonzalon to code review.

**Comment by gonzalon** [comment]
Ok for me 👍

**Comment by bradmac** [comment]
Hey @diegoperezn  can we remove applicationRusultProfile from GroupMembershipApplication?

This is already captured with the member property

**Comment by bradmac** [comment]
Also, this looks wrong
```
                GroupMembershipApplication gma = new GroupMembershipApplication();
                if ( org == null ) {
                    gma.setNewOrgProvided(newOrgTitle);
                    org = parent.getOrganisation();
                }
```

I think we should leave org as null, just set the title. We already have the admin org, so dont need it again.

**Comment by bradmac** [comment]
In SignupApp you have this:
```
            if ( !StringUtils.isEmpty(gma.getNewOrgProvided()) ) {
                if (org.childOrg(gma.getNewOrgProvided(), session) == null) {
                    org = org.createChildOrg(gma.getNewOrgProvided(), session);
                } else {
                    org = org.childOrg(gma.getNewOrgProvided(), session);
                }
            }
```

But thats not quite right.

Firstly, we should be trying to locate an org by the title property, not by orgId.

And when you do create an organisation, we do want to set the org title from getNewOrgProvided, but we do not want to use this as the orgId of the new org. Instead generate an orgid without spaces and special characters by using DbUtils.replaceYuckyChars

**Comment by diegoperezn** [comment]
For this case :
```
GroupMembershipApplication gma = new GroupMembershipApplication();
                if ( org == null ) {
                    gma.setNewOrgProvided(newOrgTitle);
                    org = parent.getOrganisation();
                }
```

This property is used for a few places, for example, to know if the logged user is allowed to approve the app and I though that the parent organisation is the closest one to related the app. and also is used in other places, Do you thinks this places can be changed to used the admin org of the app? Remember that in these cases with do not have org yet: 
```
 protected boolean isApplicationWithinOrg(GroupMembershipApplication application) {
        boolean isWhitIn = false;
        for (Organisation org : getUserOrgs()) {
            if ( application.getWithinOrg().isWithin(org) ) {
                isWhitIn = true;
                break;
            }
        }
        return isWhitIn;
    }
```

**Comment by bradmac** [comment]
"Do you thinks this places can be changed to used the admin org of the app" - Yes, use the admin org.

**Comment by diegoperezn** [comment]
@bradmac I added changes to the vfs project and we have to change the database to allow null values for the withinOrg var in GroupMembershipApplication

**Comment by hoanglinhlan** [comment]
passed
