### ISSUE TITLE
Allow multiple email recipients for testing EDMs

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3244]
When testing and approving emails, it is often necessary to send a test to several users so all stake holders can review. 

Currently the user has to send each test email individually. We want them to be able to enter a list of recipient addresses and have a test email sent to each
- Use the test button with enter recipient
- this issue applies to both group emails and automated emails

![image](https://cloud.githubusercontent.com/assets/826458/26132616/a39e73e0-3af5-11e7-977d-2c687e1aec7f.png)

![image](https://cloud.githubusercontent.com/assets/826458/26132649/db7716e6-3af5-11e7-8769-6e05a90182b6.png)

**Comment by bradmac** [comment]
Status display:
- return the list of new email ID's in the response to the POST
- add a JSON status service to ManageEmailItemPage sendContent (use WebUtils.asJson()). Should return fields status, from, to, subject, send attempts
- after submitting the POST, display a table with statuses of each item. Include a link to the email item page for each row

**Comment by diegoperezn** [comment]
Its ok for me!

**Comment by bradmac** [comment]
hey @gonzalon looks like the UI hasnt been integrated into the automations page yet:
http://localhost:8080/autoEmails/

This should work the same as for group emails

**Comment by gonzalon** [comment]
Updated to implement the same feature in the automation page

**Comment by hoanglinhlan** [comment]
passed
