### ISSUE TITLE
Check for special characters in Web name field when uploading products

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3245]
When uploading products http://customerfusion.admin.kademi.com.au/products/

If a special character like " is used in the webname field it breaks as this is used in the URL.

Can we validate the upload and stop it if a special character is used, or not import those lines that use a special character?

**Comment by bradmac** [comment]
@diegoperezn can you please add this to the old csv importer, as well as the new import wizard

**Comment by diegoperezn** [comment]
@paddyow Do you have the file you tried to upload?

**Comment by diegoperezn** [comment]
@gonzalon Could you review it?

**Comment by gonzalon** [comment]
Looks great :)
