### ISSUE TITLE
Support ExtraField rendering in LeadMan

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3246]
Please implement rendering of Funnels ExtraField values (ie com.fuselms.apps.funnels.ExtraField) the same as group/profile ExtraField values (ie io.milton.cloud.server.web.ExtraField)

Note that it might be possible to consolidate to a single class, which would be io.milton.cloud.server.web.ExtraField

If not consolidating the two classes, consider applying a common interface, and moving rendering logic to a common static method or service.

**Comment by bradmac** [comment]
@mkhoudary is this already done?

**Comment by mkhoudary** [comment]
Done..

**Comment by hoanglinhlan** [comment]
passed
