### ISSUE TITLE
Could not create membership in second time

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#3249]
![image](https://cloud.githubusercontent.com/assets/735555/26208840/4c21d316-3c15-11e7-9a71-cb8d9216a3e6.png)

To reproduce this bug:

- Go to a user profile
- Try to add new membership by clicking "Add membership and organisation", then click save. It worked ok
- Try again with other membership, then will get this error

I have investigated the problem. We loaded  ```/theme/apps/leadman/viewLead.js``` in admin console, so at line 331:

```
 body.on('hide.bs.modal', '.modal', function () {
       $(this).find('input, select, textarea').not(':button, :image, :reset, :submit, :hidden').val('');
 });
```

this bit will reset all form fields inside a modal when it's getting hidden. This bug doesnt occur in our prod server so i think it's recently appeared.

**Comment by anhnt** [comment]
we need to limit this event handler to specific bootstrap modals, not global scope as it is atm

**Comment by bradmac** [comment]
Just checked locally and seems ok. @anhnt please confirm if still active

**Comment by anhnt** [comment]
looks good to me as well
