### ISSUE TITLE
Create proposal page

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3256]
- for front end sites as part of KCRM
- allow setting the customer and status fields
- create new proposal at /proposals/new , redirect after saving to nextHref
- once created allow adding quotes
- allow quickly adding quotes with just the following:
  - vendor
  - file attachment
  - total amount
  - title
  - customer defaulted from proposal customer
  - lead defaulted from proposal lead

**Comment by ducdhm** [comment]
Done!

**Comment by bradmac** [comment]
Couple of things
- when adding a quote we need to be able to attach a file as part of the create modal
- do not redirect to the quote page after adding

**Comment by bradmac** [comment]
In the add quote form, allow the user to add a single line item with the following fields. If adding a line item all fields except supplier are required.
- supplier (entity selector)
- description;
- quantity
- unitPrice

**Comment by ducdhm** [comment]
Front-end stuff is done!

**Comment by ducdhm** [comment]
Done frontend stuff!

**Comment by bradmac** [comment]
Done backend stuff!

**Comment by hoanglinhlan** [comment]
after create quote
in quote page, it's not showing customer. It should show customer like a proposal customer
http://hattonfake.kademi.com.au/quotes/74742314

**Comment by bradmac** [comment]
@hoanglinhlan can you clarify the problem? perhaps with an annotated screenshot?

**Comment by hoanglinhlan** [comment]
hi @bradmac 
After user created a proposal, we alway have a customer for this proposal and all quotes of this proposal
so I think we should showing existed customer in quote page 
![image](https://user-images.githubusercontent.com/20508726/27162753-266c6750-51ad-11e7-84c2-c3a6d9c46ff2.png)

like in proposal page
![image](https://user-images.githubusercontent.com/20508726/27162762-3e89c7ec-51ad-11e7-8f9d-237f7ef890b9.png)

**Comment by mkhoudary** [comment]
Fixed.. pls test on kademi-prod

**Comment by hoanglinhlan** [comment]
passed
