### ISSUE TITLE
Search not working in client account

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3263]
http://ward6.admin.kademi.com.au/manageUsers/?startDate=24/05/2007&finishDate=24/05/2017

When you type a search in, the results do not update.

![image](https://cloud.githubusercontent.com/assets/2201340/26381568/118f2822-4069-11e7-89a8-ea40a9cb023d.png)

**Comment by bradmac** [comment]
Problem because of the custom report in this account
