### ISSUE TITLE
2 Columns Container: the container does not appear if it is empty

### ISSUE THREAD

**Issue by diegoperezn** [Kademi/kademi-dev#3267]
If I used the 2nd column and the 1st one is empty the content is shown in the left

![captura de pantalla 2017-05-24 a las 13 54 10](https://cloud.githubusercontent.com/assets/26150017/26383700/8157aa16-4088-11e7-84af-623074c230a3.png)

![captura de pantalla 2017-05-24 a las 13 54 36](https://cloud.githubusercontent.com/assets/26150017/26383709/8ccde7d4-4088-11e7-91c3-edef64a8d528.png)

**Comment by ducdhm** [comment]
Should work now but need to save edm content again!
