### ISSUE TITLE
Cannot change EDM button color in editor

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3268]
The value is not saved and updated.

![image](https://cloud.githubusercontent.com/assets/2201340/26383838/7929d572-4078-11e7-8f04-1b2d2e867257.png)

**Comment by paddyow** [comment]
FYI, it is not updating background-color only bgcolor

<table align="center" border="0" cellpadding="0" cellspacing="0" class="button-wrapper" bgcolor="#2BAADF" style="border-radius:0px; background-color: #2BAADF">

**Comment by ducdhm** [comment]
Fixed!

**Comment by ducdhm** [comment]
Done! Can check in QA Server for now.
