### ISSUE TITLE
Dropzone is conflicted in File Manager screen

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#3271]
Reason: When enabling dropzone-lib and File Management screen also includes other dropzone js file, and then conflict happens

**Comment by bradmac** [comment]
ok, so maybe its time for the admin app to have dependencies

**Comment by ducdhm** [comment]
@bradmac 👍

**Comment by ducdhm** [comment]
I have added a fix for it. Should work now!
