### ISSUE TITLE
Cannot create or delete profiles on Olhub

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3272]
http://minda.admin.olhub.com/manageUsers/?q=test&g
Minda tried to delete profile on Olhub and got error:
An error occurred removing users. You might not have permission to do this.

Also cannot delete or create new profiles from the root of Olhub.
When trying to create profile from root, error: org.hibernate.exception.GenericJDBCException: could not execute statement

**Comment by bradmac** [comment]
DB problem, fixed
