### ISSUE TITLE
Quote page: duplicate quote after quote created 

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#3277]
http://version1.itsinsured-fake.kademi.com.au/quotes/

**Comment by bradmac** [comment]
not sure if this is still active, but please check

**Comment by mkhoudary** [comment]
Quote page needs revision now,

**Comment by mkhoudary** [comment]
@hoanglinhlan can you reproduce please? or this is an old bug? because last time I checked this problem wasn't present.

**Comment by hoanglinhlan** [comment]
Hi @mkhoudary 
I checked, this issue is still active ( please search: quotefor3277-001)
![image](https://user-images.githubusercontent.com/20508726/27018197-a2649f5a-4f58-11e7-937f-653cf116f0fb.png)

Profile to login as: http://itsinsuredtqa.admin.kademi.com.au/manageUsers/72924918
1: go to quote page then create a new quote 
http://itsinsuredqa-crm.kademi.com.au/quotes/
2: after redirect to quote detail page, please back to quote page then search with new quote's name

**Comment by mkhoudary** [comment]
Fixed..

**Comment by hoanglinhlan** [comment]
please re-check 
 this issue is still active

**Comment by mkhoudary** [comment]
Fixed.. but payment-lib version 1.0.2, and leadman-lib 1.0.10 doesn't appear on server although I've published both using ksync

**Comment by bradmac** [comment]
hey @mkhoudary best not to use numbering like "1.0.10", use "1.1.0" instead. Ideally i'd like to change to just a straight numbering like 0312 but we can do that later.

**Comment by bradmac** [comment]
@mkhoudary just looking at payment lib, you can see the publishing history here:

http://kademi.admin.kademi.com.au/manageApps/payment-lib/#history-tab

As you can see 1.0.2 has not been published:
![image](https://user-images.githubusercontent.com/826458/27203490-3960b41a-527a-11e7-9600-ddea9619e252.png)

There was a problem in the previous version of ksync where it was not republishing, so possibly you're using an out of date version

**Comment by bradmac** [comment]
I just ran the current version of ksync and 1.0.2 was published

![image](https://user-images.githubusercontent.com/826458/27203559-7e384026-527a-11e7-8ac5-d2f446e2b9b3.png)

**Comment by bradmac** [comment]
And the published version is available for selection in itsinsured:

![image](https://user-images.githubusercontent.com/826458/27203586-9702fea2-527a-11e7-94d4-f8658f45cf34.png)

**Comment by bradmac** [comment]
Published leadman-lib 1.1.0

**Comment by bradmac** [comment]
Also updated bootstrap-base with new versions, and republished along with dependent themes.

**Comment by hoanglinhlan** [comment]
passed
