### ISSUE TITLE
Requirements for contact lookup TBD

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#328]
As discussed yesterday we are concerned about the way that Groups/Users is displayed and the limitations of the search function when looking up participants 

Eg. 

We want to be able to filter these additional search functions: 

1.       Dealership Name
2.       Dealer Code
3.       User ID
 
So our ideal view would be: 

1.       DELETE nick name
2.       First Name
3.       Last Name
4.       Email
5.       Dealership Name
6.       Dealer Code
7.       Participant Role
8.       User ID
 
In order for us to quickly look up a participant when they call us on the hotline, we need to have this more detailed view 

Please advise when this is possible to amend

See below an example of what we used to receive from TOYOTA – this also included a filter

**Comment by bradmac** [comment]
- I think we might be able to include organisation info in the search. 
- the participant role can be selected by the group select box
- userID should already be searched, but not extra fields

**Comment by bradmac** [comment]
Closing in favour of the new manage users page
