### ISSUE TITLE
Reward store should allow selection of multiple variants on product details page

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3289]
@paddyow please provide a design guide

![image](https://cloud.githubusercontent.com/assets/826458/26564045/1e939cb2-4530-11e7-8432-2a3a7042c82a.png)

**Comment by paddyow** [comment]
![image](https://user-images.githubusercontent.com/2201340/27160903-0952f25c-51bb-11e7-8da5-08b070b9dbd7.png)

**Comment by bradmac** [comment]
@ducdhm please update ecom and rewardstore components as above

**Comment by bradmac** [comment]
Note that the variant types are dynamic, and there can be any number of them

**Comment by paddyow** [comment]
@ducdhm thinking we split variant drop downs into 2 cols, then they just wrap.

**Comment by ducdhm** [comment]
When have 0 param:
![when_0_param](https://user-images.githubusercontent.com/1289631/27524860-29c0a498-5a63-11e7-9fc6-884948eb80d5.png)

When have 1 param:
![when_1_param](https://user-images.githubusercontent.com/1289631/27524862-2f3a48c0-5a63-11e7-9493-002e4601dbd3.png)

When have more than 1 param:
![when_2_params](https://user-images.githubusercontent.com/1289631/27524869-34ea43b0-5a63-11e7-843d-771a9ab70325.png)

**Comment by ducdhm** [comment]
Done!
