### ISSUE TITLE
Terst New Products Uploaded Tool for decimal places

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3297]
@hoanglinhlan please test the upload of products using both CSV and Excel files here http://kademisolutions.admin.kademi.us/products/

Please test that the base cost allows a decimal place i.e. $25.40  or $50.50 for example.

![image](https://cloud.githubusercontent.com/assets/2201340/26610468/f5072358-45ea-11e7-9bb2-79bbae40c7c0.png)

**Comment by hoanglinhlan** [comment]
hi @paddyow 
current, it's still showing error with decimal cost
![image](https://cloud.githubusercontent.com/assets/20508726/26614501/14f893c2-45eb-11e7-82ff-5952fb4a15ab.png)

[products.zip](https://github.com/Kademi/kademi-dev/files/1040229/products.zip)

**Comment by tuzzmaniandevil** [comment]
The Products importer has been re-writen to work with the framework in #3347 
I tested it and now imports decimal points :-). @hoanglinhlan I'll assign the new issue to you to test all the new importers
