### ISSUE TITLE
eCommerce - orders by Anonymous has 404 link 

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#3298]
http://polomania.admin.kademi.com.au/shopping-carts/
![image](https://cloud.githubusercontent.com/assets/20508726/26615621/7212f47e-45f2-11e7-99a0-556914fcf1a9.png)

I think we should hide this link with order by  Anonymous

**Comment by ducdhm** [comment]
![newui](https://cloud.githubusercontent.com/assets/1289631/26813177/918fe07e-4aa6-11e7-9014-d1bf071d5e58.png)

**Comment by hoanglinhlan** [comment]
passed
