### ISSUE TITLE
pieChart component issue

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#3299]
Data test: 
p3 https://lan-test.admin.kademi.com.au/pages/c5s/version1/
http://version1.c5s.kademi.com.au/contenteditor?fileName=p34235.html&miltonUserUrl=/users/lan&miltonUserUrlHash=bba28691-0efd-4e56-a54b-5c7f9b4e6f0c:i5bjztr_yT33idX2nRlAsjRkLP8

1: enter chart's title then save. after refresh page, title field is empty
2: select query type  then choose a query and save. after refresh value of query dropdown and Aggregation dropdown are "None"
3: save color is not work

**Comment by anhnt** [comment]
after upgrading theme and libs, everything is working fine :)
