### ISSUE TITLE
all Component: showing new page after click and entered on any field

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#3300]
- Create a new web page then add any component. 
- open setting of this component then click to any field and entered 

==> browser refresh and showing a new page

**Comment by hoanglinhlan** [comment]
it's still not working

**Comment by ducdhm** [comment]
Where did you test it?

**Comment by hoanglinhlan** [comment]
hi @ducdhm 
just re-checked, not all component. Current, at least we have one component still not working
Please check in here http://version1.c5s.kademi.com.au/contenteditor?fileName=p2704.html&miltonUserUrl=/users/lan&miltonUserUrlHash=64bd028e-91ae-465b-9b61-53c446873a18:cxxfwGJzi9DGv8vpqxJfIffZqpg

![image](https://user-images.githubusercontent.com/20508726/26838797-6c6b6b5a-4b0b-11e7-9e06-50549e924fb8.png)

**Comment by ducdhm** [comment]
Fixed! Need a deployment!

**Comment by hoanglinhlan** [comment]
passed
