### ISSUE TITLE
Assign CPD certificate to a group

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3304]
- User can choose which group the CPD points and cert are awarded to
- When the module is completed, the points and certificate must only be awarded to a profile in the selected group
- If no groups are selected, the profile is awarded all sets of points and certs

![image](https://cloud.githubusercontent.com/assets/2201340/26661920/f17ce496-46c3-11e7-8fe9-436c7dcec20e.png)

Additionally, it would be good to show the certificate name in the profile learning record so the CPD points have reference to the provider i.e. ACRRM or RACGP

![image](https://cloud.githubusercontent.com/assets/2201340/26662013/8b2f7c84-46c4-11e7-9886-fb1ccc0cd8ea.png)

**Comment by mkhoudary** [comment]
This is done.. can be tested after the next deployment
