### ISSUE TITLE
Integrate translation support into front end

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3306]
Please integrate translatable support into websites.

This will allow, for example, the translatable class to be added to menu items so that a user can select a language, and then click the translate button for a menu item and enter its translation, and then have that displayed.

**Comment by bradmac** [comment]
For an example of usage, see manageProductDetails.html
```
<input type="text" class="form-control required translatable" name="title" data-source-field="title" value="$page.translate('title')" />
```

**Comment by bradmac** [comment]
@ducdhm i've added Translatable support to ProductInRewardResource. So you should be able to implement translatable support in teh front end same as we have in the admin page for ManageProductFolder

**Comment by ducdhm** [comment]
JS stuffs are done!

**Comment by bradmac** [comment]
- currently displays the word "Translate". Should just be the icon as per in the admin
- should only display for users with content editing permission (similar to KToolbar)
- possibly we make this part of KToolbar?

**Comment by ducdhm** [comment]
Done!
