### ISSUE TITLE
Demo: Choosing BS theme

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3309]
- Can we load the latest K theme so I can select it, or set it to be the default theme in an account?
- Selecting BS causes a page not found which does not look the best

![image](https://cloud.githubusercontent.com/assets/2201340/26665714/edd6dbce-46de-11e7-8af4-9fdb17c26057.png)

I want to use this theme:
![image](https://cloud.githubusercontent.com/assets/2201340/26666176/e54fa00a-46e1-11e7-95da-c59efa31f92f.png)

**Comment by paddyow** [comment]
@ducdhm we need to extract the new Kademi theme from this demo account and make it part of our theme selection.

http://kademisolutions.admin.kademi.us/manageUsers/11695433/#summary-tab

Brad tells me you are working on some theme stuff now.  FYI @anhnt create the demo site.

@ducdhm we need this doing today if possible as I have to have a demo rolled out tomorrow.

**Comment by ducdhm** [comment]
Done!

**Comment by paddyow** [comment]
I installed the theme, but cannot select it to make the change.
http://rewardtest1.admin.kademi.us/websites/ptest/version2/themeSelect

**Comment by ducdhm** [comment]
Seem like we dont have moment-lib in US and error message is not showed. I'll create issue for handling this

**Comment by ducdhm** [comment]
https://github.com/Kademi/kademi-dev/issues/3325
