### ISSUE TITLE
Demo: Updating libs

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3311]
To use the latest reward store components, the app library version update had to be manually selected.

When I change the version of rewardstorelib, it does not remember my choice or show the change in the drop down even though the new components have updated.

![image](https://cloud.githubusercontent.com/assets/2201340/26666874/9fd79e66-46e5-11e7-8bc0-a28dbebcefb0.png)

Anh also tells me I need to update the user lib before I can build the rewardstore as intended.  Is this a workflow we want users to go through or should all the latest libs be pre-installed when a new account is created?

**Comment by bradmac** [comment]
Moving to https://github.com/Kademi/kademi-dev/issues/3448
