### ISSUE TITLE
Demo: category panel not rendering images

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3313]
On page load the category panels render with the correct number and with images:
![image](https://cloud.githubusercontent.com/assets/2201340/26666926/e43f801e-46e5-11e7-8a83-9ed134e98448.png)

Then defaults to the below:
![image](https://cloud.githubusercontent.com/assets/2201340/26666910/d3cb9a2e-46e5-11e7-8716-ce789078d434.png)

Is this intended?  The old category component using an older lib would render the cat images in the editor window for me.

**Comment by anhnt** [comment]
fixed and applied to stock

**Comment by hoanglinhlan** [comment]
passed
