### ISSUE TITLE
Demo: Category list component not rendering titles 

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3322]
http://rewardtest1.admin.kademi.us/pages/ptest/version2/

Should look like this:
![image](https://cloud.githubusercontent.com/assets/2201340/26675367/fcb237c4-4706-11e7-8e10-e9d76bf8e520.png)

Looks like this:
![image](https://cloud.githubusercontent.com/assets/2201340/26675383/0c432e14-4707-11e7-8ab2-bacc2bec513a.png)

**Comment by anhnt** [comment]
works ok with rewardstore-lib 1.0.5
![image](https://cloud.githubusercontent.com/assets/735555/26709350/5d241e18-477c-11e7-8655-897adfd2a7a3.png)
