### ISSUE TITLE
Add color picker to background colour in editor

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3324]
![image](https://cloud.githubusercontent.com/assets/2201340/26676368/d0c7c62a-470a-11e7-91f9-862f60a732e5.png)

**Comment by paddyow** [comment]
The color picker panel should show the theme colors as default as small tiles, but then allow the user to optionally choose a choose a color using a picker.

For example: https://github.com/carloscabo/jquery-palette-color-picker

![image](https://user-images.githubusercontent.com/2201340/27250438-27ae4aa8-5373-11e7-8242-5abbaa05b61f.png)

**Comment by hoanglinhlan** [comment]
passed
