### ISSUE TITLE
Select doctype 'top' hides menu

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3326]
Using editor you lost the menu bar if you choose doctype top
![image](https://cloud.githubusercontent.com/assets/2201340/26676864/e16f0b44-470c-11e7-9d32-dfb5000b641d.png)

**Comment by ducdhm** [comment]
@paddyow @bradmac do you have any suggestion for this case? It's just css stuff. When you choose Dock type is "fixed", it means position of container is fixed and top: 0. And.... it's overlapping menu

**Comment by bradmac** [comment]
Yep. Its all working correctly. @paddyow i dont think you should be docking the container to the top of the screen
