### ISSUE TITLE
Demo: base template has unwanted padding I cannot control

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3327]
There is a gap below the menu bar, but cannot find a way to remove it without editing the source code.
![image](https://cloud.githubusercontent.com/assets/2201340/26677223/530bf6d0-470e-11e7-8190-c6a85bab2660.png)

This is the result:
![image](https://cloud.githubusercontent.com/assets/2201340/26677236/6237e9d4-470e-11e7-87c2-3b0627bbcbb8.png)

**Comment by paddyow** [comment]
@duc can you add a variable to control this.  There will be pages that need a header image but needs to be flush with the top nav bar where the BS theme applies a default button margin.

@navbar-margin-bottom

**Comment by ducdhm** [comment]
@paddyow Bootstrap already supports `@navbar-margin-bottom` variable for it. You can use it now! 

FYI: List of available variables of Bootstrap are at http://getbootstrap.com/customize/#navbar

**Comment by bradmac** [comment]
Hey guys. This is not something that should be "controlled". Its just part of the theme. If we want to change the theme, we change the theme.

**Comment by paddyow** [comment]
@ducdhm update K theme not to apply that bottom margin on the nav.

Question: Is the a reason why a container has no margin setting?  I can add padding but want to add margins as well.

**Comment by ducdhm** [comment]
Move margin stuff to https://github.com/Kademi/kademi-dev/issues/3343
