### ISSUE TITLE
Migrate contact request report to elasticsearch

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#333]
Should allow aggregations/filtering for
 - form
 - by each field (ie state, country, postcode)
 - user group

**Comment by lachlanrdale** [comment]
Beautiful, thanks Brad. As an FYI are a looking to close off testing today, to push forward with launch tomorrow.

Cheers,

**Comment by bradmac** [comment]
I dont think we can get this report updated today. But I think if you can just verify that the correct data has been captured on the contact record, then that should be sufficient.

**Comment by lachlanrdale** [comment]
Sure thing Brad - as long as we can export as needed there shouldn't be any major issue (client has requested this).

**Comment by lachlanrdale** [comment]
Yep, have verified. Thanks Brad.

**Comment by bradmac** [comment]
Hey @skwidge might be best if you pick this up.
