### ISSUE TITLE
Editor: nesting a container 

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3330]
@ducdhm I want to insert a container which has a full width BG image, then have type which conforms to the box width so it aligns with the rest of the page content.  How would I achieve this?

![image](https://cloud.githubusercontent.com/assets/2201340/26678150/790ad398-4712-11e7-80ec-026ab98b6779.png)

**Comment by ducdhm** [comment]
You just need change `Layout` of container is `Box` and `Background for` change to `Container`

**Comment by ducdhm** [comment]
@paddyow Maybe we need better Name of option and value of `Background for`
