### ISSUE TITLE
Demo: Account setup - reward store APP did not install correctly 

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3333]
http://rewardtest2.admin.kademi.us/pages/rewardtest2/version1/

After installing the reward store APP
1) The libs needed to be manually updated
2) The templates are missing components.  See below rewardstoredashboard, which only shows cats

http://rewardtest2.kademi.us//theme/apps/rewardstore/contenteditor?fileName=rewardStoreDashboard.html&miltonUserUrl=/users/patrick-707421&miltonUserUrlHash=5059164d-b932-4d14-ae96-7aaf5e765145:P7EybafKWM85cQAFHTM7wUhGWZw

![image](https://cloud.githubusercontent.com/assets/2201340/26712073/2dff97b2-47a8-11e7-98ba-9d8a92cdc688.png)

**Comment by bradmac** [comment]
@paddyow i think this should be cool now
