### ISSUE TITLE
Leadman - quotes page:  create quote Button on popup doesn't work 

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#3335]
Profile file https://lan-test.admin.kademi.com.au/manageUsers/74497161
Page: http://hattonfake.kademi.com.au/quotes/
- Click to new quote button 
- Enter all require field then click create quote button ==> nothing happen

**Comment by ducdhm** [comment]
It's working normally!

**Comment by hoanglinhlan** [comment]
passed
