### ISSUE TITLE
Cannot import users (using profile tool) into a journey without it failing

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3336]
I have this journey http://rewardtest1.admin.kademi.us/funnels/onboarding/#journeyBuilder-tab

If I add a user manually to the sales consultant group the profile is added and the journey works as intended

If I use the profile uploaded tool, match on cols, the import fails

http://rewardtest1.admin.kademi.us/manageUsers/upload

File below

[users.xlsx](https://github.com/Kademi/kademi-dev/files/1047211/users.xlsx)

**Comment by tuzzmaniandevil** [comment]
The email address wasn't being set before the SubscriptionEvent got fired. So it failed to create the email item
