### ISSUE TITLE
K-editor back buttons

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3337]
http://owensdemo1.kademi.us//theme/apps/rewardstore/contenteditor?fileName=rewardStoreDashboard.html&miltonUserUrl=/users/patrick-707421&miltonUserUrlHash=1a96fa33-0b30-4223-ba59-653b888bfe60:ASLDDsiPj_lDMfbL1c2Eqy2-CEo

When opening a template with our editor, we do not need to show a back button, it goes to a blank page and the editor is opened in a new window.

![image](https://cloud.githubusercontent.com/assets/2201340/26720465/c1746216-47cb-11e7-99e3-80a33d4d1948.png)

When editing an email using the JB, we need to add a back button.  This should go back to the email config  page, not the JB canvas.

http://rewardtest1.admin.kademi.us/funnels/onboarding/emailAction-88a93d/#message-tab
The user has to use the back button in the browser currently.

![image](https://cloud.githubusercontent.com/assets/2201340/26720516/f4e7abbc-47cb-11e7-81c5-7d030288ab91.png)

**Comment by ducdhm** [comment]
Fixed! Can see the change in next deployment!
