### ISSUE TITLE
Entity Finder in Edit Quote page doesn't search for orgs and custs

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#3338]
As was applied in the edit quote page, the fields for Vendor and Suppliers were searching for both orgs and custs before applying the entity finder, now they only search for customers.

Please make sure they search for both.

**Comment by bradmac** [comment]
@ducdhm please sort this out asap

**Comment by ducdhm** [comment]
Done! I have added entityFinder-lib and dependencies on it from payment-lib

**Comment by tannguyen3489** [comment]
I checked on admin and front-end. It is still ok.

![image](https://cloud.githubusercontent.com/assets/1665005/26769595/4dfdf598-49da-11e7-9982-050c1e77c0b4.png)
