### ISSUE TITLE
Entity Finder makes search fields unclickable

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#3340]
When trying to use the quote page after having entity finder associated with the vendor/customer fields, both fields are unclickable(focusable via clicking) due to a field that is above them with 0 opacity.

Please fix that to allow the visible fields to be clickable, a suggested solution is to give the 0 opacity field a css pointer-events: none.

**Comment by bradmac** [comment]
:+1:

**Comment by ducdhm** [comment]
It's working normally in my side. Can you double-check again?

**Comment by ducdhm** [comment]
Just need to deploy!
