### ISSUE TITLE
Allow selecting subscription groups as opt-ins for a primary group

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#3344]
Appeared here
https://acfenz.admin.kademi.com.au/groups/Advertiser/

**Comment by bradmac** [comment]
what is the problem?

**Comment by AlaaKhalaf94** [comment]
when I make the Advertiser group an opt-in for members
and save

it shows an error

**Comment by bradmac** [comment]
Its the wrong way around. You should be editing the members group, and selecting "Advertisers"

**Comment by bradmac** [comment]
OK, so currently only "user tag" groups are presented for selection as opt-ins for primary groups. We should change this to allow selecting sub groups

**Comment by bradmac** [comment]
This needs updating:

![image](https://cloud.githubusercontent.com/assets/826458/26820022/7b42a208-4af5-11e7-9e45-4a79aa389716.png)

**Comment by mkhoudary** [comment]
Done..

**Comment by mkhoudary** [comment]
@bradmac  Pending deployment..
