### ISSUE TITLE
Kademi subscription part 3: Acquire and validate a license

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3345]
- Create a new filter (similar to IDPFilter) and configure in applicationContext.xml
- This will check for a previously acquired license which will have been persisted to the DB
- If present check the expiry date (TODO: later will generate signature)
- If not present or not valid, use the client to acquire one for the admin domain (note that when accessing a website, the website needs to be looked up to find the admin domain)
- If no valid license can be obtained, then reject the request, ie do not continue processing the filter chain

**Comment by gonzalon** [comment]
KademiLicense
- Organisation
- licenseText
- licenseSig
- expiryDate
- acquiredDate
