### ISSUE TITLE
Cannot edit parameters of password reset button in EDM template

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3348]
I should be able to adjust padding, change button colour...

This is the case on both AU and US servers.

![image](https://cloud.githubusercontent.com/assets/2201340/26813882/c185f6ce-4ac4-11e7-9e0a-66b0160bd521.png)

**Comment by ducdhm** [comment]
I have deployed the newest version of email-lib. It works normally now. Just need to update it on your site
