### ISSUE TITLE
Demo: PasswordDoReset template

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3350]
I think the template for this should be broken down into parts, so the user can edit the title and button copy.  

![image](https://cloud.githubusercontent.com/assets/2201340/26814918/543546da-4acc-11e7-999a-be2a25118742.png)

**Comment by bradmac** [comment]
I think the copy can simply be removed, and the user can add text components. The copy on the button should be a configurable settings.

**Comment by bradmac** [comment]
Note that the standard template which uses this component needs to be updated to include the lead copy as text components.

**Comment by ducdhm** [comment]
@bradmac And we have a border around the form which contains title, description, input and button. I think better, we make title, description and button text are configurable.

**Comment by ducdhm** [comment]
Done!
