### ISSUE TITLE
Deleting a sent email removes the history from the profile email tab

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3351]
http://rewardtest1.admin.kademi.us/manageUsers/12462469/#emailAppTab-tab

**Comment by mkhoudary** [comment]
@paddyow the bug not clear to me.. can you please give more explanation?

**Comment by bradmac** [comment]
@paddyow is saying that when you send a group email, initially you see the emailitems on the profile page of recipients. But he's saying that if you delete that group email then the emailitems disappear from the profile page.

Its important that we have a permanent record of all emails sent.

**Comment by Uafinder** [comment]
waiting for this one
https://github.com/Kademi/kademi-dev/issues/4601

**Comment by bradmac** [comment]
Should be ready to test now

**Comment by Uafinder** [comment]
yup, working great!
