### ISSUE TITLE
Cant complete task 

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#3352]
Login to hattonfake site by account 
https://lan-test.admin.kademi.com.au/manageUsers/74497161/#general-tab
 then go to lead http://hattonfake.kademi.com.au/leads/74683718/
and complete current task 
it's running under this funnel: https://lan-test.admin.kademi.com.au/funnels/newjourney/#properties-tab
it's showing null error:
![image](https://cloud.githubusercontent.com/assets/20508726/26820871/9f8538dc-4ace-11e7-9d9a-5dac5d46ad26.png)

**Comment by bradmac** [comment]
@mkhoudary i think you said this was because the lead was already closed. Please confirm.

**Comment by mkhoudary** [comment]
The journey itself is wrongfully built, the task has no name, no title, after I've added a name to the task it worked just fine.
