### ISSUE TITLE
EDM editor is showing wrong settings for image component

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3354]
http://rewardtest1.admin.kademi.us/groupEmails/12605741/edmeditor?fileName=index.html&useHash=true

http://rewardtest1.admin.kademi.us/groupEmails/12605741/#messages-tab

![image](https://cloud.githubusercontent.com/assets/2201340/26824362/60545be0-4af4-11e7-8a7c-d08842b65b63.png)

**Comment by ducdhm** [comment]
Done! Need deploy to prod
