### ISSUE TITLE
Feature to select a sales date range and purge data in one go

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3355]
http://3m.admin.kademi.com.au/sales/3m-sales/#history-tab

Currently records display in 1000's.  Need to choose start and end date, then purge all data between the range.

**Comment by bradmac** [comment]
Already there ..

![image](https://user-images.githubusercontent.com/826458/26856423-a1a5ec34-4b77-11e7-9bd2-c234008ef7ea.png)
