### ISSUE TITLE
theme param editor page

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3357]
We want to allow non-technical users to change the theme parameters such as primary colour, corner radius, etc.

Currently users must edit the theme-params.less file, which requires knowledge of bootstrap and CSS.

So..do we make a new page? Or show a sidebar on theme checker? Or something else?

To update the parameters just POST to the manage website with a parameter of "updateThemeParams". All parameters and their values will be persisted to theme-params.less

**Comment by bradmac** [comment]
As discussed, initially we will just support the main params
- brand colours
- border radius
- text font
- headings base font
- base line height
- base padding

**Comment by ducdhm** [comment]
I'll add a button for changing theme in Ktoolbar. First thing need to do is make KToolbar as an app. It should be quick. https://github.com/Kademi/kademi-dev/issues/2604

**Comment by ducdhm** [comment]
@bradmac Please kindly help me to do backend stuff to support POST data to "/" in frontend site

**Comment by bradmac** [comment]
@ducdhm i have a site with KToolbar enabled, but i cant see any options to edit theme params

**Comment by ducdhm** [comment]
Done!

![newui](https://user-images.githubusercontent.com/1289631/26967783-bbc2fb94-4d29-11e7-99e9-da60be60a7c2.png)

**Comment by ducdhm** [comment]
@bradmac if value which I send to server is null or empty, can we remove it out of theme-parametter?

**Comment by bradmac** [comment]
@ducdhm i've improved the parsing, so you get default params now :)

And also will remove params which are empty. This does mean that if there is a default it will be restored

**Comment by ducdhm** [comment]
Leave me with it now :)

**Comment by ducdhm** [comment]
Done!
