### ISSUE TITLE
KCRM: Show funnel name on leads panel

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3359]
Eg
http://itsinsuredqa-crm.kademi.com.au/custs/23b1ead2-d803-4353-8616-85001cdf900f/

![image](https://user-images.githubusercontent.com/826458/26958649-efef24c4-4d1f-11e7-80de-ca92c87e708f.png)

**Comment by mkhoudary** [comment]
Done..

**Comment by mkhoudary** [comment]
Ready for test after @bradmac uploads next version

**Comment by hoanglinhlan** [comment]
passed
