### ISSUE TITLE
Calendar: upcoming events panel

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3360]
Create a configurable setting for how many days ahead to show events for

**Comment by mkhoudary** [comment]
@bradmac this is done, the days count ahead is stored in an extra field called upcoming-event-days.. so this is at a user level now.

**Comment by mkhoudary** [comment]
@bradmac  Ready to test whenever deployed..

**Comment by bradmac** [comment]
:+1: looks good.
