### ISSUE TITLE
KCRM: Allow setting customer avatar

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3361]
Similar to currently available on profile page

**Comment by mkhoudary** [comment]
Done..
Avatar can be changed from both view profile and view lead pages..
Additionally avatar now appear at the header of the lead and lead profile:

![image](https://user-images.githubusercontent.com/3704174/27081951-761a26a6-504b-11e7-90e0-46d5bc78b3e6.png)

![image](https://user-images.githubusercontent.com/3704174/27081957-82b314b8-504b-11e7-9840-82651998f298.png)

**Comment by bradmac** [comment]
Nice!

**Comment by hoanglinhlan** [comment]
hi @mkhoudary 
where can I change lead's avatar in lead page and profile page
![image](https://user-images.githubusercontent.com/20508726/27115568-c19b6b12-50f5-11e7-9e1b-c6e5de17b130.png)

**Comment by mkhoudary** [comment]
@hoanglinhlan please try this at the http://kademi-prod.com/ it's not deployed to production yet

**Comment by hoanglinhlan** [comment]
passed
