### ISSUE TITLE
change "lead cancelled" heading on lead page to indicate success or failure

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3362]
When leads are completed successfully in a journey (eg claims completed or acquisition) this must show success on the lead. I think this needs either a new node or setting on the current end lead node.

![image](https://user-images.githubusercontent.com/826458/26959011-f663fd6e-4d21-11e7-86da-0565b5945384.png)

**Comment by mkhoudary** [comment]
Will need to do the following:
1- Create cancel lead node.
2- Remove the newly created ending status field.
3- Let end lead node not to sent the cancelled flag.
4- Modify leadman screens to show cancelled/successful.
5- Modify insured flows to feature the new node.

**Comment by mkhoudary** [comment]
Done..
