### ISSUE TITLE
KCRM: Quick add task

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3363]
A KCRM user should be able to quickly add a task from the menu with
- due date
- task description
- assigned to

This should not be related to any particular lead

**Comment by mkhoudary** [comment]
This is done

**Comment by mkhoudary** [comment]
@bradmac Waiting deployment for testing

**Comment by hoanglinhlan** [comment]
profile login: https://lan-test.admin.kademi.com.au/manageUsers/74497161
login to http://hattonfake.kademi.com.au
I click to create a contact menu but nothing happen
