### ISSUE TITLE
New UI/UX for market place

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#3365]
Current UI:
 * Dashboard
![dashboard](https://user-images.githubusercontent.com/1289631/26967992-948a69da-4d2a-11e7-8c03-70b3f3f409ce.png)

 * Detailed page
![detailed_page](https://user-images.githubusercontent.com/1289631/26967995-99c86d16-4d2a-11e7-86b7-b537660f71d0.png)

**Comment by salehh93** [comment]
hey guys I can help for this 
What do you think of this?
![ui](https://user-images.githubusercontent.com/23012214/29004026-d0ac6ad6-7ac9-11e7-9b0e-524002f9ebd0.jpg)

**Comment by ducdhm** [comment]
@salehh93 It's looking good and its style is not fitted with our admin theme.

**Comment by bradmac** [comment]
We also need
- server side searching
- ability to select themes, apps or both
- option to show libs

**Comment by ducdhm** [comment]
New UI for market place (with textbox for searching app by name)
![newui - market place](https://user-images.githubusercontent.com/1289631/33159608-0b54e28a-d047-11e7-8054-a9298df71a95.png)

**Comment by ducdhm** [comment]
New UI for detailed page of app:
 * Not installed:
![newui - non installed](https://user-images.githubusercontent.com/1289631/33159616-18f444c6-d047-11e7-9084-957fc8ae2a16.png)

 * Installed:
![newui - installed](https://user-images.githubusercontent.com/1289631/33159620-1d8e6908-d047-11e7-92d7-e60f20ffbbac.png)

**Comment by ducdhm** [comment]
When error in review form:
![newui - error on review](https://user-images.githubusercontent.com/1289631/33159645-607788ee-d047-11e7-8955-c6715a5b8360.png)

**Comment by Uafinder** [comment]
1. symbol counter covers "submit" button
![image](https://user-images.githubusercontent.com/1945230/33170935-caf3b142-d052-11e7-8198-13ddbbfe9564.png)

2. Timestamp bad and it's not working with timezone
![image](https://user-images.githubusercontent.com/1945230/33170999-1a87d4c2-d053-11e7-9c0d-f0dd53f4f5ae.png)
It shows that comment left 11 hours in future.
http://vlad-test59.admin.kademi-ci.co/marketPlace/KLearning/

**Comment by bradmac** [comment]
Guys, I've moved reviews related bugs here:
https://github.com/Kademi/kademi-dev/issues/4490

@Uafinder please confirm the searching and installation functionality is working correctly on this issue disregarding review related issues

**Comment by Uafinder** [comment]
Working ok!
