### ISSUE TITLE
Reward demo:  Templates are out of date

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3367]
http://rewardtest1.admin.kademi.com.au/websites/rewardtest1/version1/#panel_details-tab

- Created new account an AU
- Created website
- Installed K theme
- Installed Rewards Store
- Selected K theme under themes
- Went to edit the reward store template and it's not showing the latest and greatest template 

Maybe the libs are not up to date?

http://rewardtest1.kademi.com.au//theme/apps/rewardstore/contenteditor?fileName=rewardStoreDashboard.html&miltonUserUrl=/users/patrick&miltonUserUrlHash=8cbffa52-3b9f-4a9b-8be4-1c78ba548541:LMhnoZbMjCGhLv6ri1-ROW6GqQA

**Comment by bradmac** [comment]
hey @ducdhm and @anhnt can you guys help @paddyow ?

**Comment by paddyow** [comment]
I need these latest libs to install on a new account, at the moment I cannot step through and create a reward store.

**Comment by paddyow** [comment]
Tried again but the updated template are not showing
Also I installed K Theme, but could not select it under manage themes, got error:

Could not enable all dependencies. These failed: user-lib

**Comment by ducdhm** [comment]
@bradmac I deployed the latest version of rewardstore-lib is 1.0.7 but in my test account, it's always available only version 1.0.0 for rewardstore-lib. You can check my admin console in AU at http://duc-test.admin.kademi.com.au/websites/duc-test-bs/version1/#panel_apps-tab
