### ISSUE TITLE
Cannot edit image in Keditor

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3368]
http://kademi.admin.kademi.us/

http://kademi.admin.kademi.us/funnels/website-enquiries/emailAction-f6db01/#message-tab

Showing wrong options, we should show option to edit image

![image](https://user-images.githubusercontent.com/20508726/27018282-62424e6c-4f59-11e7-97b3-f517e2f52893.png)

**Comment by ducdhm** [comment]
Already fixed. Need to deploy!

**Comment by hoanglinhlan** [comment]
passed
