### ISSUE TITLE
Deleting a course and program does not remove from group

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#337]
When you delete a course or program then go to a group where that course was assigned, it is still visible in the group and cannot be removed.

**Comment by bradmac** [comment]
Note that Kademi supports multiple versions of a site, so the fact that a course or program is deleted from one version does not mean its deleted in any other. For example, your might delete a program in a draft version, but if that immediately removed enrolement from the live version it would be a disaster!

So it is correct that the enrolement is not changed by deleting a course or program, it MUST be that way.

However, you should be able to remove an enrolement regardless of whether it has been deleted.

**Comment by bradmac** [comment]
We should add a delete button to the enrolements, instead of using "Not available" as a selection
