### ISSUE TITLE
Demo creation issues

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3375]
Should we set the roles on the group for Redeemer and content viewer by default?

Should we create a website already linked to the group?

Import products goes to page not found http://testreward5.admin.kademi-prod.com/products/upload

Product images are not uploading, i.e. the cannot be found  http://testreward5.admin.kademi-prod.com/products/breville-blender/#panel_details-tab

Could not find the points management page, nor award points to user via their profile.

**Comment by bradmac** [comment]
Mostly done. Still need to sort out images ( @tuzzmaniandevil ?) and link the group to the website

**Comment by bradmac** [comment]
Now adding the group to the website when the rewardstore app is enabled. Also fixed image cropping
