### ISSUE TITLE
Table Uploaders: Be able to save configuration

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#3378]
This should save any options provided by the app and also the field mappings.

**Comment by hoanglinhlan** [comment]
hi @tuzzmaniandevil 
**for user uploader**: just showing none on 
https://lan-test.admin.kademi.com.au/tableUploaders/usersUploader
![image](https://user-images.githubusercontent.com/20508726/27221796-0c82c674-52b4-11e7-9df8-8112eb9a4d23.png)

for org uploader: it's not showing anything
https://lan-test.admin.kademi.com.au/organisations/upload

**Comment by tuzzmaniandevil** [comment]
Have you saved any configurations yet? Itbwill only show the ones you saved  :-)
