### ISSUE TITLE
Integrate leadman analytics page with common date selector

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3380]
Eg, see http://itsinsuredqa-crm.kademi.com.au/analytics/acquisition

Where we show active leads this will not be affected by date range. The date range should only apply to leads completed in the specified date range
- closed deals in the funnel
- the histogram and circles in the left hand panel

![image](https://user-images.githubusercontent.com/826458/27113218-b88124bc-510f-11e7-98f5-17949f840288.png)

**Comment by mkhoudary** [comment]
This is done..
