### ISSUE TITLE
Menu editor: option to control visibility of menu items by group

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3384]
We would like to be able to choose whether menu items are shown
- for all users
- for anonymous users only
- for users in a specified group only

![image](https://user-images.githubusercontent.com/826458/27115214-44a068f6-511d-11e7-85da-2a49f5ffae0e.png)

**Comment by bradmac** [comment]
I've changed the "hidden" propertly on MenuConfigItem to be string, so i suggest we use values
- blank or "false" visible for all users
- "true" not visible for any user
- "anon" - only visible for not logged in users
- [group name] - only visible for a specific group

**Comment by ducdhm** [comment]
Done! @bradmac Can you add backend stuff to handle other values of "hidden" property?

**Comment by bradmac** [comment]
Done! But @ducdhm the selected value of the drop down is not being redisplayed, looks like there is nothing in the form init js to set the current value of the dropdown

**Comment by bradmac** [comment]
@ducdhm be great if you can finish this off today

**Comment by ducdhm** [comment]
It should work now :)

**Comment by hoanglinhlan** [comment]
showing "loading..." text under menu items
![image](https://user-images.githubusercontent.com/20508726/27577853-58c24ece-5b4c-11e7-9400-9a2de975aadf.png)

http://lantest1.admin.kademi-prod.com/pages/c5s-rewardstore001/version1/
http://version1.c5s-rewardstore001.kademi-prod.com/contenteditor?fileName=p18248.html&miltonUserUrl=/users/hoanglinhlan&miltonUserUrlHash=ed6236e4-6569-4f71-88a3-c29ff260fc38:6f4KiyDzGr2DLmvoRi_psDngdSE

**Comment by ducdhm** [comment]
Fixed!

FYI: In first time, when `menu.json` doesnt exist, will fallback to using menu item data in template

**Comment by hoanglinhlan** [comment]
passed
