### ISSUE TITLE
Manage application page: Button is disapear after I click to change status

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#3385]
http://lantest1.admin.kademi-prod.com/manageApps/#installed-tab

![image](https://user-images.githubusercontent.com/20508726/27121084-25737f2a-5110-11e7-9b0c-fa3c7df33769.png)

**Comment by ducdhm** [comment]
@bradmac Seem like `isCore` of  `AppControlBean` is not working in manageApps screen

**Comment by bradmac** [comment]
@ducdhm please try now
