### ISSUE TITLE
Support getting voucher by user for Voucher App

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#3389]
Need for https://github.com/Kademi/client-emc-airnz/issues/126

**Comment by tuzzmaniandevil** [comment]
There are 3 methods on the VouchersApp to accept a Profile, ProfileBean or UserResource

example:
```
$applications.vouchersApp.getVouchersForUser($profile)
```

**Comment by tannguyen3489** [comment]
@tuzzmaniandevil : the method always returned empty. Please recheck !

**Comment by tannguyen3489** [comment]
it works well
