### ISSUE TITLE
Update EWay error descriptions

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#339]
Invalid EWAY_CARDNUMBER
“Please enter a valid credit card number.”

Invalid Card Number
“Please enter a valid credit card number.”

Invalid EWAY_CARDEXPIRYYEAR
“Please enter a valid expiry date.”

Invalid Customer Phone
“Please enter a valid phone number.”

Invalid Amount
“Invalid donation amount. Please check your information, and try again.”

Expired Card
“Your card seems to be expired. Please check your information, and try again.”

No Credit Account
“There appears to be no credit on your account. Please contact your bank.”

Insufficient Funds
“There appears to be no credit on your account. Please contact your bank.”

Stolen Card
“There seems to be an issue processing your credit card. Please contact your bank.”

Suspected Fraud
“There seems to be an issue processing your credit card. Please contact your bank.”

Exceeds Withdrawal Limit
“There seems to be an issue processing your credit card. Please contact your bank.”

Amex Declined
“There seems to be an issue processing your credit card. Please contact your bank.”

Challenged Fraud
“There seems to be an issue processing your credit card. Please contact your bank.”

Country Match Fraud
“There seems to be an issue processing your credit card. Please contact your bank.”

High Risk Country Fraud
“There seems to be an issue processing your credit card. Please contact your bank.”

Anonymous Proxy Fraud
“There seems to be an issue processing your credit card. Please contact your bank.”

Transparent Proxy Fraud
“There seems to be an issue processing your credit card. Please contact your bank.”

Undefined Fraud Error
“There seems to be an issue processing your credit card. Please contact your bank.”

Risk Score Fraud
“There seems to be an issue processing your credit card. Please contact your bank.”

Suspicious Customer First Name
“There seems to be an issue processing your credit card. Please contact your bank.”

Suspicious Customer Last Name
“There seems to be an issue processing your credit card. Please contact your bank.”

Invalid Billing Street
“Invalid street address detected. Please check your entries and try again.”

EWAY_CARDHOLDERNAME Required
“Please check your credit card details and try again. If problems persist please contact your bank.”

EWAY_CARDNUMBER Required
“Please enter a valid credit card number and try again.”

EWAY_CARDCVN Required
“Please enter a valid CVN number and try again.”

Invalid Expiry Date
“Please enter a valid expiry date and try again.”

Invalid Issue Number
“Please check your credit card details and try again. If problems persist please contact your bank.”

**Comment by skwidge** [comment]
@bradmac new error messages committed and pushed

**Comment by bradmac** [comment]
Add another one:
TRANSACTION_RESPONSE_MESSAGE_MAP.put("D4405", "Do Not Honour");

“Please check your credit card details and try again. If problems persist please contact your bank.”

**Comment by bradmac** [comment]
Done
