### ISSUE TITLE
Cannot upload an image via Keditor

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3390]
http://kademi.admin.kademi.us/funnels/emoticon/emailAction-ed2b2c/#summary-tab

http://kademi.admin.kademi.us/funnels/emoticon/emailAction-ed2b2c/#message-tab

Click change photo, try to upload image.  It fails to upload and show.

**Comment by ducdhm** [comment]
Fixed! Should work on QA Server

**Comment by hoanglinhlan** [comment]
passed
