### ISSUE TITLE
Manage Auctions page: date range is not working

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#3392]
https://github.com/Kademi/kademi-dev/issues/2152#issuecomment-308648994

I choose 7 day ago from date range but in autions table, it's showing autions from 3 month ago
https://lan-test.admin.kademi.com.au/auctions/?state=closed
![image](https://user-images.githubusercontent.com/20508726/27169603-b951e7b2-51d4-11e7-8199-9564e2f5c5da.png)

please filter by start Date

**Comment by hoanglinhlan** [comment]
hi @tannguyen3489 
it's still not working
http://lantest1.admin.kademi-prod.com/auctions/

**Comment by tannguyen3489** [comment]
it was fixed.

**Comment by hoanglinhlan** [comment]
passed
