### ISSUE TITLE
KCRM: the tasks page should allow seeing all tasks in the team

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#3393]
**profile login:** https://lan-test.admin.kademi.com.au/manageUsers/74497161
**login to** http://hattonfake.kademi.com.au

**Comment by hoanglinhlan** [comment]
on QA server
http://lantest1.admin.kademi-prod.com/websites/hattonfake001/version1/#panel_apps-tab
http://version1.hattonfake001.kademi-prod.com/dashboard
I click to create a task menu and put the task's name then save
but this task is not showing in task page 
http://version1.hattonfake001.kademi-prod.com/tasks/

**Comment by mkhoudary** [comment]
Tasks appear normally..
But to use such feature you must be logged in with a user that belongs to sales group..

**Comment by bradmac** [comment]
hey guys, let me know if there is a useability issue here. If we're not going to show tasks for some reason, then we should communicate that to the user.

**Comment by hoanglinhlan** [comment]
hi @mkhoudary 
please use this profile to check
http://lantest1.admin.kademi-prod.com/manageUsers/74549/#summary-tab
the tasks page should allow seeing all tasks in the team (assigned to themself, not assigned, and assigned to others in the same team). but current the task page just showing only tasks what assigned to this profile

**Comment by mkhoudary** [comment]
The sales group in this site lacks "SalesTeamViewer" role which allowed what you are asking..
