### ISSUE TITLE
reward store - checkout page: product's point should be a base cost from Product if SKU cost is  blank

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#3399]
Profile login: https://lan-test.admin.kademi.com.au/manageUsers/41267184/#pointsBucketTab-tab
Product to check: http://c5s.kademi.com.au/c5s-business/Samsung/Samsung-Phone/samsung-phone01/
Product's base cost: 130
Product cost in SKU: 100
in frontEnd page, select this product then go to checkout page
==> it should be use product cost in SKU
![image](https://user-images.githubusercontent.com/20508726/27216132-8dd4a82a-529e-11e7-87df-d47c7cdd7712.png)

**Comment by tuzzmaniandevil** [comment]
To use SKU's you need to tick the "Use Inventory Control" on the Reward Store app settings

**Comment by hoanglinhlan** [comment]
hi @tuzzmaniandevil 
I ticked the "Use Inventory Control" on the Reward Store app settings
but it's still not working

**Comment by bradmac** [comment]
@hoanglinhlan if you're viewing in the front end you will need to reindex after changing that setting

**Comment by hoanglinhlan** [comment]
it's work now
