### ISSUE TITLE
K-editor padding not remembered on button

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3401]
http://kademi-prod.com/groupEmails/74643/#messages-tab
http://kademi-prod.com/groupEmails/74643/edmeditor?fileName=index.html&useHash=true

After setting the padding, the values return to zero but the padding remains in the button.

When a button is dropped onto a canvas, it should default padding.  at the moment padding it set to 0 and button does not look like a button.

![image](https://user-images.githubusercontent.com/2201340/27218030-bce4ed3e-52bf-11e7-9098-7cf7b7d01764.png)

**Comment by ducdhm** [comment]
Fixed! Can test on QA server
