### ISSUE TITLE
orgsLocator: not working

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#3402]
https://github.com/Kademi/kademi-dev/issues/2837
**Editor**: 
http://version1.c5s.kademi.com.au/contenteditor?fileName=p2704.html&miltonUserUrl=/users/lan&miltonUserUrlHash=8c16cfc1-7da8-4baa-aad2-a0d8a14113cd:Nynn4H7qdlYjU4m4TLZUvyyvzjQ
**FrontEnd**:
http://version1.c5s.kademi.com.au/p2704.html?miltonUserUrl=/users/lan&miltonUserUrlHash=cf29b9b7-ad95-4f1a-b710-ee9e32c3535f:ILvJF3XWKgnY3trR147cdPqbU1I

**org to check**: https://lan-test.admin.kademi.com.au/organisations/41265574/edit

![image](https://user-images.githubusercontent.com/20508726/27220029-e2570348-52ad-11e7-90b6-e04e39829028.png)

1: on frontEnd, after click to org, map is showing wrong location 
2: map's ratio is too much 
3: click to select some org in list, point location is not move (please zoom out to view this issue, )
4: list org is still showing an org what removed in backEnd ( RAWENE JOYCE LIMITED)

**Comment by ducdhm** [comment]
@hoanglinhlan 

```
1: on frontEnd, after click to org, map is showing wrong location
```
All your location lat and long is 0.0 so orgLocator is working normally.

```
2: map's ratio is too much
```
Nope. Default zoom level is 15 so it's ok

```
3. click to select some org in list, point location is not move (please zoom out to view this issue, )
```
Same with 1, you NEED to update LATITUDE and LONGITUDE for all your locations

 ```
4. list org is still showing an org what removed in backEnd ( RAWENE JOYCE LIMITED)
```
Just need to re-index `org` index and RAWENE JOYCE LIMITED is not showing!
