### ISSUE TITLE
Table uploader: save configuration is not working

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#3403]
https://github.com/Kademi/kademi-dev/issues/3378
hi @tuzzmaniandevil 
**for user uploader**: just showing none on 
https://lan-test.admin.kademi.com.au/tableUploaders/usersUploader
![image](https://user-images.githubusercontent.com/20508726/27221796-0c82c674-52b4-11e7-9df8-8112eb9a4d23.png)

**for org uploader**: it's not showing anything
https://lan-test.admin.kademi.com.au/organisations/upload

**Comment by tuzzmaniandevil** [comment]
Have you saved any configurations yet? It will only show the ones you saved :-)

I haven't  moved the org importer  to the new framework  yet

**Comment by hoanglinhlan** [comment]
passed
