### ISSUE TITLE
KCRM: should be change avatar if user click to their avatar

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#3404]
https://github.com/Kademi/kademi-dev/issues/3361
hi @mkhoudary 
current, avatar's link just a link to current lead page. so I think it will be good if user can change their avatar when they click to avatar image 

![image](https://user-images.githubusercontent.com/20508726/27222514-b27ccb54-52b6-11e7-821e-68405afba234.png)

**Comment by mkhoudary** [comment]
Done

**Comment by hoanglinhlan** [comment]
it's not working in QA server 
profile http://lantest1.admin.kademi-prod.com/manageUsers/74549
http://hattonfake001.kademi-prod.com/leads/76327/

**Comment by mkhoudary** [comment]
You should update the leadman-lib to the latest version..

**Comment by bradmac** [comment]
@hoanglinhlan please remember to test with new accounts each time so you are always starting from a known state. You should not re-use old test accounts.

**Comment by hoanglinhlan** [comment]
passed
