### ISSUE TITLE
Journey Builder: Authoring email content

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3406]
Not all emails automated via journeys will be HTML where the body is centered, with images etc, many are made to look like they have been typed by someone and personally sent.  This can have a greater conversion rate.  Currently Keditor does not support the ability to change the canvas setting to 100% wide so a personal styled email can be created.

Suggested options:

1) Change Keditor so this can be achieved
2) The edit button has two options 1) Rich HTML using Keditor  2) Plain Text (which uses our standard WYSIWYG editor 

![image](https://user-images.githubusercontent.com/2201340/27250272-e37b8bd4-536d-11e7-8f63-9d3aebc29e60.png)

**Comment by bradmac** [comment]
I think option 1) is best

**Comment by bradmac** [comment]
Also, i think the editor should be on the page, rather then opening a seperate tab

**Comment by paddyow** [comment]
Agreed with the above, when you click 'Manage email' it takes you away from the JB experience and feels disconnected.

**Comment by ducdhm** [comment]
@paddyow I think you misunderstood @bradmac. He mentioned that we'll show edm inline/embed in page instead of showing modal when click on edit message.

**Comment by ducdhm** [comment]
and IMHO, I prefer second option because edmEditoris supporting 600px width only and it's fixed. It's complicate to allow edmEditor to support 100% (full-width). And as you remember, all components which contains photo and cols container are depended on 600px.

**Comment by bradmac** [comment]
OK, second option is fine. The problem is that if a user creates the email by one editor, then open it with the other, it will be all screwy. So ideally we would lock the editor for an email

**Comment by anhnt** [comment]
I've added text editor support. @bradmac please help me with "lock editor for an email" part

![image](https://user-images.githubusercontent.com/735555/28306443-8362709a-6bc9-11e7-96f8-4210fcf0f7f2.png)

**Comment by bradmac** [comment]
I think its fine as it is
