### ISSUE TITLE
Independent funnels

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3407]
At the moment it seems a funnel is tied to the created journey. 

In the case of an acquisition funnel with say 4 stages, there might be multiple journeys created for different campaigns, but with the same end goal, so it makes sense for different journeys to be created that link to the same funnel.  From a analytics perspective, this is simpler vs. say running 5 campaigns, each with a journey and funnel.

- Split funnels out where a funnel can be created
- When a journey is created, a funnel is selected

**Comment by mkhoudary** [comment]
@paddyow can you give us a certain example? this can be solved using start funnel goal action, but I need a clear example to check if it works analytically too.

**Comment by bradmac** [comment]
@paddyow A journey is a journey, and the stages represent progress towards an ultimate goal. If you have different ways of reaching that end goal then they should just be different flows within the one journey.
