### ISSUE TITLE
Specify checkout to pull ORG address

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3412]
Update or create new checkout component 

- User adds product to checkout
- The checkout needs to pull the address from the users org
- The address needs to be locked

This is a requirement from an administration workflow where all orders need to be sent to the users work address.

**Comment by bradmac** [comment]
@mkhoudary please make the following updates to shoppingCartFormComponent.html
- create a settings form
- have a checkbox setting for 'use organisation address'
- have a select box setting for 'organisation type' which displays all org types
- when rendering with the checkbox is enabled, get a list of orgs as follows
  - if an orgtype is selected find all orgs attached to the user with that orgtype
  - if no orgtype is selected, get the orgs from all primary memberships
- if there is only one org (the normal use case) just fill input fields and make them readonly
- if there are multiple orgs, try to find one using the selectedOrg cookie (ie see orgSelectorComponent.html). If no cookie is available then just use the first in the list. Use that to fill the inputs and make them readonly
- if multiple orgs also display a select box to allow the user to select one. When selected, change the fields to that org.

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/27725903-97f608da-5da2-11e7-9fe0-989fbb67b141.png)

**Comment by anhnt** [comment]
Done in shoppingcart-lib 1.0.5

**Comment by AlaaKhalaf94** [comment]
passed
