### ISSUE TITLE
Update Points Uploader button

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3413]
http://allstarrewards.admin.kademi.us/rewards/points/

Should use the new uploader:
![image](https://user-images.githubusercontent.com/2201340/27268901-0c77d4be-54f6-11e7-8d1a-a1ae594b676e.png)

Change button text to 'Upload file' as we now support options other than CSV.

New uploader http://allstarrewards.admin.kademi.us/tableUploaders/pointsUploader

**Comment by ducdhm** [comment]
New UI:
![newui](https://user-images.githubusercontent.com/1289631/27315812-0a0d99ba-55a6-11e7-91ba-e7c839e9f84b.png)
