### ISSUE TITLE
e-com checkout page: it's showing 2 items for 1 product

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#3414]
https://github.com/Kademi/kademi-dev/issues/3279
profile login 
https://lan-test.admin.kademi.com.au/manageUsers/41267184/#summary-tab

- go to e-com page, select one  product then click add to cart 2 times.
- go to e-com checkout page, it should be showing 1 row with quantity = 2 for this product . current,  it's showing 2 items for 1 product

![image](https://user-images.githubusercontent.com/20508726/27272626-577ae1be-54f5-11e7-9229-8be97e7a5895.png)

**Comment by tuzzmaniandevil** [comment]
@hoanglinhlan Did you enter different details for the fields when adding it to the cart? If so then it will show as 2 different items. 

![screenshot from 2017-06-20 11-13-51](https://user-images.githubusercontent.com/3378330/27309699-93a86918-55a9-11e7-9940-1e9f62748d40.png)

**Comment by hoanglinhlan** [comment]
hi @tuzzmaniandevil 
I just add product, dont put anything because this product has not extra field

**Comment by bradmac** [comment]
@hoanglinhlan that product "samsung01" does have order options:

https://lan-test.admin.kademi.com.au/products/samsung01/#variants-tab

"firstName", etc

**Comment by hoanglinhlan** [comment]
hi @tuzzmaniandevil 
please re-check with new data 
profile: http://lantest3.admin.kademi-prod.com/manageUsers/158548/#summary-tab
login to c5s-ecom site, then select a product 
http://003c5s-ecomstore001.kademi-prod.com/03c5secom-us/

**Comment by Uafinder** [comment]
It looks ok at the moment
