### ISSUE TITLE
KCRM: Search does not work

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3416]
http://kcrm.kademi.us/dashboard

1) There is some random search copy appearing
2) Cannot search for a lead (nothing happens)

![image](https://user-images.githubusercontent.com/2201340/27274375-552ca1d8-5516-11e7-813b-d4ad08e6588a.png)

**Comment by bradmac** [comment]
This is because we have 2 searches
- leadman search
- website search

And they dont both fit. 

A couple of options
- adapt the standard search to show search results from enabled apps. This would mean having a common way of displaying different types of search results.  Eg if blogs and leadman were enabled, we would display blog articles and leads together
- break the dependency between leadman and search app, so the search app box doesnt get displayed

**Comment by mkhoudary** [comment]
I will go with no. 2 if there's no problem with Paddy?

**Comment by bradmac** [comment]
Just thinking about this, I think we will have situations where a customer wants to use leadmanagement along with other apps such as blogs or elearning. Eg a company might want their salesreps to have elearning about sales.

With option 2 that would mean we have 2 search boxes in the navbar which is what we have now and looks horrible.

So option1 might be better.

But we might want to change this a little to be more of a conventional omni-search like we have in the admin. So it would display a compact dropdown list of search results which would display results from all enabled search compatible apps. The existing leads page which has a specific lead search would remain unchanged

@mkhoudary what do you think?

**Comment by paddyow** [comment]
Hey guys, something I have been thinking about.

When I search in KCRM I want to return results for:
- Leads
- Contacts
- Companies
- Tags

For example I might want to search for leads relating to the tag FMCG 
Or search for a specific company to edit it's details or see contacts linked to that company
Or find a contact that might not have a lead linked to it

For example:
![image](https://user-images.githubusercontent.com/2201340/27414696-42406bfe-5746-11e7-8b41-336ed0dc2f80.png)

**Comment by bradmac** [comment]
Yep, so that is the omnishearch option i mentioned above. Note that this will not be specific to leadman, it will be a change to our search app and will return any type of data depending on what apps are enabled.

**Comment by paddyow** [comment]
Lets do omni search.

**Comment by bradmac** [comment]
@mkhoudary I've made a start

I think our approach should be this:
- handle a new request param called omniQuery in ContentSearchPage. This will output a fragment containing search results, not a whole page
- this will call a new method on SearchManager called omniSearch (i've started)
- the SearchManager will collect a list of AppIndexers which want to be included and get them to add their search fields (done). It will execute the search and then iterate over the searchits in the ES response
- For each hit, find the related AppIndexer by the type, and call the renderOmniResult method to render the result to a stringbuilder

ContentSearchPage writes the result to the output

**Comment by bradmac** [comment]
Have added OmniSearchAppIndexer and moved the new methods to it

Only implemented 2 indexers, leads and tasks. We might also want to add ProfileAppIndexer and OrgAppIndexer ... maybe

**Comment by bradmac** [comment]
Actually... i can see a problem with that approach. I think it would be better abstracted at the application level, and just let apps add whatever criteria they want to the ES search. That way the LeadManApp can include the profile and orgs indexes, but filter for only lead profiles and orgs

**Comment by bradmac** [comment]
Righto. So now SearchManager has this:
```
public KSearchResponse omniSearch(String searchPhrase, Integer pageSize, Integer pageNum) {
```

And we have this app interface
```
public interface OmniSearchApplication extends Application{

    /**
     * Return
     *
     * @param searchPhrase
     * @param outputFields
     * @return
     */
    QueryBuilder buildOmniQuery(String searchPhrase, Set<String> outputFields);

    bool renderOmniSearchHit(OutputStream out, SearchHit hit);
}
```

I think ContentSearchPage can call this, and then iterate over the hits. ContentSearchPage will get a list of all OmniSearchApplication's active in the website and call renderOmniSearchHit for each hit. Each OmniSearchApplication will only render documents it knows about and will return true which will cause the ContentSearchPage to break out of the loop. That will avoid multiple renderings of the same result.

The implementations of OmniSearchApplication (eg LeadManApp) will call a TextTemplater to render the fragment to the outputstream

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/27668632-782ad8a4-5cd6-11e7-81f1-e2635ada8247.png)

**Comment by bradmac** [comment]
See search.js
```
function initContentSearch() {
    flog("initContentSearch");

    var txtKeyword = $("input[name=omni]");
    var searchResults = $('#omni-search-suggestions');
    txtKeyword.on({
        keyup: function () {
            var query = $(this).val();
            typewatch(function () {
                flog("do search ", query);
                // Load fragment
                try {
                    var href = 'contentSearch';
                    $.ajax({
                        url: href,
                        type: 'GET',
                        data: {
                            omni: query.trim()
                        },
                        dataType: 'html',
                        success: function (data) {
                            flog("complete");
                            searchResults.html(data);
                            searchResults.removeClass("hide");

```

**Comment by bradmac** [comment]
and searchPortlet.html

```
        <div class="input-group">
            <input type="text" name="omni" placeholder="Search" class="form-control" style="width: 120px" />
            <span class="input-group-btn">
                <button class="btn btn-default" type="button">&nbsp;<i class="glyphicon glyphicon-search"></i>&nbsp;</button>
            </span>
        </div>
    </div>
    <ul id="omni-search-suggestions" class="hide"></ul>
```

**Comment by bradmac** [comment]
And see leadman/leadProfileOmniSearchResult.html for the rendering:

```
<li class="search-suggestion" >
    <a href="/custs/$!searchResult.userId">
        <span>$!searchResult.source.nickName</span> 
        &ndash; 
        <span class="text-info">$!searchResult.source.email</span>
        <br/>
        <small class="text-muted">$!searchResult.source.firstName $!searchResult.source.surName</small>
    </a>
</li>
```

**Comment by ducdhm** [comment]
Done!

**Comment by ducdhm** [comment]
I also add UP and DOWN button to select suggestion item. Press ENTER to click on selected suggestion item

**Comment by bradmac** [comment]
@ducdhm can you please make the omni search results hide when the user clicks away, like in the admin?

**Comment by ducdhm** [comment]
Done!

**Comment by bradmac** [comment]
Is now integrated with leads and profiles. Content comes later

**Comment by hoanglinhlan** [comment]
it's not working
profile to login: http://lantest06.admin.kademi-prod.com/manageUsers/143902
site to test: http://006hattonfake001.kademi-prod.com/dashboard

**Comment by mkhoudary** [comment]
You need to install search-lib from marketplace to get new search working, @ducdhm I think Website Search app should have search-lib as a dependency.
