### ISSUE TITLE
Journeys: Funnel 'Lead Group' should not show 'Group Tags'

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3417]
http://kademi.admin.kademi.us/funnels/investors/#properties-tab

![image](https://user-images.githubusercontent.com/2201340/27274608-643e7984-5517-11e7-8798-78fbfe168feb.png)

**Comment by bradmac** [comment]
Fair enough, just show primary and subscription groups.

**Comment by AlaaKhalaf94** [comment]
passed
