### ISSUE TITLE
Journeys: Cannot save or set the lead group

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3418]
http://kademi.admin.kademi.us/funnels/investors/#properties-tab

When I add a title of 'Investors' and select the group 'Investors' and click save, it does not save.

**Comment by bradmac** [comment]
Actually it is saving, which you can see in the json file:
```
    "title": "Investors",
    "leadsGroup": "investor",
```

But its not redisplaying

**Comment by tuzzmaniandevil** [comment]
defaultInitialGoal has been removed from Funnel but wasn't set as ignored. I've manually removed it from the JSON and have also made it ignore-able

**Comment by hoanglinhlan** [comment]
passed
