### ISSUE TITLE
Handling deleted leads and such

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3422]
There was once a drop down to change the funnel for a lead.  We have leads right now with no funnel and need to set the funnel to delete the lead.

![image](https://user-images.githubusercontent.com/2201340/27281228-4c3765d2-552e-11e7-8460-2b94969ec91a.png)

**Comment by mkhoudary** [comment]
Done

**Comment by bradmac** [comment]
Hey guys, we dont want to allow users to change the funnel for a lead, because this will put the lead into an inconsistent state. Thats why we removed the ability to change funnels.

So @mkhoudary can you please remove this?

@paddyow if you're have an issue deleting leads lets just address that directly

**Comment by paddyow** [comment]
@bradmac here are things I need to do:

We have leads who are not in a funnel (due to the journey being deleted) so I cannot cancel the lead as the lost reason drop down in KCRM does not work due to the values being tied to the funnel setup.  Nor can I delete the lead from the admin as there is no where to find a lead that is not in a funnel.

I want to delete contacts which are spam related, the only way to do this is via manage users.  So I would have to 1 cancel the lead then 2 delete the profile from the admin which is a pain.

What do you suggest?

**Comment by paddyow** [comment]
@mkhoudary 

On the KCRM contact page http://kcrm.kademi.us/custs/
- Add check boxes to each row, so multiple contacts can be selected then deleted 
- The contact page should also have an independent delete button http://kcrm.kademi.us/custs/manega2110/
- When a contact is deleted, all leads associated with the contact need to be deleted 
- The contacts page is not showing contacts in KCRM, please look into this

In the admin:
- Need a screen to find leads, even those that are not in a funnel and be able to delete them
- Be able to select more than one lead using check boxes
- Have a drop down delete option: Delete lead OR Delete lead & contact 

Deleting a journey in the admin:
- When someone deletes a journey from here  http://kademi.admin.kademi.us/funnels/
- The journey, funnel and the leads in the funnel should be deleted
- Show the following message before the journey is deleted

"Deleting a journey will permanently delete your journey steps, funnel and all leads associated with your funnel.  Are you sure you want to continue?"

You can also use this icon in the alert popup http://fontawesome.io/icon/exclamation-triangle/

**Comment by gonzalon** [comment]
-Delete in /custs/
![image](https://user-images.githubusercontent.com/2773216/31696795-32bbc080-b410-11e7-95b4-8a08a4dfa7b8.png)

-Delete in the customer details page

![image](https://user-images.githubusercontent.com/2773216/31696804-4c0942f6-b410-11e7-9cbc-9b184ca79b23.png)

- When deleting the customer also will delete the lead
- Seems that's working fine atm: http://kcrm.kademi.us/custs/


In the admin:
- The page for leads is: /leads/ 
- Delete options for deleting the leads
![image](https://user-images.githubusercontent.com/2773216/31696914-d525413e-b410-11e7-85ce-7f160b6d99bd.png)


Funnel:
- Also delete the asociated leads
![Uploading image.png…]()

**Comment by AlaaKhalaf94** [comment]
Hi @gonzalon , when I try to delete journey1 here : http://alaa5.admin.kademi-ci.co/funnels/
It shows me an error , and told me that the Funnel deleted
and the Funnel doesn't deleted

![capture1](https://user-images.githubusercontent.com/26510030/31721332-c5f66b96-b421-11e7-8d5b-6f677177bfdc.PNG)


![capture2](https://user-images.githubusercontent.com/26510030/31721340-ca92fde0-b421-11e7-9253-b884d5174588.PNG)

and please use this icon in the alert popup http://fontawesome.io/icon/exclamation-triangle/

**Comment by AlaaKhalaf94** [comment]
passed
