### ISSUE TITLE
reward store: config of product detail auto set 0.0 

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#3424]
https://github.com/Kademi/kademi-dev/issues/3180#issuecomment-309369474
after saved, it's auto set 0.0 for margins, GST and point mutilier
![image](https://user-images.githubusercontent.com/20508726/27281848-dc43c862-5517-11e7-9e57-483487901c59.png)

**Comment by tuzzmaniandevil** [comment]
Added a fix

**Comment by hoanglinhlan** [comment]
passed
