### ISSUE TITLE
Past order ecomerce: showing duplicate row 

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#3425]
https://github.com/Kademi/kademi-dev/issues/3356
profile login 
http://lantest1.admin.kademi-prod.com/manageUsers/69705
link to page
http://c5s-ecomstore001.kademi-prod.com/past-orders.html

![image](https://user-images.githubusercontent.com/20508726/27282680-2d333804-551b-11e7-9556-36b1da92bde1.png)

**Comment by tannguyen3489** [comment]
the reason is the checkout page shows duplicate products.
