### ISSUE TITLE
Inline ckeditor broken

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#3427]
![image](https://user-images.githubusercontent.com/735555/27316747-17895a74-55ac-11e7-8a20-e167fda2d3a9.png)

**Comment by anhnt** [comment]
fixed

**Comment by AlaaKhalaf94** [comment]
it is still broken

**Comment by ducdhm** [comment]
Already fixed! Need to deploy!

**Comment by hoanglinhlan** [comment]
passed
