### ISSUE TITLE
Cant change upcoming-event-range

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#3429]
https://github.com/Kademi/kademi-dev/issues/3360
Profile to login: http://lantest1.admin.kademi-prod.com/manageUsers/69705/#summary-tab
http://c5s-rewardstore001.kademi-prod.com/dashboard

after I changed upcoming event range, it's alway re-set to 30days

**Comment by mkhoudary** [comment]
To get this working you should have an extra field in the user group named: upcoming-event-range..

I've added it, please check now..

**Comment by hoanglinhlan** [comment]
hi @mkhoudary 
so if our customer want to use upcoming events panel, they need create this extra field. 
why do I need this extra field in the user group? Do we have any way to use this pânel without this extra field

**Comment by mkhoudary** [comment]
As agreed with Brad, we will be having a default value set at the component level, but we will still need the extra field to be able to set that for each user separately.
