### ISSUE TITLE
Calendar page: dont show list Coming events

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#3430]
after I create a new event, it's not showing in calendar and in list Coming events
http://lantest1.admin.kademi-prod.com/Calendars/Techtalk/

**Comment by mkhoudary** [comment]
@bradmac the problem actually was with displaying the calendar events .. I tried to reproduce locally but with no luck.. then I restarted the instance and everything worked just fine.. but after a bit Lans site doesn't open anymore.. I either get error 500 or This page isn’t working.. console log window in Jenkins doesn't respond.

**Comment by bradmac** [comment]
@tuzzmaniandevil can you investigate please?

**Comment by bradmac** [comment]
Fixed
