### ISSUE TITLE
calendar lib js error

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#3437]
move all inline js to standalone js
remove 
```
#parse("/theme/masterTemplate.html")
#@render()
#end
```

Fix js error that causes content editor not load

**Comment by bradmac** [comment]
@tannguyen3489 is this complete now?

**Comment by tannguyen3489** [comment]
Anh want me to move all js codes in velocity files in all libs to the standard js file. Currently, I am on leadman-lib.
