### ISSUE TITLE
Task takes a long time to appear on KCRM dashboard

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3439]
Note this only occurred within the past hour:

Create a lead here: http://www.kademi.co/solutions/trade-program-1.html

This JB creates a task: http://kademi.admin.kademi.us/funnels/loyalty-rewards-campaign/#journeyBuilder-tab

Tasks take about 10 minutes to appear on incoming dashboard in KCRM http://kcrm.kademi.us/dashboard

**Comment by bradmac** [comment]
The task node is after the email delivery node. So the task wont appear until how ever long it takes to successfully deliver the email.

**Comment by paddyow** [comment]
This is now working.
