### ISSUE TITLE
frontEnd leads page: should have a column to show current journey of lead 

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#3442]
leads page is showing 1 lead for each journey, if we dont have column to show current journey, it's quite difficult to find a lead

![image](https://user-images.githubusercontent.com/20508726/27416175-e53cb4cc-5735-11e7-84fa-5c7a9bc6f9d4.png)

**Comment by bradmac** [comment]
:+1:

**Comment by gonzalon** [comment]
New version of leadman 1.3.6 


![image](https://user-images.githubusercontent.com/2773216/30674750-50dc63f8-9ed0-11e7-97d9-b0506503bd92.png)

**Comment by AlaaKhalaf94** [comment]
passed
