### ISSUE TITLE
Leadman tags list

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3444]
Currently the list of available tags is embedded as json in the page
```
<input type="text" id="view-lead-tags" placeholder="Type to Add Tags" value="$selectedTags" />
```

Please change this to use ajax to load the list only when needed

**Comment by mkhoudary** [comment]
These are the already selected tags not the list of available tags, available tags are loaded using ajax in viewLead.js line 584

**Comment by bradmac** [comment]
OK, but i'm getting a parse exception in JS. I think we're always going to have parsing problems using this approach. I suggest instead setting the selected tags into a JS variable and using a page init script to set the selected tags.
```
<script>
var tags = $selectedTags ;
setTags(tags);
```

**Comment by salehh93** [comment]
Hey @bradmac  I see no problem !

**Comment by bradmac** [comment]
OK, will leave that for now
