### ISSUE TITLE
Version button broken

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3445]
Cannot version a website from website management page
http://kademi.admin.kademi.us/websites/kademi-www/version57/#

Clicking on the version icon does not open the version dialogue.

**Comment by ducdhm** [comment]
I see this error message

```
/templates/themes/admin/

Line: 390, Column: 105

Invocation of method 'getDKimDnsTxt' in class io.milton.cloud.server.apps.website.ManageWebsiteBranchFolder threw exception java.security.GeneralSecurityException: Reading CA private key failed at kademi.admin.kademi.us:/theme/apps/admin/manageWebsite.html[line 390, column 105]
```

**Comment by tuzzmaniandevil** [comment]
There was an error parsing private key's after updating BouncyCastle. I've corrected this and a few other bugs and added Unit Tests

**Comment by tuzzmaniandevil** [comment]
Tested and working
