### ISSUE TITLE
Comms getting sent at wrong time

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3452]
This trigger http://admin.minda.olhub.com/autoEmails/120049291/#triggers-tab
Is set to trigger at 5:47pm

Looking at this profile http://admin.minda.olhub.com/manageUsers/235941684/#emailAppTab-tab

The email and SMS was sent at 08:49am NZ time, so 6:49am AU time.
SMS - http://admin.minda.olhub.com/smsHistory/247830022

**Comment by bradmac** [comment]
The timer was scheduled correctly, but the processing was delayed due to a server outage

**Comment by paddyow** [comment]
SMS messages were sent yesterday a 6:20am for trigger 11-DAY90-THANKYOU
Which should have been sent at 5:40pm

![image](https://user-images.githubusercontent.com/2201340/27463253-c9927f3e-5809-11e7-9198-54097d9a926e.png)

**Comment by bradmac** [comment]
Yeah, messages were delayed. Should have been sent the previous day
