### ISSUE TITLE
KCRM Performance enhancements

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3453]
- Dashboard: load leads asynchronously from LeadsFolder, via request param to generate dashboard view. Load in pages of 10, with "Load more" link underneath. Can change to infinite scroll later.
- Order leads by most recent contact first
- And i think we need to do something on the lead page, but will look at that after wes has finished mucking about with beta

**Comment by bradmac** [comment]
leadman.js now has an ajax call to load the leads list. We should apply a limit of generating 10 at a time, and to use a start parameter to skip to the starting record to allow loading more

**Comment by ducdhm** [comment]
I'm done with Frontend stuff

**Comment by bradmac** [comment]
Just noticed a couple of things:
1. timeago is not being applied to the leads. 
![image](https://user-images.githubusercontent.com/826458/27468292-295fab2a-583d-11e7-9a4c-3e9e4057a0aa.png)

2. Deal cancelled button shows the KToolbar vars modal:
![image](https://user-images.githubusercontent.com/826458/27468317-475d30d4-583d-11e7-81af-199168bb299f.png)

**Comment by ducdhm** [comment]
Done!
