### ISSUE TITLE
Points Importer: Add a points column for each Points Tag

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#3461]
This will allocate the points to the user and also tag the points with the selected tag. If it's a debit it will set the reason code to the points tag name

**Comment by hoanglinhlan** [comment]
If I choose a point tag column, it's still say I need to choose point column
![image](https://user-images.githubusercontent.com/20508726/27571498-627a9e10-5b30-11e7-93ff-64b173a4e256.png)

**Comment by hoanglinhlan** [comment]
after re-build, it doesn't say any thing and it's doesn't next step

**Comment by hoanglinhlan** [comment]
it's still not working with correct setting 
http://lantest1.admin.kademi-prod.com/tableUploaders/pointsUploader
[error import point tag.zip](https://github.com/Kademi/kademi-dev/files/1107880/error.import.point.tag.zip)
error file is just showing null message 
![image](https://user-images.githubusercontent.com/20508726/27625107-a4443922-5c0d-11e7-928e-febe5fbaf38b.png)

**Comment by hoanglinhlan** [comment]
It's still not working

**Comment by hoanglinhlan** [comment]
passed
