### ISSUE TITLE
Statistics for the Subscriptions

### ISSUE THREAD

**Issue by gonzalon** [Kademi/kademi-dev#3466]
- Create a background job to post Statistics about the org, such as webpages / users.
- Create a REST endpoint to save this in the Subscription
- Create a java client

**Comment by bradmac** [comment]
This really doesnt look right..
```
    public static Integer countByHomeAdminOrg(Organisation org, Session session) {
        Criteria crit = session.createCriteria(Profile.class);
        crit.setProjection(Projections.rowCount());
        crit.setCacheable(true);
        crit.add(Restrictions.eq("homeAdminOrg", org));
        crit.add(Restrictions.eq("enabled", Boolean.TRUE));
        return crit.list().size();
    }
```

**Comment by gonzalon** [comment]
Updated the queries using list size for the row count propagation, deployed new version of VFS and updated the pom.
