### ISSUE TITLE
Completing a lead task does not correctly refresh lead page

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3468]
After completing a task the task panel updates, but not the panels below which show what we're waiting for. This is confusing for the user because they dont know whats happening next

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/27558861-aef895d0-5b12-11e7-8ac5-6aeaaee4ca1e.png)

**Comment by anhnt** [comment]
fixed. @Uafinder please test it in fresh account. thanks

**Comment by Uafinder** [comment]
good
![image](https://user-images.githubusercontent.com/1945230/31547064-9bca9244-b02e-11e7-8f39-69cb9d877656.png)
