### ISSUE TITLE
Avatar upload form is screwy in leadman theme

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3470]
1. Please make this form look nicer, should use the standard controls
2. Currently it doesnt save if the user doesnt crop. I'm pretty sure this has been fixed elsewhere!

![image](https://user-images.githubusercontent.com/826458/27559600-345ebf04-5b15-11e7-9a19-4b4baea016b7.png)

**Comment by hoanglinhlan** [comment]
passed
