### ISSUE TITLE
Improve file upload modal

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3472]
1. Remove the "example block" text
2. Improve styling of upload button
3. Add a progress upload indicator

![image](https://user-images.githubusercontent.com/826458/27560021-c7654a7e-5b16-11e7-8f4b-7a77a0d7afcf.png)

**Comment by bradmac** [comment]
@salehh93 can you do this please?

**Comment by bradmac** [comment]
Regarding item 3, note that jquery.forms-1.1.5.js has a progress callback:

```
        if (typeof config.onProgress === 'function') {
            flog('[jquery.forms] onProcess');
            ajaxOpts.xhr = function () {
                var xhr = new window.XMLHttpRequest();
                //Upload progress
                xhr.upload.addEventListener("progress", function (evt) {
                    if (evt.lengthComputable) {
                        var percentComplete = (evt.loaded / evt.total) * 100;
                        flog('[jquery.forms] onProcess: ', percentComplete);
                        config.onProgress.call(this, percentComplete, form);
                    }
                }, false);
                return xhr;
            };
        }
        
```

**Comment by anhnt** [comment]
Done using dropzone

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/33120247-0f56df4e-cfa4-11e7-914a-177c266e224a.png)

![image](https://user-images.githubusercontent.com/735555/33120289-306acef2-cfa4-11e7-9b04-9c908c666956.png)

**Comment by bradmac** [comment]
:+1:

**Comment by Uafinder** [comment]
works perfect!
