### ISSUE TITLE
orgSelector: move browse orgs to loading by ajax

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3474]
Currently, when orgSelector renders it outputs links for child orgs in a hierarchy. In some situations this can have a severe performance impact.

What we should do is to move the rendering to a template fragment (ie rendered with TextTemplater) called using ajax, and only called when the user clicks the dropdown to browser orgs.

**Comment by bradmac** [comment]
I've added this to QueriesFolder
```
        } else if ( params.containsKey("browseOrgs") ) {
            C(TextTemplater.class).writePage("reporting/browseOrgs", this, params, out);
            return;   
```

**Comment by bradmac** [comment]
High priority because its causing severe performance issues in some situations

**Comment by tuzzmaniandevil** [comment]
Done, Requires reporting-lib 1.0.4 or greater

**Comment by bradmac** [comment]
@tuzzmaniandevil have you updated other apps which depend on this to 1.0.4?

**Comment by tuzzmaniandevil** [comment]
Yup

**Comment by hoanglinhlan** [comment]
It' showing duplicate org in dropdown 
profile to login: https://rootorg.admin.kademi-prod.com/manageUsers/13868/#summary-tab
login to reward01

**Comment by ducdhm** [comment]
@hoanglinhlan You should not use rootorg for testing. You need create your own org for testing!

**Comment by tuzzmaniandevil** [comment]
Fixed, New version is 1.0.5, I have updated dependencies as well.

**Comment by hoanglinhlan** [comment]
passed

**Comment by bradmac** [comment]
Please use 
```
ReportingApp.searchOrgs
```
