### ISSUE TITLE
KCRM Analytics page updates

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3475]
- add date selector control to default template. This should control data sensitive data
- change the 3 metrics to the following, and make these seperate components from the leadman app
  - number of new leads created
  - leads lost (ie cancelled)
  - leads won (ie closed)
- show the total number inside the circle
- add new components for quotes data (from payments app)
  - number of proposals issued
  - number of quotes issued
  - number of quotes accepted

![image](https://user-images.githubusercontent.com/826458/27566719-1bf260b2-5b3b-11e7-99e0-2a7cdb263996.png)

**Comment by gonzalon** [comment]
Guys @anhnt @ducdhm 
I did this, probably it could look better and isnt refreshing when the dates change.

![image](https://user-images.githubusercontent.com/2773216/31368291-5908cfc2-add9-11e7-9d6a-d89269cfa37e.png)

I added the methods in the payment app for the rest.

countNewQuotes
countAcceptedQuotes
countNewProposals (This one would only count for proposals whit a quote)

**Comment by anhnt** [comment]
doing this now

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/32321178-df798332-bff2-11e7-91b9-b4dc534684cd.png)


![image](https://user-images.githubusercontent.com/735555/32321169-d8925f58-bff2-11e7-9840-a8bc1abc2b69.png)

**Comment by anhnt** [comment]
@gonzalon please have a look at ```LeadManAnalyticsPage.java```, method ```loadDateSummary```

It doesnt have date range filter for aggs ie ```cancelledAggr```

So date range triggers on frontend but result still remains the same

**Comment by gonzalon** [comment]
@anhnt  just updated the queries!

**Comment by anhnt** [comment]
@gonzalon please update query to be able to filter lead by date range
![image](https://user-images.githubusercontent.com/735555/32366209-bad6defe-c0af-11e7-8695-7aad332af232.png)

**Comment by gonzalon** [comment]
Depends on: https://github.com/Kademi/kademi-dev/issues/4335

**Comment by AlaaKhalaf94** [comment]
passed
