### ISSUE TITLE
File upload fields for Funnels

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3478]
We would like to be able to define funnel fields as file upload fields, and for these fields to be appropriately displayed to the user

When displayed on the lead page it should allow an existing file to be downloaded, and allow for a new file to be uploaded.

Note that the ExtraField class used on Funnel already has the fileUpload property, so we should use that.

Bonus points: have a re-usable control that can be used in task outcomes, so the user can upload directly in the task outcome modal.

![image](https://user-images.githubusercontent.com/826458/27568199-9539a2ce-5b44-11e7-8586-24fe57f99f5e.png)

**Comment by gonzalon** [comment]
@bradmac can you please tell me where is this page? couldn't find it

**Comment by bradmac** [comment]
- enable Leadman app
- login to the website
- create a lead (aka a journey)
- view the lead details page

**Comment by gonzalon** [comment]
In addition to what Brad said:

- In the properties of the journey:
![image](https://user-images.githubusercontent.com/2773216/31980160-27f17a68-b9a7-11e7-9f50-73cb3d9f756a.png)

- then in the website, lead page you are going to see:
![image](https://user-images.githubusercontent.com/2773216/31980215-711bca7c-b9a7-11e7-8314-90b3db71c3cd.png)

- if there is a file:
![image](https://user-images.githubusercontent.com/2773216/31980232-8885e710-b9a7-11e7-8292-95f5b1587c95.png)

**Comment by AlaaKhalaf94** [comment]
Hi @gonzalon , I add "field1 , field2 , field3" extra fields from properties of the journey , then I refresh the page , and those appear like this

![capture1](https://user-images.githubusercontent.com/26510030/31991525-a4089fe0-b980-11e7-824e-be47391bd7e9.PNG)

and I think the Stages appear in the same way cause the same problem
http://alaa-test15.admin.kademi-ci.co/funnels/journey1/version1/#properties-tab

Then I go to website, lead page , I see the extra fields appear like this
http://version1.alaa-test15.kademi-ci.co/leads/1083367/

![capture2](https://user-images.githubusercontent.com/26510030/31991673-f78294e6-b980-11e7-9abf-f579e94113d3.PNG)

**Comment by AlaaKhalaf94** [comment]
https://github.com/Kademi/kademi-dev/issues/4253

**Comment by bradmac** [comment]
This is probably a class filter problem.

Please add @docs to ExtraField

**Comment by gonzalon** [comment]
@AlaaKhalaf94 you should be able to test it now :)

**Comment by AlaaKhalaf94** [comment]
Hi @gonzalon , please try to upload file to "Extra Field02" , then delete it , then try to upload file again to "Extra Field02" , it will show you this error

![capture1](https://user-images.githubusercontent.com/26510030/32042481-5eead390-ba40-11e7-91c6-3b4c4817516d.PNG)

admin : http://alaa-test16.admin.kademi-ci.co
in this page : http://version1.alaa-test16.kademi-ci.co/leads/1130593/

**Comment by AlaaKhalaf94** [comment]
Hi @gonzalon ,  I try to upload file to "Extra01:" , then delete it , then try to upload file again to "Extra01:" , it doesn't work with me to upload file again
http://version1.alaa-test19_alaa-test19.kademi-ci.co/leads/1234336/

The appearance of the buttons becomes corrupted when the loaded file name is large
![capture1](https://user-images.githubusercontent.com/26510030/32216627-36504612-be2e-11e7-831b-0f772fade28e.PNG)

**Comment by gonzalon** [comment]
@AlaaKhalaf94  this one and https://github.com/Kademi/kademi-dev/issues/4264 should be working fine

now for the text its going to cut the name like this:
![image](https://user-images.githubusercontent.com/2773216/32531499-dbc8a94c-c4a8-11e7-9b0a-d67066fb068d.png)


please test with the latest version 1.6.4

**Comment by AlaaKhalaf94** [comment]
passed
