### ISSUE TITLE
Cant create a new profile in root org if this profile existed in child org

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#3480]
https://rootorg.admin.kademi-prod.com/manageUsers/

**Comment by bradmac** [comment]
I've just checked and cannot reproduce the issue

**Comment by bradmac** [comment]
@AlaaKhalaf94 please check if this issue is still active

**Comment by AlaaKhalaf94** [comment]
@bradmac I check and see this issue is not active
