### ISSUE TITLE
Showing error page after create auction 

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#3481]
http://lantest1.admin.kademi-prod.com/auctions/

after I created auction "BMW2", it's showing page: 
http://lantest1.admin.kademi-prod.com/websites/bmw2/

**Comment by tuzzmaniandevil** [comment]
I fixed the template.

@hoanglinhlan I got really stuck as the changes weren't showing, Then I discovered that there was an app overriding the templates for auctions called "extra-app-test". I disabled it and the correct template has rendered. Any idea why this was done?
