### ISSUE TITLE
Leadman theme - in lead page: showing error page after click to create lead on menu 

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#3484]
profile to login http://lantest1.admin.kademi-prod.com/manageUsers/74549
login to http://hattonfake001.kademi-prod.com/dashboard
click to open lead page of any lead in dashboard page
(ie: http://hattonfake001.kademi-prod.com/leads/76327/) 
then click to create a new lead in menu 
![image](https://user-images.githubusercontent.com/20508726/27584525-976bb1b8-5b62-11e7-8af3-709ae71ae197.png)
==> it's showing error page

**Comment by bradmac** [comment]
Works correctly on a new account - http://version1.hattonfake03w.kademi-prod.com/leads/120928/

**Comment by hoanglinhlan** [comment]
passed
