### ISSUE TITLE
leadman theme - Switch to another goal Popup: wrong message

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#3485]
https://github.com/Kademi/kademi-dev/issues/3431
![image](https://user-images.githubusercontent.com/20508726/27595626-6af70a0e-5b87-11e7-81ae-7f702b879f7d.png)

profile to login: http://lantest1.admin.kademi-prod.com/manageUsers/74549
lead: http://hattonfake001.kademi-prod.com/leads/117242/
current, this popup's showing message of "next node" function

**Comment by AlaaKhalaf94** [comment]
Switch to another goal Popup as it is
profile to login: http://lantest1.admin.kademi-prod.com/manageUsers/74549
lead: http://hattonfake001.kademi-prod.com/leads/117242/

![capture1](https://user-images.githubusercontent.com/26510030/27819689-10016f0a-60a4-11e7-9c67-0717750d93cf.PNG)

**Comment by tannguyen3489** [comment]
it was fixed in the leadman-lib 1.1.8

**Comment by hoanglinhlan** [comment]
passed
