### ISSUE TITLE
leadman - control timer - rechedule popup: it's doesn't show any thing after I click to calendar ico

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#3486]
https://github.com/Kademi/kademi-dev/issues/3431
![image](https://user-images.githubusercontent.com/20508726/27595892-25b3ff0a-5b88-11e7-8c38-11513b79be85.png)

profile to login: http://lantest1.admin.kademi-prod.com/manageUsers/74549
lead: http://hattonfake001.kademi-prod.com/leads/117242/

**Comment by bradmac** [comment]
Thats correct, the icon just indicates its a date/time field, its not a button

**Comment by ducdhm** [comment]
@hoanglinhlan you need update leadman-theme to newest version is `1.0.8`. Currently, it's version is `1.0.3` in your site

**Comment by ducdhm** [comment]
FYI: You need re-publish leadman-theme in rootorg first

**Comment by bradmac** [comment]
Guys, for testing we should never maually change versions.

@hoanglinhlan please just create a new account with latest version. I
