### ISSUE TITLE
leadman theme - control timer: stop/pause button is not work 

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#3487]
https://github.com/Kademi/kademi-dev/issues/3431
profile to login: http://lantest1.admin.kademi-prod.com/manageUsers/74549
lead: http://hattonfake001.kademi-prod.com/leads/117242/

**Comment by ducdhm** [comment]
Same issue with https://github.com/Kademi/kademi-dev/issues/3486
