### ISSUE TITLE
License check in background tasks

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3488]
LocalAsynchProcessor - see line 295
EmailItemQueueStore - see isIgnored 438. Just skip disabled
SmsItemQueueStore
IntegrationSchedulerProcess
JsScheduler
ScanTriggerTimersProcess - probably put the check in TriggerTimer.takeDue, although this method could be moved up to ScanTriggerTimersProcess
SchedulerProcessor

**Comment by gonzalon** [comment]
SmsItemQueueStore -- TODO
JsScheduler -- TODO
ScanTriggerTimersProcess -- TODO

--
LocalAsynchProcessor -- Done
EmailItemQueueStore  -- Done
IntegrationSchedulerProcess -- Done
SchedulerProcessor -- Done
