### ISSUE TITLE
Blobs Content edit: Editing image width/height makes the ratio wrong

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#3489]
Using the CKEditor, When you right click on an image and edit it. then change either the width or the height the aspect ratio goes all wrong. It seems to be swapping the width and height around

http://zoetis.admin.kademi.com.au/blogs/News/star-breeder-program/#bodyCopy-tab

**Comment by ducdhm** [comment]
Fixed!
