### ISSUE TITLE
Group search not working

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3490]
http://kademi.admin.kademi.us/manageUsers/?filter-tags=CRM

Entering a search term does nothing.

![image](https://user-images.githubusercontent.com/2201340/27616696-dd170220-5bf4-11e7-80f7-93b50b09b09a.png)

**Comment by bradmac** [comment]
Note that this is **blog tags**, not user groups

**Comment by paddyow** [comment]
Updated:

Not all groups are showing (only the contact group), and the search field text box is not there to search for a group.

![image](https://user-images.githubusercontent.com/2201340/27617049-4a68b11e-5bf7-11e7-9795-51092a1f5509.png)

**Comment by bradmac** [comment]
The search box only displays when there is several values. There is no need for a search box when there is 1 item

**Comment by hoanglinhlan** [comment]
passed
