### ISSUE TITLE
Multiple image uploads dont work in popup editor

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3493]

**Comment by bradmac** [comment]
For example, see waterco, try editing a module page and add and change multiple images.

In the browser console you can see "undefined" in the milton tree path

**Comment by ducdhm** [comment]
The reason is when user doesnt select any folder and press uploading, we can't detect which path will upload images to. So I'll add validation when click on upload button.

**Comment by bradmac** [comment]
No, this is not related to validation. Uploading the first file works fine, but then stops working

**Comment by ducdhm** [comment]
Fixed!

**Comment by hoanglinhlan** [comment]
passed
