### ISSUE TITLE
Add back alignment option in image dialog

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3495]
We used to have an option on the image dialog for an image to be aligned left or right. But this is not currently present.

This is necessary for our clients to be able to layout pages. Please add it back

![image](https://user-images.githubusercontent.com/826458/27622927-2a094fb4-5c2e-11e7-8b22-373f3597836a.png)

**Comment by ducdhm** [comment]
@bradmac CKEditor toolbar has align button for align text as well as image so I dont think we need this option for image dialog

**Comment by ducdhm** [comment]
Done!

**Comment by hoanglinhlan** [comment]
1: choose an image and select right align then saved
2: edit that image, popup showing correct align ( it's right) but preview image showing with left align
![image](https://user-images.githubusercontent.com/20508726/27671659-77f8620a-5cbf-11e7-98d8-feb75c084a14.png)
http://lantest1.admin.kademi-prod.com/blogs/samsung/art01/#bodyCopy-tab

**Comment by bradmac** [comment]
@ducdhm we used to have some sample text with the image to show the alignment

**Comment by ducdhm** [comment]
Done!

**Comment by AlaaKhalaf94** [comment]
passed
