### ISSUE TITLE
Content field for voucher types

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3498]
- add a new column to VoucherType called "content"
- add a new tab to the voucher type details page to edit content in ckeditor (not keditor because this will be used in multiple contexts such as email, pdf, web, etc)
- implement a default voucher PDF page
- add a preview button to the voucher details page which will open the voucher PDF page

**Comment by hoanglinhlan** [comment]
@tuzzmaniandevil 
1: 
after I click to open PDF voucher and preview, it's showing blank page 
http://lantest1.admin.kademi-prod.com/vouchers/voucher001/3fb2f

2: I think we should use button, we dont need a dropdown 
![image](https://user-images.githubusercontent.com/20508726/27674144-930114ac-5cce-11e7-8ff2-52f59e18caf2.png)

**Comment by tuzzmaniandevil** [comment]
@hoanglinhlan do you have the vouchers app enabled on any site? It only shows sites that have the app enabled

**Comment by hoanglinhlan** [comment]
great!!
after enabled voucher app on a site, it's work 
however, I think it should be a button, not a dropdown
