### ISSUE TITLE
Integrate files with omnisearch

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3505]
Related https://github.com/Kademi/kademi-dev/issues/3416

**Comment by bradmac** [comment]
Done

![image](https://user-images.githubusercontent.com/826458/36405665-b573a8dc-1656-11e8-9db4-764252a9a10f.png)

**Comment by Uafinder** [comment]
Need a bit more info, where and what search should do?

**Comment by bradmac** [comment]
@Uafinder this should mean that files are included in omni search results, in the admin and also front end search page.

Eg:
![image](https://user-images.githubusercontent.com/826458/36510092-be79df20-17c6-11e8-8879-a9e86dfb04ba.png)

**Comment by bradmac** [comment]
content-lib 1.2.7

**Comment by Uafinder** [comment]
Some mentions:

1. Can't find manually uploaded files
![image](https://user-images.githubusercontent.com/1945230/36932485-423fe46e-1ed2-11e8-8ac2-2c9c6e8a8e52.png)
It was directly uploaded via file manager

2. Can't find default page, e.g. home etc
![image](https://user-images.githubusercontent.com/1945230/36932507-93d372e6-1ed2-11e8-8b69-dbef08d4da4e.png)
![image](https://user-images.githubusercontent.com/1945230/36932509-99447a0e-1ed2-11e8-81b6-495f888343a2.png)

3. Should it search in assets catalog?
![image](https://user-images.githubusercontent.com/1945230/36932515-b1322d50-1ed2-11e8-92f8-4854a3b6636c.png)

4. When you click on page link it add a double slash in the end of the address
![image](https://user-images.githubusercontent.com/1945230/36932611-f0359694-1ed3-11e8-9053-edc5abad4d9e.png)
![image](https://user-images.githubusercontent.com/1945230/36932612-f85adaa0-1ed3-11e8-835e-9fbc9bb07f0f.png)

5. Should be searchable by a part of the file name, e.g. "Page" should show Page1 and page2 choices
![image](https://user-images.githubusercontent.com/1945230/36932643-a9f09200-1ed4-11e8-8e64-a82aeca0605c.png)
![image](https://user-images.githubusercontent.com/1945230/36932647-ae3d9150-1ed4-11e8-8820-39461555b5ca.png)

**Comment by bradmac** [comment]
> Should it search in assets catalog?

Asset search is covered by this issue:
https://github.com/Kademi/kademi-dev/issues/5077

**Comment by bradmac** [comment]
> Can't find manually uploaded files

This is intended to find pages, ie html pages. Searching for binary files will be supported through the asset lib

**Comment by bradmac** [comment]
> Should be searchable by a part of the file name, e.g. "Page" should show Page1 and page2 choices

Search is using terms matching rather then prefix, which is by design. So searching for "page" or "my" will match "my page"

**Comment by bradmac** [comment]
> Can't find default page, e.g. home etc

This works after reindexing

![image](https://user-images.githubusercontent.com/826458/37009918-e41fa8c8-214d-11e8-921a-8a37c2e96418.png)

**Comment by bradmac** [comment]
> When you click on page link it add a double slash in the end of the address

Fixed

**Comment by Uafinder** [comment]
So, looks fine
