### ISSUE TITLE
Fix double modal on lead from email

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3513]
Click "Lead from email" in the menu, shows 2 modals..

![image](https://user-images.githubusercontent.com/826458/27774723-6ca9590c-5feb-11e7-8d25-0931fbd4f19b.png)

http://itsinsuredqa-crm.kademi.com.au/leads/75521536/

**Comment by gonzalon** [comment]
Test with the latest leadman lib 1.3.7

**Comment by AlaaKhalaf94** [comment]
Hi @gonzalon , I try to open "Lead from email" modal , and it doesn't work with me
when I click on it from menu nothing happens

I test here in "test3" site :  http://alaa-test3.admin.kademi-ci.co/

**Comment by bradmac** [comment]
OK, the problem here is that K-Theme combines all JS files into a single URL to improve performance. But this site has all apps enabled so that URL is too long.

**Comment by bradmac** [comment]
I'll look into this

**Comment by AlaaKhalaf94** [comment]
Hi @bradmac , I create new account : http://test6.admin.kademi-ci.co
And the dialog does not appear at all : http://test6.kademi-ci.co/

**Comment by bradmac** [comment]
hey @gonzalon the JS problem is fixed, but the modal isnt appearing, and i cant actually see what code should make it appear.

**Comment by gonzalon** [comment]
Fixed. Test with the latest leadman lib 1.3.9

**Comment by AlaaKhalaf94** [comment]
passed
