### ISSUE TITLE
Uploading large file breaks importer template

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3515]
[Points - May 2017.xlsx](https://github.com/Kademi/kademi-dev/files/1118264/Points.-.May.2017.xlsx)
http://asrdev.admin.kademi.us/tableUploaders/pointsUploader

1) The footer breaks position
2) The table goes out of its parent container vs sit inside the container and get scrolled

![image](https://user-images.githubusercontent.com/2201340/27775600-e704b2d2-5fe6-11e7-9b45-d1c75926c0e1.png)

**Comment by bradmac** [comment]
need to add table-responsive

**Comment by Uafinder** [comment]
Yup, works great, after new uploading process being implemented...
