### ISSUE TITLE
schedule email - message template: container showing overlap

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#3521]
after I drag a container to EDM, it's showing overlap
http://lantest07.admin.kademi-prod.com/scheduledEmails/07schedulemail001/#configuration-tab
![image](https://user-images.githubusercontent.com/20508726/27814579-a4be254a-60a7-11e7-84b7-6309fb414961.png)

**Comment by ducdhm** [comment]
@hoanglinhlan This screen is not done yet. It's belong to this https://github.com/Kademi/kademi-dev/issues/2759.

FYI: This issue occur because of web snippet. If we load right edm snippet, everything is ok.
