### ISSUE TITLE
reward store page: showing error

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#3522]
profile to login http://lantest04.admin.kademi-prod.com/manageUsers/153411/#summary-tab
http://04c5s-rewardstore001.kademi-prod.com/04c5s-pointbucket-us/#

![image](https://user-images.githubusercontent.com/20508726/27816779-cda17c18-60b7-11e7-8810-130b541bef98.png)

**Comment by anhnt** [comment]
worked ok with rewardstore-lib 1.1.2
