### ISSUE TITLE
Need re-index to see a new product

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#3523]
http://lantest04.admin.kademi-prod.com/manageSearch/
add a new product, then go to the manage search page ==> quantity of productstore is not update

**Comment by bradmac** [comment]
@hoanglinhlan there is no index called "productstore"

which are you referring to?

**Comment by hoanglinhlan** [comment]
sorry @bradmac 
it's "	rewardstore"

**Comment by hoanglinhlan** [comment]
just because I don't add the product to reward store
