### ISSUE TITLE
Previous button on user upload tool does not go back

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3524]
http://vayatest.admin.kademi.com.au/tableUploaders/usersUploader

Instead it seems to progress forward.

![image](https://user-images.githubusercontent.com/2201340/27819072-de7d3a9e-60db-11e7-8cc2-5294ecda39bc.png)

**Comment by Uafinder** [comment]
No, the same...
Tested on http://vayatest.admin.kademi.com.au/tableUploaders/usersUploader and http://vlad-test10.admin.kademi-ci.co/

**Comment by tuzzmaniandevil** [comment]
Duplicate of #3887
