### ISSUE TITLE
Email history only goes back to 20/05/2017  

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3525]
http://admin.minda.olhub.com/emails/

Client needs to download a CSV dating back further in order to do their reporting.

Is there a way to access email history beyond the date of 20/05/2017

**Comment by bradmac** [comment]
hey @gonzalon, this issue is affecting our old platform on olhub only

Please checkout the appropriate branch and correct this problem, then i'll deploy.

https://github.com/Kademi/kademi-server/tree/olhub-backport

**Comment by AlaaKhalaf94** [comment]
Hi @gonzalon 
here http://admin.minda.olhub.com/emails/ 
I can not make export CSV to test it
