### ISSUE TITLE
Analytics funnel is showing duplicated stages

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#3527]
Stages on admin
![image](https://user-images.githubusercontent.com/735555/27828400-34d14b24-60e6-11e7-916e-08cd5540efb5.png)

Stages on funnel graph
![image](https://user-images.githubusercontent.com/735555/27828383-25364b2e-60e6-11e7-87b9-c409c549adcb.png)

funnel.json is looking good, so i think that's because the stage name is uppercase

**Comment by bradmac** [comment]
Note tht the funnel  shows data from the leads in the database. Changing stage names will not update existing leads, so you will still see previous stage names. This is expected

**Comment by anhnt** [comment]
Yes its showing stages that has been renamed.
