### ISSUE TITLE
Upload the image in leadProfileCoverComponent does not work

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#3528]
in : http://alaa-test.admin.kademi-prod.com/
in this page : http://version1.alaatest01.kademi-prod.com/newpage02.html

Does not recognize or upload the new image that is selected
![capture6](https://user-images.githubusercontent.com/26510030/27830898-16f71bfc-60d1-11e7-9b4f-ce3a78a7cd1e.PNG)

**Comment by bradmac** [comment]
@tuzzmaniandevil please check image utils are installed.

**Comment by tuzzmaniandevil** [comment]
@AlaaKhalaf94 Please retest on CI

**Comment by AlaaKhalaf94** [comment]
I've tested it on CI , and it has worked well
