### ISSUE TITLE
TableUploadManager: Handle dates better

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#3529]
Support the following date formats by default:
- yyyy-MM-dd'T'HH:mm:ss.SSSZZ
- yyyy-MM-dd'T'HH:mm:ssZZ
- dd/MM/yyyy
- dd/MM/yyyy HH:mm
- yyyy/MM/dd HH:mm

Also if the file is an Excel spreadsheet, Parse date columns as date to get the correct value

If a "Date Format" is selected from the Options step, Use that instead.

**Comment by paddyow** [comment]
This issue still persists using this date format 15/06/17 01:00

Same file to http://kademitest.admin.kademi.us/rewards/points/

**Comment by bradmac** [comment]
Checked locally and seems all good. Will do another deploy to US to confirm is updated.

**Comment by AlaaKhalaf94** [comment]
Hi @tuzzmaniandevil  , How can I test this ?

**Comment by bradmac** [comment]
@AlaaKhalaf94 please test by doing an upload where you specify the date format in the import settings, and you upload a file with date columns in taht format

**Comment by AlaaKhalaf94** [comment]
passed
