### ISSUE TITLE
Carousel supports content

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#3533]
Now, carousel supports only image.

**Comment by bradmac** [comment]
:+1:

**Comment by ducdhm** [comment]
New UI:

![newui](https://user-images.githubusercontent.com/1289631/28014189-f168cd4e-6595-11e7-8f39-1564c33ce556.png)

![newui2](https://user-images.githubusercontent.com/1289631/28014193-f4aa1f30-6595-11e7-8dbc-81a688dd60bb.png)
