### ISSUE TITLE
[ Points system : points gto to user's org ] does no work well

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#3535]
When I choose points system as points gt to user's org , and add points to any org
Points can not be converted to the users in the organization

the site : http://alaa-test.admin.kademi-prod.com/
the point bucket : http://alaa-test.admin.kademi-prod.com/points-buckets/
the org : http://alaa-test.admin.kademi-prod.com/organisations/156329/edit
the user : http://alaa-test.admin.kademi-prod.com/manageUsers/148677/#general-tab

**Comment by bradmac** [comment]
I've changed the configuration slightly and it works now:

![image](https://user-images.githubusercontent.com/826458/27885443-2fc49b8a-622c-11e7-8c88-1ba9f57f8d98.png)

**Comment by bradmac** [comment]
What i did was
1. Set the org type on the points bucket
2. Add that org type to the organisation

1
![image](https://user-images.githubusercontent.com/826458/27885556-82ddaa00-622c-11e7-8f60-6ad56adfbbd8.png)

2. 
![image](https://user-images.githubusercontent.com/826458/27885576-8e749680-622c-11e7-986d-42de0c5b1638.png)

**Comment by bradmac** [comment]
But this does look like a bug, i think the points should show up even when no org type is selected.

**Comment by bradmac** [comment]
@tuzzmaniandevil please ensure points are displayed for a user even when there is no org type

**Comment by AlaaKhalaf94** [comment]
passed
