### ISSUE TITLE
Tidy up buttons on reward points page

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3538]
We've now got way too many buttons:

![image](https://user-images.githubusercontent.com/826458/27892317-15ddfa96-6253-11e7-8335-5628ab1c8d13.png)
http://localhost:8080/rewards/points/

The points buckets and promotions buttons should stay as they are, but the other buttons should go into a tools drop down similar to the manage users page

**Comment by anhnt** [comment]
done 
![image](https://user-images.githubusercontent.com/735555/27897982-ba3dfef2-624d-11e7-839a-77fb2d4e84e3.png)

**Comment by hoanglinhlan** [comment]
passed
