### ISSUE TITLE
Full height option for container

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#3539]
Need a small js stuff for making container full height.
Reason no CSS: You need to make sure all parents of container have `height: 100%`

**Comment by ducdhm** [comment]
Done!

**Comment by bradmac** [comment]
How do we get the bg to be full page width?

![image](https://user-images.githubusercontent.com/826458/27897117-77171972-6272-11e7-9d85-98f8fca908aa.png)

**Comment by bradmac** [comment]
Looking good.

![image](https://user-images.githubusercontent.com/826458/27897357-f22da4ea-6273-11e7-888b-8455d7b5c196.png)
