### ISSUE TITLE
analytic page: should be showing list source

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#3545]
profie to test: http://lantest08.admin.kademi-prod.com/manageUsers/175958/#summary-tab
funnel: http://lantest08.admin.kademi-prod.com/funnels/008hattonfake001-funnel001/#properties-tab
I have 2 source (008 source 001 and 008 source 002) , and I think we should showing list source under "deal total". current, I dont know what it's showing now
http://008hattonfake001.kademi-prod.com/analytics/008hattonfake001-funnel001?filters=&stage
![image](https://user-images.githubusercontent.com/20508726/27897298-a05654b6-6249-11e7-8694-8ff4f30c00cb.png)

**Comment by anhnt** [comment]
i think it is ES aggregation issue. sources field are being analyzed. 
@bradmac please advise

**Comment by bradmac** [comment]
@tuzzmaniandevil is the best person to talk to

**Comment by anhnt** [comment]
works ok now
