### ISSUE TITLE
Google map component of leadman in dashboard

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#3549]
Need to convert this map to component

**Comment by anhnt** [comment]
this component is called leadsGeoLocation and belongs to leadman-lib

**Comment by AlaaKhalaf94** [comment]
The component exists , but it does not work with me , it does not appear .

**Comment by tannguyen3489** [comment]
@AlaaKhalaf94 : I checked your website instance. Please use leadman theme and config google api key in setting app.

![image](https://user-images.githubusercontent.com/1665005/29110751-f9da61de-7d11-11e7-8b57-73fd6d0f8d11.png)

**Comment by AlaaKhalaf94** [comment]
passed

**Comment by bradmac** [comment]
Hey guys, can someone tell me why this needs the leadman-theme? KCRM needs to work with any theme.

**Comment by tannguyen3489** [comment]
sorry, Alaa, I checked again. The #portlets("header") exist on all themes, so you only need to config the google API key, it will work on all themes.

**Comment by AlaaKhalaf94** [comment]
passed
