### ISSUE TITLE
Ksurvey: after create an Ksurvey, left menu showing error under Ksurvey menu

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#3554]
http://lantest1.admin.kademi-prod.com/ksurvey/
![image](https://user-images.githubusercontent.com/20508726/27948636-b6bee138-6324-11e7-8667-7da92de518bc.png)

**Comment by tannguyen3489** [comment]
I clean data on local, this bug will be fixed. So please reset lan-test.

**Comment by tannguyen3489** [comment]
it happens again.

**Comment by tannguyen3489** [comment]
it was fixed.

**Comment by hoanglinhlan** [comment]
passed
