### ISSUE TITLE
Ksurvey detail page: question's title showing source code

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#3555]
![image](https://user-images.githubusercontent.com/20508726/27952582-ff8cb1ca-6332-11e7-819f-2e30e1824a00.png)

http://lantest1.admin.kademi-prod.com/ksurvey/survey-b44e71ff-3542-4ed9-81fe-a7c98deb8386/#questions-tab

**Comment by tannguyen3489** [comment]
it was fixed.
![image](https://user-images.githubusercontent.com/1665005/28009506-e4261eb2-6585-11e7-9d35-f5ef4e8da7d0.png)
