### ISSUE TITLE
Validate task fields on new lead

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3565]
If the description field is entered, validate the task field

![image](https://user-images.githubusercontent.com/826458/28048938-2bbe054c-6648-11e7-99a5-20dcaab52130.png)

**Comment by gonzalon** [comment]
Test with the latest leadman-lib 1.5.0

**Comment by AlaaKhalaf94** [comment]
passed

**Comment by bradmac** [comment]
This is wrong, its just making the task title mandatory all the time.

It should only be required if there is a task description
