### ISSUE TITLE
selectedOrganisation: Add option to allow linking to company page

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3569]
Please add an option to the selected org component to allow producing a link to the KCRM company page for the organisation

![image](https://user-images.githubusercontent.com/826458/28051004-651e25ee-6655-11e7-86a1-9c7483b442fe.png)

**Comment by bradmac** [comment]
I've overridden the component in CCA temporarily. Please remove when done.

http://cca.admin.kademi.com.au/repositories/cca-sales/version1/theme/apps/reporting/texteditor?fileName=selectedOrganisationComponent.html

**Comment by ducdhm** [comment]
Done!

**Comment by AlaaKhalaf94** [comment]
passed
