### ISSUE TITLE
Update leadCompaniesComponent to be searchable

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3570]
- allow searching
- use pagination
- use ES (i think you can use @tuzzmaniandevil 's new methods)

http://version1.cca-sales.kademi.com.au/companies/

Currently looks like this:
![image](https://user-images.githubusercontent.com/826458/28051286-53c1c452-6657-11e7-99c0-0287e42e8ee2.png)

http://version1.cca-sales.kademi.com.au/companies/

**Comment by bradmac** [comment]
@anhnt please update CCA

**Comment by anhnt** [comment]
i updated CCA to use latest leadman-lib but this doesnt show any company
```$page.paginator``` is not available

**Comment by anhnt** [comment]
worked fine now
