### ISSUE TITLE
Assign to Org Type in Admin Organisations screen

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#3580]
The feature assign to org type is not implemented, needs implementation

**Comment by mkhoudary** [comment]
https://github.com/Kademi/client-cf-itsinsured/issues/77

**Comment by mkhoudary** [comment]
Done..

**Comment by bradmac** [comment]
See comment:
https://github.com/Kademi/kademi-platform/commit/b3e9daf761ab3c266855d3a1d34b83e1b2aaae30

**Comment by bradmac** [comment]
Also, please add an option to the UI to either add the org type (default) or to remove it from selected orgs.

**Comment by mkhoudary** [comment]
Done..
