### ISSUE TITLE
The sale data page is error (/sales/)

### ISSUE THREAD

**Issue by tannguyen3489** [Kademi/kademi-dev#3583]
![image](https://user-images.githubusercontent.com/1665005/28148427-e7b7e86c-67b0-11e7-882b-93353e494a11.png)

**Comment by bradmac** [comment]
Note that this page is never actually used. We should replace it at some point.

**Comment by tannguyen3489** [comment]
@bradmac : you mean, we don't need to fix it now?

**Comment by bradmac** [comment]
Correct.

**Comment by tannguyen3489** [comment]
ok, thanks.
