### ISSUE TITLE
KPI leaderboard result is not correct

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#3588]
![image](https://user-images.githubusercontent.com/735555/28162275-b0832632-67f0-11e7-8088-80db00ff70bb.png)

I think this is ES5 issue since there's only sale record that attributes to "Anh Nguyen" and this leaderboard result is aggregated by ```assessedFullName```

SaleDataApp.java line 1298, branch master

```
leadboardAgg = AggregationBuilders.terms("leaders")
                    .field("assessedFullName")
                    .subAggregation(leaderboardMetric);
```

**Comment by bradmac** [comment]
use "assessedFullName.keyword"

**Comment by anhnt** [comment]
it worked 👍
