### ISSUE TITLE
Broken image links in group emails editor

### ISSUE THREAD

**Issue by skwidge** [Kademi/kademi-dev#359]
Andy Gale at Waterco is experiencing some trouble with image editing in the group emails editor:

> Hi Bruce,
> 
> I am also attempting to set up a group email including a picture.
> When uploading/attaching the image to the rich text editor, it shows as a broken link when I send
> the test email;
> http://admin.waterco.olhub.com/groupEmails/how-to-test-for-ozone-flow/#messages-tab
> Could you please take a look?
> 
> Thanks.
> Andy

...

> Hi Bruce,
> 
> I tried to adjust the size of the picture and its showing as a broken link again.
> 
> Kind regards,
> Andy

**Comment by tuzzmaniandevil** [comment]
Fixed
