### ISSUE TITLE
Manage vouchers page

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3591]
Please create a new admin page for managing vouchers.

Currently we have a page for managing voucher types, and each voucher type page allows searching for vouchers:
![image](https://user-images.githubusercontent.com/826458/28193133-a14455da-688e-11e7-8edb-c3675b1e150f.png)

However, it would be better to instead have a single page for finding vouchers across all voucher types.

This new page should
- allow searching by keyword as per the current search
- allow selecting a voucher type to filter
- allow selecting by status
- use pagination
- allow exporting to CSV

The current vouchers tab on the voucher type page should continue to show summary information and have create/upload/export, but the vouchers table should be removed.

**Comment by AlaaKhalaf94** [comment]
Hi @gonzalon , I test it and selecting by status is not allowed

I test here http://alaa-test.admin.kademi-prod.com/vouchers/?q=&status=&voucherType=
I try to select "Allocated , Redeemed , Pending , Idle" and it does not show results

**Comment by gonzalon** [comment]
Hi @AlaaKhalaf94,
 Im seeing in your test that you can't find the vouchers by status with the drop down. 
But if you try like this, its fine:
http://alaa-test.admin.kademi-prod.com/vouchers/?q=&status=Redeemed&voucherType= 

Probably that's because you imported the vouchers with the status?

**Comment by AlaaKhalaf94** [comment]
passed

**Comment by bradmac** [comment]
Now getting this error:
![image](https://user-images.githubusercontent.com/826458/28548506-775cdd94-7128-11e7-8a06-066d4ad89574.png)

http://airnz.admin.kademi.com.au/manageUsers/75893290

**Comment by bradmac** [comment]
```
    @Override
    public Resource getPage(Resource parent, String requestedName) {
        if ( parent instanceof WebsiteRootFolder ) {
            if ( requestedName.equals("voucher-type") ) {
                WebsiteRootFolder wrf = (WebsiteRootFolder) parent;
                return new VoucherRedemptionPage(requestedName, wrf);
            }
            if ( requestedName.equals("vouchers") ) {
                WebsiteRootFolder wrf = (WebsiteRootFolder) parent;
                return new VouchersPage(requestedName, wrf);
            }

        }
        return null;
    }
```
