### ISSUE TITLE
Lead page for admin console

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#3593]

**Comment by bradmac** [comment]
Its a start ..

![image](https://user-images.githubusercontent.com/826458/29056066-4d9ccef0-7bb5-11e7-8dfb-9482aed4d86c.png)

Eg http://localhost:8080/leads/121/

**Comment by bradmac** [comment]
@ducdhm can you please build the page content? This uses the same resource as for the front end so the ajax services are all the same.

**Comment by bradmac** [comment]
Want it have similar capabilities as the front end lead page, but it doesnt need to be exactly the same.

**Comment by ducdhm** [comment]
@bradmac Can you implement the resource for this screen? I can't see it in my local.

**Comment by bradmac** [comment]
Yep, its already added. I've added a link on the manage funnel page to help you find it :)

![image](https://user-images.githubusercontent.com/826458/29147122-f1c8cd48-7d19-11e7-99c0-d1bf1a98f9a1.png)

**Comment by ducdhm** [comment]
@bradmac I still got 404 error page when click on link in manage funnel page. Can you double-check?

**Comment by bradmac** [comment]
Pushed.. should work now

**Comment by ducdhm** [comment]
Done!

**Comment by ducdhm** [comment]
Need to apply entity finder for `Assign to` dropdown
