### ISSUE TITLE
File sync alternative to webdav

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#36]
Suggested by Callum at Ward6:

Currently Kademi supports authoring through:
 - built in wyisiwig content editors
 - built in text editor for css, js and html files
 - webdav access to allow editing through IDE's such as Sublime, Coda, Dreamweaver, etc

However, in many cases working on actual local files is preferable to either browser based editing or remote file editing through webdav. 

Kademi can support this through a native file sync client. This will work in a conceptually similar manner to the dropbox client. But instead of being integrated into the operating system it will just be a command line utility.

It would also be good to embed a mini-kademi in the utility to allow completely offline development.

**Comment by bradmac** [comment]
Docs on using the tool - http://docs.kademi.co/howtos/devs/developing-with-sync.html

**Comment by bradmac** [comment]
@Uafinder could you please have a try at testing the file sync tool. Instructions in the link above. You should check that files are correctly updated on the server when local changes are made - update, delete, create.
Check that changes on the server are applied locally when a sync is run.
And check that conflicts are handled correctly, ie where the same file is modified on both client and server.

**Comment by Uafinder** [comment]
It works!!!
Creating, Updating, Renaming, Deleting works ok.
When you provide changes on server it transfers to local machine after some time (approx 1 minute).
When you try to create a conflict - it choose most defensive way. If you delete it from one side and rename from another it will choose rename, no errors, no malfunctions i've spot.
