### ISSUE TITLE
Lead dashboard doesnt refresh after creating new lead

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#3604]

**Comment by anhnt** [comment]
also lead tasks should refresh 
map donuts and sales summary should refresh
also when canceling or closing a lead, leads list should refresh

**Comment by anhnt** [comment]
I fixed those above issues but there's problem with Task completion pie chart. At the moment its always zero
![image](https://user-images.githubusercontent.com/735555/31490021-d7b18668-af6c-11e7-8303-3baa4fa4c8ce.png)

@tuzzmaniandevil can you have a look.

**Comment by anhnt** [comment]
@tuzzmaniandevil this doesnt work because when you creating new task, assignedToOrg is null, if we have a term query to filter by assignedToOrg.id, no result returns.

See this example query: http://vlad-test15.admin.kademi-ci.co/queries/tasktest/

**Comment by tuzzmaniandevil** [comment]
@anhnt The method you are calling is `getTeamTaskStatus` which is designed to get the **Team** tasks, It doesn't that by looking at the assighedToOrg, Which comes from the Lead assignedToOrg

If that panel isn't designed to show team task stats but individual tasks then you are using the wrong method

**Comment by tuzzmaniandevil** [comment]
I have updates the tasks index so assignedToOrg is never null, It will default to the admin org if no assigneToOrg it set.

**Comment by anhnt** [comment]
thanks its working now. just added some code to reload the piechart when a task is updated
