### ISSUE TITLE
ES5 Migration - Test Sites

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#3607]
Please edit and add your name if you are checking a project

- carters (wes)
- airnz (anh)
- zoetis (duc)
- waterco (duc)
- 3M (anh)
- cca (anh)
- reach(Gonzalo)
- Nesst(Gonzalo)
- swimart (duc)

**Comment by anhnt** [comment]
airnz is migrated to es5 on version11

**Comment by anhnt** [comment]
3m is migrated

**Comment by gonzalon** [comment]
Nesst is working fine

**Comment by gonzalon** [comment]
reach a.k.a ward6 it's working fine

**Comment by ducdhm** [comment]
zoetis is migrating... 99,99% completed
 * zoetis-livestock-reseller in es5migration
 * user-stats-app is in es5migration
 * posterBuilder is in es5migration
 * module-report is in es5migration - Need to re-check /user-report/ screen after changing query

**Comment by tuzzmaniandevil** [comment]
Carters looks good, Just the reporting site to do

**Comment by ducdhm** [comment]
waterco is migrating, 50%...
 * queries in es5migration
 * hydroxypure in es5migration
 * waterco-signup in es5migration

**Comment by ducdhm** [comment]
swimart is migrating...
 * queries in es5migration
 * customreports in es5migration

**Comment by bradmac** [comment]
Tried deploying to prod, but web2 didnt come up on ap.se.2-0306-beta

@tuzzmaniandevil need you to look into that tomorrow please
