### ISSUE TITLE
Search error in input finder plugin js.

### ISSUE THREAD

**Issue by tannguyen3489** [Kademi/kademi-dev#3609]
![ezgif-4-6f9a96c97c](https://user-images.githubusercontent.com/1665005/28362112-775ec4ec-6ca5-11e7-91d9-33857e437ed3.gif)

**Comment by ducdhm** [comment]
Is it your local? You need to reindex for it. It's just issue related to elasticsearch, not JS stuff.

**Comment by tannguyen3489** [comment]
thank Duc. After reindexing, it is ok.
