### ISSUE TITLE
Implement themes from bootswatch

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3619]
Please create marketplace themes from here:
https://bootswatch.com/

These should be correctly integrated via LESS parameters.

Note that these themes depend on bs3.3.7, so do this first - https://github.com/Kademi/kademi-dev/issues/3618

**Comment by salehh93** [comment]
done

**Comment by bradmac** [comment]
I cant see any new themes here:
https://github.com/Kademi/kademi-dev/tree/master/src/main/marketplace/themes

**Comment by salehh93** [comment]
done !
create all themes and tested it
can you check here 
https://github.com/Kademi/kademi-dev/tree/master/src/main/marketplace/themes

**Comment by bradmac** [comment]
I created a website and checked it appears correctly with k-theme

I then applied cerulean-theme and checked /dashboard and /profile and both had problems:

Dashboard:
![image](https://user-images.githubusercontent.com/826458/28549589-2b2e3484-712f-11e7-98e5-1674b50a3b38.png)

Profile:
![image](https://user-images.githubusercontent.com/826458/28549605-49b9ceea-712f-11e7-8a6f-def25c547786.png)

These pages appear correctly in k-theme

**Comment by AlaaKhalaf94** [comment]
passed

**Comment by bradmac** [comment]
@ducdhm since @salehh93 is having a baby, can you please finish those changes you mentioned?

**Comment by ducdhm** [comment]
@AlaaKhalaf94 In next time, please test carefully! All themes are using same variables of cosmo theme. How can this issue be passed?

**Comment by AlaaKhalaf94** [comment]
**In Cerulean theme**
Progress bars appears incorrectly , and in Dialogs Modals appears incorrectly too
And there is a repetition in the appearance of some parts such as " Default , Navbar , Buttons , Typography ,,,,,, "

And **Other themes** are using same variables of cosmo theme

**Comment by ducdhm** [comment]
`And Other themes are using same variables of cosmo theme`
@AlaaKhalaf94 You need create a website for each of theme.

**Comment by ducdhm** [comment]
You can create a website for each of theme or after changing theme, you need to clear your browser cache to see the effect.

**Comment by AlaaKhalaf94** [comment]
@ducdhm I make new account for this : http://bootswatch01.admin.kademi-prod.com/

And I  create a website for each of theme : http://bootswatch01.admin.kademi-prod.com/websites/

Only Cosmo-theme work well , but Other themes does not work with me

for example : yeti-theme
when I select theme from here : http://bootswatch01.admin.kademi-prod.com/websites/yeti/version1/themeSelect

logs page shows me that "Could not find template: /theme/defaultThemeTemplate.html"
http://bootswatch01.admin.kademi-prod.com/logging

**Comment by ducdhm** [comment]
I have synced all themes to QA. Should work now!

Reason is all themes' content are empty!

**Comment by AlaaKhalaf94** [comment]
passed
