### ISSUE TITLE
KCRM complete dialogue should show task title....

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3622]
The top section should not show a summary (at the moment way too long), it should show the task title and description only.  

![image](https://user-images.githubusercontent.com/2201340/28510174-1bb53ac0-708a-11e7-8947-8e6531780502.png)

**Comment by ducdhm** [comment]
I added toggle content button when Notes is loooong....

New UIs:
![newui](https://user-images.githubusercontent.com/1289631/29105527-82a19f2e-7cf8-11e7-81fa-c8d5e68a9d37.png)

![newui2](https://user-images.githubusercontent.com/1289631/29105529-85bda0b8-7cf8-11e7-83c2-d4e680887016.png)
