### ISSUE TITLE
Disorder in front end in reward page

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#3624]
Admin account : http://alaa-test.admin.kademi-prod.com/

In this page : http://alaatest02.kademi-prod.com/rewards/
![capture1](https://user-images.githubusercontent.com/26510030/28520994-70f18ddc-707a-11e7-82e7-8596806e3f1b.PNG)

And in this page : http://alaatest02.kademi-prod.com/rewards/lebanon/
when I add new entry , and shows error to me
![i140 cimgpsh_orig](https://user-images.githubusercontent.com/26510030/28521177-1db52f4c-707b-11e7-8632-1cbf520255c2.png)

**Comment by AlaaKhalaf94** [comment]
It's as it is

![capture1](https://user-images.githubusercontent.com/26510030/28751099-0a72262a-7507-11e7-8f88-b9316d6443fc.PNG)

![capture2](https://user-images.githubusercontent.com/26510030/28751101-0fc999c8-7507-11e7-806b-5fae3c25d5fa.PNG)

**Comment by bradmac** [comment]
Please ensure you re test with a fresh account

**Comment by AlaaKhalaf94** [comment]
I repeated the test with a new account
http://reward09.admin.kademi-prod.com/

with this user : http://reward09.admin.kademi-prod.com/manageUsers/251426/#summary-tab

in this page : http://forreward09.kademi-prod.com/rewards/
![capture1](https://user-images.githubusercontent.com/26510030/28751403-43f947ae-750f-11e7-8eb1-bbf0c08cea8a.PNG)

**Comment by tannguyen3489** [comment]
I checked on version 1.0.6. It works well. Please recheck it for me.

![image](https://user-images.githubusercontent.com/1665005/29065954-fc06c9d0-7c57-11e7-99d5-1b2427e47a1d.png)
![image](https://user-images.githubusercontent.com/1665005/29066002-204c6638-7c58-11e7-8c3a-25ad64266014.png)

**Comment by tannguyen3489** [comment]
please check it on version 1.0.7

**Comment by AlaaKhalaf94** [comment]
passed
