### ISSUE TITLE
Searching msg should hide when search complete msg is shown

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#3625]
![image](https://user-images.githubusercontent.com/735555/28521253-f401a23a-709c-11e7-929d-25ca6b1d9c57.png)

**Comment by bradmac** [comment]
Here's an idea. Each message has some sort of message type id. When a new message is displayed, check for any messages with the same type id. If there are any, hide them immediately.

Eg in the screenshot above those 2 messages would have message type id "userSearchStatus".

**Comment by ducdhm** [comment]
I forgot to mention you that we return instance after you show a message. You can update this message or close it. Let me create doc for it.

**Comment by bradmac** [comment]
I think we should support my suggested approach. Often these messages will not be in the same piece of code.
