### ISSUE TITLE
Sending an email to a lead profile with the "forward" address does not show in the timeline

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3633]

**Comment by gonzalon** [comment]
Seems to be working:

![image](https://user-images.githubusercontent.com/2773216/31593767-1b067612-b28d-11e7-83c8-dc318769268b.png)


To test:
- Create a lead with a valid email
- Send an email to the forward address
![image](https://user-images.githubusercontent.com/2773216/31593793-46c43046-b28d-11e7-9a14-fcca6c31d029.png)

**Comment by AlaaKhalaf94** [comment]
Hi @gonzalon , when I click on "forward" it doesn't work anything

I login with this user : http://alaa5.admin.kademi-ci.co/manageUsers/63007/#summary-tab
to this lead : http://version1.alaa5.kademi-ci.co/leads/776799/

**Comment by gonzalon** [comment]
@AlaaKhalaf94 sorry I wasn't clear enough.
- just copy the address in the foward link
- open your email (Fastmail, Outlook, etc..) and write / send an email.

**Comment by bradmac** [comment]
Note that clicking the forward link will open a new email window from your email client (if using a desktop client like Outlook or Thunderbird). But you usually need to Alt-Tab to get to that window.

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/31689726-deb738fc-b3ec-11e7-9c3b-1fc71a12008f.png)

**Comment by AlaaKhalaf94** [comment]
passed
