### ISSUE TITLE
Deleting the role also delete the group

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#3638]
Here : http://alaa-reward.admin.kademi-prod.com/groups/
I have added anew group thats name is "test"
then I've opened it and add "Redeemer" role  on their own organisation

Then I've deleted it , and click in ok button
![capture1](https://user-images.githubusercontent.com/26510030/28572029-08a34160-714e-11e7-9826-7b60e0fe910c.PNG)

and role has not disappeared
![capture2](https://user-images.githubusercontent.com/26510030/28572063-2784031c-714e-11e7-8ab6-44c2ae6957ef.PNG)

Then I refresh the page . and show me an Error page
so I return to groups page , and see that "test" group does not exist

**Comment by bradmac** [comment]
This is actually deleting the group.

```
DELETE /groups/test4/
```

**Comment by tuzzmaniandevil** [comment]
Fixed
