### ISSUE TITLE
Could not delete group from points buckets page

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#3639]
here : http://alaa-reward.admin.kademi-prod.com/points-buckets/store001/?startDate=19%2F07%2F2017&finishDate=25%2F07%2F2017&dataQuery=&startPos=0#groups-tab

I can not delete "member-deleted-1500982606178" group

Notes : 
- This group already existed, but it has problems and has been deleted from the list of groups
- It succeeds in deleting the natural groups on the groups page

group page : http://alaa-reward.admin.kademi-prod.com/groups

**Comment by bradmac** [comment]
- We should not show soft deleted groups here
- Also check that soft deleted groups are not used in points processing

**Comment by tuzzmaniandevil** [comment]
Added a check to make sure soft deleted groups aren't used or shown

**Comment by AlaaKhalaf94** [comment]
passed
