### ISSUE TITLE
LeadMan app is creating multiple sales / leads groups

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#3642]
![image](https://user-images.githubusercontent.com/735555/28601970-8d9bb18a-71e5-11e7-8b81-61278cec6485.png)

**Comment by ducdhm** [comment]
@bradmac I got same issue in my local. `leads` and `sales` groups are duplicated so much.

**Comment by bradmac** [comment]
@ducdhm can you check the ajax response? it shouldnt have duplicated values:

**Comment by anhnt** [comment]
I can see duplicated groups on group management page

![image](https://user-images.githubusercontent.com/735555/28655123-ac4f33ac-72c3-11e7-8dc8-7629a02b9430.png)

**Comment by bradmac** [comment]
@anhnt please let me know if you can figure out what is creating them. ie is it server startup, lead creation, etc

**Comment by gonzalon** [comment]
Please test in a new account, create a website and enable / disable lead man app multiple times, should only have one sales and leads group.

**Comment by AlaaKhalaf94** [comment]
passed
