### ISSUE TITLE
Closing lead causes error

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3652]
{"data":null,"fieldMessages":[],"messages":["Closed deal"],"nextHref":"","status":true}

This is the lead that I closed.  After closing it went to white page with the above error.

http://kcrm.kademi.us/leads/12895528/

And this lead caused the same error http://kcrm.kademi.us/leads/13091004/

**Comment by bradmac** [comment]
Fixed - https://github.com/Kademi/kademi-dev/issues/3632
