### ISSUE TITLE
Cannot add profile without email to a group

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#3655]

**Comment by bradmac** [comment]
@anhnt can you provide more details?

**Comment by anhnt** [comment]
Please try adding this user to the group "Executing Priorities"
http://vaya.admin.kademi.us/manageUsers/13321809/#summary-tab

**Comment by bradmac** [comment]
Thats because this triggers the 6month journey, which attempts to send an email to the user, which fails because there is no email address:

```
    class java.lang.RuntimeException::org.hibernate.PropertyValueException: not-null property references a null or transient value: io.milton.cloud.server.db.EmailItem.recipientAddress
    class org.hibernate.PropertyValueException::not-null property references a null or transient value: io.milton.cloud.server.db.EmailItem.recipientAddress
```

**Comment by bradmac** [comment]
So thats a project implementation problem.
