### ISSUE TITLE
Blogs: Editor page has fixed height

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3656]
Keditor should be full height.
http://vaya.admin.kademi.us/blogs/vayablog/article1/#bodyCopy-tab

![image](https://user-images.githubusercontent.com/2201340/28660572-d92230a4-72f6-11e7-8600-4585c47a4dbb.png)

**Comment by ducdhm** [comment]
Done!

![Uploading FireShot Screen Capture #047 - 'Article #2' - localhost_8080_blogs_my blog bs2_article-2_#bodyCopy-tab.png…]()
