### ISSUE TITLE
Blogs: Cannot change an image

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3657]
No files upload options.
http://vaya.admin.kademi.us/blogs/vayablog/article1/#bodyCopy-tab

![image](https://user-images.githubusercontent.com/2201340/28660605-faf28d6e-72f6-11e7-9ffa-95dfb380226a.png)

**Comment by ducdhm** [comment]
Done! Need to deploy!

**Comment by AlaaKhalaf94** [comment]
I test with prod server , and I cannot change an image
http://reward09.admin.kademi-prod.com/blogs/blog01/art01/#bodyCopy-tab

![capture1](https://user-images.githubusercontent.com/26510030/28751647-f2447594-7515-11e7-86f7-98ee8d20674b.PNG)

**Comment by AlaaKhalaf94** [comment]
passed
