### ISSUE TITLE
Popup alert does not closed after I click on OK button

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#3658]
In this page : http://alaa-test.admin.kademi-prod.com/websites/alaatest04/version1/themeSelect
The popup appear when I want to change a theme for live version

![capture1](https://user-images.githubusercontent.com/26510030/28662664-97fc6e24-72c3-11e7-926f-1fa955ebfff8.PNG)

**Comment by ducdhm** [comment]
It's working normally!

**Comment by AlaaKhalaf94** [comment]
@duc , the problem is
Popup does not disappear after pressing the OK button
