### ISSUE TITLE
Video playback error in chrome

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3660]
When logged in with this user:
http://waterco.admin.kademi.com.au/manageUsers/37420105/#summary-tab

To this page:
http://training.waterco.com/programs/HDX15/HDX5/HDX5.5/pbiofilm.html

I am unable to play the video in chrome. It plays correctly in FF.

Firefox correctly plays the file using HLS, but in chrome when Flash is disabled or in "ask first" mode the file is being opened with webm:
http://training.waterco.com/programs/HDX15/HDX5/HDX5.5/094.mp4/alt-640-360.webm

This file is not generated, it times out.

**Comment by bradmac** [comment]
@tuzzmaniandevil i think we might need to move webm generation to AWS

**Comment by tuzzmaniandevil** [comment]
Added a fix for VOD
