### ISSUE TITLE
Test sending group emails

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3661]
1. Create a reward store account as described here - https://github.com/Kademi/kademi-dev/issues/3637
2. Import a set of about 100 fake user accounts (use mailinator addresses) into the participants group using the user import wizard. Include some invalid email addresses to test failed emailed logging, eg to domains that dont exist. **do not** set passwords on user accounts
3. Create an email welcoming users to the new reward store program. This should be a professional looking email with realistic content including images. Include a prominent button for the users to click on to go to the site (password reset). Here's an example - https://carters.admin.kademi.com.au/groupEmails/38966567/
4. Send the email to the group
5. Verify that email statistics are correct, for number of sends, failed emails etc
6. Open some emails with showing images enabled, and verify "open rate" statistics are correct
7. Verify that the user can click through to the rewards website and enter a password, then use the site

**Comment by AlaaKhalaf94** [comment]
Sending messages to the members of the group with available emails
this is youtube URL : https://youtu.be/Zrhqizf6JAE

Adding users with unavailable email
this is youtube URL : https://youtu.be/Ay1Kn0tFXm4

**Comment by bradmac** [comment]
Hi @AlaaKhalaf94 , thats looking good. But a couple of things
- just leave the from address blank if you dont have a custom domain name
- in the demo you are using a plain button and inserting a URL. But the test case says to use a password reset button

> Include a prominent button for the users to click on to go to the site (password reset)
