### ISSUE TITLE
Multiple prompts to create tags

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3662]
When adding a tag with the tags input on the lead page, I get prompted to create the tag multiple times (often 3)
![image](https://user-images.githubusercontent.com/826458/28696929-bc865268-738c-11e7-8d08-1d1c14e5293e.png)

This appears to be because the initTagsInput is called multiple times (see line 483) and it creates new event listeners each time

**Comment by ducdhm** [comment]
@bradmac I can't reproduce this issue in my local. Do you have step by step to reproduce?

**Comment by bradmac** [comment]
Hi @AlaaKhalaf94 can you please investigate. First verify that you see the same problem as me (use the itsinsured qa site), and check with me if not. Then please write steps to reproduce the problem and assign back to @ducdhm

**Comment by AlaaKhalaf94** [comment]
Hi @bradmac I can't reproduce this issue too , I can create tags normally without multiple prompts

I try here : http://leaddsash.kademi-prod.com/leads/341411/
admin : http://fortoday.admin.kademi-prod.com

**Comment by bradmac** [comment]
Great!
