### ISSUE TITLE
Set an email address by default in the process of sending emails

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#3676]
In this page : http://alaaemails.admin.kademi-prod.com/groupEmails/275727/#sendInfo-tab

When the user want to send emails , I think an mail address must exist by default in Email from address field
And this email address associated with the name of the site

OR , allow it to be blank, and then the system uses a default mail address for the selected website

**Comment by bradmac** [comment]
I dont think we should set a default address, because the correct address to use depends on which website they select. Instead we should just use a reasonable email if left blank

**Comment by bradmac** [comment]
New UI

![image](https://user-images.githubusercontent.com/826458/28801735-fd28e494-76a6-11e7-9a23-dbe5e99a06b3.png)

**Comment by AlaaKhalaf94** [comment]
passed
