### ISSUE TITLE
The notification appears twice

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#3677]
Here in points buckets page : http://alaaemails.admin.kademi-prod.com/points-buckets/foremail-points/
When I visit the page they appear

![capture1](https://user-images.githubusercontent.com/26510030/28776718-79bf15de-7600-11e7-9c58-2ed3207e731e.PNG)

**Comment by bradmac** [comment]
hey @ducdhm i think we can just remove these notifications entirely.

**Comment by ducdhm** [comment]
@bradmac We just need categorize messages.

New UI:
![newui](https://user-images.githubusercontent.com/1289631/28810716-6761a608-76b5-11e7-9c88-b3b5a8ff52a1.png)
![newui2](https://user-images.githubusercontent.com/1289631/28810717-67644ffc-76b5-11e7-80d3-3bfc1e637e72.png)

**Comment by ducdhm** [comment]
Done!
