### ISSUE TITLE
Create leadman summary stats component

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3678]
This should be a 2x2 table similar to that in the old leadDash.html template

Have a setting to select which funnel.

The 4 metrics should be:
- % tasks completed during the selected date range out of all tasks which are due within the selected date range
- the number of leads closed (ie completed) in the selected date range, out of the number of leads created within the date range
- Number of new leads created within the selected date range out of number of new contacts created within the date range
- Total closed sales within the selected date range

**Comment by AlaaKhalaf94** [comment]
The leadsStatsSummary Component appears twice in k-editor
once of them works well and the second shows error

![capture1](https://user-images.githubusercontent.com/26510030/28914143-4e559248-7843-11e7-9dd6-b6c0740076c0.PNG)

admin : http://leadsummary.admin.kademi-prod.com
K-iditor : http://version1.leadsummary.kademi-prod.com/contenteditor?fileName=index.html

**Comment by tuzzmaniandevil** [comment]
@AlaaKhalaf94 I tested it and seems fine?

**Comment by tuzzmaniandevil** [comment]
Found a bug and it has been fixed. Please re-test :smile:

**Comment by bradmac** [comment]
@tannguyen3489 currently the new component is not listening for changes to the date range selector.

Can you please update it so the stats do update when a new date range is selected?

**Comment by bradmac** [comment]
Also, for some reason the 2x2 grid is only occupying half of its cell. Please make sure this uses all of the container width
![image](https://user-images.githubusercontent.com/826458/28952420-2a64ea22-7925-11e7-98b9-d1192b739aba.png)

**Comment by tannguyen3489** [comment]
it was implemented on 1.3.2

**Comment by AlaaKhalaf94** [comment]
passed
