### ISSUE TITLE
Open rate in sending emails stop working

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#3680]
here : http://newerror.admin.kademi-prod.com/groupEmails/289869/#status-tab

I send email to 3 users , and I oped 2 of them
but Open rate does not change

![capture1](https://user-images.githubusercontent.com/26510030/28813395-c39c4b12-76a1-11e7-94ba-c650fcbd35f9.PNG)

![capture2](https://user-images.githubusercontent.com/26510030/28813402-c841947e-76a1-11e7-8332-c38ac69c5b22.PNG)

**Comment by bradmac** [comment]
Your email program needs to have enabled opening images.

**Comment by bradmac** [comment]
OK, looks like the pixel tracker isnt being inserted for component based emails

The component renderer needs to add this
```
<img src="http://$page.closest('website').domainName${formatter.portString}/ack?i=$page.emailItem.id" height="1" width="1" alt=""/>
```

**Comment by AlaaKhalaf94** [comment]
https://github.com/Kademi/kademi-dev/issues/3661

**Comment by AlaaKhalaf94** [comment]
Hi @tuzzmaniandevil 
I send email to 3 users , and I oped 2 of them
but Open rate does not change

http://fortoday.admin.kademi-prod.com/groupEmails/363643/#status-tab
