### ISSUE TITLE
Email component icons get in way

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3683]
The container icons sit on top of the text making it hard to edit.  They should sit outside the container.

![image](https://user-images.githubusercontent.com/2201340/28852250-312d231c-776b-11e7-91f9-4dbbe4058197.png)

**Comment by ducdhm** [comment]
@paddyow So which position do you want me to move?

**Comment by paddyow** [comment]
@ducdhm move on top of the bounding box.

![image](https://user-images.githubusercontent.com/2201340/36762979-28807c00-1c7a-11e8-9cae-eb7eddc951cd.png)

**Comment by bradmac** [comment]
@ducdhm if you're still not sure please discuss with Paddy directly rather then asking on the issue

**Comment by ducdhm** [comment]
Done!

**Comment by Uafinder** [comment]
Yeap, looks fine
