### ISSUE TITLE
A problem in Sales Data Uploader

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#3687]
Here before uploading it asks me to identify "Sales Data Series" field basically to make  Uploading  process
But in the selection table below, there is no name for this field

![capture1](https://user-images.githubusercontent.com/26510030/28859646-3f8d74e8-7761-11e7-94a5-6257f491225b.PNG)

http://newerror.admin.kademi-prod.com/tableUploaders/salesDataUploader
I try to upload this file : 
[salesDataUploader.zip](https://github.com/Kademi/kademi-dev/files/1192792/salesDataUploader.zip)

**Comment by tuzzmaniandevil** [comment]
@AlaaKhalaf94 you must select a sales data series on step 2, not step 3
