### ISSUE TITLE
Velocity code appears after upload points process when I don't select the reason column

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#3689]
User profile : http://newerror.admin.kademi-prod.com/manageUsers/292373/#pointsBucketTab-tab
![capture3](https://user-images.githubusercontent.com/26510030/28869329-05fe32c0-7785-11e7-829d-e87f5a100e0e.PNG)

From this page : http://newerror.admin.kademi-prod.com/tableUploaders/pointsUploader
I try to upload this file : [Points Uploader.zip](https://github.com/Kademi/kademi-dev/files/1193473/Points.Uploader.zip)

**Comment by tuzzmaniandevil** [comment]
Added a null check

**Comment by AlaaKhalaf94** [comment]
passed
