### ISSUE TITLE
OrgsLocator doesnt work

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3691]
The orgs locator page doesnt work with stock configuration.

What i saw initially was that the google api key entered in the googlemaps-lib app settings was not used in the orgs locator app. Instead there was a hard coded value.

I've updated this to use the configured value, but there are still problems.

I'm seeing an invalid API key error:
```
"Google Maps API error: InvalidKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#invalid-key-map-error"
```

Also, the orgsLocator.js script is not initialising the component. Initially this was looking for a class which was not used anywhere. I've added this class to the component but there still seems to be some problem with the initialisation because the selector is returning zero elements.

**Comment by bradmac** [comment]
Once thats done please update libs and ensure working correctly here:
http://version2.abn.kademi.com.au/orgsLocator
https://insured.admin.kademi.com.au/websites/abn/version2/#panel_apps-tab

**Comment by ducdhm** [comment]
Done!

**Comment by ducdhm** [comment]
http://version2.abn.kademi.com.au/orgsLocator is working now.
