### ISSUE TITLE
Changing version on courses page navigates to website manager

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3694]
Eg from here:
http://zoetis.admin.kademi.com.au/websites/zoetis-livestock-reseller/es5migration/programs/CATTLE/ZL0601M/

i end up here:
http://zoetis.admin.kademi.com.au/websites/zoetis-livestock-reseller/030817/#panel_details-tab

**Comment by ducdhm** [comment]
Already fixed in https://github.com/Kademi/kademi-dev/issues/3686
