### ISSUE TITLE
K-Survey Update

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3697]
Issue: The survey name is used in the front-end that the end user sees, however I need to add a survey name that is meaningful to me i.e. it has a code in it, but the front-end user does not see.

Update:
- Add a field to the top called 'Survey Name' which does not get displayed in the front-end template, but is used to describe the survey for the admin user only.
- Rename the field 'Name' to 'Survey title' which get's used in the front-end.

In the survey list page, we need to display the Survey Name, not title.

![image](https://user-images.githubusercontent.com/2201340/28906188-311f0a9a-7859-11e7-9ed7-04f2c60e78d3.png)

**Comment by anhnt** [comment]
done

**Comment by paddyow** [comment]
Rename field 'Mood' to 'Response' as K feedback can manage different types of feedback.

![image](https://user-images.githubusercontent.com/2201340/29010578-96d2a716-7b6f-11e7-894f-2a186958ad19.png)

**Comment by anhnt** [comment]
done
