### ISSUE TITLE
K Feedback not show question

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3698]
The K feedback generated code does not include the question, only the icons.  Add question as well.

**Comment by ducdhm** [comment]
Done!

![newui](https://user-images.githubusercontent.com/1289631/28933782-a3ab4d0e-78a8-11e7-8256-8143e1d92490.png)

**Comment by paddyow** [comment]
See this email http://vaya.admin.kademi.us/funnels/executing-priorities-journey/emailAction-m3w2/#message-tab

This is sent 
![image](https://user-images.githubusercontent.com/2201340/29012946-88bb5ee4-7b82-11e7-8a90-5c045736a4c8.png)

Note K feedback is not rendering the text above the icons.  Have updated APP versions.

**Comment by paddyow** [comment]
Ignore this
