### ISSUE TITLE
K Survey Layout

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3699]
@ducdhm 

Where we have a text only option, or just image, can the canvas area of the content refactor vs have an absolute height and width?

![image](https://user-images.githubusercontent.com/2201340/28909766-2d4a2abc-786d-11e7-9737-81f9af801a86.png)

**Comment by paddyow** [comment]
When you drop in a k feedback with text only the text is constraint to the fixed width and height container.
![image](https://user-images.githubusercontent.com/2201340/28952042-173aade6-7912-11e7-8bf1-f59e1b5dfef1.png)

This is fine if we are showing an image but what if we wanted to show 5 images that have avrying sizes likle this.

![image](https://user-images.githubusercontent.com/2201340/28952065-414a5096-7912-11e7-9aa1-93eeb7d77044.png)

Or we want to show 3 text responses like this.
![image](https://user-images.githubusercontent.com/2201340/28952122-828859b8-7912-11e7-82d1-0d3038bcf794.png)

The containers should not be fixed height and width, instead the image or text should display as they are uploaded with some padding and margins to spread out the options.

**Comment by ducdhm** [comment]
Done!
