### ISSUE TITLE
Update SendEmailGoalAction to allow sending to multiple recipients

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3709]
Allow the "to" field to return a comma separated list of email addresses. An email should be sent to each address in that list.

**Comment by mkhoudary** [comment]
Done and tested on QA

**Comment by bradmac** [comment]
Just one thing i noticed, inside the foreach loop if you cant find something currently it returns. I think instead it should just skip that email recipient, but continue the for loop for other recipients

Eg this return:
```
        for (String targetEmail : toEmails) {
            EmailItem i = EmailItem.instantiate(lead.getAdminDomain(), now, from2, p.getEmail());

            from2 = batchEmailService.generateReplyTo(from2, w, p, callback, i);

            if ( !from2.contains("@") ) {
                if ( w == null ) {
                    log.warn("Could not locate website  {} in organisation {} for funnel {}", this.website, org.getOrgId(), f.getName());
                    return nextNodeId;
```

https://github.com/Kademi/kademi-platform/commit/487f99a0a950659aace2a0e06c3e09f288a79740#commitcomment-24397524

**Comment by mkhoudary** [comment]
Fixed

**Comment by AlaaKhalaf94** [comment]
Hi @mkhoudary , when I leave white space after email , doesn't send message to it

I put this in "to" field "alaakhalaf94@mailinator.com , alaa@kademi.co"
"alaa@kademi.co" receive the message
"alaakhalaf94@mailinator.com" doesn't receive the message

**Comment by AlaaKhalaf94** [comment]
passed

**Comment by bradmac** [comment]
The change means that the default no longer works.

By default the action should send to the lead profile. But now when the recipient field is blank no email is sent

**Comment by bradmac** [comment]
Note that the change i've made here means that recipient emails which do not have a corresponding profile will not be sent. I'm not sure if that conflicts with existing requirements.
