### ISSUE TITLE
User without user admin role can add himself to any group

### ISSUE THREAD

**Issue by gonzalon** [Kademi/kademi-dev#3713]
A user in a group without the "User Administrator" role can add himself to any group through his profile page.
The delete does the pertinent validation.

**Comment by bradmac** [comment]
Here's how i think this should work
- user_admin role allows a user to add/remove groups on a profile, but only groups which do not include the Administrator role. 
- Only users with the Administrator role can add/remove groups with that role
- any user can view their own profile. But without user_admin role they only get access to view and edit basic info (password, unsub, userid, email, name)

**Comment by AlaaKhalaf94** [comment]
passed
