### ISSUE TITLE
Add user to group

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#3715]
![image](https://user-images.githubusercontent.com/735555/29021639-6304bd68-7b90-11e7-8a8e-99a9f5ec7de3.png)

Steps:

Create new users in http://vaya.admin.kademi.us/manageUsers/ with default membership: Participants in Cohort August 2017

Go to newly created profile and add membership Executing Priorities in Cohort August..
Add membership managing-time in Vaya

There is a membership: participants in Vaya group is automatically created?

**Comment by bradmac** [comment]
@anhnt i followed those steps but the extra group was not added:

http://vaya.admin.kademi.us/manageUsers/13734808/#summary-tab

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/29035048-23c87784-7b4f-11e7-84da-45018e77413c.png)

**Comment by ducdhm** [comment]
@anhnt I can't reproduct this issue. Please double-check again. Maybe an automation or journey runs...

**Comment by anhnt** [comment]
Just reproduced this in the profile http://vaya.admin.kademi.us/manageUsers/13748205/#general-tab

Initial group: Participants in Cohort August
Add Executing Priorities in Cohort August
Add managing-time
Fill value for extra fields: Competency and Habit
Add registered

**Comment by anhnt** [comment]
Yeah i think might be the issue with vaya journey as well

**Comment by mkhoudary** [comment]
Looking at **FunnelManager** method **createLead** line 485:

```
Lead lead = Lead.create(r, f.getBranch(), trackingId, cust, source, beginPoint.getNodeId(), beginPoint.getStageName(), now, session);
        if ( cust != null ) {
            if ( StringUtils.isNotBlank(f.getLeadsGroup()) ) {
                Group leadsGroup = Group.findGroup(C(CurrentRootFolderService.class).getOrganisation(), f.getLeadsGroup(), session);
                cust.createGroupMembership(leadsGroup, cust.getHomeAdminOrg(), session);
            } else {
                Group leadsGroup = C(LeadManApp.class).getLeadsGroup();
                cust.createGroupMembership(leadsGroup, cust.getHomeAdminOrg(), session);
            }

            lead.setInitialContactDate(now);
        }
```
We can observe that when a journey starts the membership is added to the homeMembershipOrg.. so this is part of the journey creation.

**Comment by ducdhm** [comment]
@anhnt @bradmac so what do you think about this? Is it issue?

**Comment by bradmac** [comment]
Yep, thats it. This is just so we have a group which identifies all lead profiles. We dont need to add them to the group if they're already in it.

So I've put in a change so it only adds them to the leads group if they're not already in the group.

**Comment by ducdhm** [comment]
@anhnt I think you can test it in your local now.

**Comment by anhnt** [comment]
I've tested locally and confirmed it working
