### ISSUE TITLE
K Feedback - show/hide title

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3716]
There are times when we don't want to show the Kfeedback title due to using some MVEL or something in the email body.

Rather than use code to hide it, add an option to show/hide the kfeedback title.

![image](https://user-images.githubusercontent.com/2201340/29042600-ef58e202-7bfa-11e7-8f06-de814e9d14da.png)

**Comment by ducdhm** [comment]
NewUI:

![newui](https://user-images.githubusercontent.com/1289631/29085359-3efeb838-7c99-11e7-9a16-771818bef3f7.png)
