### ISSUE TITLE
Visual query builder

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3718]
Update the queries page to allow creating adhoc queries with a visual editor
- select output columns
- build the query
- add aggregations

Perhaps use these
http://querybuilder.js.org/
https://github.com/piotch/jQuery-QueryBuilder-Elasticsearch

**Comment by bradmac** [comment]
Couple of probs:
- some weird problem with re-running or displaying results. Please make sure that if the query is changed and the user presses run they then see the output of that updated query
- handle the IP type in logs
- remove the site drop down at top right
- move the "Select fields" button into the results tab so its associated with the results table
- also move the size input into the results tab for same reason
- display aggregations in tables in another output tab

**Comment by bradmac** [comment]
Size doesnt seem to work:
![image](https://user-images.githubusercontent.com/826458/32359169-ba3eaf20-c0b0-11e7-89d0-93cb264e98c2.png)

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/32359258-9620cc3a-c0b1-11e7-9035-2b0e88a0178a.png)

**Comment by bradmac** [comment]
Aggregations dont appear to be getting rendered

**Comment by bradmac** [comment]
Something seems to be adding fields to the roles collection:
![image](https://user-images.githubusercontent.com/826458/32419788-bced6672-c2e4-11e7-9d88-f0ee6312a62e.png)

**Comment by bradmac** [comment]
Remove the aggregation name field:
![image](https://user-images.githubusercontent.com/826458/32419804-f16e13b0-c2e4-11e7-91da-5e34f95b9579.png)

**Comment by bradmac** [comment]
Also, i think a couple of layout changes would be good:
- move the query builder to a new tab, which should be the first tab
- move the aggregation builder UI into the aggregations tab
- allow for multiple aggregations

**Comment by Uafinder** [comment]
When opening, multiple pop-ups appears
![image](https://user-images.githubusercontent.com/1945230/33178080-7dee46ee-d06d-11e7-8281-1db3f3b6bcc9.png)

Pushing to the field label also gives a double pop-up
![image](https://user-images.githubusercontent.com/1945230/33178173-e13b8fe0-d06d-11e7-951f-fc34ec56e4ae.png)

Pop-ups should not multiply while several actions done
![image](https://user-images.githubusercontent.com/1945230/33178227-1a3fbb4a-d06e-11e7-8085-5b1202e4399c.png)

Pushing minus near the add fields button cause a very interesting bug
![image](https://user-images.githubusercontent.com/1945230/33178418-c5368d76-d06e-11e7-9260-c4968602ee6c.png)
![image](https://user-images.githubusercontent.com/1945230/33178430-cea461a8-d06e-11e7-92ef-71c789cf7d18.png)
http://vlad-test59.admin.kademi-ci.co/queries/level-logs/#queryBuilderTab-tab

**Comment by Uafinder** [comment]
Yup, it works!
