### ISSUE TITLE
Sales claims app

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3724]
Create a new marketplace app to allow users to enter sales data. In some cases these need to be approved by an admin before being activated. Once activated, create an entry in a sales data series, and save the record id on the sales claim.

Depends on
- Sales data app
- KongoDB
- User app

Components
- form to enter a new sales claim
- view claims showing status (for an end user)
- view pending claims (for an administrator)

Roles
- SalesClaimEditor ( can create and edit their own sales claims, but not approved records)
- SalesClaimAdmin (can review and accept or reject sales claims)

Admin screen
- search for sales claims, allow filtering by user, date, etc

Front end screen
- default page to allow viewing and entering sales claims for sales claim editors

Journey nodes
- goal for sales claim entered
- goal for sales claim approved/rejected

**Comment by ducdhm** [comment]
@bradmac How can I get session in custom app? I need it for adding record to data series.

**Comment by mkhoudary** [comment]
@ducdhm having a session into custom apps leaks a direct connection to database and leaves kademi with no protection at all since a session can do anything with database.

Instead we can create you the required feature as a method in the data series app so you can use it in your custom app.

**Comment by bradmac** [comment]
Yep, never use session in custom apps directly. Just use a method on sales data app if there is one other wise well add it

**Comment by bradmac** [comment]
@tuzzmaniandevil please check and add if needed

**Comment by bradmac** [comment]
@ducdhm a couple of issues i can see:

1.I dont think we should have a button to request approval. Just submitting the claim should make it require approval:
![image](https://user-images.githubusercontent.com/826458/29588039-1bd88252-87e4-11e7-997b-31f7d7fd63dc.png)
2. Please remove the spin animation on the status cog
3. Allow uploading a file attachment with the claim
4. The Product SKU field should be doing a lookup on SKU's, like we do on the promotions page (eg http://boschpromotions.nz/rewards/block-competition-vap/)
5. Remove "tags"
6. The fields should be displayed from the configured data series. Only display configured custom fields, and use their field name rather then "field 1" etc

**Comment by bradmac** [comment]
Current UI:

![image](https://user-images.githubusercontent.com/826458/29594006-194b5960-8802-11e7-9174-920ed0e77554.png)

![image](https://user-images.githubusercontent.com/826458/29594012-22509458-8802-11e7-871a-122555a2fa5a.png)

**Comment by ducdhm** [comment]
@bradmac Currently, I can add claim to Sale Data as a record but still an issue with it. I can't add Product SKU as well as extra fields. Our API doesnt support it yet

**Comment by bradmac** [comment]
Added product search controller to website.js, eg

http://version1.claim02.loopbackdns.com:8080/salesDataClaimsProducts/

```
[
{"tokens":["a1","$200 A La Carte Prepaid Visa","$200 A La Carte Prepaid Visa"],"value":"a1"},
{"tokens":["a2","$50 Myer Gift Card","$50 Myer Gift Card"],"value":"a2"}
]
```

**Comment by ducdhm** [comment]
Done!

**Comment by bradmac** [comment]
@tuzzmaniandevil can you please update the sales claim nodes so they are only active for a journy for that claim.

![image](https://user-images.githubusercontent.com/826458/29846281-3ffc8526-8d6a-11e7-9ee7-1ca0a7daa87e.png)

**Comment by tuzzmaniandevil** [comment]
Done

**Comment by bradmac** [comment]
Sales claim records need to be able to be made by anonymous users (ie non-logged in) or logged in users.

Please create a configuration option to control whether claims can be made by non-logged in users.

In this case we need to capture contact fields
- email 
- first name

For a non-logged in user, when the claim is submitted, attempt to locate a profile by email address. If not found auto-create the profile and link the claim to it. If one is found then use it.

**Comment by ducdhm** [comment]
Done!
