### ISSUE TITLE
Certificate has 2 pages with second page is blank

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#3725]
Reported from Katie

**Comment by anhnt** [comment]
http://zoetis.admin.kademi.com.au/websites/zoetis-livestock-reseller/030817/programs/CATTLE/ZL0779/ZL0779/#files-tab

**Comment by bradmac** [comment]
This is probably just a CSS/style issue related to the height of the content.

@ducdhm please investigate

**Comment by ducdhm** [comment]
As I checked, It's fixed!

**Comment by Uafinder** [comment]
Yup, looks fine at the moment... I've checked on test user in zoetis acc
Will do a re-check in fresh acc
