### ISSUE TITLE
Cant delete extra field in group settings page

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#3727]
http://anh.admin.kademi.com.au/groups/leads/

**Comment by anhnt** [comment]
Also reproducible in the US http://vaya.admin.kademi.us/groups/managers/

**Comment by bradmac** [comment]
@ducdhm looks like a problem because of the new modal. Its POST'ing to /groups/[groupname] but isnt sending any data, should be sending the removeFieldName parameter

**Comment by ducdhm** [comment]
Fixed!

**Comment by mkhoudary** [comment]
https://github.com/Kademi/client-vaya/issues/88
