### ISSUE TITLE
Velocity code appear in popup restore product in  Audit Records

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#3729]
Here : http://fortoday.admin.kademi-prod.com/auditRecords

when I want to restore any product that has been deleted , this popup appear and it contain velocity code it should not appear to the user

![capture1](https://user-images.githubusercontent.com/26510030/29248011-9daf359a-8015-11e7-80d1-6a364a129e34.PNG)

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
Yup, looks great
