### ISSUE TITLE
Ksurvey questions ordering is gone when reload page

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#3731]
Here "Manage Survey | Month 2 reflection survey" : http://vaya.admin.kademi.us/ksurvey/survey-57b96d7a-d1c2-40a5-9860-08de7d604d1f/#questions-tab
I arrange questions 1, 2, 3, 4 ,5

And when I preview the page in site : http://vaya-group.kademi.us/ksurvey/survey-57b96d7a-d1c2-40a5-9860-08de7d604d1f/?miltonUserUrl=/users/alaa2&miltonUserUrlHash=ae3a6f2a-29ce-4cca-bb81-72c39e35f028:qL_kb2aBt8JSLLcGnKX1qBNuhME
Order questions appear 1, 2, 3, 5, 6, 4

And when I come back to "Manage Survey | Month 2 reflection survey" I see the order that I do comes back devastating

**Comment by ducdhm** [comment]
Fixed!

**Comment by AlaaKhalaf94** [comment]
passed
