### ISSUE TITLE
Improve competitionForm component

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3735]
- add settings to allow selecting a promotion, so that the component can be used on content pages. If none selected it should use the promotion from the current page if possible
- setting for whether to show other users photo uploads or not
- improve the UI for photo upload. See screenshot below, this is pretty bad, we want something modern and awesome

![image](https://user-images.githubusercontent.com/826458/29288015-14e88d24-80ec-11e7-9189-6d86289b08d6.png)

**Comment by ducdhm** [comment]
New UI:
![aaaa](https://user-images.githubusercontent.com/1289631/30821926-396cbe14-a251-11e7-9b97-c9bac487cd77.png)

**Comment by ducdhm** [comment]
![newui2](https://user-images.githubusercontent.com/1289631/30821969-73f87154-a251-11e7-8fcf-da5899640e2e.png)

**Comment by bradmac** [comment]
:+1: looks nice!

**Comment by bradmac** [comment]
@Uafinder please discuss with @ducdhm if you need a hand setting up to test

**Comment by Uafinder** [comment]
1. Could not submit request
![image](https://user-images.githubusercontent.com/1945230/31809373-1e0092f8-b580-11e7-8263-e3ba6ae99df1.png)

2. Image pixelated
![image](https://user-images.githubusercontent.com/1945230/31809441-6cf08742-b580-11e7-8471-c2a9bbf47833.png)

http://vlad20-promo.kademi-ci.co/page2.html
http://version1.vlad20-promo.kademi-ci.co/contenteditor?fileName=page2.html&miltonUserUrl=/users/3120a759-575d-4b8e-9b11-11c221a4366f&miltonUserUrlHash=cf012988-68ac-4ff8-a5b0-7ca5ca7fadf3:_cZr-KYqSw9G373DAtcT7_Zw54s

3. Deselecting available fields in competition form setting doesn't make influence on the field appearance on page.
![image](https://user-images.githubusercontent.com/1945230/31809864-3777a274-b582-11e7-9d98-e8a7057e729e.png)

4. User can't upload multiple images.
![image](https://user-images.githubusercontent.com/1945230/31810131-493a893a-b583-11e7-97f1-ef8a2294380c.png)

**Comment by ducdhm** [comment]
@Uafinder 1, 2 and 3 are fixed. About 4, we allow user to upload only 1 photo per a promotion. I also hided  the preview panel of uploaded photo as your photo.

**Comment by Uafinder** [comment]
doh, it doesn't works at all
1. Create a page
2. Add a component
3. select promo and edit available fields - set checkboxes
4. Push save
5. refresh page
6. No checkboxes selected

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
1. Reduce image uploading window
It's original
![image](https://user-images.githubusercontent.com/1945230/32322862-a93757a0-bfce-11e7-9eda-293882ff8520.png)
It's component
![image](https://user-images.githubusercontent.com/1945230/32322882-b960fc12-bfce-11e7-945d-56338b65e2fe.png)

2. Visual bug after uploading first image and submitting request
It's clickable and leading to image uploaded earlier.
![image](https://user-images.githubusercontent.com/1945230/32322950-fca3e138-bfce-11e7-89ea-2bf3b6f9bd51.png)

3. Submit text, size, and color doesn't work at all.
![image](https://user-images.githubusercontent.com/1945230/32323881-2694c3f6-bfd2-11e7-979f-efaa8efe9a9d.png)
![image](https://user-images.githubusercontent.com/1945230/32323913-3a0a0900-bfd2-11e7-9a80-2cd03c0ef6d5.png)

http://version1.vlad30-promos_vlad-test30.kademi-ci.co/pags1.html
http://vlad-test30.admin.kademi-ci.co/pages/vlad30-promos/version1/

**Comment by ducdhm** [comment]
@Uafinder 
`2.` and `3.` are fixed.

About `1.`, I think it's OK because the width of upload photo is depended on width of its container. And look at your 2 examples, first one is in container which has layout is `Box` and second one is `Auto` or `Wide` layout. That's why they are looked different.

**Comment by Uafinder** [comment]
2 and 3 ok
1st still a question - probably would be good to reduce it somehow, because if it will be more images it will create a mess on the screen.
![image](https://user-images.githubusercontent.com/1945230/32373716-535a8e76-c0a3-11e7-9743-bde7769718b9.png)


Also
4. Show user's photo probably should hide Photo Gallery, not image uploads window.
![image](https://user-images.githubusercontent.com/1945230/32373962-7b577ae6-c0a4-11e7-8bee-1e76dd783993.png)
![image](https://user-images.githubusercontent.com/1945230/32373977-88d41364-c0a4-11e7-873b-9d56013a20ab.png)

5. Terms and conditions leads to error
![image](https://user-images.githubusercontent.com/1945230/32374166-3aef848e-c0a5-11e7-846d-7237093426cf.png)
![image](https://user-images.githubusercontent.com/1945230/32374180-446a859a-c0a5-11e7-973d-4627a3c95b54.png)

**Comment by Uafinder** [comment]
Works like a charm
