### ISSUE TITLE
Mandatory organisation field in Alerts

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#3740]
Please modify dashboard alerts app to require organisation field, and if not set for any reason have it as the account org by default.

**Comment by mkhoudary** [comment]
Doned

**Comment by AlaaKhalaf94** [comment]
When I try to leave organisation field in Alerts empty , and save
The save operation succeeds
http://fortoday.admin.kademi-prod.com/manageAlerts/alert-363297#details-tab

Then I refresh the page , and I see "the main org" was putted in organisation field by default

**Comment by gonzalon** [comment]
Hi @AlaaKhalaf94 
you can leave it empty. If so, it will save it with the account org.

So seems that what you are seeing is right :)

**Comment by AlaaKhalaf94** [comment]
passed
