### ISSUE TITLE
Convert journal to lib

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#3741]
Need for https://github.com/Kademi/client-vaya/issues/21

**Comment by ducdhm** [comment]
New UI when panel is hide
![newui](https://user-images.githubusercontent.com/1289631/29373583-ec03f828-82d8-11e7-8e2b-fff2e4980338.png)

New UI when panel is showed
![newui2](https://user-images.githubusercontent.com/1289631/29373591-f288d88a-82d8-11e7-90b0-f12ad7c57c83.png)

New UI when saving/loading journal entry
![newui3](https://user-images.githubusercontent.com/1289631/29373612-00c4c508-82d9-11e7-80e0-824c49aee52b.png)

**Comment by paddyow** [comment]
1) Have an option in the APP to hide or show the page name
2) The page name should show the page title by default, then if no title show the page name
2) Show the date the journal entry was made (small text above entry)

**Comment by ducdhm** [comment]
Moved to https://github.com/Kademi/kademi-dev/issues/3754
