### ISSUE TITLE
Create an ajax service to retrieve a list of fields from FieldService

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3744]
Related - https://github.com/Kademi/kademi-dev/issues/3742

Ajax/json service to retrieve the list of fields. This should only return fields from currently active apps.

Should allow filtering on only fields which support profile filtering, which would also return enough information to be used in QueryBuilder.js (see #3746)

**Comment by tuzzmaniandevil** [comment]
The URL for the resource is `/_fields`
Here is an example of the JSON response:
```JSON
{
  "data": [
    {
      "input": "",
      "operators": [
        "equal",
        "not_equal",
        "less",
        "less_or_equal",
        "greater",
        "greater_or_equal",
        "is_null",
        "is_not_null"
      ],
      "values": [],
      "id": "birthDate",
      "label": "Birthday",
      "placeholder": "*|birthDate|*",
      "type": "datetime"
    },
    {
      "input": "",
      "operators": [
        "equal",
        "not_equal",
        "less",
        "less_or_equal",
        "greater",
        "greater_or_equal",
        "is_null",
        "is_not_null"
      ],
      "values": [],
      "id": "ageYears",
      "label": "Age",
      "placeholder": "*|ageYears|*",
      "type": "integer"
    }
  ],
  "fieldMessages": [],
  "messages": [],
  "nextHref": "",
  "status": true
}
```

**Comment by bradmac** [comment]
Hey @tuzzmaniandevil couple of things i picked up on
- please move to a kademi package. We should not be using the milton package namespace for anything new
- instead of "fieldservice" use just "fields" as the package name

So instead of io.milton.cloud.server.fieldservice.FieldsService should have co.kademi.server.fields.FieldsService

**Comment by tuzzmaniandevil** [comment]
I've made those changes now
