### ISSUE TITLE
add ckeditor plugin to provide a list of fields, allow user to insert

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3745]
Depends on https://github.com/Kademi/kademi-dev/issues/3744

The list should be all fields returned from FieldService

When the user selected a field it should be inserted into the editor at the current cursor location with square brackets, eg [firstName]

**Comment by ducdhm** [comment]
Note:
```
{
    "input": "",
    "operators": [
        "equal",
        "not_equal",
        "less",
        "less_or_equal",
        "greater",
        "greater_or_equal",
        "is_null",
        "is_not_null"
    ],
    "values": [],
    "id": "profile_birthDate",
    "label": "Profile Birthday",
    "placeholder": "*|profile_birthDate|*",
    "type": "datetime"
}
```
`id` will be text which we'll add in content as placeholder.

**Comment by ducdhm** [comment]
New UI:
![newui](https://user-images.githubusercontent.com/1289631/30823798-9d138a5a-a257-11e7-90d4-b3e5f13502c8.png)

**Comment by ducdhm** [comment]
@bradmac Plugin is ready but I checked in frontend, seem like backend doesnt support it yet. Right?

**Comment by bradmac** [comment]
Is the KCode toolbar button integrated with EDM's?

![image](https://user-images.githubusercontent.com/826458/30838540-8d8c01cc-a2c8-11e7-9926-23ef16e0d02b.png)

**Comment by bradmac** [comment]
Its all working :)

I just had to change to using the placeholder attribute, eg
```
 "placeholder": "*|profile_birthDate|*",
```

**Comment by ducdhm** [comment]
@bradmac I already added KCode plugin to EDM.

![newui](https://user-images.githubusercontent.com/1289631/30840487-bb11ad30-a2a1-11e7-9785-d55a00c87ac8.png)

**Comment by bradmac** [comment]
OK, must have been a caching thing

**Comment by Uafinder** [comment]
*|profile_email_domain|* - returns email address, should be email domain, e.g. everything after @ 
*|profile_orgIds|* - return groups values, should be org id's
http://vlad32-test.admin.kademi-ci.co/emails/1718439

**Comment by ducdhm** [comment]
@bradmac Can you help me explain these fields to @Uafinder ?

**Comment by bradmac** [comment]
Please ignore the lead fields for now

> This is for eCommerce as far as I understand.
Well, for product purchases, which can be either from ecom or reward stores

**Comment by bradmac** [comment]
> |profile_orgIds| - return groups values, should be org id's

This is correct, its intended to be that way. This is intended to be used for filtering and decisions, rather then displaying in pages.

**Comment by bradmac** [comment]
> |profile_email_domain| - returns email address, should be email domain, e.g. everything after @

OK, that needs to be fixed

**Comment by bradmac** [comment]
Fixed domain name field

**Comment by bradmac** [comment]
Fixed FirstPurchaseDate

**Comment by Uafinder** [comment]
The thing is that specific fields (which depending to specific app) are absent on custom pages.
E.g. I've create a page in a leads website and edit it. KCode for leads will not appear. The same situation with eCommerce and reward store.
![image](https://user-images.githubusercontent.com/1945230/33326306-4c6c3b14-d45d-11e7-82d1-1c98b8e53ef2.png)
http://vlad-test62.admin.kademi-ci.co/pages/vlad62-leads1/version1/?contenteditor=lea.html

the full list of this fields are present only in emails, because it depends on global apps

**Comment by bradmac** [comment]
> The thing is that specific fields (which depending to specific app) are absent on custom pages.
E.g. I've create a page in a leads website and edit it. KCode for leads will not appear. The same situation with eCommerce and reward store.

If i understand you correctly, this is correct and by design.

When an app is enabled (either at account or website level) it makes its fields available. If its not enabled, those fields are not available.

**Comment by Uafinder** [comment]
Nope, I mean that:
If you enable an app for account and on the website, and try to add kcode to the custom page on this website, fields (which are specific to this app will not appear)

**Comment by bradmac** [comment]
LeadManApp doesnt have any fields. I think what you're looking for is in FunnelApp

**Comment by Uafinder** [comment]
Not sure.
for example this fields are part of what app:
|lead_createdDate|
|lead_dealAmount|
|lead_stage|
|lead_source|

Or those ones:
|products_lastPurchaseDate|
|products_firstPurchaseDate|
|products_averagePurchaseAmount|
|products_highestPurchaseAmount|
|products_numPurchases|
(reward store app or ecommerce app)

?

**Comment by bradmac** [comment]
the lead fields are from FunnelsApp. The product fields are from ProductsApp

**Comment by Uafinder** [comment]
Adding some lead fields to the custom page caused page to be completely broken.
1. Go here http://vladtest02.admin.kademi-ci.co/pages/vlad02-leads/version1/
2. Add new page
3. add some text component
4. Push save, ensure that page could be viewable
5. Edit it again, and add kcode with for example |lead_createdDate|
6. try to check this page again and you will see 500 server error
![image](https://user-images.githubusercontent.com/1945230/33769938-9c6a48fc-dc34-11e7-9317-f556543a654f.png)
![image](https://user-images.githubusercontent.com/1945230/33769943-a085ec98-dc34-11e7-8062-06a9c9f7f359.png)

**Comment by bradmac** [comment]
```
09:00:39 Caused by: java.lang.NullPointerException
09:00:39 	at com.fuselms.apps.funnels.FunnelApp.lambda$fields$0(FunnelApp.java:305)
09:00:39 	at co.kademi.server.fields.AbstractField.evaluate(AbstractField.java:67)
09:00:39 	at co.kademi.server.fields.FieldsService.evaluateAllFields(FieldsService.java:168)
09:00:39 	at co.kademi.server.components.DynamicComponentService.evaluateDynamicComponents(DynamicComponentService.java:81)
09:00:39 	at co.kademi.server.components.DynamicComponentService.evaluateDynamicComponents(DynamicComponentService.java:63)
09:00:39 	at io.milton.cloud.server.web.templating.SimpleHtmlTemplater.writePage(SimpleHtmlTemplater.java:176)
09:00:39 	at io.milton.cloud.server.web.templating.SimpleHtmlTemplater.writePage(SimpleHtmlTemplater.java:103)
09:00:39 	at io.milton.cloud.server.apps.admin.editor.ContentEditorPage.renderContentEditor(ContentEditorPage.java:58)
09:00:39 	at io.milton.cloud.server.apps.admin.editor.ContentEditorPage.sendContent(ContentEditorPage.java:74)
09:00:39 	at io.milton.http.CompressingResponseHandler.respondContent(CompressingResponseHandler.java:116)
```

**Comment by bradmac** [comment]
Should be fixed now

**Comment by Uafinder** [comment]
Same thing
![image](https://user-images.githubusercontent.com/1945230/33883250-d42d95de-df43-11e7-9875-d7b13102d1d2.png)
![image](https://user-images.githubusercontent.com/1945230/33883255-d8155fd8-df43-11e7-95fd-a71cd8b6bbaa.png)

http://vladtest04.admin.kademi-ci.co/pages/vlad04learn/version1/
http://version1.vlad04learn-vladtest04.kademi-ci.co/test.html

**Comment by bradmac** [comment]
The previous error occured when editing a page, this error occurs when viewing the page. Thats a differenent error :)

**Comment by bradmac** [comment]
Have found a few other places that could produce the same error and fixed.

**Comment by Uafinder** [comment]
Yup, it doesn't show error at the moment...
However:
1. You add some KCode which depends on Funnel app
2. push save
3. refresh page
4. All kcodes disappears

http://vladtest05.admin.kademi-ci.co/pages/vlad05leads/version1/
http://vladtest05.admin.kademi-ci.co/pages/vlad05leads/version1/?contenteditor=page.html

**Comment by bradmac** [comment]
hey @Uafinder i've tested locally and seems ok, and your reference account has expired.

can you check if the problem above is still active?

**Comment by Uafinder** [comment]
ok, so kcode works ok for me at the moment
partially, leads fields are not visible, but it's another story
