### ISSUE TITLE
Blog editing container getting cut off at bottom of page

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3748]
http://vaya.admin.kademi.us/blogs/vayablog/gilead-ldp-resource-guide-5/#bodyCopy-tab

Unable to scroll down to the very bottom.

![image](https://user-images.githubusercontent.com/2201340/29389082-8cc492a2-832b-11e7-8147-8dcee6b8531c.png)

**Comment by ducdhm** [comment]
Fixed!
