### ISSUE TITLE
Show group type

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3749]
When viewing and choosing a group, it would be good to show the group type icon i.e. tag or list..

![image](https://user-images.githubusercontent.com/2201340/29395255-eac78a5e-8352-11e7-9455-bdd78a7a0a0d.png)

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/32888853-47f13cee-cafb-11e7-853c-b1b6688553d8.png)

Please update kademi-dev before testing

**Comment by Uafinder** [comment]
it works!
