### ISSUE TITLE
Calendar selector should allow selecting personal calendars

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3750]
The calendar selector component currently allows the user to select calendars from the current website.

But sometimes users have their own personal calendars, and they should be able to select that from the list, eg;
http://itsinsuredqa-crm.kademi.com.au/users/tanteset1/Calendars/default/

**Comment by bradmac** [comment]
Duc, Wes has mostly done it, but please just add a "Personal calendars" label above the list of personal calendars in the drop down

**Comment by ducdhm** [comment]
Note from @bradmac 

```
ok, so first thing, if the calendarapp is enabled, then any new user will have a default calendar created
ie when the user is created, a calendar gets created for them. Called "default
```

**Comment by ducdhm** [comment]
New UI:
![aaaaaaaa](https://user-images.githubusercontent.com/1289631/30845032-c781f5c4-a2bb-11e7-88fd-e13cdfbeaa65.png)
