### ISSUE TITLE
Allow creating and editing calendar events through front end sites

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3751]
Should only show options to edit if the user has authoring permission on the calendar.

http://insured-crm_insured.kademi.com.au/users/mark2/Calendars/default/
For example:
![image](https://user-images.githubusercontent.com/826458/35949033-6869ed8e-0cd4-11e8-82d9-35a03759bf02.png)

**Comment by bradmac** [comment]
This is needed urgently for ITI

**Comment by anhnt** [comment]
Please go to calendar page and add or edit event
![image](https://user-images.githubusercontent.com/735555/35966106-74c20dda-0cef-11e8-8a68-d348badfff33.png)

**Comment by bradmac** [comment]
@anhnt as discussed please make this use a simple html editor only, not keditor

**Comment by anhnt** [comment]
Done

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/36031782-99cb1a7a-0db4-11e8-914c-8c062f593dfe.png)
this link should be removed

upload images to files into calendar tab fails
![image](https://user-images.githubusercontent.com/1945230/36032251-13c259be-0db6-11e8-9982-4139706cd88e.png)

pushing edit image fails whole page and browser
![image](https://user-images.githubusercontent.com/1945230/36032308-3cf44b08-0db6-11e8-806a-ddb77f9f0e9f.png)

**Comment by bradmac** [comment]
hey @anhnt regarding uploading, we should disable the file browsing option and only allow uploading via the assets tab. I believe @ducdhm has already done this on other pages so please talk to him.

**Comment by Uafinder** [comment]
Raised some non-critical problems.
Mostly looks good
