### ISSUE TITLE
Have a Create Lead modal in admin profile page

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#3758]
We need to have a create lead modal like the one in KCRM:

![image](https://user-images.githubusercontent.com/3704174/29513671-b7cc567e-866e-11e7-8dca-5c6fed80ed60.png)

![image](https://user-images.githubusercontent.com/3704174/29513678-bddfc032-866e-11e7-8b75-597ca2db2497.png)

![image](https://user-images.githubusercontent.com/3704174/29513696-c40bebf2-866e-11e7-8434-939b6ae4aa95.png)

Please note that this functionality is to be added to the profile page > leads tab in the admin, so for this the lead profile email field will be pre filled.

**Comment by mkhoudary** [comment]
https://github.com/Kademi/client-vaya/issues/178

**Comment by bradmac** [comment]
:+1:

**Comment by bradmac** [comment]
@gonzalon  please assist @anhnt by changing the Funnels app to always show the lead tab, even when a user has no leads.

**Comment by anhnt** [comment]
deployed to QA

**Comment by AlaaKhalaf94** [comment]
passed
