### ISSUE TITLE
Ability to track who issued points and points debits

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3759]
Add "issued by" field to points report. This is to assist with auditing.

- the field will be blank for points which have been created by the import process
- for manually created records it will link to the admin user who created it
- same for debit records

Related to quote QU-0163

Please let me know when complete

**Comment by gonzalon** [comment]
Done

**Comment by gonzalon** [comment]
@AlaaKhalaf94 take in mind that if you are going to test it with existing data, you have to re-index for it to work
* rewardPoints
* rewardPointsDebit

**Comment by AlaaKhalaf94** [comment]
Hi @gonzalon , Brad ask to add "issued by" as link to the admin user who created it , please fixed it
 - In Points Report : http://alaa-test4.admin.kademi-ci.co/reporting/points?startDate=03%2F10%2F2017&finishDate=09%2F10%2F2017
 - In Points Debit Report : http://alaa-test4.admin.kademi-ci.co/reporting/pointsDebit?startDate=03%2F10%2F2017&finishDate=09%2F10%2F2017

And in Points Report , the reward Name is not assigned

![capture1](https://user-images.githubusercontent.com/26510030/31327431-dedf5452-acd7-11e7-9b51-0acfd6cf0a5b.PNG)

**Comment by gonzalon** [comment]
@AlaaKhalaf94 fixed the reward name not assigned,
we dont support links in the reports atm.

**Comment by AlaaKhalaf94** [comment]
passed
