### ISSUE TITLE
[Menu Component] Option for move portlets("shoppingCart") after user dropdown

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#3761]
![untitled](https://user-images.githubusercontent.com/1289631/29598472-461b05da-87f3-11e7-8260-a9874a772ca9.png)

**Comment by bradmac** [comment]
are you sure we need this? i really dont like the idea of stuffing a million options into our menu configuration

that will make it unuseable

wouldnt it be better to just have one location which makes sense?

**Comment by ducdhm** [comment]
Let it be!
