### ISSUE TITLE
Badges and levels app

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3762]
Overview
----
An achievement is a series of levels connected to some measurable quantity. The measurable quantity can be either a points bucket or a data series. Levels are purely linear, ie they are achieved simply for reaching a threshhold and must be attained in order. Eg to get level 2 you must first get level 1

A badge represents a user has achieved some criteria, and will usually be awarded from a journey. The criteria is arbitrary, its not limited to being linear. Eg you can ge the "Sales Superstar" badge for getting 10 sales in one month and "Customer champion" for getting 2 good reviews in a week. But you dont need to get one before another

Data
----

BaseRecognition
- name
- title
- topic
- image

RecognitionBadge Extends BaseRecognition
- title
- image
- groups

RecognitionLevel Extends BaseRecognition
- title
- image
- value

RecognitionTopic
- Level[]
- title
- image
- groups
- points bucket, OR
- data series

RecognitionAward
- badgeID, or Achievement level ID
- topic
- ... ?

Journey nodes
----
- award badge
- badge awarded goal
- level achieved goal

Components
----
- Badges panel, shows all badges for the current user
- Achievement panel, shows the current level for the current user

**Comment by bradmac** [comment]
I'm doing the backend implementation in java. Will look at doing the front end with a custom app

**Comment by bradmac** [comment]
Badges can now be awarded from journeys

**Comment by bradmac** [comment]
Levels are awarded when the admin clicks the "Generate awards" button on a topic

![image](https://user-images.githubusercontent.com/826458/30008740-6df38280-9176-11e7-9840-a97a394438ce.png)

**Comment by bradmac** [comment]
@ducdhm please integrate into demos

**Comment by paddyow** [comment]
http://claims.admin.kademi.us/recognition/14591839/

When I change the ''Levels Value'' to sales data series and save, it reverts back to points bucket after I refresh.

![image](https://user-images.githubusercontent.com/2201340/30058761-ad1724d0-927f-11e7-9656-5afcfe0711fb.png)

**Comment by bradmac** [comment]
Still need to build components

**Comment by bradmac** [comment]
@tuzzmaniandevil can you please 
- fix the config bug above
- create components (@duc can finish off)

**Comment by bradmac** [comment]
levelPanelComponent is functional. Shows the highest level for the current user in a selected topic

![image](https://user-images.githubusercontent.com/826458/30091776-7df1486c-930f-11e7-82c6-192415509502.png)


![image](https://user-images.githubusercontent.com/826458/30091732-48668b76-930f-11e7-8cd4-f09c53567478.png)

**Comment by bradmac** [comment]
The manage topic page now has a list of awards

![image](https://user-images.githubusercontent.com/826458/30091863-ef47cdec-930f-11e7-9d40-76da1b4bed19.png)
