### ISSUE TITLE
Having goal time controls in admin

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#3765]
Please add those goal time controls to the lead page in admin:

![image](https://user-images.githubusercontent.com/3704174/29612750-7acc6680-880b-11e7-8392-3430829c8211.png)

**Comment by mkhoudary** [comment]
@anhnt I did basic implementation in the lead page.. please add some front-end magic

**Comment by anhnt** [comment]
done 
![image](https://user-images.githubusercontent.com/735555/29659643-21f57aa4-88e9-11e7-976e-14f24d43824c.png)

**Comment by mkhoudary** [comment]
Tested
