### ISSUE TITLE
Auction end date does not get remembered

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3773]
When I create an auction from the auction list page, choose an end date in the modal popup, then save, then open the auction to edit its details, the end date resets to the current date.

http://hinda.admin.kademi.us/auctions/fitbit-1/#details-tab

![image](https://user-images.githubusercontent.com/2201340/29737885-d133df1c-8a59-11e7-952f-c51585dc2497.png)

**Comment by ducdhm** [comment]
@anhnt If I remove timezone lib, it's working normally. Can you double-check again?

**Comment by anhnt** [comment]
fixed 

![image](https://user-images.githubusercontent.com/735555/29920980-24723ef2-8e7a-11e7-8d56-efcd1946c54e.png)

**Comment by anhnt** [comment]
@AlaaKhalaf94 please rebuild QA and test it

**Comment by Uafinder** [comment]
Aha!
It saved ok at the moment, but:
When organisation has no timezone selected, values are not displaying.
Timezone selected
![image](https://user-images.githubusercontent.com/1945230/30544604-b8188d46-9c8f-11e7-904f-41ad8de3e025.png)
timezone removed
![image](https://user-images.githubusercontent.com/1945230/30544622-c841857e-9c8f-11e7-83bc-dda92acca7cc.png)
![image](https://user-images.githubusercontent.com/1945230/30544653-e3012806-9c8f-11e7-90ed-979bcea7b205.png)

**Comment by gonzalon** [comment]
@Uafinder seems ok to me

**Comment by Uafinder** [comment]
The same sit at the moment:
Timezone selected
![image](https://user-images.githubusercontent.com/1945230/32374506-bdd71082-c0a6-11e7-9f2c-07f14008a90e.png)
![image](https://user-images.githubusercontent.com/1945230/32374522-cc54570a-c0a6-11e7-8ac7-009a3d9258d8.png)

Removing timezone:
![image](https://user-images.githubusercontent.com/1945230/32374543-df06e3fe-c0a6-11e7-90b3-157d7649c674.png)
![image](https://user-images.githubusercontent.com/1945230/32374554-ea95dafe-c0a6-11e7-8a16-061866d8c66f.png)

http://vlad-test31.admin.kademi-ci.co/auctions/test1/#details-tab

**Comment by gonzalon** [comment]
##TZ Buenos Aires selected:
![image](https://user-images.githubusercontent.com/2773216/32581589-592e89b4-c54f-11e7-8209-13fd8a467c68.png)

![image](https://user-images.githubusercontent.com/2773216/32581596-6443acbc-c54f-11e7-8726-3286af04f684.png)


##No selected TZ:
![image](https://user-images.githubusercontent.com/2773216/32581623-86ab2a50-c54f-11e7-89c2-d075669c8933.png)

![image](https://user-images.githubusercontent.com/2773216/32581631-92e9dc4e-c54f-11e7-8d19-2900f8168460.png)

##TZ Kiev Selected:
![image](https://user-images.githubusercontent.com/2773216/32581659-ade94c14-c54f-11e7-884b-ecf7c4321ae0.png)

![image](https://user-images.githubusercontent.com/2773216/32581666-b7d1d8ea-c54f-11e7-823d-04db41dbb8e3.png)

**Comment by Uafinder** [comment]
It works like a charm!
