### ISSUE TITLE
Cannot see excel data when uploading file into ORGs

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3774]
http://hinda.admin.kademi.us/tableUploaders/organisationsUploader

This file:
[ORGs - List of companies r2.xlsx](https://github.com/Kademi/kademi-demos/files/1253365/ORGs.-.List.of.companies.r2.xlsx)

Has data:
![image](https://user-images.githubusercontent.com/2201340/29738102-0717c0ea-8a5e-11e7-990c-2c5dcfaf88d2.png)

What I see:

![image](https://user-images.githubusercontent.com/2201340/29738109-170c397c-8a5e-11e7-8ea0-cc87b457cbf0.png)

**Comment by paddyow** [comment]
Ok worked it out.  The data needs an ORG type to upload.

But the state isn't showing even through it's in the spreadsheet.

![image](https://user-images.githubusercontent.com/2201340/29738132-aa15c558-8a5e-11e7-997b-dcca24254424.png)

[ORGs - List of companies r2.xlsx](https://github.com/Kademi/kademi-dev/files/1253367/ORGs.-.List.of.companies.r2.xlsx)

**Comment by paddyow** [comment]
Ok worked it out.

It needed me to add the ORG ID - @bradmac does the system not auto generate the ID if not added to the file?

![image](https://user-images.githubusercontent.com/2201340/29738150-4611f620-8a5f-11e7-8829-839f829c1efc.png)

**Comment by bradmac** [comment]
You do need to provide an OrgID. But that doesnt explain why blank values were displayed for address etc

**Comment by Uafinder** [comment]
looks ok at the moment
