### ISSUE TITLE
Sales Data Upload Issue

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3777]
When uploading to here http://hinda.admin.kademi.us/tableUploaders/salesDataUploader?salesDataSeries=sales-data

This file:
[Sales Data.zip](https://github.com/Kademi/kademi-dev/files/1253385/Sales.Data.zip)

I get these errors and 4 rows failed:
[Error.zip](https://github.com/Kademi/kademi-dev/files/1253386/Error.zip)

Yet the file looks fine.

**Comment by bradmac** [comment]
Its just because there are 4 blank rows at the end of the file
```
,35,1/11/2016 0:00,johnbrown@mailinator.com,26/08/2017 0:00,,1000008
,900,1/12/2016 0:00,johnbrown@mailinator.com,26/08/2017 0:00,,1000009
,,,,,,
,,,,,,
,,,,,,
,,,,,,
```

**Comment by bradmac** [comment]
@tuzzmaniandevil please ensure blank rows are ignored without raising an error
