### ISSUE TITLE
Validation error on Auction Page

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3780]
http://hinda.admin.kademi.us/auctions/laptop2/#details-tab

If you don't add a value into the Description field, you get a network error, but it should tell the user to add a value into the Description field.

![image](https://user-images.githubusercontent.com/2201340/29746815-ac893312-8b29-11e7-8513-52ab64ffe640.png)

**Comment by anhnt** [comment]
Auction description is now required field

**Comment by Uafinder** [comment]
it's really required now, so it's ok
