### ISSUE TITLE
Poll comma separation issue

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3781]
http://hinda.admin.kademi.us/kpoll/managePolls/poll-8zLYvsOZumaPQryZnrtTncd7DTl45c01#detail-tab

When creating a poll question, if you add a comma in the answer, it splits the answer into 2 like below.

![image](https://user-images.githubusercontent.com/2201340/29746877-bd0b6a6e-8b2b-11e7-9874-7a344d5eb7d1.png)

Becomes this when you submiot

![image](https://user-images.githubusercontent.com/2201340/29746876-b08a354a-8b2b-11e7-9414-39b57c00985a.png)

Should be able to insert a comma into an answer

**Comment by ducdhm** [comment]
Done!

**Comment by Uafinder** [comment]
http://vlad-test10.admin.kademi-ci.co/kpoll/managePolls/
http://vlad10-learn.kademi-ci.co/dashboard
I cant make poll visible on my account. Could you help?

**Comment by ducdhm** [comment]
@Uafinder Now, we have component for Kpoll, so you should drag n drop this component into the page which you want to view.

**Comment by Uafinder** [comment]
Yeap, it works!
@ducdhm thanks for your help...
