### ISSUE TITLE
Velocity code appear when the journey ends 

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#3786]
Its appear here in this page : http://gilead.admin.kademi.us/leads/14255654/#information-tab

![capture1](https://user-images.githubusercontent.com/26510030/29768580-755a9d9c-8bef-11e7-8e40-357b724bbb29.PNG)

**Comment by anhnt** [comment]
it now will hid that part when lead is closed

**Comment by AlaaKhalaf94** [comment]
passed
