### ISSUE TITLE
Profile.find gets all profile including disabled ones

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#3787]
We need to filter only enabled profiles

**Comment by mkhoudary** [comment]
Done

**Comment by bradmac** [comment]
Hey @mkhoudary you cant just the semantics of a widely used method like that. This could break the logic in production accounts.

It is perfectly correct to have a method which locates profiles regardless of the status of their soft delete flag. There are many cases where we need to locate a user which may or may not have been soft deleted.

Its best to instead create a new method like Profile.findEnabled and then use that method in situations you know definitely must only locate enabled users.

**Comment by bradmac** [comment]
FYI, i have reverted the change to Profile.find

**Comment by mkhoudary** [comment]
👍

**Comment by mkhoudary** [comment]
Added a new method
