### ISSUE TITLE
Email Shows Wrong Content

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#3788]
This email , in title " Lead viewed link " , that send when the lead open link which sent to him in other email , show wrong content

![capture1](https://user-images.githubusercontent.com/26510030/29770880-ce38fcb0-8bf9-11e7-8732-0318ac3c5606.PNG)

**Comment by mkhoudary** [comment]
Fixed

**Comment by mkhoudary** [comment]
@AlaaKhalaf94 please update leadman-lib in gilead and test accordingly in production

**Comment by AlaaKhalaf94** [comment]
passed
