### ISSUE TITLE
Course picker is broken

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3789]
Profile http://hinda.admin.kademi.us/manageUsers/14203500/#summary-tab

Page http://reward-store-hinda.kademi.us/myLearning

Cannot select another program from the drop down, there are 2.

![image](https://user-images.githubusercontent.com/2201340/29799474-2e16fa4e-8ca7-11e7-9dcd-e44e5358fcc8.png)

**Comment by ducdhm** [comment]
Fixed!
