### ISSUE TITLE
Ampersand missing in module title + course title

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3790]
http://hinda.admin.kademi.us/websites/reward-store-hinda/version1/programs/p1/q1/m1/#details-tab

Expected:
![image](https://user-images.githubusercontent.com/2201340/29799527-916adcb4-8ca7-11e7-972b-45eca0f53cfd.png)

Result:
![image](https://user-images.githubusercontent.com/2201340/29799538-996dc002-8ca7-11e7-804a-88fa8de0d2f1.png)

**Comment by ducdhm** [comment]
@bradmac It's known issue. Can you double-check it?

**Comment by bradmac** [comment]
@ducdhm what do you mean by a known issue? i think we can just handle this with appropriate encoding

**Comment by ducdhm** [comment]
@gonzalon Can you help me on this issue?

 * I save my module title as `Module 1 &amp; 2`
 * In frontend, my code just is `$mod.title`
 * Instead of display `Module 1 & 2`, it displays only `Module 1 2`

**Comment by gonzalon** [comment]
@ducdhm added a escape for html entities now I can see it fine:

![image](https://user-images.githubusercontent.com/2773216/35069572-6ec26f12-fc3f-11e7-9bac-01a2acdc9f29.png)

I checked around and couldn't find another place isn't showing it fine, let me know if you find any!

**Comment by Uafinder** [comment]
YYup, looks better

**Comment by Uafinder** [comment]
Same bug with a course name:
E.g. i have a course name "c1 & title" and it shows me like "c1 title"
![image](https://user-images.githubusercontent.com/1945230/35210109-8cf380bc-ff59-11e7-90dc-b9ee3331e7cd.png)
![image](https://user-images.githubusercontent.com/1945230/35210118-9418eeb8-ff59-11e7-9cc7-f19dae8ff544.png)
![image](https://user-images.githubusercontent.com/1945230/35210120-99ee6480-ff59-11e7-9ebf-e0dfab9cb545.png)
http://vladtest25.admin.kademi-ci.co/websites/vlad25learn/version1/programs/p1/c1/

**Comment by gonzalon** [comment]
![image](https://user-images.githubusercontent.com/2773216/35884876-e849dc74-0bf0-11e8-85d2-4e4708d64625.png)

**Comment by Uafinder** [comment]
Yup, it works!
