### ISSUE TITLE
Inverting rego page

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3793]
http://claims.admin.kademi.us/pages/claims-demo/version1/

If you invert the container for the rego page, the modal popup text is white, so you cannot read it.

![image](https://user-images.githubusercontent.com/2201340/29817423-4d76b402-8cfb-11e7-829d-1974cb0e3e03.png)

**Comment by ducdhm** [comment]
Done!

**Comment by Uafinder** [comment]
looking good at the moment
