### ISSUE TITLE
KCMR: Cannot connect companies to profiles

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3794]
This lead has a company name 'Hone' associated with it.
http://kcrm.kademi.us/leads/14337648/

The company (ORG) was created when I created the lead.

Under companies, the ORG did not show any members associated with it, even though the company was created at the same time the lead was.
http://kcrm.kademi.us/companies/

In the lead page, when I re-type the company Hone, it cannot find it, or any other companies.
![image](https://user-images.githubusercontent.com/2201340/29852150-d7c3e1c2-8d7b-11e7-8a23-b66c3c85d3ea.png)

**Comment by bradmac** [comment]
I can see a member associated with the company:

![image](https://user-images.githubusercontent.com/826458/29854666-93836d82-8d9b-11e7-84d5-c15ee8ff054b.png)

**Comment by bradmac** [comment]
But i can see there is a problem searching companies

No results - http://kcrm.kademi.us/leads?orgSearch=h

500 error - http://kcrm.kademi.us/leads?orgSearch=

**Comment by bradmac** [comment]
@tuzzmaniandevil please investigate

**Comment by tuzzmaniandevil** [comment]
matchQuery only works when a query string isn't blank, I've added a check now
