### ISSUE TITLE
Improve list after demos

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#3795]
Updating...

 * Can't find Signup app in web site manager (need to enable it in Manage App first)
 * Can't find Sales Data app in web site manager (need to enable it in Manage App first)
 * alerts-lib is not enabled when enabling Alerts app
 * Move translate stuff to KToolbar
 * Default, KToolbar should be hidden instead of showed
 * Register component doesnt show name fields although `Display name fields` option is checked as initialized

**Comment by bradmac** [comment]
- Create KSignup, KSalesData and KAlerts as marketplace apps 
- make sure each app has all necessary dependencies, eg libs and other apps

**Comment by ducdhm** [comment]
Done!
