### ISSUE TITLE
KCRM: Cannot see any analytics

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3796]
http://kcrm.kademi.us/analytics/kademi-sales

![image](https://user-images.githubusercontent.com/2201340/29855861-50f1cdfa-8d92-11e7-8fe3-d0ee9197579f.png)

**Comment by bradmac** [comment]
I've updated apps, and its working now

![image](https://user-images.githubusercontent.com/826458/29897820-d5e6dd26-8e36-11e7-9a9c-8b165180396c.png)
