### ISSUE TITLE
KCRM: Closing a lead causes white error page

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3797]
Close this lead to see what i see.  This happens with all leads I close.

http://kcrm.kademi.us/leads/11377186/

**Comment by bradmac** [comment]
Yep, got that

![image](https://user-images.githubusercontent.com/826458/29865964-1131b3f4-8dcb-11e7-8172-4c69db26636d.png)

**Comment by anhnt** [comment]
I've tested locally and there's no problem when closing a lead. Just updated kcrm leadman-lib to the latest version. @paddyow can you please confirm its working on the kcrm site now?
