### ISSUE TITLE
Module renewal functionality

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#3799]
Currently, when a ModuleStatus is completed the user is able to view the module again, but it is in readonly mode.

The new ModuleExpiryProcessor checks for modules which have passed their renewal date (60 days prior to expiry) and sets the renewal flag, and raises an event which will usually email the user to ask them to do the module again.

This means that a module must appear as if it is not completed when it is past its renewal date, and must allow the user to re-complete the module. Quizes should be reset.

**Comment by mkhoudary** [comment]
https://github.com/Kademi/client-zoetis/issues/272

**Comment by gonzalon** [comment]
@mkhoudary now the ModuleExpiryProcessor reset all the data but the completed status.
Now if the module is in the renewal period the can do it again.

**Comment by bradmac** [comment]
@gonzalon please move the event out of the domain class. Event management should be handled at the manager or service layer, not at the domain layer

ModuleStatus
```
DefaultIndexedItemUpdatedEvent e = new DefaultIndexedItemUpdatedEvent(getWebsite().getOrganisation(), null, this, false, session.getTransaction());
EventUtils.fireNoThrow(C(EventManager.class), e);
```

**Comment by mkhoudary** [comment]
@gonzalon I will need to have the module renewal period configurable from the module page.

**Comment by bradmac** [comment]
As discussed, thats a nice to have but we probably wont have it ready for when yuo need it. So best to test locally or in QA using the time simulator

**Comment by mkhoudary** [comment]
I've checked the renewal feature
