### ISSUE TITLE
Create LearningLog app indexer

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3800]
Please create a new AppIndexer as part of LearningApp

This should be very similar to ModuleStatusAppIndexer, except that it will be indexing from LearningLog instead of ModuleStatus.

This is because LearningLog is a permanent record of module completions, while ModuleStatus only represents current status, and can change as records expire.

However, the index needs to have fields for renewalDate and expiryDate, these fields might need to be added to LearningLog. Also might be good to add the module status ID

**Comment by AlaaKhalaf94** [comment]
At your request @mkhoudary

**Comment by AlaaKhalaf94** [comment]
passed
