### ISSUE TITLE
Language management

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3810]
The TranslationService currently has 2 hardcoded languages.

Please update this to have a configurable list of languages which should be persisted to the database

Create a new role called "Translater". This role is required to allow users to edit translations.

Update ManageTranslationsPage to use this.

Update ManageTranslationsPage to have search and pagination. Allow searching by
- select language from dropdown
- search by source type
- search by source id
- search by field
- search by translated text

ManageTranslationsPage should allow
- add/edit/delete of languages
- add/edit/delete of translations

**Comment by AlaaKhalaf94** [comment]
Hi @gonzalon , where can I see these updates ?

**Comment by gonzalon** [comment]
@AlaaKhalaf94 
For translations:
http://alaa.admin.kademi-ci.co/translations/

In the manage translations you can get to the languages page:
http://alaa.admin.kademi-ci.co/languages

**Comment by AlaaKhalaf94** [comment]
Hi @gonzalon , I try here : http://alaa-test4.admin.kademi-ci.co/translations/ and search by field doesn't work with me

And I add more than 100 translations  and the pagination doesn't appear

**Comment by gonzalon** [comment]
@AlaaKhalaf94 The search works by the start of the word, atm it's searching by:
sourceType
sourceId
translated

Going to add sourceField.
Related to the translations with the same data, one is Source0102 and the other is source0102. 
As its generating a hash with the text it's not the same!

**Comment by gonzalon** [comment]
Pagination added

**Comment by AlaaKhalaf94** [comment]
Here : http://alaa-test4.admin.kademi-ci.co/translations/ When I try to search about "two" word there is one result , but the pagination still appear

![capture1](https://user-images.githubusercontent.com/26510030/31373111-7018466c-ada1-11e7-8a28-d215d3cf4ff6.PNG)

And when I refresh the page , the pagination disappear
It shall disappear when the search results are less than 100 without refresh , please fix this @gonzalon

**Comment by AlaaKhalaf94** [comment]
Here : http://alaa-test4.admin.kademi-ci.co/translations/

When I try to add new translation with the same exist translation data it show me that The operation was successfully
and doesn't add any new translation

![capture1](https://user-images.githubusercontent.com/26510030/31614264-79bcacf2-b28e-11e7-8568-4fe61986e62a.PNG)

@gonzalon ,  please fix that to show error message when this case happen

**Comment by gonzalon** [comment]
Now it's showing The translation was updated / created accordingly

**Comment by AlaaKhalaf94** [comment]
passed
