### ISSUE TITLE
Custom report should use table name, not table title

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#3811]
![image](https://user-images.githubusercontent.com/735555/30058675-3bf33f46-9266-11e7-8d9e-c55befc2f7d6.png)

There's no option value

![image](https://user-images.githubusercontent.com/735555/30058694-4a8256c8-9266-11e7-8d20-8e984539b5b7.png)

**Comment by bradmac** [comment]
Fixed
