### ISSUE TITLE
scheduled email attachment should use data table csv

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#3812]
See here https://zoetis.admin.kademi.com.au/scheduledEmails/gudair-accreditation-report/#configuration-tab

![image](https://user-images.githubusercontent.com/735555/30058808-bafba38c-9266-11e7-8495-e1b64fb4ed38.png)

So when go to ```https://zoetis.admin.kademi.com.au/reporting/gudair-accreditation-report.csv``` i got 500 error

The url should be csv output of data table ie 
```
https://zoetis.admin.kademi.com.au/queries/gudairAccreditationTable?as=csv&from=0&size=10000
```

**Comment by anhnt** [comment]
https://github.com/Kademi/client-zoetis/issues/280

**Comment by bradmac** [comment]
Actually no, its correct to be sending content from the CustomReportCsvPage. This uses the selected query internally to generate that data.

The error causing the 500 response is:
```
Caused by: java.lang.NullPointerException
	at io.milton.cloud.server.apps.reporting.CustomRepoReportCsvPage.sendAsCsv(CustomRepoReportCsvPage.java:84)
	at io.milton.cloud.server.apps.reporting.CustomRepoReportCsvPage.sendContent(CustomRepoReportCsvPage.java:71)
```

**Comment by bradmac** [comment]
Fixed in next deploy.

But @anhnt if you need a workaround, just replace nulls in your query table with empty strings

**Comment by anhnt** [comment]
worked on AU server now
