### ISSUE TITLE
pages of modules not working well

### ISSUE THREAD

**Issue by salehh93** [Kademi/kademi-dev#3813]
if moving modules from olhub to new website it's not working well if was there are fields
and click on next without filling fields and this field has class required appear problem
like this
![module2](https://user-images.githubusercontent.com/23012214/30061995-435f31b8-9252-11e7-9c71-5eaf1fa3a873.jpg)

![module3](https://user-images.githubusercontent.com/23012214/30062237-21df5d14-9253-11e7-9587-d3fd68d7a404.jpg)

can you check 
here
http://version1.ae-acdelco-rewards.kademi.com.au/programs/p1/c1/m1/pfirst-page.html
or here 
http://version1.idhealth-training.kademi.com.au/programs/Carers/Carers1/Carers01/p38703.html

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/30088216-0a421812-92f9-11e7-91c5-26c1859bc2fd.png)

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/30088236-31bee6d6-92f9-11e7-97f3-f8fac306b743.png)

**Comment by bradmac** [comment]
learner-lib updated to 1.1.1
KLearning updated to 1.0.2

**Comment by bradmac** [comment]
Note that jquery.module.js is now part of learning-lib

**Comment by bradmac** [comment]
Please deploy updated libs to .AU

**Comment by bradmac** [comment]
Should be fixed after deploying and updating to learning-lib 1.1.1
