### ISSUE TITLE
Cannot process rewards from manage KPI page

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3814]

**Comment by gonzalon** [comment]
Couldn't  reproduce it. Any indications?

**Comment by bradmac** [comment]
Example URL - http://localhost:8080/sales/bosch-sales/kpis/monthly-trade-sales/?period=6#results-tab

![image](https://user-images.githubusercontent.com/826458/31104530-fd4e34a0-a839-11e7-8b1d-ad0c9dd159e7.png)

But this period does require reward processing:

![image](https://user-images.githubusercontent.com/826458/31104537-149ffca6-a83a-11e7-909c-e85bf1159ae8.png)

**Comment by AlaaKhalaf94** [comment]
Hi @gonzalon , How can I test ?

**Comment by gonzalon** [comment]
1. Create a data series /sales/
![image](https://user-images.githubusercontent.com/2773216/31251656-347a9b1a-aa7b-11e7-85c2-ab27f0e9167e.png)

2. Create test data
![image](https://user-images.githubusercontent.com/2773216/31251049-34940ea8-aa79-11e7-981d-a66d3286ac8c.png)
![image](https://user-images.githubusercontent.com/2773216/31251708-687555a4-aa7b-11e7-803d-518838b71553.png)

3. In the new series create a KPI
4. process the kpi

**Comment by AlaaKhalaf94** [comment]
passed
