### ISSUE TITLE
open and close for dropdown at the same time

### ISSUE THREAD

**Issue by salehh93** [Kademi/kademi-dev#3817]
in module page there is dropdown don't working well  
for example this page
http://version1.idhealth-training.kademi.com.au/programs/Carers/Carers1/Carers01/p57534.html
please click on any dropdown in page

I think because there is in module js function repeated twice
function initLearningContentStyles()
..apps/learner/module.js

**Comment by bradmac** [comment]
Hi @salehh93 

module.js should not be used anymore, its been replaced with jquery.module.js

I've checked the page above and i can see that module.js is not being included in the page.
```
<script charset="utf-8" src="/theme/apps/learner/jquery.module.js">//</script>
```

**Comment by ducdhm** [comment]
@salehh93 Can you re-check again? I see you change `module.js` to `jquery.module.js` and seem like this issue doesnt happen anymore

**Comment by salehh93** [comment]
passed
