### ISSUE TITLE
Panel component

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3818]
Create a new KEditor component
- allows editing HTML content similar to existing plain html component
- also allows selecting an icon to appear inside the panel at top left
- allows selecting a panel colour style

Examples of the end result:
![image](https://user-images.githubusercontent.com/826458/30138069-81738f9e-93ba-11e7-81b5-357931f7761d.png)

![image](https://user-images.githubusercontent.com/826458/30138080-8bc44baa-93ba-11e7-82c5-622f78979cd2.png)

**Comment by anhnt** [comment]
done

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/30358728-a3d9e186-9870-11e7-9948-20bcf265e598.png)

**Comment by AlaaKhalaf94** [comment]
Hi @anhnt , I want you to put color chooser to panel box please , To have the possibility of creating such a picture attached at the top

And put color chooser to icon also, not only for background of it please

**Comment by bradmac** [comment]
Hi @anhnt, currently the icon is always white on black. 

![image](https://user-images.githubusercontent.com/826458/30397233-49dcbc5c-9920-11e7-9b97-cd8b2e65be88.png)

We need it to use theme styles appropriately, like bootstrap alerts:
![image](https://user-images.githubusercontent.com/826458/30397306-8cd8a322-9920-11e7-8488-a5e6000efaf8.png)

Notice how the panel border, background, and text and icon foreground/background all use variants of the selected style? We should do the same

**Comment by anhnt** [comment]
done

![image](https://user-images.githubusercontent.com/735555/30411595-360eb13c-993c-11e7-8177-536f124659ad.png)

Also user can set custom color for icon

**Comment by AlaaKhalaf94** [comment]
passed

**Comment by AlaaKhalaf94** [comment]
Hi @anhnt , why the min-height is 190px ? It's causing me trouble in appearance

![capture1](https://user-images.githubusercontent.com/26510030/30596365-92fe9050-9d5c-11e7-8d55-0f71a30e069b.PNG)

**Comment by bradmac** [comment]
I think we need a min-height, but much less, should be just for a single line, ie about 30px

**Comment by anhnt** [comment]
We use standard bootstrap panel so we can define less params in theme-params.less.

**Comment by bradmac** [comment]
Hey @anh we need users to be able to use this component without coding. So we should override that in bootstrap Base

**Comment by anhnt** [comment]
panel should have option to not show the icon

**Comment by bradmac** [comment]
hey @ducdhm we need the min height change above. Note sure about @anhnt s comment about not showing icon..

**Comment by anhnt** [comment]
added min height and option to toggle show panel icon
