### ISSUE TITLE
Create a dropdown panel component

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3819]
- create a component similar to the plain html component which allows editing HTML content
- allow entering a title (probably in settings)
- allow selecting a panel background style

End result should be similar to this:
![image](https://user-images.githubusercontent.com/826458/30138187-ff17564c-93ba-11e7-91ef-bc8208c0fc45.png)

**Comment by anhnt** [comment]
done
![image](https://user-images.githubusercontent.com/735555/30267780-d3f941e0-970d-11e7-93cb-ac624c650c44.png)

**Comment by AlaaKhalaf94** [comment]
passed

**Comment by AlaaKhalaf94** [comment]
https://github.com/Kademi/Client-3DN/issues/53

**Comment by AlaaKhalaf94** [comment]
Hi @anhnt , Can you reduce the min-height of the body bf component ?

![capture1](https://user-images.githubusercontent.com/26510030/30628312-3e32564c-9dde-11e7-8ccf-1466f086be46.PNG)
