### ISSUE TITLE
Improve style of hide following button

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3820]
Learning styles includes a button which initially hides content following it, and when clicked displays content up to the next hide following component

This has been re-implemented from the old Fuse theme to bootstrap, but the style isnt correct

It should look like this:
![image](https://user-images.githubusercontent.com/826458/30138283-7aeee316-93bb-11e7-874c-1001794fdd02.png)

But it currently looks like this:
![image](https://user-images.githubusercontent.com/826458/30138288-87c139fe-93bb-11e7-9135-c21e9312c6e5.png)

- Please add an arrow to the right as per the original design.
- Use an inverted colour scheme, so it has a solid colour

**Comment by anhnt** [comment]
this is working for me with an arrow
![image](https://user-images.githubusercontent.com/735555/30373828-da7d4bd8-98ac-11e7-9e4b-ff7d19aaba88.png)

And that button is k-theme default style button

**Comment by AlaaKhalaf94** [comment]
Hi @anhnt , Where can I find this button and try use it ?

**Comment by anhnt** [comment]
@AlaaKhalaf94  please go to Elearning -> Edit a module page then click to the button

![image](https://user-images.githubusercontent.com/735555/30409430-15bf3364-992f-11e7-8707-28d27cac614f.png)

**Comment by bradmac** [comment]
hey @anhnt could you also make this available as a component? I think there are valid use cases for both having it inline and also having it beween other html blocks

**Comment by AlaaKhalaf94** [comment]
Hi @anhnt , can you reduces the right padding here ?

![capture1](https://user-images.githubusercontent.com/26510030/30431682-0d34fdb2-9968-11e7-8c6c-29b3ef3a65d0.PNG)

**Comment by bradmac** [comment]
The arrow should be right aligned, like standard bootstrap dropdown buttons

**Comment by AlaaKhalaf94** [comment]
Hi @anhnt , Can you make the ability to put two effective buttons in one page under each other?

like here in this page : http://training.idhealtheducation.edu.au/programs/Carers/Carers3/Carers05/p7-bipolar-disorder.html

**Comment by bradmac** [comment]
Just to confirm the requirement for this button
- all content following the button should be initially hidden
- when clicked, all content **up to the next show/hide button** should be displayed

This logic is already implemented in the old styles, should just be a copy/paste

**Comment by ducdhm** [comment]
Note: Should move js stuff of this button out of jquery.module.js or module.js

**Comment by ducdhm** [comment]
Settings for new component:
![aaaa](https://user-images.githubusercontent.com/1289631/30577851-17acca82-9d3b-11e7-83fb-35d58af9058b.png)

**Comment by AlaaKhalaf94** [comment]
passed
