### ISSUE TITLE
Update groups page

### ISSUE THREAD

**Issue by gonzalon** [Kademi/kademi-dev#3822]
- Should be able to filter by an org in the groups page.
- Users having multiple memberships should be listed multiple times
- Remove should only remove the membership selected

**Comment by gonzalon** [comment]
Related to: https://github.com/Kademi/client-emc-cca/issues/25#issuecomment-327485238

**Comment by gonzalon** [comment]
![image](https://user-images.githubusercontent.com/2773216/30142652-1ea037ac-93d6-11e7-8b7a-f5ac581dc83a.png)
![image](https://user-images.githubusercontent.com/2773216/30142666-2cfc5448-93d6-11e7-9938-0902835a1b89.png)

**Comment by Uafinder** [comment]
A few questions:
1. Is this a members counter or memberships counter?
If one user has membership in more than one org, it adds +1 to counter, so memberships become more than physical members...
![image](https://user-images.githubusercontent.com/1945230/30541993-48ab0960-9c86-11e7-90b3-d8fcefa8162d.png)
2.  Same question here on members page
![image](https://user-images.githubusercontent.com/1945230/30542041-7a88c364-9c86-11e7-81d0-6cb3033cc296.png)

**Comment by Uafinder** [comment]
Also, probably would be great to change text when user membership is deleting.
![image](https://user-images.githubusercontent.com/1945230/30542329-abdc2b94-9c87-11e7-89fe-9701ab6c5f4a.png)
Should be something like:
Are you sure you want to remove 1 user from group?
or
Are you sure you want to remove 1 user membership?

**Comment by bradmac** [comment]
"1. Is this a members counter or memberships counter?" - it should be a count of memberships. So if a user is connected to 2 orgs it should count as 2 memberships
"2. Same question here on members page" - yes, same

**Comment by bradmac** [comment]
"Also, probably would be great to change text when user membership is deleting." - Fixed

**Comment by Uafinder** [comment]
Very minor:
When you delete one member text appends in plural (e.g. membershipS)

**Comment by bradmac** [comment]
"When you delete one member text appends in plural (e.g. membershipS)" - we can live with that :)

**Comment by bradmac** [comment]
@Uafinder if everythign else is fine please close the issue

**Comment by Uafinder** [comment]
Yup, works correct
