### ISSUE TITLE
Module pages have all gone out of orders

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#3824]
> Hi, I am working on a module and the pages have all gone out of order? Is there a way to stop the system moving the pages around, its really hard when there are a lot of pages to get them back in order 
https://zoetis.admin.kademi.com.au/websites/zoetis-livestock-reseller/030817/programs/OTHER/ZL0721/ZL0721/#files-tab

@AlaaKhalaf94 please try to reproduce this issue by creating a new module on QA with lot of pages. **do not touch to that above module**

**Comment by bradmac** [comment]
Note that ordering is preserved in each page with the "order" param which can be viewed directly with the file manager.

https://zoetis.admin.kademi.com.au/repositories/zoetis-livestock-reseller/030817/programs/OTHER/ZL0721/ZL0721/

For example page pbreaks-the-flea-lifecycle.html has "order"=12
https://zoetis.admin.kademi.com.au/repositories/zoetis-livestock-reseller/030817/programs/OTHER/ZL0721/ZL0721/texteditor?fileName=pbreaks-the-flea-lifecycle.html

![image](https://user-images.githubusercontent.com/826458/30184972-d27e4fe6-9473-11e7-9b3b-caa371da6367.png)

**Comment by bradmac** [comment]
Also, we have had a problem in the past with order when there were more then 10 pages, because ordering was alphabetical. Eg it would go 1, 10, 11,12, 2, 3, 4

That bug should have been fixed a while ago, but please check

**Comment by AlaaKhalaf94** [comment]
I checked and There is no bug
