### ISSUE TITLE
KCCRM: Kademi sales funnel analytics not showing

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3825]
http://kcrm.kademi.us/analytics/kademi-sales

All panels are blank.

**Comment by bradmac** [comment]
However, when clicking on the date control (top left) the date picker does not appear

I can see in the logs this:
```
[jquery.pageDatePicker] Dropdown trigger is clicked
```

But the range picker is not shown

**Comment by bradmac** [comment]
@ducdhm can you please investigate:
http://kcrm.kademi.us/analytics/agency-sales

**Comment by anhnt** [comment]
fixed
