### ISSUE TITLE
we need to controller on padding  for website logo

### ISSUE THREAD

**Issue by salehh93** [Kademi/kademi-dev#3826]
we need to controller form navbar component 
for example 
![logoneed](https://user-images.githubusercontent.com/23012214/30164006-cec768d2-93e3-11e7-8c5c-9ee09c56ee45.jpg)

should the padding : 0 15px ;

**Comment by salehh93** [comment]
done

**Comment by bradmac** [comment]
Looks good!

**Comment by AlaaKhalaf94** [comment]
Checked
