### ISSUE TITLE
Problem with infinite scroll in reward store component

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3827]
For this site:
http://asrdev.admin.kademi.us/websites/devsite01/version1/#panel_apps-tab

In this front end reward store:
http://devsite01.kademi.us/general-2/

It appears that the infinite scroll isnt working.

**Comment by faithtek** [comment]
This is not an issue. I am in the middle of development on this.

**Comment by bradmac** [comment]
Gotcha!
