### ISSUE TITLE
Add paginator to reward store products list

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3829]
Currently the reward store products list page displays all matched products.

- Please change this to use a paginator 
- Seperate pages for adding and removing products
- allow filtering by category
- all adding/removing either selected items (ie using checkboxes) or all matching records

**Comment by AlaaKhalaf94** [comment]
- Adding product is in seperate page but removing products **isn't**

- Part of word category is hidden under the select  box

![capture1](https://user-images.githubusercontent.com/26510030/30372500-af0ce5d8-9886-11e7-8290-d93bb58f02b0.PNG)

**Comment by bradmac** [comment]
"Adding product is in seperate page but removing products isn't" - that is correct. We have split the two activities (adding and removing) intentionally to fix some useability issues

"Part of word category is hidden under the select box" - thats ok for this page
