### ISSUE TITLE
Subscriotions: credits

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3836]
- when a new plan is selected, calculate a credit for the current plan (if any) and reduce the new plan's initial payment by that amount
- add a credit field on KademiSubscription. Whenever a payment is due, reduce the payment amount by the credit, and then zero out the credit amount. If the credit is greater then the payment amount just do not make the payment, and reduce the credit. We need to record this somewhere somehow

**Comment by AlaaKhalaf94** [comment]
Hi @gonzalon , How can I test ?

**Comment by bradmac** [comment]
Actually we can jsut close this for now
