### ISSUE TITLE
Allow use of rule based groups with sending group emails

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3839]

**Comment by bradmac** [comment]
Need to check performance of sends to large groups, including large normal groups

**Comment by bradmac** [comment]
Example rules for a group
```
{                                  
"condition":
"AND",     "rules": [ {
"id": "profile_groups",
"field":"groups",   "type":
"string", "input": "select",
"operator": "contains",  "value":
"donor", "ruleType": "rule"  } ],
"ruleType": "ruleList"  
}
```

**Comment by bradmac** [comment]
We now have UI editable rules:

![image](https://user-images.githubusercontent.com/826458/30246856-58aff3ee-9659-11e7-8798-f5663ce65f69.png)

**Comment by Uafinder** [comment]
Pending until logical expressions will not be repaired

**Comment by Uafinder** [comment]
I've a dynamic group which has 627 members
But when i've tried to send emails to them it generate only 10 emails. Looks like some limitations.
![image](https://user-images.githubusercontent.com/1945230/30634173-e360d176-9df6-11e7-9016-9051d0a50f2e.png)
![image](https://user-images.githubusercontent.com/1945230/30634192-f199c158-9df6-11e7-923d-457d44b05e45.png)

**Comment by Uafinder** [comment]
Also, problem with scheduled emails:
Scheduled emails fires to the no one, when dynamic group is assigned.
http://vlad-test.admin.kademi-prod.com/scheduledEmails/scheduledqa01/#configuration-tab

**Comment by Uafinder** [comment]
About members in dynagroup (first issue) - it's ok!

About scheduled emails
I have email scheduled to a group which contains one user, and dynagroup with 633 users
As a result system fires 25! (emails) to a single user (which is alone in his group), and no emails to dynagroup.
http://vlad-test.admin.kademi-prod.com/scheduledEmails/scheduledqa03/#configuration-tab

**Comment by bradmac** [comment]
@tuzzmaniandevil can you please look into the issue with scheduled emails

**Comment by Uafinder** [comment]
No emails was send at all, when dynamic groups are in list.
http://vlad-test12.admin.kademi-ci.co/scheduledEmails/scheduledqa1/#configuration-tab
![image](https://user-images.githubusercontent.com/1945230/31388532-139a8d38-add7-11e7-8048-f5406e6e792c.png)
![image](https://user-images.githubusercontent.com/1945230/31388544-1e100dc4-add7-11e7-889c-e9bf30abf6cf.png)

**Comment by tuzzmaniandevil** [comment]
Works absolutely fine for me
http://wesleytest.admin.kademi-ci.co/scheduledEmails/test-email/#history-tab

![screenshot-wesleytest admin kademi-ci co-2017-10-11-09-13-13-275](https://user-images.githubusercontent.com/3378330/31408645-bf9f3c80-ae65-11e7-8fd4-438aef3a180b.png)


![screenshot-wesleytest admin kademi-ci co-2017-10-11-09-15-10-816](https://user-images.githubusercontent.com/3378330/31408654-c5adaa4e-ae65-11e7-82ea-a254e37c56fd.png)


![screenshot-wesleytest admin kademi-ci co-2017-10-11-09-22-02-223](https://user-images.githubusercontent.com/3378330/31408667-d56c6164-ae65-11e7-8ec5-ec7a290eac53.png)

**Comment by bradmac** [comment]
@tuzzmaniandevil can you please confirm if you can see @Uafinder s email work?
http://vlad-test12.admin.kademi-ci.co/scheduledEmails/scheduledqa1/#configuration-tab

**Comment by Uafinder** [comment]
i'm closing this issue, it seems to be fine
