### ISSUE TITLE
Group Goal

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3842]
- I created a rego journey as below
- The first group goal I left without any group selection
- The result was it created 2x leads and fired off the email to the email that registered twice

Does not seem correct...

![image](https://user-images.githubusercontent.com/2201340/30245772-911c579a-9627-11e7-8eb1-f4451a76be00.png)

**Comment by bradmac** [comment]
I've changed GroupGoal so it now only matched if a group is configured. So the journey above wouldnt do anything until a group is selected, and then it will only create a single journey when added to the selected group.
