### ISSUE TITLE
Keditor - text padding

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3843]
@ducdhm why do we add left and right padding to text?  This means every time you add text to a container, you have to remove the padding if you want your text flush with the container edge.

![image](https://user-images.githubusercontent.com/2201340/30245798-6218fcfe-9628-11e7-8948-6ce08911ee1f.png)

**Comment by ducdhm** [comment]
I removed padding-left and padding-right in `text` and `photo` components in EDM Editor

**Comment by Uafinder** [comment]
Great!
