### ISSUE TITLE
Shopping cart goal

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3844]
The shopping cart goal which is also used for rewards store checkouts is only available if the eCommerce APP is switched on.

Was this intended?

![image](https://user-images.githubusercontent.com/2201340/30245902-cf1acb2c-962b-11e7-8c76-525d6ac14cdf.png)

**Comment by bradmac** [comment]
@tuzzmaniandevil please create a corresponding goal in reward store app

Note they both are triggered by the same event, and can probably use the same underlying Goal java class

**Comment by tuzzmaniandevil** [comment]
Will now work with both reward and ecommerce apps
