### ISSUE TITLE
Journey alert causing checkout error

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3845]
This journey http://staymetrics.admin.kademi.us/funnels/redeemer-journey/#journeyBuilder-tab

Adding the 'activate alert' node causes a checkout error so I cannot checkout from the reward store.

![image](https://user-images.githubusercontent.com/2201340/30246078-974db25c-9632-11e7-92dc-e1be09dd8080.png)

This is the alert http://staymetrics.admin.kademi.us/websites/stay-metics/version1/alert-14769609#details-tab

**Comment by mkhoudary** [comment]
@gonzalon this alert node still uses alert physical ids, please change it to seek for alerts by id first and if not found to seek by the newly created alert name.

**Comment by bradmac** [comment]
@gonzalon please update the alert node settings to display a list of alerts in a select box

![image](https://user-images.githubusercontent.com/826458/30252877-383a701a-96ce-11e7-803c-0df7805acf16.png)

**Comment by bradmac** [comment]
This should persist the alert name into the journey, but ensure the Alert node continues to work correctly with either name or ID persisted

**Comment by AlaaKhalaf94** [comment]
passed
