### ISSUE TITLE
Timer goal not firing

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3847]
See this journey http://staymetrics.admin.kademi.us/funnels/registration-journey/#journeyBuilder-tab

Started from this rego page http://stay-metics.kademi.us/participants/signup

The timer goal which is set for 1 minute is not firing, also note the connector to the next node is not aligned to the node outcome - could this be part of the issue?

![image](https://user-images.githubusercontent.com/2201340/30246597-6fb8ea12-9642-11e7-963a-4e39ec5c7529.png)

![image](https://user-images.githubusercontent.com/2201340/30246619-af9392ea-9642-11e7-8788-cec6e77424dc.png)

**Comment by mkhoudary** [comment]
@paddyow you are using the past-time connector not the timeout connector, you shall use the timeout connector when you are not using relative time.. because with non-relative times the journey simply timesout and finds no exit node

**Comment by bradmac** [comment]
Yeah, I've checked the json and confirmed its setup to use the **past** timeout outcome.

```
            "timerGoal": {
                "nodeId": "timerGoal-550b85",
                "title": "Wait 2 days",
                "x": 600,
                "y": 220,
                "timeoutMultiples": "1",
                "timeoutUnits": "m",
                "timeoutNode": "",
                "pastTimeNode": "emailAction-11a8da",
                "timeoutRelativeDateMVEL": null,
                "stageName": null,
                "cost": null,
                "probability": null,
                "source": null,
                "description": "Timer",
                "timoutTime": null,
                "name": "timerGoal-550b85",
                "timerTime": null
            }
```

**Comment by bradmac** [comment]
@paddyow just link the yellow "timeout" output to the next node

![image](https://user-images.githubusercontent.com/826458/30252827-4b896ca8-96cd-11e7-8680-eecc7dd42619.png)
