### ISSUE TITLE
Download backup button does not work

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#3848]
When I try to download backup from Zoetis site:
https://zoetis.admin.kademi.com.au/backup/

Nothing happens.. checking JS/Network does not show any activity or error as well.

**Comment by bradmac** [comment]
@tuzzmaniandevil if this is a performance issue, we might need to consider whether the backup runs in the background, and produces a download link.

This might be good to have a history of backups (and restores?) anyway

**Comment by tuzzmaniandevil** [comment]
We are going to refactor the backup to run in the background and to create a zip file with individual json files for each app.
