### ISSUE TITLE
"Simulate the time" doesn't work well

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#3849]
When I try to make "Simulate the time" from here : http://admin.kademi-prod.com/maint/#utils-tab
and the period that I set up for more than a month
the target site become blank with me
this is a target site that I try with it : http://renewal.admin.kademi-prod.com

When I put : 40000 minutes and submit
and the date/time beacome : Oct 08 04:35:19 UTC 2017
the site work well with me

![capture1](https://user-images.githubusercontent.com/26510030/30248000-5865ebf4-9628-11e7-8146-e2664930493e.PNG)

When I put : 50000 minutes and submit
and the date/time beacome : Oct 15 03:19:53 UTC 2017
the site become blank with me

![capture2](https://user-images.githubusercontent.com/26510030/30248003-607f7ff8-9628-11e7-9b64-302602aaf998.PNG)

**Comment by bradmac** [comment]
@mkhoudary please check the logs to see what error is causing the site to be blank

**Comment by mkhoudary** [comment]
@bradmac it looks like when changing QA time a massive amount of time related operations happen.. like vaya journeys, automated emails, automated reports.
There is no certain error when refreshing appears, but locally the time operation works just fine without any problem.

**Comment by bradmac** [comment]
we'll support testing module renewals using a new feature

https://github.com/Kademi/kademi-dev/issues/3851
