### ISSUE TITLE
Module renewal keeps on firing emails

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#3850]
When module is renewed, it keeps on firing module renewed event every one hour until expired or renewed.

**Comment by mkhoudary** [comment]
Fixed

**Comment by mkhoudary** [comment]
@bradmac the query should not get any renewed modules from the beginning, but I've noticed that this condition is commented.. any clue why? ModuleStatus.java line 122

**Comment by bradmac** [comment]
Fixed
