### ISSUE TITLE
Reward store product links to 404 error page from product detail page

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3856]
User http://staymetrics.admin.kademi.us/manageUsers/14779388/#summary-tab

Go here http://stay-metics.kademi.us/stay-metics-store/171997/255899/256538/256545/257301/257103/elec/172277/255762/255774/14815881/

Click a product 
![image](https://user-images.githubusercontent.com/2201340/30257649-e150c1d6-96f6-11e7-9078-6832dd7d9d6d.png)

**Comment by ducdhm** [comment]
Fixed!
