### ISSUE TITLE
Backup and restore fields

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3857]
http://safetydemo.admin.kademi.us/backup/

admin URL, username and password should not be mandatory if uploading a file.

![image](https://user-images.githubusercontent.com/2201340/30260955-96fa88e4-970d-11e7-962c-e828ded1ccd1.png)

**Comment by bradmac** [comment]
should only be required when restoring across servers

And should initially be hidden, with a button like "Transfer content from a remote server"

**Comment by Uafinder** [comment]
Looks ok
