### ISSUE TITLE
Experiments

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3860]

**Comment by bradmac** [comment]
Manage experiment page:
![image](https://user-images.githubusercontent.com/826458/30308204-d3ff9444-97d7-11e7-8561-b4c826832720.png)

**Comment by bradmac** [comment]
Use in EDM editor:

![image](https://user-images.githubusercontent.com/826458/30308231-0d1d685a-97d8-11e7-967b-9a393f8ebe0f.png)

**Comment by bradmac** [comment]
Note that the experiment can be either

"test1" - select the experiment, but not variant, so this is the control option
"test1/b" - the test1 experiment, and the variant "b"

**Comment by bradmac** [comment]
@ducdhm please update the container settings to allow the user to select either the control option or a variant for an experiment.

Use the following service to get the list:
http://localhost:8080/experiments/?asJson

**Comment by ducdhm** [comment]
Done!

**Comment by bradmac** [comment]
Note that "conversion" in this context means clicking a link generated by an experiment panel
