### ISSUE TITLE
Group save button does not work

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3861]
http://staymetrics.admin.kademi.us/groups/participants/

Clicking save does not save.

**Comment by ducdhm** [comment]
Fixed!

**Comment by AlaaKhalaf94** [comment]
passed

**Comment by salehh93** [comment]
@bradmac 
but not work in this website 
http://mahle.admin.kademi.us/groups/Learners/
please check in US server not QA

**Comment by bradmac** [comment]
Yeah, the fix hasnt been deployed yet.

**Comment by bradmac** [comment]
Should be deployed today
