### ISSUE TITLE
Cannot manage the survey menu item

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3862]
http://stay-metics.kademi.us/ note it appears in the menu

Admin: http://staymetrics.admin.kademi.us/pages/stay-metics/version1/

Does not appear in menu builder.

![image](https://user-images.githubusercontent.com/2201340/30306787-a7e1b03c-97bd-11e7-8717-4ea0511c1398.png)

Need options to 
- change if visible in the menu
- only available to logged in users

**Comment by ducdhm** [comment]
Fixed!
