### ISSUE TITLE
Cannot add to cart

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3864]
This user http://staymetrics.admin.kademi.us/manageUsers/14901952/#summary-tab

Adding to cart gives this error 'Sorry, we could not add the item to your cart. That item is currently unavailable'

**Comment by bradmac** [comment]
was out of stock

**Comment by paddyow** [comment]
This user http://staymetrics.admin.kademi.us/manageUsers/14901952/#summary-tab

Cannot add any product to cart, have checked stock levels.

![image](https://user-images.githubusercontent.com/2201340/30314651-b0d698a2-97e4-11e7-89df-495f6e3e0c5e.png)

![image](https://user-images.githubusercontent.com/2201340/30314669-c0d0d538-97e4-11e7-96df-2f14fd84f7df.png)

**Comment by gonzalon** [comment]
There was a bug when the inventory location wasn't configured in the website. 
Now it should work for both (org and website) settings.

**Comment by gonzalon** [comment]
To test take in mind to test setting the reward store at the organisation level, and another test would be at the website level.

![image](https://user-images.githubusercontent.com/2773216/30351400-4624bd3c-986f-11e7-9c2d-13987a25965e.png)

**Comment by Uafinder** [comment]
Yeah, it works.
Please note that website setting have an advantage after global app setting.
E.g. if global contains warehouse-1 parameter, and warehouse-2 is setup in website, website settings will be active. But if global contains warehouse-1 parameter and checkbox Inventory control checked, and website setting contains warehouse-2 parameter and checkbox Inventory control unchecked - Inventory control will not be work at all.
If this logics are correct, issue could be closed.

**Comment by bradmac** [comment]
Thats ok, later we can improve management. In reality, users will only control settings at org level
