### ISSUE TITLE
KEditor initialisation bug

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3866]
I've seen this issue a few times before. The content in the editor doesnt display sometimes when doing a refresh, but it does display when loading the page withouth a refresh (ie clicking enter on address bar)

https://www.youtube.com/watch?v=zlAHa2v0voU&feature=em-upload_owner

**Comment by ducdhm** [comment]
Fixed!

**Comment by ducdhm** [comment]
Note: It happens only in Firefox

**Comment by Uafinder** [comment]
https://github.com/Kademi/kademi-dev/issues/3997

**Comment by Uafinder** [comment]
Still spot this issue, it appears on different pages
https://github.com/Kademi/kademi-dev/issues/3997

**Comment by bradmac** [comment]
Lets look at it again in the next milestone

**Comment by ducdhm** [comment]
This issue is ready fixed in other commit

**Comment by Uafinder** [comment]
closing this issue... will open a separate one if needed
