### ISSUE TITLE
Checkout form validation prevents user from re-submitting form

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3867]
http://staymetrics.admin.kademi.us/manageUsers/15049872/#summary-tab

Add product to cart
Complete form but fail to add a phone number
Submit form
Note validation that appears
Enter phone number
Note the submit button is greyed out and cannot be clicked on again
Refresh, compete form with phone number and submit - goes through ok

![image](https://user-images.githubusercontent.com/2201340/30361972-08598d92-989d-11e7-95b4-ff8231b697ba.png)

**Comment by ducdhm** [comment]
Fixed!
