### ISSUE TITLE
Registration bug / duplicate profiles

### ISSUE THREAD

**Issue by cynWard6** [Kademi/kademi-dev#387]
After contacting by email (using Contact us section), the user is not able to register his profile due to his email account is already registered.

**Comment by bradmac** [comment]
@skwidge can you please address this as a priority item?

**Comment by skwidge** [comment]
Done

**Comment by skwidge** [comment]
Not done. This is not the same as duplicate profiles being created - this is gap in functionality

**Comment by skwidge** [comment]
Profile.findByEmail(email) > Profile.find(email)
