### ISSUE TITLE
Searching for an Org does not show title to make selection

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3871]
http://staymetrics.admin.kademi.us/manageUsers/

Adding new user

1) Org ID shows (title should show)

![image](https://user-images.githubusercontent.com/2201340/30410717-34688c04-9950-11e7-96cd-49e353c68fc7.png)

http://staymetrics.admin.kademi.us/groupEmails/15106487/#recipients-tab

Sending email

1) Org ID shows (title should show)
2) ORG dropdown needs higher z index, appears behind exclude field

![image](https://user-images.githubusercontent.com/2201340/30410729-4494285e-9950-11e7-9bb5-e441fce77819.png)

![image](https://user-images.githubusercontent.com/2201340/30410770-792aeb16-9950-11e7-9595-624f180552b8.png)

**Comment by gonzalon** [comment]
@paddyow ups, that my bug! related to this 

https://github.com/Kademi/kademi-dev/issues/3823

**Comment by gonzalon** [comment]
Pushed the changes in https://github.com/Kademi/kademi-dev/issues/3823
Closing this one
