### ISSUE TITLE
The ability to do maintenance to leads

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#3872]
We need to be able to do maintenance work to leads in case a lead entered an inconsistent state, the ability shall contain but not be limited to:
1- The ability to select the current goal/node.
2- The ability to explicitly set the current timer date.
3- The ability to view the transition history of that lead.

**Comment by bradmac** [comment]
3. See LeadJourneyTransition

**Comment by gonzalon** [comment]
Changing the goal:

![image](https://user-images.githubusercontent.com/2773216/30461916-fd9ddc8a-9a15-11e7-9a84-4fd34eff1ddf.png)



Changing the time for the schedule:

![image](https://user-images.githubusercontent.com/2773216/30461928-26e9bb9a-9a16-11e7-92fb-9b62c516cf0a.png)

**Comment by gonzalon** [comment]
Timeline for the lead .. 

![image](https://user-images.githubusercontent.com/2773216/30464493-eac23ef2-9a25-11e7-88a9-48f29a0c035d.png)

**Comment by mkhoudary** [comment]
@AlaaKhalaf94 please test

**Comment by AlaaKhalaf94** [comment]
passed
