### ISSUE TITLE
Unable to turn off HINDA APP 

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3879]
http://dealerengagement.admin.kademi.us/manageApps/#installed-tab

Expect if it can be turned on, it should be possible to turn it off?

**Comment by bradmac** [comment]
The Hinda APP is not a core app, should be able to be turned on or off

**Comment by paddyow** [comment]
Also note that any new sub account created is by default installing the HINDA App.  The HINDA App should not be switched on when a new account is created.

**Comment by AlaaKhalaf94** [comment]
passed
