### ISSUE TITLE
Manage Products: Can't filter by supplier

### ISSUE THREAD

**Issue by gonzalon** [Kademi/kademi-dev#3880]
The dropdown for filtering by supplier isnt working correctly.

**Comment by gonzalon** [comment]
Fixed need to deploy

**Comment by gonzalon** [comment]
@AlaaKhalaf94 thats the org you are in :) 

Changed the name:
![image](https://user-images.githubusercontent.com/2773216/30672403-4a684718-9ec0-11e7-96cb-975c55087cf9.png)

Dropdown:
![image](https://user-images.githubusercontent.com/2773216/30672413-55e32662-9ec0-11e7-948e-f146844f4939.png)

**Comment by Uafinder** [comment]
Looks ok at the moment
