### ISSUE TITLE
Keditor bug uploading 2nd image fails

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3881]
http://consumer-sales-app.admin.kademi.us/pages/sales-demo-1/version1/

Watch the video below.  Seems after adding a BG image, then a 2nd image in a container, the 2nd image does not update until the page is saved and refreshed.

[Ice Video 20170918-142141-1.zip](https://github.com/Kademi/kademi-dev/files/1309683/Ice.Video.20170918-142141-1.zip)

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
Yup, it looks ok!
