### ISSUE TITLE
Rename a website should not allow spaces in its name

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#3883]
Renaming a website allows the user to include spaces which breaks the URL.  Validate no spaces are included.

![image](https://user-images.githubusercontent.com/2201340/30530722-8aa6d9d8-9c8c-11e7-9eb1-c9627fa81c81.png)

**Comment by AlaaKhalaf94** [comment]
I can rename a website with space from Repositories page : http://testaccount010.admin.kademi-ci.co/manageRepos/

![untitled01](https://user-images.githubusercontent.com/26510030/39112337-db9883b0-46e0-11e8-8c9d-58d013d1aa35.png)

**Comment by anhnt** [comment]
Done

**Comment by AlaaKhalaf94** [comment]
passed
