### ISSUE TITLE
Default sorting attribute for users page

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#3886]
What is the default sorting attribute for users page. I don't understand :(
Probably it should be name, email or something else...
![image](https://user-images.githubusercontent.com/1945230/30532535-7b706512-9c5d-11e7-8193-809e0b77fb95.png)

**Comment by bradmac** [comment]
it should be sorted by relevance, although when there is no search term there is no relevance, so in that case should be name then email

**Comment by Uafinder** [comment]
Ok, works properly...
