### ISSUE TITLE
Users import - Previous button works as next button 

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#3887]
![image](https://user-images.githubusercontent.com/1945230/30534181-adca147e-9c65-11e7-9683-053caad2656b.png)
Prev button works similar to next button

**Comment by tuzzmaniandevil** [comment]
@Uafinder This has already been done. Make sure to clear your cache as it's a Javascript change

**Comment by bradmac** [comment]
hey guys, notice this issue is in I7 which is not the current milestone

**Comment by Uafinder** [comment]
@tuzzmaniandevil Nope, it's still there, please notice that that's a common uploader bug, not only users import.
http://vlad-test10.admin.kademi-ci.co/tableUploaders/usersUploader

**Comment by tuzzmaniandevil** [comment]
Ahhh right! Got it now :-)

**Comment by Uafinder** [comment]
yeah, great :)
