### ISSUE TITLE
Popup comments in CKEditor

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#3888]
Please add the possibility to create popup comments on specific text using CKEditor:

![image](https://user-images.githubusercontent.com/3704174/30534554-5f28546e-9c67-11e7-8a1b-5d947bafdae3.png)

**Comment by mkhoudary** [comment]
https://github.com/Kademi/client-gilpin-travelworld/issues/8

**Comment by anhnt** [comment]
should use bootstrap popover

**Comment by bradmac** [comment]
we already have a modal plugin for ckeditor
