### ISSUE TITLE
Bulk users removing

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#3889]
When you do a bulk user deletion, after you push ok in the popup window, users deleted, but to show changes page should be refreshed.
 
![image](https://user-images.githubusercontent.com/1945230/30534918-eb6d930c-9c68-11e7-86ad-4b1416f376cf.png)

**Comment by bradmac** [comment]
Probably just needs a reloadFragment

**Comment by gonzalon** [comment]
Depends on: https://github.com/Kademi/kademi-dev/issues/3902

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
Nope, it's still there :(
tested here:
http://vlad-test.admin.kademi-prod.com/manageUsers

**Comment by ducdhm** [comment]
@Uafinder It's working normally with me. Can you check with incognitor tab or cache your browser cache?

**Comment by bradmac** [comment]
I tested now on the link above and initially saw the problem. But then i hard refreshed and tried again and it worked correctly.

**Comment by Uafinder** [comment]
Working at the moment
