### ISSUE TITLE
Support sending comments on a topic to users

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#3890]
In forums app, we need the user to be able to subscribe to receive others comments about some topic on email, user should submit this to topic itself or when they comment.

**Comment by mkhoudary** [comment]
https://github.com/Kademi/client-gilpin-travelworld/issues/11

**Comment by bradmac** [comment]
@tuzzmaniandevil lets have a chat. I think our notifications support should handle this, but needs checking

**Comment by tuzzmaniandevil** [comment]
Done here: https://github.com/Kademi/kademi-dev/issues/3963
