### ISSUE TITLE
Enabled and disabled users switch

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#3893]
"Enabled users" shows enabled and disabled users both 
![image](https://user-images.githubusercontent.com/1945230/30538813-61fe4c8c-9c78-11e7-85ed-b020ed02179c.png)

"Disabled users" shows already deleted users
![image](https://user-images.githubusercontent.com/1945230/30538843-780a23f2-9c78-11e7-8d5e-09bfb7cbb9fe.png)

Is it by design?

**Comment by bradmac** [comment]
@Uafinder can you please provide a link to that account so we can investigate why thats happening?

**Comment by Uafinder** [comment]
http://vlad-test.admin.kademi-prod.com

**Comment by bradmac** [comment]
I've checked and it currently appears correct:
![image](https://user-images.githubusercontent.com/826458/30565608-1072cd16-9d1d-11e7-98fe-3fb156299ae1.png)

![image](https://user-images.githubusercontent.com/826458/30565623-22c97c94-9d1d-11e7-8649-eeba8f3d730b.png)

**Comment by Uafinder** [comment]
https://drive.google.com/open?id=0B9V2ZH-h_cR2ZVlTYU1DRjR4MWc

I've created a video... please take a look... cache cleared, diff browsers
user: adminqa@mailinator.com
password: Pa$$w0rd

**Comment by Uafinder** [comment]
Looks like some indexing trouble...
I've disable user, it doesn't appears in disabled users list, i've run re-index and disabled user successfully appers in disabled users list and vice versa

**Comment by bradmac** [comment]
ok, thanks for clarifying

**Comment by Uafinder** [comment]
Yeap, looks great at the moment
