### ISSUE TITLE
appear velocity code on search page

### ISSUE THREAD

**Issue by salehh93** [Kademi/kademi-dev#3895]
appear velocity code on search page
if I search on "Contact"
I think the problem from search-lib 
![image](https://user-images.githubusercontent.com/23012214/30541121-ad3d58aa-9c82-11e7-9a87-e0c5d5d042e7.png)

http://oceanyouth.kademi.com.au/contentSearch?q=Contact

**Comment by bradmac** [comment]
Note that resources in theme should be excluded in content search results.

**Comment by bradmac** [comment]
also note that this is not velocity code. Its just js in the component file

**Comment by gonzalon** [comment]
Needs to be deployed, please test it after after reindexing
http://admin.oceanyouth.kademi.com.au/websites/oceanyouth/version1/manageSearch/
