### ISSUE TITLE
Account history doesn't show removing membership

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#3897]
![image](https://user-images.githubusercontent.com/1945230/30542695-018a5dd0-9c89-11e7-8f35-6c7d0ca032cf.png)
It's showing that group membership is added, but doesn't show information that it has been removed.

**Comment by bradmac** [comment]
- add a column to SignupLog for deleted date
- create a deleted signuplog when a group memmbership is removed
- display added and removed signuplogs on timeline

**Comment by gonzalon** [comment]
![image](https://user-images.githubusercontent.com/2773216/33971152-eae22904-e0db-11e7-99c1-615af513c95e.png)

**Comment by Uafinder** [comment]
Yup it works!
