### ISSUE TITLE
Organisations import options bug

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#3898]
![image](https://user-images.githubusercontent.com/1945230/30545579-b47be63a-9c92-11e7-8bc4-d70afa6f2cdb.png)

1. orgid is not in alphabet order
2. what is internalorgid? is this not a double of orgid?

**Comment by bradmac** [comment]
"OrgID" - this is the user definable unique identifier for an organisation. Eg "STORE-123"
"Internal org ID" - this is Kademi's unique identifier for an organisation. Eg 3321334

**Comment by bradmac** [comment]
But yes, fields should be in alphabetical order.

**Comment by Uafinder** [comment]
Work ok!
