### ISSUE TITLE
Reload fragment don't find ids

### ISSUE THREAD

**Issue by gonzalon** [Kademi/kademi-dev#3902]
I was using:

`                $('#manageUsersContent').reloadFragment();
`

The div is in the webpage, and has the ID attr.

I'm seeing in the console:

`[jquery.reloadFragment] IDs:`

I think it might be because of the each, as the $(this) for my case is not an array.

**Comment by ducdhm** [comment]
@gonzalon, I have checked with
```
$('#manageUsersContent').length // is 0
```

Seems like this element doesn't exist. Can you double-check again?

**Comment by bradmac** [comment]
Hey @ducdhm can you please look into this? Its just the manage users page

**Comment by gonzalon** [comment]
@ducdhm Sorry, the example was something I was changing isn't pushed.
That's why I said that the div was on the page, and had the attr id.
