### ISSUE TITLE
A bug in the style container settings in kediter

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#3905]
In this account , in edit home page : http://categorycont.admin.kademi-prod.com/pages/categorycont/version1/

![capture1](https://user-images.githubusercontent.com/26510030/30584737-5486e3e6-9d33-11e7-9bea-47bea7e065d2.PNG)

**Comment by ducdhm** [comment]
Fixed!

**Comment by AlaaKhalaf94** [comment]
passed
