### ISSUE TITLE
Import users mechanism works slow

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#3906]
File which contains 2000 lines processing approx 8 minutes. It's mostly new accounts.

[import_users.xlsx](https://github.com/Kademi/kademi-dev/files/1313937/import_users.xlsx)
Interesting observation... when uploader starts he process 40-50 lines per hop (per 2 seconds), in the end he process 5-6 lines per hop (per 2 seconds)

**Comment by bradmac** [comment]
I've put in some performance optimisations which should increase the speed generally, and also prevent the decrease in speed as the uploader progresses

**Comment by Uafinder** [comment]
It works much faster... 2000 lines file processed in 4 minutes without decreasing speed as the uploader progresses...

**Comment by bradmac** [comment]
The qa server is pretty slow so I think will be faster in prod. All good.
