### ISSUE TITLE
Plain emails testing results

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#3908]
I've test Send Emails mechanism with positive scenario, some content was added to message body, but nothing serious.
This email tasks were executed...
![image](https://user-images.githubusercontent.com/1945230/30591827-0c805784-9d4d-11e7-9a07-64ba857ba2f7.png)
http://vlad-test.admin.kademi-prod.com/groupEmails/
So, results:
50 emails - 27 sesconds
300 emails - 105 seconds
1000 emails - 330 seconds (5 minutes 30 seconds)

Troubles:
1. Can't manage email sending queue... i've a message which falls into "retrying" state and has no possibility to exclude it (or delete it) to complete email message task.
2. Looks like "Opened" information doesn't appears. I've tried mailinator accounts and real gmail account.
3. There is no possibility to stop task... it's appearing in the running state forever.
4. Would be great to add links to Retrying, Failed emails to review those emails
![image](https://user-images.githubusercontent.com/1945230/30591767-cf6547e2-9d4c-11e7-9b94-44d87815b83a.png)

**Comment by bradmac** [comment]
"4. Would be great to add links to Retrying, Failed emails to review those emails" - moved to own issue - https://github.com/Kademi/kademi-dev/issues/3925

**Comment by bradmac** [comment]
"Can't manage email sending queue... i've a message which falls into "retrying" state and has no possibility to exclude it (or delete it) to complete email message task."

That is expected behaviour.

**Comment by bradmac** [comment]
"There is no possibility to stop task... it's appearing in the running state forever."

Did you press cancel? If so, can you please link me to an example job which you attempted to cancel?

**Comment by bradmac** [comment]
"4. Would be great to add links to Retrying, Failed emails to review those emails"

That has been done in a seperate issue

**Comment by bradmac** [comment]
So @Uafinder please review comments above. Looks like only the canceling thing that might be a problem, but just need to check on new server.

**Comment by bradmac** [comment]
Also, 1000 emails in 5 mins isnt great, but i think its ok. Will be faster on prod servers.

**Comment by Uafinder** [comment]
It's ok at the moment.
About sending performance - it should be tested on prod by using production environment.
