### ISSUE TITLE
Lead importer doesn't create lead properly

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#3909]
When leads are imported and created they are added as regular static data, leads should be created using the create method in the FunnelManager not as a regular DB record, so when it is created it is subject to transitioning.

**Comment by mkhoudary** [comment]
@bradmac this solution starts the lead correctly, but neither this solution nor the old code manages importing ended leads or cancelled leads.. 

I am assigning to you for peer review.

**Comment by bradmac** [comment]
Hi @mkhoudary looks ok to me. I think its ok to only support importing active leads at this point. A future enhancement will be to support lead state in the importer.

**Comment by AlaaKhalaf94** [comment]
When I try to import new leads , "Closed Date" Column isn't imported
I test here : http://alaa-test7.admin.kademi-ci.co/funnels/journey1/version1/#lead-tab

This is excel file : [import-leads.zip](https://github.com/Kademi/kademi-dev/files/1378922/import-leads.zip)

**Comment by bradmac** [comment]
@gonzalon please ensure the closed date field gets set

Note that if a lead is "closed" that means its not an active lead

**Comment by gonzalon** [comment]
@bradmac 
Just tested with the file and the reason the date is not being save is the format:
> 15/10/2017  10:55:00 PM
I tried again with 12/10/2017 22:55 and worked fine
Should we support this?

**Comment by bradmac** [comment]
As discussed, please ensure the user is informed of any parse errors. And we should also handle this date format.

**Comment by gonzalon** [comment]
- Added validation for the date, it's going to show an error message to the user if the format is not correct.
- Also added the option for the user to select the 12hs format with AM/PM.

Please, take in mind that the importer it's going to use the chosen format  or fallback to the default one, so it could work with two different formats but ideally we should use only one date format in the sheets.

**Comment by AlaaKhalaf94** [comment]
passed
