### ISSUE TITLE
Subscription payment: Display credit amount

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3916]
I selected and paid for a plan, and then upgraded to a higher plan immediately.

This should have resulted in me having a credit, but i cant see that credit anywhere:

![image](https://user-images.githubusercontent.com/826458/30619170-1cdbb970-9df2-11e7-9426-842d5e9d6c83.png)

Please ensure that any current credit is displayed on this page

**Comment by gonzalon** [comment]
https://github.com/Kademi/kademi-dev/commit/aa5a71206eb9ba478a8724127150753b54f8152a
