### ISSUE TITLE
Contact form component should allow selection of opt-in groups

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3917]
I have a form like this:
![image](https://user-images.githubusercontent.com/826458/30621824-87f77e6a-9e01-11e7-8c4d-1005bd6ccd25.png)

I would like users submitting this form to be added to a configured group (eg "Newsletter"). So please add settings to allow page authors to chose which groups to add users to.

Also, the page author might want users to have groups which they can choose to be added to as optins. These groups should be shown with tick boxes.

**Comment by anhnt** [comment]
Component settings:
![image](https://user-images.githubusercontent.com/735555/32769811-dc6245ba-c94f-11e7-9554-a99b5a1fff17.png)

Group settings
![image](https://user-images.githubusercontent.com/735555/32769823-edf9652e-c94f-11e7-9877-2f1c19cb1e8c.png)

Contact us settings:
![image](https://user-images.githubusercontent.com/735555/32769847-0601c7c4-c950-11e7-85fb-f7ae023b908d.png)

**Comment by AlaaKhalaf94** [comment]
passed
