### ISSUE TITLE
ckeditor toolbar is not appearing when editing content in a calendar event page

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3918]
![image](https://user-images.githubusercontent.com/826458/30622381-6c3fb22e-9e05-11e7-8f3d-92d49aaffc17.png)

Event page is here
http://youmum.admin.kademi.com.au/Calendars/youmum-webinars/webinar-with-our-breast-feeding-expoert#details-tab

**Comment by bradmac** [comment]
Found it! But its in a messed up location

![image](https://user-images.githubusercontent.com/826458/30622479-028e4c7c-9e06-11e7-9051-9e004753e38c.png)

**Comment by ducdhm** [comment]
Fixed!

`initFullscreenEditor(target, previewUrl)` method is available for admin at the moment. I'll convert it to plugin soon.

**Comment by ducdhm** [comment]
New UI:
![newui](https://user-images.githubusercontent.com/1289631/30678234-07c35f88-9ebb-11e7-844d-2c48122b9799.png)

**Comment by ducdhm** [comment]
Modal:
![newui2](https://user-images.githubusercontent.com/1289631/30678236-0dc81374-9ebb-11e7-982f-a97ca76090e5.png)
