### ISSUE TITLE
Incorrect number of profiles on the dashboard

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#3919]
![image](https://user-images.githubusercontent.com/1945230/30630665-396af130-9dea-11e7-8879-c8c02bfd7405.png)
![image](https://user-images.githubusercontent.com/1945230/30630719-69fae530-9dea-11e7-96fb-940972fd282c.png)
Looks like profiles tile shows memberships instead of profiles.

**Comment by bradmac** [comment]
Now used the same source as the manage users page, so should be consistent

**Comment by Uafinder** [comment]
Yup, works fine
