### ISSUE TITLE
Paginator on the modules activity tab links to the main tab

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#3922]
![image](https://user-images.githubusercontent.com/1945230/30641027-3057f95c-9e0e-11e7-96b2-c31f57457784.png)
![image](https://user-images.githubusercontent.com/1945230/30641042-4391e460-9e0e-11e7-88dd-b8b72a26f988.png)
It causes a problem when you paging a list of module activities...

**Comment by gonzalon** [comment]
Fixed.

**Comment by Uafinder** [comment]
Yup, looks better on QA
