### ISSUE TITLE
Unknown host names should not resolve to admin console

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3923]
Currently, if a user opens a page for any unknown domain on Kademi we display the login page for the root org admin.

Eg - https://this-doesnt-exist.admin.kademi-prod.com/
![image](https://user-images.githubusercontent.com/826458/30667403-89c517d4-9eab-11e7-8a88-4b1e2d1894e5.png)

This can be very confusing to users who have got the wrong address.

Note that current process is convenient for development, and we should preserve the current behaviour for when there is no host, ie just an IP address or the special "localhost" host name

**Comment by bradmac** [comment]
Now displays this:

![image](https://user-images.githubusercontent.com/826458/30671006-ed2639ea-9eb8-11e7-93f7-b32b44c96e86.png)

**Comment by Uafinder** [comment]
Looks ok!
