### ISSUE TITLE
More filtering options for email history page

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3925]
update the email history page to allow filtering by
- email job (eg the group email or automation)
- status (eg failed, delivered, retrying)

![image](https://user-images.githubusercontent.com/826458/30673847-242817d6-9eca-11e7-8206-920f37472a37.png)

Then please update the email status page to link to the email history page with the request appropriate parameters
https://user-images.githubusercontent.com/1945230/30591767-cf6547e2-9d4c-11e7-9b94-44d87815b83a.png

Related - https://github.com/Kademi/kademi-dev/issues/3908

**Comment by gonzalon** [comment]
Filters ... 
![image](https://user-images.githubusercontent.com/2773216/30884870-be906948-a36d-11e7-96bd-da34796135c3.png)

Links...
![image](https://user-images.githubusercontent.com/2773216/30884901-d855722e-a36d-11e7-85d3-4096facb264d.png)


@Uafinder those links are ok?

**Comment by Uafinder** [comment]
Links are good.
Question, how it can be opened and failed at the same time?
![image](https://user-images.githubusercontent.com/1945230/30969217-6b4eab52-a46a-11e7-874c-bc7b9b03dc84.png)

**Comment by bradmac** [comment]
@Uafinder please provide a link to your site so we can investigate

**Comment by Uafinder** [comment]
http://vlad-test.admin.kademi-prod.com/emails/?q=&status=o&job=

**Comment by bradmac** [comment]
"Question, how it can be opened and failed at the same time?" - I've confirmed the email is marked as read. This could be because the image tracker has been loaded by viewing the email in the admin.

**Comment by Uafinder** [comment]
yeap, works fine!
