### ISSUE TITLE
Subscription page enhancements

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3927]
- please order the plan table by cost
- and display the product details in a new column
- change the layout so that the "manage sub" and "due payments" panels are side by side, in 2:1 col layout
- add expiry date to the current plan panel
- do not put "There is no due payment.." in a blue panel, because that makes it look like a button. Just plane text is fine
- please format transaction history dates as short date/time
![image](https://user-images.githubusercontent.com/826458/30677441-d33012b4-9edf-11e7-8a1e-98808606ad52.png)

**Comment by bradmac** [comment]
Getting an exception when clicking through from a trial plan:
```
21:00:14 Caused by: java.lang.NullPointerException
21:00:14 	at java.math.BigDecimal.compareTo(BigDecimal.java:2625)
21:00:14 	at com.fuselms.apps.subscription.ManageSubscriptionPage.lambda$getProducts$5(ManageSubscriptionPage.java:365)
21:00:14 	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
21:00:14 	at java.util.TimSort.sort(TimSort.java:220)
21:00:14 	at java.util.Arrays.sort(Arrays.java:1512)
21:00:14 	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:348)
21:00:14 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
21:00:14 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
21:00:14 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
21:00:14 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
21:00:14 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
21:00:14 	at com.fuselms.apps.subscription.ManageSubscriptionPage.getProducts(ManageSubscriptionPage.java:365)
```

**Comment by bradmac** [comment]
Added temp hack by setting Trial product to zero cost

**Comment by bradmac** [comment]
The table has a new column, but its just repeating the title. Should be brief:
![image](https://user-images.githubusercontent.com/826458/30718962-ea1902ec-9f75-11e7-8d50-5db287386ae3.png)

**Comment by bradmac** [comment]
"change the layout so that the "manage sub" and "due payments" panels are side by side, in 2:1 col layout" - The layout is currently 1:1, please change to 2:1 to give plan content more room

**Comment by gonzalon** [comment]
Updated
