### ISSUE TITLE
Subcriptions: payment process

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3928]
Currently, when i click "Change plan" the "payment details" panel appears, but its not obvious to the user that this is now visible.

![image](https://user-images.githubusercontent.com/826458/30676860-6e739d62-9edc-11e7-9417-9f49bb10c0b7.png)

The best solution is probably to display the payment form in a modal (large)

**Comment by gonzalon** [comment]
https://github.com/Kademi/kademi-dev/commit/f78e3c58a70f91950903675c42dc32f7178e76af

**Comment by bradmac** [comment]
"The best solution is probably to display the payment form in a modal (large)" 

There is a modal now, but its not large to it looks squished. Please change to a large modal.

![image](https://user-images.githubusercontent.com/826458/30719123-66e9fa1a-9f76-11e7-9919-4340a8786586.png)

**Comment by bradmac** [comment]
Added .modal-lg

**Comment by bradmac** [comment]
Getting an error on payment:

![image](https://user-images.githubusercontent.com/826458/30719620-5053e8d6-9f78-11e7-8f01-327747dd5fdd.png)


```
org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
21:25:33 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
21:25:33 	at java.lang.Thread.run(Thread.java:748)
21:25:33 Caused by: java.lang.RuntimeException: EWay app is not configured. eWayApiIKey has not been set
21:25:33 	at com.fuselms.apps.eway.EwayService.getCreds(EwayService.java:532)
21:25:33 	at com.fuselms.apps.eway.EwayService.purchase(EwayService.java:397)
21:25:33 	at com.fuselms.apps.subscription.ManageSubscriptionPage.makePayment(ManageSubscriptionPage.java:191)
21:25:33 	at io.milton.cloud.util.SessionManagerUtils.apply(SessionManagerUtils.java:209)
21:25:33 	at io.milton.cloud.util.SessionManagerUtils.processFormCommandInTransaction(SessionManagerUtils.java:176)
```
