### ISSUE TITLE
Subscriptions: Payment panel enhancements

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3929]
- on the payment panel, do not display the recurring frequency input
- change "card name" label to "Card holder name"
- add a progress notification that the payment is processing immediately when the user presses submit

On payment confirmation:
![image](https://user-images.githubusercontent.com/826458/30677020-638aad40-9edd-11e7-8216-8ed50cb4f6d5.png)

- add a tick icon to the confirmation message
- the return button should be horizontally centred, but not full width. Add a left arrow icon to indicate returning. Change text to "Return to your site"
- also add the same left arrow icon to the "Return to site" button at the top

**Comment by gonzalon** [comment]
Also added placeholders to the fields
