### ISSUE TITLE
Physical location for ORG bugs

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#3931]
1. Map is sitting on the Sydney by default
2. If you select any number in latitude, longitude it search University of Alabama
3. When you push save map reset to default location.
4. When you enter Address and Address 2, push search and it finds correct map location, however if you push save it resets map location to default.
5. When you access organisation details it doesn't search map location automatically, you should push search.
6. When you enter coordinates, save page, and them reopen it, map location search ok and automatically by coordinates.

**Comment by bradmac** [comment]
hey @Uafinder, when you search for a location, you need to select the location to set the coordinates, and then save. If you search and save without selecting a location, then no location is set.

I couldnt reproduce a problem in steps 2-3 above

**Comment by bradmac** [comment]
Agreed we should do something to avoid having an initial location appear. I think it would be good to just hide the map if lat/lng arent set, until the search button is pressed.

@ducdhm can you please update?

**Comment by ducdhm** [comment]
Done!

**Comment by Uafinder** [comment]
looks good!
