### ISSUE TITLE
New calendar component

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#3932]
http://travelworld.co.nz/more/school-holidays/

![image](https://user-images.githubusercontent.com/735555/30684926-50806c6c-9edd-11e7-9664-79475dfcd11f.png)

We should have options to show all months or some months
We also have color indicator for specific event. ie holidays in green, public holidays in red, etc

**Comment by anhnt** [comment]
https://github.com/Kademi/client-gilpin-travelworld/issues/18

**Comment by ducdhm** [comment]
New UI:
![multi-cal](https://user-images.githubusercontent.com/1289631/30730819-f23dd9fc-9f93-11e7-8095-d1dbbfac11a1.png)

**Comment by anhnt** [comment]
worked

**Comment by anhnt** [comment]
@ducdhm as discussed with brad we should:

> we should have different colours for the different types of events
>have 3 calendars, and events from both are loaded into the component

**Comment by bradmac** [comment]
Note that calendars have a colour property. So if we can load from the 3 calendars we should be able to use that property for the event color

**Comment by bradmac** [comment]
I'll make calendar colours configurable in the manage calendar screen

**Comment by bradmac** [comment]
New UI allowing simple text entry of colour:

![image](https://user-images.githubusercontent.com/826458/31060628-33dca32a-a773-11e7-897c-f77886aa1729.png)

**Comment by bradmac** [comment]
@ducdhm please update the component to use the configured colour to display events

**Comment by mkhoudary** [comment]
https://github.com/Kademi/client-gilpin-travelworld/issues/18

**Comment by anhnt** [comment]
Admin:

![image](https://user-images.githubusercontent.com/735555/31214584-04951902-a9d6-11e7-8a50-1a624d8d01ab.png)

Component:

![image](https://user-images.githubusercontent.com/735555/31214592-1172304c-a9d6-11e7-889b-249ea3426de5.png)

Settings:
![image](https://user-images.githubusercontent.com/735555/31214613-2d0c7f56-a9d6-11e7-8b06-06b65a07e28a.png)

**Comment by AlaaKhalaf94** [comment]
Hi @anhnt , I create 2 Calendars as shown here : http://alaa-test3.admin.kademi-ci.co/Calendars/
and I select colors

![capture1](https://user-images.githubusercontent.com/26510030/31226636-8ccbbf70-a9df-11e7-818d-e9228048fa06.PNG)

Then in page "Calendar color" here : http://alaa-test3.admin.kademi-ci.co/pages/alaa-test3/version1/
I add calendar component and I select the 2 calendars in settings

![capture2](https://user-images.githubusercontent.com/26510030/31226701-c201b294-a9df-11e7-8f7b-7a2d49aa9fa8.PNG)

But when I view the "Calendar color" page , I can't see the events in calender
Is there something missing in my test ? or there is something error ?

**Comment by anhnt** [comment]
http://version1.alaa-test3.kademi-ci.co/calendarscolor.html?miltonUserUrl=/users/anh&miltonUserUrlHash=db922db2-f0dc-49c5-9f78-ef0d7601ed96:n4ca8EdbxJapLyOyNioPBSdn3q4 worked for me 

![image](https://user-images.githubusercontent.com/735555/31263763-7d5b654a-aa8e-11e7-944b-b6ff0b4de7f1.png)

**Comment by AlaaKhalaf94** [comment]
passed
