### ISSUE TITLE
Dashboard and groups page difference (Dynamic groups)

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#3934]
![image](https://user-images.githubusercontent.com/1945230/30685812-d56fc4fa-9ebe-11e7-9111-7cee0b617e3b.png)
![image](https://user-images.githubusercontent.com/1945230/30685843-f125e08a-9ebe-11e7-99c5-9455d050a07e.png)
This is because of dynamic groups is absent on the groups count (second screenshot)

**Comment by bradmac** [comment]
The first shows the number of groups defined, while the second screen shows the number of groups associated with displayed profiles. I think its ok for dynamic groups not to be included in this

**Comment by Uafinder** [comment]
It's make sence, so probably leaving as is
