### ISSUE TITLE
Evaluate security enhanced velocity and mvel

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3938]
See projects here:
https://github.com/MohammedFuad97

**Comment by gonzalon** [comment]
MVEL:

Seems its working for the expression evaluation but not for the templates.
Seems that for the templates isnt using the PropertyAccessor.

For the cases where we use MVEL.eval methods it's working fine.
We should only add the implementation for the filter manager, something like:

```
                ParserContext ctx = new ParserContext();
                ctx.addProperty("mvel.filtersManager", "io.milton.cloud.server.repoapps.FiltersManager");
                Object result = MVEL.eval(template, localVars);
```

But for the cases we use templates isnt working: 

```
TemplateRuntime.eval(templ, localVars).toString();
```

Or how I tried addapting the code so it would use a provided ParserContext 

```
                ParserContext ctx = new ParserContext();
                ctx.addProperty("mvel.filtersManager", "io.milton.cloud.server.repoapps.FiltersManager");
                CompiledTemplate ct = TemplateCompiler.compileTemplate(templ, ctx);
                return TemplateRuntime.execute(ct, null, new MapVariableResolverFactory(localVars)).toString();
```

**Comment by bradmac** [comment]
hey @mkhoudary we really need to be able to build the velocity jar.

can you provide instructions?

**Comment by gonzalon** [comment]
MVEL Update:

After the update of MVEL is working fine for the templates as well:

Ex:
```
                ParserContext ctx = new ParserContext();
                ctx.addProperty("mvel.filtersManager", "io.milton.cloud.server.repoapps.FiltersManager");
                bodyHtml = TemplateRuntime.eval(template, localVars).toString();
```

**Comment by gonzalon** [comment]
VELOCITY:

The validation itself it's working fine:
For ex. in TextTemplater I added:
`        engine.addProperty("velocity.filtersmanager", "io.milton.cloud.server.mail.FiltersManager1");
`

I had some issues with the validation process.

Example ASTReference.java
`result` sometimes is null, and that breaks the whole process.

```
        if (rsvc.getFiltersManager() != null && !rsvc.getFiltersManager().exposeToScripts(result.getClass().getName())) {
            return null;
        }    
```

**Comment by gonzalon** [comment]
Null checks for Velocity
https://github.com/Kademi/velocity-engine/commit/aec1114c0595b18b0093cce978df70e3aa1b91c2

**Comment by gonzalon** [comment]
@bradmac what should we do about this now?

**Comment by bradmac** [comment]
Please build and deploy mvel/velocity with updated version numbers to our maven repo, and then integrate with kademi

**Comment by gonzalon** [comment]
@Uafinder did some changes to enforce security in the templates / expressions of Velocity and MVel.
Please take it in mind and look around if I broke something  :P

**Comment by anhnt** [comment]
Could not build Kademi local at the moment.
```
[ERROR] Failed to execute goal on project kademi-server: Could not resolve dependencies for project com.fuselms:kademi-server:jar:1190: Failed to collect depen
dencies at org.mvel:mvel2:jar:2.3.2: Failed to read artifact descriptor for org.mvel:mvel2:jar:2.3.2: Could not transfer artifact org.mvel:mvel2:pom:2.3.2 from
/to kademi-private (http://dl.bintray.com/kademi/Kademi): Not authorized , ReasonPhrase:Unauthorized. -> [Help 1]

**Comment by bradmac** [comment]
Mine ran ok
```
------------------------------------------------------------------------
Building kademi-server 1190
------------------------------------------------------------------------
Downloading: http://kademi.bintray.com/Kademi/org/mvel/mvel2/2.3.2/mvel2-2.3.2.pom
           
Downloaded: http://kademi.bintray.com/Kademi/org/mvel/mvel2/2.3.2/mvel2-2.3.2.pom (11 KB at 3.7 KB/sec)
```

**Comment by anhnt** [comment]
OK i can build now thanks
