### ISSUE TITLE
Support rule based container visibility

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3939]
This is needed for edge cases where we cant implement the visibility logic through group membership

**Comment by bradmac** [comment]
Done.

![image](https://user-images.githubusercontent.com/826458/30724736-1b7e1368-9f94-11e7-9278-bc41428738c8.png)

**Comment by bradmac** [comment]
Note that in this context "user" is a UserResource.

The map of variables passed to components for rendering is also available in the expression evaluation context. So that includes the variables set in SendEmailGoalActionBatchEmailCallback:

```
        public String beforeSend(Profile p, String template, Map templateVars, EmailItem emailItem) {
            templateVars.put("lead", lead);
            templateVars.put("funnel", funnel);
            templateVars.put("domain", C(CurrentRootFolderService.class).getPrimaryDomain() + C(Formatter.class).getPortString());

            RootFolder rf = (RootFolder) templateVars.get("organisation");

            if ( lead.getAssignedToProfile() != null ) {
                try {
                    templateVars.put("assignedTo", rf.findEntity(lead.getAssignedToProfile()));
```

**Comment by bradmac** [comment]
@mkhoudary please test with Vaya

**Comment by mkhoudary** [comment]
https://github.com/Kademi/client-vaya/issues/222

**Comment by mkhoudary** [comment]
@bradmac when I try to save the rules they are ignored and not applied to EDM HTML

**Comment by mkhoudary** [comment]
Tested on QA
