### ISSUE TITLE
Seo Support: Allow resources to provide SEO fields

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#3941]
These fields should be:
- description
- keywords
- canonical
- structuredData - application/ld+json - https://developers.google.com/search/docs/guides/intro-structured-data

It requires the portlet `header` to be included in the header part of the page.

Example using a custom controller:
```javascript
controllerMappings
    .websiteController()
    .enabled(true)
    .isPublic(true)
    .path('/helloWorld')
    .seoContent('genSeoContent')
    .defaultView(views.templateView('/helloworld.html'))
    .build();

function genSeoContent(page, seoBean) {
    var baseUrl = formatter.getBaseWebsiteUrl();
    
    seoBean
        .withDescription("This is a Hello World page")
        .withKeywords(["Hello", "World", "Awesomeness"])
        .withCanonical(baseUrl + '/helloWorld');
}
```

**Comment by Uafinder** [comment]
Hey, Wes!
Need a hand here, give me some advises for test this issue?

**Comment by bradmac** [comment]
I think we can just close this one, its really a dev focused thing

**Comment by bradmac** [comment]
Looks like this hasnt actually been hooked up into masterTemplate.

**Comment by bradmac** [comment]
OK, is integrated with seoHeaderl.html in content-lib

But only specific resources produce structrured content
