### ISSUE TITLE
Voucher creation minor bug

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#3944]
![image](https://user-images.githubusercontent.com/1945230/30732283-70bfb81e-9f7a-11e7-8706-f505650be1ec.png)
When you create a number of vouchers to see changes in total count you should refresh page.

**Comment by bradmac** [comment]
Yep. Please add a reloadFragment after vouchers creation to update totals

**Comment by Uafinder** [comment]
Also would be great to add those reload fragment after uploading vouchers CSV.

**Comment by Uafinder** [comment]
Yup!
