### ISSUE TITLE
Voucher ID template format validation

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#3945]
Would be great to add a validation to ID Template field which will check if it's correct.
Because if it's wrong there will be an error when create vouchers...
![image](https://user-images.githubusercontent.com/1945230/30732514-9ac7812c-9f7b-11e7-9f7b-aa9248e28e19.png)
![image](https://user-images.githubusercontent.com/1945230/30732524-a3f178f2-9f7b-11e7-8488-a7c63e574a8f.png)

**Comment by bradmac** [comment]
I think we can have
- a bootstrap text dropdown with a few example templates
- a "Test" button which will apply the template and show the output in a modal, and show an error if incorrect

**Comment by gonzalon** [comment]
Now we can test the templates, also its going to do the same validation on the save.

![image](https://user-images.githubusercontent.com/2773216/33972564-4a9cce24-e0e3-11e7-8995-fb61eae91796.png)

Valid:
![image](https://user-images.githubusercontent.com/2773216/33972570-54445528-e0e3-11e7-8a5b-1e4525a988fc.png)

Invalid:
![image](https://user-images.githubusercontent.com/2773216/33972580-5d415e5a-e0e3-11e7-8394-6bce7f345356.png)


What should we add as examples?

**Comment by Uafinder** [comment]
Works ok!
Examples would be great to have as much as you can (to have an example for syntax)
Now we have only two:
ABC-@{randomHex(3)} - ABC-4c1
MM-@{formatter.getYear(date)}-@{randomHex(3)} - MM-2015-724
