### ISSUE TITLE
Question about periodically page freeze (long loading)

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#3946]
![image](https://user-images.githubusercontent.com/1945230/30732671-5045b2e4-9f7c-11e7-955d-5ad73a0e659d.png)

Is it possible that there left some integration with zopim which may freeze page loading?

**Comment by bradmac** [comment]
I've seen that myself on occasion. It seems like there is an occasional problem with Zopim which affects our page loading. 

However, we are probably changing away from Zopim soon
