### ISSUE TITLE
Edit translation button 

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#3950]
It appears everywhere and it's drive me mad...
![image](https://user-images.githubusercontent.com/1945230/30739326-9148ad64-9f95-11e7-829d-ddccbe0ddade.png)
Upper menu cause this button to be hidden...
![image](https://user-images.githubusercontent.com/1945230/30739352-a8e2b398-9f95-11e7-9a59-b838fc8718b7.png)

**Comment by bradmac** [comment]
@ducdhm we need a way to turn it on or off. Is there an option for that yet?

**Comment by ducdhm** [comment]
@bradmac It's a part of KToolbar. Just need to disabled KToolbar

**Comment by ducdhm** [comment]
https://github.com/Kademi/kademi-dev/issues/3969

**Comment by Uafinder** [comment]
Thanks, i will disable it for a while
