### ISSUE TITLE
Contact creation bugs

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#3951]
1. New contact will not appears in list without refresh.
![image](https://user-images.githubusercontent.com/1945230/30739887-972dde6e-9f97-11e7-904e-60511d63b3d8.png)
2. Created contact falls into Leads group by default, not sure if it's correct.
3. Need to change font color to white, text is invisible.
![image](https://user-images.githubusercontent.com/1945230/30739958-d5cbede6-9f97-11e7-8695-db4477cff5f0.png)

**Comment by bradmac** [comment]
2: it should go into the group configured on the funnel

**Comment by anhnt** [comment]
> 2: it should go into the group configured on the funnel

@bradmac if we have more than 1 funnel and each funnel is configured to have separate leads group. So what it should do?

**Comment by Uafinder** [comment]
Yup, it's good
