### ISSUE TITLE
Groups sorting incorrect when dynamic groups in list

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#3952]
![image](https://user-images.githubusercontent.com/1945230/30740366-5ab3a1ec-9f99-11e7-9d61-dd6c07464ec4.png)
for example in applications settings

**Comment by bradmac** [comment]
Looks like its applying case-sensitive sorting. Would be good to change to case-insensitive

**Comment by Uafinder** [comment]
Yeap, works fine
