### ISSUE TITLE
Manage products page default filter

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#3955]
![image](https://user-images.githubusercontent.com/1945230/30742383-77ae8fc0-9fa1-11e7-900d-44e9e604ffb1.png)
When you open manage products page it shows all products, but filter is already setup to supplier org (current org i think), I think that there should be something "Not selected" or some sort...

**Comment by bradmac** [comment]
Yep, should initially be no supplier filter selected

**Comment by Uafinder** [comment]
Yeap, working great
