### ISSUE TITLE
products paginator

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#3957]
When you setup paginator to 5000, page selector disappears and there is no possibility to go back to smaller amount.
![image](https://user-images.githubusercontent.com/1945230/30745308-43e3c82e-9fae-11e7-92cd-941294670281.png)
![image](https://user-images.githubusercontent.com/1945230/30745330-53de2724-9fae-11e7-8951-647aec3b1666.png)

**Comment by bradmac** [comment]
I think this is fine.
