### ISSUE TITLE
Products default sorting incorrect

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#3958]
![image](https://user-images.githubusercontent.com/1945230/30745433-cced707a-9fae-11e7-9cc4-f13a7c6bc057.png)
Should be by code or by name
Also with categories page
![image](https://user-images.githubusercontent.com/1945230/30745637-9eb97aa4-9faf-11e7-8480-0f76e0d38e6b.png)

**Comment by bradmac** [comment]
I would expect the default sorting to be by title, thats what users would want. Is that happening now?

**Comment by Uafinder** [comment]
No, it isn't. I have products from product001 to product 1000, both screenshots captured from the first page. So it takes some weird criteria to sort products.

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/31441379-b2313554-ae9b-11e7-9940-b403d6a80641.png)

http://vlad-test13.admin.kademi-ci.co/products/

**Comment by bradmac** [comment]
Should use title as default sorting

**Comment by bradmac** [comment]
Closing, superceded by https://github.com/Kademi/kademi-dev/issues/4144
