### ISSUE TITLE
When enter SKUs details product details doesn't appears

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#3959]
![image](https://user-images.githubusercontent.com/1945230/30746485-9062046e-9fb2-11e7-81dc-6f5c31888301.png)
![image](https://user-images.githubusercontent.com/1945230/30746588-e369b472-9fb2-11e7-8b53-b711532653ef.png)
This bug appears when you're using search.

**Comment by Uafinder** [comment]
Looks like it appears when you're using search and product variants are in sight.

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/30798100-f16bfa6e-a1e0-11e7-903c-7638525bd79d.png)

**Comment by gonzalon** [comment]
I think this is not an issue anymore. Tried both cases explained here.

**Comment by Uafinder** [comment]
This bug appears when you're using search and then try to add some SKU code on searched product
Reproduced on fresh account
http://vladtest44c.admin.kademi-ci.co/skus/

**Comment by gonzalon** [comment]
Should be working now :)

**Comment by Uafinder** [comment]
yeah, looks ok
