### ISSUE TITLE
Enable adding and checking tags to organisation in automation

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#3961]
We need to have organisation tags being checked and added as part of the automation framework.

**Comment by mkhoudary** [comment]
https://github.com/Kademi/client-zoetis/issues/286

**Comment by bradmac** [comment]
Possibly consider using journeys instead of automations

**Comment by bradmac** [comment]
OK, i think the best way to do this is to use journeys as follows
- add a journey node to tag an organisation. The settings should allow an org type to be selected as the tag to apply, and also an org type to be selected. When executed it will attempt to locate an org associated with the current user of that type, and apply the tag to it.
- add dynamic fields to funnels. We can then create a dynamic field which returns the number of modules completed for the required module, by the user's organisation

**Comment by bradmac** [comment]
dynamic fields implemented - https://github.com/Kademi/kademi-dev/issues/3971

**Comment by bradmac** [comment]
@gonzalon please implement a new journey node which will add a tag (ie org type) to an organisation
- settings should allow selecting the org type to add, eg "certified store"
- settings should also allow selecting an org type which will be used to locate the organisation to update from among those a user is associated with. Eg "store"

**Comment by gonzalon** [comment]
Needs to be deployed

**Comment by bradmac** [comment]
Please see comments on commit
https://github.com/Kademi/kademi-platform/commit/6d496f3f34bbc6954d563b3feb95e0ffde451866

**Comment by AlaaKhalaf94** [comment]
passed
