### ISSUE TITLE
Fixes for manage SKU's page

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3964]
- error when deleting a SKU with inventory locations
- error when a SKU has associated product orders
- screen refresh is very slow when there are a large number of SKUs (eg 1000 or so)

**Comment by Uafinder** [comment]
Looks ok at the moment
Probably would be great to add some button to delete SKU, because clearing SKU code field is not obvious decision.

**Comment by bradmac** [comment]
Problem with that is you actually cant delete the row, because rows are always shown for all combinations of variants. So it would be weird for a user to delete a row, but the row is still there

**Comment by Uafinder** [comment]
So, we could call the button not Delete, but Clear (with tip Clear SKU details or some sort). It would be more obvious i think.

**Comment by bradmac** [comment]
OK, but we can do that in a later milestone

**Comment by bradmac** [comment]
Moved remaining task to new issue, closing.

**Comment by Uafinder** [comment]
Sure, no probs
