### ISSUE TITLE
Delete all points improvement

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#3968]
We will need delete progress like we did in reindex screen.
Also we need to disable delete all button if there's job which is in progress

**Comment by bradmac** [comment]
Should use TrackedProcessable, and integrate with background task management

**Comment by AlaaKhalaf94** [comment]
Hi @gonzalon , when I try to delete about 1000 record , this messag appear

![capture1](https://user-images.githubusercontent.com/26510030/31223235-4ef26eae-a9d2-11e7-944a-00a093410efd.PNG)

And when I click on "see the status" , direct me to new page contain only this 
![capture2](https://user-images.githubusercontent.com/26510030/31223384-cd3534e0-a9d2-11e7-8497-18ec889811a0.PNG)
http://alaa-test2.admin.kademi-ci.co/tasks/deleteAllPoints_alaa-test2_188184

Can you do the same as on the reindex page ?

**Comment by gonzalon** [comment]
![image](https://user-images.githubusercontent.com/2773216/31252764-c5c8e43e-aa7e-11e7-93db-124ece9f8d5c.png)

**Comment by AlaaKhalaf94** [comment]
passed
