### ISSUE TITLE
In vouchers page , the checkbox to select all vouchers doesn't work

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#3970]
Here in this page : http://bartercard.admin.kademi.com.au/vouchers/

![capture1](https://user-images.githubusercontent.com/26510030/30795391-fd2a3cae-a1d5-11e7-9e3a-f1b4a71ad7c7.PNG)

**Comment by Uafinder** [comment]
It works only once e.g. if i select all, then deselect all, then select all again and it doesn't work this time.

**Comment by Uafinder** [comment]
Yup, works ok
