### ISSUE TITLE
Support dynamic fields being defined on funnels

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3971]

**Comment by bradmac** [comment]
Here's an example of a dynamic field definition in a funnel.json:

```
    "extraFields": [
        {
            "name": "numGudairModules",
            "title": "Num Gudair Modules",
            "required": false,
            "aggregate": false,
            "expression": "user.name",
            "type" : "integer"
        }
    ],
```

**Comment by bradmac** [comment]
And can be used like this:

![image](https://user-images.githubusercontent.com/826458/30836632-ecde82ba-a2bb-11e7-9443-1e56a8abae80.png)

**Comment by bradmac** [comment]
Hi @mkhoudary, please try this and close if thats what you need

**Comment by mkhoudary** [comment]
Hey @bradmac this should work fine with me with the Zoetis requirements, waiting for deployment.
