### ISSUE TITLE
eCommerce products search slow

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#3974]
![image](https://user-images.githubusercontent.com/1945230/30796391-7c77b9ce-a1da-11e7-9405-a22ffb13eb81.png)
When select All in products filter it searches all products for 10-15 secs (1000 prods)

**Comment by bradmac** [comment]
Should be refactored to be same as reward store product management

**Comment by gonzalon** [comment]
Seems to be already refactored!

**Comment by Uafinder** [comment]
Case:
I've a store with 1000 products in it.
I've apply a filter to see a few of them, then I change a filter to "All categories" and search longs for a 18 seconds.
![image](https://user-images.githubusercontent.com/1945230/33884055-e37d0490-df46-11e7-84eb-48ec753f7d78.png)
http://vladtest04.admin.kademi-ci.co/ecommerce/vlad04ecomm-ecomstore/#products-tab

**Comment by Uafinder** [comment]
Much better!
