### ISSUE TITLE
Products ordering doesn't work from product page directly

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#3975]
When you add a product to cart from manage products page it's ok and added product to a cart
![image](https://user-images.githubusercontent.com/1945230/30796748-15c210b0-a1dc-11e7-8734-856b23169788.png)
When you accessing direct product page and try to add product to cart, nothing is happened.
![image](https://user-images.githubusercontent.com/1945230/30796794-3cd4bc84-a1dc-11e7-81c7-09b2af60f314.png)
http://version1.vladqa3-products.kademi-prod.com/storeqa1/
![image](https://user-images.githubusercontent.com/1945230/30797204-c26cd31c-a1dd-11e7-9269-14f26257618a.png)

**Comment by ducdhm** [comment]
Fixed! 

FYI: It's e-commerce issue not rewardstore

**Comment by Uafinder** [comment]
Yeap, working ok
