### ISSUE TITLE
Lead importer bugs

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#3976]
http://vlad-test.admin.kademi-prod.com/funnels/journeyqa1/version1/#lead-tab
1. Start row field should be moved to the right, like in other importers
![image](https://user-images.githubusercontent.com/1945230/30804308-a3241f84-a1f5-11e7-9f6f-6b8837a624b9.png)
2. Assigned to, source, stage, deal amount, closed date fields are not importing.
![image](https://user-images.githubusercontent.com/1945230/30804383-ee2d345c-a1f5-11e7-8240-a42b98dad88b.png)
3. When lead profile already created with other group memberships, group membership "leads" is not added to him.
![image](https://user-images.githubusercontent.com/1945230/30804520-6c18f824-a1f6-11e7-84d4-aabcd424eef8.png)
4. Admin have no permissions to lead from other sales manager.
![image](https://user-images.githubusercontent.com/1945230/30804643-d1f802b6-a1f6-11e7-8c27-7d42bf339820.png)
5. Visual bug - overlay
![image](https://user-images.githubusercontent.com/1945230/30805488-51dac330-a1fa-11e7-9c2c-abbabcf1f761.png)

**Comment by tuzzmaniandevil** [comment]
I've moved the importer to the new table uploader framework, This alone should fix many bugs! I've also fixed the values not updating

**Comment by Uafinder** [comment]
All closed, third moved to separate issue
