### ISSUE TITLE
Nested hide/show button doesn't work with next

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#3978]
Here : http://3dn.admin.kademi.com.au/websites/idhealth-training/version1/programs/prof/MH1/mod03/#files-tab
please make view to page num 5

and try to press ""next"" in the bottom of page it will show the hidden content inside the first hide/show button
and that's right

but when you press again on ""next"" , it success to go to the next page without show the hidden content inside the second hide/show button

please , make this property to be allowed on nested hide/show button

**Comment by bradmac** [comment]
@ducdhm please make sure the component isnt using any page load JS, because modules use pjax so needs to use the page loaded event

**Comment by ducdhm** [comment]
Fixed!

**Comment by AlaaKhalaf94** [comment]
Hi @ducdhm , can you create the possibility of enabling this property for the hide/show button and removing the enablement ?

Ex: checkbox in the properties of the component

**Comment by ducdhm** [comment]
@AlaaKhalaf94 As I checked in old site, all you need for this case is collapsed panel, not show hide button.

**Comment by ducdhm** [comment]
As discussed, we'll use accordion or let current behavior be.

**Comment by AlaaKhalaf94** [comment]
These have passed
