### ISSUE TITLE
Leads link follow you to wrong leads page

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#3979]
http://vlad-test.admin.kademi-prod.com/leads/2300643/#information-tab
![image](https://user-images.githubusercontent.com/1945230/30805598-be701568-a1fa-11e7-84b9-778878a321f6.png)

![image](https://user-images.githubusercontent.com/1945230/30805611-cba469dc-a1fa-11e7-932e-1c35bbe4b503.png)

**Comment by bradmac** [comment]
That link should go to the manage journey/funnel page

**Comment by gonzalon** [comment]
The link to /leads now will show you all the leads for the org. (Quick version, probably will need improvement in a future)

![image](https://user-images.githubusercontent.com/2773216/30999710-2c106290-a533-11e7-96e0-0399546ad8d4.png)

**Comment by Uafinder** [comment]
Probably would be to return here:
http://vlad-test.admin.kademi-ci.co/funnels/journeyqa1/version1/#lead-tab

**Comment by bradmac** [comment]
No, its fine for a lead page to have as its parent the leads list page.

**Comment by Uafinder** [comment]
as you wish, however leads page looks poor at the moment and leads tab on the journey page looks better... this page need to be improved, so moving to separate issue...
