### ISSUE TITLE
Manage products search works very sensitive

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#3981]
![image](https://user-images.githubusercontent.com/1945230/30809441-65fda1ba-a20a-11e7-994b-7e7b51482cba.png)

There should be a delay before start searching, to avoid multiple search pop-ups and multiple query DB operations.

http://vlad-test.admin.kademi-prod.com/products

**Comment by bradmac** [comment]
@ducdhm please make sure the alerts dont accumulate, should only ever be 1.

And we have a jquery lib already to provide a typing delay

**Comment by mrdadah** [comment]
I've checked it.
I see the alerts don't accumulate, also typing delay is the same as the other pages.

@Uafinder, could you please recheck if the issue still exist?

**Comment by Uafinder** [comment]
https://drive.google.com/file/d/1hncnighale07Z6azmZvzujQfS_K6K412/view?usp=sharing
If It looks ok, then great.
Probably, would be great to remove multiple pop-ups
http://vladtest11.admin.kademi-ci.co/products/

**Comment by bradmac** [comment]
I think thats ok. We might change the notification UI at some point, but the main thing for now is that pages are using the notification system correctly.
