### ISSUE TITLE
manage SKUs search works only when you initiate it by pressing Enter

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#3982]
![image](https://user-images.githubusercontent.com/1945230/30809562-d43b5b90-a20a-11e7-9381-f94b791da4b4.png)

There should either button for manual search or context search feature (like on the other pages).

http://vlad-test.admin.kademi-prod.com/skus

**Comment by bradmac** [comment]
Should have a typing delay feature to auto-search

**Comment by mrdadah** [comment]
Done

**Comment by Uafinder** [comment]
Same thing here
looks pretty, but multiple pop-ups should be removed
![image](https://user-images.githubusercontent.com/1945230/34356970-622fd3c6-ea4b-11e7-9250-e7cad505a7de.png)
http://vladtest11.admin.kademi-ci.co/skus

**Comment by Uafinder** [comment]
Yup, fine
