### ISSUE TITLE
Task details minor bug - text doubling

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#3983]
![image](https://user-images.githubusercontent.com/1945230/30809796-b1595edc-a20b-11e7-99cc-8fa47022b5e4.png)
http://vladqa4-kcrm.kademi-prod.com/dashboard

**Comment by Uafinder** [comment]
It's the same, at the moment... :(
![image](https://user-images.githubusercontent.com/1945230/30847311-b62190fe-a2a3-11e7-8738-23327e28314a.png)
Also
http://vladqa4-kcrm.kademi-prod.com/tasks/
![image](https://user-images.githubusercontent.com/1945230/30847367-f72a79e4-a2a3-11e7-9a85-c9bee48b392a.png)

**Comment by bradmac** [comment]
hey @Uafinder please make sure you're testing with a new account.

When we update libs those changes dont apply to existing accounts

**Comment by bradmac** [comment]
If this problem exists with a new account, please provide a link to the admin

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/31068996-27ace8ea-a763-11e7-86b0-5733e74605e6.png)
http://vlad-test6.admin.kademi-ci.co
http://version1.vladqa6-kcrm.kademi-ci.co/dashboard

**Comment by bradmac** [comment]
Aha, it was in 2 places :)

**Comment by Uafinder** [comment]
Yeap, works ok
