### ISSUE TITLE
Manage SKUs page: images doesn't show up without refresh

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#3984]
http://vlad-test.admin.kademi-prod.com/skus/

No image appears
1. Push image upload
2. Upload image
3. Push save
4. No image appears - need to refresh page.

![image](https://user-images.githubusercontent.com/1945230/30811136-054186d8-a210-11e7-89d3-58f25a0f9038.png)

No automatic renewal after removing image
![image](https://user-images.githubusercontent.com/1945230/30811445-de4429c2-a210-11e7-9148-6fdb7158ec6f.png)

No success pop-up message when cropping image
1. Push image upload
2. Upload image
3. Push crop after drawing rectangle
4. No success pop-up message appears.

**Comment by anhnt** [comment]
Working ok here http://anhtest2.admin.kademi-ci.co/skus/

@Uafinder if you can reproduce all 3 problems above please ping me

**Comment by bradmac** [comment]
Note that the vlad-test account has an expired license, and there's a problem renewing it. Will check after that account is enabled again

**Comment by Uafinder** [comment]
1st and 2nd issues are really ok,
The 3rd is still an issue:

No success pop-up message when cropping image
1. Push image upload
2. Upload image
3. Push crop after drawing rectangle
4. No success pop-up message appears.

**Comment by anhnt** [comment]
Fixed

**Comment by Uafinder** [comment]
ok
