### ISSUE TITLE
Manage SKUs page: image no viewable

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#3985]
![image](https://user-images.githubusercontent.com/1945230/30811751-cb40a336-a211-11e7-9249-63a4ede935df.png)
http://vlad-test.admin.kademi-prod.com/skus/

**Comment by tuzzmaniandevil** [comment]
Can't reproduce. Works fine for me

**Comment by Uafinder** [comment]
Not working for me, Chrome and FF both

**Comment by bradmac** [comment]
@tuzzmaniandevil I can easily reproduce the error

- open this page - http://vlad-test.admin.kademi-prod.com/skus/
- click this image 
![image](https://user-images.githubusercontent.com/826458/30988956-8256c526-a4f8-11e7-8672-15b5e2aeb177.png)
- displays the modal with broken image
![image](https://user-images.githubusercontent.com/826458/30988973-953b955e-a4f8-11e7-9fcf-6a44a453aedd.png)


Checking the image which is being loaded, its this address, so is missing the hash:
http://vlad-test.admin.kademi-prod.com/_hashes/files//alt-150-150.png

**Comment by tuzzmaniandevil** [comment]
All that modal does is show any existing images on the Product

@ducdhm Can you add a button to the modal to be able to manually upload an image? Like the upload button if no image is selected

**Comment by bradmac** [comment]
Just to confirm, when clicking an image, display a modal with
- an image upload button
- list of images attached to the product

The user should then be able to upload a new image or select an image from the product.

It might be nice to replace the current button group with just showing this modal.

**Comment by Uafinder** [comment]
it works great!
