### ISSUE TITLE
Update stock value error when push cancel

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#3986]
![image](https://user-images.githubusercontent.com/1945230/30812017-70cdd292-a212-11e7-80f7-3355820df1ca.png)
![image](https://user-images.githubusercontent.com/1945230/30812027-75e537b6-a212-11e7-84f9-504aa2ca6b66.png)

http://vlad-test.admin.kademi-prod.com/inventory/2288599/

**Comment by tuzzmaniandevil** [comment]
Fixed

**Comment by Uafinder** [comment]
looks ok
