### ISSUE TITLE
Inventory manage page:

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#3987]
![image](https://user-images.githubusercontent.com/1945230/30812568-c4c72ed8-a213-11e7-9a7d-3eaf86fa4732.png)
No of products empty...
http://vlad-test.admin.kademi-prod.com/inventory/

Additional link expected
![image](https://user-images.githubusercontent.com/1945230/30812616-e7809216-a213-11e7-800c-06a3d405bf3e.png)
http://vlad-test.admin.kademi-prod.com/inventory/2288596/

**Comment by bradmac** [comment]
Is this problem still active?

**Comment by Uafinder** [comment]
Second is gone, first is still active
number of products empty
![image](https://user-images.githubusercontent.com/1945230/37663321-a42808ae-2c61-11e8-9102-61ee66191e58.png)
http://vladtest44c.admin.kademi-ci.co/inventory/
but when you enter the inventory
![image](https://user-images.githubusercontent.com/1945230/37663356-b627ea74-2c61-11e8-872c-573ee4d49152.png)
You see that there are something inside

**Comment by gonzalon** [comment]
![image](https://user-images.githubusercontent.com/2773216/37687182-69690a62-2cff-11e8-8e65-6caac1f2681f.png)

**Comment by Uafinder** [comment]
Done... it works
