### ISSUE TITLE
Hard delete function for vouchers

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3988]
Currently we have a soft-delete function for vouchers, but this makes data migration hard.

Please add an additional function to do hard-deletes of vouchers.

This should have appropriate warnings. It might be nice to have a text field where the user is required to enter their password, and this is explicitly checked in the delete process

**Comment by gonzalon** [comment]
![image](https://user-images.githubusercontent.com/2773216/30833858-40d7ca52-a2ad-11e7-8121-e19350022e5a.png)
![image](https://user-images.githubusercontent.com/2773216/30833870-4d9c521c-a2ad-11e7-8646-eb1fe27a8d16.png)

**Comment by Uafinder** [comment]
When incorrect password is entered:
![image](https://user-images.githubusercontent.com/1945230/30845737-7a5d6ee0-a29d-11e7-81b9-aab05a41e238.png)
or
![image](https://user-images.githubusercontent.com/1945230/30845752-8c6f92fc-a29d-11e7-9435-19e5cac1e87c.png)
Should be Incorrect password error

**Comment by gonzalon** [comment]
Changed the message to "Incorrect password"

**Comment by Uafinder** [comment]
Still remains first error:
![image](https://user-images.githubusercontent.com/1945230/30966479-b1509308-a461-11e7-98ef-6c78e9dfd582.png)
It happens when you try to enter password which not met requirements of default password policy.

**Comment by gonzalon** [comment]
@Uafinder misunderstood your first message! now isn't validating the format for the password

**Comment by Uafinder** [comment]
this error appeared when i tried to use simple password (111111 for example). Now it's ok!
