### ISSUE TITLE
subscription: downgrading plan doesnt work

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3990]
1. I created a trial account
2. upgraded to standard
3. upgraded to pro
4. attempted to downgrad to standard

However, i was charged $500 for pro again, and the plan didnt change.

![image](https://user-images.githubusercontent.com/826458/30833536-ec505496-a2ab-11e7-9d5b-07081998213d.png)

Instead, this should have done a downgrade with no charge, as the existing plan fees would cover the period and leave a credit of about $300.

**Comment by bradmac** [comment]
This worked correctly, but when i looked at the transaction list i thought it had charged me 200, but it had applied a credit:
![image](https://user-images.githubusercontent.com/826458/30837891-ba9cb908-a2c4-11e7-8f40-d10e39a0b668.png)

So i think we need to highlight credit rows. Please use a bootstrap label-success class.

**Comment by gonzalon** [comment]
@bradmac should I close this?
