### ISSUE TITLE
Promotions bugs

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#3994]
http://vlad-test.admin.kademi-prod.com/rewards/promotionqa01/
1. Date pickups doesn't appears when you click on fields
![image](https://user-images.githubusercontent.com/1945230/30849146-0ea96304-a2aa-11e7-8acb-fa607641dec0.png)
2. Save causes JSON reaction
![image](https://user-images.githubusercontent.com/1945230/30849314-96cae3e8-a2aa-11e7-8027-d5554d1feb89.png)
3. Cancel button does nothing.
![image](https://user-images.githubusercontent.com/1945230/30849412-f00b4a06-a2aa-11e7-994b-6fda22da2b99.png)
4. Image add button does nothing
![image](https://user-images.githubusercontent.com/1945230/30850240-8a3f2550-a2ad-11e7-897b-d503a5b8d7c5.png)
5. When adding groups, groups doesn't appear
![image](https://user-images.githubusercontent.com/1945230/30851777-46dfd732-a2b2-11e7-94df-b5c71f9f1799.png)
![image](https://user-images.githubusercontent.com/1945230/30851812-635ca822-a2b2-11e7-92cc-7ed89c141db6.png)

**Comment by Uafinder** [comment]
2,3,4,5 appears when you try to access "Content" tab while page is still loading.
Looks like Loading kEditor interrupts normal Ajax loading.

**Comment by bradmac** [comment]
Appears to be because of JS init error
```
ReferenceError: initEditorFrame is not defined

```

```
            $(function () {
                $("select.pointsType").click(function () {
                    showHidePointsOrgType();
                });
                showHidePointsOrgType();

                initEditReward(quiz, allGroups);
                //function to initiate bootstrap-datepicker
                $('.date-picker').datepicker({
                    autoclose: true
                });
                $('.TabNav a:first').tab('show');

                initRewardImages();
                initEditorFrame();
            });
```

**Comment by Uafinder** [comment]
those ones are ok
