### ISSUE TITLE
Promotion competition page

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#3995]
http://version1.vladqa6-rewards.kademi-prod.com/rewards/promotionqa02/
![image](https://user-images.githubusercontent.com/1945230/30856758-fbb31688-a2c1-11e7-9c45-f986d4db7197.png)
1. Red color by default on some fields

If you setup Organisation checkbox
2. Can't submit entry because of Organisation. Organisation should be picked up from list.

If you setup image upload checkbox
3. No possibility to upload image
![image](https://user-images.githubusercontent.com/1945230/30857079-2313809a-a2c3-11e7-96f9-6ffacc885208.png)

If you setup product checkbox
4. Please select a product error appears
![image](https://user-images.githubusercontent.com/1945230/30857191-885d093a-a2c3-11e7-87cd-8c9a82b70ec5.png)

5. Submit another doesn't work
![image](https://user-images.githubusercontent.com/1945230/30857428-5a0886e4-a2c4-11e7-9f33-edcf552b02fc.png)

6. No possibility to make additional fields visible on form.
![image](https://user-images.githubusercontent.com/1945230/30857454-72d160f6-a2c4-11e7-86a8-3e3bf4cc15c7.png)
![image](https://user-images.githubusercontent.com/1945230/30857468-7a5cf20e-a2c4-11e7-84be-515295169af0.png)

**Comment by bradmac** [comment]
There's a JS error on init
```
TypeError: $(...).mupload is not a function
```

**Comment by bradmac** [comment]
@Uafinder can you please provide a link to the admin account for this site so we can investigate?

**Comment by Uafinder** [comment]
http://vlad-test.admin.kademi-prod.com/rewards/promotionqa02/#details-tab

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/34333379-94ad138c-e96e-11e7-979f-6191ccc476d1.png)

Looks good atm without error

**Comment by Uafinder** [comment]
most of them fixed
closing this one and will open another issue...
