### ISSUE TITLE
Add SEO support to html content pages

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4000]
extension to - https://github.com/Kademi/kademi-dev/issues/3941

Plain html content pages should implement SEOResource

**Comment by tuzzmaniandevil** [comment]
This can now be used by setting the follow meta tags on a page:
- **keywords** - This is a comma seperated field e.g. `about us, about, help`
- **description** 

![image](https://user-images.githubusercontent.com/3378330/30889421-be943f2c-a382-11e7-918c-9759d81c83bc.png)

**Comment by bradmac** [comment]
We shouldnt expect users to have to enter the meta field names.

@ducdhm can you please update the form so those fields are hard coded?

**Comment by ducdhm** [comment]
@bradmac Front-end stuff is done. But when saving `keywords` value with `,` character, `keywords` and `description` will be merged into a meta named `keywords,description`

**Comment by bradmac** [comment]
Hi @ducdhm i think there's a misunderstanding. We need inputs for the specific SEO fields. The user should not need to or be able to edit the names of the meta fields.

![image](https://user-images.githubusercontent.com/826458/30988481-e2989556-a4f6-11e7-9d46-03f0b52e7244.png)

**Comment by ducdhm** [comment]
@bradmac Where did you check it? I checked in QA (https://rootorg.admin.kademi-prod.com/pages/kademi-www/version56/) and it's working normally.

**Comment by ducdhm** [comment]
`keywords` and `description` are always there. User can't remove or edit meta name, just value for these metas.

![newui](https://user-images.githubusercontent.com/1289631/31048079-36f2c87a-a640-11e7-95a7-6dafb25e30f0.png)

**Comment by bradmac** [comment]
That looks better, i couldnt see that before.

But next problem is those fields must not be required:

![image](https://user-images.githubusercontent.com/826458/31050670-41efb274-a6ae-11e7-8265-32f39f120cff.png)

**Comment by ducdhm** [comment]
Fixed!

**Comment by ducdhm** [comment]
@bradmac can you do backend stuff for supporting "," in keywords?

**Comment by bradmac** [comment]
@ducdhm i cant see any problem. I've set values with commas and seems to work correctly:
![image](https://user-images.githubusercontent.com/826458/31590611-cc76c5a0-b26f-11e7-9537-fdde5e0eadd0.png)

![image](https://user-images.githubusercontent.com/826458/31590615-d7114f26-b26f-11e7-8e7a-342697d77586.png)

**Comment by anhnt** [comment]
tested working ok for me
