### ISSUE TITLE
Subscription: Error on upgrading

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4001]
This occured after first upgrading to Standard.

![image](https://user-images.githubusercontent.com/826458/30894079-ff14f300-a39d-11e7-9f67-295b72b1e7dd.png)

http://ksignupb1.admin.kademi-prod.com/license
http://subscription.kademi-prod.com/manage-subscription?adminDomain=ksignupb1.admin.kademi-prod.com

**Comment by gonzalon** [comment]
@bradmac should I close this?
