### ISSUE TITLE
Allow selecting website as filter on web hits report 

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4002]
https://github.com/Kademi/client-2one2f-3M/issues/129

**Comment by gonzalon** [comment]
MVEL:

Seems its working for the expression evaluation but not for the templates.
Seems that for the templates isnt using the PropertyAccessor.

For the cases where we use MVEL.eval methods it's working fine.
We should only add the implementation for the filter manager, something like:

```
                ParserContext ctx = new ParserContext();
                ctx.addProperty("mvel.filtersManager", "io.milton.cloud.server.repoapps.FiltersManager");
                Object result = MVEL.eval(template, localVars);
```

But for the cases we use templates isnt working: 

```
TemplateRuntime.eval(templ, localVars).toString();
```

Or how I tried addapting the code so it would use a provided ParserContext 

```
                ParserContext ctx = new ParserContext();
                ctx.addProperty("mvel.filtersManager", "io.milton.cloud.server.repoapps.FiltersManager");
                CompiledTemplate ct = TemplateCompiler.compileTemplate(templ, ctx);
                return TemplateRuntime.execute(ct, null, new MapVariableResolverFactory(localVars)).toString();
```

**Comment by AlaaKhalaf94** [comment]
Hi @gonzalon , I see the selecting website as filter is set , but what is these numbers ?
http://alaa-test1.admin.kademi-ci.co/reporting/esWebsiteAccess?startDate=26%2F09%2F2017&finishDate=02%2F10%2F2017

![capture1](https://user-images.githubusercontent.com/26510030/31068796-467be3d0-a762-11e7-9cdd-c70b34301128.PNG)

**Comment by gonzalon** [comment]
@AlaaKhalaf94 that number should be the same as the hits, fixed now :)

![image](https://user-images.githubusercontent.com/2773216/31103700-d99d4910-a834-11e7-87be-f0168205ecd5.png)

**Comment by AlaaKhalaf94** [comment]
passed
