### ISSUE TITLE
Can't find the voucher type

### ISSUE THREAD

**Issue by salehh93** [Kademi/kademi-dev#4005]
about Vouchers types **deleted** 
appear bug after click on  "Hard Delete Vouchers"

http://cpg.admin.kademi.com.au/voucher-type/?deleted#

![image](https://user-images.githubusercontent.com/23012214/30906622-1843382c-a381-11e7-8187-1d204973f4cf.png)

**Comment by bradmac** [comment]
please make sure we can use hard delete on soft deleted voucher types.

**Comment by Uafinder** [comment]
yup, works ok
