### ISSUE TITLE
KEditor is not working correctly in scheduled emails

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4006]
![image](https://user-images.githubusercontent.com/826458/30945067-5b5e485e-a458-11e7-80a6-144a30645dc6.png)

**Comment by ducdhm** [comment]
Fixed!

![newui](https://user-images.githubusercontent.com/1289631/30949083-977fae82-a43e-11e7-9fe1-ba004c7bbbb3.png)

**Comment by Uafinder** [comment]
It stucks for me at this point.
![image](https://user-images.githubusercontent.com/1945230/31003944-ecca4ec6-a4fa-11e7-8526-82e01ea88780.png)
http://vlad-test.admin.kademi-ci.co/scheduledEmails/scheduledqa05/#configuration-tab

**Comment by Uafinder** [comment]
Just claryfying, can't reproduce... :(

**Comment by Uafinder** [comment]
Aha, found it...
It look stucks when you try to do hard refresh in FF (e.g. ctrl +F5)
And then only clearing cache could solve a problem...

**Comment by bradmac** [comment]
hey @Uafinder I'm closing because the problem related to this issue is fixed.

If there is another issue with editor initialisation, please create another issue for that.
