### ISSUE TITLE
KCRM analytics funnels not working

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4008]
http://kcrm.kademi.us/analytics/kademi-sales?filters=source%3DNone&stage=Proposal

Clicking on lead circles does not always return data in the table, when there should be leads appearing.

For example clicking on hot circle returns no results yet hot has leads set to the funnel stage.

![image](https://user-images.githubusercontent.com/2201340/31002759-d30f7fb2-a52f-11e7-960a-cc3cc93bd87d.png)

Also not sure what these icons are?

![image](https://user-images.githubusercontent.com/2201340/31002864-484948ee-a530-11e7-969b-1bb0dad9b4a7.png)

**Comment by anhnt** [comment]
its working fine with latest leadman-lib. Please ping me when you need to update kcrm us website @paddyow

**Comment by AlaaKhalaf94** [comment]
There is not problem on it
