### ISSUE TITLE
Error when create >2000 vouchers

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4010]
![image](https://user-images.githubusercontent.com/1945230/31005510-ae5eab58-a501-11e7-985c-61f187c00e64.png)
the are creating successfully, but error shows up
when amount is smaller it doesn't raise this error...
http://vlad-test.admin.kademi-ci.co/voucher-type/skoda/#vouchers-tab

**Comment by bradmac** [comment]
Might be a gateway timeout

**Comment by tuzzmaniandevil** [comment]
Looks ok, I added 5000 vouchers. Must be fixed with the nginx change

**Comment by Uafinder** [comment]
Yeap, looks ok at the moment.
