### ISSUE TITLE
Issue when using filter and delete vocuhers

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4011]
![image](https://user-images.githubusercontent.com/1945230/31006058-dd681d1a-a503-11e7-8c31-5e122e1641de.png)
For example you select "Volkswagen" voucher type filter and then delete several vouchers from it
After deleting them, filter remains, but there are appears vouchers from other types in list (AUD for example)

**Comment by bradmac** [comment]
Please make sure that all criteria are applied on changed criteria

**Comment by Uafinder** [comment]
yeap, works ok
