### ISSUE TITLE
Show deleted vouchers issues

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4012]
http://vlad-test.admin.kademi-ci.co/voucher-type/
![image](https://user-images.githubusercontent.com/1945230/31006755-bcd53850-a506-11e7-89db-de8ba48ccd8a.png)
1. When you delete voucher type it appears deleted voucher types list. But all vouchers there are lost.
![image](https://user-images.githubusercontent.com/1945230/31006819-00f2e262-a507-11e7-92b7-ec04b086ea60.png)
![image](https://user-images.githubusercontent.com/1945230/31006861-2a4f5c58-a507-11e7-9469-53ee5ccbcb3d.png)

2. When you're on show deleted page, there shouldn't be menu like "Delete", rather should be "Restore".
![image](https://user-images.githubusercontent.com/1945230/31007018-b8154d22-a507-11e7-98e1-e3703d504cbf.png)

3. When you push "Hard delete" it does something, and return you to non-deleted page, but not change button.
![image](https://user-images.githubusercontent.com/1945230/31007312-d3cdb350-a508-11e7-9cef-247073baf1f8.png)

4. There is no possibility to hard delete voucher type.

5. When you for example delete one voucher type and then want to hard delete other vouchers, hard delete button does nothing.
E.g. you delete 1, than want to hard delete 2, and this will not work without refresh.

6. Hide "Sell vouchers" button
![image](https://user-images.githubusercontent.com/1945230/31009373-d64f54d8-a50f-11e7-9c8d-6856d0041463.png)

**Comment by gonzalon** [comment]
1. Fixed
2. Not showing the "Delete" option, the restore could be a future improvement
3. Fixed, and now it also reload in the same page.
4. Maybe another improvement

**Comment by gonzalon** [comment]
5. Fixed
6. if we hide the button there is no other way to use this functionality, it's that ok?

**Comment by bradmac** [comment]
> if we hide the button there is no other way to use this functionality, it's that ok?

The button should be hidden for deleted voucher types. The user should not be able to sell vouchers for a deleted voucher type.

**Comment by Uafinder** [comment]
Yup, looks fine at the moment
