### ISSUE TITLE
Ckeditor addon to insert fontawesome icons

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#4014]
https://www.michaeljanea.com/ckeditor/font-awesome

**Comment by bradmac** [comment]
:+1:

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/33703916-c5587c12-db5c-11e7-8759-a46abf487807.png)

**Comment by Uafinder** [comment]
Really good thing... working perfect, only one question... should it be added to email editor?
http://vladtest02.admin.kademi-ci.co/groupEmails/3254887/#messages-tab

**Comment by bradmac** [comment]
No, should not be available in EDM because it relies on CSS assets that arent compatible with mail clients

**Comment by Uafinder** [comment]
Understood... so it works great!
