### ISSUE TITLE
Improve rewardstore app components

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#4015]
* Search doesnt work
 * Add load more button in case infinitive scroll doesnt work

**Comment by ducdhm** [comment]
Done!

**Comment by Uafinder** [comment]
Not sure if there should be load more button when no products appears by filter
![image](https://user-images.githubusercontent.com/1945230/31074424-4c690388-a779-11e7-91d2-2429f1b334a0.png)

Search working poor... e.g. If i want to find Product0* it doesn't find anything, but if i enter an exact product title - it finds product successfully.
![image](https://user-images.githubusercontent.com/1945230/31074633-3c8c7e44-a77a-11e7-92e9-d79fa4465ca5.png)
![image](https://user-images.githubusercontent.com/1945230/31074645-492c28fc-a77a-11e7-9d02-c324cdda4ab4.png)
Also "Load more" button appears everywhere...

Also search by code doesn't work.

**Comment by ducdhm** [comment]
@Uafinder Can you provide me link to check?

**Comment by bradmac** [comment]
I think Vlad is right that the "load more" button should be hidden when there's no more results

**Comment by Uafinder** [comment]
@ducdhm  this link was actual yesterday.
vladqa6-promo.kademi-ci.co/vladreward1/
http://vlad-test6.admin.kademi-ci.co
userqa05@mailinator.com

I've created a fresh account
vlad8-promo.kademi-ci.co
http://vlad-test8.admin.kademi-ci.co
adminqa@mailinator.com
![image](https://user-images.githubusercontent.com/1945230/31124947-394d0f66-a84f-11e7-9fec-af9647243f58.png)
![image](https://user-images.githubusercontent.com/1945230/31124973-57f7a660-a84f-11e7-855f-e1f7fab3be76.png)
![image](https://user-images.githubusercontent.com/1945230/31124983-61009758-a84f-11e7-80ab-24e2f0e2f391.png)
Search doesn't work at all

Load more button disappears completely, i haven't saw it anymore anywhere.

**Comment by ducdhm** [comment]
I fixed Load more button stuff.

**Comment by tuzzmaniandevil** [comment]
@ducdhm Added productCode as a search field as requested :-)

**Comment by ducdhm** [comment]
Done!

**Comment by Uafinder** [comment]
1. Search is not working by product title:
![image](https://user-images.githubusercontent.com/1945230/32899076-a568f9f6-caf2-11e7-818f-6e90ec4b2926.png)
![image](https://user-images.githubusercontent.com/1945230/32899089-aef53764-caf2-11e7-8488-5e8a45ed0171.png)

2. When you find something "Load more" button appears:
![image](https://user-images.githubusercontent.com/1945230/32899116-c914d0d2-caf2-11e7-820e-71d24415412f.png)

http://vlad52-store_vlad-test52.kademi-ci.co/vlad52-store-store
http://vlad-test52.admin.kademi-ci.co/websites/

**Comment by ducdhm** [comment]
@tuzzmaniandevil Can you help me in this issue again? After adding productCode in search field, the search feature work incorrectly. Example: when you install KRewardStore app, you go to website and search `Hawai`, you'll get nothing. But if you search with `Hawaii`, you can see the product with title `Hawaii`.

**Comment by tuzzmaniandevil** [comment]
Updated query

**Comment by ducdhm** [comment]
Many thanks @tuzzmaniandevil

**Comment by ducdhm** [comment]
@Uafinder About the button which you see when there is no production, you need to update lib.

All done!

**Comment by Uafinder** [comment]
Yup, it's fine, looking great!
