### ISSUE TITLE
Lead importer fails when Deal Amount field contains dot or comma

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4016]
![image](https://user-images.githubusercontent.com/1945230/31011654-bb64c452-a517-11e7-93fd-912e3d26ffa3.png)

[export-leads(6).zip](https://github.com/Kademi/kademi-dev/files/1343924/export-leads.6.zip)
http://vlad-test.admin.kademi-ci.co/funnels/journeyqa1/version1/#lead-tab

**Comment by bradmac** [comment]
This should be as tolerant as possible of different numeric formats. Same should be true of other importers which deal with numeric values, eg sales data

**Comment by gonzalon** [comment]
We are going to support formats like:
- comma for thousand separator
- dot for decimal separator
- having dollar euro pound simbols

Ex:
$1,000.50
1,000.50
1000.50

--
Updated code in
Leads Importer
Products Importer
Sales Importer

**Comment by Uafinder** [comment]
working ok
