### ISSUE TITLE
Journey link on page is bad

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4017]
![image](https://user-images.githubusercontent.com/1945230/31012149-6fc91992-a519-11e7-8f8a-e9bcb2644a80.png)
![image](https://user-images.githubusercontent.com/1945230/31012166-7d240e3a-a519-11e7-9e08-a120b09b6a6b.png)

http://vlad-test.admin.kademi-ci.co/funnels/journeyqa1/version1/#journeyBuilder-tab

**Comment by gonzalon** [comment]
This link its also wrong:

![image](https://user-images.githubusercontent.com/2773216/32629042-c679ed1c-c5fc-11e7-90d9-6176fad27663.png)

![image](https://user-images.githubusercontent.com/2773216/32629076-de2e2860-c5fc-11e7-92f6-8b7860b9cf5f.png)

**Comment by gonzalon** [comment]
As this page should be to manage the funnel branches and this is still to be implemented, I added a blank page with a redirect to the /funnels page.

**Comment by Uafinder** [comment]
ok, problem is solved for now
