### ISSUE TITLE
Create and delete account old and new QA

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4019]
http://rootorg.admin.kademi-prod.com/organisations/
When create ORG account on old QA server - everything is fine
http://rootorg.admin.kademi-ci.co/organisations/
When create ORG account on new QA server - gain error
![image](https://user-images.githubusercontent.com/1945230/31018130-a4b2457e-a533-11e7-8536-078d93ac0045.png)

When truing to delete ORG account on new QA server - gain error
![image](https://user-images.githubusercontent.com/1945230/31018202-d52071b8-a533-11e7-957c-3dd69683e239.png)

**Comment by bradmac** [comment]
@tuzzmaniandevil we might need to extend the timeout on nginx. It should probably be unlimited as we have some long running requests

**Comment by tuzzmaniandevil** [comment]
I've changed the timeout on nginx to 30 minutes

**Comment by Uafinder** [comment]
Yeap, creating works ok.
But deleting still failed.
You could try to delete vlad-test8 or vlad-test3,4,5 organisations from rootorg.
http://rootorg.admin.kademi-ci.co/organisations/
vlad@kademi.co

**Comment by tuzzmaniandevil** [comment]
The error is: `Cannot delete an admin domain. Remove the admin domain first`

**Comment by bradmac** [comment]
@Uafinder this error is correct, you cant delete an organisation which is an admin domain. If you want to, you first need to blank out the admin domain.

It would be nice to have a better error message for this situation, but in reality admin domains are very rarely deleted, and never by clients, so that is a low priority task.

**Comment by Uafinder** [comment]
Moved to separate issue...
https://github.com/Kademi/kademi-dev/issues/4060
