### ISSUE TITLE
Lead Bulk Remove

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4020]
Add a tick boxes to each lead row and a button to bulk delete leads.

Should be available on any filter including Active Closed Cancel.

http://kcrm.kademi.us/leads/?query=&leadType=active

**Comment by tuzzmaniandevil** [comment]
Backend done and basic front-end

**Comment by tuzzmaniandevil** [comment]
@anhnt or @ducdhm can you make it look awesome?

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/32217827-bd3ed148-be5b-11e7-8420-55bb00548fe3.png)
Done

**Comment by Uafinder** [comment]
looks bad in a base lib
![image](https://user-images.githubusercontent.com/1945230/32227587-7a23339c-be54-11e7-811b-736eb0dd10df.png)

http://vlad27-leads_vlad-test27.kademi-ci.co/leads/?query=&leadType=active
http://vlad-test27.admin.kademi-ci.co/websites/

Fresh account

**Comment by anhnt** [comment]
Hi @Uafinder 
Please upgrade leadman-lib

![image](https://user-images.githubusercontent.com/735555/32228273-63bb32fe-be80-11e7-82de-18d641362072.png)

**Comment by anhnt** [comment]
http://vlad-test27.admin.kademi-ci.co/websites/vlad27-leads/version1/#panel_apps-tab

**Comment by anhnt** [comment]
Actually I should update bootstrap-base to depend on latest leadman-lib and themes to depend on latest bootstrap-base. Please re-check in fresh account

**Comment by Uafinder** [comment]
Looks ok at the moment!
