### ISSUE TITLE
Keditor poll and learning panel

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4021]
The new Poll and Learning panel have extra padding.  When added to the page they should be aligned left and have equal margins to the right and button as they tile.

![image](https://user-images.githubusercontent.com/2201340/31052602-ba43181c-a6d4-11e7-8e5f-d252cfb5e832.png)

**Comment by ducdhm** [comment]
As discussed with @bradmac 

```
Add js stuff to handle tile components automatically. If we drop tile component into a cell, we'll make this cell is `tiled cell` by adding `div.row` inside it which wraps all tile components
```

**Comment by ducdhm** [comment]
Done!
