### ISSUE TITLE
Carousel options

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4023]
Add the following options:

1) Show or hide gradient shadow (the right and left shading on the carousel) 
2) Option to have the image 'Stretched' or 'Actual size' 

![image](https://user-images.githubusercontent.com/2201340/31052633-030e6442-a6d6-11e7-8506-301f553c058f.png)

This is stretched:
![image](https://user-images.githubusercontent.com/2201340/31052660-e6efe104-a6d6-11e7-9892-c15b3e745c88.png)

Actual size (without shading)
![image](https://user-images.githubusercontent.com/2201340/31052662-09ed0a9c-a6d7-11e7-9591-9d3f809966d2.png)

**Comment by ducdhm** [comment]
Done!

**Comment by paddyow** [comment]
Awesome!
