### ISSUE TITLE
K-toolbar border radius does not work

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4024]
When adding a border radius value, none of the components frames adopt a border radius.  It is my understanding that applying a radius would cause each component frame to have rounded edges?

![image](https://user-images.githubusercontent.com/2201340/31052810-64a4cec2-a6da-11e7-8676-a2b5700f9f60.png)

**Comment by bradmac** [comment]
Yep,should do. If the bootstrap parameters arent being honored by components, we need to fix the components.

**Comment by ducdhm** [comment]
@paddyow Which theme are you using? And which component are not changed after you change border-radius?

Note: value should be `5px` not only `5`

**Comment by bradmac** [comment]
hey @paddyow can you give a link to this page?

**Comment by ducdhm** [comment]
Note: Need to fix the way K-theme override `.btn` class. At the moment, it forces `.btn` has `border-radius: 0`

**Comment by anhnt** [comment]
Its working for me. Anw i just added border radius small and large option to customize 

![image](https://user-images.githubusercontent.com/735555/32261202-95fe32f0-beff-11e7-94bb-3e121a9f867c.png)

**Comment by AlaaKhalaf94** [comment]
checked
