### ISSUE TITLE
Module page components

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4026]
PSD file here: [Component - module page.zip](https://github.com/Kademi/kademi-dev/files/1347685/Component.-.module.page.zip)

The module page should be split out into configurable components. 

- Page should be split into 3 components 1) Page body 2) Module page list 3) Q&A comments
- The module page should allow full width content based on the setting of the containers
- Splitting the components out will allow the admin to add/remove/shuffle them around the page
- I have updated the icons in the control component to use Fontawesome
- I have adjusted the Q&A comments section
- The modules page list has included a completed vs not completed status icon
- Need to get the correct theme colors applied, for example the Q&A submit button should be success not info, the icons in the control panel should be text color

Preview:
![image](https://user-images.githubusercontent.com/2201340/31061141-98ff19b8-a769-11e7-8364-0cdbef53c8af.png)

Components with markup:
![image](https://user-images.githubusercontent.com/2201340/31061136-8ec3aff4-a769-11e7-9bbe-141738528f84.png)

**Comment by ducdhm** [comment]
Done!

**Comment by paddyow** [comment]
Bottom section still needs updating as per creative:

![image](https://user-images.githubusercontent.com/2201340/31210997-ab03bf4a-a9e1-11e7-9ba4-cd25cbd1fd39.png)

**Comment by ducdhm** [comment]
```
Add option to show/hide title
```
@paddyow Let's discuss about it later

```
Missing progress bar
```
Fixed!

```
Setting row height is great, but images are getting stretched and look pixelated
```
Fixed!

**Comment by paddyow** [comment]
- Image are still pixelated 
![image](https://user-images.githubusercontent.com/2201340/31321745-f43e094e-acd5-11e7-87c6-2c576bbe5279.png)

**Comment by ducdhm** [comment]
Done!

**Comment by paddyow** [comment]
This page http://moblix-channel.kademi-ci.co/training.html
This user http://moblix.admin.kademi-ci.co/manageUsers/152956/#summary-tab

1) Note these components need to work with the module picker when it has been separated out as a component i.e. we could use the component to show different modules in different layouts on the page, then use the picker to filter on the programs and courses
2) Full height thumbnail option needs a gradient at the bottom of the container like the PSD for lighter images or the text i.e. Title and  CPD points will not show
3) Need option to show any program or course for any given component.  Can we have a list with check boxes?
4) Need to fix responsive layout - looks bad (see below)

1. I think at mobile breakpoint we turn off full height or the text will be sitting over a small image area
2. Gap appearing
3. Copy is flush with the grey container, need to add padding

![image](https://user-images.githubusercontent.com/2201340/31359395-8d4099e4-ad95-11e7-8e74-6c0c5daaf6c6.png)

**Comment by ducdhm** [comment]
Done!

**Comment by paddyow** [comment]
http://moblix-channel.kademi-ci.co/training.html

1) Gap missing that was there before that divides the two components?
2) The list format broken

![image](https://user-images.githubusercontent.com/2201340/31531152-fe9be0a6-b030-11e7-9362-9380a75c3bca.png)

**Comment by ducdhm** [comment]
Fixed!

![fireshot screen capture 074 - training - moblix-channel_kademi-ci_co_training_html](https://user-images.githubusercontent.com/1289631/31541637-84b8212e-b039-11e7-9c4c-e6999d49e526.png)

**Comment by paddyow** [comment]
Unable to select any courses from the component:

Web pages http://moblix.admin.kademi-ci.co/pages/moblix-employees/version1/

Template http://moblix-employees.kademi-ci.co//theme/apps/user/contenteditor?fileName=dashboard.html&miltonUserUrl=/users/patrick&miltonUserUrlHash=44eb828a-0b03-4c44-95eb-83caa4685c4c:byvbI5h_wlylV2jF4aVUED09x1E

![image](https://user-images.githubusercontent.com/2201340/31582310-bca06658-b1cb-11e7-9367-7231e88f71d9.png)

**Comment by bradmac** [comment]
There are no courses in that website

![image](https://user-images.githubusercontent.com/826458/31582561-8313133c-b1e3-11e7-8820-e59a35ddfd01.png)

**Comment by Uafinder** [comment]
Can't find and add modulePagePagination component to test it separately.
Is it ok?
![image](https://user-images.githubusercontent.com/1945230/31657205-7e86fee2-b336-11e7-810d-48469cdb0af2.png)
http://vlad17-learn.kademi-ci.co//theme/apps/learner/contenteditor?fileName=modulePage.html&miltonUserUrl=/users/18f99d7f-b812-4fb0-8ef3-b3dce205fff5&miltonUserUrlHash=cacefa35-d624-410d-b807-a338509085b5:QBEDQvfuBMextOsi0c51-4Xc2O8

**Comment by ducdhm** [comment]
@bradmac Because type of `modulePagePagination` is `module` so in contentEditor, it's not showed in snippets list. Is it correct behavior?

**Comment by bradmac** [comment]
Working now:

![image](https://user-images.githubusercontent.com/826458/31696870-9b3d7d56-b410-11e7-900a-7bf56df73548.png)

**Comment by bradmac** [comment]
I've updated LearningApp to return appropriate components for the template, rather then the edited resource
```
    public List<KEditorComponent> components(CommonResource cr, TemplatingApplication.TemplateDef tdef) {
        if( tdef != null && tdef.getParentPath().equals("theme/apps/learner/") ) {
            return ComponentBean.forType(allComponents, "html", "module");
        } else {
            return ComponentBean.forType(allComponents, cr);
        }        
    }
```

**Comment by Uafinder** [comment]
Yeap, it looks ok.
