### ISSUE TITLE
Dynamic components dont work when using content editor in custom app

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#4027]
From duc

> Because dynamic components settings are loading from url _components/componentName and each dynamic components has its own js stuff for loading its settings. We can't change them via jquery.contentEditor plugin.

> And I think it's bad idea to let JS stuff handle backend stuff. IMHO, I think it's simple stuff, just need to handle any request which contains _components and redirect it to /_components as default for custom app and issue is resolved

https://github.com/Kademi/client-gilpin-travelworld/issues/22#issuecomment-332417563

**Comment by bradmac** [comment]
We've now mapped _components to custom resources. But currently custom resources have no way to indicate what types of resource they are. Components have a list of types they are compatible with, such as "html", "edm", "product", etc.

**Comment by bradmac** [comment]
I've added methods to ControllerMappingBuilder to allow specifying resource types for custom app resources.

Eg - using addType
```
controllerMappings
    .adminController()
    .path("/kfeedback/")
    .enabled(true)
    .defaultView(views.templateView("kfeedback/index.html"))
    .addType("survey")
    .build();
```

**Comment by bradmac** [comment]
Have applied an update which should now correctly locate component resources

**Comment by anhnt** [comment]
worked great on AU server
