### ISSUE TITLE
google maps component does not work when adding in manual address

### ISSUE THREAD

**Issue by Anton69arb** [Kademi/kademi-dev#4028]
http://version1.playmoremusic.kademi-prod.com/contenteditor?fileName=contact-us.html

![image](https://user-images.githubusercontent.com/32444328/31062550-e1b94c0a-a787-11e7-88f4-189605e49b0f.png)

**Comment by bradmac** [comment]
Also tried with our office address and got same result

**Comment by ducdhm** [comment]
Duplicated with https://github.com/Kademi/kademi-dev/issues/4249
