### ISSUE TITLE
Top Balances component query not working

### ISSUE THREAD

**Issue by gonzalon** [Kademi/kademi-dev#4030]

**Comment by gonzalon** [comment]
To test
-create a website
-enable the reward store app
-add the Top Balances

**Comment by AlaaKhalaf94** [comment]
Hi @gonzalon , I have a question for you

When I add Top Balances component and select "site1-points2" points bucket from settings
data in this page : http://alaa-test1.admin.kademi-ci.co/rewards/points/ that related to "site1-points2" points bucket will appear in point Balance table in the site ?

If no , can you guide me to which data will appear in point Balance table in the site ?
this is admin console : http://alaa-test1.admin.kademi-ci.co/

I add Top Balances component here "home" page : http://alaa-test1.admin.kademi-ci.co/pages/site1/version1/

**Comment by bradmac** [comment]
Currently the component says "no matching participants"

![image](https://user-images.githubusercontent.com/826458/31121009-06ea5d64-a893-11e7-9eaa-4afe5c07d5b5.png)

This is probably because no user groups have been assigned to the points bucket:
![image](https://user-images.githubusercontent.com/826458/31121046-2db7b450-a893-11e7-9215-6a8719062c34.png)

http://alaa-test1.admin.kademi-ci.co/points-buckets/

Please assign a user group (eg participants) to the points bucket, and then check.

**Comment by AlaaKhalaf94** [comment]
I  assign a user group to the points bucket , and still nothing appears in point balance table
http://alaa-test1.admin.kademi-ci.co/points-buckets/

![capture1](https://user-images.githubusercontent.com/26510030/31122570-0b908f6c-a845-11e7-902c-0f0e2a4366c2.PNG)

**Comment by bradmac** [comment]
Yep, setup correctly but appears to not be working

**Comment by gonzalon** [comment]
@AlaaKhalaf94 
We have changed it, so it would show you the report based on your membership with the ReportingAccess role.

**Comment by AlaaKhalaf94** [comment]
Hi @gonzalon , This worked with me
But I cant see the point balance to organisation

Here , in point bucket setting I select "Points go to user's organisation"
http://alaa-test1.admin.kademi-ci.co/points-buckets/site1-points2/?startDate=02%2F10%2F2017&finishDate=04%2F10%2F2017&dataQuery=&startPos=0#details-tab

Then I've converted points to organization
http://alaa-test1.admin.kademi-ci.co/rewards/points/?dataQuery=org&searchGroup=undefined&searchReward=site1-points2&tagId=&reasonCode=

and those points doesn't appear in point balance table
here in home page : http://alaa-test1.admin.kademi-ci.co/pages/site1/version1/

![capture1](https://user-images.githubusercontent.com/26510030/31164581-758ff122-a8f0-11e7-9d96-768083246c43.PNG)

**Comment by bradmac** [comment]
hi @AlaaKhalaf94, after a configuration change like that you'll need to reindex organisations and profiles

please reindex and then check again

**Comment by AlaaKhalaf94** [comment]
That works with me well , Thanks @bradmac
