### ISSUE TITLE
Duplicating a container will have new container with components that have the same IDs

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#4032]
![image](https://user-images.githubusercontent.com/735555/31065832-857c66a8-a772-11e7-8b46-28e63200c5e2.png)

It does show on first 2 block but not show when edit 3rd block

http://travelworld.admin.kademi.com.au/blogs/featured/experts/#bodyCopy-tab

**Comment by anhnt** [comment]
I can see the problem. When duplicating a container to create new one, all components inside that container has the same ID. So keditor would not work properly ie init ckeditor inline

**Comment by ducdhm** [comment]
I have checked and seem like it's dynamic element's issue.

**Comment by anhnt** [comment]
tested working ok
