### ISSUE TITLE
Learning Components

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4034]
Thoughts for eLearning components:

Options: Panels or List will vary how the modules are displayed

Panels:
- Options using check boxes to choose if CPD points, Reward points, Time, and Button is shown (can  very a minimal or detailed panel)
- Like reward store panels (Number of panels, panels per row)

When Lists is selected:
- No options, just returns all modules in the chosen course

General:
- The progress bar is a blue strip
- The module started or not started is supported by a button "Start" or "Resume"

![image](https://user-images.githubusercontent.com/2201340/31067969-7404ada2-a7a1-11e7-945d-a30d44482a48.png)

When the panels are used on the dashboard, they could look like this:
![image](https://user-images.githubusercontent.com/2201340/31068132-523b5198-a7a2-11e7-874c-a82f14e8aa77.png)

**Comment by paddyow** [comment]
@ducdhm  I have sent you the artwork via wetransfer. 

Module picker - fix up the module picker based on artwork

**Module Tile Component**
We have different use cases where we want a big minimal hero tile on the dashboard vs. a list of tiles on the my learning page that have more detail, so looking to create a configurable tile component.

- Show panel with button
- Show time
- Show reward points
- Show CPD points

All tiles will show a module title + progress bar

![image](https://user-images.githubusercontent.com/2201340/31106323-91a77624-a836-11e7-94cc-d9db7803f019.png)

**Module List**
- Shows all details including module description 
- Show all modules or cap the number or modules
- Rows alternate with light grey color

![image](https://user-images.githubusercontent.com/2201340/31106106-be248392-a834-11e7-9d79-2654e6b1aa56.png)

**Comment by ducdhm** [comment]
Done!

**Comment by paddyow** [comment]
A few things:
1) Latest artwork was not followed
2) Progress bar not working
