### ISSUE TITLE
Backup/Restore issue

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4035]
http://vlad-test.admin.kademi-prod.com
I've created a backup here, and restore it here:
http://vlad-test.admin.kademi-ci.co/

As a result, all client sites are empty. After investigation we discovered that there is no template /theme/defaultThemeTemplate.html and http://vlad-test.admin.kademi-ci.co/repositories/bootstrap-base/1.4.1 is empty at all.

**Comment by tuzzmaniandevil** [comment]
Did you select "Yes" for "Transfer content from a remote server" ?

As you are going between servers you need to do this and provide the correct details to be able to fetch the files

**Comment by Uafinder** [comment]
No, i've use local file. I've not tested online restore between two servers, just a simple file backup.

**Comment by tuzzmaniandevil** [comment]
@Uafinder You still upload the backup json file, But because you are restoring a backup from a different server you need to fill in the remote server details otherwise it won't be able to get any of the blobs

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/31147678-1b628b00-a8e7-11e7-9aca-4094986fe8ef.png)

**Comment by Uafinder** [comment]
understood, will rise another issue if there will be errors
