### ISSUE TITLE
Journey creation bug - title empty

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4036]
http://vlad-test6.admin.kademi-ci.co/funnels/journeyqa01/version1/#properties-tab
when you create a journey, you've entering it's title, but when you're redirecting to it's properties - title field is empty.
![image](https://user-images.githubusercontent.com/1945230/31068470-cb6c5720-a760-11e7-9aeb-631d584e7372.png)

**Comment by anhnt** [comment]
Fixed

**Comment by Uafinder** [comment]
Passed
