### ISSUE TITLE
KCRM: Leads are not appearing after creation without page refresh

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4038]
I create a lead but it doesn't appears in list without refresh
![image](https://user-images.githubusercontent.com/1945230/31069983-6650ad94-a767-11e7-8fe9-06d630fe8791.png)
![image](https://user-images.githubusercontent.com/1945230/31070016-776943ac-a767-11e7-9308-e58f11cf0bba.png)

http://version1.vladqa6-kcrm.kademi-ci.co/leads/?query=&leadType=active
http://vlad-test6.admin.kademi-ci.co/funnels/journeyqa01/version1/#properties-tab

**Comment by anhnt** [comment]
Working ok now can you please re-check?

**Comment by Uafinder** [comment]
looks ok at the moment!
