### ISSUE TITLE
When website search app is not enabled front-end error appears

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4041]
![image](https://user-images.githubusercontent.com/1945230/31073431-7998e332-a774-11e7-86e9-e562c6a4e42c.png)
http://vladqa6-promo.kademi-ci.co/vladreward1/
http://vlad-test6.admin.kademi-ci.co/websites/vladqa6-promo/version1/#panel_apps-tab

**Comment by bradmac** [comment]
@tuzzmaniandevil can you investigate

**Comment by tuzzmaniandevil** [comment]
@Uafinder I can't re-produce, I had the website search app turned on and off. If you can reproduce it can you please provide the steps to do so?

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/31122162-736eef0e-a843-11e7-8071-3901e5f5b923.png)

I was able to reproduce it on the fresh account:
1. Create an account http://vlad-test7.admin.kademi-ci.co
2. Create admin user
3. Create a website and give access to admins
4. Enable global apps: products, rewards, reward store
4. Create several products
5. Create points bucket (reward)
6. Create reward store, add several products there, activate it, give access to it for admins
7. Login to website http://vlad7-promo.kademi-ci.co/
8. Forget to add apps to a website
9. Add reward store app to website, products and rewards
10. Go to store, a see an error... http://vlad7-promo.kademi-ci.co/reward/

I wouldn't touch this account to give you possibility to reproduce it.

**Comment by tuzzmaniandevil** [comment]
Changed rewardstore-lib to depend on the search app. So the search app will be enabled by default now

**Comment by tuzzmaniandevil** [comment]
You will need to create a new account to test it.

**Comment by Uafinder** [comment]
Yeah, works ok...
