### ISSUE TITLE
Incorrect number of products when add them to reward store

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4042]
![image](https://user-images.githubusercontent.com/1945230/31074188-1694cba8-a778-11e7-83f9-e3d067e6b327.png)
95 records - it's a total amount of all products, no matter of added or not.
http://vlad-test6.admin.kademi-ci.co/reward-store/vladreward1/?addProducts

**Comment by tuzzmaniandevil** [comment]
Should be sorted now :-)

**Comment by Uafinder** [comment]
Yup, looks ok at the moment
