### ISSUE TITLE
Improve main leads page

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4043]
http://vlad-test6.admin.kademi-ci.co/leads/
Looks poor at the moment.
As a result of https://github.com/Kademi/kademi-dev/issues/3979

**Comment by bradmac** [comment]
:+1:

**Comment by bradmac** [comment]
Looks ok to me at the moment. Is this still active?

**Comment by Uafinder** [comment]
It looks that it's impossible to get to it other way but direct link, and it looks not very poor - so probably ok for now
I was able to get to it only by moving from here
http://vladtest44c.admin.kademi-ci.co/leads/11405764/#information-tab
![image](https://user-images.githubusercontent.com/1945230/37664203-7d3ad74c-2c63-11e8-9cfa-90ea5a8a40d7.png)

![image](https://user-images.githubusercontent.com/1945230/37664225-8bb381a2-2c63-11e8-8d87-1667e12cc5e0.png)
Note that:
- no column for journey name
- no filter or search
- a lot of columns which are not often for use

if that's ok - issue can be closed

**Comment by bradmac** [comment]
I think its ok for now
