### ISSUE TITLE
Award point records appears twice

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4044]
![image](https://user-images.githubusercontent.com/1945230/31076493-0580930a-a783-11e7-9e13-0d4c8841dc6c.png)
When issued date specified, second record appears with it, when issued date is not specified, both records has similar issued dates.
http://vlad-test6.admin.kademi-ci.co/rewards/points/
![image](https://user-images.githubusercontent.com/1945230/31076658-ff4d5db4-a783-11e7-919e-3f763ff4907b.png)
![image](https://user-images.githubusercontent.com/1945230/31076700-29aceb9c-a784-11e7-9271-79beaae81822.png)
![image](https://user-images.githubusercontent.com/1945230/31076688-17f1d408-a784-11e7-91d9-653670cccf27.png)

**Comment by tuzzmaniandevil** [comment]
Tested locally and couldn't reproduce, Then found this allocation rule on the account:
http://vlad-test6.admin.kademi-ci.co/points-rules/rule1#general-tab

That's why they are being awarded twice :-)

**Comment by Uafinder** [comment]
Ooops, my mistake...
I've delete points allocation rule, and it's begin to award once, but why pop-up appears twice?
![image](https://user-images.githubusercontent.com/1945230/31115114-b6b8b00c-a829-11e7-99fc-38fcc90d3d1c.png)

http://vlad-test6.admin.kademi-ci.co/rewards/points/
adminqa@mailinator.com

**Comment by Uafinder** [comment]
moved to separate issue
https://github.com/Kademi/kademi-dev/issues/4051
