### ISSUE TITLE
Add translation error

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4046]
![image](https://user-images.githubusercontent.com/1945230/31079039-07ab6650-a78d-11e7-98ce-1a71df3875e7.png)

![image](https://user-images.githubusercontent.com/1945230/31078987-d447e0a4-a78c-11e7-9f60-2ab3a83c04a2.png)
http://vladqa6-promo.kademi-ci.co/vladreward1/
http://vlad-test6.admin.kademi-ci.co

**Comment by gonzalon** [comment]
@Uafinder just remember to choose one language in your profile.
![image](https://user-images.githubusercontent.com/2773216/31210788-2a7d2054-a9f1-11e7-8281-a596a38604ff.png)

**Comment by Uafinder** [comment]
Yeah, working great
