### ISSUE TITLE
Only show appropriate templates in new page modal

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4047]
Currently, the new page modal shows a list of all templates in the system, which includes templates that are not appropriate for content pages. Such as the template for a profile page:

![image](https://user-images.githubusercontent.com/826458/31104749-3ba98884-a83b-11e7-8c1e-8e3ff044e9f0.png)

This list should be filtered to only show templates appropriate for content pages, and should default to the normal page template

**Comment by Uafinder** [comment]
Looks filtered at the moment
