### ISSUE TITLE
Promotion components

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4048]
Need a component to show promotions.

Two types:
- Promotion tile
- Hero promotion tile

Like we created for Bosch, there are 3 states of promotions active, winner pending and closed.

For the hero tile, it would be great if the title font could scale based on the size of the title, for example a large promotion tile would use a H2.

![image](https://user-images.githubusercontent.com/2201340/31106411-378b6474-a837-11e7-80ca-2bca3157e6bc.png)

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/31670223-5469fbfa-b381-11e7-92aa-e0798b84d4db.png)
done

**Comment by AlaaKhalaf94** [comment]
Hi @paddyow , In the second row of the component , should it display only two promotions or more ?
as shown in the screenshot

![capture1](https://user-images.githubusercontent.com/26510030/32440355-74e94410-c2fb-11e7-9195-948592d273bd.PNG)
