### ISSUE TITLE
Improve manage scheduled emails

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4050]

**Comment by bradmac** [comment]
New list page UI

![image](https://user-images.githubusercontent.com/826458/31109846-188c04a2-a85f-11e7-8214-e9b91fefde87.png)

New detail page UI

![image](https://user-images.githubusercontent.com/826458/31109899-77f0f18c-a85f-11e7-9e8a-bbb504e6009d.png)

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/31116942-9ff8b540-a830-11e7-80ef-24f3c91593c0.png)
http://vlad-test6.admin.kademi-ci.co/scheduledEmails/scheduledqa02
adminqa@mailinator.com (user is necessary)

**Comment by tuzzmaniandevil** [comment]
Fixed

**Comment by Uafinder** [comment]
Yeap, bug fixed.
One thing... members count does not count dynamic group members...
![image](https://user-images.githubusercontent.com/1945230/31163485-42542594-a8eb-11e7-96ca-51f1106a8a43.png)
http://vlad-test.admin.kademi-ci.co/scheduledEmails/scheduledqa06/
adminqa@mailinator.com
