### ISSUE TITLE
Doubling success pop-up messages bug

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4051]
http://vlad-test6.admin.kademi-ci.co/rewards/points/
adminqa@mailinator.com

Awarding or debiting points cause success pop-up messages fired twice.
![image](https://user-images.githubusercontent.com/1945230/31116028-37ccc806-a82d-11e7-9b68-ce3fddbdf2aa.png)
![image](https://user-images.githubusercontent.com/1945230/31116036-3b568b38-a82d-11e7-9fa4-6ba8d95c1769.png)

**Comment by bradmac** [comment]
There is a parameter you can pass to alerts to identify them, so they replace an existing alert rather then showing another one. Please use that.

**Comment by mrdadah** [comment]
fixed

**Comment by Uafinder** [comment]
Works fine, yoohooo!
