### ISSUE TITLE
Polls do not show unless they have a group assigned

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4056]
Is this intended?  I thought no groups shows a content item to all end users?

Poll config:  http://paddy.admin.kademi-ci.co/kpoll/managePolls/poll-Tz2eKT5gdfWubF9YVQnIaIOTwS5gNbGC#groups-tab

Test with this user: http://paddy.admin.kademi-ci.co/manageUsers/101653/#summary-tab

**Comment by bradmac** [comment]
it doesnt need to be that way, but I think thats reasonable, because in reality there will always be a group selected.
