### ISSUE TITLE
Reward store add products screen isnt working properly with parent product libraries

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4057]
Eg:
https://carters.admin.kademi.com.au/reward-store/trade-reward/?addProducts&q=&l=12198884&categoryName=[Any%20category]

![image](https://user-images.githubusercontent.com/826458/31157780-d1996362-a919-11e7-8964-c76f090db027.png)

Is missing this product:
https://carters.admin.kademi.com.au/products/80771422/#panel_details-tab

**Comment by Uafinder** [comment]
Yeap, it works at the moment
