### ISSUE TITLE
Enabling KLeadman via Market place bugs

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4061]
![image](https://user-images.githubusercontent.com/1945230/31172135-fd7ca7fa-a90a-11e7-9319-a9d6a6880136.png)

1. I've create a fresh account http://vlad-test9.admin.kademi-ci.co/
2. Create a vlad9-kcrm site
3. Install app from marketplace (website page)
4. Go to dashboard and watch messages.
5. Second and third message have incorrect links.
6. Last message says that Journey is created, but link leads to error. Probably because journey app is not enabled.

**Comment by Uafinder** [comment]
Incorrect link are remains:
![image](https://user-images.githubusercontent.com/1945230/31810904-317adc3e-b586-11e7-890b-64718167011a.png)

Journey link error also remains
![image](https://user-images.githubusercontent.com/1945230/31810921-48a1b338-b586-11e7-8cfc-3d443b038bb0.png)
Probably link should be:
http://vlad-test23.admin.kademi-ci.co/funnels/journey1/version1 where version1 should link to current version.

It's a fresh account
http://vlad-test23.admin.kademi-ci.co

**Comment by gonzalon** [comment]
@Uafinder sorry I forgot to tell you point out the last version of the lib. 
KLeadman 1.0.5
If you check you have some libs to update!

I just test it in here:
http://gnz-test1.admin.kademi-ci.co/

**Comment by Uafinder** [comment]
It works!
