### ISSUE TITLE
Import users mechanism performance

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4062]
Processing users file from specifying columns to begin import process step (from 3 to 4) takes 120 secs.
File contains ~4000 users.
![image](https://user-images.githubusercontent.com/1945230/31175051-8b7fe6f6-a916-11e7-92ef-d60fdde5c76f.png)
[users(4).txt](https://github.com/Kademi/kademi-dev/files/1355711/users.4.txt)
http://vlad-test9.admin.kademi-ci.co
adminqa@mailinator.com

Import process speed bad... 25 mins :(

**Comment by gonzalon** [comment]
@Uafinder Brad did some changes that affect a lot in the performance, this should be good enough for now!

**Comment by Uafinder** [comment]
Done a small test, result the same...
but probably not a priority at the moment
