### ISSUE TITLE
Create an auction title adds a hyphen

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4064]
When I enter an auction title like Fitbit Giveaway! - it add the name as fitbit-giveaway which is not allowed as hyphens are rejected.

1) either allow hyphens in the name (if we can)
2) or don't add hyphens in the auto name creation as the user types it

![image](https://user-images.githubusercontent.com/2201340/31205669-98b5c18a-a9be-11e7-9734-0a5a1d0cd66d.png)

http://moblix.admin.kademi-ci.co/auctions/fitbitgiveaway/#details-tab

**Comment by bradmac** [comment]
hyphens should be allowed

**Comment by AlaaKhalaf94** [comment]
passed
