### ISSUE TITLE
Levels component

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4067]
When a level component is dropped into the dashboard:

- Have option to show or hide title of the level
- Title should be H3 (or configurable i.e. choose header size)
- If there is no level do not show a panel.  The user should be able to set a level of 0 and choose what image they want to show for it
- The level image should respond i.e. if it is bigger than the container is should respond (scale down), if smaller it should not scale up.
- Do not show the title 'Channel Levels' as part of the component.  

![image](https://user-images.githubusercontent.com/2201340/31210105-3b2433d6-a9db-11e7-886d-7d0170d13dfd.png)

**Comment by paddyow** [comment]
Change 'Topic' to 'Select a Level'

Order of fields:

1) Show level name (tick box)
2) Level name font size (drop down h1, h2 etc)
3) Show placeholder image (Visible/hidden) (tick box)
4) Choose placeholder image
- small font below "Show an image when the user has no level."

*note if the user does not select show level name, nor adds a placeholder image, nothing should appear in the template*

![image](https://user-images.githubusercontent.com/2201340/31358581-ea91813e-ad91-11e7-9833-f5bf0b2a2f41.png)

**Comment by bradmac** [comment]
"Change 'Topic' to 'Select a Level'" - No, the user isnt selecting a level. They're selecting a topic which contains levels. 

The level is whatever each user has obtained.

**Comment by ducdhm** [comment]
```
Show placeholder image (Visible/hidden) (tick box)
```
Instead of it, I added remove placeholder image

![newui](https://user-images.githubusercontent.com/1289631/31376702-ff666780-adcf-11e7-9acc-c8726c868618.png)

**Comment by ducdhm** [comment]
```
note if the user does not select show level name, nor adds a placeholder image, nothing should appear in the template
```
It's available on frontend. In editor page, I still show text `No awarded level found` for letting user know where the component is
