### ISSUE TITLE
Claims Components

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4068]
Claim component:
- option to show or hide the image of the receipt 
- if the receipt image is shown, do not scale vertically, just make the image scale on the x axis only
- remove any background colors in the component (needs to be transparent) 
- add success ticks for each part of the process as the user completes the form i..e when a input is complete show the tick (use success color)
- when submitted show the complete panel, this should not have a BG color (needs to be transparent) 
- User can enter another if the button is clicked
- option to invert fonts and icons to account for white or coloured backgrounds (form and button does not need to invert)

Claims list
- option to show or hide the menu bar and check box - in case the user just wants to show a list of claims

PSD:
[Sales Claims.zip](https://github.com/Kademi/kademi-dev/files/1358112/Sales.Claims.zip)

![image](https://user-images.githubusercontent.com/2201340/31211864-567e567c-a9e8-11e7-8262-4533b02b8c8c.png)

![image](https://user-images.githubusercontent.com/2201340/31211868-5b1bb8be-a9e8-11e7-8b90-d966a7491d73.png)

**Comment by ducdhm** [comment]
```
option to show or hide the image of the receipt
```
Done!

```
if the receipt image is shown, do not scale vertically, just make the image scale on the x axis only
```
Set max-height for image is `300px`

```
remove any background colors in the component (needs to be transparent)
```
I added an option below form background color is `transparent` for letting form has transparent background

```
add success ticks for each part of the process as the user completes the form i..e when a input is complete show the tick (use success color)
```
As discussed, we will change the icon and text of `Upload receipt` to `Upload other receipt` when user selects a receipt

```
when submitted show the complete panel, this should not have a BG color (needs to be transparent)
User can enter another if the button is clicked
```
Done!

```
option to invert fonts and icons to account for white or coloured backgrounds (form and button does not need to invert)
```
You can set `inverse` for container which contains this component to do it

```
option to show or hide the menu bar and check box - in case the user just wants to show a list of claims
```
As discussed, we'll hide only add button
