### ISSUE TITLE
Changing page template causes meta tags to duplicate 

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4069]
http://moblix.admin.kademi-ci.co/pages/moblix-channel/version1/

![image](https://user-images.githubusercontent.com/2201340/31212194-b7edca1c-a9ea-11e7-870e-d8fb8b9552d1.png)

**Comment by ducdhm** [comment]
Depend on https://github.com/Kademi/kademi-dev/issues/4000

**Comment by anhnt** [comment]
I have investigated this. the form data posted to server is correct so it seems to be a java error

**Comment by tuzzmaniandevil** [comment]
The data being posted is incorrect. It's using the same meta id for both the description and the keyword fields. e.g.:
```
metaName.1508381873115:keywords
metaContent.1508381873115:
metaName.1508381873115:description
metaContent.1508381873115:
```

**Comment by tuzzmaniandevil** [comment]
I put in a fix that will be applied on the next deploy

**Comment by Uafinder** [comment]
Yes, it works!
