### ISSUE TITLE
Need help configuring sales claim APP

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4070]
- Cannot search for products that I have loaded
- Getting error when submitting
- I have setup a data series

Please advise what I need to do to make this work.

This user http://moblix.admin.kademi-ci.co/manageUsers/152956/#summary-tab

This page http://version1.moblix-channel.kademi-ci.co/contenteditor?fileName=sales-claims.html&miltonUserUrl=/users/patrick&miltonUserUrlHash=49a18864-b74b-4f35-82b3-686589ccbf90:nrdd1RCUWaR99w04g-qTuUpvjMU

![image](https://user-images.githubusercontent.com/2201340/31212611-2bf9d1e2-a9ed-11e7-8c2c-dbb1355e9e0f.png)

**Comment by bradmac** [comment]
Its only searching on products with SKU's, since the user will generally enter a SKU

http://moblix.admin.kademi-ci.co/skus/

**Comment by bradmac** [comment]
Eg
![image](https://user-images.githubusercontent.com/826458/31252911-4a627656-aa7f-11e7-977b-a63251051ca4.png)

**Comment by paddyow** [comment]
Cools I can see the prod appearing, but still getting an error when I submit.

Error when creating claim: java.lang.NullPointerException

**Comment by ducdhm** [comment]
Fixed issue related to `java.lang.NullPointerException`
