### ISSUE TITLE
Reward store template rending error

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4071]
Error rendering component: rewardStoreCategoryProducts

http://moblix.admin.kademi-ci.co/pages/moblix-channel/version1/

Rewardstore dashboard and rewardStoreCategory template.

![image](https://user-images.githubusercontent.com/2201340/31212812-8229d9bc-a9ee-11e7-84a3-73fa9df3f937.png)

**Comment by bradmac** [comment]
This error is occuring because the reward store resource is not being found.

I've added a null check. But in this case the template is being rendered for a reward store so it should definitely be found!

```
    var rewardStoreFolder = page;
    if (rewardName) {
        rewardStoreFolder = page.find("/" + rewardName);
    }
    if( rewardStoreFolder == null ) {
        log.warn("Could not find reward store: " + rewardName);
        return null;
    }
    var rewardStoreName = rewardStoreFolder.rewardStore.name;
```

**Comment by bradmac** [comment]
So @ducdhm please check why the current page is not being used as the reward store

**Comment by tuzzmaniandevil** [comment]
If no reward store is configured and it's either on a RewardStoreFolder or RewardStoreCategoryFolder it will use that to get the reward store name

**Comment by AlaaKhalaf94** [comment]
passed
