### ISSUE TITLE
Auctions Components and templates

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4072]
Update auction components
1) Component without description
2) Component with description  
3) Component closed auction

![image](https://user-images.githubusercontent.com/2201340/31360129-bc3afbc4-ad98-11e7-9bac-7aca864d1d75.png)

Create auction templates:

1) Auction list (show a list of active and closed auctions)
2) Auction detail (shows live auction details)

Split up auction detail components so they can be re-arranged in a template.

- fix up bid button so it's flush with the bid input
- bid history should be a on a white background 

![image](https://user-images.githubusercontent.com/2201340/31360232-2d56dcb0-ad99-11e7-8f97-9f6461614866.png)

**Comment by ducdhm** [comment]
Done!

**Comment by paddyow** [comment]
![image](https://user-images.githubusercontent.com/2201340/31866583-82358d42-b7cd-11e7-804b-e7b11a7112f8.png)

1) Don't say 4 weeks just put number of days i.e. 28 Days XX:XX:XX
2) Check font sizes:  Title = 20px bold,  Time 26px bold, big 16px light
3) Remove header
4) Cannot see any Auctions templates under the template section of manage pages - these need adding as per the brief above

**Comment by bradmac** [comment]
hey @paddyow can you confirm which of those things is a must-have for this milestone?
