### ISSUE TITLE
KCRM: minor visual bugs

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4075]
![image](https://user-images.githubusercontent.com/1945230/31226569-43a694f0-a9df-11e7-8887-cc3bc9e3a6b9.png)
http://vlad10-kcrm.kademi-ci.co/leads/?query=&leadType=active
http://vlad-test10.admin.kademi-ci.co/websites/vlad10-kcrm/version1/#panel_apps-tab
adminqa@mailinator.com

**Comment by anhnt** [comment]
Fixed

**Comment by Uafinder** [comment]
Works great!
