### ISSUE TITLE
Ksurveyapp fails to install

### ISSUE THREAD

**Issue by mrdadah** [Kademi/kademi-dev#4076]
When I try to install ksurveyapp from market place it fails with a generic message:

 **An error occured doing the publish. Please check your internet connection and try again**

After investigating the issue we found that this was because KongoDB app is not enabled, after checking dependencies.json we've noticed that KongoDB app is already added as an app dependency.

Applications with dependency installation from marketplace needs to be enhanced to either auto install dependencies or write the user a meaningful message.

**Comment by bradmac** [comment]
I created a fresh account, and installed ksurveyapp and it did correctly install KongoDB

![image](https://user-images.githubusercontent.com/826458/31254143-f74d5ff8-aa83-11e7-8a91-abf10128ffa1.png)

**Comment by bradmac** [comment]
But i can see this in the logs:

```
INFO  io.milton.cloud.server.apps.ApplicationManager  - No app dependencies for app  ksurveyapp
INFO  io.milton.cloud.server.repoapps.ControllerMappingList  - executeFunction: executing..
WARN  io.milton.cloud.server.repoapps.ControllerMappingList  - No such method: initApp
java.lang.NoSuchMethodException: No such function initApp
	at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:204)
```

**Comment by bradmac** [comment]
I've pushed a fix which adds a dependencies.json file for the admin context. That might resolve the problem, but note that this update isnt in a deployed version of the lib yet.

**Comment by bradmac** [comment]
@mrdadah can you confirm if this is resolved now?

**Comment by mrdadah** [comment]
Tested 👍🏻
