### ISSUE TITLE
Round corners does not appears - editor, images

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4077]
I have this page created via editor. Orange section should have rounded corners, but when you access this content via front-end site - it's simple square.
![image](https://user-images.githubusercontent.com/1945230/31230431-abf6b906-a9ec-11e7-897c-18449312a0b4.png)
![image](https://user-images.githubusercontent.com/1945230/31230447-b57dce4c-a9ec-11e7-91e2-daeba0e3aa25.png)
http://vlad-test10.admin.kademi-ci.co/products/product092/#panel-content-tab
http://vlad10-rewstore.kademi-ci.co/vlad10-rewstore-store/231302/

**Comment by ducdhm** [comment]
@Uafinder As following bootstrap doc (https://getbootstrap.com/docs/3.3/components/#jumbotron), when jumbotron in `.container`, it'll have border-radius. So I removed this option completed. So if you want rounded corner for jumbotron, just need set layout of container which contain it is `Box`.

**Comment by Uafinder** [comment]
Understood!
