### ISSUE TITLE
CONTAINER ISSUE - cant change background colors - no color picker

### ISSUE THREAD

**Issue by Anton69arb** [Kademi/kademi-dev#4078]
please can you add a color picker to the tab shown on the Screen grab (pic)
![screenshot-version1 sweets-for-heavens kademi-ci co-2017-10-06-09-30-52-489](https://user-images.githubusercontent.com/32444328/31251365-35fae48c-aa7a-11e7-93d5-306f85877077.png)

http://version1.sweets-for-heavens.kademi-ci.co/contenteditor?fileName=index.html&miltonUserUrl=/users/anton&miltonUserUrlHash=733f1b49-d7f9-4a0b-8c1c-f2983ccb9956:MtrBiOGDjhycNVrwe0iu0S-6o4k

thanks :)

**Comment by anhnt** [comment]
background color picker added 

![image](https://user-images.githubusercontent.com/735555/31817635-1aa9df9e-b5bf-11e7-898b-416218379161.png)
