### ISSUE TITLE
Cant copy and paste the content

### ISSUE THREAD

**Issue by Anton69arb** [Kademi/kademi-dev#4081]
Cant copy and paste the content with the same style and paste it to another page or any where, if you play with it, it does copy it but not in the same style manner

![cant copy and paste the content with the same style and paste it to another page or any where if you play with it it does copy it but not in the same style manner](https://user-images.githubusercontent.com/32444328/31254799-a2dec698-aa86-11e7-83e7-7293f43c5c7c.png)

http://v4-ktheme.kademi-dev.kademi.us/contenteditor?fileName=index.html&miltonUserUrl=/users/anton&miltonUserUrlHash=50cf4e41-ebf9-4820-8822-d6d001b2c3ab:P9mSRLeZiLvrWy-8nV3n_rg7w1I

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/31255864-a45f1eb4-aa8b-11e7-97d7-859d70f74740.png)

**Comment by bradmac** [comment]
@Anton69arb this might just be because the original content came from the old theme
