### ISSUE TITLE
Claims Reporting Components

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4082]
Create the following components for Keditor.  These components should not require anyone to write a query, they should be drag, drop and your're done.

**Sales Claims**
All components should filter by organisation and date range.

Component
- Single metric of how many claims have been made

Component
- Single metric of pending claims

Component
- Single metric of total claims in $

Component
- Histogram of claims over time

Component
- Table of dealers that shows date of claim, dealer name, product purhcased, sale amount, status i.e. pending or approved

**Comment by gonzalon** [comment]
Single metric components are done

**Comment by anhnt** [comment]
Component: Histogram of claims over time ---DONE

**Comment by anhnt** [comment]
Component: Table of dealers: done 

http://version1.moblix-reporting.kademi-ci.co/test.html

**Comment by anhnt** [comment]
Fixed: add kongodb prefix when declare query in custom app

```
controllerMappings.addQuery("/APP-INF/queries/claimsTable.query.json", ["kongo-salesDataClaimer"], ["ReportsViewer"]);
```

Added: Creating query table in custom app

**Comment by paddyow** [comment]
This user http://moblix.admin.kademi-ci.co/manageUsers/240803/#summary-tab
This page http://moblix-reporting.kademi-ci.co/claims.html

1. Need to add decimal place
2. Claims pending should be 2 based on the APP http://moblix.admin.kademi-ci.co/manageSaleDataClaimer/
3. No claims data appearing in table


![image](https://user-images.githubusercontent.com/2201340/31581577-02d2a23c-b1bb-11e7-8d83-50148f0d07aa.png)

**Comment by anhnt** [comment]
all fixed please check again
