### ISSUE TITLE
Editing organisation parent doesnt seem to work

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4083]
I need to move an organisation to a new parent in .AU cluster.

![image](https://user-images.githubusercontent.com/826458/31256527-a21fa2d2-aa8f-11e7-8cb0-220fc2129a30.png)

This needs to be moved under Gilpin. However, when i used "Edit parent" i get this error:

![image](https://user-images.githubusercontent.com/826458/31256563-c9613e32-aa8f-11e7-9a8a-43c68f17397b.png)

Also, if i try to use the older feature "Edit path" the default path doesnt look correct. This shouldnt be a resource path, it should be the logical parent/child organisation relationship
![image](https://user-images.githubusercontent.com/826458/31256600-2092a5c4-aa90-11e7-91f5-e79f2b2f9c44.png)

**Comment by AlaaKhalaf94** [comment]
passed
