### ISSUE TITLE
when adding an image with text, Button is not big enough and is not visible, needs to be fixed

### ISSUE THREAD

**Issue by Anton69arb** [Kademi/kademi-dev#4085]
when adding an image with text, Button is not big enough and is not visible, needs to be fixed

![1](https://user-images.githubusercontent.com/32444328/31257668-437789f0-aa96-11e7-8aea-62673ae6d099.png)

![2 button is not big enough and is not visible needs to be fixed](https://user-images.githubusercontent.com/32444328/31257670-467ea750-aa96-11e7-998c-9238cab870fb.png)

http://v4-ktheme.kademi-dev.kademi.us/contenteditor?fileName=index.html&miltonUserUrl=/users/anton&miltonUserUrlHash=247a6f86-d1d7-44ed-91fa-9e1c932a058a:BZSpxKTSyaecDT45RXFGiRKSpnw

**Comment by bradmac** [comment]
- Also the alignment dropdown has been pushed down over the image.
- and we need to be able to specify padding for the image

**Comment by bradmac** [comment]
Its almost there!

Still doesnt quite fit with K-Theme though, because of the larger then normal buttons:
![image](https://user-images.githubusercontent.com/826458/31468902-43732fa4-af3c-11e7-8824-e6fd76f63c58.png)

One option is just to remove the input labels. Users can see what the inputs are from the placeholders.

**Comment by ducdhm** [comment]
@bradmac @salehh93 how about increase width of `modal-lg` in k-theme? Issue is came from `k-theme` because of size of button

**Comment by bradmac** [comment]
@ducdhm it should be robust enough to handle different themes.

If we just remove input labels (see comment above) then there should be plenty enough room on all themes

**Comment by bradmac** [comment]
>  And maybe we can remove the label of input. No need because we have placeholder of them. And first option of align can be - No align select - when we remove the lable

+1

**Comment by ducdhm** [comment]
@salehh93 A small thing, I see you change "Width" to "Widthh", please revert it back.

**Comment by ducdhm** [comment]
Let me continue with it

**Comment by ducdhm** [comment]
Updated UI:
![newui](https://user-images.githubusercontent.com/1289631/31881623-555b3f1a-b80e-11e7-8659-8a20d78d4485.png)

**Comment by AlaaKhalaf94** [comment]
passed
