### ISSUE TITLE
Org selector not showing in Kditor or filtering correctly

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4087]
**Component not showing in Keditor**

![image](https://user-images.githubusercontent.com/2201340/31257806-84b92816-aa86-11e7-89b6-f29a55019ded.png)

When you drag this in the component does not show in the container, but it does appear in the front end after saving.

Admin http://moblix.admin.kademi-ci.co/pages/moblix-reporting/version1/

Template Page: http://version1.moblix-reporting.kademi-ci.co/contenteditor?fileName=points.html&miltonUserUrl=/users/patrick&miltonUserUrlHash=389f9d66-d2b2-4d7e-b396-43e78eab0643:caMwS5zeVdc5Jcoye4g3fOjUYHc

Admin reporting user: http://moblix.admin.kademi-ci.co/manageUsers/240803/#summary-tab
Go to points page to see the component showing.

**Not filtering in front end**

When typing in an ORG name, the only search that pulls up any org is typing the letter T
![image](https://user-images.githubusercontent.com/2201340/31257946-64ebb2d2-aa87-11e7-8132-c4c8dce3c6a4.png)

If you type Califo.... it does not work.

**Comment by Uafinder** [comment]
T works for search because T symbol are in ORG id e.g. T1, t2 and so on, so probably search does not work by Organisation name.

**Comment by Uafinder** [comment]
Created separated issue for filtering, component showing in editor fixed
