### ISSUE TITLE
Create account ID validation

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4089]
![image](https://user-images.githubusercontent.com/1945230/31265642-910e01da-aa78-11e7-9ee4-79d0530b4bf1.png)
Error appears when you provide ID with uppercase characters.
Should be a soft validation or just converting ID to lowercase.
http://vlad-test10.admin.kademi-ci.co/organisations/

**Comment by gonzalon** [comment]
now for the accounts its converting the org id to lowercase

**Comment by Uafinder** [comment]
It works!
