### ISSUE TITLE
KAuctions app installation dashboard messages add

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4093]
Should be added admin dashboard messages for installation of Auction APP as it exists on other apps installation.

**Comment by bradmac** [comment]
Sorry, not sure what you mean. Can you please clarify?

**Comment by Uafinder** [comment]
I mean that some apps like Reward Store of Leadman raise some dashboard messages in admin which tells you about some groups automatic creation with links on it and that there are some content created by default. Would be great to have some for auctions.
Like this:
![image](https://user-images.githubusercontent.com/1945230/35375979-b5c6c2ec-01b1-11e8-9f4a-309ae6c23c65.png)

or teach me how to create them and add to app install, and I will create them for some apps

**Comment by Uafinder** [comment]
Doh... it's already created
We've created an auction called vlad26auc - Sample Auction. You can manage it here

So closing this one
