### ISSUE TITLE
Site pop-up tip bad

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4094]
![image](https://user-images.githubusercontent.com/1945230/31276911-09960aa2-aaa7-11e7-8ede-f18235e629b3.png)
Website manage pop-up tips bad

**Comment by salehh93** [comment]
I used the title method 
![image](https://user-images.githubusercontent.com/23012214/31467328-3b1201dc-aee2-11e7-8011-0fb5a45422f9.png)
@bradmac  that's good ?

**Comment by bradmac** [comment]
:+1:

**Comment by Uafinder** [comment]
Great, it works!
