### ISSUE TITLE
KEditor - change photo button does nothing

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4095]
![image](https://user-images.githubusercontent.com/1945230/31277373-50a52e94-aaa9-11e7-9c89-1a01c54e2b4f.png)
I've add a simple image + text container, press change gear icon on container and Change photo button doesn't work.
http://vlad-test10.admin.kademi-ci.co/products/product090/#panel-content-tab
adminqa@mailinator.com

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
it works
