### ISSUE TITLE
Inverting a container makes calendar unreadable 

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4096]
http://moblix.admin.kademi-ci.co/pages/moblix-channel/version1/

sales-claims.html

I need to invert the container so the claims completion message with the thumbs up is white and not black.  But doing so inverts the calendar.

Can a container be inverted without inverting a calendar?

![image](https://user-images.githubusercontent.com/2201340/31303521-af9b3798-ab5a-11e7-9498-5463621b63e2.png)

**Comment by ducdhm** [comment]
Fixed!
