### ISSUE TITLE
Edit button in claims table does not work

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4097]
Clicking edit does nothing.

User http://moblix.admin.kademi-ci.co/manageUsers/152956/#summary-tab

![image](https://user-images.githubusercontent.com/2201340/31303791-30e3279e-ab5f-11e7-94c7-c9c5c4555ac3.png)

**Assign to Vlad for testing**

**Comment by AlaaKhalaf94** [comment]
passed
