### ISSUE TITLE
Apply background image to parent container applies it to the child contatiner

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4098]
If you apply a BG image to a parent container, it should not inherit into the child containers otherwise the user has to go through and correct all child containers.

![image](https://user-images.githubusercontent.com/2201340/31305117-b147b918-ab7d-11e7-99a1-32af1b19d4aa.png)

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
Looks pretty
