### ISSUE TITLE
Cannot change dynamic group title

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4099]
- Create a dynamic group
- Edit a dynamic group
- Only option are below which resets the dynamic group to a primary, list or tag after you rename it

![image](https://user-images.githubusercontent.com/2201340/31306012-935c2906-ab92-11e7-8f74-8c726abd553d.png)

Change dynamic group icon to Font Awesome fa-refresh

Config page"

- Correct copy to "A dynamic group is driven by rules. Select the rules below for profiles to be included in this group.'

![image](https://user-images.githubusercontent.com/2201340/31306026-e7420216-ab92-11e7-88da-a1016b1d2bb3.png)

**Comment by bradmac** [comment]
Please update the group membership settings modal. A normal group should not be able to be changed to a dynamic gruop, and vice versa. 

So we can just hide the type selection for dynamic gruops

**Comment by gonzalon** [comment]
![image](https://user-images.githubusercontent.com/2773216/32634893-be0e7f60-c612-11e7-9459-f96a8b62d334.png)

![image](https://user-images.githubusercontent.com/2773216/32634910-d64651f2-c612-11e7-8acc-35a06a262340.png)

**Comment by AlaaKhalaf94** [comment]
passed
