### ISSUE TITLE
Registration component

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4101]
Add the following options:

- Show or hide lables
- Align fields left, right and center
- Choose input size (small, medium and large)
- Customize which fields to show or hide 
- Number of columns i.e. 1,2,3 or 4
- Set padding in between fields
- Would be good if we could order fields by dragging and dropping them

![image](https://user-images.githubusercontent.com/2201340/31313437-0fefc4b8-ac2f-11e7-9cc3-362cbcff1f2a.png)

**Comment by mrdadah** [comment]
The previous commits were necessary for Waterco.
I'll continue the issue later when I have some time to.

**Comment by bradmac** [comment]
:+1:

**Comment by mrdadah** [comment]
I've added show/hide cancel button option, to be used in phhub
https://github.com/Kademi/client-sudler-phhub/issues/4

**Comment by anhnt** [comment]
- ~~Choose input size (small, medium and large)~~

**Comment by anhnt** [comment]
- Align fields left, right and center
- Number of columns i.e. 1,2,3 or 4
- Set padding in between fields
>> Should use default bootstrap form and align field by container

**Comment by AlaaKhalaf94** [comment]
Hi @anhnt , I can't see these options in within list of component settings

I test here : http://testaccount03.admin.kademi-ci.co/websites/testaccount03/version1/#panel_theme-tab

![untitled01](https://user-images.githubusercontent.com/26510030/38172286-5168ccf2-35b2-11e8-820f-59caeef3a9e2.png)

**Comment by anhnt** [comment]
@AlaaKhalaf94 

Show or hide lables -> **done**
Align fields left, right and center -> **we wont do, we use bootstrap stock form layout**
Choose input size (small, medium and large) -> **done**
Customize which fields to show or hide -> **done**
Number of columns i.e. 1,2,3 or 4 -> **its not easy to have build settings that put fields on specific column**
Set padding in between fields -> **wont do, use bootstrap style**
Would be good if we could order fields by dragging and dropping them -> **i dont think we should do**

**Comment by bradmac** [comment]
:+1:

**Comment by AlaaKhalaf94** [comment]
Thanks @anhnt
