### ISSUE TITLE
Cannot edit email using Text Editor

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4102]
Drop an email node into a journey
Edit email
Choose 'Text Editor'
See error message 'Invocation of method'

![image](https://user-images.githubusercontent.com/2201340/31313715-b6e58c88-ac36-11e7-9118-4fd4d006068d.png)

If you first edit the email using Keditor, then save, then open using the editor it open fine.

Journey http://paddy.admin.kademi-ci.co/funnels/test/version1/#journeyBuilder-tab
EMail http://paddy.admin.kademi-ci.co/funnels/test/version1/emailAction-ec2327/#message-tab

**Comment by bradmac** [comment]
```
10:50:12 Caused by: java.lang.NullPointerException
10:50:12 	at io.milton.cloud.server.web.KademiResourceFactory.findResource(KademiResourceFactory.java:241)
10:50:12 	at io.milton.cloud.server.web.KademiResourceFactory.findResource(KademiResourceFactory.java:193)
10:50:12 	at io.milton.cloud.server.web.templating.VelocityHtmlTemplater.getTemplateResource(VelocityHtmlTemplater.java:284)
10:50:12 	at io.milton.cloud.server.web.templating.VelocityHtmlTemplater.getCssPaths(VelocityHtmlTemplater.java:215)
10:50:12 	at io.milton.cloud.server.web.templating.ThemeDependentHtmlTemplater.getCssPaths(ThemeDependentHtmlTemplater.java:53)
```

**Comment by bradmac** [comment]
Should be fixed now
