### ISSUE TITLE
Duplicate profile being created by journey

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4103]
I send this email manually http://moblix.admin.kademi-ci.co/groupEmails/307160/#sendInfo-tab

Which starts this journey http://moblix.admin.kademi-ci.co/funnels/registration/version1/#journeyBuilder-tab

When the user is approved, Kademi creates a 2nd profile using the same email address, see test2@kademi.co

Is this expected? From memory we don't allow duplicate profiles?

**Comment by bradmac** [comment]
Should be fixed now
