### ISSUE TITLE
Pending registration email not firing

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4104]
This journey http://moblix.admin.kademi-ci.co/funnels/registration/version1/#journeyBuilder-tab

When a group goal is used, and the pending node output is linked to an email, should this fire when the user submits the registration form but is pending?

![image](https://user-images.githubusercontent.com/2201340/31313928-877208ee-ac3d-11e7-8728-0d297cad3f5c.png)

**Comment by bradmac** [comment]
hey @paddyow this isnt really a valid journey. Only one outcome from the goal will be taken. If you want emails to be sent on the 3 outcomes you need to have them all linked up.

**Comment by bradmac** [comment]
note that all 4 journies proceeded past accept, they did not wait for pending:

![image](https://user-images.githubusercontent.com/826458/31322265-0c3db65a-acf1-11e7-84dc-0dbdd70c12b5.png)

**Comment by bradmac** [comment]
can you please reproduce the problem, and then leave the journey so we can see it?

**Comment by bradmac** [comment]
@paddyow this was probably fixed in #4103 

can you check if still active?
