### ISSUE TITLE
In pop-up, when I leave the primary fields blank it closes the pop-up

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#4107]
In this page : http://alaa-test4.admin.kademi-ci.co/translations/
When I try to add new translation and leave the "Translated" feild blank , and submit it closes the pop-up
and doesn't add any translation

And when I open pop-up again , it shows me the error that "Please enter all required fields"

![capture1](https://user-images.githubusercontent.com/26510030/31315898-95ed0db4-ac2a-11e7-919e-9faceb43ea89.PNG)

**Comment by gonzalon** [comment]
Duplicated https://github.com/Kademi/kademi-dev/issues/4045
