### ISSUE TITLE
Menu not clicking through to parent menu item

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4109]
Templates http://moblix.admin.kademi-ci.co/pages/moblix-channel/version1/

Note I created custom nav items with sub menu items
![image](https://user-images.githubusercontent.com/2201340/31322715-ce5986fa-ace8-11e7-8b41-71cbda5e1a1b.png)

This user http://moblix.admin.kademi-ci.co/manageUsers/152956/#summary-tab

Click through to here http://moblix-channel.kademi-ci.co/moblix-channel-store/

Then click on sales claim and note the URL http://moblix-channel.kademi-ci.co/moblix-channel-store/sales-claims.html

It's not going to the parent menu item.

What should the nav URL be?  Should an nav link work from the root upwards?

![image](https://user-images.githubusercontent.com/2201340/31322738-2ecaf4f6-ace9-11e7-8032-b6b59711b922.png)

**Comment by bradmac** [comment]
Dont use relative paths in menus, because that relative path will only be correct from certain urls

Instead just use the full path, eg 
```
/moblix-channel-store/sales-claims.html
```
