### ISSUE TITLE
grant rewards action enhancements

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4110]
Currently the grant rewards action only supports a hard coded value:
![image](https://user-images.githubusercontent.com/826458/31323588-3f9a002a-ad06-11e7-814a-0fb7bd4d9de2.png)

Please update the settings to support:
- a points expression (numPointsMvel). Note that the user should only be able to select points OR a points expression
- a "reason" field, which is plain text

**Comment by anhnt** [comment]
done

**Comment by AlaaKhalaf94** [comment]
Hi @anhnt , Here when I put this mvel expression **@{formatter.toInteger("520.33")}** and save , then I open the setting of node again , and I see the mvel become like this **@{formatter.toInteger("**

http://alaa-test23.admin.kademi-ci.co/funnels/grantrewards/version1/#journeyBuilder-tab

![capture1](https://user-images.githubusercontent.com/26510030/32326268-eba39872-bfda-11e7-91d4-c4090932fded.PNG)

**Comment by bradmac** [comment]
@anhnt can you please check that we're html encoding the expression, we definitely need to support syntax like this

But @AlaaKhalaf94 is there any reason for using that expression? you could just use plain text for 520.33

**Comment by anhnt** [comment]
fixed

**Comment by AlaaKhalaf94** [comment]
@bradmac , about using this mvel expression @{formatter.toInteger("520.33")} , I asked Anh to give me a mvel expression to use , and he gave me it

@anhnt , here : http://alaa-test27.admin.kademi-ci.co/funnels/journey1/version1/#journeyBuilder-tab I make three tests with :
- @{formatter.toInteger("520.33")}
- @{formatter.toInteger('520.33')}
- 330
but doesn't work with me , it doesn't convert any points

I test with these users : 
- http://alaa-test27.admin.kademi-ci.co/manageUsers/1677265/#pointsBucketTab-tab
- http://alaa-test27.admin.kademi-ci.co/manageUsers/1675264/#pointsBucketTab-tab
- http://alaa-test27.admin.kademi-ci.co/manageUsers/1675351/#pointsBucketTab-tab

What is wrong with me ?

**Comment by bradmac** [comment]
When i execute the journey i see this in the log:
```
09:33:38 INFO  com.fuselms.apps.funnels.FunnelManager  - nodeTransition: Entering node ID=grantRewards-4ecd8a, Title=null class=class com.fuselms.apps.funnels.GrantRewardsGoalAction
09:33:38 WARN  com.fuselms.apps.funnels.GrantRewardsGoalAction  - Not awarding points, num points is null
```

Note the last line, "Not awarding points"

**Comment by bradmac** [comment]
The problem was because we simple werent handling points expressions, only fixed points.

I've added code to evaluate the expression now

**Comment by anhnt** [comment]
i just test and noticed that we dont need ```@{ }``` to wrap variables.

Working fine for me with this 

![image](https://user-images.githubusercontent.com/735555/32428451-59181fa2-c2f8-11e7-8a2b-e16eb9667fbe.png)

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/32428656-6d630688-c2f9-11e7-8825-4ec08ca1e770.png)

**Comment by AlaaKhalaf94** [comment]
passed
