### ISSUE TITLE
Saving causes Keditor to add extra containers at the bottom of the page

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4112]
http://moblix.admin.kademi-ci.co/pages/moblix-channel/version1/

Template http://moblix-channel.kademi-ci.co//theme/contenteditor?fileName=defaultThemeTemplate.html&miltonUserUrl=/users/patrick&miltonUserUrlHash=b10233bb-5396-445c-a529-607f329a3455:_ytN3j_PCv6wbVxY2-pxzjvvY4I

Before save
![image](https://user-images.githubusercontent.com/2201340/31323950-47504098-acf9-11e7-86c4-7c7b11544142.png)

After save
![image](https://user-images.githubusercontent.com/2201340/31323958-5b11e06e-acf9-11e7-8c47-221cb88e25f3.png)

This seems to occur on all pages.

**Comment by ducdhm** [comment]
Already fixed!

**Comment by Uafinder** [comment]
Looks ok!
