### ISSUE TITLE
When two or more polls on one page success message bad

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4114]
There are several polls on one page, when first poll is answered all going fine, but when second poll is answered - JS message appears.
![image](https://user-images.githubusercontent.com/1945230/31328696-156fcd24-acdf-11e7-91bb-2891ec69bc7f.png)

http://version1.vlad10-learn.kademi-ci.co/index-1.html?miltonUserUrl=/users/adminqa-mailinator-com&miltonUserUrlHash=37b680f6-7f43-4aa8-999e-69423d7688d8:N6VCCmVPZmarQnje2928vAFmvI4

http://vlad-test10.admin.kademi-ci.co/kpoll/managePolls/

adminqa@mailinator.com

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
Works fine
