### ISSUE TITLE
Blog post layout broken

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4117]
http://moblix.admin.kademi-ci.co/manageUsers/397438/#summary-tab

http://moblix-channel.kademi-ci.co/programs/p1/c1/MB5000/pcamera-lens.html?r=1507538763876

![image](https://user-images.githubusercontent.com/2201340/31330611-dde8817e-ad2a-11e7-9aff-3b11861e6a93.png)

**Comment by ducdhm** [comment]
Fixed!
