### ISSUE TITLE
When you check installed apps from website page it should be filtered by website

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4119]
![image](https://user-images.githubusercontent.com/1945230/31335963-8632d452-acfd-11e7-8e0c-735bca4f4dd6.png)

I've go to manage websites page, then manage website, then find apps, then installed apps tab.
It shows me all apps which installed accross my account, but should display only installed for this website.

http://vlad-test10.admin.kademi-ci.co/marketPlace?websiteBranch=version1&websiteName=vlad10-competition&type=app#purchased-tab

**Comment by bradmac** [comment]
To see what apps you have installed in a website you should use the apps tab on website manager

So instead of filtering installed apps on the app manager, we should just hide the installed tab when there is a website specified.

**Comment by bradmac** [comment]
@gonzalon please add a simple #if condition to not show the installed apps tab when there is a website name param

**Comment by gonzalon** [comment]
Was already fixed:

![image](https://user-images.githubusercontent.com/2773216/32635086-a1138436-c613-11e7-864e-fc7d97617c16.png)

**Comment by Uafinder** [comment]
Yup!
