### ISSUE TITLE
Change photo button inaccessible (does nothing)

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4120]
![image](https://user-images.githubusercontent.com/1945230/31336131-2a80e314-acfe-11e7-9442-d3373d1e7b4c.png)
When i select a simple template with photo, i can't change it with component controls.

http://vlad-test10.admin.kademi-ci.co/rewards/promoqa1/#rewardContent-tab
adminqa@mailinator.com

**Comment by bradmac** [comment]
@ducdhm should we move the editor into an overlay?

**Comment by ducdhm** [comment]
Front-end is done!

@bradmac I used `?goto` for previewing content but all I got is `The host name version1_rootorg.local-store.loopbackdns.com:8080 was not found on this server, or its license is invalid`.

Can you help me take a look at it?

**Comment by bradmac** [comment]
Looks like ?goto isnt correctly integrated with new website name structure

**Comment by tuzzmaniandevil** [comment]
Fixed in https://github.com/Kademi/kademi-dev/issues/4297

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
It works!
