### ISSUE TITLE
Promotion entry accept/reject does not update entry state 

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4121]
![image](https://user-images.githubusercontent.com/1945230/31337627-d74e671e-ad04-11e7-840f-76da7c1982a5.png)

1. Create a promotion which requires approval
2. Create an entry
3. Go to entries page: http://vlad-test10.admin.kademi-ci.co/rewards/entries-promoqa1.html
4. Check either appove or reject for entry
5. It says that it's successfully approved|rejected, but it doesn't disappears from the list.

Deleting promotion entry cause page refresh and raise checkbox on the old position.
![image](https://user-images.githubusercontent.com/1945230/31337960-34261490-ad06-11e7-866c-99d72763b46f.png)
![image](https://user-images.githubusercontent.com/1945230/31337997-564ec99a-ad06-11e7-8710-52f9aa0d9da2.png)

**Comment by tuzzmaniandevil** [comment]
The entry state does get updated, It just wasn't refreshing the page. I've added reload fragment now to the entries. The entry shouldn't disappear from the list, but the status should be updated.

As for the second error, I can't reproduce that

**Comment by Uafinder** [comment]
First fixed
Second:
I wrote a video... it happens when you delete something in two steps...
http://vlad-test12.admin.kademi-ci.co/rewards/entries-promoqa1.html
https://drive.google.com/file/d/0B9V2ZH-h_cR2V1I2Y2l1MVNjQTg/view?usp=sharing

**Comment by tuzzmaniandevil** [comment]
Seemed to be a firefox specific issue.

**Comment by Uafinder** [comment]
Yup, great!
