### ISSUE TITLE
2 sales data claimer app available for install

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4122]
![image](https://user-images.githubusercontent.com/1945230/31338126-cc31d846-ad06-11e7-998c-69e1b85bbbcf.png)
http://vlad-test10.admin.kademi-ci.co/marketPlace?websiteBranch=version1&websiteName=vlad10-competition&type=app#browse-tab

**Comment by bradmac** [comment]
Thats just an issue with the CI environment. Please use  "salesDataClaimer"
