### ISSUE TITLE
The text field appears at the top of the list of organizations

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#4123]
Like this img , the box specified in red is text field

![capture1](https://user-images.githubusercontent.com/26510030/31338206-fb65c348-ad06-11e7-8b20-80d34d521a97.PNG)

Thats happened in group emails in recipients tab when I try to add recipient organisations : http://alaa-test3.admin.kademi-ci.co/groupEmails/421953/#recipients-tab

**Comment by ducdhm** [comment]
Fixed!

**Comment by AlaaKhalaf94** [comment]
passed
