### ISSUE TITLE
Content editor stucks on the blank page

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4124]
When i click edit page, content editor doesn't start.
![image](https://user-images.githubusercontent.com/1945230/31341255-9d2d59ac-ad11-11e7-9987-13e2087e610c.png)
![image](https://user-images.githubusercontent.com/1945230/31341265-a8771a78-ad11-11e7-97f7-db5225a98cd9.png)

http://vlad-test10.admin.kademi-ci.co/pages/vlad10-competition/version1/
http://version1.vlad10-competition.kademi-ci.co/contenteditor?fileName=page6.html&miltonUserUrl=/users/adminqa-mailinator-com&miltonUserUrlHash=eb8470c3-7206-46e2-94be-8e61b8b798c0:f-avvGWsPZjzNl44FXjGaj3H1ZA
adminqa@mailinator.com

**Comment by ducdhm** [comment]
I see `Handler is not defined` in console message.

@bradmac I think we got issue with dependencies.

 1. `Reward and promotion` app is depended on `rewards-lib`
 2. `rewards-lib` is depended on `handlerbars-lib`
 3. When enabling `Reward and promotion` app, `rewards-lib` is enabled but not `handlerbars-lib`

Can you help me investigate it?

**Comment by bradmac** [comment]
Seems to be working now.

I dont think there is an actual problem with enabling dependencies. But if anyone can reproduce a situation where deps arent enabled i'll look into it!

**Comment by Uafinder** [comment]
Looks ok on specified and fresh account... will keep an eye on it
