### ISSUE TITLE
KEditor: Photo/Image Component link regex doesn't support params

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#4126]
Trying to use this link fails:
`https://youtu.be/KdxI79Bgxz8?list=PLNJCZZAkPWxBghPQp3HFDiBrJRbDODwPE`
but this one works:
`https://youtu.be/KdxI79Bgxz8`

**Comment by bradmac** [comment]
@tuzzmaniandevil is talking about validation...

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
It works!
