### ISSUE TITLE
Module template

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4127]
1) Add space in between icon and text
2) Note padding and put all pages in a box
3) The module page only becomes ticked when it has been completed and all completed pages stay ticked to show progress
4) Avatar should be in circle 
5) Remove line

I love how I can move the tool bar around, but doing so it would be good to have options on the tools bar to align the menu items i.e. Align left, right or center

![image](https://user-images.githubusercontent.com/2201340/31360414-04da6788-ad9a-11e7-9b40-19eaca5823d1.png)

**Comment by ducdhm** [comment]
New UI for comments
![comment](https://user-images.githubusercontent.com/1289631/31479243-0e5c8942-af40-11e7-9c2c-a9e95cfb40c5.png)

**Comment by ducdhm** [comment]
New UI for recent posts:
![community_comments_list](https://user-images.githubusercontent.com/1289631/31479254-15c88294-af40-11e7-9268-7c55cd51f836.png)

**Comment by paddyow** [comment]
Padding not correct see below:

![image](https://user-images.githubusercontent.com/2201340/31531056-32b1719a-b030-11e7-88ee-add2d8613fae.png)

**Comment by ducdhm** [comment]
I have updated k-theme and it worked!

**Comment by Uafinder** [comment]
Looks ok for me
