### ISSUE TITLE
Create My Learning Page template

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4128]
Picker needs to be split out.

![image](https://user-images.githubusercontent.com/2201340/31360677-356be808-ad9b-11e7-9314-8bcc0db787f8.png)

**Assign to Vlad for testing**

**Comment by ducdhm** [comment]
New UI:
![newui](https://user-images.githubusercontent.com/1289631/31383303-b9ff61fa-ade4-11e7-9275-4247d607fea5.png)

**Comment by Uafinder** [comment]
http://vlad13-learn.kademi-ci.co//theme/apps/learner/contenteditor?fileName=myLearning.html&miltonUserUrl=/users/vlad-bayrak&miltonUserUrlHash=9b409f2c-6823-4703-886c-69d8e6386d48:Lt_9uKJPlORTlPDUvEu4T6al1_A
http://version1.vlad13-learn.kademi-ci.co/myLearning


1. Course description is not showing
![image](https://user-images.githubusercontent.com/1945230/31427304-7c698dd0-ae6f-11e7-9cb4-d925496e52d1.png)
![image](https://user-images.githubusercontent.com/1945230/31427318-8554c694-ae6f-11e7-8feb-5a6ce7b6b9d6.png)

2. Course selector doesn't show courses into a program.
![image](https://user-images.githubusercontent.com/1945230/31427419-d95bf5b4-ae6f-11e7-965b-c9b12ae64c13.png)
![image](https://user-images.githubusercontent.com/1945230/31427422-de5a450c-ae6f-11e7-90e2-4dd9887628dc.png)

**Comment by ducdhm** [comment]
@Uafinder Can you check permission of user which you're logged-in as

**Comment by Uafinder** [comment]
True, course selector is ok!
But description problem is there.
![image](https://user-images.githubusercontent.com/1945230/31438342-821f4730-ae90-11e7-90c6-3b5b150d130b.png)
![image](https://user-images.githubusercontent.com/1945230/31438361-8d120f60-ae90-11e7-98dc-9891b14b36dd.png)

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
Both No description label and real description text appears in KEditor
![image](https://user-images.githubusercontent.com/1945230/31609813-54db665e-b27e-11e7-8254-d6f08c6ad283.png)
http://version1.vlad17-learn.kademi-ci.co/contenteditor?fileName=test2.html&miltonUserUrl=/users/18f99d7f-b812-4fb0-8ef3-b3dce205fff5&miltonUserUrlHash=811a1bd1-65a5-4b81-ad2c-5b70edfe6754:oKFX1epCkgyh4ltP9POZP0UFTuo

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
Both fixed

**Comment by Uafinder** [comment]
Looks ok!

**Comment by Uafinder** [comment]
When you change course 1 to course 2, it's changing ok, but doesn't change label
![image](https://user-images.githubusercontent.com/1945230/31652209-0eae6272-b327-11e7-951f-8dca5c5b4028.png)
http://version1.vlad17-learn.kademi-ci.co
http://version1.vlad19-learn.kademi-ci.co

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
Items per row parameter is no longer work
![image](https://user-images.githubusercontent.com/1945230/31707293-84c2f7de-b3f4-11e7-9cdd-863b61b9b6f7.png)
![image](https://user-images.githubusercontent.com/1945230/31707316-9f822c8e-b3f4-11e7-970f-63c96c7a270d.png)
http://version1.vlad19-learn.kademi-ci.co/contenteditor?fileName=learn.html&miltonUserUrl=/users/adminqa&miltonUserUrlHash=27dc546a-f735-486f-a443-5fc564f5d7ef:6Jv8Gt8UQm33XD5zCxA7pVY5zG8
http://vlad-test19.admin.kademi-ci.co/pages/vlad19-learn/version1/

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
working  great!
