### ISSUE TITLE
Blog components and templates

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4129]
Create blog components just like learning with adjustments:

![image](https://user-images.githubusercontent.com/2201340/31364281-7091eb12-adaf-11e7-9cdf-86b365d25cbb.png)

Note the blog article page needs a component adding for files.  These are uploaded when creating the blog article itself.

![image](https://user-images.githubusercontent.com/2201340/31364364-fe015230-adaf-11e7-8861-8e6bc2157330.png)

**Comment by ducdhm** [comment]
Done!

**Comment by Uafinder** [comment]
Can't find this components...
![image](https://user-images.githubusercontent.com/1945230/33214152-55f95a90-d133-11e7-83b4-7f66ae369053.png)
http://vlad-test60.admin.kademi-ci.co/pages/vlad60-blog/version1/

**Comment by ducdhm** [comment]
@Uafinder It's the component at top. Very first app. But you need to update libs again, I have updated the component so when there is blog articles, there is a message in contentEditor.

**Comment by Uafinder** [comment]
Works perfectly
