### ISSUE TITLE
Categories not showing in reward store filters

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4130]
User http://moblix.admin.kademi-ci.co/manageUsers/152956/#summary-tab

![image](https://user-images.githubusercontent.com/2201340/31365655-35faf35a-adb8-11e7-892f-0b1a3bdccd9b.png)

Note the product 10-inch 8GB Quad Core Android™ Tablet has a category here http://moblix.admin.kademi-ci.co/categories/256467/#products-tab

**Comment by ducdhm** [comment]
@paddyow Please check @gonzalon comment in related issue
