### ISSUE TITLE
numProducts always is 0 in rewardstore category

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#4132]
https://github.com/Kademi/kademi-dev/issues/4130

Category has 1 product: http://moblix.admin.kademi-ci.co/categories/171992/#products-tab
Preview page: http://moblix-channel.kademi-ci.co/moblix-channel-store/
User: http://moblix.admin.kademi-ci.co/manageUsers/152956/#summary-tab

![image](https://user-images.githubusercontent.com/826458/31410439-160c47b6-ae6b-11e7-874c-6de20c2be7fb.png)

**Comment by bradmac** [comment]
@gonzalon a couple of things to look into here:
1. need to understand why the numProducts method is not working, and fix it
2. but this component shouldnt actually use that. Instead we should be using ES to get an aggregation of available categories

**Comment by gonzalon** [comment]
@ducdhm I just added the product to the reward store and it's showing in the page
![image](https://user-images.githubusercontent.com/2773216/31420027-8b9cb42c-ae9b-11e7-8e99-ed8a9e78c2be.png)

**Comment by bradmac** [comment]
@ducdhm please check if that was the problem

**Comment by ducdhm** [comment]
@gonzalon Yeah, you're right. After adding correct products, categories are displayed correctly.
