### ISSUE TITLE
Kcode plugin not rendering in email client

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4133]
http://kademi.admin.kademi.us/funnels/channel-loyalty-campaign/version1/emailAction-ef856d/#message-tab

*|profile_firstName|* and *|profile_email|* does not render.

![image](https://user-images.githubusercontent.com/2201340/31372491-ac97bc54-ade1-11e7-9828-1248b81b3e30.png)

**Comment by bradmac** [comment]
This is expected because KCode works with the component framework, and this email isnt using components.

But we'll see if its viable to integrate with non-component emails

**Comment by bradmac** [comment]
Hey @paddyow thats because the Kademi website is on the old theme which doesnt support KCode or components.

So you can use the old style templating, and we should get the guys to convert our site to components
