### ISSUE TITLE
Manage orgs page: sort by path doesnt work correctly

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4134]
Eg
http://cca.admin.kademi.com.au/organisations/?q=&searchOrgType=store&sortfield=parentOrgLinks&sortdir=asc

![image](https://user-images.githubusercontent.com/826458/31409856-ca856792-ae69-11e7-983c-eef099bc3369.png)

**Comment by gonzalon** [comment]
@Uafinder I fixed it in the new organisations page /organisations-es
Please re index the orgs before testing!

**Comment by Uafinder** [comment]
Yeap, it works
