### ISSUE TITLE
Email templates

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4135]
We would like the ability to create email templates from normal emails, and the ability to create a normal email from a template.
- user can "Create template" from a normal email. This will create a new GroupEmailJob flagged as a template, which will be a copy of the original email
- when editing an email template, it should be the same as a normal email, except no ability to send or view logs
- the create email modal should have an option to select a template. The selected template will be populated into the new email. This should be all data, eg subject, content, recipients, etc
- also have a new button to create an email template
- the emails list page should have 2 tabs. The first is the normal email job list, the second is for templates.
- please add pagination to the email job list (but not templates)

**Comment by Uafinder** [comment]
1. Pop-up message probably should contain something like "Template is created" or "$templateName is created"
![image](https://user-images.githubusercontent.com/1945230/31488003-0d55da30-af45-11e7-854a-1df46ef22061.png)
http://vlad-test13.admin.kademi-ci.co/groupEmails/

2.

**Comment by tuzzmaniandevil** [comment]
1. Fixed
2. Fixed
3. It will now be "Template - " instead of "Copy of "
4. It won't append the notes now but will copy across any existing notes

**Comment by Uafinder** [comment]
4. The same.
http://vlad-test19.admin.kademi-ci.co/groupEmails/802175/#sendInfo-tab
![image](https://user-images.githubusercontent.com/1945230/31716433-6f547c3a-b410-11e7-8894-4bcfbdda7f76.png)

5. I have a template, which i have no need anymore. I delete it, and then go to emails tab to create email from other correct
![image](https://user-images.githubusercontent.com/1945230/31716834-2b021a9a-b412-11e7-91c6-a6d7a9fb90bb.png)
![image](https://user-images.githubusercontent.com/1945230/31716846-39ed6226-b412-11e7-92aa-b7ea54ecdcbd.png)
![image](https://user-images.githubusercontent.com/1945230/31716897-7a2557c2-b412-11e7-8566-59e2ee2f0ab1.png)
http://vlad-test19.admin.kademi-ci.co/groupEmails/
After refresh it wouldn't be there

**Comment by Uafinder** [comment]
Works great!
