### ISSUE TITLE
Hinda APP switched off, still synced

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4138]
http://moblix.admin.kademi-ci.co/manageApps/#installed-tab

I switched off the Hinda app, deleted all prods and cats.  Next day all the prods and cats were back.

Looks like the app was still running.

![image](https://user-images.githubusercontent.com/2201340/31421294-53a55334-ae92-11e7-920a-1018c7ba935c.png)

**Comment by bradmac** [comment]
The app is currently on. Are you sure you turned it off in this account?

![image](https://user-images.githubusercontent.com/826458/31421393-a559d16c-aea3-11e7-8986-46de6e513d93.png)

**Comment by bradmac** [comment]
@gonzalon has confirmed we're not currently checking.

Please add a check that the app is enabled for the account before running any jobs

**Comment by AlaaKhalaf94** [comment]
passed
