### ISSUE TITLE
Email visual layout bugs

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4139]
![image](https://user-images.githubusercontent.com/1945230/31428433-5dc40956-ae73-11e7-852a-79fcdcdfb4b1.png)
![image](https://user-images.githubusercontent.com/1945230/31428441-642cefec-ae73-11e7-97be-2a3e13d94c70.png)

Included and excluded organisations selector contains minor visual layout bug.
http://vlad-test13.admin.kademi-ci.co/groupEmails

probably this options need to be separated, e.g. Included contains only included, excluded contains only excluded.

**Comment by gonzalon** [comment]
@Uafinder I can't reproduce it :/ tried it in Chrome and Firefox.

**Comment by Uafinder** [comment]
@gonzalon it looks ok to me also... it could be fixed by some other fix...
Anyway, i will keep an eye on it...

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/31720027-0eb973e0-b41e-11e7-9bfb-af285afdb6bd.png)
Found it again
Fresh account
http://vlad-test20.admin.kademi-ci.co/groupEmails/803487
Firefox
adminqa@mailinator.com

**Comment by bradmac** [comment]
Confirmed i can see it too

**Comment by gonzalon** [comment]
Did reproduce it in the fresh account. Fixed.

**Comment by Uafinder** [comment]
Yup, looks ok!
