### ISSUE TITLE
All emails falls into queue state

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4140]
![image](https://user-images.githubusercontent.com/1945230/31438435-c872b294-ae90-11e7-95be-1ac76f96df83.png)
http://vlad-test13.admin.kademi-ci.co/groupEmails
i've create send mail task, run it, but it stucks, i've tried to investigate a problem and looks like QA emails are broken.
i've tried from other account - the same.
Also, email history now is in forever loading...
![image](https://user-images.githubusercontent.com/1945230/31438501-009b938e-ae91-11e7-9e88-171b21f6813c.png)
user: adminqa@mailinator.com

**Comment by tuzzmaniandevil** [comment]
Seems to be fixed now, I think it was related to #4141

**Comment by Uafinder** [comment]
IT looks ok at the moment
