### ISSUE TITLE
Password issue when doing restore backup

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4142]
![image](https://user-images.githubusercontent.com/1945230/31445849-afe0c43e-aea7-11e7-8469-c6bce0a949ca.png)

It's probably appears when password not contain numbers or characters.
http://vlad-test14.admin.kademi-ci.co/backup/

**Comment by bradmac** [comment]
@Uafinder a couple of things
- you only need to use a remote server when transferring content from another platform, so its not needed for going from one CI account to another
- the password you enter must be correct, and all Kademi passwords must at least meet the requirement of 6 chars and container numbers and letters, so this message is valid if the password you entered does not meet that requirement

**Comment by Uafinder** [comment]
Understood, so probably there should be a validation for password complexity ever when you change it from admin console...

**Comment by Uafinder** [comment]
moved to separate issue https://github.com/Kademi/kademi-dev/issues/4152
