### ISSUE TITLE
Reward store product management updates

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4144]
For this page:
![image](https://user-images.githubusercontent.com/826458/31464000-84074fec-af2c-11e7-9fa1-389633c21bd5.png)

- remove margin and multiplier columns
- add column for base cost
- add column for product added to store date (ie created date for ProductInReward)
- allow sorting by code, title, created date, base cost
- use title as default sorting
- update the category filter dropdown to show child categories under their parent

**Comment by Uafinder** [comment]
Works perfect
