### ISSUE TITLE
Reward store: add products enhancements

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4145]
Related: https://github.com/Kademi/kademi-dev/issues/4144

![image](https://user-images.githubusercontent.com/826458/31464339-cb3594e0-af2d-11e7-83af-44e869ecd773.png)

For the add products page, please make the following enhancements
- remove margin and multiplier cols
- add column for product created date
- add column for base cost
- allow sorting by cols code, title, created date, base cost

**Comment by Uafinder** [comment]
1. Created date is not showing when product is on adding page
![image](https://user-images.githubusercontent.com/1945230/31484978-f402b72e-af3a-11e7-9c6c-cbb75fb832ea.png)
http://vlad-test13.admin.kademi-ci.co/reward-store/vlad13-points-store/

**Comment by tuzzmaniandevil** [comment]
@Uafinder Note the created date on products is a new field so it won't show for existing products only new products.

**Comment by tuzzmaniandevil** [comment]
![image](https://user-images.githubusercontent.com/3378330/31521852-9f265544-b007-11e7-898f-914f4ad9f327.png)

**Comment by Uafinder** [comment]
Yup, understand... It works at the moment
