### ISSUE TITLE
Keditor adding a extra class 

### ISSUE THREAD

**Issue by gonzalon** [Kademi/kademi-dev#4147]
If you save it, the layout change from boxed to fluid. I saw it was adding an extra class to a section. I "hacked" it to add the buttons, but we needs to be able to edit as usual.

URL:
http://milestoneevents.global//theme/apps/blogs/contenteditor?fileName=viewBlogArticle.html&miltonUserUrl=/users/celine-gilpin&miltonUserUrlHash=97fe581c-dfaf-4b28-907d-f51cd9a86f59:HUPu8orrYu-7Eo0QaVJfQrpf9Bw

The layout should be like this:
![image](https://user-images.githubusercontent.com/2773216/31466389-7c782bf0-af33-11e7-823f-c8a87ad5d495.png)

**Comment by bradmac** [comment]
@ducdhm please investigate today

**Comment by ducdhm** [comment]
As I checked as Text Editor, code for container of this page is
```
<section class="container">
    <div class="container-bg bgWhite paddingBottomLarge blogArticle">
        <div class="container-content-wrapper" style="">
```

but our standard container structure is
```
<section>
    <div class="container-bg background-for">
        <div class="container-layout container">
            <div class="container-content-wrapper">
```

And if you dont have `div.container-layout`, contentEditor will correct it for you by adding it after `div.container-bg`.

And seem like you set box layout in wrong way. `container` should be added in `div.container-bg` instead of `section` tag

**Comment by ducdhm** [comment]
@Uafinder Can you test with provided link at top comment?

**Comment by Uafinder** [comment]
@ducdhm 
Hand needed... could you provide me short descr - what should be tested. In two words...

**Comment by ducdhm** [comment]
@Uafinder For simplest description: It's bug of container and sub container. When you change layout of container, layout of sub container will be change to the same.

**Comment by Uafinder** [comment]
so, it's expected to have layout inheritance to the child container?

**Comment by bradmac** [comment]
hey @Uafinder i think test the following:
- create a page in keditor
- add a container, eg 2 cols
- add a container inside that container, eg 3 col container in left parent col
- make changes to the parent container, eg background colour, padding etc
- verify that the changes only apply to the parent, and do not apply to the child container

**Comment by Uafinder** [comment]
Layout and dock type parameters are inherited from the parent. E.g. if I change this ones in parent it will drill down to the child containers.
http://vlad-test62.admin.kademi-ci.co/pages/vlad62-learn/version1/?contenteditor=page1.html

**Comment by ducdhm** [comment]
@Uafinder Can you double check again? I think it's working normally. Chat with me when you test this issue. I'll help you ;)

**Comment by Uafinder** [comment]
@ducdhm Yeah, it looks normally. I was confused that for changing container you should click on it and required thing is to click change gear icon. I thought that when properties of one container is open, you shouldn't push change gear icon again...
