### ISSUE TITLE
Removing selected product cause incorrect pop-up tip

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4150]
![image](https://user-images.githubusercontent.com/1945230/31485834-e6fe32da-af3d-11e7-827f-c6cfab6aa5d7.png)
1. Select product from the list
2. Push remove selected
3. Watch "adding selected" pop-up
http://vlad-test13.admin.kademi-ci.co/reward-store/vlad13-points-store/#products-tab

**Comment by salehh93** [comment]
done

**Comment by Uafinder** [comment]
Looks great!
