### ISSUE TITLE
FIrefox Issue when you delete an element from list and after page refreshes checkbox appears on the position where deleted element was placed

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4151]
It's a specific Firefox issue.
Faced it here:
https://github.com/Kademi/kademi-dev/issues/4121
Then I faced it on the reward store manage products page...
![image](https://user-images.githubusercontent.com/1945230/31486650-d65af5dc-af40-11e7-963a-821cc517a7ef.png)
![image](https://user-images.githubusercontent.com/1945230/31486662-e066275e-af40-11e7-969a-8e5b187ab604.png)
http://vlad-test13.admin.kademi-ci.co/reward-store/vlad13-points-store/#products-tab

I will add newly spotted places where this bug appears here...

**Comment by bradmac** [comment]
We should add this:

```
autocomplete="off"
```

https://stackoverflow.com/questions/299811/why-does-the-checkbox-stay-checked-when-reloading-the-page

**Comment by tuzzmaniandevil** [comment]
@bradmac Yup thats how I fixed the other page

**Comment by tuzzmaniandevil** [comment]
Done, Also added to the checkbox method on Formatter

**Comment by Uafinder** [comment]
Yup, fixed

**Comment by Uafinder** [comment]
Same bug when adding products to reward store
![image](https://user-images.githubusercontent.com/1945230/31597850-5ebb1fc8-b253-11e7-89a0-f1c50c14f30f.png)
![image](https://user-images.githubusercontent.com/1945230/31597876-79491502-b253-11e7-8645-3ed8c7389eee.png)
And as a result
![image](https://user-images.githubusercontent.com/1945230/31597889-8723751e-b253-11e7-852f-c5957be46b02.png)

**Comment by Uafinder** [comment]
Yup, it works ok. To be continued
