### ISSUE TITLE
Should be no possibility to enter simple password which not satisfies basic password complexity

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4152]
Now it can be overrun by entering password via admin console on manage user page.
There is no validation there.

http://vlad-test13.admin.kademi-ci.co/manageUsers/620497/#general-tab

It's moved from https://github.com/Kademi/kademi-dev/issues/4142

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/32818648-0db92afa-c9f7-11e7-9d2b-f04223df16dd.png)

**Comment by anhnt** [comment]
Fixed

**Comment by Uafinder** [comment]
Yup, it works!
