### ISSUE TITLE
Manage products in reward store details page opens like new page not modal

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4153]
1. go to the page http://vlad-test13.admin.kademi-ci.co/reward-store/vlad13-points-store
2. select any category which contains products
3. push product details button (gear)
![image](https://user-images.githubusercontent.com/1945230/31494570-82b9d684-af5c-11e7-838b-88301d23dbcd.png)
4. Special page for specified product appears... It's not a quite theme compliant.
When you push save, no success message appears.
5. Click back button in browser
![image](https://user-images.githubusercontent.com/1945230/31494654-fc75cab4-af5c-11e7-83f9-7bb80e133dde.png)
6. Then click gear icon again and pop-up window appear successfully.
![image](https://user-images.githubusercontent.com/1945230/31494674-13c6c1f0-af5d-11e7-8099-ad656b623015.png)

**Comment by bradmac** [comment]
@tuzzmaniandevil please make sure we're using $().on("click") to open the modal

**Comment by Uafinder** [comment]
Fixed
