### ISSUE TITLE
not appear photo if open from email

### ISSUE THREAD

**Issue by salehh93** [Kademi/kademi-dev#4154]
in email template
if I add photo from k-editor not appear in email 
![template](https://user-images.githubusercontent.com/23012214/31496434-f358eb44-af63-11e7-970c-c25142b63f36.jpg)

![im3](https://user-images.githubusercontent.com/23012214/31496436-f45025e4-af63-11e7-8285-e7291b051b9b.jpg)

I think because internal link  
src="/_hashes/files/8a889188f937d0e24ff6beef1936d615c3346b81" 

can you check here 
http://travelworld.admin.kademi.com.au/groupEmails/81018595/edmeditor?fileName=index.html&useHash=true

from any user and send test email

**Comment by bradmac** [comment]
@ducdhm please investigate urgently. Definitely needed for travelworld and all clients who use emails!

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
The same...
![image](https://user-images.githubusercontent.com/1945230/31720381-2138e004-b41f-11e7-994c-2b6a34a20117.png)
![image](https://user-images.githubusercontent.com/1945230/31720457-5249dfcc-b41f-11e7-8a08-004d2a358078.png)
![image](https://user-images.githubusercontent.com/1945230/31720485-6125c3f8-b41f-11e7-9f59-127e99a6a3ae.png)

**Comment by bradmac** [comment]
hey @Uafinder, the original issue reported was with KEditor. But i think your example was created with the rich text editor

If KEditor works correctly please close this issue. If there is a problem with the rich text editor then create a new issue.

**Comment by Uafinder** [comment]
Understood, will do...
It works, but doesn't restrict for resolution limitation
![image](https://user-images.githubusercontent.com/1945230/31766307-df160006-b4cf-11e7-9a54-c127b6cd2ffa.png)
In the editor
![image](https://user-images.githubusercontent.com/1945230/31766347-f89d8b7a-b4cf-11e7-9b8a-58ea61161db6.png)
![image](https://user-images.githubusercontent.com/1945230/31766363-04b04e8e-b4d0-11e7-9247-786326fcd13d.png)
http://vlad-test20.admin.kademi-ci.co/groupEmails/854540/#messages-tab

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
It works!
