### ISSUE TITLE
Web hits report, detailed items seems incorrect

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4157]
See this as an example - http://airnz.admin.kademi.com.au/reporting/esWebsiteAccess?startDate=13%2F07%2F2017&finishDate=13%2F10%2F2017&term-website=37119321

- the CSV export should include all URLs, not just top 10 (the report page should just be top 10 though)
- for some reason hits to category pages dont seem to be included, eg http://www.airnewzealandelitegift.co.nz/reward1/Category-Dine/ - please check the query

**Comment by AlaaKhalaf94** [comment]
Hi @gonzalon , here : http://alaa4.admin.kademi-ci.co/reporting/esWebsiteAccess?startDate=11%2F10%2F2017&finishDate=17%2F10%2F2017&term-website=

The sum of the numbers in the table does not equal the number in the chart
In chart 96
In the table, the sum of the digits is 93

![capture1](https://user-images.githubusercontent.com/26510030/31650755-76e7d9d2-b321-11e7-9019-c765332056ba.PNG)

**Comment by bradmac** [comment]
Hi @AlaaKhalaf94 the table is only listing the top 10 urls. Its likely there are a few urls not shown which account for the difference.

**Comment by AlaaKhalaf94** [comment]
passed
