### ISSUE TITLE
The calendar is not selecting/ not working in the embargo date selector (blogs)

### ISSUE THREAD

**Issue by Anton69arb** [Kademi/kademi-dev#4158]
Hey, The calendar is not selecting/ not working in the embargo date selector (blogs) can wee get it setup and test, thank you :)

![the calendar is not selecting_not working in the embargo date selector](https://user-images.githubusercontent.com/32444328/31529356-4af803c2-b035-11e7-811d-85510f376871.png)

http://antontest.admin.kademi-ci.co/blogs/sweets-for-heavens%2012/orange-cream-soda-pop-cupcakes/#activity-tab

**Comment by salehh93** [comment]
done

**Comment by AlaaKhalaf94** [comment]
Its work well with me , but the calendar pop up appears above the text field
I test here : http://alaa5.admin.kademi-ci.co/blogs/blog01/blog01/#activity-tab

![capture2](https://user-images.githubusercontent.com/26510030/31664818-97e41456-b34f-11e7-9863-ef29ac79bac7.PNG)

**Comment by salehh93** [comment]
done

**Comment by AlaaKhalaf94** [comment]
passed

**Comment by ducdhm** [comment]
@AlaaKhalaf94 Did you check this issue with different timezone? I'm 100% sure @salehh93 changes doesnt work wit timezone

**Comment by bradmac** [comment]
Please test with changing the timezone on the org edit page:
![image](https://user-images.githubusercontent.com/826458/31966959-dcfc28e8-b968-11e7-8035-2398bf741e48.png)

**Comment by salehh93** [comment]
can you test now please

**Comment by AlaaKhalaf94** [comment]
passed
