### ISSUE TITLE
Lead page: Completing a task will automatically create new task

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#4159]
Also in timeline it says there's new task created

![image](https://user-images.githubusercontent.com/735555/31529346-ddc3f6a8-b002-11e7-9ea5-29e885690eb4.png)

**Comment by anhnt** [comment]
I see the problem: When completing a task, dueDate field is automatically set to be next 7 days. So that will create new task.

![image](https://user-images.githubusercontent.com/735555/31531619-4f717744-b012-11e7-9f14-6169f7bf5d04.png)


@bradmac @paddyow should that field be empty by default unless user selects a date?

**Comment by paddyow** [comment]
Add watermark to field 'Select a date' so aligns with the other fields which have one.

**Comment by anhnt** [comment]
Fixed

**Comment by Uafinder** [comment]
It looks good.
