### ISSUE TITLE
Table Uploader not showing errors correctly

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4160]
I have a file where I setup next import settings:
![image](https://user-images.githubusercontent.com/1945230/31538232-8c8c138c-b00d-11e7-971c-bd30e8f3178c.png)
But when I go further it looks that some columns are not properly counted, I mean shift to the right...
![image](https://user-images.githubusercontent.com/1945230/31538327-de1f50a6-b00d-11e7-961a-8d19e322c59c.png)
http://vlad-test16.admin.kademi-ci.co
fresh account

**Comment by Uafinder** [comment]
The same thing with products, so probably an importer common bug
![image](https://user-images.githubusercontent.com/1945230/31540091-4a17acae-b013-11e7-9799-ecf198088938.png)
![image](https://user-images.githubusercontent.com/1945230/31540146-7c1841d2-b013-11e7-9a53-ef2f23f3dab8.png)

**Comment by Uafinder** [comment]
Still the same thing!
![image](https://user-images.githubusercontent.com/1945230/31598423-3dab1c86-b256-11e7-8e3b-c31111bb69c7.png)
fresh account
http://vlad-test17.admin.kademi-ci.co/tableUploaders

**Comment by tuzzmaniandevil** [comment]
Done, But will still show "Column not imported" if the column wasn't selected in the previous row

**Comment by Uafinder** [comment]
looks ok
