### ISSUE TITLE
Leads minor visual bug

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4161]
Checkbox to select lead are not in place.
![image](https://user-images.githubusercontent.com/1945230/31546433-f8c999a2-b02b-11e7-89c0-c1bb06fe5c13.png)

**Comment by anhnt** [comment]
it looks good at the moment

![image](https://user-images.githubusercontent.com/735555/33820937-72bf221e-de84-11e7-9749-79533064bca2.png)

**Comment by Uafinder** [comment]
looks great!
