### ISSUE TITLE
Lead page: cancelling task cause completing task record appears

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4162]
![image](https://user-images.githubusercontent.com/1945230/31546568-8576f426-b02c-11e7-9e33-98f00791e932.png)
http://vlad16-leads.kademi-ci.co/leads/672957/
1. Create a task
2. Cancel it
3. Watch incorrect timeline record.

**Comment by gonzalon** [comment]
Now you should see:

![image](https://user-images.githubusercontent.com/2773216/31589754-4f45338e-b263-11e7-89a9-41d3ec7902fb.png)

**Comment by Uafinder** [comment]
it works!
