### ISSUE TITLE
KPI sales component

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4163]
1) Remove the background color so it's transparent (color will be applied to the container)
2) Make text and icon black as standard (user can invert container if required to make text white)
3) Make the component elements fill the container (user can add padding to the container)
4) **Note the component does not resize inside the container (it overflows), see below**
5) Colors:
   - 2016 circle Primary
   - 2017 circle Info
   - Not on track Warning
   - On track Success 
6) Make the circles slightly thicker

![image](https://user-images.githubusercontent.com/2201340/31580097-ee70e0ca-b191-11e7-84e5-e7ed21a6ea21.png)

What needs to be done...

![image](https://user-images.githubusercontent.com/2201340/31580089-b3d649b4-b191-11e7-996f-5f6edaf7e320.png)

The title will be added using a text component.

I also need a single KPI doing as well, and note the component like the KPI sales component overflows and does not resize to the container.

![image](https://user-images.githubusercontent.com/2201340/31582327-268dbd4a-b1cc-11e7-9bd7-5f6791d42b60.png)

**Comment by ducdhm** [comment]
Done!

**Comment by paddyow** [comment]
User http://moblix.admin.kademi-ci.co/manageUsers/762030/#summary-tab

When the page first loads the Growth KPI circle does not update to show the current status so looks like this:

![image](https://user-images.githubusercontent.com/2201340/31648767-42ae1d18-b35b-11e7-9114-58c3fdf5818d.png)

When you then select the same period from the period picker, the circle updates.
![image](https://user-images.githubusercontent.com/2201340/31648780-56e4daf6-b35b-11e7-8c04-0a09fea7c5dc.png)

**Comment by ducdhm** [comment]
@paddyow As default, when no cookie/history for selected period, we'll select current period. And I have checked with current period, Growth KPI is Off track with 0% in-progress

**Comment by bradmac** [comment]
Issue is that when no date range has been selected we default to a range of -7 days to now.

Somehow we want it to default to the current KPI period, which is the end date of the last assessed period until that plus the KPI interval.

**Comment by bradmac** [comment]
hey @ducdhm here's how i think we handle this

- the kpiPeriodPicker holds its own cookie, selectedKpiPeriodId
- when a period is selected, set this cookie and also set the common date range params
- when this component displays and there is no selectedKpiPeriodId, set the period id to some special value (eg "current") and set the common date range to the current period range, and reload the page

**Comment by ducdhm** [comment]
Done!

**Comment by Uafinder** [comment]
It shows current KPI period at the moment, so it's ok
I've a question
Why in admin console KPI showed as reached, but in the frontend - not?
![image](https://user-images.githubusercontent.com/1945230/32444045-e41a11ee-c309-11e7-8be4-98556421c356.png)
![image](https://user-images.githubusercontent.com/1945230/32444057-eecfae1e-c309-11e7-87d0-ff6b845dfb33.png)

**Comment by bradmac** [comment]
@ducdhm can you check please?

**Comment by ducdhm** [comment]
@Uafinder Can you double-check again?

I have checked with http://moblix.admin.kademi-ci.co/manageUsers/762030/#summary-tab and here is what I got in frontend:
![ui](https://user-images.githubusercontent.com/1289631/32482032-89afa2ea-c3c8-11e7-993a-cb115b744ce3.png)

**Comment by Uafinder** [comment]
weird thing... it was there yesterday... :(
will keep an eye on it
