### ISSUE TITLE
KPI visualization report

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4164]
1) On the current component the padding is not even around the graph, the RHS has extra padding
2) Have an option in the component to remove the title, outer border and vertical grey lines.  Also make sure when these items are removed the component resizes to fill the container so the admin can apply padding to the container
2b) Make sure the text inverts if the container is inverted
3) Either (1) make sure the histogram uses the brand theme colors or (2) give options to choose colors 
4) The end result 

![image](https://user-images.githubusercontent.com/2201340/31580153-6ef9fe74-b193-11e7-979c-5b0b5b6d340a.png)

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/31625874-de766b40-b2d1-11e7-965c-a819502ec2e2.png)

![image](https://user-images.githubusercontent.com/735555/31625896-eb7fbbfc-b2d1-11e7-9cee-a0c62cda64a1.png)


Done

**Comment by paddyow** [comment]
Remove link from title as it goes to a TODO page
![image](https://user-images.githubusercontent.com/2201340/31639963-5cead678-b327-11e7-82fd-a68a062493dc.png)

SKU http://moblix.admin.kademi-ci.co/products/676331/#panel_details-tab

Sales data has SKU codes http://moblix.admin.kademi-ci.co/sales/sales-data-2016-and-2017/#history-tab

Please also add table height and Table title field to the component.

**Comment by anhnt** [comment]
done

**Comment by Uafinder** [comment]
ok, please check this one
http://vladtest06.admin.kademi-ci.co/pages/vlad06data/version1/
http://vladtest06.admin.kademi-ci.co/pages/vlad06data/version1/?contenteditor=rep3.html
it show no data at all...
![image](https://user-images.githubusercontent.com/1945230/34034902-02fcc640-e189-11e7-9480-10de78696f86.png)
however it shows here

**Comment by anhnt** [comment]
Please login as Sales data group user so it will work

http://vladtest06.admin.kademi-ci.co/manageUsers/3353745/#summary-tab

**Comment by Uafinder** [comment]
Inverted check box does nothing
![image](https://user-images.githubusercontent.com/1945230/34097315-66a7b11e-e3e1-11e7-9b45-707f53816401.png)
![image](https://user-images.githubusercontent.com/1945230/34097321-6db389ec-e3e1-11e7-8e77-eaa5ea244285.png)

**Comment by anhnt** [comment]
Inverted means text color is inverted. see sample here

![image](https://user-images.githubusercontent.com/735555/31625874-de766b40-b2d1-11e7-965c-a819502ec2e2.png)

**Comment by Uafinder** [comment]
Inverted off
![image](https://user-images.githubusercontent.com/1945230/34104821-ae1ae264-e3fa-11e7-9734-58fc2447a46e.png)

Inverted on
![image](https://user-images.githubusercontent.com/1945230/34104852-d26db812-e3fa-11e7-9726-7a2b7963f230.png)

So, no changes
http://vladtest06.admin.kademi-ci.co/pages/vlad06data/version1/

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/34201018-d5b35cc0-e57b-11e7-8f3f-95e9ca1813b5.png)
looks ok!
