### ISSUE TITLE
Sales APP reporting components - no data showing

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4165]
This user http://moblix.admin.kademi-ci.co/manageUsers/240803/#summary-tab

This page http://moblix-reporting.kademi-ci.co/sales.html

We have a data series with KPI and sales data linked to SKUs http://moblix.admin.kademi-ci.co/sales/sales-data-2016-and-2017/#general-tab

![image](https://user-images.githubusercontent.com/2201340/31581623-e7336646-b1bb-11e7-82cf-2dd58c99e405.png)

**Comment by anhnt** [comment]
@bradmac kpi api returns data with zero. Can you please have a look
Here is data for Growth KPI graph

http://jsoneditoronline.org/?id=04de1f2dc7e8102b59a27a8f2c0a54fe

**Comment by bradmac** [comment]
ok, will take a look tomorrow

**Comment by bradmac** [comment]
http://moblix-reporting.kademi-ci.co/sales/sales-data-2016-and-2017/growth-kpi?startDate=&endDate=&interval=day&dateHistogram

**Comment by bradmac** [comment]
hey @anhnt and @paddyow, that is returning data for a KPI. But the user is not a participant in that KPI, so doesnt see any data.

KPI's are not intended to be aggregated. And its not possible to do that, for example a KPI which is an average of data, its not valid to average averages.

I think what you want here for a reporting user is just a histogram of the sales data series, not a KPI.
