### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4166]
Need to update the badge component.

Options:
A) List all badges or choose how many from 1+
B) When 1 badge is displayed always show the most recently awarded badge
C) Show/hide badge title
D) Choose how many badges per row
E) Ensure there is comfortable padding in between badges
F) Ensure there is no padding around the outside of the component so the admin can apply padding to the container

1) Show a list of badges in a row
2) Shows just 1 badge on the dashbaord
3) Shows badges in rows of 4

![image](https://user-images.githubusercontent.com/2201340/31582553-7b621e14-b1d2-11e7-803f-fb65fe0bf609.png)

**Comment by ducdhm** [comment]
as discussed with @bradmac 

```
A) List all badges or choose how many from 1+
```
At the moment, we'll skip this option

**Comment by ducdhm** [comment]
Done!

**Comment by paddyow** [comment]
Change badges per page to badges per row

![image](https://user-images.githubusercontent.com/2201340/31926679-ced037d8-b8db-11e7-9a9b-36f3c81dcae3.png)

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
Where this component located? Which app should be enabled to work with?

**Comment by bradmac** [comment]
This is part of KRecognition

**Comment by Uafinder** [comment]
Need a hand:
I have a such topic for recognition:
http://vlad-test56.admin.kademi-ci.co/recognition/2050641/
I've setup some test data and process some levels and generate awards to users based on levels
It's successfully count awards, but when I go to user page there no awards there:
http://vlad-test56.admin.kademi-ci.co/manageUsers/2048814/#summary-tab
And as a result it doesn't show any badges and levels on the frontend
http://version1.vlad56-recog_vlad-test56.kademi-ci.co/123.html

**Comment by bradmac** [comment]
hey @Uafinder can you please talk directly to Paddy for any information you need?

**Comment by Uafinder** [comment]
There is no padding between badges rows
![image](https://user-images.githubusercontent.com/1945230/34948544-2857f900-fa16-11e7-85ed-7923f5a27cd3.png)
Should be comfortable
http://version1.vlad22sales-vladtest22.kademi-ci.co/page2.html
https://vladtest22.admin.kademi-ci.co

**Comment by ducdhm** [comment]
@anhnt Need add padding/margin bottom for badge.

**Comment by anhnt** [comment]
Done

**Comment by Uafinder** [comment]
yup, it works like a charm!
