### ISSUE TITLE
create a new page on your website when you in a folder - not allowing to view or links working

### ISSUE THREAD

**Issue by Anton69arb** [Kademi/kademi-dev#4167]
when you in a folder on your website and you create a new page, The template page is not allowing us to use any of the previous template pages - this does not allow us to view our page and letting them work - you can edit but not view live :) even when linking pages.

![the template page is not allowing us to use any of the previous template pages - this does not allow us to view our page and letting them work - you can edit but not view live](https://user-images.githubusercontent.com/32444328/31589579-9435eb44-b260-11e7-8fa2-95891607603e.png)

![when you in the file manager place to find the problem](https://user-images.githubusercontent.com/32444328/31589577-90c06570-b260-11e7-9360-3083639d9373.png)

http://kademi.admin.kademi.us/pages/kademi-dev/v4-ktheme/Getting%20started/

**Comment by Anton69arb** [comment]
In the properties menu, sorry forgot to mention that

**Comment by bradmac** [comment]
@Anton69arb please check after next deploy if there is still an issue

**Comment by Anton69arb** [comment]
thank you, works and is running to spec :)
