### ISSUE TITLE
can only edit names for folders in the file manager and not on the tab menus

### ISSUE THREAD

**Issue by Anton69arb** [Kademi/kademi-dev#4169]
can only edit names for folders in the file manager and not on the tab menus -tab menu has delete only, 
if we could put a properties menu there to edit the folder.

http://kademi.admin.kademi.us/pages/kademi-dev/v4-ktheme/

![can only edit names for folders in the file manager and not on the tab menus](https://user-images.githubusercontent.com/32444328/31589757-5b385e00-b263-11e7-9ebe-29dd75143171.png)

**Comment by anhnt** [comment]
added rename button

![image](https://user-images.githubusercontent.com/735555/31752716-91cc16c8-b4b6-11e7-8635-dd7e06808db3.png)

![image](https://user-images.githubusercontent.com/735555/31752731-a3501548-b4b6-11e7-86d1-76b1f65f7f96.png)

**Comment by AlaaKhalaf94** [comment]
passed
