### ISSUE TITLE
Allow upgrade specific app when it has settings

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#4171]
For example salesDataClaimer app, there's no way to upgrade it 

![image](https://user-images.githubusercontent.com/735555/31593302-09ea4c9e-b258-11e7-9264-3d26690b042e.png)

**Comment by tuzzmaniandevil** [comment]
The version option will always show now for custom apps. Not that any apps that have manually added the `version` selector will need to be updated

**Comment by AlaaKhalaf94** [comment]
checked
