### ISSUE TITLE
Points importer creates points records with zero points

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4172]
Points and debit records should only be created if the value is not zero

Currently it creates zero point records. This is especially problematic when using multiple columns for different tags

Example import config:
![image](https://user-images.githubusercontent.com/826458/31593907-0636f21a-b28e-11e7-8199-538b2808d355.png)

Showing zero records:
![image](https://user-images.githubusercontent.com/826458/31593878-dbc17122-b28d-11e7-9ffb-e1316392a868.png)

**Comment by AlaaKhalaf94** [comment]
passed
