### ISSUE TITLE
Lead company saving in lead profile causing an error

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4173]
![image](https://user-images.githubusercontent.com/1945230/31598879-b8874ca2-b258-11e7-8f9a-3a55eadf77ed.png)
1. Open lead
2. Go to the company block
3. If company does not exist - feel free to create one, if it is already, just push save details.
4. Error appears, no changes made.
http://vlad17-lead.kademi-ci.co/leads/722439/
http://vlad-test17.admin.kademi-ci.co/websites/

**Comment by Uafinder** [comment]
Looks ok at the moment

**Comment by Uafinder** [comment]
Same error on leads company page
![image](https://user-images.githubusercontent.com/1945230/32163484-1acbea78-bd65-11e7-82b1-c4617fb15b3a.png)
http://vlad25-leads.kademi-ci.co/companies/1195947

**Comment by tuzzmaniandevil** [comment]
Applied same fix

**Comment by Uafinder** [comment]
It's ok at the moment
