### ISSUE TITLE
Lead profile unlink from company caused incorrect pop-up 

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4174]
![image](https://user-images.githubusercontent.com/1945230/31599117-ac31d430-b259-11e7-935e-09b5ebf4f36e.png)
![image](https://user-images.githubusercontent.com/1945230/31599134-b8529ea2-b259-11e7-9ea3-4bfd130ccb95.png)
Pushing unlink caused pop-up Company details is saved
http://vlad17-lead.kademi-ci.co/leads/722439/
http://vlad-test17.admin.kademi-ci.co/websites/

**Comment by Uafinder** [comment]
The same situation
![image](https://user-images.githubusercontent.com/1945230/32226525-6c6d299a-be51-11e7-89f2-4ae269d27243.png)
http://vlad26-leads_vlad-test26.kademi-ci.co/leads/1260650/

**Comment by anhnt** [comment]
Please create new fresh account or update leadman-lib and re-check

**Comment by Uafinder** [comment]
It works!
