### ISSUE TITLE
Lead profile company button doesn't change label

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4175]
![image](https://user-images.githubusercontent.com/1945230/31599203-05ab24b2-b25a-11e7-823c-f11601a21672.png)

1. When page is refreshed you enter a name of company which are not in database and then button save details change it's label to "create company".
2. The expected thing is to do the same when you for example unlink bad company and want to add new one. Button label doesn't change.

**Comment by anhnt** [comment]
fixed

**Comment by Uafinder** [comment]
Fresh account
Rebuild QA
http://version1.vlad33-leads_vlad-test33.kademi-ci.co/leads
http://vlad-test33.admin.kademi-ci.co/websites/vlad33-leads/version1/#panel_details-tab

**Comment by anhnt** [comment]
Re-synced libs. please check

**Comment by Uafinder** [comment]
Looks ok
