### ISSUE TITLE
Lead creation date and change by date picker caused multimple pop-ups appears on every change 

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4176]
![image](https://user-images.githubusercontent.com/1945230/31599587-add1f714-b25b-11e7-9e26-29345eac0425.png)
When you're using a date/time picker every change made there are saving online and caused multiple pop-ups appear.
One more thing, there two different types of pop-up appears, green with "created date is saved" and blue with "saved created". Probably should be only first.
I've wrote a video.
https://drive.google.com/file/d/0B9V2ZH-h_cR2VjdGTnNwR1VFeDA/view?usp=sharing

**Comment by anhnt** [comment]
Yup just updated messages

**Comment by Uafinder** [comment]
Works like a charm
