### ISSUE TITLE
Carousel element minor bug - next icon doesn't appears in editor

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4177]
![image](https://user-images.githubusercontent.com/1945230/31600644-e7b3f55a-b25f-11e7-9daa-37c2ce836a36.png)
When you change previous and next icons for carousel element in editor, icon for next is not appears in editor.
http://version1.vlad17-reward.kademi-ci.co/contenteditor?fileName=test1.html&miltonUserUrl=/users/18f99d7f-b812-4fb0-8ef3-b3dce205fff5&miltonUserUrlHash=7f251022-fb17-4c2a-a61a-74458bcb47bf:6OZtKFHYCXDbPVuakQYv6ymw5w8
Frontend is ok

**Comment by ducdhm** [comment]
@Uafinder Can you double-check again? It's working normally in my side. Can you close setting panel to check as well as?

**Comment by Uafinder** [comment]
Ahhhr... it's hide besides options side panel... sorry!
