### ISSUE TITLE
Product in rewards fields validation needed and decimal separator add

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4179]
1. Product in rewards details doesn't support any other type of decimal separator but dot. So comma or space is not allowed. E.g. "0.05" is correct, but "0,05" is not and "1000" is correct and "1 000" is not.
![image](https://user-images.githubusercontent.com/1945230/31604428-f034cf86-b26b-11e7-97ce-b7bff03949ee.png)
2. Validation needed... when you enter some value which system thinks it's incorrect is write "Saved" ok, but values disappear completely! It's very dangerous.
![image](https://user-images.githubusercontent.com/1945230/31604520-40ae70e8-b26c-11e7-8aec-a2981d4ff37b.png)
![image](https://user-images.githubusercontent.com/1945230/31604527-4600fc82-b26c-11e7-9480-eafe1cd56586.png)
![image](https://user-images.githubusercontent.com/1945230/31604536-4cf5464c-b26c-11e7-8470-f49d407a2a4d.png)
http://vlad-test17.admin.kademi-ci.co/reward-store/vlad17-reward3-store/#products-tab

**Comment by tuzzmaniandevil** [comment]
1. We are only going to support dot for decimal separators. We don't be supporting spaces either. From this page: https://en.wikipedia.org/wiki/Decimal_mark

> In countries with a decimal comma, the decimal point is also common as the "international" notation because of the influence of devices, such as electronic calculators, which use the decimal point.

2. Fixed

**Comment by Uafinder** [comment]
Understood
Validation issue:
1. When validation works on one field, it highlights this field and those which are in one line with it.
![image](https://user-images.githubusercontent.com/1945230/31712083-bd99c8f4-b402-11e7-9b04-26d489d92d41.png)

**Comment by tuzzmaniandevil** [comment]
@Uafinder That is an issue with the jQuery forms plugin. @ducdhm Please can you have a look?

**Comment by ducdhm** [comment]
@bradmac Do you think it's good idea to allow user to enter number like `1,000` or `1 000`? IMHO, for input or textbox, just allow to enter only digits. `1,000` or `1 000` is just for formatting with displaying purpose

**Comment by bradmac** [comment]
I think forms should never ignore user input. If someone types in invalid characters, those should appear and the user should be given an explicit validation message.

To just ignore input will in many cases cause confusion for the user, because there is no feedback to them.

So i think the current approach it field validation is fine. We just need to make sure the usual validation mechanism works correctly for this form.

**Comment by anhnt** [comment]
fixed form validation

**Comment by Uafinder** [comment]
Works great!
