### ISSUE TITLE
Zero missed for time pop-up on the module frontend

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4181]
![image](https://user-images.githubusercontent.com/1945230/31611012-0a2a8a36-b283-11e7-8d3b-4fa458aa5022.png)
![image](https://user-images.githubusercontent.com/1945230/31611042-296caed8-b283-11e7-8ba1-a6e08fc5f08d.png)
![image](https://user-images.githubusercontent.com/1945230/31611051-333dce38-b283-11e7-8bc2-052d7a167486.png)

e.g. 15:0 for 15:00, 15:1 for 15:01 and 15:3 for 15:03
http://vlad17-learn.kademi-ci.co/programs/PRG1/CRS1/m1/ppage1.html

**Comment by mrdadah** [comment]
@anhnt could you review my commit and approve it if everything is ok?

**Comment by bradmac** [comment]
@mrdadah looks good!

**Comment by Uafinder** [comment]
it's ok!
