### ISSUE TITLE
export modules activity on backup

### ISSUE THREAD

**Issue by salehh93** [Kademi/kademi-dev#4182]
we can't  import and export modules activity on backup
I can't see modules activity here  http://3dn.admin.kademi.com.au/websites/idhealth-training/version1/programs/Carers/Carers1/Carers01/#activity-tab
from
http://3dn.admin.olhub.com/backup/

**Comment by bradmac** [comment]
@tuzzmaniandevil can you look into this today, please?

**Comment by salehh93** [comment]
after upload learning_moduleStatus backup I waited allot but useless

**Comment by bradmac** [comment]
Hi @salehh93 please discuss with @mkhoudary 

The plan now is to use SQL to export modulestatuses, and to use a table uploader to import.

**Comment by tuzzmaniandevil** [comment]
@mkhoudary @salehh93 The module activity importer is ready to use.

**Comment by mkhoudary** [comment]
Tested and working..
