### ISSUE TITLE
Page changing from one to another doesn't cause comments reload

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4183]
http://vlad17-learn.kademi-ci.co/programs/PRG1/CRS1/m1/ppage1.html
Just switch from page 1 to page 2
note, that comments doesn't disappear
if you will refresh page - you will note that they are gone
http://vlad17-learn.kademi-ci.co/programs/PRG1/CRS1/m1/ppage2.html
also if you go directly to the page 2, you will note that comments are absent and this is correct
if you will go back to previous page, which should contain comments they will not appear.

http://vlad-test17.admin.kademi-ci.co/ 
adminqa@mailinator.com

**Comment by bradmac** [comment]
Comments should be associated with the module, not the page, so should not change from one page to the next.

Refreshing the page should continue to display the same comments as shown on other pages

**Comment by bradmac** [comment]
@gonzalon can you look into this please?

**Comment by gonzalon** [comment]
please test with the latest forums-lib version 1.1.1

**Comment by Uafinder** [comment]
it works!
