### ISSUE TITLE
Manage orgs page issues

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4184]
- trim search criteria 
- change "profiles" to organisations in no results message
![image](https://user-images.githubusercontent.com/826458/31634168-0374b01c-b31f-11e7-8a80-612589896ff4.png)
- move search box to left so it aligns with search results
- move actions which are contextual to checkboxes so they align with checkboxes. Probably in a tools dropdown with "Remove" as the main inline button
- remove the panel around search results
- Add an orgtype search term for "No type"

**Comment by gonzalon** [comment]
![image](https://user-images.githubusercontent.com/2773216/31637737-9a004250-b32c-11e7-941a-c2a3936d7dde.png)

**Comment by Uafinder** [comment]
Yeap, looks fine
