### ISSUE TITLE
Points panel background colour clash

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4186]
The points balance is not visible because its black text on a black background:
![image](https://user-images.githubusercontent.com/826458/31635470-552d4de8-b323-11e7-8e4c-afd0164ac2ed.png)

Thats because the panel uses brand-primary which has been set through customisation to be black:
![image](https://user-images.githubusercontent.com/826458/31635742-660aa6dc-b324-11e7-83b2-62b6d4f6ddc8.png)

We need to give our users an easy option to deal with this. Maybe allow them to select the brand colour for panel background? Or an option to use an inverted colour scheme?

**Comment by bradmac** [comment]
OK, so the problem is that headings have a hard color override:
![image](https://user-images.githubusercontent.com/826458/31691177-9c816034-b3f1-11e7-90e9-fe705292dcaa.png)

But non heading styles get white text when using panel-primary:
![image](https://user-images.githubusercontent.com/826458/31691210-c4916790-b3f1-11e7-8b0b-eca391ffcc39.png)

So I've put in a temp hack so the text is at least visible by usnig p.lead instead of h2:

![image](https://user-images.githubusercontent.com/826458/31691158-83cbca52-b3f1-11e7-8778-4db06f58dbff.png)

**Comment by bradmac** [comment]
But that text is too small. We should have something better..

**Comment by ducdhm** [comment]
@bradmac I think in k-theme, we should set headings-color is `inherited` same as default of bootstrap

**Comment by anhnt** [comment]
It's now configurable 

![image](https://user-images.githubusercontent.com/735555/31703540-36d848cc-b407-11e7-8478-435caf1690dc.png)

**Comment by Uafinder** [comment]
It works. Even you disable Inherit checkbox near Heading color, check box inverted text color saves the situation.
http://version1.vlad23-points.kademi-ci.co/pages1.html?miltonUserUrl=/users/2f5ccda6-2de0-4223-a41b-31d380bf3e5c&miltonUserUrlHash=e696706e-0878-413a-8d9d-ab8faefe71df:foNyrQLUhkjijpwC01rleBFoEP4

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/31822221-b37e6596-b5b0-11e7-939e-5e1159a7c927.png)
