### ISSUE TITLE
Funnels: Processing leads even when cancelled

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#4187]
We need to check if a lead is cancelled before processing them.

**Comment by Uafinder** [comment]
Hey, Wes...
Could you give me a hand with test this issue. What should I do?

**Comment by tuzzmaniandevil** [comment]
Create a funnel with 2 Goals Example:
- Begin
- Group Goal
- Page Viewed Goal
- Send Email Action
- End

Then:
- Create a new user and add them to the configured group
- Cancel the lead in the front-end
- Login as the user to the website
- The email should NOT be sent as the lead has been cancelled

**Comment by Uafinder** [comment]
Yes, it works ok.
