### ISSUE TITLE
KEditor is failing to initialise

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4188]
Eg
http://linkrewards.kademi.com.au//theme/apps/rewardstore/contenteditor?fileName=rewardStoreDashboard.html&miltonUserUrl=/users/lyle-de-villiers&miltonUserUrlHash=3496e02a-d4ca-42c3-b795-cd65f0332ecc:4PFlNsDKoBygH1W6g_INzK487N8

![image](https://user-images.githubusercontent.com/826458/31637457-53a4342a-b32b-11e7-879b-3741822d8f0e.png)

No sign of errors in the logs, but initContentEditorPage is not called

![image](https://user-images.githubusercontent.com/826458/31637479-65fe64ba-b32b-11e7-9f53-8353672def81.png)

**Comment by ducdhm** [comment]
Content editor and keditor js stuff are working normally. Error came from `kpis.js`
```
Uncaught TypeError: $(...).mupload is not a function
    at HTMLDocument.<anonymous> (kpis.js:14)
    at fire (jquery-1.11.0.js:3099)
    at Object.fireWith [as resolveWith] (jquery-1.11.0.js:3211)
    at Function.ready (jquery-1.11.0.js:3423)
    at HTMLDocument.completed (jquery-1.11.0.js:3453)
```

**Comment by ducdhm** [comment]
I have removed `kpis.js` file because its content is not related to kpi or salesdata stuff.

**Comment by Uafinder** [comment]
Looks ok!
