### ISSUE TITLE
Hey, its not letting us select any styles, need to change the colors of the links in the text - not working :)

### ISSUE THREAD

**Issue by Anton69arb** [Kademi/kademi-dev#4189]
Hey, its not letting us select any styles, need to change the colors of the links in the text - not working :)

![its not letting us select any styles](https://user-images.githubusercontent.com/32444328/31638905-7ee4eb00-b332-11e7-8f12-13b2ae7d8e24.png)

http://docs.kademi.co/programs/dev/d3/app-2/contenteditor?fileName=pintroduction.html&miltonUserUrl=/users/anton&miltonUserUrlHash=c40c300f-1d88-43f7-a0d5-2bba62f35f77:AKVpBSNH7Oz0tmErjiKqprq61m0

**Comment by bradmac** [comment]
@Anton69arb we dont want to manually set link colours. The link colour should come from the site stylesheet.
