### ISSUE TITLE
SKUs not appearing in table

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4191]
This user http://moblix.admin.kademi-ci.co/manageUsers/152956/#summary-tab

This page http://moblix-channel.kademi-ci.co/sales-data.html

![image](https://user-images.githubusercontent.com/2201340/31640644-5543ed0c-b32b-11e7-8d6a-3d3378848d6c.png)

SKU http://moblix.admin.kademi-ci.co/products/676331/#panel_details-tab

Sales data has SKU codes http://moblix.admin.kademi-ci.co/sales/sales-data-2016-and-2017/#history-tab

Please also add table height and table title field to the component.

**Comment by tuzzmaniandevil** [comment]
That's because no SKU's have been setup here: http://moblix.admin.kademi-ci.co/skus/

**Comment by tuzzmaniandevil** [comment]
It works once I added the sku. I've made a small adjustment to show the sku code if we couldn't find a matching sku
