### ISSUE TITLE
KEditor adding edit buttons

### ISSUE THREAD

**Issue by gonzalon** [Kademi/kademi-dev#4192]
When saving the page in the editor:
http://milestoneevents.global//theme/apps/blogs/contenteditor?fileName=viewBlogArticle.html&miltonUserUrl=/users/celine-gilpin&miltonUserUrlHash=8fb86799-5c73-4578-8795-a8c18d43a6b9:JzL_FBkHoYRd-HeFItoTrLIz1f0

It would add:
![image](https://user-images.githubusercontent.com/2773216/31642634-6fb13358-b348-11e7-912e-534e70b5fd75.png)

**Comment by ducdhm** [comment]
Duplicated with https://github.com/Kademi/kademi-dev/issues/4241
