### ISSUE TITLE
admin elearning: allows searching courses, modules, programs 

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#4195]

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/33110431-6c414bf6-cf7a-11e7-8227-db215fb56a50.png)

Done

**Comment by Uafinder** [comment]
http://vlad-test58.admin.kademi-ci.co/websites/vlad58-learn/version1/programs/p1/c1/
1. While searching probably would be great to hide all level splitters.
![image](https://user-images.githubusercontent.com/1945230/33126205-58430d08-cf8c-11e7-9397-79643b42b60e.png)

2. While searching, there is no possibility to change something - drop-down menu is bad
![image](https://user-images.githubusercontent.com/1945230/33126423-198332ae-cf8d-11e7-80e3-bcd05a60e73d.png)

3. When using Uppercase in search - the search process begins only after 3-rd symbol.
Eg. "Se" doesn't look anything, "Sea" - works perfect.
Eg. "Te" doesn't look anything. "Tes" - works perfect.
![image](https://user-images.githubusercontent.com/1945230/33126636-dcfea29a-cf8d-11e7-8837-514e67f33deb.png)

**Comment by bradmac** [comment]
> While searching probably would be great to hide all level splitters.

No, its fine, we dont need that

**Comment by bradmac** [comment]
Issues 2 and 3 are significant.

**Comment by bradmac** [comment]
But we can leave updates to a later milestone

**Comment by anhnt** [comment]
Fixed 2 and 3

**Comment by AlaaKhalaf94** [comment]
passed
