### ISSUE TITLE
Better admin dashboard alert

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#4197]
Current UI when we have a lot of alerts: 
![ui](https://user-images.githubusercontent.com/1289631/31653425-becfd36e-b34c-11e7-9b8a-e64ec839a2e9.png)

Maybe can use notification in topnav as original clipone theme (http://preview.themeforest.net/item/clipone-bootstrap-3-responsive-admin-template/full_screen_preview/5881143?_ga=2.178038432.446918208.1508227378-462555083.1507514649)

**Comment by bradmac** [comment]
No, as discussed we want alerts to be inline in the page. These are important, they're saying that an app has created new groups, orgs, etc, or reconfigured settings.

If those are put in a facebook style notification box users will rarely look at them.

And note that its not realistic to have so many alerts. A real user would simply close alerts once they've seen them.

But i think we can improve the style of the alerts. Eg something like this:

https://cdn.dribbble.com/users/90530/screenshots/845092/alert_messages_mobile.jpg

**Comment by mrdadah** [comment]
Done, new alerts should looks like this 

<img width="1455" alt="screen shot 2017-12-24 at 4 08 17 pm" src="https://user-images.githubusercontent.com/11255121/34327111-e8ba46ca-e8c4-11e7-80dd-f60915a9f0bc.png">

**Comment by mrdadah** [comment]
@bradmac if you have any comments just let me know

**Comment by Uafinder** [comment]
Looks great! 👍
