### ISSUE TITLE
Leads with closed date empty and specified column for import are not importing

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4198]
I have a list of leads which are partially active and others are already closed with closed date attribute specified.
I upload file and specify all necessary columns for import, and after that system says that leads with no closed date specified will not be imported.
![image](https://user-images.githubusercontent.com/1945230/31662841-ac494e7c-b348-11e7-8056-386b2d098033.png)
![image](https://user-images.githubusercontent.com/1945230/31662859-b4f8f90a-b348-11e7-8a5e-6ac28094211f.png)
http://vlad-test19.admin.kademi-ci.co/tableUploaders

**Comment by gonzalon** [comment]
Related to: https://github.com/Kademi/kademi-dev/issues/3909#event-1296780196

**Comment by bradmac** [comment]
The closed date is just blank, which should be treated as null, ie the lead is not closed

**Comment by Uafinder** [comment]
Yup, it works...
