### ISSUE TITLE
Validate task fields on new lead from kademi console

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#4199]
If the description field is entered, validate the task field
related to : https://github.com/Kademi/kademi-dev/issues/3565

![capture1](https://user-images.githubusercontent.com/26510030/31667688-d8998810-b358-11e7-84d6-0c7218a604e0.PNG)

**Comment by anhnt** [comment]
Done

**Comment by AlaaKhalaf94** [comment]
passed
