### ISSUE TITLE
Add option button in add extra fields in sales data doesn't work

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#4200]
Here : http://alaa5.admin.kademi-ci.co/sales/training-data/#general-tab

At the bottom of the page when I try to add extra fields in its modal the "add option" button doesn't work

![capture1](https://user-images.githubusercontent.com/26510030/31668756-bd3e170e-b35b-11e7-8f80-a0c4cd3bb934.PNG)

**Comment by AlaaKhalaf94** [comment]
That passed , and "add option" button work well with me , but this linked on other modal , that's in the same page , in records tab , in create records modal

Ex : 
- here : http://alaa5.admin.kademi-ci.co/sales/training-data/#general-tab at the bottom of the page I  add an extra field "description01" "Did you have learned 01"  and I add two options on it "yes,No" .

- In the same page , in records tab , I try to add new record , but I can't see the options that I add within "Did you have learned 01"

**Comment by gonzalon** [comment]
![image](https://user-images.githubusercontent.com/2773216/34237327-edf8ec60-e660-11e7-9f78-18f09eb70c94.png)

![image](https://user-images.githubusercontent.com/2773216/34237332-f769555a-e660-11e7-9093-ff164cc62840.png)

**Comment by AlaaKhalaf94** [comment]
Hi @gonzalon , I can't see your update

I test here : http://fresh14.admin.kademi-ci.co/sales/new-series/#general-tab

![capture1](https://user-images.githubusercontent.com/26510030/34246469-70bed33c-e637-11e7-8c22-9bb709115585.PNG)

![capture2](https://user-images.githubusercontent.com/26510030/34246475-74f7f2c6-e637-11e7-9877-bd9651a639b5.PNG)

**Comment by gonzalon** [comment]
@AlaaKhalaf94 Ups forgot to push my changes :( Should be able to see it now

**Comment by AlaaKhalaf94** [comment]
passed
