### ISSUE TITLE
Points earned component, with optional tag

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4202]
Please create a new component as part of rewardstore-lib

This will show points earned for the current participant, for a selected points bucket, and optionally filtered by a points tag.

- ensure common date range is applied
- for org based points buckets, use the common org selector
- component settings should allow selection of a points bucket and (optional) points tag
- the component should be updated if the date range or selected org changes
- note that multiple instances of this component can be used in a page
- use similar layout as singleValueComponent

**Comment by Uafinder** [comment]
What is the name of this component? Recent Points?

**Comment by bradmac** [comment]
Called "pointsEarned"
```
controllerMappings.addComponent("rewardstore/components", "pointsEarned", "html", "Shows points earned for the current participant, for a selected points bucket and optionally filtered by a points tag", "Reward Store");
```

**Comment by Uafinder** [comment]
Works like a charm!
