### ISSUE TITLE
Create a Module Status Table Uploader

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#4203]

**Comment by Uafinder** [comment]
1. Probably need to add validation for program, course, and module existed to avoid possibility of adding fake data.

2.

**Comment by bradmac** [comment]
> Probably need to add validation for program, course, and module existed to avoid possibility of adding fake data.

No, we actually need to allow users to import historical data which might not correspond to current course structure

**Comment by bradmac** [comment]
> When select to upload profile email and do not upload profile ID uploader will think that this is a new row.

If you provide a profileID (ie username) and there is no such user, that should be a validation failure

**Comment by Uafinder** [comment]
Again, the situation is following:
I've set import emails and do not import user ids
![image](https://user-images.githubusercontent.com/1945230/33174340-4b3bc4c2-d060-11e7-8840-80642afc85ec.png)
But it says that they are new
![image](https://user-images.githubusercontent.com/1945230/33174388-7b7c3efa-d060-11e7-9f7b-ab084e26cc13.png)
http://vlad-test59.admin.kademi-ci.co/tableUploaders/moduleStatusUploader

**Comment by tuzzmaniandevil** [comment]
@Uafinder The "New rows to be inserted" in this case refers to existing module status records. Not profiles. Though I did find a small bug locating a profile

**Comment by Uafinder** [comment]
ok, understood
and one more:
when you upload data which is not correspond to the actual learning data all links which could be old will leads to an error
![image](https://user-images.githubusercontent.com/1945230/33487365-9d8e942e-d6b5-11e7-8279-9b2a6919b420.png)
http://vlad-test65.admin.kademi-ci.co/training/?startDate=01%2F09%2F2017&endDate=01%2F12%2F2017

**Comment by bradmac** [comment]
@Uafinder thats noted but we wont do anything about that for now

**Comment by Uafinder** [comment]
ok, so it works perfect...
