### ISSUE TITLE
New org page creation pop-up incorrect

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4204]
![image](https://user-images.githubusercontent.com/1945230/31712872-03d942b6-b405-11e7-8b2a-1116daf901a6.png)
I've creating an org, and it gives me such pop-up
Should be something like "$orgname$ is created" or "Organisation is created"
http://vlad-test19.admin.kademi-ci.co/organisations-es

**Comment by bradmac** [comment]
Please change to "Created organisation" (no exclamation marks)

**Comment by anhnt** [comment]
done

**Comment by AlaaKhalaf94** [comment]
passed
