### ISSUE TITLE
Improved Accordion Component

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#4205]
Add possibility to choose icon to appear when Accordion is closed and when its open
and choose alignment to it , please

thing like this 

![capture1](https://user-images.githubusercontent.com/26510030/31716524-ed3abd3a-b410-11e7-918a-e35b38f8b16c.PNG)

**Comment by AlaaKhalaf94** [comment]
https://github.com/Kademi/client-gilpin-travelworld/issues/36

**Comment by bradmac** [comment]
If this is required for travelworld then it should be High Priority and in the current milestone

**Comment by salehh93** [comment]
done

**Comment by ducdhm** [comment]
@salehh93 When you're done, please add label `Ready to Test QA` and dont remove any labels

**Comment by ducdhm** [comment]
@salehh93 A couple of comments from me:
 1. Dont add any number to label like this "Panel style1"
 2. Dont commit `package-lock.json`. You should add it in ignore file inside `keditor` folder
 3. Please naming class more meaning. Dont use `panelIcon1` and `panelIcon2`. They're meaningless.
 4. Please write LESS instead of normal CSS in LESS file (you research about LESS, how to do it)
 5. Please test before assigning issue to tester. I'm sure that you CSS rules are not correct

```
.panel-heading .collapsed .panelIcon1   {display:block;}
.panel-heading .collapsed .panelIcon2   {display:none;}
.panel-heading a:not(collapsed) .panelIcon2{display:block;}
.panel-heading a:not(collapsed) .panelIcon1{display:none;}
```

**Comment by salehh93** [comment]
@ducdhm 
first thanks for this notes 
1,2 by mistake
3 I am use panelIconCollapsed , panelIconExpanded instead of panelIcon1 and panelIcon2
4 I am already used less but not work with me because used in dependencies file cssMedia instead of lessMedia

now it's fixed

**Comment by AlaaKhalaf94** [comment]
Hi @bradmac , Should there be a control for the alignment of icon, or is it good?
I used it here : http://version1.alaa-test9.kademi-ci.co/index.html
In home page : http://alaa-test9.admin.kademi-ci.co/pages/alaa-test9/version1/

In travelworld site , the alignment of icon is left
http://version1.travelworldnz.kademi.com.au/ourDeals/australian-open-from-469/

**Comment by ducdhm** [comment]
@salehh93  Just a small thing, please dont remove `Label` of issues like `enhancement`, `High priority`. They are same like tags for issue. Please dont remove. Just add or remove labels like `Ready to test`, `Discuss` or `question`

**Comment by bradmac** [comment]
@AlaaKhalaf94 its ok, we dont need it yet

**Comment by AlaaKhalaf94** [comment]
passed

**Comment by AlaaKhalaf94** [comment]
I tried to use it again, but it does not work with me properly
I choose icons from setting of component , but doesn't appear in Accordion
@anhnt , Repair the component , please

I test it again here : http://alaa-test32.admin.kademi-ci.co/pages/alaa-test32/version1
in Golden page

**Comment by anhnt** [comment]
Fixed working ok now

**Comment by AlaaKhalaf94** [comment]
Thanks @anhnt
passed
