### ISSUE TITLE
Improved Panel Component

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#4206]
Please make the following :
- Add the possibility to specify padding .
- Remove the link between its style and font color " I mean when I change the panel style, do not change the text color stays black " .

**Comment by AlaaKhalaf94** [comment]
https://github.com/Kademi/client-gilpin-travelworld/issues/36

**Comment by ducdhm** [comment]
@AlaaKhalaf94 @bradmac Do you think it's ok for letting user to change padding of panel? Padding of panel should be came from theme.

**Comment by bradmac** [comment]
users should be **able** to change padding. 

But they should not **need** to change padding for the component to have a correct and professional appearnace

**Comment by salehh93** [comment]
done

**Comment by AlaaKhalaf94** [comment]
passed
