### ISSUE TITLE
Tag & Reason Code filters doesn't contain variants which was changed without refresh

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4209]
1. I've debit some points from user with reason code E
2. Then I want to use filter by "E" code, but it's empty
![image](https://user-images.githubusercontent.com/1945230/31721958-6e015796-b423-11e7-91d8-b69fecaee5e2.png)
http://vlad-test20.admin.kademi-ci.co/points-buckets/points/

**Comment by bradmac** [comment]
http://vlad-test20.admin.kademi-ci.co/manageApps/#installed-tab

![image](https://user-images.githubusercontent.com/826458/31744938-67a26fbc-b4bd-11e7-980f-19eb383bf015.png)

**Comment by bradmac** [comment]
The list is generated from settings, not from looking at records

**Comment by bradmac** [comment]
E is a special code which means Expiry, and should always be an available choice, regardless of settings

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/32169677-336b0752-bd7a-11e7-9f49-6d7c067f49f3.png)
So, if you say that it should appears always, why it's absent here.
http://vlad25-test.admin.kademi-ci.co/rewards/points/

**Comment by bradmac** [comment]
OK, we should add it to that list as standard

**Comment by gonzalon** [comment]
![image](https://user-images.githubusercontent.com/2773216/32529547-0ef2f2b0-c49e-11e7-93eb-f0373eec8c7f.png)

**Comment by bradmac** [comment]
@Uafinder the list shows only used reason codes. There is no point allowing searching for something which isnt there.

**Comment by Uafinder** [comment]
oh, understood
