### ISSUE TITLE
Files are uploaded to wrong folder

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#421]
Browser: Chrome
OS: Windows 8.1
Description: Go to File kademi admin, then go to file manager. Click to enter /theme folder and then upload a file.
Expect: File should be uploaded to /theme folder
Actual: File is uploaded to root folder (parent of /theme folder)

**Comment by bradmac** [comment]
@ducdhm just pointed that out :)

**Comment by bradmac** [comment]
Done
