### ISSUE TITLE
Slow page display when funnels are enabled

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4212]
Clicking from an email sent by the US server to a webpage on the US server was running very slow, at times it took 15 seconds from clicking to the page finishing loading.

Manually add a user to this group http://kademi.admin.kademi.us/groups/loyalty-email-campaign/members/ to send an email.

Then in Mailinator click from the first email link.

**Comment by bradmac** [comment]
I think we need to disable firing the PageHitFunnelEvent

**Comment by paddyow** [comment]
This might also be connected.

Ran some Google Ads with the URL and query /solutions/b2b-channel-incentives.html?source=googleadb2b

Looks like clicking through from a Google Adwords campaign people were bouncing almost immediately which 'might' be due to the page not loading quick enough.  See the number below.

![image](https://user-images.githubusercontent.com/2201340/31866677-c5183424-b7ce-11e7-99a2-56397f105111.png)

**Comment by bradmac** [comment]
I've disabled the page viewed event, so should be much faster now

**Comment by bradmac** [comment]
Re-enabling page viewed event. I think the db changes we've made should make things faster now
