### ISSUE TITLE
Organisation import performance results

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4213]
Import process are slowing down while importing.
On the start there was 20-25 orgs per hop (2 secs), after 2000 orgs already imported speed is 5 orgs/2sec and slowing down. Will update a result when it finishes.
update: so, import of file, which contains 10800 orgs takes 3 hours and 15 minutes, while import ends it processed by 1 org into 2 seconds.

**Comment by bradmac** [comment]
Can you have another go?

**Comment by Uafinder** [comment]
Much better... Approx 1 hour...
