### ISSUE TITLE
Adding photo via rich text editor caused it doesn't appears in emails

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4215]
http://vlad-test20.admin.kademi-ci.co/groupEmails/803487/#messages-tab
https://user-images.githubusercontent.com/1945230/31720381-2138e004-b41f-11e7-994c-2b6a34a20117.png
https://user-images.githubusercontent.com/1945230/31720457-5249dfcc-b41f-11e7-8a08-004d2a358078.png
https://user-images.githubusercontent.com/1945230/31720485-6125c3f8-b41f-11e7-9f59-127e99a6a3ae.png

Add a picture via Rich txt editor and it's not appears in email body.

**Comment by bradmac** [comment]
I think its currently missing the domain name

**Comment by ducdhm** [comment]
Fixed!

**Comment by AlaaKhalaf94** [comment]
passed
