### ISSUE TITLE
KEditor - doubleclick on image to edit it caused a bug

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4216]
![image](https://user-images.githubusercontent.com/1945230/31766619-bfe0c08a-b4d0-11e7-82fb-54ad2a35270d.png)
1. Open page for edit
2. Found an image in text
3. Select it
4. When i use toolbar button it works ok, but i use doubleclick on image to edit it caused a bug.
http://vlad-test20.admin.kademi-ci.co/groupEmails/854540/#messages-tab

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
yup, works fine
