### ISSUE TITLE
Lead creation process - accounts pickup

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4217]
1. ![image](https://user-images.githubusercontent.com/1945230/31772332-05c64798-b4e8-11e7-91d0-fb8fa08d15ab.png)
![image](https://user-images.githubusercontent.com/1945230/31772343-0f7dee58-b4e8-11e7-84f2-24710be95645.png)
userqa03 account is not appearing in list because it doesn't have leads group. Is this correct or not?
http://vlad-test20.admin.kademi-ci.co/manageUsers/
http://vlad20-lead.kademi-ci.co/leads/?query=&leadType=active

2. Doublin' user accounts when you create a lead
For example I have a user userqa05@... with name userQA05 and without groups.
I've tried to create a lead and enter userqa05 to name... it says that no account found.
![image](https://user-images.githubusercontent.com/1945230/31772640-0b549db2-b4e9-11e7-8352-4ae2adbff808.png)
I resume enter data and create lead. It created another account userqa05...
![image](https://user-images.githubusercontent.com/1945230/31772920-b97eb846-b4e9-11e7-89f0-29b24bf0056f.png)
http://vlad-test20.admin.kademi-ci.co/manageUsers/

**Comment by tuzzmaniandevil** [comment]
1. Yes that is correct :-)
2. Updated the logic. If we find a profile with a matching email address we will use that email address. Otherwise we create a profile.

**Comment by Uafinder** [comment]
Yup, it works!
