### ISSUE TITLE
Create more than one lead without page refresh

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4218]
1. Create a lead.
2. Open create lead dialog for create another one. Note, that some fields are already entered.
![image](https://user-images.githubusercontent.com/1945230/31773333-1bc372a2-b4eb-11e7-9dbb-a7fc9e27b38f.png)
3. Create a lead without change already specified fields.
4. Note, that field Source are not entered but it was specified on the lead creation dialog.
![image](https://user-images.githubusercontent.com/1945230/31773321-107f146e-b4eb-11e7-815c-b17ecbcfaf06.png)
http://vlad20-lead.kademi-ci.co/leads/?query=&leadType=active
http://vlad-test20.admin.kademi-ci.co/manageUsers/

**Comment by tuzzmaniandevil** [comment]
This was caused by the new Class filter stuff. Fixed now

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/32163784-19420c36-bd66-11e7-8a4f-eeb45ab59f0a.png)
The field source are still preselected when create lead after creation of another one.
http://vlad25-leads.kademi-ci.co/leads/?query=&leadType=active
http://vlad25-test.admin.kademi-ci.co/funnels/journey1/version1/#properties-tab

**Comment by bradmac** [comment]
> The field source are still preselected when create lead after creation of another one

I think this is a good thing. If a user is entering multiple leads it will often be the case that many fields will be the same.

>  And when it's preselected - it doesn't save in lead properties.

But that is a bug!

**Comment by tuzzmaniandevil** [comment]
Easiest way to fix it is to reset the stage to blank as every time the modal opens or the journey field changes it will reload the stages for that journey

**Comment by Uafinder** [comment]
Yup, it looks ok at the moment
