### ISSUE TITLE
Migration issue - No training components showing

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4220]
Looks like the latest learning components have not been pushed.

From:
http://moblix.admin.kademi-ci.co/pages/moblix-channel/version1/

To:
http://moblix-hinda.admin.kademi.us/hinda-settings/

See training.html which has code but no components showing.

Test with this profile http://moblix.admin.kademi-ci.co/manageUsers/762030/#summary-tab

Go to this page http://moblix-channel-site.kademi.us/training.html

**Comment by anhnt** [comment]
fixed
