### ISSUE TITLE
Click through from Category on dashboard fails to show prods in the store

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4224]
This user http://moblix.admin.kademi-ci.co/manageUsers/762030/#summary-tab

Needs fixing on QA Moblix and the Hinda account http://moblix-hinda.admin.kademi.us

![image](https://user-images.githubusercontent.com/2201340/31800297-afa515e8-b58b-11e7-8274-761e60ba533e.png)

**Comment by ducdhm** [comment]
Fixed! Just need re-indexing!
