### ISSUE TITLE
Cannot upload claim

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4225]
This user http://moblix-hinda.admin.kademi.us/manageUsers/15806276/#summary-tab

See claim app here http://moblix-hinda.admin.kademi.us/manageSaleDataClaimer/

![image](https://user-images.githubusercontent.com/2201340/31800579-8aa08f0a-b58d-11e7-9b93-a3af9720dbc7.png)

**Comment by ducdhm** [comment]
Fixed!

**Comment by paddyow** [comment]
Cannot approve a claim

http://moblix-hinda.admin.kademi.us/manageSaleDataClaimer/
