### ISSUE TITLE
Unable to upload new image for emoticon feedback

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4226]
http://moblix-hinda.admin.kademi.us/kfeedback/#!/surveys/detail/?id=program-sentiment

Note I tried this with a new survey and it still failed.

![image](https://user-images.githubusercontent.com/2201340/31800990-c9863794-b590-11e7-9af8-07917c6173f7.png)

**Comment by anhnt** [comment]
fixed http://moblix-hinda.admin.kademi.us/kfeedback/#!/surveys/detail/?id=test
