### ISSUE TITLE
Reward selector component doesn't change promotion on selection

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4229]
![image](https://user-images.githubusercontent.com/1945230/31808778-4cf13444-b57d-11e7-92f4-2eaed5fe70ff.png)
When you change promotion via selector it doesn't change page to appropriate promotion page.
http://vlad20-promo.kademi-ci.co/page2.html

**Comment by anhnt** [comment]
This is old component and i dont think we need it at the moment since we can set specific promotion via settings for promotion form.

**Comment by Uafinder** [comment]
IF it's an old component, so we probably should hide it, or remove from selection list

**Comment by bradmac** [comment]
hey @anhnt no, this component is for selecting a promotion for filtering data. Its not related to promotion selection in settings.

Its needed for building analytics dashboards which shows data from promotions, and should work similar to the common date selector

**Comment by bradmac** [comment]
@Uafinder this is not intended for users to select a promotion. In the situation you have on page2.html you would either select the promotion in settings, or you would normally just have each promotion page display itself and not need to select a promotion on the component

**Comment by Uafinder** [comment]
Ok, understood!
