### ISSUE TITLE
Email history show nothing

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4230]
http://vlad-test21.admin.kademi-ci.co/emails/?q=&status=&job=
http://vlad-test21.admin.kademi-ci.co/groupEmails/
![image](https://user-images.githubusercontent.com/1945230/31819324-e71b5e4c-b5a4-11e7-941a-4dc8313e17a1.png)

**Comment by gonzalon** [comment]
Hi @Uafinder I can see the history and filter by the different jobs:
http://vlad-test21.admin.kademi-ci.co/emails/?q=&status=&job=
Tried duplicating one job and seems ok.
Can you still reproduce it?

**Comment by Uafinder** [comment]
it looks ok at the moment... I will keep an eye on it

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/32376967-f957c860-c0ae-11e7-95c6-efa3b6454401.png)
![image](https://user-images.githubusercontent.com/1945230/32376986-0530125a-c0af-11e7-934d-41326e5d4208.png)

Spot it again!
http://vlad-test31.admin.kademi-ci.co/groupEmails/1580103/log.html

**Comment by bradmac** [comment]
Displays correctly for me:
![image](https://user-images.githubusercontent.com/826458/32419221-986c8534-c2db-11e7-9f8a-692fde49a53a.png)

**Comment by bradmac** [comment]
If this happens again can you please check your web console for JS errors or network errors?

**Comment by bradmac** [comment]
Just tidied up the page layout a bit

**Comment by Uafinder** [comment]
will keep an eye on it
