### ISSUE TITLE
Points button looks have incorrect link

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4231]
![image](https://user-images.githubusercontent.com/1945230/31820814-a3237588-b5ab-11e7-9336-b1fb3d3cd583.png)
It transfers you to:
http://vlad-test23.admin.kademi-ci.co/rewards/points/       this page is from another lib.
But looks it should take you to:
http://vlad-test23.admin.kademi-ci.co/points-buckets/points/

**Comment by salehh93** [comment]
done

**Comment by AlaaKhalaf94** [comment]
passed
