### ISSUE TITLE
KEditor broken after enablin' Reporting app on website

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4232]
http://vlad-test23.admin.kademi-ci.co/pages/vlad23-points/version1/
![image](https://user-images.githubusercontent.com/1945230/31823814-01dcb86e-b5b6-11e7-8a0a-4a9ed889866e.png)
adminqa@mailinator.com
I have a site where Reward Store app was activated. I tried to enable Reporting app and after that all pages failed to open via KEditor. I tried to disable app and clear cache but it doesn't fix the problem. Please advice.

**Comment by bradmac** [comment]
I've updated libs, and seems to be working now
![image](https://user-images.githubusercontent.com/826458/32079318-b4bb4036-bb06-11e7-863e-81049b28a6d9.png)

**Comment by Uafinder** [comment]
yup, looks ok. I will keep an eye on it

**Comment by Uafinder** [comment]
Spot it again:
1. Create a fresh account
2. Create an admin user for me
3. Login by this user: adminqa@mailinator.com
4. Create a website
5. Install there learning app and enable there reporting app
6. Go to edit content and created learn.html page
7. Try to edit it, but content editor stucks...
8. Same sit while trying to edit home page.
http://vlad-test28.admin.kademi-ci.co/websites/vlad28-learn/version1/#panel_details-tab
![image](https://user-images.githubusercontent.com/1945230/32273732-4cec277c-bf0c-11e7-86af-b1dc73f3505d.png)

**Comment by bradmac** [comment]
The problem is because the k-theme lib repository is empty:
http://vlad-test28.admin.kademi-ci.co/repositories/k-theme/1.2.5/

**Comment by bradmac** [comment]
But the current main version isnt empty:
http://rootorg.admin.kademi-ci.co/repositories/k-theme/1.2.5/

**Comment by bradmac** [comment]
OK, i think this was because of the problem with the autoloader that wes fixed.

So shouldnt happen again.

@Uafinder please test with a fresh account

**Comment by Uafinder** [comment]
Yup, looks fine at the moment
