### ISSUE TITLE
Tile component

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4234]
Please create a component for a standard tile
- image + heading + text (each optional?)
- optional link, which should link heading + image
- perhaps layout similar to below?

https://www.vendhq.com/retail-resource-hub

![image](https://user-images.githubusercontent.com/826458/31873675-3ec83bfa-b821-11e7-9266-89d6cd350b93.png)

**Comment by anhnt** [comment]
done

**Comment by AlaaKhalaf94** [comment]
passed
