### ISSUE TITLE
Create stars rating component in CKeditor

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#4235]
Please create stars rating component in CKeditor , rating in them shall be halves
like "component-rating" component in Keditor

![capture1](https://user-images.githubusercontent.com/26510030/31876231-53c6f736-b7da-11e7-9439-59ce9476b95c.PNG)

**Comment by salehh93** [comment]
done

**Comment by salehh93** [comment]
note: You must upgrade for content-lib app to 1.1.8

**Comment by bradmac** [comment]
Text is wrong:

![image](https://user-images.githubusercontent.com/826458/31913831-e99fc038-b8a4-11e7-919e-0b175fd63c21.png)

Please change to just "XX stars". Eg
- 1 star
- 1.5 stars
- 2 stars
- etc

**Comment by bradmac** [comment]
Also, cannot edit the rating once its added to the page. It should have an edit option on the context menu:
![image](https://user-images.githubusercontent.com/826458/31914377-ea234816-b8a6-11e7-87df-f3dcde7f8a48.png)

**Comment by salehh93** [comment]
done 
can you double click  on stars for edit


note: You must upgrade for content-lib app to 1.1.9

**Comment by AlaaKhalaf94** [comment]
passed

**Comment by ducdhm** [comment]
@salehh93 Did you check in other browsers like IE? In general, we support IE9+ with minimum support. I have checked in your code and seem like you used multi-background for this component. I think it's incorrect. Can you check what @anhnt in his component?

**Comment by bradmac** [comment]
> can you double click on stars for edit

@salehh93 note that "double click" is not used is web editing. This feature should use standard framework integrations for ckeditor.

**Comment by ducdhm** [comment]
@bradmac @salehh93 How about just add font-awesome plugin for ckeditor? They already have star (http://fontawesome.io/icon/star-o/, http://fontawesome.io/icon/star/) and half-star (http://fontawesome.io/icon/star-half-o/, http://fontawesome.io/icon/star-half/). Users can choose color and font-size for star by theirself

**Comment by ducdhm** [comment]
FontAwesome plugins:
 * https://ckeditor.com/cke4/addon/fontawesome
 * https://ckeditor.com/cke4/addon/ckeditorfa

**Comment by bradmac** [comment]
it would be good to use fontawesome stars. 

the problem with images is that the colour is fixed, but we need the colour to be driven by the theme, ie LESS params

Should be easy to just replace the images with multiple spans with each star

**Comment by ducdhm** [comment]
Yeah, so what we need from this plugin:
 * Add rating config number of stars
 * Rated stars can be 1, 1.5, etc...
 * Total stars can be configurable and default is 5
 * Star icons are used font-awesome

**Comment by bradmac** [comment]
> Total stars can be configurable and default is 5

Not needed for now, maybe add in future when we have time

So should be just a small change :)

**Comment by salehh93** [comment]
done

**Comment by ducdhm** [comment]
@salehh93 A couples of comments of https://github.com/Kademi/kademi-dev/commit/1aed1ef6d59cb9d50068ff6e94b7bf8b715b87c5
1. You dont need `/static/jqte/jquery-te-1.4.0.css` and `/static/jqte/jquery-te-1.4.0.js` for this plugin. Please remove them
1. Line 194 has `alert`. You should remove it
2. Line 252  and 258, the group should be different. `imageGroup` is just for images element
3. Display text should be in Capitalize case. Example: `rating Properties` should be `Rating Properties`
4. Please format source code before pushing the code. We should have clean code with well comments for maintenance in future

**Comment by salehh93** [comment]
I am fixed all and the alert by mistake

**Comment by ducdhm** [comment]
@salehh93 I have checked this plugin and seem like it can't let me edit the rating.

![bug](https://user-images.githubusercontent.com/1289631/32205576-9412a7c4-be22-11e7-9c08-fa407688ee41.png)

![bug2](https://user-images.githubusercontent.com/1289631/32205579-96ba65fc-be22-11e7-85f5-191775eedc7e.png)

**Comment by ducdhm** [comment]
@salehh93 And one more thing, can you switch to span tag instead of a tag?

**Comment by salehh93** [comment]
now it's all good

**Comment by AlaaKhalaf94** [comment]
Here in home page : http://alaa-test24.admin.kademi-ci.co/pages/alaa-test24/version1/
I use the stars component and I see it as a link in website page with text-decoration underline style in hover 
and with this href "#rating-189799-1509629926187" appear in URL when I click on stars

![capture1](https://user-images.githubusercontent.com/26510030/32329332-6c893f8c-bfe5-11e7-8145-37f4e738247e.PNG)

@salehh93 , please remove the link frome stars

**Comment by ducdhm** [comment]
@salehh93 That's why I asked you change `a` tag to `span` tag

**Comment by bradmac** [comment]
I think this is ok now
