### ISSUE TITLE
OK button in Select image modal from CKeditor does not appear in its specified location

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#4236]
In Select image modal from CKeditor , OK button does not appear in its specified location
http://version1.alaa-test10.kademi-ci.co/contenteditor?fileName=index.html

![capture1](https://user-images.githubusercontent.com/26510030/31876619-fab86286-b7db-11e7-95ce-46a77c1c2b48.PNG)

**Comment by ducdhm** [comment]
Duplicated with https://github.com/Kademi/kademi-dev/issues/4085
