### ISSUE TITLE
New KCode fields

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4239]
Please create new fields in ContentApp
- currentYear: just return the current year, eg 2017. 
- accountTitle: the title of the current account (eg Organisation title)
- profilePrimaryOrgTitle: return the title of the organisation from the user's primary membership. If the user has multiple primary memberships just take the first.

These can be plain AbstractFields, with no ES support

**Comment by gonzalon** [comment]
There are 3 new options in the KCode dropdown:
- Current Year
- Account title
- Profile Org Title

![image](https://user-images.githubusercontent.com/2773216/31919662-84a272c2-b8c0-11e7-8094-cb2a53723083.png)

![image](https://user-images.githubusercontent.com/2773216/31919669-947223b4-b8c0-11e7-9fbb-35f08c2f2a01.png)

**Comment by AlaaKhalaf94** [comment]
passed
