### ISSUE TITLE
Experiments - we cant delete experiments,

### ISSUE THREAD

**Issue by Anton69arb** [Kademi/kademi-dev#4240]
Hey hey :)

Experiments - we cant delete experiments,

When clicking on the delete button, it states we should click on the experiment check box that we want deleted, the check box option is not available, please could we add one, thank you

![experiments - hey we cant delete experiments](https://user-images.githubusercontent.com/32444328/31912395-3ce9ee26-b8a0-11e7-8d10-2b438a4f0d3c.png)

http://antontest.admin.kademi-ci.co/experiments/927158

thank you!

**Comment by AlaaKhalaf94** [comment]
Attached picture is different from the link

- About attached picture , its work well with delete experiments : http://alaa-test16.admin.kademi-ci.co/experiments/

- About attached link , like this http://alaa-test16.admin.kademi-ci.co/experiments/1134572
there isn't check box to select which variant that I want to delete

![capture1](https://user-images.githubusercontent.com/26510030/32045405-cd392326-ba48-11e7-9e4b-3e64b15ec147.PNG)

Please fixed that @gonzalon

**Comment by gonzalon** [comment]
Ups sorry, misunderstood.
Now you can delete variants too.

![image](https://user-images.githubusercontent.com/2773216/32080589-140d43da-bb0d-11e7-91e5-2111f5b5d3ee.png)

**Comment by AlaaKhalaf94** [comment]
passed
