### ISSUE TITLE
Marks appear on page sometimes when creating a page and modifying the page components

### ISSUE THREAD

**Issue by Anton69arb** [Kademi/kademi-dev#4241]
This happen's sometimes, not sure what from,
what i did was create the page and when i moved some text around and moved pics and saved, these marks would appear,
can you take a look and see why please

if you move a pic around as the page is at the moment and save, it adds a new mark to it

http://antontest.admin.kademi-ci.co/pages/sweets-for-heavens/version1/

![this happen s sometimes not sure what from](https://user-images.githubusercontent.com/32444328/31916209-0edc04e8-b8ae-11e7-8b00-79f487b757a5.png)

**Comment by bradmac** [comment]
See gallery.html

**Comment by ducdhm** [comment]
https://github.com/Kademi/keditor/issues/71

**Comment by ducdhm** [comment]
Not sure why this happens but I added some codes for fixing incorrect structure so when you get these icons, you should go to contentEditor again and re-save it. The new code will help you remove these icons.

**Comment by Uafinder** [comment]
Looks ok, at the moment. Will keep an eye on it
