### ISSUE TITLE
KPI component for Moblix

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4242]
Login as this guy: http://moblix.admin.kademi-ci.co/manageUsers/698106/#summary-tab

Update KPI component:
1) Doughnut color Info
2) Must be transparent
3) Text white to show KPI title and level
5) The doughnut should show progress towards the level 

![image](https://user-images.githubusercontent.com/2201340/31921329-98c5e96a-b8ba-11e7-984d-5446d5884981.png)

PSD [KPIs employee.zip](https://github.com/Kademi/kademi-dev/files/1409294/KPIs.employee.zip)

BUG:
note this guy http://moblix.admin.kademi-ci.co/manageUsers/698106/#summary-tab

Has an achievement but the KPI component for time is not showing any data.

![image](https://user-images.githubusercontent.com/2201340/31921069-de95cb60-b8b8-11e7-9b4f-d95c338feb19.png)

Series and KPI http://moblix.admin.kademi-ci.co/sales/employee-time/#general-tab

**Comment by ducdhm** [comment]
Fixed!

**Comment by paddyow** [comment]
This profile http://moblix.admin.kademi-ci.co/sales/employee-time/#history-tab

Has two records http://moblix.admin.kademi-ci.co/sales/employee-time/#history-tab

- July 25 hours
- August 15 hours (processed)

The monthly KPI is 140 hours

1) The first July period they did not reach their target so should not be on track
2) The 2nd August period should show in progress but currently shows nothing (this period has not been processed)

Not sure if I have miss configured something, and for the data series 'units' not sure what this should be set to.

**Comment by bradmac** [comment]
@paddyow you can check their assessed periods from the admin:

http://moblix.admin.kademi-ci.co/sales/employee-time/kpis/hours/#results-tab

![image](https://user-images.githubusercontent.com/826458/31927492-dd3c54f4-b8f0-11e7-81f0-eaa83a1704ce.png)

This user did not reach any levels, and was not given any points

**Comment by ducdhm** [comment]
@bradmac This KPIs doesnt have baseline
![untitled](https://user-images.githubusercontent.com/1289631/31927582-fb820788-b8be-11e7-8805-5fc33da25465.png)

**Comment by bradmac** [comment]
@ducdhm It doesnt need a baseline

But @paddyow  looks like the problem is you havent selected a target for the ontrack status component:

![image](https://user-images.githubusercontent.com/826458/31927608-59aab7b0-b8f1-11e7-9536-44059f7c975c.png)

**Comment by bradmac** [comment]
But guys, lets make sure we dont say "On track" for past periods. Once a period is completed the user should be told if they achieved the target or not, it doesnt make sense to say they are "on track" if we know they did or did not achieve it.

**Comment by ducdhm** [comment]
@bradmac Yeah for sure. I think with current period, we can say `On Track` or `Off Track` but with processed period, should be `Achieved` or `Not achieved`.

Let me update them

**Comment by bradmac** [comment]
:+1:

**Comment by ducdhm** [comment]
@bradmac Please kindly help me to calculate completed percentages of assessed level

**Comment by bradmac** [comment]
@tuzzmaniandevil can you assist?

What we need is the ability to calc a percentage of the level specified on the KPI component for assessed periods.

We may neeed to add API support to KpiDataPage to find the value of a level for a participant for a specified period. Remember that targets can be static (as per this example) or dynamic (ie looked up from a dataseries)

And it might be nice to have a method which calculates the final percentage of the KPI result by using that method

**Comment by paddyow** [comment]
This profile peteremployee@mailinator.com

KPI Customer Satisfaction KPI
http://moblix.admin.kademi-ci.co/sales/employee-customer-satisfaction-index/#general-tab
- Has records for July only
- Total of 6 records
- Target = 8 (averaged)

* This user should not be on track for July (which looks correct)
* This user should not have any data for Aug and Sept but when the date picker is changed, the KPI doughnut does not update.  It should be null for Aug and Sept.

KPI time
http://moblix.admin.kademi-ci.co/sales/employee-time/#general-tab
- Has records for July, Aug, Sept
- Target of 140 hours per month
- July and aug were not reached
- Sept target was reached

*Currently all period are showing on track which is incorrect

**Comment by ducdhm** [comment]
Fixed!

**Comment by paddyow** [comment]
Change the status of each KPI to....

You're on track (when in progress)
You're not on track (when in progress)
You hit your target (when the period is over)
You did not reach your target (when the period is over)

**Comment by ducdhm** [comment]
@paddyow I'll make them configurable for you. So you can change to anything you want
