### ISSUE TITLE
Dashboard alerts are not displaying

### ISSUE THREAD

**Issue by Anton69arb** [Kademi/kademi-dev#4248]
Dashboard alerts are not displaying when a group is selected. When "None" is selected for the group, it does display

![dashboard is not working correctly](https://user-images.githubusercontent.com/32444328/31968329-536913b6-b96d-11e7-9a23-a80ddde7fc67.png)

http://version1.sweets-for-heavens.kademi-ci.co/dashboard

**Comment by AlaaKhalaf94** [comment]
passed
