### ISSUE TITLE
Google Maps Component: Can't select a result when using "Manually" option

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#4249]
The list seems to show behind the config panel, Using the allow keys on the keyboard seems to work. Also once i've selected an address using the keyboard it changes all the components on the page, Not just the one you have selected.

http://googlemapsbug.gilpinperformance.kademi.com.au//theme/contenteditor?fileName=defaultThemeTemplate.html

Reported by Celine from Gilpin.

**Comment by ducdhm** [comment]
Fixed!

**Comment by AlaaKhalaf94** [comment]
Hi @ducdhm , It doesn't work with me
I test here in "map" page : http://alaa-test23.admin.kademi-ci.co/pages/alaa-test23/version1/
When I try to select "Manually" option from Google Map Settings this popup appear

![capture1](https://user-images.githubusercontent.com/26510030/32314830-5f9b5112-bfb2-11e7-8294-2ae00d879a91.PNG)

and when I click on "ok" the map disappear

**Comment by ducdhm** [comment]
Fixed!

**Comment by AlaaKhalaf94** [comment]
passed
