### ISSUE TITLE
Cannot see menu items when editing defaultThemeTemplate

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4252]
http://moblix.admin.kademi-ci.co/pages/moblix-employees/version1/

![image](https://user-images.githubusercontent.com/2201340/31987294-159334aa-b9b7-11e7-9c21-463c21988d18.png)

**Comment by bradmac** [comment]
OK, probably related to class filter

**Comment by bradmac** [comment]
@tuzzmaniandevil would you like to look at this? i would say there is a class being denied which is used by the menu builder

**Comment by tuzzmaniandevil** [comment]
It's definitely getting the json from the server:
![screenshot-moblix-employees kademi-ci co-2017-10-26-09-43-23-039](https://user-images.githubusercontent.com/3378330/32022365-a4f14b84-ba32-11e7-84a3-8a94b600dac0.png)

**Comment by tuzzmaniandevil** [comment]
Turned out to be a class filter error. All fixed
