### ISSUE TITLE
Hosted Zones DNS: Validate on record creation to make sure an existing record doesn't exist

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#4256]

**Comment by mkhoudary** [comment]
@AlaaKhalaf94 please try to add a record.. in hosted zone.. then try to set the domain to match it in one of the sites.. then change to same domain with www prefix.. if the old records are deleted.. then the problem persists.. otherwise this is passed.

**Comment by AlaaKhalaf94** [comment]
Done

But it should show meaningful message when I create site with domain already exist
I test here : http://alaa-test.admin.kademi.com.au/websites/alaatest2/version1/#panel_details-tab

![capture1](https://user-images.githubusercontent.com/26510030/32699624-7884d4de-c7c1-11e7-9bd8-61554d5e3ee4.PNG)

**Comment by bradmac** [comment]
@tuzzmaniandevil please improve the validation response

**Comment by tuzzmaniandevil** [comment]
It will now show a field validation message under the domain name field

![image](https://user-images.githubusercontent.com/3378330/32752670-ef901444-c92e-11e7-9d2c-bc2bbbe14c68.png)

**Comment by AlaaKhalaf94** [comment]
passed
