### ISSUE TITLE
Achievement level progress component

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4257]
Create a component as part of the KRecognition app
- is configured for a topic
- displays the current level for the user
- displays progress towards the next level as a circle
- displays a background color and icon from the current level

![clipboard - october 26 2017 10-35 am](https://user-images.githubusercontent.com/826458/32033305-600adb12-ba68-11e7-8029-9251be4464ed.png)

**Comment by bradmac** [comment]
This is using the same markup as the KPI ontrack component, but i havent integrated CSS

![image](https://user-images.githubusercontent.com/826458/32029716-d229dd3a-ba52-11e7-87f1-d47bffcd75a5.png)

**Comment by bradmac** [comment]
Functional integration:
![image](https://user-images.githubusercontent.com/826458/32029845-94706e72-ba53-11e7-8036-e7c397ede7f2.png)

**Comment by bradmac** [comment]
And can now set colours on a level:
![image](https://user-images.githubusercontent.com/826458/32030138-7b2c4e70-ba55-11e7-9000-95d6dbbfc19d.png)

**Comment by bradmac** [comment]
@ducdhm can you complete front end integration please?

**Comment by ducdhm** [comment]
Done!

**Comment by paddyow** [comment]
- At the Topic name under the circle so it matches KPIs
- Make the progress bar the next level color

This user http://moblix.admin.kademi-ci.co/manageUsers/698106/#summary-tab
Has 180 hours recorded for time

Levels are http://moblix.admin.kademi-ci.co/recognition/1114291/
- Bronze 100
- Silver 200
- Gold 300

The bar does not look like it is 80% towards the next level.

![image](https://user-images.githubusercontent.com/2201340/32037887-23629046-ba73-11e7-8255-682e99060bd4.png)

**Comment by ducdhm** [comment]
Done!
