### ISSUE TITLE
Promotions picture upload issue

### ISSUE THREAD

**Issue by gonzalon** [Kademi/kademi-dev#4258]
By default when we enable the app enable  User uploads image

I can't upload a image:
![image](https://user-images.githubusercontent.com/2773216/32026141-77ee5818-ba3f-11e7-90de-3ac8e01be326.png)

To be able to do that I need to change the component settings to "Show user's photo" 
![image](https://user-images.githubusercontent.com/2773216/32026209-d568931e-ba3f-11e7-8fbf-33ec45a39b54.png)

Component:
competitionFormComponent

**Comment by ducdhm** [comment]
Fixed!

**Comment by gonzalon** [comment]
Seems ok!
