### ISSUE TITLE
modal is not big enough, cant view the text and picture

### ISSUE THREAD

**Issue by Anton69arb** [Kademi/kademi-dev#4260]
issue: modal is not big enough, cant see the text and picture,
could we please make it bigger or have a click and pull button option to make it to a custom/inter-changeable window size please

its on every modal window - so if you able to do it for the entire kademi platform

![issue modal is not big enough cant see the text and picture](https://user-images.githubusercontent.com/32444328/32030495-c49ab3a6-ba57-11e7-8a0d-eaac810c1531.png)

**Comment by bradmac** [comment]
Please add the modal-lg class

**Comment by Uafinder** [comment]
looks ok at the moment
