### ISSUE TITLE
ranking engagement in journeys

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4261]

**Comment by bradmac** [comment]
Here's an example config:

```
{
   ...
  "scoringFactors" : [ {
    "leadScoringFactorTypeId" : "emailResponse",
    "properties" : {

    },
     "boost" : 3.5
  },
  {
    "leadScoringFactorTypeId" : "webActivity",
    "properties" : {
      "path" : "/dashboard"
    },
     "boost" : 2.0
  }],
  "preferentialJobTitles" : null
}
```

**Comment by bradmac** [comment]
@anhnt can you assist with the UI of manageFunnel.html

![image](https://user-images.githubusercontent.com/826458/32153183-c40799e8-bd8d-11e7-8f45-dd44e44227aa.png)

**Comment by anhnt** [comment]
done

**Comment by bradmac** [comment]
I'll add some more scoring factor types
- reward store
- ecom

**Comment by bradmac** [comment]
Supported factors:
![image](https://user-images.githubusercontent.com/826458/32203997-9793e06a-be4b-11e7-94b8-c108fcda066c.png)

**Comment by bradmac** [comment]
Integrated ranked listing with the admin leads page:
![image](https://user-images.githubusercontent.com/826458/32204714-ca05561a-be4f-11e7-8fa1-512c00db8559.png)

**Comment by bradmac** [comment]
Still need to integrate with search fields, and then use in LeadMan front end

**Comment by bradmac** [comment]
Integrated with leadman dashboard:
![image](https://user-images.githubusercontent.com/826458/32358754-7bccf5a6-c0ad-11e7-8ae5-7a0ea2f83bfa.png)

**Comment by bradmac** [comment]
@ducdhm please add a readonly column for the score:

![image](https://user-images.githubusercontent.com/826458/32358796-ca1e24dc-c0ad-11e7-94dc-92f3d523bf91.png)

**Comment by anhnt** [comment]
done
![image](https://user-images.githubusercontent.com/735555/32360580-e99f9e4a-c089-11e7-92c5-57b0062bb7b5.png)
