### ISSUE TITLE
Cannot delete learner registration journey

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4262]
http://moblix.admin.kademi-ci.co/funnels/

**Comment by paddyow** [comment]
Ok so it looks like it will only allow me to if all the leads are deleted.  Is this intended?

**Comment by bradmac** [comment]
I've just checked with a funnel which has leads. It was able to delete the funnel successfully.

Can you please let me know which funnel you cant delete?

**Comment by paddyow** [comment]
I tested with another account and was able.  The prior journey I deleted after removing the lead.  Will close the issue as I cannot reproduce.
