### ISSUE TITLE
Upload fields buttons for funnels doesn't work well

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#4264]
From view lead page : http://alaa-test16.admin.kademi-ci.co/leads/1123990/#information-tab

- Upload button doesn't work never
- Delete button shows wrong popup say "Saved OK!" , and doesn't delete file

![capture1](https://user-images.githubusercontent.com/26510030/32043545-b9b4e0d8-ba43-11e7-8186-ce6c6b28e657.PNG)

**Note** : The file that I try to delete , I've uploaded it from the website : http://version1.alaa-test16.kademi-ci.co/leads/1123990/

depends on : https://github.com/Kademi/kademi-dev/issues/3478

**Comment by AlaaKhalaf94** [comment]
Hi @gonzalon , Here : http://alaa-test19.admin.kademi-ci.co/leads/1234336/#information-tab 
I see the same problem that I wrote here for you : https://github.com/Kademi/kademi-dev/issues/3478#issuecomment-340706014

**Comment by AlaaKhalaf94** [comment]
Hi @gonzalon , now it work well with me , but there is a little improvement in appearance
please add margin-bottom to name of file uploaded , I think 6px to be fine

![capture1](https://user-images.githubusercontent.com/26510030/32602852-5abe48a4-c550-11e7-98c4-d2346872177c.PNG)

**Comment by bradmac** [comment]
And please use button group :)

**Comment by AlaaKhalaf94** [comment]
passed
