### ISSUE TITLE
Showing more details during table importing

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#4267]
I have noticed that the returned JSON while pulling the current table import status returns:
"updatedCount":##,"deletedCount":##,"errorCount":##,"createdCount":##"

It would be good to show those records under the progress bar so the user importing data could get notified if something is going wrong, especially when importing huge amount of data.

**Comment by tuzzmaniandevil** [comment]
![image](https://user-images.githubusercontent.com/3378330/32084700-2f0d877a-bb27-11e7-935c-32eea2f3a9b1.png)

**Comment by Uafinder** [comment]
Works perfect
