### ISSUE TITLE
Update admin funnel management page, to move leads to a seperate page

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4269]
This should improve performance of the management page and make it easier to enhance lead searching

**Comment by bradmac** [comment]
New manage lead page - 
![image](https://user-images.githubusercontent.com/826458/32081936-c5b5f490-bb14-11e7-8557-9380db9a7563.png)

**Comment by bradmac** [comment]
New leads page:

![image](https://user-images.githubusercontent.com/826458/32081963-e6927f76-bb14-11e7-91b3-198cda6b6fc5.png)

**Comment by Uafinder** [comment]
1. Paginator should be implemented. Only 10 leads are showing on the page.
![image](https://user-images.githubusercontent.com/1945230/32266960-30be6eda-bef2-11e7-9f2a-b39500f5635c.png)

2. What is the score parameter?

3. Is there should be bottom com.fuselms.apps.funnels.manage... stuff?

4. Sorting by email, date, stage would be good.

5. When you edit some lead, and then try to go back, you're getting to the invalid leads page.
![image](https://user-images.githubusercontent.com/1945230/32267031-802970e6-bef2-11e7-94a1-097ecbbd7d14.png)
![image](https://user-images.githubusercontent.com/1945230/32267046-8c3bd446-bef2-11e7-8f79-ed7b484f53ff.png)
![image](https://user-images.githubusercontent.com/1945230/32267051-955ea602-bef2-11e7-8ff9-9c7f826a4f3a.png)

6. Delete lead button does nothing.

7. Bulk delete function would be good.

**Comment by bradmac** [comment]
> What is the score parameter?

Thats our exciting new feature, see here - https://github.com/Kademi/kademi-dev/issues/4261

**Comment by bradmac** [comment]
@gonzalon please make this page more awesome

**Comment by gonzalon** [comment]
1- Pagination added, the default page size its 100. 
3- Removed

**Comment by gonzalon** [comment]
- 1 Pagination added, the default page size its 100. 
- 2 --
- 3 Removed
- 4 Done
- 5 It's taking you to the "All leads" page. Why is invalid? 
- 6/7 Updated as the same style in the other leads page

**Comment by Uafinder** [comment]
1. Pagination ok, there is no possibility to change page size.
![image](https://user-images.githubusercontent.com/1945230/32548404-32b82716-c48e-11e7-80d6-26105b0fd107.png)
2. ok
3. ok
4. Sorting works ok, but when you click some header to sort - sorting ended successfully, but Kademi ico blinking constantly. 
![image](https://user-images.githubusercontent.com/1945230/32548546-b7fd0a72-c48e-11e7-9255-f77e5ce332f6.png)
5. I'm on journey1 leads page, e.g. http://vlad-test36.admin.kademi-ci.co/funnels/journey1/version1/leads/ , but when i'm going back I getting to All leads page, e.g. http://vlad-test36.admin.kademi-ci.co/leads/ . That's not right.
6. ok

**Comment by bradmac** [comment]
> I'm on journey1 leads page, e.g. http://vlad-test36.admin.kademi-ci.co/funnels/journey1/version1/leads/ , but when i'm going back I getting to All leads page, e.g. http://vlad-test36.admin.kademi-ci.co/leads/ . That's not right.

What do you mean by "going back"? Do you mean clicking the back button on your web browser? If so that will take you to whatever page you viewed previously.

**Comment by gonzalon** [comment]
The date issue and other minor issues fixed.
I talked with Brad and the link in the breadcrumbs can stay like that.

**Comment by gonzalon** [comment]
Found two issues:
- when the funnel was created, if you go directly to the leads page would throw a NPE.
- the list wasn't filtering by funnel, so you would see the leads in all funnels!

**Comment by Uafinder** [comment]
Both confirmed

**Comment by Uafinder** [comment]
About those ones which were fixed - they are ok

**Comment by gonzalon** [comment]
Both are fixed, it's filtering and for the new journey:
![image](https://user-images.githubusercontent.com/2773216/32703553-957b4ab4-c85c-11e7-9938-339286ee2843.png)

**Comment by Uafinder** [comment]
looking great, page size moved to separate
