### ISSUE TITLE
ecom products list component, layout breaks in list mode

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4272]
![image](https://user-images.githubusercontent.com/826458/32139122-712b4ef4-bc9d-11e7-8db3-3c27bb1bfb1d.png)

Screeen shot from here - http://milton.io/milton-store/ - but i need to update that site to work now

**Comment by anhnt** [comment]
cant reproduce above issue but i can see another bug when layout is grid
![image](https://user-images.githubusercontent.com/735555/32368105-319dd0ea-c0b7-11e7-8f74-96f5e762009d.png)

**Comment by anhnt** [comment]
fixed
![image](https://user-images.githubusercontent.com/735555/32369036-542fece4-c0ba-11e7-9c62-af17275c4f89.png)
![image](https://user-images.githubusercontent.com/735555/32369055-62b79fb4-c0ba-11e7-9925-28b36a0c3da5.png)

**Comment by AlaaKhalaf94** [comment]
passed
