### ISSUE TITLE
Leads manage page quick edit need enhancement

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4277]
http://vlad25-leads.kademi-ci.co/leads/?query=&leadType=active
1. Go to the leads page
2. Try to change source value.
3. If it was empty it will be filled out by first from list.
4. If it's not your choice (for example you need another source) everything will be ok, but if it is your choice, and you just leave cell - it will not save value. So you will need to setup incorrect value and then change it to correct.
![image](https://user-images.githubusercontent.com/1945230/32164273-a63caa14-bd67-11e7-8f8d-477072520473.png)
![image](https://user-images.githubusercontent.com/1945230/32164281-aefd1f4e-bd67-11e7-9947-31dcaad91a0e.png)

**Comment by bradmac** [comment]
@ducdhm maybe we should change from a select input to a bootstrap button dropdown? then we can save on click. We could do onclick with a select as well, but the problem is a user can scroll through the list so can select without clicking.

**Comment by anhnt** [comment]
added a placeholder so that the first option will not be selected at the first time
![image](https://user-images.githubusercontent.com/735555/32270398-5fc0fadc-bf28-11e7-9c07-4b1594a2bde9.png)

**Comment by Uafinder** [comment]
There is a minor bug:
When you're accessing column for a first time, it shows choose $columnname$ (e.g. choose stage), even for filled cell.
When you're accessing column for the second time - it shows a value for filled cell and choose $columnname$ for empty cell and that's correct.
First time
![image](https://user-images.githubusercontent.com/1945230/32319660-03aa6fde-bfc4-11e7-9d43-11d8e526499f.png)
![image](https://user-images.githubusercontent.com/1945230/32319670-0b0df76e-bfc4-11e7-8003-857bae5cb372.png)
Further times
![image](https://user-images.githubusercontent.com/1945230/32319690-19f7d72c-bfc4-11e7-8d4c-eca9322fc7b5.png)

http://vlad30-leads_vlad-test30.kademi-ci.co/leads/?query=&leadType=active

**Comment by anhnt** [comment]
Fixed please test again

**Comment by Uafinder** [comment]
It works with bugs!
Often when you change several amounts in column it changes value incorrectly.
I wrote a video, which show this problem and the problem with score amount disappears...
https://drive.google.com/open?id=1XI0vgXXqfP3Q1v5Yn3RnJTSewNbgeRtW

**Comment by anhnt** [comment]
I could not reproduce. it does save values correctly for me

**Comment by bradmac** [comment]
@Uafinder I also followed the steps in the video, and it worked correctly

**Comment by Uafinder** [comment]
Found a problem, this is a sorting issue
The thing is, that if deal amount is not filled yet - it's null. When you are using quick edit feature it sets deal amount to "0", not null. And if you don't sort leads list manually, when you edit some lead it jumps somewhere up and think that it enter some mess.

**Comment by anhnt** [comment]
I think we should temporary disable sorting when editing a row. So user just need to click sort again if needed

**Comment by bradmac** [comment]
Guys, thats not a problem worth solving. Users are able to edit the table just fine as it is now. It will initially be unexpected, but then users will understand its being sorted and that is actually correct.

**Comment by Uafinder** [comment]
closing
