### ISSUE TITLE
Content of page is disappear when I change the title from its Properties

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#4278]
I create page and I put code on it , then I try to change the title from its properties
After that when I view the page , the content of page is disappear

To reproduce this issue , do the following , please:
- Here : http://alaa-test18.admin.kademi-ci.co/pages/alaa-test18/version1/ , make view to "page-five"
- Change its title
- View the page again , you'll see that the content disappear

The problem is happening just when I create the page just by writing code , when I create page by creating components the problem doesn't happen

**Comment by ducdhm** [comment]
@bradmac The main issue of it is because Alaa used custom template which does not exist in Page template list. So everytime she edit properties of page in Edit web page screen, the template is save with other value. So what should we do with this case?

**Comment by bradmac** [comment]
> The main issue of it is because Alaa used custom template which does not exist in Page template list

@ducdhm i can see one custom template:
![image](https://user-images.githubusercontent.com/826458/32248489-b780251a-beea-11e7-890d-c0f4de6792cd.png)

And i can see that this is in the page template list:
![image](https://user-images.githubusercontent.com/826458/32248510-c7a2148a-beea-11e7-8066-ae0d7a402758.png)

So can you please confirm what you mean about the template not being in the list?

**Comment by bradmac** [comment]
I've just checked that i can edit the page title without losing content. So i cannot reproduce any problem

![image](https://user-images.githubusercontent.com/826458/32248631-1d3e9bb6-beeb-11e7-9a92-7943c2ee2f57.png)

![image](https://user-images.githubusercontent.com/826458/32248638-25105366-beeb-11e7-9c14-64ec62251eaa.png)

**Comment by ducdhm** [comment]
@AlaaKhalaf94 I also checked same way as @bradmac, I can't reproduce your issue too. Can you double-check again?

**Comment by mkhoudary** [comment]
The page that Alaa encountered the problem with was written outside of the pages page, so the used template wasn't listed.. and we shouldn't create a page in a manual way that doesn't comply with the UI builder.
