### ISSUE TITLE
Ecom store error

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#4279]
http://anh.admin.kademi-ci.co/ecommerce/my-store/#general-tab

![image](https://user-images.githubusercontent.com/735555/32166732-556d0692-bd99-11e7-9aec-369a751f90b8.png)

**Comment by anhnt** [comment]
This error occurs when a product with empty price is added to ecom store

**Comment by bradmac** [comment]
@tuzzmaniandevil please also refactor the ecom manage store page to be the same as reward stores, ie with a sepereate view for adding products

**Comment by Uafinder** [comment]
Error fixed.
About Refactoring to be similar to reward store:
1. "Remove selected" button should be added
2. Removing and adding product via checkboxes should be removed.
![image](https://user-images.githubusercontent.com/1945230/32731123-b0da86d2-c891-11e7-9c8a-e3552fc08971.png)

**Comment by Uafinder** [comment]
Looks ok
