### ISSUE TITLE
KEditor images bugs

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4280]
1. When you set image to align, it doesn't show alignment in editor body and editor summary.
![image](https://user-images.githubusercontent.com/1945230/32171209-0a51b612-bd80-11e7-8af9-574b52c2ffc3.png)
![image](https://user-images.githubusercontent.com/1945230/32171399-9f255d84-bd80-11e7-99d1-1bf5bbbc5eb9.png)
Result will be such kind.
![image](https://user-images.githubusercontent.com/1945230/32171425-aefc479a-bd80-11e7-93a5-9b307a55bcc6.png)

2. Image disappears when edit it.
You have an image added to page.
You're going to edit it's size for example. Going into image and change size, and press ok. But image will not appears.
![image](https://user-images.githubusercontent.com/1945230/32171539-2a888fa4-bd81-11e7-8942-d9155137d4a1.png)
![image](https://user-images.githubusercontent.com/1945230/32171616-67ce1398-bd81-11e7-9342-9b50d201c141.png)
Page should be refreshed to see that effect.

But when you select uploaded image from the left list and than change size from original size all will be ok.

http://vlad-test20.admin.kademi-ci.co/groupEmails/854540/edmeditor?fileName=index.html&useHash=true

**Comment by ducdhm** [comment]
@Uafinder 

`1.` Here is what I got and seem like it's ok. Doesnt look like your screen shot

![aaaa](https://user-images.githubusercontent.com/1289631/32595372-4c8b8668-c562-11e7-8758-b20f6b98bcd5.png)

`2.` Fixed!

**Comment by Uafinder** [comment]
2. YEah, it's ok
1. probably I've just got to specific image size which looks like on my screen
so, it ok
