### ISSUE TITLE
Email send page enhancement for pop-ups.

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4281]
For creation it works great.
![image](https://user-images.githubusercontent.com/1945230/32172298-c7102d4e-bd83-11e7-9994-18592ef9a43e.png)
But for deletion it wrote it's ID.
![image](https://user-images.githubusercontent.com/1945230/32172315-d6b8a5dc-bd83-11e7-98b6-69f90834785c.png)
http://vlad-test24.admin.kademi-ci.co/groupEmails/

The same thing with templates.

Also would be great to add email job name when deleting asks Are you sure...
![image](https://user-images.githubusercontent.com/1945230/32172392-172e49c8-bd84-11e7-9c95-66638d8b175f.png)

**Comment by anhnt** [comment]
Done

**Comment by Uafinder** [comment]
It works!
