### ISSUE TITLE
Create organisation - org type dropdown is empty

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4282]
![image](https://user-images.githubusercontent.com/1945230/32173685-7701954a-bd88-11e7-955d-cb50711ebffb.png)
http://vlad-test24.admin.kademi-ci.co/organisations/
1. Create organization - there is no possibility to specify org type while creating. When editing - all seems to be fine.

2. Probably would be good to change modal header to Add new organisation not Edit organisation.
![image](https://user-images.githubusercontent.com/1945230/32173963-3a7bb384-bd89-11e7-8f56-5a8407b48403.png)

**Comment by bradmac** [comment]
> Create organization - there is no possibility to specify org type while creating.

Fixed

**Comment by bradmac** [comment]
> Probably would be good to change modal header to Add new organisation not Edit organisation.

Fixed

**Comment by Uafinder** [comment]
It works!
