### ISSUE TITLE
SKU's page import/export button and dropdown does nothing

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4284]
![image](https://user-images.githubusercontent.com/1945230/32174992-20eee320-bd8c-11e7-9ac6-3681c3f5b082.png)
http://vlad25-test.admin.kademi-ci.co/skus/

**Comment by gonzalon** [comment]
This was fixed 

![image](https://user-images.githubusercontent.com/2773216/32639214-a548f84c-c627-11e7-9ae7-9b75875b2231.png)

**Comment by Uafinder** [comment]
Yup, it's ok
