### ISSUE TITLE
Add support for new website name structure {websiteName}_{adminOrgId}

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#4285]
We will still need to support the original structure of `{websiteName}.kademi.com.au` but also the new structure `{websiteName}_{adminOrgId}.kademi.com.au`

This is so a website name isn't unique across the platform, But only for an account. This makes restoring a backup from one account to another much easier where you want to keep the website name the same.

**Comment by Uafinder** [comment]
for example you logged in to site
http://version1.vlad26-learn_vlad-test26.kademi-ci.co/dashboard
when you change it to http://version1.vlad26-learn.kademi-ci.co/dashboard (for example it has some old link) system asks for enter credentials
Looks like incorrect, site is not changing.

**Comment by tuzzmaniandevil** [comment]
@Uafinder Both links asks me to login. Maybe you are logged into the top one already. Remember login details are specific to the domain name, So if the domain name changes you won't be logged in anymore.

Once I logged into both links they site was the same

**Comment by bradmac** [comment]
@Uafinder it is expected that the login state on one domain will not apply to a different domain, even when they represent the same underlying website

**Comment by Uafinder** [comment]
Understood
