### ISSUE TITLE
KEditor container don't allow edit content

### ISSUE THREAD

**Issue by gonzalon** [Kademi/kademi-dev#4288]
The container had this class `.keditor-highlighted-dropzone` in the column settings:

Which didnt allow to edit the content itself.

I deleted that, saved and now I'm seeing `keditor-sub-container-content` class and working fine.

Site: http://versionnew.gilpinperformance.kademi.com.au/contenteditor?fileName=our-team-test.1.1.1.html

**Comment by anhnt** [comment]
cant reproduce with latest k-theme

**Comment by gonzalon** [comment]
Hey @anhnt I'm not sure how to reproduce this... the user only updates the site by the editor, so probably the class was added by the editor but at some point wasn't removed and then saved with it.

For ex. if I add the class manually and save it, after that I can't modify the content

![image](https://user-images.githubusercontent.com/2773216/32352190-02feb61e-c085-11e7-9c32-6cc1ffb9dbd9.png)

**Comment by anhnt** [comment]
@gonzalon please tell me if you can reproduce it again. I tried several times but not able to reproduce it

**Comment by gonzalon** [comment]
Closing it for now
