### ISSUE TITLE
Training results search field should be wider and it's not work at all

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4291]
![image](https://user-images.githubusercontent.com/1945230/32215202-fd427902-be29-11e7-88cc-ca6107683df4.png)
http://vlad-test26.admin.kademi-ci.co/training/?startDate=25%2F10%2F2017&endDate=31%2F10%2F2017

1. Should be wider
2. Context search is not work. When press enter search are initiated but find nothing.

**Comment by tuzzmaniandevil** [comment]
1. Fixed (Specific to firefox Urg..)
2. Search works but only searches on the profile and and email
![image](https://user-images.githubusercontent.com/3378330/32640625-80f51dfc-c62e-11e7-8912-cac7a393ca8e.png)

**Comment by Uafinder** [comment]
It works!
