### ISSUE TITLE
Table uploaders minor bug

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4292]
1. Access any table uploader
2. Upload file
3. Do some import
4. Then leave page and then go back to table uploader again.
5. It will show you error with "Please upload file first" thing.

![image](https://user-images.githubusercontent.com/1945230/32216393-948ef0d0-be2d-11e7-93f9-b88ca8ee943a.png)

http://vlad-test26.admin.kademi-ci.co/tableUploaders

**Comment by Uafinder** [comment]
Product uploader for example:
![image](https://user-images.githubusercontent.com/1945230/32895908-38d0ffd0-caea-11e7-8fae-1726d888099c.png)
http://vlad-test52.admin.kademi-ci.co/tableUploaders/productsUploader

**Comment by anhnt** [comment]
i doubled check this but seems not be able to reproduce. Looks like it was fixed

**Comment by Uafinder** [comment]
Could not reproduce... closing...
Will take an eye on it...
