### ISSUE TITLE
Import users button doesnt work

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4294]
![image](https://user-images.githubusercontent.com/826458/32257424-e9706c22-bf19-11e7-80b1-84fbd30e6e13.png)

Note there are no messages in console log

http://travelworld.admin.kademi.com.au/tableUploaders/usersUploader

**Comment by bradmac** [comment]
[example-iser.xlsx](https://github.com/Kademi/kademi-dev/files/1432930/example-iser.xlsx)

**Comment by ducdhm** [comment]
Fixed!

**Comment by ducdhm** [comment]
Issue here is we force `min=1` for startRow textbox. So in your example excel file, startRow is 0 and browser prevents our form submit because of invalid value.
