### ISSUE TITLE
Group emails time to send

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4295]
Please add a feature for group emails to be sent at a particular date/time
- add a date/time field to group email properties
- when the email is sent, emails should be generated normally
- but emails should only be sent after that date/time is passed, or its null

Two ways to do this
- copy the date/time field to each email item and make it a restriction in EmailItem.findToSend
- OR, create the new col in BaseEmailJob and use a join

The second option might be better because then if the user wanted to change it after generating emails they can easily  do that

**Comment by Uafinder** [comment]
Some kind of time zone bug, or some sort
I have an org, with time zone setup: Kiev
http://vlad-test55.admin.kademi-ci.co
1. create a new group email
2. enter some data inside, enter time to send in 15 minutes
3. Save
4. Leave page (go to dashboard for example) and return.
5. Note that data changes to -11 hours from specified time.

**Comment by Uafinder** [comment]
it's not fixed.
Fresh account
http://vlad-test58.admin.kademi-ci.co/groupEmails/2099434/#sendInfo-tab
Still adding -11 hours to current result.

**Comment by tuzzmaniandevil** [comment]
Should be fixed now. Please keep in mind the timezone thing isn't related to this issue.

**Comment by Uafinder** [comment]
It doesn't work at all at the moment...
1. Create email
2. Edit params, enter some subject, content, set time to +5 minutes
3. Save
4. Refresh page for email, time will set back to -11 hours.
And one more, if you push send, emails will not be fired.

**Comment by tuzzmaniandevil** [comment]
Please can you provide more details? Which time are you talking about?
Testing locally I can set a "Time to send" and click send, It generates the emails and then sends the emails when it reaches the "Time to send" time

**Comment by bradmac** [comment]
@tuzzmaniandevil I followed Vlad's instructions and saw the same result he described.

I selected the current time plus 5 minutes (18:09), then saved, then refreshed and i see this:

![image](https://user-images.githubusercontent.com/826458/33196106-25685c64-d142-11e7-804a-62635e26abf2.png)

**Comment by bradmac** [comment]
Note that Vlad's account has a timezone set:

![image](https://user-images.githubusercontent.com/826458/33196114-43256724-d142-11e7-9ea1-26fbed87b4d7.png)

So looks like we're not consistently applying the timezone to parse/display the time

**Comment by tuzzmaniandevil** [comment]
We weren't taking the timezone into account when saving. Fixed now

**Comment by Uafinder** [comment]
Great! it works at the moment
