### ISSUE TITLE
Incorrect link for preview for promotion page 

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4297]
![image](https://user-images.githubusercontent.com/1945230/32269911-898d6ffc-befc-11e7-9639-a6571b7dfb87.png)
![image](https://user-images.githubusercontent.com/1945230/32269917-8ec7d322-befc-11e7-8c1c-e533b436168c.png)
http://vlad-test27.admin.kademi-ci.co/rewards/promo1/#entryForm-tab

**Comment by tuzzmaniandevil** [comment]
Fixed

**Comment by Uafinder** [comment]
looks ok at the moment!
