### ISSUE TITLE
Promotion page - can't submit enter because

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4298]
![image](https://user-images.githubusercontent.com/1945230/32271837-679bab54-bf04-11e7-95a7-9da83b5b66d7.png)
![image](https://user-images.githubusercontent.com/1945230/32271939-c2d9b0ba-bf04-11e7-8bde-a923356eca1f.png)

Just a simple entry form for anonymous user but it can be submitted. Please note, that user fields are not visible. probably it could be dedicated to developing separate promotion component. There are same trouble.
http://vlad27-promo_vlad-test27.kademi-ci.co/rewards/promo1/

**Comment by gonzalon** [comment]
https://github.com/Kademi/kademi-dev/commit/d6a41f2b1544e91be1d9d1b36bcb8413c025e2c4

@Uafinder now if it's an anon form by default would show you the fields for the user information:

![image](https://user-images.githubusercontent.com/2773216/32477658-b9b7a35e-c3e4-11e7-9ee1-4a112f331643.png)

If you remove all the fields in the settings of the component  and submit the form now shows a user friendly msg

![image](https://user-images.githubusercontent.com/2773216/32477704-de62178e-c3e4-11e7-99bf-bb25414df1db.png)


Please test with the latest rewards-lib, version 1.1.0

**Comment by Uafinder** [comment]
Looks ok!
