### ISSUE TITLE
NPE when using VouchersApp

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#4299]
When booking a voucher, an NPE is thrown and the import fails.

**Comment by mkhoudary** [comment]
Fixed

**Comment by Uafinder** [comment]
What user, where, where it happened?

**Comment by bradmac** [comment]
Hey @Uafinder we just need to check voucher validation and redemption in front end sites

To do that
- create a website
- enable the vouchers app
- make sure the website is within an org account which is the redeeming org for a voucher type
- make sure you login as a user with voucher redeemer role
- allocate a voucher frmo admin
- verify you can search for and find that voucher in the front end

Here is a live example:
Login as http://accor.admin.kademi.com.au/manageUsers/79444959/#summary-tab

![image](https://user-images.githubusercontent.com/826458/32629404-f540a8ec-c5fd-11e7-88e1-feadb0fb7ce0.png)

![image](https://user-images.githubusercontent.com/826458/32629448-1b2a464e-c5fe-11e7-915c-8822114a0ed9.png)

**Comment by Uafinder** [comment]
It works!
