### ISSUE TITLE
My rewards link appears even rewards app is not enabled

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4300]
![image](https://user-images.githubusercontent.com/1945230/32275833-5e4cdc92-bf15-11e7-9b32-c4aea3cf8705.png)
http://vlad29-learn_vlad-test29.kademi-ci.co/myLearning
http://vlad-test29.admin.kademi-ci.co/websites/vlad29-learn/version1/#panel_apps-tab

**Comment by bradmac** [comment]
Unfortunately that currently comes from the elearning app.

But i think we can move it to rewards and promotions

**Comment by bradmac** [comment]
Should be done now

**Comment by Uafinder** [comment]
looks great!
