### ISSUE TITLE
Live button from manage courses and manage modules pages gives error

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4301]
![image](https://user-images.githubusercontent.com/1945230/32278240-bf517fe0-bf1d-11e7-898f-e5f0344513ed.png)

![image](https://user-images.githubusercontent.com/1945230/32278229-b59d36d8-bf1d-11e7-9fd6-afe7e8d48aec.png)

http://vlad-test29.admin.kademi-ci.co/websites/vlad29-learn/version1/programs/p1/c1/

http://vlad-test29.admin.kademi-ci.co/websites/vlad29-learn/version1/programs/p1/c1/m2/#files-tab

**Comment by anhnt** [comment]
fixed

**Comment by Uafinder** [comment]
It works!
