### ISSUE TITLE
Promotion save issue

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4302]
![image](https://user-images.githubusercontent.com/1945230/32280857-d7fd0a34-bf25-11e7-8bfe-a9ff4bfdc1ba.png)
Probably due to this one:
The host name version1_vlad-test29.vlad29-promo.kademi-ci.co was not found on this server, or its license is invalid

http://vlad-test29.admin.kademi-ci.co/rewards/promo2/#details-tab

**Comment by bradmac** [comment]
Cant reproduce. Saves ok for me:

![image](https://user-images.githubusercontent.com/826458/32296126-3078a882-bfb0-11e7-8209-d009d5537db2.png)

**Comment by Uafinder** [comment]
It works
Probably used an old lib... need to update base lib
