### ISSUE TITLE
When uploading photo without specifying folder fails

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4303]
![image](https://user-images.githubusercontent.com/1945230/32281600-f4453dc2-bf27-11e7-83c2-a193de0e9752.png)
For example here:
http://vlad-test10.admin.kademi-ci.co/products/product090/#panel-brief-tab
Just try to upload image without selecting folder to the left. And it will continue forever.

**Comment by bradmac** [comment]
Currently the image dialog is querying this url:
http://vlad-test10.admin.kademi-ci.co/repositories/products/_DAV/PROPFIND?fields=name

For example, when editing:
http://vlad-test10.admin.kademi-ci.co/products/product090/

@ducdhm can you update this to use version1 of the products repo? or even better get it to lookup the live branch.

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
Yup, it works!
