### ISSUE TITLE
Edit report link is incorrect when the live version isnt "version1"

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4306]
Eg
https://carters.admin.kademi.com.au/reporting/month-end

This links to 
https://carters.admin.kademi.com.au/repositories/queries/version1/contenteditor?fileName=month-end.html

The edit link should use the live version name of the queries repo

**Comment by anhnt** [comment]
fixed

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/32330696-8a3f0da0-bfe9-11e7-9f37-cde1c6ea5261.png)
https://carters.admin.kademi.com.au/repositories/queries/version1/contenteditor?fileName=month-end.html

Looks the same

**Comment by anhnt** [comment]
This will need to wait for next AU deployment

**Comment by Uafinder** [comment]
FYI
![image](https://user-images.githubusercontent.com/1945230/32372658-7a48906e-c09e-11e7-80c2-43f79da250df.png)

**Comment by Uafinder** [comment]
it works!
