### ISSUE TITLE
Points credits and debits points do not appear to match database

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4308]
Points report:
https://carters.admin.kademi.com.au/reporting/points

Points debit report:
https://carters.admin.kademi.com.au/reporting/pointsDebit

I ran these reports for 1/Oct to 31/Oct (after reindexing) and then exported to CSV, and checked the totals

The totals appear to differ from running an aggregation directly in the db:

```
select count(*), sum(num_points) from points where reward = 8368169
and issued_date >= '2017-10-1' and issued_date < '2017-11-1'

select count(*), sum(num_points) from points_debit where reward = 8368169
and issued_date >= '2017-10-1' and issued_date < '2017-11-1'
```

Gives:
debits: 1633573
credits: 2734613
diff: 1,101,040

The difference is an exact match on points statement differences for the same period.

**Comment by mkhoudary** [comment]
@bradmac I exported files and sum of credit:
![image](https://user-images.githubusercontent.com/3704174/32498275-f3789d12-c3d7-11e7-8faf-c26eea330ba4.png)

Sum of debit:
![image](https://user-images.githubusercontent.com/3704174/32498293-00f91a84-c3d8-11e7-9bf2-fa056d6eda56.png)

And that exactly matches the number you've mentioned..

**Comment by bradmac** [comment]
Hmm, very strange. 

To mitigate the risk of this happening again, lets display totals on the manage buckets page from the db, filtered by date range. Currently the totals are for all time.

Eg
https://carters.admin.kademi.com.au/points-buckets/

![image](https://user-images.githubusercontent.com/826458/32527363-934840bc-c492-11e7-8a9f-3b99bb67b8bb.png)

**Comment by tuzzmaniandevil** [comment]
All done and working:
http://moblix.admin.kademi-ci.co/points-buckets/

**Comment by Uafinder** [comment]
Looks ok at the moment
