### ISSUE TITLE
Lead creation - source doesn't save when create more than one lead

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4310]
1. http://vlad30-leads_vlad-test30.kademi-ci.co/leads/?query=&leadType=active
2. Create a lead with some specified details (source, stage)
3. Save and close
4. Create another lead. Note that Source and Stage field already filled
5. Don't change Source field
6. Save and close
7. Note that source field is empty in second lead.

![image](https://user-images.githubusercontent.com/1945230/32320189-a1c2dc14-bfc5-11e7-97e4-b473e3c2b2eb.png)

**Comment by bradmac** [comment]
> Create another lead. Note that Source and Stage field already filled

This is fine.

But it needs to be persisted

**Comment by gonzalon** [comment]
@Uafinder it wasn't remembering the stage, it'd always select the first one (Cold).
Now it's clearing the source too, so the user has to select it.

latest leadman lib (1.6.3)

**Comment by Uafinder** [comment]
It works!
