### ISSUE TITLE
Login.html change logo

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4311]
Change logo is hiding besides Change Background Image and Remove background image
Probably should be Changed to Change Logo image and Remove Logo Image
![image](https://user-images.githubusercontent.com/1945230/32324277-89af6aee-bfd3-11e7-8da8-40955523b033.png)
http://vlad-test30.admin.kademi-ci.co/websites/vlad30-promos/version1?editTemplate=theme/apps/login/login

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
Not sure, if changed something...
![image](https://user-images.githubusercontent.com/1945230/32364571-4a3f883e-c07e-11e7-830c-551bd54f8e71.png)
http://vlad-test31.admin.kademi-ci.co

**Comment by Uafinder** [comment]
It works!
