### ISSUE TITLE
Remove pop-ups on open points-bucket

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4312]
![image](https://user-images.githubusercontent.com/1945230/32325860-5b7a6e34-bfd9-11e7-8a9c-738e1e1b9409.png)
http://vlad-test30.admin.kademi-ci.co/points-buckets/vlad30-store-points/?startDate=27%2F10%2F2017&finishDate=02%2F11%2F2017&dataQuery=&startPos=0#details-tab

**Comment by bradmac** [comment]
@ducdhm this should use the message identifier so they all replace each other instead of adding new messages

**Comment by ducdhm** [comment]
@bradmac I already have identifier for them. But @Uafinder doesnt want to show these messages in first time user go to this screen.

**Comment by ducdhm** [comment]
@bradmac So what do you think?

**Comment by bradmac** [comment]
The problem at the moment is that we see 3 messages. If they all have the same ID and the ID system is working correctly the user would only see 1 message. Its fine for that message to display when the page is shown when the page is first opened.

**Comment by ducdhm** [comment]
@bradmac We have 2 IDs for message in this screen. One for leaderboard tab and one for debits tab. Do you want me to merge them into 1? 

> The problem at the moment is that we see 3 messages
Vlad took this screenshot when 2 others are closed. It's not 3 messages :)

**Comment by bradmac** [comment]
> Do you want me to merge them into 1?

Yes please. As a user these messages arent very important, i dont want to see my screen filled with them

**Comment by anhnt** [comment]
done

**Comment by Uafinder** [comment]
https://drive.google.com/open?id=1pLK4fzZot9Y02IydWAABfYCb2T7a5O7W
looks different, but not much better... 
http://vlad-test44.admin.kademi-ci.co/points-buckets

**Comment by anhnt** [comment]
Fixed please test again

**Comment by Uafinder** [comment]
Looks great!
