### ISSUE TITLE
KCRM funnel not working

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4313]
http://kcrm.kademi.us/analytics/kademi-sales?filters=source%3DNone&stage=Hot

Clicking on hot does not show the correct list of leads in the table below.

Note this lead is HOT but is not in the table http://kcrm.kademi.us/leads/15869188/

![image](https://user-images.githubusercontent.com/2201340/32356452-36506892-c089-11e7-90cd-04ecd2f31dd1.png)

**Comment by gonzalon** [comment]
The query we are running:
`{
  "bool" : {
    "must" : [
      {
        "term" : {
          "funnel" : {
            "value" : 7651239,
            "boost" : 1.0
          }
        }
      },
      {
        "bool" : {
          "should" : [
            {
              "term" : {
                "orgIds" : {
                  "value" : 1257,
                  "boost" : 1.0
                }
              }
            },
            {
              "term" : {
                "assignedToOrg.orgId" : {
                  "value" : "kademi",
                  "boost" : 1.0
                }
              }
            }
          ],
          "disable_coord" : false,
          "adjust_pure_negative" : true,
          "minimum_should_match" : "1",
          "boost" : 1.0
        }
      },
      {
        "term" : {
          "stageName" : {
            "value" : "Hot",
            "boost" : 1.0
          }
        }
      }
    ],
    "must_not" : [
      {
        "term" : {
          "cancelled" : {
            "value" : "T",
            "boost" : 1.0
          }
        }
      },
      {
        "exists" : {
          "field" : "source",
          "boost" : 1.0
        }
      }
    ],
    "disable_coord" : false,
    "adjust_pure_negative" : true,
    "boost" : 1.0
  }
}
`

Seems we have two issues:
- the filter by funnel, as in the index there is no record with that value
- seems we should filter by stageName as "hot" instead of "Hot" 

`
{
    "query": {
        "bool" : {
            "must" : [
                {
                    "bool" : {
                        "should" : [
                            {
                                "term" : {
                                    "orgIds" : 1257
                                }
                            },
                            {
                                "term" : {
                                    "assignedToOrg.orgId" : "kademi"
                                }
                            }
                        ]
                    }
                },
                {
                    "term" : {
                        "stageName" : "hot"
                    }
                }
            ],
            "must_not" : [
                {
                    "term" : {
                        "cancelled" : "T"
                    }
                },
                {
                    "exists" : { "field" : "source" }
                }
            ]
        }
    }
}
`

**Comment by gonzalon** [comment]
![image](https://user-images.githubusercontent.com/2773216/32422479-62c278e2-c305-11e7-8796-a95d6fc13399.png)

From: 
![image](https://user-images.githubusercontent.com/2773216/32422516-a7bdc262-c305-11e7-923f-81be533d9a17.png)

**Comment by anhnt** [comment]
@gonzalon please update to filter result by stage. Currently results are the same when filter by specific stage or not

@paddyow at the moment we click to bubble to filter leads by stage. But i think we could add a dropdown list for stages. What do you think?

**Comment by gonzalon** [comment]
Depends on: https://github.com/Kademi/kademi-dev/issues/4335

**Comment by AlaaKhalaf94** [comment]
passed

**Comment by gonzalon** [comment]
It's showing the stages where it should be showing the sources, which makes the filters dont find any data:


![image](https://user-images.githubusercontent.com/2773216/32635676-2d118c56-c616-11e7-9111-e0a52f272bd2.png)

**Comment by gonzalon** [comment]
needed to deploy the libs to US.
