### ISSUE TITLE
Only display lead page components on the lead page

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4314]
When editing the dashboard template, i see a lot of Leadman components which cant be used here, they can only be used on a lead page.

For example:
![image](https://user-images.githubusercontent.com/826458/32357451-a69565e0-c0a1-11e7-9652-b1fee82acc8e.png)

Please ensure components which are specific to the lead page are only shown when editing the lead page template

**Comment by ducdhm** [comment]
@bradmac How can do it? Maybe we can add something special to components like special category. And in contentEditor, we can filter it like this.

**Comment by bradmac** [comment]
hey @ducdhm sounds like you dont know components already have a type property!

Eg in LeadManApp:
```
        ComponentBean.add(allComponents,
                "leadman/components", "leadDetailForm",
                "Display lead form in lead page",
                "Leadman App component",
                null,
                "lead"
        );
```

That last argument "lead" means that this component will only be displayed on pages (and templates) where $page.is("lead") returned true

However, this component will be displayed on all pages, because all html pages return true for "html"

```
        ComponentBean.add(allComponents,
                "leadman/components", "leadTasksNav",
                "Display nav buttons on lead tasks page",
                "Leadman App component",
                null,
                "html"
        );
```

Types are set on components in the same way for custom apps.

So please ensure appropriate type values are set.

**Comment by bradmac** [comment]
But @ducdhm note this is in the Krabby milestone

**Comment by anhnt** [comment]
Fixed, also fixed leads list component

**Comment by Uafinder** [comment]
http://vladtest04.admin.kademi-ci.co/blogs/blogqa1/mazda/#bodyCopy-tab
Looks like all components are listed in blog content edition...
![image](https://user-images.githubusercontent.com/1945230/33891724-812199aa-df5f-11e7-9fe2-346fb3b979e6.png)

**Comment by bradmac** [comment]
@Uafinder there are components from the LeadMan app which can be used on any page. For example, the list of tasks for the current user can be used on any page.

Components which cant be used on any page are those which require a lead resource to work, for example the component which displays lead details form can only be used on the lead template.

So this issue was to make sure that only components which can legitimately be used on any page are available on any page, and components which can only work on the lead page are available on the lead page.

I've had a look at the list of components available and that looks right to me:
![image](https://user-images.githubusercontent.com/826458/33904995-04a36aba-dfe2-11e7-8304-f9ceb234872b.png)

**Comment by bradmac** [comment]
However, there are a lot of components missing preview images so i'll create a seperate issue for that

**Comment by Uafinder** [comment]
ok
so, it looks good
