### ISSUE TITLE
Leads score amount

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4316]
Score in admin console:
![image](https://user-images.githubusercontent.com/1945230/32369733-02f768a6-c093-11e7-9544-c63b3da62258.png)
Score on dashboard:
![image](https://user-images.githubusercontent.com/1945230/32369742-1350ee8e-c093-11e7-9376-405607fd1639.png)
Score on leads page:
![image](https://user-images.githubusercontent.com/1945230/32369762-2734fd1e-c093-11e7-8842-9a1348d755b5.png)
http://vlad-test31.admin.kademi-ci.co
http://vlad31-leads_vlad-test31.kademi-ci.co/leads/?query=&leadType=active

(moved issue to https://github.com/Kademi/kademi-dev/issues/4368)

**Comment by bradmac** [comment]
Thats fine for now
