### ISSUE TITLE
KPoll created by value bad

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4317]
![image](https://user-images.githubusercontent.com/1945230/32370906-6b78d424-c097-11e7-9774-cfe3c100cab9.png)
![image](https://user-images.githubusercontent.com/1945230/32371118-4b264200-c098-11e7-89bb-36c954e12761.png)

http://vlad-test31.admin.kademi-ci.co/kpoll/managePolls/

Seems like it use UserID value.

**Comment by bradmac** [comment]
Please change to using the user's name if there is one, and only display userid if there is no name.

Note that there is a property called formattedName on Profile for this purpose

**Comment by anhnt** [comment]
done

**Comment by Uafinder** [comment]
It works!
