### ISSUE TITLE
Manage users page - page size component

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4319]
http://vlad-test30.admin.kademi-ci.co/manageUsers/?sortfield=firstName,email&startPos=0&pageSize=100&
![image](https://user-images.githubusercontent.com/1945230/32378133-9f5a11f2-c0b2-11e7-90f3-70c4f8fa54a5.png)
I've more than 10000 users
![image](https://user-images.githubusercontent.com/1945230/32378178-b724b1a2-c0b2-11e7-8af5-fd41f505ff8d.png)

Page size component should be added

**Comment by bradmac** [comment]
Number of users appears correct:
![image](https://user-images.githubusercontent.com/826458/32419195-3240d1ac-c2db-11e7-9c3b-5a4de6534458.png)

**Comment by bradmac** [comment]
Not sure what you mean by "page size list"

**Comment by bradmac** [comment]
@gonzalon please enable the page size list

**Comment by Uafinder** [comment]
Paginator implemented, but some problems exists...
When you change page size from 100 to 5000 it loads very slowly and cause some scripts stop.
And also, after page loads and when you try to move to last page, it looks broken.
![image](https://user-images.githubusercontent.com/1945230/32432750-59859c1a-c2e1-11e7-9cda-4cc144eea882.png)
I wrote a video on process changing page size from 100 to 5000

**Comment by bradmac** [comment]
@gonzalon please investigate apparent performance issue when loading with 5k users

**Comment by bradmac** [comment]
@Uafinder yes the page will be very slow with a page size of 5k, and this could cause scripts to not load correctly. 

This is expected behaviour. Users should generally use a smaller page size, but if they really need to see 5k they should be able to select it.

**Comment by Uafinder** [comment]
Working better
