### ISSUE TITLE
When Base cost of products that added to ecommerce is null , it shows error

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#4321]
When Base cost of products that added to ecommerce is null , it shows error in website page : http://version1.alaa-test25_alaa-test25.kademi-ci.co/ecom-store/
![capture3](https://user-images.githubusercontent.com/26510030/32413316-cf8c9c4e-c217-11e7-8f76-7ffd54436501.PNG)

And shows error in "Website Manager" list in side navbar just from manage eCommerce store page : http://alaa-test25.admin.kademi-ci.co/ecommerce/ecom-store/#products-tab

![capture1](https://user-images.githubusercontent.com/26510030/32413292-58ae73fe-c217-11e7-8595-a2ad0bfe37fd.PNG)

This is the products page : http://alaa-test25.admin.kademi-ci.co/products/

![capture2](https://user-images.githubusercontent.com/26510030/32413307-992355a8-c217-11e7-9050-08ae27af6dd6.PNG)

**Comment by bradmac** [comment]
here's the stack trace
```
09:46:25 Caused by: java.lang.NullPointerException
09:46:25 	at co.kademi.db.ProductInEComStore.withMargin(ProductInEComStore.java:427)
09:46:25 	at co.kademi.db.ProductInEComStore.invoiceCost(ProductInEComStore.java:396)
09:46:25 	at co.kademi.db.ProductInEComStore.memberBuyPrice(ProductInEComStore.java:382)
09:46:25 	at co.kademi.db.ProductInEComStore.finalCost(ProductInEComStore.java:370)
09:46:25 	at com.fuselms.apps.ecommerce.ProductInStoreBean.toBean(ProductInStoreBean.java:32)
```

**Comment by bradmac** [comment]
Added null checks. Note that if there is no base cost then the cost will not be correctly displayed in search results.

**Comment by bradmac** [comment]
that seems to be working now

**Comment by AlaaKhalaf94** [comment]
passed
