### ISSUE TITLE
Support bootstrap styles for blog articles

### ISSUE THREAD

**Issue by gonzalon** [Kademi/kademi-dev#4324]
Celine it's asking to be able to select the same styles in the blog article editor as in the web page editor:

Page styles:

![image](https://user-images.githubusercontent.com/2773216/32422628-3c93a474-c306-11e7-90ca-486f3d962815.png)

Blog article styles:

![image](https://user-images.githubusercontent.com/2773216/32422632-4403289c-c306-11e7-95e6-fa4b435c0a24.png)

**Comment by ducdhm** [comment]
@bradmac @gonzalon Main issue of here is because we're editing Blog Article in admin instead of frontend. If you can provide me a Resource for editing it in frontend, it'll be cool

**Comment by bradmac** [comment]
FYI, currently loading styles from here:
http://localhost:8080/templates/themes/admin2/styles.js

**Comment by bradmac** [comment]
hey @ducdhm a very simple thing we can do, which we should do anyway, is update the admin styles.js to have bootstrap styles

This should be the same as in the bootstrap-base styles.js

**Comment by mrdadah** [comment]
Done,,
@bradmac , Please give me rights to push my changes to Kademi-dev 

<img width="429" alt="screen shot 2017-11-07 at 3 56 22 pm" src="https://user-images.githubusercontent.com/11255121/32497141-44c50a7e-c3d4-11e7-830a-575fb85c0f3d.png">

**Comment by bradmac** [comment]
you should be able to now

**Comment by mrdadah** [comment]
Pushed

**Comment by AlaaKhalaf94** [comment]
waiting this issue to be closed : https://github.com/Kademi/kademi-dev/issues/4342 , to test

**Comment by AlaaKhalaf94** [comment]
passed
