### ISSUE TITLE
Email sending failed

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4328]
http://vlad32-test.admin.kademi-ci.co/emails/?q=&status=&job=
With error : No MimeMessage found
I've post to real and mailinator addresses - sit are the same.

**Comment by bradmac** [comment]
Problem is the from email address:
```
noreply@vlad32-learn_vlad32-test.kademi-ci.co
```

**Comment by Uafinder** [comment]
http://vlad-test35.admin.kademi-ci.co/emails/1783334
Doesn't send at all
It gives next error
Domain contains illegal character

**Comment by Uafinder** [comment]
Up

**Comment by bradmac** [comment]
Note that if the website contains a hyphen then we need to use an underscore to separate website from org, and that will cause this error.

However, this isnt a real error because real clients will use their own domain names.

**Comment by Uafinder** [comment]
I can't test this issue https://github.com/Kademi/kademi-dev/issues/4003
because of this error...

**Comment by bradmac** [comment]
Please see the comment above
