### ISSUE TITLE
Keditor - change your video button does nothing

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4330]
![image](https://user-images.githubusercontent.com/1945230/32441238-60279f82-c2ff-11e7-91a7-a98215a26bf1.png)
http://vlad32-test.admin.kademi-ci.co/websites/vlad32-learn/version1/programs/p1/c1/m1/#files-tab
Created a new page, add a component with video. Push change video button, and it does nothing.

Also problem with side panel
When you click on the gear icon once - side panel appears
When you click on it second time - side panel hides
But when you wanna to call it back again - gear icon button become inactive and does nothing.
![image](https://user-images.githubusercontent.com/1945230/32441530-c10cf7ec-c300-11e7-872d-9477a7dbffd5.png)

**Comment by anhnt** [comment]
Fixed. please update kademi dev before testing

**Comment by Uafinder** [comment]
It works!
