### ISSUE TITLE
The event appears in calendar but doesn't appear in events list

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#4331]
Here : http://alaa-test27.admin.kademi-ci.co/Calendars/Calendar01/ I've created two events, but I can't see them in the Events list at next to them

![capture3](https://user-images.githubusercontent.com/26510030/32441654-391aa356-c301-11e7-91f1-99c4ac10029f.PNG)

**Comment by bradmac** [comment]
The "Coming events" list only shows upcoming events, ie events in the future. Those events are in the past.
