### ISSUE TITLE
Unwanted Module deletion is possible

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4332]
1. Create a module
2. Create a page
3. Open page in Keditor
4. Add some text
5. Upload some video via this button
![image](https://user-images.githubusercontent.com/1945230/32444835-9fa61d84-c30c-11e7-90b0-2a18f6a9af2f.png)
6. 
![image](https://user-images.githubusercontent.com/1945230/32444861-ae07bc48-c30c-11e7-86e7-a90a983b8aa8.png)
Close it with success
7. Go back to edit video modal and try to delete it WITHOUT clicking on file...
![image](https://user-images.githubusercontent.com/1945230/32444997-169e224c-c30d-11e7-8f9d-c3e6ec28622d.png)
![image](https://user-images.githubusercontent.com/1945230/32445015-237cf024-c30d-11e7-98a3-779575f94b1c.png)
8. And that's it... whole module was removed!
http://vlad32-test.admin.kademi-ci.co/websites/vlad32-learn/version1/programs/p1/c1

**Comment by bradmac** [comment]
@ducdhm looks like the wrong URL is being constructred for the delete

**Comment by anhnt** [comment]
Could not reproduce.
Go to this page: http://version1.vlad32-learn_vlad32-test.kademi-ci.co/programs/p1/c1/m1/contenteditor?fileName=pp2test.html&miltonUserUrl=/users/anh&miltonUserUrlHash=d482923c-74c4-46e1-a36a-5064552242dc:UFhRE7179iGqYBOPzDfYGl-64lo

![image](https://user-images.githubusercontent.com/735555/32591869-da363350-c553-11e7-834f-ca6c9ae73d0d.png)

![image](https://user-images.githubusercontent.com/735555/32591890-f0ac8468-c553-11e7-87bf-421d0b8f9739.png)

**Comment by anhnt** [comment]
fixed

**Comment by Uafinder** [comment]
Yeah, it's good!
