### ISSUE TITLE
KCRM Analytics Page: Funnel shouldn't be updated on filters

### ISSUE THREAD

**Issue by gonzalon** [Kademi/kademi-dev#4335]
- Remove the funnel filtering when the user clicks on a source (or other aggregation)
should still filter table though
-We need a way to remove a filter once applied so the clear filters should always be shown (the clear filters appear when you click on the source but not the stage)

**Comment by anhnt** [comment]
done

**Comment by AlaaKhalaf94** [comment]
passed
