### ISSUE TITLE
New manage orgs page, org type filtering doesnt work

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4336]
![image](https://user-images.githubusercontent.com/826458/32476667-9c0219ea-c3dd-11e7-814f-2ac0f2d12e09.png)

**Comment by Uafinder** [comment]
Org type filter absent
![image](https://user-images.githubusercontent.com/1945230/32540109-513a9102-c474-11e7-9f0e-01d318354e11.png)
http://vlad-test36.admin.kademi-ci.co/organisations/

**Comment by gonzalon** [comment]
Hey @Uafinder sorry forget to mention that, it would only show when there are more than 4 items to filter.
Just added one org type to your account:

![image](https://user-images.githubusercontent.com/2773216/32572530-c17bc9e8-c52f-11e7-9f15-85af598fbebc.png)

**Comment by Uafinder** [comment]
It works!
