### ISSUE TITLE
New manage orgs page, show basic stats

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4337]
The new manage orgs page should have a similar layout as the manage users page. This includes displaying basic statis at the top, and arrangement of buttons:

![image](https://user-images.githubusercontent.com/826458/32476685-ccfedfe2-c3dd-11e7-8b51-07c7496d1b68.png)

Please show
- total orgs
- total org types

**Comment by gonzalon** [comment]
![image](https://user-images.githubusercontent.com/2773216/32522611-e0ebf7f2-c47c-11e7-81aa-55b4cd979a9a.png)

**Comment by bradmac** [comment]
@gonzalon in the screenshot above i can see 4 org types in the aggregation list, but it says "1" in the stats panel

**Comment by gonzalon** [comment]
as we spoke it's updating the stats by the filters as the users page

**Comment by Uafinder** [comment]
It works perfect...
