### ISSUE TITLE
New manage orgs page, agg filters

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4338]
![image](https://user-images.githubusercontent.com/826458/32476988-eb61f922-c3df-11e7-9103-867c768ef778.png)

https://zoetis.admin.kademi.com.au/organisations/?term-orgTypes=noType

**Comment by gonzalon** [comment]
The filtering works fine after a re-index

**Comment by gonzalon** [comment]
The amount of orgs in the agg filter was wrong for no type

![image](https://user-images.githubusercontent.com/2773216/32518638-12b21d4c-c46f-11e7-9db9-9476d9554ecc.png)

**Comment by Uafinder** [comment]
Looks like no-type problem is because of root org appears to count...
https://github.com/Kademi/kademi-dev/issues/4283
I will take a look on filter not working problem.
