### ISSUE TITLE
Email app should be enabled automatically when installing apps

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4339]
When you go to website app market and install app from there - Email app is not enabled automatically, but looks like it should to ensure that all functions are work correctly.
http://vlad-test35.admin.kademi-ci.co/
![image](https://user-images.githubusercontent.com/1945230/32486379-233d5462-c3af-11e7-8ca2-758fdf1bf133.png)

**Comment by bradmac** [comment]
hey @Uafinder its not that simple. An app should only depend on the email app if there is something specific that it depends on. That decision is made for each app, its not a blanket rule that all apps should depend on the email app.

> but looks like it should to ensure that all functions are work correctly.
Can you be more specific? Which app doesnt work properly without the email app?

**Comment by Uafinder** [comment]
Sure, no probs... I've install four different types of app:
sales
leadman
learning
reward-store
All was created with email app disabled. If needed - I can check all market apps.

**Comment by bradmac** [comment]
But what problems did you see? We should only add an app as a dependency on another if there is some specific need for it. What is that need for each app?

**Comment by bradmac** [comment]
Just to clarify: dont go checking which apps depend on email app or not, just report what problems you see, and then we can resolve each problem individually.

**Comment by Uafinder** [comment]
No probs... I've just spot this while working on other issues and decided to report. No need to do job for sake of job :)
