### ISSUE TITLE
promotion images bugs

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4340]
When choosing to upload image in promotion two bugs appear:
1. When you upload image - it show very pixelated.
![image](https://user-images.githubusercontent.com/1945230/32490122-c7a36eaa-c3ba-11e7-8522-f94462ae797e.png)

2. When you submit one entry, then push submit another, it goes back to initial page, but:
- it already contains image in upload image box (which was uploaded earlier)
- it doesn't contain your previous uploaded image in uploaded images list. 
![image](https://user-images.githubusercontent.com/1945230/32490244-203ad2c4-c3bb-11e7-8083-bea169137684.png)

http://version1.vlad35-promo_vlad-test35.kademi-ci.co/rewards/promo1/
http://vlad-test35.admin.kademi-ci.co/

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
1. When you submit one entry and push "submit another" it appears to be that user photo is not showing.
![image](https://user-images.githubusercontent.com/1945230/32603608-02c76f88-c553-11e7-9b39-18e7de9206a9.png)
http://version1.vlad41-promos_vlad-test41.kademi-ci.co/rewards/promo1/
http://vlad-test41.admin.kademi-ci.co/rewards/promo1/#details-tab

**Comment by bradmac** [comment]
@anhnt please check why the image thumb is not displayed.

**Comment by anhnt** [comment]
That image thumb is not showing because css background image is not correct. Just fixed now

**Comment by Uafinder** [comment]
It works!
