### ISSUE TITLE
Klead - Link|Unlink company and further search issue

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4341]
1. Create a lead and open it
2. Go to company details
3. Create a company by using company information
4. Unlink company
5. Try to search company which you just created
it will show you your company by only several symbols entered, but if you for example enter full name - no company found.

![image](https://user-images.githubusercontent.com/1945230/32491917-16332280-c3c1-11e7-8721-2d3e372013e1.png)
![image](https://user-images.githubusercontent.com/1945230/32491927-1dc469fa-c3c1-11e7-969d-9bf80e6524bf.png)

When this is not a single company (I've create a ecb2), it will not show you completely after creating and unlinking procedure.
![image](https://user-images.githubusercontent.com/1945230/32491992-64cb0494-c3c1-11e7-9f00-3d3701b96555.png)
After refresh:
![image](https://user-images.githubusercontent.com/1945230/32492010-752b58c0-c3c1-11e7-80df-4d174669d77d.png)

http://version1.vlad35-leads_vlad-test35.kademi-ci.co/leads/1788997/
http://vlad-test35.admin.kademi-ci.co/organisations

**Comment by gonzalon** [comment]
Seems the problem was the cache for the search, disabled it

**Comment by Uafinder** [comment]
Minor issue remains, but I think we can ignore it, because it's hardly reproduced by end user
