### ISSUE TITLE
Couldn't edit content for blogs

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#4342]
Here : http://alaa-test29.admin.kademi-ci.co/blogs/components/components/#bodyCopy-tab
I try to edit content , but the keditor doesn't load

It shows me error in console : " VM2325:161 WebSocket connection to 'ws://version1.alaa-test29_alaa-test29.kademi-ci.co:81/comments/version1.alaa-test29_alaa-test29.kademi-ci.co/content/L2Jsb2dzL2NvbXBvbmVudHMvY29tcG9uZW50cy8=' failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT"

![capture1](https://user-images.githubusercontent.com/26510030/32497804-6b493c36-c3d6-11e7-9e4b-7742e3f542cf.PNG)

**Comment by ducdhm** [comment]
@AlaaKhalaf94 I can't reproduce this issue. Can you help me?

**Comment by AlaaKhalaf94** [comment]
stranger , I can't reproduce it again
