### ISSUE TITLE
Points which allocated via points allocation rules are not listed in points list

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4343]
I have an allocation rule which award 50 points on every award.
They are adding to user points, but doesn't display in points list:
http://vlad-test31.admin.kademi-ci.co/manageUsers/1533595/#pointsBucketTab-tab
http://vlad-test31.admin.kademi-ci.co/points-buckets/points/
http://vlad-test31.admin.kademi-ci.co/points-rules/
![image](https://user-images.githubusercontent.com/1945230/32498250-dc9188b6-c3d7-11e7-8b53-0ccf0d824f4e.png)

**Comment by tuzzmaniandevil** [comment]
It's deffenatly adding the points, Not sure where your screenshot is from.
![image](https://user-images.githubusercontent.com/3378330/32636275-ef5590e4-c618-11e7-8872-f2419e6c3067.png)

**Comment by bradmac** [comment]
@Uafinder please always give the URL of the page where you see a problem

**Comment by Uafinder** [comment]
it's not about image...
I mean that I can't see points which are allocated by point allocation rule

**Comment by Uafinder** [comment]
I've checked again, looks I've not seen points because of date issue
https://github.com/Kademi/kademi-dev/issues/4486
Closing this one
