### ISSUE TITLE
Allow anon users to view calendar event

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#4346]
At the moment this needs login to view http://version1.travelworldnz_travelworld.kademi.com.au/Calendars/secondaryschoolholiday?start=2017-11-01&end=2017-12-01&_=1510107652192

I think we can have new role for viewing calendar event then add that role to **public** group

https://github.com/Kademi/client-gilpin-travelworld/issues/37

**Comment by anhnt** [comment]
Note that our new component is using ajax that doenst allow anno user to see results.

**Comment by tuzzmaniandevil** [comment]
We already support this :-)

You just give the Content Viewer role to the Calendar repository.

**Comment by anhnt** [comment]
Yup looking good thanks
