### ISSUE TITLE
profile.lastVisit field is always null

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#4347]
Please have a look at this query http://vlad-test29.admin.kademi-ci.co/queries/test/#queryBuilderTab-tab

This user has visited some websites but it doesnt stored value to ES profile index http://vlad-test29.admin.kademi-ci.co/manageUsers/1291940/#userAppTab-tab

The lastVisit field will be updated if reindex

**Comment by gonzalon** [comment]
To test:
- Create a new profile
- Login with that profile
- Visit one website
- Create a query like the one in the example to check
- The visit should apper wihout the need to re-index

**Comment by AlaaKhalaf94** [comment]
Hi @gonzalon , I make steps like you said but the visit doesn't appear without the need to re-index
that still need re-index to appear

I test here : http://fresh07.admin.kademi-ci.co/queries/test/#queryResult-tab

**Comment by gonzalon** [comment]
Hi @AlaaKhalaf94 
here the steps I did to test it:

1) Created this user http://fresh07.admin.kademi-ci.co/manageUsers/3293103/#general-tab
2) Logged in in: http://version1.fresh07-fresh07.kademi-ci.co/dashboard
3)

![image](https://user-images.githubusercontent.com/2773216/33852274-bab887d2-df1e-11e7-9b9f-288a3b28f041.png)

**Comment by AlaaKhalaf94** [comment]
passed
