### ISSUE TITLE
Scheduled email content Keditor stucks

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4348]
1. Fresh account
2. Cache cleared
3. Created new email job
4. Saved some details
5. Edit content
6. 
![image](https://user-images.githubusercontent.com/1945230/32542397-2213428c-c47b-11e7-82fb-3b8bf5c37616.png)
http://vlad-test36.admin.kademi-ci.co/scheduledEmails/scheduleqa1/#configuration-tab
![image](https://user-images.githubusercontent.com/1945230/32542438-50dc24c6-c47b-11e7-9cbf-ba740510e3ba.png)
Hard refresh won't help

**Comment by anhnt** [comment]
Tested working fine on chrome and firefox

**Comment by Uafinder** [comment]
1. Delete all emails tasks
2. Clear cache
3. Create new task
4. Edit it, fill from, subject, hourly rate
5. Push save
6. Press edit content

**Comment by bradmac** [comment]
If we cant solve the problem directly, lets just move the editor to a new tab

**Comment by ducdhm** [comment]
The root cause I guess is `$.getScriptOnce`. Sometimes, it doesnt work well. Open in new tab doesnt help in this case.

**Comment by Uafinder** [comment]
IT works!
