### ISSUE TITLE
Leads quick edit feature bugs

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4352]
When using quick edit feature for leads:
1. Score amount disappears
2. Journey label disappears
![image](https://user-images.githubusercontent.com/1945230/32548257-bff76e4e-c48d-11e7-8c6d-e78df2dfbbf5.png)
http://vlad36-leads_vlad-test36.kademi-ci.co/leads/

**Comment by anhnt** [comment]
> Journey label disappears

Fixed

> Score amount disappears

@bradmac When a row is updated datatable will update that row with data which returns from server which is LeadBean object. But that object doesnt have score prop so that column will be blank. The same problem with funnelName field but i added that to LeadBean. Please advise!

**Comment by bradmac** [comment]
> But that object doesnt have score prop so that column will be blank

Thats fine, we can live with it like this

**Comment by Uafinder** [comment]
ok
