### ISSUE TITLE
New org page visual bug when resolution is not 1920x1080

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4353]
![image](https://user-images.githubusercontent.com/1945230/32552695-76261f8a-c49d-11e7-9a57-1595b5ae18b7.png)
http://vlad-test38.admin.kademi-ci.co/organisations/

**Comment by bradmac** [comment]
@gonzalon please move the map and "create account" links into the tools dropdown. They're not frequently used

**Comment by gonzalon** [comment]
![image](https://user-images.githubusercontent.com/2773216/32574733-eec2af5a-c536-11e7-9419-f4e71d4ab96e.png)

**Comment by Uafinder** [comment]
Nice move, it works!
