### ISSUE TITLE
dashboard graphs are not responsible without refresh

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4354]
![image](https://user-images.githubusercontent.com/1945230/32553957-f73733e0-c4a0-11e7-820d-4936ae6d9739.png)
![image](https://user-images.githubusercontent.com/1945230/32553965-fd4eaefc-c4a0-11e7-8a4a-24f476f69e9c.png)
http://vlad-test38.admin.kademi-ci.co/

**Comment by bradmac** [comment]
That's fine
