### ISSUE TITLE
Stream dashboard zone which may cause no way situation

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4355]
Marked zone is clickable and leads to full screen stream window, and there is no way out of there.
![image](https://user-images.githubusercontent.com/1945230/32554438-6dbeec96-c4a2-11e7-9d52-e57485ce72f2.png)
 
![image](https://user-images.githubusercontent.com/1945230/32554454-82600a04-c4a2-11e7-805b-e6e1666fce3c.png)
http://vlad-test38.admin.kademi-ci.co/

**Comment by bradmac** [comment]
the stream needs a complete overhaul anyway..

**Comment by bradmac** [comment]
Stream has been rebuilt now
