### ISSUE TITLE
Submitting an order takes longer than normal

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4357]
Login with this guy http://incremental-marketing.admin.kademi.com.au/manageUsers/82811266/#pointsBucketTab-tab

Add to cart and checkout.  The time to complete the checkout takes up to and beyond 5 seconds, which is longer than expected.

**Comment by bradmac** [comment]
Seems fixed now. I think same issue as for https://github.com/Kademi/kademi-dev/issues/4366

**Comment by Uafinder** [comment]
Hey, is it possible to test in this account with specified guy?

**Comment by bradmac** [comment]
Yep, this is a demo account

**Comment by Uafinder** [comment]
The result is 3 seconds at the moment, so I think it's ok?!
