### ISSUE TITLE
Is Inverse option being overwriten

### ISSUE THREAD

**Issue by gonzalon** [Kademi/kademi-dev#4358]
Celine from Gilpin was trying to set the footer links in white. Setted the is inverse option in the container and now its like:
![image](https://user-images.githubusercontent.com/2773216/32582856-bb86f960-c555-11e7-8d17-31685ef3b06d.png)

So it should be the default colour for the hyperlinks in black, and the inverse should be white. And underline on hover
URL: http://versionnew.gilpinperformance_gilpin.kademi.com.au//theme/contenteditor?fileName=defaultThemeTemplate.html

We should let her know once this is fixed.

**Comment by ducdhm** [comment]
@gonzalon Fixed! Please check it out. If it's ok for you. Please deploy to AU

**Comment by gonzalon** [comment]
Works :)

![image](https://user-images.githubusercontent.com/2773216/32586531-ee733a20-c567-11e7-81e1-a6dc17022290.png)

Need to deploy to AU

**Comment by ducdhm** [comment]
Deployed!

**Comment by gonzalon** [comment]
This its working in the Gilpin site
