### ISSUE TITLE
After Install app to a website button should become inactive and with correct label

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4361]
Before install
![image](https://user-images.githubusercontent.com/1945230/32605341-c7acb49c-c559-11e7-957e-75aeb45ab190.png)
After install
![image](https://user-images.githubusercontent.com/1945230/32605376-e7eaa142-c559-11e7-97e1-7f92ea883a54.png)
What does it mean Enable?! It's already enabled...
It's clickable, but it says to install app again.
![image](https://user-images.githubusercontent.com/1945230/32605445-1e4a7208-c55a-11e7-978d-74c2eb5f254b.png)

**Comment by bradmac** [comment]
Now shows "Already installed" instead of button

![image](https://user-images.githubusercontent.com/826458/32634849-8b7168ce-c612-11e7-9e3b-aa4e9b8cc1da.png)

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/32648352-14eed5ec-c5fe-11e7-96a6-c0f70d44f748.png)
It's after install
The same thing after refreshing page.
http://vlad-test43.admin.kademi-ci.co/marketPlace/KLearning/?websiteBranch=version1&websiteName=vlad43-learn

**Comment by Uafinder** [comment]
It's ok! Just was need to rebuild
