### ISSUE TITLE
Could not create voucher type when ID or name are using accross rootorg

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4362]
![image](https://user-images.githubusercontent.com/1945230/32608697-e04562cc-c565-11e7-850e-ed9047fe30c6.png)

http://vlad-test41.admin.kademi-ci.co/voucher-type/

This name were existed in my test accounts earlier.

**Comment by gonzalon** [comment]
Removed constrains for the name in voucher type in the US and AU db

**Comment by gonzalon** [comment]
Rootorg:
![image](https://user-images.githubusercontent.com/2773216/32703963-bded2570-c862-11e7-9616-36b171c7a2c9.png)

Child org:
![image](https://user-images.githubusercontent.com/2773216/32703967-d2a23af0-c862-11e7-8835-f7eb117389d0.png)

**Comment by Uafinder** [comment]
it works ok

**Comment by Uafinder** [comment]
It creates voucher type without any problems, however when you push create vouchers (for example 50), it takes naming and other options from those other type which were exist earlier...
http://vlad-test50.admin.kademi-ci.co/voucher-type/vw/#details-tab
It has next naming parameter YY-@{randomHex(4)}
But it created for me next vouchers
http://vlad-test50.admin.kademi-ci.co/vouchers/?q=&status=&voucherType=vw
e.g. randomHex(5)

**Comment by gonzalon** [comment]
@Uafinder I'm not sure if I get what's happening:
I tried changing the naming parameter and creating new ones and seems to work as expected:

![image](https://user-images.githubusercontent.com/2773216/32928435-ca1e658c-cbb6-11e7-83a7-e4122ac72e26.png)

**Comment by Uafinder** [comment]
I don't know...
Was not able to reproduce it once more... :(
closing issue, will keep an eye on it
