### ISSUE TITLE
Voucher type extra field add option button does nothing

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4363]
![image](https://user-images.githubusercontent.com/1945230/32608952-a679a20a-c566-11e7-93af-a8b402332de5.png)
http://vlad-test41.admin.kademi-ci.co/voucher-type/skd1/#details-tab

**Comment by gonzalon** [comment]
Fixed
![image](https://user-images.githubusercontent.com/2773216/32704899-cad2521a-c871-11e7-9d55-70bddeb9a156.png)

**Comment by Uafinder** [comment]
It's ok at the moment
