### ISSUE TITLE
Should randomHex(5) expression return values with 3 or 4 symbols? 

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4365]
I have an expression for vouchers creation skdYY-@{randomHex(5)}
It create for me some vouchers, but some of the was shorter that I expected, for example:
skdYY-beb
skdYY-68bf
So the question is, RandomHex(5) should return values between 0-fffff, or 10000-fffff (to save number of symbols)?
http://vlad-test41.admin.kademi-ci.co/voucher-type/skd1/#details-tab

**Comment by bradmac** [comment]
Should definitely return 5 characters!

**Comment by tuzzmaniandevil** [comment]
Good catch! On the odd occasion it would not generate the correct length. I've updated it so it always will now. Tested it by generating 10000 vouchers

**Comment by Uafinder** [comment]
great, it works!
