### ISSUE TITLE
KJourneys app

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4369]
Create a marketplace app for when user want to use journeys for automation, but not necessarily part of lead management

This will create a funnel and enable funnels and tracking for the website its installed into

It will enable Leadman as an account level application, but not install it into any websites

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/32634876-b02567d8-c612-11e7-81fc-f93dd6bff6f3.png)

**Comment by Uafinder** [comment]
1. It doesn't enable tacking and funnels for website level
2. It creates all groups and dashboard messages for leads.
http://vlad-test47.admin.kademi-ci.co/websites/vlad47-jour/version1/#panel_apps-tab

**Comment by bradmac** [comment]
Fixed. Incorrect folder name for website installation

**Comment by Uafinder** [comment]
it works
