### ISSUE TITLE
Funnel lead should click through to lead not lead list

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4371]
http://kcrm.kademi.us/analytics/kademi-sales

If you click on the cog icon, it should open the lead.

![image](https://user-images.githubusercontent.com/2201340/32636910-173ad870-c60b-11e7-88cb-fbeb03b3617e.png)

**Comment by gonzalon** [comment]
Please re-index the leads to test it :)

**Comment by Uafinder** [comment]
Still same sit
![image](https://user-images.githubusercontent.com/1945230/32657532-c78c5420-c61e-11e7-83be-8e1c9848bda1.png)
![image](https://user-images.githubusercontent.com/1945230/32657543-cf5cc90a-c61e-11e7-9248-9c0acf8e6f19.png)
http://vlad43-leads_vlad-test43.kademi-ci.co/analytics/journey1

**Comment by gonzalon** [comment]
@Uafinder  just did a re-index and its working fine in the account you linked:

http://vlad43-leads_vlad-test43.kademi-ci.co/analytics/journey1


![image](https://user-images.githubusercontent.com/2773216/32703416-8a0d52e6-c85a-11e7-8a05-ae6330730ae4.png)

![image](https://user-images.githubusercontent.com/2773216/32703418-9c6984dc-c85a-11e7-9541-81df70dd65b1.png)

**Comment by Uafinder** [comment]
Looks ok at the moment
