### ISSUE TITLE
Lead contacts bugs

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4373]
![image](https://user-images.githubusercontent.com/1945230/32649559-26aaaa40-c603-11e7-962b-ff9ad28402c1.png)
![image](https://user-images.githubusercontent.com/1945230/32649565-2f2d11bc-c603-11e7-84bf-a11cbd3ef883.png)
1. Font color bad - should be white or invertable
2. After creating contact - it's adding to leads group. Is it ok?
3. Creating contact (push create and close) doesn't cause to update list of contacts
![image](https://user-images.githubusercontent.com/1945230/32649678-9f4cbcb8-c603-11e7-90c1-6b2848f1efa8.png)
4. No quite understand how display name for a contact is forming...
I've tried several enter variants and only full fulfillment give me name as a result. Probably, if name+surname is not entered, should use preferred name field, if it's also empty, first or last name should be used separately.
![image](https://user-images.githubusercontent.com/1945230/32649987-c9f59c7c-c604-11e7-92ae-aec6d761b7fa.png)
5. Import button
![image](https://user-images.githubusercontent.com/1945230/32650716-7bb0fb58-c607-11e7-872f-b8b767e0f794.png)

**Comment by anhnt** [comment]
>2. After creating contact - it's adding to leads group. Is it ok?

@bradmac can you please advise

>4.No quite understand how display name for a contact is forming...
>I've tried several enter variants and only full fulfillment give me name as a result. Probably, if name+surname is not entered, should use preferred name field, if it's also empty, first or last name should be used separately.

It will show following, from high priority to low priority

Preferred name -> first name (last name) -> No name

**Comment by Uafinder** [comment]
Looks fine!
