### ISSUE TITLE
Promotions app dependencies

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4375]
When you enable Rewards and Promotions app it doesn't enough to make it works...
I've enable it here
http://vlad-test43.admin.kademi-ci.co/manageApps/#installed-tab
And then enable it here
http://vlad-test43.admin.kademi-ci.co/websites/vlad43-promo/version1/#panel_apps-tab
Create a promo here:
http://vlad-test43.admin.kademi-ci.co/rewards/promo1/#details-tab
But when you go to frontend it gives you an error:
http://version1.vlad43-promo_vlad-test43.kademi-ci.co/rewards/promo1/
And while editing it shows an error too:
![image](https://user-images.githubusercontent.com/1945230/32651685-7cb8dc70-c60a-11e7-8125-b9411634fdbd.png)

But when I will install RewardStore app into account it will work.
Would be great to have Promotions app installation as it existed with other large Apps. It will transparent and easy without searching dependencies to other apps.

**Comment by bradmac** [comment]
We need to ensure that the Rewards and Promos app does not depend on RewardStore.

**Comment by tuzzmaniandevil** [comment]
Works fine with the Reward Store app off.

The promo was configured for the wrong website which didn't have the Rewards and Promotions app turn on. It was setup for `vlad43-leads` and not `vlad43-promo`. Changing the website to `vlad43-promo` where the app is turned on made it work

**Comment by Uafinder** [comment]
My mistake...
Anyway we now have App Install for Promotions which is great
