### ISSUE TITLE
When no rewards is available area for rewards are still clickable and leads to error

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4376]
![image](https://user-images.githubusercontent.com/1945230/32653412-8423c398-c610-11e7-8f3c-bd513533d919.png)
![image](https://user-images.githubusercontent.com/1945230/32653419-8a2c9828-c610-11e7-9b95-f80e0faaa7a1.png)
http://vlad43-promo_vlad-test43.kademi-ci.co/rewards/
http://vlad-test43.admin.kademi-ci.co/rewards/

**Comment by anhnt** [comment]
Fixed

**Comment by Uafinder** [comment]
It works
