### ISSUE TITLE
Delete all leads on the second page cause impossible to go back

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4377]
For example you have 120 leads separated to 2 pages. You go to second page, select all leads on the second page by select all checkbox, press delete.
All leads on the second page are deleted, pages component disappear and you would have an empty list with 100 leads in it.
![image](https://user-images.githubusercontent.com/1945230/32655714-7ffb4bc2-c617-11e7-9470-2ca9799f3e91.png)
![image](https://user-images.githubusercontent.com/1945230/32655479-5b2c6688-c616-11e7-9a3e-465336164a63.png)
http://vlad-test43.admin.kademi-ci.co/funnels/journey1/version1/

Also after that main leads page begin to work badly...
It's displaying only 28 records instead of 100...

**Comment by gonzalon** [comment]
@Uafinder now it would update the number of leads and the table but would leave the paginator as is.
You should see something like:

![image](https://user-images.githubusercontent.com/2773216/33866201-1a471282-df5a-11e7-9e04-747f1371114e.png)

**Comment by Uafinder** [comment]
Yeap, looks fine at the moment
