### ISSUE TITLE
KCRM: Displaying records counter bad on Contacts page

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4378]
![image](https://user-images.githubusercontent.com/1945230/32656038-e42f9dd6-c618-11e7-83d2-d0258c9eadff.png)
http://vlad43-leads_vlad-test43.kademi-ci.co/custs/?startPos=100&pageSize=100
http://vlad-test43.admin.kademi-ci.co

**Comment by gonzalon** [comment]
Fixed: 
![image](https://user-images.githubusercontent.com/2773216/32706897-2786e9cc-c885-11e7-9bbe-c84828dcd51f.png)

**Comment by Uafinder** [comment]
Looks great
