### ISSUE TITLE
KCRM: Payments menu bad

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4379]
![image](https://user-images.githubusercontent.com/1945230/32656725-c87ad580-c61b-11e7-901b-09ed2ad1b802.png)
http://vlad43-leads_vlad-test43.kademi-ci.co
http://vlad-test43.admin.kademi-ci.co/

**Comment by mkhoudary** [comment]
This is not a bug, this is something wrong with the account the payment-lib isn't activated, I activated it and it worked normally.

**Comment by bradmac** [comment]
@Uafinder the menu item should be present (by default) when the app is enabled. I think Leadman depends on the payments app, so the Payments app will be enabled when Leadman is enabled. 

Note that the list of apps displayed beside the "Find more apps" button is not a complete list of apps, its just showing marketplace apps, it doesnt show libs, themes and other dependencies.

If you switch to the apps tab you will see Payments app is enabled:
![image](https://user-images.githubusercontent.com/826458/33746714-c7aa0dba-dc23-11e7-8d1b-014dcd3c9f73.png)

**Comment by Uafinder** [comment]
ok, so payments app is enabled, but payment lib as @mkhoudary  says is not enabled...
So, when Leadman app installed it either should disable payments menu or enable payments-lib...

**Comment by bradmac** [comment]
@mkhoudary the problem is that leadman-lib only depends on the payments app directly (ie the java app) but java apps dont have dependencies
```
        {
            "appId": "paymentApp",
            "branch": ""
        }
```

Please change this so that the marketplace app KPayment is a dependency. I think it makes more sense for this to be a dependency of KLeadman rather then leadman-lib

**Comment by bradmac** [comment]
@anhnt please update dependencies as above

**Comment by bradmac** [comment]
use KLeadMan 1.0.7

**Comment by Uafinder** [comment]
Yup, it works like a charm
