### ISSUE TITLE
KCRM: Leads page pagination?

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4380]
![image](https://user-images.githubusercontent.com/1945230/32657385-392baa6e-c61e-11e7-8849-3ae6f7e846f1.png)
Does leads page need a pagination?
http://vlad43-leads_vlad-test43.kademi-ci.co/leads/?query=&leadType=active

**Comment by bradmac** [comment]
No, not at the moment.

The intended usage of this page isnt consistent with pagination

**Comment by Uafinder** [comment]
Ok, no probs!
