### ISSUE TITLE
KCRM: Unlink company button should be removed from company page

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4381]
![image](https://user-images.githubusercontent.com/1945230/32661276-0c02d3d0-c62f-11e7-9d29-1290c6986fab.png)
Pressing it cause reset all data for company, so probably just need to remove button (or probably change title). Note that leads remain linked to org even if you press this button.
http://vlad43-leads_vlad-test43.kademi-ci.co/companies/1917470

**Comment by anhnt** [comment]
Removed that button

**Comment by Uafinder** [comment]
Yup, button removed
