### ISSUE TITLE
Blogs content editor doesn't work on chrome

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#4382]
here : https://oceanyouth.admin.kademi.com.au/blogs/homepage/oy-advisory-committee-sydney/#bodyCopy-tab
When I try to edit content the editor stays in a loading state and does not work
this case just on chrome browser

![capture1](https://user-images.githubusercontent.com/26510030/32696975-2ef5f2c2-c78e-11e7-9ce9-db29f552bd42.PNG)

But when I try on firefox browser it works well

**Comment by bradmac** [comment]
This looks like the https/http problem. @ducdhm can you take a look and then lets talk about how to resolve

**Comment by bradmac** [comment]
hey @tuzzmaniandevil i think that if the current admin site is https we need to use a https address for the blog article

**Comment by ducdhm** [comment]
@tuzzmaniandevil At the moment in CI, If I use https, it'll redirect to Kademi.Chat. So I can't test it.

**Comment by bradmac** [comment]
@tuzzmaniandevil lets chat..

**Comment by tuzzmaniandevil** [comment]
Fixed HTTPS on CI. It's only using a self-signed cert but it works but websockets as well

**Comment by ducdhm** [comment]
@tuzzmaniandevil With `https://rootorg.admin.kademi-ci.co/organisations/2054263/edit` link, I got this error

```
This page isn’t working

rootorg.admin.kademi-ci.co redirected you too many times.

ERR_TOO_MANY_REDIRECTS
```

**Comment by tuzzmaniandevil** [comment]
@ducdhm Fixed :-)

**Comment by ducdhm** [comment]
Done!

**Comment by AlaaKhalaf94** [comment]
It is work well now
