### ISSUE TITLE
Fix htmlPanel component

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#4385]
Example: http://version2.idhealth-training_3dn.kademi.com.au/programs/prof-disability/DP01/MOD03/contenteditor?fileName=pfeedback.html

**Comment by ducdhm** [comment]
Fixed!

**Comment by bradmac** [comment]
Hey @ducdhm I've checked on the 3DN site and i cannot see an editor for the html panel component

http://version2.idhealth-training_3dn.kademi.com.au/programs/prof-disability/DP01/MOD03/contenteditor?fileName=pfeedback.html

Tested in Firefox and Chrome including in incognito mode.

![image](https://user-images.githubusercontent.com/826458/32746441-7f89e936-c91a-11e7-80c7-aaac4d2c38be.png)

**Comment by bradmac** [comment]
Note that i do see the editor working on this page:
http://version2.idhealth-training_3dn.kademi.com.au/programs/prof-disability/DP01/MOD02/contenteditor?fileName=pwhat-is-mental-illness.html

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
works great!
