### ISSUE TITLE
Enabling vouchers app doesn't cause appearing it in the menu

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4387]
![image](https://user-images.githubusercontent.com/1945230/32720568-9c729402-c86c-11e7-9837-cb0f21dd933c.png)
1. Enable voucher app
2. Appropriate menu items doesn't appear in side menu
3. Looks like it depends on Rewards app, because if you enable it - all items will appear correctly

http://vlad-test45.admin.kademi-ci.co/manageApps/#installed-tab

**Comment by bradmac** [comment]
Fixed

**Comment by Uafinder** [comment]
yup
