### ISSUE TITLE
ORG search does not work

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4390]
http://kademi.admin.kademi.us/organisations/

Search for 'Incentive Logic'

This org does exist, and  it does not refine to show only this ORG.

**Comment by bradmac** [comment]
It does for me:
![image](https://user-images.githubusercontent.com/826458/32749233-9cdba430-c923-11e7-975b-81fda4405d61.png)

**Comment by bradmac** [comment]
But the ranking is screwy. It should be sorting by relevance, and "incentive logic" should be at the top of the list when searching for "incentive logic"

**Comment by bradmac** [comment]
When no ordering field is selected:
- if there is no search criteria, order by title
- if there is a search criteria, order by relevance

**Comment by bradmac** [comment]
And please remove the address field

**Comment by gonzalon** [comment]
![image](https://user-images.githubusercontent.com/2773216/32752811-7680f40a-c92f-11e7-9fda-0a8d0cfd8fd6.png)

![image](https://user-images.githubusercontent.com/2773216/32752816-80e424a8-c92f-11e7-9474-18a3134fe7e2.png)

**Comment by Uafinder** [comment]
There are no default sorting:
![image](https://user-images.githubusercontent.com/1945230/32838824-eada6796-ca1a-11e7-9c72-039ff6752c96.png)

http://vlad-test50.admin.kademi-ci.co/organisations

**Comment by gonzalon** [comment]
1. by default its ordering by relevance, this is for the original issue Paddy reported:

Ex
![image](https://user-images.githubusercontent.com/2773216/32927572-2f822814-cbb2-11e7-9b57-840669017633.png)

![image](https://user-images.githubusercontent.com/2773216/32927608-66df048a-cbb2-11e7-8744-7db971d999a8.png)


2. Fixed

**Comment by Uafinder** [comment]
ok
