### ISSUE TITLE
Deleting a lead should delete any associated tasks

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4391]
Currently after a lead is deleted, its tasks are still active.

**Comment by bradmac** [comment]
OK, thats weird, I'm sure it was doing that..

**Comment by paddyow** [comment]
From memory I deleted the lead from here http://kcrm.kademi.us/leads/?query=&leadType=active

Using the check boxes.

**Comment by AlaaKhalaf94** [comment]
passed
