### ISSUE TITLE
Editor panel layout different in editor and front end site

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4392]
Here is how a page looks when viewed in the front end:

![image](https://user-images.githubusercontent.com/826458/32756514-57ecc39c-c93f-11e7-87ed-2b0a1310a3b6.png)
http://www.idhealtheducation.edu.au/programs/prof-disability/DP01/MOD02/pwhat-is-mental-illness.html

Here is how it looks in the editor:
![image](https://user-images.githubusercontent.com/826458/32756528-6c1e853a-c93f-11e7-99d5-352187b90190.png)
http://version2.idhealth-training_3dn.kademi.com.au/programs/prof-disability/DP01/MOD02/contenteditor?fileName=pwhat-is-mental-illness.html

**Comment by ducdhm** [comment]
@bradmac The reason here is because in `masterTemplate.html`, developers added new less file

```
        $templater.pushLess("/theme/less/bootstrap.less", "all", 0)
        $templater.pushLess("/theme/theme-params.less", "all")
        $templater.pushLess("/theme/style.less", "all")
```

but in `contentEditor.html`, we have only 2 less files
```
        $templater.pushLess("/theme/less/bootstrap.less", "all", 0)
        $templater.pushLess("/theme/theme-params.less", "all")
```

That's why.

**Comment by ducdhm** [comment]
@Anton69arb Can you help me create an article in our docs site. This article is about how to styling in Kademi in correct way. The content is 

```Kademi has a standard less file for styling named "theme-params.less". All CSS rules, LESS variables should be in this file. If you want to modularize your less by having multi-less files, you should import theme in "theme-params.less" instead of adding them in "masterTemplate.html". 

Note: If you add custom less files in "masterTemplate.html", your styles will be not showed in content editor screen.
```

**Comment by bradmac** [comment]
hey @ducdhm this will go into our developer section, but we're not working on that yet
