### ISSUE TITLE
Cant upload video to video component

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4393]
Editing this page:
http://docs.kademi.co/getting-started/elearning/contenteditor?fileName=importing-a-scorm-module.html

Clicking the "Change your video" button does nothing:

![image](https://user-images.githubusercontent.com/826458/32759300-9a236b04-c94d-11e7-95e5-8022db9fb7ac.png)

I'm seeing this error on page load

`TypeError: selectPicker.selectpicker is not a function`

**Comment by anhnt** [comment]
This is fixed on QA https://github.com/Kademi/kademi-dev/issues/4330

**Comment by bradmac** [comment]
OK
