### ISSUE TITLE
Move keditor, contentEditor and edmEditor into libs

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#4394]

**Comment by ducdhm** [comment]
@bradmac I want a somethings like .ksyncingore for our ksync. I have `node_modules` folder for keditor which will be used for compiled keditor but I dont want to sync this folder because it's really huge. Can you provide me solution for it? Atm, everytime I sync keditor-lib, I need to remove `node_modules` and when I need to compile, I need to re-install node modules again. It'll take me a time for installing

**Comment by bradmac** [comment]
ok, we can add an ignored list to the ksync properties file

**Comment by ducdhm** [comment]
Done!

**Comment by ducdhm** [comment]
@bradmac I need only ignore properties for ksync.

**Comment by bradmac** [comment]
Actually, realised we dont need to put dependencies in AdminApp, we can just leave them in the old templates but remove from new templates using admin-lib

**Comment by bradmac** [comment]
hey @Uafinder we need to test keditor works for EDMs and web pages
- email editing works (eg journey emails, group and scheduled)
- web content editing works (web pages, blog articles, etc)

We need to test 2 situations
- when admin-lib is NOT installed. This is the initial situation
- when admin-lib IS installed. This will be for newly created accounts

**Comment by Uafinder** [comment]
- when admin-lib is NOT installed. This is the initial situation
Looks ok by quick look. Will investigate more precise tommorow

**Comment by bradmac** [comment]
From @Uafinder 

![image](https://user-images.githubusercontent.com/1945230/32951260-f7deaa36-cbb1-11e7-8908-cfa680fab7b6.png)
http://vlad-test55.admin.kademi-ci.co/groupEmails/2025672/#messages-tab

**Comment by bradmac** [comment]
added edmeditor lib to admin-lib deps

**Comment by Uafinder** [comment]
This one is fixed, others looks ok
