### ISSUE TITLE
Minor visual bug on dashboard when large users and orgs number

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4395]
![image](https://user-images.githubusercontent.com/1945230/32780712-f8a63b64-c94a-11e7-9cd8-1f50246b4ae0.png)
Resolution 1600*900
It looks pretty on full hd.
http://rootorg.admin.kademi-ci.co/

**Comment by bradmac** [comment]
Dont need to do anything about the autoloader, thats only for internal use.

I think we can change numbers for profiles and orgs to use abbreviated formatting like "15k"

use:
```
formatter.formatUnits
```

**Comment by gonzalon** [comment]
![image](https://user-images.githubusercontent.com/2773216/33188671-955a6eaa-d100-11e7-9679-882d9e5b989c.png)
![image](https://user-images.githubusercontent.com/2773216/33188680-a350649c-d100-11e7-9d36-708e28d1b2d6.png)
![image](https://user-images.githubusercontent.com/2773216/33188688-b7d71e9c-d100-11e7-85a5-d82a8c102921.png)


The only one I think it looks a bit weird its:

![image](https://user-images.githubusercontent.com/2773216/33188704-cf24b58c-d100-11e7-9348-134f33590808.png)

**Comment by Uafinder** [comment]
yup, it works!
