### ISSUE TITLE
Date picker, content editor and other js doesn't work - promotions

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4396]
![image](https://user-images.githubusercontent.com/1945230/32784163-b9318ad6-c956-11e7-9a11-dc9c2d8384e5.png)
http://vlad-test48.admin.kademi-ci.co/rewards/promo1qa/#details-tab
from console
GET http://vlad-test48.admin.kademi-ci.co/static/keditor/dist/js/keditor-0.0.0.min.js 404 (Not Found)

**Comment by bradmac** [comment]
Need to either have the formbuilder dependency included in the admin, or statically add the formbuilder js

**Comment by bradmac** [comment]
Please install from the marketplace:

![image](https://user-images.githubusercontent.com/826458/32818112-3513eff2-ca26-11e7-92cb-86190f8a1535.png)

**Comment by bradmac** [comment]
Note that the problem will only be solved if KPromotions is installed, as this has the dependencies. Enabling promotions directly from the apps page will not work correctly. We will remove the ability to enable from the apps page in the near future

**Comment by Uafinder** [comment]
works like a charm...
the install app approach - is very suitable for end user...
