### ISSUE TITLE
Quiz enhancements to support dynamic CPD allocation based on num attempts

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#44]
- num quiz attempts in quiz template
 - trigger to fire on quiz attempt/success
 - trigger is able to issue CPD points
 - certificate template to display sum of cpd

**Comment by Uafinder** [comment]
"trigger to fire on quiz attempt/success" -> works ok!

**Comment by Uafinder** [comment]
1. When action is to "Award CPD points" this is not displaying on the main triggers page.
![image](https://cloud.githubusercontent.com/assets/1945230/5892370/3193f630-a4c5-11e4-81c8-51033b5dc063.png)
2. Maybe we should add a num of awarded CPD points to the user profile. Very difficult to track either user gain them or not.
3. minor text issue... should be something like "please specify a users email..."
![image](https://cloud.githubusercontent.com/assets/1945230/5892455/65e76898-a4c7-11e4-9975-e59c65b60ced.png)

**Comment by bradmac** [comment]
@tuzzmaniandevil , could you look into these issues?

**Comment by tuzzmaniandevil** [comment]
"minor text issue... should be something like "please specify a users email..." " - Done

**Comment by tuzzmaniandevil** [comment]
"When action is to "Award CPD points" this is not displaying on the main triggers page. " - Fixed

**Comment by tuzzmaniandevil** [comment]
"Maybe we should add a num of awarded CPD points to the user profile. Very difficult to track either user gain them or not." - In the admin console, if you go to the manage users page these is a section called "Learning statistics", if you click on that it will show all the modules that have been completed and with how many attempts.

**Comment by tuzzmaniandevil** [comment]
"Maybe we should add a num of awarded CPD points to the user profile. Very difficult to track either user gain them or not." - Added section in user profile under Learning Staticstics called CPD Points, this will now show all CPD points allocated to the user

**Comment by tuzzmaniandevil** [comment]
"I have a trigger which should award CPD points to user when it completes one of the learning modules. http://admin.asmi.olhub.com/autoEmails/aahha/ (test_CPD). I've complete a module with user vw-demo5, use 2 attempts. Looks like points are not awarded, or it's not seen anywhere." - Cannot replicate.

**Comment by bradmac** [comment]
@Uafinder could you confirm if the issue above is still an issue?

**Comment by Uafinder** [comment]
well, i still cant award those CPD points to my user.
I've used this trigger http://admin.asmi.olhub.com/autoEmails/aahha/ (When a learner passes quiz true in asmi-demo:VWAG_1/Seat/Seat1, then award 25.0 CPD Points for certificate SEAT certif) and user vw-demo6.
![image](https://cloud.githubusercontent.com/assets/1945230/6050458/5871ec16-acc8-11e4-8c6d-1269052a6944.png)
I'm not sure. Possible i'm wrong anywhere...

**Comment by bradmac** [comment]
Hey @tuzzmaniandevil, can you please confirm that you are able to award CPD points through the trigger in QA? If you can then might be worth having a chat with Vlad on skype

**Comment by tuzzmaniandevil** [comment]
![screenshot - 090215 - 10 28 47](https://cloud.githubusercontent.com/assets/3378330/6098531/80bfc6a8-b046-11e4-8e48-d78a3f38456e.png)
I tried it with the VW training course and change the event and seems to work, didn't work with SEAT, there seems to be an issue with the SEAT quiz, doesn't allow me to finish. Maybe check the quiz is setup correctly.

**Comment by tuzzmaniandevil** [comment]
Issue has been fixed.

**Comment by Uafinder** [comment]
This bug is fixed.
I need assistance on certificate setting to see on it awarded points. Could you give me an example?!
