### ISSUE TITLE
Invoices page, buttons not working

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4400]
http://moblix.admin.kademi-ci.co/invoices/1976221#

![image](https://user-images.githubusercontent.com/826458/32812987-a92e5504-ca0c-11e7-8054-88a5000083d1.png)

**Comment by bradmac** [comment]
Send form something like this:
![image](https://user-images.githubusercontent.com/826458/32860542-c7309350-cab6-11e7-8211-df0212accd10.png)

**Comment by gonzalon** [comment]
PDF:

![image](https://user-images.githubusercontent.com/2773216/32926916-baafda16-cbae-11e7-8437-c66787ba47e0.png)

Send:
![image](https://user-images.githubusercontent.com/2773216/32926936-c88ad51e-cbae-11e7-9311-a9fb069d0df6.png)

![image](https://user-images.githubusercontent.com/2773216/32926945-d4360d34-cbae-11e7-9a79-e59cf25b70c6.png)

**Comment by AlaaKhalaf94** [comment]
Hi @gonzalon , here : http://newfresh.admin.kademi-ci.co/invoices/2225559/ I try to send Invoice but it shows me error 

"An error occured: org.hibernate.PropertyValueException: not-null property references a null or transient value: io.milton.cloud.server.db.EmailItem.fromAddress - java.lang.RuntimeException: org.hibernate.PropertyValueException: not-null property references a null or transient value: io.milton.cloud.server.db.EmailItem.fromAddress"

![capture1](https://user-images.githubusercontent.com/26510030/33363193-fa4c726e-d4e7-11e7-9c7b-795f90a5b041.PNG)

**Comment by gonzalon** [comment]
Fixed

**Comment by AlaaKhalaf94** [comment]
here : http://fresh01.admin.kademi-ci.co/invoices/3015623/# , I can't save data in "Update Invoice Items" table
I click on save button and shows me alert that the save done , but it doesn't

![capture1](https://user-images.githubusercontent.com/26510030/33540642-abde5246-d8d4-11e7-859d-a17352f12acf.PNG)

**Comment by gonzalon** [comment]
@AlaaKhalaf94 at the moment it's working. I just saved some data in your test account.

![image](https://user-images.githubusercontent.com/2773216/33575484-afc1f2b4-d9a1-11e7-8549-5a3ee67c571e.png)

The save button saves the "Update Invoice details"
And for the details if you start typing and use tab to move to the next field it would automatically save it.

**Comment by gonzalon** [comment]
Now it saves the details on Enter or when the input loose the focus.

**Comment by AlaaKhalaf94** [comment]
@gonzalon , The Vendor feild doesn't inserted in PDF "print"
http://fresh03.admin.kademi-ci.co/invoices/3061439/

![capture1](https://user-images.githubusercontent.com/26510030/33600355-aaf564b8-d9b1-11e7-93ac-4b7d980e426c.PNG)

http://fresh03.admin.kademi-ci.co/invoices/3061439/invoicePreview.html?pdf

![capture2](https://user-images.githubusercontent.com/26510030/33600362-b367683a-d9b1-11e7-9cb9-de71493033f6.PNG)

**Comment by gonzalon** [comment]
Fixed!
![image](https://user-images.githubusercontent.com/2773216/33630880-bc0fca1a-da6d-11e7-8723-55cdaea9a01c.png)

**Comment by AlaaKhalaf94** [comment]
@gonzalon , here : http://fresh03.admin.kademi-ci.co/invoices/3061439/ in Send Invoice modal , I set that I want to send me a copy
but I didn't receive any email on : alaa@kademi.co

![capture1](https://user-images.githubusercontent.com/26510030/33651203-ab88a73e-da6d-11e7-99e3-bb0c4cf75019.PNG)

**Comment by gonzalon** [comment]
Fixed, and just tested it in CI.

Mailinator acc:
![image](https://user-images.githubusercontent.com/2773216/33692476-5bc6dac8-db52-11e7-9e8e-11ac45eb27e1.png)

My email:

![image](https://user-images.githubusercontent.com/2773216/33692495-69567f72-db52-11e7-8011-e2202a756ada.png)

**Comment by AlaaKhalaf94** [comment]
passed
