### ISSUE TITLE
Calendar enhancements

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4401]
- on the event attendees page, allow adding a new attendee. See CalEventAttendeesResource and manageAttendees.html , this should a similar form as the front end which allows selecting guests
- allow confirming attendance for attendees, this should set the participationStatus property of the AttendeeRequest to CONFIRMED
- add a button to generate invoices. This will generate 1 invoice per primary attendee, with line items for the attendee and each guest. The invoice title should be "[TITLE OF EVENT] with [NUM GUESTS] guests", if guests is > 0

**Comment by gonzalon** [comment]
To test:
1. Create a calendar
2. Create an event
3. Enter to the event details, and go to tab "Attendees" > button "View"
4.

![image](https://user-images.githubusercontent.com/2773216/33157807-9808f50a-d069-11e7-9306-e7b2f4b241ac.png)

**Comment by AlaaKhalaf94** [comment]
Hi @gonzalon , that's work well

but when I generate Invoice to one of attendee , it Generate Invoice with big Invoice number
what is this number ?

http://fresh01.admin.kademi-ci.co/invoices/

![capture1](https://user-images.githubusercontent.com/26510030/33545622-6c00b2f0-d8e7-11e7-9309-81243a1a1668.PNG)

**Comment by gonzalon** [comment]
@AlaaKhalaf94 this is the invoice number that its being generated automatically. We are going to change it to be numbers but so far its like that

**Comment by AlaaKhalaf94** [comment]
passed
