### ISSUE TITLE
Learners app when install learners group doesn't add to specific roles

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4403]
1. Install KLearning app
2. Check Learners group and it will not have "Content Viewer" and "Learners" roles assigned.
http://vlad-test50.admin.kademi-ci.co

**Comment by bradmac** [comment]
Hi @anhnt can you do this please? Just need to add some controller code in app.js

See KLeadman for an example

**Comment by anhnt** [comment]
Done

**Comment by Uafinder** [comment]
It works!
