### ISSUE TITLE
Vouchers issues

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4404]
http://vlad-test50.admin.kademi-ci.co/voucher-type/
http://vlad50-vouch_vlad-test50.kademi-ci.co/vouchers
1. What should Voucher table contain without search?
![image](https://user-images.githubusercontent.com/1945230/32834787-87c91e6c-ca0c-11e7-9ff3-ba083e6125db.png)

2. Change status and redeem buttons should work only when some checkboxes selected.
![image](https://user-images.githubusercontent.com/1945230/32834780-7ee13244-ca0c-11e7-8a9a-bc981988126c.png)

3. When you select some voucher by checkbox and click "redeem" or "change status" - it will says that it's ok, but status will not change.
![image](https://user-images.githubusercontent.com/1945230/32835461-dd06d1c4-ca0e-11e7-8dfb-401d56a99e78.png)
![image](https://user-images.githubusercontent.com/1945230/32835472-e2c7203c-ca0e-11e7-82b8-56df89b01a8b.png)
![image](https://user-images.githubusercontent.com/1945230/32835476-e8fe449e-ca0e-11e7-975d-371798df4e95.png)
![image](https://user-images.githubusercontent.com/1945230/32835497-fe44a3e8-ca0e-11e7-9871-9cbf1f331a7a.png)

4. Change status button probably would be great to rename to Mark as pending (or just Pending).
![image](https://user-images.githubusercontent.com/1945230/32835529-1b0a877c-ca0f-11e7-8da2-0dfafe54eb5e.png)
![image](https://user-images.githubusercontent.com/1945230/32835537-20934b52-ca0f-11e7-896c-9367dc73ebe0.png)

5. Probably user should see vouchers which was redeemed by himself without search.

6. Probably user should not see vouchers which was allocated to another org or user.
![image](https://user-images.githubusercontent.com/1945230/32835600-61a48458-ca0f-11e7-88ca-7d9eec179a5f.png)
![image](https://user-images.githubusercontent.com/1945230/32835619-710c44e4-ca0f-11e7-8810-cb3826fea259.png)

7. Probably should be some validation on selling vouchers and allocating them to someone.
![image](https://user-images.githubusercontent.com/1945230/32835653-9ad061e8-ca0f-11e7-894a-ec6500305a26.png)

**Comment by bradmac** [comment]
> What should Voucher table contain without search?

It should be empty

> Change status and redeem buttons should work only when some checkboxes selected.

OK, we should add a messge "Please select one or more vouchers"

> When you select some voucher by checkbox and click "redeem" or "change status" - it will says that it's ok, but status will not change.

The status should be updated. This looks like a server side bug.

> Change status button probably would be great to rename to Mark as pending (or just Pending).

This is intended to open a form allowing the voucher to be set to any status, not just pending. So might be the wrong form showing

> Probably user should see vouchers which was redeemed by himself without search.

No, we dont need that. Cashiers are generally not interested in redeemed vouchers, they are focused on processing customers who present vouchers, which need to checked they havent been redeemed.

> Probably user should not see vouchers which was allocated to another org or user.

No, they need to see vouchers which have been redeemed, as long as its from a voucher type that the user has access to via their redeeming organisation.

**Comment by bradmac** [comment]
So @gonzalon please check issue with redeem and change status above. Also check that the change status button should be opening the change status form.

**Comment by Uafinder** [comment]
Ok, most of them are ok...
will create a separate one if needed
