### ISSUE TITLE
All Help pages inaccessible

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4406]
![image](https://user-images.githubusercontent.com/1945230/32836688-5b971b12-ca13-11e7-98c0-cf51503a1b73.png)
![image](https://user-images.githubusercontent.com/1945230/32836702-684e1cde-ca13-11e7-9781-af85b7eb8a79.png)

**Comment by anhnt** [comment]
that was fixed last week

**Comment by Uafinder** [comment]
Great!
