### ISSUE TITLE
Scheduled emails - multiple sending detected

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4410]
http://vlad-test50.admin.kademi-ci.co/scheduledEmails/scheduledqa01/#configuration-tab
I have such configuration
It cause multiple emails send to one recipient...
[email_history log.xlsx](https://github.com/Kademi/kademi-dev/files/1475356/email_history.log.xlsx)
It sends 38 email to one user

probably it happens only for first scheduled sending

**Comment by bradmac** [comment]
Hi Vlad, please test with normal groups, not dynamic.

Its actually not a realistic test case to use this with dynamic group.s

**Comment by Uafinder** [comment]
Not sure why you say that, but you're the boss :)
