### ISSUE TITLE
Make navbar menu component border configurable

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4412]
Our client has a site here:
http://versionnew2.gilpinperformance-gilpin.kademi.com.au/

By default the menu has a light grey border, but she wants no border on the navbar

Please provide a configurable option in keditor to control this, either as
- an option on the menu component
- a theme variable in the variables editor

**Comment by anhnt** [comment]
Done via theme variables settings
![image](https://user-images.githubusercontent.com/735555/33055026-9fa88c50-ceaf-11e7-9bc8-775c20c139f4.png)

**Comment by ducdhm** [comment]
@anhnt Please make its border width configurable

**Comment by anhnt** [comment]
As discussed with brad we decided to leave it as is for now

**Comment by AlaaKhalaf94** [comment]
passed
