### ISSUE TITLE
KEditor: containers should not resize while dragging a component

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4414]
When i'm editing a page in KEditor I often need to move components from one container to another. This is often very frustrating because when i start dragging a component the container it was in changes size, and shifts other containers around, making it hard to find the container i intended to drag it to.

Please see if you can do an update so container height is set immediately before dragging, and then put back to normal when the drag is completed?

**Comment by ducdhm** [comment]
Done!

**Comment by bradmac** [comment]
I cant see the update working. I'm testing in a site with the latest admin-lib and content editor lib

This is before drag:

![image](https://user-images.githubusercontent.com/826458/32915516-01d71d04-cb7e-11e7-9bb0-48d0797a9e9e.png)

This is during the drag. As you can see the container I'm dragging from has collapsed in size

![image](https://user-images.githubusercontent.com/826458/32915525-1377c964-cb7e-11e7-82e8-2e2a594618f4.png)

**Comment by ducdhm** [comment]
@bradmac It's working fine in my local. Can you double-check keditor-lib and contentEditor-lib are enable or not in your local?
