### ISSUE TITLE
Add product order from admin

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4415]
Please add a UI feature to the orders page to add an order directly:
http://localhost:8080/shopping-carts/

- use the profile entity finder jquery plugin to lookup a customer
- allow setting address fields
- allow adding multiple product order line items

**Comment by bradmac** [comment]
@Uafinder i think this is ready for test now

**Comment by Uafinder** [comment]
Can you give me an example... it's from http://vladtest03b.admin.kademi-ci.co/shopping-carts/ here?
Or it should be something like: http://vladtest03b.admin.kademi-ci.co:8080/shopping-carts/
?

**Comment by bradmac** [comment]
wes says its not quite done yet..

**Comment by tuzzmaniandevil** [comment]
@ducdhm Could you please add a search box to the Modal so a user can search for products then add it to the form?
They should also be able to delete products and change the quantity/variants

There is a search API here are the params:
`url: /shopping-carts/?searchProducts`
```
searchProducts=true
storeType={storeType input}
rewardStoreName={rewardStoreName input}
eCommStoreName={eCommStoreName input}
q={the search query}
```

**Comment by bradmac** [comment]
@tuzzmaniandevil as discussed, please consider moving those end points to the respective apps resources

**Comment by tuzzmaniandevil** [comment]
Changed endpoints.
For eCom use `/ecommerce/{store-name}/`
For reward use `/reward-store/{store-name}/`

For both use these parameters:
```
searchProducts=true
q={the search query}
```

**Comment by Uafinder** [comment]
Hey @gonzalon, give me a bit more info pls

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/36503731-f3ed4872-17b2-11e8-9497-caef005d3808.png)

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/36503862-74d6314c-17b3-11e8-8a7b-20a1b2e0203b.png)

**Comment by bradmac** [comment]
@gonzalon I've just seen a couple of problems
- when an order is placed it doesnt appear in the list. Please do a reloadFragment
- I couldnt see the product search working

**Comment by gonzalon** [comment]
Added the reload fragment and a message to clarify that you have to enter at least 3 characters to start searching by product code or title.

**Comment by Uafinder** [comment]
1. Validation should works on all necessary fields
http://vladtest37a.admin.kademi-ci.co/shopping-carts/
![image](https://user-images.githubusercontent.com/1945230/36586217-a1ca2f1a-1889-11e8-8395-8ceb0ff915de.png)

2. Product name should be completed after successful search selection
-enter to search first three symbols of product, select it from dropdown list
![image](https://user-images.githubusercontent.com/1945230/36586310-f6b59af0-1889-11e8-86c8-2138c927a8d8.png)

3. Should be a standard country selector as it usual
![image](https://user-images.githubusercontent.com/1945230/36586354-1daf7248-188a-11e8-9c2d-3700959a130e.png)

4. After completing fill order it doesn't display in the order list. Refresh doesn't help. re-index doesn't help. 
![image](https://user-images.githubusercontent.com/1945230/36586371-2bcd4d96-188a-11e8-9b20-bd7f2ac4439d.png)

**Comment by gonzalon** [comment]
- Added validations, and countries dropdown:
![image](https://user-images.githubusercontent.com/2773216/36696503-3d367586-1ba9-11e8-9d8a-7f0b1e2ba95b.png)

![image](https://user-images.githubusercontent.com/2773216/36696515-48704418-1ba9-11e8-918c-ab9a93db4e10.png)

- Now it also clean the search input once you select the product.
- Saving / refreshing its working fine now

**Comment by Uafinder** [comment]
Yup, mostly looks fine
One question about validation:
![image](https://user-images.githubusercontent.com/1945230/36901298-636dfd4a-1e2f-11e8-8e0d-54f199811189.png)
these fields are looks not mandatory, but probably should be...
How do you think?

**Comment by bradmac** [comment]
I think we can leave that to the administrator to decide whether to enter those fields or not.

**Comment by Uafinder** [comment]
Ok, so looking good
