### ISSUE TITLE
Lead fields for assigned to properties

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4418]
We want to replace this with standard fields
```
@{lead.assignedToProfile.formattedName}
@{formatter.ifNull(assignedTo.allFields.?jobTitle, '')}
```

**Comment by bradmac** [comment]
Can now use this:

```
*|lead_assignedTo_FullName|*
*|lead_assignedTo_jobTitle|*
```

![image](https://user-images.githubusercontent.com/826458/32865059-639295e0-cac6-11e7-90ec-bc8a8122fcd5.png)

**Comment by AlaaKhalaf94** [comment]
Hi @bradmac , I can't find job Title
http://version1.fresh04-fresh04.kademi-ci.co/contenteditor?fileName=golden.html

![capture1](https://user-images.githubusercontent.com/26510030/33715550-a30821d6-db5b-11e7-86a9-29762f16df16.PNG)

**Comment by bradmac** [comment]
@AlaaKhalaf94 the examples above are custom fields for the assigned sales person. So you would need to create a custom field called "jobTitle" for the sales person group to see the same as my example above.

However, there is also a jobTitle property for the lead itself, and i've added a field for that.

**Comment by AlaaKhalaf94** [comment]
checked
