### ISSUE TITLE
Confusing UI for editing pages

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4419]
Client by default was clicking the drop down, then editing the page which opens the WYSIWYG editor so thought there was a problem with Keditor.

To open Keditor you have to click the edit button, which he was not doing.

We need to clearly differentiate between the 3 types of editing.  The edit icon should by default use Keditor, but the drop down should show the 3 ways to edit in case the user bypasses the edit icon.

![image](https://user-images.githubusercontent.com/2201340/32867569-ec345cd0-cac1-11e7-90b4-9e6be727bbe5.png)

**Comment by bradmac** [comment]
Done.

![image](https://user-images.githubusercontent.com/826458/32869480-09f31c38-cadc-11e7-82c8-a8b5dcf44214.png)

**Comment by AlaaKhalaf94** [comment]
passed
