### ISSUE TITLE
Manage orgs page, add aggregation with filtering for parent org

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4420]
Related https://github.com/Kademi/kademi-dev/issues/3140

Should be like on manage users page where we can see the number of orgs by parent org, and click on them to filter

![image](https://user-images.githubusercontent.com/826458/32872354-33861096-caeb-11e7-92cd-e2fceb3e0e78.png)

**Comment by gonzalon** [comment]
![image](https://user-images.githubusercontent.com/2773216/32917654-c3071c76-cb84-11e7-94d0-7f42571c4e41.png)

**Comment by Uafinder** [comment]
it's ok, there is an issue, moved to separate https://github.com/Kademi/kademi-dev/issues/4443
