### ISSUE TITLE
Need lead Title adding

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4423]
Currently it's hard to track leads when there are multiple with a single customer, the only way to do this is to open every lead then look at the notes.  

Add a lead 'Title' that sits with the lead description. 
![image](https://user-images.githubusercontent.com/2201340/32874739-2fa0525a-cae8-11e7-9e88-d2dcf6ddb185.png)

Add lead title next to score on leads page http://kcrm.kademi.us/leads/?query=&leadType=active

Additionally note lead description is not saving which needs fixing.

**Comment by gonzalon** [comment]
Need to deploy the libs.
Latest leadman-lib 1.7.2

**Comment by AlaaKhalaf94** [comment]
@gonzalon . here : http://version1.fresh03-fresh03.kademi-ci.co/leads/3064923/ when I change other field like "Lead Description" for example
then refresh the page , the content of "Lead Title" deleted

![capture1](https://user-images.githubusercontent.com/26510030/33606944-e532783a-d9c7-11e7-9ae0-dcbe2b55898c.PNG)

And I can't see Lead Title field in lead page from kademi console : http://fresh03.admin.kademi-ci.co/leads/3064923/#information-tab

**Comment by gonzalon** [comment]
Fixed, and added the title to the admin page :)

**Comment by AlaaKhalaf94** [comment]
Hi @gonzalon , I can't see Lead Title field in admin page : http://fresh04.admin.kademi-ci.co/leads/3089831/#information-tab

**Comment by gonzalon** [comment]
@AlaaKhalaf94  Ups sorry! Forgot about that, added!

**Comment by AlaaKhalaf94** [comment]
passed
