### ISSUE TITLE
Add company notes field

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4425]
Note the company list page is not working:
http://kcrm.kademi.us/companies/

Then open a company and add there.

![image](https://user-images.githubusercontent.com/2201340/32875568-cf0f759c-caec-11e7-81a8-a9bc558d2615.png)

**Comment by gonzalon** [comment]
![image](https://user-images.githubusercontent.com/2773216/33349704-2602fe9c-d500-11e7-8684-2d3aa2607327.png)
leadman-lib 1.7.3

**Comment by AlaaKhalaf94** [comment]
passed
