### ISSUE TITLE
KCRM Closing deal amount field prepopulating

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4426]
![image](https://user-images.githubusercontent.com/1945230/32891416-1fe76400-cadb-11e7-8a37-fd7f4b9b1e51.png)

Should deal amount be prepopulated while closing deal?

**Comment by bradmac** [comment]
Yep, should be pre-populated. And date should be defautled to current date/time

**Comment by anhnt** [comment]
Fixed

**Comment by Uafinder** [comment]
Yup
