### ISSUE TITLE
eComm manage stores issues

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4428]
http://vlad-test52.admin.kademi-ci.co/ecommerce/ecom/#products-tab

1. Search and category selection doesn't work
![image](https://user-images.githubusercontent.com/1945230/32894688-2dcfa374-cae6-11e7-8449-6f18f1277948.png)

2. Should be a validation on incorrect decimal symbols, and similar to reward stores
![image](https://user-images.githubusercontent.com/1945230/32894762-72afa43a-cae6-11e7-9fa4-f896bd7f79c7.png)

3. Should be a space in pop-up text
![image](https://user-images.githubusercontent.com/1945230/32894803-98a10832-cae6-11e7-8d9b-a5ae4efc8bb9.png)

**Comment by Uafinder** [comment]
1 and 3 are fixed
2 remain
Should be a validation on incorrect decimal symbols, and similar to reward stores
https://user-images.githubusercontent.com/1945230/32894762-72afa43a-cae6-11e7-9fa4-f896bd7f79c7.png
Fresh account
http://vlad-test64.admin.kademi-ci.co/ecommerce/vlad64-ecomm-ecomstore/#products-tab

**Comment by tuzzmaniandevil** [comment]
Done

**Comment by Uafinder** [comment]
yup, it works!
