### ISSUE TITLE
eComm installation should enable products database

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4429]
When you install eCommerce store it's just enable app and nothing else.
Should enable Products database, and create some pre-staged products (as it is in reward store app installation). 
http://vlad-test52.admin.kademi-ci.co

**Comment by bradmac** [comment]
True, ecom should depend on products app

**Comment by bradmac** [comment]
@anhnt can you please update the init script for KCommerce so it creates initial product database same as reward store does

**Comment by anhnt** [comment]
Done

**Comment by Uafinder** [comment]
Looks great
