### ISSUE TITLE
Supplier org search list ordering bad

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4431]
![image](https://user-images.githubusercontent.com/1945230/32896589-1ff757fa-caec-11e7-988b-de73e6c734f6.png)
Should be by name
http://vlad-test52.admin.kademi-ci.co/products/

**Comment by bradmac** [comment]
@ducdhm can we change this to use the org entity finder?

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/33009787-7aeac7f2-ce0a-11e7-951c-47eb96e5148a.png)

Done

**Comment by Uafinder** [comment]
It works
