### ISSUE TITLE
Import products weird behaviour

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4432]
I have an account with some products in it:
![image](https://user-images.githubusercontent.com/1945230/32896790-a4582e20-caec-11e7-8f51-8c0a369f1eaa.png)
I take next file:
[products(4).zip](https://github.com/Kademi/kademi-dev/files/1478899/products.4.zip)
Enter all necessary fields for import (id, name, title, base cost, etc)
![image](https://user-images.githubusercontent.com/1945230/32896905-f349f4b4-caec-11e7-8d76-e84fb98ad50c.png)
![image](https://user-images.githubusercontent.com/1945230/32897047-3f245f6e-caed-11e7-9a74-6239b55f96d7.png)
It says that ID is invalid in a part of rows, other part is ok.
Not quite understand why, because they are similar one to another.
Could you assist?
http://vlad-test52.admin.kademi-ci.co/tableUploaders/productsUploader

**Comment by bradmac** [comment]
The "ID" field is for Kademi's internal ID. Its only valid if there is a product in your account with that ID.

Just looking at the first row in the results above there is ID 57410. I cannot see any product with that ID in this account, so its not valid

**Comment by Uafinder** [comment]
Vlad 10:59 AM
i've realize that ID is not present and it should not work
but why it says that a half count of full list is present and they will be updated
?
brad 11:01 AM
maybe those ID's do match products?
Vlad 11:01 AM
nope
there are only 6 products left
the standard 6 ones

**Comment by bradmac** [comment]
Please investigate. According to Vlad there are records with ID's which do NOT match, but are not being shown as invalid.

**Comment by gonzalon** [comment]
@Uafinder can you still reproduce this?

![image](https://user-images.githubusercontent.com/2773216/33643449-07999656-daa4-11e7-82e1-d87668bab16b.png)

**Comment by Uafinder** [comment]
@gonzalon  Yup, here
Please try this account
http://vladtest01.admin.kademi-ci.co/products/
And use file whiche I provided:
https://github.com/Kademi/kademi-dev/files/1478899/products.4.zip

**Comment by gonzalon** [comment]
I can't reproduce it in your account either :( 

![image](https://user-images.githubusercontent.com/2773216/33739643-a9bad5d0-dc02-11e7-8af2-ad912e92c536.png)

**Comment by Uafinder** [comment]
@gonzalon don't select supplier column to import... suppliers are from the other org, so just ignore this column... you should see errors about product id

**Comment by gonzalon** [comment]
@Uafinder  Could reproduce it, and found what was happening. The problem was that we had deleted products with the same internal id. Now it's validating if the ID is from a deleted product, it would give you a validation error as "invalid id", also is checking that you can update the product checking the org ids.

**Comment by Uafinder** [comment]
Yup, looks good at the moment
