### ISSUE TITLE
KMediaLibrary - Media manager app

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#4434]
Similar to media management in Wordpress. Just better

**Comment by bradmac** [comment]
So here's what I'm thinking:
- start with an asset library, for storing images, video and text along with information about the media, eg dimensions, language, author, etc
- have an asset type which is a content item. For example, a content type might have an image, a video, a text field and a date
- content types can be provided by apps, and can also be user defined. Eg a custom blogging app could have a new content type representing a blog article. Or a user might define a content type for the "services" section of a website

**Comment by bradmac** [comment]
A key aspect of the Asset API is that it allows representing relationships between assets.

This will be used for representing that one image is a "thumbnail" of a video, but also for content types to have relationships which represent more meaningful relationships to other content items

**Comment by bradmac** [comment]
The Asset API is intended to allow different implementations. The initial implementation will just be in hibernate and using the BlobStore.

But we should create an implementation for production based on AWS Neptune. This will be good for managing the dynamic properties and relations between content items

**Comment by bradmac** [comment]
OK, so
- the content library app will be a custom app
- all content to be persisted and retrieved through the AssetManager
- the ContentTypeManager will be used for content types, both provided by apps and user defined
- all applications can use the AssetManager, they dont need to use the app

**Comment by bradmac** [comment]
Here's an example of a custom content type for representing pets:

![image](https://user-images.githubusercontent.com/826458/34473518-a6315f1c-efd8-11e7-95fd-df26c337b4c1.png)

**Comment by bradmac** [comment]
Example of a list of content and media types
![image](https://user-images.githubusercontent.com/826458/34473566-62779b78-efd9-11e7-8171-f4d5c700322f.png)

**Comment by bradmac** [comment]
Example of a list of assets, some media assets, some content assets
![image](https://user-images.githubusercontent.com/826458/34473575-809d0ca0-efd9-11e7-8e4e-43ba608e8ad8.png)

**Comment by bradmac** [comment]
Example of an image asset showing multiple tags and resized image views

![image](https://user-images.githubusercontent.com/826458/34473805-0bad9812-efdc-11e7-89cd-503a84211d2f.png)

**Comment by bradmac** [comment]
Closing, moving dev to specific issues
