### ISSUE TITLE
Auction placing bid does not update parameters

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4437]
1. Go to auction.
2. Place a bid
3. Note that Current Bid, bid count bid and bid history is not updating after you place bid...
![image](https://user-images.githubusercontent.com/1945230/32938788-03d040e2-cb86-11e7-8ba8-aae29f87b353.png)
http://vlad-test53.admin.kademi-ci.co

**Comment by bradmac** [comment]
Hi @anhnt I'm guessing this is a front end issue. But if you need back end support please just assign to me.

**Comment by anhnt** [comment]
Fixed. Looking good on new fresh account now http://version1.w1-anhtest9.kademi-ci.co/auctions/

**Comment by Uafinder** [comment]
1. When adding second bid and further bids, bid placer doubling in bid history.
![image](https://user-images.githubusercontent.com/1945230/33653267-350fb52c-da75-11e7-9b92-620862badadf.png)
2. When you are placing a bid, it uses your user id instead of username to display a bid information. Should be username instantly.
3. When someone placed a bid, while you are on the page - bids also doubling in bid history.
![image](https://user-images.githubusercontent.com/1945230/33653341-79edb806-da75-11e7-88e6-b9ff47188f54.png)
http://vlad-test69.admin.kademi-ci.co

**Comment by anhnt** [comment]
Found the issue with re-render bid history..

**Comment by anhnt** [comment]
@bradmac i figured out that the auction bid event was fired twice so the bid history is duplicated. Please have a look

https://github.com/Kademi/kademi-platform/blob/310d8c5455f92929882968ca85d0d8d3d2bd55f7/fuse-server/src/main/java/com/fuselms/apps/auctions/AuctionApp.java#L423

**Comment by bradmac** [comment]
@Uafinder please take a look

**Comment by Uafinder** [comment]
Still the same
![image](https://user-images.githubusercontent.com/1945230/33711822-05249eb6-db4e-11e7-9996-50a1127d53c8.png)
http://version1.vlad01auc2-vladtest01.kademi-ci.co/auctions/aucqa02/
http://vladtest01.admin.kademi-ci.co/websites/vlad01auc2/version1/#panel_details-tab

**Comment by tuzzmaniandevil** [comment]
Yup it can get fired twice. But have different actions. So i've added the action to the json now.
`BID_PLACED`
and
`OUTBID`

**Comment by anhnt** [comment]
Fixed @Uafinder please test on new account

**Comment by Uafinder** [comment]
Working great!
