### ISSUE TITLE
Media component for contentEditor

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#4439]
Options:
 * Vertical align for `media-left`
 * With for `media-left`

**Comment by Uafinder** [comment]
I can't find this component, how it looks like?

**Comment by ducdhm** [comment]
@Uafinder You need to enable `keditor-lib` and `contentEditor-lib` in your website to see this component. 

It looks like:
![newui](https://user-images.githubusercontent.com/1289631/33053441-23b35e94-cea6-11e7-8a58-f5713a95c2c6.png)

**Comment by bradmac** [comment]
hey @ducdhm please remember that @Uafinder should never have to install libs manually.

**Comment by ducdhm** [comment]
I have checked with fresh account, media component is available there.

**Comment by Uafinder** [comment]
No options at all... :(

![image](https://user-images.githubusercontent.com/1945230/33075812-6a399f7c-ced3-11e7-934a-7b2413b1bd93.png)
http://vlad-test57.admin.kademi-ci.co/websites/vlad57-tst1/version1/programs/p1/c1/m1/?contenteditor=psyesey.html

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
1. Add media component
2. Edit it
3. Add some left width parameter
4. Save and close editor
5. Open page for edit again, left width parameter would be empty.

**Comment by bradmac** [comment]
hey @ducdhm do we even need image dimensions?? For a media component the image should always fill its container. Having dimensions when the user hasnt entered them causes lots of problems, like we've seen with the standard photo component

**Comment by ducdhm** [comment]
@bradmac Without width, the image is not showed because in media component, it requires width for image to display. For simple and best solution, I removed the `height` option. Just keep `width` option only. Image's height always is auto

**Comment by bradmac** [comment]
It needs to be the width of the container, which I think is just standard bootstrap. Fixed widths won't work in a responsive site

**Comment by ducdhm** [comment]
@bradmac If you check in official page of Bootstrap, media component is not responsive component. I added some extra styles which allow media component responsive in Kademi

**Comment by Uafinder** [comment]
looks ok, but this one is bad
1 Add media component
2 Edit it
3 Add some left width parameter
4 Save and close editor
5 Open page for edit again, left width parameter would be empty.

**Comment by bradmac** [comment]
@ducdhm sorry i was thinking the component had an image above text, so the image had to be the container width. For this layout you're correct and we should just stick with the bootstrap standard.

I think we also need a component where the image is above the text, i'll create another issue for that

**Comment by bradmac** [comment]
Thumbnail component - https://github.com/Kademi/kademi-dev/issues/4546

**Comment by bradmac** [comment]
Please change the image height and width labels to say "Image height" and "Image width"

**Comment by ducdhm** [comment]
Done!

**Comment by Uafinder** [comment]
Great, it works!
