### ISSUE TITLE
Lowest unique bid auction

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4444]
https://en.wikipedia.org/wiki/Unique_bid_auction
I've read some about this auction and some questions appear:
1. According to information from wiki participants should not see bids from other participants and there is no mention of parameter current bid (for participant).
2. User can place a bid once. When he tried to place it second time, he receives an error:
![image](https://user-images.githubusercontent.com/1945230/32947979-3bebd5c0-cba6-11e7-90d0-b8217ba17ac0.png)
Error should be more user friendly.

http://vlad-test53.admin.kademi-ci.co/auctions/
http://vlad53-auc_vlad-test53.kademi-ci.co/auctions/aucqa02/

**Comment by tuzzmaniandevil** [comment]
1. Should be fixed now :-)
2. This is correct. I've fixed the error that get's displayed

**Comment by Uafinder** [comment]
yup, looks good for me
