### ISSUE TITLE
Timeline shows that email received but it's failed actually

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4446]
![image](https://user-images.githubusercontent.com/1945230/32955476-c252fb08-cbbe-11e7-8c18-b87ce0eead6e.png)
![image](https://user-images.githubusercontent.com/1945230/32955486-ca005468-cbbe-11e7-92e6-75fe886496d6.png)
http://vlad-test55.admin.kademi-ci.co/manageUsers/2022990/#summary-tab

**Comment by bradmac** [comment]
Should change the text in the timeline to reflect status

**Comment by gonzalon** [comment]
![image](https://user-images.githubusercontent.com/2773216/33194752-0c926dac-d137-11e7-9bf4-1ae96bd1b8ea.png)

**Comment by Uafinder** [comment]
Goood
