### ISSUE TITLE
When you debit points without specifing reason - some id adding to reason field

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4447]
![image](https://user-images.githubusercontent.com/1945230/32955847-ceffc812-cbbf-11e7-8e96-4e53a7c492db.png)
![image](https://user-images.githubusercontent.com/1945230/32955855-d45d9758-cbbf-11e7-8389-276f8ff7e633.png)
http://vlad-test55.admin.kademi-ci.co/manageUsers/2022990/#pointsBucketTab-tab

**Comment by tuzzmaniandevil** [comment]
If the reason field was blank it would put in the users id aka username. I've removed that step now.

**Comment by Uafinder** [comment]
It's ok!
