### ISSUE TITLE
Show Expected Remaining Time in Import Wizard

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#4450]
It's very vital to add an expected remaining time in the table wizard screen

![image](https://user-images.githubusercontent.com/3704174/32989356-4a3b926e-cd1d-11e7-8141-a13155c93cf4.png)

All elements are available for the calculation, Time can be taken every 10 records for example, then subtracted from prev time.. the resulting time is the time needed for importing 10 records, then the total remaining records can be divided on 10 and multiplied by the time required for the 10 records, 10 is an example.

So if import is getting faster or slower, the remaining time will be affected automatically.

**Comment by bradmac** [comment]
I think apply a moving window of average speed over the last 5 seconds, and then apply that to the number of rows remaining.

Eg if 10 records were processed in the last 5 seconds and there are 100 records remaining, then there is 50secs remaining

**Comment by gonzalon** [comment]
![image](https://user-images.githubusercontent.com/2773216/33739155-e6ec460c-dc00-11e7-8d5a-2a4f5942ab47.png)

**Comment by Uafinder** [comment]
Timezone issue...
![image](https://user-images.githubusercontent.com/1945230/33765534-ee7031b0-dc21-11e7-93d9-5a044d0c201c.png)

**Comment by gonzalon** [comment]
@Uafinder I fixed the timezone problem, but I couldn't reproduce the other issue.
If you can reproduce it again maybe post the console requests to see the data you are pulling?
thanks!

**Comment by Uafinder** [comment]
yup, looks fine right now
