### ISSUE TITLE
Leadman company page issues

### ISSUE THREAD

**Issue by gonzalon** [Kademi/kademi-dev#4452]
- Leadman /companies/ page is slow

![image](https://user-images.githubusercontent.com/2773216/33000153-3adf3b1a-ce0b-11e7-881e-f69dec0df7ea.png)

- It's also showing deleted orgs

**Comment by gonzalon** [comment]
Tested with 5k org and its ok. Also filtering the deleted orgs.

**Comment by Uafinder** [comment]
Yeap, working, great
