### ISSUE TITLE
Points allocation in data series

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#4453]
Lyle has just uploaded a spreadsheet with 40 rows of sales data.
Points allocation rule: points amount = amount / 1.15 / 100

26 rows with calculated points amount >= 1 were inserted
14 rows were not inserted

Please see the log here http://viri.admin.kademi.com.au/sales/sales-by-dealer/sources/source-dealer-rewards/#history-tab

**Comment by bradmac** [comment]
This is correct behaviour, we dont create points records with a zero value
