### ISSUE TITLE
Width parameters doesn't affect text component

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4454]
It's looks such kind in editor
![image](https://user-images.githubusercontent.com/1945230/33008245-ffc7dbd4-cdda-11e7-9a22-dfe36abc0fbf.png)
But frontend looks next way
![image](https://user-images.githubusercontent.com/1945230/33008265-0a5d769e-cddb-11e7-9d7e-228cca10d5e0.png)
http://vlad-test56.admin.kademi-ci.co/websites/vlad56-learn/version1/programs/p1/c1/m1/#files-tab

**Comment by ducdhm** [comment]
@Uafinder It's ok on my side (tested with your link). Can you double-check again?

![ui](https://user-images.githubusercontent.com/1289631/33054782-0d19ff14-ceae-11e7-9969-53065fab1044.png)

![ui2](https://user-images.githubusercontent.com/1289631/33054783-0de23a74-ceae-11e7-9920-3b45f1b8d11d.png)

**Comment by Uafinder** [comment]
Ahhh, its because of missing spaces in text... :)
Probably wouldn't be reproduced in prod... Closing
