### ISSUE TITLE
Improve email status formatting

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4455]
we dont require this number of decimal places:

![image](https://user-images.githubusercontent.com/826458/33014668-f35bb9e8-ce4c-11e7-8359-eee59b355d1d.png)

Please change to 1 decimal place

http://travelworld.admin.kademi.com.au/groupEmails/

**Comment by anhnt** [comment]
Fixed

**Comment by bradmac** [comment]
The change only applies to how the page is initially rendered. It still displays incorrectly when updated from ajax

**Comment by AlaaKhalaf94** [comment]
passed
