### ISSUE TITLE
Organisations searching list ordering

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4456]
While searching organisations to add a membership or product, we received results as a list. But this list is completely unsorted. E.g. I have orgs with names org00001..00009 and search for example "org0000", it gives me a list of orgs, but the order is weird.
![image](https://user-images.githubusercontent.com/1945230/33016484-6e038d34-cdf7-11e7-81da-cf559ff7281c.png)
http://vlad-test56.admin.kademi-ci.co/products/
![image](https://user-images.githubusercontent.com/1945230/33016508-85eeab7c-cdf7-11e7-9f3f-35d665d75090.png)
http://vlad-test56.admin.kademi-ci.co/manageUsers/2041590/#summary-tab

I'm told about it before here
https://github.com/Kademi/kademi-dev/issues/4390

Not sure where here a "relevance"...

**Comment by bradmac** [comment]
Relevance is just the score based on finding your search terms in each document. In the example above the documents will have the same score, so there is no specific ordering.
