### ISSUE TITLE
Certificate image or video uploading error

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4457]
![image](https://user-images.githubusercontent.com/1945230/33016874-d3b37850-cdf8-11e7-921e-ec62cb11ebf8.png)
http://vlad-test56.admin.kademi-ci.co/certificates/cert_2046977

**Comment by tuzzmaniandevil** [comment]
Works fine for me. No error.

**Comment by tuzzmaniandevil** [comment]
Even on a newly create certificate. Still works fine

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/33075432-1e61cc24-ced2-11e7-8de6-150c8ae965d1.png)
Fresh account
http://vlad-test57.admin.kademi-ci.co
adminqa@mailinator.com

**Comment by tuzzmaniandevil** [comment]
Found the bug and fixed

**Comment by Uafinder** [comment]
Great, it works!
