### ISSUE TITLE
Login-as component

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4462]
We need a component which can be added to front end websites to make the "login-as" capability available.

For example, this is so that sales reps can view customers in their lead management site, and then login as a customer to a reward site.

Note that we need to be very careful with authorisation. Any request to generate a login-as link should check that the current user has WRITE_ACL permission to the user they're logging as. This priviledge should come from the UserAdministrator or Administrator roles

The component should allow selecting which website to login to.

**Comment by tuzzmaniandevil** [comment]
Please test with user-lib 1.1.3

**Comment by Uafinder** [comment]
Can't find this component, user-lib 1.1.3 is installed.

**Comment by tuzzmaniandevil** [comment]
@Uafinder The login as component will only work on a lead page, profile page or a public profile page.

**Comment by Uafinder** [comment]
Would be great to have a dropdown list of available websites.
![image](https://user-images.githubusercontent.com/1945230/33559821-ade7b220-d916-11e7-8ba4-21a8eedf00bd.png)

**Comment by anhnt** [comment]
Done

**Comment by Uafinder** [comment]
hmmm...
looks like, when you click login as button it doesn't transfer you to specific site...
![image](https://user-images.githubusercontent.com/1945230/33944905-2bc714a4-e026-11e7-83a5-6142798177ed.png)


![image](https://user-images.githubusercontent.com/1945230/33944892-2044c2a2-e026-11e7-8ae6-99be241db79f.png)

![image](https://user-images.githubusercontent.com/1945230/33944880-18903654-e026-11e7-8943-65e5d221c478.png)

http://vladtest05.admin.kademi-ci.co/pages/vlad05leads/version1/

**Comment by bradmac** [comment]
It does work when logged in as admin, but not when logged in as a sales user.

@tuzzmaniandevil can you please provide instructions for setting up roles

@anhnt please add text to the component settings explaining the requirements for roles

**Comment by tuzzmaniandevil** [comment]
So the component requires the user to have the `User Administrator` role.

@Uafinder Please make sure the sales group has the correct roles.
@anhnt If you need any more info to add the explanation please let me know

**Comment by anhnt** [comment]
help text added

**Comment by Uafinder** [comment]
Hmmm... I logged in as userqa01 (useradmin role) and try to login to another site. It doesn't transfer...
But when you full administrator links work ok.

**Comment by bradmac** [comment]
@Uafinder the problem is because of this - https://github.com/Kademi/kademi-dev/issues/4656

The user admin control hasnt actually been added because the role name is incorrect

**Comment by bradmac** [comment]
@Uafinder please note that using Login-as from a profile page (eg /profile) is not a meaningful test

The profile page renders for the current user, so you're just logging in as yourself.

To test this properly you should use it with a lead page or a customer contact page.

**Comment by bradmac** [comment]
I've checked that this does work with the fix from #4656,  but as above please test with a more representative example

**Comment by Uafinder** [comment]
Yup, looks fine!
Thanks for info!
