### ISSUE TITLE
Move to parent - org id selector probably should be standard Org selector with cases

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4466]
![image](https://user-images.githubusercontent.com/1945230/33078889-b2ea0f78-cedc-11e7-962d-9f5aa6a968d6.png)
http://vlad-test57.admin.kademi-ci.co/organisations/?startPos=0&pageSize=100&
Now it's a regular text field with validation.

**Comment by anhnt** [comment]
Done

**Comment by Uafinder** [comment]
Working great
