### ISSUE TITLE
Points allocation enhancements

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4467]
Here's an example: http://viri.admin.kademi.com.au/sales/sales-by-dealer/sources/source-dealer-rewards/#general-tab

![image](https://user-images.githubusercontent.com/826458/33091996-9d58bade-cf5d-11e7-9671-0e1600da33bc.png)

Please make the following enhancements
- Add an option to allow either allocate individual points records for each sale (as it does now) or to roll up sales into a single value and award a single points record for that. This option is for situations where individual sales are very small and the points records are rounded to zero, by adding them together the rounding will be avoided. This process should mark all included records as allocated.
- Add an optional expression field to "ignore" records. If this expression evaluates to true the record will not have any points allocated, and will not be marked as allocated, so it could be included in the next processing (if the expression output changes). Make this a textarea field to allow for more complex rules
- Change the existing expression field to a textarea to allow for more complex rules

**Comment by Uafinder** [comment]
Yeap, looks great!
