### ISSUE TITLE
Integrate fullstory

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4468]
Please create a new marketplace app which integrates this site - https://www.fullstory.com/

This should be similar to our Google analytics integration, ie simply generate the code snippet into the head.

**Comment by ducdhm** [comment]
New Timeline post with FullStory
![newui](https://user-images.githubusercontent.com/1289631/33312180-b14a3800-d459-11e7-813b-1c01b110ac30.png)

**Comment by ducdhm** [comment]
Setting for KFullStory
![newui2](https://user-images.githubusercontent.com/1289631/33312256-e976cb80-d459-11e7-8163-8ee2d35c1f66.png)

**Comment by Uafinder** [comment]
After enablin' app for a website
![image](https://user-images.githubusercontent.com/1945230/33325442-f276fc9a-d45a-11e7-81ce-8980e45e45ea.png)
http://vlad-test62.admin.kademi-ci.co/websites/vlad62-fullstory/version1/#panel_details-tab

**Comment by bradmac** [comment]
Hey @ducdhm a couple of changes please
- rename the app to just FullStory. The "K" prefix should indicate Kademi apps, FullStory isnt by Kademi
- dont show the URL, just show a button like "View details" and the link will be to that URL

**Comment by ducdhm** [comment]
Done!

**Comment by ducdhm** [comment]
@Uafinder Documentation for this app: http://docs.kademi.co/getting-started/community-management/fullstory-integration.html

**Comment by bradmac** [comment]
Please put the fullstory node on the left (ie inbound=true) because this represents something the user did

![image](https://user-images.githubusercontent.com/826458/33363777-995dc98a-d546-11e7-89af-17f972fb7de8.png)

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/33364543-93f859fa-d4ed-11e7-9e9f-d655a72998bb.png)

**Comment by ducdhm** [comment]
Done!

**Comment by Uafinder** [comment]
Ok, it works great!
