### ISSUE TITLE
Logs page JS error

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4470]
This occurred here - http://kademi.admin.kademi.us/logging - after reindexing

```
TypeError: data.hits.hits[0].fields is undefined
viewLogs.js:35:21
success
http://kademi.admin.kademi.us/theme/apps/admin/viewLogs.js:35:21
fire
http://kademi.admin.kademi.us/static/jquery/1.11.0/jquery-1.11.0.js:3099:10
fireWith
http://kademi.admin.kademi.us/static/jquery/1.11.0/jquery-1.11.0.js:3211:7
done
http://kademi.admin.kademi.us/static/jquery/1.11.0/jquery-1.11.0.js:9310:5
callback
```

Seems to be due to this code
```
            success: function (data) {
                if (data.hits.hits.length > 0) {
                    filterOptions.since = data.hits.hits[0].fields.date[0];
                }
```

**Comment by ducdhm** [comment]
@Uafinder Step by step do to it:
 * Create something in your account like products, categories, etc...
 * Reindex them
 * Access logging screen at `/logging`
 * Open other tab to your account, and see any JS error in Console tab of Web Development Tool

**Comment by bradmac** [comment]
Wasnt working for me locally. I've changed now to get an explicit server time in the ajax response

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/33166404-c24c5a36-d042-11e7-885e-03c3bee7b899.png)
I saw this error in console log while working on this issue.

**Comment by bradmac** [comment]
Oops, didnt commit web changes. Fixed.
