### ISSUE TITLE
manage modules page gives 500 error

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4471]
![image](https://user-images.githubusercontent.com/1945230/33126043-ac8ffda4-cf8b-11e7-862c-fe31372851d3.png)
http://vlad-test58.admin.kademi-ci.co/manageModules
![image](https://user-images.githubusercontent.com/1945230/33126065-c3b65f5a-cf8b-11e7-98b7-791f59aefa6b.png)

**Comment by bradmac** [comment]
Working normally now

![image](https://user-images.githubusercontent.com/826458/33148255-03f14518-d030-11e7-916a-595408dc307f.png)

**Comment by bradmac** [comment]
If you can still reproduce the problem please capture the errors from jenkins logs
http://www.kademi-ci.co:8080/job/Kademi-Run-Hinda/lastBuild/console

**Comment by Uafinder** [comment]
some way it's fine at the moment...
I will take an eye on it
