### ISSUE TITLE
Content editor breaks when editing non published elearning module

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#4472]
Please try to open content editor of any page of this module : http://3dn.admin.kademi.com.au/websites/idhealth-training/version2/programs/prof-disability/DP01/MOD02/#files-tab

![capture1](https://user-images.githubusercontent.com/26510030/33127235-4f318948-cf90-11e7-8cd4-086e4b7fb160.PNG)

**Note** : the version selected is version2 , and it is not published

**Comment by bradmac** [comment]
Looks like the problem is that admin-lib hasnt been published to the .au marketplace

**Comment by ducdhm** [comment]
Already fixed! After I and @bradmac deployed latest version for admin-lib to AU marketplace

**Comment by AlaaKhalaf94** [comment]
it's work now
