### ISSUE TITLE
Photo plugin should allow images to be physically resized and cropped

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4473]
Support the following editing options
- crop
- resize (physical)

We may add additional editing options later 

This should be available for uploading new images, but should also be able to be applied to existing photos

**Comment by bradmac** [comment]
@tuzzmaniandevil can you please check that suitable services are available?

**Comment by ducdhm** [comment]
Needed https://github.com/Kademi/kademi-dev/issues/4583

**Comment by ducdhm** [comment]
Done!

**Comment by bradmac** [comment]
Hey @ducdhm where can i see it? I've tried in a few places but cant see any option. Would be good to attach screenshots so we know what to expect

![image](https://user-images.githubusercontent.com/826458/33808918-083a4bac-de53-11e7-8cfe-fbd127394810.png)

**Comment by ducdhm** [comment]
Done!

**Comment by bradmac** [comment]
Seeing this error when using the photo component in keditor:

![image](https://user-images.githubusercontent.com/826458/34022548-cf682a42-e1a4-11e7-930a-9437994609f5.png)

**Comment by bradmac** [comment]
And where do we see this awesomeness?
![image](https://user-images.githubusercontent.com/826458/34022740-cc99b668-e1a5-11e7-9adb-22a6ed400323.png)

**Comment by ducdhm** [comment]
@bradmac I have added dependencies in admin-lib. You should see it in fresh account.

**Comment by Uafinder** [comment]
https://github.com/Kademi/kademi-dev/issues/4630

**Comment by Uafinder** [comment]
module thumbnail photo upload:
1. Upload one image
2. Click to edit
3. Edit some
4. click "back to upload"
5. Click ok
thumbnail would be bad
![image](https://user-images.githubusercontent.com/1945230/34038768-21bfa2ca-e196-11e7-9fa1-ec9bfa08e9bc.png)

http://vladtest07.admin.kademi-ci.co/websites/vlad07learn/version1/programs/p1/c1/m1/#details-tab

**Comment by bradmac** [comment]
Hey @ducdhm please ensure the editor can physically resize images. This is critical for emails etc.

**Comment by ducdhm** [comment]
Done!

**Comment by Uafinder** [comment]
Globally it's ok! Some other issue are separated...

**Comment by Uafinder** [comment]
https://github.com/Kademi/kademi-dev/issues/4663
