### ISSUE TITLE
problem manually adding/moving groups to folders

### ISSUE THREAD

**Issue by Anton69arb** [Kademi/kademi-dev#4475]
Hey, dropping and dragging the groups into folders - it works -
but when manually trying to add a group  to a folder it gives this error, please can we fix this

![hey dropping and dragging the groups into folders - it works -](https://user-images.githubusercontent.com/32444328/33151310-74ac9058-d03c-11e7-8469-ce5421dca031.png)

http://antontest.admin.kademi-ci.co/groups/

**Comment by bradmac** [comment]
hey @Anton69arb I've tried that and seems to work ok.

If you can reproduce the issue please show me
