### ISSUE TITLE
Moblix Demo issue

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4476]
**KPI sales data not showing in KPI and table**
This user http://moblix.admin.kademi-ci.co/manageUsers/762030/#summary-tab

![image](https://user-images.githubusercontent.com/2201340/33154870-8dda5bca-d03f-11e7-95dc-acdb2b9956b5.png)

**Comment by anhnt** [comment]
I found another issue with sales data graph
http://moblix-channel_moblix.kademi-ci.co/sales/sales-data-2016-and-2017/growth-kpi?startDate=&endDate=&interval=day&dateHistogram

there's some weird string 

```
http://moblix-channel_moblix.kademi-ci.co/sales/sales-data-2016-and-2017/growth-kpi?startDate=&endDate=&interval=day&dateHistogram

**Comment by anhnt** [comment]
looking good atm

**Comment by AlaaKhalaf94** [comment]
I see that is ok
