### ISSUE TITLE
P6Spy integration

### ISSUE THREAD

**Issue by gonzalon** [Kademi/kademi-dev#4478]

**Comment by gonzalon** [comment]
I added two lines in the spliffy-default.properties:

```
jdbc.driverClassName=org.h2.Driver
jdbc.url=jdbc:h2:file:target/db;MVCC=TRUE;MODE=PostgreSQL

#jdbc.driverClassName=com.p6spy.engine.spy.P6SpyDriver
#jdbc.url=jdbc:p6spy:h2:file:target/db;MVCC=TRUE;MODE=PostgreSQL
```

So we should comment / un comment this to use p6spy.
Then in the spy.properties file we have two appenders, by default it's the console:

appender=com.p6spy.engine.spy.appender.StdoutLogger
#appender=com.p6spy.engine.spy.appender.FileLogger

then the propertie, outagedetection it's to detect long-running statements, by default is 60 secs.

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/33164229-c305bf68-d096-11e7-8e8c-3c847c59970e.png)

**Comment by gonzalon** [comment]
Working on CI: http://rootorg.admin.kademi-ci.co/maintCache#perRequestSql-tab
