### ISSUE TITLE
Reason field is mandatory sever side but not validated client side

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#4479]
![image](https://user-images.githubusercontent.com/735555/33157327-df0ba2b2-d033-11e7-8199-a76ec13fd9a5.png)

**Comment by anhnt** [comment]
fixed

**Comment by AlaaKhalaf94** [comment]
passed

**Comment by bradmac** [comment]
@tuzzmaniandevil can you please check if this field is not-null, and whether it should be, and whether anything else conflicts with that
