### ISSUE TITLE
Logs page error while accessing the page

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4481]
http://vlad-test59.admin.kademi-ci.co/logging
![image](https://user-images.githubusercontent.com/1945230/33165627-27c98242-d040-11e7-869e-6a01c4ccc8eb.png)
Receive this while working with this issue, so steps to reproduce are the same:
https://github.com/Kademi/kademi-dev/issues/4470

**Comment by bradmac** [comment]
should be fixed now. you may need to reindex for this to work, or use a fresh account

**Comment by Uafinder** [comment]
Yup, looks good
