### ISSUE TITLE
Group emails EDM editor failed to load

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4482]
![image](https://user-images.githubusercontent.com/1945230/33166711-e229590c-d043-11e7-8601-88e132e2bc5f.png)
http://vlad-test59.admin.kademi-ci.co/groupEmails/2130568/#messages-tab

**Comment by bradmac** [comment]
@ducdhm looks like the same issue with keditor path.

**Comment by anhnt** [comment]
That's because edmEditor-lib latest version 1.0.1 is not used on fresh new account. I will check

**Comment by anhnt** [comment]
works fine on fresh new account

**Comment by Uafinder** [comment]
Yup, it works at the moment
