### ISSUE TITLE
Lead page image upload enhancement

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4483]
1. Need more pretty pop-up for image deletion.
![image](https://user-images.githubusercontent.com/1945230/33170673-d8af4a86-d051-11e7-991f-8f19f764b3d1.png)

2. Need some success pop-up when file deleted successfully.
http://vlad59-leads_vlad-test59.kademi-ci.co/leads/2132529/
http://vlad-test59.admin.kademi-ci.co/websites/

**Comment by Uafinder** [comment]
Image deletion pop-up doubling when pressing to delete image
![image](https://user-images.githubusercontent.com/1945230/33260443-84ece0ec-d368-11e7-8fac-2a569bf4f306.png)
http://vladlive-leads_vlad-live.kademi.com.au/leads/85268189/
http://vlad-live.admin.kademi.com.au/websites/vladlive-leads/version1/#panel_apps-tab

**Comment by anhnt** [comment]
Working ok after upgrading leadman-lib

**Comment by Uafinder** [comment]
Yeah, it works!
