### ISSUE TITLE
points allocation rule creation prepopulated date doesn't correspond with timezone

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4486]
![image](https://user-images.githubusercontent.com/1945230/33175986-1cec7994-d066-11e7-9493-b60d995223d1.png)
1. Create new Points allocation rule
2. Go to edit it
3. Check Start date...
http://vlad-test59.admin.kademi-ci.co/points-rules/pointsalloqa#general-tab

**Comment by tuzzmaniandevil** [comment]
Will now apply org timezone when displaying and saving the date

**Comment by Uafinder** [comment]
ok, looks ok at the moment
