### ISSUE TITLE
While learming app installed rewards link leads to error

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4487]
![image](https://user-images.githubusercontent.com/1945230/33176669-8a4437e6-d068-11e7-82b3-283bc4c4fca7.png)
1. Klearning installed
2. Courses and modules are created
3. Points bucket are created, but link in module properties are leading to error.
![image](https://user-images.githubusercontent.com/1945230/33176762-e0ce9da4-d068-11e7-970d-8be2df3ba1fc.png)

http://vlad-test59.admin.kademi-ci.co/websites/vlad59-learn/version1/programs/p1/c1/m2/#details-tab

**Comment by bradmac** [comment]
@gonzalon rewards should be an optional dependency of elearning.

Can you please update so that the rewards section is only displayed if the rewards app (ie points buckets) is enabled for the account?

**Comment by gonzalon** [comment]
Now it's only going to show that bit if the app rewards is enabled.

**Comment by Uafinder** [comment]
It works!
