### ISSUE TITLE
Query question

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4488]
I try to learn how to use queries and create a simple query:
![image](https://user-images.githubusercontent.com/1945230/33177287-bde28ccc-d06a-11e7-9540-c05d495db3d0.png)
With such aggregation parameters:
![image](https://user-images.githubusercontent.com/1945230/33177320-daa795a0-d06a-11e7-9782-589a9dc89c18.png)
And i'm receiving such error:
![image](https://user-images.githubusercontent.com/1945230/33177330-ead66442-d06a-11e7-9351-9df3c71fdde4.png)
Where i'm wrong?
http://vlad-test59.admin.kademi-ci.co/queries/Test_user-query

**Comment by bradmac** [comment]
@gonzalon can you please assist Vlad?

**Comment by gonzalon** [comment]
Hi Vlad, I just review your query and you weren't doing anything wrong, there was a bug for the date range query :+1: 

Just fixed that:

![image](https://user-images.githubusercontent.com/2773216/33191821-f767ac40-d121-11e7-971f-c488d2e87acd.png)

**Comment by Uafinder** [comment]
Yup, looks ok

Another question:
why email items appears in profile query?

**Comment by gonzalon** [comment]
The idea is that this way we are able to join data from emailitem index to his parent (profile).

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/33256020-e4802ac4-d358-11e7-8d88-d63319baa9a2.png)
Memberships.groups - nothing can be typed criteria field

**Comment by gonzalon** [comment]
Hmmm seems that its a numeric field:

![image](https://user-images.githubusercontent.com/2773216/33287995-84e5c16a-d41f-11e7-8a82-d02536ee3556.png)

**Comment by bradmac** [comment]
Yep. You probably want groupName instead

**Comment by Uafinder** [comment]
Ok, closing this one, will open a separate one if needed...
