### ISSUE TITLE
Debits values don't match

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4489]
![image](https://user-images.githubusercontent.com/1945230/33179558-7f7f8dd8-d072-11e7-9c03-0a0fa82c3cd0.png)
![image](https://user-images.githubusercontent.com/1945230/33179610-b8d4abea-d072-11e7-8cb7-0c016dd49ed1.png)
Looks like another time issue.
http://moblix.admin.kademi-ci.co/points-buckets/
http://moblix.admin.kademi-ci.co/points-buckets/moblix-channel-points/#debits-tab

**Comment by tuzzmaniandevil** [comment]
![image](https://user-images.githubusercontent.com/3378330/33193327-af9a4340-d12c-11e7-924a-84e773060b18.png)

![image](https://user-images.githubusercontent.com/3378330/33193330-b39ad716-d12c-11e7-9054-634a565bf9c3.png)

Works great for me?

**Comment by Uafinder** [comment]
It's a time issue, you have checked this while this problem was not visible already.
I told you that those purchase which marked "in future" has incorrect time (I mean my local time was 23th November, and purchase date was already 24th).
I think that this issue is related to timezone.

**Comment by tuzzmaniandevil** [comment]
The timezone wasn't being used when displaying the dates. But also there is no timezone set on the moblix account so it defaults to the server timezone anyway. Which is Pacific/Auckland. So it will show in the future for you :-)

**Comment by Uafinder** [comment]
looks ok :)
