### ISSUE TITLE
Change manage module page to use keditor by default for module pages

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4492]

**Comment by gonzalon** [comment]
now the Edit  opens the default content editor:
![image](https://user-images.githubusercontent.com/2773216/33194899-1ef01dd6-d138-11e7-85f2-dfb25f825f74.png)

**Comment by AlaaKhalaf94** [comment]
passed

**Comment by bradmac** [comment]
Needs to work the same as Edit Web Pages, where it selects an editor based on the theme

**Comment by gonzalon** [comment]
Changed it now it's cheking if the theme, if its KEditor would use the EDM if not the old one.

**Comment by AlaaKhalaf94** [comment]
Hi @gonzalon , I didn't understand you clearly , Can you tell me how to check , please?

**Comment by bradmac** [comment]
@AlaaKhalaf94 a website using the old theme (Eg bootstrap 335) should use the old style editor (no drag/drop). This is what Zoetis does.

But websites using modern themes (eg installed from the marketplace) should use the new KEditor (ie with drag and drop)

**Comment by gonzalon** [comment]
@AlaaKhalaf94 you can check creating two websites with different themes for the websites, and then choosing the websites in the drop down:

Ex, if the theme of the website is ktheme it should use keditor, if not the old editor.

![image](https://user-images.githubusercontent.com/2773216/33810083-7cfcb53a-de65-11e7-8561-fbb8288038ce.png)

**Comment by AlaaKhalaf94** [comment]
passed
