### ISSUE TITLE
Email not sending when setting up passwords for users

### ISSUE THREAD

**Issue by Anton69arb** [Kademi/kademi-dev#4494]
The emails are not sending, please can we take a look at this 

![emails are not sending](https://user-images.githubusercontent.com/32444328/33192429-6bc3a88c-d127-11e7-9377-4400456f3a01.png)

http://antontest.admin.kademi-ci.co

**Comment by bradmac** [comment]
Should be working again

**Comment by Uafinder** [comment]
It works!
