### ISSUE TITLE
Content editor navbar broken

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#4496]
![image](https://user-images.githubusercontent.com/735555/33195544-07d55a3a-d10b-11e7-97f5-138bb6b85678.png)

http://version2.idhealth-training_3dn.kademi.com.au/programs/prof-disability/DP02/MPD04/contenteditor?fileName=phow-can-person-centred-support-be-used-in-mental-health-treatments-and-supports.html

**Comment by anhnt** [comment]
Fixed

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/33202126-d35893e4-d12d-11e7-9e66-1a4245decba6.png)

**Comment by AlaaKhalaf94** [comment]
passed
