### ISSUE TITLE
Rewards product browsing and shopping cart

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#45]
Users should be able to browser a library of products which can be redeemed for their points, choose and add to shopping cart, and checkout with payment from their points.
The product library itself can be managed by a higher organisation/business unit, and products from that library must be opted in to the reward to be available. Products from multiple libraries can be opted in.

Additional information may be provided when a product is selected for inclusion in a reward. These override the default values set on the reward store
- points multiplier (ie multiplier applied to base cost to get number of points to deduct)
- GST
- margin
- client margin
- final points value (which if given overrides the calculated points value)

Points value is calculated as follows:
 - (base cost + freight)
 - x GST
 - x margin x client margin
 - x pointsMultiplier

Items selected in the shopping cart are considered redeemed after checkout. Each item is recorded on a transaction log visible to the user

As part of checkout process the user can select an address associated with their account (eg business unit associated with their membership), or select a specific address associated with their profile directly, or enter an ad-hoc address

**Comment by bradmac** [comment]
TODO: implement image cropping on manageproducts

**Comment by bradmac** [comment]
Ready for initial release

**Comment by Uafinder** [comment]
1. There is no possibility to create a reward store when you haven't any reward with points system enabled.
2. When creating reward store and validation on some fields work there is no red rectangle across it. Should be i think.
![image](https://cloud.githubusercontent.com/assets/1945230/5835498/2e444936-a172-11e4-87e9-e6e0badd86cd.png)
3. There is no possibility to delete a reward store. When you push "delete", it just opens a reward store for editing.
4. There is a possibility to create more than one reward store with the same credentials. Looks similar to me and no chance to determine which one you needed.
![image](https://cloud.githubusercontent.com/assets/1945230/5835513/6d813136-a172-11e4-8511-d20bedcab5f5.png)
5. Clicking on every product in the reward store causes the error.
![image](https://cloud.githubusercontent.com/assets/1945230/5835522/8e2d8920-a172-11e4-9ff9-c9e085eb9e49.png)
6. When i create a reward store it shows no products in My library and Kademi library, but products are created in organisation.
7. Incorrect label or incorrect button on Shopping cart page when you want to create it. Looks like it brings to incorrect modal. 
![image](https://cloud.githubusercontent.com/assets/1945230/5835621/76abb4d8-a173-11e4-8c33-251cc710a397.png)
![image](https://cloud.githubusercontent.com/assets/1945230/5835638/a40d1ba6-a173-11e4-850c-dde266b68aec.png)
8. I've tried to access to Store page from the user side. It gives me an error. App is enabled.
![image](https://cloud.githubusercontent.com/assets/1945230/5835699/473662a6-a174-11e4-9cfe-a9ce423fb065.png)

**Comment by bradmac** [comment]
"There is no possibility to create a reward store when you haven't any reward with points system enabled." - That is correct. A reward store must be associated with a points based reward

**Comment by bradmac** [comment]
"2. When creating reward store and validation on some fields work there is no red rectangle across it. Should be i think. " - Thats fine, we can leave it.

**Comment by bradmac** [comment]
"3. There is no possibility to delete a reward store. When you push "delete", it just opens a reward store for editing." - Fixed

**Comment by bradmac** [comment]
"4. There is a possibility to create more than one reward store with the same credentials. Looks similar to me and no chance to determine which one you needed. " - Fixed

**Comment by bradmac** [comment]
"5. Clicking on every product in the reward store causes the error. " - Fixed

**Comment by bradmac** [comment]
"6. When i create a reward store it shows no products in My library and Kademi library, but products are created in organisation." - You need to toggle the switch from "Included" to "All", because by default it only shows products which are included in the reward store

**Comment by bradmac** [comment]
"7. Incorrect label or incorrect button on Shopping cart page when you want to create it. Looks like it brings to incorrect modal. " - Fixed. Should not have been on that page, and has been removed.

**Comment by bradmac** [comment]
"8. I've tried to access to Store page from the user side. It gives me an error. App is enabled. " - Fixed. Note that if there are multiple stores for 1 website (unusual) it will add each as a menu item

**Comment by Uafinder** [comment]
1. Understood
2. ok
3. Yeap, checked in another issue
4. Yes, fixed
5. Partially fixed, will describe issue at the bottom
6. Understood
7. Fixed
8. Didn't check yet.

**Comment by Uafinder** [comment]
1. Product page is simple, should be more it theme.
![image](https://cloud.githubusercontent.com/assets/1945230/5947989/fd8872d0-a749-11e4-9ac3-13317a139772.png)
Like this one
![image](https://cloud.githubusercontent.com/assets/1945230/5947994/0d20a122-a74a-11e4-8e60-6317e07908e2.png)

2. Products which are not included into store still causes an error when you are clicking on it.
![image](https://cloud.githubusercontent.com/assets/1945230/5948024/37cc6ab4-a74a-11e4-99b6-a175f5073ad2.png)

3. No "Ok" message when saves product details in store.
![image](https://cloud.githubusercontent.com/assets/1945230/5948042/71f3c836-a74a-11e4-80cc-e6001c516899.png)

**Comment by Uafinder** [comment]
All 3 bugs still active.

**Comment by bradmac** [comment]
"Product page is simple, should be more it theme." - this page is not intended to be accessed directly. Instead what should happen is when you click the gear icon on the reward store page the product details are loaded into a modal which is displayed. See screen shot. Can you confirm if this is happening?

![pir](https://cloud.githubusercontent.com/assets/826458/6178782/2b34e496-b377-11e4-83f9-4a645230cae3.png)

**Comment by bradmac** [comment]
"Products which are not included into store still causes an error when you are clicking on it." - When a product has been excluded from the reward store its gear icon link should not be visible. Like this:

![pir2](https://cloud.githubusercontent.com/assets/826458/6178800/6884b330-b377-11e4-9845-50aff78eb33f.png)

**Comment by bradmac** [comment]
"No "Ok" message when saves product details in store." - The user should not be on that page, instead the modal should work as expected.

**Comment by bradmac** [comment]
I cant reproduce any of those problems as described above. @Uafinder could you please confirm?

**Comment by Uafinder** [comment]
1. "Product page is simple, should be more it theme." - this page is not intended to be accessed directly. Instead what should happen is when you click the gear icon on the reward store page the product details are loaded into a modal which is displayed. See screen shot. Can you confirm if this is happening?

![image](https://cloud.githubusercontent.com/assets/1945230/6217381/e212edd8-b61b-11e4-9066-1ef8800dc3e9.png)
![image](https://cloud.githubusercontent.com/assets/1945230/6217385/f519eb5c-b61b-11e4-85af-31f84298da8a.png)


2. "Products which are not included into store still causes an error when you are clicking on it." - When a product has been excluded from the reward store its gear icon link should not be visible.

Gear icon become invisible as expected. But the link which i provided on top leads to error page.

3. Looks like QA has a problem with showing products (when status switch is turn to "All", and then when it go back to included).
![image](https://cloud.githubusercontent.com/assets/1945230/6217448/98cd108a-b61c-11e4-96e3-ea20a8500201.png)
