### ISSUE TITLE
Email history page needs paginator

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4502]
Currently displaying up to 10k records, which makes the page very slow.

**Comment by AlaaKhalaf94** [comment]
Hi @gonzalon , here : http://fresh02.admin.kademi-ci.co/groupEmails/ I sent email to 400 user

but I can't see  any record in history : http://fresh02.admin.kademi-ci.co/emails/?q=&status=&job=3033952

What is wrong with me ?

**Comment by bradmac** [comment]
@gonzalon that looks like the same problem we saw with waterco yesterday. Need to check that emails are getting indexed correctly.

**Comment by gonzalon** [comment]
@AlaaKhalaf94 I tried to reproduce it but I couldn't, send email with 350 and 700 emails.
Any advice to reproduce it?

**Comment by AlaaKhalaf94** [comment]
@gonzalon , Now I could not reproduce the problem again, later if I can produce it I'll create issue for it
Thanks

this issue passed
