### ISSUE TITLE
Error in journal submitting a post

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4503]
Observed in production in 3dn
```
INFO - 26-11-2017T20:34:28,987 - io.milton.http.HttpManager  - POST :: www.idhealtheducation.edu.au///users/camilla/journal/mod08/_DAV/PUT start
INFO - 26-11-2017T20:34:29,043 - io.milton.http.json.PutJsonResource  - processForm: class io.milton.cloud.server.web.DirectoryResource
INFO - 26-11-2017T20:34:29,043 - io.milton.cloud.server.web.DirectoryResource  - createNew: null
ERROR- 26-11-2017T20:34:29,043 - io.milton.http.StandardFilter  - exception sending content
java.lang.NullPointerException
	at io.milton.cloud.server.web.DirectoryResource.createNew(DirectoryResource.java:267)
	at io.milton.http.json.PutJsonResource.processFile(PutJsonResource.java:186)
	at io.milton.http.json.PutJsonResource.processForm(PutJsonResource.java:116)
	at io.milton.http.http11.PostHandler.processExistingResource(PostHandler.java:85)
	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:196)
```

**Comment by AlaaKhalaf94** [comment]
Hi @bradmac , I test with this user : http://3dn.admin.kademi.com.au/manageUsers/84854250/#summary-tab

in these page : 
http://www.idhealtheducation.edu.au/programs/Carers/Carers1/Carers01/p1-before-you-start.html
http://www.idhealtheducation.edu.au/programs/Carers/Carers1/Carers01/p2-learning-outcomes.html
http://www.idhealtheducation.edu.au/programs/Carers/Carers1/Carers01/p38703.html
http://www.idhealtheducation.edu.au/programs/Carers/Carers1/Carers01/p43593.html

and I can't find any prob

**Comment by bradmac** [comment]
@AlaaKhalaf94 did you confirm that what you posted was saved, so if you come back it redisplays?

**Comment by AlaaKhalaf94** [comment]
yes @bradmac  , I have confirmed this

**Comment by bradmac** [comment]
I tested with a few test accounts which worked ok.

Then i tested as the user in the original issue. It did succeed, but took 17seconds which isnt acceptable

**Comment by bradmac** [comment]
This was because the server is creating a search index for the journal content for each user, which shouldnt happen

**Comment by bradmac** [comment]
Fixed. Doesnt index content under user repos now, and also only indexes website repos
