### ISSUE TITLE
New ckeditor plugin/template to support show hide content

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#4504]
1) to be able to use the htmlPanel
2) to edit the content of htmlPanel to have content with the green heading and dropdown icon shown above, which when clicked shows content inside its div
3) we DO NOT want to use the old show/hide button, that is something completely different
4) we have a ckeditor plugin called bspanel. This *could* be used as the basis for a plugin which does what we want in 2)
5) OR we could easily create a template which provides a panel with green heading and a dropdown button

Old olhub sample

![image](https://user-images.githubusercontent.com/735555/33248962-4e11c0d2-d35a-11e7-89d4-d3b03cf5a1ec.png)

![image](https://user-images.githubusercontent.com/735555/33248967-56f8161a-d35a-11e7-8bae-060a42dcf289.png)

**Comment by bradmac** [comment]
My suggestion is that we have a ckeditor template which just inserts a regular bootstrap panel, but with the appropriate classes for show/hide, and a dropdown icon.

Note that the panel must be expanded when in the editor, so use a css class to override the initial display: none state, eg .editorPage .collapse

This needs to support semantic classes, which should apply a bg colour to the heading and body divs

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/33252763-a294ca10-d372-11e7-9805-5f1e572de378.png)

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/33252781-b4f6b7e0-d372-11e7-8fb1-34beaf21eb61.png)

**Comment by AlaaKhalaf94** [comment]
Hi @anhnt , here in home page : http://test99.admin.kademi-ci.co/pages/test99/version1/
There is 3 panels , two expandable panels and one static panel inside each other

![capture1](https://user-images.githubusercontent.com/26510030/33256108-4b94d25a-d359-11e7-8447-c630d0e0a0f3.PNG)

the "expandable panel 02" should be closed at first

- And another simple thing , the sample img of static panel , shall be without arrow

![capture2](https://user-images.githubusercontent.com/26510030/33256266-03ab24ca-d35a-11e7-808e-d0b4937cacb5.PNG)

**Comment by anhnt** [comment]
please try again

**Comment by AlaaKhalaf94** [comment]
passed
