### ISSUE TITLE
EDM editor will not open via journeys on QA

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4506]
http://moblix.admin.kademi-ci.co/funnels/registration/version1/emailAction-3455cf/#message-tab

Does not seem to occur on AU and US

![image](https://user-images.githubusercontent.com/2201340/33294293-1a1253da-d424-11e7-9a29-8735431eb1de.png)

**Comment by gonzalon** [comment]
@Duc there was an error 500 in the page, and added an extra check in the Js, but the EDM editor isn't working

**Comment by ducdhm** [comment]
After I update admin-lib, edmEditor-lib and keditor-lib, it's working normally now.

**Comment by AlaaKhalaf94** [comment]
Works normally
