### ISSUE TITLE
Cannot edit old email node in journey

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4507]
http://rootorg.admin.kademi.com.au/funnels/test/version1/#journeyBuilder-tab

When I created a new journey I could, just seems to be one that was created a while back.

**Comment by ducdhm** [comment]
@bradmac After I create a new node, new node also can not be edited :( And in repository, there is only `funnel.json` file only. http://rootorg.admin.kademi.com.au/repositories/test/version1/

**Comment by bradmac** [comment]
@ducdhm can you fix it please? This is just a front end issue as far as i can see.

**Comment by bradmac** [comment]
ok, so problem is a 404 on the node
https://rootorg.admin.kademi.com.au/funnels/test/version1/emailAction-fd5434?mode=settings

**Comment by bradmac** [comment]
Thats because the funnel json could not be parsed:
```
    class com.fasterxml.jackson.databind.JsonMappingException::Could not resolve type id 'pageViewGoal' into a subtype of [simple type, class com.fuselms.apps.funnels.JourneyNode]: 
```

**Comment by bradmac** [comment]
Fixed.

The problem was that the page viewed goal wasnt setup correctly. If you see it again, just remove the page viewed goal and save
