### ISSUE TITLE
KLead - timeline for lead bad

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4508]
![image](https://user-images.githubusercontent.com/1945230/33309095-a6466e6c-d425-11e7-8ab5-77d2d9d6b9a9.png)
http://vlad62-leads1_vlad-test62.kademi-ci.co/leads/2206710/
http://vlad-test62.admin.kademi-ci.co/websites/vlad62-leads1/version1/#panel_apps-tab

**Comment by bradmac** [comment]
I've just reindexed and confirmed the error is still there.

**Comment by tuzzmaniandevil** [comment]
Re-indexing the `log`/`webhits` index fixed the issue

**Comment by tuzzmaniandevil** [comment]
![image](https://user-images.githubusercontent.com/3378330/33351987-82e92e0a-d50b-11e7-934b-a4196b8a6a48.png)

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/33366461-060f3abc-d4f4-11e7-91c2-c030adf3e502.png)
Fresh account
http://vlad64-leads_vlad-test64.kademi-ci.co/leads/2229892/
http://vlad-test64.admin.kademi-ci.co/websites/

**Comment by bradmac** [comment]
If this problem occurs with a fresh account then we need to resolve that, we cant expect users to have to reindex before using their account

**Comment by tuzzmaniandevil** [comment]
Related to #4529

**Comment by Uafinder** [comment]
looks ok
