### ISSUE TITLE
Switching on/off timeago in admin console

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#4512]
So a customer requested to be able to view dates in the admin console, not timeago. While I know that using mouse hover this can be achieved, but the customer wants to be able to compare dates of multiple records by eye.

My initial suggestion that needs discussion is a checkbox either at the admin console top menu, part of the account configuration, or above each table in a way that enables by-table enable disable.

What do you guys think?

**Comment by bradmac** [comment]
Adding that functionality would be extremely time consuming and probably cause a heap of bugs, and i dont think any other clients would want it.

The user is able to compare dates "be eye". Eg if they see a record which was "2 days ago" and another was "3 days ago" then they know they were 1 day apart.

The user should also be able to export records to CSV. If they cant current do that then that would be something we can consider

**Comment by mkhoudary** [comment]
Ok.. I will see that with the client
