### ISSUE TITLE
When adding a new menu , I can not hide it for non-logged in users

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#4513]
I test here : http://fresh.admin.kademi-ci.co/websites/fresh/version1/#panel_theme-tab
I add "contactus" menu by hand , and from its setting there is no choice to show it just for logged in user

![capture1](https://user-images.githubusercontent.com/26510030/33319585-f01a7f3e-d447-11e7-9b84-f86b5b19ad78.PNG)

**Comment by bradmac** [comment]
> I add "contactus" menu by hand , and from its setting there is no choice to show it just for logged in user

Yes, please just select a particular group if you want logged in users only to see it.

However, normally a contactus page is available to all users

**Comment by AlaaKhalaf94** [comment]
Thanks @bradmac , all are good for me now
