### ISSUE TITLE
Social Icons Component of EDM missed two icons

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4515]
![image](https://user-images.githubusercontent.com/1945230/33320972-9a5ddb18-d44c-11e7-976a-5cbb3057e5f4.png)
In a square mode.
http://vlad-test62.admin.kademi-ci.co/pages/vlad62-learn/version1/?contenteditor=page2.html

**Comment by ducdhm** [comment]
Fixed!

**Comment by ducdhm** [comment]
@Uafinder So the square is squared. I have added Rounded style for this component too.

**Comment by Uafinder** [comment]
It works great
