### ISSUE TITLE
websockets error while loading pages and keditor

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4522]
VM7438:164 WebSocket connection to 'ws://version1.vlad64-learn_vlad-test64.kademi-ci.co:81/comments/version1.vlad64-learn_vlad-test64.kademi-ci.co/content/LzEyMy5odG1s' failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT

http://version1.vlad64-learn_vlad-test64.kademi-ci.co/123.html
http://vlad-test64.admin.kademi-ci.co/pages/vlad64-learn/version1/

**Comment by tuzzmaniandevil** [comment]
Fixed WS on CI

**Comment by Uafinder** [comment]
It works ok!
