### ISSUE TITLE
All goal links leads to error

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4524]
![image](https://user-images.githubusercontent.com/1945230/33371862-b80203a2-d504-11e7-9d11-a32c99c2b4be.png)
http://vlad-test64.admin.kademi-ci.co/funnels/journey1/version1/leads/

![image](https://user-images.githubusercontent.com/1945230/33371877-c6bb1320-d504-11e7-97da-87313b24227d.png)
http://vlad-test64.admin.kademi-ci.co/manageUsers/2229908/#funnelsTab-tab

![image](https://user-images.githubusercontent.com/1945230/33371917-e5201aa4-d504-11e7-9a09-a60b6abde7f2.png)

**Comment by bradmac** [comment]
I think this is probably caused by an invalid journey, which was happening because of a seperate issue related to the web page viewed goal

Please try again with a fresh funnel

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/33713431-d7073722-db53-11e7-91aa-3485a9f3af35.png)
No matter of journey type, fresh one in fresh account.
http://vladtest01.admin.kademi-ci.co/funnels/journey1/version1/leads/

**Comment by bradmac** [comment]
OK, links are incorrect:

Correct:
http://vladtest01.admin.kademi-ci.co/funnels/journey1/version1/userVisitGoal-bc0863

Incorrect:
http://vladtest01.admin.kademi-ci.co/funnels/journey1/version1/leads/userVisitGoal-bc0863

**Comment by bradmac** [comment]
Should be fixed now

**Comment by Uafinder** [comment]
Yup, looks good
