### ISSUE TITLE
Leads with no goals after importing shows goal "not found"

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4528]
1. Import file which included file with partially filled goals
2. All leads with empty goals after import will show as "not found"
[export-leads (1).txt](https://github.com/Kademi/kademi-dev/files/1513847/export-leads.1.txt)
![image](https://user-images.githubusercontent.com/1945230/33376340-fd74d2c8-d515-11e7-83ac-7b8b71c66216.png)
http://vlad-test64.admin.kademi-ci.co/funnels/journey1/version1/leads/

**Comment by bradmac** [comment]
I think thats correct. What would you expect to see?

**Comment by Uafinder** [comment]
ok, no probs, just claryfing
