### ISSUE TITLE
Visits tab for a user empty

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4529]
![image](https://user-images.githubusercontent.com/1945230/33377469-3d62ef56-d51a-11e7-85d2-067be50059dd.png)
Fresh account
http://vlad-test63.admin.kademi-ci.co/manageUsers/2235103/#userAppTab-tab
Curing by re-index webhits

**Comment by bradmac** [comment]
```
10:01:24 Caused by: java.lang.IllegalArgumentException: Fielddata is disabled on text fields by default. Set fielddata=true on [userAgent] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead.
```

**Comment by tuzzmaniandevil** [comment]
Index mappings weren't being created correctly initially.

**Comment by Uafinder** [comment]
it works!
