### ISSUE TITLE
Stop the timer (for timeout) when lead is cancelled

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4530]
![image](https://user-images.githubusercontent.com/1945230/33377799-6538b29e-d51b-11e7-8a0e-f8d5632f0009.png)
When your step contains timeout and lead is cancelled, timer should be stopped.
http://vlad-test63.admin.kademi-ci.co/manageUsers/2234992/#funnelsTab-tab

**Comment by bradmac** [comment]
I've added a check to timer processing to make sure the lead isnt closed, it was already checking its not cancelled or deleted.

Also now hiding the timer rows if the lead is closed, and dislpaying the closed date

**Comment by Uafinder** [comment]
Great, it works!
