### ISSUE TITLE
Organisations second page bad...

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4531]
1. open this one
http://vlad-test64.admin.kademi-ci.co/organisations/
2. Click second page
![image](https://user-images.githubusercontent.com/1945230/33382300-0e421102-d529-11e7-8c05-b4bd5fd97e6a.png)
3. Page loading failed, list is not full
![image](https://user-images.githubusercontent.com/1945230/33382315-1aeb6cdc-d529-11e7-8455-60832be70b37.png)

**Comment by bradmac** [comment]
I'm seeing this error:
![image](https://user-images.githubusercontent.com/826458/33397628-13677a86-d5b1-11e7-8e22-ac43d65e1e58.png)

**Comment by gonzalon** [comment]
Added a extra validation to avoid the NPE.

**Comment by Uafinder** [comment]
Works ok
