### ISSUE TITLE
Add the option to shows T&C in KConfirmDetails

### ISSUE THREAD

**Issue by gonzalon** [Kademi/kademi-dev#4533]

**Comment by gonzalon** [comment]
![image](https://user-images.githubusercontent.com/2773216/33404668-10c3b61e-d5ca-11e7-85ca-f95fda09d9a3.png)

![image](https://user-images.githubusercontent.com/2773216/33404679-1cabda38-d5ca-11e7-8963-5f86becaa091.png)

![image](https://user-images.githubusercontent.com/2773216/33404688-24dbf936-d5ca-11e7-8f8a-ab231494f0bf.png)

**Comment by gonzalon** [comment]
Please test with
KConfirmDetails, version: 1.0.1

**Comment by AlaaKhalaf94** [comment]
Hi @gonzalon , Tha T&C URL shall be like what ?
can you suggest sample for me , please?

**Comment by gonzalon** [comment]
@AlaaKhalaf94 it should point to any URL, its going to be used to show the Terms and conditions for a program, so it would be a page of the website.

**Comment by AlaaKhalaf94** [comment]
passed
