### ISSUE TITLE
KEditor scrolls to top of screen on start drag

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4534]
I have a long email and I need to move a component in the middle to the bottom.

But as soon as i start dragging the component the editor jumps to the top of the scroll, which means i cant get to where i want to drop the component

Before drag:
![image](https://user-images.githubusercontent.com/826458/33407713-7ac50c86-d5d7-11e7-9844-bbd6afe19ce8.png)

After drag (without dropping)
![image](https://user-images.githubusercontent.com/826458/33407771-bf727ecc-d5d7-11e7-8808-7228568653a2.png)

**Comment by ducdhm** [comment]
I have removed extra spaces between container when dragging snippet or component. So no more scroll to top.

**Comment by Uafinder** [comment]
Looks good for me
