### ISSUE TITLE
ksurvey -  details change to generate csv  on request

### ISSUE THREAD

**Issue by gonzalon** [Kademi/kademi-dev#4535]
Change it to generate the CSV on request instead of generating it every time.
Also atm it's having a problem with "

URL: http://gilead.admin.kademi.us/ksurvey/survey-3b5134f9-8a8d-4241-8571-50e128feb255/#statistic-tab

File
surveyDetail.html

**Comment by anhnt** [comment]
Fixed on gilead and stock ksurvey app

**Comment by gonzalon** [comment]
Tested with the one export failing. Worked fine :+1:
