### ISSUE TITLE
alt-hls.m3u8 format is truncating the last 2 seconds of videos in JWPlayer

### ISSUE THREAD

**Issue by skwidge** [Kademi/kademi-dev#454]
Demonstrated with both .mov and .mp4 sources.

<quote>
once you've finished with orgs page...

http://admin.deloitte-fraud.olhub.com/

-------- Forwarded Message --------
Subject: 	video problems
Date: 	Fri, 19 Jun 2015 02:12:44 +1200

Hi Brad, 

We are still having issues with the videos. Even after I have uploaded the new videos, they still cut 2 seconds short. 

Did you manage to have a look at it? 

Regards,
</quote>

**Comment by skwidge** [comment]
The apache commons tailer class is uncharacteristically rubbish in its implementation, at first glance. We get the file segment name before the file is completely written.
The hack we put in to get around that was always dropping the last segment. Added a close() method to SegmentWriterListener to clean up the last segment.

**Comment by skwidge** [comment]
Just a thought; For vide that has already been converted via the old code, we will have to delete the records from the hls_* tables.

**Comment by bradmac** [comment]
That can be done on a case by case basis. Just need to add ?force to the url to force it to regenerate
