### ISSUE TITLE
Kademi survey app: question type is null on db

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#4541]
@Uafinder please check on QA so if we can reproduce it, we need to fix it

**Comment by Uafinder** [comment]
How can I access a DB records for survey. They are absent in query index...

**Comment by anhnt** [comment]
All custom apps will store database here http://vladtest07b.admin.kademi-ci.co/jsondb/

**Comment by Uafinder** [comment]
can't reproduce... :(
