### ISSUE TITLE
Price for products already added to reward store doesn't update after update price for a product

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4542]
Not sure if it's a bug
1. Create a fresh account, create a website and install rewardstore app there
2. Upload some product details - cost for example
3. Go to reward store page:
![image](https://user-images.githubusercontent.com/1945230/33430133-1263c6b8-d5d8-11e7-9dd4-6916f574dd8d.png)
4. Check frontend:
![image](https://user-images.githubusercontent.com/1945230/33430146-1eb6aca0-d5d8-11e7-89b2-7a0f86ba593a.png)

So, product which already added to store had not updating when you update it's details.
http://vlad-test65.admin.kademi-ci.co/reward-store/vlad65-rstore-store/#products-tab

**Comment by bradmac** [comment]
The problem is most likely that the rewardstore index isnt being updated when the product is updated.

@tuzzmaniandevil can you please check?

**Comment by tuzzmaniandevil** [comment]
Couldn't reproduce,
Here are my steps, Maybe I missed something:
- Created a new account in CI - http://westest01.admin.kademi-ci.co
- Created a new website - http://westest01.admin.kademi-ci.co/websites/westest01/version1/
- Installed the KRewardStore app
- Viewed the website to make sure all prices where 0
![image](https://user-images.githubusercontent.com/3378330/33589422-34e1b9bc-d9dd-11e7-9b78-35fb10ae1e78.png)
- Update the base cost of the iPad Mini
![image](https://user-images.githubusercontent.com/3378330/33589427-4485a6a8-d9dd-11e7-8941-fd5dafebc7f5.png)
- Refreshed the website
![image](https://user-images.githubusercontent.com/3378330/33589436-4bda5160-d9dd-11e7-89e0-ab6fe65485b6.png)
- Works correctly

I also tried locally and seems fine there too

**Comment by Uafinder** [comment]
Yup, if you update points directly - it's ok.
But if you use uploader - the problem persists.
Account http://vlad-test68.admin.kademi-ci.co/products/
![image](https://user-images.githubusercontent.com/1945230/33613990-c554c380-d9de-11e7-9bcf-226c4ec73d9e.png)
![image](https://user-images.githubusercontent.com/1945230/33613999-cb06965a-d9de-11e7-82e3-4078032e8406.png)

**Comment by tuzzmaniandevil** [comment]
The importer wasn't updating the index. Added a fix

**Comment by Uafinder** [comment]
Yup, it works perfect
