### ISSUE TITLE
Orders timestamp incorrect

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4543]
![image](https://user-images.githubusercontent.com/1945230/33432787-fb38b048-d5e1-11e7-9222-ba7bc3363095.png)
Another timezone issue
http://vlad-test65.admin.kademi-ci.co/shopping-carts/

**Comment by tuzzmaniandevil** [comment]
It will now use the timezone

**Comment by Uafinder** [comment]
Fine thing
