### ISSUE TITLE
EDM components must never have template code in attributes

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4545]
When using the passwordResetLinkEDM we were seeing a problem with styles in some email clients. This turned out to be because those clients were stripping the inline styles from the a tag element.

This was because there were some template variables with no value, so were being output as template code, eg <a style="color: #ffffff; $fontStyles">, and the clients interpreted this as risky so removed the styles completely, including the correctly formatted styles.

To resolve the problem we removed the template tags from the component and then the used styles were no longer stripped out.

So please check passwordResetLinkEDM and other EDM components to ensure that template variables with no value are not output.

**Comment by bradmac** [comment]
Also, we currently have 2 password reset link components, apparently one for EDM and one for the web. 

This is confusing to users.

I dont think we need a web based password reset link at all so please remove it.

**Comment by ducdhm** [comment]
@bradmac They're all for EDM. But one is come from Java and one is came from JS. The one has "EDM" name is renamed by our former so... we have duplicated component with different name. So... ? Should I remove the one from Java or from JS?

**Comment by bradmac** [comment]
@ducdhm Where a java app provides components we cant change that because doing so can break client sites.

So  please remove the component declaration in JS. You can still override all of the component files, its just the declaration that cant be overridden.

**Comment by mkhoudary** [comment]
@anhnt I've noticed that the parameters are named differently, like innerPaddingTop and paddingInnerTop.. and that's causing templates to fail..

**Comment by anhnt** [comment]
This commit contains the fixes for passwordResetLink component. thanks @mkhoudary

**Comment by Uafinder** [comment]
When you select checkbox for password reset link, this link doesn't appear in email.
http://vladtest08.admin.kademi-ci.co/groupEmails/3414932/#recipients-tab
![image](https://user-images.githubusercontent.com/1945230/34109707-1e045940-e40d-11e7-80b3-25f3801e121a.png)

![image](https://user-images.githubusercontent.com/1945230/34109732-2b71d454-e40d-11e7-989e-36de8fae8b75.png)

**Comment by anhnt** [comment]
@Uafinder @mkhoudary this issue is fixed on latest email lib but it was not enabled on Vlad's test website. So it loaded the static version of the component which was done long time ago. I just enabled email app which also enabled email-lib and then it works fine

**Comment by Uafinder** [comment]
undestood...
so old component would be great to remove...
works ok
