### ISSUE TITLE
Thumbnail component for KEditor

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4546]
Please create a component corresponding the standard bootstrap thumbnail component, allowing for an image and text

![image](https://user-images.githubusercontent.com/826458/33459783-36bb1e18-d690-11e7-9773-e98be37b80b0.png)

https://getbootstrap.com/docs/3.3/components/#thumbnails

**Comment by ducdhm** [comment]
Done!

**Comment by ducdhm** [comment]
New component UI:
![newui](https://user-images.githubusercontent.com/1289631/33537992-7be38f8a-d8f1-11e7-9389-d3eaf2d11114.png)

**Comment by bradmac** [comment]
:+1:

**Comment by bradmac** [comment]
> there are no options about those buttons. is it by design and they should be edited by hands?

Buttons are part of the content area, so can be edited using ckeditor. These are not seperate components

But what i just noticed is that ckeditor doesnt have styles to support button styles. The user should be able to create normal links (eg with anchor icon) and apply a button style to it with the usual semantic classes like success, primary, etc.

But thats a seperate issue not related specifically to the thumbnail component

> When you delete label for button and then try to enter name...only one symbol falls into button, other will be outside of the button.

This is just a normal link, and applies anywhere ckeditor is used. I am able to edit link text correctly, although its not always obvious how to do it. Its not a defect.

**Comment by Uafinder** [comment]
Ok, so it's works correctly!
