### ISSUE TITLE
Orgtype refactoring

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4547]
Every use of Organisation.getOrgType should be replaced with Organisation.getSelectedOrgTypes

**Comment by gonzalon** [comment]
@Uafinder there was a few places where we were only getting one of the org types for the org, now it was changed so it would always return the whole list of org types.
there is no actual "test" but we should be aware of this change to see if it breaks something ...

**Comment by Uafinder** [comment]
Ok, I've done some tests and register some issues which may caused by this.
Also will keep in mind about this one.
