### ISSUE TITLE
Date range picker component should have selectable default date range

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4548]
Should allow selecting the same options as the selectable ranges

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/33543722-a545dd2e-d90a-11e7-9973-c480cdb1969d.png)

**Comment by anhnt** [comment]
@Uafinder please update kademi dev and try with fresh account

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/33659330-7ee6392e-da88-11e7-9e2b-a1ccf774bb35.png)
1. Default value should be 3 days instead of period
2. Visual bug when component size is setup to ExtraSmall,Small,Large
http://vlad-test69.admin.kademi-ci.co/pages/vlad69-repo/version1/

**Comment by bradmac** [comment]
@anhnt in Vlad's example the middle part is btn-warning but the prev/next buttons are btn-primary

I think the same colour should be applied to middle and next/prev buttons

**Comment by anhnt** [comment]
Fixed all above issues

**Comment by Uafinder** [comment]
Yup, all looks great
