### ISSUE TITLE
orderHistory component should have a message when there are no orders

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4549]
Please add a message "There are no orders yet" when the table is empty
![image](https://user-images.githubusercontent.com/826458/33464833-548227b6-d6a9-11e7-953f-cac81fba1955.png)

**Comment by anhnt** [comment]
done

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/33468619-4a3c11c2-d690-11e7-8d11-8fa81a5642b1.png)

**Comment by Uafinder** [comment]
Great
