### ISSUE TITLE
Orders export file looks weird

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4552]
"Cart ID","7da16661-998a-40ac-b6ed-7bc94a4ad00e","Ordered Date","01/12/2017 14:32","Fulfillment","C"
"First Name","Last Name","Email","Phone"
"adminqa","adminqa","adminqa@mailinator.com",""

"Address Line 1","Address Line 2","State","Postcode"
"addrrrr","addrrrr2","Kiev City","04073"

"SKU","Name","Quantity","Unit Cost","Total Cost"
"p6","Hawaii","1.00","320.00","320.0000"

"Cart ID","3cec03fc-2c33-4b94-b975-013804939342","Ordered Date","01/12/2017 14:29","Fulfillment","C"
"First Name","Last Name","Email","Phone"
"adminqa","adminqa","adminqa@mailinator.com",""

"Address Line 1","Address Line 2","State","Postcode"
"add","add2","kiev","04073"

"SKU","Name","Quantity","Unit Cost","Total Cost"
"p7","Tiguan","1.00","60.00","60.0000"

For two orders
It can't be import easily

**Comment by bradmac** [comment]
Hey @Uafinder sorry i dont understand. Can you describe the problem? Perhaps with screenshots.

**Comment by Uafinder** [comment]
ok, no probs, it's my mistake
I've have a list of orders (in my case it's one)
![image](https://user-images.githubusercontent.com/1945230/33550488-d4baee3c-d8f6-11e7-93a6-155a1342962b.png)
I wanna to export it to CSV file to have a flat list and to be able to import it in future
![image](https://user-images.githubusercontent.com/1945230/33550530-f1bd0146-d8f6-11e7-8799-a1c45ad080b3.png)
System gives me a file which are not a CSV, would be hard to analyze and could not be imported easily in future.
![image](https://user-images.githubusercontent.com/1945230/33550553-0c82d76c-d8f7-11e7-9b47-a38fa56a4d87.png)

**Comment by bradmac** [comment]
OK, i understand what you mean.

Our clients have asked for this format, so its correct. It would be nice to have a flat format which could be re-imported, but thats not a priority at the moment.

**Comment by Uafinder** [comment]
understood
