### ISSUE TITLE
Can't upload more than one image in Keditor

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4553]
1. Create email
2. Edit content body
3. Enter some block which contains text
4. Upload one image
5. Add some content
6. Upload second image, but it doesn't appear in list and editor.
http://vlad-test66.admin.kademi-ci.co/groupEmails/2604173/#messages-tab

**Comment by bradmac** [comment]
Currently cant check because of disk space issue on CI

**Comment by bradmac** [comment]
I think might have been a temporary problem, seems ok now

**Comment by Uafinder** [comment]
Yup, it works at the moment
