### ISSUE TITLE
Query builder enhancements: Add sorting

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4554]
Allow the user to select sorting for query results

**Comment by gonzalon** [comment]
Now we can add up to 3 sort fields..
![image](https://user-images.githubusercontent.com/2773216/33535907-75ecb0ba-d915-11e7-9acd-c09aa51521f4.png)

**Comment by Uafinder** [comment]
Ascending sort by email is not working:
![image](https://user-images.githubusercontent.com/1945230/33555730-13ea3c80-d90a-11e7-90b8-bd1c9156a11f.png)
![image](https://user-images.githubusercontent.com/1945230/33555738-1ada1966-d90a-11e7-999b-cacfdabe0c9d.png)
http://vlad-test67.admin.kademi-ci.co/queries/profile-test/#queryBuilderTab-tab

**Comment by gonzalon** [comment]
Fixed.

**Comment by Uafinder** [comment]
looks ok!
