### ISSUE TITLE
Improve UI of "login as"

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4557]

**Comment by bradmac** [comment]
related - https://github.com/Kademi/kademi-dev/issues/4462

**Comment by bradmac** [comment]
New UI. Click on the down arrow to see versions for a website

![image](https://user-images.githubusercontent.com/826458/33532243-c641eb2a-d8fc-11e7-8fa6-eefac25d5cb2.png)

**Comment by Uafinder** [comment]
Pretty...
