### ISSUE TITLE
Query builder enhancements: filter by type

### ISSUE THREAD

**Issue by gonzalon** [Kademi/kademi-dev#4558]
add the option to filter by the type of the document ex.

![image](https://user-images.githubusercontent.com/2773216/33532725-fc5b9be4-d900-11e7-9a61-e717d751a6a3.png)

**Comment by gonzalon** [comment]
Now we have the type field:
![image](https://user-images.githubusercontent.com/2773216/33535594-52ab7200-d913-11e7-9d68-6125197a17b2.png)

**Comment by Uafinder** [comment]
1. EmailItems bug. Should be emailItem I think.
![image](https://user-images.githubusercontent.com/1945230/33552290-22b947ae-d8fd-11e7-9a6e-0f276d699303.png)
![image](https://user-images.githubusercontent.com/1945230/33552308-2fbfd224-d8fd-11e7-814d-41f1c88b6f0b.png)
![image](https://user-images.githubusercontent.com/1945230/33552324-408f47ce-d8fd-11e7-83cd-ab5924aaccc5.png)

**Comment by bradmac** [comment]
hey @gonzalon looks like you're using the ID property instead of the indexItemType property

Eg for emailitems you should be using this:

```
        @Override
        public String getIndexItemType() {
            return "emailItem";
        }
```

**Comment by gonzalon** [comment]
Changed to use indexItemType as Brad said, now it showing the correct names.

![image](https://user-images.githubusercontent.com/2773216/33576410-999847e2-d9a4-11e7-9efd-18f6e597933e.png)

**Comment by Uafinder** [comment]
Yup, looking great
