### ISSUE TITLE
learning portlet component layout fixups

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4559]
We have a learning app component which displays a hero module, followed by available modules or courses. The layout is not working correctly. Eg module images are not shown

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/33590503-6066a8de-d9b2-11e7-843e-0e8228ea83b5.png)

**Comment by anhnt** [comment]
Also fixed issue on mobile screen

**Comment by anhnt** [comment]
Fixed. please test on new fresh account

**Comment by Uafinder** [comment]
yup, looks good
