### ISSUE TITLE
Convert module.js to a jQuery plugin

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#456]
Should be checked in all themes!

**Comment by bradmac** [comment]
hey, make sure you dont actually change any themes, because we must not break existing client sites! Just make it available, and we can tell new customers to use it, and we'll integrate with the next round of themes

**Comment by ducdhm** [comment]
Okay

**Comment by ducdhm** [comment]
it will be named "jquery.elearning"

**Comment by anhnt** [comment]
:+1:

**Comment by ducdhm** [comment]
Hi @Uafinder, can you help me re-testing Module page with jquery.module plugin? I have deployed it on my site. Please kindly test at http://admin.ducdhm.olhub.com/websites/test-jquerymodule/version1/

**Comment by ducdhm** [comment]
@Uafinder You just create user and test on `text-jquerymodule` site. If you want, you can create new program for testing :P

**Comment by Uafinder** [comment]
![image](https://cloud.githubusercontent.com/assets/1945230/13905325/7ee90e84-eec5-11e5-9298-0360324154f1.png)
How it could be?
I've past only two pages from five

**Comment by Uafinder** [comment]
![image](https://cloud.githubusercontent.com/assets/1945230/13905344/d74195d8-eec5-11e5-8e1a-8595f1cabc7e.png)
And this one in the end

**Comment by ducdhm** [comment]
@Uafinder About 100% - In progress, I think it's possible. It happens when you're at last page and last page is quiz, you answer quiz incorrect and back to My Learning.

Btw, please test it again.
