### ISSUE TITLE
Org importer - orgs with multi-orgtype membership can't be imported

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4560]
![image](https://user-images.githubusercontent.com/1945230/33549499-66bca75c-d8f3-11e7-9d4c-0123c0ccc90e.png)
I want to upload orgs which are a part of multiple orgtypes. I've export a list to see how it looks and when I try to import them back it gives me error...
http://vlad-test67.admin.kademi-ci.co/tableUploaders/organisationsUploader

**Comment by bradmac** [comment]
we should probably split on comma, but this can wait until a later milestone

**Comment by Uafinder** [comment]
Yeah. looks ok
