### ISSUE TITLE
Orgtypes doesn't appears in search index without re-index

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4561]
http://vlad-test67.admin.kademi-ci.co/manageSearch/org/
I've add some OrgTypes and assigned some orgs to them.
But when I go to manage search page I saw that orgTypes, and orgTypesSearch fields are empty.
I've done re-index and all types appear correctly.

**Comment by bradmac** [comment]
@gonzalon please ensure that the indexed document is updated when org types are added or removed

**Comment by gonzalon** [comment]
Hi @Uafinder I tried to reproduce the erorr locally and in your account but I can't.

Tried whit the option in the manage orgs page
![image](https://user-images.githubusercontent.com/2773216/33581741-ed25e6dc-d9b6-11e7-963d-8d2d37397d56.png)

and with the org page
![image](https://user-images.githubusercontent.com/2773216/33581768-0d2d96dc-d9b7-11e7-8f11-de2fb1d6286d.png)

both ways I see the index being updated

**Comment by Uafinder** [comment]
Weird... it was...
Ok, closing, will take a look
