### ISSUE TITLE
Orgs with multiple orgtypes on manage search page shows only one orgtype 

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4562]
![image](https://user-images.githubusercontent.com/1945230/33550115-71eb7930-d8f5-11e7-94b7-63342ed5f3b1.png)
![image](https://user-images.githubusercontent.com/1945230/33550124-7ab776cc-d8f5-11e7-8061-519615441184.png)
http://vlad-test67.admin.kademi-ci.co/organisations/

**Comment by bradmac** [comment]
thats true of all fields in all indexes, they only show the first of multi value fields.

This is intentional, this is really just a debugging tool, to see full data on the manage indexes page you can view the raw json data.
