### ISSUE TITLE
Question about existing account

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4563]
I had an account http://vlad-test66.admin.kademi-ci.co which worked on Friday, but today it looks broken.
Fresh account seems fine.
Why it can be? 
![image](https://user-images.githubusercontent.com/1945230/33551229-62c4d90c-d8f9-11e7-96e6-664c54880d1e.png)
![image](https://user-images.githubusercontent.com/1945230/33551249-6e85177a-d8f9-11e7-8f14-b7a6fb135a42.png)
![image](https://user-images.githubusercontent.com/1945230/33551311-a9bf8df2-d8f9-11e7-8c29-c589fe619ac4.png)
![image](https://user-images.githubusercontent.com/1945230/33551429-00531a30-d8fa-11e7-86a3-4cf61a4beb4f.png)

**Comment by bradmac** [comment]
Jenkins logs show this..
```
09:06:45 Failed to execute phase [query], all shards failed
09:06:45 	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:272)
09:06:45 	at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:130)
09:06:45 	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:241)
```

So looks like its a problem with the ES server. We had a problem with the disk being completely filled up, so that might have caused some corruption.

**Comment by bradmac** [comment]
I'm reindexing all indexes in that account, should hopefully fix it

**Comment by Uafinder** [comment]
Yup, it helps...
