### ISSUE TITLE
Module page add and save bug

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4564]
![image](https://user-images.githubusercontent.com/1945230/33552615-3a28ad20-d8fe-11e7-8c04-0334fd39c3e5.png)
![image](https://user-images.githubusercontent.com/1945230/33552543-e32e58bc-d8fd-11e7-9a83-ab3b5be92cb2.png)
![image](https://user-images.githubusercontent.com/1945230/33552603-2802192e-d8fe-11e7-8518-ba665f301c7b.png)
http://vlad-test67.admin.kademi-ci.co/websites/vlad67-elearn/version1/programs/p1/c1/m1/#files-tab

**Comment by bradmac** [comment]
Template code being displayed:
![image](https://user-images.githubusercontent.com/826458/33585891-817fe170-d9cb-11e7-8f8d-2a548b7efd36.png)

Ideally, for a new page this would say "New page"

**Comment by bradmac** [comment]
I'm not seeing the JS error above, but i am seeing a 404:

![image](https://user-images.githubusercontent.com/826458/33585954-cb2aca7e-d9cb-11e7-83d8-0172d8a3788f.png)

**Comment by bradmac** [comment]
The POST should be to the folder href and the pageName parameter should be present but empty

Eg:
```
pageName=
order=10
template=learner/modulePage
pageTitle=test
body=<p>test</p>
```

**Comment by bradmac** [comment]
OK, so i've noticed that when filename is blank it will try to save to the contenteditor resource. This will never work becasue the contenteditor resource doesnt know how to save content for each real resource.

Instead it should POST to the directory

**Comment by bradmac** [comment]
I've fixed that so it does POST to the directory, but we still have the problem that:
- template param is not being sent
- pageTitle param is not being sent

**Comment by Uafinder** [comment]
Yup, looks good
