### ISSUE TITLE
Uploader progress bar looks work from total rows count not from import count

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4565]
![image](https://user-images.githubusercontent.com/1945230/33557143-116d3930-d90f-11e7-9c5f-c63672c0e433.png)
I have a file with 10500 rows, and I import all rows from 10000...
As a result progress bar shows me that import is almost complete from the early beginning of the process.
http://vlad-test67.admin.kademi-ci.co/tableUploaders/usersUploader

**Comment by tuzzmaniandevil** [comment]
The progress bar will now take the start row into account

**Comment by Uafinder** [comment]
Yup, it works.
But now, when import starts progress bar shows 90 percent completion and then go back to start...
Video
https://drive.google.com/open?id=1gU-KD4bnrpofTLCyEXpY5789JNZTQNau

**Comment by Uafinder** [comment]
Done, works ok!
