### ISSUE TITLE
Date range component empty

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4566]
![image](https://user-images.githubusercontent.com/1945230/33560466-776f788e-d918-11e7-878b-5205a6bf28dc.png)
http://vlad-test67.admin.kademi-ci.co/pages/vlad67-elearn/version5/?contenteditor=123456.html
Component shows transparent or nothing.

**Comment by anhnt** [comment]
Just created fresh account, created a website then enable reports app.
Page date range picker works ok for me http://anhtest7.admin.kademi-ci.co/pages/w1/version1/

**Comment by anhnt** [comment]
Its not showing when i edit the page again. should be a bug

**Comment by anhnt** [comment]
Fixed

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/33609473-ea6c33aa-d9d0-11e7-84e1-23ecb306cd87.png)
This error probably due to daterange picket lib disabled. It should be enabled automatically, because that's completely not obvious by user.
upd. Datarange picker doesn't help
![image](https://user-images.githubusercontent.com/1945230/33611165-180f26f0-d9d6-11e7-88e9-99f998351e4f.png)
fresh account
http://vlad-test68.admin.kademi-ci.co/pages/vlad68-repo/version1/?contenteditor=repo2.html

**Comment by Uafinder** [comment]
Yup, looks fine
