### ISSUE TITLE
Implement proper next invoice number 

### ISSUE THREAD

**Issue by gonzalon** [Kademi/kademi-dev#4567]
We need to implement properly the method to get the next invoice number

PaymentService.getNextInvoiceNumber

Related to: https://github.com/Kademi/kademi-dev/issues/4401#issuecomment-348908624

**Comment by gonzalon** [comment]
In the payment app now we have the setings for the invoice number:
![image](https://user-images.githubusercontent.com/2773216/33587947-4152eb42-d9d5-11e7-830c-72cb265389a3.png)

and now when we create a new Invoice:

![image](https://user-images.githubusercontent.com/2773216/33587980-6879d01e-d9d5-11e7-8e8d-a312470be3d4.png)

**Comment by bradmac** [comment]
Example expression:
```
INV-@{nextCounter(5)}
```

**Comment by gonzalon** [comment]
Updated:
![image](https://user-images.githubusercontent.com/2773216/33588799-9aae4b42-d9d9-11e7-92bd-d33a08317b85.png)

**Comment by AlaaKhalaf94** [comment]
passed
