### ISSUE TITLE
Invoice: Mark as sent

### ISSUE THREAD

**Issue by gonzalon** [Kademi/kademi-dev#4568]
The mark as sent option fires the delete event

![image](https://user-images.githubusercontent.com/2773216/33589338-c8251274-d9dc-11e7-97af-70550f0a51c5.png)

Even the invoice is send the invoice is not marked as "Sent"

**Comment by bradmac** [comment]
ok, probably should do this straight away

**Comment by AlaaKhalaf94** [comment]
@gonzalon  , I test here : http://fresh05.admin.kademi-ci.co/invoices/3260556/#
I've sent this invoice to its Customer : http://fresh05.admin.kademi-ci.co/manageUsers/3260446/#emailAppTab-tab but it is not marked as "Sent"

**Comment by AlaaKhalaf94** [comment]
passed
