### ISSUE TITLE
Quote: Mark as accepted

### ISSUE THREAD

**Issue by gonzalon** [Kademi/kademi-dev#4569]
Mark as accepted fires the delete event:

![image](https://user-images.githubusercontent.com/2773216/33589418-31e96e3a-d9dd-11e7-990d-20761e3ce697.png)

 in the edit of the quote there is a button to accept it but it doesn't work:

![image](https://user-images.githubusercontent.com/2773216/33589445-5b7087a2-d9dd-11e7-9cf7-c1cb0f50e0c0.png)

**Comment by AlaaKhalaf94** [comment]
passed
