### ISSUE TITLE
Minor Uploader bug when several files uploaded

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4570]
1. Upload file
2. Go next
3. Check column, and for example deserve that it's incorrect file
4. Go back
5. Upload another file
6. Go to check columns
7. It's gives you error such as you would push next button
![clipboard - december 5 2017 9-57 am](https://user-images.githubusercontent.com/1945230/33596112-39bd7ae6-d9a3-11e7-945d-d061920ca635.png)
http://vlad-test66.admin.kademi-ci.co/tableUploaders/productsUploader

**Comment by anhnt** [comment]
I was able to reproduce this bug. But after that i cant reproduce. @Uafinder please try again on CI and provide some more info ie console log for ajax request or js error

thanks

**Comment by Uafinder** [comment]
Doh... still can't reproduce...
Will open it when saw it again
