### ISSUE TITLE
Assign org type pop-up doesn't read current org type

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4571]
![image](https://user-images.githubusercontent.com/1945230/33598263-bd52c3fa-d9aa-11e7-9278-27edb7350bff.png)
![image](https://user-images.githubusercontent.com/1945230/33598284-d9bc5e8e-d9aa-11e7-8f80-6bf6ad067205.png)
As a result no possibility to clear org type for multiple organisations in one time.
![image](https://user-images.githubusercontent.com/1945230/33598323-00b426a2-d9ab-11e7-9e5f-2c18222c3916.png)
http://vlad-test68.admin.kademi-ci.co/organisations/

**Comment by gonzalon** [comment]
Fixed
![image](https://user-images.githubusercontent.com/2773216/33637136-2505fd62-da84-11e7-8746-d14e9c96f76f.png)

**Comment by Uafinder** [comment]
Ok, it works!
