### ISSUE TITLE
recentPoints component doesnt show data if points bucket is org-based

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#4572]
Login as this user to see profile page http://viri.admin.kademi.com.au/manageUsers/83000596/#pointsBucketTab-tab

Currently there're 2 method to get recentPoints
```
public List<Points> findPointsByLimit(String pointsBucket, int limit, OrgData recip) 

public List<Points> findPointsByLimit(String pointsBucket, int limit, ProfileBean recip)
```
but component template code:

```
#set( $recentPoints = $applications.rewardStore.findPointsByLimit($bucket, 100, $profile) )
```

**Comment by bradmac** [comment]
The template code is correct. When you pass in a profile but the points bucket is org type, the findPointsByLimit finds an appropriate organisation to use.

**Comment by bradmac** [comment]
I've jsut checked with latest version on beta and appears to work correctly.

Will deploy and see if still a problem

**Comment by bradmac** [comment]
OK, that seems to be working correctly now:
![image](https://user-images.githubusercontent.com/826458/33629358-a2b673d4-da68-11e7-8236-fa43ab4ac17d.png)
