### ISSUE TITLE
Keditor loading console errors due to incorrect external links

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4574]
1. While loading keditor 
![image](https://user-images.githubusercontent.com/1945230/33609272-2ab4b672-d9d0-11e7-9145-834a4a9d2893.png)

2. LearningApp while loading keditor
![image](https://user-images.githubusercontent.com/1945230/33612607-c7b6cffa-d9da-11e7-85f4-b74451266e79.png)

3. Forum App links
![image](https://user-images.githubusercontent.com/1945230/33653662-69325a66-da76-11e7-8d54-a1c17f942159.png)

4. Reward store app links
![image](https://user-images.githubusercontent.com/1945230/33658647-23ef011a-da86-11e7-8a82-74fa15859e66.png)

5. Leads and payment app links
![image](https://user-images.githubusercontent.com/1945230/33769454-f921777a-dc32-11e7-9b27-7c1734584ebe.png)

P.S. Dashboard loading console always show this ones
![image](https://user-images.githubusercontent.com/1945230/33666798-be221732-daa3-11e7-857d-66a11f99e0dc.png)

to be continued

**Comment by bradmac** [comment]
@anhnt this might have been fixed with the thumb updates you did

**Comment by anhnt** [comment]
@Uafinder please recheck. thanks

**Comment by Uafinder** [comment]
Yup, mostly looks good
