### ISSUE TITLE
Quote: PDF preview / print

### ISSUE THREAD

**Issue by gonzalon** [Kademi/kademi-dev#4575]
Implement the PDF as in invoice

![image](https://user-images.githubusercontent.com/2773216/33632920-0139403e-da74-11e7-9a40-c76b60220b3d.png)

**Comment by gonzalon** [comment]
![image](https://user-images.githubusercontent.com/2773216/33640796-889fcb4c-da97-11e7-8c03-4eb3e2fcb40d.png)

**Comment by AlaaKhalaf94** [comment]
passed
