### ISSUE TITLE
Support all numeric types for aggregations in query builder

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4576]
Eg AVG should work with double

**Comment by gonzalon** [comment]
@Uafinder fixed, you can take this in mind to test 

![image](https://user-images.githubusercontent.com/2773216/33638298-578bb730-da8a-11e7-84e5-a83e400a9369.png)

![image](https://user-images.githubusercontent.com/2773216/33638305-5d7b5286-da8a-11e7-9775-8a23fc741d3e.png)

**Comment by Uafinder** [comment]
It looks ok at the moment...
