### ISSUE TITLE
Paste text from clipboard by ctrl-v is not work - course description

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4577]
![image](https://user-images.githubusercontent.com/1945230/33655505-e0a2edc2-da7b-11e7-8ab6-4841bc2c7037.png)
http://vlad-test69.admin.kademi-ci.co/websites/vlad69-elearn/version1/programs/p1/

**Comment by ducdhm** [comment]
@Uafinder Can you provide me the data in clipboard which you use to paste? I can't reproduce this issue.

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/33820048-11beab34-de56-11e7-9234-efb7e03cbe2e.png)
https://en.wikipedia.org/wiki/Volkswagen_Golf
for example

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
Yup, course description is ok.
Same thing in other places - for example text component of Keditor or certificate content.
![image](https://user-images.githubusercontent.com/1945230/34155724-25109238-e4c3-11e7-9041-242e1fedc007.png)

**Comment by anhnt** [comment]
Tested on new account working ok http://anhtest11.admin.kademi-ci.co/pages/w1/version1/

**Comment by Uafinder** [comment]
Looks good at the moment. not sure why it was appear
