### ISSUE TITLE
directoryIndexComponent shows folder parent

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#4579]
When using the directoryIndexComponent I've noticed that the component iterates through page.parent.subFolders, this conflicted with how it used to work, take waterco as an example.

The fix for this to just use page.subFolders, given that page is a ContentDirectoryResource, so the component will be showing what the page folder contains.

Is this a correct fix?  or page.parent was used for a specific purpose that's not clear to me

**Comment by bradmac** [comment]
When viewing a page for a directory (eg myfiles/dir1) it should show a list of files and directories inside myfiles/dir1

I cant see any reason why it should use the parent.

**Comment by mkhoudary** [comment]
@mrdadah please remove .parent, increase version

**Comment by mrdadah** [comment]
Done
