### ISSUE TITLE
Voucher change status doesn't update screen

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4580]
No matter which action: buttons redeem, cancel, or manually change status doesn't cause update screen to see changes.
![image](https://user-images.githubusercontent.com/1945230/33663444-a734dd3a-da98-11e7-870b-57009c80d1c1.png)
![image](https://user-images.githubusercontent.com/1945230/33663453-aeba207e-da98-11e7-92d0-e2575fa6e564.png)
http://vlad-test69.admin.kademi-ci.co

**Comment by bradmac** [comment]
@gonzalon please ensure that reloadFragment is being used to refresh the page content after status changes.

**Comment by gonzalon** [comment]
@Uafinder I could only reproduce the problem for the Redeem button. The rest was refreshing the page ok.
Fixed that one, in vouchers-lib 1.0.5

**Comment by Uafinder** [comment]
yup, it works!
