### ISSUE TITLE
Edit course details after changing a program cause a very cery long window for course details

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4581]
![image](https://user-images.githubusercontent.com/1945230/33655689-7226eafa-da7c-11e7-870d-6e4083fab473.png)
http://vlad-test69.admin.kademi-ci.co/websites/vlad69-elearn/version1/programs/programQA/vw/
https://drive.google.com/open?id=1XyiabsRynt3ic4q6QSq7VGUwXqzu585D
It's not obvious and this problem not observed every time, but it happens often.
It happens only if description has value.

**Comment by anhnt** [comment]
Fixed

**Comment by Uafinder** [comment]
Looks better
