### ISSUE TITLE
Uploader invalid rows limit

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4582]
When system processing file contains more than 999 rows which are marked as invalid file processing stops...
![image](https://user-images.githubusercontent.com/1945230/33669448-2b61753e-daab-11e7-8d45-9cbcbfa539db.png)
http://vlad-test69.admin.kademi-ci.co/tableUploaders/organisationsUploader

**Comment by bradmac** [comment]
This is by design.

**Comment by Uafinder** [comment]
ok
