### ISSUE TITLE
Integrate profile finder with organisor field on events

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4587]

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/33704825-8ee474f2-db60-11e7-9e0b-e3bc96849feb.png)

**Comment by Uafinder** [comment]
Search by profiles doesn't work...
![image](https://user-images.githubusercontent.com/1945230/33943847-ec8464de-e022-11e7-9f5c-4df22ebd2488.png)
http://vladtest05.admin.kademi-ci.co/Calendars/calQA01/hrdhdrhd-ddr-drj#details-tab

**Comment by bradmac** [comment]
I'm seeing this error in the user search ajax response:
http://vladtest05.admin.kademi-ci.co/manageUsers?asJson=true&type=profile&omni=a

```
{ "took" : 1, "timed_out" : false, "_shards" : { "total" : 2, "successful" : 1, "failed" : 1, "failures" : [ { "shard" : 0, "index" : "qa1-profile-3327117.1513193825170", "node" : "l_Vv3_XCQEK1i0NAVP6_Xg", "reason" : { "type" : "query_shard_exception", "reason" : "No mapping found for [orgId] in order to sort on", "index_uuid" : "wUDtB32DT8Wv0DytHWvRXA", "index" : "qa1-profile-3327117.1513193825170" } } ] }, "hits" : { "total" : 0, "max_score" : null, "hits" : [ ] }, "serverTimeMillis" : 1513193851274 }
```

I've reindexed profiles and orgs

**Comment by Uafinder** [comment]
yup, it works !
