### ISSUE TITLE
keditor loading non-critical error in console

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4588]
![image](https://user-images.githubusercontent.com/1945230/33706548-26a7c2e0-db3d-11e7-9f11-5cf13f0cceb0.png)
http://vladtest01.admin.kademi-ci.co/pages/vlad01repo/version1/?contenteditor=reportpage.html
http://vladtest01.admin.kademi-ci.co/pages/vlad01repo/version1/

**Comment by bradmac** [comment]
Problem is that the d3-lib dependency wasnt enabled:

![image](https://user-images.githubusercontent.com/826458/33746521-c7f40088-dc22-11e7-8818-5fdc150d2639.png)

**Comment by bradmac** [comment]
Note that d3-lib should be enabled, because other libs that depend on it are enabled (eg nvd3-lib)

For some reason many libs are reporting no dependencies:
```
14:22:48 INFO  io.milton.cloud.server.db.AppControl  - setStatus appId=nvd3-lib org=vladtest01 enabled=true controlId=3106622
14:22:48 INFO  io.milton.cloud.server.apps.ApplicationManager  - checkAppDependencies: is dependent app.
14:22:48 INFO  io.milton.cloud.server.apps.ApplicationManager  - No app dependencies for app  nvd3-lib
```

This does not occur in a fresh account, but is reproducible in the account above

**Comment by bradmac** [comment]
I added some logging and now cant reproduce. Its possible it was fixed with some other changes

**Comment by bradmac** [comment]
@Uafinder please check if you can reproduce this issue with a fresh account

**Comment by Uafinder** [comment]
Reproduced on the fresh account
![image](https://user-images.githubusercontent.com/1945230/33757850-a7714c80-dc04-11e7-85b7-e81c6d036003.png)
http://vladtest02.admin.kademi-ci.co/pages/vlad02repo/version1/
1. Create a new website
2, Enable reports app there
3. Create a page
4. Edit page

**Comment by ducdhm** [comment]
@Uafinder Can you re-check again? I followed your step-by-step and it's working normally with me.

http://duc-test-2.admin.kademi-ci.co/pages/duc-test-2/version1/

**Comment by Uafinder** [comment]
Fresh account
![image](https://user-images.githubusercontent.com/1945230/35096207-0051980e-fc54-11e7-84de-d69e65b25074.png)

Steps to reproduce,
1. Create fresh account
2. Create admin
3. Create a website
4. update libs (content-lib wants to be updated)
5. Enable reports app for site
6. Create a page
7. Open page for edit
http://vladtest23.admin.kademi-ci.co/pages/vlad23repo/version1/

**Comment by Uafinder** [comment]
1. rootorg, create account from there
2. then create a user with admin rights for this account
3. logout and login as that user
4. create a website
5. go to ./manageApps/#installed-tab and update content-lib
6. go to ./websites/vlad23arepo/version1/#panel_apps-tab and enable reports
7. go to pages
8. create a page
9. edit it

**Comment by ducdhm** [comment]
@Uafinder I still get no error follow your step-by-step. 

@bradmac Can you try follow Vlad's step-by-step to get some lucks?

**Comment by bradmac** [comment]
hey, leave me out of it!

you guys should talk together on chat to sort this out :)

**Comment by Uafinder** [comment]
looks like a backend issue

Vlad 11:50 AM
ok, i'm creating an account in FF and then after account is created i'm moving to chrome
so open FF
you should clear a cache
then moving to http://rootorg.admin.kademi-ci.co/ under my admin vlad@kademi.co... i suppose you could use your own account

duc 11:51 AM
yeah

Vlad 11:52 AM
then you push new account
i'm using both vladtest25a name and orgid, you could use vladtest25b
push create
account is created and you are already on the new account dashboard, move to users and create a user, display name, first name, surname are adminqa, email is adminqa@mailinator.com
group administrators

duc 11:55 AM
vladtest25b
I have created vladtest25b user on vladtest25b

Vlad 11:57 AM
when you create a user, ypou should setup password for him

Vlad 11:57 AM
then
you move to chrome
clear cache there
open vladtest25b account and log in under vladtest25b user

Vlad 11:58 AM
then you should to create a website

Vlad 12:00 PM
ok
http://vladtest25a.admin.kademi-ci.co/manageApps/#installed-tab
update from hear
not for website

Vlad 12:02 PM
sure
then go to website apps

duc 12:02 PM
enable reporting app?

Vlad 12:03 PM
yup
then create a page
then edit
when edititnng push f12 to console
there will be an error in upper part of log

**Comment by Uafinder** [comment]
ok. so the problem was that we just enable reporing app by hands without install some other app via MarketPlace
when we follows regular and correct steps, all seems to be fine...
