### ISSUE TITLE
Leads site home page has bad clickable area

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4589]
![image](https://user-images.githubusercontent.com/1945230/33723513-976d5f02-db75-11e7-85e4-ee9dc13c00ba.png)
http://vlad01lead_vladtest01.kademi-ci.co/

**Comment by Uafinder** [comment]
Heya
Create a fresh account, create a website, install leadman app there via market place, try to access leadman frontend and nothing appears... No login, logo
![image](https://user-images.githubusercontent.com/1945230/33825696-21c1bf52-de6b-11e7-96a8-226b6854142d.png)

http://vladtest03b.admin.kademi-ci.co/websites/
http://vlad03leads_vladtest03b.kademi-ci.co/

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
Yup, looks fine
