### ISSUE TITLE
Issue while anonymously comment with notifications

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4590]
Unfortunately there is an issue when you setup a checkbox to receive notification when someone leaves a reply.
For example:
1. user1 leaves a comment and setup a check box to follow via email
2. user2 comments user1's post and also setup a check box for following
3. As a result user1 should receive email
4. Then user3 leaves a comment without following check box
5. As a result user1 and user2 should receive emails. But instead user1 doesn't receive email(!)
6. Then user4 leaves a comment
6. As a result user1 and user2 should receive emails and user3 should not receive email. Instead user1 and user 2 doesn't receive emails and user3 receive email.
So, looks like email received by the last user in comments list.
![image](https://user-images.githubusercontent.com/1945230/33757716-09835ac2-dc04-11e7-88b2-06115737a536.png)
![image](https://user-images.githubusercontent.com/1945230/33757730-15bfa6d8-dc04-11e7-9c60-3c55ef56384a.png)
http://vladtest02.admin.kademi-ci.co

**Comment by tuzzmaniandevil** [comment]
Should work better now

**Comment by Uafinder** [comment]
Yup, looks better
