### ISSUE TITLE
Lead title disappers when using quick lead edit function

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4591]
![image](https://user-images.githubusercontent.com/1945230/33761640-72f1b388-dc12-11e7-9729-4c4b8c5dd070.png)
1. Watch for lead title disappear when you try to edit deal value for example.
http://vlad02-leads_vladtest02.kademi-ci.co/leads/?query=&leadType=active
http://vladtest02.admin.kademi-ci.co/funnels/journey1/version1/#journeyBuilder-tab

**Comment by anhnt** [comment]
@Uafinder please rebuild QA to test

**Comment by Uafinder** [comment]
looks ok at the moment
