### ISSUE TITLE
Hinda Categories not displaying correctly

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4593]
2 things to confirm.

1) We show categories 4 levels deep and that the categories are importing correctly to cater for this
2) The category title is not importing, instead it's using the category ID http://safetydemo.admin.kademi.us/categories/

![image](https://user-images.githubusercontent.com/2201340/33809978-e34f9fd6-de52-11e7-9741-c5621afb6ee0.png)

**Comment by gonzalon** [comment]
@paddyow  I did an update for the categories in the safety demo, now are ok... but I had to delete the old ones, so I think that not all the products are asigned to categories
