### ISSUE TITLE
Enhance links to users info on manage orgs page

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4595]
- Change the existing "view users.." link text to "View memberships"
- Add a new link "View users" which links to the manage users page with a term filter on the organisation

![image](https://user-images.githubusercontent.com/826458/33812702-1c925fb4-de84-11e7-9c6b-96aac7afd4b1.png)

**Comment by gonzalon** [comment]
![image](https://user-images.githubusercontent.com/2773216/33853635-7a34c842-df23-11e7-981c-3631fa809094.png)

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/33887910-1203139c-df54-11e7-8f12-148146b0c579.png)
Incorrect link
this caused all functions to malfunction
http://vladtest04.admin.kademi-ci.co/manageUsers?term-orgs=3311668

**Comment by bradmac** [comment]
@gonzalon the link to manageUsers is missing the trailing slash, so links on that address are relative to the root.

Please just change /manageUsers? to /manageUsers/?

**Comment by gonzalon** [comment]
Ups, good catch, fixed.

**Comment by Uafinder** [comment]
Works great
