### ISSUE TITLE
Keditor text component: cant change background color and picker not working

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#4596]

**Comment by anhnt** [comment]
Fixed. Also added text color settings

![image](https://user-images.githubusercontent.com/735555/33818006-3c833f00-de75-11e7-9490-d58aa54bb39a.png)

**Comment by AlaaKhalaf94** [comment]
passed

**Comment by anhnt** [comment]
Fixed an issue which set the background and text to be black initially
