### ISSUE TITLE
Certificate edition issue

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4598]
When your try to copy paste some example info (for example for current username of some sort) it will show the text but not the variable info.
![image](https://user-images.githubusercontent.com/1945230/33820248-233aa9a2-de57-11e7-8399-02a654b40acf.png)
After pasting
![image](https://user-images.githubusercontent.com/1945230/33820260-3011ef50-de57-11e7-9904-70388336ccfe.png)
But page source will contain appropriate information
![image](https://user-images.githubusercontent.com/1945230/33820277-44ca67e2-de57-11e7-8616-d5d06c00f8e5.png)
It caused by hiding all info which are following "@" symbol when pasting.

**Comment by bradmac** [comment]
Hey guys, now that we have KCode we should deprecate that style of templating. 

So things to do:
1. Ensure we have KCode fields for each of those templating examples (because they're frequently used)
2. Remove the example template code.

**Comment by bradmac** [comment]
@gonzalon please implement FieldProviderApplication on LearningApp and create fields for
- module title
- module completed date

Make sure ComponentHtmlTemplater is correctly integrated in certificate generation.

**Comment by gonzalon** [comment]
![image](https://user-images.githubusercontent.com/2773216/33908175-64696576-dfec-11e7-83dc-9ed005ee3e37.png)

**Comment by gonzalon** [comment]
@paddyow  I did an update for the categories in the safety demo, now are ok... but I had to delete the old ones, so I think that not all the products are asigned to categories

**Comment by Uafinder** [comment]
Yeah, looking good!

**Comment by bradmac** [comment]
Hey guys, this is a bit of a whoopise. We cant disable the old style of templating because we have clients who are using it!

**Comment by bradmac** [comment]
Should be working correctly now:
![image](https://user-images.githubusercontent.com/826458/34503339-99a2c30e-f07c-11e7-9cda-73b3d21e602a.png)

**Comment by Uafinder** [comment]
yeap, both styles work correctly

**Comment by bradmac** [comment]
Old style should use code like this..
```
    public void sendContent(OutputStream out, Range range, Map<String, String> params, String contentType) throws IOException, NotAuthorizedException, BadRequestException, NotFoundException {
        VelocityEngine engine = C(TextTemplater.class).getEngine();
        RootFolder rootFolder = WebUtils.findRootFolder(this);
        String templatePath = "/templates/apps/learner/certificate.html";
        templatePath = rootFolder.getDomainName() + ":" + templatePath;
        Template template = engine.getTemplate(templatePath);
        Writer writer = new OutputStreamWriter(out);
        Context datamodel = new VelocityContext();
        datamodel.put("page", this);
        datamodel.put("params", params);
        datamodel.put("formatter", C(Formatter.class));
        datamodel.put("rootFolder", rootFolder);
        template.merge(datamodel, writer);
        writer.flush();
    }
```

**Comment by Uafinder** [comment]
Both styles still works properly

![image](https://user-images.githubusercontent.com/1945230/35572358-1fd6ac7c-05dd-11e8-89b4-d61b49b8ddf3.png)


Only thing is old style is not visible in editor
![image](https://user-images.githubusercontent.com/1945230/35572247-e8285550-05dc-11e8-941a-902ec0ba1751.png)
But when you switch to Source code
![image](https://user-images.githubusercontent.com/1945230/35572165-ba48eb5e-05dc-11e8-852a-06a97d672360.png)
http://vladtest28g.admin.kademi-ci.co/certificates/cert_4851482/?useHash=true

**Comment by gonzalon** [comment]
@bradmac I talked to Wes about this and found that it's because of this https://github.com/Kademi/kademi-dev/issues/951

What should we do?

**Comment by bradmac** [comment]
Hey guys.
The action point from this issue was to ensure KCode can be used.
But the problem was the implementation broke rendering of certs for old themes.

This issue can be closed if KCode is working correctly and there is no regression error affecting rendering of old certs.

If there is a problem with editing old theme templates then that should be logged as a seperate issue which is not critical, because there are very few (probably none) new certificates being created for old theme sites.

**Comment by bradmac** [comment]
@Uafinder please close this issue if it is resolved as above

**Comment by Uafinder** [comment]
ok, closing
