### ISSUE TITLE
Moblix Demo issues

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4599]
This user http://moblix.admin.kademi-ci.co/manageUsers/762059/#summary-tab

Cannot submit a claim http://moblix-channel_moblix.kademi-ci.co/sales-claims.html
Claim should appear after it is submitted.

When the poll on the dashboard is submitted, it does not update. Need to refresh.

**Comment by anhnt** [comment]
Can submit claim and they do appear now. There's old mapping that didnt get update when the app is upgraded.

**Comment by anhnt** [comment]
Kpoll form should work now
