### ISSUE TITLE
Create an app for one of those horrible, annoying popup things when a user is about to leave a site

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4600]
Create a new marketplace app. This will have a portlet similar to KToolbar to inject some JS.

When a user moves their mouse to the top edge of the page (which indicates they're about to navigate away) display a modal with configured content

The modal will typically be a contact page to regsiter to a newsletter.

This content should be editable.

The content should be editable with KEditor, and should support images etc. So i think the best way to do that is to hold the content in a file in the website

**Comment by mrdadah** [comment]
done

**Comment by bradmac** [comment]
done
