### ISSUE TITLE
Group email task can't be deleted

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4601]
![image](https://user-images.githubusercontent.com/1945230/33831283-19218fd4-de80-11e7-8760-61f2d40cd369.png)
http://vladtest03b.admin.kademi-ci.co/groupEmails/

**Comment by bradmac** [comment]
It was attempting a hard delete when it should have been doing a soft deleted.

Should be fixed now

**Comment by Uafinder** [comment]
Yup, looks ok!
