### ISSUE TITLE
Journeys have disappeared 

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4606]
http://moblix.admin.kademi-ci.co/funnels/

All the nodes have gone across all journeys

http://moblix.admin.kademi-ci.co/funnels/registration/version1/#journeyBuilder-tab

**Comment by bradmac** [comment]
Looks ok

![image](https://user-images.githubusercontent.com/826458/33858250-cdd272aa-df33-11e7-9af3-0f255bfb0b22.png)
