### ISSUE TITLE
Group roles enhancements

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#4607]
Should be searchable, and maybe make the modal wider
![image](https://user-images.githubusercontent.com/735555/33870737-dc27489a-df41-11e7-9756-9a7255d45cdf.png)

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/33881127-6e956b20-df66-11e7-9518-831d681949cb.png)

**Comment by Uafinder** [comment]
Would be great to have some role description... really

**Comment by bradmac** [comment]
Moved description to new issue - https://github.com/Kademi/kademi-dev/issues/4619

**Comment by AlaaKhalaf94** [comment]
tested
