### ISSUE TITLE
Errors in console while leads frontend page loading

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4608]
![image](https://user-images.githubusercontent.com/1945230/33872810-135a88e8-df21-11e7-84b7-c0c8a7a3ff24.png)
http://vlad04leads_vladtest04.kademi-ci.co/

**Comment by anhnt** [comment]
looking ok without any error. @Uafinder can you please re-check

**Comment by anhnt** [comment]
Fixed, please test leadman features if you can see any error after fixing this issue

**Comment by Uafinder** [comment]
Looks ok... if I spot some issues I will raise them separately
