### ISSUE TITLE
Some completed emails showing as pending

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4610]
![image](https://user-images.githubusercontent.com/1945230/33875990-cc0c7986-df2c-11e7-8631-349dad16f943.png)
![image](https://user-images.githubusercontent.com/1945230/33877853-5d850f2c-df32-11e7-8d68-3c2dffc74927.png)
http://vladtest04.admin.kademi-ci.co/groupEmails/3302305/log.html
![image](https://user-images.githubusercontent.com/1945230/33877878-739166f8-df32-11e7-991d-a2a209497613.png)
http://vladtest04.admin.kademi-ci.co/emails/?q=&status=&job=

**Comment by bradmac** [comment]
OK, so thats becauce it wasnt indexed when the email sent. We fixed an issue yesterday which could resolve this. 

@Uafinder if you can reproduce this issue then let me know, otherwise will ignore it.

**Comment by Uafinder** [comment]
Yup, can't reproduce it at the moment...
So closing for now
