### ISSUE TITLE
Enable changing loginComponent title

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#4611]
Currently login component shows preprepared title:
Please login to view this page

We need to have it as a setting..

**Comment by mkhoudary** [comment]
https://github.com/Kademi/kademi-dev/issues/4614

**Comment by mkhoudary** [comment]
Done..

**Comment by mkhoudary** [comment]
@Uafinder to test this, go to KEditor, drag a loginFormComponent, try to change the title above, if title is blank you should see a default title, if a logo is added the title should disappear

**Comment by Uafinder** [comment]
yup, works as expected
