### ISSUE TITLE
loginFormComponent logo bug

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#4612]
When logo is set and reset, login form component still shows a blank image.

**Comment by mkhoudary** [comment]
https://github.com/Kademi/kademi-dev/issues/4614

**Comment by mkhoudary** [comment]
Done..

**Comment by mkhoudary** [comment]
@Uafinder to test this, add a logo to the login form let it show, then remove it.. if the title reappeared then this is resolved.

**Comment by Uafinder** [comment]
Yup, looks good
