### ISSUE TITLE
Omni search nullity check fails

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#4613]
When using omni search on website.. and no results match WebsiteRootFolder while there are results that match OrganisationRootFolder an empty string is returned as result.. so the nullity check fails and shows blank.

**Comment by mkhoudary** [comment]
https://github.com/Kademi/kademi-dev/issues/4614

**Comment by mkhoudary** [comment]
@Uafinder to test this, use omni search on website.. for anything you type either a result should appear or the sentence "No results found".. but it will never show a blank list.

**Comment by Uafinder** [comment]
looks ok at the moment
