### ISSUE TITLE
Ksync publish throws TimeoutException

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#4614]
When I try to publish an app or lib, ksync throws TimeoutException.. when I try to access site kademi.admin.kademi.com.au and modify a file in a repo.. the save loader keeps rolling.

![image](https://user-images.githubusercontent.com/3704174/33884721-7e81cab4-df49-11e7-9517-b5c76ef452ef.png)

**Comment by bradmac** [comment]
This is just a read timeout on a PUT, its nothing to do with ksync.

You can check why a PUT is timing out simply by doing a PUT from the command line to the same address. This might be a problem with your internet connection, or it might be some problem on the server.
