### ISSUE TITLE
Need to support templates for RepositoryApp

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#4615]
We need to let RepositoryApps be able to offer templates.. I've noticed that RepositoryApp:949 appendTemplates has no implementation.

This would help with many apps including the exit popup app.

**Comment by bradmac** [comment]
hey @mkhoudary i think you're right it would be nice, but note that this has no functional effect on the operation of apps, ie apps can still provide templates. This method is just used for building the UI to give users a list of templates to choose from.

**Comment by bradmac** [comment]
@mkhoudary are you ok to do this feature?

**Comment by mkhoudary** [comment]
@bradmac sure..

**Comment by mkhoudary** [comment]
Done and tested on Dev..

**Comment by bradmac** [comment]
Looks good! 👍
