### ISSUE TITLE
Add membership pop-up should close after succeed adding

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4617]
![image](https://user-images.githubusercontent.com/1945230/33887748-7be8c7e4-df53-11e7-9543-9a094add885b.png)
http://vladtest04.admin.kademi-ci.co/manageUsers/3303887/#summary-tab

**Comment by bradmac** [comment]
Actually i think remaining open is better, because the user often needs to add multiple memberships, and its annoying to have to re-open the modal each time.

**Comment by Uafinder** [comment]
ok, just wondering...
