### ISSUE TITLE
Create missing component preview images

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4618]
Please ensure that **all** components have preview images.

I can see missing images in the leadman app:

![image](https://user-images.githubusercontent.com/826458/33905050-3bb87b3a-dfe2-11e7-98df-b7f9f6629eca.png)

**Comment by Uafinder** [comment]
https://github.com/Kademi/kademi-dev/issues/4574

**Comment by anhnt** [comment]
added lot of missing component preview images

**Comment by AlaaKhalaf94** [comment]
I see that there are still some  missing component preview images , such as:
- component-publicProfileMemberships
- component-publicProfileContact
- component-topPurchased
- component-eventManager
- component-ecomProduct

Admin : http://fresh12.admin.kademi-ci.co/pages/fresh12/version1/
in page "Golden"

**Comment by anhnt** [comment]
added more missing images

**Comment by AlaaKhalaf94** [comment]
I'm sorry @anhnt  , there are other some missing component preview images :

- component-kpiTargetProgress
- component-salesDataCompare

Admin : http://fresh15.admin.kademi-ci.co/pages/fresh15/version1/
in page "newOne"

**Comment by anhnt** [comment]
they're there. but you didnt enable Sales data app so you dont see them

**Comment by bradmac** [comment]
@anhnt was Alaa seeing broken preview images? If so we need to fix that, and that should not happen due to a disabled app.

Also, i can see the same image used for multiple components:
![image](https://user-images.githubusercontent.com/826458/34283640-c46c2692-e731-11e7-9052-7365a5d31530.png)

**Comment by bradmac** [comment]
Please use different images for single value metric and number of users:
![image](https://user-images.githubusercontent.com/826458/34283806-cd2aade8-e732-11e7-9cb5-0d0275d49df4.png)

**Comment by anhnt** [comment]
Done

**Comment by AlaaKhalaf94** [comment]
There are set of components is displayed twice : 
- component-socialLinks
- component-errorDetails
- component-htmlPanel
- component-showHideButton
- component-rating
- component-tile
- component-recentUserRegistrations
- component-recentActiveUsers
- component-registrationsOverTime
- component-membersTable

There are set of different components use the same img , in "Sales Data Claimer" apps

![capture1](https://user-images.githubusercontent.com/26510030/34383184-37c8ac62-eb1c-11e7-9774-5c7142986025.PNG)

http://version1.fresh16-fresh16.kademi-ci.co/contenteditor?fileName=org.html
admin : http://fresh16.admin.kademi-ci.co

**Comment by anhnt** [comment]
```
There is a set of components is displayed twice :

component-socialLinks
component-errorDetails
component-htmlPanel
component-showHideButton
component-rating
component-tile
component-recentUserRegistrations
component-recentActiveUsers
component-registrationsOverTime
component-membersTable
```
Cant reproduce

```
There is a set of different components use the same img , in "Sales Data Claimer" apps
```
Fixed

**Comment by AlaaKhalaf94** [comment]
Hi @anhnt , The components are displayed twice in the list , like this examples : 

![capture1](https://user-images.githubusercontent.com/26510030/34405258-02a6d3d4-ebbb-11e7-9939-fc02929f4390.PNG)

![capture2](https://user-images.githubusercontent.com/26510030/34405259-02c5ebc0-ebbb-11e7-896a-4f2a532116c8.PNG)

![capture3](https://user-images.githubusercontent.com/26510030/34405260-034a8c36-ebbb-11e7-96a1-50575824f469.PNG)

**Comment by AlaaKhalaf94** [comment]
passed
