### ISSUE TITLE
Add role description and integrate with roles selection modal

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4619]
Extension to https://github.com/Kademi/kademi-dev/issues/4607

1. Edit io.milton.cloud.server.role.Role interface to have another method getDescription
2. Add this method for all instances of Role. RepositoryAppRole can be stubbed out for now (ie return null)
3. Use this property in the new role selection modal (#4607) to display the description

**Comment by bradmac** [comment]
Hey @anhnt this requires a java change. If you're happy to do it please go ahead, and check with me if you need a hand.

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/33977475-9e9c442a-e0cd-11e7-8c13-29f88d768632.png)
 
Please rebuild to test

**Comment by Uafinder** [comment]
yup, it works, but description is absent on some roles
![image](https://user-images.githubusercontent.com/1945230/34042162-00b36964-e1a4-11e7-9099-c349dcd34d2d.png)
And some others

**Comment by anhnt** [comment]
Added more description

**Comment by Uafinder** [comment]
Yup, looks great!
