### ISSUE TITLE
Moblix issues #1

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4620]
This user http://moblix.admin.kademi-ci.co/manageUsers/762030/#summary-tab

- The default 'reward store' menu item is now appearing for some reasons?  i do not want this to show as I have a custom menu dropdown to show reward store and auctions 

![image](https://user-images.githubusercontent.com/2201340/33921253-ccdc3c62-e016-11e7-95b5-423e2b4e22dd.png)

- The 'dashboard' menu item cannot be moved to the beginning of the menu using the menu drag and drop control, does not allow me to change its position

![image](https://user-images.githubusercontent.com/2201340/33921147-fdf2306e-e015-11e7-8b7c-91208ab81b6f.png)

- Getting a poll rendering error on dashboard

![image](https://user-images.githubusercontent.com/2201340/33921177-33a7505e-e016-11e7-8001-9c95aa9074a1.png)

http://moblix-channel_moblix.kademi-ci.co/sales-data.html

sales data in the graph not showing anymore

![image](https://user-images.githubusercontent.com/2201340/33921208-764743a6-e016-11e7-8100-2815bb0e96aa.png)

**Comment by ducdhm** [comment]
@paddyow Kpoll and Sales chart are fixed by reindexing

**Comment by ducdhm** [comment]
Done!
