### ISSUE TITLE
Moblix issues #2

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4621]
This user http://moblix.admin.kademi-ci.co/manageUsers/762059/#summary-tab

Adding a sales claim does not work here http://moblix-channel_moblix.kademi-ci.co/sales-claims.html

When added it should appear in the table below.

Data looks dodgy in the JSON dbase.
![image](https://user-images.githubusercontent.com/2201340/33921418-c87585e2-e017-11e7-8a94-e0bff7cc34a9.png)

Please also test at least the first part of the journey works when the claim email is fired: http://moblix.admin.kademi-ci.co/funnels/sales-claims/version1/#journeyBuilder-tab

**Comment by ducdhm** [comment]
Just need reindex and the data is there.
