### ISSUE TITLE
Mobix issue #3

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4622]
We have a rego journey here http://moblix.admin.kademi-ci.co/funnels/registration/version1/#journeyBuilder-tab

The first email once the participant is approved is sent an email with a button that should click them through and log them into the dashboard.

This is the template in the journey http://moblix.admin.kademi-ci.co/funnels/registration/version1/emailAction-3455cf/#summary-tab

The link is http://moblix-channel.kademi-ci.co/dashboard

Not sure why the login token is not getting applied now?

**Comment by bradmac** [comment]
Looks like that email does have the correct token on it:
http://moblix.admin.kademi-ci.co/emails/3318606

http://moblix-channel.kademi-ci.co/dashboard?miltonUserUrlHash=a8328af2-e969-4ff2-8346-f91b45b0cd25%3AAK2oYexLmo6xuUs7SqczyNGZfkw&edmid=3318606&miltonUserUrl=%2Fusers%2Fsdfds

**Comment by bradmac** [comment]
> Not sure why the login token is not getting applied now?

@paddyow why do you think there's no login token?

**Comment by paddyow** [comment]
This is the rego page http://moblix-channel_moblix.kademi-ci.co/dealer-claims/signup

I registered this user kadtest123@mailinator.com
Approved them in the admin
Got sent the first email in the journey
When I click through from the link in the eamil which is http://moblix-channel.kademi-ci.co/dashboard?miltonUserUrlHash=ebc3f61f-769e-4ddb-82a1-998d25cde4c5%3A9YIxic4DKaVOrJH6VLXcLmZAJno&edmid=3319398&miltonUserUrl=%2Fusers%2Ftest2

I get the login page
![image](https://user-images.githubusercontent.com/2201340/33923084-328ddd02-e023-11e7-9fb6-6c31962238c8.png)

Not sure what has changed, as this was working a few weeks back

**Comment by ducdhm** [comment]
It's fixed!

**Comment by Uafinder** [comment]
Ok, for me
