### ISSUE TITLE
Moblix issues

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4623]
![image](https://user-images.githubusercontent.com/1945230/33932371-7bfd35be-dffb-11e7-8b72-ac9c4b4e14d8.png)
Claim products contains deleted products
http://moblix.admin.kademi-ci.co/manageUsers/762059/#summary-tab
http://moblixchannel-moblix.kademi-ci.co/sales-claims.html

Issue with carousel
![clipboard - december 13 2017 11-37 am](https://user-images.githubusercontent.com/1945230/33932433-983df3f8-dffb-11e7-9453-87e34b9de930.png)
http://moblixchannel-moblix.kademi-ci.co

**Comment by ducdhm** [comment]
`Issue with carousel` is fixed!
