### ISSUE TITLE
multiple pop-ups appering when saving lead details in admin

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4624]
![image](https://user-images.githubusercontent.com/1945230/33939720-e159ce4a-e014-11e7-9913-acb31fdf8cc6.png)
http://vladtest05.admin.kademi-ci.co/leads/3328441/#information-tab

**Comment by ducdhm** [comment]
Fixed! I added default category for all messages. So this issue will be never happened again.

**Comment by Uafinder** [comment]
Yup, looks fine
