### ISSUE TITLE
ELearning component to see module progress of users within the current user's team

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4627]
- this should integrate with the orgselector, and show users from the currently selected org
- show a table of all module statuses, probably use pagination
- allow filtering by status (complete or in-progress), user, program, course and module

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/34031178-b70e2eb2-e1a2-11e7-8226-3299b2b21eac.png)

**Comment by Uafinder** [comment]
can't find this component in list...
http://vladtest07b.admin.kademi-ci.co/pages/vladb07learn/version1/

**Comment by anhnt** [comment]
added component image. please update kademi-dev and test on new account

**Comment by Uafinder** [comment]
1. Would be great to have dropdown lists for programs, courses and modules.
![image](https://user-images.githubusercontent.com/1945230/34104056-ae30af3e-e3f7-11e7-8ac3-73ace2dd03e0.png)

2. should be org selector in component setting I suppose.
![image](https://user-images.githubusercontent.com/1945230/34104083-c97ffdf8-e3f7-11e7-8f31-ca728b2b8aae.png)

3. User from other ORG can see the page with data from current org.
![image](https://user-images.githubusercontent.com/1945230/34104160-0a109774-e3f8-11e7-8051-e2835323540e.png)

http://vladtest08.admin.kademi-ci.co/

**Comment by bradmac** [comment]
> Would be great to have dropdown lists for programs, courses and modules.

I think having some sort of tree selection would be best, because courses depend on program, and modules depend on course, etc

**Comment by bradmac** [comment]
- remove complete column
- instead of displaying the 3 codes, display the module title if possible. @tuzzmaniandevil will add this to the index
- for the user, display the formattedName, and have an optional link  (from settings) to the profile page under /custs
- do not display expiry date
- have a single status column, which has a green tick if complete, otherwise show percentage completion

**Comment by tuzzmaniandevil** [comment]
Added the module title to the index

**Comment by anhnt** [comment]
> remove complete column
>instead of displaying the 3 codes, display the module title if possible. @tuzzmaniandevil will add this to the index
>for the user, display the formattedName, and have an optional link (from settings) to the profile page under /custs
>do not display expiry date
>have a single status column, which has a green tick if complete, otherwise show percentage completion

Done

>should be org selector in component setting I suppose.

There is org selector component under Reports app

>User from other ORG can see the page with data from current org.

Please add org selector component so it will get from current selected org

**Comment by Uafinder** [comment]
Incorrect user profile links:
![image](https://user-images.githubusercontent.com/1945230/34157911-2c20b4c8-e4cc-11e7-8732-b8216e450367.png)
![image](https://user-images.githubusercontent.com/1945230/34157897-23223b12-e4cc-11e7-8fe1-f90f02310861.png)
http://vladtest09.admin.kademi-ci.co/
http://version1.vlad09lear-vladtest09.kademi-ci.co/page3.html

**Comment by anhnt** [comment]
It needs to enable Leadman app because that page is customer detail page ie http://version1.vlad09lear-vladtest09.kademi-ci.co/custs/227ac233-8ea2-45e3-a223-af4c1b49b8c7/

**Comment by Uafinder** [comment]
How can Leadman lib is related to Learning app?! That's completely not obvious...

**Comment by bradmac** [comment]
@Uafinder the page being linked to isnt related to elearning. Its the customer profile page which is part of the leadman app. Note that its not leadman-lib thats needed, its the KLeadman app.

Menu items can be hidden from the menu editor as normal.

I think it would make sense to move this customer profile page to a generic app like UsersApp, but we wont do that just yet, lets just make sure it all actually works first.

**Comment by Uafinder** [comment]
Ok, so if leadman thing is ok, other is good!
