### ISSUE TITLE
Enhancements to generating plain text from html emails

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4628]
Styles are included, these should be removed:
![image](https://user-images.githubusercontent.com/826458/33975202-f36cb826-e0f1-11e7-8439-1c81b8dff6e3.png)

You can do this by using Jerry to remove specific elements such as <style> prior to conversion to text.

And non-text elements are converted to newlines, but when we have deeply nested divs this results in lots of empty lines. We should change this to that we only ever produce one newline for a consecutive list of non-text elements

**Comment by gonzalon** [comment]
@Uafinder for your reference you have to select the option to display the email body as plain text.
One problem as you can see in the image Brad posted was the styles, another is that we were getting something like:
![image](https://user-images.githubusercontent.com/2773216/34025376-6d877250-e1b4-11e7-8e32-a46eba492438.png)

And now:

![image](https://user-images.githubusercontent.com/2773216/34025383-7caffc20-e1b4-11e7-8878-5a0deb4cc539.png)

Also to test I used the content of the email "Qantas 12 Days - HKG788" in travelworld.

**Comment by Uafinder** [comment]
Yup, looks ok...
