### ISSUE TITLE
Pie chart component small bug

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4629]
![image](https://user-images.githubusercontent.com/1945230/33988070-c8ebb118-e0cb-11e7-821e-0e7483ad41a4.png)
http://vladtest06.admin.kademi-ci.co/pages/vlad06data/version1/

**Comment by bradmac** [comment]
@gonzalon can you please update so that when the description is missing we use the query name

**Comment by bradmac** [comment]
I think there are a few components that allow selecting a query so we should check those as well

**Comment by gonzalon** [comment]
We were missing a bunch of @Docs annotations should be fine for all QueryTables

**Comment by Uafinder** [comment]
ok, list is empty at the moment
