### ISSUE TITLE
uploading second image cause error to Loginform component

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4630]
![image](https://user-images.githubusercontent.com/1945230/33993862-f5963250-e0e0-11e7-95b8-2d89024ee643.png)
http://vladtest06.admin.kademi-ci.co/pages/vlad06data/version1/
1. Add component to page
2. upload image for logo
3. Remove image
4. Try to upload another image

**Comment by bradmac** [comment]
@ducdhm this issue might be redundant with the new image controls, but please check

**Comment by ducdhm** [comment]
Move to https://github.com/Kademi/kademi-dev/issues/4663#event-1393917886
