### ISSUE TITLE
Link from product page to see the variants in the SKU page

### ISSUE THREAD

**Issue by gonzalon** [Kademi/kademi-dev#4632]

**Comment by gonzalon** [comment]
In the products page:

![image](https://user-images.githubusercontent.com/2773216/34020046-c3932f9a-e196-11e7-9279-78a423b00cc1.png)

In the Sku page:
![image](https://user-images.githubusercontent.com/2773216/34020054-ce006948-e196-11e7-88cd-56e09ae72cd5.png)

**Comment by AlaaKhalaf94** [comment]
passed
