### ISSUE TITLE
Re-process KPI error

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4633]
![image](https://user-images.githubusercontent.com/1945230/34033092-8188f9b4-e181-11e7-8153-afe8973644b5.png)
http://vladtest06.admin.kademi-ci.co/sales/salesqa01/kpis/kpiqa01/#general-tab

**Comment by gonzalon** [comment]
Now it would validate that it found a profile for the email.

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/34212027-9ca3c988-e5a3-11e7-9e81-64f021a99e23.png)
![image](https://user-images.githubusercontent.com/1945230/34212037-a2fdb7d0-e5a3-11e7-9414-c029026fa0ab.png)
looks like it process correctly only first string, other strings are mentioning as invalid...

**Comment by Uafinder** [comment]
yup, looks fine!
