### ISSUE TITLE
Permission access denied for typical learner

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4635]
Member of learner group can't access to MyLearning page:
http://vladb07learn_vladtest07b.kademi-ci.co/myLearning
http://vladtest07b.admin.kademi-ci.co/groups/learners/
![image](https://user-images.githubusercontent.com/1945230/34043771-2ca10cfa-e1ab-11e7-94a8-fdc5e3ffe2aa.png)

**Comment by Uafinder** [comment]
Probably related to this change because when user in viewable group everything works fine, but when he in completable group - error appears
https://github.com/Kademi/kademi-dev/issues/2715

**Comment by bradmac** [comment]
Probably because of this - https://github.com/Kademi/kademi-dev/issues/4656

You'll need to remove the current role and add it again

**Comment by Uafinder** [comment]
nope. it's not because of this
![image](https://user-images.githubusercontent.com/1945230/34155316-8ecf90b8-e4c1-11e7-952b-69722466ba74.png)
Fresh account
http://vladtest09.admin.kademi-ci.co/websites/

**Comment by bradmac** [comment]
Ok, the permission for the mylearning page only worked correctly when it was applied to the org. Fixed so also works for repos.

**Comment by Uafinder** [comment]
Nope, still doesn't have access. The reason is that role membership is assigned to website, not Org.
The basic Learner group is created by Market place installation, so probably would be correct to change it to role in their own org membership.

**Comment by tuzzmaniandevil** [comment]
Updated the app to create the roles with "their own organisation"

**Comment by Uafinder** [comment]
Yup, looks great!
