### ISSUE TITLE
Survey app - error when adding a question to survey and press enter

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4636]
![image](https://user-images.githubusercontent.com/1945230/34047675-aef54e60-e1b9-11e7-9cc6-9369786ffc97.png)
http://vladtest07b.admin.kademi-ci.co/ksurvey/survey-5769c769-21b1-4a66-90fc-03dac2e5d22b/#questions-tab

**Comment by anhnt** [comment]
Fixed

**Comment by Uafinder** [comment]
yup, looks work
