### ISSUE TITLE
Finish survey text bad

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4637]
![image](https://user-images.githubusercontent.com/1945230/34048374-25d45f7e-e1bc-11e7-943c-f0a36ea57b79.png)
![image](https://user-images.githubusercontent.com/1945230/34048384-2d3eaa80-e1bc-11e7-85b6-c1cfc8c9beca.png)
text for links are same color as background
http://vladtest07b.admin.kademi-ci.co/ksurvey/survey-920af56d-1ec9-4caa-81ed-4a71337cde7c/#questions-tab
http://vladb07survey-vladtest07b.kademi-ci.co/ksurvey/survey-920af56d-1ec9-4caa-81ed-4a71337cde7c/

**Comment by bradmac** [comment]
@ducdhm please make sure we're using bootstrap classes and components correctly.

**Comment by anhnt** [comment]
Done

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/34357052-58dad2fc-ea4c-11e7-933c-ce49df2a7638.png)

**Comment by anhnt** [comment]
Yup fixed

**Comment by Uafinder** [comment]
yup, fine
