### ISSUE TITLE
Show Category levels when adding products to reward store

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4639]
http://safetydemo.admin.kademi.us/reward-store/safety-store/?addProducts

Currently looks like this:
![image](https://user-images.githubusercontent.com/2201340/34085111-8b0e0f32-e3df-11e7-8a40-e7fdbdc9fde9.png)

Should look like this http://safetydemo.admin.kademi.us/reward-store/safety-store/#products-tab

![image](https://user-images.githubusercontent.com/2201340/34085113-956a2236-e3df-11e7-9121-310cfe85c192.png)

**Comment by gonzalon** [comment]
![image](https://user-images.githubusercontent.com/2773216/34085249-816efc44-e3f2-11e7-9bcd-78a9727dbd35.png)

**Comment by AlaaKhalaf94** [comment]
passed
