### ISSUE TITLE
Managing large lists of products

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4640]
**Use case**
Most of my safety programs use the same reward store list, but each time I setup a new safety site, I have to spend a lot of time searching thousands of reward store products and add them to my reward store.

I want the ability to reuse a reward store list across accounts.

Could these be setup in the root account and pulled?

**Comment by bradmac** [comment]
No, but you can simply export the reward store and import it into another account.

![image](https://user-images.githubusercontent.com/826458/34129990-16fcf050-e4ab-11e7-80ed-1012534b8b06.png)
