### ISSUE TITLE
Test reward store search and pager

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4641]
http://safetydemo.admin.kademi.us/reward-store/safety-store/#products-tab

@Uafinder please test the search function and pager on the above page to ensure it works as intended.

**Comment by Uafinder** [comment]
1. when accessing reward store page error appears in console and search and filter don't work (sometimes)
![image](https://user-images.githubusercontent.com/1945230/34108653-90a2c80a-e409-11e7-8d36-49d66ae30bdf.png)

2. Paginator works incorrect. When you select 6 page for example, it shows you not sixth hundred of products, but all 600 products in list... e.g. it just raise a limit...
![image](https://user-images.githubusercontent.com/1945230/34109107-42588e9e-e40b-11e7-8b8a-94f61d3666d4.png)
But there are from 1 to 500 products

**Comment by bradmac** [comment]
That error appears unrelated, it looks like some libs havent been installed.

**Comment by gonzalon** [comment]
I coudln't reproduce the error for the search, seems to be working fine to me. Can you still reproduce it? If so maybe provide the steps to reproduce it!

The logic for the paginator was updated

**Comment by Uafinder** [comment]
1. Error doesn't appear
2. Paginator still works badly.
For example you're on first page and you see 100 products from 1 to 100. You click to seconds page and you should see 100 products from 101 to 200. However it shows you 200 products from 1 to 200.

**Comment by gonzalon** [comment]
@Uafinder cant reproduce the error locally. Did you test it in the safetydemo or in CI?

**Comment by Uafinder** [comment]
i'm testing on safety demo as Patrick asks...

**Comment by Uafinder** [comment]
Yup, looks good at the moment
