### ISSUE TITLE
Add 'Every day cost' field in reward store

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4642]
Client wants to see the 'Every day cost' field added next to the base cost so they can make a decision if the product is added.

This would need to be added to screens:
http://safetydemo.admin.kademi.us/reward-store/safety-store/
http://safetydemo.admin.kademi.us/reward-store/safety-store/?addProducts

They would like the field to show a percentage of the base costs i.e. 150% of everyday cost.

**Comment by bradmac** [comment]
@gonzalon we need to do this:
- display Product.rrp on both reward store screens (existing products and add products)
- populate Product.rrp from the every day cost field from Hinda

I'm not sure which field that is though..

**Comment by gonzalon** [comment]
Now its being imported from Hinda:


![image](https://user-images.githubusercontent.com/2773216/34132900-e4125124-e4b6-11e7-9506-19d600d6819f.png)

![image](https://user-images.githubusercontent.com/2773216/34132905-ec6cf22a-e4b6-11e7-8850-a7798c4c9b59.png)

**Comment by AlaaKhalaf94** [comment]
passed
