### ISSUE TITLE
Managing new vs. discontinued reward products

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4644]
In order to manage a reward store, the admin needs to know

1) When a product has expired and is no longer available so they can optionally choose a product to replace it
2) When the Hinda sync runs and a product is removed, does this automatically get removed from the reward store
3) When a new product is added so they can opt to add this

What ways could we support this?

**Comment by bradmac** [comment]
We've already applied that feedback.

The user can sort existing products by added date, and when adding new products they can sort by date created.

The sync does remove products from the product library, although @gonzalon is just checking if they're removed from reward stores as well.

**Comment by gonzalon** [comment]
For 2: https://github.com/Kademi/client-hinda/issues/16
