### ISSUE TITLE
SKU page taking too long to load (around 15 secs)

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4645]
http://asrdev.admin.kademi.us/skus/

Then searching for AW14803 took about 20 secs.

**Comment by gonzalon** [comment]
I tested locally with around 4k skus

**Comment by Uafinder** [comment]
Hmmm... at the Patrick's link it still takes 20 seconds to search...

**Comment by gonzalon** [comment]
I just did a test locally with images as well and its fast as well...I think we didnt deploy this change to US yet.

**Comment by Uafinder** [comment]
Yeah, looks much better at the moment
