### ISSUE TITLE
SKUs missing image

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4648]
See here http://asrdev.admin.kademi.us/skus/

![image](https://user-images.githubusercontent.com/2201340/34088376-2ee40252-e3fd-11e7-80de-51c5503fa618.png)

Under products the image exists.

![image](https://user-images.githubusercontent.com/2201340/34088390-4511273a-e3fd-11e7-9a0d-3f125d6dee6e.png)

**Comment by gonzalon** [comment]
https://github.com/Kademi/client-hinda/issues/18
