### ISSUE TITLE
Base cost not showing

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4649]
See here http://asrdev.admin.kademi.us/skus/

Power Path® Deluxe Carpet Washer has base cost of 183.40

Not base costs showing on prods http://asrdev.admin.kademi.us/products/?dataQuery=Power&supplier=

Or reward stores http://asrdev.admin.kademi.us/reward-store/general/#products-tab

Or reward store add page http://asrdev.admin.kademi.us/reward-store/general/?addProducts

**Comment by gonzalon** [comment]
Updated the import from Hinda, now it would use the lowest price of the SKUs as the base price of the product.

**Comment by AlaaKhalaf94** [comment]
passed
