### ISSUE TITLE
A better way to choose categories 

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4650]
http://asrdev.admin.kademi.us/reward-store/general/?addProducts

When trying to search for a category, when there are hundreds, the process takes a long time.  Need to be able to search for and select multiple categories.  

We also need to select categories to exclude.

![image](https://user-images.githubusercontent.com/2201340/34088532-0c3e1b42-e3fe-11e7-828b-ad98eeb8a900.png)

Adding a combo of search and check boxes would be good, similar to the below.
https://semantic-ui.com/modules/dropdown.html

![image](https://user-images.githubusercontent.com/2201340/34088590-6c8cd524-e3fe-11e7-9173-94619dff28a3.png)

**Comment by bradmac** [comment]
So we need to have 2 category selection inputs, and each one needs to allow searching and selecting multiple items

The 2 inputs will be for included and excluded categories.

**Comment by tuzzmaniandevil** [comment]
Changed the search syntax to be similar to GitHub allowing you to include and exclude terms and fields.
Example to search for apples excluding the Electronics (name: elec) category:
`apples -category:elec` or `apples -categoryTitle:Electronics`
Or to search for anything in the "Food Supply" category and the "Food" categories:
`category:food-supply category:food` or `categoryTitle:"Food Supply categoryTitle:Food"`

Terms that contain a space like a category name needs to be in double quotes as in the above example.
Any terms that aren't followed by a colon `:` is treated as a normal search term on the product name and title for example `apple` is a search term but `category:elec` is a field term. If a term starts with `-` it's treated as an exclude term e.g. `apple -category:elec` will search for products with a name or title containing `apple` and that ARE NOT in the elec category

Here are all the search fields:
- category or categoryName
- categoryTitle
- supplier or supplierName
- supplierTitle
- sku or skuName
- skuTitle

**Comment by tuzzmaniandevil** [comment]
This is what the current page looks like:
![image](https://user-images.githubusercontent.com/3378330/34970277-65337b02-fad8-11e7-8518-81762ba4bd0c.png)

We want it to have a similar UI to GitHub with the dropdown boxes like this:
![image](https://user-images.githubusercontent.com/3378330/34970249-20da6fce-fad8-11e7-876c-cd5c0107fde5.png)

The fields we want are:
- include category - Be able to select multiple
- exclude category - Be able to select multiple
- supplier - Be able to select multiple
- library - Only be able to select one

**Comment by ducdhm** [comment]
@bradmac 

 * `manageAddProducts.html` file, line `54`, please help me to show only 10-20 categories.
 * `manageAddProducts.js` file:
    * Line 120: Change url `/` to real request
    * Line 138: Add data result from server to `categories` variable

**Comment by bradmac** [comment]
hey @ducdhm a couple of probs:
1. initially when nothing has been selected, when i do a search the "currently selected" section shows all categories
![image](https://user-images.githubusercontent.com/826458/35065289-b1204d06-fc31-11e7-8c2a-3568c5b43fa5.png)
2. When i select a category is should be added to the search text box, but currently it isnt
![image](https://user-images.githubusercontent.com/826458/35065322-d2791302-fc31-11e7-9e16-dfd6be3cccdc.png)
this should be the same as github:
![image](https://user-images.githubusercontent.com/826458/35065355-eb0f9850-fc31-11e7-97cf-0670131877b0.png)

**Comment by bradmac** [comment]
- unticking a category must remove it from the search query box

**Comment by bradmac** [comment]
I've added a new term called "combine" which allows terms to be combined with AND or OR

Eg: this will display products in either category
```
category:175865 category:175874 combine:or
```

**Comment by bradmac** [comment]
Also, I've noticed that when selecting a category there is often a space added between the request parameter and the value, which makes the url invalid:

See after the q=

![image](https://user-images.githubusercontent.com/826458/35067605-53cf8a24-fc39-11e7-800d-2004acc61a2d.png)

**Comment by ducdhm** [comment]
Done!

**Comment by bradmac** [comment]
@Uafinder over to you for testing.

**Comment by Uafinder** [comment]
looks good for me

**Comment by bradmac** [comment]
I can see a few probs

1. the NOT filtering doesnt seem to be working 
![image](https://user-images.githubusercontent.com/826458/35886576-60314da8-0bf6-11e8-880b-356fbfa2ab34.png)

2. The search is extremely slow. Please check SQL performance (see utils page) and add indexes if needed

3. Need to show full cat path to identify cats with the same name
![image](https://user-images.githubusercontent.com/826458/35886602-81ca6a44-0bf6-11e8-89e5-73da89b907be.png)

**Comment by gonzalon** [comment]
1. Fixed
2. Should be way faster as we are only bringing the 20 parent categories
3. Now it shows the parent category
![image](https://user-images.githubusercontent.com/2773216/35895746-ac697c5a-0c1d-11e8-8a0a-dadfa70fb546.png)
4. Integrated

**Comment by Uafinder** [comment]
1. Works ok
2. Ok
3. 
4. i'm not sure if it's correct
![image](https://user-images.githubusercontent.com/1945230/35917856-5781bb4e-0c18-11e8-9553-a2b8f188ed86.png)
When parent category contains child category with products and you select parent category, child category products not appear

**Comment by gonzalon** [comment]
4. It's only going to be like that when there are more than 20 Categories so the search make sense to use it.
5. We only show the products for the category atm

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/35970759-35775a06-0cd4-11e8-8f3e-126aabfeee6a.png)
When you clear search field, it doesn't show full categories list
http://vladtest31a.admin.kademi-ci.co/reward-store/vlad31aweb-store/?addProducts

**Comment by gonzalon** [comment]
hey @ducdhm  can you take a look at it? Seems like if you only click / unclick works fine, but when after you search the content is replaced (manageAddProducts.js - initSelectPicker) with the result, so when you blank the search field doesn't show all the data.

I think we could save the original state?

**Comment by ducdhm** [comment]
@bradmac I have this case which I can't resolve it. Example: 
 * I select `Cate 1` and `Cate 2` in default list
 * I type `3` to search and select `Cate 3`
 * I refresh my browser, in query textbox, I can see `category:cate-1 category:cate-2 category:cate-3` but in categories selectbox, only `Cate 1` and `Cate 2` are selected.

-> Reason is `Cate 3` doesnt exist in default list

To resolve it, I think we show all categories as default and disable search via AJAX. What do you think?

**Comment by bradmac** [comment]
This has been done in another issue
https://github.com/Kademi/kademi-dev/issues/4916
