### ISSUE TITLE
Can't add product to cart when I need to select a variant

### ISSUE THREAD

**Issue by gonzalon** [Kademi/kademi-dev#4652]
In the list of products, if the product has a variant you cant add it directly to the cart as you need to select a variant.

Ex:
![image](https://user-images.githubusercontent.com/2773216/34090684-a2682b66-e41d-11e7-9882-a5c3df0c2227.png)

If I select a variant here, I can add it:
![image](https://user-images.githubusercontent.com/2773216/34090711-d674ccac-e41d-11e7-9cfa-6a8e139318e2.png)

**Comment by bradmac** [comment]
I think we need to remove the add to cart button on the list page. It will be rare that products wont have variants.

**Comment by anhnt** [comment]
Removed the class that triggers adding item to cart. Now when clicked to that button it will redirect to product detail page

**Comment by AlaaKhalaf94** [comment]
passed
