### ISSUE TITLE
Organisation selector doesn't appear after enable it from menu settings

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#4653]
admin : http://fresh09.admin.kademi-ci.co

I enable organisation selector from menu settings : http://fresh09-fresh09.kademi-ci.co//theme/contenteditor?fileName=defaultThemeTemplate.html

![capture1](https://user-images.githubusercontent.com/26510030/34096437-eac4c65c-e3dd-11e7-954b-8d0e9f14d398.PNG)

but in the site , the org selector doesn't appear , appear white space instead of it

![capture2](https://user-images.githubusercontent.com/26510030/34096475-1a077c66-e3de-11e7-9f3a-dee31a1b74a8.PNG)

**Comment by tuzzmaniandevil** [comment]
The user needs to either have the `Reporting Access` role of the `Administrator` role for the org selector to show and work
