### ISSUE TITLE
Roles are being displayed with their description, should be name

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4656]
![image](https://user-images.githubusercontent.com/826458/34128846-f38e004a-e4a6-11e7-94a1-ac9bb7b27b8a.png)

Related - https://github.com/Kademi/kademi-dev/issues/4619#issuecomment-351993950

Note that this created invalid roles, the name doesnt match the actual role so will not convey permissions

**Comment by Uafinder** [comment]
yup, looks fine at the moment... I saw it yesterday, but thought that it's by design...
