### ISSUE TITLE
eLearning workflow not working

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4658]
Video
[Part 4 - Adding training content.zip](https://github.com/Kademi/kademi-dev/files/1570308/Part.4.-.Adding.training.content.zip)

**Comment by paddyow** [comment]
Clicking save causes error
![image](https://user-images.githubusercontent.com/2201340/34139950-ad4330f4-e4cb-11e7-82f9-844ca8786ebc.png)

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
Those ones looks fixed,
but please note two things...
1. Error in console while adding some component to container
![image](https://user-images.githubusercontent.com/1945230/34164279-cdc74246-e4e1-11e7-9789-f65c192d086d.png)

2. when you first time add page, it loads content editor very long - approx. 15 secs, and if you add name of the page and click save before it load completely - content editor will not load successfully.

**Comment by tuzzmaniandevil** [comment]
1. The surveyDB didn't have the "Allow Access" enable to was throwing an error

**Comment by Uafinder** [comment]
Yup, looks better
