### ISSUE TITLE
Kchat date\time issue

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4660]
![image](https://user-images.githubusercontent.com/1945230/34147110-3a11ebe6-e4a5-11e7-8e5e-7d8103645c48.png)
When you're leaving messages timestamps looks bad for it.
http://vlad09test_vladtest09.kademi-ci.co/
http://vladtest09.admin.kademi-ci.co/

**Comment by tuzzmaniandevil** [comment]
It will now take the timezone into account

**Comment by Uafinder** [comment]
Looks fine!
