### ISSUE TITLE
Geo-loc error on leadman page loading

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4661]
![image](https://user-images.githubusercontent.com/1945230/34150383-e4bbaf2c-e4b0-11e7-941c-2d94a9e5079a.png)
http://vlad09lead_vladtest09.kademi-ci.co/dashboard
userqa02@mailinator.com

Looks like it's because of missed Sales Team Viewer role.
Is it by design?

**Comment by anhnt** [comment]
Looks ok with SalesManager on org role

**Comment by anhnt** [comment]
http://vladtest09.admin.kademi-ci.co/groups/sales-manager/

**Comment by Uafinder** [comment]
Same problem with membership in org
