### ISSUE TITLE
Errors in console while creating a lead

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4662]
![image](https://user-images.githubusercontent.com/1945230/34150522-38a865e4-e4b1-11e7-9d02-30d2d4519d42.png)
http://vlad09lead_vladtest09.kademi-ci.co/dashboard
userqa02@mailinator.com

it looks like because of missing Sales Team Viewer role... why it's needed for Lead creation?

P.s. Create lead buttons also don't work.

**Comment by anhnt** [comment]
Cannot reproduce at the moment. The user with only sales role can search for existing lead profiles without any error

![image](https://user-images.githubusercontent.com/735555/34188338-6eb2645c-e568-11e7-8538-f565fa930390.png)

**Comment by anhnt** [comment]
I noticed that the sales role must be connect to org to work. It was Sales on vlad09lead which causes the error

![image](https://user-images.githubusercontent.com/735555/34188426-e7d8d55a-e568-11e7-9f67-fd1690b5109f.png)

**Comment by bradmac** [comment]
> I noticed that the sales role must be connect to org to work.

Yes, thats because leads exist across websites, it really doesnt make sense to limit per website. Eg you cant say someone can manage leads in website A but not website B, because they're the same leads.

**Comment by Uafinder** [comment]
ok, causing a new issue
