### ISSUE TITLE
Image component adding bug

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4664]
1. Create a custom page
2. Push edit
3. Add 2 columns (33/67) container
4. Take Photo block and drag & drop it to left part of container.
5. Image will not appear
![image](https://user-images.githubusercontent.com/1945230/34155039-79f0fa2a-e4c0-11e7-821b-f3eb23cc4a43.png)
http://vladtest09.admin.kademi-ci.co/pages/vlad09lear/version1/

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
Yup, looking good
