### ISSUE TITLE
Categories not displaying correctly

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#4665]
Categories not displaying correctly in quick add from product page
http://fresh11.admin.kademi-ci.co/products/3430622/#panel_details-tab

![capture1](https://user-images.githubusercontent.com/26510030/34156846-aa9862a6-e4c7-11e7-8a78-d242493ee38a.PNG)

**Comment by bradmac** [comment]
Please use a similar appearance as on the reward store pages, ie indented child cats

**Comment by gonzalon** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/2773216/34180083-40196668-e572-11e7-8063-14f4c544adde.png)

**Comment by AlaaKhalaf94** [comment]
passed

**Comment by AlaaKhalaf94** [comment]
In "Most Products Viewed Report" page and "Most Purchased Products Report" page , also categories not displaying correctly 

http://fresh11.admin.kademi-ci.co/reporting/MostPopularProduct
http://fresh11.admin.kademi-ci.co/reporting/MostPurchasedProduct

![capture1](https://user-images.githubusercontent.com/26510030/34208821-70ba6508-e598-11e7-8bee-011315ea4b82.PNG)

**Comment by bradmac** [comment]
Created new issue for reports - https://github.com/Kademi/kademi-dev/issues/4672
