### ISSUE TITLE
Can't find / reproduce video

### ISSUE THREAD

**Issue by gonzalon** [Kademi/kademi-dev#4667]
If I open de video I can reproduce it: 
https://waterco.admin.kademi.com.au/repositories/hydroxypure/version1/videos/Chemicals/Changing%20Perox%20containers.mp4

but when I select the video seems that its not getting the correct location:

![image](https://user-images.githubusercontent.com/2773216/34186634-d418e630-e591-11e7-8cdf-f6d69db50f45.png)

Site:
http://version1.hydroxypure-waterco.kademi.com.au/videos/Chemicals/

**Comment by bradmac** [comment]
Wrong streamnig format path on Chrome:
http://version1.hydroxypure-waterco.kademi.com.au/alt-640-360.webm

**Comment by anhnt** [comment]
Fixed on version3 http://version3.hydroxypure-waterco.kademi.com.au/videos/Chemicals/

**Comment by gonzalon** [comment]
Working fine!
