### ISSUE TITLE
Video url is wrong after uploaded via keditor

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#4668]
See image placeholder output

```
<img class="video-jw" id="undefined" src="/download.mp4/_DAV/PROPFIND?fields=milton:hash/alt-640-360.png" data-autostart="false" data-aspectratio="4:3" data-video-src="/download.mp4/_DAV/PROPFIND?fields=milton:hash" data-repeat="false" data-controls="true">

**Comment by anhnt** [comment]
This need to test on production, so i will inform when libs are updated on AU

**Comment by Uafinder** [comment]
ok, waiting

**Comment by bradmac** [comment]
@anhnt assigning to you because needs you to action it

**Comment by anhnt** [comment]
Tested working ok here http://anh.admin.kademi.com.au/pages/anhtest2/version1/

**Comment by Uafinder** [comment]
I've check here, looks not very good for me:
http://anhtest2-anh.kademi.com.au/123.html
http://anh.admin.kademi.com.au/pages/anhtest2/version1/
![image](https://user-images.githubusercontent.com/1945230/34385091-e5d317b4-eb28-11e7-8591-ffa308d4f160.png)

**Comment by bradmac** [comment]
Works correctly for me. 

Probably the streaming format of the video hadnt generated yet, so i think is ok

**Comment by bradmac** [comment]
hey @Uafinder the first video works fine for me. Second isnt playing, but that appears to be because it hasnt generated the streaming format yet.

**Comment by bradmac** [comment]
Lets discuss when you're online

**Comment by Uafinder** [comment]
hmmm, looks ok to me too...
weird thing...
It looks ok on QA for me too
