### ISSUE TITLE
Installing Leadman app via Marketplace create a group with incorrect role in org linking

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4669]
https://github.com/Kademi/kademi-dev/issues/4662
https://github.com/Kademi/kademi-dev/issues/4661
Installation cause creation of group where some roles added:
![image](https://user-images.githubusercontent.com/1945230/34198573-948cbe92-e573-11e7-9a13-9eefa739d265.png)
where vlad10lead is a website
as discussed with Anh and brad there should be in their own organisation.
http://vladtest10.admin.kademi-ci.co/groups/sales/

**Comment by bradmac** [comment]
@anhnt can you update the KLeadman init script to create org based roles?

**Comment by anhnt** [comment]
Fixed

**Comment by Uafinder** [comment]
Content viewer role still has link to a website
![image](https://user-images.githubusercontent.com/1945230/34355361-50af47ac-ea3d-11e7-871c-e71c465eb067.png)
http://vladtest11.admin.kademi-ci.co/groups/

**Comment by anhnt** [comment]
Content Viewer role should be linked to website repo. @bradmac can you please confirm?

**Comment by bradmac** [comment]
@anhnt thats correct. The sales roles need to be org based, but content viewer should be for the website only, because we dont necessarily want to give the sales people access to every website in the account

**Comment by anhnt** [comment]
so handing over to vlad..

**Comment by Uafinder** [comment]
yup, looks good
