### ISSUE TITLE
Module image thumbnails are not displaying

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4670]
![image](https://user-images.githubusercontent.com/1945230/34205486-45ae9b84-e58b-11e7-8bd5-e48f7b02d775.png)
![image](https://user-images.githubusercontent.com/1945230/34205475-3ce8dd0c-e58b-11e7-85dc-cac0bbf926a3.png)
http://vladtest10.admin.kademi-ci.co/websites/vlad10learn2/version1/programs/p1/c1/m2/#details-tab
http://vlad10learn2_vladtest10.kademi-ci.co/myLearning
http://vlad10learn2_vladtest10.kademi-ci.co/dashboard

**Comment by bradmac** [comment]
@ducdhm please ping me if you need a hand

**Comment by ducdhm** [comment]
Fixed! @Uafinder you should reselect image and save it.

**Comment by AlaaKhalaf94** [comment]
passed
