### ISSUE TITLE
Make some Roles only support organisation association

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4671]
Some roles jsut dont make sense to be connected to a repository, eg Sales role, because leads are the same across the whole account regardless of website.

For these roles, the user should not have the option of selecting a repository.

- Extend the Role interface with an enum property of targetType - {Repo, Org, Both}
- Update the manage gruop page, so the modal for adding roles to a group only shows valid options for the role

Related - https://github.com/Kademi/kademi-dev/issues/4661#issuecomment-352989633 https://github.com/Kademi/kademi-dev/issues/4669

**Comment by gonzalon** [comment]
ReportingAccessRole  - ORGANISATION
OrgAdminRole - ORGANISATION
UserAdminRole - ORGANISATION
AdminRole - BOTH

**Comment by gonzalon** [comment]
@Uafinder so we added validation for the roles to check whit what they can connect.
I just changed a few, but for you to check it, If you try to assign any of these roles to a repository:
ReportingAccessRole - ORGANISATION
OrgAdminRole - ORGANISATION
UserAdminRole - ORGANISATION
it should show something like:

![image](https://user-images.githubusercontent.com/2773216/37686004-871d0f22-2cfa-11e8-8f5b-b7f40e73df39.png)

**Comment by Uafinder** [comment]
ok
