### ISSUE TITLE
Support alt tags on Kademi's ckeditor image plugin

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4675]
![image](https://user-images.githubusercontent.com/826458/34235462-bce48b34-e656-11e7-9a6b-81ec8aaa4d54.png)

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/34292285-ec447826-e732-11e7-875a-bc863999cf50.png)

**Comment by AlaaKhalaf94** [comment]
passed
