### ISSUE TITLE
Promotion detail admin: missing form builder lib

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#4678]
![image](https://user-images.githubusercontent.com/735555/34332171-4e7810e6-e960-11e7-97c7-7480f1693297.png)

Also consider to use fuelux form builder

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
Looks ok at the moment...
btw, I worked with promos yesterday and didn't spot this error...weird
