### ISSUE TITLE
Enable previewing journey emails

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#4682]
At the moment when we try to test an email from a journey, this generally returns an exception of not being able to process the email template because of a missing **lead** object in the scope. This is correct since we only select the profile.

But since most of our emails use the **lead** object in creating the email content, this makes the test button for emails with **lead** object used untestable.

To enable testing we need to allow user to select the profile, and filter down a list of leads to the leads of the same journey being tested, after selection the user can then fire a test email that uses this lead and this profile.

**Comment by mkhoudary** [comment]
https://github.com/Kademi/client-vaya/issues/237

**Comment by bradmac** [comment]
@mkhoudary i think you're right, but really there are 3 things here:
- firstly, expressions in emails should always be null safe, so they dont throw an exception when there is something missing. Being non-null safe has really caused us a few problems. MVEL supports null safe notation (like velocity)
- secondly, its better to use fields then MVEL expressions, wherever possible. We added a couple of new fields recently to assist with this. So please consider refactoring when you can
- and thirdly, yes, i agree the ability to select a lead for a target profile is a good feature which we should do

**Comment by mkhoudary** [comment]
I've checked that and it is working fine..
