### ISSUE TITLE
KChat visual bugs

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4685]
- Username missed
![image](https://user-images.githubusercontent.com/1945230/34351538-ead9aa7e-ea25-11e7-9e9b-9eb00c088921.png)

- Avatar dimensions bad. It looks incorrect aspect ratio between width and height.
![image](https://user-images.githubusercontent.com/1945230/34352774-1d50ce2c-ea2d-11e7-8f0b-20a2c2756dca.png)

- Green online icon is not in place

- avatar is empty
![image](https://user-images.githubusercontent.com/1945230/34353279-d6727ee4-ea2f-11e7-84bd-8241a7e65839.png)

https://vlad11chat_vladtest11.kademi-ci.co/
https://vladtest11.admin.kademi-ci.co

**Comment by bradmac** [comment]
@ducdhm looks like front end stuff, can you do these?

**Comment by ducdhm** [comment]
UI in admin:
![newui](https://user-images.githubusercontent.com/1289631/34431324-c9c0dc7c-eca0-11e7-9622-89c63e90f7b5.png)

UI in frontend
![newui2](https://user-images.githubusercontent.com/1289631/34431325-ca8960ca-eca0-11e7-9188-e84f1de56778.png)

**Comment by Uafinder** [comment]
Looks fine
