### ISSUE TITLE
https to http problem

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4687]
You're on https address of admin console. You're going to review websites and it automatically change https to http.
Same situation with organisation details link.
![image](https://user-images.githubusercontent.com/1945230/34353010-721c862a-ea2e-11e7-904a-26639e618eb8.png)
https://vladtest11.admin.kademi-ci.co/

**Comment by bradmac** [comment]
I cant see any problem. All the links appear to be https. Eg the Websites link in the menu is to https://vladtest11.admin.kademi-ci.co/websites

**Comment by Uafinder** [comment]
I wrote a video. A link really looks like https, but looks some redirection works
https://drive.google.com/file/d/1tv84B9qWYGtvSAdMhqqXpXVZDUq7KT1n/view?usp=sharing

**Comment by bradmac** [comment]
OK, got it. This happens when the link is a collection resource, but does not have a trailing slash.

Eg the link is to https://vladtest11.admin.kademi-ci.co/websites then redirects to http://vladtest11.admin.kademi-ci.co/websites/

**Comment by bradmac** [comment]
@gonzalon can you please check AbstractResource.checkRedirect? might be a problem with WebUtils.isHttps()

**Comment by Uafinder** [comment]
Yup, looks better
