### ISSUE TITLE
New photo plugin: photo upload failed

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4688]
1. go to module details
2. click select on the module thumbnail
3. click upload image
4. select image
5. it will upload it but doesn't show in preview and in the left panel

same thing with keditor and image component
![image](https://user-images.githubusercontent.com/1945230/34356092-5fb634ee-ea43-11e7-9247-b93e326d336d.png)
http://vladtest11.admin.kademi-ci.co/websites/vlad11chat/version1/programs/p1/c1/m1/#details-tab

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
Yup, works fine
