### ISSUE TITLE
SKU code disappears when entering

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4692]
SKU code disappears when entering, refresh doesn't help
https://drive.google.com/file/d/1-ZF4QFO-hjr8kbkbPo7dANlSQDdO7Qsw/view?usp=sharing
http://vladtest11.admin.kademi-ci.co/skus/

**Comment by bradmac** [comment]
I've checked and seem that the SKU is created, and after refreshing the page displays correctly.

So looks like a front end or timing issue.

**Comment by anhnt** [comment]
I added small delay before reloading the row so it will fix the issue which doesnt show sku code after update but does show after reloading.

@gonzalon please help me with the issue which doesnt show sku code even after refreshing the page manually

**Comment by bradmac** [comment]
> help me with the issue which doesnt show sku code even after refreshing the page manually

Note that this means the data is not being saved at all.

**Comment by gonzalon** [comment]
@anhnt  this should be working fine atm

**Comment by anhnt** [comment]
yup fixed thanks

**Comment by Uafinder** [comment]
yup, looks fine!
