### ISSUE TITLE
Promotions - can't select organisation

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4693]
http://version1.vlad11promos-vladtest11.kademi-ci.co/rewards/promosqa01/
http://vladtest11.admin.kademi-ci.co/rewards/promosqa01/#entryForm-tab
I have create several orgs and inventories, but list is still empty...
![image](https://user-images.githubusercontent.com/1945230/34359321-b5b1527c-ea5f-11e7-83cc-8809f2133bbb.png)
https://github.com/Kademi/kademi-dev/issues/3995

**Comment by anhnt** [comment]
Fixed

**Comment by Uafinder** [comment]
yup, works fine
