### ISSUE TITLE
Test SendEmail goal node throws NPE if From is blank

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#4694]
If from is blank an NPE is thrown when testing sending the email from a SendEmailGoalNode

**Comment by mkhoudary** [comment]
Done..

@Uafinder to test this.. create a journey with a SendEmail node.. try to test sending from email manager, if it worked then this is resolved.. if failed then still there's a problem.. 

Please note that the from shall be left empty.

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/34383906-4a9fc000-eb21-11e7-9e48-22f6276429be.png)
I've have this message when push send test
However if I use manually select recipient - it's ok.

**Comment by gonzalon** [comment]
@Uafinder locally coudln't reproduce any of this issues... can you confirm? if you can reproduce could you explain me how to do it? or link the account! Thanks!!

**Comment by Uafinder** [comment]
Couldn't reproduce both problems on fresh account
Will keep an eye on it
