### ISSUE TITLE
Organisations search

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4696]
![image](https://user-images.githubusercontent.com/1945230/34382773-ebc7ba62-eb19-11e7-9c59-f7f99b0d7156.png)
When I enter some symbols which are not a part of org name, dropdown list appears.
it looks like it searching in ParentOrg field as well and my parentorg is vlad12dtest and that's why dropdown with results appears.
is it by design?
http://version1.vlad12dpromos-vladtest12d.kademi-ci.co/rewards/promosqa01/

**Comment by bradmac** [comment]
Yeah, i think this is reasonable. Often the parent will represent something the user might want to search by, eg their region, so we want it included

**Comment by Uafinder** [comment]
ok, great!
