### ISSUE TITLE
Error in console while journey page open

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4697]
![image](https://user-images.githubusercontent.com/1945230/34383637-2f8044c2-eb1f-11e7-9b77-1ba3b0c41423.png)
http://vladtest12d.admin.kademi-ci.co/funnels/first-journey/version1/#journeyBuilder-tab
Install journey app from marketplace.

**Comment by bradmac** [comment]
I think that should be ok. I dont think it will affect anything.

**Comment by Uafinder** [comment]
No probs, just FYI
