### ISSUE TITLE
Error when accessing kSurvey step of journey

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4698]
http://vladtest12d.admin.kademi-ci.co/manageUsers/3674680/#funnelsTab-tab
![image](https://user-images.githubusercontent.com/1945230/34384795-2708831a-eb27-11e7-949d-f868f7096ddf.png)
![image](https://user-images.githubusercontent.com/1945230/34384782-19ae96a0-eb27-11e7-9251-8f5c06daf6f3.png)
http://vladtest12d.admin.kademi-ci.co/funnels/first-journey/ksurveySubmittedGoal-91500c

**Comment by bradmac** [comment]
The path was wrong, but not all nodes have a details page so i've removed the link

**Comment by Uafinder** [comment]
Ok, link was removed
