### ISSUE TITLE
KPI's & Data series targets

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#47]
The Sales data app can be used to track KPI's of users. We want to add targets so that when KPI's exceed targets triggers are fired and reward points can be allocated.

A sales data series can be associated with multiple names targets (eg "good", "excellent"), and each target can have a default value (eg 500). Targets can be overridden per user and apply for some date range. Typically this will allow targets to be adapted to be an achievable challenge for each user.

When a sales data series point exceeds a target, only the greatest target matched will be triggered.

Points can also be award based on the values of the sales data. For example, a salesman who sells $50,000 of products might be awarded 50,000 points. Actual points awarded can have factors added or multiplied, and can be transferred to another recipient.

Recipients of points will be either an individual (profile) or company (organisation) based on the points system used in the destination reward.

Sales data can be loaded in bulk or individually by an admin, or individually by a user. 

The sales data series can be configured to require approval, in which case no action is taken when data is uploaded until approved. A user must have the SALES_DATA_APPROVER permission to approve it.

**Comment by bradmac** [comment]
Hey @tuzzmaniandevil, could you please:
 - improve the KPI's tab on the manage KPI page
 - improve the Points tab on the manage data series page

**Comment by tuzzmaniandevil** [comment]
- "improve the KPI's tab on the manage KPI page" - Done
 - "improve the Points tab on the manage data series page" - Done
Still need to add soft delete ability to both items.

**Comment by tuzzmaniandevil** [comment]
"implement CSV import/export for KPI levels" - Done

**Comment by tuzzmaniandevil** [comment]
Added soft delete for KPI's

**Comment by tuzzmaniandevil** [comment]
Added soft delete for Points

**Comment by tuzzmaniandevil** [comment]
@bradmac https://github.com/Kademi/kademi-dev/issues/47#issuecomment-71112309 - Done
