### ISSUE TITLE
New photo crop plugin save button does nothing when you crop large image

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4700]
![2011_skoda_octavia_rs_by_bt_design_003_9118](https://user-images.githubusercontent.com/1945230/34406373-5a983e1a-ebc1-11e7-869b-fcf969e96ba2.jpg)
![clipboard - december 28 2017 10-26 am](https://user-images.githubusercontent.com/1945230/34406399-780b8e7a-ebc1-11e7-8545-44a330c9182a.png)
![clipboard - december 28 2017 10-30 am](https://user-images.githubusercontent.com/1945230/34406401-78453698-ebc1-11e7-99c3-6ded1e6c7ed3.png)
![clipboard - december 28 2017 10-31 am](https://user-images.githubusercontent.com/1945230/34406400-7829f1da-ebc1-11e7-866a-b9a29723c5cd.png)
http://vladtest13.admin.kademi-ci.co/websites/vlad13learn/version1/programs/p1/c1/m1/#details-tab

**Comment by bradmac** [comment]
Here's the error in jenkins:
```
GRIZZLY0205: Post too large
```

@ducdhm can you change this to use a PUT instead of POST? Should be almost the same as what you're doing now

**Comment by bradmac** [comment]
Actually, I've increased the max from 2Mb to 10Mb which should be sufficient.

@ducdhm can you please 
1. Check the file size prior to sending, make sure is less then 10Mb
2. Update the client side to check for a success code. When this happens the request is aborted so there is just an empty response. You should check for status: true or similar in the response, if thats not there then tell the user its failed.

**Comment by Uafinder** [comment]
Up!

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
Yup, it works!
