### ISSUE TITLE
Manage products - issue uploading multiple images with multiple images

### ISSUE THREAD

**Issue by Anton69arb** [Kademi/kademi-dev#4701]
Hello

When I was uploading images to the product images and I add 3 x varients ( i-phone 7, white, black, red)
the code is ip7000 - therefore the varients code is ip7000.1, ip7000.2, ip7000.3 for each colour.

When I add them into the product images - It only adds one image and not all three
it should load all three variants.

http://ant6.admin.kademi-ci.co/products/

**Comment by bradmac** [comment]
Now correctly attaches all uploaded files.

Uploaded 2 files (note naming convention)
![image](https://user-images.githubusercontent.com/826458/35890904-7cf4bd7a-0c06-11e8-93fb-4f6a6d4e0aec.png)

![image](https://user-images.githubusercontent.com/826458/35890896-70e219a6-0c06-11e8-80a5-0009cf71069c.png)

Both files attached to product:
![image](https://user-images.githubusercontent.com/826458/35890918-8df6143e-0c06-11e8-9be5-9c1831650337.png)

**Comment by Uafinder** [comment]
yup, it works
