### ISSUE TITLE
Fresh site home page weird symbols

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4703]
![image](https://user-images.githubusercontent.com/1945230/34432072-d1a3836e-ec7c-11e7-83de-693449c2d4c3.png)
http://vlad14cchat-vladtest14c.kademi-ci.co/
http://vladtest14c.admin.kademi-ci.co/pages/vlad14cchat/version1/
What is the XXXXXXXXX symbols?

**Comment by bradmac** [comment]
Thats just debugging code, which should be removed

**Comment by Uafinder** [comment]
Looks good
