### ISSUE TITLE
points balance component for EDM minor visual issue

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4705]
In the editor pts icon looks ok
![image](https://user-images.githubusercontent.com/1945230/34433810-6e918498-ec8a-11e7-8755-f9e9348494af.png)
But when email arrives it looks next way:
![image](https://user-images.githubusercontent.com/1945230/34433877-e1bf8b4a-ec8a-11e7-9ee7-9ac907e8ad6f.png)

**Comment by bradmac** [comment]
Thats a known issue, and there is no way to resolve it.

**Comment by Uafinder** [comment]
huh... understood
