### ISSUE TITLE
Console error on opening email for editing and more places

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4706]
![image](https://user-images.githubusercontent.com/1945230/34433906-175e13e8-ec8b-11e7-9690-70c954dccd23.png)
1. create email
2. edit it
http://vladtest14c.admin.kademi-ci.co/groupEmails/3741606/#sendInfo-tab

02:02:43 ERROR io.milton.http.http11.GetHandler  - Exception sending content for:/_fields of resource type: co.kademi.server.fields.FieldsResource
02:02:43 java.lang.NullPointerException
02:02:43 	at co.kademi.server.content.AssetTypeManager.getAssetTypes(AssetTypeManager.java:59)
02:02:43 	at io.milton.cloud.server.apps.content.ContentApp.fields(ContentApp.java:840)
02:02:43 	at co.kademi.server.fields.FieldsService.appendFields(FieldsService.java:106)
02:02:43 	at co.kademi.server.fields.FieldsService.getAllFields(FieldsService.java:89)
02:02:43 	at co.kademi.server.fields.FieldsService.getAllFieldBeans(FieldsService.java:121)
02:02:43 	at co.kademi.server.fields.FieldsResource.lambda$getFields$0(FieldsResource.java:55)
02:02:43 	at io.milton.cloud.server.db.utils.LazyValueHolder2.get(LazyValueHolder2.java:39)
02:02:43 	at co.kademi.server.fields.FieldsResource.getFields(FieldsResource.java:54)
02:02:43 	at co.kademi.server.fields.FieldsResource.sendContent(FieldsResource.java:46)
02:02:43 	at io.milton.http.CompressingResponseHandler.respondContent(CompressingResponseHandler.java:116)
02:02:43 	at io.milton.http.AbstractWrappingResponseHandler.respondContent(AbstractWrappingResponseHandler.java:90)
02:02:43 	at io.milton.cloud.server.web.KademiResponseHandler.respondContent(KademiResponseHandler.java:38)
02:02:43 	at io.milton.http.http11.GetHandler.sendContent(GetHandler.java:223)
02:02:43 	at io.milton.http.http11.GetHandler.processExistingResource(GetHandler.java:85)
02:02:43 	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:196)
02:02:43 	at io.milton.http.http11.GetHandler.processResource(GetHandler.java:66)
02:02:43 	at io.milton.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:127)
02:02:43 	at io.milton.http.http11.GetHandler.process(GetHandler.java:60)
02:02:43 	at io.milton.http.StandardFilter.process(StandardFilter.java:50)
02:02:43 	at io.milton.http.FilterChain.process(FilterChain.java:46)
02:02:43 	at co.kademi.server.subscription.KademiSubscriptionFilter.process(KademiSubscriptionFilter.java:45)
02:02:43 	at io.milton.http.FilterChain.process(FilterChain.java:46)
02:02:43 	at co.kademi.server.idp.IDPFilter.process(IDPFilter.java:41)
02:02:43 	at io.milton.http.FilterChain.process(FilterChain.java:46)
02:02:43 	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter$1.execute(MiltonOpenSessionInViewFilter.java:41)
02:02:43 	at io.milton.context.RootContext.execute(RootContext.java:90)
02:02:43 	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter.process(MiltonOpenSessionInViewFilter.java:34)
02:02:43 	at io.milton.http.FilterChain.process(FilterChain.java:46)
02:02:43 	at io.milton.http.HttpManager.process(HttpManager.java:158)
02:02:43 	at co.kademi.server.Kademi$1.service(Kademi.java:191)
02:02:43 	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
02:02:43 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
02:02:43 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
02:02:43 	at java.lang.Thread.run(Thread.java:748)
02:02:43 ERROR io.milton.http.StandardFilter  - exception sending content
02:02:43 java.lang.RuntimeException: java.lang.NullPointerException
02:02:43 	at io.milton.http.http11.GetHandler.sendContent(GetHandler.java:233)
02:02:43 	at io.milton.http.http11.GetHandler.processExistingResource(GetHandler.java:85)
02:02:43 	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:196)
02:02:43 	at io.milton.http.http11.GetHandler.processResource(GetHandler.java:66)
02:02:43 	at io.milton.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:127)
02:02:43 	at io.milton.http.http11.GetHandler.process(GetHandler.java:60)
02:02:43 	at io.milton.http.StandardFilter.process(StandardFilter.java:50)
02:02:43 	at io.milton.http.FilterChain.process(FilterChain.java:46)
02:02:43 	at co.kademi.server.subscription.KademiSubscriptionFilter.process(KademiSubscriptionFilter.java:45)
02:02:43 	at io.milton.http.FilterChain.process(FilterChain.java:46)
02:02:43 	at co.kademi.server.idp.IDPFilter.process(IDPFilter.java:41)
02:02:43 	at io.milton.http.FilterChain.process(FilterChain.java:46)
02:02:43 	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter$1.execute(MiltonOpenSessionInViewFilter.java:41)
02:02:43 	at io.milton.context.RootContext.execute(RootContext.java:90)
02:02:43 	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter.process(MiltonOpenSessionInViewFilter.java:34)
02:02:43 	at io.milton.http.FilterChain.process(FilterChain.java:46)
02:02:43 	at io.milton.http.HttpManager.process(HttpManager.java:158)
02:02:43 	at co.kademi.server.Kademi$1.service(Kademi.java:191)
02:02:43 	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
02:02:43 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
02:02:43 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
02:02:43 	at java.lang.Thread.run(Thread.java:748)
02:02:43 Caused by: java.lang.NullPointerException
02:02:43 	at co.kademi.server.content.AssetTypeManager.getAssetTypes(AssetTypeManager.java:59)
02:02:43 	at io.milton.cloud.server.apps.content.ContentApp.fields(ContentApp.java:840)
02:02:43 	at co.kademi.server.fields.FieldsService.appendFields(FieldsService.java:106)
02:02:43 	at co.kademi.server.fields.FieldsService.getAllFields(FieldsService.java:89)
02:02:43 	at co.kademi.server.fields.FieldsService.getAllFieldBeans(FieldsService.java:121)
02:02:43 	at co.kademi.server.fields.FieldsResource.lambda$getFields$0(FieldsResource.java:55)
02:02:43 	at io.milton.cloud.server.db.utils.LazyValueHolder2.get(LazyValueHolder2.java:39)
02:02:43 	at co.kademi.server.fields.FieldsResource.getFields(FieldsResource.java:54)
02:02:43 	at co.kademi.server.fields.FieldsResource.sendContent(FieldsResource.java:46)
02:02:43 	at io.milton.http.CompressingResponseHandler.respondContent(CompressingResponseHandler.java:116)
02:02:43 	at io.milton.http.AbstractWrappingResponseHandler.respondContent(AbstractWrappingResponseHandler.java:90)
02:02:43 	at io.milton.cloud.server.web.KademiResponseHandler.respondContent(KademiResponseHandler.java:38)
02:02:43 	at io.milton.http.http11.GetHandler.sendContent(GetHandler.java:223)
02:02:43 	... 21 more

**Comment by bradmac** [comment]
That error appears to be fixed now

**Comment by Uafinder** [comment]
looks good for me
