### ISSUE TITLE
Send email journey block cause error on adding and saving

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4708]
![image](https://user-images.githubusercontent.com/1945230/34439107-4f6e0576-ecb4-11e7-9c24-5c1140500c46.png)
error on adding
![image](https://user-images.githubusercontent.com/1945230/34439131-6c205638-ecb4-11e7-9370-0b93bf7d728c.png)
error on saving
http://vladtest15.admin.kademi-ci.co/funnels/first-journey/version1/#journeyBuilder-tab

**Comment by bradmac** [comment]
This usually happens when the journey is invalid for some reason.

**Comment by bradmac** [comment]
```
ModuleProgressAction from String value (""): value not one of declared Enum instance names: [MODULE_SAVED, EXPIRED, MODULE_LANGUISHING, SUBMITTED, MODULE_COMPLETE, MODULE_STARTED, RENEWAL]
```

**Comment by bradmac** [comment]
Same issue as here - https://github.com/Kademi/kademi-dev/issues/4714

**Comment by Uafinder** [comment]
Yup
Possible choices for Module progress should be either dropdown or described in help page.
