### ISSUE TITLE
KMediaLibrary: Improve assets page UI

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4710]
Extends - https://github.com/Kademi/kademi-dev/issues/4434
- Improve upload UI, including progress
- use timeago for dates
- anythign else needed for good UX

Eg URL - http://localhost:8080/asset-manager/

![image](https://user-images.githubusercontent.com/826458/34473903-3e7d0dc6-efdd-11e7-9a49-0d21a612b3cc.png)

**Comment by ducdhm** [comment]
Done!

**Comment by Uafinder** [comment]
1. Date/time is not using a timezone.
![image](https://user-images.githubusercontent.com/1945230/34601834-61ff6b24-f206-11e7-914c-08b5d18ba64d.png)

2. Delete file is not possible
![image](https://user-images.githubusercontent.com/1945230/34601846-6be06dbe-f206-11e7-9ac0-7f89ecd98342.png)

3. uploading progress in not visible (just a simple indicator)
![image](https://user-images.githubusercontent.com/1945230/34601937-9320fc54-f206-11e7-8bd6-2076270b8442.png)

4. GUI for content query bad
![image](https://user-images.githubusercontent.com/1945230/34602017-e687ea6a-f206-11e7-800d-4aa8b499372f.png)

5. Add button cause a dropdown which are empty
![image](https://user-images.githubusercontent.com/1945230/34602040-0422e5d4-f207-11e7-9b8c-d1a3028b9096.png)

6. No possibility to download content

7. Error when adding something to asset
![image](https://user-images.githubusercontent.com/1945230/34602123-50aca7a0-f207-11e7-94d3-e62a1cb8340b.png)

8. Opening audio or text file cause this kind of error
![image](https://user-images.githubusercontent.com/1945230/34602225-a5ddf012-f207-11e7-96d5-4b7e85ac9924.png)

And pls explain "Content query" feature...

**Comment by bradmac** [comment]
> GUI for content query bad

Dont worry about this, its covered in a different issue and is still in progress

**Comment by bradmac** [comment]
> Add button cause a dropdown which are empty

That is correct if there are not asset types created. Go to the /content/ page to create asset types

**Comment by bradmac** [comment]
> Error when adding something to asset

This is for a content query asset which is not ready for test yet. Please just test with images, videos

**Comment by bradmac** [comment]
> Opening audio or text file cause this kind of error

Does not support audio and text files yet

**Comment by ducdhm** [comment]
> Delete file is not possible
I send data `toDelete` to server but it doesnt work

> uploading progress in not visible (just a simple indicator)
Do you think we need percentage for uploading?

**Comment by bradmac** [comment]
> I send data toDelete to server but it doesnt work

Fixed

**Comment by bradmac** [comment]
> Do you think we need percentage for uploading?

@ducdhm the progress bar should show the progress of the upload. Ie if half of the file has been uploaded the progress bar should be half filled in. This is just normal progress bar stuff.

You can do this with the onProgress callback in jquery.forms

**Comment by ducdhm** [comment]
Done!

**Comment by Uafinder** [comment]
yup, looks good
so, other things are todo
