### ISSUE TITLE
Changing variant doesnt change item url to add to cart

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#4711]
![image](https://user-images.githubusercontent.com/735555/34474299-cc1c8efa-efaf-11e7-8dc3-bf52f8de8b12.png)

**Comment by anhnt** [comment]
test user: http://viri.admin.kademi.com.au/manageUsers/95192325

**Comment by ducdhm** [comment]
Please test on QA

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/34477455-06bdfad8-efa3-11e7-91ff-06e25c319ba9.png)
No change for me.
I've open a product details, change variant, and inspect "add to cart" button. It seems look to same link.
http://vlad16rewards_vladtest16.kademi-ci.co/vlad16rewards-store/elec/3806598
http://vladtest16.admin.kademi-ci.co/products/3806598/#panel_details-tab

**Comment by bradmac** [comment]
Doesnt work.

**Comment by bradmac** [comment]
@Uafinder to test this, just confirm that you are able to add to your cart when using SKU's (ie with inventory control enabled)

**Comment by Uafinder** [comment]
Works as expected... variants are possible to add to cart, base product is not...
so, passed
