### ISSUE TITLE
Video playback issue on preview - keditor

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4712]
![image](https://user-images.githubusercontent.com/1945230/34478350-1a38e022-efa9-11e7-8ebc-3df9b4292250.png)
1. Create a page
2. Adding a video component
3. Change video button
4. upload another video
5. Click ok
6. Click play on video, it will be invisible and will give an error.
http://vladtest16.admin.kademi-ci.co/pages/vlad16rewards/version1/
http://vladtest16.admin.kademi-ci.co/pages/vlad16rewards/version1/?contenteditor=page3.html

**Comment by ducdhm** [comment]
Fixed in other issue

**Comment by Uafinder** [comment]
Still there,
fresh account
![image](https://user-images.githubusercontent.com/1945230/35157063-82692fb8-fd3b-11e7-93d7-f5aa8deb6d7e.png)
http://vladtest23d.admin.kademi-ci.co/pages/vlad23dsales/version1/
I've create a page, upload a video there and press ok
Video begin to play without visualization and then error in console appears...

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
yup, looks good
