### ISSUE TITLE
Module progress node with some mistake data blocks other nodes options tab

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4714]
![image](https://user-images.githubusercontent.com/1945230/34487884-e6cab126-efde-11e7-8256-66c24da27de8.png)
1. Add begin node
2. Add module progress node
3. Add some program name for example, or module name
4. refresh
5. try to edit begin node and you will see an error.
http://vladtest15.admin.kademi-ci.co/funnels/first-journey/version1/#journeyBuilder-tab

**Comment by bradmac** [comment]
We should create a settings file for the begin node. But there arent any settings, so this should not have any functional impact.

**Comment by Uafinder** [comment]
Disagree,
it also impact on email nodes as well and all options there are ignored
http://vladtest15.admin.kademi-ci.co/funnels/first-journey/version1/#journeyBuilder-tab
![image](https://user-images.githubusercontent.com/1945230/34520090-e804294e-f08f-11e7-9328-71f501d316e4.png)

**Comment by bradmac** [comment]
> it also impact on email nodes as well and all options there are ignored

Thats a different issue. It looks like the journey had become invalid for some reason.

**Comment by bradmac** [comment]
The module progress action field was empty and this was causing the journey to be invalid, which meant that the journey couldnt be parsed so no nodes were available.

I set it to this: MODULE_STARTED

And is ok now

**Comment by Uafinder** [comment]
Yeah, simply regular user couldn't know the correct values for module status
