### ISSUE TITLE
Content queries

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4715]
A common use case is for a piece of content to be chosen for display based on what groups the viewing user is in (ie customer segments)

We can currently do this with container visibility rules, but this is difficult to manage for larger numbers of segments

- Create an asset type which is a content query, ie which allows the user to specify rules to select another piece of content
- Create components to add to web pages and EDM's to use a selected content query. This could either select text content (ie html) or an image or video.

**Comment by bradmac** [comment]
Fixed

**Comment by bradmac** [comment]
Currently the manage page for an asset query looks like this. We want to change this so it uses the same rule builder UI as for dynamic groups.

Current:
![image](https://user-images.githubusercontent.com/826458/34694353-a79b6354-f52b-11e7-8692-a60a1ee8061d.png)

Change to use rules builder like dynamic groups:
![image](https://user-images.githubusercontent.com/826458/34694380-c33f31e4-f52b-11e7-80ab-2fc6e165045e.png)

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/34723847-9aa1266a-f554-11e7-9476-97e997904214.png)
1. Save cause an error
2. Is old target fields still needed?
http://vladtest20b.admin.kademi-ci.co/asset-manager/dbe0dea7-c7de-415c-80ad-38e9cdc103dd

**Comment by bradmac** [comment]
The target field is needed for selecting a single asset. But we need to extend this to allow selecting an asset type.

The query builder is to decide whether a rule is matched, if it is matched then the asset(s) returned comes from either the target asset (single item) or the target asset type (multiple items)

**Comment by bradmac** [comment]
@ducdhm can you see why we're getting 2 inputs for the target asset?

**Comment by bradmac** [comment]
@ducdhm please update manageQueryAsset.html to allow selecting either input?

![image](https://user-images.githubusercontent.com/826458/34806664-397879c4-f6e9-11e7-9d84-b0835d959037.png)

**Comment by bradmac** [comment]
Need to allow selecting a target content type

**Comment by ducdhm** [comment]
New UI:
![newui](https://user-images.githubusercontent.com/1289631/34859188-3d356e20-f787-11e7-9d3b-3b21883678eb.png)

**Comment by tuzzmaniandevil** [comment]
:+1:

**Comment by bradmac** [comment]
Can now access content resources through front end

**Comment by bradmac** [comment]
OK, just need to add a component to display text assets from queries now.

**Comment by bradmac** [comment]
Done
