### ISSUE TITLE
Org selector is not showing

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#4717]
Check this profile http://anhtest11.admin.kademi-ci.co/manageUsers/3800869/#summary-tab who connected to 2 orgs

Org selector is put on index.html http://version1.w1-anhtest11.kademi-ci.co/contenteditor?fileName=index.html

Login as that user to see no org selector showing

**Comment by mkhoudary** [comment]
Hey @anhnt I checked this and it looks like the behavior of the component is to get the children of an org assigned to a user.. I will chat with Brad about this..

**Comment by mkhoudary** [comment]
Fixed

**Comment by Uafinder** [comment]
Yup, it works...
tested on the fresh account and on the Anh's account...
