### ISSUE TITLE
Minor visual issue on user leads tab (padding different for 1st and 2nd lead)

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4720]
![image](https://user-images.githubusercontent.com/1945230/34518768-a5d957de-f089-11e7-80f5-6937f64f8929.png)
http://vladtest15.admin.kademi-ci.co/manageUsers/3831503/#funnelsTab-tab

**Comment by bradmac** [comment]
Thats because they're tables, the alignment varies to fit the content. This is acceptable.
