### ISSUE TITLE
Calendar doesn't appear when click on date input

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#4721]
Here : http://scenario.admin.kademi-ci.co/proposals/3869905 
In "Add new Quote" modal , when I click on "Expiry Dates input" , the calendar shall appear

![capture2](https://user-images.githubusercontent.com/26510030/34522479-7cdf0808-f09b-11e7-8718-0a34d139eba3.PNG)

![capture1](https://user-images.githubusercontent.com/26510030/34522414-2a8425ac-f09b-11e7-85e5-a4599cca6577.PNG)

**Comment by GeoBlaso** [comment]
Can I contribute?

**Comment by bradmac** [comment]
Hi @GeoBlaso thanks for the offer, but kademi core is not open for contributions at the moment (hopefully we'll have a developer edition you can run locally in the near future)

But our drag and drop editor is an open project, and is pretty cool!

https://github.com/Kademi/keditor

**Comment by AlaaKhalaf94** [comment]
the problem still exists : http://testaccount013.admin.kademi-ci.co/proposals/16002206

![untitled01](https://user-images.githubusercontent.com/26510030/39301840-45dc423c-4959-11e8-9fc4-e6be3981e220.png)

**Comment by anhnt** [comment]
Ok i was seeing wrong page due to original href is expired

**Comment by AlaaKhalaf94** [comment]
cool it has now appeared, but it needs a simple adjustment in appearance
http://testaccount013.admin.kademi-ci.co/proposals/16002206

![untitled01](https://user-images.githubusercontent.com/26510030/39404131-22942522-4b95-11e8-9cbd-bb91c3dd5880.png)

![untitled02](https://user-images.githubusercontent.com/26510030/39404132-22b5df0a-4b95-11e8-991e-f7a97bd23e6c.png)
