### ISSUE TITLE
Organisation selector doesn't appears via menu component

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4723]
![image](https://user-images.githubusercontent.com/1945230/34522957-ffb689b6-f09d-11e7-8fbe-eef420bb312f.png)
![image](https://user-images.githubusercontent.com/1945230/34522987-2850a6ae-f09e-11e7-83e5-3d1314c57b6a.png)
http://vladtest15.admin.kademi-ci.co/websites/vladsales01/version1/#panel_apps-tab

**Comment by bradmac** [comment]
Note that this will only appear if the user has multiple org memberships

**Comment by Uafinder** [comment]
Yeah, that's was a problem...
