### ISSUE TITLE
Manage email send node (edit via text editor)  

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4724]
![image](https://user-images.githubusercontent.com/1945230/34523189-05713242-f09f-11e7-8ec7-8837e4cedcf4.png)

![image](https://user-images.githubusercontent.com/1945230/34523180-ff52a60c-f09e-11e7-98c3-4f10037913a6.png)

http://vladtest17.admin.kademi-ci.co/funnels/journey2/version1/emailAction-7cd7fc/#message-tab

**Comment by bradmac** [comment]
Fixed

**Comment by Uafinder** [comment]
looks good!
