### ISSUE TITLE
KPI Level threshold "Find from series" need fields criteria

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#4725]
When we want to read level target from another series there's no possibility that we filter the target data series with filter parameters, so basically we need to have 5 fields to set while setting a level.

**Comment by mkhoudary** [comment]
Done..

![image](https://user-images.githubusercontent.com/3704174/34532356-8ec8e084-f0be-11e7-91f8-65d7d1e0db55.png)

@Uafinder to test this, please create two data series, one populate with data for target and populate custom fields, then populate the other and user the data fields when you create a level to filter by some field value

**Comment by Uafinder** [comment]
Works fine!
