### ISSUE TITLE
Asset selection jquery plugin

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4728]
Please create a jquery plugin to make a text input into an asset selection UI for use with forms. The text input should still be present in the form and submit the selected asset uniqueid property.

This asset selection should allow searching for assets, optionally with an asset type specified on the text input as a data attribute

Here is the typical html for an asset field:
```
<input name="thumb" class="form-control select-asset select-asset-image" value="76bb8995-fccf-447b-8620-6c83d58d6a43" type="text">
```

Here is an example type to work with, which should be added to - http://localhost:8080/repositories/contentTypes/version1/texteditor?fileName=types.xml
```
<types>
  <source>/myController.js</source>
  <type class="contentType">
    <name>pet</name>
    <views>
      <mvelHtmlTemplate>
        <template>theme/petTemplate</template>
        <paramName>otherView</paramName>
        <mvelTemplate>&lt;h1&gt;@{asset.name}&lt;/h1&gt;</mvelTemplate>
      </mvelHtmlTemplate>
    </views>
    <defaultView class="pageHtmlTemplate">
      <pagePath>/showpet.html</pagePath>
    </defaultView>
    <fields>
      <typedField>
        <name>petName</name>
        <text>petName</text>
        <title>Pet name</title>
        <type>text</type>
        <required>true</required>
      </typedField>
      <typedField>
        <name>species</name>
        <text>species</text>
        <title>Species</title>
        <type>text</type>
        <required>true</required>
      </typedField>
      <typedField>
        <name>birthDate</name>
        <text>birthDate</text>
        <title>Birth date</title>
        <type>date</type>
        <required>true</required>
      </typedField>
      <derived>
        <name>age</name>
        <mvelExpr>formatter.durationYears(birthDate, formatter.now)</mvelExpr>
      </derived>
      <relation>
        <name>thumb</name>
        <text>Pets photo</text>
        <title>Pets photo</title>
        <contentType>image</contentType>
        <required>true</required>
        <allowMany>true</allowMany>
      </relation>
      <relation>
        <name>funnyVideo</name>
        <text>A video showing your pet doing something funny</text>
        <title>Funny video</title>
        <contentType>video</contentType>
        <required>true</required>
        <allowMany>false</allowMany>
      </relation>
    </fields>
  </type>
</types>
```

Then you can create a content item of type "pet"

http://localhost:8080/asset-manager/

![image](https://user-images.githubusercontent.com/826458/34550087-e5876666-f172-11e7-8f97-069c9aa30d7e.png)

Then click the button to create a content item:
http://localhost:8080/asset-manager/new?type=pet

![image](https://user-images.githubusercontent.com/826458/34550105-04fa2b8c-f173-11e7-81d5-24dd7253c608.png)

Make the 2 fields shown become asset selection fields
  
If you need to change the HTML, see RelationFieldDef.java

```    
public String renderInput(ContentItemAsset asset, Object value) {
        String html = "";
        if (value instanceof List) {
            List list = (List) value;
            if (list.isEmpty()) {
                html += "<input type=\"text\" name=\"" + getName() + "\" class=\"form-control select-asset select-asset-" + getContentType() + "\" value=\"\" />";
            } else {
                for (Object val : list) {
                    String s = toAssetId(val);
                    html += "<input type=\"text\" name=\"" + getName() + "\" class=\"form-control select-asset select-asset-" + getContentType() + "\" value=\"" + s + "\" />";
                }
            }
        } else {
            String s = toAssetId(value);
            html = "<input type=\"text\" name=\"" + getName() + "\" class=\"form-control select-asset select-asset-" + getContentType() + "\" value=\"" + s + "\" />";
        }
        return html;
    }
```

**Comment by ducdhm** [comment]
@bradmac Plugin is ready. I need filter `type` for searching asset type.

**Comment by bradmac** [comment]
OK, thats added now

It does a prefix search on format, which works for image and video, but can also be used for other content types

**Comment by bradmac** [comment]
I've integrated with the edit page as well as the new item page (and later will merge the 2 into one template, i think)

**Comment by bradmac** [comment]
@ducdhm can you extend this a bit more. 

Can you please allow for uploading a new image or video from this control? This should have cropping etc for images.

**Comment by bradmac** [comment]
@ducdhm also, please move the type detection inside the plugin. Its good to have an option to specify the type, but usually the assetFinder plugin should determine the type from classes on the input

Also, please make this support content types with type=content, class=select-asset-content, and have a data attribute for the asset type

Example
```
<input name="pet1" class="form-control select-asset select-asset-content" data-asset-type="pet" value="" type="text">
```

This should produce an ajax query like:
http://localhost:8080/assets/?q=a&type=content&assetType=pet

**Comment by bradmac** [comment]
Currently, the value of the input is blanked out when rendered:

![image](https://user-images.githubusercontent.com/826458/34693942-40ac92b8-f52a-11e7-9911-377f772a7b86.png)

**Comment by bradmac** [comment]
> Currently, the value of the input is blanked out when rendered.

Done

![image](https://user-images.githubusercontent.com/826458/34713857-65e00ba2-f58c-11e7-859a-5b794f44b88b.png)

**Comment by bradmac** [comment]
Not correctly filtering by content type, but good enough for now
