### ISSUE TITLE
Additional data series field bug when create a record manually

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4732]
![image](https://user-images.githubusercontent.com/1945230/34560714-9f50fa9a-f14f-11e7-9db7-3ce7c6a404cf.png)
But when you create data series record manually (via create record button) this field looks like a dropdown list.
![image](https://user-images.githubusercontent.com/1945230/34560754-ce7cb7be-f14f-11e7-8c0b-dafde55ceb15.png)
http://vladtest18.admin.kademi-ci.co/sales/salesqa01/#history-tab

and also it shows that that's a required field but it's not!
![image](https://user-images.githubusercontent.com/1945230/34560873-552e3b5c-f150-11e7-9d95-2531a3892275.png)

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
Yup, looks good
