### ISSUE TITLE
Leaderboard starts from #0, should be #1

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4733]
![image](https://user-images.githubusercontent.com/1945230/34562170-e6defa28-f155-11e7-8fb3-e29f0a46bf3c.png)
http://vladtest18.admin.kademi-ci.co/sales/salesqa01/kpis/kpiqa01/#general-tab

**Comment by mrdadah** [comment]
Fixed

**Comment by Uafinder** [comment]
Yup, looks fine!
