### ISSUE TITLE
Install KMediaLibrary app via MarketPlace cause menu error

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4735]
1. Create a website
2. Install app there via MarketPlace
3. Go to left menu
![image](https://user-images.githubusercontent.com/1945230/34563722-7b3e9470-f15c-11e7-9b80-1074eda761ec.png)
![image](https://user-images.githubusercontent.com/1945230/34563730-864ba63c-f15c-11e7-8022-75eaac82eb8c.png)
http://vladtest18.admin.kademi-ci.co/mediaLibrary/

**Comment by bradmac** [comment]
We're no longer using a seperate app for this, so i've deleted it from source control.

You will need to remove it from the CI marketplace manually though

**Comment by Uafinder** [comment]
How can I do that?

**Comment by bradmac** [comment]
Yep

**Comment by Uafinder** [comment]
Yeah, looks fine.
App removed from CI rootorg.
