### ISSUE TITLE
Downloading added files in blogs , is not available

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#4736]
Here : http://scenario.admin.kademi-ci.co/blogs/blogname/articletitle/#files-tab I've added two files

In preview blog , downloading files is not available, it opens it as a text file in a new tab

![capture1](https://user-images.githubusercontent.com/26510030/34563764-a003b8c6-f15c-11e7-91b0-6cbd6050c24f.PNG)

**Comment by bradmac** [comment]
@mrdadah please add the download attribute to force files to be downloaded rather then opened

https://stackoverflow.com/questions/2793751/how-can-i-create-download-link-in-html#16316830

**Comment by mrdadah** [comment]
Done

**Comment by AlaaKhalaf94** [comment]
passed
