### ISSUE TITLE
Error in console while accessing Points tab in User

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4738]
![image](https://user-images.githubusercontent.com/1945230/34571545-78bd4230-f177-11e7-929d-fe37f93a3999.png)
http://vladtest18.admin.kademi-ci.co/manageUsers/3892461/#pointsBucketTab-tab

**Comment by bradmac** [comment]
Looks like we're using the same ID in the points panels

**Comment by anhnt** [comment]
Fixed, please update kademi-dev to test

**Comment by anhnt** [comment]
Also fixed duplicated orgId inputs

**Comment by Uafinder** [comment]
looks good
