### ISSUE TITLE
Error while products upload

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4739]
![image](https://user-images.githubusercontent.com/1945230/34605796-8e9b49e6-f215-11e7-89a2-ff79a154cb22.png)
![image](https://user-images.githubusercontent.com/1945230/34605806-96e1a276-f215-11e7-918c-fa9ed232096f.png)
http://mysolution.admin.kademi-ci.co/tableUploaders/productsUploader

**Comment by bradmac** [comment]
@Uafinder can you reliably reproduce this?

**Comment by Uafinder** [comment]
Easily
![image](https://user-images.githubusercontent.com/1945230/34710238-2696c8a0-f523-11e7-9c7d-f1bbaf7013bf.png)
![image](https://user-images.githubusercontent.com/1945230/34710264-3e789ad4-f523-11e7-898e-6e144a183bc2.png)
http://vladtest20.admin.kademi-ci.co/tableUploaders/productsUploader
![image](https://user-images.githubusercontent.com/1945230/34710273-463961d6-f523-11e7-8654-0aa63e3a3013.png)

**Comment by bradmac** [comment]
Cannot reproduce

![image](https://user-images.githubusercontent.com/826458/34742655-c9127192-f5eb-11e7-88b6-3688131a5993.png)

**Comment by bradmac** [comment]
I've tried with 500 records and 2k records, seems to work fine.

**Comment by bradmac** [comment]
OK, so i've discovered this only occurs with new accounts, and it only happens once.

**Comment by bradmac** [comment]
The problem occurs when the products repository is auto-created in the import process.

To resolve it, I've added an initialisation process to the products app to auto-create the products repository, so it will already exist when the uploader runs.

Note that this wont apply to existing accounts which already have the products app enabled.

**Comment by Uafinder** [comment]
ok, understood
looks better
