### ISSUE TITLE
salesDataclaimer app appears twice in marketPlace

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4741]
![image](https://user-images.githubusercontent.com/1945230/34613377-3b37e040-f236-11e7-9a66-f263f0bd4f95.png)
http://mysolution.admin.kademi-ci.co/marketPlace?websiteBranch=version1&websiteName=resellers&type=app#browse-tab

**Comment by bradmac** [comment]
The correct one is salesDataClaimer (lower case first letter)

Please remove the other from CI marketplace, it has already been removed from source code

**Comment by Uafinder** [comment]
Yup, I've un-publish it in rootorg CI...

**Comment by Uafinder** [comment]
I've in-publish it several times, but after server reboot it appears again :(

**Comment by bradmac** [comment]
@tuzzmaniandevil please check out why it keeps coming back

**Comment by tuzzmaniandevil** [comment]
"SalesDataClaimer" was still in kademi-dev

**Comment by Uafinder** [comment]
Thanks, looks fine now
