### ISSUE TITLE
Manage content type page

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4743]
- Allow adding and removing field definitions for the 4 types - typed field, relation, derived field and simple field
- Allow adding and removing views, eg template page view
- Do something about controllers

Have an indicator structure used for both views and controllers. Eg a view or a controller could be indicated by the presence of a request parameter, a content type or method, and these can be combined with booleans

**Comment by bradmac** [comment]
done relation and typed fields

**Comment by bradmac** [comment]
@tuzzmaniandevil please add support for adding derived and simple fields

**Comment by bradmac** [comment]
Added ability to create the 4 field types

**Comment by bradmac** [comment]
@tuzzmaniandevil please add the ability to remove views and fields. And please add ability to configure the default view.

**Comment by bradmac** [comment]
@ducdhm there is an ajax service to remove fields now. Send a param called "toDelete" with the names of the fields to remove, suitable for use with checkboxes

**Comment by bradmac** [comment]
And I've added similar services for views (toDeleteViews) and permissions (toDeletePermissions)

**Comment by ducdhm** [comment]
Done!
