### ISSUE TITLE
add HTML alt tags for screen readers through content editor

### ISSUE THREAD

**Issue by Anton69arb** [Kademi/kademi-dev#4744]
Hey, The  HTML alt tags for screen readers through content editor used to be working and visible, please could we add it to the image component

http://ant16.admin.kademi-ci.co/websites/ant16/version1/#panel_apps-tab

![screenshot-version1 ant16-ant16 kademi-ci co-2018-01-08-12-45-17-805](https://user-images.githubusercontent.com/32444328/34655719-3a1c9e6e-f473-11e7-85cc-196002cc4cda.png)

**Comment by ducdhm** [comment]
Done!

**Comment by Uafinder** [comment]
need more info pls

**Comment by Anton69arb** [comment]
so basically they need to add tags to there images,

**Comment by Anton69arb** [comment]
Seem to be a problem, the settings icon for the component is not available and the picture component is not on the components list to add it to the container - see picture for example

http://ant16.admin.kademi-ci.co/pages/ant16/version1/

![1](https://user-images.githubusercontent.com/32444328/35132453-4a4a1b5c-fd30-11e7-8c95-1f67d0184ee8.png)

thank you

**Comment by ducdhm** [comment]
@Uafinder I added Alt text option for image component. You just check image in view has alt text like option or not.

@Anton69arb I have fixed, so you can see option for photo component. And you can type `photo` in search box to see photo component. The reason why photo component is not at top place is `I moved photo component from static to dynamic`

**Comment by Uafinder** [comment]
Alt text options is not saving for the image
1. Create a page
2. edit
3. Add image component
4. Edit it
5. Add some alt text
6. Push save
7. Close edit
8. Open edit again
9. There is no alt text in the field

Also i've check frontend - there are no signs of alt text attribute.
![image](https://user-images.githubusercontent.com/1945230/35218963-45356e0a-ff79-11e7-9422-269e81bad6df.png)

http://vladtest25.admin.kademi-ci.co/pages/vlad25learn/version1/

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
Yup, looks fine now
