### ISSUE TITLE
Changing reward-store code results all reward products pages broken

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4746]
For example, you have 30 products in reward store and you need to change reward store code.
When you change it, this will cause all products detail pages to be broken, because links will not update. Only the removing and adding back a product to a store will cause link regenerating.
![image](https://user-images.githubusercontent.com/1945230/34670148-c042e2fa-f47d-11e7-84d3-c58dc47aa311.png)
![image](https://user-images.githubusercontent.com/1945230/34670217-03d18620-f47e-11e7-9646-af6441130737.png)
![image](https://user-images.githubusercontent.com/1945230/34670243-1e2a142e-f47e-11e7-8deb-21b854fb4036.png)
http://mysolution.admin.kademi-ci.co/manageUsers/

**Comment by bradmac** [comment]
This is expected. The solution is to reindex the reward store.

**Comment by Uafinder** [comment]
yup, re-index helps!
