### ISSUE TITLE
Auction doesn't appears on the frontend

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4748]
http://mysolution.admin.kademi-ci.co/manageUsers/3964135/#summary-tab
http://resellers-mysolution.kademi-ci.co/auctions/
Can't understand why auction doesn't appears for me at the frontend. I'm logging with the user specified upper.

**Comment by tuzzmaniandevil** [comment]
Because a points bucket was set on the Auction, The user needs access to that points bucket. Adding the Dealers group to the points buckets fixed the issue

**Comment by bradmac** [comment]
@tuzzmaniandevil ok lets add an installation script to set everything up so the logged in user can immediately click through to the auctions page and see everything working.

this should use the same default points bucket and participant group as reward stores.

**Comment by bradmac** [comment]
Note that KAuctions depends on KRewardStore (or should if it doesnt) so much of that configuration should already be there.

**Comment by Uafinder** [comment]
Ok, understood...
script looks good
