### ISSUE TITLE
salesDataClaim entering products dropdown always empty

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4749]
![image](https://user-images.githubusercontent.com/1945230/34673564-531ec12c-f48b-11e7-8438-6606f38a1984.png)
http://mysolution.admin.kademi-ci.co/
http://resellers-mysolution.kademi-ci.co/data-claims.html

**Comment by tuzzmaniandevil** [comment]
The sales data claim app uses Product Sku's, There were no Sku's setup. After I added one the search worked

**Comment by bradmac** [comment]
@Uafinder please let me know if you want to discuss.

**Comment by Uafinder** [comment]
It simple not obvious for configuring, just need to know that fact :)
