### ISSUE TITLE
Journey email node sending bug (specified To address)

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4750]
![image](https://user-images.githubusercontent.com/1945230/34673994-df40dc2a-f48c-11e7-9190-58d1e2478128.png)
When you fill up field "to address" and enter no values to upper two fields (Reply to address and Email from address) email will not fire.
http://mysolution.admin.kademi-ci.co/funnels/claims/version1/emailAction-19557d/#summary-tab

**Comment by gonzalon** [comment]
Can't reproduce:
http://mysolution.admin.kademi-ci.co/funnels/claims/version1/emailAction-19557d/#summary-tab

![image](https://user-images.githubusercontent.com/2773216/36006646-0dbc712a-0da3-11e8-819b-c92b4db82229.png)

**Comment by Uafinder** [comment]
Yup, it works... probably was changed something

**Comment by Uafinder** [comment]
Spot it again here
http://vladtest32.admin.kademi-ci.co/funnels/journey2/version1/emailAction-5eeb45/#summary-tab
fresh account
I've tried to create lead by hands and via import. Both not working.

**Comment by bradmac** [comment]
@Uafinder you can see the reason in the logs..
```
15:12:21 INFO  com.fuselms.apps.funnels.FunnelManager  - nodeTransition: Entering node ID=emailAction-5eeb45, Title=null class=class com.fuselms.apps.funnels.SendEmailGoalAction
15:12:21 INFO  io.milton.cloud.server.mail.BatchEmailService  - Generating Reply-To email from: vlad@kademi.co
15:12:21 INFO  io.milton.cloud.server.mail.BatchEmailService  - emailTemplate doens't contain an expression.
15:12:21 INFO  com.fuselms.apps.funnels.SendEmailGoalAction  - Sending email to an address which we do not have a profile for: vlad@kademi.co
```

Kademi will not ever send an email to a profile which is not linked to the sending account.

Please create a profile in the account with the email address you want to send to.

**Comment by Uafinder** [comment]
ok, undestood
