### ISSUE TITLE
salesDataClaimer app in admin and website level

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4751]
The both apps on both levels has an option, called "Data series" where you should specify data series for this claimer. That's not completely obvious.
If one this parameters are not setup correctly, it will generate next error on processing.
![image](https://user-images.githubusercontent.com/1945230/34674836-1acebb88-f490-11e7-9767-3647a0b4f299.png)
http://mysolution.admin.kademi-ci.co/manageSaleDataClaimer/

**Comment by bradmac** [comment]
When the app is installed
- check for a series with a default name of "SalesClaims"
- if it doesnt exist, create it, and create a dashboard alert to say it was created
- use that as the setting

On the manage page
- if no series has been selected, display an alert at the top of the page, with a select box to choose a series. Also provide a link to the data series page so the user can create one if needed
- Add a settings tab to make it easy to see and change the setting

**Comment by ducdhm** [comment]
@bradmac I need a method from SalesDataApp which allows custom app to create new data series

**Comment by bradmac** [comment]
Added this method:
```
public SalesDataSeries createSeries(String name, String title, Group salesByGroup) {
```

**Comment by gonzalon** [comment]
It was working fine but not assigning the name / title to the data series should be working ok now !

**Comment by Uafinder** [comment]
Ok, good for now, will do some checkings in future
