### ISSUE TITLE
Delete claim does nothing

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4752]
![image](https://user-images.githubusercontent.com/1945230/34675926-b71aab3e-f493-11e7-893e-c6c64e1a20ca.png)
http://mysolution.admin.kademi-ci.co/manageSaleDataClaimer/
1 select claim
2 push delete
3 refresh
4 see that claim are still in place

It looks like because of they already approved or rejected. The new claim is deleting successfully. So would be great to add a validation or disable checkboxes as it done on the frontend.

**Comment by gonzalon** [comment]
@Uafinder talked with Brad about disabling it and said it's not necessary in the admin.
Now you should be able to delete any claim without problems.

**Comment by AlaaKhalaf94** [comment]
passed
