### ISSUE TITLE
What about hide old csv uploaders?

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4753]
http://mysolution.admin.kademi-ci.co/organisations/
![image](https://user-images.githubusercontent.com/1945230/34676033-0e5866ac-f494-11e7-9fbc-8f328e310ada.png)

http://mysolution.admin.kademi-ci.co/products/
![image](https://user-images.githubusercontent.com/1945230/34676072-3f60e896-f494-11e7-8065-f244b3e8655c.png)

**Comment by bradmac** [comment]
For product import, i think we need to leave it because Carters still uses it. But move it to the bottom of the list under a seperator with text "Upload CSV (old)"

**Comment by tuzzmaniandevil** [comment]
All done

**Comment by Uafinder** [comment]
Yeah, looks great!
