### ISSUE TITLE
Enter claims frontend date/time bug

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4754]
For example you're entering a claim with date:
![image](https://user-images.githubusercontent.com/1945230/34677227-2559d06c-f498-11e7-9204-2f37033a3236.png)
Push save and then review it, and time will be -11 hours from setup.
![image](https://user-images.githubusercontent.com/1945230/34677281-47bd9b7a-f498-11e7-8c74-2062a06c7200.png)
http://resellers-mysolution.kademi-ci.co/data-claims.html
http://mysolution.admin.kademi-ci.co/edit/
Looks very similar to a bug which was fixed by @tuzzmaniandevil in scheduled emails.
https://github.com/Kademi/kademi-dev/issues/4295

**Comment by gonzalon** [comment]
Should be ok now! Time ATM: 15:17

![image](https://user-images.githubusercontent.com/2773216/35077499-92ffa0ac-fc62-11e7-8ba7-a2d68bfbc510.png)

![image](https://user-images.githubusercontent.com/2773216/35077504-a09a9e56-fc62-11e7-81a7-1d752c32523e.png)

**Comment by AlaaKhalaf94** [comment]
Hi @gonzalon , I see the problem still appear
I create clime with 18/01/2018 0:00 Purchase date

![capture1](https://user-images.githubusercontent.com/26510030/35102217-e39cadc2-fc6a-11e7-9b2f-228b11d21755.PNG)

and it appear on admin with 17\01\2018 13:00 

![capture2](https://user-images.githubusercontent.com/26510030/35102305-36a717dc-fc6b-11e7-8f03-e2eed1d1d057.PNG)

http://mysolution.admin.kademi-ci.co/manageSaleDataClaimer/
http://resellers-mysolution.kademi-ci.co/data-claims.html

**Comment by gonzalon** [comment]
Now it should be fine, both in the frontend and admin. Fixed in 1.1.6

**Comment by Uafinder** [comment]
Yup, looks better at the moment.
