### ISSUE TITLE
Content query list component

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4757]
This should function much the same as a blog article list component, except it shows content items from the asset library

**Comment by bradmac** [comment]
Please update the component to have settings:
- allow selecting a query asset
- similar settings as blog articles

Note that the selected query asset has a property targetAssetType. Load the properties for that type to allow selecting properties for:
- title
- image
- brief

**Comment by bradmac** [comment]
Working now:

![image](https://user-images.githubusercontent.com/826458/34806565-8a8800a6-f6e8-11e7-895d-b0bba4a6fa98.png)

**Comment by bradmac** [comment]
Thats using this component:
```
<section data-type="component-assetQueryList" data-query="6b71000d-d27c-431f-bb23-96e4fc45ae1b">
    <div data-dynamic-href="_components/assetQueryList" id="keditor-dynamic-element-1515628677698"></div>
</section>
```

**Comment by bradmac** [comment]
This is using hardcoded settings:
```
<!-- todo: these should come from settings -->
#set( $thumbProp = "thumb" )
#set( $captionProp = "petName" )
```

@ducdhm can you please update assetQueryListSettings.html to allow selecting those properties for the asset type?

**Comment by bradmac** [comment]
Note that you can now get the target asset type from ajax:

![image](https://user-images.githubusercontent.com/826458/34859087-0626d860-f7b9-11e7-9006-6b7f2fbdef88.png)

**Comment by bradmac** [comment]
And can now get asset types as json:
http://localhost:8080/content/pet/?asJson

![image](https://user-images.githubusercontent.com/826458/34859279-13af8fbc-f7ba-11e7-82d1-7c3a4c7ff489.png)

**Comment by ducdhm** [comment]
Done!

**Comment by bradmac** [comment]
Now have the ability to select a field (usually a derived field) to populate each item in the list from a template defined on the content type.

Eg:
Here is the editor:
![image](https://user-images.githubusercontent.com/826458/35025889-ce7a9f62-fbac-11e7-8fdb-60c2111d3605.png)

Here is the derived field:
![image](https://user-images.githubusercontent.com/826458/35025903-e31a9ef4-fbac-11e7-8de5-df34539011a0.png)

Here is the details page for the field, showing the mvel template:
![image](https://user-images.githubusercontent.com/826458/35025913-f316916e-fbac-11e7-8f4d-6dc0fe96b479.png)
