### ISSUE TITLE
Unable to change selected font size in container

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4762]
If you highlight some text in a container, and try to change the font to say H4, all the type updates and not just the selected text. You should be able to change the font size of selected text.

http://kademi.admin.kademi.us/pages/kademi-dev/v5-sections/howtos/moblix/

![image](https://user-images.githubusercontent.com/2201340/34758554-188ea468-f62b-11e7-8130-b67e4a8b81f1.png)

**Comment by ducdhm** [comment]
Already fixed!
