### ISSUE TITLE
Youtube component doesnt allows to fullscreen

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#4763]
Solution: https://stackoverflow.com/questions/27723423/youtube-iframe-embed-full-screen

**Comment by ducdhm** [comment]
Done!

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/34878455-e84f5e62-f7b2-11e7-910a-910371fb938e.png)
http://version1.vlad21clearn-vladtest21c.kademi-ci.co/page1.html

I've create a new fresh acc, fresh site
Add a custom page and add there a youtube component
Then View page and try to full screen
http://version1.vlad21clearn-vladtest21c.kademi-ci.co/page1.html
http://vladtest21c.admin.kademi-ci.co/pages/vlad21clearn/version1/

**Comment by ducdhm** [comment]
@Uafinder you need to sync latest code to apply my changes. I have checked the code and it's old

**Comment by Uafinder** [comment]
Yup looks fine at the moment...
I've tested in a fresh account, so no idea why code was old
