### ISSUE TITLE
SCORM content is null in frontend

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#4764]
Link to module: http://swimart.admin.kademi.com.au/websites/swimart/27102015nohydroxypure/programs/2018Promo/PPP/PPP1/#files-tab

Zip file for SCORM content: 
[89c4a5926769ddeee82abc47b7c1f37a8d00629f.zip](https://github.com/Kademi/kademi-dev/files/1617754/89c4a5926769ddeee82abc47b7c1f37a8d00629f.zip)

Frontend link: http://training.swimart.com.au/programs/2018Promo/PPP/PPP1/

**Comment by bradmac** [comment]
I've uploaded locally and seeing this JS error when running the SCORM module
```
TypeError: $(...).offset(...) is undefined
```

**Comment by bradmac** [comment]
I've uploaded locally and is working correctly:

![image](https://user-images.githubusercontent.com/826458/34794184-c248cac4-f6b2-11e7-84eb-127b62f54735.png)

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/34794202-d65efa10-f6b2-11e7-849f-7afcc64691b9.png)

**Comment by bradmac** [comment]
Looking at the swimart site, it appears the scorm module hasnt been added correctly, there is nothing showing:

![image](https://user-images.githubusercontent.com/826458/34794260-f886bb32-f6b2-11e7-8a0a-6509b3e0f540.png)

Although i can see files have been unzipped:
![image](https://user-images.githubusercontent.com/826458/34794281-05829ec8-f6b3-11e7-84a8-ab84ecedb284.png)

**Comment by bradmac** [comment]
Problem was that the site was using an old theme
