### ISSUE TITLE
Pressing "Cancel" while uploading something not really cancel a task

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4765]
1. I've upload a file with products (more than 1000)
[Lonza_TraxProducts_full.zip](https://github.com/Kademi/kademi-dev/files/1618150/Lonza_TraxProducts_full.zip)
2. when import reach 1000 I've press cancel
3. it says that import cancelled
4. go to background tasks and there will be a task
![image](https://user-images.githubusercontent.com/1945230/34764384-0ba55244-f5f7-11e7-9fd6-8d016696cb5e.png)
5. Go back to products uploader and I saw in console that ajax is still checking for upload status update. 
![image](https://user-images.githubusercontent.com/1945230/34764424-30025826-f5f7-11e7-8a07-b7ce8e671927.png)
6. Go to Jenkins and watch for logs
![image](https://user-images.githubusercontent.com/1945230/34764594-ac7fab74-f5f7-11e7-8b59-6054ae1d6c27.png)
http://vladtest20e.admin.kademi-ci.co/tableUploaders/productsUploader

**Comment by bradmac** [comment]
hey @Uafinder thats ok, the status checking continues while there is a task to check. Thats what you're seeing in jenkins logs and the browser logs. The task isnt running (at least those logs dont indicate that it is running), but the front end continues to check the task status.

**Comment by Uafinder** [comment]
ok, understood, thanks
