### ISSUE TITLE
Add "you are about to leave website" option to CKEditor links

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#4769]
We need an option in the CKEditor links plugin to allow adding a confirmation message when the user clicks through.. 

Aim is to create something like this:
![image](https://user-images.githubusercontent.com/3704174/34819967-f2138b6c-f6c7-11e7-83a7-15ff5cd330fc.png)

**Comment by mkhoudary** [comment]
https://github.com/Kademi/client-sudler-phhub/issues/4

**Comment by bradmac** [comment]
Rather then doing this on each link (which would be tricky from a content management perspective) we could make this an app which listens for click events. Any event for a page on a different domain name would consume the event and display the modal.

The OK button would then be made into an actual link to the other site.

**Comment by bradmac** [comment]
@ducdhm your thoughts?

**Comment by ducdhm** [comment]
@bradmac I think we can make it as an app. Whenever users click on external link, we'll show popup like this. To check external link, it's not hard. Just check link is not started with `/` (except `//`).

**Comment by bradmac** [comment]
:+1:
