### ISSUE TITLE
Knowing asset file size and mime type

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#4770]
We need a way to be able to know asset file size and mime type.. to be able to implement such feature:
![image](https://user-images.githubusercontent.com/3704174/34825197-30777348-f6da-11e7-82af-b9378007dba2.png)

**Comment by mkhoudary** [comment]
https://github.com/Kademi/client-sudler-phhub/issues/12

**Comment by bradmac** [comment]
Asset has the mimetype in the format property.

I'll add the ability to get the file size.

**Comment by bradmac** [comment]
BinaryAsset now has a fileSize property (bytes)

```
Long getFileSize();
```

BTW, there is a method on formatter that will be helpful

```
    /**
     * Convert the given object to a user friendly description of the size,
     * assuming the value is in bytes. If the value is a Resource it will take
     * the content length
     *
     * Eg 300 B, 5 KB, 3 MB
     *
     *
     *
     * @param o
     * @return
     * @DocumentedMethod
     */
    public String formatBytes(Object o) {
```
