### ISSUE TITLE
Support dynamic media assets

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4773]
In situations where a page is being rendered for a content asset (eg displaying a page for a Pet) we will want to display images and videos (ie media) assets related to the content asset. Eg the thumb for the pet, or a funny video

This needs to be dynamic, ie it uses a property of the asset.

I've created a new component called dynamicMediaAsset, but I'm not sure that this is the right approach.

Another approach is to integrate the asset library into our existing photo and video components, so that they can allow a content type property to be selected instead of selecting a specific file or asset.

Example:
![image](https://user-images.githubusercontent.com/826458/34853155-34ba92b0-f797-11e7-9df2-619c66d2f111.png)

![image](https://user-images.githubusercontent.com/826458/34853186-5196d9fc-f797-11e7-92c7-fef032c469db.png)

**Comment by bradmac** [comment]
@ducdhm what do you think? Should we integrate property selection into standard video and photo components? Or continue with using a seperate component? If using a seperate component we'll need to replicate the style settings, eg rounded corners etc.

**Comment by bradmac** [comment]
If integrating with the standard image/video components, we can consider using KCode fields, because these include asset type fields, and there might be fields on other objects useful for displaying media

**Comment by bradmac** [comment]
OK, so i think the best way to handle this is to update the existing image and video components to support selecting KCode fields.

That all the current styles and options remain available.

**Comment by ducdhm** [comment]
As discussed:
 * Removing static photo and video component
 * Add dynamic photo and video component in contentApp with KCode support

**Comment by ducdhm** [comment]
@bradmac Web components are ready to test. I'm doing EDM Photo component.

**Comment by ducdhm** [comment]
@bradmac Frontend stuff is working now. Just need support KCode for previewing in content editor page

**Comment by bradmac** [comment]
Working:
![image](https://user-images.githubusercontent.com/826458/35370412-7f162c2e-01f2-11e8-8a3a-dc27da242fff.png)

![image](https://user-images.githubusercontent.com/826458/35370395-6ba1191a-01f2-11e8-9cb1-bbd4075eda67.png)

**Comment by bradmac** [comment]
@Uafinder over to you for testing. Note that to test this you need to create a content item and then view it in the front end, so the kcode field can be evaluated for the content item.

**Comment by Uafinder** [comment]
ok, closing as discussed
