### ISSUE TITLE
Autoloader missed on rootorg

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4775]
![image](https://user-images.githubusercontent.com/1945230/34878630-78ef54a4-f7b3-11e7-871d-2caaccfb5145.png)
http://rootorg.admin.kademi-ci.co/

I can't find autoloader and not sure if autoloading works automatically.

**Comment by bradmac** [comment]
The problem was that there were organisations with a null parent, which makes them root orgs. But that is invalid, there should only ever be 1 rootorg.

I'm not sure how we ended up with multiple root orgs, but i've moved the others to be under the real rootorg.

**Comment by Uafinder** [comment]
Yup, looks ok
