### ISSUE TITLE
New Journey Email not firing

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4776]
Create a new journey here http://kademi.admin.kademi.us/funnels/channel-loyalty-campaign-followup/version1/#journeyBuilder-tab

It is triggered when a profile is added to this group Loyalty Email Campaign Followup

The first email when fired is blank http://kademi.admin.kademi.us/funnels/channel-loyalty-campaign-followup/version1/emailAction-15d10e/#summary-tab

Also you cannot test fire the email, says " Couldnt not send test email: Could not send email: id to load is required for loading"

**Comment by paddyow** [comment]
Note this applies to any new journey, here is another I created http://kademi.admin.kademi.us/funnels/agency-campaign-1/version1/emailAction-8ea87b/#message-tab

**Comment by bradmac** [comment]
FYI
```
class java.lang.IllegalArgumentException::id to load is required for loading
- org.hibernate.event.spi.LoadEvent.<init>(LoadEvent.java:87)
- org.hibernate.event.spi.LoadEvent.<init>(LoadEvent.java:59)
- org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.load(SessionImpl.java:2410)
- org.hibernate.internal.SessionImpl.get(SessionImpl.java:913)
- co.kademi.db.Lead.get(Lead.java:316)
- com.fuselms.apps.funnels.manage.ManageSendEmailResource.sendTest(ManageSendEmailResource.java:249)
```

**Comment by gonzalon** [comment]
@Uafinder this error was caused by the change I made to select the leads, here it was empty and failing because of that.
Now if you just use the "Test" button it would "create" a mock lead so it wont fail if we are using the lead in a expression for the email...

**Comment by paddyow** [comment]
Looks good to me

**Comment by Uafinder** [comment]
I've an active lead, but I can't select it in email test template...
![image](https://user-images.githubusercontent.com/1945230/34941180-53ded3ac-f9fb-11e7-843b-943da4db5fb0.png)
https://vladtest22.admin.kademi-ci.co/funnels/journey1/version1/emailAction-c9038c/#summary-tab

**Comment by gonzalon** [comment]
@Uafinder the lead is related to the target profile. if you enter the target email it would show the leads for that user.
Ex:
![image](https://user-images.githubusercontent.com/2773216/34960722-ea0281a8-faa0-11e7-82ab-8b18b7a87ac1.png)

**Comment by Uafinder** [comment]
Yup, looks good... missed that thing
