### ISSUE TITLE
function component for KPI on-track target achiever

### ISSUE THREAD

**Issue by Anton69arb** [Kademi/kademi-dev#4779]
Hey, what is the function of this, could you explain please, when making an on-track target achiever for  users with KPI's

http://version1.ant-kpi3_ant-kpi3.kademi-ci.co
http://version1.ant-kpi3_ant-kpi3.kademi-ci.co/index.html

![screenshot-version1 ant-kpi3_ant-kpi3 kademi-ci co-2018-01-15-11-10-16-368](https://user-images.githubusercontent.com/32444328/34921338-79a58330-f9e5-11e7-8cf5-d034b03b504c.png)

**Comment by bradmac** [comment]
@ducdhm should that input be showing in the admin? It seems to be hidden in front end.

**Comment by ducdhm** [comment]
Already fixed!

**Comment by Uafinder** [comment]
it works
