### ISSUE TITLE
Relation field types to allow creation and editing in place

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4781]
Should be dependent on the type of field

Eg if the relation field is defined for an image, then it should allow uploading an image. Similar for video.

If its to a content type, then the field should allow creating an instance of the content type and linking to it

For a text asset, it should provide an editor in a modal (similar for editing calendar events)

**Comment by bradmac** [comment]
I've moved the HTML into template files templates/apps/content/asset-fields/groupField.html and relationFieldInput.html

**Comment by ducdhm** [comment]
@bradmac I add extra relationFields for text and binary as following:

```
      <relation>
        <name>document</name>
        <text>Document</text>
        <title>Document</title>
        <contentType>binary</contentType>
        <required>true</required>
        <allowMany>false</allowMany>
      </relation>
      <relation>
        <name>description</name>
        <text>Description</text>
        <title>Description</title>
        <contentType>text</contentType>
        <required>true</required>
        <allowMany>false</allowMany>
      </relation>
```

but it throws error like
```Error: Error invoking method 'get(java.lang.Integer)' in java.util.ArrayList at rootorg.admin.loopbackdns.com:/theme/apps/content/asset-fields/relationFieldInput.html[line 9, column 33]```

Code line 9 is

```
#if( $fieldDef.allowMany )
    #foreach($relation in $relations)
        #set( $asset = $services.assetManager.find($relation.objectId) )
        #renderFieldInput($asset $fieldDef)
    #end
#else
    #set( $relation = $relations[0] ) // Line 9
    #set( $asset = $services.assetManager.find($relation.objectId) )
    #renderFieldInput($asset $fieldDef)
#end
```

**Comment by bradmac** [comment]
@ducdhm I dont like this UI, i think we need something nicer:

![image](https://user-images.githubusercontent.com/826458/34956999-85fca996-fa90-11e7-9846-61a9a729cd09.png)

I was thinking we would have one line, something like a button group, with an upload button to upload a new item

**Comment by bradmac** [comment]
@ducdhm regarding that error, just needed this
```
    #if(!$relations.isEmpty() )
        #set( $relation = $relations[0] )
    #end
```

**Comment by bradmac** [comment]
Here's what i've come up with:
![image](https://user-images.githubusercontent.com/826458/34963893-b9ef1102-faaf-11e7-97ae-6316daf0e4db.png)

**Comment by bradmac** [comment]
Clicking the edit icon shows the related asset in a modal:

![image](https://user-images.githubusercontent.com/826458/34964030-4eaf0c3e-fab0-11e7-91d9-c868533a28f3.png)

**Comment by bradmac** [comment]
@ducdhm can you please apply the same approach to other asset types

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/34969575-4a72b584-fad4-11e7-9474-833cba8a45aa.png)

We're now displaying modals to create and edit related assets

**Comment by bradmac** [comment]
@ducdhm please ensure the creation modals all correctly update the input value

Note that new asset responses now include a assetUniqueName property to identify the new resource.

**Comment by bradmac** [comment]
@ducdhm can you make sure that for multi-value relation fields, there is always a blank field for the user to add a new item? So if they select an item with the last field we should add a new blank one.

![image](https://user-images.githubusercontent.com/826458/34971987-67e0d3c6-fae3-11e7-9782-31316386c281.png)

**Comment by ducdhm** [comment]
Done!
