### ISSUE TITLE
Youtube component - error while pressing Cancel on video choose

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4784]
![image](https://user-images.githubusercontent.com/1945230/34938667-e44df5a8-f9f1-11e7-98e3-852575afd1fc.png)
![image](https://user-images.githubusercontent.com/1945230/34938632-bec1e844-f9f1-11e7-8304-581b1b9fac53.png)
1. Add a container and a component
2. Press edit component
3. Press change video
4. Press cancel on video choose
5. Error in console appears
https://vladtest22.admin.kademi-ci.co/pages/vlad22learn/version1/

**Comment by ducdhm** [comment]
Done!

**Comment by Uafinder** [comment]
Yup, looks good
