### ISSUE TITLE
Notify checkbox on comments block have no influence to send notification

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4786]
1. Create a website, install forums there, create a page...
2. Go to page, login as some user, leave a comment and don't select Notify checkbox.
3. Open different browser, leave a comment
4. Open emails history and watch that notify about comment has fired.
https://vladtest22.admin.kademi-ci.co/emails/?q=&status=&job=

**Comment by tuzzmaniandevil** [comment]
Fixed

**Comment by Uafinder** [comment]
Looks better
