### ISSUE TITLE
journey title bad on creation

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4788]
I've two journeys
![image](https://user-images.githubusercontent.com/1945230/34943655-30c58852-fa05-11e7-904e-498253a99d8e.png)
When I try to create a lead it's title looks bad
![image](https://user-images.githubusercontent.com/1945230/34943681-4d6577ba-fa05-11e7-9291-0bd98b326431.png)
![image](https://user-images.githubusercontent.com/1945230/34943688-55e03b14-fa05-11e7-8391-3817a10f6b26.png)
https://vladtest22.admin.kademi-ci.co/

**Comment by gonzalon** [comment]
New lead, now it would show the title or the name if the title wasn't setup.

![image](https://user-images.githubusercontent.com/2773216/34968518-9679ea52-face-11e7-8e68-59f88aed6a78.png)

![image](https://user-images.githubusercontent.com/2773216/34969578-4e83e77e-fad4-11e7-976e-688686291633.png)

**Comment by Uafinder** [comment]
YUp, fine in that places...
but remains here: when push create new lead in the frontend
![image](https://user-images.githubusercontent.com/1945230/34978164-fe141cb0-faa5-11e7-9326-c7db4f56c8ee.png)
http://vlad22leads_vladtest22.kademi-ci.co/dashboard
https://vladtest22.admin.kademi-ci.co/

**Comment by gonzalon** [comment]
Fixed in leadman 1.7.8 

![image](https://user-images.githubusercontent.com/2773216/35022285-fe8a4404-fb99-11e7-8a8f-cdd223243225.png)

**Comment by AlaaKhalaf94** [comment]
This is fine
But I see another place with the same bug , in "Quick Lead" menu
http://vlad22leads_vladtest22.kademi-ci.co/
https://vladtest22.admin.kademi-ci.co/

![capture1](https://user-images.githubusercontent.com/26510030/35038550-d30c4946-fb83-11e7-85b7-0e015730851d.PNG)

**Comment by gonzalon** [comment]
Hopefully we are not missing any other one :P 

![image](https://user-images.githubusercontent.com/2773216/35067730-b57fdf62-fc39-11e7-9281-47399d2ad7b3.png)

**Comment by AlaaKhalaf94** [comment]
Passed
