### ISSUE TITLE
Level progress panel component bugs

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4789]
1. Bug in circle viewing in editor
![image](https://user-images.githubusercontent.com/1945230/34946343-2ab95498-fa0f-11e7-94fa-33c63aa1fc07.png)
- add component
- edit it, assign some topic to it
- save
- close tab
- then open page for edit again
- check that circle will replaced by numeric value

it also happens on adding component

2. When you change a container layout from auto to box for example it cause a visual bug in editor
![image](https://user-images.githubusercontent.com/1945230/34946590-25dad4be-fa10-11e7-9abd-94f1a8a654ef.png)

**Comment by ducdhm** [comment]
Already fixed!

**Comment by Uafinder** [comment]
2. Not fixed
![image](https://user-images.githubusercontent.com/1945230/36982509-aa373af0-2098-11e8-9465-db413c43cb79.png)
https://vladtest38d.admin.kademi-ci.co/pages/vladtest38dsales/version1/

1. Yup, fixed

**Comment by bradmac** [comment]
> When you change a container layout from auto to box for example it cause a visual bug in editor

Hey guys, this is a low priority issue. If that is the only remaining problem we can put that into the Priority3 milestone.

**Comment by Uafinder** [comment]
Opened separate issue for that
