### ISSUE TITLE
When badge node contains no badge inside it blocks journey work (NPE)

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4791]
Should be a validation, which will not allow to save node without selected badge. Or it could be NPE check on journey execution.
![image](https://user-images.githubusercontent.com/1945230/34948343-81f8d75a-fa15-11e7-9dca-97dfb7195fd0.png)
![image](https://user-images.githubusercontent.com/1945230/34948373-94011af2-fa15-11e7-87e3-267f4a63ae34.png)
https://vladtest22.admin.kademi-ci.co/funnels/journey1/version1/#journeyBuilder-tab

**Comment by tuzzmaniandevil** [comment]
Added UI Validation and a null check in the back end

**Comment by Uafinder** [comment]
yup, looks good
