### ISSUE TITLE
KPI review page questions

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4792]
1. Date selector... there are appears 2015, 2016 years, and no possibility to change to 2017 for example. What it for?
2. Pop-up bad for date
![image](https://user-images.githubusercontent.com/1945230/34949406-b41c0c0e-fa18-11e7-89c1-a475bf55de2c.png)

3. When you select another year it cause terrible visual bug...
![image](https://user-images.githubusercontent.com/1945230/34949442-c88dcf10-fa18-11e7-993a-1d9d79ab2b2e.png)
![image](https://user-images.githubusercontent.com/1945230/34949457-d00e258c-fa18-11e7-8fac-4ce0bc6d92e6.png)

4. All three buttons doesn't work - and tell to select KPI period, but how it can be selected no one knows...
![image](https://user-images.githubusercontent.com/1945230/34949507-f16c672a-fa18-11e7-81f7-e9f895e9bd1d.png)

https://vladtest22.admin.kademi-ci.co/kpis/

**Comment by gonzalon** [comment]
1,2,3 Fixed
4. There was a problem in the display but you should see something like this:

![image](https://user-images.githubusercontent.com/2773216/36081961-c8735ba6-1009-11e8-89eb-b55d09ad7a6a.png)

**Comment by Uafinder** [comment]
2,3 -ok
1 - when you are at 2018 year, it shows some years back successfully, but when you move to 2017 there is no possiblity to move from there to 2016 for example
![image](https://user-images.githubusercontent.com/1945230/36150192-8926f6d4-10cb-11e8-8b9a-4479a0d7a0b8.png)
![image](https://user-images.githubusercontent.com/1945230/36150197-8f0c779a-10cb-11e8-9381-3dbebf8bcddc.png)
http://vladtest33.admin.kademi-ci.co/kpis/?year=2018

4 - still not work for me

**Comment by bradmac** [comment]
@Uafinder I've corrected the config of your KPIs
- set start date to 1/1/2018
- set period to monthly (daily is not realistic)
- removed baseline series

**Comment by bradmac** [comment]
To do the **initial** processing of KPIs, you do that from the data series page:
![image](https://user-images.githubusercontent.com/826458/36171256-c63df112-1166-11e8-9cb3-03726b2a5239.png)

**Comment by bradmac** [comment]
KPI periods which have been processed can then be re-processed (if required) from the Review KPIs page.

**Comment by Uafinder** [comment]
ok, understood
