### ISSUE TITLE
Leaderboard KPI order weird 

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4793]
![image](https://user-images.githubusercontent.com/1945230/34949580-28e5dd30-fa19-11e7-9881-9d8974155f19.png)
https://vladtest22.admin.kademi-ci.co/sales/salesqa01title/kpis/kpiqa01/#general-tab
Should be as marked on the screenshot. OR I missed somewhere?

**Comment by tuzzmaniandevil** [comment]
Added sorting

**Comment by AlaaKhalaf94** [comment]
passed
