### ISSUE TITLE
Managing license process complicated

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4797]
So,
1. So to subscriptions
2. Find there a necessary org (account)
3. Open it
4. Verify that license is expired
5. Push add license
6. Enter date time
7. Save
8. Refresh the license information in the site button
9. It transfer you to account where license was managed
10. You push manage subscription (or you shouldn't?)
11. But still will redirect you to license page when you try to access other pages.
12. And then after some time, (3-5 minutes, account become live)
http://vlad-test20.admin.kademi-ci.co/
http://rootorg.admin.kademi-ci.co/subscriptions/800506/
![image](https://user-images.githubusercontent.com/1945230/34983304-bc7178b0-fab5-11e7-9f30-abe167072d79.png)

**Comment by bradmac** [comment]
> Refresh the license information in the site button

After pushing that button the client account should be re-enable immediately.

**Comment by bradmac** [comment]
@gonzalon please see if you can reproduce the problem Vlad saw above. Use an existing expired account in CI to test with.

**Comment by gonzalon** [comment]
Fixed, now it'd invalid the cache and after you do the "Refresh the license" you can access any page without waiting the 5min

**Comment by Uafinder** [comment]
Working like a charm...!
