### ISSUE TITLE
error while trying to setup Google Maps component (keditor)

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4798]
![image](https://user-images.githubusercontent.com/1945230/34989063-b3e924ea-fac9-11e7-95c2-43d6d4486ae4.png)
http://vladtest22.admin.kademi-ci.co/pages/vlad22learn/version1/
1. Create a page
2. Add googleMaps component
3. Click edit on the component

**Comment by ducdhm** [comment]
@Uafinder Can you double-check again? I checked in CI and it works normally

**Comment by Uafinder** [comment]
Yup, it works at the moment
