### ISSUE TITLE
text editor - table split cells vertically and horizontally are mixed places

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4801]
1. Create a page
2. Add a text component there
3. Add a table to the text
4. Try to merge and split cells
5. When you push "split horizontally" it do it vertically and vice versa.
![image](https://user-images.githubusercontent.com/1945230/35053053-cbe4d2cc-fbb1-11e7-9041-3ff003c45cca.png)
spotted on prod itinsured
http://insured.admin.kademi.com.au/pages/insured/iti16012018/customquotes/

**Comment by bradmac** [comment]
"split horizontally" means to create a horizontal split, ie to create 2 cells one over the other

![image](https://user-images.githubusercontent.com/826458/35060970-aeaff984-fc24-11e7-9559-1a41327077d2.png)

So i think this is correct
