### ISSUE TITLE
Ability to hide categories in reward store

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4802]
- add a hidden flag to category
- update reward store components so that hidden categories are never displayed

**Comment by gonzalon** [comment]
Category with products:

![image](https://user-images.githubusercontent.com/2773216/35077627-2e2f2f34-fc63-11e7-96a9-884f23bceea5.png)

Hidden checkbox:
![image](https://user-images.githubusercontent.com/2773216/35077617-267ff96c-fc63-11e7-8fe8-244c69dd8ce7.png)


Reward store menu:
![image](https://user-images.githubusercontent.com/2773216/35077658-43b760ec-fc63-11e7-84d5-7c3f009598eb.png)

**Comment by gonzalon** [comment]
Update also going to change it so it only shows the categories that has products in that reward store.

**Comment by gonzalon** [comment]
Front end:

![image](https://user-images.githubusercontent.com/2773216/35131331-679236f0-fd2a-11e7-9c95-8b5adf62f6b1.png)


Categories:
![image](https://user-images.githubusercontent.com/2773216/35131341-779f0eba-fd2a-11e7-8fa2-1887a9d8c4ec.png)

Hidden: Homeware / hidden-child
No products: cate
No products in the reward store: gonz

**Comment by Uafinder** [comment]
Hey,
I've several problems:
1. I've not see child categories on the frontend.
http://vladtest25.admin.kademi-ci.co/categories/
![image](https://user-images.githubusercontent.com/1945230/35227294-6830928c-ff96-11e7-8d05-1383a1f5fad1.png)

2. Question: should product being displayed if it present in hidden category?

3. Enhancement: hidden column should be added to Manage categories page
![image](https://user-images.githubusercontent.com/1945230/35227415-b82cfa46-ff96-11e7-8ef4-993f61345914.png)

**Comment by bradmac** [comment]
> Enhancement: hidden column should be added to Manage categories page

We wont worry about that for now.

**Comment by bradmac** [comment]
> Question: should product being displayed if it present in hidden category?

This feature should have no impact on the display of products. It only affects whether categories are displayed.

**Comment by bradmac** [comment]
> I've not see child categories on the frontend.

If you mean that child categories of hidden categories are not displayed then that is correct. But note that this is an invalid use case. It doesnt make sense to have sub-categories of hidden categories.

**Comment by Uafinder** [comment]
Yup, looks good
