### ISSUE TITLE
Email history CSV not showing all statuses 

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4805]
http://kademi.admin.kademi.us/emails/?q=&status=&job=

When you export to CSV, the status field shows Complete or Failed only.  It should also show the additional status of  Opened and Converted.

The UI also needs updating
![image](https://user-images.githubusercontent.com/2201340/35079115-a88c4f6e-fc59-11e7-9c53-4333ff95c252.png)

Complete/Failed > Opened > Converted

**Comment by gonzalon** [comment]
@AlaaKhalaf94  Please take in mind that if you test with an old account you are going to need to re index the emailItems.!

**Comment by AlaaKhalaf94** [comment]
passed
