### ISSUE TITLE
Losing next timer goal at email decision node in journey

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4806]
Emails were sent out via this journey:
http://kademi.admin.kademi.us/funnels/channel-loyalty-campaign/version1/

At the first email result goal, some profiles are not progressing and no longer have a current goal:
![image](https://user-images.githubusercontent.com/2201340/35094096-6cc46a54-fc98-11e7-97a9-516665583441.png)

Example of profiles I have found from a quick review that have no timer goal.

http://kademi.admin.kademi.us/manageUsers/17612667/#funnelsTab-tab
http://kademi.admin.kademi.us/manageUsers/17612511/#funnelsTab-tab
http://kademi.admin.kademi.us/manageUsers/17612819/#funnelsTab-tab
http://kademi.admin.kademi.us/manageUsers/17613241/#funnelsTab-tab

This is an example of a profile that did progress to the next timer and has a goal.  They are all part of the same batch.
http://kademi.admin.kademi.us/manageUsers/17612753/#funnelsTab-tab

How can I find out which profiles no longer have a goal as these will need to be restarted.

**Comment by gonzalon** [comment]
@paddyow I can't seem to be able to reproduce it, but we should keep an eye on it to see if happens again
now regarding the leads you have without any action I did an update so we can update those by the excel upload and set a new current goal correctly  (https://github.com/Kademi/kademi-dev/issues/4810)

For this case, what should that be? should they go directly to the second email?

**Comment by paddyow** [comment]
I uploaded this list:
[Test list.xlsx](https://github.com/Kademi/kademi-dev/files/1650316/Test.list.xlsx)

- Into this group: http://kademi.admin.kademi.us/groups/loyalty-email-campaign/members/
- I matched on First Name, Last Name and Email only.

A few that got stuck on the email decision node:
http://kademi.admin.kademi.us/manageUsers/17861892/#funnelsTab-tab
http://kademi.admin.kademi.us/manageUsers/17861914/#funnelsTab-tab

A few that progressed ok:
http://kademi.admin.kademi.us/manageUsers/17862000/#funnelsTab-tab

**Comment by Uafinder** [comment]
I've send more than 100 emails per import via send email node, and all of them was processed ok, email result node was fine. So closing
