### ISSUE TITLE
Asset manager links doubling

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4807]
![image](https://user-images.githubusercontent.com/1945230/35102466-b4ebfe8c-fc6b-11e7-9e66-7ab73c74325d.png)
http://vladtest23.admin.kademi-ci.co
![image](https://user-images.githubusercontent.com/1945230/35102486-c0acfda2-fc6b-11e7-8192-aedd404b1aee.png)

**Comment by bradmac** [comment]
Fixed

**Comment by Uafinder** [comment]
yup, looks good
