### ISSUE TITLE
bulk email sending via journey node history trouble

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4808]
So, we have a simple journey which constains only begin and send email
Send email has only From setting, site, and subject, some content inside
Begin node has initial checkbox.
So, after instant lead creation it will receive email.
Then we take a file with 104 leads inside, and import it to the journey.
Import finish with success, but when we go to email history tab, there we will see only a few emails was send, and some of they in pending or undefined status.
![image](https://user-images.githubusercontent.com/1945230/35105059-5a4ed62c-fc73-11e7-963f-c84d8e856726.png)
however if you will access email item directly it will show that sending ok
![image](https://user-images.githubusercontent.com/1945230/35105097-747643be-fc73-11e7-9a41-819bc78ef41c.png)

The same situation will be on the journey node email history tab
![image](https://user-images.githubusercontent.com/1945230/35105171-9df4dd5e-fc73-11e7-959a-5ba2fd12a1a6.png)

So, some trouble with indexes - re-index email items solve a problem.
http://vladtest23.admin.kademi-ci.co/funnels/second-journey/version1/emailAction-8fc5cf/#history-tab

**Comment by gonzalon** [comment]
@Uafinder I can't reproduce it locally or in that account. I think this was fixed with another update I did for the emails. Can you confirm?

**Comment by Uafinder** [comment]
looks better now
