### ISSUE TITLE
Contact Us Form Component: Option to redirect to another page on success

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#4809]
Feature request from Sarah at Travel World.

After successfully submitting a form they want to be able to redirect to another page instead of showing the thank you message

**Comment by Uafinder** [comment]
Redirect works ok, but Thanks pop-up doesn't appear. Is it expected?
For example
![image](https://user-images.githubusercontent.com/1945230/36852526-88bc60f2-1d74-11e8-8a96-2e5bdb090923.png)

**Comment by bradmac** [comment]
The next page will usually be configured to display the message, so thats fine

**Comment by Uafinder** [comment]
Ok, so it works like a charm
