### ISSUE TITLE
Importing lead should set current node / goal correctly

### ISSUE THREAD

**Issue by gonzalon** [Kademi/kademi-dev#4810]
When the lead is imported:
if the lead is new it should wait for the goal timer or execute the action that it's being set.
if the lead exists the node should being set should be different to the current one for it to work.

**Comment by gonzalon** [comment]
@AlaaKhalaf94 example to test would be to create a jurney that has a timer goal and a email.
Import one lead to the timer goal, and check that waits the timer and then continues.
Import another lead to the email action, you should get the email inmediatly.

**Comment by Uafinder** [comment]
Hey, it looks doesn't work for me
I've import a large file which contains 4 different nodes, but as a result it looks like just a complete new lead.

[export-leads(13) - Cop1y.zip](https://github.com/Kademi/kademi-dev/files/1660322/export-leads.13.-.Cop1y.zip)

http://vladtest26.admin.kademi-ci.co/funnels/journey3/version1/leads/?startPos=0&pageSize=100&

**Comment by gonzalon** [comment]
@Uafinder fixed, just tested it with the same journey you created (just changed the time to 1 min)

![image](https://user-images.githubusercontent.com/2773216/35417157-1511c802-0291-11e8-8d33-a874282424d9.png)

**Comment by Uafinder** [comment]
Yeah, it works!
