### ISSUE TITLE
Ampersand symbol bad in page header for modules

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4811]
1. In admin console is looks like &amp;
2. In frontend it looks like && instead of &
![image](https://user-images.githubusercontent.com/1945230/35141430-93478f42-fd03-11e7-8651-2c51462b445d.png)
http://vladtest23b.admin.kademi-ci.co/websites/vlad23blearn/version1/programs/p1/c1/m1m3/#details-tab
http://version1.vlad23blearn-vladtest23b.kademi-ci.co/programs/p1/c1/m1m3/

**Comment by gonzalon** [comment]
Had to do some update to not break https://github.com/Kademi/kademi-dev/issues/3790#issuecomment-358898507

Both should be fine with  learner-lib 1.2.3

**Comment by Uafinder** [comment]
Fixed in a admin,
same thing in frontend... but double ampersand is not looking very bad and I don't think that it's vital, so closing for now...
![image](https://user-images.githubusercontent.com/1945230/35210405-b6604e3e-ff5a-11e7-97b3-32bfdb5cc5ce.png)
http://vladtest25.admin.kademi-ci.co/websites/vlad25learn/version1/programs/p1/c1/
