### ISSUE TITLE
error when open photo editor for Dashboard alert image (Assets)

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4812]
![image](https://user-images.githubusercontent.com/1945230/35143193-7e33f414-fd09-11e7-890a-70fa7839cf89.png)
http://vladtest23b.admin.kademi-ci.co/manageAlerts/alert-4446527#bodyCopy-tab
1. Add alert
2. Upload image
3. Push edit image button
![image](https://user-images.githubusercontent.com/1945230/35143237-a8cd37bc-fd09-11e7-8908-fadccd3f3d0f.png)

**Comment by Uafinder** [comment]
Now,
when you click on image insert button it gives you an error to console and image uploader doesn't open,
![image](https://user-images.githubusercontent.com/1945230/35620093-b06db55e-0688-11e8-91d4-6870b5409436.png)

http://vladtest28h.admin.kademi-ci.co/manageAlerts/alert-4887468#bodyCopy-tab

**Comment by ducdhm** [comment]
`1. When you push upload image to assets tree - it uploads successful, gives no errors but image doesn't appear.`

We already have issue for assets stuff. So I'll ignore it in this ticket.

**Comment by ducdhm** [comment]
```
2. When you push upload image to Files tree - it gives an error:
```
@Uafinder Because you dont choose any folder and just press upload so you'll upload to root (`/`). We dont store image in root. That's why you'll get error like that.

@bradmac What do you think about the case when use doesnt choose any folder and just press upload to `/`?

**Comment by bradmac** [comment]
In situations like this where there is no logical repository to use, the user should just use the asset library. Thats what its intended for.

So we should be able to hide the file tree

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
Ok, so when I click to upload image, it gives me just empty left bar, and when I try to upload image - error appears:
![image](https://user-images.githubusercontent.com/1945230/35805884-3b976cbe-0a86-11e8-8074-e68a4cba0ed1.png)
http://vladtest30a.admin.kademi-ci.co/manageAlerts/alert-5048892#bodyCopy-tab

**Comment by ducdhm** [comment]
Fixed in other issue!

**Comment by Uafinder** [comment]
Yup, error not appears anymore
