### ISSUE TITLE
Notifications on new comments work only once

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4813]
1. Setup anonymous comments
2. open page in one browser
3. leave a comment and check notifications check box
4. open page in other browser
5. leave a comment without checking notifications check box
6. Check email history - comment notification will fire
7. Open third browser
8. leave a comment with check notifications check box
9. Check email history - comment notification will not fire, which is incorrect
to insure that in doesn't works correctly
10. Go to the first browser
11. leave a comment again and check notifications check box again
12. Check email history - comment notification will fire for third user (that's ok)
13. Go to the second browser and leave comment there
14.  Check email history - comment notification will not fire, for first and third users both, which is incorrect
http://vladtest23c.admin.kademi-ci.co/emails/?q=&status=&job=
http://version1.vlad23canon-vladtest23c.kademi-ci.co/page1.html

**Comment by tuzzmaniandevil** [comment]
We don't send a new notification to a user unless they view the notification by logging in or if 6 hours have passed since the last notification.

@Uafinder Please text with a 6 hours delay between comments.

**Comment by bradmac** [comment]
@tuzzmaniandevil is this using the current date service? If so Vlad can use the maint page to fast forward the time, right?

**Comment by tuzzmaniandevil** [comment]
That's correct :-)

**Comment by Uafinder** [comment]
- if 6 hours have passed since the last notification - it works!
- they view the notification by logging in - it doesn't work!
http://vladtest25a.admin.kademi-ci.co/emails/?q=&status=&job=

**Comment by tuzzmaniandevil** [comment]
We now ack notifications when a logged in user visits the page of the comment

**Comment by Uafinder** [comment]
Looks fine!
