### ISSUE TITLE
Can't create email with subdomain

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#4816]
I create a site with "supporters.minda.asn.au" Domain name
http://minda.admin.kademi.com.au/websites/minda/version1/#panel_details-tab

Then in I try to put "<supporters@minda.asn.au>" in Email from address feild in email template , it doesn't success with me
it shows me error that "The email address must have a domain name the same as the domain on the website selected."

![capture2](https://user-images.githubusercontent.com/26510030/35193902-d6127930-feb2-11e7-99ef-1fd9c4cd9092.PNG)

http://minda.admin.kademi.com.au/groupEmails/98052656/#sendInfo-tab

**Comment by bradmac** [comment]
@AlaaKhalaf94 that is correct, that domain name is not linked to this account so cannot be used.

You need to create a website and set that domain name on it.
