### ISSUE TITLE
Admin Console - User Profile Page - Adding export ability

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#4824]
We need to enable export for summary tab contents and emails tab contents, this is part of a task that needs to be fulfilled for Vaya.

**Comment by mkhoudary** [comment]
https://github.com/Kademi/client-vaya/issues/235

**Comment by gonzalon** [comment]
@mkhoudary related to the summary tab, should it be the cards and the timeline? any format in particular?

Working on the email tab export

**Comment by mkhoudary** [comment]
@gonzalon attached an example of what we'd expect

[summaryExportSample.xlsx](https://github.com/Kademi/kademi-dev/files/1692805/summaryExportSample.xlsx)

**Comment by gonzalon** [comment]
@mkhoudary I talked with Brad and he say at the moment we are not doing the cards for the summary.

The rest it's ready to test!

**Comment by mkhoudary** [comment]
Checked.. Great work @gonzalon
