### ISSUE TITLE
Question about different email statuses

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4825]
So, I've a email which was send some time ago.
we have some different statuses for it, e.g. sent, open, converted, failed, and so on.
I tried to open some messages from different post systems, such as mailinator, gmail, or kademi domain, but even I open this email it doesn't say to me that it was open. 
Why it could be?
I've check QA and prod both
http://vladtest25.admin.kademi-ci.co/emails/?q=&status=&job=
http://vlad-live.admin.kademi.com.au/emails/?q=&status=&job=

So, the status of those emails remains "complete", instead of be changed to "Opened"
![image](https://user-images.githubusercontent.com/1945230/35225499-32ac6cd0-ff91-11e7-8c87-7bf899872ab6.png)

**Comment by bradmac** [comment]
> but even I open this email it doesn't say to me that it was open. Why it could be?

We use pixel tracking to detect opens. There was an issue previously where the tracking pixel wasnt being added, so please check with a new email and new account.

Note that we will only detect the email being opened if the client has image loading enabled. Many clients block image loading by default.

So please check that you're using a new email and you have image loading enabled.

**Comment by Uafinder** [comment]
i've test yesterday in a fresh account...
and click to load images which was blocked by default
gmail is not block images by default, but it doesn't matter of it... status of email still remained as "completed"

**Comment by bradmac** [comment]
These emails somehow have an incorrect pixel tracking link, eg
```
http://vlad25learn-vladtest25.kademi-ci.co/i=4532818
```

**Comment by bradmac** [comment]
OK, the issue is that the email app was turned off for the website, and its the email app which tracks opens...

**Comment by bradmac** [comment]
I've moved the ack resource into the AdminApp, so its always available and doesnt require the user to enable the email app

**Comment by Uafinder** [comment]
Yeah, it start to track them
