### ISSUE TITLE
Keditor - photo block become too bottom

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4826]
Photo block was one of the top blocks of the Keditor, because it used very often. Now it located on the very bottom of the list. Not sure if it's correct.
![image](https://user-images.githubusercontent.com/1945230/35227661-51e2ddae-ff97-11e7-8293-61723e12bfdd.png)
![image](https://user-images.githubusercontent.com/1945230/35227674-5b484e42-ff97-11e7-97f9-b520d7abc821.png)
http://vladtest25.admin.kademi-ci.co/pages/vlad25sales/version1/

**Comment by bradmac** [comment]
We;re not controlling the order of components currently. Users can find the component with the search tool.

We might look at some mechanism to push common components to the top in a later milestone
