### ISSUE TITLE
Invoicing API

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4827]
Create an InvoicingApplication interface to abstract common invoicing operations.
- create purchase order (similar to a Quote or Invoice)
- create quote
- create invoice

Note that this interface should be independent of the Kademi persistence classes for invoicing, eg Quote, PaymentItemList, etc. 

Update the PaymentApp to be an implementation of InvoicingApplication

This should write to the stream for when these items are created, including a link to the created item.

Integrate the InvoicingApp framework with ProductOrder creation (should respond no matter how productorders are created, eg from stores or from admin)

1. When a ProductOrder is created, create a purchase order in for the product supplier
2. Roll-up ProductOrders into a single invoice and send to the client based on a configurable schedule (eg weekly)

Purchase Order Details
Sent to the product supplier as part of the checkout transaction, for each ProductOrder in the Cart.
-          Order Date
-          Delievery name (ie ordering customer)
-          Delivery address (ie from the Cart)
-          Deivery intructions
-          Delivery contact number
-          Shopping cart unique id number
-          Product Sku, name and purchase price + freight when necessary

Invoice
Includes all ProductOrders within the scheduled job date range. List each ProductOrder as a line item.
-          Order Date
-          Delievery name
-          Delivery contact number
-          Shopping cart unique id number
-          Product Sku, name and sell price rounded up to the next full dollar

**Comment by Uafinder** [comment]
how it can be tested? I've tested Xero integration a bit, is it the same?

**Comment by bradmac** [comment]
Xero is the only real implementation, so i think we can just close it
