### ISSUE TITLE
Xero integration

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4828]
Extension to https://github.com/Kademi/kademi-dev/issues/4827

Create an app which integrates the Invoicing API to Xero

**Comment by tuzzmaniandevil** [comment]
To get Xero setup:

- Create a free demo account on Xero: https://www.xero.com/nz/signup/ and use the Demo organisation
- Install the Xero app from the marketplace
- Navigate to the Xero app settings under "Apps" and connect with Xero
- Enable the purchase orders and invoicing from the Settings tab in Reward Stores
- Place an order in the Reward Store

A purchase order should appear in Xero. You can force the invoices to generate from the Settings tab in Reward Stores page

**Comment by Uafinder** [comment]
Well... all your steps are completed:
- Create a free demo account on Xero: https://www.xero.com/nz/signup/ and use the Demo organisation - *ok*
- Install the Xero app from the marketplace - *app installation doesn't enable it, had to enable it by hands* 
- Navigate to the Xero app settings under "Apps" and connect with Xero - *ok*
- Enable the purchase orders and invoicing from the Settings tab in Reward Stores - *ok*
- Place an order in the Reward Store - *ok*
- A purchase order should appear in Xero. You can force the invoices to generate from the Settings tab in Reward Stores page - *it doesn't appear in Xero after Force invoice process*
http://vladtest38b.admin.kademi-ci.co/reward-store/#rewardSettings-tab

**Comment by tuzzmaniandevil** [comment]
Fixed the issue with the Xero app not installing.
I tested everything else and works fine.

Please ensure the app is installed on the Website and you have connected to Xero from the Org.

Once you have connected to Xero, Refresh the page and open the settings to confirm it's been connected.

**Comment by Uafinder** [comment]
Yeah, it works like a charm
