### ISSUE TITLE
Error message - when posting a question on comments

### ISSUE THREAD

**Issue by Anton69arb** [Kademi/kademi-dev#4829]
Hey, there is an error message, when you try to post the message it gives this error -
 "Sorry, we could not process your request
Sorry, there appears to be a problem with the network or server. 
Please check your internet connection. 
If you're connected ok this might be a glitch in the system. - parsererror".

http://ant-comments.admin.kademi-ci.co/pages/ant-comments/version1/
http://ant-comments.admin.kademi-ci.co/manageUsers/4539062/#summary-tab

![1](https://user-images.githubusercontent.com/32444328/35247811-a70c33cc-0030-11e8-9562-93a8016a952b.png)

![2](https://user-images.githubusercontent.com/32444328/35247812-a736bf84-0030-11e8-8235-0c6cbcd33fb2.png)

**Comment by bradmac** [comment]
@tuzzmaniandevil can you take a look

**Comment by bradmac** [comment]
Just to confirm, we have forum components intended for use with forums pages.

We also have a comments component intended for use on any sort of content page.

@gonzalon please update the components only intended for forums so they are only available in the editor for forums pages
