### ISSUE TITLE
e-learning course - buttons should state start and not resume

### ISSUE THREAD

**Issue by Anton69arb** [Kademi/kademi-dev#4830]
Hey,
This user never started the e-learning course and the buttons should state start and not resume, please can we fix,

http://swimart.admin.kademi.com.au/manageUsers/95298615/#learningAppTab-tab

![this user never started the e-learning course and the buttons should state start and not resume please can we fix](https://user-images.githubusercontent.com/32444328/35251223-16949d5c-003f-11e8-84bb-2335cb9ec38d.png)

**Comment by anhnt** [comment]
@Anton69arb when logged in as that user, it shows him the courses on his dashboard, not modules. And each course has started module, so the course is started. Note that we show courses when there are lot of modules
