### ISSUE TITLE
Image editor doesnt work when dialog is opened for an existing image

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4831]
I edited the dimensions and clicked the tick button. Note the logs "no selected file"

![screenshot from 2018-01-23 13-16-12](https://user-images.githubusercontent.com/826458/35251354-b0327e66-003f-11e8-9891-73fe102d85fd.png)

http://docs.kademi.co/getting-started/Website-management/contenteditor?fileName=page-permissions.html

**Comment by ducdhm** [comment]
Fixed in other issue

**Comment by Uafinder** [comment]
Yup, looks good
