### ISSUE TITLE
Crazy acquisition rate

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4832]
![image](https://user-images.githubusercontent.com/826458/35252675-6c6de358-0046-11e8-95e7-1ca887d9360a.png)

Its showing 500%, but i think its illogical for it to greater then 100

http://insured-crm_insured.kademi.com.au/dashboard

**Comment by gonzalon** [comment]
at the end it can have this rates as the data its related to the selected period but can carry older data.
