### ISSUE TITLE
Cant delete folder and image which contains spaces in name

### ISSUE THREAD

**Issue by Anton69arb** [Kademi/kademi-dev#4833]
Cant delete folder and image which contains spaces in the name, please can we fix

http://kademi.admin.kademi.us/pages/kademi-dev/v7/getting-started/community-management/
ensure you in version 7
proceed an click to uploading users to table uploader - the 1st picture with a CSV file you can try  

![cant delete images or folders](https://user-images.githubusercontent.com/32444328/35255972-79798010-0056-11e8-81e0-9a1fe3cfd522.png)

**Comment by bradmac** [comment]
Getting a 404 on this url:
```
http://docs.kademi.co/getting-started/community-management/uploader%2520pics/_DAV/PROPFIND?fields=name,milton:hash,getcontenttype%3EcontentType,href,iscollection&depth=1
```

**Comment by bradmac** [comment]
So it looks like we're double encoding the file name

**Comment by Uafinder** [comment]
looks fixed on QA, on the address which provided by @Anton69arb error still appear

**Comment by bradmac** [comment]
@ducdhm can you please apply updates to both clusters, and apply the update to the kademi account so anton can use it?

**Comment by ducdhm** [comment]
Done!

**Comment by Uafinder** [comment]
Same thing on the Anton's link![image](https://user-images.githubusercontent.com/1945230/35619503-f09aee82-0686-11e8-8b34-b207143f060a.png)

**Comment by ducdhm** [comment]
@Uafinder You need to update new version of mtree-lib to see the change. Btw, i have upgrade latest version for mtree-lib in Anton's account.

**Comment by Uafinder** [comment]
Ok, closing
