### ISSUE TITLE
"All" products in category

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4835]
So, I have 2 products in Parent category and 2 x 2 in child1 and child2.
When you choose them separately it shows ok, but when you click on All, it shows you a Parent category products. But when you click on the Parent category, it show same products.
Is it ok, or All should show Parent+child1+child2?
![image](https://user-images.githubusercontent.com/1945230/35276736-0b4c81d6-004d-11e8-96c1-a0d671998401.png)
http://vladtest25asite2_vladtest25a.kademi-ci.co/vladtest25asite2-store/elec/?q=
http://vladtest25a.admin.kademi-ci.co/categories/

**Comment by bradmac** [comment]
I think the issue that we have here is that clicking "All" selects the parent category, but currently our search looks for products connected to that specific category. 

Instead, when a category is selected the search should return all products in that category or its child categories.

**Comment by gonzalon** [comment]
![image](https://user-images.githubusercontent.com/2773216/35358162-936463c2-01ba-11e8-83a6-eae3a9aac94c.png)

**Comment by Uafinder** [comment]
ok
