### ISSUE TITLE
Email to lead team contain incorrect link

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#4836]
When I make assign the lead to lead team

![capture1](https://user-images.githubusercontent.com/26510030/35279497-eb4ba1e2-0055-11e8-9685-8bceb3b1cd4e.PNG)

When I click on " Click Here " , it lead me to wrong link : http://leads/4554059
http://vaya-master.admin.kademi-ci.co/emails/4554104

**Comment by bradmac** [comment]
Hi @AlaaKhalaf94 the link is generated from a website which has the LeadMan app enabled. It looks like the app was disabled when the email was sent, but I've checked and that app is currently enabled.

Can you please check again after confirming that the app is enabled in the website?

**Comment by AlaaKhalaf94** [comment]
Thanks @bradmac , I've checked and the link worked fine
"http://vaya-master_vaya-master.kademi-ci.co/leads/4581349/"

But , it show me that I don't have permission to view this page , What powers do I have to be able to display the lead's page ?

**Comment by bradmac** [comment]
The Sales role should give you access

**Comment by AlaaKhalaf94** [comment]
Thanks
