### ISSUE TITLE
Carousel visual bug when using add content feature

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4838]
![image](https://user-images.githubusercontent.com/1945230/35285545-591f628e-0066-11e8-8144-e98feb375aeb.png)
So, when you add some custom content and press save it looks ugly on the editor panel...
http://vladtest25a.admin.kademi-ci.co/pages/vlad25atest/version1/

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
yup, it works!
