### ISSUE TITLE
Email history is not showing Opened emails (status remains Complete)

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4841]
So, the issue is that physically email status is changing from "complete" to "open", which you could see on the email details and send email details, but on email history page email statuses remains obsolete "complete".
![image](https://user-images.githubusercontent.com/1945230/35332544-f46e0ee0-0113-11e8-8364-7c227b32ddcb.png)
![image](https://user-images.githubusercontent.com/1945230/35332551-fbea0a84-0113-11e8-867c-79fc4a85899f.png)
http://vladtest26.admin.kademi-ci.co/emails/?job=&status=&q=

**Comment by bradmac** [comment]
Fixed

**Comment by Uafinder** [comment]
ok, looks good
