### ISSUE TITLE
Teams management app enable

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4842]
1. we don't have special app for teams in MarketPlace

2. when enable teams by hand there is an error in frontend:
![image](https://user-images.githubusercontent.com/1945230/35336683-da7a0986-0121-11e8-87eb-b7894b4c47d6.png)

http://vlad26lead_vladtest26.kademi-ci.co/team/
http://vladtest26.admin.kademi-ci.co/teamGroups/

**Comment by Uafinder** [comment]
looks like this happen because team-lib was not enabled when app was. So the dependency should be added.

**Comment by bradmac** [comment]
> looks like this happen because team-lib was not enabled when app was. So the dependency should be added.

Java apps dont have dependencies, so we need to create a marketplace app which depends on the java app and the lib.

**Comment by anhnt** [comment]
please restart QA and sync. then find KTeam app from marketplace

**Comment by Uafinder** [comment]
Looks good
