### ISSUE TITLE
Dynamic media asset missed image for keditor

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4843]
![image](https://user-images.githubusercontent.com/1945230/35338520-d3fde8ac-0126-11e8-9903-ee3d0e4ed3a0.png)
![image](https://user-images.githubusercontent.com/1945230/35338543-e311acf2-0126-11e8-9ec6-227e7a716bc3.png)
http://vladtest26.admin.kademi-ci.co/pages/vlad26website/version1/

**Comment by ducdhm** [comment]
We removed this component.
