### ISSUE TITLE
main menu element highlight - content types and asset manager

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4844]
When you on the asset manager page, content menu folder should not be collapsed and Asset manager menu item should be hightlighted
http://vladtest26.admin.kademi-ci.co/asset-manager/
![image](https://user-images.githubusercontent.com/1945230/35338909-ca332c0a-0127-11e8-8ab9-9b13c35fac6e.png)
![image](https://user-images.githubusercontent.com/1945230/35338921-d06578b2-0127-11e8-8706-a88e4e3ec63a.png)

When you on the content types page, this menu item should be highlighted:
http://vladtest26.admin.kademi-ci.co/content-types/
![image](https://user-images.githubusercontent.com/1945230/35338860-aaabcc2a-0127-11e8-8478-f7d483097c62.png)

**Comment by bradmac** [comment]
Looks like this has been fixed now

**Comment by Uafinder** [comment]
Yup, it works!
