### ISSUE TITLE
Auction components cause it appear on the frontend by multiple times

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4847]
![image](https://user-images.githubusercontent.com/1945230/35380721-c597235e-01c2-11e8-8bb9-cfaf08e6700e.png)
that's how it looks like on the editor
and that's how it looks like on the frontend:
![image](https://user-images.githubusercontent.com/1945230/35380767-df2760d6-01c2-11e8-97ca-dadb0fd33943.png)
![image](https://user-images.githubusercontent.com/1945230/35380777-e483c5ba-01c2-11e8-9e52-511df605f979.png)
Looks weird!
http://vladtest26.admin.kademi-ci.co/pages/vlad26auc/version1/

**Comment by ducdhm** [comment]
@bradmac Main issue here is `auctionDescriptionComponent`. This component is working only in detailed auction page. When drag in component and drop in any pages, this issue will occured. The code of this component is:

```
#if($page && "$!page.title" != "")
    <div class="auction-detail">
        <div class="clearfix auction-body">
            $!page.body
        </div>
    </div>
#else
    #fakeUI()
#end

#macro(fakeUI)
    <div class="auction-detail">
        <div class="clearfix auction-body">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis laborum molestias, odit asperiores nemo natus voluptate distinctio est sunt neque iste, quidem architecto, quos dolor repudiandae autem quae tenetur. Beatae officia, quas inventore nesciunt blanditiis quia, quidem repudiandae velit! Fugiat adipisci debitis eveniet, laudantium ipsam pariatur, dolorem eum tempore unde?
        </div>
    </div>
#end
```

So... what should I do?

**Comment by bradmac** [comment]
Hi @ducdhm please update the component so that
- it is only available for pages of type auction
- if somehow used on other pages it will display an appropriate error message

@Uafinder please ensure that you only use auction components (which require a specific auction) on an auction page template. I think we have components intended to be used on the dashboard etc which display a list of current auctions.

**Comment by ducdhm** [comment]
Done!

**Comment by Uafinder** [comment]
Yup, looks better
