### ISSUE TITLE
Auction title component shows page title instead of auction title

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4848]
![image](https://user-images.githubusercontent.com/1945230/35381145-f8ead9d4-01c3-11e8-81ba-324e3a81aacd.png)
![image](https://user-images.githubusercontent.com/1945230/35381154-fc0fe2c6-01c3-11e8-8c06-82034727ae68.png)
![image](https://user-images.githubusercontent.com/1945230/35381156-005ce2de-01c4-11e8-9f5c-48f9ce4faa1c.png)
http://vladtest26.admin.kademi-ci.co/pages/vlad26auc/version1/
1. Create a page
2. Add an auction title component
3. Note it display "page title"
4. Save
5. View in frontend - it will show page title

**Comment by ducdhm** [comment]
@Uafinder Fixed in other issue.

Note: In other issue, we decided to show this component only in Auction detailed page.

**Comment by Uafinder** [comment]
ok
