### ISSUE TITLE
Lowest Unique Bid Auction Current Bid should not be visible

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4850]
![image](https://user-images.githubusercontent.com/1945230/35387123-343ea304-01d7-11e8-8154-856e4feb83c6.png)
Current bid value for Lowest Unique Bid Auction (LUBA) is irrelevant. It should either always show a start value or it should be hided at all.
The start price of the auction on screenshot is 500. But it shows last bid, like it should be for regular auction. 
http://vladtest26.admin.kademi-ci.co/auctions/

p.s. also question about a step for placing bids... should we manage this parameter? Usually, LUBA bids are very precise and can take to 1 cent. E.g. 500.15, 500,17 and so on.

**Comment by bradmac** [comment]
- correct, do not display current bid for this type of auction
- bids must be whole numbers, ie integers

**Comment by gonzalon** [comment]
Not showing the last bid for LUB
![image](https://user-images.githubusercontent.com/2773216/35595347-4786f7f6-067b-11e8-9e4f-aa84a013476a.png)

**Comment by Uafinder** [comment]
Yup, it works!
