### ISSUE TITLE
Auction bid allow decimals question

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4851]
Do we allow users to enter decimals (numbers after comma) for bids?
If yes, there are an error appear:
![image](https://user-images.githubusercontent.com/1945230/35387930-6c47fe64-01da-11e8-8fe4-9c64a9eb08f6.png)
If no, we should remove two zeroes after dot, because it could be misunderstanded by user.
![image](https://user-images.githubusercontent.com/1945230/35387872-34126fca-01da-11e8-86c5-9183bb759e98.png)
http://vladtest26.admin.kademi-ci.co/auctions/

**Comment by bradmac** [comment]
yup, we should require it to be integer and only display as integer

we may have an auctions project soon so this is high priority

**Comment by gonzalon** [comment]
Fixed in 1.1.2

**Comment by Uafinder** [comment]
Please update lib version on CI
![image](https://user-images.githubusercontent.com/1945230/35616254-6342bc26-067d-11e8-9389-33f666d44acf.png)

**Comment by gonzalon** [comment]
Sorry!! now should be available to test it :)

**Comment by Uafinder** [comment]
Yeah, it works
No probs
