### ISSUE TITLE
Product categories bugs

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4852]
1. When parent category doesn't contain any product it will not show it on the frontend, even if some child categories contain products.
![image](https://user-images.githubusercontent.com/1945230/35390188-2e2e3130-01e3-11e8-8a1e-3c8102f0c2ae.png)
![image](https://user-images.githubusercontent.com/1945230/35390199-3aadd5aa-01e3-11e8-962e-3961641dda89.png)

2. When you add category as a child to another category this information is not being indexed correctly. For example:
You have two categories,
You adding some products to one of them, then add those products to a reward store
Then some time ago you want to add your category as a child to some another one which you just created. You add it, but it become invisible on the frontend.
Re-index helps.

3. When you have for example two parent categories, and one has some child categories and six products total and another one has child category and two products In it.
Now, attention,
- you access frontend reward store page
- it shows you all 8 products
- you click on the second parent category - screen is blinking, reloading and user can think that this is already a choosen category items, but no, it still shows 8 products
- going further, click on child category, it shows you only one product which is correct;
- then clicking to first parent category header - screen is blinking and reloading again, but you still see one product from the second category no matter of first category header already highlighted...
![image](https://user-images.githubusercontent.com/1945230/35390600-b7a86ec0-01e4-11e8-8d5f-5ba4d95d62c3.png)

http://vladtest27.admin.kademi-ci.co/categories/

**Comment by gonzalon** [comment]
1) Fixed here: https://github.com/Kademi/kademi-demos/issues/218
2) Spoke with Brad about this and as this is not such a frequent update it's going to stay like this for performance sake. So if we do a change like this we have to be aware that we need to re index.
3) At the moment that click was ment to be for collapse and show the child categories, going to update it to show the child categories AND show the products.

**Comment by gonzalon** [comment]
Fixed in rewardstore-lib 1.3.5

**Comment by Uafinder** [comment]
Ok, so
1. looks ok
2. Ok, no probs
3. Yup, looks good.
