### ISSUE TITLE
Team button is available for unregistered users

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4859]
![image](https://user-images.githubusercontent.com/1945230/35446885-c446b3b4-02be-11e8-86fa-4872999b053f.png)
http://vlad28leads-vladtest28.kademi-ci.co/

**Comment by bradmac** [comment]
Thats ok, its not unusual or unexpected for menu items to be displayed when a user is not logged in. Its only a problem if non-logged in users are able to see content

**Comment by Uafinder** [comment]
Ok, no probs
