### ISSUE TITLE
Team view button leads you to a team profile page where membersips are for currect user

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4860]
![image](https://user-images.githubusercontent.com/1945230/35447537-a5bbe8ea-02c0-11e8-9db6-a4374d47a5f9.png)
![image](https://user-images.githubusercontent.com/1945230/35447483-82b90bb6-02c0-11e8-8fa3-3c68fab36e0f.png)
Selected memberships are not for team member, it from current user.
http://vladtest28.admin.kademi-ci.co/manageUsers/4688806/#general-tab
http://vlad28leads-vladtest28.kademi-ci.co/team/

**Comment by bradmac** [comment]
We should update these components so that they display data from the user associated with the current page when the page is a LeadPage

**Comment by gonzalon** [comment]
I think its working as expected. I don't know the configuration you had at that moment but now:

The configure gropuup is "team-group"
![image](https://user-images.githubusercontent.com/2773216/36082370-ac95fb10-100d-11e8-8adc-cc646d4687bd.png)

What I see in /teams:
![image](https://user-images.githubusercontent.com/2773216/36082375-b4206b04-100d-11e8-94cd-65ea2a51eb94.png)

And from the manage users page:
![image](https://user-images.githubusercontent.com/2773216/36082384-ca80c2b8-100d-11e8-95cc-959ed2085cb4.png)

**Comment by Uafinder** [comment]
Yeah, looks good!
