### ISSUE TITLE
When product contains more than 2 variant types SKU bug appears

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4863]
1. Open product
2. Add three variant types: e.g. memory, size, color
3. Go to SKU
4. Type some SKU code for one of variants
5. Note that SKU title and SKU base cost fields will not be active
![image](https://user-images.githubusercontent.com/1945230/35503466-dfd8ae58-04e8-11e8-803d-138dfc25adda.png)
http://vladtest28.admin.kademi-ci.co/skus/

**Comment by bradmac** [comment]
yep, looks like the reload fragment isnt working correcty, probably because of the productid returning multiple rows

**Comment by Uafinder** [comment]
Also it cause image not appear after uploading...

**Comment by gonzalon** [comment]
Just tried in the account  http://vladtest28.admin.kademi-ci.co/skus/ and seems to be working fine

**Comment by Uafinder** [comment]
Yup, it looks ok at the moment
I will keep an eye on it
