### ISSUE TITLE
Minor console error while working with leads frontend

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4865]
![image](https://user-images.githubusercontent.com/1945230/35511669-83079244-0505-11e8-82ab-d46f999123d7.png)
http://vlad28leads_vladtest28.kademi-ci.co/dashboard
Something dedicated to datetimepicker lib
Is it ok, or it could be interesting to fix?

**Comment by bradmac** [comment]
@ducdhm what do you think?

**Comment by ducdhm** [comment]
It's not even a bug. It's just warning issue in console. And end-users never open console log for checking something like that. So it's acceptable

**Comment by Uafinder** [comment]
no probs... it's just FYI
