### ISSUE TITLE
Error in console while using quick lead edit feature 

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4866]
![image](https://user-images.githubusercontent.com/1945230/35512834-bf555a52-0509-11e8-902f-6e02380b513d.png)
1. Open Leads page
2. Check some assigned to:
3. Click on other place without selecting some...
http://vlad28leads_vladtest28.kademi-ci.co/leads/?query=&leadType=active
http://vladtest28.admin.kademi-ci.co

**Comment by gonzalon** [comment]
Found a similar issue trying to update the source too.
Both should be ok, latest version is 1.8.0

**Comment by Uafinder** [comment]
It works
