### ISSUE TITLE
Filter by assigned doesn't work when you're in sales group (in team)

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4867]
1. I've a member of team which should check sales date and watch teams
2. http://vlad28leads_vladtest28.kademi-ci.co/leads/?query=&leadType=active
3. Assigned to filter is empty
![image](https://user-images.githubusercontent.com/1945230/35515486-fa06253e-0511-11e8-8eee-d523ba501348.png)
http://vladtest28.admin.kademi-ci.co/websites/vlad28leads/version1/#panel_apps-tab

Also Teams page are inaccessible for him.
![image](https://user-images.githubusercontent.com/1945230/35515537-2812d9e0-0512-11e8-8392-14a77d4459be.png)

But seems like he has all necessary permissions
![image](https://user-images.githubusercontent.com/1945230/35515562-3db0adea-0512-11e8-81f4-c0042dffa0b9.png)

**Comment by gonzalon** [comment]
@Uafinder I just checked and to solve this issue you needed to add the user to the Sales group, because of the config of the leadman app.


![image](https://user-images.githubusercontent.com/2773216/35539682-7ed8674a-05b7-11e8-92ef-750bf65d868f.png)
http://vladtest28.admin.kademi-ci.co/manageUsers/4701727/#summary-tab

Web
![image](https://user-images.githubusercontent.com/2773216/35539693-8ba64d66-05b7-11e8-87c0-860eb50ea62b.png)

**Comment by Uafinder** [comment]
Ok, understood with first thing, but what is happening with Teams permissions? It's still bad...
![image](https://user-images.githubusercontent.com/1945230/35569182-1f4398c8-05d4-11e8-9a3e-f055347faf2d.png)
http://vladtest28.admin.kademi-ci.co/manageUsers/4701727/#summary-tab
http://vlad28leads-vladtest28.kademi-ci.co/team/

And one more:
Why when you select team dropdown filter. there are only org name?
![image](https://user-images.githubusercontent.com/1945230/35569253-66596760-05d4-11e8-903c-5c42cf7d3f67.png)

**Comment by gonzalon** [comment]
@Uafinder just checked on the code and the team dropdown, its being populated by the users memberships where the user has a the ROLE_SALES or ROLE_SALES_MANAGER or ROLE_SALES_TEAM_VIEWER.

So if the user adminqa has a membership to another org with one of those roles it should show there 


For the team page it was missing the user administrator for the org or repo.

**Comment by Uafinder** [comment]
Undesrtood...
So, probably most of problems will be sorted when we would have a MarketPlace app with necessary default settings.
