### ISSUE TITLE
Lowest Unique Bid auction - leader is not showing correctly in admin

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4870]
When a minimum bid placed by several users, in admin leader value disappear.
![image](https://user-images.githubusercontent.com/1945230/35616438-e42eb5ba-067d-11e8-949d-acab96ef7878.png)
![image](https://user-images.githubusercontent.com/1945230/35616501-18537e0c-067e-11e8-9a80-75de4e1586b8.png)
http://vladtest28h.admin.kademi-ci.co/auctions/

Also, when auction is ending there is no winner in the end

**Comment by gonzalon** [comment]
@Uafinder should't the leader be 106 as is the lower unique bid?

**Comment by Uafinder** [comment]
@gonzalon 
Yup, you're right. The leader should be 106 bid as it is a lowest unique

I mean that leader disappears when lowest bid is placed more than once.

**Comment by Uafinder** [comment]
Yup, it works like a charm!
