### ISSUE TITLE
Mtree error while open Keditor

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4871]
![image](https://user-images.githubusercontent.com/1945230/35622403-6b707f88-0690-11e8-9e48-8b255264b0fd.png)
http://vladtest28h.admin.kademi-ci.co
Open any page or template in keditor and you will see it...

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
Yup, looks better
