### ISSUE TITLE
Bulk upload files to assets - assets not appear in the list

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4872]
Using Bulk upload
1. open asset manager http://vladtest28j.admin.kademi-ci.co/asset-manager/
2. Click bulk upload
3. Upload some images
4. Upload successful but they don't appear in list
5. re-index doesn't help
![image](https://user-images.githubusercontent.com/1945230/35626309-ff839112-069d-11e8-8726-2c166cf5ed1a.png)

**Comment by bradmac** [comment]
Was missing transaction handling, should be fixed now

**Comment by Uafinder** [comment]
vlad 10:40 AM
i'm don't see that it fixed...
i've push bulk upload, upload some images and nothing is happened
new assets not apperar
http://vladtest28k.admin.kademi-ci.co/asset-manager/

brad 11:42 AM
ok, just assign back

**Comment by bradmac** [comment]
OK, should be fixed now.

**Comment by Uafinder** [comment]
Yeah, upload works successful
