### ISSUE TITLE
Asset manager filter bad when moving from content type page

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4873]
1. http://vladtest28j.admin.kademi-ci.co/content-types/IMAGE/
2. Then click asset manager
![image](https://user-images.githubusercontent.com/1945230/35628935-fcfaf806-06a5-11e8-867b-44c2a3a221b6.png)
3. 
![image](https://user-images.githubusercontent.com/1945230/35628945-05bcb790-06a6-11e8-9d5f-ca43aa6a2dd0.png)
Looks like it should change filter to view only assets of this type or it should show all assets...

**Comment by bradmac** [comment]
Fixed

**Comment by Uafinder** [comment]
Yup, works great
