### ISSUE TITLE
EDM Editor - Image edition icons missed on all components

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4875]
http://vladtest28k.admin.kademi-ci.co/groupEmails/4921540/#messages-tab
![image](https://user-images.githubusercontent.com/1945230/35668705-2f292e16-073b-11e8-8512-8393bccc458e.png)
![image](https://user-images.githubusercontent.com/1945230/35668713-35967448-073b-11e8-81da-292a3678e767.png)

And there is no image component in the component selection to the right!
![image](https://user-images.githubusercontent.com/1945230/35668735-4cf29d7e-073b-11e8-86e6-9834da616bbd.png)

**Comment by ducdhm** [comment]
@Uafinder You need enable email-lib to see image component. It's a part of email-lib for now

**Comment by bradmac** [comment]
hey @ducdhm we want vlad to test as if he is a user, and users must never be required to install libs

I dont think the photo component should be part of email-lib, its just a normal content item, so should be part of content-lib

that is a dependency of bootstrap-base so will be enabled for all sites regardless of what apps are enabled

**Comment by ducdhm** [comment]
@bradmac I dont agree with you about this. User wants to send an email but dont enable `email-lib` or `KEmail` app for their website. Is it right?

**Comment by bradmac** [comment]
The email app should not need to be enabled for a user to send emails. The email app at a website level is intended to provide an email inbox screen.

The photo component should be considered a normal content component, and we have one intended for use in web delivery and another for use with email, but its still a functional aspect of content editing

**Comment by ducdhm** [comment]
Understood and Done!

**Comment by Uafinder** [comment]
Yup, it works
