### ISSUE TITLE
Create a MarketPlace app for Teams

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4876]
https://github.com/Kademi/kademi-dev/issues/4867

Would be great to have a MarketPlace app to setup Teams with necessary roles and libs.

Vlad 11:48 PM
There is a problem when you enable teams it doesn't enable teams-lib

brad 11:48 PM
yes, because we dont have a marketplace app yet
but in the meantime you can just install teams-lib manually

**Comment by gonzalon** [comment]
Done here: https://github.com/Kademi/kademi-dev/issues/4842

**Comment by gonzalon** [comment]
We need to deploy to AU / US

**Comment by bradmac** [comment]
hey @gonzalon please ping me when you're ready and i'll show you how to deploy

**Comment by gonzalon** [comment]
Published
