### ISSUE TITLE
Possibility to add a custom link name instead of URL

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4880]
![image](https://user-images.githubusercontent.com/1945230/35680750-debde4d4-0763-11e8-97ae-f4ecc70115b4.png)
![image](https://user-images.githubusercontent.com/1945230/35680637-93e53e76-0763-11e8-973d-d71419849544.png)
to be link here
![image](https://user-images.githubusercontent.com/1945230/35680660-a3c536de-0763-11e8-8e5c-2f5a6cb61aff.png)
Like a <a href="https://www.w3schools.com/html/">Visit our HTML tutorial</a> instead of <a href="https://www.w3schools.com/html/">https://www.w3schools.com/html</a>
http://vladtest28k.admin.kademi-ci.co/pages/vlad28kweb/version1/

**Comment by bradmac** [comment]
hey Vlad, yes thats normal and currently supported.

Once a link is inserted you can simply edit the text of the link like normal text. Or you can highlight a piece of text and then click the link button to provide a link for the text.

**Comment by ducdhm** [comment]
@Uafinder: You can change the protocol to `Other` and insert any link you want

**Comment by Uafinder** [comment]
Yup, checked, looks good
