### ISSUE TITLE
Flash upload via text component doesn't work

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4883]
It looks that this component very obsolete...
![image](https://user-images.githubusercontent.com/1945230/35683312-34d44220-076c-11e8-8252-22c8ddfc6aa5.png)
http://vladtest28k.admin.kademi-ci.co/pages/vlad28kweb/version1/

upload doesn't work at all
![image](https://user-images.githubusercontent.com/1945230/35683337-493dbe58-076c-11e8-9051-c1fbff91e848.png)

**Comment by bradmac** [comment]
yes, please remove that button

**Comment by ducdhm** [comment]
Done!

**Comment by Uafinder** [comment]
Yup, tab was removed
