### ISSUE TITLE
keditor page background question

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4885]
This how it looks in the editor
![image](https://user-images.githubusercontent.com/1945230/35684875-dc86bbde-0770-11e8-9849-c39b1bc23e78.png)

This how it looks on the frontend
![image](https://user-images.githubusercontent.com/1945230/35684924-f9dc9e2e-0770-11e8-910b-0472630bf8de.png)

Upper part of image is cropped on the frontend.
The difference looks like in a upper panel
Should it be like it at the moment or background should looks like in the editor...

http://vladtest28k.admin.kademi-ci.co/pages/vlad28kweb/version1/

**Comment by bradmac** [comment]
I think its just because the bg is being vertically centred. You have other options for the position to adjust as required

**Comment by bradmac** [comment]
Note that the difference in appearance is due to the difference in height which is expected

**Comment by Uafinder** [comment]
Ok, no probs... just clarifying
