### ISSUE TITLE
Weird auction timer behaviour

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4887]
![image](https://user-images.githubusercontent.com/1945230/35722533-5f45cbee-07ff-11e8-88ef-2f73a320b9bf.png)
![image](https://user-images.githubusercontent.com/1945230/35722546-6dfbce40-07ff-11e8-86cd-ca4b0cfbde74.png)
I've an auction which should end in a hour from now, but timer shows that it will end in some minutes
http://vladtest28m.admin.kademi-ci.co/auctions/aucqa01/#details-tab

And in the end of this time it shows
![image](https://user-images.githubusercontent.com/1945230/35722847-a40b702a-0800-11e8-90fa-b1da07423a05.png)
But when you enter to bid it, it will show that 43 minutes left
![image](https://user-images.githubusercontent.com/1945230/35722881-c5a862e2-0800-11e8-8b95-660526899993.png)

Steps to reproduce
1. check local time, note minutes e.g. 10:15 means 15 minutes
2. create an auction which will longs for an hour
3. set it as active
4. go to frontend and watch that it will show 45 minutes instead of hour

**Comment by gonzalon** [comment]
@Uafinder 
 - coudln't reproduce the creation time issue
- the issue was that it was showing the wrong countdown, so when it showed it was finished it was wrong.

**Comment by Uafinder** [comment]
Nope, issue still there.
I've just create it, and it should longs for an hour
http://vladtest30e.admin.kademi-ci.co/auctions/aucqa01/#details-tab
So, read carefully:
1. Create an auction, select basic start time and finish time in a hour. just click on starrt date field and then just click on the end date field.
2. Going next, note current time (for example 1:20)
3. Then edit auction, set is as active
4. Then go to frontend to the auctions page
5. check counter of the auction.
6. Note that timer shows time to next hour start, not for end time of auction. E.g.
![image](https://user-images.githubusercontent.com/1945230/35913946-2777cdc0-0c0a-11e8-9a59-03988bb7a7c3.png)
![image](https://user-images.githubusercontent.com/1945230/35913785-90bf561e-0c09-11e8-9471-9801bad43503.png)

**Comment by gonzalon** [comment]
@Uafinder sorry forgot to mention that the latest lib for auctions was 1.1.2

Just updated the lib and did the test in your account. 

![image](https://user-images.githubusercontent.com/2773216/35940254-6fba7962-0cb3-11e8-831a-b985fdd987e0.png)

**Comment by Uafinder** [comment]
yup, looks better
