### ISSUE TITLE
Keditor - Lot of lead components missed thumbnail images

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4889]
![image](https://user-images.githubusercontent.com/1945230/35730257-0ba8c75a-081a-11e8-828a-811aa21c5844.png)

http://vladtest28n.admin.kademi-ci.co/websites/vlad28nlead/version1?editTemplate=theme/apps/leadman/viewLead

**Comment by anhnt** [comment]
Done

**Comment by Uafinder** [comment]
Ok, looks good
