### ISSUE TITLE
Kcodes for leadman question

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4890]
I can't add Kcodes for leads to see them works
I've add them on the lead page (viewLead template) and completely new page
But I can't see them on the frontend.
Please assist...
http://vladtest28n.admin.kademi-ci.co/pages/vlad28nlead/version1/
All necessary app are installed.

**Comment by bradmac** [comment]
Here's an example using an EDM which should demonstrate it

![image](https://user-images.githubusercontent.com/826458/35833287-68a346d8-0b35-11e8-8a74-f20ace38fa91.png)

http://vladtest28n.admin.kademi-ci.co/funnels/nurture-journey/version1/#journeyBuilder-tab

**Comment by Uafinder** [comment]
Finally get a result in my environment :)
