### ISSUE TITLE
Keditor - website list component links incorrect

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4892]
![image](https://user-images.githubusercontent.com/1945230/35738281-0a23e30c-0837-11e8-85ee-1ce26c3339c2.png)
![image](https://user-images.githubusercontent.com/1945230/35738289-11d884c2-0837-11e8-9bcd-0bc6a55a2dcc.png)
![image](https://user-images.githubusercontent.com/1945230/35738300-1dc522a4-0837-11e8-9cfe-a2d7150985cd.png)
http://vladtest29.admin.kademi-ci.co/pages/vlad29web/version1/

**Comment by ducdhm** [comment]
@Uafinder These components are available only for Dashboard. Not for website.

**Comment by Uafinder** [comment]
You mean like this?
http://version1.vlad29web-vladtest29.kademi-ci.co/dashboard

**Comment by Uafinder** [comment]
Yup, realized where it's located
