### ISSUE TITLE
Category List

### ISSUE THREAD

**Issue by faithtek** [Kademi/kademi-dev#4894]
After an update to the Categories List last week, to allow when clicking on a category to show all products in the category that was clicked on and all sub-categories, I now get the following error:

This can be found at this site: http://version1.devsite01-asrdev.kademi.us/general-1/

Error rendering component: rewardStoreCategoriesList
class org.apache.velocity.exception.MethodInvocationException - Invocation of method 'getChildren' in class com.fuselms.apps.rewardstore.RewardStoreFolder threw exception java.lang.ClassCastException: org.elasticsearch.search.aggregations.bucket.terms.UnmappedTerms cannot be cast to org.elasticsearch.search.aggregations.bucket.terms.LongTerms at devsite01-asrdev.kademi.us:/theme/apps/rewardstore/components/rewardStoreCategoriesListComponent.html[line 30, column 83]

**Comment by gonzalon** [comment]
Hi @faithtek we needed to re-index the data as there was an update in the indexes. Just did that and seems to be working fine now. Can you double check? Thanks

**Comment by faithtek** [comment]
Fixed.
