### ISSUE TITLE
Video asset doesn't play preview in selector

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4897]
![image](https://user-images.githubusercontent.com/1945230/35853411-1369bcf0-0b36-11e8-8c4f-0ec4bd4dc64d.png)
http://vladtest30b.admin.kademi-ci.co/websites/vlad30bweb/version1/programs/p1/c1/m1/#files-tab
1. Go to page
2. Add video component
3. Push change video
4. Click on assets tab
5. Upload some video
6. After it allows you to press play - press play
7. Video will not play and gives an error in console

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
ok, it fixed on the preview of uploader, but still remains on the page preview
![image](https://user-images.githubusercontent.com/1945230/35965611-20cb2408-0cc4-11e8-8e35-f7507592c3af.png)
http://vladtest31a.admin.kademi-ci.co/pages/vlad31aweb/version1/

**Comment by Uafinder** [comment]
Yup, it works!
