### ISSUE TITLE
Creating a new blog article does not save the 'brief' field content

### ISSUE THREAD

**Issue by OzrenOrchard** [Kademi/kademi-dev#490]
Hey guys, we have an issue with creating blog content (http://admin.zoetis.olhub.com/blogs/), where the first create/save attempt does not capture the brief field content. Please see below.

We create a new blog through the admin interface.
![create a new article](https://cloud.githubusercontent.com/assets/7787717/8490625/4d8e3c7a-216f-11e5-8e45-49ccb74d327e.PNG)

Content for the blog is added to the 'brief' section, and then the article is saved.
![article created text added and saved](https://cloud.githubusercontent.com/assets/7787717/8490901/2318b9de-2174-11e5-8224-23496172236d.PNG)

However the 'brief' content does not save on the first entry. It can be updated after, but it does not save initially.
![content wasnt saved only title](https://cloud.githubusercontent.com/assets/7787717/8490905/4696de40-2174-11e5-91dc-a818bfce4c5e.PNG)

Cheers

**Comment by tuzzmaniandevil** [comment]
I have corrected this issue and the fix will be available when milestone 2015-07-m30 gets released.
