### ISSUE TITLE
Exception when adding AssetQuery

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#4900]
When adding a new AssetQuery an NPE is thrown, that's because the query asset doesn't return asset types and so the onCreate tries to iterate through null.

**Comment by mkhoudary** [comment]
Fixed.. @bradmac I'd suggest that the getAssetType method returns Collections.EMPTY_LIST when no types found.. but want to check with you first that returning null wasn't intentional.

**Comment by bradmac** [comment]
@mkhoudary you should not just always return an empty list. Its perfectly valid to return a null list in situations where there is no defined list, or its not possible to find a list. 

On the client side it should not assume the list will not be null.
