### ISSUE TITLE
Keditor video uploading progress-bar absent

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4901]
1. Open page for edit
2. Add some video component
3. Change video button
4. Upload some video
5. When you push upload, the uploading process is going in background without any progress bar which can be confusing for end user.

For example image uploading have progress bar
Uploading in progress for video
![image](https://user-images.githubusercontent.com/1945230/35861055-0f0a32a2-0b4f-11e8-8794-7af37182c496.png)
Uploading in progress for image
![image](https://user-images.githubusercontent.com/1945230/35861677-6f9ef6be-0b51-11e8-89ea-ad941138e3b9.png)

http://vladtest30b.admin.kademi-ci.co/websites/vlad30bweb/version1/programs/p1/c1/m1/#files-tab

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
Works like a charm!
