### ISSUE TITLE
badge minor bug when adding left or right margin

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4903]
![image](https://user-images.githubusercontent.com/1945230/35867511-975fe364-0b62-11e8-8389-6bbdf53070b2.png)
You select 3 badges per line, but when you add side margins it becomes 2 per line.
http://vladtest30c.admin.kademi-ci.co/pages/vlad30cweb/version1/

**Comment by bradmac** [comment]
@Uafinder that is expected behaviour when using internal padding.
