### ISSUE TITLE
Keditor not loading on US or AU

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4904]
Has loading icon, but the page does not load.

http://kademi.admin.kademi.us/websites/demo-site/version1/programs/test/c1/m1/#files-tab
http://100things.admin.kademi.com.au/websites/100things-development/version1/programs/Test/test/test/#files-tab

**Comment by ducdhm** [comment]
Done!

**Comment by paddyow** [comment]
Does not load on this account http://moblix-intratrain.admin.kademi.us/pages/moblix-employees/version1/

Click dashboard.

**Comment by bradmac** [comment]
please try now

**Comment by bradmac** [comment]
I enabled
- ckeditor-lib
- mtree-lib
- mselect-lib

**Comment by paddyow** [comment]
Great
