### ISSUE TITLE
EDM editor in journeys not show images in preview

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4907]
![image](https://user-images.githubusercontent.com/1945230/35915888-47bd128c-0c11-11e8-8044-dfd6293cfa02.png)
![image](https://user-images.githubusercontent.com/1945230/35915898-52e87b7e-0c11-11e8-83a2-e15ce9ec5627.png)

http://vladtest30e.admin.kademi-ci.co/funnels/first-journey/version1/emailAction-d06c3f/#message-tab

1. edit email node
2. Push edit message
3. Add some content
4. Press save and close edm
5. Note that text appears successfully but images not appear.

**Comment by ducdhm** [comment]
@bradmac Can you help me check this issue? I dont know why photoEDM component is not showed in funnel. I select website for email node and `content-lib` is enabled.

**Comment by bradmac** [comment]
@ducdhm i think its because we're displaying raw (non-rendered) content in the funnel EDM preview.

I've seen the same issue with the password reset component.

Thats something for me to deal with :)

**Comment by bradmac** [comment]
ok, done

![image](https://user-images.githubusercontent.com/826458/35954882-0ebf6102-0cf1-11e8-9c83-83c07f4c37b8.png)

**Comment by Uafinder** [comment]
Looks bad:
1. When you open message tab of email node it shows some backend stuff
![image](https://user-images.githubusercontent.com/1945230/35965278-0d45fc10-0cc3-11e8-868e-e67aeb0817e9.png)

2. When you open editor, add some stuff, press save and push close button - editor is not closing. And error in console appears.
![image](https://user-images.githubusercontent.com/1945230/35965394-6a2092b0-0cc3-11e8-920b-6e5fa9690da5.png)

http://vladtest31a.admin.kademi-ci.co/funnels/first-journey/version1/email1/#message-tab

**Comment by bradmac** [comment]
> When you open message tab of email node it shows some backend stuff

Fixed

**Comment by bradmac** [comment]
> When you open editor, add some stuff, press save and push close button - editor is not closing. And error in console appears.

Fixed

**Comment by Uafinder** [comment]
Yup, it works!
