### ISSUE TITLE
Issue when selecting categories while adding products to a reward store

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4908]
When you select some category, simply nothing is happened
I've tried to reboot server and clear cache
Here is a video:
https://drive.google.com/file/d/1AcDHwBWpfFpaqQIxETZK-9iq7NhZmSR9/view?usp=sharing
http://vladtest30e.admin.kademi-ci.co/reward-store/vlad30eweb-store/?addProducts

**Comment by gonzalon** [comment]
@Vlad i just test it in your account I can add products to the reward store whitout problems. 
The video you linked is another one :P can you still reproduce it?

**Comment by bradmac** [comment]
hey @gonzalon the page load time for a query is very slow. I'm seeing 6000ms when selecting a category.

Can you look into that?

**Comment by Uafinder** [comment]
Ooops, guys...
My mistake about video
The original was
https://drive.google.com/open?id=1k99E-J-2AUY9kOv5fZPzESCpHMkr5o4F
Anyway, will retest

**Comment by Uafinder** [comment]
But the problem persists...
Issue that when you accessing add products page and click on the some category - nothing is happened, filtering is not going.
![image](https://user-images.githubusercontent.com/1945230/35970233-48ef7c78-0cd2-11e8-9ce9-9d9799a71580.png)
![image](https://user-images.githubusercontent.com/1945230/35970243-4f1e388c-0cd2-11e8-95f5-bf9522693d32.png)
http://vladtest31a.admin.kademi-ci.co/reward-store/vlad31aweb-store/?addProducts

**Comment by Uafinder** [comment]
It's probably because of long page loading
![image](https://user-images.githubusercontent.com/1945230/35970528-501599f0-0cd3-11e8-88ec-5b6c8912598b.png)

**Comment by gonzalon** [comment]
Did some changes isnt going up of ~1.3 sec

![image](https://user-images.githubusercontent.com/2773216/36001421-1301b9d2-0d8b-11e8-8843-16bb844a6015.png)

**Comment by Uafinder** [comment]
Looks better
