### ISSUE TITLE
product images page works very very slow when a lot of products present

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4909]
![image](https://user-images.githubusercontent.com/1945230/35923266-6422da3a-0c28-11e8-9f77-72fb921ce334.png)
1. Loading takes to 30 secs
2. Every uploaded image cause renewal of this page, which also takes 30secs*x - products

http://vladtest30e.admin.kademi-ci.co/products/

**Comment by bradmac** [comment]
Problem is that we're iterating over each product looking for images. When there are lots of products, this takes a very long time

```
            for (Product p : products) {
                if (p.getImages() != null) {
                    int i = 0;
                    for (ItemImage pi : p.getImages()) {
```

23000 queries..

![image](https://user-images.githubusercontent.com/826458/35942856-1500d850-0cbc-11e8-9f08-1fc13823f45a.png)
**

**Comment by bradmac** [comment]
@gonzalon please refactor to query directly for ProductImage, instead of iterating over products

**Comment by Uafinder** [comment]
Same results for me, fresh account and 7700 products.
~50 sec for page loading
~ 2-3 minutes to add three images
![image](https://user-images.githubusercontent.com/1945230/35969843-dfacf070-0cd0-11e8-840a-2830fb43b463.png)
http://vladtest31a.admin.kademi-ci.co/product-images/

**Comment by gonzalon** [comment]
After adding some indexes in the database its loading in ~35 ms

**Comment by Uafinder** [comment]
Works much faster
