### ISSUE TITLE
Points Importer- Unable to set reason code

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#4912]
Should be able to use the Points tag column to set the reason code on a points debit. This is determined by the points column, If it's negative it's a points debit

**Comment by Uafinder** [comment]
Yes, when value is negative - it works like debit, but it doesn't setup points tag
[Downloads.zip](https://github.com/Kademi/kademi-dev/files/1707006/Downloads.zip)
I've upload 150 users file
then upload points 2 file
the try to upload points 2 debits file
http://vladtest31a.admin.kademi-ci.co/points-buckets/points/

**Comment by tuzzmaniandevil** [comment]
CI Wasn't running the latest code, Updated and works

**Comment by Uafinder** [comment]
Yup, it works!
