### ISSUE TITLE
EDM editor issues

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4913]
Editor not opening here:
https://insured.admin.kademi.com.au/autoEmails/76842252/edmeditor?fileName=index.html&useHash=true

And..
https://insured.admin.kademi.com.au/funnels/policy-review/version1/emailAction-4202e0/#message-tab

And..
http://insured-crm_insured.kademi.com.au//theme/apps/user/contenteditor?fileName=dashboard.html

**Comment by ducdhm** [comment]
Fixed! Make sure you clean your browser cache

**Comment by bradmac** [comment]
Looks good!
