### ISSUE TITLE
Leaderboard EDM components

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4915]
Please create new components for use with EDMs for
- displaying a points leaderboard. Allow selecting the number to show (and always show the current user)
- displaying a KPI leaderboard. Allow selecting the KPI, and also allow the editor to choose to either display for the current (in progress) period, or the most recently assessed period

**Comment by bradmac** [comment]
Simple but should be ok for now

![image](https://user-images.githubusercontent.com/826458/36131669-c8daf72e-10d7-11e8-8629-762be306d79c.png)

**Comment by gonzalon** [comment]
![image](https://user-images.githubusercontent.com/2773216/36567046-21e44802-188a-11e8-9dc0-a0bde4f1f878.png)

**Comment by bradmac** [comment]
@gonzalon can you make the col headings left aligned?

**Comment by Uafinder** [comment]
I can't see any rank or header...
![image](https://user-images.githubusercontent.com/1945230/36599375-dc872e5e-18b7-11e8-9ada-2fd2d0d4661d.png)
http://vladtest37a.admin.kademi-ci.co/groupEmails/6637068/#messages-tab

I can't see any leaderboard component in the end email
![image](https://user-images.githubusercontent.com/1945230/36599528-5056d4a6-18b8-11e8-9765-a28ef766dc4a.png)
![image](https://user-images.githubusercontent.com/1945230/36599550-5cd0d182-18b8-11e8-9f2e-f5ce1d600130.png)

**Comment by gonzalon** [comment]
http://gnztest16.admin.kademi-ci.co/

![image](https://user-images.githubusercontent.com/2773216/36763155-95d7d328-1c8b-11e8-8e10-dadf206b6159.png)

**Comment by Uafinder** [comment]
Yup, it works, but:
1. Current user appears twice in list
![image](https://user-images.githubusercontent.com/1945230/36848485-03dc5edc-1d6a-11e8-9e3f-c04d4c5f70dd.png)

2. Still doesn't see rank column at all (and no option to force it to appear)

**Comment by bradmac** [comment]
@gonzalon please
- add an option for whether or not to display the user's name (this often needs to be hidden)
- ensure the current user is only displayed once (either in rankings or added to end)
- always display the ranking

**Comment by bradmac** [comment]
> ensure the current user is only displayed once (either in rankings or added to end)

I jsut pushed a fix

**Comment by Uafinder** [comment]
Ok, mostly works
Non-critical moving to another issue
