### ISSUE TITLE
Products page filter by category, add products to category

### ISSUE THREAD

**Issue by gonzalon** [Kademi/kademi-dev#4916]
From https://github.com/Kademi/kademi-dev/issues/4910

Add a filter as the one in the reward store.
![image](https://user-images.githubusercontent.com/2773216/35953333-fa41dc76-0ce8-11e8-9219-f6e17f82e5b3.png)

Can select and add products to categories. (UI similar to add users to groups)

![image](https://user-images.githubusercontent.com/2773216/35953341-0587ddc4-0ce9-11e8-8cc4-8cb12744f45e.png)

**Comment by bradmac** [comment]
Improved category selection. Moved the initial list display to ajax which fixed state management in the jquery plugin.

**Comment by Uafinder** [comment]
looks good
