### ISSUE TITLE
contact form not loading user

### ISSUE THREAD

**Issue by Anton69arb** [Kademi/kademi-dev#4921]
Hey, When adding user details from the landing page, the user is not being uploaded to a group, if you go to manage contact requests, you will see the name there but it's not being added to users

http://version1.consumer-nurture-campaign_moblixdemo.kademi.us/
https://moblixdemo.admin.kademi.us/manageContacts/
![1](https://user-images.githubusercontent.com/32444328/36008930-9107440a-0dae-11e8-8aef-046d604f83d1.png)

**Comment by bradmac** [comment]
The problem here is that no profile is being created.

**Comment by gonzalon** [comment]
The app was off! Changed that, and configured the group.

**Comment by bradmac** [comment]
@gonzalon the issue here is that a contact request was created, but a profile wasnt

if the app was off then no contact request should have been created.

can you please re-check?

Also, if any changes are needed please just advise @Anton69arb what they are.

**Comment by Uafinder** [comment]
in that case when app is not enabled for a website, page gives an error, otherwise it successfully get a user and create a profile for it
for those accounts apps could be enabled by hands not via MarketPlace
