### ISSUE TITLE
Opening any product fails due to Unexpected identifier error

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4922]
![image](https://user-images.githubusercontent.com/1945230/36023259-7ff9cf4e-0d94-11e8-8abd-5e38392d9a60.png)
As a result no product functionality is not working: add variant type, add field, save, etc
http://vladtest31b.admin.kademi-ci.co/products/fitbit000/#variants-tab

**Comment by ducdhm** [comment]
Done!

**Comment by Uafinder** [comment]
Yup, looks good
