### ISSUE TITLE
Create learning program cause some weird course and module appear 

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4923]
![image](https://user-images.githubusercontent.com/1945230/36025520-0317af84-0d9c-11e8-8ee3-e5fc2e5c5078.png)
1. Create a program
2. Check for weird things
http://vladtest31c.admin.kademi-ci.co/websites/vlad31cweb1/version1/programs/pr1/

**Comment by bradmac** [comment]
Fixed

**Comment by Uafinder** [comment]
Yup, it works!
