### ISSUE TITLE
Cannot close EDM editor window

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4925]
http://100things.admin.kademi.com.au/funnels/onboarding/version1/emailAction-2f727d/#message-tab

Clicking the close button does nothing

![image](https://user-images.githubusercontent.com/2201340/36059142-31fc3f00-0e86-11e8-8763-b118d1a0fbf2.png)

**Comment by bradmac** [comment]
I think this has already been fixed, but not deployed

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
Yup, it works in prod and ci both...
