### ISSUE TITLE
EDM images not rendering in email client

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4926]
http://100things.admin.kademi.com.au/funnels/onboarding/version1/emailAction-2f727d/#message-tab

Created the above email
Added some content and a header image
Fired off to to this profile http://100things.admin.kademi.com.au/manageUsers/100973010/#emailAppTab-tab

Image renders when you look at it in Kademi, but not in Mailinator or my personal email client Thunderbird.

![image](https://user-images.githubusercontent.com/2201340/36059195-454f6838-0e87-11e8-96b8-4ba51d8821e2.png)

![image](https://user-images.githubusercontent.com/2201340/36059200-486c6cd2-0e87-11e8-9c23-d96d504c6489.png)

**Comment by bradmac** [comment]
the new photoEDM component is generating a link with the path only, it also needs the host name:
```
<img src="/_hashes/files/1a18c34bc573cf936bb289600fb615c6e18107bb" style="display: block; border: 0;" alt="" width="212" height="">
```

**Comment by paddyow** [comment]
Note this is across all emails templates, journeys, triggers etc

**Comment by bradmac** [comment]
Fixed, but requires deploy and new content-lib

**Comment by Uafinder** [comment]
https://github.com/Kademi/kademi-dev/issues/4933
probably the result of the fix
![image](https://user-images.githubusercontent.com/1945230/36096508-5690eefe-0fff-11e8-84e9-c145cd69acb0.png)
In journeys and send emails as well

**Comment by bradmac** [comment]
OK, there's a few aspects to this..
- if there is no website selected for an email then resources (ie images) will be loaded from the admin URL. This generally will not be allowed
- if there is a website selected, then resources will be loaded from there. This will still fail unless there is some permission in place to do it..
- The system now provides an asset type by default called "public" which has public viewing permissions. This is tagged automatically to newly uploaded images.
- Also, the system now automatically creates a "public" group for new accounts, which is given content viewing role, so even without the new asset type images should be viewable through websites

![image](https://user-images.githubusercontent.com/826458/36127267-73e5e96a-10c1-11e8-90c2-5352777b9700.png)

![image](https://user-images.githubusercontent.com/826458/36127297-976fd954-10c1-11e8-9ca8-c3972c4f9548.png)

**Comment by Uafinder** [comment]
It looks ok
