### ISSUE TITLE
Course picker displaying courses in wrong order

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4929]
This profile http://100things.admin.kademi.com.au/manageUsers/101041141/#summary-tab

![image](https://user-images.githubusercontent.com/2201340/36067785-de43bb34-0f18-11e8-9588-32dbaa9542cc.png)

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
yup, looks good
