### ISSUE TITLE
Profile template

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4931]
Points panel needs to appear in the profile template as a component so it can be removed or moved around.

![image](https://user-images.githubusercontent.com/2201340/36067843-a967acfc-0f1a-11e8-8501-cdb69e5a31e9.png)

**Comment by bradmac** [comment]
Currently we have a portlet in templates/apps/rewardstore/transactions.html

Please copy this into a component

**Comment by ducdhm** [comment]
Done!

**Comment by Uafinder** [comment]
I see it in editor
![image](https://user-images.githubusercontent.com/1945230/36934081-4ec87092-1eec-11e8-9f11-0468946cd1d4.png)
but not in frontend
![image](https://user-images.githubusercontent.com/1945230/36934090-66eb8326-1eec-11e8-97c5-884078a51ad2.png)
http://version1.vladtest38caucstore-vladtest38c.kademi-ci.co/profile/
http://vladtest38c.admin.kademi-ci.co/pages/vladtest38caucstore/version1/

Also, this component is only visible while you're in reward store site. Is it ok?

**Comment by ducdhm** [comment]
@Uafinder In editor, it's just sample data which let content creator knows how the component looks like. In frontend, it's can be blank when no data

**Comment by bradmac** [comment]
hey @ducdhm that component should not be blank when there's no transactions.

Its important that users can see it, and it should say "No transactions" and their balance is zero

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
Ok, component appears, but no data in it
![image](https://user-images.githubusercontent.com/1945230/36979050-f72674ac-208e-11e8-95c0-e9c30b74df9a.png)
http://vladtest38d.admin.kademi-ci.co/manageUsers/8080971/#pointsBucketTab-tab
![image](https://user-images.githubusercontent.com/1945230/36979060-ff170302-208e-11e8-8098-1ee38e992506.png)
http://vladtest38daucstore-vladtest38d.kademi-ci.co/profile/

**Comment by bradmac** [comment]
Changed to handle multiple participants, and fixed API call to lookup transactions

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/36999272-7dc84df6-2124-11e8-9ac0-bff5fdb081e8.png)

**Comment by bradmac** [comment]
@Uafinder please check the situation where a points bucket has organisation attribution, and a user is in two such organisations. It should show 2 transactions tables each with the name of the organisation

**Comment by Uafinder** [comment]
Ok, there is problem
Points which are allocated to organisation is not seeing in user profile.
![image](https://user-images.githubusercontent.com/1945230/37039024-18f2c07e-215f-11e8-9957-9341cfdac360.png)
![image](https://user-images.githubusercontent.com/1945230/37039065-314e9ad0-215f-11e8-839a-6ede97b56490.png)
http://vladtest39.admin.kademi-ci.co/points-buckets/points

However it appears in organisation profile
![image](https://user-images.githubusercontent.com/1945230/37039428-218da1bc-2160-11e8-95ec-46401e6cfe9a.png)

So, the question is: where it should appear?

**Comment by bradmac** [comment]
@Uafinder the points bucket is configured for individual points, not organisation:
http://vladtest39.admin.kademi-ci.co/points-buckets/vladtest39aucstore-points/#details-tab

![image](https://user-images.githubusercontent.com/826458/37068501-e34759fc-2213-11e8-81bb-73ab8c8fbf17.png)

To test with organisation based points first please create a points bucket with organisation attribution, then select an org type for the type of organisations who can receive those points. Then create an organisation of that type, then associate a user with it

**Comment by bradmac** [comment]
Two of the points buckets are not configured for recipients:

![image](https://user-images.githubusercontent.com/826458/37083189-ad251db0-2253-11e8-8029-eb3611882199.png)

Please select an org type or group for each one

**Comment by Uafinder** [comment]
Ok, question:

Should points awarded to organisation be showed in user profile which are a member of this organisation?

**Comment by gonzalon** [comment]
@Uafinder I tested locally and seems working fine, you need to create a reward store for that point bucket and website for it to show in the transactions.

**Comment by Uafinder** [comment]
ok, seems like I was able to see it.
