### ISSUE TITLE
KSurvey statistics, results not shown

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4932]
We should be seeing results here:
![image](https://user-images.githubusercontent.com/826458/36077574-6f1c0e78-0fd1-11e8-9cf4-17b9feccb093.png)

http://gilead.admin.kademi.us/ksurvey/survey-7c8f8bc6-575a-48c4-b431-f97f5c136a25/#statistic-tab

**Comment by ducdhm** [comment]
@mrdadah I fixed issue with total submissions in list survey page

**Comment by ducdhm** [comment]
@mkhoudary As I double-checked all functions like `Clear result by user` or `Clear all result` in my local, all are working normally. Please re-check again. If you get any issues, please give me step by step to reproduce.
