### ISSUE TITLE
EDM for journeys photo component image not showing

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4933]
![image](https://user-images.githubusercontent.com/1945230/36090372-d3e6f3ce-0fe8-11e8-90b7-f88836c890b4.png)
1. Create a journey
2. Add email node
3. Edit email
4. Open visual editor
5. Add some photo component
6. Upload image, click ok
7. Image will not be shown in editor and in preview.
http://vladtest32.admin.kademi-ci.co/funnels/first-journey/version1/email1/#message-tab

**Comment by ducdhm** [comment]
Depends on https://github.com/Kademi/kademi-dev/issues/4926

**Comment by bradmac** [comment]
Duplicate of https://github.com/Kademi/kademi-dev/issues/4926
