### ISSUE TITLE
Filter by Opened emails doesn't work

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4934]
well, When email is opened it's get this status
but
when you try to find all opened emails using a filter it shows that no opened emails in list
![image](https://user-images.githubusercontent.com/1945230/36096038-38d68290-0ffd-11e8-9659-4494327e0a3e.png)
![image](https://user-images.githubusercontent.com/1945230/36096042-41bfd988-0ffd-11e8-917b-da622be53084.png)
http://vladtest32.admin.kademi-ci.co/emails/?q=&status=o&job=

**Comment by bradmac** [comment]
This problem was because the index wasnt being updated when emails were opened. After reindexing they appear.

I've corrected the problem with index not being updated when emails are opened.

**Comment by Uafinder** [comment]
Yup, it works!
