### ISSUE TITLE
When upload images to auction details it should filter files by type

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4935]
![image](https://user-images.githubusercontent.com/1945230/36141254-bca1d732-10ac-11e8-8d25-f1687bdc9719.png)
![image](https://user-images.githubusercontent.com/1945230/36097459-bf7d12e0-1003-11e8-9f5d-16d6b84a5b06.png)
it should show only files with image file types.
http://vladtest32.admin.kademi-ci.co/auctions/aucqa01/#details-tab

Same thing with Module thumbnail images
![image](https://user-images.githubusercontent.com/1945230/36141319-ed939d26-10ac-11e8-9628-6af6021d13bd.png)
![image](https://user-images.githubusercontent.com/1945230/36141338-01a4d8c0-10ad-11e8-8b4b-ae029182f91f.png)

**Comment by ducdhm** [comment]
Done!

**Comment by Uafinder** [comment]
yup, it works!
