### ISSUE TITLE
Auctions list component doesn't show auctions on the frontend

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4936]
http://vladtest32a.admin.kademi-ci.co/pages/vlad32aweb/version1/
![image](https://user-images.githubusercontent.com/1945230/36099177-565dfebc-100a-11e8-913c-4199558a7641.png)
![image](https://user-images.githubusercontent.com/1945230/36099183-5d206640-100a-11e8-989f-80acd837f120.png)
I've added auctions list component, setup it a bit and wanna to check it on the frontend. It doesn't show auctions list.

**Comment by bradmac** [comment]
This component is currently only working on the /auctions page
```
#foreach($auction in $page.childrenWithPermission.sortByExpr("auctionEndDate"))
```

**Comment by bradmac** [comment]
@ducdhm please change this to work on any page by looking up the auctions page

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
It works
