### ISSUE TITLE
kEditor bug when editing image

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4937]
1. Create page
2. Add some text component
3. Push image button there
4. Upload to asset or select some image from the asset
5. Push edit
6. Edit some
7. Push save
Image will not appear on the page
http://vladtest32.admin.kademi-ci.co/pages/vlad31bweb7/version1/
![image](https://user-images.githubusercontent.com/1945230/36101607-8204ba26-1012-11e8-80d8-4c55dbf6d7ed.png)
![image](https://user-images.githubusercontent.com/1945230/36101570-6753f52a-1012-11e8-8e2b-34e82a7796a0.png)

**Comment by ducdhm** [comment]
Depends on https://github.com/Kademi/kademi-dev/issues/4926

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
looks good
