### ISSUE TITLE
Promotion component not working

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4944]
Promotion Tile Settings component does not show any properties when you configure it.

http://moblixdemo.admin.kademi.us/pages/consumer-journey/version1/

Open the page test.html

![image](https://user-images.githubusercontent.com/2201340/36136340-138fb7e4-10e4-11e8-967d-d3bfdca44d8f.png)

**Comment by ducdhm** [comment]
Added message when no active promotion found

**Comment by ducdhm** [comment]
@Uafinder This component is working normally. Just because of no active promotion found, so the settings looks like uncompleted.

**Comment by Uafinder** [comment]
Yeah, looks fine
