### ISSUE TITLE
EDM editor image edition bug

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4945]
1. Create email
2. Add some text component
3. Push image button there
4. Upload to asset or select some image from the asset
5. Push edit
6. Edit some
7. Push save
8. Image will not appear on the page
http://vladtest33.admin.kademi-ci.co/groupEmails/5468594/edmeditor?fileName=index.html&useHash=true
http://vladtest33.admin.kademi-ci.co/asset-manager/
Image is successfully added to assets and public tag is assigned

same, with edm editor in journeys

**Comment by Uafinder** [comment]
https://drive.google.com/open?id=1uQYBfMy49MWK7_ORGLUSMbZDNqp2dfmt

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
Yup, it works!
