### ISSUE TITLE
When one asset has more than one type assigned it appears multiple times in assets list

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4948]
![image](https://user-images.githubusercontent.com/1945230/36155568-5e2c0eb2-10dd-11e8-8299-aa132080f4c4.png)
http://vladtest33.admin.kademi-ci.co/asset-manager/
1. Add an asset
2. Assign it to some types
3. Back too assets list, it will appears in list multiple times

**Comment by bradmac** [comment]
Fixed

**Comment by Uafinder** [comment]
Same thing
![image](https://user-images.githubusercontent.com/1945230/36197651-0c4526ce-117d-11e8-9551-064bc5b4ceb5.png)
Fresh account
http://vladtest34.admin.kademi-ci.co/asset-manager/

**Comment by bradmac** [comment]
Oops, didnt deploy the updated asset lib

Fixed now

**Comment by Uafinder** [comment]
Yup, looking good
