### ISSUE TITLE
Add products to reward store minor bugs

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4952]
![image](https://user-images.githubusercontent.com/1945230/36157563-b7ceb64a-10e2-11e8-98bb-6136dec9284b.png)
![image](https://user-images.githubusercontent.com/1945230/36157580-c0499a7e-10e2-11e8-9ca6-0f26add428f2.png)
Some buttons not aligned to the right, but they was some time ago. probably due to some recent fixes
http://vladtest33.admin.kademi-ci.co/reward-store/vlad33web-store/?addProducts
http://vladtest33.admin.kademi-ci.co/reward-store/vlad33web-store/#products-tab

**Comment by bradmac** [comment]
Fixed the first one, second seems to have already been fixed

**Comment by Uafinder** [comment]
yup, looks good at the moment
