### ISSUE TITLE
KCRM search box not working

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4953]
http://kcrm.kademi.us/dashboard

Searching for a lead returns no results.  The lead does exist.   Have re-indexed.

![image](https://user-images.githubusercontent.com/2201340/36176296-3ede91a4-1166-11e8-9a27-67ba726f40d8.png)

**Comment by bradmac** [comment]
related - https://github.com/Kademi/kademi-dev/issues/3505

**Comment by bradmac** [comment]
Note that @tuzzmaniandevil has implemented omnisearch for the menu search box, which this should be using.

We'll also need to do some work on the search page

**Comment by gonzalon** [comment]
leadman-lib 1.8.2
search-lib 1.1.3

**Comment by Uafinder** [comment]
Searching still does nothing
http://vladtest34c.admin.kademi-ci.co/websites/vladtest34cleads/version1/#panel_apps-tab

**Comment by bradmac** [comment]
That's because of this error in the search
```
18:34:57 java.lang.RuntimeException: org.apache.velocity.exception.MethodInvocationException: Invocation of method 'omniSearch' in  class io.milton.cloud.server.apps.search.SearchApp threw exception [qa1-bran-6131256-6127682] IndexNotFoundException[no such index] at vladtest34cleads-vladtest34c.kademi-ci.co:/theme/apps/search/omniSearchResults.html[line 2, column 39]
```

**Comment by bradmac** [comment]
Thats because indexes dont exist for website content:
http://vladtest34c.admin.kademi-ci.co/websites/vladtest34cleads/version1/manageSearch/
![image](https://user-images.githubusercontent.com/826458/36348749-9de04620-14db-11e8-9084-7f4ecfe57e0c.png)

**Comment by bradmac** [comment]
Thats because indexes dont exist for website content:
http://vladtest34c.admin.kademi-ci.co/websites/vladtest34cleads/version1/manageSearch/
![image](https://user-images.githubusercontent.com/826458/36348749-9de04620-14db-11e8-9084-7f4ecfe57e0c.png)

**Comment by bradmac** [comment]
Note there was a problem creating the website level indexes, fixed

**Comment by bradmac** [comment]
Should work now, but you should reindex at the website level to check content (eg from website pages and blogs)

**Comment by Uafinder** [comment]
Yup, it works!
