### ISSUE TITLE
UpcomingEvents component needs to support personal calendar selection

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4954]
Please add an option to the upcomingEvents component settings to use the logged in user's personal calendar.

This is needed for KCRM where appointments are made in the user's personal calendar and we need that displayed on the dashboard.

**Comment by bradmac** [comment]
@ducdhm this is done for upcomingEvents, can you please also integrate into calendarWidget ?

I've added some server side code to calendarWidgetComponent.html  ..
```
#if( $calendar && $calendar == '_default')
    #set ($defaultCalendar = '/users/' + $userResource.name + '/Calendars/default/')
#else
```

So you can get the href of the personal calendar. This needs to be passed to JS somehow i think. Or you could actually built it entirely in JS, i think there's a global variable with the logged in user's username

**Comment by bradmac** [comment]
Its likely that the user does not have a calendar called "default". Please check from the admin profile page and create one if needed

**Comment by anhnt** [comment]
@Uafinder please create new fresh user and test with this component.

**Comment by Uafinder** [comment]
hmmm, i'm receiving an error
![image](https://user-images.githubusercontent.com/1945230/37715613-2eb06552-2d25-11e8-92b5-219e552e23ff.png)
http://vladtest45.admin.kademi-ci.co/pages/vladtest45web/version1/?contenteditor=page2.html
Added calendar and events components and setup they as personal calendar.

**Comment by bradmac** [comment]
Thats because that user does not have a personal calendar:
![image](https://user-images.githubusercontent.com/826458/37738162-ff151c7a-2dba-11e8-9fd0-25ea609be86e.png)
http://vladtest45.admin.kademi-ci.co/manageUsers/11608530/#calendarEventsTab-tab

You should create a new user to test with in the account, and ensure you create that user while the calendars app is enabled so it can create the default calendar

**Comment by Uafinder** [comment]
yeah looks ok
