### ISSUE TITLE
Choosing website on social goal breaks journey

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4955]
http://moblix.admin.kademi-ci.co/funnels/social-campaign/version1/#journeyBuilder-tab

If a social goal has a website selected, it fails.  Is this expected?

**Comment by bradmac** [comment]
i think there shouldnt be a website, because there is no related website when a social interaction happens.

**Comment by bradmac** [comment]
Please just remove the website setting

**Comment by Uafinder** [comment]
yup, looks good
