### ISSUE TITLE
Email result goal - convert node - not working

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4956]
You cannot drag the arrow from the top output "converted" 

![image](https://user-images.githubusercontent.com/2201340/36188024-51cd2140-119d-11e8-845f-332a65f7de3f.png)

http://kademi.admin.kademi.us/funnels/test23/version1/#journeyBuilder-tab

**Comment by bradmac** [comment]
I think we should change this a bit.

Howabout we have 2 goals:
- Email Delivery Result (delivered, failed)
- Email Interaction (opened, converted)

**Comment by bradmac** [comment]
Note that we'll need to preserve backwards compatibility

**Comment by bradmac** [comment]
Done. Here's an example journey showing both email goals

![image](https://user-images.githubusercontent.com/826458/36401368-f0d4f09a-163b-11e8-99bd-9eafefc4f691.png)

**Comment by bradmac** [comment]
@ducdhm please investigate the problem with the transition being lost

**Comment by ducdhm** [comment]
@bradmac Seem like it come from server-side. As I checked, when you press save settings of addToGroup node, there is only 1 request to server at `/funnels/myFunnel/version1/addToGroup-e347cb?mode=settings`. After that, email open node is changed to email delivery node.

**Comment by bradmac** [comment]
Seems to be working correctly now, this after editing and refreshing:
![image](https://user-images.githubusercontent.com/826458/37008969-867a9254-2149-11e8-925a-4c0bce0566ce.png)

**Comment by Uafinder** [comment]
Fresh account
![image](https://user-images.githubusercontent.com/1945230/37036373-29982dda-2158-11e8-9ba0-a3c150471a6b.png)
http://vladtest39.admin.kademi-ci.co/funnels/journey1/version1/#journeyBuilder-tab

1. Create a journey
2. Edit it, add blocks begin, send email, email delivery, email open, add to group node and end.
3. Edit settings for begin, send email and add to group nodes.
4. It saves
5. Refresh page
6. Trouble appears

**Comment by bradmac** [comment]
I cant see a problem where dragging a connection from "entered when timeout passed" creates a link for "failed"

**Comment by bradmac** [comment]
Moved the "passed time" connection problem here - https://github.com/Kademi/kademi-dev/issues/5090

**Comment by bradmac** [comment]
@Uafinder I cannot reproduce the issue you described above. Lets discuss, and you can walk me through it

**Comment by bradmac** [comment]
@ducdhm says

after you connect all nodes, click on settings of Add To Group node
choose any group
press save
and then refresh

Email opened is changed to Email delivery

**Comment by bradmac** [comment]
Fixed

**Comment by Uafinder** [comment]
This one is fixed...
Question: what should I do with email to it become "converted"?

**Comment by bradmac** [comment]
> Question: what should I do with email to it become "converted"?

"Converted" means that the user has clicked a link in the email, in other words we have succeeded in getting the customer to take an action.

So just a click a link in the email :)  the links should automatically have an edmid parameter added to them, and thats how the server knows its a link from an email

**Comment by Uafinder** [comment]
It works
