### ISSUE TITLE
Query table selector takes description instead of query table name

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4959]
![image](https://user-images.githubusercontent.com/1945230/36206557-74d27a66-119b-11e8-97e4-c8fc2f80b8b3.png)
http://vladtest34a.admin.kademi-ci.co/queries/
![image](https://user-images.githubusercontent.com/1945230/36206573-85ff7780-119b-11e8-8c40-7923c8aa2e74.png)

**Comment by bradmac** [comment]
Done. Required reporting-lib 1.2.4

**Comment by Uafinder** [comment]
Yup, it works!

**Comment by Uafinder** [comment]
same thing in this components:
Pie chart
![image](https://user-images.githubusercontent.com/1945230/36844225-87e25048-1d5a-11e8-8934-34f4f09549ce.png)
Date histogram
![image](https://user-images.githubusercontent.com/1945230/36844237-93d6350e-1d5a-11e8-83c1-1d89a63bc749.png)
http://vladtest38a.admin.kademi-ci.co

**Comment by tuzzmaniandevil** [comment]
Fixed in reporting-lib 1.2.5

**Comment by Uafinder** [comment]
Yeah, it works!
