### ISSUE TITLE
Adding query table component (pie component) queries list empty by default

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4960]
![image](https://user-images.githubusercontent.com/1945230/36206681-f6d08616-119b-11e8-936f-72f4fcecf8dd.png)
1. Create a page
2. Add query table component there
3. Try to edit it
4. No query tables in list

Change radio button between query table and query and back and it will show up
http://vladtest34a.admin.kademi-ci.co/pages/vladtest34aweb/version1/ 

Same for Pie component
![image](https://user-images.githubusercontent.com/1945230/36207091-644db03c-119d-11e8-85df-db67515be6da.png)

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
Yeah, looks good
