### ISSUE TITLE
Selecting query for pie cause error in console

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4961]
![image](https://user-images.githubusercontent.com/1945230/36207150-8e71e9d2-119d-11e8-9535-61c39f29a4ee.png)
1. add pie component
2. select query
3. note the error

http://vladtest34a.admin.kademi-ci.co/pages/vladtest34aweb/version1/

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
looks good
