### ISSUE TITLE
Selecting aggregation for histogram query component cause error 

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4962]
![image](https://user-images.githubusercontent.com/1945230/36207256-e416bc5a-119d-11e8-9896-ed219d6792eb.png)

1. Add date histogram settings
2. Select query
3. Select aggregation
4. note error
http://vladtest34a.admin.kademi-ci.co/pages/vladtest34aweb/version1/

**Comment by ducdhm** [comment]
Done!

**Comment by Uafinder** [comment]
Yeah, looks better
