### ISSUE TITLE
Adding pie component query cause error on the page frontend

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4963]
![image](https://user-images.githubusercontent.com/1945230/36207579-13967686-119f-11e8-9c60-4daca1375ce2.png)
1. Add pie component
2. Save
3. View page on the frontend
4. Check error
http://vladtest34a.admin.kademi-ci.co/pages/vladtest34aweb/version1/

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
It works!
