### ISSUE TITLE
Upload image for sales claims should filter file types

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4964]
Should show only images, because all other files rejected (even PDF)
![image](https://user-images.githubusercontent.com/1945230/36210552-5ceb75e0-11a7-11e8-82fc-e8ba3317b612.png)
http://version1.vladtest34asales-vladtest34a.kademi-ci.co/page1.html

**Comment by bradmac** [comment]
hey @gonzalon can you take a look please?

**Comment by gonzalon** [comment]
Fixed in salesDataClaimer: 1.1.7

![image](https://user-images.githubusercontent.com/2773216/36236026-ba22a222-1258-11e8-95ef-9ceb2ce9aacc.png)

**Comment by Uafinder** [comment]
YUp, works ok
