### ISSUE TITLE
Add to group button does not work on users page

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4976]
http://kademi.admin.kademi.us/manageUsers/

Both the button and the link in the drop down do not work

![image](https://user-images.githubusercontent.com/2201340/36293912-f689ab92-1330-11e8-9a24-c3a50b38834b.png)

**Comment by bradmac** [comment]
Works initially, but not after searching

**Comment by bradmac** [comment]
Fixed.

**Comment by Uafinder** [comment]
It works after search
