### ISSUE TITLE
defaultthemeTemplate - image from assets are no showing

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4978]
![image](https://user-images.githubusercontent.com/1945230/36303369-9f1b8680-1314-11e8-9f19-d257f20d2d98.png)
1. Open for edition defaultthemetemplate
2. Push change logo
3. Upload image to assets
4. Click ok
5. Image will not appear
http://vladtest34c.admin.kademi-ci.co/pages/vladtest34caucstore/version1/

**Comment by bradmac** [comment]
hey @ducdhm this appears to be building a hashes url for the image, eg:

/_hashes/files/3cffebd1-772f-4806-b01a-67a7d8fd8d67

But we cannot use _hashes with assets, you must create a url to the asset, eg

/assets/3cffebd1-772f-4806-b01a-67a7d8fd8d67

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
Good!
