### ISSUE TITLE
Blog content editor - text controls panel doesn't appear

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4981]
![image](https://user-images.githubusercontent.com/1945230/36309798-ae4ea71c-132e-11e8-8b64-fe0c1b40039e.png)
1. Create article
2. Edit it's content
3. Add some text component
4. Edit it, text controls will not appear
http://vladtest34c.admin.kademi-ci.co/blogs/skoda/skoda-octavia-from-russia/#bodyCopy-tab

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
looks better
