### ISSUE TITLE
Multi-image purpose for blog article

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4985]
![image](https://user-images.githubusercontent.com/1945230/36311792-167fdf44-1335-11e8-9388-16a98f8fa67a.png)
http://vladtest34c.admin.kademi-ci.co/blogs/skoda/skoda-images/#images-tab
what is the purpose for multi-image uploading, when only the last image is using for article thumbnail?

**Comment by bradmac** [comment]
Thats because the images are then available for custom blgo article templates to use, even if our default ones dont currently use them

**Comment by Uafinder** [comment]
understood
