### ISSUE TITLE
Category not showing any products to add

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4986]
Have re-indexed 

http://moblix.admin.kademi-ci.co/categories/visacards/?q=&l=&incl=true#products-tab

None showing
![image](https://user-images.githubusercontent.com/2201340/36333770-da80e93c-13cc-11e8-8945-b05253c642da.png)

**Comment by bradmac** [comment]
duplicate - https://github.com/Kademi/kademi-dev/issues/4916

**Comment by bradmac** [comment]
Note that reindexing is not relevant to this screen since its a db search
