### ISSUE TITLE
Claim APP updates

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4987]
When choosing a data series in the Claim APP, the option must only apply to the current website.  

Currently it updates all claim APP settings on all websites which means you can only ever select one data series.

![image](https://user-images.githubusercontent.com/2201340/36334637-59bea150-13d0-11e8-8b5f-6f833af6aaef.png)

The 2x claim goals should have an option to select a website, so it only fires for the given website.

![image](https://user-images.githubusercontent.com/2201340/36334891-8b221308-13d0-11e8-96e1-ca1cd57c3811.png)

**Comment by bradmac** [comment]
> When choosing a data series in the Claim APP, the option must only apply to the current website.

Fixed

**Comment by bradmac** [comment]
> The 2x claim goals should have an option to select a website, so it only fires for the given website.

I dont think we should need this. You should probably have seperate data series if you're using them on a different websites

**Comment by Uafinder** [comment]
Yeah, looks good
