### ISSUE TITLE
Segmenting leads

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4992]
I have this group http://kademi.admin.kademi.us/groups/loyalty-email-campaign-followup/members/

I need to download this group as a list with company names.  The only way to do this in the admin console is via the lead group which has the Company field, however this does not give me the segmented list.

If you look at this profile http://kademi.admin.kademi.us/manageUsers/16267668/#general-tab
They have a value in the Company field.

These profiles do not have a lead in KCRM as their journey ended, but they have a contact.

How can I download this list with First Name, Last Name, Email.... and company name in it?

**Comment by bradmac** [comment]
As discussed, simply download from the members CSV page

But it depends on this - https://github.com/Kademi/kademi-dev/issues/5000
