### ISSUE TITLE
De-dup orgs tool

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#4995]
- ability to search for and see duplicate orgs, grouped into sets of duplicated items
- ability to select which sets to merge

**Comment by bradmac** [comment]
Orgs on the right get merged into the org on the left

![image](https://user-images.githubusercontent.com/826458/36360047-77ee6640-1585-11e8-9a66-ac779afbf6e6.png)

**Comment by bradmac** [comment]
hey @Uafinder and @mkhoudary this is the new feature we need to sort out CCA. 

Please check you're happy with it in CI first, then use it carefully in production. I suggest just merge one duplicate set first, check the results, then do a few more. Then do all of them once your confident its working correctly.

**Comment by Uafinder** [comment]
5. It will not merge orgs when there are no users in it.
Simply nothing is happened after merging.
![image](https://user-images.githubusercontent.com/1945230/36374618-a32ea79a-1574-11e8-83d0-19b86b03e1cb.png)
![image](https://user-images.githubusercontent.com/1945230/36374630-aaacdb18-1574-11e8-856b-181a3d911ccf.png)
After refresh
![image](https://user-images.githubusercontent.com/1945230/36374644-b5a5ee74-1574-11e8-948b-23c7e9b0fb8c.png)
http://vladtest35.admin.kademi-ci.co/organisations/dedupe

**Comment by bradmac** [comment]
OK, so the problem was that it was actually identifying the wrong orgs to merge. Ie instead of merging the 1st it was merging the 11th

**Comment by bradmac** [comment]
Fixed.

**Comment by Uafinder** [comment]
looks good at the moment
