### ISSUE TITLE
remove button when there is no domain name

### ISSUE THREAD

**Issue by Anton69arb** [Kademi/kademi-dev#4996]
Hey :)

Could we remove this button as it does not make sense to have it when there is no domain name for the website,  must only view when there is a domain name, as kademi has an SSL that can be used for an account that has no domain name.

![1](https://user-images.githubusercontent.com/32444328/36356719-94587f1c-155a-11e8-8f77-8ea1ec822db7.png)
![2](https://user-images.githubusercontent.com/32444328/36356720-9486f766-155a-11e8-9218-41fd68b57d3c.png)

**Comment by Uafinder** [comment]
Yup, looks good
