### ISSUE TITLE
CKeditor can't edit Input fields in modal

### ISSUE THREAD

**Issue by gonzalon** [Kademi/kademi-dev#4997]
Soraya can't add a modal because you can't edit the title field, you can't edit the last input either.

 https://airnz.admin.kademi.com.au/products/mount-gay-rum-1703-br-small-nz-delivery/#panel-content-tab 

![image](https://user-images.githubusercontent.com/2773216/36358376-66559222-1572-11e8-9c87-bc69bd994c8f.png)

**Comment by ducdhm** [comment]
Fixed!

**Comment by gonzalon** [comment]
Working
