### ISSUE TITLE
Update time field in journey timer goal

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#4999]
http://kademi.admin.kademi.us/funnels/sales-incentive-companies/version1/#journeyBuilder-tab

Should allow the user to enter the time as hh:mm , eg "15:30"

**Comment by ducdhm** [comment]
@bradmac So in timer goal node, `timerTime` can be `15:30`, instead of only number like `10`, `23`, etc..., right ?

**Comment by bradmac** [comment]
yeah, should be like 15:30

But I'm not sure thats working correctly, @tuzzmaniandevil can you check?

**Comment by bradmac** [comment]
See KademiUtilsTest and Goal:
```
    public Date calcDueDate(Date enteredDate, Lead lead, FunnelTester tester) {
        Calendar cal = calcDueDate(enteredDate, lead);
        if ( cal == null ) {
            log.info("calcDueDate returned null");
            return null;
        }

        // Now add minutes
        if ( tester != null ) {
            int durationMins = durationMins(enteredDate, cal.getTime());
            int newDelayMins = tester.adjustTimeoutMins(lead, durationMins);
            cal.setTime(enteredDate);
            cal.add(Calendar.MINUTE, newDelayMins);
        } else {
            // And adjust time if there is one
            if ( StringUtils.isNotBlank(timerTime) ) {
                Date t = KademiUtils.parseTime(timerTime);
                if ( t != null ) {
                    Calendar c = Calendar.getInstance();
                    c.setTime(t);
                    int hour = c.get(Calendar.HOUR_OF_DAY);
                    int min = c.get(Calendar.MINUTE);
                    cal.set(Calendar.HOUR_OF_DAY, hour);
                    cal.set(Calendar.MINUTE, min);
```

**Comment by tuzzmaniandevil** [comment]
It will now parse `hh:mm aa` e.g. `03:30 PM` (12-hour time) and `HH:mm` e.g. `15:30` (24-hour time)

**Comment by ducdhm** [comment]
![newui](https://user-images.githubusercontent.com/1289631/36773786-f02eda0e-1c8d-11e8-9ecf-f0e8dcb6c995.png)

**Comment by ducdhm** [comment]
Done!

**Comment by Uafinder** [comment]
Ok, time allows to be setup, but I can't setup the timer execution
1. Setup timer
![image](https://user-images.githubusercontent.com/1945230/36933498-59edb02c-1ee2-11e8-8355-db9660a16c88.png)
2. Create a lead
3. Open leads page
![image](https://user-images.githubusercontent.com/1945230/36933499-6d87abe2-1ee2-11e8-8d78-64c4053c2949.png)
![image](https://user-images.githubusercontent.com/1945230/36933500-7596b3fa-1ee2-11e8-8884-2137066e2617.png)

It always shows that there no current timer
http://vladtest38c.admin.kademi-ci.co/manageUsers/7775962/#funnelsTab-tab

**Comment by bradmac** [comment]
@Uafinder you need to select the timeout (multiples + interval, eg "3 days"). The time component is optional, but it doesnt do anything by itself

![image](https://user-images.githubusercontent.com/826458/36949950-c2370a9e-2053-11e8-82e9-7129520c9c2e.png)

**Comment by Uafinder** [comment]
ok, so it should fire at the specified time after timeout, right?i have such settings
![image](https://user-images.githubusercontent.com/1945230/36974987-526d55a0-2081-11e8-8776-25001c77f0de.png)
So, time should execute at this time (e.g. at 01:25 07\03\2018), however it says that:
![image](https://user-images.githubusercontent.com/1945230/36975059-87f7b6fc-2081-11e8-8595-4ba7de0b73a5.png)
So looks like this time setting has no influence on timer time

**Comment by bradmac** [comment]
Problem was that the persisted time value wasnt being used

**Comment by bradmac** [comment]
Fixed.

**Comment by Uafinder** [comment]
Ok, it works!
