### ISSUE TITLE
EDM editor - blogs component image doesn't fall into container size

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5009]
Reported by Lyle
http://hydra.admin.kademi.com.au/groupEmails/103783275/#messages-tab
Reproduced in CI
http://vladtest35a.admin.kademi-ci.co/groupEmails/

1. Create an article
2. Add 66/33 container
3. Add text to the left
4. Add blogs component, setup it.
5. Watch how it looks on the preview (ediror)
6. Send test
![image](https://user-images.githubusercontent.com/1945230/36420705-8d791f0a-163e-11e8-8b04-348e3e0d9499.png)
![image](https://user-images.githubusercontent.com/1945230/36420723-92bfe9bc-163e-11e8-9bc8-d33389033db7.png)
When it comes it looks like
![image](https://user-images.githubusercontent.com/1945230/36420739-a54e5b86-163e-11e8-8fd2-287e5842b97d.png)
As you can see 33% container size is oversized.
This is caused by a large image in blog article thumbnail.

However, I put some small image, and it becomes large too
![image](https://user-images.githubusercontent.com/1945230/36421718-4fef54ca-1642-11e8-8697-02944f82c991.png)

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
Ok, it fixed on QA... should be deployed to Lyle account ASAP!

**Comment by Uafinder** [comment]
update blog lib version there
