### ISSUE TITLE
EDM editor: layout break when add some wide component

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5010]
1. Create email
2. Add some 66/33 container
3. Add some text to the left
4. Add points earned component to the right
5. Note that all right container moved to the bottom
It's completely not acceptable to be user friendly and visual. Should never happened with any component.
http://vladtest35a.admin.kademi-ci.co/groupEmails/6367639/#sendInfo-tab
Spotted in Gilpin, reproduced in CI
![image](https://user-images.githubusercontent.com/1945230/36423599-4725e15e-1649-11e8-9566-a92e91b66833.png)

**Comment by bradmac** [comment]
I think this is kind of correct behaviour

If you look at the screenshot above you can see that the green component is physically too large to fit into the right.

What i've done is just change that default text from [select] to [?] so its more likely to fit.

However, the same layout problem will occur if a user's points value is too long for the right hand column

**Comment by Uafinder** [comment]
Yeah, it looks better when [?] is selected, but when points size reach 100000, it transits to bottom part.
