### ISSUE TITLE
EDM editor: points earned component issue

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5011]
![image](https://user-images.githubusercontent.com/1945230/36423737-b8adb504-1649-11e8-9fc4-7e37d5bc79e5.png)

Component value should never looks like variable
http://hydra.admin.kademi.com.au/groupEmails/103783275/edmeditor?fileName=index.html&useHash=true
Spotted in Gilpin

**Comment by bradmac** [comment]
@ducdhm can you ensure that
- when viewed in the editor, always display sample points value, eg 999
- when rendered for real (ie not in editor) display "N/A" if we cant get points for the user
- ensure the component layout html is not duplicated for editor and non-editor usage

**Comment by ducdhm** [comment]
Done!

**Comment by Uafinder** [comment]
looks better
