### ISSUE TITLE
EDM editor: thumbs for product components bad

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5013]
![image](https://user-images.githubusercontent.com/1945230/36424333-9ab0c31e-164b-11e8-97b3-c7d18bceed16.png)
![image](https://user-images.githubusercontent.com/1945230/36424342-a1308f12-164b-11e8-9fcd-423a2e164436.png)
![image](https://user-images.githubusercontent.com/1945230/36424349-a73fe15a-164b-11e8-80f3-e24d0e0ee233.png)
http://vladtest35a.admin.kademi-ci.co/groupEmails/6367639/#messages-tab

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
looks good
