### ISSUE TITLE
EDM editor: Purchased products list component show photos cause layout broken

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5014]
![image](https://user-images.githubusercontent.com/1945230/36430826-bb7ed258-165e-11e8-9e48-a1c05d527d53.png)
![image](https://user-images.githubusercontent.com/1945230/36430837-c32bd53c-165e-11e8-9c25-056945fac135.png)
When you check this checkbox, component moves to the left no matter of component placing in the layout.
http://vladtest35a.admin.kademi-ci.co/groupEmails/6377316/#messages-tab

**Comment by bradmac** [comment]
@Uafinder i think this is because with the photo that table just physically cannot fit in a narrower column

So please check with the component used in a full width container.

**Comment by Uafinder** [comment]
ok, looks better on the 100% container
