### ISSUE TITLE
EDM Editor: single product component button should has some color by default

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5015]
![image](https://user-images.githubusercontent.com/1945230/36431154-888b9d3a-165f-11e8-8f2f-1255ffb61583.png)
By default button is white and layout is white, so user not image that there is a button at all
![image](https://user-images.githubusercontent.com/1945230/36431210-a62310b2-165f-11e8-8577-39a9f8ab6d49.png)
http://vladtest35a.admin.kademi-ci.co/groupEmails/6377316/#messages-tab

**Comment by bradmac** [comment]
:+1:

**Comment by Uafinder** [comment]
Yup, it works
