### ISSUE TITLE
KSurvey enhancements

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5017]
- show the list of individual submissions on a new tab
- each submission should link to a new page which shows their answers
- show survey submissions on the user's timeline, with links to the submission detail page

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/37279361-2bc0c8be-261d-11e8-9af9-d2a1b23ec501.png)

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/37279389-43c7f5c2-261d-11e8-97e3-b0461eb80a48.png)

**Comment by AlaaKhalaf94** [comment]
tested
