### ISSUE TITLE
leadman theme loading too slow

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5020]
![image](https://user-images.githubusercontent.com/1945230/36478471-879cc6d4-170d-11e8-8bbf-6880352349a2.png)
![image](https://user-images.githubusercontent.com/1945230/36478475-8df7baca-170d-11e8-9bab-f0dad92ccce1.png)
It's after hard refresh
http://version1.vladtest36leads-vladtest36.kademi-ci.co/dashboard
loading longs for 30 seconds and more

**Comment by bradmac** [comment]
I got a load time of 4.7secs. Not great, but ok.

@Uafinder can you check?

**Comment by Uafinder** [comment]
ok, lets leave it as is

**Comment by Uafinder** [comment]
As confirmed in ITI loading is really slow
To reproduce it pls clear cache or do a hard refresh
I got 20-30 seconds on ITI pages.
Will provide details of fresh account a bit later

**Comment by bradmac** [comment]
I think this should be resolved by https://github.com/Kademi/kademi-dev/issues/5080

@Uafinder please check in CI with the latest theme.

We will need to upgrade production clients to the latest themes and libs to get the full performance improvement

**Comment by Uafinder** [comment]
Well, looks better...
Not ideal, but better...
the most time of leadman theme loading takes loading 2.9MB theme file...
