### ISSUE TITLE
de-dup orgs tool count of orgs doesn't renew after processing

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5022]
![image](https://user-images.githubusercontent.com/1945230/36480366-c21c9166-1714-11e8-919a-a1d3cf6c44e3.png)
1. Select some number of orgs
2. note number of found duplicate orgs
3. push merge
4. note that list is updated, but number doesn't changed
http://vladtest36.admin.kademi-ci.co/organisations/dedupe

**Comment by bradmac** [comment]
Thats fine.
