### ISSUE TITLE
De-dup orgs tool double memberships left when user was a member of both orgs

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5023]
1. User is a member of both orgs which will be merged
2. Found them and merge
3. Orgs are successfully merged, but user still has two memberships in one org
![image](https://user-images.githubusercontent.com/1945230/36480977-f580f374-1716-11e8-91d0-476c9c6c5966.png)
http://vladtest36.admin.kademi-ci.co/manageUsers/6448946/#summary-tab

**Comment by bradmac** [comment]
I dont think this matters. In reality users wont be in both orgs
