### ISSUE TITLE
The image inserted in email by ckeditor in journey ,  doesn't appear

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#5025]
Journey   : http://alaa-test99.admin.kademi-ci.co/funnels/journey1/version1/#journeyBuilder-tab

Manage email : http://alaa-test99.admin.kademi-ci.co/funnels/journey1/version1/email1/#message-tab

![untitled01](https://user-images.githubusercontent.com/26510030/36483751-aaa1f0d4-171f-11e8-8d8a-867c3b0b27d6.png)

That's because the src of image added incomplete
src="/_hashes/files/f6351ea65686ffb0014874d5eb0ece75a15fceb9"

**Comment by bradmac** [comment]
I'm thinking of maybe adding something server side to check for any src or href attributes that dont have a domain name..

**Comment by bradmac** [comment]
When i add an image in the journey email editor i get a non fully qualified url:
```
<p><img align="" alt="undefined" class="img-responsive" data-hash="2b4c70ed32aca3fb457f63bb14493b4e9b88904f" data-uniqueid="" height="113" src="/_hashes/files/2b4c70ed32aca3fb457f63bb14493b4e9b88904f" style="width: 200px; height: 113px;" width="200" /></p>
```

But when i do the same in group email editor i do get a fully qualified url:
```
<p><img align="" alt="undefined" class="img-responsive" data-hash="9d80711e77897f6ed453cfe9cc758bd1d9cf683a" data-uniqueid="" height="319" src="http://localhost:8080/_hashes/files/9d80711e77897f6ed453cfe9cc758bd1d9cf683a" style="width: 371px; height: 319px;" width="371" /></p>
```

**Comment by bradmac** [comment]
Done, but should test on CI

**Comment by bradmac** [comment]
Just did a quick check on CI and seems ok

**Comment by AlaaKhalaf94** [comment]
passed
