### ISSUE TITLE
Need expression filtering for allowed groups in assets

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#5028]
We need to display allowed groups in group asset as an expression, where all groups are ran against it.. e.g. I want to display optins of a specific parent or so.. because with this way I need to hardcode the groups in the asset.. this is needed in PHHub.

**Comment by bradmac** [comment]
Not sure i understand you correctly, lets chat..

**Comment by bradmac** [comment]
OK, so as discussed we'll add the ability to select a group folder rather then using an expression

**Comment by bradmac** [comment]
Can add group fields now:
![image](https://user-images.githubusercontent.com/826458/36698076-c50fce54-1bad-11e8-8a9d-787b0f846616.png)

![image](https://user-images.githubusercontent.com/826458/36698528-f0eadd92-1bae-11e8-976d-9bbbb499e29e.png)

**Comment by bradmac** [comment]
And this on the edit form for an asset:
![image](https://user-images.githubusercontent.com/826458/36698577-19a6fd2e-1baf-11e8-9a72-07891961592d.png)
