### ISSUE TITLE
sales settings changing cause an error 

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5031]
Not quite understand, for what this settings tab exists
Also, when try to change something it cause an error
![image](https://user-images.githubusercontent.com/1945230/36587406-d0133ab6-188d-11e8-9275-1c05d12752e9.png)

**Comment by gonzalon** [comment]
@Uafinder the settings page is to update the same settings you could update in the apps page in the org level or the website level.

salesDataClaimer 1.1.9

**Comment by Uafinder** [comment]
ok, error doesn't appear
