### ISSUE TITLE
Blank page when using template in assets page

### ISSUE THREAD

**Issue by mrdadah** [Kademi/kademi-dev#5033]
When I set a template to be used within asset page, It shows the template with blank page

For example: 
here is a template link:
http://phhub-phhub.kademi-ci.co//theme/contenteditor?fileName=newsAndEvents.html

When I use it in asset page template:
http://version1.phhub-phhub.kademi-ci.co/templates/texteditor?fileName=event.html

<img width="705" alt="screen shot 2018-02-25 at 2 29 59 pm" src="https://user-images.githubusercontent.com/11255121/36641475-815ac126-1a38-11e8-86da-d725d079eaf3.png">

It shows a blank page

<img width="1680" alt="screen shot 2018-02-25 at 2 29 37 pm" src="https://user-images.githubusercontent.com/11255121/36641476-89506bd8-1a38-11e8-9b5d-26096d19b68e.png">

**Comment by bradmac** [comment]
Hi @mrdadah that page is working correctly for me:

http://version1.phhub-phhub.kademi-ci.co/assets/2d383cd5-b757-492c-9b4f-57cc8b959044

![image](https://user-images.githubusercontent.com/826458/36647548-2667ad74-1aec-11e8-9623-5d4d4526cbb9.png)

Please let me know if you are still seeing the problem

Also, its a good idea to check the logs when you see problems like this:
http://phhub.admin.kademi-ci.co/logging

**Comment by bradmac** [comment]
Kademi uses the following template structure
- physical resource (eg an Asset, FileResource, BlogArticle, Profile)
- page template (eg /theme/page.html, /theme/apps/user/profile.html)
- theme template (eg /theme/defaultThemeTemplate.html)

This rendering order is fixed, all pages must follow this process

Currently the event content type is configured to render with a page template called /templates/event.html

This has a template, which is therefore being used as the theme template, of /theme/newsAndEvents.html

However, theme/newsAndEvents isnt correctly setup to be a theme template, it looks like its intended to be a page template.

So i think the mistake here is thinking we can have arbitrary number of linked page templates.

Instead, just create a single page template and use that as the template for this content type
