### ISSUE TITLE
Multiple Category Selection

### ISSUE THREAD

**Issue by faithtek** [Kademi/kademi-dev#5034]
http://asrdev.admin.kademi.us/reward-store/general-1/#products-tab

The Multiple Category Selection works on this page, however when multiple categories are selected -- the page won't show the products from that multiple category selection.

**Comment by bradmac** [comment]
@gonzalon please take a look.

Also, and this is probably related, we're displaying duplicates:
![image](https://user-images.githubusercontent.com/826458/36645782-b7864c9e-1ad2-11e8-850e-0807ffd40aa0.png)

**Comment by gonzalon** [comment]
Here is an example of how it works:

Filtering by experiences:
![image](https://user-images.githubusercontent.com/2773216/36652038-0d44c38e-1b11-11e8-8ac8-6092f066bdee.png)

Filtering by High value
![image](https://user-images.githubusercontent.com/2773216/36652050-1d210312-1b11-11e8-9980-65df3970e15c.png)

Filtering by both (by default it's OR, so this mean the product has to be at least in one of the categories we filter)
![image](https://user-images.githubusercontent.com/2773216/36652072-3682194a-1b11-11e8-97d1-855e2ed60481.png)

Filtering by both but whit "AND" combine: (the product has to be in all of the categories filtered)
![image](https://user-images.githubusercontent.com/2773216/36652124-82335728-1b11-11e8-99b4-a5d468a8f35c.png)

**Comment by Uafinder** [comment]
Yeah, looks fine
