### ISSUE TITLE
Learning components for certificates and CPD

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5036]
Related - https://github.com/Kademi/projects/issues/61

**Comment by bradmac** [comment]
@ducdhm can you please assist by
- adding an option for whether to display CPD hours
- adding an option for whether to display start date
- adding an option for whether to display the person's name

**Comment by bradmac** [comment]
Needed for https://github.com/Kademi/projects/issues/61

**Comment by Uafinder** [comment]
Yeah, looks fine
