### ISSUE TITLE
Template code showing on vouchers page

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5037]
![image](https://user-images.githubusercontent.com/826458/36649985-ae2f97f8-1b05-11e8-8e08-2e3cb51a3222.png)

https://airnz.admin.kademi.com.au/voucher-type/cloo31dec/#vouchers-tab

**Comment by Uafinder** [comment]
Can't reproduce it on QA
http://vladtest38a.admin.kademi-ci.co/voucher-type/vouchqa/#vouchers-tab
AirNZ still unfixed
https://airnz.admin.kademi.com.au/voucher-type/cloo31dec/#vouchers-tab

**Comment by bradmac** [comment]
I dont think we've done a deploy to production with this fix

**Comment by Uafinder** [comment]
Нгзб дщщлы пщщв
