### ISSUE TITLE
Cannot set shopping cart item quantity to zero

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5038]
Note that this should remove the item from the cart

![image](https://user-images.githubusercontent.com/826458/36651320-3ecf1b74-1b0d-11e8-8b45-80b0c971c29e.png)

http://linkrewards-hydra.kademi.com.au/checkout/

The POST request still has a quantity of 1
```

changeItemHrefQuantity | /nz-linkrewards-store/Sports-Leisure/race-shirt-3xl-14-nz/?
-- | --
quantity | 1

```

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/36901463-ff850f8e-1e2f-11e8-9c33-8855df0752de.png)
Clicking "minus", cart reloaded but nothing happen
http://vladtest38baucstore_vladtest38b.kademi-ci.co/checkout/
http://vladtest38b.admin.kademi-ci.co/websites/

**Comment by ducdhm** [comment]
Done!

**Comment by Uafinder** [comment]
looks good
