### ISSUE TITLE
Shopping cart icon is invisible in inverted navbars

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5039]
This is because the extra div is breaking bootstraps inverted styles

**Comment by bradmac** [comment]
Fixed

![image](https://user-images.githubusercontent.com/826458/36651412-b5ebae2a-1b0d-11e8-83ff-bbfee6a98cc3.png)

**Comment by bradmac** [comment]
Requires shoppingcart-lib 1.0.8

**Comment by Uafinder** [comment]
yeah, looks good
