### ISSUE TITLE
Add option to pointsEarnedComponent to use date range or not

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5040]
Currently the pointsEarnedComponent applies the common date range criteria which defaults to 7 days

This can be unexpected for users not using a date range picker.

Please add an option for whether to apply date criteria or not, and default to not using it.

Once deployed please apply the change to http://hydra.admin.kademi.com.au to not use dates

http://linkrewards-hydra.kademi.com.au//theme/apps/user/contenteditor?fileName=dashboard.html

Related https://github.com/Kademi/projects/issues/64

**Comment by Uafinder** [comment]
It doesn't work
when selected checkbox
![image](https://user-images.githubusercontent.com/1945230/36847206-3bb08724-1d66-11e8-8b14-161ee3b55d1b.png)
when checkbox deselected
![image](https://user-images.githubusercontent.com/1945230/36847220-514f7f9a-1d66-11e8-8b8a-4cc54e6a452a.png)
Most of points are awarded in 7 days period

**Comment by ducdhm** [comment]
@Uafinder Did you check in admin, when you choose `7 days ago`?

**Comment by Uafinder** [comment]
Sure, it shows some points.
![image](https://user-images.githubusercontent.com/1945230/36852703-138047da-1d75-11e8-9584-2cd33409ea90.png)

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
Well, I don't see that this parameter is saving, so probably something going wrong.
1. Install all necessary apps, create a page, add there component and date range picker
2. Edit component settings
3. Select date range checkbox
4. Note points are changed, so it works
5. save
6. Close edition page
7. Open page for edition again
8. Open settings for components
9. Note that checkbox are not visible, however points shows like it's active
![image](https://user-images.githubusercontent.com/1945230/36932189-601abd28-1ece-11e8-85c1-fb890e1ae3af.png)
http://vladtest38c.admin.kademi-ci.co/pages/vladtest38caucstore/version1/

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
Yeah, looks fine
