### ISSUE TITLE
Not able to connect KFeedback goal 

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5041]
http://moblix.admin.kademi-ci.co/funnels/k-feedback-tutorial/version1/#journeyBuilder-tab

I get this error when connecting the kfeedback goal..
![image](https://user-images.githubusercontent.com/826458/36653441-066bd3f0-1b1a-11e8-883a-246267bfb6ec.png)

![image](https://user-images.githubusercontent.com/826458/36653415-ec61fc0a-1b19-11e8-8aa8-b568608de6e4.png)

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
Yup, error not appears
