### ISSUE TITLE
Login, then logout and there is no possiblity to login again

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5044]
1. Spot this on the ITI CRM
2. open this http://insured-crm_insured.kademi.com.au
3. login by userqa01@mailinator.com
4. logout
5. that's all, white screen appears.

**Comment by bradmac** [comment]
@Uafinder i cant reproduce. Can you please check?

**Comment by Uafinder** [comment]
Well, i'm also can't reproduce it...
Weird thing...
