### ISSUE TITLE
Add Social Share button for Facebook and LinkedIn, This share should be recorded against the user

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#5047]

**Comment by Uafinder** [comment]
Where I can see that?

**Comment by Uafinder** [comment]
Facebook looks ok
One thing, when you push cancel to share window, it gives error for us
![image](https://user-images.githubusercontent.com/1945230/37344066-fa44c244-26d1-11e8-9f9c-08d02de05e42.png)

Linkedin in process
