### ISSUE TITLE
Doubling calendar events when submit attendance 

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5050]
Based on ITI
1. Create an event
2. Create an appointment
3. Open event calendar
4. open event
5. Submit attendance
6. Open calendar, note another event created
![image](https://user-images.githubusercontent.com/1945230/36721531-d6fd1bac-1bb3-11e8-8f4c-93f8204990b5.png)
http://insured-crm_insured.kademi.com.au/users/test-user-1/Calendars/default/

Couldn't reproduce it on QA

**Comment by gonzalon** [comment]
@Uafinder I couldn't reproduce it. 
But I'm not sure what do you mean whit "Create an appointment"

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/37413067-d9e0a800-27ae-11e8-9965-96a6631fd84c.png)
I mean a reminder... sorry, was mistaken in terminology
http://insured-crm_insured.kademi.com.au/users/test-user-1/Calendars/default/

**Comment by gonzalon** [comment]
@Uafinder the process should be:
- that the organizer create an event
- the attendee accept the invitation
- the event gets created in the attendee calendar

So thats why you are seeing the duplication. 
The common case is that the organizer doesn't confirm the event as it shouldn't (this could be a future enhancement) 
If you test it again as this you shouldn't see the duplication, but you should see that the event gets created in the attendee calendar

**Comment by Uafinder** [comment]
ok, that's a common usage, but in ITI we have a personal calendars, so, other user doesn't see it I think
What i'm doing
- create a event as an organisor
- sign in by another user
- event is not visible

So, what should I do?
I just will ignore it as non-common case?

**Comment by bradmac** [comment]
@Uafinder the use case in ITI is that an appointment is created through the journey and it appears in the broker's personal calendar. There is no registration workflow in that use case.

The broker needs to be able to add and change the events in their personal calendar, but they wont use any sort of registration.

**Comment by Uafinder** [comment]
ok, understood
