### ISSUE TITLE
KCRM: Assigned to nobody cause task to close

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5051]
1. Create a task
2. Assign it to yourself
3. open tasks page
4. Open task
5. Choose assign to nobody
6. Watch that task will moved to closed
![image](https://user-images.githubusercontent.com/1945230/36727214-230daf78-1bc5-11e8-8349-ba8194b3ddc1.png)
http://vladtest36leads_vladtest36.kademi-ci.co
http://vladtest36.admin.kademi-ci.co/websites/

also spot this in ITI

**Comment by tuzzmaniandevil** [comment]
@Uafinder I've followed your steps exactly and tried a few other ways, The task never get's deleted, Only gets unassigned which it should do :-)

**Comment by Uafinder** [comment]
https://drive.google.com/open?id=17ovZPPAFQbhW_42JgyICV-94Ni-lngjy
I've wrote a video for this case

**Comment by tuzzmaniandevil** [comment]
When you click "Done", That doesn't save, That marks the task as complete, Assigning happens as soon as you click the button, No further action is required.

So you are closing the task, as well as unassigning it.

**Comment by Uafinder** [comment]
Ooops...
sorry
