### ISSUE TITLE
Image selection in assets produces incorrect link

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5052]
The asset selector is generating a link to the hashes resource:
http://rhipe.admin.kademi-ci.co/_hashes/files/c09bc6f2-8ac5-4135-9600-f3521e4b252b

But this is incorrect, assets must link to /assets/xxx

For example:
http://rhipe.admin.kademi-ci.co/websites/rhiperewards/version1/programs/software1/software10/sw101/#details-tab

![image](https://user-images.githubusercontent.com/826458/36762454-74767b2e-1c88-11e8-9d17-e5b31e6c34ed.png)

![image](https://user-images.githubusercontent.com/826458/36762441-635e04d8-1c88-11e8-980f-43ee12bcf265.png)

**Comment by Uafinder** [comment]
Looks ok at the moment.
tested on my own qa and rhipe site
