### ISSUE TITLE
"Find a broker app" needs to be added to organisations and organisation types

### ISSUE THREAD

**Issue by Anton69arb** [Kademi/kademi-dev#5056]
The customer, 'abn-insured' - requires only the Brokers to view, when you search for a broker - using the application "Find a broker" on this page. at the moment its showing insurers/underwriters. but must only view the brokers.
http://www.australianbrokernetwork.com.au/
http://www.australianbrokernetwork.com.au/find-a-broker.html

The find a broker app is working on the groups at the moment, but, the option that we need will require organizations, as the broker is not a user - as there could be 10 brokers in one area/location, 

Can we add this function to the application as it does not support organizations and organization types yet.

http://version7.abn-insured.kademi.com.au/contenteditor?fileName=become-a-broker-partner.html&miltonUserUrl=/users/mark2&miltonUserUrlHash=40357890-ffb6-4f4f-ac1c-fc5fa9dfe564:X0UTxjKfGjupsiBEHcMMuPOInzM

![1](https://user-images.githubusercontent.com/32444328/36823050-13caf3e4-1d60-11e8-8a4c-d8ae03fdf2ae.png)

**Comment by Anton69arb** [comment]
https://insured.admin.kademi.com.au/websites/abn/version5/

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/37506433-65151258-291c-11e8-8d52-d03781cf9961.png)

jquery-orgFinder is now a lib as well

**Comment by Uafinder** [comment]
It's a OrgLocator component?
If so, so pls note to https://github.com/Kademi/kademi-dev/issues/5161

**Comment by anhnt** [comment]
Fixed #5161 please test again

**Comment by Uafinder** [comment]
Looks good
