### ISSUE TITLE
Bulk find and select locations for organisations

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5058]
On the organisations map page (/organisations/map) do the following:
- show the number of organisations with locations (ie lattitude and longitude)
- show the number of organisations without locations
- if orgs without locations > 0 show a button to find and set them
- when pressed, for each organisation do a google maps search for the provided address (same as is currently done on the org details page), and if a matching location is found set its lat/lng as the organisation coords

Also, ensure orgs with no coords are not included in map search responses

**Comment by gonzalon** [comment]
Button to process in /organisations/map

![image](https://user-images.githubusercontent.com/2773216/37261526-0d11723a-2602-11e8-800d-2b8f3e586a71.png)


For the org to be process it has to have the address set

**Comment by Uafinder** [comment]
Error in console and it doesn't work
![image](https://user-images.githubusercontent.com/1945230/37709891-5fec77a2-2d14-11e8-9bc5-eb1149ffb592.png)
http://vladtest45.admin.kademi-ci.co/organisations/map

**Comment by gonzalon** [comment]
it was failing for wrong addresses fixed that.

**Comment by Uafinder** [comment]
Seeing this kind of error
![image](https://user-images.githubusercontent.com/1945230/37769635-5025cdb6-2dda-11e8-8b08-8f12e562e96d.png)
http://vladtest45a.admin.kademi-ci.co/organisations/map

01:06:16 ERROR io.milton.cloud.server.apps.orglocator.OrgsMapPage  - ex
01:06:16 org.hibernate.TransactionException: Transaction not successfully started
01:06:16 	at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.commit(AbstractTransactionImpl.java:170)
01:06:16 	at io.milton.cloud.server.apps.orglocator.OrgsMapPage.processForm(OrgsMapPage.java:111)
01:06:16 	at io.milton.http.http11.PostHandler.processExistingResource(PostHandler.java:85)
01:06:16 	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:196)
01:06:16 	at io.milton.http.http11.PostHandler.processResource(PostHandler.java:68)
01:06:16 	at io.milton.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:127)
01:06:16 	at io.milton.http.http11.PostHandler.process(PostHandler.java:62)
01:06:16 	at io.milton.http.StandardFilter.process(StandardFilter.java:50)
01:06:16 	at io.milton.http.FilterChain.process(FilterChain.java:46)
01:06:16 	at co.kademi.server.subscription.KademiSubscriptionFilter.process(KademiSubscriptionFilter.java:45)
01:06:16 	at io.milton.http.FilterChain.process(FilterChain.java:46)
01:06:16 	at co.kademi.server.idp.IDPFilter.process(IDPFilter.java:43)
01:06:16 	at io.milton.http.FilterChain.process(FilterChain.java:46)
01:06:16 	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter$1.execute(MiltonOpenSessionInViewFilter.java:41)
01:06:16 	at io.milton.context.RootContext.execute(RootContext.java:90)
01:06:16 	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter.process(MiltonOpenSessionInViewFilter.java:34)
01:06:16 	at io.milton.http.FilterChain.process(FilterChain.java:46)
01:06:16 	at io.milton.http.HttpManager.process(HttpManager.java:158)
01:06:16 	at co.kademi.server.Kademi$1.service(Kademi.java:194)
01:06:16 	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
01:06:16 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
01:06:16 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
01:06:16 	at java.lang.Thread.run(Thread.java:748)
01:06:16 ERROR io.milton.http.StandardFilter  - exception sending content
01:06:16 org.hibernate.TransactionException: Transaction not successfully started
01:06:16 	at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.rollback(AbstractTransactionImpl.java:200)
01:06:16 	at io.milton.cloud.server.apps.orglocator.OrgsMapPage.processForm(OrgsMapPage.java:126)
01:06:16 	at io.milton.http.http11.PostHandler.processExistingResource(PostHandler.java:85)
01:06:16 	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:196)
01:06:16 	at io.milton.http.http11.PostHandler.processResource(PostHandler.java:68)
01:06:16 	at io.milton.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:127)
01:06:16 	at io.milton.http.http11.PostHandler.process(PostHandler.java:62)
01:06:16 	at io.milton.http.StandardFilter.process(StandardFilter.java:50)
01:06:16 	at io.milton.http.FilterChain.process(FilterChain.java:46)
01:06:16 	at co.kademi.server.subscription.KademiSubscriptionFilter.process(KademiSubscriptionFilter.java:45)
01:06:16 	at io.milton.http.FilterChain.process(FilterChain.java:46)
01:06:16 	at co.kademi.server.idp.IDPFilter.process(IDPFilter.java:43)
01:06:16 	at io.milton.http.FilterChain.process(FilterChain.java:46)
01:06:16 	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter$1.execute(MiltonOpenSessionInViewFilter.java:41)
01:06:16 	at io.milton.context.RootContext.execute(RootContext.java:90)
01:06:16 	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter.process(MiltonOpenSessionInViewFilter.java:34)
01:06:16 	at io.milton.http.FilterChain.process(FilterChain.java:46)
01:06:16 	at io.milton.http.HttpManager.process(HttpManager.java:158)
01:06:16 	at co.kademi.server.Kademi$1.service(Kademi.java:194)
01:06:16 	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
01:06:16 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
01:06:16 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
01:06:16 	at java.lang.Thread.run(Thread.java:748)

Also seeing this error
![image](https://user-images.githubusercontent.com/1945230/37769755-b4f4de94-2dda-11e8-9e5a-af82eaeb0a45.png)
It successfully connect location to org, but nevertheless give that error

**Comment by gonzalon** [comment]
Updated to show a more significative message to the user. Fix the error.

**Comment by Uafinder** [comment]
Fresh account
Same for me...
-To reproduce create some orgs
-Then add some addresses (for example in 3 orgs)
-Check that it doesn't return Null address by searching
-try to bulk fit their location
![image](https://user-images.githubusercontent.com/1945230/37818407-bf19c09e-2e82-11e8-8d53-f2d956e31327.png)
![image](https://user-images.githubusercontent.com/1945230/37818438-d11b6644-2e82-11e8-859b-45aa2f49c401.png)
http://vladtest45b.admin.kademi-ci.co/organisations/map
Looks like this error appears when more than 1 org has address...

**Comment by Uafinder** [comment]
Finally it works like a charm!
