### ISSUE TITLE
sales claims settings changing data series does nothing

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5061]
![image](https://user-images.githubusercontent.com/1945230/36842907-e744f13a-1d55-11e8-87e8-044aaa66c40a.png)
![image](https://user-images.githubusercontent.com/1945230/36842916-ee83775a-1d55-11e8-98fd-fcdbd89453bd.png)
![image](https://user-images.githubusercontent.com/1945230/36842925-f5c93b8a-1d55-11e8-822d-ef22b65985ec.png)
1. open settings for sales claims
2. edit data series
3. save
4. nothing changed
http://vladtest38a.admin.kademi-ci.co/manageSaleDataClaimer/#claims-setting-tab

**Comment by tuzzmaniandevil** [comment]
Fixed in salesDataClaimer 1.2.0

**Comment by Uafinder** [comment]
Yeah, now it changes app settings globally for entire account.
