### ISSUE TITLE
Leaderboard EDM component enhance end email look

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5065]
While looks in editor such way
![image](https://user-images.githubusercontent.com/1945230/36891241-9b621360-1e09-11e8-906b-e556d8acdaee.png)
But in the end it looks such way
![image](https://user-images.githubusercontent.com/1945230/36891414-3c74bda2-1e0a-11e8-9f01-71ec1690bce5.png)
http://vladtest38b.admin.kademi-ci.co/groupEmails/7657797/#messages-tab

**Comment by bradmac** [comment]
I think its actually not useable with that lack of styling, all of our clients would reject it.

@ducdhm can you improve its appearance please?

**Comment by ducdhm** [comment]
Done!

**Comment by Uafinder** [comment]
Ok, there are more options, but still looks bad on end side...
In editor
![image](https://user-images.githubusercontent.com/1945230/37099570-50ae053a-2229-11e8-82c9-082baa6e3127.png)
End side
![image](https://user-images.githubusercontent.com/1945230/37099559-47088424-2229-11e8-9539-936bf1400d06.png)
http://vladtest39a.admin.kademi-ci.co/groupEmails/8480336/#messages-tab

**Comment by bradmac** [comment]
Looks ok to me in thunderbird
![image](https://user-images.githubusercontent.com/826458/37117227-7e8cd35a-22b5-11e8-9c6d-729abf9e3244.png)

**Comment by bradmac** [comment]
@ducdhm can you please do a litmus test?

**Comment by ducdhm** [comment]
Fixed!

**Comment by AlaaKhalaf94** [comment]
I see that's fine now
