### ISSUE TITLE
debit points for user failed when points bucket connected to orgs

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5070]
![image](https://user-images.githubusercontent.com/1945230/36898891-6b0eaaf4-1e25-11e8-8c97-24eae32f24cd.png)
You have points which are assigned to org
When you try to debit some points, it says that user can't be located. However user exited and linked to organisation,
Same thing works ok with awarding points
http://vladtest38b.admin.kademi-ci.co/points-buckets/points/

**Comment by bradmac** [comment]
@Uafinder i think this is probably because the points bucket has been setup to award points to an organisation, but no org type has been selected. Entering the OrgID of org00002 works correctly.

@tuzzmaniandevil please update this and the credit screen to use the entity finder plugin. Both should work the same way.

**Comment by Uafinder** [comment]
Same for me:
![image](https://user-images.githubusercontent.com/1945230/36974064-ff1a631e-207d-11e8-9a2a-5ec7f6cd909a.png)
http://vladtest38d.admin.kademi-ci.co/points-buckets/points/

**Comment by bradmac** [comment]
@tuzzmaniandevil please ensure both credits and debits work the same way in resolving participants.

**Comment by gonzalon** [comment]
Just tested it here: http://vladtest38d.admin.kademi-ci.co/points-buckets/points/ 
Seems that its all working as it should!

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/37340170-e6997aac-26c5-11e8-862a-28d4ff70c540.png)
Hey @gonzalon 
I've a points bucket points2 (http://vladtest38d.admin.kademi-ci.co/points-buckets/points2/#details-tab)
it setup to award points to user's org, so when user award - points go to user... same as with debits...
so, for debit points I try to select a user, userqa20 for example, it gives me that user in selector, but when I try to debit points - it give me an error

**Comment by gonzalon** [comment]
@Uafinder when the points bucket its configured as:
- Points go to user: you can search for users
- Points go to user's organisation: you can search for orgs

It's not finding the user because its searching for an org!

**Comment by Uafinder** [comment]
ok
