### ISSUE TITLE
Possibility to create category with codes contains spaces caused bugs

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5071]
There are no validation when create a category.
Code field must not contain spaces and some complex symbols
![image](https://user-images.githubusercontent.com/1945230/36903264-e0b139f6-1e35-11e8-8350-aa29d9ef206c.png)

possibility to create category with complex code, caused bugs on new searching and filtering
![image](https://user-images.githubusercontent.com/1945230/36903332-1e0ff8be-1e36-11e8-861c-72caf046c712.png)
![image](https://user-images.githubusercontent.com/1945230/36903342-248fe884-1e36-11e8-8ea1-6a96a1774fd1.png)

**Comment by ducdhm** [comment]
Fixed!

**Comment by Uafinder** [comment]
Yeah, looks fine
