### ISSUE TITLE
Should text panel be linked to some component or porbably to the top?

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5072]
![image](https://user-images.githubusercontent.com/1945230/36932268-3c8fb77c-1ecf-11e8-86b3-4e477bc8a3ab.png)
While editing text, there are often comes a UX problem dedicated to a text panel. It could cover some elements of interface.
How do you think, should it be linked to some place (probably to the top)?

**Comment by bradmac** [comment]
@ducdhm what do you think?

**Comment by ducdhm** [comment]
I think dock it at top is better UX

**Comment by bradmac** [comment]
I think floating is good, its more obvious what it is that you're editing.

I dont think this is a critical issue and we can ignore for now

**Comment by bradmac** [comment]
@Uafinder i think we can close this issue unless there is a specific situation where its preventing users from doing something

**Comment by Uafinder** [comment]
ok, no probs
