### ISSUE TITLE
Timer queue is empty bu should contain some element

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5074]
![image](https://user-images.githubusercontent.com/1945230/36933367-3db0f736-1ee0-11e8-9114-0b620b254dbe.png)
http://vladtest38c.admin.kademi-ci.co/funnels/journey1/version1/timerGoal-dc338f
1. Create a lead
2. Watch timer goal page

**Comment by tuzzmaniandevil** [comment]
The panel shows a count of all leads in the queue, The table shows timers that are due. So the above is correct.

**Comment by tuzzmaniandevil** [comment]
We have changed to table to show items in the queue now

**Comment by Uafinder** [comment]
Understood, looks ok now
