### ISSUE TITLE
Kfeedback - can't submit feedback

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5076]
![image](https://user-images.githubusercontent.com/1945230/36933891-5479e35c-1ee9-11e8-851f-c5811258e24e.png)
http://vladtest38cweb-vladtest38c.kademi-ci.co/send-feedback/?survey=feed&option=happy1
Had an error in console and no feedback submitted
http://version1.vladtest38cweb-vladtest38c.kademi-ci.co/kpiqa01.html
Also please note that default emoticons not appear
![image](https://user-images.githubusercontent.com/1945230/36933907-b4616272-1ee9-11e8-83d6-d205e6be23ca.png)

**Comment by ducdhm** [comment]
Default icons are fixed!

**Comment by ducdhm** [comment]
Show error message when submitting is error.

@Uafinder KFeedback HTML template is used for EDM. So when you send in EDM, login token will be added to the link of KFeedback options. So when you click the link in EDM, you'll be logged-in automatically.

**Comment by Uafinder** [comment]
When added HTML text to EDM (default)
![image](https://user-images.githubusercontent.com/1945230/36971642-291a5a2e-2075-11e8-8e42-6eca3a3c209c.png)
![image](https://user-images.githubusercontent.com/1945230/36971708-5afacad8-2075-11e8-97a6-ae206213bb01.png)

When submitting feedback
![image](https://user-images.githubusercontent.com/1945230/36971796-a6f9f01c-2075-11e8-9f28-afd99218d252.png)
even if you force login tokens to all links in email settings
![image](https://user-images.githubusercontent.com/1945230/36972329-615e1220-2077-11e8-9159-a3cee7b0764d.png)

Also please note that Copy to email button does nothing

**Comment by ducdhm** [comment]
@Uafinder Why you dont test in fresh account?

I tested in fresh account and everything work normally! http://duc-test-11.admin.kademi-ci.co/kfeedback/#!/surveys/test

**Comment by Uafinder** [comment]
Well, now it looks like this
![image](https://user-images.githubusercontent.com/1945230/37024548-d19347f8-2131-11e8-91fb-f3e94a108795.png)
http://vladtest38f.admin.kademi-ci.co/kfeedback/#!/surveys/list

![image](https://user-images.githubusercontent.com/1945230/37024693-40842920-2132-11e8-9c8a-833ab911b9ed.png)

**Comment by ducdhm** [comment]
I think I'll remove HTML Template in kfeedback admin screen. We dont need it anymore. We already have component for it

**Comment by bradmac** [comment]
hey @Uafinder the error in the logs says "no current user". Are you logged in

**Comment by ducdhm** [comment]
I have fixed. So instead of check `miltonUserUrl` param, kfeedback will use `securityManager.currentUser` to get current user

**Comment by Uafinder** [comment]
Fresh account, cache completely cleared
Bunch of errors while submitting survey:
![image](https://user-images.githubusercontent.com/1945230/37098553-d1e197aa-2226-11e8-9ccd-098294133078.png)
http://vladtest39a.admin.kademi-ci.co/groupEmails/8477610/#sendInfo-tab

After some try next error appears
![image](https://user-images.githubusercontent.com/1945230/37098768-60f3c4fe-2227-11e8-8cea-539f8d39af33.png)

![image](https://user-images.githubusercontent.com/1945230/37098840-91cdaf7c-2227-11e8-8282-78111a205de1.png)

**Comment by anhnt** [comment]
Fixed

- jquery not found error due to new consolidate dependencies changes
- cant submit feedback due to fire `kfeedbackSubmittedGoal` without current logged in user. So i added a fix that checks if there is logged in user before submitting feedback

**Comment by Uafinder** [comment]
Well,
1. Fresh account
2. Create a website
3. Install kfeedback there
4. Create email, select "add links" checkbox
5. Add a component there and configure it
6. Send test
7. After receiving email try to click on any emoticon
8. Watch errors
![image](https://user-images.githubusercontent.com/1945230/37282956-e2fdd342-25fe-11e8-880e-162d95b7b29d.png)
http://vladtest40c.admin.kademi-ci.co/groupEmails/9520585/#sendInfo-tab

**Comment by anhnt** [comment]
looks like there is issue with jquery lib. i am checking now

**Comment by Uafinder** [comment]
Yeah, looks good at the moment
