### ISSUE TITLE
Integration History: Use date range selector and paginator

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#5078]

**Comment by Uafinder** [comment]
More info pls

**Comment by gonzalon** [comment]
hey @Uafinder I added the paginator for this page:
![image](https://user-images.githubusercontent.com/2773216/37571456-c598c3b2-2b61-11e8-9dba-a08041e083ae.png)

**Comment by Uafinder** [comment]
ok
