### ISSUE TITLE
Add validation logic to version names to prevent upper case characters

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#5081]
http://swimart.admin.kademi.com.au/websites/swimart/swimart-18R1/#panel_details-tab

View this version and get the error message

```
The host name swimart-18r1.swimart-swimart.kademi.com.au was not found on this server

**Comment by anhnt** [comment]
The problem is version name contains uppercase char.

**Comment by bradmac** [comment]
@ducdhm can you please update the validation logic for creating new versions to ensure names are all lowercase?

**Comment by Uafinder** [comment]
validation works ok
