### ISSUE TITLE
points markers are bad on front-end

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5086]
![image](https://user-images.githubusercontent.com/1945230/37035494-697aa6f6-2155-11e8-9318-e26ae0ea5db9.png)
http://vladtest39aucstore_vladtest39.kademi-ci.co/dashboard
http://vladtest39.admin.kademi-ci.co/websites/

**Comment by bradmac** [comment]
the fontawesome-lib hasnt been deployed properly
![image](https://user-images.githubusercontent.com/826458/37056183-802ad84c-21e8-11e8-9218-b36a74db428f.png)

**Comment by bradmac** [comment]
The files in source code were corrupt.

Fixed.

**Comment by AlaaKhalaf94** [comment]
tested
