### ISSUE TITLE
Add support for content-base and list-unsubscribe headers when sending emails

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5089]
List-unsubscribe
----
https://stackoverflow.com/questions/4365850/list-unsubscribe-in-e-mail-header-how-to#7804157

Content-base
----
Base to be used for resolving relative URIs within this content part. | Content-Base: | RFC 2110
-- | -- | --

Looks like this in thunderbird
![image](https://user-images.githubusercontent.com/826458/37060803-3cfa9f0e-21f6-11e8-8eb8-155d37d7ec23.png)

**Comment by Uafinder** [comment]
How can I test this one?

**Comment by bradmac** [comment]
just check for regression errors. if we can still send emails then its ok :)

**Comment by Uafinder** [comment]
It works!
