### ISSUE TITLE
jouney builder - can't remove connection line

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5093]
1. Create journey
2. Add some blocks and connections
3. Click delete on some connection
4. Nothing is happened
![image](https://user-images.githubusercontent.com/1945230/37100430-95b1ba94-222b-11e8-9e5a-75c79278fa29.png)
http://vladtest39a.admin.kademi-ci.co/funnels/journey2/version1/#journeyBuilder-tab

**Comment by bradmac** [comment]
I can see this error in JS:
```
jsPlumb: fire failed for event click : TypeError: portData is undefined
```

**Comment by bradmac** [comment]
@ducdhm can you please take a look?

And please add logging so that if this situation occurs we get a decent message in the logs.

**Comment by AlaaKhalaf94** [comment]
passed
