### ISSUE TITLE
title of the selected organisation component needs adjusting

### ISSUE THREAD

**Issue by Anton69arb** [Kademi/kademi-dev#5095]
When you drag the display the title of the selected organisation component into the container it does not show an example, or any setting or to move it or delete the component, please can we fix this

![when you drag it into the container it does not show an example or any setting or to move it or delete the component please can we fix this](https://user-images.githubusercontent.com/32444328/37127737-ef29d5b0-22db-11e8-92e8-5d28ac3d80e0.png)

http://antleaddman2.admin.kademi-ci.co/pages/antleaddman2/version1/
click on the dashboard template

**Comment by ducdhm** [comment]
Done!

**Comment by AlaaKhalaf94** [comment]
I can't see your update

http://new-test88.admin.kademi-ci.co/pages/new-test88/version1/
in dashboard page

**Comment by ducdhm** [comment]
@AlaaKhalaf94 Did you update latest code in CI?

**Comment by ducdhm** [comment]
I have updated latest code in CI and it's workning normally. Seems like you forgot to update in CI.

Link to check: http://duc-test-12.admin.kademi-ci.co/pages/duc-test-12-ste/version1/

**Comment by AlaaKhalaf94** [comment]
tested
