### ISSUE TITLE
Refactor app settings to use repository persistence

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5096]
Its very inefficient using hibernate to persist app settings.

Instead, use an immutable object containing all app settings read from the website repository and cached in memory with the hash as the cache key

Also, do the same for org level app settings by using a special org settings repo. This repo should be used for all account config and settings, eg IDP

**Comment by bradmac** [comment]
Hi @Uafinder please give this a thorough test. This is a change to how apps are managed. There should be no visible result to users, but it could potentially affect any part of Kademi involving manipulation of apps.

So please verify:
- creatting new accounts and websites
- installing apps from the marketplace
- turning apps on and off through the apps tab, at website and org level
- editing app settings, at website and org level

**Comment by bradmac** [comment]
Moved settng lookup into a consolidated service, but is currently still using DB settings.

Also created a repo implementation, but not currently being used, still needs to be finished

**Comment by bradmac** [comment]
OK, seems to be working, but will leave it out of app.js until after this deploy

**Comment by bradmac** [comment]
Enabled and pushed. Lets see how it goes this time.

**Comment by bradmac** [comment]
@Uafinder over to you. Please ensure that the normal processes for creating websites and accounts continue to work, as well as installing and updating apps.

Note that existing accounts and apps should have their existing settings copied to the file on the first change, ie enabling/disabling an app or editing settings

You should be able to see changes in the website repository

Eg http://bradtesta1.admin.kademi-ci.co/repositories/w1/version1/

![image](https://user-images.githubusercontent.com/826458/38528464-f9de7672-3cb3-11e8-9825-4e9c64a1a886.png)

**Comment by Uafinder** [comment]
I've access some old account...install new app, edit some settings
WEB-INF folder was created, but there are no file inside
http://vladtest47.admin.kademi-ci.co/pages/vladtest47web/version1/WEB-INF/

new account apps manage looks good

**Comment by Uafinder** [comment]
aha found it

**Comment by Uafinder** [comment]
ok, but why xml file doesn't contain some apps records:
- for example - Reports, User registration and signup, Forums, topics and questions... their options are missed in configuration file.

**Comment by bradmac** [comment]
@Uafinder I've pushed a fix, and retested with your account.

I deleted the settings.xml file, then enabled the alerts app (previously is was disabled) and thats generated the new settings.xml file which appears to include records correctly

**Comment by bradmac** [comment]
Apps page after enabling alerts, but without refreshing:
![image](https://user-images.githubusercontent.com/826458/38964903-ade46648-43cd-11e8-9d3b-9c6c3b0c58ba.png)

**Comment by bradmac** [comment]
Settings file:
http://vladtest47.admin.kademi-ci.co/repositories/vladtest47web/version1/WEB-INF/texteditor?fileName=settings.xml

Reporting is now included
```
  <app appInstanceId="Reporting" enabled="true">
    <settings>
      <entry>
        <string>reindexDays</string>
        <string>65</string>
      </entry>
    </settings>
  </app>
```

**Comment by Uafinder** [comment]
Created new account
Install there some apps
the go to apps page
Change reporting interval for Reports
Change product app setting from classical editor to keditor
but there are no sights of this changes in XML file
However some other options is successfully fall there
http://vladtest49f.admin.kademi-ci.co/repositories/vladtest49faucstore/version1/WEB-INF/texteditor?fileName=settings.xml
http://vladtest49f.admin.kademi-ci.co/websites/vladtest49faucstore/version1/#panel_apps-tab

**Comment by bradmac** [comment]
@Uafinder I think the repository settings was disabled when you tested, because we needed to release with the old settings.

**Comment by bradmac** [comment]
> Change product app setting from classical editor to keditor

Note that this setting is held at the org level, not the website. Thats why its not persisted to website settings. This is because the editing is done in the org.

**Comment by bradmac** [comment]
> Change reporting interval for Reports

Same here, that setting doesnt (and cant) apply to a specific website so it applies to the org, so isnt in website settings

**Comment by bradmac** [comment]
Here's one you can see:
![image](https://user-images.githubusercontent.com/826458/39412566-a8472402-4c72-11e8-85f7-68ce5cb1f4a3.png)

![image](https://user-images.githubusercontent.com/826458/39412568-b53b2460-4c72-11e8-9a19-a77b42a8111b.png)

**Comment by Uafinder** [comment]
Yeah, looks fine
