### ISSUE TITLE
not displaying a histogram of debits reports

### ISSUE THREAD

**Issue by Anton69arb** [Kademi/kademi-dev#5097]
Component for reward store - Display a histogram of debits reports

Not showing information, 
cant setup the component/ assign it to a reward store and is not viewing debited points
please may we fix this

![screenshot-antleaddman2-antleaddman2 kademi-ci co-2018 03 09-10-01-58](https://user-images.githubusercontent.com/32444328/37176584-a9191fc6-2381-11e8-9b52-ef33001edff0.png)

http://antleaddman2.admin.kademi-ci.co/pages/antleaddman2/version1/
http://version1.antleaddman2-antleaddman2.kademi-ci.co/dashboard

**Comment by bradmac** [comment]
```
TypeError: chart.update is not a function
```

**Comment by bradmac** [comment]
@ducdhm also the org selector component isnt displaying, can you check that out please?

**Comment by ducdhm** [comment]
@bradmac I got this error when load this component

```Error rendering component: debitsActivity<br/>class org.apache.velocity.exception.MethodInvocationException - Invocation of method 'getDebitsHistogram' in  class com.fuselms.apps.rewardstore.RewardStoreApp threw exception Failed to execute phase [query], all shards failed; shardFailures {[GTGdNT_mQrGXiDqJaFsFEA][local1-rewardpointsdebit-1][0]: RemoteTransportException[[GTGdNT_][local[1]][indices:data/read/search[phase/query]]]; nested: ElasticsearchParseException[failed to parse date field [Fri Mar 09 00:00:00 ICT 2018] with format [strict_date_optional_time||epoch_millis]]; nested: IllegalArgumentException[Parse failure at index [0] of [Fri Mar 09 00:00:00 ICT 2018]]; }{[GTGdNT_mQrGXiDqJaFsFEA][local1-rewardpointsdebit-1][1]: RemoteTransportException[[GTGdNT_][local[1]][indices:data/read/search[phase/query]]]; nested: ElasticsearchParseException[failed to parse date field [Fri Mar 09 00:00:00 ICT 2018] with format [strict_date_optional_time||epoch_millis]]; nested: IllegalArgumentException[Parse failure at index [0] of [Fri Mar 09 00:00:00 ICT 2018]]; }{[GTGdNT_mQrGXiDqJaFsFEA][local1-rewardpointsdebit-1][2]: RemoteTransportException[[GTGdNT_][local[1]][indices:data/read/search[phase/query]]]; nested: ElasticsearchParseException[failed to parse date field [Fri Mar 09 00:00:00 ICT 2018] with format [strict_date_optional_time||epoch_millis]]; nested: IllegalArgumentException[Parse failure at index [0] of [Fri Mar 09 00:00:00 ICT 2018]]; }{[GTGdNT_mQrGXiDqJaFsFEA][local1-rewardpointsdebit-1][3]: RemoteTransportException[[GTGdNT_][local[1]][indices:data/read/search[phase/query]]]; nested: ElasticsearchParseException[failed to parse date field [Fri Mar 09 00:00:00 ICT 2018] with format [strict_date_optional_time||epoch_millis]]; nested: IllegalArgumentException[Parse failure at index [0] of [Fri Mar 09 00:00:00 ICT 2018]]; }{[GTGdNT_mQrGXiDqJaFsFEA][local1-rewardpointsdebit-1][4]: RemoteTransportException[[GTGdNT_][local[1]][indices:data/read/search[phase/query]]]; nested: ElasticsearchParseException[failed to parse date field [Fri Mar 09 00:00:00 ICT 2018] with format [strict_date_optional_time||epoch_millis]]; nested: IllegalArgumentException[Parse failure at index [0] of [Fri Mar 09 00:00:00 ICT 2018]]; } at local-bs_rootorg.loopbackdns.com:/theme/apps/rewardstore/debitsActivityComponent.html[line 21, column 31]```

**Comment by gonzalon** [comment]
![image](https://user-images.githubusercontent.com/2773216/37372917-750bfc2a-2779-11e8-94cd-fedce7bdf30c.png)

**Comment by Uafinder** [comment]
looks good
