### ISSUE TITLE
Gaps between containers

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#5103]
http://kademi-www.admin.kademi.us/pages/kademi-www/version1/

@ducdhm why are there gaps appearing inbetween nested containers?  Is this Keditor or the theme?  I need nested containers in a 3 col grid to be flush with each other.

![image](https://user-images.githubusercontent.com/2201340/37239414-755879de-248f-11e8-844d-db842e1825e5.png)

**Comment by ducdhm** [comment]
New Options: 
![newui](https://user-images.githubusercontent.com/1289631/37274262-b40101d0-260e-11e8-9a1b-cee923af378e.png)

**Comment by AlaaKhalaf94** [comment]
passed
