### ISSUE TITLE
Images uploading into the root

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#5104]
http://kademi-www.admin.kademi.us/repositories/kademi-www/version1/

Why are uploaded images via Keditor uploading into the root of the website? They should go into the theme/images folder.

![image](https://user-images.githubusercontent.com/2201340/37250069-42b30774-2548-11e8-8674-a5ef4d288fbc.png)

**Comment by bradmac** [comment]
No, they should not be uplaoded to theme/images by default.

The theme/images folder is only for assets used by the theme. Images which are page content should usually be in the same folder as the page they're used on (by default)
