### ISSUE TITLE
Server 500 error on whole account after Reward store installation

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5106]
1. Create a fresh account
2. Create a website
3. Install a reward store app there
4. Watch error page
![image](https://user-images.githubusercontent.com/1945230/37281681-881e98ca-25fa-11e8-9a37-4769f1f7010a.png)
http://vladtest40a.admin.kademi-ci.co
http://vladtest40.admin.kademi-ci.co
http://vladtest40b.admin.kademi-ci.co

**Comment by bradmac** [comment]
I think is ok now

**Comment by Uafinder** [comment]
Yeah, error doesn't appear
