### ISSUE TITLE
jquery libs are not installed when creating new account/website

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#5108]
Steps to reproduce:

Create fresh account, then create new website on it

```
anh No app dependencies for repo app bootstrap-base version=io.milton.vfs.db.Branch@654778c621:50:19
INFO anh Dependencies file not found /theme/apps/bootstrap-base/dependencies.json21:50:19
INFO anh checkAppDependencies: is dependent app.21:50:19
INFO anh setStatus: appId=bootstrap-base branch=version1 enabled=true appControlId=963714621:50:19
INFO anh setStatus: appId=bootstrap-base enabled=true appControlId=963686321:50:19
INFO anh App bootstrap-base of type class io.milton.cloud.server.repoapps.RepositoryApp is already installed. Will enable it21:50:19
INFO anh Found missing dependency bootstrap-base:1.6.9 of k-theme, attempting to install21:50:19
INFO anh Missnig app: content-lib21:50:19
INFO anh Missnig app: bootstrap-base21:50:19
INFO anh getMissingDepenencies: Found 2 deps for app k-theme

**Comment by anhnt** [comment]
http://anhtest20.admin.kademi-ci.co/websites/anhw2/version1/#panel_details-tab

**Comment by anhnt** [comment]
https://github.com/Kademi/kademi-dev/issues/5076

**Comment by anhnt** [comment]
Still not working on CI after rebuilt and update kademi dev

**Comment by anhnt** [comment]
i spotted a case that doesnt install needed libs
when created new account, then created a website, it doesnt install libs like jquery, ckeditor, contentEditor, keditor, etc
But when i go to theme setting and install other theme like bootstrap-theme, it will install those libs although there are still missing libs like **keditor-lib**

**Comment by bradmac** [comment]
OK, i think is fixed now

**Comment by Uafinder** [comment]
Still looks not enabling some libs
Fresh account:
http://vladtest40e.admin.kademi-ci.co/
![image](https://user-images.githubusercontent.com/1945230/37331980-236397dc-26ae-11e8-914c-54cd666c2a3d.png)

**Comment by bradmac** [comment]
Seems ok with a fresh account:
http://issue5108.admin.kademi-ci.co/sales/s17692/#general-tab

**Comment by Uafinder** [comment]
yup, looks fine now
