### ISSUE TITLE
Points multipliers

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#511]
Reward store clients need to be able to incentivise particular participants with points multipliers.

A multiplier means that whenever points are loaded (possibly for a certain tag?) the actual points inserted are multiplier.

The facility should allow future extension to support transfers, where some points are allocated to related parties

https://github.com/Kademi/client-emc-repco/issues/6

**Comment by tuzzmaniandevil** [comment]
Please note I added an organisation column.

**Comment by bradmac** [comment]
Can you put some notes on the milestone?
