### ISSUE TITLE
journey app installation cause 500 error

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5111]
1. Create a fresh account
2. Create a website
3. Install journeys app there
4. Try to open journey
![image](https://user-images.githubusercontent.com/1945230/37339993-320d0720-26c5-11e8-9e11-c6d0c4c242ac.png)
http://vladtest40f.admin.kademi-ci.co/funnels/first-journey/version1/

**Comment by bradmac** [comment]
Seems ok
http://issue5108.admin.kademi-ci.co/websites/issue5108w1/version1/#panel_apps-tab

**Comment by Uafinder** [comment]
looks fine now
