### ISSUE TITLE
Vaya Master - error "Handlebars is not defined" appear in lead page

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#5112]
In lead page on vaya-master admin , error "Handlebars is not defined" appear in console although handlebars-lib is enable

![untitled01](https://user-images.githubusercontent.com/26510030/37342278-c405fa5e-26cc-11e8-8473-17b9490c74b5.png)

http://vaya-master.admin.kademi-ci.co/leads/4728163/#information-tab

This error did not appear before last update

**Comment by bradmac** [comment]
Looks ok currently - http://vaya-master.admin.kademi-ci.co/leads/4728163/#information-tab

**Comment by AlaaKhalaf94** [comment]
Thanks
