### ISSUE TITLE
profile transactions component - minor issue

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5113]
![image](https://user-images.githubusercontent.com/1945230/37349601-7de7bafe-26df-11e8-89d7-b7906917093f.png)
When points award doesn't contain award reason it shows in a bad way
http://vladtest40fweb-vladtest40f.kademi-ci.co/profile/
http://vladtest40f.admin.kademi-ci.co/

**Comment by Uafinder** [comment]
Same thing
![image](https://user-images.githubusercontent.com/1945230/37461978-f97d2a94-2858-11e8-99b7-5c0b95766208.png)
http://vladtest41bweb-vladtest41b.kademi-ci.co/profile/
http://vladtest41b.admin.kademi-ci.co/manageApps/#installed-tab

**Comment by gonzalon** [comment]
sorry I forgot to push yesterday :-/ 
rewardstore-lib: 1.4.3

**Comment by Uafinder** [comment]
Yup, looks ok
