### ISSUE TITLE
profile memberships removing bug when member of one group in different orgs

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5114]
For example user is a participant in org00001 and rootorg
When he click on X in his profile to remove one membership, it removes both memberships (probably all memberships with this name)
![image](https://user-images.githubusercontent.com/1945230/37351038-d997b284-26e2-11e8-8df0-b355388a6632.png)
http://vladtest40fweb-vladtest40f.kademi-ci.co/profile/
http://vladtest40f.admin.kademi-ci.co/manageUsers/9776223/#summary-tab

**Comment by gonzalon** [comment]
Can't reproduce, check the code and its deleting the membership by the ID!!

**Comment by Uafinder** [comment]
was easily able to reproduce
http://vladtest41b.admin.kademi-ci.co/manageUsers/10165095/#summary-tab
login as this user
try to delete root membership
![image](https://user-images.githubusercontent.com/1945230/37461581-73d33cd6-2857-11e8-9157-f852ccbcd423.png)
then refresh
you will see that user loose all of his memberships

**Comment by gonzalon** [comment]
@Uafinder sorry, you were right! now it should be fixed

**Comment by Uafinder** [comment]
No probs :)
Looks ok now
