### ISSUE TITLE
Test module renewal/expiry functionality

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#5116]
1- Setup an account on QA.. with a learning module.. that has an expire date and a renewal period..
2- Create 2 to 3 emails to remind the user that the learning module they've finished is about to expire (Exactly like the Zoetis gudair emails)
3- Use time simulator in CI to emulate time passes.. make sure module opens for renewal 2 months before expire.. make sure all reminder emails reach users.. and make sure users can actually retake the module in the renewal time

**Comment by Uafinder** [comment]
Vlad 1:18 PM
and it doesn't fire any actions when 10 month past
http://vladtest44c.admin.kademi-ci.co/autoEmails/
i've setup such automation
first email should fire when renewal become available
i've moved time to the required one, but it won't fire

mkhoudary 1:21 PM
what is the time?

Vlad 1:22 PM
current server time
19 January 2019 12:51:56 PM

mkhoudary 1:22 PM
hmm

Vlad 1:22 PM
http://vladtest44c.admin.kademi-ci.co/training/?startDate=14/03/2018&endDate=20/03/2018

mkhoudary 1:22 PM
The renewal time is 19/01/2019 12:45

Vlad 1:22 PM
yeah

**Comment by gonzalon** [comment]
Did some updates and test it whit the same account @Uafinder was using now I can see:
![image](https://user-images.githubusercontent.com/2773216/37690189-47302430-2d0e-11e8-86ba-9464cfeadcfc.png)

**Comment by Uafinder** [comment]
Fresh account
Have a module
![image](https://user-images.githubusercontent.com/1945230/37707701-be1a5040-2d0c-11e8-9b82-c547cc735dea.png)
![image](https://user-images.githubusercontent.com/1945230/37707726-cd6911da-2d0c-11e8-89cf-2664a690f782.png)
![image](https://user-images.githubusercontent.com/1945230/37707756-eaeecaec-2d0c-11e8-96f9-45a07ad773a2.png)
http://vladtest45.admin.kademi-ci.co/autoEmails/
http://vladtest45.admin.kademi-ci.co/training/?startDate=15%2F03%2F2018&endDate=21%2F03%2F2018
renewal email still not firing for me...

**Comment by gonzalon** [comment]
@Uafinder the thing is that the query would go from (CURRENT_DATE - 7) to in this case Sun Jan 20 23:59:32 NZDT 2019

so its not finding the module to renew, to try this you can use the simulate time and also can force the renew process to be fired  

![image](https://user-images.githubusercontent.com/2773216/37739531-3fccec08-2dbf-11e8-8777-c844e0edb0eb.png)

**Comment by bradmac** [comment]
Also, note that with renewal we dont really care exactly when it gets sent. It needs to be a couple of months before expiry but the exact number of days isnt important

**Comment by Uafinder** [comment]
1. Create module, setup renewal policy to 1 year
2. Create some automation steps, to fire when completed, when renewal available, 30 days and 60 days delay after that
3. finish module
4. renewal time what setup to 21/01/2019 21:56
5. As we discussed and find out some source code with Mo there are 7 days more after this date (not sure why)
Date to = CurrentDateService.now();
Date from = f.addHours(to, -7 * 24); // allow processing records up to 7 days ago, in case they were missed
6. So we decided to move date in simulator to 28/01/2019 21:54
7. Then i wait for several minutes, but nothing changed. Renewal not become available and automation not fired as well
http://vladtest45a.admin.kademi-ci.co/training/?startDate=16%2F03%2F2018&endDate=22%2F03%2F2018

**Comment by Uafinder** [comment]
ok, as discussed we split it into two tasks:
1- test it works manual
2- test using simulator as he says

So, first one
After running expiry process job it removes data from module activity page
![image](https://user-images.githubusercontent.com/1945230/37763819-bf9d81c8-2dc8-11e8-920b-6317447505ca.png)
http://vladtest45a.admin.kademi-ci.co/websites/vladtest45aweb/version1/programs/Program1/Course1/TitleModule1/#activity-tab

However it says that it's processed into user page.
http://vladtest45a.admin.kademi-ci.co/manageUsers/12024409/#learningAppTab-tab

**Comment by mkhoudary** [comment]
@Uafinder after testing locally.. the timer that does the renewal runs every 1 hour.. this is not related to simulator.. so it shall take its time.. my local testing showed 100% correct behavior so best thing is to:
1- Create a fresh user
2- Set time back to 10 months ago using simulator
3- Complete module activity
4- Set time back to normal
Then wait until later.. or tomorrow and let's see..

**Comment by Uafinder** [comment]
@mkhoudary 
Ok, I've test a provided case:
as a result:
- module become processed in user activity tab;
![image](https://user-images.githubusercontent.com/1945230/37816273-2b9a01c8-2e7b-11e8-890f-aed731830de6.png)
- module lost his score and percentage of completion in module activity tab (Mo says that it's ok)
![image](https://user-images.githubusercontent.com/1945230/37816308-48914a52-2e7b-11e8-84d1-29826a034b88.png)
- training result remains the same
![image](https://user-images.githubusercontent.com/1945230/37816340-64e698ec-2e7b-11e8-91d6-46f41fcd8e4c.png)

So, what out next step?

**Comment by mkhoudary** [comment]
I've checked this.. this shall be fine.. when the user renews the module this will change.
