### ISSUE TITLE
Certificare doesn't show images which are placed in assets

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5118]
1. Create a certificate
2. Upload one image to assets and one as regular
3. Save
4. Add certificate to module
5. Save module
6. Push preview
Note that image from assets doesn't appear
![image](https://user-images.githubusercontent.com/1945230/37399016-0be26fa8-2789-11e8-945a-11ab09ebdbb0.png)
![image](https://user-images.githubusercontent.com/1945230/37399028-14499c66-2789-11e8-9442-e1e7dfd67832.png)
http://vladtest41a.admin.kademi-ci.co/certificates/cert_9961495/?useHash=true

**Comment by bradmac** [comment]
That's happening because permission is being denied.

However, the image has the public type and this appears to have the correct permission

**Comment by bradmac** [comment]
I've adjusted so that asset permissions apply to assets loaded through the admin as well as front end websites

**Comment by Uafinder** [comment]
Yup, it works!
