### ISSUE TITLE
error in console while loading dashboard

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5119]
![image](https://user-images.githubusercontent.com/1945230/37400658-445a8848-278e-11e8-94b6-ec60df5036f7.png)
http://vladtest41a.admin.kademi-ci.co/
1. Fresh account
2. create a website
3. install learning app

**Comment by bradmac** [comment]
Dependencies werent being installed in the new account. Should be fixed now

**Comment by Uafinder** [comment]
Yeah, looks so
