### ISSUE TITLE
My learning page course selector appears always and block some modules from start

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5120]
![image](https://user-images.githubusercontent.com/1945230/37403661-3fb0ce1a-2798-11e8-9d34-1de351b2f3bb.png)
http://version1.vladtest41aweb-vladtest41a.kademi-ci.co/myLearning
http://vladtest41a.admin.kademi-ci.co/groups/learners/

When open page selector is already activated and no possibility to collapse it.

probably a related issue
no navigation buttons appear for user when he accessing module page
![image](https://user-images.githubusercontent.com/1945230/37403956-133cd166-2799-11e8-9f81-3a76fad1a177.png)
http://version1.vladtest41aweb-vladtest41a.kademi-ci.co/programs/Program1/Course1/Module1/ppage1.html

**Comment by anhnt** [comment]
Please test with new account

**Comment by Uafinder** [comment]
Yeah, looks good at the moment
