### ISSUE TITLE
Unable to send a test email to an email address that exists

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#5122]
This is the email test@kademi.co

This is the automation https://zoetis.admin.kademi.com.au/autoEmails/78437262/?startDate=15/03/2008&finishDate=15/03/2018#action-tab

![image](https://user-images.githubusercontent.com/2201340/37428988-12afa46a-2822-11e8-85dd-2a8ee2031a21.png)

**Comment by paddyow** [comment]
Seems like this occurs when the profile has a duplicate under disabled users.

![image](https://user-images.githubusercontent.com/2201340/37429615-f7a51fcc-2823-11e8-99d0-e66fd3992667.png)

**Comment by bradmac** [comment]
You cant send because the automation is disabled. 

If you dont want to enable it for testing then duplicate it (with the duplicate function), and either change the trigger condition or uncheck the recipient to ensure it doesnt do anything. Then you can test it.
