### ISSUE TITLE
Text editor not working

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#5124]
Error in console log

```
Uncaught ReferenceError: Handlebars is not defined
   
    at fire (jquery-1.11.0.js:3099)
    at Object.fireWith [as resolveWith] (jquery-1.11.0.js:3211)
    at Function.ready (jquery-1.11.0.js:3423)
    at HTMLDocument.completed (jquery-1.11.0.js:3453

**Comment by anhnt** [comment]
http://viri.admin.kademi.com.au/pages/viridian-club-reps/version1/texteditor?fileName=index.html

**Comment by anhnt** [comment]
i have checked and confirmed handlebar-lib is enabled both account and website

**Comment by bradmac** [comment]
Problem is just that the handlebars repo is invalid in that account. Please use set hash to sync it with the primary

**Comment by anhnt** [comment]
working ok now
