### ISSUE TITLE
Create User Visits QueryTable

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5125]
Please create a querytable (ie with controllerMappings.addTableDef) to reporting-lib which returns users and their number of visits within the selected date range

This should have the following columns
- full name (first + last), which is a link to /custs/XXX
- the number of visits
- date of last visit

**Comment by bradmac** [comment]
Note this should be on the uservisit index, not the logs index

**Comment by anhnt** [comment]
Done and deployed to AU server as `User Visits Table`

**Comment by bradmac** [comment]
Just made the user name a link
