### ISSUE TITLE
Profile transactions component doesn't show org points when site contains both user and org points atribution

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5129]
1. Create a website
2. Install reward store
3. Add additional point bucket with org points attribution
4. Add reward store and connect it to current site and alternative org point bucket
5. Create a user
6. Assign it to organisation (which should gain points)
7. Go to points page
8. Award him some points in both buckets
9. Go under this user to frontend and review profile page
10. There will be only first points bucket in transactions place.
http://vladtest41b.admin.kademi-ci.co/manageUsers/10165095/#summary-tab

**Comment by bradmac** [comment]
I'm seeing both points buckets:
![image](https://user-images.githubusercontent.com/826458/37488095-6d7b0980-28f8-11e8-87ef-540ba4cc4daa.png)

**Comment by bradmac** [comment]
can you please confirm what the problem is?

**Comment by Uafinder** [comment]
Nope...
looks ok now, not sure why It was... will keep an eye on it...
