### ISSUE TITLE
Improve KTheme for when used in leadman

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5132]
![image](https://user-images.githubusercontent.com/826458/37489376-452d9ba6-28fc-11e8-9891-c341f8c3aa86.png)

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/37517146-0c24bf1e-2943-11e8-931f-3ffd786f8de7.png)

**Comment by AlaaKhalaf94** [comment]
tested
