### ISSUE TITLE
Module pages can't be edited on fresh account

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5135]
1. Create a fresh account
2. Create a website
3. Install Learning app there
4. Create a module
5. Create a page, try to edit it
It will not open for edition and give a bunch of errors...
![clipboard - march 16 2018 10-56 am](https://user-images.githubusercontent.com/1945230/37512102-cd93116c-2909-11e8-8d9d-a1be1a92e659.png)
http://vladtest42.admin.kademi-ci.co/websites/vladtest42web/version1/programs/Program1/Course1/Module1/#files-tab

be aware, Anh already change theme by link provided so it become to work

**Comment by anhnt** [comment]
This issue can be reproduced by just create new account/website with default k-theme. It will not install jquery libs and content lib for that website so it causes the error

**Comment by anhnt** [comment]
looks ok atm after rebuilt

**Comment by AlaaKhalaf94** [comment]
I see error when I create new page on module
http://test-account05.admin.kademi-ci.co/websites/test-account05/version1/programs/prog01/Course01/Mod01/#files-tab

I test with fresh account , and just installed KLearning app

![untitled01](https://user-images.githubusercontent.com/26510030/37583039-470b32ae-2b58-11e8-92e9-6c0b7f6f44bf.png)

**Comment by bradmac** [comment]
hi @AlaaKhalaf94 I've just checked and that seemed ok

Can you please double check?

**Comment by AlaaKhalaf94** [comment]
can't reproduce the issue
