### ISSUE TITLE
Access Ksurvey page cause several errors in console

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5138]
![image](https://user-images.githubusercontent.com/1945230/37515958-4ba7094a-2915-11e8-8145-f77fda716d79.png)
1. Create a website
2. Install kSurvey there
3. Access ksurvey page
http://vladtest42.admin.kademi-ci.co/ksurvey/

looks like some dependencies are not installed

**Comment by bradmac** [comment]
This is a serious problem with how dependencies are managed.

Should be fixed now

**Comment by AlaaKhalaf94** [comment]
fixed
