### ISSUE TITLE
kEditor component should have a preivew (should looks better when non-configured)

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5139]
Similar to EDM editor

1. debits histogram component
![image](https://user-images.githubusercontent.com/1945230/37519341-68949dd6-2921-11e8-9300-d9414cb76cf6.png)
http://vladtest42.admin.kademi-ci.co/pages/vladtest42web/version1/

**Comment by anhnt** [comment]
done in rewardstore-lib 1.4.4

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/37553544-d777e894-29fc-11e8-9442-ccb2a350d004.png)

**Comment by anhnt** [comment]
@Uafinder please find more component which have same problem so i can apply this solution

**Comment by Uafinder** [comment]
ok, histogram is ok
question about this component
![image](https://user-images.githubusercontent.com/1945230/37591419-2ef206c2-2b74-11e8-848c-2767a2857f34.png)
It shows nothing on preview and targeted to some weird default Reward store
![image](https://user-images.githubusercontent.com/1945230/37591453-44b9ce72-2b74-11e8-9212-bc1c3a871c04.png)

**Comment by bradmac** [comment]
"Default" is for when its used on a page in a reward store, in that case you dont need to select the reward store it will just use whatever its inside.

**Comment by bradmac** [comment]
We should definitely have some preview content for it.

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/37643054-f321e1f6-2c51-11e8-83ed-34853661b73f.png)

**Comment by Uafinder** [comment]
ok, some more
- Blog articles component
- blog image should be a bit better
![image](https://user-images.githubusercontent.com/1945230/37657099-b2dc9ef0-2c52-11e8-95fe-d7357c9c041a.png)
http://vladtest44c.admin.kademi-ci.co/pages/vladtest44cweb/version1/

- feedback component bad
![image](https://user-images.githubusercontent.com/1945230/37657201-fbf8b4ac-2c52-11e8-8311-217cce36352a.png)

- all reporting component should have some default view
![image](https://user-images.githubusercontent.com/1945230/37657281-30ef1d68-2c53-11e8-9167-3491d0a607fc.png)

- display competition result
![image](https://user-images.githubusercontent.com/1945230/37657343-5d24ef66-2c53-11e8-89af-6e595ce83c33.png)

- display competition form
![image](https://user-images.githubusercontent.com/1945230/37657411-8b51302a-2c53-11e8-84b4-403e5a5a0dd2.png)

- status of current promotions missed image
![image](https://user-images.githubusercontent.com/1945230/37657443-b0f1060c-2c53-11e8-9203-17c283f82359.png)

- two claims components also need to have some default view
![image](https://user-images.githubusercontent.com/1945230/37658542-73e878c8-2c56-11e8-85c8-901a4af2b7ef.png)

- KPI target component
![image](https://user-images.githubusercontent.com/1945230/37658628-acfe73ec-2c56-11e8-85a8-51f66222e823.png)

- sales table and sales table compare default view
![image](https://user-images.githubusercontent.com/1945230/37658690-c90871d2-2c56-11e8-9ed8-3547c29950e0.png)

**Comment by bradmac** [comment]
@anhnt if any of these are going to take a while (say, more then 30mins) then let me know. As long as we can see the outline of a component thats the main thing. its nice to have some content but not essential for visual editing

**Comment by anhnt** [comment]
claimOverTime and salesDataCompare are rendering data from API so cant make preview

**Comment by bradmac** [comment]
> claimOverTime and salesDataCompare are rendering data from API so cant make preview

:+1:

**Comment by Uafinder** [comment]
also
- badges component
![image](https://user-images.githubusercontent.com/1945230/37832918-adeb77ec-2eb2-11e8-9c0a-7fb7e8950784.png)

**Comment by anhnt** [comment]
badges component
level component
_**Done**_

**Comment by Uafinder** [comment]
ok, looks fine
