### ISSUE TITLE
EDM: Images are not displaying on the fronend emails

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5143]
Editor view
![image](https://user-images.githubusercontent.com/1945230/37525537-d5868684-2935-11e8-94d5-02b8dfc27287.png)
http://vladtest42a.admin.kademi-ci.co/funnels/journey1/version1/email1/#message-tab

Frontend
![image](https://user-images.githubusercontent.com/1945230/37525575-f2d6e418-2935-11e8-8d50-cea8c78b9b55.png)

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/37550991-042f524c-29ca-11e8-9baf-f12e5216e493.png)

Content lib is not enabled so it could not find the photoEDM component

**Comment by anhnt** [comment]
I just created new account/website and content-lib is not enabled by default 
http://anhtest26.admin.kademi-ci.co/websites/w1/version1/#panel_apps-tab

@bradmac please have a look

**Comment by anhnt** [comment]
Rebuilt CI and re-synced then everything is working OK with fresh account

**Comment by AlaaKhalaf94** [comment]
tested
