### ISSUE TITLE
Invalid image dimensions shown in image editor

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5144]
Add an image to page editor, using the ckeditor/html component
Do not set any dimensions
right click on the image and open image editor modal

You see this:
![image](https://user-images.githubusercontent.com/826458/37571003-fc810552-2b5b-11e8-9b5e-65cef227b1e1.png)

**Comment by anhnt** [comment]
Fixed

**Comment by AlaaKhalaf94** [comment]
tested
