### ISSUE TITLE
Existing contact not found when adding a new lead

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5145]
![image](https://user-images.githubusercontent.com/826458/37572005-6bd08290-2b69-11e8-9ccf-18248a60c4b3.png)

But the profile exists:
![image](https://user-images.githubusercontent.com/826458/37572006-7bd9884e-2b69-11e8-8acc-3a24d53d1997.png)

note the profile is found when just searching for first name

**Comment by AlaaKhalaf94** [comment]
tested
