### ISSUE TITLE
register form component enhancement

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#5148]
Has redirect url settings after submitted form at component level
At the moment default redirecting to dashboard

```
 $(document).ready(function(){
        if($('.register-form-component').length > 0) {
            initRegister("/dashboard");
        }
    });

**Comment by anhnt** [comment]
done

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/37964675-8412c3f2-31ec-11e8-9c4a-03d6c5388448.png)
Also changed radio buttons to single checkbox on settings

**Comment by AlaaKhalaf94** [comment]
tested
