### ISSUE TITLE
NV lib is not defined on CI and prod (for example zoetis)

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5149]
1. Rebuild
2. Start CI
3. Note errors in console
as result
in fresh account it doesn't enabled as well
http://vladtest43.admin.kademi-ci.co/

**Comment by Uafinder** [comment]
On prod as well

**Comment by bradmac** [comment]
i think this is just until you install an app

**Comment by bradmac** [comment]
Problem was admin-lib 1.0.3 was being used for new accounts. Now that 1.0.4 is published it should use the correct lib

**Comment by Uafinder** [comment]
looks ok at the moment
