### ISSUE TITLE
Cropper js downloading error while accessing some pages in admin

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5150]
![image](https://user-images.githubusercontent.com/1945230/37588987-8e2418a4-2b6c-11e8-94da-2491a01d8bb4.png)
http://vladtest43.admin.kademi-ci.co/websites/vladtest43web/version1/programs/Program1/Course1/
Looks like it cause cropper malfunction
![image](https://user-images.githubusercontent.com/1945230/37589066-c3d41b2a-2b6c-11e8-8baf-ad80ae4aac64.png)

**Comment by bradmac** [comment]
This is the relative path problem seen elsewhere too. should be fixed now

**Comment by Uafinder** [comment]
Ok now
