### ISSUE TITLE
OrgSelector js dowloading error while accessing some pages in admin

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5151]
![image](https://user-images.githubusercontent.com/1945230/37594077-d887c822-2b7c-11e8-9e7f-98d1643bde3d.png)
http://vladtest43.admin.kademi-ci.co/reward-store/#rewardStores-tab

**Comment by bradmac** [comment]
Same root cause as this - https://github.com/Kademi/kademi-dev/issues/5150

**Comment by Uafinder** [comment]
Fresh account:
the same for me
![image](https://user-images.githubusercontent.com/1945230/37596198-16491862-2b84-11e8-81ae-27eb2b5d8aff.png)
http://vladtest43c.admin.kademi-ci.co/

**Comment by bradmac** [comment]
Closing, duplicate of https://github.com/Kademi/kademi-dev/issues/5153
