### ISSUE TITLE
Tagsinput js dowloading error while accessing some pages in admin

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5153]
![image](https://user-images.githubusercontent.com/1945230/37604827-8914b066-2b9a-11e8-96f2-e630c82cf595.png)
http://vladtest43c.admin.kademi-ci.co/

**Comment by bradmac** [comment]
This fix should resolve other CSS problems

**Comment by Uafinder** [comment]
this one looks ok
