### ISSUE TITLE
KCRM tasks page has no option to display all tasks regardless of who is assigned

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5155]
![image](https://user-images.githubusercontent.com/826458/37629852-090d8cc4-2c46-11e8-9781-13dd5faf2bac.png)

**Comment by gonzalon** [comment]
![image](https://user-images.githubusercontent.com/2773216/37631215-8bb861c4-2c4d-11e8-90c4-b7e3ff47074c.png)


leadman-lib  1.8.9

**Comment by Uafinder** [comment]
Yeah, looks ok
