### ISSUE TITLE
managedatarecord css dowloading error while accessing some pages in admin

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5157]
![image](https://user-images.githubusercontent.com/1945230/37642447-ca848db0-2c25-11e8-8a40-2aa0a16e42bb.png)
http://vladtest44.admin.kademi-ci.co/manageApps/#installed-tab

**Comment by bradmac** [comment]
I think this is fixed, but its possible it wasnt pushed

**Comment by bradmac** [comment]
Should be pushed now, please redeploy

**Comment by Uafinder** [comment]
Same after re-deploy
![image](https://user-images.githubusercontent.com/1945230/37644604-01b5f844-2c2d-11e8-8860-ad70f71d1050.png)
http://vladtest44b.admin.kademi-ci.co/manageApps/#installed-tab

**Comment by bradmac** [comment]
please deploy again

**Comment by Uafinder** [comment]
Yeah, it works
