### ISSUE TITLE
Allow pasting images into KCRM notes

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5158]
Use a technique like this to catch pasted data when adding a note
http://joelb.me/blog/2011/code-snippet-accessing-clipboard-images-with-javascript/

Upload the data to /assets as an image, get back a UUID which you can use to display the image at /assets/[UUID]

Then insert an image into the note

This is the create note UI
![image](https://user-images.githubusercontent.com/826458/37642669-ecbf20ae-2c82-11e8-85cc-238443fcf15d.png)

Gets displayed like this
![image](https://user-images.githubusercontent.com/826458/37642709-10bc8f1e-2c83-11e8-8727-3ffb9b976e14.png)

**Comment by anhnt** [comment]
Uploading screenshot by posting to /assets returns no result but status 200 ok. @bradmac do we need to set specific field name or something to make it work?

![image](https://user-images.githubusercontent.com/735555/37652857-7eca1a80-2c6f-11e8-96a4-7b2a1d2ca2b7.png)

**Comment by anhnt** [comment]
I pushed the code so you can test locally

**Comment by bradmac** [comment]
> Uploading screenshot by posting to /assets returns no result but status 200 ok. @bradmac do we need to set specific field name or something to make it work?

@anhnt just have a look at what other stuff does, eg uploading an image from the assets tab on the image modal, see mupload

**Comment by bradmac** [comment]
Eg:

![image](https://user-images.githubusercontent.com/826458/37688224-cfc3561a-2d03-11e8-944e-60e1dc40e781.png)


POST http://localhost:8080/asset-manager/

-----------------------------14943159631242869231199898207
Content-Disposition: form-data; name="NewFile"; filename="orewa.jpg"
Content-Type: image/jpeg

**Comment by bradmac** [comment]
But you can upload to /assets or /asset-manager, does the same thing but asset-manager is only available in admin. So probably use /assets

**Comment by bradmac** [comment]
You might need to change the inline-attachment.js plugin to use multipart form-data uploads. See jquery.forms.js for an example

**Comment by bradmac** [comment]
Fixed

![image](https://user-images.githubusercontent.com/826458/37690330-13f57a42-2d0f-11e8-8645-900868f58e29.png)

![image](https://user-images.githubusercontent.com/826458/37690335-22894caa-2d0f-11e8-9ef8-0d0974238d05.png)

**Comment by bradmac** [comment]
Requires leadman-lib 1.9.0
KLeadman 1.1.2

**Comment by anhnt** [comment]
👍

**Comment by anhnt** [comment]
it wont work when editing a note so need fix

**Comment by Uafinder** [comment]
Ok, there is a major stopper here
When you add an image to the note, it write a timeline record...
When note contains image note timeline record become ugly because of html tags there...
![image](https://user-images.githubusercontent.com/1945230/38737582-5c402398-3f38-11e8-8c64-49d5000b97e5.png)
http://vladtest48fleads-vladtest48f.kademi-ci.co/leads/15816550/
But the stopper is that when you add a note with image, all following activities which go to timeline will add to the note content...
E.g.
1. Create a lead
2. Add a note with image
3. Add task
4. Note that new timeline record is absent, and new content is added to previous note record

**Comment by AlaaKhalaf94** [comment]
In website it's fine
http://version1.testaccount06-testaccount06.kademi-ci.co/leads/15851675/

![untitled01](https://user-images.githubusercontent.com/26510030/38799403-2091cc3e-416d-11e8-8fe2-66acee13e5fd.png)

but the image doesn't appear in admin console
http://testaccount06.admin.kademi-ci.co/manageUsers/15851030/#summary-tab

![untitled02](https://user-images.githubusercontent.com/26510030/38799469-42fe0634-416d-11e8-8c24-d5c04798199f.png)

**Comment by bradmac** [comment]
Thats fine, its not needed in admin

If thats the only problem can be closed
