### ISSUE TITLE
keditor Orglocator component bad

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5161]
1. Enable app for an account and website
2. Create a page
3. Add container and drop an orglocator component there
4. Note error in console and orglocator doesn't appear
![image](https://user-images.githubusercontent.com/1945230/37668252-b678c9de-2c6c-11e8-95d4-8a5e08fb1aa9.png)
http://vladtest44c.admin.kademi-ci.co/pages/vladtest44cweb/version1/

**Comment by anhnt** [comment]
Fixed

**Comment by Uafinder** [comment]
looks fine for me

**Comment by AlaaKhalaf94** [comment]
passed
