### ISSUE TITLE
OrgSelector select country tool selects incorrect country 

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5167]
For example:
![image](https://user-images.githubusercontent.com/1945230/37710183-89e5a7ee-2d15-11e8-9ae3-234dd02a2296.png)
Select Ukraine
It will select UAE instead
![image](https://user-images.githubusercontent.com/1945230/37710308-ea5c693c-2d15-11e8-9327-e40fd01a079e.png)
Hard refresh is a requirement
http://version1.vladtest45web-vladtest45.kademi-ci.co/page1.html
http://vladtest45.admin.kademi-ci.co/

**Comment by anhnt** [comment]
Should be fixed with latest orgLocator-lib

**Comment by anhnt** [comment]
not fixed yet

**Comment by anhnt** [comment]
Finally fixed

**Comment by Uafinder** [comment]
It works!
