### ISSUE TITLE
OrgSelector init search checkbox does nothing

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5168]
When checkbox deselected it seems need to just load component and wait for user interaction
But it doesn't happen
![image](https://user-images.githubusercontent.com/1945230/37710435-52a66d1c-2d16-11e8-894e-a3706c7302fc.png)
![image](https://user-images.githubusercontent.com/1945230/37710477-7000ecc0-2d16-11e8-9638-e01785c50da4.png)
http://version1.vladtest45web-vladtest45.kademi-ci.co/page1.html

**Comment by anhnt** [comment]
We need to have settings of initial lat & lng. Should get from component on admin editor

**Comment by bradmac** [comment]
:+1:

**Comment by bradmac** [comment]
@anhnt I think we will want the user to be able to search for an address and select it in a drop down.

**Comment by anhnt** [comment]
Now when searching for a place on content editor, and if ticked to search when init, it will find that last selected place dropdown initially 

![image](https://user-images.githubusercontent.com/735555/37822814-2f2180d4-2eba-11e8-9053-953352fc8cc8.png)
![image](https://user-images.githubusercontent.com/735555/37822873-5e9dacc0-2eba-11e8-9593-8295d8fb2dee.png)

**Comment by anhnt** [comment]
finally fixed

**Comment by Uafinder** [comment]
Yeah, looks ok!
