### ISSUE TITLE
Contactus form success redirects to an error page

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5170]
![image](https://user-images.githubusercontent.com/1945230/37712295-1d4117b6-2d1c-11e8-9e0f-e200ab7acd4c.png)
http://vladtest45web-vladtest45.kademi-ci.co/contactus

**Comment by bradmac** [comment]
@anhnt looks like the redirect url isnt being defaulted correctly

**Comment by anhnt** [comment]
Fixed

**Comment by Uafinder** [comment]
Yeah, looks good now
