### ISSUE TITLE
OrgLocator data is visible for non-signed users

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5171]
![image](https://user-images.githubusercontent.com/1945230/37712360-52bc262e-2d1c-11e8-8a44-416ec7733124.png)
http://vladtest45web-vladtest45.kademi-ci.co/orgsLocator/

**Comment by bradmac** [comment]
Yes, that is expected.

Normally users are not logged in when using a store locator page.

**Comment by bradmac** [comment]
Eg
https://www.farmers.co.nz/farmersstores.html

**Comment by Uafinder** [comment]
got it
