### ISSUE TITLE
Custom fields arent available in uploader for sales data records

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5173]
I've defined several custom fields on a data series:
![image](https://user-images.githubusercontent.com/826458/37745990-dd707b6a-2ddc-11e8-9dea-6da42220cbad.png)

But when i go to upload data those fields arent available:
![image](https://user-images.githubusercontent.com/826458/37746040-1322ec84-2ddd-11e8-8df5-7c8e018dedf8.png)

**Comment by bradmac** [comment]
Fixed

**Comment by Uafinder** [comment]
Yeah, it works!
