### ISSUE TITLE
Certificate 404

### ISSUE THREAD

**Issue by cdennington** [Kademi/kademi-dev#518]
I have created a module page and added one of the certificates I created earlier.

After adding the certificate, a preview button appears, I am assuming this button should allow me to preview the certificate I have just added, but instead it takes to a 404 page.

Below is a screenshot of the 404 page.
![image001](https://cloud.githubusercontent.com/assets/1114197/8667611/2597ddd2-2a45-11e5-9a94-0156c75e5d45.jpeg)

**Comment by bradmac** [comment]
Fixed. It looks like the certificate just hadnt been saved on the module when selecting "preview". I've done that now and it opens the certificate.
Note that i also had to correct some malformed template tags in the certificate HTML.
