### ISSUE TITLE
Email sending test problem

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5180]
WHile sending test, error appears
![image](https://user-images.githubusercontent.com/1945230/37775647-26c1bc2a-2dec-11e8-9db3-a940ea2e8ec9.png)
http://vladtest45a.admin.kademi-ci.co/groupEmails/12134421/#messages-tab
![image](https://user-images.githubusercontent.com/1945230/37775658-2e26589a-2dec-11e8-8868-4f4583dbcb3c.png)
![image](https://user-images.githubusercontent.com/1945230/37775677-38fb28d6-2dec-11e8-9f8b-929bc0c9c12e.png)

**Comment by bradmac** [comment]
Just affects CI. @tuzzmaniandevil please update config

**Comment by tuzzmaniandevil** [comment]
Fixed

**Comment by Uafinder** [comment]
Passed!
