### ISSUE TITLE
Can't edit asset query list component keditor

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5181]
1. Create page
2. Add component there
3. Edit it a bit and save
4. Close editor
5. open page for edit again
6. Try to change some params
![image](https://user-images.githubusercontent.com/1945230/37780074-9b4cbf0e-2df6-11e8-80c2-4b9708d16e81.png)
http://vladtest45a.admin.kademi-ci.co/pages/vladtest45aweb/version1/

**Comment by anhnt** [comment]
https://github.com/Kademi/kademi-dev/issues/5184

**Comment by bradmac** [comment]
is this resolved now with the dynamic href fix?

**Comment by anhnt** [comment]
that js error has gone now

**Comment by Uafinder** [comment]
yup, its ok
