### ISSUE TITLE
Points leaderboard needs to properly handle orgs

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5183]
When checking to see if the current user is in the leaderboard, we can only check the profile if its an individual based system.

For organsiation based points systems we need to find the appropriate org (using QueryManager.selectedOrgs ?)

**Comment by anhnt** [comment]
Done

**Comment by anhnt** [comment]
If orgselector is available it will get selected org and calculate the points rank of it.

**Comment by Uafinder** [comment]
It works... also tested with disabled orgselector
