### ISSUE TITLE
OrgLocator console error when no orgTypes in account

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5185]
1. Create website
2. Install orglocator app there
3. Insure that no orgtypes are added
4. Create a page and edit it
5. Add Org component - note error in console
![image](https://user-images.githubusercontent.com/1945230/37817909-1837cd6c-2e81-11e8-81cb-d56bfbd42f41.png)
http://vladtest45b.admin.kademi-ci.co/pages/vladtest45bweb/version1/

**Comment by anhnt** [comment]
Fixed as well

**Comment by Uafinder** [comment]
Looks good
