### ISSUE TITLE
EDM point components doesn't work at all

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5188]
http://vladtest45b.admin.kademi-ci.co/groupEmails/12630214/#messages-tab
I have such email message
It contains both buckets (user and org-based) to test
But points is not visible on the preview and on the frontend.
![image](https://user-images.githubusercontent.com/1945230/37821802-4b8cea38-2e8d-11e8-8a0e-729fefceb76f.png)
![image](https://user-images.githubusercontent.com/1945230/37821824-5abb6a2a-2e8d-11e8-8cca-ef0417859c63.png)
I'm sending email to this user
http://vladtest45b.admin.kademi-ci.co/manageUsers/12632124/#summary-tab

**Comment by bradmac** [comment]
This is probably due to this - https://github.com/Kademi/kademi-dev/issues/5199

@Uafinder please check with the #5199 fix

**Comment by Uafinder** [comment]
Looks good
