### ISSUE TITLE
Missed module field in module learning node 

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5190]
![image](https://user-images.githubusercontent.com/1945230/37832698-ff3853d2-2eb1-11e8-9575-9c55b5eebbaf.png)
http://vladtest45c.admin.kademi-ci.co/funnels/first-journey/version1/#journeyBuilder-tab
It looks because incorrect field mapping... you've mapped actions list to module field.

**Comment by anhnt** [comment]
Fixed

![image](https://user-images.githubusercontent.com/735555/38656848-50dce9a6-3e47-11e8-9a76-e15e19b4b312.png)

**Comment by Uafinder** [comment]
looks good
