### ISSUE TITLE
Cannot upload image to survey to regular placeholder

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5191]
![image](https://user-images.githubusercontent.com/1945230/37833930-522ed4be-2eb5-11e8-8ad0-ffbdc71ce761.png)
http://vladtest45c.admin.kademi-ci.co/ksurvey/survey-08fe2b6b-f9ed-465c-a6c2-a68c0e5ad4cb/#questions-tab
1. Create survey
2. add question
3. click on image upload
4. upload image, note the error appears

**Comment by anhnt** [comment]
Fixed

**Comment by anhnt** [comment]
Its now using mountRepository to create ksurvey own repo to manage uploaded files

**Comment by Uafinder** [comment]
Yeah, it works
