### ISSUE TITLE
Rego forms to allow specifying additional group(s) to add the user to

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5193]

**Comment by Uafinder** [comment]
Not working for me.
create a page
select learners group as target
select participants group as additional
check opt-in groups
![image](https://user-images.githubusercontent.com/1945230/37905015-32641d76-3106-11e8-9e9e-e08ca0ef9070.png)
view rego page
complete rego form
check groups for new user
no signs of participants group for this user
http://vladtest46.admin.kademi-ci.co/groups/learners/

**Comment by bradmac** [comment]
FYI, here's an example signup page
![image](https://user-images.githubusercontent.com/826458/37929011-3a1fad42-319b-11e8-90cb-74dba6440289.png)

http://rhiperewards-rhipe.kademi-ci.co//theme/apps/signup/contenteditor?fileName=register.html

**Comment by bradmac** [comment]
@Uafinder that needs to be selected on the component
http://vladtest46web-vladtest46.kademi-ci.co//theme/apps/signup/contenteditor?fileName=register.html

![image](https://user-images.githubusercontent.com/826458/37929083-70056f0a-319b-11e8-991f-7b484d649d40.png)

Sorry, i should have put that on the issue

**Comment by Uafinder** [comment]
Yeah, i understand this but it  doesn't  work for me...
Even i change  registration open for additional group.
i've a custom rego page and a regular one... both doesn't work for adding additional group...
http://vladtest46.admin.kademi-ci.co/pages/vladtest46web/version1/?contenteditor=rego.html
http://vladtest46.admin.kademi-ci.co/websites/vladtest46web/version1?editTemplate=theme/apps/signup/register

**Comment by bradmac** [comment]
This is done and live now
