### ISSUE TITLE
Updating the theme made the menu editor hard to use

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#5194]
Buttons overlap the menu text items.

![image](https://user-images.githubusercontent.com/2201340/37871031-830184da-302f-11e8-95bd-0d3034756e27.png)

Cannot change the name of the My Learning page - it does not save.

![image](https://user-images.githubusercontent.com/2201340/37871067-6a8a4b16-3030-11e8-8d42-68b74abc9ad0.png)

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/38191286-532cbfe0-3692-11e8-8406-80bd9a65366c.png)

**Comment by Uafinder** [comment]
Looks fine
