### ISSUE TITLE
Enable selecting visibility for groups option

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#5197]
For containers, I'd like to be able to select if a container is either "Visible" or "Invisible" for the selected groups.. 

For backwards compatibility, when this is not selected, the default is visible for groups.

**Comment by mkhoudary** [comment]
Done..

![image](https://user-images.githubusercontent.com/3704174/37875265-dec35bce-303c-11e8-9090-1ca1ada3e759.png)

**Comment by Uafinder** [comment]
Yeah, looks fine
