### ISSUE TITLE
Button to resend failed emails

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5198]
Sometimes an email will fail to be delivered and we want to send it again

Please add a button to the manage email item page to reset email status so it will be resent

Eg
https://carters.admin.kademi.com.au/emails/110994518

See
- ManageEmailItemPage
- /theme/apps/email/manageEmailItem.html

**Comment by gonzalon** [comment]
![image](https://user-images.githubusercontent.com/2773216/37880248-c1ce3c00-30e1-11e8-9493-2aadd7f729b8.png)

**Comment by Uafinder** [comment]
Ok, the button is present, but i can't see that it tries to resend email.
![image](https://user-images.githubusercontent.com/1945230/37900717-b6093d82-30f7-11e8-8b12-916be88a91d3.png)
I push resend but nothing changed. there is no additional record for another sending.
http://vladtest46.admin.kademi-ci.co/emails/13426794#
