### ISSUE TITLE
Add an option in OrgLocator component to show only selected orgtypes

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#5201]
We need to have an option added to OrgLocator component to only show the selected orgtypes

**Comment by anhnt** [comment]
done

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/37892776-2f197d12-3103-11e8-886b-1d68a6fdab5c.png)

**Comment by AlaaKhalaf94** [comment]
passed
