### ISSUE TITLE
Allow filter org with no org type assigned in org locator app

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#5202]
Please apply to OrgsMapPage.java line 225

I added frontend support in orgLocator component

![image](https://user-images.githubusercontent.com/735555/37892704-e530e190-3102-11e8-8c3e-06933d26fe6f.png)

just filter like we do on manage orgs page ie http://localhost:8080/organisations/?term-orgTypes=cust-company,no-type&term-orgs=

**Comment by bradmac** [comment]
:+1:

**Comment by Uafinder** [comment]
https://github.com/Kademi/kademi-dev/issues/5220
