### ISSUE TITLE
when push resend button and email still fails it doesn't visible in email history by filter

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5203]
1. send email which will fail in result
2. check email history, by filter failed - it will be there
3. go to email page, push re-send button
4. go back to email history page
5. select filter by failed and there will not be this email
![image](https://user-images.githubusercontent.com/1945230/37901175-26e5d26c-30f9-11e8-9c93-edeabc070008.png)
![image](https://user-images.githubusercontent.com/1945230/37901190-2fa4285e-30f9-11e8-8d50-5a438ec92d4a.png)
http://vladtest46.admin.kademi-ci.co/emails/?q=&status=f&job=

**Comment by bradmac** [comment]
Yes, that is expected. If you resend the email its the same email, so if it gets delivered its no longer a failed email.

**Comment by Uafinder** [comment]
Yeah... but it's still failed and still doesn't appear in this filter...
look here first
http://vladtest46.admin.kademi-ci.co/emails/?q=&status=&job=
then look here
http://vladtest46.admin.kademi-ci.co/emails/?q=&status=f&job=
Note that email still not fire, so its failed

**Comment by bradmac** [comment]
I think the problem might be that the failed attempts are still there, and thats causing the system to consider the email as failed immediately.

So now I'm deleting the failed send attempts

**Comment by bradmac** [comment]
Actually, just saw this in the logs
```
20:56:23 INFO  io.milton.cloud.server.apps.email.EmailItemQueueStore  - Not adding emailitem because job is disabled. EmailItemId=13433604 job: emailqa03 (13432859) status=c
```

So that email isnt being sent because its from a job which is currently disabled

**Comment by bradmac** [comment]
OK, its not actually disabled, its just too old. The system marks as failed emails for jobs which are 2 days old or more.

@Uafinder please test with a recent email item, ie from a job less then 2 days old.

**Comment by Uafinder** [comment]
Same for me here
http://vladtest47.admin.kademi-ci.co/emails/?q=&status=&job=
To reproduce pls do following:
1. http://vladtest47.admin.kademi-ci.co/groupEmails/15550070/#sendInfo-tab
2. send email
3. note that some emails ok and one will be failed
4. ensure that it will appear on the email history http://vladtest47.admin.kademi-ci.co/emails/?q=&status=f&job=
5. go to email page, try to resend it
6. go back to email gistory and note that it will not there

**Comment by bradmac** [comment]
When i resend your email i see this in the logs
```
21:15:48 INFO  io.milton.cloud.server.apps.email.EmailItemQueueStore  - Not adding emailitem because job is disabled. EmailItemId=15549960 job: emailqa01-1 (15549838) status=c
``

Note that this log is from old code. Looks like CI has reverted to an old build

**Comment by bradmac** [comment]
Note that this has now been used in production so all good
