### ISSUE TITLE
Clear button in Orglocator component doesn't clear org types chosen from component setting

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#5204]
In hydroxypure : http://a-version.hydroxypure-waterco.kademi.com.au/orgsLocator

**Comment by anhnt** [comment]
I think this is expected. The client just wanted to allow user searching with those given types. So when they clearing the query, the selected types should be kept as initial loaded

@bradmac @mkhoudary what do you guys think?

**Comment by bradmac** [comment]
Yep, but in that case the X should be associated with the text input:
![image](https://user-images.githubusercontent.com/826458/37945609-7b370716-31dd-11e8-8dfa-a19710eb34b1.png)

Also, we need to remove the country select box due to client feedback, so lets do that as part of this issue

**Comment by anhnt** [comment]
And published the libs to AU

**Comment by AlaaKhalaf94** [comment]
- In component setting I select "LG,MD" Org Types to make filter about its by default when I visit the page
In home page : http://test-account09.admin.kademi-ci.co/pages/test-account09/version1/
![untitled01](https://user-images.githubusercontent.com/26510030/37957023-3323b6ca-31ad-11e8-9cc8-6ddfb699c18d.png)

but when I visit the page , I can't see the filter results until I do something on like "select other org type OR click on clear search button"
http://version1.test-account09_test-account09.kademi-ci.co/index.html

**Comment by Uafinder** [comment]
it looks because you select "search when init"... and start location doesn't have any store near...

**Comment by AlaaKhalaf94** [comment]
yes , that works well now
Thanks @Uafinder
