### ISSUE TITLE
Visual bug on shopping cart

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5206]
![image](https://user-images.githubusercontent.com/1945230/37916610-f50102c2-3124-11e8-92e6-2e7b59b10c26.png)
http://vladtest46web-vladtest46.kademi-ci.co/checkout/
http://vladtest46.admin.kademi-ci.co/websites/vladtest46web/version1/#panel_details-tab

**Comment by anhnt** [comment]
Done

**Comment by Uafinder** [comment]
looks fine
