### ISSUE TITLE
Full width videos

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5208]
The kademi video component seems to behave differently to youtube for video sizing. Eg;

Eg see here the Kademi video is quite narrow but the youtube video is full width:
![image](https://user-images.githubusercontent.com/826458/37938313-ab8bd4ce-31b9-11e8-8dc2-7ea449662408.png)

I think full width is correct, so the kademi vid component should be updated to behave the same as the youtube component

**Comment by anhnt** [comment]
Done

![image](https://user-images.githubusercontent.com/735555/38026216-7ac1b08c-32b5-11e8-9d9b-960f533b187b.png)

**Comment by Uafinder** [comment]
Works like a charm!
