### ISSUE TITLE
View in browser & unsub components needs more parameters

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#5212]
I need to be able to:
- change its font, size, color
- align left, right and center

![image](https://user-images.githubusercontent.com/2201340/37940925-03b7a7de-31b7-11e8-87a2-31e7b6abbdb4.png)

![image](https://user-images.githubusercontent.com/2201340/37940970-3d5d2252-31b7-11e8-9416-1741c11f230e.png)

Ideally I want to be able to drop the link into a block of text I write, maybe Kcode would support this?

Often unsubs needs to sit in the footer and in a block of copy like below.
![image](https://user-images.githubusercontent.com/2201340/37940997-6cce8e72-31b7-11e8-81ed-f3b670531ce2.png)

**Comment by bradmac** [comment]
hey @paddyow the unsub link is just to the profile page. If you've enabled adding login tokens to all links, then you can just make a link to /profile/ in the copy

Note that we now support the base href header for EDM's so you dont need to worry about the full address (ie domain name)

**Comment by bradmac** [comment]
Same for the view in browser link, use the link /viewEmail
