### ISSUE TITLE
OrgsFinder shows all orgtypes of users to the left

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#5218]
When users are displayed in the left menu in orgsfinder, the orgtypes tags show regardless to the tags selected for the component.

We want to "only" show the types that is available for the component next to the users in the left menu

**Comment by anhnt** [comment]
Done 
![image](https://user-images.githubusercontent.com/735555/37958530-fda6ce1e-31da-11e8-9226-9e2a499fba85.png)

**Comment by AlaaKhalaf94** [comment]
passed
