### ISSUE TITLE
orgslocator doesn't show orgs without type

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5220]
http://version1.vladtest46bweb-vladtest46b.kademi-ci.co/orgslocator.html
this org is missed
http://vladtest46b.admin.kademi-ci.co/organisations/13725990/edit/
![image](https://user-images.githubusercontent.com/1945230/37956591-710f1252-31b4-11e8-96c6-55e513ae865e.png)
looks like NO TYPE type is not working at all

**Comment by anhnt** [comment]
Please rebuild and resync to test

**Comment by AlaaKhalaf94** [comment]
Hi @anhnt , I can't see your update : http://version1.testaccount08-testaccount08.kademi-ci.co/orgsLocator/

although there is org without type : http://testaccount08.admin.kademi-ci.co/organisations/15854481/edit/

**Comment by anhnt** [comment]
@bradmac can you please help us delete target/classes folder on CI server to get fresh build? Its working fine locally for me

**Comment by anhnt** [comment]
Fixed

**Comment by AlaaKhalaf94** [comment]
passed
