### ISSUE TITLE
Ability to run multiple points allocation rules per data series

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5224]

**Comment by bradmac** [comment]
See example here:
http://rhipe.admin.kademi-ci.co/sales/partner-sales/#points-tab

![image](https://user-images.githubusercontent.com/826458/38170264-643dd5bc-35d4-11e8-8cc6-ec75c7cc2c74.png)

**Comment by bradmac** [comment]
@Uafinder please test the "Allocate rewards" button. This should create rewards for all configuration points allocations, which will apply to all sales data records which match each allocation.

Typically there will be a points allocation for each type of product. In this example there is one for Microsoft365 and another for Azure.

![image](https://user-images.githubusercontent.com/826458/38170267-acb8324c-35d4-11e8-9555-6726cadf7cb5.png)

![image](https://user-images.githubusercontent.com/826458/38170270-b76c291e-35d4-11e8-83ba-59c58f78d1d2.png)

**Comment by bradmac** [comment]
Note that a sales data record should only be processed once, although it can match multiple points allocation rules. But once processed it shouldnt be processed again.

**Comment by Uafinder** [comment]
It works like a charm!
