### ISSUE TITLE
Add spinner to submit button

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5234]
Users need immediate feedback that they've clicked a button.

Please update jquery.forms so that when a form is submitted the submit button text is replaced with an animated spinner. This must go back to the original text on completion of the ajax request.

**Comment by anhnt** [comment]
Done

![image](https://user-images.githubusercontent.com/735555/38007729-fed8afc4-3274-11e8-8121-ecd4e50629ee.png)

**Comment by Uafinder** [comment]
looks good
