### ISSUE TITLE
keditor module page - image doesn't fall into container dimensions

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5236]
1. Create a module and a page there
2. Add 50/50 container... check box layout for it.
3. Add photo component there
4. Upload image which is bigger than expected placeholder.
5. Note that image doesn't resized to fall into container... 
![image](https://user-images.githubusercontent.com/1945230/38020812-dc2c9aee-3283-11e8-99a3-5289c16d7b08.png)
http://vladtest46c.admin.kademi-ci.co/websites/vladtest46cweb/version1/programs/program1/course1/module1/?contenteditor=ppage1.html

**Comment by bradmac** [comment]
@anhnt please ensure images are responsive by default. Eg have this initially ticked:
![image](https://user-images.githubusercontent.com/826458/38048314-7db188a0-3321-11e8-9a2d-0cd2e0c49e51.png)

**Comment by anhnt** [comment]
Done

**Comment by Uafinder** [comment]
ok, it looks ok for standard photo component
please apply this fix for next ones prestaged content 
![image](https://user-images.githubusercontent.com/1945230/38085157-3c6e4982-3358-11e8-9342-d4999b87a031.png)
http://vladtest46g.admin.kademi-ci.co/websites/vladtest46gweb/version1/programs/program1/course1/module1/#files-tab

**Comment by bradmac** [comment]
:+1:

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/38123367-dfb5d194-3404-11e8-9afe-348e2dc60dd7.png)
Done

**Comment by Uafinder** [comment]
Yeah, it looks good
