### ISSUE TITLE
Signup index doesn't update after user import completed

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5238]
http://vladtest46c.admin.kademi-ci.co/signupSearch
here you can see 13 users and 19 memberships
http://vladtest46c.admin.kademi-ci.co/manageUsers/
here you can see much more

After doing re-index numbers will be good

**Comment by bradmac** [comment]
I'm seeing 23 users on manage users page, and 22 profiles on the signups page. The difference of 1 is because my admin account is appearing on the manage users page.

So i cant see a problem.

![image](https://user-images.githubusercontent.com/826458/38170237-da97f9e6-35d3-11e8-804f-c7569993889d.png)

![image](https://user-images.githubusercontent.com/826458/38170239-e74dec4a-35d3-11e8-9d69-563f2b1ef1e8.png)

**Comment by bradmac** [comment]
Note that this page is date sensitive, ie only signups in the selected date range are shown

**Comment by bradmac** [comment]
Also note that the signups page doesnt use ES, so reindexing will have no effect on the date it shows

**Comment by Uafinder** [comment]
Ok, my mistake.
The problem observed when you work with keditor component - registrations over time
![image](https://user-images.githubusercontent.com/1945230/38237538-2aaaec92-3730-11e8-8a7c-dca1ddd0e09b.png)
http://version1.vladtest47dweb-vladtest47d.kademi-ci.co/page2.html

http://vladtest47d.admin.kademi-ci.co/pages/vladtest47dweb/version1/

So, you could watch a problem when accessing users page first and see there more than 100 users
And then you could open page 2 where component located and check that there is only one user.

**Comment by Uafinder** [comment]
Note that I done some re-index on the account and now it shows correct value.
So, to reproduce it pls upload some users and note the count difference between component value and actual value.

**Comment by bradmac** [comment]
Hi Vlad, when i login i dont see what you see:
http://version1.vladtest47dweb-vladtest47d.kademi-ci.co/page2.html

![image](https://user-images.githubusercontent.com/826458/38526817-e0d0df6a-3cab-11e8-9cdd-d3c13531a4a0.png)

**Comment by bradmac** [comment]
Can you please provide steps to reproduce the problem including
- the URL where the problem occurs
- the user you're logging in with when you see the problem

**Comment by Uafinder** [comment]
Probably something very specific, I can't reproduce it at the moment... however some libs were updated already, so it could be fixed somehow...
