### ISSUE TITLE
Keditor WYSIWYG editor not showing when you edit text in a container, or saving content changes.

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#5244]
http://v4.comeflywithus-rhipe.kademi.com.au/contenteditor?fileName=how-to-earn.html&miltonUserUrl=/users/patrick&miltonUserUrlHash=d8cb681e-7dcc-4815-a970-9b68f0bc76ff:eCXasIgcvsbj0wiN17krq4QsAks

http://rhipe.admin.kademi.com.au/pages/comeflywithus/v4/

![image](https://user-images.githubusercontent.com/2201340/38059838-d447106a-3333-11e8-96ca-c9744504ee65.png)

**Comment by bradmac** [comment]
ckeditor-lib hadnt synced properly
