### ISSUE TITLE
jw player lib

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5246]
Please copy jw player assets into a new lib, and update dependencies that need it

**Comment by anhnt** [comment]
Done

**Comment by anhnt** [comment]
@Uafinder please test with fresh account

- video component 
- video addon from ckeditor

**Comment by Uafinder** [comment]
can't test on QA, waiting deploy to prod

**Comment by Uafinder** [comment]
both on qa and us doesn't see preview when add component to page
also when upload video - no preview
playback in editor also doesn't work
no matter of flash disable or enable
same on browserstack
http://vladtest46e.admin.kademi-ci.co/manageUsers/
http://anhtest1.admin.kademi.us/pages/w1/version1/

**Comment by bradmac** [comment]
hey vlad, please ignore QA for this issue

**Comment by bradmac** [comment]
note that there is a delay on generating the video. it wont be immediately available

**Comment by bradmac** [comment]
Works fine for me here in FF

http://version1.w1-anhtest1.kademi.us/page1.html

**Comment by Uafinder** [comment]
![clipboard - 29 2018 12-38](https://user-images.githubusercontent.com/1945230/38083308-df42060a-3351-11e8-87d2-4b2deb964dc6.png)

**Comment by bradmac** [comment]
@anhnt looks like a JS problem when the video is added. I see this in browse console:
```
There was a problem setting up the player:  
Object { message: "g.filterPlaylist is not a function", version: "6.12.4956", type: "jwplayerError" }
```

**Comment by Uafinder** [comment]
also probably the related problem...
when uploading video, it doesn't appears on the right preview side at all
![image](https://user-images.githubusercontent.com/1945230/38083539-8b2c903e-3352-11e8-93ac-6e6d18997ba0.png)

**Comment by anhnt** [comment]
Finally fixed

**Comment by anhnt** [comment]
Uploaded a fix to http://anhtest2.admin.kademi.com.au/

When everything is ok i will deploy new version to AU and US

**Comment by Uafinder** [comment]
Checked on QA, looks fine for me
