### ISSUE TITLE
keditor audio component bad

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5249]
![image](https://user-images.githubusercontent.com/1945230/38085257-81457878-3358-11e8-8707-b7dc23a67497.png)
http://vladtest46g.admin.kademi-ci.co/websites/vladtest46gweb/version1/programs/program1/course1/module1/#files-tab

**Comment by anhnt** [comment]
Fixed as in https://github.com/Kademi/kademi-dev/issues/5261

**Comment by Uafinder** [comment]
it works
