### ISSUE TITLE
Layout of edit buttons of menu items in Keditor are damage

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#5251]
http://testaccount01.admin.kademi-ci.co/pages/testaccount01/version1/

![untitled01](https://user-images.githubusercontent.com/26510030/38090103-ccf7800a-3361-11e8-84d6-81108c2c6642.png)

**Comment by bradmac** [comment]
i think we have an issue for this already, but cant find it right now so will leave it for now

**Comment by AlaaKhalaf94** [comment]
https://github.com/Kademi/kademi-dev/issues/5194
