### ISSUE TITLE
keditor: Incorrect behaviour when adding several videos in 50/50 container

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5261]
1. Fresh account
2. Create a page
3. Add 50/50 container
4. Add video component there (to the left side)
5. Upload some video, click ok, verify that video uploaded
6. Add video component to the right side of the component
7. Note that video falls into left side instead of right side
http://vladtest46l.admin.kademi-ci.co/pages/vladtest46lweb/version1/
![image](https://user-images.githubusercontent.com/1945230/38137050-0f3504a0-342b-11e8-9cc2-6beb81a3a3db.png)
![image](https://user-images.githubusercontent.com/1945230/38137057-1c0af7fc-342b-11e8-87d8-dcb7f77624f0.png)
![image](https://user-images.githubusercontent.com/1945230/38137064-23300bb2-342b-11e8-87d2-e2d0786613a4.png)

**Comment by anhnt** [comment]
Fixed

**Comment by anhnt** [comment]
please restart QA and resync to test

**Comment by Uafinder** [comment]
it works
