### ISSUE TITLE
Media element component should have margin options

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#5267]
Need to apply margins or it sits flush with every other component around it.

Would also be good to apply padding in between the text and image sections.

![image](https://user-images.githubusercontent.com/2201340/38158508-7ff6242e-34e1-11e8-822c-613eb6dc4434.png)

**Comment by trungjc** [comment]
![screenshot_5](https://user-images.githubusercontent.com/704946/51982592-0278ac00-24c9-11e9-9e62-4a45265fc9d7.png)


Margin and padding options added to media component in keditor-lib 1.3.6

**Comment by Uafinder** [comment]
Looks good
