### ISSUE TITLE
leadTasksTable component saves and refreshes immediately on selecting a date

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5271]
Eg from this page:
http://kcrm.kademi.us/tasks/?sort=dueDate-asc&assignedTo=brad&q=

Click a task to open its modal. Select a new date. The change is saved immediately and the page refreshes.

Its good to save immediately, but the modal shouldnt close

**Comment by anhnt** [comment]
Done

**Comment by Uafinder** [comment]
it works
