### ISSUE TITLE
Update task modal to seperate completion from editing

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5272]
Currently the task modal in KCRM can be opened either from the pencil (to edit) or from the green tick to mark as complete.

Here is the current screen after clicking the pencil:
![image](https://user-images.githubusercontent.com/826458/38221191-5ad86e42-3732-11e8-964b-5c2559270449.png)

Please update so that when the modal is opened for editing only the parts above the red line are shown.

Similarly, when the task is opened for completion only show elements below the red line

Note that if a task is configured with task outcomes the user must select a task outcome and that workflow must remain as it is.

**Comment by anhnt** [comment]
Done

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/38289006-3747c0aa-37fe-11e8-9bb0-edcd0c432897.png)

**Comment by anhnt** [comment]
>When pencil clicked - no assignment selector

I think we wont show that when edit task?

**Comment by bradmac** [comment]
@anhnt have a look at my wavy red line, assignment is definitely inside :)

**Comment by anhnt** [comment]
Fixed

**Comment by Uafinder** [comment]
ok

**Comment by bradmac** [comment]
This is incorrect. We need to remove task completion/cancel buttons:

Please see the sketch at the top of this issue which shows we need to include task assignment in the modal, but not task completion buttons

![image](https://user-images.githubusercontent.com/826458/38474549-3d35367e-3bf4-11e8-8266-5c74bd8621c0.png)

**Comment by bradmac** [comment]
@anhnt please move the completed/cancel buttons into the completion modal. The editing modal should only allow changing assigned to, not completing/cancelling

**Comment by anhnt** [comment]
Just removed complete/cancel button on editing task. We already have buttons for complete/cancel task in list tasks

![image](https://user-images.githubusercontent.com/735555/38654234-80dfda1e-3e38-11e8-9493-6c0a6fff7350.png)
![image](https://user-images.githubusercontent.com/735555/38654243-89c18ea2-3e38-11e8-80af-ff16f7742023.png)

**Comment by Uafinder** [comment]
Now looks good
