### ISSUE TITLE
UX update to task completion buttons

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5273]
Currently we show both cancel and complete buttons with equal size and prominence. I think this is confusing and distracts users from what they will normally want which is the green tick to complete the task:
![image](https://user-images.githubusercontent.com/826458/38221283-cdd5cb24-3732-11e8-9aa5-706b7610bfca.png)

Please update this to use a button dropdown, where the primary button is the green completion tick, and the dropdown button is Cancel

This way the cancel button is initially hidden, but is available when needed

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/38288995-27568e10-37fe-11e8-80ac-17cb18f9f3aa.png)

**Comment by Uafinder** [comment]
Looks good!
