### ISSUE TITLE
Timezone issue displaying KPIs

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#5275]
See here http://blackberry-demo.admin.kademi.us/sales/rebate-incentive/kpis/percentage-growth/?period=21461519#history-tab

![image](https://user-images.githubusercontent.com/2201340/38230074-7c4a6c70-374f-11e8-8b8f-f906fed63c1a.png)

The results screen shows slightly different sales data offset by -1 days
![image](https://user-images.githubusercontent.com/2201340/38230099-97b86b10-374f-11e8-8792-cfc0e474e293.png)

The actual sales data is all in 2018
http://blackberry-demo.admin.kademi.us/sales/rebate-incentive/#history-tab

Logging in as http://blackberry-demo.admin.kademi.us/manageUsers/21359265/#kpiAppTab-tab

The date ranges are offset by 1x day and no data appears in the KPI component.

**Comment by paddyow** [comment]
@anhnt can you look at this today please.

Can you look at this please http://blackberry-demo.admin.kademi.us/manageUsers/21359265/#kpiAppTab-tab

![image](https://user-images.githubusercontent.com/2201340/38232789-a836dbe6-375b-11e8-98d2-ffbfd6156f35.png)

And login as that profile.  When I choose those periods, I cannot see any progress on the KPI panel.

![image](https://user-images.githubusercontent.com/2201340/38232796-b28d7398-375b-11e8-92f7-b6e5dcea5a54.png)

**Comment by anhnt** [comment]
Just process kpi again and see that period is now from 1/1/18

**Comment by bradmac** [comment]
The problem is still there:
![image](https://user-images.githubusercontent.com/826458/38239574-3de128de-3781-11e8-9944-9ac6c4879c4b.png)

![image](https://user-images.githubusercontent.com/826458/38239616-5936ddae-3781-11e8-8cde-d3c9c5023cf9.png)

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/38239704-92e86338-3781-11e8-888f-4d449b6dfbd5.png)

**Comment by bradmac** [comment]
- had to re-save the start date (since timezone was changed after saving)
- then re-process KPIs
- that fixed the period dates
- more to go..

**Comment by bradmac** [comment]
- kpiPeriodPicker wasnt applying org timezone

**Comment by bradmac** [comment]
Timezone issue is sorted
