### ISSUE TITLE
KPI results not displaying

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5276]
@anhnt can you look at this today please.

Can you look at this please http://blackberry-demo.admin.kademi.us/manageUsers/21359265/#kpiAppTab-tab

![image](https://user-images.githubusercontent.com/2201340/38232789-a836dbe6-375b-11e8-98d2-ffbfd6156f35.png)

And login as that profile.  When I choose those periods, I cannot see any progress on the KPI panel.

![image](https://user-images.githubusercontent.com/2201340/38232796-b28d7398-375b-11e8-92f7-b6e5dcea5a54.png)

Can you check the component is functioning correctly.

**Comment by anhnt** [comment]
Just a note:

**set the timezone BEFORE setting up data!**

**When KPI is percentage growth, level value should be in percentage as well**

**When KPI is percentage growth, assessedResult.assessedAmount is percentage value**

**Comment by Uafinder** [comment]
well... It looks that way... not sure if it's correct
![image](https://user-images.githubusercontent.com/1945230/38307455-804d11a6-381c-11e8-95f5-94549ae0a6cf.png)
http://vladtest47gsales-vladtest47g.kademi-ci.co/dashboard
This user
http://vladtest47g.admin.kademi-ci.co/manageUsers/15650937/#summary-tab

**Comment by bradmac** [comment]
@anhnt can you please review and assist Vlad?

**Comment by anhnt** [comment]
Fixed an issue that set value for circle but the value is not a number ie formatted as currency 1,234.56

![image](https://user-images.githubusercontent.com/735555/38669066-97c86e1c-3e6f-11e8-8179-d1e77098b009.png)

**Comment by Uafinder** [comment]
looks fine now
