### ISSUE TITLE
Lead note content to automatically render a link for url

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#5279]
![image](https://user-images.githubusercontent.com/735555/38241132-ab03c0d2-375b-11e8-9d73-5aa20aa8ad0e.png)

**Comment by bradmac** [comment]
:+1:

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/38291112-740152e0-3808-11e8-9491-45d0c1094cd3.png)

**Comment by Uafinder** [comment]
https://github.com
http://github.com
ftp://github.com
www.github.com

it's a test

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/38302837-c013cd44-380c-11e8-9b18-63d240075426.png)

**Comment by bradmac** [comment]
i think thats fine for now. I know sites which convert to links without http/https often convert text that shouldnt be

**Comment by Uafinder** [comment]
no probs
