### ISSUE TITLE
Do not allow hyphens in an account ID (need to validate) 

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#5282]
If so this breaks things i.e. opening a webpage in Keditor.

something-something would break
somethingseomthing would be ok

![image](https://user-images.githubusercontent.com/2201340/38287335-85fe953e-380d-11e8-963f-626969eebcc5.png)

**Comment by bradmac** [comment]
> If so this breaks things i.e. opening a webpage in Keditor.

It doesnt break keditor, although rocketchat doesnt open links correctly with underscores so it can look like it.

Sending emails does get broken

**Comment by anhnt** [comment]
Fixed

**Comment by Uafinder** [comment]
works ok
