### ISSUE TITLE
Allow points allocation sources to be linked to a promotion which controls start/end date

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5286]
See "Ad-hoc Promotions"
https://docs.google.com/document/d/14KL3I-2l1yRNYaMDiF2xOo3Fa-GY6wmmBP8goLRMX_0/edit

**Comment by bradmac** [comment]
Implemented on polnts allocation rules:
![image](https://user-images.githubusercontent.com/826458/38844832-3d863d7a-4249-11e8-9396-c99bb443102e.png)

**Comment by bradmac** [comment]
There is now a summary of points items referencing the promotion on the promotion details page:
![image](https://user-images.githubusercontent.com/826458/38846055-71f403c6-424e-11e8-853b-ee08d4581d1e.png)

**Comment by Uafinder** [comment]
it works like a charm!
