### ISSUE TITLE
Text component cannot be edited

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#5290]
http://schneiderelectric.admin.kademi.com.au/pages/digitize/version1/

Edit file **Registration test**

**Do not edit any other page!**

**Comment by anhnt** [comment]
this class prevent editor toolbar showing `keditor-highlighted-dropzone`

**Comment by anhnt** [comment]
Fixed please rebuild and try reproducing it if possible

**Comment by Uafinder** [comment]
Well, looks fine in this definite case.
Pls check this one
https://github.com/Kademi/kademi-dev/issues/5321
