### ISSUE TITLE
Schneider Electric: IE8 rego fields text is not visible + validation on mandatory fields doesn't work + thank you page doesn't appear after success rego

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5292]
IE8 rego fields text is not visible
![image](https://user-images.githubusercontent.com/1945230/38409230-4a6ffd28-3989-11e8-9930-d22b4b8800a5.png)
http://digitiserewards.com.au/

validation on mandatory fields doesn't work
![image](https://user-images.githubusercontent.com/1945230/38409291-876a37e8-3989-11e8-87b3-1cd40d015c5d.png)

thank you page doesn't appear after success rego
![image](https://user-images.githubusercontent.com/1945230/38409358-d226592e-3989-11e8-9c14-54df043c0f67.png)

**Comment by bradmac** [comment]
IE8 support is not required for this or other projects
