### ISSUE TITLE
KCRM outcome options

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#5296]
If you fail to choose an option and instead hit the Complete Task button, the journey breaks and does not step forward and create the next task.

Validate an option has been chosen before the Complete Task button can be pressed.

![image](https://user-images.githubusercontent.com/2201340/38450369-f6943796-3a5f-11e8-8075-5a13860d02c7.png)

**Comment by anhnt** [comment]
And deployed leadman-lib to kcrm

**Comment by Uafinder** [comment]
Need a short instruction with creating Outcome nodes...
I tried to add task, but there is a disabled outcome node...
http://vladtest48f.admin.kademi-ci.co/funnels/journey1/version1/#journeyBuilder-tab

**Comment by bradmac** [comment]
Just add the nodes you want to go to next, and then drag a link from the red output to each one:

![image](https://user-images.githubusercontent.com/826458/38783211-54268086-4153-11e8-890c-35b7e02ceb8f.png)

Once you've done that, click the settings for the task node and edit the properties of each outcome:

![image](https://user-images.githubusercontent.com/826458/38783236-941ed51c-4153-11e8-9a16-6bd3f2ac7a98.png)

**Comment by Uafinder** [comment]
Yup, it works
Thanks for help
