### ISSUE TITLE
error loading fonts on https

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5298]
Eg

https://waterco.admin.kademi.com.au/

![screenshot from 2018-04-09 09-46-24](https://user-images.githubusercontent.com/826458/38472905-119887b4-3bdb-11e8-92f8-eea6255777ad.png)

**Comment by anhnt** [comment]
Looks good to me. however i see that error is caused by zopim

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/38594870-ba2f5694-3d72-11e8-8f8c-9d63a739c337.png)

**Comment by bradmac** [comment]
yeah, not seeing that anymore in FF
