### ISSUE TITLE
Daily and monthly active users report

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5299]
Please create 2 new reports based on access log
- daily active users
- monthly active users

These should be the same except they will aggregate by day or month respectively

The reports should have 3 main output elements
- date histogram showing the number of users who visited in each date bucket
- a total number of unique users who visited during the time frame
- a table listing users ordered by highest number of page views during the selected date range

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/38494150-fb2861fe-3c1e-11e8-9429-a6d442ff3ad2.png)

**Comment by anhnt** [comment]
@bradmac should we have csv export function?

**Comment by bradmac** [comment]
yes please

**Comment by anhnt** [comment]
@bradmac please have a look

http://localhost:8080/reporting/userVisitReport.csv ->working
http://localhost:8080/reporting/userVisitReport.csv?param1=xx&param2=yy -> not working

**Comment by bradmac** [comment]
Both URLs work fine for me. Tested with FF and Chrome

**Comment by anhnt** [comment]
http://localhost:8080/reporting/reporting/userVisitReport.csv?aggInterval=day&aggWebsite= wrong url generated by js. will fix soon

**Comment by bradmac** [comment]
Looks good

![image](https://user-images.githubusercontent.com/826458/38642491-59567868-3e2e-11e8-8b65-88f229051542.png)

**Comment by anhnt** [comment]
Just added js patch for downloading csv

**Comment by Uafinder** [comment]
Looks good
Pls be aware of
https://github.com/Kademi/kademi-dev/issues/5326
