### ISSUE TITLE
Gilpin site has no d3 libs enabled - error in console

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5300]
![image](https://user-images.githubusercontent.com/1945230/38497051-639cecd0-3c08-11e8-8ee1-c106eeb7d487.png)
http://gilpin.admin.kademi.com.au/pages/gilpinperformance/versionnew2/
just FYI

**Comment by bradmac** [comment]
Fixed. FYI, in future you can resolve this my clicking "Update all" on the account level apps page
