### ISSUE TITLE
zoetis error while download rep-report

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5301]
![image](https://user-images.githubusercontent.com/1945230/38497639-6e3f181e-3c0a-11e8-8b48-3d620f018cc4.png)
https://zoetis.admin.kademi.com.au/rep-reports/?startDate=09/03/2018&finishDate=09/04/2018
https://zoetis.admin.kademi.com.au/rep-reports/?startDate=09/04/2015&finishDate=09/04/2018
After page downloads successfully click download CSV button - error appears
![image](https://user-images.githubusercontent.com/1945230/38497880-3779fbae-3c0b-11e8-88a1-0488349e1185.png)

**Comment by bradmac** [comment]
Note that rep-report is a zoetis custom report, so moving to the zoetis repo
