### ISSUE TITLE
Points to support decimal places

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5303]

**Comment by bradmac** [comment]
@Uafinder please check everything related to points
- ensure no regression errors
- ensure points can use decimals

**Comment by Uafinder** [comment]
1. final points in reward store doesn't save
![image](https://user-images.githubusercontent.com/1945230/38611787-52c3fd00-3d8d-11e8-85d5-0373449f69cf.png)
-edit some product
-add some points with decimals
-save
-open it for edition again... it will be empty
http://vladtest48b.admin.kademi-ci.co/reward-store/vladtest48baucstore-store/?q=&categoryName=

2. award and debit points doesn't takes decimal values
![image](https://user-images.githubusercontent.com/1945230/38612154-793831e4-3d8e-11e8-82f6-d24d2deadbb9.png)
e.g., i awarded 100.25 and it shows that 100.0 points was awarded
same for debit - 2.0 for 2.56

3. Frontend doesn't show decimal points at all
E.g. product cost is 980.15 and it shows 980
![image](https://user-images.githubusercontent.com/1945230/38612276-e3ca3c8c-3d8e-11e8-806d-305d6d3a1248.png)
![image](https://user-images.githubusercontent.com/1945230/38612296-ea972822-3d8e-11e8-8268-ea5787c30d51.png)
![image](https://user-images.githubusercontent.com/1945230/38612456-696f2dca-3d8f-11e8-89fa-7b81b108ada7.png)
http://version1.vladtest48baucstore-vladtest48b.kademi-ci.co/vladtest48baucstore-store/
![image](https://user-images.githubusercontent.com/1945230/38612795-72063680-3d90-11e8-94ec-fb06c46bad06.png)

4. Shopping cart doesn't display decimals
![image](https://user-images.githubusercontent.com/1945230/38612939-de34ad50-3d90-11e8-9eca-fc598c945ce2.png)
However it could be a following from not using decimals while working with store
http://vladtest48b.admin.kademi-ci.co/shopping-carts/

5. Auctions doesn't allow to place a decimal value
![image](https://user-images.githubusercontent.com/1945230/38613051-47799eb0-3d91-11e8-96d6-933b9a73125d.png)
http://version1.vladtest48baucstore-vladtest48b.kademi-ci.co/auctions/vladtest48baucstore-auction/

6. Current bid - doesn't show decimal value 
![image](https://user-images.githubusercontent.com/1945230/38613076-65d38204-3d91-11e8-8ea2-65006a5259bd.png)
http://version1.vladtest48baucstore-vladtest48b.kademi-ci.co/auctions/

7. Grant rewards journey step - doesn't save decimal values
![image](https://user-images.githubusercontent.com/1945230/38613238-e2d66956-3d91-11e8-8e99-2704f90c4198.png)
http://vladtest48b.admin.kademi-ci.co/funnels/journey1/version1/#journeyBuilder-tab

i think that there could be more places :(

**Comment by bradmac** [comment]
> final points in reward store doesn't save
Fixed

**Comment by bradmac** [comment]
> award and debit points doesn't takes decimal values

Fixed

![image](https://user-images.githubusercontent.com/826458/38644424-8937088a-3e34-11e8-9f61-0b93a01f08e0.png)

**Comment by bradmac** [comment]
> Frontend doesn't show decimal points at all. E.g. product cost is 980.15 and it shows 980

I think this is correct. In practise no one will ever use decimal points on product costs.

**Comment by bradmac** [comment]
> Shopping cart doesn't display decimals

As above, i think this is fine.

**Comment by bradmac** [comment]
> Auctions doesn't allow to place a decimal value

This is also ok, users wont place bid with decimal points.

**Comment by bradmac** [comment]
> Current bid - doesn't show decimal value

As above

**Comment by bradmac** [comment]
> Grant rewards journey step - doesn't save decimal values

This is fine

**Comment by bradmac** [comment]
Just to clarify, we're making a change because its necessary to support **awarding** fractional points. Eg someone might be awarded 0.4 points 20 times. Without this change each points record would be rounded to zero and so they wont have any points. With this change they  will receive 0.4 x 20 = 8 points.

However, there is no requirement and no expectation that users will ever use fractional points. Eg they wont purchase an item for 0.4 points. They will always use integers for purchasing and bidding.

**Comment by Uafinder** [comment]
1,2 - ok, others understood

next one
![image](https://user-images.githubusercontent.com/1945230/38681552-a1becc66-3e71-11e8-8ec3-96c6856769b6.png)
Doesn't support decimal points to view
http://vladtest48d.admin.kademi-ci.co/points-buckets/

number of records can't be decvimal
![image](https://user-images.githubusercontent.com/1945230/38681610-c20e50a4-3e71-11e8-81d2-116bf99220be.png)

assign points on users page doesn't allow to do it in decimal
![image](https://user-images.githubusercontent.com/1945230/38681660-e78256a0-3e71-11e8-8de1-862caa4473bb.png)
http://vladtest48d.admin.kademi-ci.co/manageUsers/15751804/#pointsBucketTab-tab

same for debit
![image](https://user-images.githubusercontent.com/1945230/38681692-f8e01144-3e71-11e8-8463-1cda06d3588e.png)

When allocation multiplier is set to decimal - it's converts to debit
E.g. you award 10 points and multiplier is set to 0.25 - it debits 7.5 points
![image](https://user-images.githubusercontent.com/1945230/38682461-cca26e18-3e73-11e8-9ab0-06b79faef0f1.png)
http://vladtest48d.admin.kademi-ci.co/points-rules/test2#general-tab

points statements doesn't display decimal points
![image](https://user-images.githubusercontent.com/1945230/38682629-4097eece-3e74-11e8-9166-0cf663f6ae28.png)
http://vladtest48d.admin.kademi-ci.co/pointsBalanceStats/

decimal reward points in automation details is not saving
![image](https://user-images.githubusercontent.com/1945230/38683014-26f6570c-3e75-11e8-92ce-11d250184346.png)
![image](https://user-images.githubusercontent.com/1945230/38683027-2f109a24-3e75-11e8-8bfc-40f1a7641085.png)
http://vladtest48d.admin.kademi-ci.co/autoEmails/15752924/?startDate=12/03/2018&finishDate=12/04/2018#action-tab

**Comment by bradmac** [comment]
> Doesn't support decimal points to view

Thats fine, admins dont want to see decimals here


> number of records can't be decvimal

Fixed

**Comment by bradmac** [comment]
> assign points on users page doesn't allow to do it in decimal

Fixed

> same for debit

Fixed

**Comment by bradmac** [comment]
> When allocation multiplier is set to decimal - it's converts to debit. E.g. you award 10 points and multiplier is set to 0.25 - it debits 7.5 points

This is correct. A multiplier of "2" means double points, so an original award of 10 will result in a total of 20 points being awarded (the original 10 + bonus 10).

That means a multiplier of 1 means no change, just the original points awarded and no bonus points.

A multiplier of less then 1 therefore means awarding **less then the original points**. That means we award the original amount and then debit an amount. So a multiplier of .25 means to award only 25% of the original amount. So in your example we award 10 points then debit 7.5 so a total of 2.5 is awarded

**Comment by bradmac** [comment]
> points statements doesn't display decimal points

I've updated the db column in CI to be double precision instead of integer. Newly created statements should now have decimals

**Comment by bradmac** [comment]
> decimal reward points in automation details is not saving

Thats fine, automation is deprecated.

**Comment by Uafinder** [comment]
Ok, all detected ok...
another ones
points not uploading when decimals are present
![image](https://user-images.githubusercontent.com/1945230/38722091-773b9732-3f05-11e8-980d-9e5abedda961.png)
http://vladtest48e.admin.kademi-ci.co/tableUploaders/pointsUploader
[points (6).txt](https://github.com/Kademi/kademi-dev/files/1906247/points.6.txt)

Points balance should be restricted by two decimal digits after comma
![image](https://user-images.githubusercontent.com/1945230/38722425-9094a25e-3f06-11e8-9fda-6d113365509d.png)
http://version1.vladtest48eweb-vladtest48e.kademi-ci.co/page1.html

Same for points earned components
![image](https://user-images.githubusercontent.com/1945230/38722657-40d3b8ee-3f07-11e8-80ab-dc37b6b81f37.png)
http://version1.vladtest48eweb-vladtest48e.kademi-ci.co/page1.html

Points for a user component doesn't show decimal points
![image](https://user-images.githubusercontent.com/1945230/38722709-709e74f6-3f07-11e8-8e43-902373f1626a.png)
http://version1.vladtest48eweb-vladtest48e.kademi-ci.co/page1.html

**Comment by bradmac** [comment]
> Points balance should be restricted by two decimal digits after comma

Removed decimal places. I dont think participants are interested in seeing fractional points in their balance

**Comment by bradmac** [comment]
> Same for points earned components

As above, now shows integer only

> Points for a user component doesn't show decimal points

This is correct

**Comment by Uafinder** [comment]
All fixed except this one https://github.com/Kademi/kademi-dev/issues/5331
Well, looks all of them are fixed
