### ISSUE TITLE
kcrm email notification

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#5305]
When i completed a task and assigned back to vlad for testing, it sent me an email 
```
Hi Anh Nguyen,
A task has been edited and/or assigned to you. Click Here to view it.
```

I think we should only send this to Vlad, not to me

**Comment by anhnt** [comment]
And also please add email tittle ie lead title

**Comment by bradmac** [comment]
Modified so now notifications will not be sent to the current user
