### ISSUE TITLE
Product list component broken

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#5308]
http://moblix.admin.kademi-ci.co/pages/moblixchannel/version1/

Open dashboard.

1) This was a dropdown with predefined values, but now a now free text, still changing this value does not update the component.  Why was this changed?
2) The item per row field does not update the component

Note libs have been updated.

![image](https://user-images.githubusercontent.com/2201340/38590997-e5e7c438-3d77-11e8-814c-afc5d1f310e2.png)

**Comment by bradmac** [comment]
OK, fixed a problem with mtree and mupload libs. These were correct in main source, but the versions in this account were different to whats deployed, and had the "admin" group for the js files.

Changed this to "main" and they're now correctly rendered with other js files.

However, I'm now seeing a problem with the editor not initialising.

**Comment by bradmac** [comment]
Also, can you please update the getAllGroups method in contentEditor-lib/app.js to set a content type of text/javascript? This is causing a parse error in FF

**Comment by anhnt** [comment]
re-added component that fixed the problem

**Comment by Uafinder** [comment]
looks fine
