### ISSUE TITLE
KCRM focus on extra fields tab when fields are not valid

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#5309]
![image](https://user-images.githubusercontent.com/735555/38596820-edc83876-3d7d-11e8-9e79-1e72009eef5b.png)

At the moment it stays at Lead details tab without showing any error

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/39045660-a5fe8bd4-44bd-11e8-8261-6e45217466fe.png)

Working ok for me on that site

**Comment by Uafinder** [comment]
Ok, i thought it should switch tab when extra field is not filled
Brad, how do you think... would this be a better solution?

**Comment by bradmac** [comment]
> Ok, i thought it should switch tab when extra field is not filled

I think this is ok for now.
