### ISSUE TITLE
clciking on mark as complete button cause window to collapse and nothing happen

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5312]
![image](https://user-images.githubusercontent.com/1945230/38616166-b8e530fa-3d9b-11e8-961e-085313c1aa43.png)
![image](https://user-images.githubusercontent.com/1945230/38616172-be1db236-3d9b-11e8-9be0-e5ae81bcb4bb.png)
http://vladtest48cleads-vladtest48c.kademi-ci.co/leads/15738849/

**Comment by bradmac** [comment]
hey guys, note that is part of this issue which hasnt been completed correctly yet

https://github.com/Kademi/kademi-dev/issues/5272
