### ISSUE TITLE
Error when refresh license for account

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5313]
1. Select some old account
2. Add license
3. Push refresh license
4. Note bunch of errors in console
![image](https://user-images.githubusercontent.com/1945230/38621589-d38a086e-3da9-11e8-9448-4cd0ecf618e5.png)
http://rootorg.admin.kademi-ci.co/subscriptions/3102743/
http://vladtest01.admin.kademi-ci.co/license?refreshLicense=true

**Comment by bradmac** [comment]
@Uafinder i think this is just because the account hasnt been updates for the new admin-lib stuff. All real accounts have been updated so this is just a CI issue, and wont affect real clients.

So if thats the case we can close.

**Comment by Uafinder** [comment]
ok
