### ISSUE TITLE
Option to control notifications from leadman

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5314]

**Comment by bradmac** [comment]
This is controlled at the account level:

![image](https://user-images.githubusercontent.com/826458/38653548-6f68d85e-3e5f-11e8-8a6f-56669c887af0.png)

**Comment by Uafinder** [comment]
Doesn't work for me
![image](https://user-images.githubusercontent.com/1945230/38730954-40556844-3f21-11e8-9835-3a60faa7bc7d.png)
http://vladtest48e.admin.kademi-ci.co/manageApps/#installed-tab
![image](https://user-images.githubusercontent.com/1945230/38730971-50a6b464-3f21-11e8-9600-91c61483dd6e.png)
http://vladtest48e.admin.kademi-ci.co/websites/vladtest48eleads/version1/#panel_apps-tab

Then i go here, add some tasks, change assignments, but nothing changed - emails doesn't fire.

**Comment by bradmac** [comment]
Note that it wont email the current user, so you need at least 2 users in the "sales" group.

I've just added myself and then assigned a lead to adminqa, and saw the notification was sent

http://vladtest48e.admin.kademi-ci.co/emails/15846350

**Comment by AlaaKhalaf94** [comment]
passed
