### ISSUE TITLE
Allow multiple ORG types up ORG upload

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#5315]
See here http://rhipe.admin.kademi.com.au/organisations/

I need to upload partners with two types:
- Partner
- Partner-Transacting

The only way to do this is:
- Update spreadsheet to include a new temp ORG type like 'org1'
- Tag all records with 'org1'
- Upload records
- Filter by 'org1' then apply the 2x org types
- Delete org type 'org1'

Enhancement would be to allow a file upload to include multiple columns to assign ORG Ids

**Comment by bradmac** [comment]
@paddyow you can do that now by having both org types in one cell seperately by commas

**Comment by bradmac** [comment]
Example 

[test-import-orgs.xlsx](https://github.com/Kademi/kademi-dev/files/1913762/test-import-orgs.xlsx)

![image](https://user-images.githubusercontent.com/826458/38788474-efe80f88-4187-11e8-8fcb-12608ced40aa.png)

**Comment by paddyow** [comment]
Nice!
