### ISSUE TITLE
New orders CSV

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5316]
Columns

Product SKU
Date
First Name
Last Name
Redemption Product Name
Redemption Product Quantity
Shipping Address
City
State
Post Code
Phone Number

Eg

Product SKU | Date | First Name | Last Name | Redemption Product Name | Redemption Product Quantity | Shipping Address | City | State | Post Code | Phone Number
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
VISA20 | 31/07/2017 | Joe | Bloggs | $20 Visa Card | 1 | PO Box 9999 | Esperance | Western Australia | 2222 |  123456789

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/38711327-1d2182f2-3f19-11e8-8504-bbb014cc4e8a.png)

**Comment by Uafinder** [comment]
Phone number is not exporting
http://vladtest48e.admin.kademi-ci.co/shopping-carts
![image](https://user-images.githubusercontent.com/1945230/38734283-a9000a28-3f2d-11e8-8355-88cd244e05d9.png)
![image](https://user-images.githubusercontent.com/1945230/38734301-b91d3cd2-3f2d-11e8-934b-e3bc17d71043.png)

**Comment by bradmac** [comment]
It was using the phone from the user's profile. Now it will take firstname, surname and phone from the cart if available, otherwise will read them from the profile.

**Comment by Uafinder** [comment]
ok, it works
only one thing - city column is always empty, I don't think that it's needed...

**Comment by bradmac** [comment]
City isnt used in our standard checkout form, but it can be used in custom forms so we need to support outputting it
