### ISSUE TITLE
Top 10 balances component doesn't show info

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5319]
![image](https://user-images.githubusercontent.com/1945230/38723375-8d47c9c0-3f09-11e8-9cd0-b73dc2097b05.png)
![image](https://user-images.githubusercontent.com/1945230/38723403-99b7edfc-3f09-11e8-9c55-0237186c398d.png)
http://version1.vladtest48eweb-vladtest48e.kademi-ci.co/page3.html
http://vladtest48e.admin.kademi-ci.co/pages/vladtest48eweb/version1/

**Comment by anhnt** [comment]
Hi @Uafinder 

Please add reporting access role to user who is seeing the report
Please reindex profile and org indexes as we have changed some stuff recently
tested ok with local

**Comment by AlaaKhalaf94** [comment]
passed
