### ISSUE TITLE
Issue on the leads dashboard with task description

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5322]
![image](https://user-images.githubusercontent.com/1945230/38730276-81c58b22-3f1e-11e8-8185-fd9b3ded59da.png)
http://vladtest48eleads-vladtest48e.kademi-ci.co/dashboard
user: adminqa@mailinator.com

**Comment by anhnt** [comment]
Sounds like its already sorted out

**Comment by Uafinder** [comment]
Looks fine now
