### ISSUE TITLE
Lib error in blackberry demo on sales page

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5325]
Pls be aware of this one
![image](https://user-images.githubusercontent.com/1945230/38731209-1aecb3cc-3f22-11e8-9d0b-a94ccdf5d600.png)
http://blackberry-demo.admin.kademi.us/sales/rebate-incentive/kpis/progress/#general-tab

**Comment by anhnt** [comment]
We need to remove static d3 & nvd3 import so it wont conflict with libs version

**Comment by anhnt** [comment]
Fixed. d3-lib dependencies.json content is not correct that caused this error

**Comment by Uafinder** [comment]
Well, seems like sales page is broken now
http://blackberry-demo.admin.kademi.us/sales/
![image](https://user-images.githubusercontent.com/1945230/38793295-5b564ebc-4159-11e8-85e9-45b9f29e668f.png)

Could it be connected to your fix?

**Comment by bradmac** [comment]
errors like that are usually the result of an inconsistent server cache which only affects CI, not production

solution is usually to restart the server. its only a problem if it happens reproducibly

**Comment by bradmac** [comment]
oh thats prod, let me check..

**Comment by bradmac** [comment]
Sorted

**Comment by Uafinder** [comment]
Yup, looks fine
