### ISSUE TITLE
Scorm file failed to upload

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#5330]
http://kademidemo.admin.kademi.us/websites/scorm/version1/programs/test/test/test/#files-tab

1) I created a new module 
2) Uploaded the scorm file
3) No module page was created, so I created one
4) When you view the module page you get the error 'The host name version1.scorm-kademi-demo.kademi.us was not found on this server
'
5) I then created a new module
6) then created a new module page but get the same error I did from the previous module http://kademidemo.admin.kademi.us/websites/scorm/version1/programs/test/test/test2/#files-tab

**Comment by bradmac** [comment]
> No module page was created, so I created one

This is incorrect

**Comment by paddyow** [comment]
Sending the file by WeTransfer to you and Vlad.

**Comment by Uafinder** [comment]
ok, created a fresh account, create a module structure, open empty module, upload zip file...
file uploaded ok, but nothing is happened after upload... after refresh content also doesn't appear...
http://vladtest49c.admin.kademi-ci.co/websites/vladtest49cweb/version1/programs/Program1/Course1/Module1/#files-tab

**Comment by bradmac** [comment]
OK, the file provided is not a valid SCORM 2004 file.

I think they've just exported from Articulate to HTML format, but they didnt choose the SCORM 2004 export option.
