### ISSUE TITLE
keditor list members both component filter by group doesn't work

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5334]
![image](https://user-images.githubusercontent.com/1945230/38807554-a8ba34f8-4185-11e8-9a4b-2092189261e7.png)
http://vladtest49a.admin.kademi-ci.co/pages/vladtest49aweb/version1/

I have a bunch of users in different groups
But when I select a filter it still displays me all users.

**Comment by anhnt** [comment]
Done

**Comment by AlaaKhalaf94** [comment]
tested
