### ISSUE TITLE
Stop/Go funnel goal

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5338]
Create a goal which allows manual control of progression.

All leads should initially stop. The administrator can click a button which will cause all leads stopped on that goal to proceed

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/38908618-406acde0-4315-11e8-80d7-8e47d944f590.png)

**Comment by Uafinder** [comment]
ok, it works
pls note this
https://github.com/Kademi/kademi-dev/issues/5340
