### ISSUE TITLE
Access token exception in Xero

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5343]
```
12:08:49 INFO  com.fuselms.apps.rewardstore.OrgInvoicingProcessable  - doProcess
12:08:49 INFO  io.milton.cloud.server.apps.invoicing.InvoicingService  - processOrg
12:08:49 INFO  io.milton.cloud.server.apps.invoicing.InvoicingService  - processOrg: processing invoices.. 1
12:08:49 INFO  io.milton.cloud.server.apps.invoicing.InvoicingService  - createInvoices: processing org=xerotest2 invoices=1 app=co.kademi.server.apps.xero.XeroApp@78ad7c25
12:08:49 INFO  co.kademi.server.apps.xero.XeroApp  - createInvoice: invoices=1
12:08:49 INFO  co.kademi.server.apps.xero.XeroService  - generateInvoice: customer=Brad number=null line-items=1
12:08:49 INFO  co.kademi.server.apps.xero.XeroService  - refreshToken: profile=brad token=HJOUIGDHULASNAFNR7EF91I66XASWL
12:08:50 INFO  io.milton.cloud.server.manager.SignatureManager  - setSignature: profileid=3237680 source=xero
12:08:50 INFO  io.milton.cloud.server.manager.SignatureManager  - setSignature: Found existing signature ID=15908661 profile name=brad
12:08:50 INFO  io.milton.cloud.server.manager.SignatureManager  - Saved credential ID=15908661 source=xero profileName=brad
12:08:50 INFO  co.kademi.server.apps.xero.XeroService  - refreshToken: updated signature id=15908661 sig=xeroUser
12:08:50 INFO  io.milton.cloud.server.db.AppControl  - settings: 1
12:08:50 INFO  io.milton.cloud.server.db.AppControl  - found: xeroOAuthProfileId
12:08:50 INFO  io.milton.cloud.server.db.AppControl  - use existing appsetting:  xeroOAuthProfileId
12:08:50 INFO  io.milton.cloud.server.apps.settings.DbAppSettingsService  - setOrgAppSettings: acId=15908633 name=xeroOAuthProfileId value=3237680
12:08:52 INFO  co.kademi.server.stream.audit.KademiAuditService  - tx complete tx=1187107835 updates=1 creates=0 loads=4
12:08:52 ERROR io.milton.context.RootContext  - error executing: io.milton.cloud.server.queue.impl.LocalAsynchProcessor$$Lambda$713/1073792176@224902df
12:08:52 com.xero.api.XeroApiException: token_rejected - Token HJOUIGDHULASNAFNR7EF91I66XASWL does not match an expected ACCESS token 
12:08:52 	at com.xero.api.exception.XeroExceptionHandler.newApiException(XeroExceptionHandler.java:136)
12:08:52 	at com.xero.api.exception.XeroExceptionHandler.convertException(XeroExceptionHandler.java:99)
12:08:52 	at com.xero.api.XeroClient.get(XeroClient.java:211)
12:08:52 	at com.xero.api.XeroClient.getContacts(XeroClient.java:668)
12:08:52 	at co.kademi.server.apps.xero.XeroService.getContactByContactNumber(XeroService.java:197)
12:08:52 	at co.kademi.server.apps.xero.XeroService.getOrCreateContact(XeroService.java:434)
12:08:52 	at co.kademi.server.apps.xero.XeroService.generateInvoice(XeroService.java:366)
12:08:52 	at co.kademi.server.apps.xero.XeroService.createInvoicesFromHolders(XeroService.java:242)
```

**Comment by tuzzmaniandevil** [comment]
Pushed a change to kademi-server and kademi-vfs (vfs will need to be incremented and deployed)

@bradmac once this is on Prod, Can you get Lyle to attempt to reconnect Xero to the viridian account?

**Comment by bradmac** [comment]
deployed vfs 2.4.2, and updated kademi-server

**Comment by bradmac** [comment]
Hey @tuzzmaniandevil can you verify this works on CI before we hand over to the client?

**Comment by tuzzmaniandevil** [comment]
@bradmac Yup, Give me an account to test with and i'll get on it :-)

**Comment by bradmac** [comment]
http://wesxero.admin.kademi-ci.co

**Comment by tuzzmaniandevil** [comment]
@bradmac Please update CI for testing

**Comment by bradmac** [comment]
done

**Comment by tuzzmaniandevil** [comment]
Seems to be working great now, Refreshing token without an issue

**Comment by bradmac** [comment]
Hey @Uafinder I'm looking closely at this myself, I'll take care of it :)

**Comment by bradmac** [comment]
@Uafinder note this depends on https://github.com/Kademi/kademi-dev/issues/5344

Dont bother reviewing this until we can see invoices are generated correctly in kademi (ie without xero)

To test it, 
- register with Xero to get a free trial account
- install the Xero app from the marketplace
- connect your credentials to the Xero app:
![image](https://user-images.githubusercontent.com/826458/39609033-dbf5405c-4f99-11e8-9c6d-c5c75db65123.png)

**Comment by bradmac** [comment]
Then you need a correctly setup reward store (as per #5344) and place some orders.
1. Ensure purchase orders are enabled, and verify they are created in Xero immediately after an order is placed. Check the numeric values of the costs are accurate for the purchase cost from a supplier
2. Verify the weekly invoice is generated and sent to the client. Note these costs are different (higher) then the purchase costs from the supplier

Then the auto-invoicing should be generated and setnt

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/39663128-229b4cd6-5076-11e8-8bc9-17ffaf32e8f0.png)
http://vladtest51a.admin.kademi-ci.co/shopping-carts/

**Comment by bradmac** [comment]
Hey @Uafinder i think the tax problem is resolved

BUT please use this issue to only track problems with access token. If you see any other problems related to calculations put that on a seperate issue, so we can close this once the Xero access is sorted out.

Note that the critical thing to check here is that tokens are refreshed after a period of inactivity. I think if we can confirm access continues to work after a week that is sufficient.

**Comment by Uafinder** [comment]
Looks fine at the moment...
