### ISSUE TITLE
RewardStore Invoices are generated without GST

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5344]

**Comment by bradmac** [comment]
Fixed in the admin web view:
![image](https://user-images.githubusercontent.com/826458/38972092-bf31e946-43f2-11e8-8787-1631dcf2be1c.png)

**Comment by bradmac** [comment]
However, is not in the attached PDF when sent

**Comment by bradmac** [comment]
Purchase orders:

From the client:

> Supplier = Buy Price + Freight + GST
Invoices to Client = (points price/points multiplier)/GST

**Comment by bradmac** [comment]
Purchase orders are looking good.

But getting an incorrect total on invoices:
http://bradxero.admin.kademi-ci.co/auto-invoicing/

![image](https://user-images.githubusercontent.com/826458/39506676-4923b4fa-4e2e-11e8-8600-ced2fdce6cfa.png)

**Comment by bradmac** [comment]
To test this, start by enabling auto invoicing for reward stores:
![image](https://user-images.githubusercontent.com/826458/39608766-f5f0c384-4f97-11e8-8b81-5ce7def944a3.png)

Install the PaymentApp. This will use Kademi's built in invoicing system (real clients will likely use Xero instead)

If you're using an existing account, ensure the date is set to the past so you can see it generate new invoices. You can change this back to repeatedly test.

Then ensure you have some orders in the Orders page to be invoiced.

Next, open the auto-invoicing page. This will show you the invoice(s) that will be generated. Check this information is correct:
![image](https://user-images.githubusercontent.com/826458/39608803-30f05058-4f98-11e8-8803-ba876b760ab8.png)

If that information is correct hit the button to generate invoices:
![image](https://user-images.githubusercontent.com/826458/39608807-40e71118-4f98-11e8-8435-a85e3da19250.png)

Note that this page doesnt auto-refresh after pressing the button (its not expected to be used by clients, just for debugging). Refresh to see that no invoice appears.

Now view the Invoices page and verify the invoice has been created:
![image](https://user-images.githubusercontent.com/826458/39608841-7c6aa010-4f98-11e8-91b7-eee9a90f26e2.png)

Click through to see the invoice detail:
![image](https://user-images.githubusercontent.com/826458/39608852-8c40c88e-4f98-11e8-87e6-94dd571d54f2.png)

**Comment by bradmac** [comment]
@Uafinder please check the numbers are correct

For orders placed through the rewardstore the user sees the price in points, but its critical that the invoice sent to the client is in dollars

You can see how points are calculated from the reward store page:
![image](https://user-images.githubusercontent.com/826458/39608941-22d691fc-4f99-11e8-8973-442d604d8c5b.png)

Note that the reward store should be setup as follows
- enabled inventory control
- costs should be assigned to SKUs
- the reward store should have appropriate settings for margin and tax:

![image](https://user-images.githubusercontent.com/826458/39608957-48681c10-4f99-11e8-8847-1dbe98f98ef8.png)

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/39628131-b3ee2b66-4fb0-11e8-9c9d-eef69d8260f8.png)
http://vladtest51.admin.kademi-ci.co/invoices/16046680/
Still doesn't see GST in invoice and tax issue...
however unit price and total amount is correct

**Comment by bradmac** [comment]
Have updated the column in CI to be decimal instead of integer

**Comment by bradmac** [comment]
And fixed some calcs, should be better now..
![image](https://user-images.githubusercontent.com/826458/39679342-318edb92-51f0-11e8-9c9a-9a3886285110.png)

**Comment by Uafinder** [comment]
Yup, looks better
