### ISSUE TITLE
Support translations in assets

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5351]

**Comment by bradmac** [comment]
Need to work out how to handle translations of image assets. I think we need to hold this on the entity, rather then leveraging translationservice persistence

**Comment by bradmac** [comment]
Setup a couple of langages from the translations page
![image](https://user-images.githubusercontent.com/826458/39953670-eb512572-5604-11e8-99f0-b7bb67000057.png)

Start with an asset in the default language
![image](https://user-images.githubusercontent.com/826458/39953661-d1637b88-5604-11e8-9ed9-ce412d84a9a1.png)

Then create a translation:
![image](https://user-images.githubusercontent.com/826458/39953677-09c450ba-5605-11e8-98d7-dbf615d5e027.png)

You will then have a copy of the asset with the original text, but assigned to the selected language. Edit the text to be a translation (hint: translate.google.com)
![image](https://user-images.githubusercontent.com/826458/39953722-adba5926-5605-11e8-9e00-c858bb289c26.png)

**Comment by bradmac** [comment]
Insert a text asset component (no preview yet)
![image](https://user-images.githubusercontent.com/826458/39953748-18634206-5606-11e8-9886-10294918404f.png)


Select your asset:
![image](https://user-images.githubusercontent.com/826458/39953737-f9c24662-5605-11e8-9140-2094f2126f1a.png)

**Comment by bradmac** [comment]
View the page in the website with language selector enabled in the menu, and default selected

Verify the default text is displayed:
![image](https://user-images.githubusercontent.com/826458/39953753-47fed994-5606-11e8-9300-57248e450a05.png)

Select the language of your translation and verify the translation is displayed:
![image](https://user-images.githubusercontent.com/826458/39953757-604656e4-5606-11e8-884d-59eefcfb2b9a.png)

**Comment by Uafinder** [comment]
Works like a charm
