### ISSUE TITLE
Timesheets app

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5355]
Provide the ability to enter hours against tasks, leads and/or plain text tasks.

Ability to submit for approval.

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/39220313-41f7bef6-4884-11e8-960a-6d3af57612da.png)

**Comment by bradmac** [comment]
Implemented in KTimesheets

**Comment by bradmac** [comment]
> while accessing timesheets

Was an incorrect column in the CI db. Fixed

**Comment by Uafinder** [comment]
1. When you enter some time to some task - task become not clickable and become to look bad
![image](https://user-images.githubusercontent.com/1945230/40041811-fe6a42cc-5827-11e8-876d-0a89c0948602.png)
http://vladtest51hleads-vladtest51h.kademi-ci.co/timesheets/

2. There is a possibility to see this grand total value
![image](https://user-images.githubusercontent.com/1945230/40041831-11a00fb6-5828-11e8-87eb-b9097acc9ff4.png)
http://vladtest51hleads-vladtest51h.kademi-ci.co/timesheets/

3. When you add a custom text task it gives you following error while entering some time
![image](https://user-images.githubusercontent.com/1945230/40041935-5af67b96-5828-11e8-9a2a-6c5dca57591c.png)
http://vladtest51hleads-vladtest51h.kademi-ci.co/timesheets/

4. When add time to a lead it gives you following error
![image](https://user-images.githubusercontent.com/1945230/40041979-7b2a2804-5828-11e8-9663-1ca92a27fee4.png)
http://vladtest51hleads-vladtest51h.kademi-ci.co/timesheets/

5. Error on second batch submit. Should be more pretty
![image](https://user-images.githubusercontent.com/1945230/40042063-ad42053c-5828-11e8-870e-931ef6448539.png)
http://vladtest51hleads-vladtest51h.kademi-ci.co/timesheets/

6. Timerange and dates on columns are not match
![image](https://user-images.githubusercontent.com/1945230/40042089-c96ef8e6-5828-11e8-9245-b64bb9facd73.png)
http://vladtest51hleads-vladtest51h.kademi-ci.co/timesheets/

**Comment by bradmac** [comment]
> When you enter some time to some task - task become not clickable and become to look bad
Fixed

> There is a possibility to see this grand total value
Fixed, 2 decimal places

> When you add a custom text task it gives you following error while entering some time
Fixed

> When add time to a lead it gives you following error
Fixed

> Error on second batch submit. Should be more pretty
This is fine for our purpose, doesnt need to be pretty

> Timerange and dates on columns are not match
This is correct, the timesheet displays for a calendar week with fixed start and end days. This is made to overlap with the selected date range, but isnt necessarily the same

**Comment by Uafinder** [comment]
Upper are fixed

More
1. Error while adding time to lead
![image](https://user-images.githubusercontent.com/1945230/41661248-e9cdac14-74a6-11e8-89c9-f02a4144759b.png)
http://vladtest52sleads-vladtest52s.kademi-ci.co/timesheets/

2. Visual bug when task name contains more than one word less than 3 words
![image](https://user-images.githubusercontent.com/1945230/41661337-2b915cf4-74a7-11e8-9d65-79e5e657eea9.png)
http://vladtest52sleads-vladtest52s.kademi-ci.co/timesheets/
http://vladtest52s.admin.kademi-ci.co/manageUsers/

3. Submit hours doesn't save time for leads
looks like related to first issue
e.g. there is some time entered for a lead, and when you submit hours it's just clears that field. Same happening while refresh page

4. there is a possibility to enter negative time value
![image](https://user-images.githubusercontent.com/1945230/41661697-f49ef4da-74a7-11e8-9226-7d361ecce2d1.png)
http://vladtest52sleads-vladtest52s.kademi-ci.co/timesheets/

**Comment by bradmac** [comment]
> Error while adding time to lead

I cant reproduce, appears to save correctly. If you can reproduce make sure yuo give me the user you're logging in with.

**Comment by bradmac** [comment]
> Visual bug when task name contains more than one word less than 3 words

This layout is expected

**Comment by bradmac** [comment]
> Submit hours doesn't save time for leads

Cant reproduce. I entered hours, refreshed to ensure they were saved. I then submitted hours and also refreshed and checked it had been saved. All looks good:

Logged in with: http://vladtest52s.admin.kademi-ci.co/manageUsers/16800959/#summary-tab

After submitting and refreshing:
![image](https://user-images.githubusercontent.com/826458/41684961-292f912e-7533-11e8-9bd3-28a0d30f3dd6.png)

**Comment by bradmac** [comment]
> there is a possibility to enter negative time value

I've added a check to prevent that

**Comment by bradmac** [comment]
Should be fixed now

**Comment by Uafinder** [comment]
1. Some code appears
![image](https://user-images.githubusercontent.com/1945230/41808296-fd96b9c2-76e3-11e8-825e-ccb14640598e.png)
http://vladtest52vleads-vladtest52v.kademi-ci.co/timesheets/
http://vladtest52v.admin.kademi-ci.co/manageUsers/16814766/#summary-tab this user

Seems something broken
![image](https://user-images.githubusercontent.com/1945230/41808315-2e903b3e-76e4-11e8-96ca-6ae667b606b9.png)

I've tried two fresh accounts

**Comment by bradmac** [comment]
Yep. there are missing libs:
![image](https://user-images.githubusercontent.com/826458/41823988-e4fd7c50-785c-11e8-9118-1a4f262ef284.png)

**Comment by bradmac** [comment]
I turned the apps off and on again to correct:
![image](https://user-images.githubusercontent.com/826458/41824006-2f0ee540-785d-11e8-98c9-e8bf292141f2.png)

**Comment by bradmac** [comment]
Removed debug code

**Comment by Uafinder** [comment]
Issue with adding time to leads not fixed
![image](https://user-images.githubusercontent.com/1945230/41837804-407977aa-7867-11e8-999b-f820be14e4f4.png)
http://vladtest52wleads-vladtest52w.kademi-ci.co/timesheets/
this user
http://vladtest52w.admin.kademi-ci.co/manageUsers/16874049/#summary-tab

**Comment by bradmac** [comment]
Fixed

**Comment by Uafinder** [comment]
Mostly ok
https://github.com/Kademi/kademi-dev/issues/5608
