### ISSUE TITLE
Error rendering contactus component

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5359]
ERROR io.milton.http.StandardFilter  - exception sending content
20:51:08 java.lang.RuntimeException: org.apache.velocity.exception.MethodInvocationException: Invocation of method 'getOptins' in  class io.milton.cloud.server.apps.contactus.ContactUsFormPage threw exception java.lang.NullPointerException at vladtest49ublogs-vladtest49u.kademi-ci.co:/theme/apps/contactus/components/contactFormSettings.html[line 24, column 45]
20:51:08 	at io.milton.http.http11.GetHandler.sendContent(GetHandler.java:233)
20:51:08 	at io.milton.http.http11.GetHandler.processExistingResource(GetHandler.java:85)
20:51:08 	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:196)
20:51:08 	at io.milton.http.http11.GetHandler.processResource(GetHandler.java:66)
20:51:08 	at io.milton.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:127)
20:51:08 	at io.milton.http.http11.GetHandler.process(GetHandler.java:60)
20:51:08 	at io.milton.http.StandardFilter.process(StandardFilter.java:50)
20:51:08 	at io.milton.http.FilterChain.process(FilterChain.java:46)
20:51:08 	at co.kademi.server.subscription.KademiSubscriptionFilter.process(KademiSubscriptionFilter.java:48)
20:51:08 	at io.milton.http.FilterChain.process(FilterChain.java:46)
20:51:08 	at co.kademi.server.idp.IDPFilter.process(IDPFilter.java:43)
20:51:08 	at io.milton.http.FilterChain.process(FilterChain.java:46)
20:51:08 	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter$1.execute(MiltonOpenSessionInViewFilter.java:41)
20:51:08 	at io.milton.context.RootContext.execute(RootContext.java:90)
20:51:08 	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter.process(MiltonOpenSessionInViewFilter.java:34)
20:51:08 	at io.milton.http.FilterChain.process(FilterChain.java:46)
20:51:08 	at co.kademi.server.webcache.KademiWebCacheFilter.process(KademiWebCacheFilter.java:125)
20:51:08 	at io.milton.http.FilterChain.process(FilterChain.java:46)
20:51:08 	at io.milton.http.HttpManager.process(HttpManager.java:158)
20:51:08 	at co.kademi.server.Kademi$1.service(Kademi.java:194)
20:51:08 	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
20:51:08 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
20:51:08 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
20:51:08 	at java.lang.Thread.run(Thread.java:748)
20:51:08 Caused by: org.apache.velocity.exception.MethodInvocationException: Invocation of method 'getOptins' in  class io.milton.cloud.server.apps.contactus.ContactUsFormPage threw exception java.lang.NullPointerException at vladtest49ublogs-vladtest49u.kademi-ci.co:/theme/apps/contactus/components/contactFormSettings.html[line 24, column 45]

Fresh account
http://vladtest49u.admin.kademi-ci.co/websites/vladtest49ublogs/version1?editTemplate=theme/apps/contactus/contactForm
![image](https://user-images.githubusercontent.com/1945230/39176726-2c0b74d0-47b6-11e8-9927-06caeb2d4390.png)

**Comment by mkhoudary** [comment]
Fixed

**Comment by Uafinder** [comment]
It works on the fresh account!
