### ISSUE TITLE
Existing account keditor failed to load

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5360]
http://vladtest47d.admin.kademi-ci.co/pages/vladtest47dweb/version1/testfolder/?contenteditor=pagetest5769.html
http://vladtest47d.admin.kademi-ci.co/pages/vladtest47dweb/version1/testfolder/
While opening it instantly saving and stucks
![image](https://user-images.githubusercontent.com/1945230/39185478-f3c28216-47cf-11e8-822d-4efa7f657979.png)

Spotted by katalon

**Comment by bradmac** [comment]
Just checked and seems ok currently
![image](https://user-images.githubusercontent.com/826458/39216470-e22cb616-486f-11e8-9e3f-8b1b2790735d.png)

**Comment by bradmac** [comment]
If you see the problem again please check the browser console for errors.

**Comment by Uafinder** [comment]
I watched... there was no errors... anyway i also doesn't see a problem anymore
