### ISSUE TITLE
Error while accessing logs page on travelworld

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5365]
![image](https://user-images.githubusercontent.com/1945230/39231309-4b60ba86-4872-11e8-874b-21d086d05c01.png)
http://travelworld.admin.kademi.com.au/logging

**Comment by bradmac** [comment]
Re-index the console messages index and is ok now.

We changed format for the logging index a while ago, so this is required for each account tht hasnt been reindexed since then
