### ISSUE TITLE
Sales Table Component to filter by logged in user

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#5367]
Currently the sales table component displays all the data in the selected data series, to be used by Dixie I need to have a property there (checkbox) to allow it to filter by logged user, and so to show the records sold by a specific user.

**Comment by mkhoudary** [comment]
Done..

**Comment by mkhoudary** [comment]
https://github.com/Kademi/client-hinda-dixie/issues/10

**Comment by Uafinder** [comment]
It works!
