### ISSUE TITLE
Reporting components to enable controlling title and icon

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#5368]
SalesTableComponent and OrderHistoryComponent are both used to show a table of data.. they have different look.. the look needs to be unified.

Also there's a need to be able to control their titles and icon.. to enable more control over looks and to reduce the need for customization.

**Comment by mkhoudary** [comment]
Done

**Comment by mkhoudary** [comment]
https://github.com/Kademi/client-hinda-dixie/issues/10

**Comment by Uafinder** [comment]
Looks fine
