### ISSUE TITLE
Sales table component doesn't show preview for data, icon, and label

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5370]
![image](https://user-images.githubusercontent.com/1945230/39252831-2b426938-48af-11e8-9bb8-6ce39b79d100.png)
http://vladtest50web-vladtest50.kademi-ci.co/page1.html
http://vladtest50.admin.kademi-ci.co/pages/vladtest50web/version1/?contenteditor=page1.html

**Comment by bradmac** [comment]
@trungjc when you update this component, its important to avoid duplicating much code between real and editor modes.

**Comment by trungjc** [comment]
![screenshot_12](https://user-images.githubusercontent.com/704946/51957396-177c1d80-247e-11e9-8776-6be0bb37962a.png)

Update setting page to prievew config change

**Comment by trungjc** [comment]
![screenshot_13](https://user-images.githubusercontent.com/704946/51957426-38447300-247e-11e9-9ad3-cddd49f7b7c1.png)

If user not check to "Filter by user", template will throw a exception

`#set( $dataToFilter = $dsm.findRecords($series, $qm.commonStartDate, $qm.commonFinishDate, "periodFrom", true ) )`

Try to change to: 

`#set( $dataToFilter = $dsm.findRecords($series, $qm.commonStartDate, $qm.commonFinishDate, "periodFrom", true ) )`

But It return nothing

**Comment by bradmac** [comment]
> Try to change to: #set( $dataToFilter = $dsm.findRecords($series, "",

@trungjc there is no method where the second argument is a string, so this is incorrect.

Please only use correct methods.

If you see an exception with a correct method then let me know what that exception is and we'll resolve it.

**Comment by anhnt** [comment]
added null check

**Comment by trungjc** [comment]
Updated in v1.4.8

**Comment by Uafinder** [comment]
ok, looks good
