### ISSUE TITLE
"Classic Editor" doesn't open

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#5372]
When I try to open "Classic Editor" to web page it Keeps loading and show me error in console.
http://testaccount012.admin.kademi-ci.co/pages/testaccount012/version1/

![untitled01](https://user-images.githubusercontent.com/26510030/39292499-089b305a-493f-11e8-82dc-265b5363160e.png)

![untitled02](https://user-images.githubusercontent.com/26510030/39292506-0cb287f6-493f-11e8-8f3f-33dcd97881e7.png)

**Comment by bradmac** [comment]
Hi @AlaaKhalaf94 this feature is only retained because it might be needed with old accounts.

It should otherwise not be used.
