### ISSUE TITLE
Can't update the license for old site

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#5375]
For this site : http://scenario.admin.kademi-ci.co

In subscriptions page for the site http://rootorg.admin.kademi-ci.co/subscriptions/3774815/ , I put future date , then save , then click on "Refresh the license information in the site." button

![untitled01](https://user-images.githubusercontent.com/26510030/39303975-bd526a2e-4960-11e8-975f-254c40eb89d1.png)

It lead me to login page with errors in console

![untitled02](https://user-images.githubusercontent.com/26510030/39303779-19ba0f98-4960-11e8-85d0-720075bfcbcc.png)

I try to login to site , it lead me to this page

![untitled03](https://user-images.githubusercontent.com/26510030/39303821-414f5cfc-4960-11e8-8a82-b3ecd07e30b1.png)

**Comment by bradmac** [comment]
Hi @AlaaKhalaf94 yes i know of that issue. There's no easy way to resolve it, so best just to create a new account

**Comment by bradmac** [comment]
Note this only applies to accounts created before the admin-lib update about a month ago

**Comment by bradmac** [comment]
Also, this does not apply to production accounts which were updated at the time.

**Comment by AlaaKhalaf94** [comment]
I got it , Thanks @bradmac
