### ISSUE TITLE
Indexing contact requests fields

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#5379]
Currently, contact requests are being added to the index-able content but aren't collected when indexing, that's because the indexing doesn't consider them during (insert/update).

I need to have this running as a client implementation needs searching in contact forms (MHIAA to check no duplicate address is used).

**Comment by mkhoudary** [comment]
This is done.. @bradmac I'd appreciate it if you deployed to AU anytime

**Comment by Uafinder** [comment]
Ok, i have a custom field in contact request
![image](https://user-images.githubusercontent.com/1945230/39623648-04683f58-4f9f-11e8-8f34-1d5cbf49ce83.png)
http://vladtest51.admin.kademi-ci.co/manageContacts/16045933
Which not display in query
![image](https://user-images.githubusercontent.com/1945230/39623681-14a86122-4f9f-11e8-8bdb-f3a81ff47584.png)
http://vladtest51.admin.kademi-ci.co/queries/Query/#queryBuilderTab-tab

Where i'm wrong?

**Comment by bradmac** [comment]
Change to a group by
```

        private Set<String> getFieldNames(Organisation org) {
            Set<String> names = new HashSet<>();
            List<ContactRequest> contactRequests = ContactRequest.findByOrg(org, null, SessionManager.session());

            for (ContactRequest cr : contactRequests) {
                for (ContactRequestField fields : cr.getFields()) {
                    names.add(fields.getFieldName());
                }
            }

            return names;
        }
```

![image](https://user-images.githubusercontent.com/826458/43582917-0650b8d6-96b2-11e8-895f-5495f8894f07.png)

**Comment by bradmac** [comment]
Done now

```
    public static Set<String> findFieldNames(Organisation org, Session session) {
        Criteria crit = session.createCriteria(ContactRequestField.class);
        crit.setCacheable(true);
        crit.createAlias("contactRequest", "cr");
        crit.createAlias("cr.website", "w");
        crit.add(Restrictions.eq("w.organisation", org));
        crit.setProjection(Projections.groupProperty("fieldName"));
        List l = crit.list();
        Set<String> fieldNames = new HashSet<>();
        if( l != null ) {
            for( Object o : l ) {
                String fieldName = KademiUtils.toString(o);
                if( StringUtils.isNotBlank(fieldName)) {
                    fieldNames.add(fieldName);
                }
            }
        }
        return fieldNames;
    }    
```

**Comment by bradmac** [comment]
After reindexing the fields appear:

![image](https://user-images.githubusercontent.com/826458/44248713-5dcb2080-a240-11e8-8dce-7c39f2798e39.png)

**Comment by Uafinder** [comment]
Looks so
