### ISSUE TITLE
Various improvements to manage website page

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5380]
- replace text with icons
- add new tab for controllers and components
- small improvement to mail server tab SPF settings

**Comment by bradmac** [comment]
- Tab headers now use icons
- Theme is moved to the first tab
![image](https://user-images.githubusercontent.com/826458/39411798-407beda6-4c65-11e8-90e3-ceecce565af3.png)

**Comment by bradmac** [comment]
Templates are moved to the code tab:
![image](https://user-images.githubusercontent.com/826458/39411805-616d5176-4c65-11e8-973d-836301a923b6.png)

**Comment by bradmac** [comment]
Added narrative to the groups tab
![image](https://user-images.githubusercontent.com/826458/39411815-762fdfca-4c65-11e8-862e-2eb2e5498a60.png)

**Comment by bradmac** [comment]
Email tab hides config when there is no custom domain
![image](https://user-images.githubusercontent.com/826458/39411822-858e4042-4c65-11e8-88c5-c49453b67cbf.png)

**Comment by Uafinder** [comment]
looks pretty
