### ISSUE TITLE
Reward store auto-invoicing calculations

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5381]
When submitting purchase orders to clients, calculate as follows
- unit cost = "buy price" = base cost + freight
- tax = buy price x GST

When submitting invoices to clients, calculate as follows
- unit cost = "invoice cost" 
- tax = invoice cost x GST

![image](https://user-images.githubusercontent.com/826458/39343418-d02e8d50-4a30-11e8-8675-a7c82a72e4d1.png)

**Comment by bradmac** [comment]
@Uafinder this is related to
https://github.com/Kademi/kademi-dev/issues/5343
https://github.com/Kademi/kademi-dev/issues/5344

**Comment by Uafinder** [comment]
Calculations looks fine
