### ISSUE TITLE
Support custom fulfilment statuses

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5384]
- add option to select custom statuses on manage cart page
- update hinda app to allow selection of a status to submit order

**Comment by bradmac** [comment]
Added hardcoded fields to the manage carts page. 

Partially integrated with Hinda, not finished yet.

Also need a setting to add custom statuses and generate the list from them

**Comment by bradmac** [comment]
To test..

First, setup the custom statuses in productsapp settings:
![image](https://user-images.githubusercontent.com/826458/39607293-385843f0-4f8e-11e8-84c7-72e024314e3d.png)

Then on the hinda settings page configure for sending the order on status change, and enter the status code:
![image](https://user-images.githubusercontent.com/826458/39607331-854cb0d8-4f8e-11e8-8f9f-ca69e4ade1b8.png)

Then create a new order (you can use admin screen to create an order, or front end reward store)
![image](https://user-images.githubusercontent.com/826458/39607383-d11b7b48-4f8e-11e8-9bfc-effbbcc2ddb2.png)


Then finally mark the order as approved (or other status)
![image](https://user-images.githubusercontent.com/826458/39607376-ba25d528-4f8e-11e8-827e-96c700c35702.png)

**Comment by Uafinder** [comment]
looks fine
