### ISSUE TITLE
improvement on "checkbox all organization"

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#5385]
When I click on checkbox all organization and there is pagination, and do something Ex:"Assign to org type" , this apply just on organizations existing on first page

http://testaccount015.admin.kademi-ci.co/organisations/

**Comment by bradmac** [comment]
That is correct, and that is generally expected by users . For example you can see that Github works the same way.

Its absolutely essential that where there is a checkbox to select items, the action only applies to items which are checked.

On some pages we have a dropdown active which explicitly applies to all matched items. This is always clearly different from the action which applies to checked items

**Comment by AlaaKhalaf94** [comment]
I got it , Thanks @bradmac
