### ISSUE TITLE
Points Leaderboard Component - add ORG option

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#5388]
http://rhipe.admin.kademi.com.au/groupEmails/114487171/#messages-tab

The points leaderboard component needs an option to show ranked ORGs and not just ranked profiles.  The Rhipe program is based on ORGs being rewarded so need a way to send an email out with ranked ORGs.

![image](https://user-images.githubusercontent.com/2201340/39499689-eebed3ea-4df2-11e8-8e15-d76d034afb82.png)

**Comment by bradmac** [comment]
It displays orgs for points buckets configured for orgs.

**Comment by paddyow** [comment]
- Decimal place still showing in email
- The email recipient is showing as a profile, not as their ORG
- Need an option to white label the ORG or profile names i.e. 'Another partner' or 'Another participant'  this should be configurable .  See bottom image of the logged in website.

![image](https://user-images.githubusercontent.com/2201340/39500316-08a79fea-4df7-11e8-8f8b-b15a9f99aeb4.png)

![image](https://user-images.githubusercontent.com/2201340/39500349-37ac2216-4df7-11e8-9454-3cb2be170f2b.png)
