### ISSUE TITLE
Incorrect dislpay of current user in pointsLeaderboardEDM component

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5389]
When i generate this for me I'm added to the end even though I'm not a participant, and my points is very high

![image](https://user-images.githubusercontent.com/826458/39500076-17e818ae-4e06-11e8-82dd-12c8931258f1.png)

**Comment by anhnt** [comment]
@bradmac i have debugged Points.java at `sumPointsByReward` method, it seems that we dont count debit points or expired points. I can see a Points instance which has `completedUsed = true` but still be counted

**Comment by bradmac** [comment]
Yep, thats correct. This is intended to show a leaderboard based on points earned not points balance.

The problem in the screenshot above is that
- if i really did have 2310 points i should be in top position
- but I'm not a participant, so i shouldnt be displayed at all

**Comment by anhnt** [comment]
Just added a check to only show current user if is a participant.

**Comment by Uafinder** [comment]
It works!
