### ISSUE TITLE
pointsLeaderboardEDM component - show participant in bold

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#5390]
For the participant who receives the email, show their rank in bold like we do on the website (see below image).

The participant ORG or Profile name should also render in the leaderboard where the option show user name is set to no.

![image](https://user-images.githubusercontent.com/2201340/39500487-2f1a21d8-4df8-11e8-806c-8513c0d3aae5.png)

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/39617605-86c1dbf2-4faa-11e8-9e5e-3309cc8ec8dd.png)

**Comment by Uafinder** [comment]
It works
