### ISSUE TITLE
Inline content editor shows ckeditor toolbar at very bottom of the page

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#5392]
![image](https://user-images.githubusercontent.com/735555/39503213-d1e0311e-4dee-11e8-9431-f1db7083d5d7.png)

**Comment by anhnt** [comment]
Can be reproduced by editing html asset

**Comment by Uafinder** [comment]
Looks like this way... something definitely broken
![image](https://user-images.githubusercontent.com/1945230/39521681-34533db8-4e18-11e8-8fe5-52079514c62c.png)
http://vladtest50d.admin.kademi-ci.co/asset-manager/new-text?format=text/html

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/39521996-8a179018-4e19-11e8-9b21-f86cde00e1db.png)
http://vladtest50d.admin.kademi-ci.co/asset-manager/new-text?format=text/html

**Comment by Uafinder** [comment]
Ok, find out what is the problem... text editor works
Specific sample component doesn't works, but that's another story.
So, text panel appears and it's located on the top...looks much better that it was on bottom
