### ISSUE TITLE
Customer details page are available to unsigned user

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5394]
customer details page available for anonymous user
Spotted on waterco
http://v19.waterco-waterco.kademi.com.au/custs/11111test-gmail-com/
![image](https://user-images.githubusercontent.com/1945230/39510703-536cd1fc-4df3-11e8-8dd9-8efb48d4ded8.png)

**Comment by bradmac** [comment]
This was due to incorrect permissions setup in the account
