### ISSUE TITLE
Asset manager photo component settings caused bunch of errors in console

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5399]
![image](https://user-images.githubusercontent.com/1945230/39524871-070cfec4-4e23-11e8-934e-af911bb54149.png)
http://vladtest50d.admin.kademi-ci.co/asset-manager/new-text?format=text/html

**Comment by anhnt** [comment]
Looks good atm. @Uafinder please try again

**Comment by Uafinder** [comment]
Same for me
![image](https://user-images.githubusercontent.com/1945230/39622429-d76568c2-4f9a-11e8-8174-99d60eb11d5f.png)
http://vladtest51.admin.kademi-ci.co/asset-manager/new-text?format=text/html

**Comment by anhnt** [comment]
Fixed please try again

**Comment by Uafinder** [comment]
Yup, looks fine at the moment
