### ISSUE TITLE
EDM editor is loading js and css twice

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5403]
edmEditor.html hasnt been updated to work with dependencies being injected

**Comment by bradmac** [comment]
This affected carters. It meant that they couldnt select an image after uploading through the photo component settings.

https://carters.admin.kademi.com.au/groupEmails/115996515/edmeditor?fileName=index.html&useHash=true

**Comment by bradmac** [comment]
Patched into carters to remove the inline css and js. But still a bit of a problem with layout:

![image](https://user-images.githubusercontent.com/826458/39609952-0393c58c-4fa1-11e8-9ffa-7603cbbbcedd.png)

**Comment by Uafinder** [comment]
looks good at the moment
