### ISSUE TITLE
EDM PointLeaderboard component bugs

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5405]
1. Missed participants in the middle of the list, e.g. here
![image](https://user-images.githubusercontent.com/1945230/39621769-8b6fdfee-4f98-11e8-99fe-be5dbf6d1873.png)
![image](https://user-images.githubusercontent.com/1945230/39621787-9ad895e8-4f98-11e8-8891-45be7c6071de.png)
http://vladtest51.admin.kademi-ci.co/points-buckets/points/?dataQuery=&searchGroup=undefined&searchReward=vladtest51web-points&tagId=&reasonCode=&sortfield=num_Points&sortdir=desc
http://vladtest51.admin.kademi-ci.co/groupEmails/16044695/edmeditor?fileName=index.html&useHash=true

2. One user appears in list twice.
![image](https://user-images.githubusercontent.com/1945230/39621970-3f1ad990-4f99-11e8-8e6f-33dbf4cd1440.png)
http://vladtest51.admin.kademi-ci.co/groupEmails/16044695/#sendInfo-tab

**Comment by anhnt** [comment]
Fixed the issue that shows one user twice
![image](https://user-images.githubusercontent.com/735555/39625686-c6a49ea8-4fc8-11e8-8e8c-a054dee2c241.png)


But for the missing participants @bradmac please have a look at our API
MyRewardInfo.getAllMemberPoints

**Comment by Uafinder** [comment]
looks good
