### ISSUE TITLE
KEditor contactus component doesn't have any default look

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5406]
Looks like because of all his parameters inside are empty
![image](https://user-images.githubusercontent.com/1945230/39623026-fe2e05d4-4f9c-11e8-9d82-8a771704afc7.png)
![image](https://user-images.githubusercontent.com/1945230/39623040-096a26c6-4f9d-11e8-86ce-de21438450ec.png)
http://vladtest51.admin.kademi-ci.co/pages/vladtest51web/version1/?contenteditor=page1.html

**Comment by anhnt** [comment]
Looks good with new account http://version1.w1-anhtest41.kademi-ci.co/contenteditor?fileName=index.html
Also locally

**Comment by Uafinder** [comment]
Weird...fresh account is ok
