### ISSUE TITLE
Error while accessing purchase orders page

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5409]
![image](https://user-images.githubusercontent.com/1945230/39628661-6e60980c-4fb2-11e8-998f-3d7787ea3364.png)
http://vladtest51.admin.kademi-ci.co/purchase-orders/

**Comment by bradmac** [comment]
Fixed up a bunch of copy/paste errors when this was copied from invoices.

@anhnt can you fix up this section please? Note we have 3 very similar pages - quotes, invoices and purchase orders.

Ideally we should have a shared JS file for the common stuff.

And please make sure the new item modals and data table initialisation is working

**Comment by anhnt** [comment]
refactoring inprogress..

**Comment by anhnt** [comment]
Done. @Uafinder please have a look at those pages
- Manage quotes
- Manage invoices
- Manage Purchase orders

**Comment by Uafinder** [comment]
Looks good
