### ISSUE TITLE
Purchase orders page questions

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5410]
1. GST is 0
![image](https://user-images.githubusercontent.com/1945230/39628812-e3848e40-4fb2-11e8-9a5e-f86a5ba168dd.png)

2. Tax rate should has % mark in table header i think
http://vladtest51.admin.kademi-ci.co/purchase-orders/16046671/

**Comment by bradmac** [comment]
Should be better now
![image](https://user-images.githubusercontent.com/826458/39678721-ac501d38-51e5-11e8-808d-a10279c56f2d.png)

**Comment by Uafinder** [comment]
Ok, GST is good
