### ISSUE TITLE
Cerrtificates on Waterco looking bad

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5414]
1. Image looks ugly
![image](https://user-images.githubusercontent.com/1945230/39697751-b21cae38-51fa-11e8-8daa-5a8b5cad2323.png)
http://waterco.admin.kademi.com.au/websites/waterco/v18b/programs/CL1/CL2/CL2.1/cert_37504932/certificatePreview.pdf
Looks like it doesn't resize properly

2. Image is not generating for already completed certificates
http://waterco.admin.kademi.com.au/users/5eb8573c-47a3-4c51-be34-d199ae9954c4/certificates/CL2.1_slat-chlorinators_87045373.pdf

**Comment by anhnt** [comment]
For 2 you can delete old cert and generate new one to see if its still not working

**Comment by Uafinder** [comment]
Ok, the second one is good... that's was an old certificate...

**Comment by bradmac** [comment]
The image is 2481 × 3508 pixels

But the spec is  "710 pixels wide by 1004 pixels in height."

**Comment by bradmac** [comment]
The client says that he updated the images and thanked us for the heads up they're too big.
