### ISSUE TITLE
Video and audio component cause error in keditor (assets manager)

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5415]
![image](https://user-images.githubusercontent.com/1945230/39698816-140e0b1a-51ff-11e8-9889-bedb13660ee1.png)
http://vladtest51c.admin.kademi-ci.co/asset-manager/new-text?format=text/html

![image](https://user-images.githubusercontent.com/1945230/39698833-217a4822-51ff-11e8-807a-5f92d73c9e08.png)
http://vladtest51c.admin.kademi-ci.co/asset-manager/new-text?format=text/html

**Comment by anhnt** [comment]
duplicated https://github.com/Kademi/kademi-dev/issues/5401
