### ISSUE TITLE
Timeline should show user membership with more details

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#5417]
ie shows org that user belongs to

![image](https://user-images.githubusercontent.com/735555/39739070-223c543e-52b9-11e8-87c0-d1c5a6e051b8.png)

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/49427990-69365d80-f7d7-11e8-8741-87530910ea3c.png)

**Comment by bradmac** [comment]
@anhnt can you make one change. When the org joined is the account, it should not be displayed. Ie its only meaningful when the org is a sub-org.

**Comment by anhnt** [comment]
Done 
![image](https://user-images.githubusercontent.com/735555/49450164-09f43f80-f80f-11e8-8316-8e29bb121e13.png)

**Comment by Uafinder** [comment]
Looks good
