### ISSUE TITLE
website apps settings persistence causes all apps and libs disabled 

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#5418]
The issue was reported by Lyle for ViridianClub site.

http://viri.admin.kademi.com.au/repositories/viridianclub/version1-fix-variant/

settings.xml has only XeroJ app so all needed apps and libs were disabled. 

Please see this old commit http://viri.admin.kademi.com.au/repositories/viridianclub/commit-116680654/WEB-INF/texteditor?fileName=settings.xml

**Comment by bradmac** [comment]
I couldnt reproduce in that account.

When i enabled an app (alerts) the enablements and settings were correctly copied to settings.xml

**Comment by bradmac** [comment]
OK, will just close for now and re-open if we see it again
