### ISSUE TITLE
Duplicated layout code in promo tiles component

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5423]
See promotionTileComponent.html

Please refactor to minimise duplicated layout code, ping me if you're not sure how.

**Comment by anhnt** [comment]
Done

**Comment by Uafinder** [comment]
Some images are not visible
![image](https://user-images.githubusercontent.com/1945230/40235098-c4bab016-5ab1-11e8-8deb-b1f9baaca8de.png)
http://vladtest51taucstore-vladtest51t.kademi-ci.co/page1.html
http://vladtest51t.admin.kademi-ci.co/rewards/promosqa03/#details-tab

**Comment by anhnt** [comment]
Done

**Comment by anhnt** [comment]
http://k-testkcom2.kademi-ci.co/index.html

**Comment by Uafinder** [comment]
Ok, images showing.
All of there images doesn't lead to appropriate promotion page. They all looped back to current page.
![image](https://user-images.githubusercontent.com/1945230/49586036-b72e9b00-f968-11e8-8312-2092e7d06a99.png)
http://vladtest55eweb-vladtest55e.kademi-ci.co/page1.html

**Comment by bradmac** [comment]
> Also there is a bunch of errors in console while accessing promotion edition page. They all are belongs to a missed images for kcommerce2 thumbs

That should be treated as a seperate issue, its the keditor components for kcom2

**Comment by bradmac** [comment]
> All of there images doesn't lead to appropriate promotion page

@anhnt need to replace $reward.href with a macro parameter

**Comment by anhnt** [comment]
Done

**Comment by Uafinder** [comment]
Looks good
