### ISSUE TITLE
Voucher content editable and support kcode

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#5426]

**Comment by anhnt** [comment]
https://github.com/Kademi/projects/issues/182

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/39866725-fdc62d90-547b-11e8-87a2-9f2a2c2a2824.png)
![image](https://user-images.githubusercontent.com/735555/39866735-08b54042-547c-11e8-87f0-1d8a4a5b3562.png)

@bradmac I cant get voucher expiryDate field. Could you please have a look?

**Comment by bradmac** [comment]
:+1:

**Comment by bradmac** [comment]
> I cant get voucher expiryDate field. Could you please have a look?

Looks good to me. Note that you need to configure the voucher type for expiry, and then it needs to be allocated

![image](https://user-images.githubusercontent.com/826458/39902250-3a8a08e6-5521-11e8-8908-7b3563d72d97.png)

![image](https://user-images.githubusercontent.com/826458/39902261-4bddcde4-5521-11e8-8cdb-abffd7b74eb9.png)

![image](https://user-images.githubusercontent.com/826458/39902275-5e7e8fec-5521-11e8-80e7-589a4e325d6f.png)

**Comment by bradmac** [comment]
Front end result (as html)
![image](https://user-images.githubusercontent.com/826458/39902308-8d7c5e32-5521-11e8-9d89-7655c1faee61.png)

**Comment by Uafinder** [comment]
looks fine

**Comment by bradmac** [comment]
Lots of problems because of trying to use web components when rendering PDFs which dont have the capabilities of actual web browsers (eg javascript)

Using EDM editor is more appropriate and should fix lots of problems.

**Comment by bradmac** [comment]
Moved editors to seperate pages. New UI:

![image](https://user-images.githubusercontent.com/826458/40453713-37de43dc-5f3a-11e8-88c0-64baa9b2e16f.png)

**Comment by Uafinder** [comment]
looks great

**Comment by bradmac** [comment]
Redeeming org state is not working:

https://airnz.admin.kademi.com.au/voucher-type/euro5/17708

![image](https://user-images.githubusercontent.com/826458/41072595-f10614a2-6a52-11e8-8cfd-d4373db16fa7.png)

**Comment by bradmac** [comment]
I've confirmed the field is set on the redeeming org, so should be shown

**Comment by anhnt** [comment]
Please use this code: *|voucher_redeemingOrgAddressState|*
