### ISSUE TITLE
Blog articles cant be edited when SSL is enabled

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5429]
Eg https://insured.admin.kademi.com.au/blogs/its-insured-blog/thinking-of-buying-home-and-content-insurance-read-this/#bodyCopy-tab

![image](https://user-images.githubusercontent.com/826458/39905976-3f5a1e66-5534-11e8-90e6-aec079fcdbee.png)

**Comment by bradmac** [comment]
The fix is to ensure the iframe source is on a non-versioned domain name

**Comment by Uafinder** [comment]
Now i'm seeing this
![image](https://user-images.githubusercontent.com/1945230/40052860-bfe227de-5847-11e8-9329-6969e3804ca7.png)
https://vladtest51h.admin.kademi-ci.co/blogs/blogqa1/article-test/#bodyCopy-tab

**Comment by bradmac** [comment]
OK, this is a bit tricky because
- to view a non published article we must view on a versioned domain name (since its unpublished we dont want it viewable on the main site)
- so it must be on a versioned subdomain of the kademi url for the website, eg version1.mysite.kademi.com.au
- but our wildcard ssl only applies to a single subdomain level, so doesnt apply to version1..

The workaround is
- view on the non-versioned subdomain, eg mysite.kademi.com.au
- append a host parameter so the server thinks its on a versioned site

**Comment by Uafinder** [comment]
Well...now it doesn't show error about SSL, however it doesn't show preview for a content
![image](https://user-images.githubusercontent.com/1945230/40177121-4d038c1c-59e6-11e8-983b-b0a989e21d96.png)
https://vladtest51p.admin.kademi-ci.co/blogs/blogQA2/article-test/#bodyCopy-tab

**Comment by bradmac** [comment]
Please enable force SSL for teh account and this should work correctly now

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/40219284-6117b542-5a7d-11e8-907b-5b45cecde118.png)
This option?
If yes, it looks same to me
https://vladtest51r.admin.kademi-ci.co/blogs/blogqa1/article-test/#bodyCopy-tab

**Comment by bradmac** [comment]
@Uafinder Thats for the website. If users are accessing the admin with https then our expectation is that they have set force ssl on the admin account. Otherwise there's no point using ssl because the next time you type in the address you'll forget to add https and then you'll be on an unencrypted connection

To set the admin to use SSL use this option:
https://vladtest51r.admin.kademi-ci.co/edit/

![image](https://user-images.githubusercontent.com/826458/40276802-5fcf5af0-5c67-11e8-9295-1140336d0f86.png)

**Comment by bradmac** [comment]
I've enabled that option and is appearing correctly now

**Comment by bradmac** [comment]
Note that when force SSL is enabled for a website all pages in the website should be forced to SSL.

This wasnt happening for this website, created a new issue

https://github.com/Kademi/kademi-dev/issues/5455

**Comment by Uafinder** [comment]
Hmmm... thanks for advise about SSL for account, but it's still not work for me :(
![image](https://user-images.githubusercontent.com/1945230/40295035-8e54010e-5ce0-11e8-988d-cd609f6d6f5b.png)
https://vladtest51r.admin.kademi-ci.co/blogs/blogqa1/article-test/#bodyCopy-tab
option "Should force HTTPS?" is on

**Comment by bradmac** [comment]
Looks ok to me:
https://vladtest51r.admin.kademi-ci.co/blogs/blogqa1/article-test/#bodyCopy-tab
![image](https://user-images.githubusercontent.com/826458/40329179-d637a4fa-5d9c-11e8-95ad-4d4a45e93f20.png)

**Comment by bradmac** [comment]
OK, i just checked with Chrome and it fails to show the content because the certificate is invalid and it apparently wont let you accept an invalid cert in an iframe

Just go to the front end site directly to accept the cert, then it will work
https://vladtest51rblogs-vladtest51r.kademi-ci.co/blogs/blogqa1/article-test

**Comment by Uafinder** [comment]
Looks better
