### ISSUE TITLE
Timers set current stage to null

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#5434]
When timers have their current stage field blank.. it sets the lead current stage to null.. this is an undesired behavior..

**Comment by mkhoudary** [comment]
@Uafinder to test this you can put three goal nodes one after the other.. the first one shall set a stage, the 2nd shall not.. when the 3rd is reached, the journey shall stay on the 1st stage and not blank..

**Comment by Uafinder** [comment]
It works!
