### ISSUE TITLE
Add multi-lingual support to components - part 1

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5440]
Please ensure elements within component have the new class and/or data attribute to integrate with multi-lingual support

Add class trans-lookup to identify elements to apply translation to. Eg
```
            <div class="control-group form-group row">
                <label class="control-label col-md-3 trans-lookup" for="nickName">Nickname</label>

                <div class="controls col-md-8">
                    <input type="text" name="nickName" id="nickName" required="true" class="required form-control" value="$!page.profile.nickName" />
                </div>
            </div>
```

For labels, this will automatically use the for attribute as the lookup code. For all other elements add a transcode data attribute. Eg:
```
<h4 class="trans-lookup" data-transcode="profile-heading">$title</h4>
```

For this issue only components required for Bravo project should be updated

**Comment by bradmac** [comment]
Once the attributes are added, refresh the page which displays them while logged in as an admin user and this will automatically create placeholder translation elements:
![image](https://user-images.githubusercontent.com/826458/40035931-75a9bd2e-5858-11e8-97ca-8554baf50b7c.png)

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/40043010-64dab0d0-584d-11e8-83f2-26cac37d89fe.png)

![image](https://user-images.githubusercontent.com/735555/40043027-7015f996-584d-11e8-9b0e-efaea160b1ac.png)

**Comment by anhnt** [comment]
Done

**Comment by anhnt** [comment]
updated loginForm, passwordReset and passwordDoReset components
texts here http://cw.admin.kademi.us/translations/
Copied homepage content to dashboard. Homepage has only login form now

**Comment by bradmac** [comment]
> @bradmac how should we apply translation for element attributes ie input placeholder

I think just add the trans-lookup class to the input and I'll update server side to process the placeholder and title attributes

**Comment by Uafinder** [comment]
Amazing stuff...
You just forget to add translation support for text placeholders for passwordReset and passwordDoReset components
![image](https://user-images.githubusercontent.com/1945230/40922105-03bbcf5a-681a-11e8-9539-c884a2ce87cb.png)
http://vladtest52eaucstore-vladtest52e.kademi-ci.co/page1.html

**Comment by bradmac** [comment]
That should be done now

**Comment by Uafinder** [comment]
looks no...
still doesn't appears on fresh account
http://vladtest52n.admin.kademi-ci.co/translations/
http://vladtest52nweb-vladtest52n.kademi-ci.co/page2.html
Enter your email here text is absent

**Comment by bradmac** [comment]
@Uafinder this issue is only to integrate the multilingual capability with a few specific components:

> updated loginForm, passwordReset and passwordDoReset components

I've created an issue to update all remaining components here:
https://github.com/Kademi/kademi-dev/issues/5563

**Comment by Uafinder** [comment]
i understand that... actually say my screenshot from Password Reset component

**Comment by bradmac** [comment]
Looks like the trans-lookup class hasnt been applied to the input.

@anhnt please make sure you've applied that class to inputs in these components

**Comment by Uafinder** [comment]
Yup, now it looks wonderful
