### ISSUE TITLE
Error while uploading image to assets in vouchers

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5442]
![image](https://user-images.githubusercontent.com/1945230/40050904-87fc5ed0-5841-11e8-9e58-ab2491a47571.png)
http://vladtest51h.admin.kademi-ci.co/voucher-type/vcode01/#voucherContent-tab

I think that this is dedicated somehow to your translation job

**Comment by bradmac** [comment]
Fixed. Requires content-lib 1.3.5

**Comment by Uafinder** [comment]
looks fine now
