### ISSUE TITLE
Points allocation rules to have reason template field

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5444]

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/40095907-7e23b46c-5922-11e8-8d64-9e96ee31234a.png)

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/40095927-8d9f9c26-5922-11e8-97c4-bde358fa8a97.png)

**Comment by Uafinder** [comment]
Ok, it works
But some issues appear... moving to another issue
