### ISSUE TITLE
Create a sales data leaderboard component

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5449]
This component should show a leaderboard based on the sum of sales for participants over a date period.

This should appear much the same as the points leaderboard component

Options should include
- the data series
- similar options as for points leaderboard, ie num users, show name, etc
- either a fixed date range or use common date range (default)

**Comment by anhnt** [comment]
@bradmac please add some API to get leaderboard within SalesDataApp.java. At the moment we only have this method `kpiLeaderboardData`

**Comment by bradmac** [comment]
hey @anhnt I've added salesDataRecord to KCriteriaBuilders so you can write the query yourself in template code.

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/40294403-9f1f771a-5cff-11e8-8cdc-741983bc15ef.png)

**Comment by anhnt** [comment]
Just added support for org base data series leaderboard

**Comment by Uafinder** [comment]
1. Doesn't react on date range component without refresh
http://vladtest51vsales-vladtest51v.kademi-ci.co/page1.html
![image](https://user-images.githubusercontent.com/1945230/40305502-73cb6836-5d03-11e8-9091-e373b28316bf.png)

2. Both start and end data fields are not enterable
![image](https://user-images.githubusercontent.com/1945230/40305641-feee031a-5d03-11e8-8638-e203c0bcc712.png)
nothing appears
http://vladtest51v.admin.kademi-ci.co/pages/vladtest51vsales/version1/?contenteditor=page2.html

**Comment by anhnt** [comment]
Fixed in other issue

**Comment by Uafinder** [comment]
I don't think so...
Fresh account
http://vladtest55aweb-vladtest55a.kademi-ci.co/page2.html
http://vladtest55a.admin.kademi-ci.co/pages/vladtest55aweb/version1/?contenteditor=page2.html
- Missed date range selector in component settings
- date range selector doesn't change data

**Comment by Uafinder** [comment]
Same here
https://github.com/Kademi/kademi-dev/issues/6120

**Comment by anhnt** [comment]
Seems working ok to me

![image](https://user-images.githubusercontent.com/735555/49414713-f1503f00-f7a6-11e8-8958-5546364c95e6.png)

![image](https://user-images.githubusercontent.com/735555/49414746-04fba580-f7a7-11e8-813c-244ab27fca82.png)

**Comment by anhnt** [comment]
>Missed date range selector in component settings

We removed that to use date ranger picker from site for dynamically showing data

**Comment by Uafinder** [comment]
Ok, looks good
