### ISSUE TITLE
Points allocation rules to have reason template field issues

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5452]
When you put Tags field for example to template it gives server error
tag @{record.tags}
![image](https://user-images.githubusercontent.com/1945230/40182829-f94ba4d8-59f4-11e8-8d02-bc8ccf115d14.png)
https://vladtest51p.admin.kademi-ci.co/sales/new-series/sources/source-allocqa01/#general-tab
it will give such picture
![image](https://user-images.githubusercontent.com/1945230/40183000-5f3e2b80-59f5-11e8-9546-393dadc67d59.png)

When description is big it cause error too
I think it's because of field size
ID @{record.id} SKU @{record.productSku} amount @{record.amount} tag @{record.tags}
![image](https://user-images.githubusercontent.com/1945230/40183158-c6353dec-59f5-11e8-9191-1e6d84b81387.png)
https://vladtest51p.admin.kademi-ci.co/sales/new-series/sources/source-allocqa01/#general-tab

**Comment by bradmac** [comment]
Increased column size to to 5000

**Comment by Uafinder** [comment]
Ok, the thing with column size is fixed
But the thing with error while accessing some fields persists
For example for this expressions
tag @{record.tags}
unit @{record.dataSeriesUnits}
name @{record.dataSeriesName}
Following error appears
![image](https://user-images.githubusercontent.com/1945230/40222938-ed3331a8-5a89-11e8-8e22-f7be5c5e0c52.png)
https://vladtest51r.admin.kademi-ci.co/points-buckets/points/

**Comment by bradmac** [comment]
Yes, MVEL expressions throw an error if you refer to properties which are null or dont exist

Note there is no property called "dataSeriesName". You could use 
`@{record.series.name}`

The property "tags" does not exist, but there is a property alled tagsList .. eg @{record.tagsList}

Note that this returns a collection, so you would need a foreach loop to iterate over it to produce tidy output

**Comment by Uafinder** [comment]
It works like a charm...
