### ISSUE TITLE
Support tiled components within keditor container

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#5456]
This should allow adding components to a container section and they will tile across the page, then wrap.

Components should be configurable with bootstrap column widths, eg:
col-lg-3, col-md-4, col-sm-6, col-xs-12

Add an option to containers to center content so we can achieve a layout like this with multiple components in a single container section:
![image](https://user-images.githubusercontent.com/826458/40292055-0aea68ca-5d1d-11e8-90e5-77a448140036.png)

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/40480188-e861a13a-5f77-11e8-9d0b-9809d2259b80.png)

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/40480352-640262ac-5f78-11e8-82b3-6a6c578711bf.png)

**Comment by bradmac** [comment]
We need sensible breakpoints for the cols

Eg here's an example of a 6 col layout on a large screen:
![image](https://user-images.githubusercontent.com/826458/40525649-6c2f3db6-6035-11e8-8713-995d8377e333.png)

And now on a smaller screen:
![image](https://user-images.githubusercontent.com/826458/40525642-6201e08c-6035-11e8-9a09-5d013f4d6934.png)

Please ensure the cols are set like this:
[col-lg-6, col-md-4, col-sm-3 ... etc]
[col-lg-4, col-md-3, col-sm-2 ... etc]
etc

**Comment by bradmac** [comment]
Also, the container layout reverts to non-tiled when i add another component.

**Comment by bradmac** [comment]
And please note this requirement:

> Add an option to containers to center content so we can achieve a layout like this with multiple components in a single container section:

**Comment by bradmac** [comment]
So please make the 3 updates
1) sensible breakpoints
2) prevent tile setting from being lost when a component is added
3) provide an option to centre tiling similar to the screenshot at top

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/40537116-4e2b1e2c-6038-11e8-93c6-8937d4795976.png)

**Comment by Uafinder** [comment]
1. There is no spaces between tiles in keditor
![image](https://user-images.githubusercontent.com/1945230/40542476-fa1e94e4-6028-11e8-9cd3-9c5bc8f1088d.png)
http://vladtest51zzz.admin.kademi-ci.co/pages/vladtest51zzzaucstore/version1/?contenteditor=page1.html

2. Three columns in editor looks by two columns in frontend. Same for other size. Looks like somewhere (-1) appears.
![image](https://user-images.githubusercontent.com/1945230/40543192-f7fbbc3e-602b-11e8-94fe-c659cfd3597d.png)
![image](https://user-images.githubusercontent.com/1945230/40543210-07e9576e-602c-11e8-8818-5a57959fe877.png)
http://vladtest51zzzaucstore-vladtest51zzz.kademi-ci.co/page1.html
http://vladtest51zzzaucstore-vladtest51zzz.kademi-ci.co/page2.html

**Comment by anhnt** [comment]
> Three columns in editor looks by two columns in frontend. Same for other size. Looks like somewhere (-1) appears.

Since you checked at Tile center, when on frontend there is some space between columns, so there is not enough room for 3 columns at the same row

**Comment by bradmac** [comment]
> Since you checked at Tile center, when on frontend there is some space between columns, so there is not enough room for 3 columns at the same row

The editor should correctly show how the content will appear. Spacing should be exactly the same as if using bootstrap styles and components directly, so a 3 col layout should be possible.

**Comment by bradmac** [comment]
I added a black border and a green border on 2 thumb elements to show there is a space between them
That space should not be there, it will completely break the bootstrap layout model.

![image](https://user-images.githubusercontent.com/826458/40570902-efc567fa-60e3-11e8-9db5-15a8bf2c3961.png)

**Comment by Uafinder** [comment]
Looks fine
