### ISSUE TITLE
Create random test data create more data than expected

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5458]
E.g. i tell it to create 200 records, it creates for me a 2840.
![image](https://user-images.githubusercontent.com/1945230/40304494-9e22f3aa-5cff-11e8-9f64-c4739788ab7f.png)
http://vladtest51v.admin.kademi-ci.co/sales/sales-claims/#history-tab

**Comment by bradmac** [comment]
I think it creates the number of records for each user

**Comment by Uafinder** [comment]
ok
