### ISSUE TITLE
Voucher preview on PDF doesn't display images

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5463]
preview as HTML
![image](https://user-images.githubusercontent.com/1945230/40358629-8f1b4a00-5dc8-11e8-9ed2-f1806a9d7b59.png)
preview as PDF
![image](https://user-images.githubusercontent.com/1945230/40358652-a2c4c77a-5dc8-11e8-9643-ee029b9018c3.png)
Two pages as well
https://airnz.admin.kademi.com.au/voucher-type/test/VOUCH-a70a7

**Comment by bradmac** [comment]
This is now using fully qualified URLs so that should fix it. Eg
```
<td class="text-wrapper" style="font-family: Arial, Helvetica, san-serif; font-size: 14px; line-height: 20px; color: #333333;" align="left">
<img src="http://w2-rootorg.loopbackdns.com:8080/assets/25f64b61-ce11-4a52-b01f-0a929ae69ec8" style="display: block; border: 0;" alt="" width="300" height="">
                                    
</td>
```

**Comment by bradmac** [comment]
Please use assets when uploading because the voucher folder doesnt support persisting file content

**Comment by Uafinder** [comment]
Looks better
