### ISSUE TITLE
Disable uploading to the filesystem for vouchers

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5471]
Related: https://github.com/Kademi/kademi-dev/issues/5463

Please disable uploading through the file system, only allow uploading to assets:

![image](https://user-images.githubusercontent.com/826458/40455270-53e7965e-5f40-11e8-9b69-203120e0db2b.png)

This will be a common requirement so please make sure we can re-use it easily

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/40462809-d50464d8-5f3b-11e8-80ab-f31945059d9f.png)

Done

**Comment by Uafinder** [comment]
it works
