### ISSUE TITLE
Journeys firing incorrectly

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5475]
![image](https://user-images.githubusercontent.com/826458/40518944-1dc53bc2-6011-11e8-9b82-2b984cbd33c9.png)

**Comment by bradmac** [comment]
I've added a new option to prevent begin nodes intended for direct usage only from being used by automation to create leads
![image](https://user-images.githubusercontent.com/826458/40519313-08c8f928-6013-11e8-9729-6701f403332a.png)

**Comment by Uafinder** [comment]
Yes, it works like expected
