### ISSUE TITLE
KCom2: Implement product search

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5476]
Have a search input component which will be on the store home page and category pages

Entering text will show a suggestion list like this:
![image](https://user-images.githubusercontent.com/826458/40527165-0e6d9d6c-603f-11e8-941a-6c88fe5e4bda.png)

Counts will be provided for the search term in each category

Clicking on a category + search text will open the category page with that search term entered and display search results. 

The search results will allow refinement by
- changing the search query which will search within the current category
- filter by brand
- filter by attributes, which are discovered from search results

**Comment by bradmac** [comment]
Note that you need to configure attribute names on the reward stores page
![image](https://user-images.githubusercontent.com/826458/40597198-04c2f224-6294-11e8-8d79-c44559996b3c.png)

**Comment by bradmac** [comment]
And you need to use the same attribute names for the ordering options on products
![image](https://user-images.githubusercontent.com/826458/40597209-1ef70e1e-6294-11e8-8487-68a44f8bdbd8.png)

**Comment by bradmac** [comment]
Hey @anhnt can you please finish a couple of things
- improve selection of attributes, currently only allows a single value for a single attribute, but users should be able to select multiple values in multiple attributes
- persistence of selection, if the user reloads a page selected values should show as selected
- implement product results infinite loading (ie pagination by scrolling)

**Comment by anhnt** [comment]
this is done as well

**Comment by anhnt** [comment]
not done yet..

**Comment by bradmac** [comment]
Moved remaining issues here - https://github.com/Kademi/kademi-dev/issues/5634

**Comment by Uafinder** [comment]
1. When filter could not find any product there is no possibility to reset filter or deselect category, which prevents filter to show result
![image](https://user-images.githubusercontent.com/1945230/42326206-29bef3fc-8071-11e8-8245-be6d8d60c44d.png)
e.g. here
http://vladtest53web-vladtest53.kademi-ci.co/vladtest53web-ecomstore/
select 15 MPX and 128 GB and then you will not be able to deselect any of them
http://vladtest53.admin.kademi-ci.co/skus/

2. Filter by price doesn't work
![image](https://user-images.githubusercontent.com/1945230/42326426-c8db3644-8071-11e8-9a2d-3021d8daeb65.png)

**Comment by bradmac** [comment]
Hi @anhnt I just noticed this code in storeDashboard.js
```
    function persistAttributes() {
        var arr = [];
        $('.pointsRangeList a.list-group-item').each(function () {
            if ($(this).hasClass('selected')){
                arr.push($(this).attr('data-attvalue'));
            }
        });
        $.cookie('kcom2att', arr.join(','));
    }
```

I think generally the idea of saving to cookies is a bad idea, it means the user cant just click back to get to what they were on.

Instead, I think this should be changed to just put search parameters into the URI, and use pushState

**Comment by bradmac** [comment]
Done
