### ISSUE TITLE
Adding extra class to nested DIV

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#5485]
When adding a custom class to a nested DIV in Keditor i..e roundedclass

The class renders like the below in the source code i.e. it adds 'background-for' to the class

![image](https://user-images.githubusercontent.com/2201340/40581944-a77b08c6-61a9-11e8-8ba0-d090b2744ed6.png)

![image](https://user-images.githubusercontent.com/2201340/40581940-91278036-61a9-11e8-9298-43d68f678469.png)

**Comment by trungjc** [comment]
Related https://github.com/Kademi/kademi-dev/issues/5487
![screenshot_6](https://user-images.githubusercontent.com/704946/51988768-137ce980-24d8-11e9-9729-70eabdd0a3dd.png)

It was fixed on current version

**Comment by Uafinder** [comment]
Looks good
