### ISSUE TITLE
Cannot add a custom class to DIV with a BG image

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#5487]
If you add a custom class to a DIV e.g. **roundedcorners** it works

If you add a BG image to a DIV it breaks the custom class by mixing up the BG class and custom class **'background-forroundedclass"**

div class="container-bg background-forroundedclass" style="background-color: rgb(24, 70, 143);

**Comment by trungjc** [comment]
![screenshot_6](https://user-images.githubusercontent.com/704946/51989680-1d9fe780-24da-11e9-9193-517d42181660.png)


It was fixed on current version by someone

**Comment by Uafinder** [comment]
Looks good
