### ISSUE TITLE
video MIME type and upload issue

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#5490]
The video file manager is not showing file formats .m4v and .mp4

Also when a video finishes uploading the progress bar does not stop.

![image](https://user-images.githubusercontent.com/2201340/40632582-f919e714-632b-11e8-9f20-34399a0bb666.png)

**Comment by bradmac** [comment]
Problem was the mime types file from another project was overriding our one

I made a config update so we're using a differently named mime types file.

Added m4v to it.

**Comment by bradmac** [comment]
Note that the problem was in the prod environment, so we should verify in prod

**Comment by Uafinder** [comment]
.m4v files still not showing in File Manager
tested on Zoetis and Waterco
http://waterco.admin.kademi.com.au/websites/waterco/v18b/programs/test/c1/m1/#files-tab
page1
https://zoetis.admin.kademi.com.au/websites/zoetis-livestock-reseller/280318version/programs/Test/c1/m3/#files-tab
page1

**Comment by Uafinder** [comment]
looks good now in prod

**Comment by paddyow** [comment]
https://zoetis.admin.kademi.com.au/websites/zoetis-livestock-reseller/280318version/programs/Test/c1/m1/#files-tab

Create a page
Upload a video 
Video uploads and appears in the LHS menu, but the progress bar does not go away
Save video
Upload another video, note progress bar is still there

**Comment by Uafinder** [comment]
Heya...
i closed this issue because of m4v files... they are appears in file manager correctly now
and i created a separate one https://github.com/Kademi/client-zoetis/issues/323
which is about uploading bar not disappear after upload finished
