### ISSUE TITLE
Points allocation sources to support creating points debits

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5495]
Required for https://github.com/Kademi/client-hinda-dixie/issues/70

**Comment by bradmac** [comment]
Example configuration
![image](https://user-images.githubusercontent.com/826458/40689808-0ad006d8-63f8-11e8-9684-800efd09e34b.png)

**Comment by bradmac** [comment]
Example sales data:
![image](https://user-images.githubusercontent.com/826458/40689827-2208e180-63f8-11e8-875b-6ab2d0917a4c.png)

**Comment by bradmac** [comment]
After running points allocation:
![image](https://user-images.githubusercontent.com/826458/40689839-31103318-63f8-11e8-9421-ff39e2678c08.png)

**Comment by bradmac** [comment]
And on profile page:
![image](https://user-images.githubusercontent.com/826458/40689874-636b9956-63f8-11e8-947a-98e97e0ac516.png)

**Comment by bradmac** [comment]
One more thing, we need to set a configurable reason code.

**Comment by bradmac** [comment]
Added reason code
![image](https://user-images.githubusercontent.com/826458/40692661-2e2b2838-6407-11e8-862e-43d74359a02a.png)

**Comment by Uafinder** [comment]
YEs, works like intended
