### ISSUE TITLE
KCom2: Checkout workflow - ecomCheckoutFormComponent

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5497]
Please update the checkout components to have the following screenflow

1. User enters email address and clicks Next
2. Check for a matching profile (with a set password). If a user (with a password) is found just show a password input which will be used for login. Otherwise show fields for firstname, surname and password to create a user. User clicks Next.
3. Form appears asking for shipping address. User clicks Next, cart is updated with the address information
4. Show shipping options, using PriceManager.availableShippingProviders. When user selects a shipping option this should be saved on the Cart and the checkout items refreshed to show the shipping cost. User clicks Next
5. Payment options are shown. Use can select a payment provider to see the form for that provider. User clicks "Purchase now" and the whole payment transaction is submitted
6. The user should then be taken to a new page to show appropriate post checkout content (covered in another issue)

![image](https://user-images.githubusercontent.com/826458/40699703-0624ecfc-642a-11e8-800e-375a4803d685.png)

**Comment by bradmac** [comment]
Please remove the "Skip login" button. The email field is required regardless of whether the user is logging in, registering or doing a plain checkout
![image](https://user-images.githubusercontent.com/826458/40871175-df19dfa6-668a-11e8-88f5-451b30a6a856.png)

**Comment by bradmac** [comment]
This error message is incorrect:
![image](https://user-images.githubusercontent.com/826458/40871176-064f62d0-668b-11e8-93e7-3da38c7ec45a.png)

See the requirement in step2:

> Check for a matching profile (with a set password). If a user (with a password) is found just show a password input which will be used for login. Otherwise show fields for firstname, surname and password to create a user. User clicks Next.

If the email address does not match an existing user we allow them to register or to proceed without registering

**Comment by bradmac** [comment]
Country needs to be a typeahead field with the standard country list:
![image](https://user-images.githubusercontent.com/826458/40871208-76b8329a-668b-11e8-93b2-18f94dfebeff.png)

The value posted to the server should be the 2 character country code

**Comment by bradmac** [comment]
Hey @anhnt note that you cant get the shipping providers until the shipping address has been saved. Thats because available shipping options depend on where the item is being shipped to.

This is why we need the steps in the order listed on this issue.

So when the user clicks Next after entering the address this needs to POST to the server and update the cart. You then need to reload the shipping providers panel to get available providers.

**Comment by bradmac** [comment]
Make sure the payment step has a back button like other steps
![image](https://user-images.githubusercontent.com/826458/40871720-f6e57294-6694-11e8-85dd-2420f3beb6e0.png)

**Comment by bradmac** [comment]
For some reason the inputs on the final payment form (when Manual Payments app is enabled) are all disabled:
![image](https://user-images.githubusercontent.com/826458/40871737-783bc85c-6695-11e8-9052-f671a55164e1.png)

**Comment by bradmac** [comment]
Shipping selection will  usually change the price. So when the user clicks next on the shipping panel immediately POST that to the server to update the cart, and then reload the checkout items list.

**Comment by bradmac** [comment]
OK, so please resolve the 7 issues above and ping me with any questions

**Comment by bradmac** [comment]
Please make country field pre-display the value on the cart:
![image](https://user-images.githubusercontent.com/826458/40955953-9f8fa4de-68e1-11e8-8c6e-32679b28be8e.png)

**Comment by bradmac** [comment]
Tax and freight calcs are now being applied when changing address and shipping provider info:
![image](https://user-images.githubusercontent.com/826458/40955994-d67193ae-68e1-11e8-85ad-51747d63d214.png)

See example config here- https://github.com/Kademi/kademi-dev/issues/5520

**Comment by bradmac** [comment]
When there is no image selected for a SKU, show the first image from the base product if there are any
![image](https://user-images.githubusercontent.com/826458/40956123-a1ee051c-68e2-11e8-8da5-c799b93fe980.png)

```
                    <div class="col-sm-3 item-photo">
                        #set ($photo = "/theme/img/photo_holder.png")
                        #if( $item.productSku.imageHash )
                            #set ($photo = "/_hashes/files/$item.productSku.imageHash")
                        #else
                            <!-- todo -->
                        #end
                        <div style="background-image: url($photo)"></div>
                    </div>
```

**Comment by bradmac** [comment]
Fix alignment of price and remove item X
![image](https://user-images.githubusercontent.com/826458/40956142-cd2c6340-68e2-11e8-84e6-ba1362f27011.png)

**Comment by Uafinder** [comment]
Ok,
For example we have an existed user
He added some item to cart without login and trying to checkout
![image](https://user-images.githubusercontent.com/1945230/46957493-630de580-d0a0-11e8-95be-f68532f8098b.png)

It gives me a possibility to create account with that email, but it's already existed
![image](https://user-images.githubusercontent.com/1945230/46957542-7ae56980-d0a0-11e8-9798-a47fe7573cc4.png)

Going forward
Click on skip creating account
![image](https://user-images.githubusercontent.com/1945230/46957602-8f296680-d0a0-11e8-9464-37b609286e08.png)
after entering address push next
On the shipping provider click Previous
And you will get this weird Enter your password window
![image](https://user-images.githubusercontent.com/1945230/46957668-b4b67000-d0a0-11e8-9b16-037c17ba1887.png)
http://vladtest54bweb-vladtest54b.kademi-ci.co/vladtest54bweb-ecomstore/cart

**Comment by Uafinder** [comment]
Looks good now... we should raise another issues in case of some bugs
