### ISSUE TITLE
Ability to add a City to

### ISSUE THREAD

**Issue by faithtek** [Kademi/kademi-dev#5498]
Don't know how to reference this. There are several places that lack the ability to add a City to the address. Most specifically, the Organisation Detail Page and through-out Ordering.

**Comment by bradmac** [comment]
There's a "city" property on the Cart object so just include that in your custom checkout form:

I can see this in devsite01
```
<div class="form-group">
                    <div class="col-md-12">
                        <input name="addressCity" class="form-control required" required="required" value="" placeholder="City" type="text">
                    </div>
                </div>
```

but just change to .. 
```
name="city"
```

**Comment by faithtek** [comment]
It doesn't seem to follow the order. When the shopping cart is submitted and then enters the orders list from the admin panel, the City that was submitted with the shopping cart is not there. The City Field is blank in the order details.
![image1](https://user-images.githubusercontent.com/7914822/40701233-2acf9ed2-63ab-11e8-86cd-dfd3bdc90e25.jpg)
