### ISSUE TITLE
Bugs in "content type" page

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#5499]
When add new Field in content type , the field added , but popup doesn't close
That's happend also when add new Views
http://testaccount023.admin.kademi-ci.co/content-types/myType/

![untitled01](https://user-images.githubusercontent.com/26510030/40704323-6c42fedc-63f0-11e8-9ece-63f3e46b844c.png)

And I can't edit the field

**Comment by bradmac** [comment]
This is a feature, it makes it faster to add many fields :)

Otherwise the user would have to re-open the form for every field which I've found to be tedious

**Comment by AlaaKhalaf94** [comment]
Thanks @bradmac , This is obvious for adding fields, but what about editing the field?

**Comment by bradmac** [comment]
Yep, it allows the user to make save changes multiple times without having to reopen the form each time
