### ISSUE TITLE
Improvements to show parent/child information of organisations

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5505]

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/40823760-b0f4f996-65c5-11e8-8d1a-d2c7848628b3.png)

![image](https://user-images.githubusercontent.com/826458/40823783-c4c293de-65c5-11e8-8b25-db9960437d95.png)

**Comment by Uafinder** [comment]
it works
