### ISSUE TITLE
Hinda Order Approval

### ISSUE THREAD

**Issue by faithtek** [Kademi/kademi-dev#5508]
Sent an Order to Hinda and Received some feedback from Hinda:

When a Hinda Order is Approved and is then transferred to Hinda, Hinda receives State data in the City field and City data in the State field. Please check the Hinda Order Submission information and confirm that the correct Kademi Data Fields are being sent in the correct Hinda Order API positions. Specifically check the First Name, SurName, Phone, Email, Address, Address2, City, State, and Post Code fields. But please check all other fields as well.

**Comment by faithtek** [comment]
This is still not working. What ever we have to do we NEED to get this fixed as soon as we can.

**Comment by bradmac** [comment]
OK, will investigtate

**Comment by bradmac** [comment]
I've put through a test and captured the request sent to Hinda:

```
[<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"><SOAP-ENV:Header/><SOAP-ENV:Body><ns2:PlaceOrder xmlns:ns2="www.hinda.com/client/services/catalog"><ns2:request><ns2:AccountNumber>15291</ns2:AccountNumber><ns2:ShipToAddress><ns2:Line1>line1</ns2:Line1><ns2:Line2>line2</ns2:Line2>

<ns2:City>Atlanta</ns2:City>
<ns2:State>Georgia</ns2:State>

<ns2:PostalCode>12345</ns2:PostalCode><ns2:Country>US</ns2:Country><ns2:IsDefault>false</ns2:IsDefault></ns2:ShipToAddress><ns2:ShipToEmail>brad@kademi.co</ns2:ShipToEmail><ns2:ShipToPhoneNumber>12312312x</ns2:ShipToPhoneNumber><ns2:ShipToFirstName>brad</ns2:ShipToFirstName><ns2:ShipToLastName>Re: brad McEvoy</ns2:ShipToLastName><ns2:ClientOrderNumber>48892519</ns2:ClientOrderNumber><ns2:InvoiceNote>test</ns2:InvoiceNote><ns2:OrderLines><ns2:OrderLine><ns2:ProductNumber>HN76182</ns2:ProductNumber><ns2:Quantity>1</ns2:Quantity><ns2:ClientOrderLineNumber>48892520</ns2:ClientOrderLineNumber><ns2:OrderLineCustomProperties/></ns2:OrderLine></ns2:OrderLines></ns2:request></ns2:PlaceOrder></SOAP-ENV:Body></SOAP-ENV:Envelope>]
```

**Comment by bradmac** [comment]
Note that the City and State appear to correctly match the appropriate fields on the order:

![image](https://user-images.githubusercontent.com/826458/41064597-1f5a6830-6a30-11e8-9464-08e3b51188b6.png)
