### ISSUE TITLE
select all products

### ISSUE THREAD

**Issue by mamun4343** [Kademi/kademi-dev#551]
when we have a lot of  products  , it would be good if we have a select all button in stor.  

plz check img

![untitled](https://cloud.githubusercontent.com/assets/3419573/8868593/2f6e86f8-31fc-11e5-983c-52761a16f404.png)

**Comment by tuzzmaniandevil** [comment]
Duplicate of https://github.com/Kademi/kademi-dev/issues/510 Closing...
