### ISSUE TITLE
Admin dashboard reward points gadget error

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#5513]
When I open an admin dashboard with a reward points gadget, a JS error appears.

Please check Dixie's dashboard:
http://dixie.admin.kademi.us

**Comment by mkhoudary** [comment]
https://github.com/Kademi/client-hinda-dixie/issues/66

**Comment by bradmac** [comment]
Closing as duplicate of this
https://github.com/Kademi/kademi-dev/issues/5528
