### ISSUE TITLE
Merge profiles feature

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5531]
Needs to allow selecting a group of profiles, and selecting one as the destination
- move emails, leads, modules, etc from source profiles to destination
- move memberships, unless the destination has a membership with the same group + org, in which case copy fields across
- if the destination has a password leave it, otherwise move the first credential from the sources

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/41079349-90bd51dc-6a75-11e8-8527-1a479c202d76.png)

![image](https://user-images.githubusercontent.com/826458/41079360-a22eebe2-6a75-11e8-84fd-65511be8644c.png)

**Comment by bradmac** [comment]
hi @Uafinder i dont quite understand.

But the expected behaviour is
- any field on the destination profile which is not blank should not change
- any field on the source profile which is not blank should be written into the same field in the destination, if that field is blank in the destination

Note that this applies to basic fields like nickname, firstname, etc. And it also applies to custom fields on group memberships (eg DixieID)

**Comment by Uafinder** [comment]
userqa01
![image](https://user-images.githubusercontent.com/1945230/41148279-46223a06-6b11-11e8-83a5-21f1da386f7c.png)
userqa02
![image](https://user-images.githubusercontent.com/1945230/41148308-5cb52fe4-6b11-11e8-97a9-231c9a0b5bab.png)

Merging
![image](https://user-images.githubusercontent.com/1945230/41148469-bd1ccaf4-6b11-11e8-88d8-352cf709e403.png)

Result
![image](https://user-images.githubusercontent.com/1945230/41148562-ec56e912-6b11-11e8-8761-3fd2a8ad2051.png)

http://vladtest52l.admin.kademi-ci.co/manageUsers/16577016/#general-tab

**Comment by bradmac** [comment]
Fixed. Looks like issue applied only to nickname field

**Comment by Uafinder** [comment]
fine now
