### ISSUE TITLE
Reading request payloads in JS controller

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#5532]
As a requirement for GRS, the callbacks they need from us shall read JSON from request payload, after I've checked the parameters and the http.request, I couldn't find a way to reach for the request raw body.. so need to implement that..

**Comment by bradmac** [comment]
I'm pretty sure we're already doing this, eg wes wrote a server side JS service to pull in json frmo a travel deals site

**Comment by mkhoudary** [comment]
@bradmac the service I am intending to create is a controller to be pulled by a third party, the Json the 3rd party will be sending will be on the **request** payloads, the response can be easily made as Json, and reading response is easy as well if I am requesting. I will check the Travel Deals app anyway.

**Comment by mkhoudary** [comment]
Done
