### ISSUE TITLE
Filter button works same as delete button

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5533]
![image](https://user-images.githubusercontent.com/1945230/41104065-3e031898-6a73-11e8-9108-165dcdfb6e27.png)
http://vladtest52k.admin.kademi-ci.co/funnels/first-journey/version1/leads/

**Comment by bradmac** [comment]
Its just incorrect cosmetics.

To use the filter feature click the dropdown and select a group

**Comment by bradmac** [comment]
Fixed

**Comment by Uafinder** [comment]
It works
