### ISSUE TITLE
Bulk operations failed on manage users page

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5534]
![image](https://user-images.githubusercontent.com/1945230/41104901-262422e2-6a75-11e8-8cc4-33540723150e.png)
http://vladtest52k.admin.kademi-ci.co/manageUsers/

Bulk add to group and bulk delete

**Comment by bradmac** [comment]
Fixed

**Comment by Uafinder** [comment]
Bulk delete is fixed, bulk adding to a group still failed
![image](https://user-images.githubusercontent.com/1945230/41146668-b64dfbb2-6b0c-11e8-87ac-506946dbcf2a.png)
http://vladtest52l.admin.kademi-ci.co/manageUsers/?q=&g&enabled=true

**Comment by bradmac** [comment]
I just tested on your acount in CI and add to group worked.

If you still see the problem please let me know which group you're adding to, as its likely to be related to the configuration of the gruop

**Comment by Uafinder** [comment]
Well, looks good on fresh account
