### ISSUE TITLE
Top10 points component shows nothing

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5535]
points bucket
http://vladtest52k.admin.kademi-ci.co/points-buckets/points/
![image](https://user-images.githubusercontent.com/1945230/41105389-4e5134d4-6a76-11e8-9707-2f5e259f9be9.png)
page to edit
http://vladtest52k.admin.kademi-ci.co/pages/vladtest52kweb2/version1/?contenteditor=page1.html
Frontend
http://vladtest52kweb2-vladtest52k.kademi-ci.co/page1.html

Looks like after fix
https://github.com/Kademi/client-hinda-dixie/issues/103

**Comment by Uafinder** [comment]
Still doesn't work
http://vladtest52l.admin.kademi-ci.co/points-buckets/points/
http://vladtest52lweb-vladtest52l.kademi-ci.co/page1.html

**Comment by anhnt** [comment]
its showing now by adding reporting access role

**Comment by Uafinder** [comment]
ok, it's showing, but without decimals
