### ISSUE TITLE
query table component should use table title for csv file name

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#5538]
at the moment its default to data.csv

**Comment by anhnt** [comment]
https://github.com/Kademi/client-hinda-dixie/issues/39

**Comment by anhnt** [comment]
please test on dixie as i just published latest version there

**Comment by Uafinder** [comment]
It looks pretty in Chrome and FF, but in IE table title was not being used
![image](https://user-images.githubusercontent.com/1945230/41151164-a451cf72-6b18-11e8-8952-523cd63bb522.png)
Is it worth to fix?
https://www.tdgrewards.com/reports/

**Comment by anhnt** [comment]
I think we can fix it later as IE is getting out of date

**Comment by bradmac** [comment]
I think its ok if this works correctly with modern browsers

**Comment by Uafinder** [comment]
ok, closing
