### ISSUE TITLE
new user registered to website got same userId as old user

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#5542]
https://zoetis.admin.kademi.com.au/manageUsers/119180347/#general-tab
https://zoetis.admin.kademi.com.au/manageUsers/119722775/#general-tab

At the time i checked both users have same userId: tim

Katie might changed that id to help they login and use the site but please try reproducing this issue on zoetis and QA so we can fix the problem

**Comment by Uafinder** [comment]
reproduced on Zoetis...
go to registration
http://www.thefeedzoetis.com.au/register.html
register user with name and surname "tim" and with some different email "timqa001" for example
the new user will gain userid "tim" and instantly gain access to another profile with same userid
https://zoetis.admin.kademi.com.au/manageUsers/119882853/#general-tab
note, that i will change userid to avoid real user influence
![image](https://user-images.githubusercontent.com/1945230/41275103-7a5de0bc-6e28-11e8-9e28-c437849910b2.png)

**Comment by bradmac** [comment]
@Uafinder Have you reproduced this in a standard Kademi account? Or is this a zoetis specific problem?

**Comment by Uafinder** [comment]
Looks like a standard account problem.
Reproduced it here
http://vladtest52mweb_vladtest52m.kademi-ci.co/participants/signup
![image](https://user-images.githubusercontent.com/1945230/41349285-1c3f01a0-6f18-11e8-851d-074dc0b879c0.png)
This user
http://vladtest52m.admin.kademi-ci.co/manageUsers/16782943/#general-tab
This user
http://vladtest52m.admin.kademi-ci.co/manageUsers/16782950/#summary-tab

**Comment by bradmac** [comment]
:+1:

**Comment by bradmac** [comment]
Fixed

**Comment by Uafinder** [comment]
tested on the custom component
now need to test with basic register template, but there is a bug with it
https://github.com/Kademi/kademi-dev/issues/5560

**Comment by bradmac** [comment]
that was just a problem with a lib, should be ok now

**Comment by Uafinder** [comment]
Yeah, looks fine on fresh account
