### ISSUE TITLE
Kcom2: link to a product incorrect, it's just reload store page

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5545]
![image](https://user-images.githubusercontent.com/1945230/41153729-4e4ee706-6b20-11e8-9d45-2889ad39b8ea.png)
http://vladtest52lweb2-vladtest52l.kademi-ci.co/vladtest52lweb2-ecomstore/

When you click on some product or shopping cart it just reload a page and doesn't transfer you to a product page

**Comment by Uafinder** [comment]
Need this to test further KComm2

**Comment by bradmac** [comment]
Its not using the latest libs..
![image](https://user-images.githubusercontent.com/826458/42297256-4fc9c58c-8052-11e8-8108-605bdc6f6ce5.png)

**Comment by bradmac** [comment]
However there was a problem with the component, resolved

Please ensure you use the latest KCommerce2 1.0.1, i havent republished as a new version

**Comment by bradmac** [comment]
And note that this problem was occuring when the webname field wasnt set.

ECom sites will always use webnames for SEO purposes, so that should be the primary test case

**Comment by Uafinder** [comment]
it works
thanks for info
