### ISSUE TITLE
Top10 points balance component doesn't show decimal values for points

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5546]
![image](https://user-images.githubusercontent.com/1945230/41153819-9ae169ea-6b20-11e8-87cf-8dfcfd8a00db.png)
http://vladtest52lweb-vladtest52l.kademi-ci.co/page1.html

![image](https://user-images.githubusercontent.com/1945230/41153832-a5485f38-6b20-11e8-9c28-e4d19179bddc.png)
http://vladtest52l.admin.kademi-ci.co/points-buckets/points/

**Comment by Uafinder** [comment]
https://github.com/Kademi/client-hinda-dixie/issues/103

**Comment by anhnt** [comment]
@bradmac this top balance component is using api that pulls data from ES but the needed field is long type. Could you please help me update it

```
"points": {"properties": {"points-1":     {
        "type": "long",
        "store": true
    }}},

**Comment by anhnt** [comment]
Done

**Comment by anhnt** [comment]
@Uafinder Note that you have to reindex profile and org to see the change

**Comment by Uafinder** [comment]
Heya...
I've done a full rebuild, re-sync, create new account, create new profiles, award some points, re-index...
But i can't see any data in component...
http://vladtest52m.admin.kademi-ci.co/points-buckets/points/
http://vladtest52maucstore-vladtest52m.kademi-ci.co/page1.html

**Comment by Uafinder** [comment]
ok, it works
