### ISSUE TITLE
Signup failed - error in console appears

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5551]
![image](https://user-images.githubusercontent.com/1945230/41274376-d24ea3ea-6e25-11e8-9a4a-73a868128807.png)
http://vladtest52m.admin.kademi-ci.co/pages/vladtest52mweb/version1/
http://vladtest52mweb_vladtest52m.kademi-ci.co/participants/signup

**Comment by anhnt** [comment]
Done, just updated to use latest KSignup

**Comment by Uafinder** [comment]
IT works!
