### ISSUE TITLE
Signup (register) template bad

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5560]
![image](https://user-images.githubusercontent.com/1945230/41412136-b7c2d9f6-6fe7-11e8-9cbf-a3aecd46521d.png)
http://vladtest52n.admin.kademi-ci.co/pages/vladtest52nweb/version1/
http://vladtest52n.admin.kademi-ci.co/websites/vladtest52nweb/version1?editTemplate=theme/apps/signup/register
![image](https://user-images.githubusercontent.com/1945230/41412160-c99bf46e-6fe7-11e8-8741-ed6ce7432cde.png)

**Comment by bradmac** [comment]
Should be fixed now, signup-lib was not loaded

**Comment by Uafinder** [comment]
Yeah, looks fine on fresh account
