### ISSUE TITLE
Signup component doesn't have options to enable name|surname fields

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5562]
![image](https://user-images.githubusercontent.com/1945230/41418619-bedbe91a-6ff8-11e8-9493-364189c835bc.png)
http://vladtest52n.admin.kademi-ci.co/pages/vladtest52nweb/version1/?contenteditor=page1.html
http://vladtest52n.admin.kademi-ci.co/pages/vladtest52nweb/version1/

**Comment by bradmac** [comment]
signup-lib is corrupt

http://vladtest52n.admin.kademi-ci.co/repositories/signup-lib/1.2.2/

**Comment by bradmac** [comment]
I've reloaded it in rootorg, and patched the fixed version into this account

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/41437911-d88713e0-7079-11e8-8661-d24dd57cdc8b.png)

**Comment by Uafinder** [comment]
Yeah, looks fine on fresh account
