### ISSUE TITLE
formatter.endOfDay needs depending on timezone

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#5566]
```
var thirtyDaysAgo = formatter.addDays(now, -30);
    var yesterday = formatter.addDays(now, -1);
    var toDate = formatter.endofDay(yesterday);
    var fromDate = formatter.startOfDay(thirtyDaysAgo);
```
Note that timezone in this case is Chicago (UTC -5):

from date {} : Wed May 16 05:00:00 UTC 2018 ~ Wed, 16 May 2018 00:00:00 2018 Chicago time
to date {} : Thu Jun 14 23:59:59 UTC 2018 ~ Thu, 14 Jun 2018 18:59:59 2018 Chicago time

**Comment by bradmac** [comment]
Done
