### ISSUE TITLE
Websocket is closed and then attempt to reconnect when sent a message

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#5569]
![image](https://user-images.githubusercontent.com/735555/41525535-8c367eb0-730b-11e8-8940-660850835bf1.png)

This occurs each time user sent a message and admin cant see the msg

**Comment by anhnt** [comment]
Socket messages bounces back 

![image](https://user-images.githubusercontent.com/735555/41525818-7414f874-730c-11e8-8e2b-d8fd29e5a936.png)

**Comment by bradmac** [comment]
:+1:

**Comment by bradmac** [comment]
@Uafinder can this be closed now that KChat is working?

**Comment by Uafinder** [comment]
Yes, it works
