### ISSUE TITLE
Possible problem with order status in Hinda integration

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5573]
This is an example of an order placed through the Hinda API, but where no shipping/tracking information has been added to the order:
http://owenscorningmemphis.admin.kademi.us/shopping-carts/48871235/#items-tab

This should be added automatically from the OrderStatusProcessor

Please investigate and resolve if possible

**Comment by tuzzmaniandevil** [comment]
The `OrdersStatusProcessor` get's a date of `now` which get's sent to the `OrderStatusProcessor` which is used to get orders with a filter of `ordersSinceDate`

So it will never actually fetch any orders because no orders will be included in the filter.

**Comment by tuzzmaniandevil** [comment]
Might be a good idea to store the timestamp of the last time the process ran for an org and use that instead to ensure orders are always updated.

@bradmac Thoughts?

**Comment by bradmac** [comment]
Yep, sounds good. Make it so!

**Comment by tuzzmaniandevil** [comment]
https://github.com/Kademi/client-hinda/pull/26

**Comment by tuzzmaniandevil** [comment]
This fix will work for any future orders, But not for any current orders

**Comment by bradmac** [comment]
I'm just building a deploy for CI, then please run a couple of tests through CI so we can confirm that its being processed.

**Comment by bradmac** [comment]
@tuzzmaniandevil can you please show me a couple of orders which have a status from Hinda?

**Comment by tuzzmaniandevil** [comment]
Is there a test account I can use?

**Comment by bradmac** [comment]
Use the hinda credentials here:
http://safetydemo.admin.kademi.us/hinda-settings/

You can use them with any account you have access to in CI

**Comment by tuzzmaniandevil** [comment]
@bradmac Can you deploy https://github.com/Kademi/client-hinda/pull/27 to CI, please?

Discovered a timezone issue :-)

**Comment by bradmac** [comment]
Running the build now, up in 5

**Comment by bradmac** [comment]
@tuzzmaniandevil can you please look into this? The client has reported that its still not working, and there is no change.

**Comment by tuzzmaniandevil** [comment]
https://github.com/Kademi/kademi-platform/pull/17
https://github.com/Kademi/client-hinda/pull/28

**Comment by tuzzmaniandevil** [comment]
@bradmac Please let me know when CI is updated :-)

**Comment by tuzzmaniandevil** [comment]
Sent 2 orders to Hinda, Please can you get them to update the status?
http://westesthinda.admin.kademi-ci.co/shopping-carts/16873938/
http://westesthinda.admin.kademi-ci.co/shopping-carts/17003719/

a side note, I discovered a bug, Hinda requires an address field "City" but the checkout form doesn't have a city field.

**Comment by bradmac** [comment]
Have sent to Hinda and asked them to update the status of those orders

**Comment by bradmac** [comment]
Havent had any update from Hinda yet

**Comment by bradmac** [comment]
Seems to be resolved now
