### ISSUE TITLE
importing lead to timer goal node , Ignores the creation date

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#5574]
In this journey : http://moduleexpirysample.admin.kademi-ci.co/funnels/module-expiry-reminders/version1/#journeyBuilder-tab I import lead to timer goal node "Wait for 18 days" its timeout is 18 days : http://moduleexpirysample.admin.kademi-ci.co/leads/16802532/#information-tab

According to the date of creation , It should wait only for 8 days

![capture1](https://user-images.githubusercontent.com/26510030/41660425-a6e2e8da-74a4-11e8-8780-848c51547f42.PNG)

**Comment by bradmac** [comment]
Goal timers are relative to the time they're entered, not the creation date of the journey

If you want to make a timer relative to the journey creation date you need to use this field:
![image](https://user-images.githubusercontent.com/826458/41685180-c4d4d634-7533-11e8-91bb-9ef481d999b7.png)

**Comment by AlaaKhalaf94** [comment]
This worked
