### ISSUE TITLE
Manage user data tab column headers messed up

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5576]
![image](https://user-images.githubusercontent.com/1945230/41663046-3ab2b31e-74ab-11e8-8545-8c6c895d9796.png)
http://vladtest52s.admin.kademi-ci.co/manageUsers/16800959/#salesAppTab-tab

Header for SKU column says Amount and vice versa

**Comment by bradmac** [comment]
Done

**Comment by Uafinder** [comment]
It works
