### ISSUE TITLE
Start journey question

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5580]
Is there should be a possibility to trigger journey for one profile multiple times?
![image](https://user-images.githubusercontent.com/1945230/41663848-0a8c1e12-74ad-11e8-8bcb-da62f1b71024.png)
http://vladtest52s.admin.kademi-ci.co/manageUsers/16801856/#funnelsTab-tab

**Comment by bradmac** [comment]
Depends on this setting:
![image](https://user-images.githubusercontent.com/826458/41684184-ddcaee88-7530-11e8-8ba7-8a67eb573b70.png)

**Comment by Uafinder** [comment]
yup, works like expected
