### ISSUE TITLE
Option Selection on Store Start Page

### ISSUE THREAD

**Issue by faithtek** [Kademi/kademi-dev#5585]
http://devsite01-asrdev.kademi.us/general-1/

For those items/products that have options:

- How do add options to this page for those items?
- Force a user to select one of the options if they click on the "Add To Shopping Cart"
- Also, Force the selection of an option from Details Page (http://devsite01-asrdev.kademi.us/general-1/202/257/258/16669711/
- Once an item is in the shopping cart, double check the items for options, if an item does have an option, don't let a user complete the redemption until they select an option

**Comment by bradmac** [comment]
You need to enable inventory control in reward store settings:
http://asrdev.admin.kademi.us/websites/devsite01/version1/#panel_apps-tab

Also be sure to select an inventory location:
![image](https://user-images.githubusercontent.com/826458/41757984-a4c1cab2-7639-11e8-9cb2-a893f8a7d215.png)

This forces the site to use SKUs, which requires a selection.

**Comment by bradmac** [comment]
Note that this checks for availability, and if the product is not available (the one above isnt) you'll see this at checkout:
![image](https://user-images.githubusercontent.com/826458/41758032-f2da395a-7639-11e8-8b25-2149928feed1.png)

**Comment by faithtek** [comment]
Why does Product SKU's show there being 10,423 products but the Inventory Control only has 2,930 products? Where/when does this sync? Will Inventory and Product SKU's ever match? Are they supposed to?

**Comment by bradmac** [comment]
> Where/when does this sync? 

Syncing occurs each day, you can see sync status on the hinda settings page

![image](https://user-images.githubusercontent.com/826458/41764476-588d47c2-7655-11e8-86e1-f0c48cc722af.png)

> Will Inventory and Product SKU's ever match? Are they supposed to?

All products should have at least one related SKU, which you can see from the SKU's tab, for example:
http://asrdev.admin.kademi.us/products/18978359/#skus-tab
![image](https://user-images.githubusercontent.com/826458/41764543-885279e6-7655-11e8-817b-70bbbfc53a9b.png)

> Why does Product SKU's show there being 10,423 products but the Inventory Control only has 2,930 

I dont know what you mean, where do you see those numbers? Note that there should be more SKU's then base products. Some products have many related SKUs, eg
![image](https://user-images.githubusercontent.com/826458/41764660-edc7292a-7655-11e8-83c7-e417c5c37613.png)

If the 10423 number refers to total stock quantity then we would expect that to be different from the number of items listed. If there are

**Comment by bradmac** [comment]
@faithtek would you like to reply to the above? or can this issue be closed?
