### ISSUE TITLE
CSV Exports

### ISSUE THREAD

**Issue by faithtek** [Kademi/kademi-dev#5586]
Several CSV Exports only give valuable data if users have an email address. Those without an email address, the export shows the data but doesn't connect to the user. Suggestion: use or add in addition to email, the username for the user

For instance, a CSV Export from the following page shows the information from the screen capture below
http://asrjmsmucker.admin.kademi.us/rewards/points/?dataQuery=&searchGroup=undefined&searchReward=&tagId=46584031&reasonCode=

![image1](https://user-images.githubusercontent.com/7914822/41700760-b316a6c0-74f7-11e8-962d-f3c780af336b.png)

Exporting from the below pages only returns each user's Real Name. Adding the UserName to the CSV Export, allows for easier connecting the data when in XLSX Spreadsheets.

- http://asrdev.admin.kademi.us/points-buckets/general/?startDate=19%2F06%2F2015&finishDate=19%2F06%2F2018&dataQuery=&startPos=0#points-tab
- http://asrdev.admin.kademi.us/points-buckets/general/?startDate=19%2F06%2F2015&finishDate=19%2F06%2F2018&dataQuery=&startPos=0#debits-tab
- http://asrdev.admin.kademi.us/pointTags/above-beyond/#points-tab
- http://asrdev.admin.kademi.us/pointTags/above-beyond/#debits-tab

Here's a sample of what currently exports for those:

![image2](https://user-images.githubusercontent.com/7914822/41701108-23d56a4e-74f9-11e8-98ae-ffc5928ec7a2.png)

**Comment by Uafinder** [comment]
This export CSV doesn't return new columns
http://vladtest52v.admin.kademi-ci.co/pointTags/tag1/#points-tab
http://vladtest52v.admin.kademi-ci.co/points-buckets/vladtest52vaucstore-points/?startDate=17%2F06%2F2018&finishDate=23%2F06%2F2018&dataQuery=&startPos=0#points-tab
This export is non-informative at all
http://vladtest52v.admin.kademi-ci.co/manageUsers/16814766/#pointsBucketTab-tab
And doesn't give a correct name and file extension

**Comment by bradmac** [comment]
> This export CSV doesn't return new columns

What do you mean "new columns"?

> This export is non-informative at all

What do you mean?

> And doesn't give a correct name and file extension

This is a low priority issue, please move to P3

**Comment by bradmac** [comment]
@Uafinder from what i can see above no issue has been identified with the change made for this issue. Please process this ASAP so we can finalise

**Comment by Uafinder** [comment]
Looks good
