### ISSUE TITLE
Content types group fields

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#5588]
We need the group fields for content types to enable adding multiple groups.

This is needed for Vayability activities to enable picking them with a content query.

**Comment by mkhoudary** [comment]
https://github.com/Kademi/client-vaya-vayability/issues/29

**Comment by bradmac** [comment]
This is already available, just not integrated into the UI:
```
<contentType>
  <name>TestForMo</name>
  <abstractType>false</abstractType>
  <fields>
    <group>
      <name>groups3</name>
      <indexed>false</indexed>
      <title>groups3</title>
      <required>false</required>
      <allowMany>true</allowMany>
    </group>
  </fields>
</contentType>
```
<contentType>
  <name>TestForMo</name>
  <abstractType>false</abstractType>
  <fields>
    <group>
      <name>groups3</name>
      <indexed>false</indexed>
      <title>groups3</title>
      <required>false</required>
      <allowMany>true</allowMany>
    </group>
  </fields>
</contentType>
```

![image](https://user-images.githubusercontent.com/826458/41753967-98b37b90-7624-11e8-94e4-c61ab16be18d.png)

**Comment by bradmac** [comment]
I've added the allowmany checkbox
![image](https://user-images.githubusercontent.com/826458/41754155-4bdbba8e-7625-11e8-80c2-69660dcaeac6.png)

**Comment by mkhoudary** [comment]
I tested that
