### ISSUE TITLE
Content types groups with an org or an org fields

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#5589]
Can we have a field type org? 

The case is that I will need to allow Vayability asset query for activities to pick activities by groups and/or by org.

Case is that we're designing a program just for BeamSuntory, so activity month1week1 for BS will need to be only for BS.. I don't want to touch the journey, I will just modify the asset queries to include the org.

**Comment by mkhoudary** [comment]
https://github.com/Kademi/client-vaya-vayability/issues/29

**Comment by bradmac** [comment]
New form to add this field type:
![image](https://user-images.githubusercontent.com/826458/41756501-fdf2e502-7630-11e8-8aee-0a3d5b7d64cd.png)

Example content type source:
```
<contentType>
  <name>TestForMo</name>
  <abstractType>false</abstractType>
  <fields>
    <org>
      <name>org3</name>
      <indexed>false</indexed>
      <title>org 1</title>
      <required>false</required>
      <allowMany>true</allowMany>
    </org>
  </fields>
</contentType>
```

Example asset edit form:
![image](https://user-images.githubusercontent.com/826458/41756525-176484d2-7631-11e8-9713-af263bd8f62c.png)

**Comment by mkhoudary** [comment]
@Uafinder please give this a test drive

**Comment by Uafinder** [comment]
AS far as i understand there should be a ORG selector in result?
![image](https://user-images.githubusercontent.com/1945230/42822750-7c693780-89e4-11e8-9349-32f633b89f84.png)
Because now it's a simple plain text field
http://vladtest53f.admin.kademi-ci.co/asset-manager/new?type=org

**Comment by bradmac** [comment]
Now shows a proper org select search box:
![image](https://user-images.githubusercontent.com/826458/45607504-061f0f80-baa1-11e8-9c83-dff9671615d0.png)
