### ISSUE TITLE
Add products page to Ecommerce store broken

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5593]
![image](https://user-images.githubusercontent.com/1945230/41808853-a03dd14e-76ec-11e8-98f6-fea20072666d.png)
http://vladtest52v.admin.kademi-ci.co/ecommerce/vladtest52ecomm-ecomstore/?addProducts
It doesn't display products table and buttons doesn't work

**Comment by mkhoudary** [comment]
Fixed that.

**Comment by Uafinder** [comment]
it works!
