### ISSUE TITLE
Points statements return values from another org

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5594]
http://vladtest52v.admin.kademi-ci.co/pointsBalanceStats/?searchStatementRewardId=&searchStatementDateId=
![image](https://user-images.githubusercontent.com/1945230/41809262-4988da4a-76f3-11e8-8437-006e4c0bbf78.png)

**Comment by bradmac** [comment]
Good catch :+1:

**Comment by Uafinder** [comment]
Fresh account
![image](https://user-images.githubusercontent.com/1945230/41973408-933fdae4-7a1d-11e8-9213-3da6f22ef459.png)
http://vladtest52yy.admin.kademi-ci.co/pointsBalanceStats/

**Comment by bradmac** [comment]
Forgot to assign to test..

**Comment by Uafinder** [comment]
Looks fine now, i will keep an eye on it
