### ISSUE TITLE
Reward store orders EDM component is showing base cost instead of purchase amount

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5596]

**Comment by bradmac** [comment]
Requires shopping-lib 1.0.9

**Comment by Uafinder** [comment]
Can't find this component, could you provide a bit more info

**Comment by bradmac** [comment]
This component is in the shopping cart app, not reward store (incorrect issue title)

here's a real examlpe
http://viri.admin.kademi.com.au/autoEmails/120482305/?startDate=28/03/2018&finishDate=28/06/2018#action-tab

**Comment by Uafinder** [comment]
Error appears when using that component
![image](https://user-images.githubusercontent.com/1945230/42276381-4dc8159c-7f9c-11e8-9cec-2f63459323e2.png)
http://vladtest52zzz.admin.kademi-ci.co/autoEmails/16949487/?startDate=28/06/2018&finishDate=04/07/2018#general-tab

**Comment by bradmac** [comment]
@Uafinder i think thats because your product has no images

please add at least one image to each product on your test

**Comment by Uafinder** [comment]
looks good
