### ISSUE TITLE
Leadman screen refactoring

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5599]
- new theme "kcrm"
- updated leadman pages

Creative
https://preview.uxpin.com/e3a2a9f91e732e9b83bd8a8767f8d3f5785da182#/pages/87420288/simulate/sitemap?mode=i

**Comment by anhnt** [comment]
https://github.com/Kademi/kademi-dev/issues/5651

**Comment by anhnt** [comment]
https://github.com/Kademi/kademi-dev/issues/5662

**Comment by anhnt** [comment]
@Uafinder please test here http://newkcrm.admin.kademi-ci.co/websites/newkcrm/version1/#panel_details-tab

**Comment by anhnt** [comment]
Note that there are some parts whihc not done and on related issues

**Comment by bradmac** [comment]
Closing, will work with specific issues from here on..

**Comment by anhnt** [comment]
Fixed, requires content-lib  1.4.2 and kcrm-theme 1.0.7

**Comment by paddyow** [comment]
1 - Make the BG color fafafb
2 - Panels in panels need to have a BG color of fafafb 
3 - Update menu to look like this
4 - Make sure we have the button on state color of eeeeee
5 - add in profiile image
6 - menu should align to the bottom of the header panel


![image](https://user-images.githubusercontent.com/2201340/48108941-93a8ff80-e299-11e8-876c-e1d79abbfba8.png)

**Comment by anhnt** [comment]
Done

**Comment by paddyow** [comment]
Looks good @Uafinder do you want to test this yourself.

**Comment by Uafinder** [comment]
looks good
