### ISSUE TITLE
Leadman dashboard issue

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5600]
![image](https://user-images.githubusercontent.com/1945230/41837707-f5953a26-7866-11e8-8831-e86d53c52654.png)
http://vladtest52wleads-vladtest52w.kademi-ci.co/dashboard
I think it's appears when not assigned task appears
this user
http://vladtest52w.admin.kademi-ci.co/manageUsers/16874049/

**Comment by bradmac** [comment]
just debug code, fixed
