### ISSUE TITLE
Email rate limits

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5601]
Create an ability to set rules governing email sending

Eg "Set up an alert when more than one email per minute is send from Kademi to customers"

- allow limits to be set on rates over specified intervals
- ability to target by group
- ability to take an action based on the trigger, eg pausing email sends for the account
- ability to continue sending emails (through admin settings)

**Comment by bradmac** [comment]
Admin screen updates
![image](https://user-images.githubusercontent.com/826458/46113141-47ea4b80-c241-11e8-85d7-6735f8641906.png)

**Comment by bradmac** [comment]
I think we need to change this so a rule can be applied to a group.

Also, should have an action of "notify" which will send a notification email to an appropriate group, which would presumably be configured on EmailControl

**Comment by bradmac** [comment]
Here's the rule i ended up with
![image](https://user-images.githubusercontent.com/826458/46119602-dbcb1000-c25f-11e8-84f5-d23256b2ca33.png)

**Comment by bradmac** [comment]
Note you can have multiple rules.

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/47078483-147d5a00-d20c-11e8-931a-e300e9cb7347.png)
http://vladtest54e.admin.kademi-ci.co/email-settings
http://vladtest54e.admin.kademi-ci.co/emails/17951667
Email sent ok

**Comment by bradmac** [comment]
I had to disable this temporarily because of a severe performance impact.

I'll take a look again

**Comment by bradmac** [comment]
OK, thats re-enabled, and i've moved the check to the send queue rather then generation phase. I just did a local test of 1200 users and seemed nice and fast.

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/47627020-d29cce00-db92-11e8-8b68-308e6dd0bbc9.png)
