### ISSUE TITLE
Option to turn off selecting a default org

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5602]
> When accessing reports page it shouldn't setup some specified org. Should show all by default (my opinion)

https://github.com/Kademi/client-hinda-dixie/issues/133#issuecomment-399413384

**Comment by Flowers1167** [comment]
Agreed.  Should default to all

**Comment by bradmac** [comment]
Rather then make this an option, it checks to see if the current user is a participant for an organisation (ie if they are in a group connected to an organisation points bucket). 

If they are a participant in an organisation based points program then it does the existing check to ensure the selected org is an available org

If the user is not a participant then it does nothing.

This should solve the problem for dixie because sales reps are not participants

**Comment by Uafinder** [comment]
Yup, works ok!
