### ISSUE TITLE
PyOCRService uses an independent thread pool

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#5603]
After failing to use C after values being returned from PyOCRService, I've noticed that it uses its own thread pool which doesn't have any of the thread locals set.

**Comment by mkhoudary** [comment]
Hey @bradmac the code still needs more refactoring like eliminating the PyOCRRunnable.

Also I see that the scantable method shall return the scanned table or throw an exception if an error occurred, then it's up to the caller to use this synchronously or asynchronously (Like we did with the OCRProcessable) 

Please confirm my approach so I could finalize it, right now

**Comment by bradmac** [comment]
@mkhoudary its a requirement that the service runs the job asynchronously, so the initial implementation is correctly using a threadpool, please revert to that code

**Comment by bradmac** [comment]
> After failing to use C after values being returned from PyOCRService

You should ensure your event listener code executes inside a rootcontext so C is available

**Comment by mkhoudary** [comment]
Done..
