### ISSUE TITLE
SKU doesn't display after bulk file uploading

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5604]
Check SKU page, no SKUs appear, however when you export csv, you will see that SKUs are present
![image](https://user-images.githubusercontent.com/1945230/41916848-a37feafa-7961-11e8-8508-bc8d0f53a109.png)
![image](https://user-images.githubusercontent.com/1945230/41916953-eba9d9d0-7961-11e8-8f1d-bc14bc5e6ac7.png)
And when you check frontend - all SKUs is ok there too
![image](https://user-images.githubusercontent.com/1945230/41917088-3e193a62-7962-11e8-95b3-b1f287d50441.png)
http://vladtest52x.admin.kademi-ci.co/skus/

Looks like problem appears after import via CSV file
re-index doesn't help

**Comment by bradmac** [comment]
SKU's are currently appearing:
![image](https://user-images.githubusercontent.com/826458/41939618-7e894a1e-79ea-11e8-8842-4f978c60a50f.png)

**Comment by bradmac** [comment]
@Uafinder can you please confirm if this problem is still active

**Comment by Uafinder** [comment]
Reproduced on fresh account
1. Create fresh account
2. Install kcomm2 (kcomm into account, kcomm2 into website)
3. Import products and categories
4. Go to SKU
5. Upload SKU file
6. Refresh
7. SKU page stll doesn't display SKUs
http://vladtest52yy.admin.kademi-ci.co/skus/
![image](https://user-images.githubusercontent.com/1945230/41970984-7baea020-7a15-11e8-9b37-c124f1b2a531.png)
[skus (3).zip](https://github.com/Kademi/kademi-dev/files/2140963/skus.3.zip)

**Comment by bradmac** [comment]
please try again

**Comment by Uafinder** [comment]
Yeah, looks great!
