### ISSUE TITLE
KComm2: pricing table caused descrease filter values on the left, but prices remains the same

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5605]
![image](https://user-images.githubusercontent.com/1945230/41917579-6c50a0d6-7963-11e8-96fc-3da2d856c0c3.png)
http://vladtest52xweb-vladtest52x.kademi-ci.co/vladtest52xweb-ecomstore/visacards/
http://vladtest52x.admin.kademi-ci.co/manageUsers/16882452/#summary-tab

**Comment by bradmac** [comment]
@Uafinder thats correct, the price range value is driven by list prices not personalised prices

**Comment by Uafinder** [comment]
got it
