### ISSUE TITLE
KComm2: error when adding to cart

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5606]
![image](https://user-images.githubusercontent.com/1945230/41918179-7ced65f4-7964-11e8-9dd0-c23a044fe131.png)
http://vladtest52xweb-vladtest52x.kademi-ci.co/vladtest52xweb-ecomstore/visa-1000
![image](https://user-images.githubusercontent.com/1945230/41918241-9d791444-7964-11e8-9bf9-3f5502c686f6.png)
http://vladtest52x.admin.kademi-ci.co/products/16883063/#panel_details-tab

**Comment by bradmac** [comment]
This is because you havent selected an option.

Note the form should require the user to select an option, and that is covered on this issue:
https://github.com/Kademi/kademi-dev/issues/5466#issuecomment-393010216

So closing this issue as a duplicate
