### ISSUE TITLE
KComm2: Too many digit's after comma in product price

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5607]
![image](https://user-images.githubusercontent.com/1945230/41918324-cd2b6f52-7964-11e8-8883-b61b4c5b95bd.png)
http://vladtest52xweb-vladtest52x.kademi-ci.co/vladtest52xweb-ecomstore/visa-1000
http://vladtest52x.admin.kademi-ci.co/products/16883063/#panel_details-tab

it looks appears when pricing rule work

**Comment by bradmac** [comment]
Moved to
https://github.com/Kademi/kademi-dev/issues/5466
