### ISSUE TITLE
ContactForm Component Settings submit text and thankyou message is not multilingual

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#5609]
Unless I am unaware at this point in time, I think there needs to be a method to apply multi-language support to ContactForm Component Settings.

If I apply **class="trans-lookup"** to a **data-type="component-contactForm"** then **data-submit-text="Send"** and **data-thank-you="Thank your for contacting us."** should appear in Edit Translations, should a website have languages configured.

Also, currently, if I add .trans-lookup class to data-type="component-contactForm" the whole component stops rendering.

**Comment by bradmac** [comment]
>  if I add .trans-lookup class to data-type="component-contactForm" the whole component stops rendering.

Correct, its only valid to apply this to a single element so the text is substituted.

Looking at the code below, i think we can just add trans-lookup to the alert div
```
    <div class="thankyou row" style="display: none">
        <div class="col-sm-12">
            #set($thankYouMessage = $thankYou)
            #if ($formatter.isNull($thankYouMessage))
            #set($thankYouMessage = "Thank you for your message, we will reply shortly.")
            #end
            <div class="alert alert-success">$thankYouMessage</div>
        </div>
    </div>
```

**Comment by bradmac** [comment]
The trans-lookup class should also be added here:
```
<button type="submit" class="btn $submitSize $submitColor $!submitClass">$!submitText</button>
```

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/42007460-5ed2b652-7ad4-11e8-8709-87369a17fa14.png)

**Comment by bradmac** [comment]
Translated confirmation message
![image](https://user-images.githubusercontent.com/826458/42007485-7d31c534-7ad4-11e8-9271-8c8ab1d4cc41.png)

**Comment by bradmac** [comment]
Done.

Added translation support to thank you message and send button
