### ISSUE TITLE
ContactForm Component Message field not appearing

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#5610]
ContactUs Form "message" field is appearing in KEditor but not on the front-end of website.

And I'm certain that the markup around $message is default, unaltered.

**Edit**: When writing this message I noticed something. On some domains it's working, other's it's not.

Admin: http://spinsurance-spinsurance.kademi.com.au//theme/apps/contactus/contenteditor?fileName=contactForm.html&miltonUserUrl=/users/here-comes-trouble&miltonUserUrlHash=2b76bdbf-ab94-4014-970b-7122ca2b8a8d:tPY2fpvUT3WMArizm2pF5sCVHsw

**FrontEnd**: http://version1.spinsurance-spinsurance.kademi.com.au/contactus broken
**FrontEnd**: http://spinsurance-spinsurance.kademi.com.au/contactus working
**FrontEnd**: http://spinsurance.kademi.com.au/contactus broken

Even though these three domains work fine elsewhere while viewing the website.

**Comment by bradmac** [comment]
This is working in stock

![image](https://user-images.githubusercontent.com/826458/42007633-524233e4-7ad5-11e8-9961-b19251e73e0b.png)

![image](https://user-images.githubusercontent.com/826458/42007702-aac10b76-7ad5-11e8-8740-292b368af49b.png)

**Comment by bradmac** [comment]
Problem is no longer active
