### ISSUE TITLE
Ability to make <img alt=""> Multilingual.

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#5611]
Would be nice if trans-lookup changed an img tag's alt attribute to multilingual text.

`<img class="svg trans-lookup" src="/theme/icons/life-insurance.svg" alt="Life Insurance">`

**Comment by bradmac** [comment]
```
<img src="/static/images/ballon_flight.jpg" style="display: inline-block; vertical-align: center;" alt="Balloons" class="img-thumbnail  img-responsive " width="400" height="800">
```

```
<img src="/static/images/ballon_flight.jpg" style="display: inline-block; vertical-align: center;" alt="Globos" class="img-thumbnail  img-responsive  trans-lookup" width="400" height="800">
```

![image](https://user-images.githubusercontent.com/826458/42014089-7d389af6-7af4-11e8-9758-7aff3482a22d.png)

**Comment by bradmac** [comment]
Done.

Requires content-lib 1.3.6 and platform 1343 or above

**Comment by bradmac** [comment]
@Uafinder note you might need to view source to see the alt attribute

**Comment by Uafinder** [comment]
Cools!
