### ISSUE TITLE
Error: Product Search in Admin

### ISSUE THREAD

**Issue by faithtek** [Kademi/kademi-dev#5614]
Get the error below when searching in Products in the admin tool. The correct results still show at the bottom of the page, however.

http://asrdev.admin.kademi.us/products/?dataQuery=gas+grill&supplier=&searchOrg=

![image2](https://user-images.githubusercontent.com/7914822/42061240-7af2fab8-7af7-11e8-87af-da37cd32f649.png)

**Comment by bradmac** [comment]
Fixed

**Comment by bradmac** [comment]
Note this issue only occured when searching for 2 or more words
