### ISSUE TITLE
Categories are displaying across accounts

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5615]
![image](https://user-images.githubusercontent.com/826458/42062776-e1511aca-7b82-11e8-8a56-3a80fcf16534.png)

![image](https://user-images.githubusercontent.com/826458/42062833-1c74f02c-7b83-11e8-8631-f8a60f03faf2.png)

**Comment by bradmac** [comment]
Fixed
![image](https://user-images.githubusercontent.com/826458/42063021-e08eb2fe-7b83-11e8-8263-b84b3fe75b91.png)

**Comment by bradmac** [comment]
Aslo added link frmo category page to products page

![image](https://user-images.githubusercontent.com/826458/42063333-4b0f2612-7b85-11e8-85a8-24d3095175ca.png)

**Comment by Uafinder** [comment]
Looks fine now, link to products issue moved to separate...
