### ISSUE TITLE
Issues with adding class to a container (KEditor)

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#5617]
When I first add a class to a container (not the columns), such as "page-undermask", the markup produces shows class="background-forpage-undermask background-for".

A hack / fix I've been following is to rename the class in container settings to ".page-undermask" which literally breaks the class generating script, and then on the next save I rename back to "page-undermask" and the output generated is correct enough for me to proceed, although missing "background-for" which I'm currently not making use of.

**Comment by bradmac** [comment]
Fixed.

Required contentEditor-lib 1.2.4

**Comment by bradmac** [comment]
You can patch it in directly if you want:
![image](https://user-images.githubusercontent.com/826458/42071815-73c2c0c4-7bb1-11e8-8b74-94d35d112043.png)

See 413
```
                form.find('.txt-extra-class').on('change', function () {
                    var container = keditor.getSettingContainer();
                    var containerBg = contentEditor.getContainerElement(container, '.container-bg');

                    containerBg.attr('class', 'container-bg ' + (containerBg.hasClass('background-for') ? 'background-for' : '') + " " + this.value.trim());
                });

```
