### ISSUE TITLE
Improve layout of membership properties fields, and ability to see history of changes

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5618]
Needed for https://github.com/Kademi/client-hinda-dixie/issues/150

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/42070885-8f261370-7bac-11e8-84e5-43d0a14d9140.png)

**Comment by bradmac** [comment]
History view. Click on a clock above to see history for that membership
![image](https://user-images.githubusercontent.com/826458/42070957-dbc15136-7bac-11e8-9f20-024453a93cb8.png)

**Comment by Uafinder** [comment]
Moved one non-critical issue off
looks good
