### ISSUE TITLE
Any group movement causes invalid status message

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#562]
![image](https://cloud.githubusercontent.com/assets/1945230/8939524/9738b212-356d-11e5-91d3-7b16558af745.png)
Steps to reproduce:
1. Go to the groups page
2. Try to change order of any group (just drag it a little)

**Comment by tuzzmaniandevil** [comment]
@Uafinder  We don't support reordering groups, only changing folders.

**Comment by Uafinder** [comment]
Yup, not a problem. However it's a bug anyway. You could take one group, click and hold for a while and then "Removed group from folder" message will appear.

**Comment by tuzzmaniandevil** [comment]
This will be fixed with #710
