### ISSUE TITLE
Module List Grid Option Bug

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#5621]
- Switch the component to grid layout and save
- Go to the front-end
- Click the module picker button
- Choose another program
- The underlying page reloads and the picker disappears nor do any modules appear
- The URL changes to (for example) http://version5.digitize-schneiderelectric.kademi.com.au/programs/SeCo/CO/ICO/

![image](https://user-images.githubusercontent.com/2201340/42131313-d522d10a-7d42-11e8-8e20-6d0f8fb2f89e.png)

**Comment by anhnt** [comment]
Fixed

**Comment by Uafinder** [comment]
Looks good now
