### ISSUE TITLE
Show profiles notes and allow them to be added on the admin profile page

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5623]

**Comment by bradmac** [comment]
Added to the profile tab
![image](https://user-images.githubusercontent.com/826458/42142002-09d59d88-7e01-11e8-981f-83047aa4fc2a.png)

**Comment by bradmac** [comment]
And appears on the timeline
![image](https://user-images.githubusercontent.com/826458/42142021-1e5c7038-7e01-11e8-8ab5-5cb1a36a9571.png)

**Comment by AlaaKhalaf94** [comment]
Adding note from user profile is fine, but it doesn't appear in user timeline
http://testnotes01.admin.kademi-ci.co/manageUsers/16922556/#summary-tab

![capture1](https://user-images.githubusercontent.com/26510030/42160675-c7524556-7e00-11e8-908d-e96249818388.PNG)

**Comment by bradmac** [comment]
Timeline was being generated by LeadmanApp which is incorrect, this should no longer depend on leadman. I've moved to AdminApp

**Comment by AlaaKhalaf94** [comment]
passed

**Comment by LinziC** [comment]
Sorry just to add - we may want to note for example that the customer is a non-redeemer but the branch manager has authorised the use of points - so it would be great to be able to note this somewhere other than putting it in the reason description - again, where the customer can see it - but if an admin user could look at the profile - it would be noted on there .... Hope that example makes sense :)

**Comment by bradmac** [comment]
Hi @LinziC you should remove that custom field, and instead use the new notes feature which this issue is about.

The new notes feature doesnt show on the front end profile page, only on the admin. It also lets you keep adding new notes, each with its own date

Here's an example:
https://carters.admin.kademi.com.au/manageUsers/72710083/#general-tab

![image](https://user-images.githubusercontent.com/826458/42543205-d82f743e-84fe-11e8-8655-7cc3884ec192.png)

**Comment by LinziC** [comment]
Ahh that's perfect - sorry I thought Anh and I had removed that field ..... Brad can you plesae just send me a link to the page where I can remove it ??

**Comment by bradmac** [comment]
Sorry, not sure, its whatever group you added that field to.

**Comment by LinziC** [comment]
Just want to confirm that this is where I can remove this field from https://carters.admin.kademi.com.au/groups/Trade/

**Comment by bradmac** [comment]
i think so

**Comment by LinziC** [comment]
Cool as long as removing this from here doesnt interfere in any way with what you've done - I'm happy :)

**Comment by LinziC** [comment]
ok - so I delete that field and refresh the page and the field comes back - Sorry
