### ISSUE TITLE
Product categories to be integrated with assets

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5626]
Just like we do with products

**Comment by bradmac** [comment]
Done..
![image](https://user-images.githubusercontent.com/826458/42249397-231975d8-7f7f-11e8-8f25-b859fccbb14e.png)

![image](https://user-images.githubusercontent.com/826458/42249415-344c1bd0-7f7f-11e8-900d-c9b4db2c4ea5.png)

![image](https://user-images.githubusercontent.com/826458/42249420-3dee7e44-7f7f-11e8-9bf2-cc99a9fe9672.png)

**Comment by AlaaKhalaf94** [comment]
- When I select asset types , and click on "Create asset" button, it show me  JSON code 
![capture3](https://user-images.githubusercontent.com/26510030/42560220-d7dfc3da-84fe-11e8-8b61-1fea96eeebea.PNG)

- After I edit asset The layout of result is not fine
http://fresh19.admin.kademi-ci.co/categories/testcat/#attributes-tab
![capture4](https://user-images.githubusercontent.com/26510030/42560314-0d782096-84ff-11e8-8995-8d8f2540e213.PNG)

**Comment by bradmac** [comment]
> After I edit asset The layout of result is not fine

low priority

> When I select asset types , and click on "Create asset" button, it show me  JSON code

But note that the asset is linked, so this is not a show stopper

**Comment by AlaaKhalaf94** [comment]
https://github.com/Kademi/kademi-dev/issues/5668
