### ISSUE TITLE
KAlerts to enable showing acknowledged alerts

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#5628]
We need to have a component that allows showing acknowledged alerts and unacknowledged alerts (as an option)

**Comment by mkhoudary** [comment]
https://github.com/Kademi/client-vaya-vayability/issues/31

**Comment by mkhoudary** [comment]
Done that.. @AlaaKhalaf94 the alerts component now contains an option to select which alerts to show.. acknowledged shall show disposed alerts, unacknowledged shall display undisposed alerts.

**Comment by bradmac** [comment]
@mkhoudary can this issue be closed? or is it being tested?

**Comment by AlaaKhalaf94** [comment]
all is good
