### ISSUE TITLE
Custom fields display issue on profile page

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5631]
Comes from Dixie
https://github.com/Kademi/client-hinda-dixie/issues/159
When you refresh page, dixieuserid is changing randomly between values.
E.g. one custom field is 0001 and second is 0002, it display this values randomly between all memberships.
Note, that i couldn't reproduce this on CI account
http://vladtest52zz.admin.kademi-ci.co/manageUsers/16937910/#general-tab

**Comment by bradmac** [comment]
Fix applied to US
