### ISSUE TITLE
KCom2: Improve product search

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5634]
Extension to https://github.com/Kademi/kademi-dev/issues/5476

- improve selection of attributes, currently only allows a single value for a single attribute, but users should be able to select multiple values in multiple attributes
- persistence of selection, if the user reloads a page selected values should show as selected
- implement product results infinite loading (ie pagination by scrolling)

**Comment by anhnt** [comment]
Done

**Comment by Uafinder** [comment]
Looks good
