### ISSUE TITLE
KCom2: shopping cart icon doesn't appear

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5641]
![image](https://user-images.githubusercontent.com/1945230/42321319-2e35dd16-8061-11e8-818b-40cffc34b028.png)
http://vladtest53web-vladtest53.kademi-ci.co/vladtest53web-ecomstore/iphone7
http://vladtest53.admin.kademi-ci.co/ecommerce/vladtest53web-ecomstore/#products-tab
I click on add to cart button, pop-up appears about successful adding, but shopping cart icon doesn't appear to complete purchase.

**Comment by bradmac** [comment]
This was fixed previously
