### ISSUE TITLE
Register Domain Name Broken

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#5645]
http://gohealthy.admin.kademi.com.au/registerDomain/

Cannot enter a domain name then click 'Check'.    Valuation pops up saying 'Please enter all required fields'.

Note nothing appearing in the 'select' an option drop down.

**Comment by bradmac** [comment]
Looks ok currently, i think what you saw might have been because there was a problem loading the dmoain tld price list, which was fixed a while back
