### ISSUE TITLE
EDM content does not reference Assets Components (assetQueryText)

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#5646]
I'm trying to create a multilingual email response using journeys and I've gone as far as Send Email node > Manage > Message content.

However, unlike Edit pages, I don't have access to assetQueryText component.

Here's a preview:
http://spinsurance.admin.kademi.com.au/funnels/contact-us-autoresponder/version1/emailAction-437dea/#message-tab

**Comment by bradmac** [comment]
This is working correctly locally with content-lib 1.3.6
![image](https://user-images.githubusercontent.com/826458/42545795-2f2d91d0-850e-11e8-9d43-1a9a30f3a2cc.png)

There is an update available to 1.3.5 in production:
![image](https://user-images.githubusercontent.com/826458/42545831-5198dc70-850e-11e8-90dc-ac87a70ff59b.png)

**Comment by bradmac** [comment]
Please update libs, if that doesnt fix the problem we'll release 1.3.6

**Comment by stephen-fueldesign** [comment]
Thanks Brad, content-lib 1.3.5 works!

I'll take extra care to ensure all libs are up-to-date before reporting issues next time.

**Comment by bradmac** [comment]
:+1:
