### ISSUE TITLE
Unsuccessful intergrations are missed from integrations list

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5650]
http://dixie.admin.kademi-ci.co/integration/#history-tab

These are successful
![image](https://user-images.githubusercontent.com/1945230/42368355-804a605a-810f-11e8-9c93-a7893be0f6d6.png)
but these are missed
http://dixie.admin.kademi-ci.co/integration/16960235
http://dixie.admin.kademi-ci.co/integration/16960220
and there is no chance to review their result

**Comment by bradmac** [comment]
I think its because the start date isnt being set

![image](https://user-images.githubusercontent.com/826458/42423943-50666db2-8357-11e8-90eb-c68cf2532766.png)

**Comment by bradmac** [comment]
Its now setting the started date when the job is created in the upload, so that should set the start date

Note that if there is no start date it wont be included in the date range selector

**Comment by bradmac** [comment]
Seen a problem here with a successful integration that didnt get its date set:
https://airnz.admin.kademi.com.au/integration/121615748

**Comment by bradmac** [comment]
@Uafinder seems to be working correctly now, ie with new results
![image](https://user-images.githubusercontent.com/826458/42743401-8c326646-8917-11e8-8732-7d9e77c59ff2.png)

**Comment by bradmac** [comment]
@Uafinder can you please check if the problem is still active?

**Comment by Uafinder** [comment]
Looks good now
