### ISSUE TITLE
Make CartID editable on order management page

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5657]

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/42432974-5628bc24-83a1-11e8-9667-635760105d3c.png)

**Comment by bradmac** [comment]
@faithtek

**Comment by bradmac** [comment]
Added a few more enhancements

Ability to duplicate an order:
![image](https://user-images.githubusercontent.com/826458/42478490-045daa84-8429-11e8-94f6-f738808674ab.png)

Orders list has more information and links:
![image](https://user-images.githubusercontent.com/826458/42478509-15ad826e-8429-11e8-8e21-3a535b8c9fa3.png)

**Comment by Uafinder** [comment]
It works!
