### ISSUE TITLE
Send email from lead detail frontend 

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#5662]
![image](https://user-images.githubusercontent.com/735555/42446999-81059ccc-83a2-11e8-816b-1e2fbaa41bde.png)

@bradmac should it be done with server side js? Or we are going to add some method on the backend

**Comment by bradmac** [comment]
I think best thing might be to add a new EmailService class and then add some server side JS to call it.

I'll provide details..

**Comment by anhnt** [comment]
We have that api on email app
```
applications.email.emailBuilder()
        .recipientAddress(sendToEmail)
        .fromAddress(yourEmail)
        .subject(title)
        .html(html)
        .build();

**Comment by bradmac** [comment]
:+1:

**Comment by anhnt** [comment]
Done
