### ISSUE TITLE
Eway Payment method is not integrated with KCommerce2

### ISSUE THREAD

**Issue by OlaAkeela** [Kademi/kademi-dev#5663]
An error says "Payment failed: Exception occured: Not supported yet." appears whenever we try to submit an order using Eway. 
Please integrate Eway with KCommerce2

**Comment by bradmac** [comment]
Hi @OlaAkeela, should be working now, but needs a platform update

**Comment by OlaAkeela** [comment]
Tested and works well.

**Comment by Uafinder** [comment]
Looks fine
