### ISSUE TITLE
Custom activity on leadman timeline

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#5665]
When i selected a predefined action ie Email to customer, timeline is displaying with title: "Emailed"
When i selected a custom action which is defined from funnel app, at the moment it says "Note".
I think we should improve this

![image](https://user-images.githubusercontent.com/735555/42504857-364b47b6-8467-11e8-9b68-47ce18514413.png)

![image](https://user-images.githubusercontent.com/735555/42504819-1b08da54-8467-11e8-9ee3-d01b4accf6cc.png)

BTW here is predefined actions and custom actions in term of action type values
phone-true
phone-false
email-true
email-false
customActivity1529908643937-true

**Comment by anhnt** [comment]
https://github.com/Kademi/kademi-dev/issues/5599

**Comment by anhnt** [comment]
Done for point 1

**Comment by Uafinder** [comment]
Fresh account, not seeing any changes
![image](https://user-images.githubusercontent.com/1945230/45359608-b4284680-b5d5-11e8-9410-895483876729.png)
http://vladtest53wweb-vladtest53w.kademi-ci.co/leads/17798293/?view=activities

**Comment by anhnt** [comment]
It was fixed when creating new note on dashboard but not fixed when editing note on lead page.
Done

**Comment by Uafinder** [comment]
looks good now
