### ISSUE TITLE
Videos not playing

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#5666]
Have uploaded a few videos, some will play others not.  This is the error:

![image](https://user-images.githubusercontent.com/2201340/42541900-b3a91262-84e7-11e8-9322-317f76d068fc.png)

http://schneiderelectric.admin.kademi.com.au/websites/digitize/version5/programs/SeCo/CO/ICO/#files-tab

**Comment by bradmac** [comment]
Works fine for me
![image](https://user-images.githubusercontent.com/826458/42542032-12ded288-84f9-11e8-805e-800cb3a415ec.png)

**Comment by bradmac** [comment]
Note that the streaming formats of videos take a while to generate

**Comment by bradmac** [comment]
Please check
