### ISSUE TITLE
KTimesheets: Task/Lead assignment summary page

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5667]
This is to allow reviewing the whole team at once, to see who's assigned to what (or not)

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/42551519-b63fbd0c-852b-11e8-9457-a923883d471b.png)

**Comment by bradmac** [comment]
Requires 1.0.2

**Comment by bradmac** [comment]
@Uafinder what do you need help with?

**Comment by bradmac** [comment]
http://kcrm-kademi.kademi.us/team-tasks/

**Comment by Uafinder** [comment]
If there are a lot of team members there is no possibility to scroll them to right to see the hidden ones
![image](https://user-images.githubusercontent.com/1945230/42743210-8d0ded12-88ca-11e8-9949-2b917fc5d88f.png)
http://vladtest53dleads-vladtest53d.kademi-ci.co/team-tasks/
http://vladtest53d.admin.kademi-ci.co/websites/

Time marks should be in same format
![image](https://user-images.githubusercontent.com/1945230/42743279-ff85f7c2-88ca-11e8-94e8-3cd9156ef224.png)
http://vladtest53dleads-vladtest53d.kademi-ci.co/team-tasks/

Link to a lead should lead to it's page, link to a task should lead to task
![image](https://user-images.githubusercontent.com/1945230/42743296-35cef78e-88cb-11e8-8888-fbdc0dd7b0d3.png)
http://vladtest53dleads-vladtest53d.kademi-ci.co/team-tasks/

Link to user should lead to it's team profile page (or some sort), but it's just redirected to dashboard
![image](https://user-images.githubusercontent.com/1945230/42743318-674503da-88cb-11e8-8b9c-5e996558c2b6.png)
http://vladtest53dleads-vladtest53d.kademi-ci.co/team-tasks/

It doesn't show independent tasks (which are not related to leads), as well as not showing simple plain tasks which entered on timesheets page
![image](https://user-images.githubusercontent.com/1945230/42743493-1465c918-88cd-11e8-9fb0-3b4f22a6cf38.png)
http://vladtest53dleads-vladtest53d.kademi-ci.co/team-tasks/
![image](https://user-images.githubusercontent.com/1945230/42743518-25e49d90-88cd-11e8-8d7d-8be02f35387a.png)

Assignment checkboxes works incorrectly. They are shown only when a whole lead assigned to user.
When only task assigned to user it will not show checkbox in appropriate place.
![image](https://user-images.githubusercontent.com/1945230/42743638-5ff5f12c-88ce-11e8-82eb-3afe5191a7d2.png)
http://vladtest53dleads-vladtest53d.kademi-ci.co/team-tasks/

**Comment by bradmac** [comment]
> Assignment checkboxes works incorrectly. They are shown only when a whole lead assigned to user.
When only task assigned to user it will not show checkbox in appropriate place.

Confirmd this is displaying correctly..

![image](https://user-images.githubusercontent.com/826458/42744348-e89c01aa-891f-11e8-9a8d-6d916b71664c.png)

**Comment by bradmac** [comment]
Looks like this might be a problem in admin.

**Comment by bradmac** [comment]
@Uafinder if you cant resolve the issue with checkmarks please move that to its own issue.

**Comment by Uafinder** [comment]
Ok, some issues comes to separated
Seems to be fine
