### ISSUE TITLE
Beta manage users page question

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#567]
![image](https://cloud.githubusercontent.com/assets/1945230/8940530/3151ad22-3573-11e5-8754-1912603d3ba1.png)
Why new manage users page contains not all users? (just Wesley Tuzza user)

**Comment by bradmac** [comment]
It should contain all users with a membership to a group defined by the organisation. If they're not showing up it might just need reindexing

**Comment by Uafinder** [comment]
Yup, re-indexing helps well. Thanks!
