### ISSUE TITLE
points don't get refreshed when added by criteriaBuilders

### ISSUE THREAD

**Issue by mrdadah** [Kademi/kademi-dev#5670]
When I add points or debitPoints to profile using criteriaBuilders, points in the profile points page don't get refreshed until I press **refresh balance** button on that page

![image](https://user-images.githubusercontent.com/11255121/42634451-eec6ec5c-85eb-11e8-88a6-d23491c467ac.png)

**Comment by mrdadah** [comment]
https://github.com/Kademi/projects/issues/93

**Comment by bradmac** [comment]
OK, you should not be adding points or debits through KCriteria directly. MAnaging points is pretty complex, so needs to be done through an appropriate method in RewardService

Note that RewardService should not be accessed directly from front end code. There are API methods eg on RewardFolder but not easy to use.

So i'll create a PointsManager class that can be accessed from the services object

**Comment by bradmac** [comment]
so something like this (assuming JS)
```
var pointsManager = services.points
var pointsReq = pointsManager.newPointsRequest(profile, numPoints); // numPoints can be positive or negative
pointsReq.reason = "some reason goes here";
var creditOrDebit = pointsManager.processPointsRequest(pointsReq); // will return Points or PointsDebit, or null if none created
```

**Comment by bradmac** [comment]
@mkhoudary you might need to add some code to PoitnsManager

**Comment by mkhoudary** [comment]
Done that
