### ISSUE TITLE
Enhance sales data claimer app to support multiple transactions per claim and OCR scanning

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5673]
- update the app so that a single claim can contain multiple transactions (ie in jsondb). This may remove the need for claim groups
- ensure the existing single transaction claim component works with the new structure
- new front end component to allow submitting claims which will be OCR scanned (done by @MohammedFuad97 )
- admin screen to allow adding new claims, with either 1 or more transactions in the claim, or as an OCR claim
- admin screen should allow editing and approving claims with single or multiple transactions
- admin workflow to review and edit data from OCR (this is already done)
- accepting an OCR claim will create claim transactions in the claim just as if they had been added normally
- should be a single approval workflow which also applies to non-OCR claims
- journey nodes should be triggered by accepting/rejecting claims

Depends on https://github.com/Kademi/kademi-dev/issues/5514

Related:
https://github.com/Kademi/projects/issues/300
https://github.com/Kademi/projects/issues/299
https://github.com/Kademi/projects/issues/297
https://github.com/Kademi/projects/issues/227
https://github.com/Kademi/projects/issues/224

**Comment by bradmac** [comment]
Need to copy this to a new app called KSalesClaim

**Comment by tuzzmaniandevil** [comment]
@bradmac Do you want to review? I'll fix anything I've missed or bugs I created of course :-)

**Comment by bradmac** [comment]
Thanks! Looking now, will ping back anything i find..

**Comment by bradmac** [comment]
@tuzzmaniandevil can you please remove this hard coded url:
```
                                <span class='zoom' id='ocrFile'>
                                    <span>Click to Zoom</span>
                                    <img src="http://moudatest.admin.kademi-ci.co/assets/2a0766a3-1344-4d2d-bbf2-396da618349a" alt="OCR File Hash" name="ocrFileHash"/>
                                </span>
```

**Comment by tuzzmaniandevil** [comment]
https://github.com/Kademi/kademi-dev/pull/5735

**Comment by bradmac** [comment]
I uploaded an OCR claim (using mockocr) and pressed Save on the modal:

![image](https://user-images.githubusercontent.com/826458/43065382-c4519044-8eb5-11e8-9fc4-920f9b259bb9.png)

After that no claims records were created:
![image](https://user-images.githubusercontent.com/826458/43065420-e244a046-8eb5-11e8-9ad6-74c9e3e121f9.png)

And the OCR data was no longer visible:
![image](https://user-images.githubusercontent.com/826458/43065438-f5e06496-8eb5-11e8-92aa-96eca6aa4561.png)

What should happen
- this should create claim records (ie transactions within a claim) which can then be approved
- the original OCR data should be retained for reference

**Comment by tuzzmaniandevil** [comment]
So this is in the Admin window, The "Process" modal for OCR correct?

So I need to remove the "Approve" button, And add a "Process" button?

**Comment by bradmac** [comment]
Yes, this refers to the modal:
![image](https://user-images.githubusercontent.com/826458/43109048-e6064fd0-8f38-11e8-80d9-f9b960c71c8e.png)

I need to be able to show the client saving to claim transactions, and then approving them and having that creating sales data records.

**Comment by bradmac** [comment]
After clicking "Process" (and selecting checkboxes) no claim items are shown:
![image](https://user-images.githubusercontent.com/826458/43112244-431a1386-8f49-11e8-9a84-2392f386cf24.png)

**Comment by bradmac** [comment]
The user needs to be able to see the claim items to approve them. Thats true regardless of whether they came from the OCR processing screen or were loaded as claim items directly

**Comment by tuzzmaniandevil** [comment]
Did some major refactor, So ready to test :-)
https://github.com/Kademi/kademi-dev/pull/5744

**Comment by bradmac** [comment]
Actually, i'll move this part from ES..

**Comment by bradmac** [comment]
Done. @tuzzmaniandevil I've updated to not use ES in the approval operation. please check my changes, and make sure that any other usages of ES in workflow code are replaced with using the JSON objects from JsonDB.

**Comment by tuzzmaniandevil** [comment]
At the moment a user gets looked up using their email or username, If neither is a match null is returned and then the currently logged in user or the user who submitted the image.

What do you want this workflow to look like?

**Comment by tuzzmaniandevil** [comment]
Also looks like the app doesn't currently support orgs, Only profiles, Is this correct?

**Comment by tuzzmaniandevil** [comment]
https://github.com/Kademi/kademi-platform/pull/19
https://github.com/Kademi/kademi-dev/pull/5748

Haven't done the thing that allows clients to edit the "soldBy" part of a claim yet.

**Comment by tuzzmaniandevil** [comment]
https://github.com/Kademi/kademi-dev/pull/5756

**Comment by bradmac** [comment]
Bonus points for a jquery plugin :)

**Comment by bradmac** [comment]
Approve wasnt working because it was still using soldById at the claim level.

Removed that as not needed

**Comment by bradmac** [comment]
@tuzzmaniandevil i can see a missed requirement:

> admin screen to allow adding new claims, with either 1 or more transactions in the claim, or as an OCR claim

Admins need to be able to submit OCR claims from the admin screen, but currently i cant see a way to do that

**Comment by tuzzmaniandevil** [comment]
@bradmac https://github.com/Kademi/kademi-dev/pull/5782

**Comment by bradmac** [comment]
Merged PR
