### ISSUE TITLE
Points leaderboard component - points should be rounded

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5679]
![image](https://user-images.githubusercontent.com/1945230/42723090-2125c32e-8760-11e8-9f5d-e35551eea7b6.png)
http://vladtest53dsales-vladtest53d.kademi-ci.co/report.html
http://vladtest53d.admin.kademi-ci.co/pages/vladtest53dsales/version1/

**Comment by bradmac** [comment]
Updated to render as an integer, we dont need decimal points here

**Comment by Uafinder** [comment]
Looks fine
