### ISSUE TITLE
Date range picker doesn't change period without refresh

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5680]
http://vladtest53dsales-vladtest53d.kademi-ci.co/report.html
http://vladtest53d.admin.kademi-ci.co/pages/vladtest53dsales/version1/
For example you have 7 days period
You change it to 1 month, but data not changing
![image](https://user-images.githubusercontent.com/1945230/42723110-7c4a3262-8760-11e8-94ef-32f9697e7c76.png)
Only after refresh
![image](https://user-images.githubusercontent.com/1945230/42723113-85caa7e0-8760-11e8-8ab2-0b0e9a848fa5.png)

**Comment by anhnt** [comment]
@Uafinder Fixed

**Comment by Uafinder** [comment]
Now looks good
