### ISSUE TITLE
Changing users count in KPI EDM component cause it to broke

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5684]
![image](https://user-images.githubusercontent.com/1945230/42723454-c2ecdfc0-8766-11e8-8df2-f1b8b9963073.png)
![image](https://user-images.githubusercontent.com/1945230/42723456-c7efd950-8766-11e8-8e11-187ab41b0765.png)
http://vladtest53d.admin.kademi-ci.co/groupEmails/17028986/#messages-tab
When open component to edition, and select sales source and KPI, it will gives you a preview.
But when you change users number from 5 to 4 or 6 for example, component become broken and stops to work both on preview and in the final email.

**Comment by anhnt** [comment]
Fixed

**Comment by Uafinder** [comment]
looks good
