### ISSUE TITLE
Points balance on the user dashboard should be rounded

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5688]
![image](https://user-images.githubusercontent.com/1945230/42723621-070a53ce-876a-11e8-9f4b-87fd5fdc9a07.png)
http://vladtest53d.admin.kademi-ci.co/manageUsers/17015824/#summary-tab
Login as this user
http://vladtest53dsales-vladtest53d.kademi-ci.co/dashboard

**Comment by trungjc** [comment]
This is a part of reward store
But we don't want to update reward store
It will be replace by Kcom2 in future

**Comment by bradmac** [comment]
yep, so closing
