### ISSUE TITLE
Send test email failing

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#5691]
Cannot send a test email from a journey. Error:  Sorry, we couldnt send the test. Please contact the administator to help find the problem.

http://schneiderelectric.admin.kademi.com.au/funnels/on-boarding-journey/version1/emailAction-240fcc/#summary-tab

Same issue with this account http://rhipe.admin.kademi.com.au/funnels/first-journey/version1/emailAction-9c0fd6/#summary-tab

**Comment by bradmac** [comment]
Duplicate -
