### ISSUE TITLE
Updating the lead assignee updates all tasks in the lead to the new assignee 

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#5699]
http://kcrm-kademi.kademi.us/leads/47202375/

![image](https://user-images.githubusercontent.com/2201340/42804763-3e456bbe-89ed-11e8-827f-e8f49ab9a710.png)

![image](https://user-images.githubusercontent.com/2201340/42804781-492facec-89ed-11e8-87f6-d3ceec4c9dce.png)

**Comment by bradmac** [comment]
Fixed
