### ISSUE TITLE
Bug in MembershipList filterByGroupFolder

### ISSUE THREAD

**Issue by mrdadah** [Kademi/kademi-dev#5700]
In MembershipList.java 
**filterByGroupFolder** method currently compares input params with groupName instead of groupFolderName

![image](https://user-images.githubusercontent.com/11255121/42817187-02e6f4d2-89d6-11e8-9f17-f5de84d308fa.png)

**Comment by mrdadah** [comment]
https://github.com/Kademi/client-vaya-vayability/issues/40

**Comment by bradmac** [comment]
Done
