### ISSUE TITLE
docs.kademi.co fails to load rocketchat.

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#5702]
Seems that the docs pages keep loading, and it shows the loading symbol in browser tab.

Think it's trying to load the following.
https://chat.kademi.co/packages/rocketchat_livechat/assets/rocketchat-livechat.min.js

Edit: here's an example page
http://docs.kademi.co/programs/admin/content01/coneml/psetup-content-type.html

**Comment by bradmac** [comment]
I think thats because KChat runs on our office server
