### ISSUE TITLE
KCriteria to allow paging 

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#5709]
Currently KCriteria doesn't allow paging (only starts from 0 and you can control max size)

**Comment by mkhoudary** [comment]
Done that..

**Comment by bradmac** [comment]
Please see my code review comment here..
https://github.com/Kademi/kademi-platform/commit/5af27546d73a96634aae76a4f8540cbc4003388e#r29747744

**Comment by bradmac** [comment]
I suggest moving instantiation of SearchProperties to KCriteriaBuilders, so it can be passed to the existing method which takes it as an argument

**Comment by mkhoudary** [comment]
Done..
