### ISSUE TITLE
Could not update specific profile email address

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5712]
![image](https://user-images.githubusercontent.com/1945230/42876704-2dc00c88-8a90-11e8-90c1-4d62a4fc7092.png)
http://kademi.admin.kademi.us/manageUsers/21695149/#general-tab
I setup email instead of my id, but it gives me error

**Comment by bradmac** [comment]
i think the source of this error might have been fixed today, in which case just doing a deploy should sort it out

**Comment by Uafinder** [comment]
it works now, @mkhoudary  found an existed deleted profile
