### ISSUE TITLE
Recognition wall, replies don't show

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#5713]
ForumManager doesn't return replies to a post.

**Comment by mkhoudary** [comment]
Done..

**Comment by bradmac** [comment]
@mkhoudary please see my code review comment:
https://github.com/Kademi/kademi-platform/commit/50131e3969bc874c5bb685fe8e81d3e55645530b

**Comment by mkhoudary** [comment]
After discussion we agreed that the modification is correct
