### ISSUE TITLE
API to delete a post

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#5715]
We need an API to delete a post, but it shall be careful to allow deleting the post only by the poster or by the owner of the top level post.

**Comment by mkhoudary** [comment]
Done.. @mrdadah please autoload on CI then try it..

**Comment by bradmac** [comment]
@mkhoudary please see my comments
https://github.com/Kademi/kademi-platform/commit/3f1cd5a2bd4e9ec4e8aea7aad1bd8e971cb3f570#r29757531

https://github.com/Kademi/kademi-dev/commit/ea7c3b07a3a77648f14f1ec858a72201f88ec692#r29757543

**Comment by mkhoudary** [comment]
@mrdadah please check now..

**Comment by mrdadah** [comment]
It still needs manual re-index to delete records

**Comment by mkhoudary** [comment]
Fixed that..

**Comment by mrdadah** [comment]
Works fine
