### ISSUE TITLE
API to report a post

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#5717]
While the feature exists in the legacy forum app, we need to have this extended to the KForum and the new  manager/service.

**Comment by mkhoudary** [comment]
@mrdadah this is done..

**Comment by mrdadah** [comment]
When I call report post API it throws an exception 

`class java.lang.NullPointerException::Name is null
- java.lang.Enum.valueOf(Enum.java:236)
- io.milton.cloud.server.db.PostReport$ReportCategory.valueOf(PostReport.java:86)
- co.kademi.server.forums.ForumManager.report(ForumManager.java:210)
- jdk.nashorn.internal.scripts.Script$Recompilation$8789$4353$\^eval\_.reportPost#L:130(/APP-INF/app.js:133)`

and here is line 130 to 134 in app.js
`transactionManager.runInTransaction(function () {
        log.info("reportPost: postId={}", postId);

        services.forumManager.report(postToReport, category, page.href, comment);
    });`

**Comment by mrdadah** [comment]
Works fine
