### ISSUE TITLE
Make photo component accept percentage for width and height 

### ISSUE THREAD

**Issue by OlaAkeela** [Kademi/kademi-dev#5718]
Please make photo component accept the percentage value, eg: 50% for its width and height attributes.

**Comment by bradmac** [comment]
Hi @OlaAkeela can you please give an example of where you would want to do this?

**Comment by OlaAkeela** [comment]
I needed it for https://github.com/Kademi/projects/issues/277 for the image that takes the whole screen in width.

**Comment by bradmac** [comment]
you would normally do that just placing the image in a full width container. but not relevant now
