### ISSUE TITLE
Error when generating cert - 3DN

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#5721]
I saw this in log 
```
Cant load children, directory node is null: /programs/prof-disability/DP01/MOD02/cert_78399848/
```

Logged in as this profile and download any cert on dashboard to reproduce: http://3dn.admin.kademi.com.au/manageUsers/120530235/#learningAppTab-tab

However the cert is still there when view it directly so i think there is problem at ModuleFolder.java, checkRedirect method

http://www.idhealtheducation.edu.au/programs/prof-disability/DP01/MOD02/cert_78399848/certificatePreview.pdf

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/42987946-18ee8122-8c25-11e8-8361-7de27e76a931.png)

**Comment by Uafinder** [comment]
I think it's related to CPD points

I've tested certificate download issue and it seems like connected to CPD points
When certificate has 0 CPD points bug appears and when click download certificate it redirects you to module page.
When certificate has some CPD points amount - everything works like intended.

reproduced that problem on CI
http://vladtest53g.admin.kademi-ci.co/manageUsers/17082114/#learningAppTab-tab

**Comment by bradmac** [comment]
Correct, a zero point CPD would mean that no CPD Award was generated, and thats what a cert is generated for. I've changed to always product a CPD Award.

**Comment by Uafinder** [comment]
Well, looks fine now on CI
I suppose we need to deploy to ensure it works on prod?

**Comment by bradmac** [comment]
Will do today

**Comment by Uafinder** [comment]
yup, seems to be fine now
