### ISSUE TITLE
Need a field to return profile parent org ids

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#5734]
Need to return profile parent org ids in a variable to be used in some asset queries

**Comment by mkhoudary** [comment]
Done

**Comment by mkhoudary** [comment]
@Uafinder you can test this by either adding this as a KCode and seeing the parent org ids showing or by writing that in an asset query, whatever easier for you.

**Comment by Uafinder** [comment]
Looks good
