### ISSUE TITLE
Assets to become alphabetically ordered in KEditor

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#5739]
Hi Team,

Another small implementation that would make a huge impact would be to alphabetically order items in dropdown lists and items within Asset Manager.

Perhaps the site I'm working on, being a multi-lingual site, has an above average set of selectbox options, and it's making searching for items a rather painful experience.

### Examples:

**Display text assets from a query**:
http://spinsurance.admin.kademi.com.au/funnels/contact-us-autoresponder/version1/emailAction-46de3a/#message-tab
Both "Single Assets" and "Asset Queries".

**Asset Manager**:
Would be nice for this list to be alphabetically ordered too.
And if this is going to be by type, then alphabetically within groups of Type.
http://spinsurance.admin.kademi.com.au/asset-manager/

Let me know if you need more examples an/or screenshots.

Thanks

**Comment by bradmac** [comment]
Actually, I'd like to change this to use a proper search field. Should also have ordering, but using a type-ahead UI or modal.

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/43106644-b2a336e0-8f2d-11e8-82ab-cac4db1d1e3f.png)

**Comment by bradmac** [comment]
And also in the editor property panels for asset components

**Comment by stephen-fueldesign** [comment]
FYI: Here are some screenshots to show how it's displayed.

I like Brad's idea of having a search as well, that would be next level.

<img width="325" alt="select-an-asset" src="https://user-images.githubusercontent.com/39784677/43107118-a864f040-8f2f-11e8-9add-9a1d720e891e.png">

<img width="785" alt="asset-manager" src="https://user-images.githubusercontent.com/39784677/43107116-a83bcba2-8f2f-11e8-93a5-c4cf3d680f06.png">

**Comment by bradmac** [comment]
:+1:  .. yep, we should change that from a select to a search field

**Comment by bradmac** [comment]
New UI:
![image](https://user-images.githubusercontent.com/826458/45607355-0ff44300-baa0-11e8-8441-10551aae1bb9.png)
