### ISSUE TITLE
Saving from OCR review modal should not remove columns

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5746]
Related to https://github.com/Kademi/kademi-dev/issues/5673

When i click Save i get a warning about unselected columns being removed.

Columns should not be removed at this step, the save operation should just save the claim data as it is currently shown. 

![image](https://user-images.githubusercontent.com/826458/43177203-2a46cca0-901b-11e8-811f-078979eba6f6.png)

**Comment by tuzzmaniandevil** [comment]
Is there any reason to remove columns at all?
