### ISSUE TITLE
Badge image upload issue

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5750]
![image](https://user-images.githubusercontent.com/1945230/43195777-b70fcc2a-900e-11e8-94cb-7920a541dc65.png)
http://vladtest53hh.admin.kademi-ci.co/recognition/17200442/

13:28:29 ERROR io.milton.http.StandardFilter  - exception sending content
13:28:29 java.lang.NullPointerException
13:28:29 	at org.hibernate.proxy.HibernateProxyHelper.getClassWithoutInitializingProxy(HibernateProxyHelper.java:47)
13:28:29 	at io.milton.cloud.server.repoapps.ControllerResource.dataBind(ControllerResource.java:563)
13:28:29 	at jdk.nashorn.internal.scripts.Script$Recompilation$8711$3222$\^eval\_.L:3#_uploadBadgeImage#L:96(/APP-INF/admin/manageBadge.js:102)
13:28:29 	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
13:28:29 	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
13:28:29 	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
13:28:29 	at jdk.nashorn.api.scripting.ScriptObjectMirror.call(ScriptObjectMirror.java:117)
13:28:29 	at io.milton.cloud.server.repoapps.ControllerMappingList.executeJs(ControllerMappingList.java:1262)
13:28:29 	at io.milton.cloud.server.repoapps.AppTransactionManager.lambda$runInTransaction$0(AppTransactionManager.java:91)
13:28:29 	at io.milton.cloud.util.SessionManagerUtils.lambda$executeInSessionAndTransaction$0(SessionManagerUtils.java:118)
13:28:29 	at io.milton.cloud.util.SessionManagerUtils.executeInTransaction(SessionManagerUtils.java:248)
13:28:29 	at io.milton.cloud.util.SessionManagerUtils.produceInSessionAndTransaction(SessionManagerUtils.java:131)
13:28:29 	at io.milton.cloud.util.SessionManagerUtils.executeInSessionAndTransaction(SessionManagerUtils.java:117)
13:28:29 	at io.milton.cloud.server.repoapps.AppTransactionManager.runInTransaction(AppTransactionManager.java:89)
13:28:29 	at jdk.nashorn.internal.scripts.Script$Recompilation$8710$2998AAA$\^eval\_.L:3#_uploadBadgeImage(/APP-INF/admin/manageBadge.js:96)
13:28:29 	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:643)
13:28:29 	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
13:28:29 	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
13:28:29 	at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:199)
13:28:29 	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:386)
13:28:29 	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:190)
13:28:29 	at io.milton.cloud.server.repoapps.ControllerResource.executeJs(ControllerResource.java:321)
13:28:29 	at io.milton.cloud.server.repoapps.ControllerResource.processForm(ControllerResource.java:167)
13:28:29 	at io.milton.http.http11.PostHandler.processExistingResource(PostHandler.java:85)
13:28:29 	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:196)
13:28:29 	at io.milton.http.http11.PostHandler.processResource(PostHandler.java:68)
13:28:29 	at io.milton.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:127)
13:28:29 	at io.milton.http.http11.PostHandler.process(PostHandler.java:62)
13:28:29 	at io.milton.http.StandardFilter.process(StandardFilter.java:50)
13:28:29 	at io.milton.http.FilterChain.process(FilterChain.java:46)
13:28:29 	at co.kademi.server.subscription.KademiSubscriptionFilter.process(KademiSubscriptionFilter.java:48)
13:28:29 	at io.milton.http.FilterChain.process(FilterChain.java:46)
13:28:29 	at co.kademi.server.idp.IDPFilter.process(IDPFilter.java:43)
13:28:29 	at io.milton.http.FilterChain.process(FilterChain.java:46)
13:28:29 	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter$1.execute(MiltonOpenSessionInViewFilter.java:41)
13:28:29 	at io.milton.context.RootContext.execute(RootContext.java:90)
13:28:29 	at io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter.process(MiltonOpenSessionInViewFilter.java:34)
13:28:29 	at io.milton.http.FilterChain.process(FilterChain.java:46)
13:28:29 	at co.kademi.server.webcache.KademiWebCacheFilter.process(KademiWebCacheFilter.java:125)
13:28:29 	at io.milton.http.FilterChain.process(FilterChain.java:46)
13:28:29 	at io.milton.http.HttpManager.process(HttpManager.java:158)
13:28:29 	at co.kademi.server.Kademi$1.service(Kademi.java:194)
13:28:29 	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
13:28:29 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
13:28:29 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
13:28:29 	at java.lang.Thread.run(Thread.java:748)

**Comment by bradmac** [comment]
Hi @anhnt can you look into this please? This is needed for the GH project.

**Comment by anhnt** [comment]
Fixed on version 1.0.9

**Comment by anhnt** [comment]
Looks good on GH account http://gohealth.admin.kademi-ci.co/recognition/17195731/

**Comment by Uafinder** [comment]
Looks good now
