### ISSUE TITLE
Dynamic component html structure has no [data-dynamic-href]

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#5753]
Here is button when editing a deal
![image](https://user-images.githubusercontent.com/735555/43243530-5387e782-90d1-11e8-8d83-ff2a73626716.png)

Here is when editing a normal webpage
![image](https://user-images.githubusercontent.com/735555/43243576-81f43198-90d1-11e8-9bbf-16a8576a2d20.png)

Note that we cant reproduce on normal page, so probably when edit content which is provided by custom app like traveldeal

**Comment by anhnt** [comment]
Steps to reproduce:
go to this page and change button size
https://www.travelworld.co.nz/ourDeals/test-deal/contenteditor?useHash=true

![image](https://user-images.githubusercontent.com/735555/43297818-84091032-917d-11e8-8925-16137f3582d1.png)

**Comment by bradmac** [comment]
See DynamicComponentService
```
        boolean isEditor = false;
        if ( page instanceof CommonResource ) {
            CommonResource cr = (CommonResource) page;
            isEditor = cr.is("editor");
        }

        for (Jerry compDiv : comps) {
            String href = compDiv.attr("data-dynamic-href");
            if ( !isEditor ) {
                compDiv.removeAttr("data-dynamic-href");
            }
```

**Comment by bradmac** [comment]
The edited resource needs to return true for is("editor")

**Comment by bradmac** [comment]
So i think we need to edit mappings.js in traveldeals app..
```
    /* Travel Deal Content Editor Controller */
    var contentEditorController = controllerMappings
            .websiteController()
            .enabled(true)
            .isPublic(false)
            .pathSegmentName('contenteditor')
            .defaultView(views.contentEditorView())
            .addMethod('GET', '_editTravelDeal')
            .addMethod('POST', '_saveDescription')
            .addType("html")
            .postPriviledge('WRITE_CONTENT');
```

Just .addType("editor") should do it

**Comment by anhnt** [comment]
I have added that bit ` .addType("editor")`
New buttons which were created after that work great
But old buttons which are there before the changes still dont have [data-dynamic-href]
@bradmac please advise
