### ISSUE TITLE
De-dupe profiles screen

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5759]
Should be similar to orgs dedupe screen

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/43381005-44cd6e0c-9427-11e8-85bb-5e5fcf00fa51.png)

**Comment by bradmac** [comment]
accessed from the tools menu ..
![image](https://user-images.githubusercontent.com/826458/43381070-8163b484-9427-11e8-9cc5-b3b89aea998c.png)

**Comment by Uafinder** [comment]
it works with issues
https://github.com/Kademi/kademi-dev/issues/5766
https://github.com/Kademi/kademi-dev/issues/5767
https://github.com/Kademi/kademi-dev/issues/5768
https://github.com/Kademi/kademi-dev/issues/5769
https://github.com/Kademi/kademi-dev/issues/5770
