### ISSUE TITLE
Accordion component not working in Asset Manager HTML (Web)

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#5760]
I'm having issues interacting with the Accordion Component when in the Assets Manager > HTML (web) item.

**Delete**, "**Add more item**" or editing the "**question**" is not possible.

Works in Edit a page mode, just not in Asset Manager.

p.s also "Add more item" is not proper english. Perhaps "Add another item" is better suited text :)

**Comment by bradmac** [comment]
Example - http://spinsurance.admin.kademi.com.au/asset-manager/97484861-1a9f-493d-b4df-2df72a534de4

**Comment by anhnt** [comment]
I have fixed the bug which is described on the issue. However we have another issue: Cant edit accordion heading text when editing asset content

**Comment by anhnt** [comment]
Fixed and deployed to AU and updated spinsuarance

**Comment by stephen-fueldesign** [comment]
I can confirm this is working.
