### ISSUE TITLE
Profile index parentOrgs doent get updated when changing org parent

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#5762]
```
"parentOrgs" : [
            106659627,
            81393676,
            82999944,
            81939784
          ],
```

Profile: http://viri.admin.kademi.com.au/manageUsers/83000464/#general-tab
Her org: http://viri.admin.kademi.com.au/organisations/82999944/edit/
New Parent org: http://viri.admin.kademi.com.au/organisations/82077292/edit/
Old parent org: http://viri.admin.kademi.com.au/organisations/81939784/viewDetails
But parentOrgs stores old org id which is 81939784

**Comment by anhnt** [comment]
This is affecting Viri account that Sarah has reported

**Comment by bradmac** [comment]
Its updated now..
            106659627, - Viridian Headoffice 
            81393676, -  Viridian 
            82077292, - Viridian Glass - Kevin Lowe 
            82999944 -  LV & SG NELSON ALUMINIUM LTD
