### ISSUE TITLE
Need a way to set group membership value

### ISSUE THREAD

**Issue by mkhoudary** [Kademi/kademi-dev#5764]
We need some way to set field values for a group membership.. just like for lead..

**Comment by mkhoudary** [comment]
Done.. can be used using MembershipBean like this:

` currentUser.primaryMembership.useGroupMembership(function(groupMembership) {
            groupMembership.setFieldValue('sample', '123');
        });`

**Comment by mkhoudary** [comment]
@bradmac please close if all good

**Comment by bradmac** [comment]
As discussed, the problem with this is that events wont get fired to update the search index

So best to move this to a manager, the new UserManager would be good

**Comment by mkhoudary** [comment]
Done
