### ISSUE TITLE
Accessing dedupe page first cause code appears

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5766]
![image](https://user-images.githubusercontent.com/1945230/43394295-e01890fa-9402-11e8-862b-34236366b4f0.png)
http://vladtest53kk.admin.kademi-ci.co/manageUsers/dedupe

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/43426579-374f2e86-94aa-11e8-8626-67deb4534f3c.png)

**Comment by bradmac** [comment]
Fixed

**Comment by Uafinder** [comment]
looks good
