### ISSUE TITLE
username dedupe profiles mode doesn't work

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5767]
http://vladtest53kk.admin.kademi-ci.co/manageUsers/dedupe?matchId=match-username&destMode=
![image](https://user-images.githubusercontent.com/1945230/43394354-1aad68bc-9403-11e8-8e84-cbb8e6ca6bf0.png)

table with content doesn't appears

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/43427928-dc4f4c22-94af-11e8-92d1-7f0cc9d4bddd.png)

**Comment by Uafinder** [comment]
Looks fine
