### ISSUE TITLE
dedupe page - both users and orgs menu highlighted

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5769]
![image](https://user-images.githubusercontent.com/1945230/43394874-ca08fa1e-9404-11e8-8b7f-9236e4ca3a62.png)
http://vladtest53kk.admin.kademi-ci.co/manageUsers/dedupe

**Comment by bradmac** [comment]
Fixed
![image](https://user-images.githubusercontent.com/826458/43428986-2e8e3444-94b5-11e8-8f18-23f2b043381b.png)

**Comment by Uafinder** [comment]
Yup, fine now
