### ISSUE TITLE
Keditor: photo component enhancements

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5771]
Please add the ability to set margin and padding on images, similar to other buttons etc.

![image](https://user-images.githubusercontent.com/826458/43423123-9d478022-949f-11e8-8b2c-d831656be376.png)

Also, please add the ability to select alt format resolutions, to make it easy for users to downsize large images.

Eg for this image http://deloitteweb-deloittefraudtraining.kademi.com.au/_hashes/files/c90ac7389a834e88844c334c9ad435ee7392e6c4

The user should be able to select 300x300 to product this URL:
http://deloitteweb-deloittefraudtraining.kademi.com.au/_hashes/files/c90ac7389a834e88844c334c9ad435ee7392e6c4/alt-300-300.png

Standard resolutions are:
- 150, 150
- 300, 300
- 320, 150
- 600, 400
- 640, 480
- 640, 640
- 400, 600
- 420, 290
- 800, 300
- 800, 455
- 1000, 500

**Comment by bradmac** [comment]
Notify Jane when done

**Comment by anhnt** [comment]
Done

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/43436280-eaebc726-94ad-11e8-8ea6-9fb2a8701bae.png)

**Comment by bradmac** [comment]
Needs content-lib 1.3.7

**Comment by Uafinder** [comment]
looks good
