### ISSUE TITLE
new lead analytics page

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#5774]
Breakdown task from https://github.com/Kademi/kademi-dev/issues/5599

**Comment by anhnt** [comment]
https://preview.uxpin.com/e3a2a9f91e732e9b83bd8a8767f8d3f5785da182#/pages/86048163/simulate/sitemap?mode=i

**Comment by bradmac** [comment]
Closing as duplicate https://github.com/Kademi/kademi-dev/issues/5853
