### ISSUE TITLE
Uploading categories doesnt work properly in multi-accounts

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5776]

**Comment by bradmac** [comment]
@Uafinder please check uploading product in categories, particularly in situations where there are multiple child accounts for a parent account.

**Comment by bradmac** [comment]
Also note that all uploads through the uploader wizard framework should be logged to the stream
Eg
![image](https://user-images.githubusercontent.com/826458/43496037-278816c6-958f-11e8-867c-a845212b4707.png)

**Comment by Uafinder** [comment]
OK, looks fine
