### ISSUE TITLE
Ability to change blogs article URL slug

### ISSUE THREAD

**Issue by yrsengar** [Kademi/kademi-dev#5779]
Once you have published the article you are not able to change the URL slug but it would be a nice feature to have.

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/43612890-c7e12414-9701-11e8-9dde-9a6f679ba78d.png)

![image](https://user-images.githubusercontent.com/826458/43612916-da2f5a46-9701-11e8-8c09-7cbcabb70988.png)

**Comment by bradmac** [comment]
And note that you can edit the blog name (ie path) from manage blogs:
![image](https://user-images.githubusercontent.com/826458/43615941-3e78d228-970e-11e8-82f4-44de4ce14aa5.png)

**Comment by Uafinder** [comment]
I think, the idea was to change "blog-path" attribute while article is published.
![image](https://user-images.githubusercontent.com/1945230/46737847-45f2a480-cca5-11e8-8829-0896888ccd06.png)
There is no Save button
http://vladtest54.admin.kademi-ci.co/blogs/myblog1/article123/#activity-tab

**Comment by bradmac** [comment]
Aha, got it. The intention is that the author should unpublish, change, and then re-publish.

This is because kademi supports a publishing workflow where changes can be reviewed before being published
