### ISSUE TITLE
Certificates generating issue

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5780]
so the issue i can see is that the link in the admin is to the generated file
but it should be to the path that generates the pdf
(c) Brad
https://github.com/Kademi/client-zoetis/issues/328

**Comment by bradmac** [comment]
Made a change so now existing cert files should be ignored

**Comment by Uafinder** [comment]
is it already applied to Zoetis account?
https://zoetis.admin.kademi.com.au/manageUsers/76866264/#learningAppTab-tab

**Comment by bradmac** [comment]
@Uafinder please see deployment notes here
https://chat.kademi.co/channel/deployment-followup

**Comment by Uafinder** [comment]
looks good after deploy
