### ISSUE TITLE
Sales claim / OCR process - capture store

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5781]
We need to associate sales data records with a new field to capture the store it was sold through, even when its attributed to an individual sales person.

SalesDataRecord has this new field:
```
private Organisation salesTeam; // the team a participant is part of which should be associated with the sale
```

To support this we need to:
- when an OCR claim is submitted from the front end, the claim should capture the current org. Use services.queryManager.currentTeamOrg (see QueryManager line 209). This should be captured at the claim level (not claim item)
- note that this is optional for claims
- the sales team should be displayed when processing OCR and editing/reviewing the claim (if present)
- this should be enterable when creating a new claim
- when claims are approved this value should be set on all sales data records in the new salesTeam field

Related - https://github.com/Kademi/kademi-dev/issues/5673#issuecomment-409757344

**Comment by tuzzmaniandevil** [comment]
Some questions :-)

- When uploading an OCR from the Admin, should the user be able to pick an org?
- When selecting/editing a salesTeam org, What org's should be displayed? All org or only certain orgs?

**Comment by bradmac** [comment]
> When uploading an OCR from the Admin, should the user be able to pick an org?

Yes, basically an admin needs to be able to do an upload  on behalf of  a customer, so they need to be able to select a store (optional)

> When selecting/editing a salesTeam org, What org's should be displayed? All org or only certain orgs?

Its fine to allow selecting any org.

**Comment by tuzzmaniandevil** [comment]
@bradmac Found a bug with the salesTeam displaying in the dataseries, the "getHistory" method of "ManageSalesDataSeriesFolder" is returning a list of "RecordBean" which doesn't have the salesTeam field on it yet.

**Comment by tuzzmaniandevil** [comment]
Some pull Requests :-)

https://github.com/Kademi/kademi-platform/pull/20

https://github.com/Kademi/kademi-dev/pull/5795

**Comment by tuzzmaniandevil** [comment]
@bradmac Do you want to check my work and see if it's what you wanted?
I tested it and saw the salesTeam being set (Except for the above bug) and you can edit the sales team as well.

**Comment by bradmac** [comment]
Merged, will check ..

**Comment by bradmac** [comment]
Looks good! Over to @Uafinder for testing

**Comment by bradmac** [comment]
@Uafinder can you process this asap?

**Comment by Uafinder** [comment]
@bradmac  Could describe more simply in two words?

**Comment by bradmac** [comment]
I think this is all good, tested elsewhere
