### ISSUE TITLE
Products - Unable to edit a product image once uploaded.

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#5784]
Unlike image assets within KEditor, I am unable to edit a product image once uploaded.

Furthermore, when uploading an image to being with, and even if you crop the image, it only crops by ratio and not by size. Example, the images I'm getting are 4.3mb, and cropping does not affect the size, they are still 5000k wide and there is no option to make the size / resolution less.

**Comment by anhnt** [comment]
UI and ajax is done. I have added java code to store product image but it's not done.
@bradmac please help me complete it at method 'addOrUpdateProductImage`

**Comment by bradmac** [comment]
@anhnt i cant see the UI working currently. I see the full mselect url including asset search, but i dont see the current image or an edit button

![image](https://user-images.githubusercontent.com/826458/46181867-56596580-c31c-11e8-85d9-f56688c34888.png)

**Comment by bradmac** [comment]
I've refreshed libs locally, and checked for js errors

**Comment by bradmac** [comment]
I've made some changes, have a look and let me know if any questions

**Comment by anhnt** [comment]
http://rootorg.admin.kademi-ci.co/products/109674/#panel_details-tab

**Comment by Uafinder** [comment]
Looks simple and good
