### ISSUE TITLE
Content types - Unable to set a multiline textarea field type.

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#5785]
Example: If I want to add a category description (HTML/text) or even just multi-lined textarea as an additional Attribute the only option I can use is text field.

Same for products, often times I may want to add an HTML/text content for, say, tab content in a product description. There is no provision for this.

**Comment by bradmac** [comment]
:+1:

**Comment by bradmac** [comment]
Updated XML structure:
```
<contentType>
  <name>Pet</name>
  <abstractType>false</abstractType>
  <fields>
    <typedField>
      <name>petName</name>
      <indexed>true</indexed>
      <text>petName</text>
      <title>Pet name</title>
      <required>true</required>
      <rows>10</rows>
    </typedField>
  </fields>
</contentType>
```

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/43618422-3d5b0f7e-971c-11e8-9551-a25c14779426.png)


![image](https://user-images.githubusercontent.com/826458/43618411-31977772-971c-11e8-8f0a-2543f36a3591.png)

**Comment by Uafinder** [comment]
Looks good
