### ISSUE TITLE
When profile is disabling note that says profile enabled appears

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5789]
![image](https://user-images.githubusercontent.com/1945230/43567638-ffc2d91c-963a-11e8-9e20-107518a4554b.png)
http://vladtest53mm.admin.kademi-ci.co/manageUsers/17285211/#summary-tab

**Comment by bradmac** [comment]
Fixed, just a typo

**Comment by Uafinder** [comment]
Ok!
