### ISSUE TITLE
Lead is fired on disabled profile

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5790]
Depends on Dixie issue
https://github.com/Kademi/client-hinda-dixie/issues/179#issuecomment-409704598

When you have an active lead and profile is disabled it doesn't move forward
But when some conditions met for starting new lead - it starts.
http://vladtest53mm.admin.kademi-ci.co/manageUsers/17285398/#summary-tab
Add this user to sales group, and lead will starts no matter of that user is disabled.

**Comment by bradmac** [comment]
Just checking, you know we have loginAsUserComponent.html .. ? in user-lib

**Comment by Uafinder** [comment]
looks good now
