### ISSUE TITLE
Enhance sales incentives page

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5794]

**Comment by bradmac** [comment]
Now has pagination and export to CSV
![image](https://user-images.githubusercontent.com/826458/43681671-e042a79a-98ae-11e8-8767-b691ca1a87fc.png)

**Comment by Uafinder** [comment]
I can't find that page in fresh account
http://vladtest53p.admin.kademi-ci.co/points-allocations/
In rootorg i found that page but it doesn't looks good
![image](https://user-images.githubusercontent.com/1945230/43961452-b0935e00-9cbd-11e8-96aa-fddd8c668173.png)

**Comment by bradmac** [comment]
You need to have the lastest version of salesdata-lib installed

That is the correct page, just a small cosmetic issue with the paginator when there are few records

Note that to see records on this page you need to have
- a sales data series
- with a points allocation source setup
- import records into the series
- run points allocation to award points

**Comment by Uafinder** [comment]
I've a last version installed but still don't see that page
![image](https://user-images.githubusercontent.com/1945230/44264744-67e32400-a22c-11e8-9dfc-a61e82ed824c.png)

![image](https://user-images.githubusercontent.com/1945230/44264757-77fb0380-a22c-11e8-89c1-234e7fb3606b.png)

http://vladtest53rr.admin.kademi-ci.co/manageApps/#installed-tab

**Comment by bradmac** [comment]
This is part of the Rewards app

Enabled now..

http://vladtest53rr.admin.kademi-ci.co/points-allocations/

**Comment by Uafinder** [comment]
Looks fine!
