### ISSUE TITLE
Extra Fields in Groups

### ISSUE THREAD

**Issue by faithtek** [Kademi/kademi-dev#5806]
In the extra fields section under groups -- seen here: http://asrdev.admin.kademi.us/groups/participants/

![image1](https://user-images.githubusercontent.com/7914822/43748117-c29b6552-99bb-11e8-8b3f-45b6b41ca585.png)

Editing does not work. Editing just adds a new "extra field" with the new values of the item that you clicked to edit.

Also, Removing an item does not remove. As soon as the page is saved and refreshed the item that you wanted removed comes back.

**Comment by bradmac** [comment]
Fixed in next deploy
