### ISSUE TITLE
Create a KPI leaderboard component

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5807]

**Comment by bradmac** [comment]
Mostly done.

**Comment by bradmac** [comment]
We're going to need some styling..

![image](https://user-images.githubusercontent.com/826458/43889272-d5acd5be-9c17-11e8-9a05-72c4d32e0459.png)

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/43891963-e19d4e44-9bf4-11e8-9d4c-7c6373c3c941.png)
Done

**Comment by Uafinder** [comment]
Looks good
