### ISSUE TITLE
review claim amount column incorrect

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5808]
![image](https://user-images.githubusercontent.com/1945230/43774416-ad10f8dc-9a51-11e8-8c02-64771b8a3093.png)
Spot on GH
http://gohealth.admin.kademi-ci.co/manageSaleDataClaimer/#claims-list-tab
Same on QA

**Comment by bradmac** [comment]
Looks ok now, must have been fixed already
![image](https://user-images.githubusercontent.com/826458/45605277-fba84a00-ba8f-11e8-91a7-55406aaf92b0.png)
