### ISSUE TITLE
Sales data import performance improve

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5809]
I’ve tested a file with 10k rows (added two custom fields to capture serial and model).
This file upload duration – 43 minutes.
As it usually happens on the start speed was greater but after 2000 rows upload speed decreased and takes 5 row per second (approx.)
http://vladtest53o.admin.kademi-ci.co/sales/sales-claims/?query=&minValue=&maxValue=#history-tab
This account
I'm not posting file here due the prod data

**Comment by bradmac** [comment]
:+1:

**Comment by bradmac** [comment]
Should be faster now

**Comment by Uafinder** [comment]
Ok, looks much better
10000 rows - 13 minutes
![image](https://user-images.githubusercontent.com/1945230/44252425-c5fc1100-a204-11e8-81cc-88cac92c3e40.png)
