### ISSUE TITLE
menuComponent org selector should just allow selection of direct orgs

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5810]
Currently when orgselector is enabled for the menu component it displays a full search and browse component:
![image](https://user-images.githubusercontent.com/826458/43802559-3f0885c8-9aea-11e8-8a0b-755b981b8613.png)

Please change this to be just a simple pull down menu, only of orgs the user is directly associated with (not child orgs)

In most situations this will only be a small number eg 2 or 3.

If there is only 1 org the menu item should not be displayed

**Comment by anhnt** [comment]
Done

**Comment by Uafinder** [comment]
Can't force org selector to appear...
- select it in menu component
- add reporting app
- add reporting role to participant
- participant has two orgs memberships
http://vladtest53p.admin.kademi-ci.co/manageUsers/17377555/#summary-tab
http://vladtest53p.admin.kademi-ci.co/manageUsers/17377555/?loginTo=vladtest53paucstore-vladtest53p.kademi-ci.co

**Comment by anhnt** [comment]
This needs to be checked

![image](https://user-images.githubusercontent.com/735555/43968745-37654a7c-9cf2-11e8-910c-53099c1d7ce0.png)


And now it doesnt depend on reporting app anymore :)

**Comment by Uafinder** [comment]
hey, as i said in my comment i checked those checkbox in default theme template )
but it doesn't appear

**Comment by Uafinder** [comment]
doh...
well it appears, ok will check that on Monday

**Comment by Uafinder** [comment]
Looks good now
