### ISSUE TITLE
Checkout component with organisation selection

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5811]
![image](https://user-images.githubusercontent.com/826458/43802767-f8507248-9aea-11e8-9c46-ac391281120d.png)

**Comment by anhnt** [comment]
This is already available. But note that Vlad found bug 
"When more than one org appears all fields are not read-only"
https://github.com/Kademi/projects/issues/392

**Comment by anhnt** [comment]
Fixed

**Comment by Uafinder** [comment]
Can't force to appear org selector on checkout, pls advice
![image](https://user-images.githubusercontent.com/1945230/46951154-cfccb400-d08f-11e8-85b8-4603a9dea9b4.png)
http://vladtest54c.admin.kademi-ci.co/manageUsers/17921408
http://vladtest54cweb-vladtest54c.kademi-ci.co/checkout/

**Comment by anhnt** [comment]
https://github.com/Kademi/kademi-dev/issues/6263

**Comment by bradmac** [comment]
Guys, please ignore this issue.

We're going to move OTM to use kcom2, and there is an org selection as part of the checkout form.
