### ISSUE TITLE
Move recognition methods to recognition manager

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5812]
CatalogManager is for managing product catalogs, but methods relating to recognition has been added

Eg See CatalogManager line 110
```
    public Asset createAssetForRecognition(BaseRecognition r, ContentType type) {
        Session session = SessionManager.session();
        AssetManager atm = C(AssetManager.class);
```

Please move all recognition related methods to RecognitionManager

**Comment by mkhoudary** [comment]
Done..
