### ISSUE TITLE
Add brand field to products

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5815]
brands will be managed as categories

**Comment by bradmac** [comment]
Just using a text field for now because it would slow down the page to load all cats into a select box.

Would be good to change to a autocomplete field later

![image](https://user-images.githubusercontent.com/826458/43874912-758f9d9a-9be2-11e8-8dc7-bf9733f3e5c4.png)

**Comment by bradmac** [comment]
This is functional now, @anhnt can you please change the field to do autocomplete?

Also, please change the supplier field to use org-entity-finder

**Comment by bradmac** [comment]
Added to kcom2:
![image](https://user-images.githubusercontent.com/826458/43928238-4893c468-9c84-11e8-9f68-438fa4f4a151.png)

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/43954233-ea4843c4-9cc5-11e8-8bcd-484dc9593469.png)

![image](https://user-images.githubusercontent.com/735555/43954248-f6f382f0-9cc5-11e8-8cc0-4381150fcd0c.png)

**Comment by anhnt** [comment]
Done

**Comment by Uafinder** [comment]
Looks good
