### ISSUE TITLE
photo component which is inside tabs component is not rendered

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#5816]
![image](https://user-images.githubusercontent.com/735555/43880427-900da456-9bd2-11e8-812c-b251c596602b.png)

Asset to edit here http://waterware.admin.kademi-ci.co/asset-manager/e93418e6-eabc-426f-8282-d360a018f71f

**Comment by anhnt** [comment]
https://github.com/Kademi/projects/issues/438

**Comment by bradmac** [comment]
Looks ok at the moment..

Front end:
![image](https://user-images.githubusercontent.com/826458/44070229-ba2ffa9c-9fd6-11e8-8b43-824bb4ade66f.png)

Asset content:
![image](https://user-images.githubusercontent.com/826458/44070238-c74727f0-9fd6-11e8-82cf-9670a4ed51f1.png)

**Comment by bradmac** [comment]
Note that when adding images (or any other binary asset) be sure to insert it from assets, not files, otherwise the relative paths wont work.

@anhnt please confirm if there is an active issue
