### ISSUE TITLE
Funnel tester is not working

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#5818]
Garret has setup funnel tester with his domain and i tested with mailinator. no email was generated after configured timeout is passed
![image](https://user-images.githubusercontent.com/735555/43882001-540f19e8-9bd8-11e8-95f9-1bb2cba81569.png)

![image](https://user-images.githubusercontent.com/735555/43881919-036a4594-9bd8-11e8-9cbc-f737b03504a3.png)

http://movicol.admin.kademi.com.au/manageUsers/123848532/#learningAppTab-tab

**Comment by anhnt** [comment]
Module is available on version4, not the live one

**Comment by bradmac** [comment]
The lead is waiting for the module complete goal
![image](https://user-images.githubusercontent.com/826458/43883017-d7ff9c00-9c05-11e8-8dd7-67252bead9ee.png)

but there is no timeout specified for that goal

![image](https://user-images.githubusercontent.com/826458/43882985-bce8699c-9c05-11e8-8743-0b8b26e0a15c.png)

it appears the account did complete the start module goal

![image](https://user-images.githubusercontent.com/826458/43883088-1b6a8090-9c06-11e8-9e19-f3247e8a1e4c.png)

**Comment by anhnt** [comment]
Makes sense now thanks
