### ISSUE TITLE
Fix elasticsearch module activity report

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#582]
The new elasticsearch based module activity report is not working for Waterco. No results are returned.

**Comment by bradmac** [comment]
Started integrating with AppIndexer framework, but a bit to go!

**Comment by bradmac** [comment]
@tuzzmaniandevil  Waterco appears to be doubling up data points, creating some crazy graph shapes. Can you have a look?
http://admin.waterco.olhub.com/reporting/esModuleBreakdown

**Comment by bradmac** [comment]
Also, please add a date histogram widget to the dashboard.

**Comment by tuzzmaniandevil** [comment]
Histogram is done.

**Comment by tuzzmaniandevil** [comment]
I had a look at the report for waterco, all looks correct
