### ISSUE TITLE
Auctions weird expiration text

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5821]
This is from admin
![image](https://user-images.githubusercontent.com/1945230/43946619-658d60ec-9c8e-11e8-8ad9-f6d07d03b7d7.png)
All auctions is active and not expired
That's how it looks from frontend
![image](https://user-images.githubusercontent.com/1945230/43946646-7980ca08-9c8e-11e8-8571-ebc0e5d148b7.png)

But auctions not expired and there is a possibility to place a bid.
Is it could be that auctions should say Auction end soon or some sort?

**Comment by bradmac** [comment]
@Uafinder please provide URLs so i can see this issue

**Comment by Uafinder** [comment]
Account already expired, so i will need to reproduce that on a fresh one.

**Comment by Uafinder** [comment]
Couldn't reproduce it now
