### ISSUE TITLE
Issue with closing auctions when automation trigger is assigned

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5822]
We have an auction which will finish soon
And we have an automation rule which fires a email after some auction finished with a winner
![image](https://user-images.githubusercontent.com/1945230/43951401-bcc924c4-9c9b-11e8-9678-14d53fe52202.png)
![image](https://user-images.githubusercontent.com/1945230/43951407-c165ad86-9c9b-11e8-8c38-df7b7b1d06bb.png)
If it's setup that way, when auction should finish it will not finish because of automation rule and not email will fire
http://vladtest53p.admin.kademi-ci.co/autoEmails/17378498/?startDate=04/08/2018&finishDate=10/08/2018#action-tab
http://vladtest53paucstore-vladtest53p.kademi-ci.co/auctions/sample-auc6/
Affected Schneider
![image](https://user-images.githubusercontent.com/1945230/43951832-dca76692-9c9c-11e8-9c69-16c03453e12a.png)

**Comment by bradmac** [comment]
hey @Uafinder  automations are deprecated. So if the problem is just related to automation, then we just wont use automation

**Comment by Uafinder** [comment]
It's NPE
Patrick asks me to check automations configure for Schneider
![image](https://user-images.githubusercontent.com/1945230/43951875-fc4e68f6-9c9c-11e8-9ace-0fc32316d61a.png)

**Comment by bradmac** [comment]
Will not fix automations as thats deprecated

Instead will add support to journeys - https://github.com/Kademi/kademi-dev/issues/5829
