### ISSUE TITLE
Pending membership doesn't catch for group goal in journeys

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5824]
Goal not fired when you use group goal with Pending connector.
E.g. if group goal configured to fire on participants group and pending state it will not fire.
![image](https://user-images.githubusercontent.com/1945230/43953507-e21bf8c2-9ca1-11e8-9202-7d952ef761e4.png)
![image](https://user-images.githubusercontent.com/1945230/43953520-eb371860-9ca1-11e8-978b-f7299c70f42d.png)
![image](https://user-images.githubusercontent.com/1945230/43953669-60560192-9ca2-11e8-878c-1402134cdd6f.png)

http://vladtest53p.admin.kademi-ci.co/funnels/first-journey/version1/#journeyBuilder-tab
Required for Schneider

**Comment by bradmac** [comment]
The group name wasnt being reported when a membership application was created

Should work now

**Comment by Uafinder** [comment]
yup, looks fine now
