### ISSUE TITLE
Assets importer/exporter

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5826]

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/44073013-e139355e-9fe5-11e8-9bd5-2223b3f9bc77.png)

![image](https://user-images.githubusercontent.com/826458/44073020-ede2a13c-9fe5-11e8-94f6-c6ac8735e9f3.png)

**Comment by bradmac** [comment]
moved to a dropdown

![image](https://user-images.githubusercontent.com/826458/44126478-a85c0822-a08c-11e8-912f-4d296361180b.png)

**Comment by AlaaKhalaf94** [comment]
I've maked backup from vayability : http://vayability.admin.kademi-ci.co/asset-manager/ then restore it to fresh test account : http://testassetexport.admin.kademi-ci.co/asset-manager/

But I see the content of edms are empty

For example
vayability : http://vayability.admin.kademi-ci.co/asset-manager/649567a1-6e4d-41f1-acf7-fca9f920ea8a
fresh test account : http://testassetexport.admin.kademi-ci.co/asset-manager/649567a1-6e4d-41f1-acf7-fca9f920ea8a

**Comment by bradmac** [comment]
Missed setting content on text assets. Fixed now.
