### ISSUE TITLE
KFeedback doesn't appear in assets EDM editor

### ISSUE THREAD

**Issue by AlaaKhalaf94** [Kademi/kademi-dev#5828]
Kfeedback doesn't appear in assets EDM editor in spite of kfeedback app is enabled
http://qatest.admin.kademi-ci.co/asset-manager/9fd0b1c3-0210-4a94-94e1-fd89779abb32

![capture1](https://user-images.githubusercontent.com/26510030/44018831-ada77468-9ee5-11e8-86de-cdd68044f612.JPG)

**Comment by bradmac** [comment]
I think might be same issue as this .. https://github.com/Kademi/kademi-dev/issues/5816

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/44071282-5a33bd4e-9fdc-11e8-9bda-8b837e5e768d.png)

**Comment by Uafinder** [comment]
Looks good
