### ISSUE TITLE
Extend shopping cart goal to support auctions

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5829]
Related https://github.com/Kademi/kademi-dev/issues/5822

**Comment by Uafinder** [comment]
Hey,
I am not seeing any possibility to enter some values for auctions
![image](https://user-images.githubusercontent.com/1945230/44340919-0c64a080-a48f-11e8-8a01-97028825213a.png)
Checked settings and node connections
http://vladtest53ss.admin.kademi-ci.co/funnels/first-journey/version1/#journeyBuilder-tab
http://vladtest53ss.admin.kademi-ci.co/auctions/vladtest53ssaucstore-auction/

**Comment by bradmac** [comment]
Note that this only supports the Auction Closed event, for the winner, which activates the "checkout complete" transition.

We dont support out-bid notifications currently, or notifications to non-winners

**Comment by bradmac** [comment]
However, there is one thing missing which is an option to specify the goal supports auctions. Will add that shortly.

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/44369680-4f745180-a52b-11e8-8c92-a4244d9135f2.png)

**Comment by paddyow** [comment]
Dropped in a shopping cart goal here http://schneiderelectric.admin.kademi.com.au/funnels/auction-journey/version1/#journeyBuilder-tab

Cannot see the option to support auctions.

**Comment by bradmac** [comment]
Urghhh ... the goal is in both ecom and reward store apps. I updated the ecom one.

**Comment by bradmac** [comment]
Added to rewardstore too

**Comment by paddyow** [comment]
**Email not firing**

This journey http://schneiderelectric.admin.kademi.com.au/funnels/auction-journey/version1/#journeyBuilder-tab

Tested with this profile http://schneiderelectric.admin.kademi.com.au/manageUsers/123903091/#summary-tab

Email did not fire after after the profile won the auction.

**Points not showing**

This is the auction result http://schneiderelectric.admin.kademi.com.au/auctions/test-1/#history-tab

After it closed, the profiles point balance did not see to update to show the transaction and debit http://schneiderelectric.admin.kademi.com.au/manageUsers/123903091/#pointsBucketTab-tab

**Comment by bradmac** [comment]
The auction hasnt closed yet, so there's no winner, so the goal didnt fire
http://schneiderelectric.admin.kademi.com.au/auctions/test-1/#details-tab

Thats probably because the auction was already past its closing time when it was created

**Comment by Uafinder** [comment]
Hmmm.. doesn't fire for me
http://vladtest53z.admin.kademi-ci.co/funnels/journey2/version1/#journeyBuilder-tab
http://vladtest53z.admin.kademi-ci.co/auctions/?state=closed
![image](https://user-images.githubusercontent.com/1945230/46570875-09a50880-c974-11e8-8124-2d40427dfba6.png)

**Comment by bradmac** [comment]
Please enable the journeys app for that website

![image](https://user-images.githubusercontent.com/826458/46914015-3e5c3400-cff4-11e8-8a2f-47f4b0f74286.png)

**Comment by Uafinder** [comment]
Still doesn't work
![image](https://user-images.githubusercontent.com/1945230/46936438-10fc9e00-d067-11e8-95c9-814d1c1b4cbb.png)
![image](https://user-images.githubusercontent.com/1945230/46936461-1fe35080-d067-11e8-8237-75bf56b1746d.png)
http://vladtest53z.admin.kademi-ci.co/funnels/journey2/version1/leads/

**Comment by Uafinder** [comment]
It works!

**Comment by Uafinder** [comment]
it works!

**Comment by Uafinder** [comment]
it works
