### ISSUE TITLE
Update KSurvey app to upload image within surveys

### ISSUE THREAD

**Issue by mrdadah** [Kademi/kademi-dev#5831]
Update KSurvey app to upload image within surveys

**Comment by Uafinder** [comment]
1. error in console when survey created
![image](https://user-images.githubusercontent.com/1945230/44264931-1a1aeb80-a22d-11e8-9624-48837f5841dd.png)
http://vladtest53rr.admin.kademi-ci.co/ksurvey/survey-7d0fbcf1-7ad4-4b00-b773-8bd90b721c6f/#detail-tab

2. Error while cropping image
![image](https://user-images.githubusercontent.com/1945230/44264955-3454c980-a22d-11e8-8cb3-f280926077e3.png)

https://github.com/Kademi/client-vaya-vayability/issues/138

**Comment by Uafinder** [comment]
Looks good now, fixed in other issue
