### ISSUE TITLE
Kpoll component not appearing in theme checker

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#5833]
![image](https://user-images.githubusercontent.com/2201340/44180624-c59a4200-a140-11e8-9a55-d6cb2dee475d.png)

To make the poll appear in the theme checker:
- App needs to be switched on
- A poll needs to be created and activated

So should the APP create a poll when installed, or should the admin have to set one up before they can see it in the theme checker.

**Comment by bradmac** [comment]
> A poll needs to be created and activated

Generally, when components are viewed in the theme checker and/or editor, the user should see how the component will look, ie they should see "representative content"

This should be regardless of whether polls etc have been created

**Comment by Uafinder** [comment]
Appear now
