### ISSUE TITLE
ECom: Favourites app

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5836]

**Comment by bradmac** [comment]
Note that the base product is recorded on the wishlist, not a SKU. This is same as aliexpress

![image](https://user-images.githubusercontent.com/826458/47475913-32853300-d87a-11e8-95b2-8365dc426b05.png)

**Comment by bradmac** [comment]
@anhnt please move the add to wishlist icon to the top right of the product image
![image](https://user-images.githubusercontent.com/826458/47621074-1a9dff80-db57-11e8-8b89-55bbdcd38183.png)

**Comment by bradmac** [comment]
@anhnt i think the love heart needs to be top right, not at the end of the text:

![image](https://user-images.githubusercontent.com/826458/47678809-88196100-dc27-11e8-863f-9a0781375123.png)

like on the waterware creative:

![image](https://user-images.githubusercontent.com/826458/47678786-79cb4500-dc27-11e8-98e4-649336539261.png)

https://github.com/Kademi/projects/issues/472

**Comment by bradmac** [comment]
And on the product details page it should sit over the product image, not above it

![image](https://user-images.githubusercontent.com/826458/47678881-b1d28800-dc27-11e8-9d1c-3c363e888739.png)

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/47692302-0abb1400-dc5a-11e8-8135-23241ee9f0cd.png)

**Comment by anhnt** [comment]
Fixed, also fixed for list product layout

**Comment by anhnt** [comment]
KWishList 1.0.5

**Comment by Uafinder** [comment]
Looks good
