### ISSUE TITLE
Sales data import performance results

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5840]
![image](https://user-images.githubusercontent.com/1945230/44255967-686dc180-a210-11e8-8c39-c233c53c09ed.png)
10000 - 13 minutes
50000 - 71 minutes
Looks not bad
http://vladtest53rr.admin.kademi-ci.co/sales/new-series/?query=&minValue=&maxValue=#general-tab

If you think that's ok, you can close this issue
Just FYI

**Comment by bradmac** [comment]
Yep, about 1000 rows per minute is normal and acceptable
