### ISSUE TITLE
KCRM: Menu component updates

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5841]
- change leadman menu's to match the given creative
- change the menu component so that search input has the given layout
![image](https://user-images.githubusercontent.com/826458/44313800-bda11180-a462-11e8-98c3-2ec4a3dadfbb.png)

Extension to https://github.com/Kademi/kademi-dev/issues/5599
Creative
https://preview.uxpin.com/e3a2a9f91e732e9b83bd8a8767f8d3f5785da182#/pages/87029710/simulate/sitemap?mode=i

**Comment by bradmac** [comment]
Menu items dont exactly match design, but i think this is fine
![image](https://user-images.githubusercontent.com/826458/44322403-2909d400-a4a1-11e8-8c5a-25c61440e0d0.png)

![image](https://user-images.githubusercontent.com/826458/44322410-32933c00-a4a1-11e8-9b7c-28cf31f6612a.png)

**Comment by bradmac** [comment]
And i think the search box is close enough
![image](https://user-images.githubusercontent.com/826458/44322442-61a9ad80-a4a1-11e8-9938-8e92dc110e3b.png)

**Comment by bradmac** [comment]
> these are links to and leading to error pages

Fixed. Note that these are headings, so shouldnt go anywhere

**Comment by Uafinder** [comment]
I'm not seeing 1.3.9 version in rootorg
![image](https://user-images.githubusercontent.com/1945230/44665434-91673100-aa1e-11e8-844a-a95ba79b7d19.png)
Could you check?

**Comment by anhnt** [comment]
updated lib

**Comment by Uafinder** [comment]
Looks good now
