### ISSUE TITLE
KCRM: Updated leads page layout

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5843]
![image](https://user-images.githubusercontent.com/826458/44313864-f2619880-a463-11e8-9537-8c908d719f82.png)

(ignore the plus button in the creative)

**Comment by bradmac** [comment]
@anhnt please update the filter section to make the creative
![image](https://user-images.githubusercontent.com/826458/44313870-102efd80-a464-11e8-817e-1ceaade76f13.png)

**Comment by bradmac** [comment]
> pencil icon not in place

Ignore that.

**Comment by bradmac** [comment]
> assigned to is empty

I'll look into this

**Comment by bradmac** [comment]
@Uafinder please configure teams correctly

See team config here - http://vladtest53ss.admin.kademi-ci.co/teamGroups/#teams-tab

Currently the team org type is "sales-team"
![image](https://user-images.githubusercontent.com/826458/44624137-8ededb80-a939-11e8-946c-2a63cb098a2c.png)

The assigned-to list shows profiles in those organisations which the current user is in.

Eg if the current user is in "team1" and "team2" the assign-to list will be all people in team1 and team2

**Comment by Uafinder** [comment]
Assigned to it's a different question...

my suggestion:
1. Add pagination
http://vladtest53ssweb-vladtest53ss.kademi-ci.co/leads/?query=&leadType=active
When there are more than 200 leads page become to work slowly and loading long.

**Comment by bradmac** [comment]
@anhnt can you add pagination? other option is infinite scrolling, whichever is easier

**Comment by anhnt** [comment]
added pagination as infinite scroll

**Comment by Uafinder** [comment]
ok, infinite scroll implemented

but assigned to list still empty
![image](https://user-images.githubusercontent.com/1945230/45284108-59fd8780-b4e8-11e8-9575-d8b9ea68d9ce.png)
however teams are configured correctly
![image](https://user-images.githubusercontent.com/1945230/45284177-81545480-b4e8-11e8-839f-f62d0fb4aab3.png)
http://vladtest53vweb-vladtest53v.kademi-ci.co/leads/?query=userqa01&leadType=active&from=0&size=100
Adminqa user

**Comment by anhnt** [comment]
Looks like its working ok atm

![image](https://user-images.githubusercontent.com/735555/45354548-112cf800-b5e8-11e8-8d9f-9e10d8d2891e.png)

**Comment by Uafinder** [comment]
hmm... looks fine

not sure, but better ask
Assigned to filter gives you your teammates for filtering, but should give all assigned to persons and "not assigned" selection, as well as "all assignee's"
![image](https://user-images.githubusercontent.com/1945230/45360159-66acd900-b5d7-11e8-8ca5-a004720b53c3.png)
Same for Team selector... team selector gives you only your team for selection, should be all teams which are participated
![image](https://user-images.githubusercontent.com/1945230/45360226-9956d180-b5d7-11e8-9d77-ecfc51675fd4.png)
http://vladtest53wweb-vladtest53w.kademi-ci.co/leads/

user: kcrmadmin2

also
score amount is changing while you search some lead
![image](https://user-images.githubusercontent.com/1945230/45360331-ec308900-b5d7-11e8-8490-6ae8f8afdb90.png)
![image](https://user-images.githubusercontent.com/1945230/45360342-f81c4b00-b5d7-11e8-820f-3ecf720dcfcc.png)
http://vladtest53wweb-vladtest53w.kademi-ci.co/leads/

Filter by assigned to in table doesn't work
![image](https://user-images.githubusercontent.com/1945230/45360529-80025500-b5d8-11e8-900f-73a3353029b6.png)
http://vladtest53wweb-vladtest53w.kademi-ci.co/leads/

**Comment by bradmac** [comment]
> score amount is changing while you search some lead

Thats ok

**Comment by bradmac** [comment]
> Filter by assigned to in table doesn't work

This is a critical bug

**Comment by bradmac** [comment]
Verified that search by assigned to does work locally:
![image](https://user-images.githubusercontent.com/826458/45389856-521d1f00-b671-11e8-8f32-15f9db120015.png)

**Comment by bradmac** [comment]
Also verified that assigned to does work in the test account:
![image](https://user-images.githubusercontent.com/826458/45389946-9e685f00-b671-11e8-9229-73e60c49426d.png)

**Comment by bradmac** [comment]
@Uafinder please confirm if the assigned to filtering issue is still active

**Comment by Uafinder** [comment]
Sorry, my bad, not filter but sorting
![image](https://user-images.githubusercontent.com/1945230/45411421-dc1eb500-b67c-11e8-8654-fcde2b047857.png)
http://vladtest53w1web-vladtest53w1.kademi-ci.co/leads/?query=&leadType=active&from=0&size=100

**Comment by bradmac** [comment]
@Uafinder I moved the sorting issue, if no other issues remain this can be closed

**Comment by Uafinder** [comment]
Closed
