### ISSUE TITLE
KCRM: Lead detail page - Lead tab + activities list

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5844]
![image](https://user-images.githubusercontent.com/826458/44313887-64d27880-a464-11e8-8dcb-8a0292c3e3eb.png)

Creative: https://preview.uxpin.com/e3a2a9f91e732e9b83bd8a8767f8d3f5785da182#/pages/86048160/simulate/sitemap?mode=i

Activities:
https://preview.uxpin.com/e3a2a9f91e732e9b83bd8a8767f8d3f5785da182#/pages/86051050/simulate/sitemap?mode=i

**Comment by bradmac** [comment]
@anhnt please update buttons. But its ok to ignore the cancel button

![image](https://user-images.githubusercontent.com/826458/44313904-b4b13f80-a464-11e8-99f3-6e6ece34e5a8.png)

**Comment by anhnt** [comment]
all done except we dont have api to delete note @bradmac please help

**Comment by bradmac** [comment]
@anhnt we have a few different layouts of buttons for timeline elements, but i think these should all be consistent

![image](https://user-images.githubusercontent.com/826458/44438297-a6a12180-a612-11e8-89b5-c2404f5db394.png)

**Comment by anhnt** [comment]
Done

**Comment by Uafinder** [comment]
Looks ok, opened some issues related to notes
https://github.com/Kademi/kademi-dev/issues/5887
https://github.com/Kademi/kademi-dev/issues/5886
https://github.com/Kademi/kademi-dev/issues/5885
