### ISSUE TITLE
KCRM: Lead details page - Company tab

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5845]
![image](https://user-images.githubusercontent.com/826458/44313976-276eea80-a466-11e8-9859-bac2cfcaf87f.png)

**Comment by bradmac** [comment]
New to implement the add company button:
![image](https://user-images.githubusercontent.com/826458/44313989-61d88780-a466-11e8-9300-d2b179c1ff7c.png)

Note that the first company section should always be shown (even when no company is entered/selected) and this is for the company related to the lead.

This should be followed by organisations the lead profile is related to (but not necessarily connected to the lead), and adding a new company should add it to the lead profile, is as a membership

**Comment by bradmac** [comment]
Done.

Note that the first panel is always shown, and this sets the organisation on the lead itself

Panels below that are related to the customers memberships.

**Comment by Uafinder** [comment]
Town\city field incorrect
![image](https://user-images.githubusercontent.com/1945230/44662933-cf148b80-aa17-11e8-9cef-5474ce48a4d4.png)
It takes value from state
http://vladtest53ssweb-vladtest53ss.kademi-ci.co/leads/17753053/?view=company

Select org id text should be improved, it's very light
![image](https://user-images.githubusercontent.com/1945230/44663032-0b47ec00-aa18-11e8-8517-322a1b7712fc.png)

Create new company cause country field to disappear, for new and for existed orgs
![image](https://user-images.githubusercontent.com/1945230/44663300-d0928380-aa18-11e8-9bcd-cef99699f00e.png)
To reproduce, click add new company, the enter new company name and hit create

Hit unlink also cause country to disappear
![image](https://user-images.githubusercontent.com/1945230/44663372-06d00300-aa19-11e8-834e-77df33ea6752.png)

**Comment by anhnt** [comment]
All fixed

**Comment by Uafinder** [comment]
Country field now hided when you add or remove organisations
![image](https://user-images.githubusercontent.com/1945230/44774502-f08e8800-ab7b-11e8-9c01-de27df0376e5.png)
E.g. add or unlink
http://vladtest53tweb-vladtest53t.kademi-ci.co/leads/17756149/?view=company

**Comment by anhnt** [comment]
Fixed

**Comment by bradmac** [comment]
> No validation on create new company on name - possibility to add companies with same name

> Create new company link on hover cursor should become clickable... Now it's flat

@Uafinder please move these to a seperate issue, i'd suggest p3. If there are not other issues this can be closed

**Comment by Uafinder** [comment]
Looks good
