### ISSUE TITLE
KCRM: Lead details page - contact tab

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5846]
![image](https://user-images.githubusercontent.com/826458/44314013-c3005b00-a466-11e8-8979-36242059762d.png)

https://preview.uxpin.com/e3a2a9f91e732e9b83bd8a8767f8d3f5785da182#/pages/86049228/simulate/sitemap?mode=i

**Comment by bradmac** [comment]
> Address fields

The issue here is that we dont have any address fields on profile, only on organisation. Previously these have been held as custom fields, but i've created an issue to make this standard:

https://github.com/Kademi/kademi-dev/issues/5861

**Comment by bradmac** [comment]
> Middle name placeholder text

We dont currently have a middle name field, and i'm not sure if we need it. Moved here https://github.com/Kademi/kademi-dev/issues/5862

**Comment by bradmac** [comment]
> Tags
> Console error

Fixed through setting missing libs

> Missed mobile number

Also will address this here https://github.com/Kademi/kademi-dev/issues/5862

**Comment by bradmac** [comment]
> Concept contains three buttons (cancel, lost, won). Our page contains only lost and won. Besides that, won doesn't contain amount near it.

This is covered here - https://github.com/Kademi/kademi-dev/issues/5844#issuecomment-414160840

**Comment by bradmac** [comment]
@Uafinder all the issued you mentioned are either resolved or addressed on other issues.

So back to you, please close this issue if there's nothing else.

**Comment by Uafinder** [comment]
Title field not saving while changing
![image](https://user-images.githubusercontent.com/1945230/44395558-e698d380-a542-11e8-9157-14595740c7ab.png)
http://vladtest53ssweb-vladtest53ss.kademi-ci.co/leads/17730771/?view=contact
Besides that looks fine

**Comment by Uafinder** [comment]
job title always said that there is no matching job title found
![image](https://user-images.githubusercontent.com/1945230/44662527-b22b8880-aa16-11e8-9745-9a1db38238ea.png)
http://vladtest53ssweb-vladtest53ss.kademi-ci.co/leads/17752981/?view=contact

**Comment by anhnt** [comment]
Fixed, please rebuild

**Comment by Uafinder** [comment]
it works, my bad
