### ISSUE TITLE
KCRM: Company details page

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5848]
![image](https://user-images.githubusercontent.com/826458/44314604-3c9c4700-a46f-11e8-8573-4a557175853c.png)

https://preview.uxpin.com/e3a2a9f91e732e9b83bd8a8767f8d3f5785da182#/pages/86129357/simulate/sitemap?mode=i

**Comment by Uafinder** [comment]
1.Could not save details for org, i think due the missed permissions (admin role)
![image](https://user-images.githubusercontent.com/1945230/44338759-a6284f80-a487-11e8-8b7a-ce1ef08b8cfd.png)
http://vladtest53ssweb-vladtest53ss.kademi-ci.co/companies/17723581

2. Tags also doesn't work
![image](https://user-images.githubusercontent.com/1945230/44338792-c3f5b480-a487-11e8-90f7-726c272312fd.png)

3. name is clickable but does nothing
![image](https://user-images.githubusercontent.com/1945230/44338820-dc65cf00-a487-11e8-8b13-c9a2c15a06ec.png)

4. Town|city field shows a value for a state field
![image](https://user-images.githubusercontent.com/1945230/44338912-39fa1b80-a488-11e8-9f89-5b78586cec0b.png)
![image](https://user-images.githubusercontent.com/1945230/44338924-40889300-a488-11e8-8519-d5ad5dd56cd6.png)
http://vladtest53ss.admin.kademi-ci.co/organisations/17723581/edit/

5. Error in console
![image](https://user-images.githubusercontent.com/1945230/44338979-5c8c3480-a488-11e8-945b-0e65e2128c44.png)

6. List of leads are empty
![image](https://user-images.githubusercontent.com/1945230/44339110-d2909b80-a488-11e8-8b40-3a3bb14f99dd.png)

7. missed fields for type of org
![image](https://user-images.githubusercontent.com/1945230/44339253-5a76a580-a489-11e8-9085-576c2cdef5db.png)
![image](https://user-images.githubusercontent.com/1945230/44339275-6ebaa280-a489-11e8-88c6-e9988e7f7965.png)

8. Brandline missed
![image](https://user-images.githubusercontent.com/1945230/44339365-c22cf080-a489-11e8-907d-9cd6f0546781.png)
![image](https://user-images.githubusercontent.com/1945230/44339389-d1ac3980-a489-11e8-8207-8c4630c05828.png)

9. Town|city missed
![image](https://user-images.githubusercontent.com/1945230/44339414-ef799e80-a489-11e8-8e7c-f5c937c4e07e.png)

**Comment by bradmac** [comment]
> 1.Could not save details for org, i think due the missed permissions (admin role)

Fixed

**Comment by bradmac** [comment]
> Tags also doesn't work
> Error in console

Same problem as reported earlier, just due to libs not being installed, which was resolved in the test account

> name is clickable but does nothing

Fixed

> Town|city field shows a value for a state field

Fixed

**Comment by bradmac** [comment]
> List of leads are empty

Displays correctly for me locally. Note that this shows leads directly connected to this company, not via a membership

![image](https://user-images.githubusercontent.com/826458/44367849-0b7e4e00-a525-11e8-940e-f43963caca98.png)


![image](https://user-images.githubusercontent.com/826458/44367815-eab5f880-a524-11e8-9f13-4de244d8a68f.png)

**Comment by bradmac** [comment]
> missed fields for type of org

There is no such thing as "company type" in our standard kcrm, so its correct that is not displayed

**Comment by bradmac** [comment]
> Town|city missed

Fixed

![image](https://user-images.githubusercontent.com/826458/44367979-73cd2f80-a525-11e8-9b01-79b3f2c6feca.png)

**Comment by bradmac** [comment]
> Brandline missed

@anhnt can you please take care of this last remaining item?

**Comment by Uafinder** [comment]
ok, looks good
but several issues appear
1. Tag creation weird issue
i have orgtag1
for example i want to add orgtag2
![image](https://user-images.githubusercontent.com/1945230/44391532-c8c67100-a538-11e8-9901-d1b66229c931.png)
it gives me 500 error
![image](https://user-images.githubusercontent.com/1945230/44391548-d24fd900-a538-11e8-858e-0cec0bcdbe73.png)
![image](https://user-images.githubusercontent.com/1945230/44391608-f90e0f80-a538-11e8-84ea-47a83fdf597a.png)
And there is no such org tag

**Comment by Uafinder** [comment]
save details page cause this message to appear
![image](https://user-images.githubusercontent.com/1945230/44660497-6bd32b00-aa10-11e8-806c-5f1ce8ab475c.png)

**Comment by anhnt** [comment]
Done

**Comment by Uafinder** [comment]
Looks good for me
