### ISSUE TITLE
KCRM: Contact detail page

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5850]
![image](https://user-images.githubusercontent.com/826458/44314764-6b66ed00-a470-11e8-8b2a-2a8cbd58e3e3.png)

https://preview.uxpin.com/e3a2a9f91e732e9b83bd8a8767f8d3f5785da182#/pages/86133304/simulate/sitemap?mode=i

**Comment by Uafinder** [comment]
1. Error on page
![image](https://user-images.githubusercontent.com/1945230/44338288-2c439680-a486-11e8-97f2-2a6a699b1cbd.png)
http://vladtest53ssweb-vladtest53ss.kademi-ci.co/custs/kademiqa01/

2. Missed address in specified places
![image](https://user-images.githubusercontent.com/1945230/44338333-3feefd00-a486-11e8-91d2-b8f90c3f4317.png)

3. Tags function is not work at all
![image](https://user-images.githubusercontent.com/1945230/44338355-51380980-a486-11e8-88a9-1e3e65db2cfa.png)

4. Placeholder text is bad
I think simple "Middle name" would be better
![image](https://user-images.githubusercontent.com/1945230/44338382-66ad3380-a486-11e8-8854-9407f25e55a6.png)

5. Update data fields doesn't cause to update it in the left panel
![image](https://user-images.githubusercontent.com/1945230/44338436-93f9e180-a486-11e8-819b-7356add48fc4.png)

6. these values are static
![image](https://user-images.githubusercontent.com/1945230/44338474-a4aa5780-a486-11e8-82a2-75de2ef14a66.png)

7. Upper line brand color
Green on the contacts page
![image](https://user-images.githubusercontent.com/1945230/44338594-079bee80-a487-11e8-95d0-0b807d0b32ef.png)
Blue on leads page
![image](https://user-images.githubusercontent.com/1945230/44338606-11255680-a487-11e8-98ba-6e6314696947.png)
Should be same i think

8. Org data is bad
![image](https://user-images.githubusercontent.com/1945230/44338682-5cd80000-a487-11e8-967a-84c6fa4ec2d9.png)

**Comment by bradmac** [comment]
Quite a few libs havent been installed..
![image](https://user-images.githubusercontent.com/826458/44364348-d5d46780-a51a-11e8-8d1f-3ba9181d53c5.png)

**Comment by bradmac** [comment]
I turned the leadman apps off and on to correct missing libs:
![image](https://user-images.githubusercontent.com/826458/44364419-0d431400-a51b-11e8-903e-79fcf8e9b096.png)

**Comment by bradmac** [comment]
> Error on page

Fixed

> Tags function is not work at all

It is searching now, but not adding. Moved here - https://github.com/Kademi/kademi-dev/issues/5859

> Placeholder text is bad

Fixed

> Update data fields doesn't cause to update it in the left panel

This is ok for now

> Org data is bad

> When several leads appears several org labels appears as well

These are because this is currently showing the organsiation on other leads related to the profile, which is incorrect. It should be showing the organisation associated with profile memberships

**Comment by bradmac** [comment]
> Org data is bad
> When several leads appears several org labels appears as well

Fixed

**Comment by bradmac** [comment]
> these values are static

This is being dealt with on this issue https://github.com/Kademi/kademi-dev/issues/5773

**Comment by bradmac** [comment]
@anhnt can you please just finish this..

> Upper line brand color
> Green on the contacts page
> Blue on leads page

**Comment by Uafinder** [comment]
Ok, got it all
Some left and some more
1. Title not saving
![image](https://user-images.githubusercontent.com/1945230/44388443-ccee9080-a530-11e8-9dfc-07d2947a3dfa.png)
refresh
![image](https://user-images.githubusercontent.com/1945230/44388462-d4159e80-a530-11e8-905a-2a003b8a5ba7.png)

2. Address fields missed
Missed address in specified places
![image](https://user-images.githubusercontent.com/1945230/44338333-3feefd00-a486-11e8-91d2-b8f90c3f4317.png)

3. Middle name also not saving
![image](https://user-images.githubusercontent.com/1945230/44388568-150db300-a531-11e8-8ee5-002a40c66fc4.png)

**Comment by anhnt** [comment]
title is not our standard field, so might be a custom field when on SP CRM
middle name might be added to kademi as standard field https://github.com/Kademi/kademi-dev/issues/5862? 
address fields are extra fields

**Comment by bradmac** [comment]
> title is not our standard field
> middle name might be added to kademi as standard field

Correct, will not make this standard, it can be a customisation in SP

**Comment by bradmac** [comment]
> address fields are extra fields

Will be actioned here - https://github.com/Kademi/kademi-dev/issues/5861

So ignore for the purpose of this issue

**Comment by bradmac** [comment]
Removed title and middle name fields..
![image](https://user-images.githubusercontent.com/826458/44437760-e7e40200-a60f-11e8-8671-15bf7f996a8c.png)

**Comment by Uafinder** [comment]
ok, looks good now
