### ISSUE TITLE
KCRM: Team list + detail page

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5851]
Please use layout from the SP project, NOT from the KCRM project:
https://preview.uxpin.com/86025214257f533598f807522e09dedd1ba94b8c#/pages/88212239/simulate/sitemap?mode=i

https://preview.uxpin.com/86025214257f533598f807522e09dedd1ba94b8c#/pages/87277212/simulate/sitemap?mode=i

![image](https://user-images.githubusercontent.com/2201340/44505420-a3766600-a6e4-11e8-86e4-7b316757c662.png)

--

![image](https://user-images.githubusercontent.com/826458/44560077-e9453400-a7a1-11e8-9a6e-69948032b125.png)

Note that this uses the KTeam app

**Comment by paddyow** [comment]
Should look like this, above image is old.

![image](https://user-images.githubusercontent.com/2201340/44505420-a3766600-a6e4-11e8-86e4-7b316757c662.png)

**Comment by anhnt** [comment]
I have done UI

Add new member:
![image](https://user-images.githubusercontent.com/735555/44518047-767d7f80-a6f3-11e8-9df4-714fab6a0f1a.png)

Add new team:
![image](https://user-images.githubusercontent.com/735555/44518068-872df580-a6f3-11e8-8c81-7f06c4e8a0b2.png)

Search, filter members

![image](https://user-images.githubusercontent.com/735555/44518101-9b71f280-a6f3-11e8-8231-1a4ebdac6c4d.png)


@bradmac please help with java side:
+ Some @todo points
+ Api to delete member from team

Also team detail page is now using profile template, please advise to fix or create new one to match creative

**Comment by anhnt** [comment]
Team detail

![image](https://user-images.githubusercontent.com/735555/44564275-564dcf00-a78c-11e8-821a-74856f09a315.png)


@bradmac i am using this method but seems not work
```
services.userManager.updateUser(profile);

**Comment by bradmac** [comment]
@anhnt problem is you havent wrapped the code in a transaction, so it gets rolled back
```
function saveMember(page, params) {
    log.info('a={}', page.attributes.member);
    var profile = page.attributes.member.thisProfile;
    log.info('profile={} params={}', profile, params);
    profile.firstName = params.firstName;
    profile.surName = params.surName;
    profile.nickName = params.nickName;
    profile.phone = params.phone;
    services.userManager.updateUser(profile);
    return views.jsonView(true, "Profile updated");
}
```

**Comment by Uafinder** [comment]
1. Team list
When you delete some user and then try to use search it doesn't work
![image](https://user-images.githubusercontent.com/1945230/45282536-e3f72180-b4e3-11e8-84f4-bd802bdcd440.png)
http://vladtest53vweb-vladtest53v.kademi-ci.co/team

2. When add some users and then delete one it doesn't disappear from list
![image](https://user-images.githubusercontent.com/1945230/45282662-38020600-b4e4-11e8-9da2-78478d1f0a98.png)
E.g. add two users one by one
Then delete one, watch that user remained in list without Team membership
http://vladtest53vweb-vladtest53v.kademi-ci.co/team/

3. Add sorting by name, email

**Comment by bradmac** [comment]
> When you delete some user and then try to use search it doesn't work

This is now apply a check on membership to teams. Previously if no team was selected for the filter it would just show everyone in the team group, which could include people not in a team org

**Comment by bradmac** [comment]
> When add some users and then delete one it doesn't disappear from list

Should also be resolved as above

**Comment by bradmac** [comment]
> Add sorting by name, email

The teams list is not expected to be big, usually less then 10. So sorting is not required

**Comment by bradmac** [comment]
> Update on email address field doesn't work

Fixed

**Comment by bradmac** [comment]
> Assigned leads number is limited to 100, and no possibility to review other ones.

Thats ok for now.

**Comment by bradmac** [comment]
> Role filter doesn't matter of team membership

Fixed

**Comment by bradmac** [comment]
> When user in team access team page, it shows only his team members and when you select All team manually it doesn't show you all members of any teams

Users should only see from teams they have access to

**Comment by bradmac** [comment]
> When you delete some user from team member list it removes all filtering options

@anhnt please investigate this

**Comment by anhnt** [comment]
Please resync team-lib

**Comment by Uafinder** [comment]
looks good
