### ISSUE TITLE
KCRM: Tasks page

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5852]
![image](https://user-images.githubusercontent.com/826458/44314807-06f85d80-a471-11e8-84e6-5a04c40ed6db.png)

https://preview.uxpin.com/e3a2a9f91e732e9b83bd8a8767f8d3f5785da182#/pages/86048162/simulate/sitemap?mode=i

**Comment by bradmac** [comment]
Please update button layout to match the design:
![image](https://user-images.githubusercontent.com/826458/44314819-36a76580-a471-11e8-848f-c79258a29c88.png)


Ignore the journey filter.

**Comment by Uafinder** [comment]
Click on tasks page cause tasks list to double, e.g. when there are 5 tasks it will be 10
![image](https://user-images.githubusercontent.com/1945230/44664406-d63d9880-aa1b-11e8-8278-b2ccbf57b47a.png)
http://vladtest53ssweb-vladtest53ss.kademi-ci.co/tasks/

Assignee ALL is a static text, no matter of selected. Filter is works but label doesn't change
![image](https://user-images.githubusercontent.com/1945230/44664453-fa997500-aa1b-11e8-99f9-e774d9c8fe3e.png)

Filter works only by pressing Enter button
![image](https://user-images.githubusercontent.com/1945230/44664513-21f04200-aa1c-11e8-828b-ab0231ef6441.png)

Company field shows nothing
Even if lead and participant has org membership
![image](https://user-images.githubusercontent.com/1945230/44664698-a2af3e00-aa1c-11e8-8dcf-ccd5c934691c.png)

When you complete or cancel tasks these counter not updating
![image](https://user-images.githubusercontent.com/1945230/44664777-e013cb80-aa1c-11e8-8e04-83a7ba35e748.png)

i think that there should be a link to lead no matter of lead title exists or not
![image](https://user-images.githubusercontent.com/1945230/44664844-0c2f4c80-aa1d-11e8-9099-c301041a7fc3.png)

**Comment by anhnt** [comment]
>i think that there should be a link to lead no matter of lead title exists or not
Sometimes a task doesnt relate to any lead so i think it's ok

**Comment by anhnt** [comment]
all fixed except company field
@bradmac please have a look at this class TaskAppIndexer.java

```
if ( t.getRelatedLead().getOrganisation() != null ) {
                b.field("leadOrgId", t.getRelatedLead().getOrganisation().getOrgId())
                        .field("leadOrgLongId", t.getRelatedLead().getOrganisation().getId())
                        .field("leadOrgTitle", t.getRelatedLead().getOrganisation().getTitle());
            }
```

but appear to be null even after reindexed
http://vladtest53ss.admin.kademi-ci.co/manageSearch/task/

**Comment by anhnt** [comment]
Ok its working as expected :)

**Comment by Uafinder** [comment]
Ok,
1. Sort button don't needed while we had sorting on column headers
![image](https://user-images.githubusercontent.com/1945230/45284797-1146ce00-b4ea-11e8-9949-581605e79d28.png)
http://vladtest53vweb-vladtest53v.kademi-ci.co/tasks/

2. Enter new task assignment list empty
![image](https://user-images.githubusercontent.com/1945230/45284916-671b7600-b4ea-11e8-817d-ad3a3fd21a9b.png)

3. Assigned to list empty
![image](https://user-images.githubusercontent.com/1945230/45284928-726ea180-b4ea-11e8-83ef-87f805a6d207.png)

4. Change date for task cause setup date on day before... it could be time zone issue
![image](https://user-images.githubusercontent.com/1945230/45284976-929e6080-b4ea-11e8-94a8-8bd814ed8c88.png)
![image](https://user-images.githubusercontent.com/1945230/45284988-9cc05f00-b4ea-11e8-8ae3-c294a9ae6cd1.png)

**Comment by bradmac** [comment]
> Sort button don't needed while we had sorting on column headers

> Change date for task cause setup date on day before... it could be time zone issue

These are not high priority issues. @Uafinder  Please move it to a seperate issue in p2

Assigned to issues do need to be resolved

**Comment by bradmac** [comment]
@anhnt please ensure that wherever we display team members we're using the teamMembers method on TeamManager, like we now do in LeadsFolder, eg

```
    public ResourceList<UserResource> getTeamMembers() {
        return teamMembersHolder.get(() -> {
            Profile curUser = KademiSecurityManager.currentUser();
            if ( curUser == null ) {
                return null;
            }

            OrgType salesOrgType = C(LeadManApp.class).getSalesOrgType();
            ResourceList<UserResource> list = new ResourceList<>();
            for (Profile m : C(TeamManager.class).teamMembers(curUser, salesOrgType)) {
                list.add((UserResource) UserApp.findEntity(m));
            }
            return list;
        });
    }
```

**Comment by anhnt** [comment]
It was using ES aggregation to collect team members. I added code to get team members when team org type is configured

```
#set( $teamOrgType = $applications.team.selectedOrgType )
                        #if ($teamOrgType)
                            #foreach($o in $services.teamManager.teamMembers($userResource.thisUser, $teamOrgType))
                            <li><a href="#" data-name="assignedTo" data-value="$o.name" class="filter">$o.formattedName</a>
                            </li>
                            #end
                        #else
                            #foreach($b in $aggr.aggregations.assignee.buckets)
                                #set($ur = false)
                                #set($ur = $applications.userApp.findUserResourceById($b.key))
                                <li><a href="#" data-name="assignedTo" data-value="$ur.name" class="filter">$ur.thisUser.formattedName</a>
                                </li>
                            #end
                        #end

**Comment by bradmac** [comment]
@anhnt you can assume team org type will be selected, so you can remove the second block

**Comment by anhnt** [comment]
Done

**Comment by Uafinder** [comment]
Sorting by Assigned to doesn't work
![image](https://user-images.githubusercontent.com/1945230/45412913-9237ce00-b680-11e8-8c3d-0bf9b286249b.png)
http://vladtest53w1web-vladtest53w1.kademi-ci.co/tasks

No success message on completing task
![image](https://user-images.githubusercontent.com/1945230/45413000-c01d1280-b680-11e8-8682-0c3974941a0d.png)

Complete task and create new one from same modal window doesn't work at all
![image](https://user-images.githubusercontent.com/1945230/45413095-01adbd80-b681-11e8-816f-5218f6dc9648.png)
Task not appears in list

**Comment by bradmac** [comment]
> Sorting by Assigned to doesn't work

Ignore sorting issues for now

**Comment by bradmac** [comment]
@anhnt please resolve other 2 issues. You can remove sorting completely if its quick, otherwise ignore it.

**Comment by anhnt** [comment]
Done. Also disabled client side sorting on leadman app tables

**Comment by anhnt** [comment]
@Uafinder this one needs rebuild and resync CI

**Comment by Uafinder** [comment]
Looks good now
