### ISSUE TITLE
Pending profile can access site content

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#5857]
This profile is pending admin approval http://schneiderelectric.admin.kademi.com.au/manageUsers/125253458/#summary-tab

- Has no permissions as they have not been added to the participants group that has the permissions
- Can login here http://version6.digitize-schneiderelectric.kademi.com.au/
- Can see their dashboard and points balance
- Can click on a module to access it
- Can click on a blog and view it
- None of the groups they are in have website access

**Comment by bradmac** [comment]
Pending profiles have the same permissions as profiles created by the contactus app.

So please use container visibility to ensure they can only see appropriate sections of pages
