### ISSUE TITLE
Module Statuses Table

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#5858]
Module Statuses Table shows codes, instead it needs to show a module name to be more meaningful.

![image](https://user-images.githubusercontent.com/2201340/44323748-95330a80-a496-11e8-8528-033c6da360d4.png)

**Comment by bradmac** [comment]
@paddyow can you give me a link and the user to see this?

**Comment by paddyow** [comment]
http://schneiderelectric.admin.kademi.com.au/manageUsers/123902190/#

version 6, on the profile page.

**Comment by bradmac** [comment]
So that shows the module title from the modulestatuses index. 

The index is set with data from the current live version

The current live version doesnt have these modules, so it cant find the title, so it shows the code

TLDR: push version6 live, reindex and all will be good

**Comment by paddyow** [comment]
V6 was pushed live and profile reindexed but the codes are still showing.

This profile http://schneiderelectric.admin.kademi.com.au/manageUsers/123902190/#

![image](https://user-images.githubusercontent.com/2201340/44370810-2f3e9580-a51f-11e8-8324-198f137a6582.png)

**Comment by paddyow** [comment]
The module status table only seems to show progress for everyone.

However there is an option called 'Link to profile'.  Not sure if this links the module text to the profile OR only show records for the logged in profile.

If no to the above, we need an option to filter by logged in profile only, or create a new component.

**Comment by bradmac** [comment]
Yep, this component is intended to be a reporting component, which shows modules completed for organisations that the user has reporting access to

The "link to profile" option means to put a link to each profile in the table.

If you want a component which shows the current elearning status for the currently logged in user, that is some other component.

I think we would probably want that to have a different layout to this one, ie to be more visually friendly rather then just a reporting thing.

**Comment by bradmac** [comment]
Moving to a new issue - https://github.com/Kademi/kademi-dev/issues/5865
