### ISSUE TITLE
KCRM: Add Address to Profile

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5861]
Allow setting multiple addresses on Profile (using the new Address class)

These should be selectable and editable on 
- the lead details contact tab of KCRM
- contact detaisl page of KCRM
- admin profile page
- front end profile page

See https://github.com/Kademi/kademi-dev/issues/5846#issuecomment-414297838

**Comment by bradmac** [comment]
Done admin side

![image](https://user-images.githubusercontent.com/826458/44633675-78d92580-a9e2-11e8-9064-def0782ca315.png)

![image](https://user-images.githubusercontent.com/826458/44633679-868eab00-a9e2-11e8-80ae-147099ee9dcc.png)

**Comment by bradmac** [comment]
@anhnt can you add to..

- the lead details contact tab of KCRM
- contact details page of KCRM
- front end profile page

Would be nice to add the same country auto-complete as on the kcom2 checkout form

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/44640876-6cf36080-a9ee-11e8-9cf8-56686bfb1d8d.png)

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/44642977-ee4ff080-a9f8-11e8-926f-fe36f8115ac2.png)

**Comment by anhnt** [comment]
@Uafinder please rebuild, resync CI, then upgrading leadman-lib, user-lib in your current account to test. there is new lib called `countries-states-lib` which needs to be installed as well

**Comment by Uafinder** [comment]
Country field should be a dropdown selector, not a flat field - and it's not saving
![image](https://user-images.githubusercontent.com/1945230/45285600-35a3aa00-b4ec-11e8-8893-086e914eb005.png)
http://vladtest53vweb-vladtest53v.kademi-ci.co/custs/userqa12/

From admin console
Address type and country also should be dropdowns
![image](https://user-images.githubusercontent.com/1945230/45285712-7f8c9000-b4ec-11e8-8c2d-d7621b804052.png)
http://vladtest53v.admin.kademi-ci.co/manageUsers/17794148/#general-tab

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/45351081-834d0f00-b5df-11e8-8e06-45d04aa7a790.png)

For admin console i think this is good enough for now. ie we fixed address type to be Home or Work, and doesnt allow delete address, also doesnt check for type duplicates, etc

**Comment by Uafinder** [comment]
looks good now
