### ISSUE TITLE
ELearning: My module progress component

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5865]
This should show
- module image + title (similar layout to module rows?)
- status (started/completed)
- date (either completed or started)
- provide a link to download certificate(s)
- sorted by program/course/module

**Comment by tuzzmaniandevil** [comment]
@paddyow @bradmac  Is this ok?

![image](https://user-images.githubusercontent.com/3378330/44942395-dff04300-ae03-11e8-9279-a3532818e6ee.png)

**Comment by tuzzmaniandevil** [comment]
Pull Request: https://github.com/Kademi/kademi-dev/issues/5865

**Comment by bradmac** [comment]
Done

**Comment by tuzzmaniandevil** [comment]
Forgot the preview image: https://github.com/Kademi/kademi-dev/pull/5926

**Comment by bradmac** [comment]
merged

**Comment by paddyow** [comment]
This profile http://moblix.admin.kademi-ci.co/manageUsers/762059/#learningAppTab-tab

Module image is not showing in col 1.  Module does have an image set.

![image](https://user-images.githubusercontent.com/2201340/45467692-38a8cf80-b764-11e8-9993-0bf56b31987e.png)

Need an option in the component to show/hide the image.

**Comment by tuzzmaniandevil** [comment]
It's not showing because it can't find the module for "/p1/c1/MB5000"

**Comment by tuzzmaniandevil** [comment]
program code "p1" doesn't exist. Only "Learning"

**Comment by paddyow** [comment]
@Uafinder can you test this please.

**Comment by Uafinder** [comment]
Works like a charm!
