### ISSUE TITLE
Profile creation has ghost points

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#5868]
These newly created profiles with UIDs 
http://mhiaa.admin.kademi-ci.co/manageUsers/17728976/#summary-tab
http://mhiaa.admin.kademi-ci.co/manageUsers/17728988/#summary-tab

All show the following point data even through they are new:

![image](https://user-images.githubusercontent.com/2201340/44386220-3dafa000-a565-11e8-86ca-b7781c404a07.png)

**Comment by bradmac** [comment]
The points bucket is configured to use team/org points:
![image](https://user-images.githubusercontent.com/826458/44433544-dfcd9780-a5fa-11e8-935d-d250ba81d396.png)

Those points are on the organisation the users are connected to
http://mhiaa.admin.kademi-ci.co/organisations/17302329/edit/
![image](https://user-images.githubusercontent.com/826458/44433560-f70c8500-a5fa-11e8-93db-4d1f41487edc.png)
