### ISSUE TITLE
KCRM: Cancel or complete lead bugs

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5870]
When cancel lead
![image](https://user-images.githubusercontent.com/1945230/44396385-6889fc00-a545-11e8-8489-c815fbd9b176.png)
Screen doesn't update at all
http://vladtest53ssweb-vladtest53ss.kademi-ci.co/leads/17730820/

When complete lead tasks area become bad

**Comment by anhnt** [comment]
Fixed

**Comment by Uafinder** [comment]
Ok, reload page is ok, but tags area still bad after closing or cancelling lead
E.g. here
![image](https://user-images.githubusercontent.com/1945230/44658465-979ee280-aa09-11e8-94b0-bebbf2c084b9.png)

**Comment by Uafinder** [comment]
Yup, looks good now
