### ISSUE TITLE
Update Kconfirm Properties 

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#5876]
Add the following option:  Prevent user from closing modal

Result: The modal cannot be closed via the X button or clicked outside of the modal causing the modal to close.  The use must not be able to close the modal until the form has been saved.

![image](https://user-images.githubusercontent.com/2201340/44566489-3977c280-a7b1-11e8-9ecb-15d0e050aa9b.png)

**Comment by tuzzmaniandevil** [comment]
Pull Request:
https://github.com/Kademi/kademi-dev/pull/5877

- Added support for "Prevent user from closing modal"
- Added an option to auto-refresh a page on success
- Fix a few bugs while I was in there

**Comment by bradmac** [comment]
just an issue with the transaction handling

**Comment by Uafinder** [comment]
Looks good
