### ISSUE TITLE
Inconsistent email validation on new profile form

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5878]
An email like this - aaa.d'xxx@yyy.com is valid on the edit profile page, but causes a validation error on the new profile form

![image](https://user-images.githubusercontent.com/826458/44632658-8ab2cc80-a9d2-11e8-9519-08cbcb33039a.png)

![image](https://user-images.githubusercontent.com/826458/44632664-a027f680-a9d2-11e8-8194-6a905ee2ad96.png)

Please update so that
- emails with an apostrophe such as the example above are accepted on both forms
- the same validation logic is applied on both screens

**Comment by anhnt** [comment]
Fixed

**Comment by Uafinder** [comment]
Did you remove a vlidation rules at all?
![image](https://user-images.githubusercontent.com/1945230/45826075-5b0a9200-bcfc-11e8-91c5-2cda823655bf.png)
http://vladtest53x2.admin.kademi-ci.co/manageUsers/17820438/#general-tab
![image](https://user-images.githubusercontent.com/1945230/45826095-63fb6380-bcfc-11e8-9f9a-a69e795c824b.png)

**Comment by bradmac** [comment]
Anh has updated so the standard email validation logic in our forms handler is used. I'll take a look at that.

**Comment by bradmac** [comment]
Note that most characters are allowed in the first part of the email address:
```


    The local-part of the email address may use any of these ASCII characters:

        uppercase and lowercase Latin letters A to Z and a to z;
        digits 0 to 9;
        special characters !#$%&'*+-/=?^_`{|}~;
        dot ., provided that it is not the first or last character unless quoted, and provided also that it does not appear consecutively unless quoted (e.g. John..Doe@example.com is not allowed but "John..Doe"@example.com is allowed);
        space and "(),:;<>@[\] characters are allowed with restrictions (they are only allowed inside a quoted string, as described in the paragraph below, and in addition, a backslash or double-quote must be preceded by a backslash);
        comments are allowed with parentheses at either end of the local-part; e.g. john.smith(comment)@example.com and (comment)john.smith@example.com are both equivalent to john.smith@example.com.

```

**Comment by bradmac** [comment]
So your address - di%#^&pedro@mailinator.com - is actually legal

Here's one which is not legal - a.b"@gmail.com

**Comment by Uafinder** [comment]
Looks good
