### ISSUE TITLE
KCRM: notes timeline more\less buttons does nothing

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5886]
E.g. you have a long text, and you want that it be hided partially and when you want to review it all you click more
![image](https://user-images.githubusercontent.com/1945230/44664142-151f1e80-aa1b-11e8-9573-df315cb9b63a.png)
But it doesn't happen
http://vladtest53ssweb-vladtest53ss.kademi-ci.co/leads/17753122/?view=activities

**Comment by anhnt** [comment]
Looks ok to me

![image](https://user-images.githubusercontent.com/735555/44701994-5ff07300-aabb-11e8-8aa5-93ac9a8b75ea.png)


![image](https://user-images.githubusercontent.com/735555/44702012-739bd980-aabb-11e8-88d0-c9c792c81758.png)

Can you ping me with this?

**Comment by Uafinder** [comment]
Looks ok to me as well
Maybe fixed somewhere else
