### ISSUE TITLE
KCRM: notes doesn't allow image uploading

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5887]
![image](https://user-images.githubusercontent.com/1945230/44664228-4c8dcb00-aa1b-11e8-9fc8-ea534d924805.png)
http://vladtest53ssweb-vladtest53ss.kademi-ci.co/leads/17753122/?view=activities

**Comment by anhnt** [comment]
@bradmac could you please have a look at this. here is log

![image](https://user-images.githubusercontent.com/735555/44702799-5b2dbe00-aabf-11e8-9691-f25d84a5ef33.png)

**Comment by anhnt** [comment]
http://vladtest53ss.admin.kademi-ci.co/manageUsers/17723554/#summary-tab

**Comment by bradmac** [comment]
Updated permissions in AssetsFolder

**Comment by Uafinder** [comment]
Looks better
