### ISSUE TITLE
promotionsTile component displays promotions which should be hidden based on org type

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5888]

**Comment by bradmac** [comment]
Should be fixed now

**Comment by Uafinder** [comment]
Doesn't work as i can see
![image](https://user-images.githubusercontent.com/1945230/46802161-45b9de00-cd65-11e8-9a60-bdb43029ddc5.png)
![image](https://user-images.githubusercontent.com/1945230/46802235-71d55f00-cd65-11e8-92fd-8bc1609de2c2.png)
![image](https://user-images.githubusercontent.com/1945230/46802245-7863d680-cd65-11e8-9d85-49b6c9f60984.png)
http://vladtest54a.admin.kademi-ci.co/manageUsers/17903936/#summary-tab
http://vladtest54aweb-vladtest54a.kademi-ci.co/rewards/

**Comment by bradmac** [comment]
Refactored to use PromotionsManager, and looks good locally

Requires rewards-lib 1.2.2

**Comment by bradmac** [comment]
@Uafinder please test the promotion tile component, not the default rewards page

![image](https://user-images.githubusercontent.com/826458/47467193-86c7ed00-d851-11e8-887a-80bb36f257c4.png)

**Comment by Uafinder** [comment]
Looks good
