### ISSUE TITLE
Consolidate typeahead dependencies into a lib

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5891]
typeahead files are currently referenced from static, and there are about 7 apps/libs which reference them

the danger of this is that if 2 different apps request different versions both will be injected into the site

please move typeahead files into their own lib, and update all apps which need typeahead to depend on it

note that this should include admin-lib

please ensure all changed app/libs get updated versions

**Comment by anhnt** [comment]
Done

**Comment by bradmac** [comment]
@Uafinder there should not be any affect on users, but the following are potentially affected and should be checked
- brand search box on product details
- organisation search on the registration page form
- sales team search in sales data claimer
- etc

**Comment by anhnt** [comment]
@Uafinder would be best to test on fresh account btw

**Comment by Uafinder** [comment]
i'm seeing some places where i think was search box selector:
- sales claim SKU selector on frontend and in admin console
- user selector for send test for group emails
Will add if i find somewhere else

**Comment by bradmac** [comment]
I'm not sure that these ever had a lookup UI. 

@anhnt please check. If there is no lookup on those screens just leave it, but if there is and its not working then please fix it.

**Comment by anhnt** [comment]
> sales claim SKU selector on frontend and in admin console
> user selector for send test for group emails

I have checked both and seems there is no typeahead implementation there.

**Comment by Uafinder** [comment]
Looks good now
