### ISSUE TITLE
update comingupAuction component

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#5893]
- if there are any current auctions (ie active) show the one which closes soonest
- if there are no active auctions, show the open auction which has the earliest start date

**Comment by bradmac** [comment]
```
```
/**
     * Get the current state of the auction
     *
     * @return draft, active, open, closed
     */
    public String getAuctionState() { // States = Draft, Active, open, closed
        if ( auction.getStatus() == Auction.STATUS.DRAFT ) {
            return "draft";
        } else if ( auction.getStatus() == Auction.STATUS.ACTIVE ) {
            if ( auction.getAuctionStartDate().after(CurrentDateService.now()) ) {
                return "active";
            } else if ( isAuctionClosed() ) {
                return "closed";
            } else {
                return "open";
            }
        }
        return "unknown";
    }
```

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/44700873-b079c780-aadf-11e8-9492-82e6cdd64a38.png)

**Comment by bradmac** [comment]
I've tested locally and it seems ok. The earlist closing auction is shown, as expected

**Comment by bradmac** [comment]
Now displays upcoming auction if none are active.

If not active the bid controls are hidden

**Comment by Uafinder** [comment]
Ok, i have one auction finished and one which is active
It shows to me a correct auction but say that it's finished
![image](https://user-images.githubusercontent.com/1945230/47553370-a02f6e80-d90f-11e8-923b-05057edbe70f.png)
![image](https://user-images.githubusercontent.com/1945230/47553382-a9204000-d90f-11e8-927b-7789e21aeef2.png)
http://vladtest54llweb-vladtest54ll.kademi-ci.co/dashboard
http://vladtest54ll.admin.kademi-ci.co/manageUsers/18006441

**Comment by anhnt** [comment]
Fixed

**Comment by Uafinder** [comment]
Cools... it works
