### ISSUE TITLE
Add support for date range selector for Claims page and Clais Group page

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5895]
Should be added because it almost stops to work where a lot of claims appears
You could see how it works here
http://mhiaa.admin.kademi.com.au/manageSaleDataClaimer/#claim-groups-tab
http://mhiaa.admin.kademi.com.au/manageSaleDataClaimer/#claims-list-tab

**Comment by bradmac** [comment]
Done
