### ISSUE TITLE
Blog articles ordering seems to have small issues.

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#5901]
It's working and ordering correctly in /admin/ but not on the front end.

Correct - expected.
http://plantae.admin.kademi.com.au/blogs/ (default ordered by Article date, descending)
24/05/2018
08/04/2018
22/03/2018
20/02/2018

Incorrect - not expected :)
http://plantae-plantae.kademi.com.au/blogs/articles/ (configured to order by Article date, descending).
24/05/2018
22/03/2018
20/02/2018
08/04/2018

Appears to be ordering by "day" instead of year, month, day.

**Comment by bradmac** [comment]
Fixed

**Comment by bradmac** [comment]
required blogs-lib 1.1.3
