### ISSUE TITLE
KCRM: Companies list not updated after company deletion

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5908]
![image](https://user-images.githubusercontent.com/1945230/44776104-f4bca480-ab7f-11e8-8bbc-0b3d07b0ac97.png)
http://vladtest53tweb-vladtest53t.kademi-ci.co/companies/

**Comment by anhnt** [comment]
Looks ok now

**Comment by Uafinder** [comment]
looks fine now
