### ISSUE TITLE
Scheduled emails sending muliple times

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#591]
See here: http://admin.rspca.olhub.com/scheduledEmails/rspca-qld-pet-first-aid-guide-mobile-data/#history-tab

See how an email was sent to Josie on 11/8 many times.  Not sure why?

**Comment by tuzzmaniandevil** [comment]
I can't seem to reproduce it locally. I did find where there is more than one group assigned and a user is in both groups the profiles would be added to the list of recipients to send to. I've fixed this.
Though it seems to be corrected later on the process anyway.

**Comment by bradmac** [comment]
Can you try to replicate by setting up a schedule job on prod to send to yourself?

**Comment by tuzzmaniandevil** [comment]
I've setup a scheduled email here http://admin.rspca.olhub.com/scheduledEmails/test-schedule-email/
just need to wait for it to fire.

**Comment by tuzzmaniandevil** [comment]
http://admin.rspca.olhub.com/scheduledEmails/test-schedule-email/#history-tab
Still can't reproduce
