### ISSUE TITLE
Product List component - Bug + Feature Request

### ISSUE THREAD

**Issue by yrsengar** [Kademi/kademi-dev#5914]
Hello Guys,

I think I've spotted a bug with product list component. 
I am not able to select the store in the options in the settings pane (it doesn't show any stores in the list).

**Feature Request**
If we could have the ability to choose "Product Category" in product list component along with the Store in the settings pane that would be great.
<img width="1224" alt="screen shot 2018-08-30 at 4 15 13 pm" src="https://user-images.githubusercontent.com/10014469/44829266-ebab0080-ac6f-11e8-9951-87f69b3a068b.png">

Thank you

**Comment by bradmac** [comment]
I've added a new component called Featured Product List:
![image](https://user-images.githubusercontent.com/826458/44890834-59b6fc80-ad30-11e8-937b-8db677450412.png)

The existing component is intended to work with the main product listing, and is integrated with the filter panel etc, so i think its best to keep these 2 use cases seperate

**Comment by bradmac** [comment]
Requires KCom2 1.0.9

**Comment by bradmac** [comment]
Added the ability to select a category:

![image](https://user-images.githubusercontent.com/826458/50742238-23a10080-126d-11e9-95fb-efedee9c380b.png)

**Comment by Uafinder** [comment]
Fresh account
Doesn't see such possibility
![image](https://user-images.githubusercontent.com/1945230/50832394-ace03200-1356-11e9-9848-facac3d4c824.png)
http://vladtest55vv.admin.kademi-ci.co/pages/vladtest55vvweb/version1/?contenteditor=page2.html

**Comment by bradmac** [comment]
I've reapplied my update

**Comment by Uafinder** [comment]
looks good
