### ISSUE TITLE
Cant add new team member

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#5915]
class java.lang.NullPointerException::null
- com.fuselms.apps.teams.TeamManager.getTeamOrganisation(TeamManager.java:120)
- com.fuselms.apps.teams.TeamsFolder.lambda$getTeamOrganisation$0(TeamsFolder.java:212)
- io.milton.cloud.server.db.utils.LazyValueHolder2.get(LazyValueHolder2.java:39)
- com.fuselms.apps.teams.TeamsFolder.getTeamOrganisation(TeamsFolder.java:212)
- com.fuselms.apps.teams.TeamsFolder.processForm(TeamsFolder.java:138)
- io.milton.http.http11.PostHandler.processExistingResource(PostHandler.java:85)
- io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:196)
- io.milton.http.http11.PostHandler.processResource(PostHandler.java:68)
- io.milton.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:127)
- io.milton.http.http11.PostHandler.process(PostHandler.java:62)
- io.milton.http.StandardFilter.process(StandardFilter.java:50)
- io.milton.http.FilterChain.process(FilterChain.java:46)
- co.kademi.server.subscription.KademiSubscriptionFilter.process(KademiSubscriptionFilter.java:48)
- io.milton.http.FilterChain.process(FilterChain.java:46)
- co.kademi.server.idp.IDPFilter.process(IDPFilter.java:43)
- io.milton.http.FilterChain.process(FilterChain.java:46)
- io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter$1.execute(MiltonOpenSessionInViewFilter.java:41)
- io.milton.context.RootContext.execute(RootContext.java:90)
- io.milton.cloud.server.db.utils.MiltonOpenSessionInViewFilter.process(MiltonOpenSessionInViewFilter.java:34)
- io.milton.http.FilterChain.process(FilterChain.java:46)
- co.kademi.server.webcache.KademiWebCacheFilter.process(KademiWebCacheFilter.java:125)
- io.milton.http.FilterChain.process(FilterChain.java:46)
- io.milton.http.HttpManager.process(HttpManager.java:158)
- co.kademi.server.Kademi$1.service(Kademi.java:194)
- org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
- org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
- org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
- java.lang.Thread.run(Thread.java:748)

**Comment by bradmac** [comment]
should be fixed now

**Comment by anhnt** [comment]
Looks good now thanks
