### ISSUE TITLE
Sales data claimer: allow filling empty cells

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5930]
![image](https://user-images.githubusercontent.com/826458/45130175-a771b000-b1db-11e8-82d4-cb66b64d85c8.png)

**Comment by anhnt** [comment]
Done

**Comment by anhnt** [comment]
@Uafinder would you like me to explain?

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/47499437-9bfc4600-d868-11e8-8b65-b4fa744d29b7.png)
Doesn't work for me
http://vladtest54l.admin.kademi-ci.co/manageSaleDataClaimer/#claims-list-tab

**Comment by anhnt** [comment]
I will explain when you're back to this..

**Comment by Uafinder** [comment]
ok, looks good
