### ISSUE TITLE
KCRM: Adding new member to team doesn't add user to team

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5933]
To reproduce
1. Create a team
2. Add a member and select created team
3. Check admin profile for org membership
![image](https://user-images.githubusercontent.com/1945230/45141075-8b5f1600-b1bd-11e8-9127-bac823fdca4c.png)
![image](https://user-images.githubusercontent.com/1945230/45141096-99ad3200-b1bd-11e8-808f-11764b49530b.png)
http://vladtest53u.admin.kademi-ci.co/manageUsers/17770741/#summary-tab
http://vladtest53uweb-vladtest53u.kademi-ci.co/team/

Needed for SP

**Comment by anhnt** [comment]
Fixed please rebuild

**Comment by Uafinder** [comment]
it works!
