### ISSUE TITLE
KCRM: team page delete button does nothing

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5934]
![image](https://user-images.githubusercontent.com/1945230/45141175-cd885780-b1bd-11e8-9e81-fc45e6e0e2eb.png)
http://vladtest53uweb-vladtest53u.kademi-ci.co/team/

needed for SP

**Comment by anhnt** [comment]
@bradmac please help with api to delete member

**Comment by bradmac** [comment]
Done

**Comment by bradmac** [comment]
Requires platform update, and latest team-lib

**Comment by Uafinder** [comment]
it works!
