### ISSUE TITLE
Edit team group leads to 404 error

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5935]
![image](https://user-images.githubusercontent.com/1945230/45141259-07595e00-b1be-11e8-9113-6ee570f9a43a.png)
http://vladtest53u.admin.kademi-ci.co/teamGroups/#teams-tab

**Comment by anhnt** [comment]
Done

**Comment by anhnt** [comment]
I also fixed delete team button

**Comment by Uafinder** [comment]
Looks good
