### ISSUE TITLE
Add the ability to view sent emails in the web browser

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#594]
This can be achieved by going to /viewEmail
and using either emailId or edmid to specify the Email ID.
The user needs to be logged in to view the email.
When using in Group/Automation email use the link 
`<a href="http://@{website.domainName}/viewEmail?@{login}">View Online</a>`

Generated emails automatically add the edmid to any links.

**Comment by ducdhm** [comment]
Awesome @tuzzmaniandevil :+1:

**Comment by anhnt** [comment]
really AWESOME. you saved my hours :+1:
