### ISSUE TITLE
KCRM: Create company success message bad

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5941]
![image](https://user-images.githubusercontent.com/1945230/45218684-2ab10580-b2b1-11e8-91ad-53bede524fd9.png)
http://vladtest53uuweb-vladtest53uu.kademi-ci.co/companies/

**Comment by anhnt** [comment]
For some reason datatables-lib is not installed on this account so it causes several problems since leadman-lib is heavily depending on that lib
please enable. if you can reproduce that the lib is not installed on fresh account by default please let me know

**Comment by Uafinder** [comment]
Created a fresh account on morning and databases-lin also missed
http://vladtest53v.admin.kademi-ci.co/marketPlace/?websiteBranch=version1&websiteName=vladtest53vweb&type=lib#browse-tab

**Comment by anhnt** [comment]
Fixed, please resync and test on fresh account

**Comment by Uafinder** [comment]
https://github.com/Kademi/kademi-dev/issues/5948
moved here
