### ISSUE TITLE
KCRM: Allow adding products to a lead

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5942]
Since leads often relate to products, we should formalise this by allowing users to explicitly add products to a lead.

**Comment by bradmac** [comment]
please finish this feature by:
- adding autocomplete (product search) to the add a product text field 
- adding an ability to remove products.

**Comment by bradmac** [comment]
Still some UI sugar to add on this issue in a later milestone - https://github.com/Kademi/kademi-dev/issues/5943

**Comment by Uafinder** [comment]
Looks good for me...
