### ISSUE TITLE
KCRM: Allow adding products to a lead (enhancement)

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5943]
Extension to  https://github.com/Kademi/kademi-dev/issues/5942

please finish this feature by:
- adding autocomplete (product search) to the add a product text field 
- adding an ability to remove products.

**Comment by Uafinder** [comment]
Also pls:
1. Enhance error to be more soft
![image](https://user-images.githubusercontent.com/1945230/45285938-2f61fd80-b4ed-11e8-8e6c-d07d5adbf943.png)

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/46202682-b0b8ed00-c341-11e8-9d36-e2993e7ddfbb.png)

**Comment by Uafinder** [comment]
Ok, looks fine
