### ISSUE TITLE
CMS access privilege issue.

### ISSUE THREAD

**Issue by yrsengar** [Kademi/kademi-dev#5947]
Hello Guys,
I have created a "Group" for the client accounts so they have enough CMS access to manage the content on pages, blogs and products/store.
Project URL: https://hazero.admin.kademi.com.au/

The group has roles applied to them as shown in the screenshot.
![screen shot 2018-09-10 at 4 27 04 pm](https://user-images.githubusercontent.com/10014469/45276604-66e59f80-b517-11e8-8b56-5b6a64f79309.png)

With all the roles applied to the client accounts, the client is not able to access the blog section and under pages section not able to make any changes to pages.

**Comment by bradmac** [comment]
OK, the account is "Hazero" and the website is "hazero", so i think that might be causing some confusion.

Administrative roles should generally be applied the account rather then a particular website. 

So please make sure they have Blogger and Content Author on Hazero rather then hazero.

You might find it helpful to change the account organisation name to "Hazero Ltd" etc, to make a clearer distinction.

**Comment by anhnt** [comment]
@bradmac site-admin users can create article, submit to approval
They also can see Edit web pages, but cant view editor page to edit a page
Tested with this user https://hazero.admin.kademi.com.au/manageUsers/123105191/#summary-tab

**Comment by bradmac** [comment]
OK, so this issue is now referring to front end permissions. I'll check.

**Comment by bradmac** [comment]
Fixed

**Comment by joelatfuel** [comment]
Can you please relook into this ticket - I'm encountering this bug on SP. They are trying to add a user that can only manage blog posts but are receiving an error 'You don't have permission to view this page'.

**Comment by bradmac** [comment]
@joelatfuel can you please provide 
- the user they are logging in with
- the address of the page they see that error on

**Comment by joelatfuel** [comment]
@bradmac The user's name was Beini Xue, and Megan provided the following page address.
https://spinsurance.admin.kademi.com.au

**Comment by bradmac** [comment]
That becasue that group doesnt have the Admin Viewer role. This role is needed for all groups using the admin screens
![image](https://user-images.githubusercontent.com/826458/46264135-65872000-c575-11e8-9d89-5d3b861884a0.png)

Details here
http://docs.kademi.co/programs/admin/users/cmperm/pcreating-a-limited-administrator-group.html
