### ISSUE TITLE
kcrm tag search on lead detail page is not working properly

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#5953]
![image](https://user-images.githubusercontent.com/735555/45339024-a0231b80-b5ba-11e8-89d1-83d43814ff40.png)

but ajax returns 4 records
```
[{"id":"1tags","name":"1tags"},{"id":"tag","name":"tag"},{"id":"tag1","name":"some tag"},{"id":"tag2","name":"another tag"}]

**Comment by anhnt** [comment]
I put Bloodhound back with prefetch mode and its looking good
![image](https://user-images.githubusercontent.com/735555/45401310-3ec28180-b67a-11e8-9398-8484a79d9b13.png)

**Comment by Uafinder** [comment]
Works cool
