### ISSUE TITLE
KCRM: Lead show no assignment on leads page 

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5956]
http://vladtest53wweb-vladtest53w.kademi-ci.co/leads/17798293/
![image](https://user-images.githubusercontent.com/1945230/45360851-75948b00-b5d9-11e8-9a9f-15e517285db3.png)

**Comment by bradmac** [comment]
This can happen when the selected user is not in the team member list.

To get around this i've changed it so it always outputs the selected user as the first option. This means the selected user which can be displayed twice, which is ok

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/45390309-d9b75d80-b672-11e8-8b62-145e8aec1a22.png)

**Comment by Uafinder** [comment]
Is this ok?
![image](https://user-images.githubusercontent.com/1945230/45411177-39663680-b67c-11e8-86cc-5846021f1067.png)
http://vladtest53w1web-vladtest53w1.kademi-ci.co/leads/17800338/
user: adminqa

**Comment by bradmac** [comment]
> Is this ok?

yep, see my previous comment, this is expected

**Comment by Uafinder** [comment]
Cools
