### ISSUE TITLE
KCRM: When lead closed without amount it shows code near Won

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5957]
![image](https://user-images.githubusercontent.com/1945230/45360957-9f4db200-b5d9-11e8-8c63-519dcde0a275.png)
http://vladtest53wweb-vladtest53w.kademi-ci.co/leads/17798317/

**Comment by bradmac** [comment]
Fixed
![image](https://user-images.githubusercontent.com/826458/45390542-c658c200-b673-11e8-9465-906ce15f9ac2.png)

**Comment by Uafinder** [comment]
Looks good
