### ISSUE TITLE
KCRM: Create a task from add a note window on dashboard component cause error

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5958]
![image](https://user-images.githubusercontent.com/1945230/45361239-6a8e2a80-b5da-11e8-8831-0d03fbceccb1.png)
When create save it gives you method not implemented
![image](https://user-images.githubusercontent.com/1945230/45361254-7679ec80-b5da-11e8-9898-545210f2c820.png)
http://vladtest53wweb-vladtest53w.kademi-ci.co/dashboard
user: adminqa or kcrmadmin

**Comment by bradmac** [comment]
@anhnt looks like the form handler isnt being initialised properly, although i can see it called in initNewNoteForm

So not sure whats happening, needs some debugging

**Comment by anhnt** [comment]
Fixed

**Comment by Uafinder** [comment]
Looks fine...
