### ISSUE TITLE
KCRM: Improve filtering options

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5963]
Extension to https://github.com/Kademi/kademi-dev/issues/5843#issuecomment-420260010

Assigned to filter gives you your teammates for filtering, but should give all assigned to persons and "not assigned" selection, as well as "all assignee's"
![image](https://user-images.githubusercontent.com/1945230/45360159-66acd900-b5d7-11e8-8ca5-a004720b53c3.png)
Same for Team selector... team selector gives you only your team for selection, should be all teams which are participated
![image](https://user-images.githubusercontent.com/1945230/45360226-9956d180-b5d7-11e8-9d77-ecfc51675fd4.png)
http://vladtest53wweb-vladtest53w.kademi-ci.co/leads/

user: kcrmadmin2

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/45528303-cf7b9780-b809-11e8-9fe1-1ad54e2a0331.png)
Done for assigned to team member

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/45529228-4c107500-b80e-11e8-8a7d-a8cbab530027.png)

**Comment by Uafinder** [comment]
Ok, assigned to filter works fine
About teams filter:
i see only my team and all team selector.
All teams selector works fine
My team selector shows nothing
![image](https://user-images.githubusercontent.com/1945230/45551410-8a218f00-b836-11e8-8856-c12acdd6ffc1.png)
http://vladtest53w6.admin.kademi-ci.co/manageUsers/17807750
http://vladtest53w6web-vladtest53w6.kademi-ci.co/leads/?query=&leadType=active&from=0&size=100&team=qa-team-2

**Comment by anhnt** [comment]
@bradmac please have a look at lead index, assignedToOrg field is not available
http://vladtest53w6.admin.kademi-ci.co/manageSearch/lead/?query={%20%20%20%20%20%20%20%20%22query%22:%20{%22match_all%22:%20{}},%20%20%20%20%22size%22:%20100}

Looks like something has been changed in LeadmanAppIndexer

**Comment by bradmac** [comment]
@anhnt the assignedtoorg field isnt really being used at the moment.

i think for now we should hide the team filter, there's no real need for it.

**Comment by anhnt** [comment]
Just hided that

**Comment by Uafinder** [comment]
Ok
