### ISSUE TITLE
EDM in journeys: available for groups visiblity for container doesn't work

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5985]
http://vladtest53x.admin.kademi-ci.co/funnels/joruney2/version1/emailAction-8b7ba1/#message-tab
![image](https://user-images.githubusercontent.com/1945230/45613226-44e7a200-ba6e-11e8-82d3-7144feac73fb.png)

**Comment by bradmac** [comment]
Fixed

**Comment by Uafinder** [comment]
Looks good
