### ISSUE TITLE
KCRM: issue with tasks and timeline

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5986]
Ok, i don't know how it should work but here is a problem.
For example you had one contact which has two leads (two leads for one user)
Timeline on leads page show messages for both leads at one time.
And when you click on complete task icon for task which related to another lead it cause 404 error.
Spot it here.
https://github.com/Kademi/projects/issues/660
http://vladtest53xweb-vladtest53x.kademi-ci.co/leads/17811745/
![image](https://user-images.githubusercontent.com/1945230/45615094-3a300b80-ba74-11e8-9f11-30fb361be8b6.png)
![image](https://user-images.githubusercontent.com/1945230/45615111-44eaa080-ba74-11e8-81cd-0a4a5a5c6dcf.png)
![image](https://user-images.githubusercontent.com/1945230/45615138-58960700-ba74-11e8-9291-879e6cee9131.png)

So we either need to filter timeline by lead, not by contact... or we need to disable those buttons for tasks from other lead

**Comment by anhnt** [comment]
as discussed with brad
-  its helpful to see all interactions with a customer even across different leads

So we just fixed 404 error

**Comment by Uafinder** [comment]
Looks good
