### ISSUE TITLE
KCRM: add existed tag issue when tag name have a space

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5988]
![image](https://user-images.githubusercontent.com/1945230/45619296-7027bc80-ba81-11e8-896e-38c32adb7465.png)
http://sp-spinsurance.kademi-ci.co/custs/userqa1736/

![image](https://user-images.githubusercontent.com/1945230/45619333-951c2f80-ba81-11e8-8a05-8f8b07f25ebc.png)
http://vladtest53xweb-vladtest53x.kademi-ci.co/custs/singleuser1/

**Comment by bradmac** [comment]
Fixed.

Also, changed so that new groups get created with cleaned name (ie replace spaces with hyphens)

**Comment by Uafinder** [comment]
It works
