### ISSUE TITLE
Pages: Distinctions between page name and page title.

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#5990]
It would be handy if a page property include a Name and SEO title. The distinction is important, because one is human readable and other is google bot optimised.

**Home page example**:
**File**: index.html
**Name**: Home
**Title**: Plumbing, Bathroom &amp; Tapware Supplies Online Auckland NZ | WaterWare

**Comment by bradmac** [comment]
Thats what the keyword and description tags are intended for..

![image](https://user-images.githubusercontent.com/826458/45656553-3e266100-bb3a-11e8-99a2-8a29e3708d29.png)

Note that in kademi terminology the "name" is the physical name, ie "index.html".

The title is the title displayed in the title bar. This should generally not be "Home", instead it should probably be "Plumbing, Bathroom & Tapware Supplies Online Auckland NZ | WaterWare"

**Comment by stephen-fueldesign** [comment]
I get that meta tags section creates dynamic <meta> tags.

But what I'm after is a distinction between the page name, and page title.

Because the page title is usually filled with SEO keywords and could be around 150-250 characters. And not easy to read instantly off the bat.

Below is a screenshot showing that in order for me to get an SEO page title in place on the "home" page, I had to change the name.

<img width="799" alt="screen shot 2018-09-18 at 12 55 12 pm" src="https://user-images.githubusercontent.com/39784677/45658339-919cad00-bb42-11e8-86a5-1a613e2d851d.png">

You can see that it's easy to read the names: Privacy Policy, Terms and Conditions.
But not easy to identify the homepage: "Plumbing, Bathroom &amp; Tapware Supplies Online Auckland NZ | WaterWare"

And this list will end up growing immensely.

P.s I do realise now however that the page names are using folders, which in a way help with my problem. But it would still be good to have an SEO Title and Page Name as a difference.

**Comment by stephen-fueldesign** [comment]
See Plantae's list of pages: http://plantae.admin.kademi.com.au/pages/plantae/version1/

Once an SEO company gets in there, that list will become unreadable at glance.

**Comment by bradmac** [comment]
> Below is a screenshot showing that in order for me to get an SEO page title in place on the "home" page, I had to change the name.

No, the "name" is "index.html". What you changed is the title, which is expected.

You definitely should have a descriptive title for each page. If you want to make more information available for SEO you should use the keyword and description tags.

**Comment by bradmac** [comment]
@stephen-fueldesign what do you think of this?

![image](https://user-images.githubusercontent.com/826458/45662150-d9c4cb00-bb54-11e8-9f15-2a4bff6c6dd1.png)

**Comment by stephen-fueldesign** [comment]
It's better. Shows me information: filename, template, icon, page title.
I like!
