### ISSUE TITLE
EDM in journeys: group selector, when test group selector not working

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#5996]
For example you need to test some email for specific user
We take some user within group selector range and without it
And no matter of selection, group selector will not work
http://vladtest53x1.admin.kademi-ci.co/funnels/journey1/version1/email1/#summary-tab
Send test for userqa02 (which should see content)
And for userqa03 (which shouldn't)
Both will not see it.

**Comment by bradmac** [comment]
Tested to userqa02, who can see it
http://vladtest53x1.admin.kademi-ci.co/emails/17816290

**Comment by bradmac** [comment]
userqa03 cannot see it:
http://vladtest53x1.admin.kademi-ci.co/emails/17816299

**Comment by bradmac** [comment]
So seems to work correctly

**Comment by Uafinder** [comment]
It works correctly when you send email
When you **test**email sending it's not working
E.g. click on send test
![image](https://user-images.githubusercontent.com/1945230/45825657-67421f80-bcfb-11e8-9d27-ff43ea144d10.png)
![image](https://user-images.githubusercontent.com/1945230/45825691-7fb23a00-bcfb-11e8-96b5-127c37ef49fe.png)
http://vladtest53x1.admin.kademi-ci.co/funnels/journey1/version1/email1/#message-tab

**Comment by bradmac** [comment]
hey @Uafinder yes thats what i did. And see the 2 test emails above showing the content is displayed or not appropriately for those 2 users.

**Comment by Uafinder** [comment]
Yup, looks good
