### ISSUE TITLE
KCOM2 - Shipping form needs to update when product quantities are changed

### ISSUE THREAD

**Issue by joelatfuel** [Kademi/kademi-dev#5998]
When you go through the checkout process, you either create or sign in to your account and choose your shipping option. At any point in the process, the customer can change the product quantities. The shipping form needs to be updated when a customers change the product quantities.

**Comment by bradmac** [comment]
My understanding is that the standard kcom2 checkout does work that way, but i'll check

**Comment by bradmac** [comment]
This was addressed on another issue, so closing
