### ISSUE TITLE
KCRM: Add lead from lead profile page feature

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#5999]
This should allow the user to select the journey, but no other fields are required

Note this functionality is in the old kcrm

**Comment by anhnt** [comment]
Done

**Comment by Uafinder** [comment]
Ok, looks good but some improvements needed:
1. Close modal after successful lead creation
2. Success message, e.g. "Lead created"
3. Notes should be changed to Description
4. Lead should appear in customer list instantly
http://vladtest53x2web-vladtest53x2.kademi-ci.co/custs/userqa01/

**Comment by anhnt** [comment]
Done

**Comment by Uafinder** [comment]
looks good
