### ISSUE TITLE
KCRM: lead filtering doesnt correctly handle team visibility

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6002]
A user in team X with TeamViewer role must be able to see leads which are:
- assigned to team X directly (not normally used currently)
- assigned to another member of team X
- related to a customer with a membership to an organisation in team X (eg where X is a sales territory, and the customer is a dealer in that territory)
- and any leads which are directly assigned to the user

Also, a user should only be able to add new contacts or companies if they have SalesTeamViewer or Administrator roles

**Comment by Uafinder** [comment]
ok
