### ISSUE TITLE
Contact Request download not showing all fields

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#6004]
This contact request http://mhiaa.admin.kademi.com.au/manageContacts/128650752

We have fields like:
prod3-indoor-serial-number

The downloaded report doesnt show all the fields http://mhiaa.admin.kademi.com.au/reporting/contactRequests?startDate=19%2F09%2F2015&finishDate=19%2F09%2F2018

Need all the custom fields in the contact request to troubleshoot something.

**Comment by paddyow** [comment]
Have re-indexed, extra fields are not showing.

**Comment by bradmac** [comment]
OK, the report wasnt using the latest code to find field names that the index is using.

Fixed
