### ISSUE TITLE
Custom Component rendering, but not showing up in keditor.

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#6006]
Hi, I have a custom component that seems to be rendering when I manually place into a template, but does not show up in the list of components in keditor.

**Front end**. See "Shop by concern" for the rendered custom component:
http://plantae-plantae.kademi.com.au/

**Controller mappings**:
http://plantae.admin.kademi.com.au/repositories/plantae/version1/WEB-INF/texteditor?fileName=components.js

**Manually placed markup into /index.html**:
```
	<section class="" data-type="component-shopByConcern">
		<div data-dynamic-href="_components/shopByConcern" id="keditor-dynamic-element-1537498930035"></div>
	</section>
```

**Comment by bradmac** [comment]
Should be fixed now
