### ISSUE TITLE
Kcom2 - shipping address in checkout is not pre-populated by an existing profile.

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#6011]
When visiting a KCom2 site on a brand new browser and logging in via checkout process it does not recall my shipping address.

Even after I visit profile page and add a home address.

Shipping address is still not pre-populated.

http://plantae-plantae.kademi.com.au/

**Comment by bradmac** [comment]
@anhnt please update the standard checkout form to allow the user to select from any saved address (do not assume only 'home' or 'work' named addresses)
![image](https://user-images.githubusercontent.com/826458/45946467-1573ff00-c045-11e8-94e0-13fbe518cd31.png)

Note that this should only populate the fields, if the user then changes the fields it should not update their saved address

**Comment by anhnt** [comment]
@bradmac atm we show address like bellow 

```
<input name="addressLine1" placeholder="Address line 1" type="text" class="form-control required" value="$formatter.ifNull($!cart.addressLine1, $!defaultAddr.address.addressLine1)" />

```

So if cart address is available it will override profile address. Can you confirm this is correct?

**Comment by bradmac** [comment]
As discussed..
- make profile address fields available to client side JS (eg as json written into the page)
- allow the user to select an existing address, eg use a bootstrap dropdown
- when selected the values of that address should be copied into the text fields
- nothing is saved until the user clicks next
- the user can change text fields, and this will have no effect on stored profile fields

**Comment by anhnt** [comment]
Done 
![image](https://user-images.githubusercontent.com/735555/45990590-3707d180-c0ab-11e8-9328-5afdf23ffaf1.png)

**Comment by Uafinder** [comment]
https://github.com/Kademi/kademi-dev/issues/6134
https://github.com/Kademi/kademi-dev/issues/6136

**Comment by anhnt** [comment]
should be fine now

**Comment by Uafinder** [comment]
looks good now
