### ISSUE TITLE
Kcom2 - final step of checkout process does not show a confirmation.

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#6013]
This is the site I was testing on: http://plantae-plantae.kademi.com.au

Although I have made tweaks, I don't think I've made enough changes to break the confirmation message.

ps. this is an eWay sandbox test payment gateway, use 4444333322221111 as visa test credit card to have a look.

**Comment by bradmac** [comment]
Please update as follows:
- [ ] show a modal with a thank you message, configurable through a setting on the checkout form component
- [ ] ensure the shopping cart is empied (just clearing the cart id cookie should do it)
- [ ] hide the container which contains the checkout form

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/45945317-50f7d480-c017-11e8-9960-57fb421c0706.png)

![image](https://user-images.githubusercontent.com/735555/45945330-5bb26980-c017-11e8-871f-945fab5fbbaa.png)

Done. @stephen-fueldesign please pull latest source and have a look at ecomCheckoutFormComponent.html

**Comment by Uafinder** [comment]
Perfect
