### ISSUE TITLE
Kcom2 - issues with cart not emptying after eway payment successful.

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#6014]
On http://plantae-plantae.kademi.com.au, on a fresh new browser, added 1x item to cart, visited checkout, filled out checkout process by logging in on step 1. (email address).

Once password, shipping address, shipping options, and payment steps entered, the "thank you page" showed 2 items in cart. These were items from a previous session. Not even my most recent test on a new browser (cleared cache, history etc)

I believe 1 of 2 things should happen. Either that once I log in a message should prompt me that I have a previous shopping cart with items already available, should I like to switch to it, or append to my current cart order, or two, erased the old items and the new items become the primary.

Whatever happens, once my final transaction is complete, the cart should be empty. If not, this gives the impression or feeling that I have not finished my previous order.

**Comment by bradmac** [comment]
Also, once you have a cart, logging in should not replace your current cart with a previous cart. If that happens then that is a bug

**Comment by bradmac** [comment]
Confirmed with standard kcom2 app that this works correctly
- as a logged in user add an item to a cart
- logout
- clear cookies
- add a different item
- login through the checkout process
- verify that after logging in the new cart stays as it is, ie does not get replaced with the previous cart

**Comment by bradmac** [comment]
I've done the same procedure in the plantae account and i do not see what you describe

**Comment by stephen-fueldesign** [comment]
Brad, it's possible I got mixed up with my multiple open browser windows, so if you were not able to reproduce then this is not an issue - _I was doing a lot of clicking around yesterday evening_. You can close this issue.
