### ISSUE TITLE
Kcom2 - Orders management page is not available by default

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#6015]
Not sure if this is supposed to be the case; however after my first test eway transaction using a sandbox account, I could not see any invoice in the system.

Even though Products & Stores > EWay Payments > Transactions shows I did a test.
http://plantae.admin.kademi.com.au/payments/#panel_payments-tab
18576954 | Stephen Blignault | 40.14 | NZD | Successful | 24/09/2018 16:17

**Comment by bradmac** [comment]
Not sure what you mean by invoice. Kademi has an invoiceing app but you're not using it

Do you mean you cant see the order? or are you expecting a confirmation email? if you want a confirmation email create a journey

**Comment by bradmac** [comment]
Yep, thats this page .. http://plantae.admin.kademi.com.au/shopping-carts/

Note that this admin page is currently provided by the incorrectly named "rewards shopping cart" app, i'll fix up the terminology.

**Comment by bradmac** [comment]
(updated issue title)

**Comment by bradmac** [comment]
OK, added the orders page to the ecommerce app.
