### ISSUE TITLE
Extra fields in the claim list component

### ISSUE THREAD

**Issue by yrsengar** [Kademi/kademi-dev#6018]
The claim list component currently shows only the default fields, it would be nice to have an option to add in the extra fields created in the data series.
![screen shot 2018-09-25 at 11 35 21 am](https://user-images.githubusercontent.com/10014469/45984832-3b39ec00-c0b7-11e8-958d-0cc6618a22b8.png)

**Comment by bradmac** [comment]
Note that these are displayed in the claim form, and i believe are being captured already into the claim record

**Comment by Uafinder** [comment]
Yup, looks good
