### ISSUE TITLE
Claim form does not save extra field data in data series and in sales data claimer app.

### ISSUE THREAD

**Issue by yrsengar** [Kademi/kademi-dev#6020]
When submitted, you can see the new entry in the sales data claimer app with all the default data. The extra fields created in the data series does not show up in sales claimer app.

When a claim has been approved the claim is saved in the data series with all the default data fields but the extra fields are empty.

![screen shot 2018-09-25 at 11 22 25 am](https://user-images.githubusercontent.com/10014469/45985398-332f7b80-c0ba-11e8-84b4-fbc1539e7ac9.png)
![screen shot 2018-09-25 at 11 20 49 am](https://user-images.githubusercontent.com/10014469/45985409-388cc600-c0ba-11e8-8d0c-b32d75ef26a4.png)

**Comment by anhnt** [comment]
Create and update form are fixed

**Comment by Uafinder** [comment]
looks good
