### ISSUE TITLE
KCRM: Improve layout on tablet and smartphone

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6023]
We've had complaints from a client that the new kcrm app is hard to use on phones and tablets. 

I've just done a quick look and i can see a few improvements to be made..

- [ ] organisations/companies page
![image](https://user-images.githubusercontent.com/826458/46043893-59622380-c16d-11e8-9afa-e4d779cc65df.png)
- [ ] on the customers list page remove the delete button in xs, and make the table responsive. 
![image](https://user-images.githubusercontent.com/826458/46043825-1b64ff80-c16d-11e8-8a4b-16ff87aadd90.png)

- [ ] make sure the dashboard tables are also responsive

**Comment by anhnt** [comment]
Applied to SP

**Comment by anhnt** [comment]
Fixed 6

**Comment by Uafinder** [comment]
1. Place order button bad
![image](https://user-images.githubusercontent.com/1945230/48405447-f50a1c00-e73a-11e8-8cf4-2ca8b34ddf7a.png)
http://vladtest54s.admin.kademi-ci.co/manageUsers/18181182

2. Place order modal bad as well
![image](https://user-images.githubusercontent.com/1945230/48405483-00f5de00-e73b-11e8-8953-50fcc4194081.png)

Company thing works

**Comment by anhnt** [comment]
Done

**Comment by Uafinder** [comment]
1 is good
2 - responsive is good, but we missed count selector and variant dropdown
![image](https://user-images.githubusercontent.com/1945230/48478255-6bc31a00-e80c-11e8-8f3e-4881c8f792af.png)
![image](https://user-images.githubusercontent.com/1945230/48478295-89907f00-e80c-11e8-8cf3-2f635e17214d.png)
http://vladtest54tweb-vladtest54t.kademi-ci.co/leads/18188252/
http://vladtest54t.admin.kademi-ci.co/manageUsers/18187867

**Comment by bradmac** [comment]
> 2 - responsive is good, but we missed count selector and variant dropdown

@anhnt can you put a min width on the inputs. There is a scroll on the table so that should be fine as long as the inputs dont get too small.

Also, what do you think about tweaking modals generally, so on mobile view they are 100% wide?

**Comment by anhnt** [comment]
Fixed 

Mobile

![image](https://user-images.githubusercontent.com/735555/48603936-ae225d80-e9aa-11e8-889f-53c640dfc3cb.png)

Desktop

![image](https://user-images.githubusercontent.com/735555/48603944-b9758900-e9aa-11e8-8d82-0492c8bd282b.png)

**Comment by Uafinder** [comment]
ok
