### ISSUE TITLE
KCom2: inappropriate use of !important

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6024]
Using !important is bad because it means developers cant override css rules in website customisations

Eg in kcom2.less we have this:
```
    .cart-total {
        background: #202020 !important;
        color: #fff;
        font-size: 20px;
    }
```

Please remove the !important. There should not be any need for important here, since the app defines the class.

Generally we should always avoid !important. Where we need to override a rule do that with a stronger selector, eg instead of just .cart-total you would use:
```
body .cart-total {}
```

**Comment by anhnt** [comment]
the code was copied over from old kcom so no need that important now
