### ISSUE TITLE
Group and tag names are not showing

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#6034]
https://zoetis.admin.kademi.com.au/manageUsers/45167398/#summary-tab

![image](https://user-images.githubusercontent.com/2201340/46172970-517abe80-c2e8-11e8-9d58-6dff527f4d44.png)

**Comment by bradmac** [comment]
Thats because these groups have no title:

![image](https://user-images.githubusercontent.com/826458/46173741-3c5b5b00-c2fb-11e8-849a-cd7e9f0bdc1e.png)

**Comment by bradmac** [comment]
This should now display the name if there is no title
