### ISSUE TITLE
Also add to group - option not working

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#6037]
Signup Form component

When choosing another group and submitting the rego form, the user is not added to the additional group.

![image](https://user-images.githubusercontent.com/2201340/46181320-65ceb380-c308-11e8-8695-d00a3d259eaf.png)

**Comment by bradmac** [comment]
eg http://schneiderelectric.kademi.com.au/participant/signup

**Comment by bradmac** [comment]
@paddyow use the accept ts and cs checkbox

![image](https://user-images.githubusercontent.com/826458/46181501-4b9dd100-c31a-11e8-82a9-cdf8d45d6fa4.png)

**Comment by bradmac** [comment]
Note that the other group MUST be configured as an available opt-in group
