### ISSUE TITLE
KCom fixes

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6039]
- make currency code configurable. See ecomCheckoutFormComponent line 276
- improve Eway error messages. See KCommerce2/APP-INF/texteditor?fileName=mappings.js
line 247'ish

**Comment by bradmac** [comment]
Note that a currency must be selected on the store now

![image](https://user-images.githubusercontent.com/826458/47336440-41d67600-d6ec-11e8-9049-9490b8d99c2f.png)

**Comment by bradmac** [comment]
> improve Eway error messages

Looks ok now

![image](https://user-images.githubusercontent.com/826458/47400296-18275880-d799-11e8-83a3-3ac64de5a903.png)

**Comment by Uafinder** [comment]
looks good
