### ISSUE TITLE
Content types: Field of type Relation(Content type) should display asset title, not asset id.

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#6048]
http://farmgard.admin.kademi.com.au/asset-manager/2fc062ea-98d9-40e4-bd49-74e6a4a1882c

shows english title for some fields, and asset ids for others.
<img width="558" alt="asset-types" src="https://user-images.githubusercontent.com/39784677/46317977-785f2a80-c631-11e8-81eb-a585e11a38ab.png">

The pattern shows it that "Relation (ContentType)" is the culprit.
<img width="667" alt="content-types" src="https://user-images.githubusercontent.com/39784677/46318097-d724a400-c631-11e8-9ffd-693e13d4ae36.png">

JS Errors:
<img width="1133" alt="js-errors" src="https://user-images.githubusercontent.com/39784677/46318278-6e89f700-c632-11e8-956d-637002dbb5b4.png">

**Comment by bradmac** [comment]
@anhnt can you look into this? i think its something to do with the typeahead stuff, see assetsCommon.js and jquery.assetFinder..js

**Comment by anhnt** [comment]
Fixed, tested on farmgard

![image](https://user-images.githubusercontent.com/735555/47353850-6c720000-d6e7-11e8-83dc-18a48a27b569.png)

**Comment by Uafinder** [comment]
Looks fine
