### ISSUE TITLE
Asset Manager, failing to save an asset name correctly.

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#6063]
http://farmgard.admin.kademi.com.au/asset-manager/?q=category%3APartsManuals&type=PartsManuals

    Parts Manual - Celli power harrows 2,Parts Manual - Celli power harrows 2,Parts Manual - Celli power harrows 2
    Parts Manual - Celli power harrows,,Parts Manual - Celli power harrows,

Seems to duplicate and append the title name instead of updating the name.

**Comment by bradmac** [comment]
@stephen-fueldesign the problem is that you've made a custom field called "name". So that means 2 fields are POST'ed, and they get combined

![image](https://user-images.githubusercontent.com/826458/46511668-5cb38880-c8ac-11e8-837d-f4dc9855558c.png)

**Comment by bradmac** [comment]
Also, the purpose of the standard name field is, unsurprisingly, to be the name. 

So you probably should not even have that second at all
