### ISSUE TITLE
KCom2 - Admin not showing all products

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#6064]
Products & Stores > Products
http://farmgard.admin.kademi.com.au/products/?dataQuery=&supplier&searchOrg=
only showing 13 products, and not the other 59 products.
The products are categorised and they are set to the ecom store.

If you search "Celli" or "Berti" you get 25ish results. So they products are there, just not listed by default

I did a search re-index for ecommercestore and products and no luck.

**Comment by bradmac** [comment]
Note that all the products are listed when doing a CSV export.

I'll investigate

**Comment by bradmac** [comment]
Fixed. Problem was due to an optimisation to eagerly load images
