### ISSUE TITLE
Sales Data Claimer app does not show additional fields

### ISSUE THREAD

**Issue by yrsengar** [Kademi/kademi-dev#6065]
I have used sales data claim form and added two additional fields. After submitting the form it only stores the data from the default form fields and additional field data is lost.

I think it would be good to show the additional data in the sales data claimer app.

Screenshots attached.
<img width="1701" alt="screen shot 2018-10-05 at 1 38 18 pm" src="https://user-images.githubusercontent.com/10014469/46510215-fb87b700-c8a3-11e8-972b-abca5707e089.png">
<img width="1370" alt="screen shot 2018-10-05 at 1 38 34 pm" src="https://user-images.githubusercontent.com/10014469/46510224-ffb3d480-c8a3-11e8-845b-c37725f0d25d.png">

**Comment by anhnt** [comment]
Done, version 1.5.0
![image](https://user-images.githubusercontent.com/735555/46514065-df751d00-c885-11e8-931a-7290caddc37f.png)

**Comment by yrsengar** [comment]
Works Great Anh! Thank you
