### ISSUE TITLE
Date & Time Field in Asset manager

### ISSUE THREAD

**Issue by yrsengar** [Kademi/kademi-dev#6066]
Date & Time field in asset manager does not save data.
The input type "datetime-local" is not completely supported by all browsers and they seem to be behaving quite differently in my current chrome and Firefox browsers.
I think it would be better if date and time input types are used separately or some additional js plugin to be used instead for this. There is one for bootstrap (bootstrap-datetimepicker).

Screenshot attached
<img width="1374" alt="screen shot 2018-10-05 at 2 35 38 pm" src="https://user-images.githubusercontent.com/10014469/46511622-1eb66480-c8ac-11e8-84c9-d6a429478ecd.png">

**Comment by bradmac** [comment]
moved to existing issue
https://github.com/Kademi/kademi-dev/issues/6059
