### ISSUE TITLE
Sales data claimer app: Feature request

### ISSUE THREAD

**Issue by yrsengar** [Kademi/kademi-dev#6068]
Clients want to be able to export/import all records (approved, rejected or on hold, all data) from sales data app.

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/46858773-42daee00-ce36-11e8-84a3-f36029991499.png)

**Comment by Uafinder** [comment]
After import there is a weird blank images appears for imported claims
![image](https://user-images.githubusercontent.com/1945230/46940225-e283c080-d070-11e8-89c2-5ea27c762753.png)
http://vladtest54c.admin.kademi-ci.co/manageSaleDataClaimer/#claims-list-tab

**Comment by bradmac** [comment]
> After import there is a weird blank images appears for imported claims

Thats fine

**Comment by yrsengar** [comment]
The client is still facing the import issue so I asked them to send me the exact file they were trying to import...
Also, I noticed that each time we import records it creates duplicates.

File attached.

[salesDataClaims.csv.zip](https://github.com/Kademi/kademi-dev/files/2517380/salesDataClaims.csv.zip)

**Comment by yrsengar** [comment]
Ok, I will let then know. Will this work if they export all the existing claims update the data on it, delete everything from Sales data claimer app and then import the updated version in the app?

**Comment by anhnt** [comment]
requires salesDataClaimer 1.5.6, already deployed to AU

**Comment by yrsengar** [comment]
Client reports that while importing the CSV file they are getting errors.
screenshot attached + the file they used to import is attached as well.

![image](https://user-images.githubusercontent.com/10014469/47629737-d3892c00-dba1-11e8-92ce-48ad2fbf0ba9.png)

[salesDataClaims.csv.zip](https://github.com/Kademi/kademi-dev/files/2523796/salesDataClaims.csv.zip)
