### ISSUE TITLE
Error in console when open KEditor

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6069]
![image](https://user-images.githubusercontent.com/1945230/46536903-94c0c880-c8b8-11e8-9b41-645f802631aa.png)
http://vladtest53y.admin.kademi-ci.co/pages/vladtest53yweb2/version1/?contenteditor=page1.html
http://vladtest53y.admin.kademi-ci.co/pages/vladtest53yweb2/version1/

**Comment by bradmac** [comment]
cause is that the photoeditor-lib hasnt been synced correctly
![image](https://user-images.githubusercontent.com/826458/46562607-5cbd9200-c959-11e8-937b-0636e81856a3.png)

To fix sync from rootorg
![image](https://user-images.githubusercontent.com/826458/46562644-a1e1c400-c959-11e8-9af5-043c89e4ac95.png)

Verify synced correctly in rootorg, and copy the hash
![image](https://user-images.githubusercontent.com/826458/46562657-b02fe000-c959-11e8-9057-f714b8892dca.png)

Then set hash in the account with the error.

Fixed
