### ISSUE TITLE
KCRM: Sales manager can't access team page by default

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6072]
http://vladtest53zweb-vladtest53z.kademi-ci.co/team/
http://vladtest53z.admin.kademi-ci.co/manageUsers/17874988
![image](https://user-images.githubusercontent.com/1945230/46569922-1ec66b00-c965-11e8-8fab-806d277b571a.png)

**Comment by bradmac** [comment]
Updated to use the 2 user admin roles, for viewing or editing 

![image](https://user-images.githubusercontent.com/826458/47273260-1c634280-d5ee-11e8-9a8f-9f15e72f8c35.png)

Require team-lib 1.0.6

**Comment by bradmac** [comment]
@Uafinder please update your sales group as above

**Comment by Uafinder** [comment]
It works!
