### ISSUE TITLE
KCRM: Contacts list and companies list empty

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6074]
http://vladtest53zweb-vladtest53z.kademi-ci.co/custs/
This user
http://vladtest53z.admin.kademi-ci.co/manageUsers/17874988
![image](https://user-images.githubusercontent.com/1945230/46570389-f55d0d80-c96b-11e8-9107-7f27c6a973c1.png)

http://vladtest53zweb-vladtest53z.kademi-ci.co/companies

Looks like by default sales-manager role have no access to contacts and companies

**Comment by bradmac** [comment]
Looks good after reindexing
![image](https://user-images.githubusercontent.com/826458/47272212-d9e63980-d5de-11e8-9d2b-6c6b0dd28231.png)

**Comment by bradmac** [comment]
Note that with companies, the 2 criteria for displaying organisations are:
- if the company is directly assigned to the current user
- the company is within the user's reporting hierarchy (ie within orgs the use has the ReportingAccess role on)

**Comment by bradmac** [comment]
So if a customer is connected to a company from outside the kcrm user's reporting hierarchy, and that company is not on a lead the kcrm user has access to, then they will see it on the lead but not the companies page.

Also worth mentioning that we're holding the list of assigned leads in the org index. So if there is an indexing problem, its the org index that should be reindexed

**Comment by bradmac** [comment]
I've connected 2 companies to leads to demonstrate this:
![image](https://user-images.githubusercontent.com/826458/47272356-e53a6480-d5e0-11e8-9d49-f9daa469f1cd.png)

**Comment by Uafinder** [comment]
Ok, for example i add a company
![image](https://user-images.githubusercontent.com/1945230/48189878-dcb88c80-e349-11e8-99f7-ef56f320bf4b.png)

But it will not appears in list
I don't think that's ok
http://vladtest54oweb-vladtest54o.kademi-ci.co/companies
http://vladtest54o.admin.kademi-ci.co/organisations/

**Comment by bradmac** [comment]
Currently new orgs are created at the root level. Problem is this user can only view orgs within its team.

So when a user has limited visibility of orgs, when they create a new org it should be created within their own org hierarchy, so they can see it.

**Comment by bradmac** [comment]
Updated company creation, so they are now created within the user's team

**Comment by bradmac** [comment]
Needs leadman-lib 3.1.5

**Comment by Uafinder** [comment]
Ok, i'm seeing that ORG created in user's team
![image](https://user-images.githubusercontent.com/1945230/48404340-ace9fa00-e738-11e8-8ed7-c87c1dab63f4.png)
but still can't see it in list
![image](https://user-images.githubusercontent.com/1945230/48404362-b6736200-e738-11e8-8c09-c6783ade9caa.png)
this user
http://vladtest54s.admin.kademi-ci.co/manageUsers/18181182/#summary-tab

**Comment by bradmac** [comment]
@Uafinder the group wasnt setup correctly, it was missing the ReportingAccess role.

This role is critical because that is what determines what data the user can see

![image](https://user-images.githubusercontent.com/826458/48441413-4e805280-e7f0-11e8-9278-0038f801e081.png)

Please let me know if this isnt clear.

**Comment by bradmac** [comment]
With the correct role i can now see the new org:

![image](https://user-images.githubusercontent.com/826458/48441482-87b8c280-e7f0-11e8-8003-f6c0c9df8ad0.png)

**Comment by Uafinder** [comment]
ok, opened separate issue for role in group
