### ISSUE TITLE
Certificate issue on Zoetis

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6075]
Remember those issue when regenerated certificate not showing and user saw old one?
Well, i think that's the same thing, but another place.
When user complete module in Zoetis - there is a certificate link.
CI has no such link at the moment. So i checked it directly in Zoetis
![image](https://user-images.githubusercontent.com/1945230/46571160-e0d34200-c978-11e8-94fa-4f934bb73e22.png)
![image](https://user-images.githubusercontent.com/1945230/46571163-efb9f480-c978-11e8-8356-9b6a59d13d44.png)
http://www.thefeedzoetis.com.au/users/76264ad8-2bea-41f0-b245-af3d2c4b6490/certificates/ZOELIV1343_champion-certifcate_82970640.pdf
![image](https://user-images.githubusercontent.com/1945230/46571167-f7799900-c978-11e8-8dda-cbf9e4110774.png)
So, we need to replace that link to actually generated link (to generate certificate instantly, like we did in other places)
https://zoetis.admin.kademi.com.au/manageUsers/45119098/#learningAppTab-tab

**Comment by bradmac** [comment]
Moved to client speciic issue - https://github.com/Kademi/client-zoetis/issues/332
