### ISSUE TITLE
Feature request: Custom Leaderboards

### ISSUE THREAD

**Issue by yrsengar** [Kademi/kademi-dev#6078]
The client wants to be able to import the pre-calculated data into each data series (this feature already exists) and to be able to link that data from each data series with the table component.

Each data series has a specific set of columns, number of columns and the kind of data that goes in those columns could differ as well.

**Comment by bradmac** [comment]
@yrsengar does this need to follow the usual leaderboard semantics? ie display the top X positions, and always display the current user (ie even if theyre not within the top X they are shown at the end)

**Comment by yrsengar** [comment]
Yes, please. If that organisation exists in the imported records.

Here is the list of leaderboards along with their columns this feature will be used for:
Leaderboard 1 - "Services Sales Growth"
●	Rank
●	Organisation
●	% Growth

Leaderboard 2 - "Refurbishment Sales Growth"
●	Rank
●	Organisation
●	% Growth
●	Eligibility 

Leaderboard 3 - “Cisco Volume”
●	Rank
●	Organisation
●	% Growth
●	Eligibility 

Leaderboard 4 - “Cisco SaaS"
●	Rank
●	Organisation
●	Revenue

Leaderboard 5 - “Cisco Education”
●	Rank
●	Organisation
●	Revenue

Leaderboard 6 - “Hit Your Revenue”
●	Rank
●	Organisation
●	Revenue
Leaderboard 7 - “Highest Revenue Growth”
●	Rank
●	Organisation
●	% Growth

**Comment by bradmac** [comment]
OK, as discussed..
- we'll create a new leadboard component
- this will be based on a sales data series but will not aggregate records
- rows will be ordered by the amount column
- a specified number of ranks will be displayed, plus the current user if not included
- the following cols will be displayed, although all can be hidden with settings
- each row will include [Rank, Participant(user or org, ie sales), Amount, Custom columns]

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/46724333-fa8bc680-cca3-11e8-8ba0-fba9a24e2c7f.png)
Done, requires salesdata-lib version 1.3.8

**Comment by bradmac** [comment]
hey @anhnt please add a setting to control the sort direction, ascending (lowest to highest) or descending

**Comment by anhnt** [comment]
Have that now 
![image](https://user-images.githubusercontent.com/735555/46727528-fa42f980-ccaa-11e8-93e6-ae92e7b4cda6.png)

**Comment by Uafinder** [comment]
Looks great!
