### ISSUE TITLE
Kademi to handle 301 permanent url redirects

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#6080]
For front end facing website, it is imperative that we have a platform feature that handles permanent resource (URL) redirects from from old to new.

There are many reason for this.

- When a website is going from an old platform to kademi, all old pages need to be redirected to the new kademi equivalents.
- Retain older pages' seo score
- Prevent a huge jump in 404 pages when a new website goes live on Kademi
- Redirect any links persistent in bookmarks, social media, campaigns and search engine result pages.
- And of course simply handling a resource name change; blog article, product page, services page etc.

I don't mind if this can be handled via JSON or XML, if it has a GUI or not, but if we want clients to use this feature then it should have a GUI.

**Comment by stephen-fueldesign** [comment]
Getting messaging like these from our clients:

> Hi Stephen,
>
>We just received this email, does this mean anything to you? 
>
>Thanks,
>Erin 


```
Email	unknown@user.com
Contact form	/our-products/certified-organicbrightening-camelliaface-polish/
Sorry! I can't find that page

If you're interested in the details, this is a "404 error", which usually means that the page you're trying to view doesnt exist.

This might be a bug, or maybe you just ended up somewhere you werent supposed to.

Maybe you could just go back and try another link? Or try from the home page

Would you like to tell us about it? That would really help us fix it.
If you click this button the page will try to send the information you see here to our administrator.

Tell us about itSome details, these might help us fix this problem
What you asked the page to do is called (in techie terms) a GET method

The address of this page is: http://plantae.co.nz/our-products/certified-organicbrightening-camelliaface-polish/

You got here from: https://www.facebook.com/

You're logged in as: N/A

and even more techie stuff...
Your web browser is: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

Parameters: No params

Is javascript enabled: YES!

Cookies enabled: YES!
```

We reaaaaaaally need to have ability to set up 301 permanent redirects, especially considering Kademi has feature to email website owner about a 404 page, likely coming from google search index, or facebook page etc.

**Comment by bradmac** [comment]
The redirects app is in progress :)

**Comment by anhnt** [comment]
Url will be depended on website, so if a source url matches the request and website matches, this will be redirected to target url

**Comment by bradmac** [comment]
@anhnt can you please check steve's setup here
http://farmgard.admin.kademi.com.au/kredirect/

doesnt seem to be working

btw, i'm seeing this in the logs..
```
NFO
undefined
getDB > page=io.milton.cloud.server.apps.website.WebsiteRootFolder@5686c5bb
09:39:41
INFO
undefined
id farmgard@/bootstrap-colorpicker.min.css.map
09:39:41
INFO
undefined
kredirectResolver > io.milton.cloud.server.apps.website.WebsiteRootFolder@5686c5bb kredirect bootstrap-colorpicker.min.css.map {kredirect=bootstrap-colorpicker.min.css.map}
09:39:41
ERROR
undefined
TypeError: page.throwNotFound is not a function in /APP-INF/dbUtils.js at line number 12
09:39:41

    class javax.script.ScriptException::TypeError: page.throwNotFound is not a function in /APP-INF/dbUtils.js at line number 12
    - jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
    - jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:392)
```

**Comment by stephen-fueldesign** [comment]
Seems to be working in my first few tests. Well done.

Are we able to get a CSV file uploader going? Most sites have in excess of 300 pages to do?
And/or is there an XML or JSON type data structure that can just bulk append to?
Should this request be a separate ticket?

**Comment by bradmac** [comment]
All sorted and in production
