### ISSUE TITLE
Register form multipart encoding conflicts with optins field

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6083]
The register form component currently used multipart encoding to allow file inputs:
```
<form method="post" id="registerForm" action="$formUrl" enctype="multipart/form-data"
```

However, because of this when using multiple checkbox values (eg for opt-ins) these arent correctly interpreted as  an array of values, and instead only the first value is processed by the server

Please remove the enctype attribute by default, but add an option to the component settings to enable multipart form

**Comment by anhnt** [comment]
Done

**Comment by Uafinder** [comment]
I don't see difference between checkbox selected or not for that form
http://vladtest55jj.admin.kademi-ci.co/websites/vladtest55jjweb/version1?editTemplate=theme/apps/signup/register
Could you assist?

**Comment by bradmac** [comment]
> I don't see difference between checkbox selected or not for that form

yep, there should not be a visible difference. The important thing to check is the form works correctly whether that is checked or not.
