### ISSUE TITLE
KCom2 - Shipping dropdown not dynamically refreshing correctly

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#6087]
There seems to be a bug with shipping selection that when you update either quantity or shipping country that shipping selection does not refresh with correct options; until you manually refresh the page.

Firstly, in your test case scenario, make sure you have 3 shipping options.
1. Free shipping - orders over $100
2. NZ Shipping - $5 fixed - NZ only
3. International Shipping - $20 fixed

I can reproduce the bug in the following ways:
- change of cart quantity (subtotal below or above $100) does not affect shipping selection until refresh.
- change of shipping country (between NZ or any other) does not affect shipping selection until refresh.

**Comment by anhnt** [comment]
Fixed. Deployed to AU and applied to plantae, tested with Steve account
