### ISSUE TITLE
Error in console when accessing auctions page

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6092]
![image](https://user-images.githubusercontent.com/1945230/46675628-80960780-cbe7-11e8-8a98-184a6b011b41.png)
http://vladtest53z3aucstore-vladtest53z3.kademi-ci.co/auctions/
http://vladtest53z3.admin.kademi-ci.co/websites/

**Comment by anhnt** [comment]
Fixed, rewardstore-lib needs bootstrap-upcrop-image.js

**Comment by Uafinder** [comment]
looks good
