### ISSUE TITLE
KCom2 - Add payment status

### ISSUE THREAD

**Issue by joelatfuel** [Kademi/kademi-dev#6096]
In the Carts & Orders page, we need to see the payment status. This will let us know if an order has been paid or a transaction has been declined.

**Comment by bradmac** [comment]
> This will let us know if an order has been paid or a transaction has been declined.

If the transaction has been declined, then the order has not been placed. I've added some labels on the detail page and tidied up the list page filtering to make this more obvious

![image](https://user-images.githubusercontent.com/826458/47189498-60113e80-d399-11e8-8b68-72d65474667d.png)

**Comment by Uafinder** [comment]
Yup, looks cools
