### ISSUE TITLE
Kademi: hide development urls from search engines 

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#6102]
When creating links in KEditor, and because end user clients are end user clients and will do what end user clients do which paste in full development URLs into links, this means that once a website in launched on Kademi, there is a potential for search engines spider and crawl both the development url and the TLD at the same time.

Is it possible for a platform wide implementation of: `<meta name="robots" content="noindex,nofollow">` when on a .kademi.com.au environment.

I think this is something that could appear on /theme/mainTemplate.html.

**Comment by bradmac** [comment]
Done

In bootstrap theme 3.3.7.51
and k-theme 1.6.6

**Comment by bradmac** [comment]
just needs this in the head
```
        #if( $rootFolder.versioned )
        <meta name="robots" content="noindex,nofollow"/>
        #end    
```
