### ISSUE TITLE
Profile page: remove possibility to remove last membership

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6103]
1. user should not be able to delete last membership
![image](https://user-images.githubusercontent.com/1945230/46729611-83980300-cc8e-11e8-9128-ec1bb0bf1868.png)

2. Also, he doesn't see opt-in groups and mail groups
![image](https://user-images.githubusercontent.com/1945230/46729487-2d2ac480-cc8e-11e8-945e-90c387ad265a.png)
![image](https://user-images.githubusercontent.com/1945230/46729493-30be4b80-cc8e-11e8-9ae2-d108c7c687f0.png)

3. No organization found when it should be
![image](https://user-images.githubusercontent.com/1945230/46729547-50ee0a80-cc8e-11e8-89ea-f99ed32d1e04.png)
![image](https://user-images.githubusercontent.com/1945230/46729551-56e3eb80-cc8e-11e8-88c8-6c883bb96f85.png)

http://vladtest54web-vladtest54.kademi-ci.co/profile/
http://vladtest54.admin.kademi-ci.co/manageUsers/17892757/#summary-tab

**Comment by anhnt** [comment]
> Also, he doesn't see opt-in groups and mail groups

I think we should show primary group here

>No organization found when it should be

Signup app needs to be enabled first

![image](https://user-images.githubusercontent.com/735555/47492797-fea90e00-d877-11e8-8d41-74785d040c88.png)

**Comment by anhnt** [comment]
>user should not be able to delete last membership

Done in https://github.com/Kademi/kademi-dev/issues/5798

**Comment by Uafinder** [comment]
yup
