### ISSUE TITLE
Sales data claimer error when click on team when team is rootorg

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6105]
![image](https://user-images.githubusercontent.com/1945230/46732319-d3c69380-cc95-11e8-82bf-ac203eb8f922.png)
http://vladtest54web-vladtest54.kademi-ci.co/claimer.html

**Comment by bradmac** [comment]
The submitter is the user who submitted the claim. The sales team is an optional field which can be selected when the claim is submitted. But that depends on the particular form being used to create the claim.

**Comment by Uafinder** [comment]
Looks good
