### ISSUE TITLE
Sales data claimer could not allow to do a claim

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6106]
![image](https://user-images.githubusercontent.com/1945230/46732514-594a4380-cc96-11e8-9d4e-1575b1f688fa.png)
Data series configured to sales group
user in sales group
He can't complete claim
http://vladtest54.admin.kademi-ci.co/manageUsers/17893560
http://vladtest54.admin.kademi-ci.co/manageUsers/17893495
When add user to admin - all seems to be fine

**Comment by bradmac** [comment]
Added required role:
![image](https://user-images.githubusercontent.com/826458/46764135-2789b900-cd38-11e8-8cc7-82fe7c0342c6.png)

http://vladtest54.admin.kademi-ci.co/groups/sales/

**Comment by Uafinder** [comment]
Ok, got it
