### ISSUE TITLE
Upload receipt button doesn't work on edit claim form

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6107]
![image](https://user-images.githubusercontent.com/1945230/46733644-8d733380-cc99-11e8-99a6-a9125e3ed983.png)
![image](https://user-images.githubusercontent.com/1945230/46732829-3ec49a00-cc97-11e8-891d-f404326c1ad6.png)
http://vladtest54.admin.kademi-ci.co/manageSaleDataClaimer/#claims-list-tab

**Comment by anhnt** [comment]
This feature hasnt been available. there is no js, or any code associates with it

**Comment by bradmac** [comment]
That is an important requirement. Even though normally claims are submitted through the front end, administrators need to be able to process claims users send through by email, including uploading the receipt.

**Comment by Uafinder** [comment]
Looks good
