### ISSUE TITLE
Sales data team column is empty

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6108]
![image](https://user-images.githubusercontent.com/1945230/46733717-c14e5900-cc99-11e8-8c29-b94e0b904e80.png)
![image](https://user-images.githubusercontent.com/1945230/46733724-c6130d00-cc99-11e8-9931-e167ad07d7b9.png)
http://vladtest54.admin.kademi-ci.co/sales/new-series/?query=&minValue=&maxValue=#history-tab

**Comment by bradmac** [comment]
Fixed.

Note that if the sales team is the current account its not displayed

**Comment by Uafinder** [comment]
ok
