### ISSUE TITLE
Sales claim list submitter column is empty

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6109]
![image](https://user-images.githubusercontent.com/1945230/46733857-2bff9480-cc9a-11e8-88d0-6a1f11276a96.png)
http://vladtest54.admin.kademi-ci.co/manageSaleDataClaimer/#claims-list-tab

**Comment by Uafinder** [comment]
weird, was empty

**Comment by bradmac** [comment]
Fixed.

There was a couple of different properties being used inconsistently, which should be resolved.

Note that some existing data might not display, please test with new data.

**Comment by Uafinder** [comment]
ok, looks good now
