### ISSUE TITLE
Error when change image for module

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6113]
![image](https://user-images.githubusercontent.com/1945230/46740111-b2bc6d80-ccaa-11e8-8e67-447a69736ee6.png)
![image](https://user-images.githubusercontent.com/1945230/46740127-c071f300-ccaa-11e8-979e-aa4bfd203bd3.png)
http://vladtest54.admin.kademi-ci.co/websites/vladtest54web2/version1/programs/p2/c1/m111/#details-tab

**Comment by anhnt** [comment]
Fixed, also changed to use only assets for now

![image](https://user-images.githubusercontent.com/735555/49153811-5e984600-f349-11e8-8cf8-8685e34584e4.png)

**Comment by Uafinder** [comment]
Same situation for me
Fresh account
![image](https://user-images.githubusercontent.com/1945230/49160510-91cddb80-f32f-11e8-8645-0503c6dc1970.png)
http://vladtest54yy.admin.kademi-ci.co/websites/vladtest54yyweb/version1/programs/p1/c1/m1/#details-tab

**Comment by bradmac** [comment]
@anhnt why change to use only assets? Modules live within a repository, so it makes sense to use repo assets. This makes version management easier. Assets exist outside of version management.

**Comment by bradmac** [comment]
@anhnt its using an incorrect url. Should be the root of the website:

http://localhost:8080/websites/activitywall/version1/_browse?browseHref=

**Comment by anhnt** [comment]
Finally fixed. @Uafinder please test uploading files on frontend as well as i have changed something relates to that.

**Comment by Uafinder** [comment]
Ok, loooks good
