### ISSUE TITLE
Sales claimer submit another serious issue

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6117]
For example we has a page with claim form.
We enter some claim info and push submit. Claim save correctly, and submit another claim button appears.
Hit it, claim form appears again. Enter some claim info and hit submit. System will create a claim, but it will be empty one.
http://vladtest54a.admin.kademi-ci.co/manageSaleDataClaimer/#claims-list-tab
![image](https://user-images.githubusercontent.com/1945230/46794967-a0e1d580-cd51-11e8-8bab-5431e2e96571.png)

**Comment by anhnt** [comment]
This was known issue whilst Yogesh working on cisco

**Comment by Uafinder** [comment]
Looks good
