### ISSUE TITLE
Sales claimer weird issue: code appears

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6118]
![image](https://user-images.githubusercontent.com/1945230/46795310-83613b80-cd52-11e8-8320-a8ff36405d1a.png)
http://vladtest54a.admin.kademi-ci.co/manageSaleDataClaimer/#claims-list-tab

It seems connected to upper non-approved claim, it takes team name from there. When you will approve it, code issue disappear.
![image](https://user-images.githubusercontent.com/1945230/46795566-1f8b4280-cd53-11e8-9805-ef2401daff3b.png)

**Comment by bradmac** [comment]
thats occurign when it has no sales team, but the preceding claim does.

Fixed.

**Comment by Uafinder** [comment]
Fine
