### ISSUE TITLE
Some debug thing appears in EDM editor

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6119]
![image](https://user-images.githubusercontent.com/1945230/46798292-2ff2eb80-cd5a-11e8-91d5-faa01d2edab0.png)
http://vladtest54a.admin.kademi-ci.co/groupEmails/17899686/edmeditor?fileName=index.html&useHash=true

**Comment by bradmac** [comment]
needs edmeditor-lib 1.2.2
