### ISSUE TITLE
Add path resolvers to custom apps

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#612]
add the ability to resolve url regexp groups in custom apps. if the method returns null then skip that controller and continue to the next.
to use this add this method to the controllerMappings
.addPathResolver("theGroupName", "theMethodToRun")
The following parameters get passed to the method for websites:
WebsiteRootFolder, GroupName, GroupVal

and for admin portal it's:
OrganisationRootFolder, GroupName, GroupVal

**Comment by bradmac** [comment]
Fast! You should watch more tv :)
