### ISSUE TITLE
Sales data component Leaderboard show all data by default (no matter of date range picker)

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6120]
Two same components
![image](https://user-images.githubusercontent.com/1945230/46799559-bfe66480-cd5d-11e8-81f3-190c8818b47a.png)
http://vladtest54a.admin.kademi-ci.co/websites/vladtest54aweb/version1?editTemplate=theme/apps/user/dashboard
http://vladtest54aweb-vladtest54a.kademi-ci.co/dashboard

**Comment by anhnt** [comment]
Fixed

**Comment by Uafinder** [comment]
Ok
