### ISSUE TITLE
Assign groups for kpolls should show group names

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6121]
![image](https://user-images.githubusercontent.com/1945230/46802505-28d1da80-cd66-11e8-893d-471903b39d78.png)
http://vladtest54a.admin.kademi-ci.co/kpoll/managePolls/poll-L091N7lE1Uo11PVWY1mOD9vMF2Tzv7jx/#groups-tab

**Comment by bradmac** [comment]
@anhnt this is because we changed the ManageGroupFolder to use the group ID instead of name. Please just update kpolls to use the group title

**Comment by anhnt** [comment]
Done

**Comment by Uafinder** [comment]
looks good
