### ISSUE TITLE
Theme checker issues

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6122]
Comes after this issue:
https://github.com/Kademi/kademi-dev/issues/5833
![image](https://user-images.githubusercontent.com/1945230/46802712-c62d0e80-cd66-11e8-833f-99ca06344965.png)
Users-lib
![image](https://user-images.githubusercontent.com/1945230/46802729-d7761b00-cd66-11e8-9e4b-f375f75ffac6.png)
Claims tag
![image](https://user-images.githubusercontent.com/1945230/46802738-df35bf80-cd66-11e8-9bf7-f25ab6cc4a57.png)
Top purchased

**Comment by Uafinder** [comment]
Also
![image](https://user-images.githubusercontent.com/1945230/47214167-c8feb380-d3a5-11e8-9319-9e27e2ac1ca3.png)
ecom order history
http://vladtest54g.admin.kademi-ci.co/websites/vladtest54gweb/version1/#panel_details-tab

Same for products topPurchased
![image](https://user-images.githubusercontent.com/1945230/47214220-f77c8e80-d3a5-11e8-95c0-59aeb266482e.png)

Same for claims tag
![image](https://user-images.githubusercontent.com/1945230/47214306-2a268700-d3a6-11e8-87f4-44066110fee0.png)
http://vladtest54g.admin.kademi-ci.co/websites/vladtest54gsales/version1/#panel_details-tab

**Comment by bradmac** [comment]
orderHistoryECom is from the ecommerce-lib, which is deprecated. Its not used by KCom2 so can be ignored

**Comment by bradmac** [comment]
Moved topPurchased issue here - https://github.com/Kademi/kademi-dev/issues/6183

**Comment by bradmac** [comment]
claimsTag is deprecated, will be removed in future and can be ignored for now

**Comment by bradmac** [comment]
@Uafinder if there's nothing else this issue can be closed

**Comment by Uafinder** [comment]
gotcha
