### ISSUE TITLE
KConfirm: birth date not showing calendar to choose date

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6123]
![image](https://user-images.githubusercontent.com/1945230/46803112-f45f1e00-cd67-11e8-9b27-16279e9e786f.png)

Also,
I think this is a boolean markers for settings
![image](https://user-images.githubusercontent.com/1945230/46803183-27a1ad00-cd68-11e8-8006-220be99d1047.png)
http://vladtest54a.admin.kademi-ci.co/manageUsers/17899177

**Comment by anhnt** [comment]
Fixed in KConfirm 1.0.5

**Comment by Uafinder** [comment]
It works
