### ISSUE TITLE
Profile issue for admin user

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6125]
Interests section appears twice
![image](https://user-images.githubusercontent.com/1945230/46804885-73eeec00-cd6c-11e8-9bcd-bd77aefd1d6d.png)
http://vladtest54aweb-vladtest54a.kademi-ci.co/profile/
http://vladtest54a.admin.kademi-ci.co/manageUsers/17898480/#summary-tab

**Comment by anhnt** [comment]
cant reproduce

**Comment by Uafinder** [comment]
reproduced here
http://vladtest54s.admin.kademi-ci.co/manageUsers/18180657
try this user and access profile
i think that's a Blog app related issue

**Comment by anhnt** [comment]
Fixed

**Comment by Uafinder** [comment]
Yup, it's ok now
