### ISSUE TITLE
KCom2 - system setting that allows us to show more than the 12 default products at a time.

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#6126]
May we please have a setting that allows us to adjust the default number of products to show on a page, before infinite scrolling takes over.

In fact all KCom2 projects I'm working on currently all run into the issue to only showing 12 items max. And I haven't seen infinite scrolling working correctly either. (this may be because of custom components, but the main point is having a setting that allows us to show an x amount of products by default.

https://plantae.co.nz/online-store/ only shows 12 products, should be more.
http://version1.waterware-waterware.kademi.com.au/store/tapware/fluid/ only shows 12 products, should be hundreds
http://farmgard-farmgard.kademi.com.au/farmgard-ecomstore/agricultural-contractor/cultivation-agricultural-contractor/ only shows 12 products, should be at least 17, some even 20 products.

**Comment by stephen-fueldesign** [comment]
BTW, Hazero shows infinite scrolling. So we know that works well.

http://hazero-hazero.kademi.com.au/products/store/

**Comment by bradmac** [comment]
@anhnt please add a setting to set the "page size", ie the number of products to fetch initially and also on subsequent page loads

**Comment by anhnt** [comment]
Done, this should be configured via KCommerce2 website app settings

![image](https://user-images.githubusercontent.com/735555/46932619-bb31f100-d07a-11e8-955e-b95f1d46cae1.png)

**Comment by bradmac** [comment]
hey @anhnt sorry for misunderstanding, what i meant was can we please add this as a component setting?

**Comment by anhnt** [comment]
Done 
![image](https://user-images.githubusercontent.com/735555/46944565-95b5df00-d09c-11e8-838b-6bc697f3596d.png)


I've moved code from js to component source. If someone wants to apply this to existing site please have a look at component source code below

- storeProductListComponent.html
- ecomStoreSidebarComponent.html

**Comment by anhnt** [comment]
Requires KCom2 version 1.2.0

**Comment by Uafinder** [comment]
Looks good
