### ISSUE TITLE
KCom2: Images with non-square form cropped on checkout form

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6133]
![image](https://user-images.githubusercontent.com/1945230/46861593-a572c080-ce1b-11e8-8317-1c992f403c48.png)
http://vladtest54bweb-vladtest54b.kademi-ci.co/vladtest54bweb-ecomstore/cart

**Comment by bradmac** [comment]
I think this is correct. Images do need to be cropped to fit.
