### ISSUE TITLE
KCom2: address issue when checkout

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6136]
For example we have some addresses predefined for user
http://vladtest54b.admin.kademi-ci.co/manageUsers/17908808/#general-tab
![image](https://user-images.githubusercontent.com/1945230/46868830-55ebbf00-ce32-11e8-9f26-352d27f9c290.png)
We select home address and moving forward
When we land on final checkout screen and check address we decide to change it from home to say work address.
![image](https://user-images.githubusercontent.com/1945230/46868986-fcd05b00-ce32-11e8-99ea-cbfd48f79272.png)

WE click back two times to return to address selection screen
and change address to work
![image](https://user-images.githubusercontent.com/1945230/46868881-90555c00-ce32-11e8-974d-057107d5b5eb.png)
then click forward two times
but when we go back we seeing that previous home address appears in form
![image](https://user-images.githubusercontent.com/1945230/46868920-c4c91800-ce32-11e8-985b-844821230b4e.png)
Only hard refresh helps to solve that

**Comment by bradmac** [comment]
Note that this is just pre-populating, there is no reason why the delivery address is necescarily the same as the credit card address. Eg when i use the Kademi credit card the 2 addresses are always different.

So is a low priority issue

**Comment by Uafinder** [comment]
looks solved in some other issue
