### ISSUE TITLE
KCom2: Brands issue

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6138]
For example we have some brands
Brand it's a simple category
So it's display in Category filter, same selection appears in "Browse by Brand"
the workaround is to create a Brands category and push all brands under it.
![image](https://user-images.githubusercontent.com/1945230/46869334-11612300-ce34-11e8-9ab6-b1327a59b4f3.png)
but all of this brands will still available in Categories selector component
http://vladtest54bweb-vladtest54b.kademi-ci.co/vladtest54bweb-ecomstore/
So my suggestion is to mark categories which are selected as brand somehow and do not display them in selection list and in left panel

**Comment by bradmac** [comment]
This is correct. Brands are categories, but it is up to the administrator to decide whether they want it part of the category browse hierarchy or not.

I've seen some stores that do and others that do not
