### ISSUE TITLE
KCom2: browse by price

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6139]
Not quite understand how "Browse by price" section works
Why it dislpay only 5 products with such a high priceses and ignores those are with lower ones
![image](https://user-images.githubusercontent.com/1945230/46869552-e62b0380-ce34-11e8-98f9-c1a1a8511fba.png)
Also, not quite understand why it show say 490 to 990 instead of 500-1000. Current user have no discounts.
http://vladtest54b.admin.kademi-ci.co/manageUsers/17908808/#summary-tab

**Comment by bradmac** [comment]
> Why it dislpay only 5 products with such a high priceses and ignores those are with lower ones

The counts should show the number of products in each price range. Of course the total should equal the total number of products in the search results. Is that the case?

> Also, not quite understand why it show say 490 to 990 instead of 500-1000. Current user have no discounts.

The price ranges are determined dynamically, based on the highest and lowest costs in the matched results, and this range is then split

**Comment by bradmac** [comment]
Fixed. Was missing the first range.

**Comment by Uafinder** [comment]
Looks good
