### ISSUE TITLE
Implement portlets for controller mapping on content app

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#614]

**Comment by bradmac** [comment]
Hey @tuzzmaniandevil i think you might need to refactor slightly so that this only applies to WebsiteRootFolder

Also, we need to ensure the resolvers stuff is encapsulated inside the controllermappings class

**Comment by tuzzmaniandevil** [comment]
I've refactored it so it only applies to WebsiteRootFolder's now :+1:

**Comment by tuzzmaniandevil** [comment]
Sorted the resolvers stuff as well
