### ISSUE TITLE
KCom2: You may interested modal layout bad

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6140]
![image](https://user-images.githubusercontent.com/1945230/46869853-b3cdd600-ce35-11e8-8ae5-df53ccc60fa3.png)
http://vladtest54bweb-vladtest54b.kademi-ci.co/vladtest54bweb-ecomstore/fitbit000
When add to cart something, modal you may also like appears. It's layout looks ugly.

**Comment by bradmac** [comment]
I think we need fixed heights

**Comment by Uafinder** [comment]
Still bad
![image](https://user-images.githubusercontent.com/1945230/48481035-d37d6300-e814-11e8-8ee0-71df0520d369.png)
http://vladtest54ttweb-vladtest54tt.kademi-ci.co/vladtest54ttweb-ecomstore/samt000

**Comment by anhnt** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/735555/48486788-14926900-e84f-11e8-8c08-6bca8bfd9911.png)

**Comment by Uafinder** [comment]
Looks good
