### ISSUE TITLE
Let website controller mappings define admin pages as well

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#615]
This only needed to be implemented in Content App

**Comment by bradmac** [comment]
@tuzzmaniandevil i dont think that will work. Checkout getBranch in orf:

    /**
     * Required for WebsiteBranchResource, but returns null
     * @return
     */
    @Override
    public Branch getBranch() {
        return null;
    }

**Comment by bradmac** [comment]
And i dont think we should do this, its fundamentally inconsistent to have a version of a website defining organisation level resources. Instead, use an app.

**Comment by tuzzmaniandevil** [comment]
I was rather nervous about doing it in the first place. Removing
