### ISSUE TITLE
kcom2: Non logged in user could not proceed

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6153]
1. Go to site
http://vladtest54bweb-vladtest54b.kademi-ci.co/vladtest54bweb-ecomstore/
2. Select some goods
3. Add them to cart
![image](https://user-images.githubusercontent.com/1945230/46875997-da940880-ce45-11e8-8fdb-b3495b7e6cd3.png)
4. Note that cart is not appear
5. When you click on checkout - your cart is empty
![image](https://user-images.githubusercontent.com/1945230/46876029-ec75ab80-ce45-11e8-8239-ff76951bc391.png)

**Comment by bradmac** [comment]
Looks ok

![image](https://user-images.githubusercontent.com/826458/46892204-1a500400-cec9-11e8-96b1-9acef018a35a.png)

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/46892299-68650780-cec9-11e8-8ce3-9afa4eb81683.png)

**Comment by Uafinder** [comment]
hmmm... i'm able now too

**Comment by Uafinder** [comment]
Reproduced
it happens when
- non-logged in user submitting order (and create account)
- then click on continue shopping button
- then tried to add something to a shopping cart
![image](https://user-images.githubusercontent.com/1945230/47001869-28558d00-d134-11e8-813c-a68fdf1d1cd5.png)
![image](https://user-images.githubusercontent.com/1945230/47001880-2c81aa80-d134-11e8-8764-56e21f8a1848.png)

Curing only by clearing cache

**Comment by anhnt** [comment]
Fixed in other issue. Now when non logged in user who then created an account and placed an order, they will be logged in automatically so when they click "Continue shopping" and add some more products to the cart, it shows items on checkout page

**Comment by Uafinder** [comment]
Looks good now
