### ISSUE TITLE
Move JS to bottom of body to avoid blocking rendering

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6154]

**Comment by bradmac** [comment]
Just doing bootstrap-theme for now

**Comment by bradmac** [comment]
bootstrap-theme - 3.3.7.52

**Comment by bradmac** [comment]
Done, but will need thorough testing of all apps and components in frontend

**Comment by Uafinder** [comment]
looks good so far... will raise issue if spot something related to this
