### ISSUE TITLE
KCom2 - Orders and transaction pages needs more information in admin

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#6155]
Customers are finding it very difficult to determine which transactions have shipping or voucher codes applied, and how much each transaction has been as the admin list mainly shows product total, and not order total. And then looking at an order it shows the product order total and not total order including shipping. Then the shipping breakdown does not show the cost of shipping provider, and an applied voucher does not include or show the amount redeemed.

**Orders examples 1 (_mostly correct_):**
https://plantae.admin.kademi.com.au/shopping-carts/129116099/
- Order total: $1. (_Correct as the transaction was $1 products + $5 shipping - $5 voucher_)
- Shipping: $5. (_does not display, no idea how much shipping is_)
- Voucher: $5. (_does not display, no idea how much has been redeemed. Can see voucher code._)

**Orders example 2 (does not give true picture)**
https://plantae.admin.kademi.com.au/shopping-carts/129330401/
- Orders total $1. (_Incorrect, needs to show $6. $1 product + $6 shipping - $0 voucher = $6 order_)
- Shipping: $5. (_does not display, no idea how much shipping is_)
- Voucher: blank. (_not applicable_)

**Admin Orders list page**
Admin Orders list page does not give true reflection of the order total... only product total.
<img width="1419" alt="orders" src="https://user-images.githubusercontent.com/39784677/46921652-90d03b80-d05a-11e8-8b08-6a8f31fad5c4.png">

**eWAY Paymens > Transactions is more accurate.**
<img width="1372" alt="ewaypayments" src="https://user-images.githubusercontent.com/39784677/46921680-e9073d80-d05a-11e8-962d-a6885c115c4b.png">
- would be nice if transactions list could have a link directly to the orders page. Unless orders list page more accurately describes the order then this transactions page becomes trivial.

**Comment by bradmac** [comment]
> Voucher: $5. (does not display, no idea how much has been redeemed. Can see voucher code.)

Note this is a link, so just click through to the voucher. But i've added the dollar amount:
![image](https://user-images.githubusercontent.com/826458/46922150-5cac4900-d061-11e8-8c17-4ecb748ed746.png)

**Comment by bradmac** [comment]
Note that in the order above no shipping provider was selected:

![image](https://user-images.githubusercontent.com/826458/46922254-bc572400-d062-11e8-9608-2331de60b7f7.png)

**Comment by bradmac** [comment]
@stephen-fueldesign says new accounts only get an option of international:

> - I created a new account
- then asks for shipping address.
- Once selected gives a shipping option of international shipping only.
- even though my amount is less than 100, and NZ.
- Note: international shipping option has no restrictions, always displays. It's the default.

**Comment by bradmac** [comment]
@stephen-fueldesign please check you have this in your storeCheckout.js

```    function doQuantityUpdate(cartHref, lineItemId, quantity) {
        flog("doQuantityUpdate", cartHref);

        var actors = $('.btn-decrease-quantity, .btn-increase-quantity, .ecom-txt-quantity, .btn-ecom-remove-item');
        actors.prop('disabled', true);

        $.ajax({
            type: 'POST',
            url: cartHref,
            data: {
                changeItemId : lineItemId,
                newQuantity: quantity
            },
            datatype: "json",
            success: function (data) {
                $("#ecomItemsTable, #cart-link, #cart-checkout-data, #shipping-provide-select").reloadFragment({
```

The key part is "#shipping-provide-select" on the last line

**Comment by bradmac** [comment]
We're now adding an order narrative to the notes section:
![image](https://user-images.githubusercontent.com/826458/46927057-20dca800-d090-11e8-9f8a-b4516f7437a2.png)

**Comment by bradmac** [comment]
Updated narrative
```
Toaster, Large x 11.00 = 181.10400000
Freight: 0
Total: 181.10400000
Payment result: OK, transaction ID 18652872
```

**Comment by bradmac** [comment]
OK, so i think between the 2 things discussed above should be ok
- apply updated web component JS so the shipping options are refreshed on changing quantity
- better visibiliy on the admin page

**Comment by Uafinder** [comment]
Both looks good
