### ISSUE TITLE
kCom2: can't make additional grouping for products work

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6157]
![image](https://user-images.githubusercontent.com/1945230/46944312-64c4b280-d07a-11e8-82cc-347ec57f2959.png)
http://vladtest54b.admin.kademi-ci.co/ecommerce/#settings-tab
![image](https://user-images.githubusercontent.com/1945230/46944328-6c845700-d07a-11e8-95a0-766ce1e7f206.png)
http://vladtest54bweb-vladtest54b.kademi-ci.co/vladtest54bweb-ecomstore/

**Comment by bradmac** [comment]
Thats not correctly setup.

The settings should just have the name (ie identifier) of extended attributes, and the text to display for it. This should not include values (eg Red, Gold), as Kademi gets them from the actual products

![image](https://user-images.githubusercontent.com/826458/46977813-a19bb280-d129-11e8-9bcf-cc20c3fe90ae.png)

**Comment by bradmac** [comment]
To use this you first need to create a content type called "product" with the extended fields you want:

![image](https://user-images.githubusercontent.com/826458/46977887-d0b22400-d129-11e8-90fa-1bf15cdc5fff.png)

**Comment by bradmac** [comment]
Then, to configure a product, go to its "Attributes" tab and create an asset, then edit the extended values on the asset. You will then see them on the product attributes tab:

![image](https://user-images.githubusercontent.com/826458/46977938-f63f2d80-d129-11e8-9262-2ff843dd66bb.png)

**Comment by Uafinder** [comment]
got it
