### ISSUE TITLE
kCom2: path component settings gets 500 error

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6161]
![image](https://user-images.githubusercontent.com/1945230/46956824-edede080-d09e-11e8-8310-b572781a13f2.png)
![image](https://user-images.githubusercontent.com/1945230/46956894-137aea00-d09f-11e8-9b0a-3e5a815e36fc.png)
http://vladtest54cc.admin.kademi-ci.co/websites/vladtest54ccweb/version1?editTemplate=theme/apps/KCommerce2/viewStore

**Comment by anhnt** [comment]
There is no setting for this component

**Comment by Uafinder** [comment]
Cools
