### ISSUE TITLE
KCom2 - myriad of Shipping Address / Shipping provider issues.

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#6162]
Hi, I have done some extensive testing and found quite a few issues with shipping address and shipping provider during the checkout process.

This is a critical issue. Plantae are getting antsy, to say the least.

_Bear in mind that the majority of these issues occur for a non logged in, or a new user. Returning users, and by extension, debuggers, are not getting many of these issues._

Bug list
1. Shipping provider does not update when Shipping Address > Country is changed.
2. Shipping provider does not update, even on hard refresh, if browser selects country address for you from address auto-fill.
3. Previous button not working on "Please enter your details to create new account" once you enter a new test email address, cannot go back.
4. Previous button on "Shipping providers" page does not work correctly. Seems to display both "Please enter your password" panel and "Shipping address" panel.

**Scenario 1) _Let browser pre-select your address_**
- **Browser**: Chrome
- **Product**: Sea Buckthorn Berry Night Cream, 1, $99.90
- **Please enter your email**: test-test@test.com > next
- Skip creating account
- **Shipping address**:  Click address field and let Chrome select your address from browser saved fields. Make sure your country in NZ. _(99% of the use case scenario follow this exact step)_
- Bug: **Shipping provider**: International (should be NZ shipping and International Shipping)
- **Bonus**: Change product selection quantity to an amount above $100 to give you free shipping.
- Bug: **Shipping provider**: International (should be Free shipping and International Shipping)

**Scenario 2) _User manually selects address_**
- **Browser**: Chrome
- **Product**: Sea Buckthorn Berry Night Cream, 1, $99.90
- **Please enter your email**: test-test@test.com > next
- Skip creating account
- **Shipping address**:  Manually enter your address, and choose New Zealand as your country. _(only by manually typing in your country, will the country ever be selected)_
- Bug: **Shipping provider**: International (should be NZ shipping and International Shipping)
- **Bonus**: Change product selection quantity to an amount above $100 to give you free shipping.
- Working: **Shipping provider**: Free Shipping, International (Seems shipping provider refreshes correctly when a quantity is updated.

There are more scenarios, but this is good enough.

Do you needs screenshots?

**Comment by anhnt** [comment]
Fixed on plantae and applied to standard Kcom2

**Comment by Uafinder** [comment]
3,4 fixed

**Comment by Uafinder** [comment]
Looks good now
@stephen-fueldesign  could you check as well?

**Comment by stephen-fueldesign** [comment]
@Uafinder Confirmed, 3 and 4 are working. Previous buttons functioning as expect. Thanks @anh for applying to Plantae; much appreciated.

**Comment by bradmac** [comment]
Seems like everyone is happy...
