### ISSUE TITLE
KCom2 - EDM, /common/ components bugs and updates

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#6163]
**Example: common > billingInformationComponent.html**
https://plantae.admin.kademi.com.au/emails/130635342

1. please can we have name, email and phone fields.
2. name and phone fields are currently blank - not pulling out profile details.

**Example: common > purchasedProductsComponent.html**
https://plantae.admin.kademi.com.au/emails/130635342

1. Can this component show shipping amount if there is a cost associated
2. Can tax row not show if tax amount in "$0.00"

**Comment by anhnt** [comment]
Fixed in standard kcom2. @stephen-fueldesign please see my change and apply to plantae.

**Comment by stephen-fueldesign** [comment]
Hi Anh, has this been rolled out? As this is in /common/, every time we update kcom, it overrides the updates I do, which is fine, I get that... just that I'm on kcom2 1.1.7 (same as before) and don't see any changes.

Am I to look up the reference on a newer version on the ci server?

**Comment by bradmac** [comment]
> Hi Anh, has this been rolled out? As this is in /common/, every time we update kcom, it overrides the updates I do

@stephen-fueldesign your overrides should be in your website, so will not be lost on a version update. If you're making changes in the lib itself ... please dont do that :)

**Comment by stephen-fueldesign** [comment]
Anh recommend that in order to remove the tax field, as an example, I had to edit the libs.

Is there another place I should be doing this?

If this can be updated, per site, without editing the lib itself please let me know as I don't want to be editing the lib.

**Comment by bradmac** [comment]
As discussed, definitely do not ever edit a lib directly, unless we've arranged to merge your code changes back into source control.

Just override in your site normally

**Comment by Uafinder** [comment]
looks good on CI
