### ISSUE TITLE
Kcom2: creating account doesn't catch first and last name fields

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6165]
![image](https://user-images.githubusercontent.com/1945230/47001581-7a49e300-d133-11e8-8deb-b07a73e56f55.png)
http://vladtest54d.admin.kademi-ci.co/manageUsers/17941214/#general-tab
![image](https://user-images.githubusercontent.com/1945230/47001716-cac14080-d133-11e8-8404-981ddd807039.png)

Also account created only after submitting order, not after creating button create account

**Comment by anhnt** [comment]
I can see the problem: it created new account based on final checkout form (form with card details fields)
- It doesnt create new account when submit create account form
- it doesnt prepopulate details on final card checkout form

I think we just need to fix first point, then it will auto pre-populate the final form

![image](https://user-images.githubusercontent.com/735555/47009213-1ee51880-d166-11e8-881e-736957a32005.png)

![image](https://user-images.githubusercontent.com/735555/47009312-5eac0000-d166-11e8-8abc-ab217863196b.png)

**Comment by anhnt** [comment]
All sorted

**Comment by Uafinder** [comment]
Looks good
