### ISSUE TITLE
kcom2: logout not possible from checkout

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6173]
![image](https://user-images.githubusercontent.com/1945230/47070797-ab411b00-d1fa-11e8-8c03-082d27e506f5.png)
![image](https://user-images.githubusercontent.com/1945230/47070811-b300bf80-d1fa-11e8-8929-ec486c8adfe9.png)
![image](https://user-images.githubusercontent.com/1945230/47071028-299dbd00-d1fb-11e8-82d8-f2addf76a1d0.png)
logout button doesn't work
http://vladtest54eweb-vladtest54e.kademi-ci.co/vladtest54eweb-ecomstore/cart

**Comment by anhnt** [comment]
Fixed

**Comment by Uafinder** [comment]
Looks good
