### ISSUE TITLE
kcom2: freight cost per item counts as item type

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6174]
![image](https://user-images.githubusercontent.com/1945230/47072707-43d99a00-d1ff-11e8-809a-24473b814cb8.png)
E.g. we have 2.5$ cost per item, but it counts 2.5$ per item type. E.g. 10 Iphones of one type will cost 2.5$ for all. Should be 2.5*10=25$
http://vladtest54eweb-vladtest54e.kademi-ci.co/vladtest54eweb-ecomstore/cart
![image](https://user-images.githubusercontent.com/1945230/47072772-708db180-d1ff-11e8-8731-4fc81560b65c.png)
http://vladtest54e.admin.kademi-ci.co/ecommerce/vladtest54eweb-ecomstore/?shippingId=universaldelivery

**Comment by bradmac** [comment]
This is correct, although the label on the shipping admin page is misleading.

This factor should be applied to each line item, and is intended to be used for processing/admin fees which are independent of the quantity (eg for tickets, prepaid cards, etc)

I've updated the text to help clear that up:
![image](https://user-images.githubusercontent.com/826458/47126010-f7678a80-d2e2-11e8-9042-dbbb9408c149.png)

**Comment by bradmac** [comment]
To have a cost which is dependent on the quantity, use the freight cost on the product

![image](https://user-images.githubusercontent.com/826458/47126029-0cdcb480-d2e3-11e8-9ddb-4f49de3291ed.png)

So freight in this case (quantity = 3) is 
3 x 1.60 + 1.25 = 6.05

![image](https://user-images.githubusercontent.com/826458/47126044-24b43880-d2e3-11e8-8625-83dc3d78ed1b.png)

**Comment by Uafinder** [comment]
looks clear
