### ISSUE TITLE
kcom2 - ability to customise default searchResult to control the default order of products.

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#6175]
Example, Farmgard would like to order their products by position.
Another client may want by price, or alphabetically, etc.

I do like the default method as it stands; however so far all our clients are asking for more control determining the order of products.

**Comment by bradmac** [comment]
@anhnt please take a look. I think we should add a setting to the product list component to control the sort order.

**Comment by anhnt** [comment]
Done, requires `KCommerce2 1.2.3`

![image](https://user-images.githubusercontent.com/735555/47132431-03951d00-d2ce-11e8-92c1-5fe63cbd4a75.png)

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/47132453-1c9dce00-d2ce-11e8-8d33-1b887792fdd4.png)

**Comment by Uafinder** [comment]
This is sorting by title
![image](https://user-images.githubusercontent.com/1945230/47153122-5202e580-d2e7-11e8-9910-6b4c4012f2e5.png)
http://vladtest54fweb-vladtest54f.kademi-ci.co/vladtest54fweb-ecomstore/

looks work incorrectly
http://vladtest54f.admin.kademi-ci.co/websites/vladtest54fweb/version1?editTemplate=theme/apps/KCommerce2/viewStore

**Comment by anhnt** [comment]
Fixed

**Comment by Uafinder** [comment]
Looks good
