### ISSUE TITLE
Moving JS scripts to bottom of <body> tag causing some issues.

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#6176]
Getting issues with googleMap functions and not being able to run any jQuery code, inline.

I do believe moving scripts to the bottom with anync and deferred is the right move.

We will start to create our own scripts for events and dom ready functions. This is expected by front end developers, and we don't mind.

All inline JS will be held in functions. and not directly as jQuery (as it's most likely not loaded while inline scripts are called).

**Comment by bradmac** [comment]
```
uncaught exception: InvalidValueError: onGoogleMapReady is not a function
```

**Comment by bradmac** [comment]
@anhnt as dicussed, consider introducing  an array variable like pageInitFunctions which libs like gmaps can push functions into, and gets run after jquery is loaded

**Comment by anhnt** [comment]
Fixed, requires
- bootstrap-base 2.0.0
- googlemap-lib 1.0.5
- k-theme 1.6.7 or bootstrap-theme 3.3.7.53
