### ISSUE TITLE
Error on KPoll submission

### ISSUE THREAD

**Issue by yrsengar** [Kademi/kademi-dev#6177]
When a user submits the poll answer instead of loading results it show error (screenshot attached) but the console is clean so no errors there. When you come back to the poll page and refresh, it does load the results. 
![screen shot 2018-10-19 at 3 22 48 pm](https://user-images.githubusercontent.com/10014469/47194179-dbcbb500-d3b2-11e8-8174-448189237cb9.png)

![screen shot 2018-10-19 at 3 22 08 pm](https://user-images.githubusercontent.com/10014469/47194166-ceaec600-d3b2-11e8-8573-bed4a1c68cc7.png)

**Comment by bradmac** [comment]
@yrsengar  the form handler hasnt been initialised (most likely)
that can be because
- there is a JS error on page load, or
- the class or ID the init code uses to identify the form is different inthe actual html

**Comment by bradmac** [comment]
So please check if this is just due to customisation, or a JS error (ie probably not relted to KPolls)
