### ISSUE TITLE
Auctions not finishing after time run out

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6179]
![image](https://user-images.githubusercontent.com/1945230/47221622-91036a80-d3bd-11e8-8eb5-990a41dc4bf2.png)
http://vladtest54gggweb-vladtest54ggg.kademi-ci.co/auctions/
http://vladtest54ggg.admin.kademi-ci.co/auctions/
Will provide more details on Monday

**Comment by bradmac** [comment]
Ive seen auctions completing correctly when testing the journey node, so please confirm and provide details

**Comment by Uafinder** [comment]
Nah... can't reproduce...
It looks dedicated to timezone somehow... will try to reproduce on fresh account
