### ISSUE TITLE
Feature request: Claim tracking table

### ISSUE THREAD

**Issue by yrsengar** [Kademi/kademi-dev#6189]
The client is requesting for a table where they can show claim history.
In this project we have 3 types of claims and all 3 has different sets of information so the tables needs to show the related data of a specific claim based on its type.

http://ciscoengage-cisco.kademi.com.au/make-claim.html

**Comment by bradmac** [comment]
That sounds like a customisation to me.

**Comment by yrsengar** [comment]
From my understanding, the data for all types of claims come through one data series and the backend interface to hide the columns which are not required for each claim type would be the solution for this.

**Comment by bradmac** [comment]
As discussed, i suggest doing this as a customisation to achieve the exact layout requirements of the client
