### ISSUE TITLE
admin module manager: create new page with simple form

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#6191]
![image](https://user-images.githubusercontent.com/735555/47408732-bb24a600-d78a-11e8-9ede-7a7599cc9bc7.png)

As discuss we should show page title field only. they can edit page thru editor then

**Comment by anhnt** [comment]
Done 

![image](https://user-images.githubusercontent.com/735555/47408953-67668c80-d78b-11e8-8e35-338443ce5ddc.png)

**Comment by Uafinder** [comment]
Cools...
