### ISSUE TITLE
KConfirm: ampersand encoding issue

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6192]
![image](https://user-images.githubusercontent.com/1945230/47427499-22495700-d799-11e8-9f06-afb548673552.png)
http://vladtest54j.admin.kademi-ci.co/manageUsers/17999583/#general-tab
Comes from here
https://github.com/Kademi/projects/issues/788

**Comment by bradmac** [comment]
Fixed.

Problem was on saving, so existing data will still appear this way, but new data should save and be displayed without encoding characters

**Comment by Uafinder** [comment]
Looks good now
