### ISSUE TITLE
kcom2 checkout - shipping dropdown box not working for someone logging in during checkout.

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#6193]
I tested on http://version2.plantae-plantae.kademi.com.au/online-store/cart (sandboxed testing account) - but can confirm bug appears on default settings too.

Seems that when you log in during steps 1 and 2, that the shipping drop-down field is blank.
A simple page refresh and the drop-down is populated.

Most people will not be logged in to begin with; unlike us during testing, were we tend to be logged in.

**Comment by bradmac** [comment]
Confirmed with this user:
https://plantae.admin.kademi.com.au/manageUsers/129003930/#general-tab

@anhnt please just add a reloadFragment on the shipping panel after logged in.

**Comment by anhnt** [comment]
Duplicates https://github.com/Kademi/kademi-dev/issues/6172
