### ISSUE TITLE
Kcom2 - Shipping Provider still not appearing correctly.

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#6195]
Got this message from Plantae

> We just tested this ourselves, we’re trying to place an order without signing up for an account and even after putting an address in NZ into the address form the only option given is international shipping.  Please fix ASAP.

**Note**: live version is sitting on KCom2 1.1.7
https://plantae.co.nz/
**Version2**: is KCom2 1.2.3 (_latest_)
http://version2.plantae-plantae.kademi.com.au/profile/

I will update this ticket with more information from customer. And I will try and replicate issue, but I think Safari has issues, I tested 1.1.7 on FF and Chrome and it worked.

**Comment by stephen-fueldesign** [comment]
I can confirm that even with KCom2 1.2.6 (_latest_) that a user can proceed to shipping provider page without correctly having selected a country.

This can occur on many levels, either browsers auto-populating fields and/or users typing in a country and no selecting the smart lookup search results dropdown. They simply type in their country name and move on.

I believe that the hidden country input field needs to be made required, in the very least; even though it's hidden. There should never be an instance that a user lands on the Shipping Provider's page without a country have been selected (_for whatever reason_)

I think this needs to be a priority fix.

**Comment by stephen-fueldesign** [comment]
Attached is a video showing the following:

Chrome on Mac
1. Browser auto-populating shipping address
2. User typing in "New Zealand" manually, but not clicking on dropdown. Shipping provider should be NZ, not international.
3. User typing in "New" then selected "New Zealand" from the dropdown list (_which in itself is confusing because a) kademi provides a list of countries, b) browser may provide an auto-fill option too, on top of kademi's list_)
4. Once typing in "New", and selecting "New Zealand", system correctly choosing country code, but leaves input field as "New" and does not replace with "New Zealand".
5. Have to click kademi's dropdown twice in order to input field to show "New Zealand" - to match your selection.


[checkout-shipping.mov.zip](https://github.com/Kademi/kademi-dev/files/2516717/checkout-shipping.mov.zip)

**Comment by bradmac** [comment]
Made 2 changes:
- the country code hidden input is now cleared on keydown in the typeahead input
- we do an explicit check on the country code hidden input before proceeding

the result is that the user cannot proceed without a country code being selected, and if they start searching but dont select a country, then any previously selected country code will be cleared.

![image](https://user-images.githubusercontent.com/826458/47533991-44b2b000-d912-11e8-9b20-3c6665f05bd0.png)

**Comment by bradmac** [comment]
Changes:
![image](https://user-images.githubusercontent.com/826458/47534110-a246fc80-d912-11e8-9ef9-0d6cbb98ad8a.png)

**Comment by bradmac** [comment]
Requires KCommerce 1.2.8

**Comment by stephen-fueldesign** [comment]
awesome, that will solve many of the issues. Will test in due course.

**Comment by bradmac** [comment]
New UI
![image](https://user-images.githubusercontent.com/826458/47537654-84ce5e80-d923-11e8-8724-788ce5002948.png)

**Comment by bradmac** [comment]
Also working on defaulting the country based on the IP

**Comment by stephen-fueldesign** [comment]
@bradmac cannot get this working in testing.

**Comment by stephen-fueldesign** [comment]
working

**Comment by Uafinder** [comment]
Looks good
