### ISSUE TITLE
Kcom2 - Shipping address needs to have recipients name, phone number and email address.

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#6197]
The destination shipping address and details need to have a distinction between account holder and shipping.

But even more importantly, packing slips needs to including shipping details such as Recipients Address, Name, Email and Phone.

And often times these are different to billing details.

This is not edge case.

**Comment by bradmac** [comment]
Sorry, i dont understand. Can you provide a screenshot showing what you mean?

**Comment by bradmac** [comment]
Firstname/lastname for delivery makes sense since we often need to identify who the package is to be delivered to, and a phone number can be handy as a contact if the courier has trouble finding them.

But I dont think it makes sense to collect the email address again, that should always be for the purchaser. If the courier etc wants to make contact by email it should be to the purchaser.

**Comment by bradmac** [comment]
So what i think we should do is
- add firstname, surname. phone to the shipping form, which will be captured on the cart/order
- also add phone number to the create account screen, which will be captured on the profile

**Comment by bradmac** [comment]
New UI
![image](https://user-images.githubusercontent.com/826458/47537654-84ce5e80-d923-11e8-8724-788ce5002948.png)

**Comment by bradmac** [comment]
Also working on defaulting the country based on the IP

**Comment by bradmac** [comment]
@anhnt can you please finish this off by defaulting the country when it has no initial value?

Note that the value from the Geo IP service is the full name of the country, not the country code. This should correspond to a display value in the list.

Also note that when running locally your IP is localhost which will not be resolved. So to test it hardcode your external facing IP (eg your router) into the component template.

**Comment by anhnt** [comment]
Done, but there is known issue, for example:
GeoIP returns `Vietnam`
`$formatter.countryCodes.list` returns `Viet Nam`

**Comment by Uafinder** [comment]
1. I see that phone number is not get to profile while entering shipping address, So i think we missed create account field for phone.
![image](https://user-images.githubusercontent.com/1945230/48901937-a4dc3980-ee5f-11e8-9429-ff639e1e526b.png)
http://vladtest54wweb-vladtest54w.kademi-ci.co/vladtest54wweb-ecomstore/

**Comment by bradmac** [comment]
> Done, but there is known issue, for example: GeoIP returns Vietnam $formatter.countryCodes.list returns Viet Nam

@anhnt when i last looked into this everything seemed to be working correctly.

If you see a problem let me know and we'll find a correct solution

**Comment by anhnt** [comment]
@bradmac here is sample

```
$formatter.geoIPService.getCityResponse("1.52.121.145")
```
Result:
```
![image](https://user-images.githubusercontent.com/735555/48929916-6d34c680-ef1f-11e8-8e8d-ca955622d092.png)

```
#foreach ($cc in $formatter.countryCodes.list)
    #if ("Viet Nam" == $cc.englishShortName)
    $cc
    #end
    #end
```
Result
![image](https://user-images.githubusercontent.com/735555/48929933-935a6680-ef1f-11e8-8284-0704e2f6cc78.png)

**Comment by anhnt** [comment]
>I see that phone number is not get to profile while entering shipping address, So i think we missed create account field for phone.

Added phone field

**Comment by bradmac** [comment]
Thanks, I'll check that out and see if there is another option

**Comment by bradmac** [comment]
> IMO Vietnam is correct one so we might need to update $formatter.countryCodes

I think we should match on the country code, not any textual name.

**Comment by anhnt** [comment]
This code doesnt work for me `$services.geoManager.findLocation()`

Reproducible here by adding a product to cart then see

http://tw1-anhtest2.kademi.com.au/tw1-ecomstore/p6

**Comment by bradmac** [comment]
Was using the wrong from address. Should work now after platform update.

**Comment by anhnt** [comment]
Works great on CI

**Comment by Uafinder** [comment]
ok
