### ISSUE TITLE
All (Sales, registration, certificate) claim journeys – email issue

### ISSUE THREAD

**Issue by yrsengar** [Kademi/kademi-dev#6202]
There are journeys setup for each claim type and the journey works well except one issue where the journey sends an email to admin notifying that claim has been submitted.

The email to admin also needed to have claim details the user has submitted through the claim form but at the moment it doesn't do that.

Could we please have something that makes it possible to send through these details in an email to admin.

Some screenshots attached (might be helpful).
<img width="1249" alt="screen shot 2018-10-29 at 10 30 11 am" src="https://user-images.githubusercontent.com/10014469/47622087-a880e700-db65-11e8-9d61-d83f6118c570.png">
<img width="1954" alt="screen shot 2018-10-29 at 10 30 44 am" src="https://user-images.githubusercontent.com/10014469/47622094-b59dd600-db65-11e8-95da-ddca3e15fa6f.png">

**Comment by bradmac** [comment]
I think its easiest to do that just with templating, which you should already have what you need.

I'll provide an example later today
