### ISSUE TITLE
Content download points allocation journey issue

### ISSUE THREAD

**Issue by yrsengar** [Kademi/kademi-dev#6203]
There is a content download journey which triggers only when you download a PDF file from a page. The whole journey works well, the only issue there is that it triggers each time even if you are downloading the same file again and again.

What client is expecting is that they want this journey to be trigger only once per PDF file.

Screenshots attached.
<img width="1009" alt="screen shot 2018-10-29 at 11 24 24 am" src="https://user-images.githubusercontent.com/10014469/47622730-34e2d800-db6d-11e8-9d79-6549cd6db6a2.png">

**Comment by bradmac** [comment]
This looks like a project implementation issue, not a kademi feature.
