### ISSUE TITLE
Tags issue on profile page (Form submission)

### ISSUE THREAD

**Issue by yrsengar** [Kademi/kademi-dev#6204]
On the Profile page, there are interest tags added as a list of checkboxes.  You can select tags based on your interested and it should save that data in the profile.

It saves the data with no issues but when these selections are updated it gives the error shown below in the screenshot.

Profile page: http://ciscoengage-cisco.kademi.com.au/profile/

<img width="823" alt="screen shot 2018-10-29 at 11 27 08 am" src="https://user-images.githubusercontent.com/10014469/47622788-0e716c80-db6e-11e8-9b84-497e3f910e8f.png">
<img width="809" alt="screen shot 2018-10-29 at 11 26 42 am" src="https://user-images.githubusercontent.com/10014469/47622789-13362080-db6e-11e8-9f07-a82b2abd084d.png">

**Comment by bradmac** [comment]
thats because of missing initilisation code.

Please check your customised code.
