### ISSUE TITLE
Update manage group emails page layout

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6205]
- split over 2 lines to give enough room for content to fit
- make date sensitive
- show recipient groups (included + excluded)

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/47627220-b3eb0700-db93-11e8-82db-153531cd24af.png)

**Comment by Uafinder** [comment]
1. Remove templates from that tab, they have their own tab
![image](https://user-images.githubusercontent.com/1945230/48133398-4f206280-e29f-11e8-8fd8-fb8fc97c6868.png)

**Comment by bradmac** [comment]
> Remove templates from that tab, they have their own tab

Fixed

**Comment by bradmac** [comment]
> Date range selector doesn't renew page without refresh

Fixed

**Comment by Uafinder** [comment]
Now both duplicate and create template buttons doesn't work correctly - they leads to edit current job screen
http://vladtest54r.admin.kademi-ci.co/groupEmails/

**Comment by Uafinder** [comment]
Ok, looks good
