### ISSUE TITLE
Points uploader should be able to set expiry date

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6211]

**Comment by bradmac** [comment]
here's the example i used, just ID and expiry date
![image](https://user-images.githubusercontent.com/826458/47691421-dd209b80-dc56-11e8-844a-703f551c3614.png)

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/47691445-f295c580-dc56-11e8-9db3-0de00eacdc51.png)

**Comment by Uafinder** [comment]
Looks good.
Pls note that if expiry date enter incorrectly then no expiry date would be accepted.
