### ISSUE TITLE
KookieAccept - new app to allow users to opt-in to cookies

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6212]
![image](https://user-images.githubusercontent.com/826458/47747969-84044680-dcee-11e8-9dd8-17755c78120a.png)

**Comment by bradmac** [comment]
By @trungjc 
https://github.com/Kademi/kademi-dev/tree/master/src/main/marketplace/apps/KookieAccept/common/theme/apps/cookie-accept/components

**Comment by Uafinder** [comment]
Hey @bradmac 
Need advice how can i test this...
http://vladtest55q.admin.kademi-ci.co/websites/vladtest55qweb/version1/#panel_details-tab

I've installed it here but when i'm accessing frontend - nothing appear

**Comment by Uafinder** [comment]
Ok, it works
