### ISSUE TITLE
Allow creating orders from kcrm

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6213]

**Comment by bradmac** [comment]
Eg for a US IP

![image](https://user-images.githubusercontent.com/826458/47827876-26065a80-dde5-11e8-9088-b12f768f528e.png)

**Comment by Uafinder** [comment]
We need to improve layout
It's ugly
![image](https://user-images.githubusercontent.com/1945230/48190585-c6133500-e34b-11e8-841c-c36bc1970aba.png)
http://vladtest54oweb-vladtest54o.kademi-ci.co/leads/18058853/

View button leads to error page
![image](https://user-images.githubusercontent.com/1945230/48190675-fc50b480-e34b-11e8-8c64-2ae78a426e03.png)
![image](https://user-images.githubusercontent.com/1945230/48190690-04105900-e34c-11e8-92cf-f59b8b930584.png)

**Comment by bradmac** [comment]
> We need to improve layout .. It's ugly

I think its just a bit squished because you're on a small screen. I've increased the modal size, should be ok now:

![image](https://user-images.githubusercontent.com/826458/48224053-8c026b80-e3fd-11e8-8d79-e9b0a9be0fbf.png)

**Comment by bradmac** [comment]
> View button leads to error page

This previously required the shopping cart app to be installed. I've now integrated it with leadman so users dont need to install extra apps.

@anhnt can you please copy over the necessary styles from shoppingcart-lib to leadman-lib? Or any styles which are generic can go into bootstrap-base

![image](https://user-images.githubusercontent.com/826458/48228889-65e3c800-e40b-11e8-855c-53264c1d039f.png)

**Comment by Uafinder** [comment]
1. i've created an order by sales-manager user
http://vladtest54sweb-vladtest54s.kademi-ci.co/leads/18181351/
tried to click to view order button and get this error
![image](https://user-images.githubusercontent.com/1945230/48405001-1f0f0e80-e73a-11e8-9c59-5c9b97cd323b.png)
this user
http://vladtest54s.admin.kademi-ci.co/manageUsers/18181182

2. Vertical alignment is different between text and cells
![image](https://user-images.githubusercontent.com/1945230/48405149-6dbca880-e73a-11e8-8e5d-bfc7215c8cd1.png)

**Comment by bradmac** [comment]
> tried to click to view order button and get this error

I've added permissions integration between the order details page, and the Sales and ProductViewer roles

**Comment by bradmac** [comment]
Looks ok now

![image](https://user-images.githubusercontent.com/826458/48442973-9bfebe80-e7f4-11e8-972a-338a739dde15.png)

**Comment by Uafinder** [comment]
ok, now timeline record doesn't appear, so i can't check
![image](https://user-images.githubusercontent.com/1945230/48474592-88a71f80-e803-11e8-80db-1b61912e2b4a.png)
![image](https://user-images.githubusercontent.com/1945230/48474641-9bb9ef80-e803-11e8-95f7-d443ea21f2c6.png)
http://vladtest54t.admin.kademi-ci.co/manageUsers/18187731/#summary-tab
http://vladtest54tweb-vladtest54t.kademi-ci.co/leads/18187742/

**Comment by bradmac** [comment]
just need to enable the products app for the website

![image](https://user-images.githubusercontent.com/826458/48507901-0c1f4a00-e8b2-11e8-9147-393b8f0dc855.png)

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/48507915-180b0c00-e8b2-11e8-81e4-b64dea8a9d04.png)

**Comment by Uafinder** [comment]
Yeah, looks great

**Comment by bradmac** [comment]
Just added a small layout tweak, to hide the products section when there are no products, and just display an add product button which shows the panel
