### ISSUE TITLE
KCom2: loyalty points integration

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6218]
- add configuration to ecom stores to allow connecting to multiple points buckets
- add an option to standard checkout component to allow using points in a purchase
- create a new checkout component which allows checking out using loyalty points only
  - have option for what shipping addresses to allow (manual, org, profile)

**Comment by bradmac** [comment]
Dev notes..

To create a JS controller for the new checkout component
- ensure you use runInTransaction
- get the Cart normally from CartManager (eg services.cartManager.checkoutItems.cart
- debit points using PointsManager and PointsRequest with negative points
- submit the Cart using CartManager.placeOrder

**Comment by bradmac** [comment]
Added loyalty points bucket selection to ecom store page:
![image](https://user-images.githubusercontent.com/826458/47969320-ade8af00-e0da-11e8-9f16-aa975cd2a5d4.png)

**Comment by BrewsterNZ** [comment]
The ecomCheckoutCart Component needs the following props on the Cart object to integrate points as partial / full payment.

cart.pointsBucket : The points bucket selected for the store. This could be got directly, but since other points data is described here, this keeps it all nice and tidy.
cart.pointsAllocated : The number of points the customer wants to use. (default 0)
cart.pointsMultiplier: The multiplier to translate points into currency.

**Comment by bradmac** [comment]
Updated UI

![image](https://user-images.githubusercontent.com/826458/48452956-37545b80-e816-11e8-9319-ac01dd1d034f.png)

Note that i think we ignore multipliers for now.

**Comment by bradmac** [comment]
@BrewsterNZ can you please update as follows:

- remove the "custom" option, that will confuse users
- if the option to allow users to enter any address is ticked then all fields are always editable. Meaning they can enter an address, or select one, or edit a selected one

![image](https://user-images.githubusercontent.com/826458/48520120-54e7fa80-e8d4-11e8-946a-09ee6ba873c6.png)

**Comment by bradmac** [comment]
@BrewsterNZ I've made a couple of tweaks
- the shipping provider is defaulted server side. Ie whenever the cart is requested we set the shipping provider is none is selected, and there is at least one provider.
- there were 2 methods to update points on quantity changed event, which i've merged

Can you please update to skip shipping provider selection if there is only one? As well as the changes above.

**Comment by bradmac** [comment]
Need to check behaviour with multiple org based balances available

**Comment by bradmac** [comment]
Org points debiting is working, just need to update balances when selected

**Comment by bradmac** [comment]
New checkout panel UI:

![image](https://user-images.githubusercontent.com/826458/48921594-a3fde300-ef05-11e8-8621-a03a89c85181.png)

**Comment by Uafinder** [comment]
Ok, i'm trying to purchase some product with some part of points
E.g. total 70$, i'm using 35 points
Checkout placed, but points not debited and eway payment says that all complete 70$ paid.
http://vladtest55f.admin.kademi-ci.co/shopping-carts/18309794/

Pls advice

**Comment by Uafinder** [comment]
ok, looks good
