### ISSUE TITLE
Kcom2 - purchasedProductsComponent.html. URGENT cart calculation issues.

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#6219]
Example of sub-total not adding up to correct amount.
https://plantae.admin.kademi.com.au/emails/132118379

Example of promotional product adding into subtotal.
https://plantae.admin.kademi.com.au/emails/132093295

**Comment by bradmac** [comment]
> Example of promotional product adding into subtotal.

For this, just ensure the product has a zero cost. Since you want the product to be available in the store, that means you need a seperate SKU for the same physical product, but with zero cost and not linked to the store.

**Comment by bradmac** [comment]
But the change i'll make here is to update purchasedProducts component to show decimal places..

**Comment by bradmac** [comment]
Done

![image](https://user-images.githubusercontent.com/826458/47972304-b1daf800-e0ff-11e8-852c-6a674da2b3d5.png)
