### ISSUE TITLE
Email administrator role

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6220]

**Comment by bradmac** [comment]
Example:

![image](https://user-images.githubusercontent.com/826458/48029171-73524580-e1b2-11e8-81c3-e296e1bef726.png)

**Comment by bradmac** [comment]
When logged in as a user in that group
![image](https://user-images.githubusercontent.com/826458/48029203-8b29c980-e1b2-11e8-872d-bc83657da5b2.png)

**Comment by bradmac** [comment]
This is fine. Automations are deprecated anyway.

**Comment by Uafinder** [comment]
Ok, so works fine
