### ISSUE TITLE
KPromotions: allow gift with purchase to be given for each item purchased up to a maximum

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6223]

**Comment by bradmac** [comment]
New setting

![image](https://user-images.githubusercontent.com/826458/48038167-5890c880-e1d4-11e8-952a-f12b137a78a3.png)

**Comment by bradmac** [comment]
Additional gifts are added up to the maximum for each qualifying product:
![image](https://user-images.githubusercontent.com/826458/48038217-8ece4800-e1d4-11e8-9971-3ba2edecb32d.png)

![image](https://user-images.githubusercontent.com/826458/48038228-9d1c6400-e1d4-11e8-984f-4dd8d5974f5a.png)

**Comment by bradmac** [comment]
@stephen-fueldesign this depends on a platform update and publishing kcom2, then its over to you

**Comment by Uafinder** [comment]
Several questions:
1. Gift purchase doesn't work with promotion code
e.g.
![image](https://user-images.githubusercontent.com/1945230/48066907-81668d00-e1d7-11e8-8dac-674eed139021.png)
product available without entering promo code
![image](https://user-images.githubusercontent.com/1945230/48066915-86c3d780-e1d7-11e8-94f8-e44b70987d7a.png)

2. How not to gift product but provide a discount by entering promo code?

**Comment by bradmac** [comment]
i think this is probably becasue you had previously activated that promotion, so it remains active for this cart.

@Uafinder please let me know where that account is, and what user you're using (if any) and then i can check

**Comment by Uafinder** [comment]
http://vladtest54mm.admin.kademi-ci.co/rewards/promo1/#checkout-tab

**Comment by bradmac** [comment]
@Uafinder you've configured this promotion to only be available to a specific group. Are you logged in as a member of that group? If so then tell me the user you're logged in with so i can check

![image](https://user-images.githubusercontent.com/826458/48155943-0adda280-e331-11e8-8ad5-a42fb7779d83.png)

**Comment by bradmac** [comment]
Looks fine to me

![image](https://user-images.githubusercontent.com/826458/48156059-54c68880-e331-11e8-8553-f79621147304.png)

**Comment by bradmac** [comment]
@Uafinder if there is a problem, please describe what it is, and how to reproduce it.

**Comment by Uafinder** [comment]
Ok, my user is:
http://vladtest54pp.admin.kademi-ci.co/manageUsers/18072099
My promo is:
http://vladtest54pp.admin.kademi-ci.co/rewards/promo1
It not require to enter promo code
So i'm going here
http://vladtest54ppweb-vladtest54pp.kademi-ci.co/vladtest54ppweb-ecomstore
And try to purchase camera
![image](https://user-images.githubusercontent.com/1945230/48270050-b6761800-e441-11e8-9a19-e66fcb2206ae.png)
And no product additional product appears

**Comment by bradmac** [comment]
Ohhhh, so you're saying the promotion is configured to not require a promotion code. I think you were saying the promotion was activated even when no promotion code was entered.

**Comment by bradmac** [comment]
Should be working now when promo codes are not required

**Comment by Uafinder** [comment]
Looks good
