### ISSUE TITLE
Sales manager cant see leads which assigned to sales team member

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#6224]
http://spcrm-spinsurance.kademi.com.au/leads/?query=&leadType=active&from=0&size=100&assignedTo=131408953

https://spinsurance.admin.kademi.com.au/manageUsers/131408935

Check this issue https://github.com/Kademi/projects/issues/799

**Comment by bradmac** [comment]
The filtering logic looks for what orgs the user has access to based on roles. Just need to make sure the role applies to "this organisation", not to their own team:

![image](https://user-images.githubusercontent.com/826458/48103373-ab7d8500-e293-11e8-8333-8b681423aeab.png)

**Comment by Uafinder** [comment]
Looks good for me
