### ISSUE TITLE
KCRM: enhance user errors for managing teams and users

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6226]
Comes from SP

1. 
![image](https://user-images.githubusercontent.com/1945230/48002699-f624c300-e114-11e8-9544-1b4853b8c480.png)
http://spcrm-spinsurance.kademi.com.au/team/
https://spinsurance.admin.kademi.com.au/manageUsers/131408989

2. 
![image](https://user-images.githubusercontent.com/1945230/48002722-0c328380-e115-11e8-95a9-036aa390c0cf.png)
http://spcrm-spinsurance.kademi.com.au/team/
https://spinsurance.admin.kademi.com.au/manageUsers/131408989

3. 
this user
https://spinsurance.admin.kademi.com.au/manageUsers/131408989
this link
http://spcrm-spinsurance.kademi.com.au/team/131408953/
![image](https://user-images.githubusercontent.com/1945230/48002752-24a29e00-e115-11e8-87ed-1149db8789b5.png)
![image](https://user-images.githubusercontent.com/1945230/48002773-34ba7d80-e115-11e8-9664-3b7e80105d66.png)
![image](https://user-images.githubusercontent.com/1945230/48002787-3a17c800-e115-11e8-9895-d947b5402ec4.png)

**Comment by bradmac** [comment]
We should ensure these buttons are only displayed if the user has permission to use them

**Comment by anhnt** [comment]
Fixed in standard and SP

**Comment by Uafinder** [comment]
looks good
