### ISSUE TITLE
kComm checkout component delete button out of whack

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#6228]
Need to be moved up

![image](https://user-images.githubusercontent.com/2201340/48050824-4d9b5f80-e1f7-11e8-965e-6f1d595fba7f.png)

**Comment by bradmac** [comment]
It looks fine to me..

![image](https://user-images.githubusercontent.com/826458/48094167-4f583800-e276-11e8-9055-fa291469e9e2.png)

**Comment by bradmac** [comment]
@paddyow please provide a link to where you see this problem

**Comment by paddyow** [comment]
Browserstack screenshot

![image](https://user-images.githubusercontent.com/2201340/48100176-49625700-e276-11e8-803a-1daa9fe55b9e.png)

![image](https://user-images.githubusercontent.com/2201340/48100149-39e30e00-e276-11e8-83ea-3439defeffe7.png)

**Comment by bradmac** [comment]
I see the same thing on that account

**Comment by anhnt** [comment]
This issue occurs when a site has both reward store + shopping cart and KCom2. there is conflict in css with those apps

**Comment by bradmac** [comment]
I think just dont use reward stores in the same account, its not a valid use case.

**Comment by anhnt** [comment]
ok, closing. i disabled shoppingcart app and it looks good
