### ISSUE TITLE
Installing APP on CI causes page to shake 

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#6231]
http://ecommtestp123.admin.kademi-ci.co/marketPlace/kfeedbackapp/?websiteBranch=version1&websiteName=ecomm1

When you click the install button, the UI shakes in Chrome.  Looks like the page template is trying to refactor or do something, looks very odd.

**Comment by Uafinder** [comment]
Looks good

**Comment by bradmac** [comment]
@paddyow @Uafinder @anhnt this issue was a P2 so should NOT have been worked on yet.
