### ISSUE TITLE
Keditor: Cannot edit menu items due to buttons being too large

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#6232]
Edit main template http://ecommtestp123.admin.kademi-ci.co/pages/ecomm1/version1/

![image](https://user-images.githubusercontent.com/2201340/48095609-42811780-e269-11e8-902e-7f82e3c20e5b.png)

**Comment by bradmac** [comment]
@anhnt can you make sure we set the size on these buttons as an override of theme styles?

**Comment by anhnt** [comment]
Fixed. also fixed pencil icon which was not showing. Requires contentEditor-lib 1.3.2

**Comment by Uafinder** [comment]
Looks good
