### ISSUE TITLE
Shopping for component not available in component list

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#6235]
Open index.html for example http://ecommtestp123.admin.kademi-ci.co/pages/ecomm1/version1/

![image](https://user-images.githubusercontent.com/2201340/48097747-d4d7ea00-e26e-11e8-8472-f77eacf5b0dd.png)

**Comment by anhnt** [comment]
done

**Comment by Uafinder** [comment]
Looks good
