### ISSUE TITLE
Cannot make eWay test payment

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#6236]
I can submit a payment here http://ecommtestp123.admin.kademi-ci.co/payments/?websiteBranch=ecomm1/version1#panel_pay-tab

When I checkout with the same details from the store here http://ecomm1-ecommtestp123.kademi-ci.co/ecomm1-ecomstore/cart

I get an error.

![image](https://user-images.githubusercontent.com/2201340/48098223-2e8ce400-e270-11e8-9927-fcf71c1c723b.png)

**Comment by anhnt** [comment]
I can submit order successfully without any error http://ecommtestp123.admin.kademi-ci.co/shopping-carts/18054904/

**Comment by anhnt** [comment]
if you still see error please provide your steps
