### ISSUE TITLE
Installing KCRM theme broke template

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#6237]
http://ecommtestp123.admin.kademi-ci.co/websites/crm/version1/#panel_details-tab

Click on theme checker 

Unable to find resource 'crm-ecommtestp123.kademi-ci.co:/theme/masterTemplate.html'

**Comment by paddyow** [comment]
Ok worked it out.  After installing Kcrm-theme I have to go and turn on the APP in the website to make it work.  The APP should auto enable after the theme is installed.

**Comment by bradmac** [comment]
> Ok worked it out. After installing Kcrm-theme I have to go and turn on the APP in the website to make it work. The APP should auto enable after the theme is installed.

No, thats not correct.

Just go into the website, and click "Change theme" and select your theme. There is only one step, not two.

![image](https://user-images.githubusercontent.com/826458/48101437-e085d980-e28b-11e8-804d-26c26973f50c.png)

**Comment by paddyow** [comment]
- I created a new website
- Installed leadman into the website
- it uses K-theme

![image](https://user-images.githubusercontent.com/2201340/48103808-d3192100-e284-11e8-82ed-747da88f17b9.png)

Under apps I see Kcrm-theme is already there but not on, maybe because I have already installed it on another website.

![image](https://user-images.githubusercontent.com/2201340/48103825-eb893b80-e284-11e8-9ac3-8eacdfeb2516.png)

I then install KCRM-theme.  When I check the APP is installed and on it is.

![image](https://user-images.githubusercontent.com/2201340/48103862-24c1ab80-e285-11e8-98d9-affc324d568c.png)

I then add the sales group to the new website

![image](https://user-images.githubusercontent.com/2201340/48103879-32773100-e285-11e8-8cfb-cfd291c08a40.png)

And login as this user http://ecommtestp123.admin.kademi-ci.co/manageUsers/100047/#summary-tab

..and see a blank page.

Looks like the templates are broken http://ecommtestp123.admin.kademi-ci.co/pages/crmtest5/version1/

![image](https://user-images.githubusercontent.com/2201340/48103972-85e97f00-e285-11e8-8779-b11fbc845d7d.png)

**Comment by bradmac** [comment]
Problem is that the kcrm-theme 1.0.7 wasnt synced correctly.

Thats been synced now and looks good:
