### ISSUE TITLE
KCRM theme looks incorrect

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#6238]
I have this website http://ecommtestp123.admin.kademi-ci.co/websites/crmtest2/version1/#panel_details-tab

Note all libs are up to date.

![image](https://user-images.githubusercontent.com/2201340/48101061-e2df3800-e279-11e8-9918-1ce6f56f4423.png)

Logging in to KCRM the theme has square corners.

![image](https://user-images.githubusercontent.com/2201340/48101084-f8546200-e279-11e8-8914-f23582c10b0e.png)

The Norgin demo here http://norgine.admin.kademi-ci.co/websites/ncrm/version1/#panel_apps-tab

Uses 1.0.6

![image](https://user-images.githubusercontent.com/2201340/48101188-4b2e1980-e27a-11e8-8d3c-23556df2bf2b.png)

And shows the correct theme

![image](https://user-images.githubusercontent.com/2201340/48101212-61d47080-e27a-11e8-91b1-8dd426764d57.png)

Is 1.0.7 changed as it's not showing the correct theme as per the Norgine demo.

**Comment by bradmac** [comment]
> Note all libs are up to date.

This is normal for CI. If there are newer libs a button is displayed prompting you to update all. Just click it.

![image](https://user-images.githubusercontent.com/826458/48101518-25117500-e28c-11e8-897c-6ec22538fece.png)

**Comment by paddyow** [comment]
I have the latest lib, but the theme is incorrect.  It should look like Norgine.

**Comment by bradmac** [comment]
@anhnt can you please assist paddy. We want kcrm-theme to be as per this creative

https://github.com/Kademi/kademi-dev/issues/5599

**Comment by anhnt** [comment]
sync job was failed. already fixed that for paddy but needs some more enhancement #5599

**Comment by anhnt** [comment]
Done in 5599
