### ISSUE TITLE
Cannot edit any pages on Kademi WWW

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#6239]
http://kademi.admin.kademi.us/pages/kademi-www/version64/

Keditor does not load.

**Comment by anhnt** [comment]
this site is using old theme, so keditor wont support

**Comment by bradmac** [comment]
@paddyow you need to use version v65

Its not live yet

http://kademi.admin.kademi.us/websites/kademi-www/v65/#panel_apps-tab
