### ISSUE TITLE
Tasks component doesn't update after tasks creation

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6245]
![image](https://user-images.githubusercontent.com/1945230/48186633-38cae300-e341-11e8-84ce-cdded58e9d98.png)
http://vladtest54oweb-vladtest54o.kademi-ci.co/dashboard
Create a task, but it will not appear in list without refresh

**Comment by anhnt** [comment]
Fixed, however we should not use new tasks list component and old one in a same page

**Comment by anhnt** [comment]
Done, default dashboard will now look like this

![image](https://user-images.githubusercontent.com/735555/48242596-8e20f600-e40e-11e8-9559-601e518f82a1.png)

**Comment by Uafinder** [comment]
Ok, looks good
