### ISSUE TITLE
Bug with content editor in assets (products)

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6258]
1. Go here
http://vladtest54r.admin.kademi-ci.co/asset-manager/cc9d5a39-e4ba-4ffd-a13f-5f3fe82cc1db
2. click + icon
![image](https://user-images.githubusercontent.com/1945230/48343232-849bc600-e67a-11e8-8c20-bb258676d594.png)
3. Click close
![image](https://user-images.githubusercontent.com/1945230/48343249-90878800-e67a-11e8-8a93-8c31dc112f2f.png)
4. click plus again
![image](https://user-images.githubusercontent.com/1945230/48343266-98472c80-e67a-11e8-8cef-b465e8b01e60.png)
5. keditor will not load
![image](https://user-images.githubusercontent.com/1945230/48343277-a301c180-e67a-11e8-82fa-fd0478e736f3.png)

**Comment by anhnt** [comment]
we changed to edit asset on new tab so this problem is gone

**Comment by Uafinder** [comment]
Yup, looks good
