### ISSUE TITLE
Member of sales group can't access teams page

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6259]
![image](https://user-images.githubusercontent.com/1945230/48343572-62567800-e67b-11e8-98e4-a3c3a152ca7e.png)
http://vladtest54rweb-vladtest54r.kademi-ci.co/team/
http://vladtest54r.admin.kademi-ci.co/manageUsers/18078928/#summary-tab

**Comment by bradmac** [comment]
Users must have the User Viewer role to be able to see this page

![image](https://user-images.githubusercontent.com/826458/48372590-e9f7c180-e723-11e8-8191-bb9da6a7ad58.png)

**Comment by Uafinder** [comment]
Ok
