### ISSUE TITLE
Trigger time sent at incorrect time

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#626]
I set a trigger to fire the next day @9am, received the message @7am.

http://cpaaustralia.admin.olhub.com/autoEmails/test1%281%29/#triggers-tab

**Comment by bradmac** [comment]
@tuzzmaniandevil the timezone has been set correctly on the org - http://cpaaustralia.admin.olhub.com/edit

 can you make sure the timezone is applied to the hour when it gets set into the timer?

**Comment by tuzzmaniandevil** [comment]
Sorted

**Comment by paddyow** [comment]
See this trigger:http://cpaaustralia.admin.olhub.com/autoEmails/test1%281%29%281%29/#triggers-tab

This was due to fire 1 day later at 3:30pm but I got it at 4:04pm so based on the previous trigger, it sent it exactly 1 day later but ignored the timer.  My understanding is if you set a trigger to fire 1 day later, and which has a timer, it will fire at the specific time even if it;'s less than 1 day (24 hours).

**Comment by tuzzmaniandevil** [comment]
@paddyow I tried this locally and on production and I could not reproduce the problem.

**Comment by bradmac** [comment]
Should be resolved, i think

**Comment by bradmac** [comment]
Problem now is that if a trigger is created after 10pm Sydney time it is rescheduled for an extra day. 

Problem appears to be that we do the date calculation and then apply timezone

**Comment by tuzzmaniandevil** [comment]
I have recreated the unit test and made sure it's now working correctly.
