### ISSUE TITLE
No js handlers for dynamic components

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#6263]
Here is editor page http://vladtest54cweb-vladtest54c.kademi-ci.co//theme/apps/shoppingcart/contenteditor?fileName=checkout.html

This should return js handlers http://vladtest54cweb-vladtest54c.kademi-ci.co/theme/apps/shoppingcart/_components?handlers&fileName=checkout.html

as this component has some settings

![image](https://user-images.githubusercontent.com/735555/48387051-d00bae00-e726-11e8-8e78-f78025ab8e21.png)

**Comment by bradmac** [comment]
The problem just affected the shopping cart template, because it wasnt declared as being of type "html"

Fixed
