### ISSUE TITLE
KCRM company name field not working

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#6265]
@Uafinder can you test this.

Open Kademi's CRM http://kcrm-kademi.kademi.us/
Create a new lead
Add a new company in the modal 
Add the lead information i.e. first name etc
Save lead

![image](https://user-images.githubusercontent.com/2201340/48396689-6a8fdf80-e76f-11e8-9a95-907a09d09389.png)

When I do this, then create a new lead, the company I added before is not available when I type in the company name, it should appear so I can select it.  See below.

![image](https://user-images.githubusercontent.com/2201340/48396937-3a950c00-e770-11e8-9720-cebdee0bfa7a.png)

Then when you go to the company page http://kcrm-kademi.kademi.us/companies/?
The company does not appear in the list.

However the lead company tab does show the company name I added when I created the lead http://kcrm-kademi.kademi.us/leads/64895004/?view=company

**Comment by Uafinder** [comment]
I tested on the fresh account and it seems to fine fine there
![image](https://user-images.githubusercontent.com/1945230/48403852-87102580-e737-11e8-9084-a1bbf80e01bd.png)
![image](https://user-images.githubusercontent.com/1945230/48403858-8bd4d980-e737-11e8-855b-d2dbdb1fc401.png)
![image](https://user-images.githubusercontent.com/1945230/48403869-94c5ab00-e737-11e8-9d11-385e4fb96617.png)
http://vladtest54s.admin.kademi-ci.co/teamGroups/#teams-tab

So, i think we just need to ensure that our US KCRM matches CI now
@anhnt  could you check?

**Comment by bradmac** [comment]
Also, need to make sure roles are configured correctly.
