### ISSUE TITLE
KCom2: New categories component to display a horizontal list

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6269]
Create a component which displays categories with product counts in horizontoal pills:

- use standard bootstrap styles
- use an ES query to find only cats containing products in the current store (page.attributes.store)
- if there is a category in page.attributes.category use that as the parent, otherwise look for root cats only
- list in order on number of products

Just use standard bs styles, eg
![image](https://user-images.githubusercontent.com/826458/48463447-e4dc6480-e840-11e8-8ad4-9faab1e0ca28.png)

**Comment by Uafinder** [comment]
It doesn't display on frontend
![image](https://user-images.githubusercontent.com/1945230/48480811-3cb0a680-e814-11e8-943b-9430c62780b5.png)
http://vladtest54ttweb-vladtest54tt.kademi-ci.co/
![image](https://user-images.githubusercontent.com/1945230/48480818-44704b00-e814-11e8-9e73-69bf5a923dcc.png)
http://vladtest54tt.admin.kademi-ci.co/pages/vladtest54ttweb/version1/?contenteditor=index.html

**Comment by anhnt** [comment]
Fixed

**Comment by Uafinder** [comment]
ok, it's showing, but does nothing
E.g. click on it, and nothing happened, neither filter nor redirect to category page
http://vladtest54ttweb-vladtest54tt.kademi-ci.co/vladtest54ttweb-ecomstore/
http://vladtest54ttweb-vladtest54tt.kademi-ci.co/vladtest54ttweb-ecomstore/

**Comment by Uafinder** [comment]
@bradmac  need advice?

**Comment by bradmac** [comment]
@anhnt ideally..
- if this is being used on a product list page it will filter products
- otherwise it will just link to the category page

Also, please see my comment here:
https://github.com/Kademi/kademi-dev/commit/8f876c8a0da705d8c8bfabd2877b5a3483f99704#r31302919

This is true of all components.

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/48688210-bde2b180-ebf7-11e8-92b8-05e5232b35dc.png)

KCom2 v1.4.0

**Comment by Uafinder** [comment]
Looks good
