### ISSUE TITLE
KCom2: Checkout items component options

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6272]
Please add options for the following options:
1. whether line item costs are shown as tax inclusive or tax exclusive
2. whether to show the sub-total
3. whether to show tax 
4. whether to show freight
5. whether to show free item costs (ie where cost is zero)
6. whether to show costs with decimal places or as integers (applies to all costs)

![image](https://user-images.githubusercontent.com/826458/48509620-7934de80-e8b6-11e8-939b-7914ca71bc88.png)

This is needed to use this - https://github.com/Kademi/kademi-dev/issues/6218 - with the OTM project

**Comment by Uafinder** [comment]
looks good, one separate issue created
