### ISSUE TITLE
Orders EDM component, new layout option

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6274]
Please create a new EDM component in KCom2 similar to purchasedProductsComponent with a layout like this:

![image](https://user-images.githubusercontent.com/826458/48522418-80231780-e8dd-11e8-98e6-78845d828dd5.png)

This will show the product image on the left, with textual information on the right

- always show the product title and quantity, as shown
- option for whether to show the product brief
- option to show the line item cost (tax inclusive)

**Comment by bradmac** [comment]
> But in purchasedProductsComponent we cannot get productOrder image because ${productOrder.getItemHref()} return nothing

In this component the productOrder variable is a ProductOrder object. This has properties for the productSku and product.

We should use the image on productSku if there is one like this:

```
<img src='/_hashes/files/$productOrder.productSku.imageHash' />
```
, otherwise use the product property..
```
#if( $productOrder.product.images.size() > 0 )
<img src='/_hashes/files/$productOrder.product.images[0].hash' />
#end
```

**Comment by trungjc** [comment]
I have added "purchasedProductsListComponent". Please check this commit:

https://github.com/Kademi/kademi-dev/commit/b5e873d026dd1003e3429ec67740753f9a40b6f0

**Comment by bradmac** [comment]
hey @trungjc that looks good, but there is a lot of duplicated code

What i suggest is create a macro for rendering a row. Then call that macro from the main foreach loop, and also to generate fake content

Eg
```
#macro( renderRow productImage productName quantity )
                            <tr bgcolor="${bodyBg}">
                                #if ($showProductPhoto == "true")
                                <td valign="top" style="${cellStyles}">
                                    <img src="$productImage" width="200" height="auto" alt="$productTitle" />
                                </td>
                                #end
...
```

**Comment by trungjc** [comment]
I have created "ecommerceEdmMacros.html". Please check this commit:

https://github.com/Kademi/kademi-dev/commit/f12e349ef1ad39f7093f0b45619178da27843dce

**Comment by Uafinder** [comment]
images not showing
![image](https://user-images.githubusercontent.com/1945230/49736435-ce37fa80-fc92-11e8-95e2-023f01c92e25.png)
http://vladtest55g.admin.kademi-ci.co/emails/18329164

**Comment by anhnt** [comment]
fixed, applied to this account

http://vladtest55g.admin.kademi-ci.co/emails/18333503

**Comment by anhnt** [comment]
needs to do those requirements


- option for whether to show the product brief
- option to show the line item cost (tax inclusive)

**Comment by Uafinder** [comment]
looks good

**Comment by Uafinder** [comment]
Well, one thing appears - it should show cost with the tax (tax inclusive). It showing only basic cost
http://vladtest55jj.admin.kademi-ci.co/emails/18336090
![image](https://user-images.githubusercontent.com/1945230/49866683-15e49080-fe11-11e8-9f89-eea3d7e5d028.png)
![image](https://user-images.githubusercontent.com/1945230/49866708-2e54ab00-fe11-11e8-8f80-3818cead3130.png)
http://vladtest55jj.admin.kademi-ci.co/shopping-carts/18336075/

**Comment by anhnt** [comment]
@bradmac there is no prop in ProductOrder.java that includes tax
Here is email item debug code

![image](https://user-images.githubusercontent.com/735555/49926491-3d5d5b00-feee-11e8-8c68-21c3725868a3.png)

Here is cart items table

![image](https://user-images.githubusercontent.com/735555/49926528-55cd7580-feee-11e8-9463-910bdd139380.png)

Please have a look

**Comment by bradmac** [comment]
@anhnt I've pushed a change so that ProductOrder.tax should now get set on checkout.

And ive added a getter to ProductOrder which calculates the total inc tax - grandTotalIncTax - so please use that for the total cost inc tax.

**Comment by anhnt** [comment]
Thanks, it's sorted now

**Comment by Uafinder** [comment]
Looks good

**Comment by trungjc** [comment]
Reference to https://github.com/Kademi/projects/issues/921
