### ISSUE TITLE
KCRM: lead page timeline must only show lead actions from the current lead

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6277]
Currently seems to show actions from all leads for the user

**Comment by bradmac** [comment]
Done

**Comment by bradmac** [comment]
Emails and journey automation actions are now only shown from the current lead.

**Comment by Uafinder** [comment]
Purchase and notes are showing from other lead.
Is this correct?
![image](https://user-images.githubusercontent.com/1945230/48708709-effe0e80-ec0b-11e8-9697-b4997b5677e4.png)
Where created
http://vladtest54uweb-vladtest54u.kademi-ci.co/leads/18240619/
Showing here
http://vladtest54uweb-vladtest54u.kademi-ci.co/leads/18240722

**Comment by bradmac** [comment]
lead notes should only be shown on their own lead.

but there is no direct connection from a purchase to a lead, so they should show on all leads.

**Comment by bradmac** [comment]
Fixed notes display

**Comment by Uafinder** [comment]
Looks good
