### ISSUE TITLE
KCRM: Add notes to a task

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6279]
![image](https://user-images.githubusercontent.com/826458/48592046-79fb6c80-e9ab-11e8-93bb-077b26914a56.png)

**Comment by bradmac** [comment]
Use
```
applications.leadMan.leadmanService.createNote(task, ..)
```

**Comment by anhnt** [comment]
In progress..

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/48703726-3c0a7c80-ec27-11e8-8ea6-0e1125240025.png)

**Comment by anhnt** [comment]
Done

**Comment by Uafinder** [comment]
1. edit or delete note doesn't work
![image](https://user-images.githubusercontent.com/1945230/48775366-80545600-ecd5-11e8-9cb5-1104e2c932bf.png)
It doesn't change something
http://vladtest54vweb-vladtest54v.kademi-ci.co/tasks/18243837/
http://vladtest54v.admin.kademi-ci.co/manageUsers/18243753

**Comment by anhnt** [comment]
> notes from task are showing on global lead timeline

I think it's ok and intended

**Comment by anhnt** [comment]
> edit or delete note doesn't work
> when task is not connected to lead
Try again now

**Comment by anhnt** [comment]
Fixed

**Comment by Uafinder** [comment]
looks great
