### ISSUE TITLE
KCom2 - ability to filter parent category by child categories

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#6281]
Would be good for there to be an option to either
1. traverse and follow child categories (_default state, current works this way_)
2. and another option to filter by child category, such as filter by brand, by price, by facets etc.

Here's a graphic I would like to achieve on a project:
![screen shot 2018-11-16 at 2 36 50 pm](https://user-images.githubusercontent.com/39784677/48592641-3b1ae600-e9ae-11e8-8095-7941e1327755.png)

p.s I do believe the building blocks are in place as I got this working in waterware:
http://version1.waterware-waterware.kademi.com.au/store/boilers-and-heatpumps/

**Comment by bradmac** [comment]
The standard filter component does show categories, but i think there are a couple of changes needed:

![image](https://user-images.githubusercontent.com/826458/48592971-b4ff9f00-e9af-11e8-82b5-fc392df685b6.png)

1 - show the count of products in each category. Note that this means we should change this to using elasticsearch
2 - currently clicking a category navigates to the category page. I think we should change this to only filter, which is already supported (i think) in the product list component.

There are use cases where site owners want a top level list of categories which go to their own page, but i think that would use a different component

**Comment by Uafinder** [comment]
looks great
