### ISSUE TITLE
KCRM: Engagement stats

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6282]
Show engagement stats on lead and profile page

**Comment by bradmac** [comment]
On a lead page..
![image](https://user-images.githubusercontent.com/826458/48655959-a08cd680-ea83-11e8-81ca-15efd624f0a8.png)

On profile page we cant show engagement level, because that is calculated by funnels. So instead just show the number of leads..

![image](https://user-images.githubusercontent.com/826458/48655974-bb5f4b00-ea83-11e8-8f92-8e175d868709.png)

**Comment by bradmac** [comment]
Requires leadman-lib 3.1.9

**Comment by Uafinder** [comment]
Looks good
