### ISSUE TITLE
KCRM: Filters doesn't work properly

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6288]
1. Notes and activities shows nothing
![image](https://user-images.githubusercontent.com/1945230/48707903-98f73a00-ec09-11e8-80d9-cfc777766029.png)
http://vladtest54uweb-vladtest54u.kademi-ci.co/leads/18240634/
However they are present
![image](https://user-images.githubusercontent.com/1945230/48707930-af04fa80-ec09-11e8-9c4d-530df5777a8f.png)

2. Same for calls, tags, emails and so on
![image](https://user-images.githubusercontent.com/1945230/48707967-cf34b980-ec09-11e8-9c98-6c61eb02d84c.png)
![image](https://user-images.githubusercontent.com/1945230/48707974-d52a9a80-ec09-11e8-8307-638a24a2b211.png)

**Comment by anhnt** [comment]
Done

**Comment by Uafinder** [comment]
Cools
