### ISSUE TITLE
KCRM: Email sending doesn't get timeline record

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6289]
![image](https://user-images.githubusercontent.com/1945230/48708102-45392080-ec0a-11e8-94b2-c4a166d6f2a9.png)
![image](https://user-images.githubusercontent.com/1945230/48708133-5a15b400-ec0a-11e8-862e-7966daeebdcd.png)
http://vladtest54uweb-vladtest54u.kademi-ci.co/leads/18240634/?view=activities

**Comment by bradmac** [comment]
@Uafinder note that the lead page now only shows emails associated with that particular lead/journey

You can confirm from the admin that no emails have been sent by the journey:
![image](https://user-images.githubusercontent.com/826458/48729127-b379f380-ec9b-11e8-8aa7-7ddd27a1d086.png)

**Comment by Uafinder** [comment]
i sent email directly from same page, using send email feature (on the lead page, activities tab)

**Comment by bradmac** [comment]
Thanks. Must be an issue with the email not being associated with the lead when created.

**Comment by bradmac** [comment]
Fixed. Now emails are associated with the lead when sent from the lead.

![image](https://user-images.githubusercontent.com/826458/48732036-69950b80-eca3-11e8-81c8-f944f25dee07.png)

**Comment by Uafinder** [comment]
ok, looks good
