### ISSUE TITLE
Triggers will not manually fire

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#629]
http://admin.cpaaustralia.olhub.com/autoEmails/day-006-pippa/timerTriggers.html

Unable to manually fire a trigger, still saying Waiting after it has been fired.

**Comment by tuzzmaniandevil** [comment]
This is related to #626

**Comment by bradmac** [comment]
paddy says not fixed

**Comment by bradmac** [comment]
http://cpaaustralia.admin.olhub.com/autoEmails/day-006-pippa/timerTriggers.html

**Comment by tuzzmaniandevil** [comment]
Looks like it was check the hour and because it didn't match it corrected the hour. this is correct for normal opperation but should be ignored when fired manually.

**Comment by bradmac** [comment]
Should work now. Ignoring the hour when doing the timer check on due. This also means that changing the hour on the trigger will not be applied to triggers in the timer queue

**Comment by bradmac** [comment]
Timers get rescheduled when a time is set and the trigger fires normally.

To resolve will remove the new rule that says to ignore the time when doing the reschudle check, and add a column to the table to record that a trigger has been manually fired. If manually fired we skip the reschedule check
