### ISSUE TITLE
KCRM: Missed lead title text part which contains quotes

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6290]
![image](https://user-images.githubusercontent.com/1945230/48708230-ac56d500-ec0a-11e8-8437-a49176fc3a02.png)
![image](https://user-images.githubusercontent.com/1945230/48708241-b678d380-ec0a-11e8-8bbd-81c75412c3b1.png)
http://vladtest54uweb-vladtest54u.kademi-ci.co/dashboard
http://vladtest54uweb-vladtest54u.kademi-ci.co/leads/18240634/

**Comment by bradmac** [comment]
Fixed

**Comment by bradmac** [comment]
leadman-lib 3.2.1

**Comment by Uafinder** [comment]
Looks good
