### ISSUE TITLE
Queries are being lost when reopened

### ISSUE THREAD

**Issue by joelatfuel** [Kademi/kademi-dev#6292]
I created some queries on the Deloitte website. They are valid queries because they show results in the query table component. However, when I reopen the query to make changes, it hasn't saved my changes — it reverts to the original state.

**Comment by bradmac** [comment]
@joelatfuel can you please attach a link to your query?

**Comment by joelatfuel** [comment]
Here's the [query link](https://deloittefraudtraining.admin.kademi.com.au/queries/studentsNotStarted/#queryBuilderTab-tab).

**Comment by bradmac** [comment]
Looks like this was before the rules were lost:
https://deloittefraudtraining.admin.kademi.com.au/repositories/queries/commit-133823186/texteditor?fileName=studentsNotStarted.query.json

**Comment by bradmac** [comment]
FYI queries repo
https://deloittefraudtraining.admin.kademi.com.au/repositories/queries/version1/

**Comment by joelatfuel** [comment]
@bradmac Do you have an update on when this is likely to be fixed? I'm needing this fixed to finish Deloitte's dashboard.

**Comment by bradmac** [comment]
@joelatfuel as discussed, if you can show me the last save of that query in version history where its got the rules, we can then work out what change caused it to lose the rules.

**Comment by joelatfuel** [comment]
I tried to retrace my steps and replicate this issue - but I couldn't break it! So I'll close this for now.
