### ISSUE TITLE
KCRM: Email not sending

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6294]
![image](https://user-images.githubusercontent.com/1945230/48775089-b2b18380-ecd4-11e8-9aba-67de5718383e.png)
http://vladtest54vweb-vladtest54v.kademi-ci.co/leads/18243780/?view=activities
http://vladtest54v.admin.kademi-ci.co/manageUsers/18243753
![image](https://user-images.githubusercontent.com/1945230/48775119-c8bf4400-ecd4-11e8-8cf0-c02342a7fd33.png)

**Comment by bradmac** [comment]
Problem appears to be resolved now

**Comment by Uafinder** [comment]
Yeap, it works
