### ISSUE TITLE
KCom2: products list component doesn't show products on home page

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6295]
![image](https://user-images.githubusercontent.com/1945230/48779086-79324580-ecdf-11e8-9c03-6a5ac99eaa78.png)
![image](https://user-images.githubusercontent.com/1945230/48779098-7df6f980-ecdf-11e8-801f-c4180dd0e668.png)
http://vladtest54vvweb-vladtest54vv.kademi-ci.co/

**Comment by anhnt** [comment]
You were using featuredProductList component which do the same job as storeProductList. Will remove that component...

**Comment by Uafinder** [comment]
Ok, looks good now
