### ISSUE TITLE
KCRM: Cant complete task on task detail page

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6297]
Clicking the "Complete" button shows the task edit modal instead of completion modal:

![image](https://user-images.githubusercontent.com/826458/48809368-2f059e80-ed89-11e8-9299-a122a61dc80f.png)

ALSO, please add ability to assign a user in the main edit form in the page. 

We should not be using a modal to edit the task when the task detail page is already open

**Comment by anhnt** [comment]
Done

**Comment by Uafinder** [comment]
When change assignment this field become invisible
![image](https://user-images.githubusercontent.com/1945230/48907481-479cb400-ee70-11e8-9e4f-967e1571c242.png)
http://vladtest54wwweb-vladtest54ww.kademi-ci.co/tasks/18252098/
http://vladtest54ww.admin.kademi-ci.co/manageUsers/18252073

**Comment by Uafinder** [comment]
Ok, looks good
