### ISSUE TITLE
Product import wizard problems

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6298]
The product list cant be imported because of dollar signs. I see this in the logs:
```
asBigDecimal: Couldnt convert to bigdecimal: $10.00
```

However, there is nothing about this in validation before import, or after

[gilpin-prods.zip](https://github.com/Kademi/kademi-dev/files/2602270/gilpin-prods.zip)

And the client says the "calculating" message is displayed continuously
https://gilpin.admin.kademi.com.au/

![image](https://user-images.githubusercontent.com/826458/48813797-3171f380-ed9d-11e8-89f9-4553fbac5a1b.png)

**Comment by bradmac** [comment]
> The product list cant be imported because of dollar signs

Importer is now tolerant of most currency symbols

**Comment by bradmac** [comment]
> And the client says the "calculating" message is displayed continuously

Tested with a simple file and seems fine:

[products(9).zip](https://github.com/Kademi/kademi-dev/files/2661017/products.9.zip)

**Comment by bradmac** [comment]
Also tested with the provided product spreadsheet, and status also displayed correctly.

**Comment by Uafinder** [comment]
Ukrainian hryvna is ok, russian ruble is not.... liiiiike :)

**Comment by bradmac** [comment]
LOL.

I did try to support rubles but there was some character encoding problem.
