### ISSUE TITLE
Search issue at Manage Products page

### ISSUE THREAD

**Issue by trungjc** [Kademi/kademi-dev#6300]
At Manage Products page, if search field value contains special symbols (example: "[space]-[space]",®...), the search result will return nothing.

Test keywords: `PHB - MTC300`, `Paul Mitchell - Awapuhi Shampoo®  (Original)  300ml`, `Lonely Planet - Culture Trails`

https://gilpin.admin.kademi.com.au/products/

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/48822939-bf60d500-edc3-11e8-9a74-b99907560a15.png)

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/48822970-dbfd0d00-edc3-11e8-9062-a2d62fdc99c5.png)

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/48822997-fa630880-edc3-11e8-83e2-fdd7eac805b8.png)

**Comment by bradmac** [comment]
So i think its working correctly. However the product codes have spaces which makes it impossible to search on a specific product code, because we split the search phrase into words

![image](https://user-images.githubusercontent.com/826458/48823030-22526c00-edc4-11e8-88f0-1fa11f0d60bf.png)

**Comment by bradmac** [comment]
I've done an update to strip out single punctuation characters like hyphen from search terms
