### ISSUE TITLE
KCom2: error when adding to cart

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6305]
![image](https://user-images.githubusercontent.com/1945230/48839412-164eb600-ed94-11e8-8e35-a0aa3d6a3353.png)
http://vladtest54vvweb-vladtest54vv.kademi-ci.co/vladtest54vvweb-ecomstore/beats000
http://vladtest54vv.admin.kademi-ci.co/manageUsers/18246611

**Comment by anhnt** [comment]
Cannot reproduce atm. @Uafinder could you check?

**Comment by Uafinder** [comment]
Maybe also due the incorrect lib? Seems ok to as well
