### ISSUE TITLE
KFeedbeack journey node missed settings

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6311]
No possibility to setup timeout and other settings
![image](https://user-images.githubusercontent.com/1945230/48846280-608d6280-eda7-11e8-8218-33583f8b9967.png)
http://vladtest54vvv.admin.kademi-ci.co/funnels/first-journey/version1/#journeyBuilder-tab

Needed for Carters
http://carters.admin.kademi-ci.co/funnels/after-checking-out-order-journey/version1/#journeyBuilder-tab

**Comment by anhnt** [comment]
added in v1.2.8

**Comment by Uafinder** [comment]
Looks good
