### ISSUE TITLE
Members list component not showing dynamic group members

### ISSUE THREAD

**Issue by joelatfuel** [Kademi/kademi-dev#6314]
I created three dynamic groups in Deloitte with the goal of showing these member lists in a Dashboard. I added a members list component to my Dashboard page and filtered the results by the dynamic groups I had created, but then I get a message saying 'No current results'.

<img width="1550" alt="screen shot 2018-11-22 at 12 51 53 pm" src="https://user-images.githubusercontent.com/41346338/48876830-297d8680-ee65-11e8-9280-3ebb6393bca8.png">

**Comment by bradmac** [comment]
@joelatfuel please provide..
- the page where you see the problem
- the user you're logged in with when you see the problem

**Comment by joelatfuel** [comment]
This is [the page](https://fraud-training.deloitte.co.nz/contenteditor?fileName=learners-dashboard.html) where I see the problem. I'm logged in as my own user (joel@fueldesign.co.nz)

**Comment by joelatfuel** [comment]
It's a quick workaround, but I can see that they won't be happy with this solution. The critical reason to use the membersTable component is that it has the 'View Profile' button - it's all in one place for Deloitte. Also, they can send easily send emails to members of that group.

I understand you guys are busy, so what's a realistic timeline for this bug to be fixed?

**Comment by bradmac** [comment]
Its in the current milestone, so should be done this week.

**Comment by bradmac** [comment]
@Uafinder to test this issue, create a dynamic group and verify its working (if yuo have problems with the dynamic group itself thats a seperate issue!), and then use the members table component in a front end website and connect to that dynamic group

**Comment by Uafinder** [comment]
i can't make it works
Here is a group
http://vladtest54xx.admin.kademi-ci.co/groups/18261452
Here is a page
http://vladtest54xxweb-vladtest54xx.kademi-ci.co/page1.html
Here is a component
![image](https://user-images.githubusercontent.com/1945230/49090532-9b3f4100-f266-11e8-9516-97f473c2c96e.png)
And it shows nothing
![image](https://user-images.githubusercontent.com/1945230/49090539-a1cdb880-f266-11e8-951e-7114ccd4236b.png)

**Comment by bradmac** [comment]
Sorry, my bad, i didnt push my changes.

Please try now with user-lib 1.4.1

**Comment by Uafinder** [comment]
Looks good
