### ISSUE TITLE
KCom2: different billing address country field value should be clicked twice on selection

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6315]
When you click on Australia value it pasted to field, but dropdown is not disappearing
![image](https://user-images.githubusercontent.com/1945230/48900064-00a3c400-ee5a-11e8-8e4c-2e848e03a354.png)
![image](https://user-images.githubusercontent.com/1945230/48900070-05687800-ee5a-11e8-8d32-607e81fac8ca.png)
When you click twice it paste correctly
http://vladtest54wweb-vladtest54w.kademi-ci.co/vladtest54wweb-ecomstore/cart
http://vladtest54w.admin.kademi-ci.co/manageUsers/18250694/#general-tab

**Comment by anhnt** [comment]
Fixed in v1.4.2 and jquery reloadFragment 1.0.3 in this commit https://github.com/Kademi/kademi-dev/commit/673bdb67ebd218f03b9da4548e40a13d15621964

**Comment by Uafinder** [comment]
looks good
