### ISSUE TITLE
KCom2: Expression based shipping provider

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6319]

**Comment by bradmac** [comment]
This needs to be setup initially by editing XML:
![image](https://user-images.githubusercontent.com/826458/48963413-6fb61f80-eff6-11e8-9511-84a637d663bc.png)

This will then display on the shipping providers page:
![image](https://user-images.githubusercontent.com/826458/48963417-8197c280-eff6-11e8-95ef-e3a91bf6780b.png)

And you can edit by clicking through to the detail page:
![image](https://user-images.githubusercontent.com/826458/48963421-94aa9280-eff6-11e8-87d1-23b5739ce69f.png)

**Comment by bradmac** [comment]
The XML from the example above:
```
<pricing-config>
  <shippingProviders>
    <expression id="acme" title="ACME Freight and Logistics">
      <expr>
          if( productSku.product.hasCategory("eft") ) {
            quantity * productSku.product.freightCost
          } else {
            productSku.product.freightCost
          }
      </expr>
    </expression>
  </shippingProviders>
  <taxProviders>
    <default-tax-calc id="gst"/>
  </taxProviders>
  <currencyCode>AUD</currencyCode>
  <pointsBuckets>
    <string>w2-points</string>
    <string>w3-points</string>
    <string>org-points</string>
  </pointsBuckets>
</pricing-config>
```

**Comment by bradmac** [comment]
What this expression does it..
- for a product in the "eft" category, multiple the quantity the user has selected by the freight cost on the product
- for other products its just the freight cost once (regardless of quantity)

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/48963566-d8eb6200-eff9-11e8-89df-f6c346cee3b4.png)

**Comment by Uafinder** [comment]
Looks good
