### ISSUE TITLE
Update menuComponent

### ISSUE THREAD

**Issue by trungjc** [Kademi/kademi-dev#6320]
Update menuComponent:

- When a sub menu item is selected  the 1st level menu item should be highlighted.
- Add nav-pills style to menu

https://github.com/Kademi/projects/issues/851

**Comment by trungjc** [comment]
![screenshot_4](https://user-images.githubusercontent.com/704946/49003820-57303b80-f195-11e8-9f4f-5ea7bc9155be.png)
 Pills style have added for menuComponent 
https://github.com/Kademi/kademi-dev/commit/8ed2e9de5f0cbb12b46f87714c0a18b653e31a83

**Comment by trungjc** [comment]
> When a sub menu item is selected the 1st level menu item should be highlighted.

@bradmac will take care it

**Comment by bradmac** [comment]
Done. Needs content-lib 1.4.7

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/49345316-074afa80-f6e8-11e8-8e9d-84d87f07338a.png)

![image](https://user-images.githubusercontent.com/826458/49345329-29447d00-f6e8-11e8-803b-572c0db17b2b.png)

**Comment by anhnt** [comment]
@trungjc please update menu2 component as well

**Comment by Uafinder** [comment]
Looks good
