### ISSUE TITLE
Contact form layout break in tablet screen

### ISSUE THREAD

**Issue by trungjc** [Kademi/kademi-dev#6324]
Contact form layout break in tablet screen

![screenshot_13](https://user-images.githubusercontent.com/704946/49057087-b98a4a00-f230-11e8-96ab-32600591224f.png)

**Comment by Uafinder** [comment]
I think something is broken now
![image](https://user-images.githubusercontent.com/1945230/49091498-a5fad580-f268-11e8-9715-9257e406be7c.png)
http://vladtest54xx.admin.kademi-ci.co/pages/vladtest54xxweb/version1/
http://vladtest54xxweb-vladtest54xx.kademi-ci.co/contactus

**Comment by bradmac** [comment]
thats because contactus lib hasnt synced correctly..
http://vladtest54xx.admin.kademi-ci.co/repositories/contactus-lib/1.0.8/

![image](https://user-images.githubusercontent.com/826458/49114501-38e54f80-f2fd-11e8-8f25-cac889472a03.png)

**Comment by bradmac** [comment]
Synced and removed the contactform override, now looking good

**Comment by Uafinder** [comment]
Ok, looks good
