### ISSUE TITLE
Promotions: New promotion mechanics, and extensible framework

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#6325]
![clipboard - november 27 2018 4-31 pm](https://user-images.githubusercontent.com/39784677/49106940-57415000-f2e9-11e8-8d49-03bce42e5ff4.png)

**Comment by bradmac** [comment]
Management screen. Note this is no longer on the promotion page, its on the store management.
![image](https://user-images.githubusercontent.com/826458/49269080-ffad0b00-f4c7-11e8-80f6-0a5ba27a9eb9.png)

**Comment by bradmac** [comment]
Form for a checkout rule..
![image](https://user-images.githubusercontent.com/826458/49269092-12bfdb00-f4c8-11e8-99a2-0c920e98778d.png)

Note the last 4 fields are configured by the rule type, and will be different for different rule types

**Comment by bradmac** [comment]
The 'free gift' fields have been removed from the promotion management page.

NOTE: the free gift fields are still shown if its enabled to be backwards compatible

![image](https://user-images.githubusercontent.com/826458/49269138-48fd5a80-f4c8-11e8-85c3-0b647d6880f4.png)

**Comment by bradmac** [comment]
The front end appearance hasnt really changed, but the displayed values will vary depending on the rule type:
![image](https://user-images.githubusercontent.com/826458/49269154-63cfcf00-f4c8-11e8-9efa-fcf24f3e30f3.png)

**Comment by bradmac** [comment]
Next: Create a second rule type which is "Buy X get 1 free" mechanic.

And a 'free shipping' rule, which will deduct shipping fees for elligible products (note this cant be done with shipping providers)

**Comment by bradmac** [comment]
Buy X get 1 free mechanic..

![image](https://user-images.githubusercontent.com/826458/49285765-436e3780-f4fd-11e8-8179-d171f48acdd2.png)

front end..

![image](https://user-images.githubusercontent.com/826458/49285801-5e40ac00-f4fd-11e8-88d7-cc54e54f8879.png)

**Comment by bradmac** [comment]
OK, all done. Two promotion mechanics implemented:
![image](https://user-images.githubusercontent.com/826458/49325525-b7b1e500-f5a8-11e8-81d4-122bfb489c41.png)

And developers can add more

**Comment by Uafinder** [comment]
Promotion field not saving
http://vladtest55e.admin.kademi-ci.co/websites/vladtest55eweb/version1/store-vladtest55eweb-ecomstore/?checkoutRuleId=gift-lego
![image](https://user-images.githubusercontent.com/1945230/49588211-d6302b80-f96e-11e8-9508-d8f873e4d1bc.png)

**Comment by bradmac** [comment]
Fixed

**Comment by Uafinder** [comment]
looks good
