### ISSUE TITLE
Moderate posts page should indicate type of posts

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6327]

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/49111515-2f57e980-f2f5-11e8-94fe-de5b6c335dbc.png)

**Comment by bradmac** [comment]
This is pretty rough, but should do for now

**Comment by Uafinder** [comment]
I haven't see details for content column
![image](https://user-images.githubusercontent.com/1945230/49229984-4e3ea480-f3f7-11e8-8d5c-895b2411707d.png)
http://vladtest54zz.admin.kademi-ci.co/managePosts/#posts-tab
3 month

**Comment by Uafinder** [comment]
1. feedback doesn't display on posts page
http://vladtest54zz.admin.kademi-ci.co/managePosts/#posts-tab
![image](https://user-images.githubusercontent.com/1945230/49278534-c9529a00-f48d-11e8-9254-66588b0b8895.png)
http://vladtest54zz.admin.kademi-ci.co/manageUsers/18268624/#summary-tab

p.s. icons for posts are bad
![image](https://user-images.githubusercontent.com/1945230/49278495-a7f1ae00-f48d-11e8-9a9a-f6d13791f678.png)
http://vladtest55a.admin.kademi-ci.co/managePosts/#posts-tab

**Comment by bradmac** [comment]
> feedback doesn't display on posts page

I think this is just a vaya-speciic customisation. The sentiment feedback wont be treated as a wall activity by default.

>   p.s. icons for posts are bad

I've updated to use fontawesome icons

![image](https://user-images.githubusercontent.com/826458/49325515-5ee24c80-f5a8-11e8-818a-739c542550e0.png)

**Comment by Uafinder** [comment]
Still doesn't seeing activity
![image](https://user-images.githubusercontent.com/1945230/49579972-69a93280-f956-11e8-8195-4c29e5b39b10.png)
http://vladtest55e.admin.kademi-ci.co/managePosts/#posts-tab

**Comment by bradmac** [comment]
@Uafinder you can see this working currently in vaya
http://vayability.admin.kademi.us/managePosts/#posts-tab

You're not seeing it in your account because it doesnt have all the stuff setup to do wall posts.

![image](https://user-images.githubusercontent.com/826458/49611320-0d055080-fa06-11e8-83b4-b6248e60872a.png)
