### ISSUE TITLE
CSV Export on Reports

### ISSUE THREAD

**Issue by faithtek** [Kademi/kademi-dev#6329]
CSV Export doesn't seem to work anymore on Reports. Now this may once again be my misunderstanding of how to get it to work, but either way -- needs to be looked at. You can look at this from the link below, but seems to happen the same with all our accounts:

https://nutrablend.admin.kademi.us/reporting/point-balance-report?startDate=27%2F11%2F2008&finishDate=27%2F11%2F2018

This is the report:

![image1](https://user-images.githubusercontent.com/7914822/49119270-a0f05300-f275-11e8-830f-df934f66fc23.png)

And this is the data from data.csv when I try to export:

![image2](https://user-images.githubusercontent.com/7914822/49119320-da28c300-f275-11e8-8a5f-fae59ee325c2.png)

**Comment by bradmac** [comment]
This is a custom report, but no table has been selected. This is selected when the custom report is created:

![image](https://user-images.githubusercontent.com/826458/49325330-5e948200-f5a5-11e8-9c4f-183ade5f0d8c.png)

There is currently no UI to edit the table after a report is created, but you can edit it in JSON here:

https://nutrablend.admin.kademi.us/repositories/queries/version1/texteditor?fileName=point-balance-report.report.json

![image](https://user-images.githubusercontent.com/826458/49325349-aca98580-f5a5-11e8-8135-d96e0efa0a7a.png)

**Comment by faithtek** [comment]
Thanks.
