### ISSUE TITLE
Backup/Restore: Does not restore all versions of websites and all repositories

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#633]
There appears to be no explicit restore step for websites and repositories, so i'm not sure whats doing the restore, but anyway it seems to only restore the live version 

For example on merc sandbox the only version of the star rewards program website is "version1", which appears to have the correct content but is not the correct name. And anyway, its important for merc to have the current dev version restored so they can test it

See here - http://admin.mercedes.kademi-sandbox.co/websites/mercedes-reward-program/version1/

**Comment by tuzzmaniandevil** [comment]
This is because the Backup/Restore process was never finished. see #635
