### ISSUE TITLE
members list component All groups error

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6330]
![image](https://user-images.githubusercontent.com/1945230/49153270-ee27ff80-f31d-11e8-8734-1be1ea40a3f1.png)
http://vladtest54y.admin.kademi-ci.co/pages/vladtest54yweb/version1/?contenteditor=page2.html

I think this is due to Dynamic group presence

**Comment by bradmac** [comment]
fixed

**Comment by Uafinder** [comment]
Ok, error not showing
But all groups also shows nothing
![image](https://user-images.githubusercontent.com/1945230/49276743-fef48480-f487-11e8-80a9-f47a07307767.png)
http://vladtest55aweb-vladtest55a.kademi-ci.co/page1.html
http://vladtest55a.admin.kademi-ci.co/pages/vladtest55aweb/version1/?contenteditor=page1.html

**Comment by bradmac** [comment]
The component now requires a group to be selected. I've changed the default label to "None" instead of "All groups" to indicate this.

**Comment by Uafinder** [comment]
ok
