### ISSUE TITLE
survey upload image bad

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6331]
![image](https://user-images.githubusercontent.com/1945230/49154152-5f68b200-f320-11e8-8393-f4d778c74c47.png)
![image](https://user-images.githubusercontent.com/1945230/49154163-6db6ce00-f320-11e8-88a5-d05e7f7c6607.png)
http://vladtest54y.admin.kademi-ci.co/ksurvey/survey-93545309-3549-4f1a-8f45-1e3c7d7c6122/#detail-tab

**Comment by anhnt** [comment]
Fixed in 1.4.1

**Comment by anhnt** [comment]
https://github.com/Kademi/kademi-dev/commit/a33f9a84f3b330faea944ee01143bf351cb3a8e2

**Comment by Uafinder** [comment]
When accessing survey i'm seeing this error in console:
![image](https://user-images.githubusercontent.com/1945230/49221147-f006c700-f3e0-11e8-9dbd-705c86083189.png)
http://vladtest54z.admin.kademi-ci.co/ksurvey/survey-767a5b3f-ea54-40dc-82e7-cf329371e639/#detail-tab

When cropping uploading image it shows another error in console
![image](https://user-images.githubusercontent.com/1945230/49221190-10cf1c80-f3e1-11e8-84d4-2c11df2889b9.png)

**Comment by anhnt** [comment]
>When accessing survey i'm seeing this error in console: 

Looks ok

>When cropping uploading image it shows another error in console

looks like CI doesnt support cropping image

**Comment by anhnt** [comment]
Added crop feature 

Published ksurveyapp version 1.4.2 with hash 795b253b2c8c0fc484286430de0e71db759462ba

**Comment by Uafinder** [comment]
Looks good
