### ISSUE TITLE
Category link in ecomStoreCategoriesComponent is missing store path

### ISSUE THREAD

**Issue by trungjc** [Kademi/kademi-dev#6334]
Category link in ecomStoreCategoriesComponent is missing store path. So when user use this component will go to 404 page.

> Issue with link to cats from homepage

https://github.com/Kademi/projects/issues/839#issuecomment-442408782

**Comment by bradmac** [comment]
Guys, there's 2 possibilitites
1. the component is being used within a store
2. the component is being used outside a store (eg on a website home page)

If 1. then the path should be relative to that store

If 2. then the user is required to select a store in settings.

@anhnt is this what horzCategoriesComponent does?

**Comment by trungjc** [comment]
> Guys, there's 2 possibilitites

   the component is being used within a store
    the component is being used outside a store (eg on a website home page)

If 1. then the path should be relative to that store

If 2. then the user is required to select a store in settings.

ecomStoreCategoriesComponent has been updated

**Comment by anhnt** [comment]
Fixed both components to use a absolute path ie /store-name/cat-name so when curren page is store it will use that otherwise it needs to set a store from setting.

**Comment by Uafinder** [comment]
Good
