### ISSUE TITLE
Upload to assets doesn't work at all

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6339]
Upload to assets doesn't work at all.

(And some other minor things)

![image](https://user-images.githubusercontent.com/1945230/49225299-5e04bb80-f3ec-11e8-9070-29f907a63a91.png)
http://vladtest54zz.admin.kademi-ci.co/websites/vladtest54zzweb/version1?editTemplate=theme/defaultThemeTemplate
When you edit logo first you will see following error
![image](https://user-images.githubusercontent.com/1945230/49225349-770d6c80-f3ec-11e8-90be-ba2fb9d8c661.png)

Also when you will upload image to regular placeholders - it will not select it by default. You will need to select it manually.
Upload to assets doesn't work at all.

**Comment by anhnt** [comment]
@bradmac please have a look at BrowseResource
After uploaded to asset, it is calling to this url to get file detail then adding to tree. but its returning nothing

http://vladtest54zzweb-vladtest54zz.kademi-ci.co/_browse?browseHref=/assets/69b3e31f-9ded-4dae-9554-b90b870e2600&_=1543543511224

**Comment by anhnt** [comment]
FYI upload to asset is still success and can see after reloading page

**Comment by bradmac** [comment]
> Upload to assets doesn't work at all.

@anhnt I've changed jquery.mtree.js to always use the asset path for the asset view. I'm not sure why it was doing the if statement, but seems unnecessary

Old:
```
var assetUrl = $.isKademiAdminPage ? '/assets?q=' + name : self.getPropFindUrl(path);
```

New
```
var assetUrl = '/assets?q=' + name;
```

**Comment by bradmac** [comment]
The main issue should be fixed now.

I've moved less important UX issues here - https://github.com/Kademi/kademi-dev/issues/6347

**Comment by Uafinder** [comment]
ok, looks good
