### ISSUE TITLE
Buttons for containers are invisible in blog editor

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6342]
![image](https://user-images.githubusercontent.com/1945230/49228781-c192e700-f3f4-11e8-9b05-5c9bf7f6fee9.png)
http://vladtest54zz.admin.kademi-ci.co/blogs/blog/test-1/#bodyCopy-tab

**Comment by anhnt** [comment]
This is because of conflicting between FontAwesome5 on site and FontAwesome4 on admin.
I updated admin to use FA5 and fixed the issue with contentEditor-lib that was loading wrong css file

**Comment by Uafinder** [comment]
ok
