### ISSUE TITLE
KCom2: Support ordering fields

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6346]
required for https://github.com/Kademi/client-212f/issues/101

**Comment by bradmac** [comment]
Here's an example product configuration, with both ordering field (date of birth) and ordering option (colour)

The ordering option will be handled with SKU's, while the ordering field will be handled with a form
![image](https://user-images.githubusercontent.com/826458/49320851-e019ef00-f568-11e8-9c2d-c3e5780276fa.png)

**Comment by bradmac** [comment]
Front end initially looks like this initially..
![image](https://user-images.githubusercontent.com/826458/49320892-1e171300-f569-11e8-892f-36f49c3995e6.png)

When the user adds to cart a form is displayed (because this has ordering fields; products with no fields do not get this form)
![image](https://user-images.githubusercontent.com/826458/49320923-4d2d8480-f569-11e8-8ac8-f8ba01266741.png)

**Comment by bradmac** [comment]
This is then displayed on the checkout form..

![image](https://user-images.githubusercontent.com/826458/49320938-67676280-f569-11e8-87ed-caa5353bed4f.png)

And this is displayed on the order detail page after submitted

![image](https://user-images.githubusercontent.com/826458/49320998-bb724700-f569-11e8-96dc-8a9f7522867e.png)

**Comment by bradmac** [comment]
Requires kcom2 1.4.6

**Comment by Uafinder** [comment]
Cools
