### ISSUE TITLE
Image selection should only allow selecting images

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6347]
Currently, when i use the editor UI to insert an image the browser allows me to select and insert items which are not images:

![image](https://user-images.githubusercontent.com/826458/49344618-b256b680-f6de-11e8-961d-0fc66d11177c.png)

Please ensure that when browsing for images, if the user selects a non-image resource the preview panel says 'Unsupported preview file' and the tick to accept is disabled

**Comment by anhnt** [comment]
Done

**Comment by Uafinder** [comment]
OK, it keditor (for example for page edit)
But for example for module image upload it doesn't work
![image](https://user-images.githubusercontent.com/1945230/49587266-0fb36780-f96c-11e8-8b34-ebeed43690fe.png)
http://vladtest55e.admin.kademi-ci.co/websites/vladtest55eweb/version1/programs/p1/c1/m1/#details-tab

is it implemented to all image selectors?

**Comment by bradmac** [comment]
We have 2:
- a custom ckeditor image plugin 
- a general purpose file selection lib (mselect)

They both use the same plugin for the left hand panel (mtree).

@anhnt please make sure both are working correctly.

**Comment by anhnt** [comment]
Fixed, this was using static mselect js

**Comment by Uafinder** [comment]
Looks good now
