### ISSUE TITLE
Improve menu editing UX

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6348]
1. Move the menu items editor to the top of the settings form, just under logo
2. Currently, its very easy for the user to forget to save the menu after changing menu items. I suggest save the menu immediately when the user clicks the tick button for a menu item

![image](https://user-images.githubusercontent.com/826458/49344975-3ad75600-f6e3-11e8-9c15-749759da880f.png)

![image](https://user-images.githubusercontent.com/826458/49344990-7d009780-f6e3-11e8-9994-9ae360fd4c75.png)

**Comment by anhnt** [comment]
Done

**Comment by Uafinder** [comment]
Looks good
