### ISSUE TITLE
Number of Users component not counting dynamic group members

### ISSUE THREAD

**Issue by joelatfuel** [Kademi/kademi-dev#6350]
I added a numUsers component to the Deloitte dashboard and chose one of my dynamic groups. The number in this component only shows a 0. Can we have this show the correct number of members?

This is the [page](https://fraud-training.deloitte.co.nz/contenteditor?fileName=learners-dashboard.html) where I see the problem. I'm logged in as my own user (joel@fueldesign.co.nz)

**Comment by bradmac** [comment]
Requires reporting-lib 1.4.3

**Comment by Uafinder** [comment]
it works

**Comment by joelatfuel** [comment]
@bradmac have you pushed these changes? There are no updates for me to upgrade to reporting-lib 1.4.3.

**Comment by bradmac** [comment]
@joelatfuel published, available now :)

**Comment by bradmac** [comment]
@joelatfuel sorry, this update hasnt been applied to prod yet. Should be today or tomorrow

**Comment by joelatfuel** [comment]
@bradmac Has this update been applied to production yet?

**Comment by joelatfuel** [comment]
@bradmac Do you have an update on this release?

**Comment by bradmac** [comment]
Yep. Please see this channel to keep up to date..

https://chat.kademi.co/channel/deployment-followup
