### ISSUE TITLE
KCRM: menu broken after menu component update

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6351]
![image](https://user-images.githubusercontent.com/1945230/49376235-4771a380-f70f-11e8-9e41-c263cc5b3d71.png)
http://vladtest55bbweb-vladtest55bb.kademi-ci.co

Also,
Custom menu title appears twice
![image](https://user-images.githubusercontent.com/1945230/49376275-696b2600-f70f-11e8-91ee-86abd6a04472.png)
http://vladtest55bbweb-vladtest55bb.kademi-ci.co/profile/

**Comment by anhnt** [comment]
@Uafinder menu3 is created for using with kcrm theme so it has some custom code that check and render items under button New (Plus icon). Can you please show me steps to reproduce this error?
IMO i dont think we should edit that "New" word

**Comment by Uafinder** [comment]
I installed new kcrm account, install kcrm theme
Then tried to add custom menu item (called Profile)
E.g. just edit it.
If you need we could chat when you're in.

**Comment by anhnt** [comment]
deployed to US to fix kcrm

**Comment by Uafinder** [comment]
Looks better
