### ISSUE TITLE
Admin add order screen doesnt work

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6354]
When adding a product the HTML is displayed:

![image](https://user-images.githubusercontent.com/826458/49411457-de049a00-f7cd-11e8-8913-8f0deb89a7b0.png)

**Comment by bradmac** [comment]
Fixed

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/49411775-18bb0200-f7cf-11e8-9a36-45d3b6020268.png)

**Comment by Uafinder** [comment]
Error while searching product for kcom2
![image](https://user-images.githubusercontent.com/1945230/49586743-abdc6f00-f96a-11e8-841d-847817347c56.png)
http://vladtest55e.admin.kademi-ci.co/shopping-carts/

**Comment by bradmac** [comment]
> Error while searching product for kcom2

Fixed

**Comment by bradmac** [comment]
FYI, this was a regression due to this
https://github.com/Kademi/kademi-dev/issues/6371

**Comment by Uafinder** [comment]
ok, looks better
