### ISSUE TITLE
KCRM: Enhance task list on leads page so closed leads are initially hidden

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6357]
![image](https://user-images.githubusercontent.com/826458/49470115-0b088980-f86e-11e8-890b-551c478dbd37.png)

**Comment by anhnt** [comment]
Done

![image](https://user-images.githubusercontent.com/735555/49498720-93068780-f89e-11e8-9dd1-2124b79c548d.png)

**Comment by Uafinder** [comment]
Yup, seems to be fine
