### ISSUE TITLE
Contact form component: add option to hide labels

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6358]

**Comment by trungjc** [comment]
![screenshot_6](https://user-images.githubusercontent.com/704946/49484743-b9123480-f86a-11e8-87be-4467989279e3.png)

Change to Show Labels

**Comment by Uafinder** [comment]
haven't seeing this option
![image](https://user-images.githubusercontent.com/1945230/49516103-6dc74880-f8a1-11e8-9379-71389e33ba02.png)
http://vladtest55d.admin.kademi-ci.co/pages/vladtest55dweb/version1/?contenteditor=contacts.html

http://vladtest55d.admin.kademi-ci.co/websites/vladtest55dweb/version1?editTemplate=theme/apps/contactus/contactForm
![image](https://user-images.githubusercontent.com/1945230/49516147-8fc0cb00-f8a1-11e8-9433-8fd720144d50.png)
http://vladtest55d.admin.kademi-ci.co/pages/vladtest55dweb/version1/

**Comment by anhnt** [comment]
lib repo is blank http://vladtest55d.admin.kademi-ci.co/repositories/contactus-lib/1.0.9/

i just republish so try this hash

Published contactus-lib version 1.0.9 with hash 7c8a763fbf019b1b7a741f76f7351e791356e2f3

**Comment by Uafinder** [comment]
It works on fresh account
