### ISSUE TITLE
KCRM: menu contains "Root menu item" words

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6362]
![image](https://user-images.githubusercontent.com/1945230/49514572-1b842880-f89d-11e8-951a-61b08d6949a7.png)
http://vladtest55dweb-vladtest55d.kademi-ci.co/profile/
http://vladtest55d.admin.kademi-ci.co/websites/

**Comment by anhnt** [comment]
Fixed, applied to this account

**Comment by Uafinder** [comment]
Looks good
