### ISSUE TITLE
Waterware - some products not found in index

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#6364]
At first I thought creating a new product and/or editing a product was not applying to the index fast enough and needed a manual re-index.

Turns out there is a conflict with the name.

Examples:

Missing product from index **Electric Towel Rails**
_Web Name: towel-rails_ 
http://waterware.admin.kademi.com.au/products/136271608/#panel_details-tab

Because it is assigned to the Towel Rails category
_Code: towel-rails / Kademi ID: 125576890_ 
http://waterware.admin.kademi.com.au/categories/towel-rails/#panel_details-tab

This is the issue:
http://waterware-waterware.kademi.com.au/store/towel-rails/ shows the category, not the product.

Perhaps this can be fixed the following way by enforcing the below:
/store/underfloor-and-radiators/
/store/underfloor-and-radiators/towel-rails/

**Comment by bradmac** [comment]
Looks like the product hasnt been added to store:

![image](https://user-images.githubusercontent.com/826458/49546826-06170900-f946-11e8-811b-e743f05f1ac9.png)
