### ISSUE TITLE
Asset Manager - unable to empty an already set asset field

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#6366]
Please note, this issue has been reported by all our clients who are using asset manger.

Example:
http://waterware.admin.kademi.com.au/asset-manager/3ae78336-ba05-40f4-ba57-8583bdd2fd36
Try and empty **Supplier logo** field, then click save. It reverts back. You can update the field, but not reset it to blank.

**Comment by anhnt** [comment]
done

**Comment by Uafinder** [comment]
Looks good
