### ISSUE TITLE
Asset Manager - Have to force refresh page on fields that are 'allowMany' to add another related item.

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#6367]
Please note, this issue has been reported by all our clients who are using asset manger.

Forced to refresh the page when adding “allowMany” related items.

Examples (many examples)
http://waterware.admin.kademi.com.au/asset-manager/3ae78336-ba05-40f4-ba57-8583bdd2fd36

Used Product and Additional Gallery Images.
Once you add a new item and click save, you are then required to refresh page to get a new field that says ''type to search' in order to add another item.

**Comment by anhnt** [comment]
Fixed

**Comment by Uafinder** [comment]
It works

**Comment by Uafinder** [comment]
Well, actually it works not very good
It forces refresh only for first allowMany object.
E.g. when click upload or add and push save it gives you a second field, but when you add a second one it will not show you a third
http://vladtest55f.admin.kademi-ci.co/asset-manager/9153dabf-d2af-4410-92b0-d200dd25e251
![image](https://user-images.githubusercontent.com/1945230/49654636-12cc5780-fa41-11e8-8225-f1dff2520ae5.png)
![image](https://user-images.githubusercontent.com/1945230/49654652-1c55bf80-fa41-11e8-9200-9ccda18852ca.png)

**Comment by anhnt** [comment]
You didnt restart QA so it was using old code. Just restarted and its working for me

![image](https://user-images.githubusercontent.com/735555/49680989-67b5af80-facd-11e8-9585-af02603b122f.png)

**Comment by anhnt** [comment]
Dont forget to run this job as well

![image](https://user-images.githubusercontent.com/735555/49680995-8d42b900-facd-11e8-8310-01b62f647286.png)

**Comment by Uafinder** [comment]
Yeah, looks fine
