### ISSUE TITLE
Asset Manager - PLUS symbol on a related item field appears to be reduntant or confusing.

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#6368]
http://waterware.admin.kademi.com.au/asset-manager/3ae78336-ba05-40f4-ba57-8583bdd2fd36

**Used Product** fields. Not sure what PLUS symbol is supposed to do. All customers are asking me this question.

**Comment by bradmac** [comment]
The plus button is to create a new asset, and link to it.

The edit button is to edit the currently linked asset.

We should hide the edit and view buttons for currently blank fields:

![image](https://user-images.githubusercontent.com/826458/49549388-79704900-f94d-11e8-96d0-bbba0ca328c8.png)

**Comment by stephen-fueldesign** [comment]
@brad, clicking the PLUS and EDIT icons does weird things. Either the relationship to a product asset is incorrect, or the PLUS and EDIT icons are wrong in this use case. And I don’t know what the VIEW icon is meant to do in this scenario too; other than visit the related asset individually? It just comes up blank for me.

https://waterware.admin.kademi.com.au/asset-manager/3ae78336-ba05-40f4-ba57-8583bdd2fd36

**Comment by bradmac** [comment]
> clicking the PLUS and EDIT icons does weird things

please give an example

> And I don’t know what the VIEW icon is meant to do

It is meant to view the asset. Obviously this doesnt make sense for a blank field.

**Comment by stephen-fueldesign** [comment]
Ok, PLUS and EDIT icons are fine. It was just confusing because it was not clear that you were editing or creating a new Content Type item, or which one. Would be nice to have the Content Type name on the popup to remove all confusion.

<img width="777" alt="screen shot 2018-12-06 at 2 26 40 pm" src="https://user-images.githubusercontent.com/39784677/49555257-235ad000-f964-11e8-9efc-89b7e9c1c9e1.png">

**Comment by anhnt** [comment]
I have refactored this screen.

![image](https://user-images.githubusercontent.com/735555/49641808-d0584a00-fa43-11e8-92da-e81d1c59b401.png)

So now we can view/edit/delete selected relation asset which is allowMany
There is always a placeholder at the last so user can enter text to find/select new asset

![image](https://user-images.githubusercontent.com/735555/49641893-14e3e580-fa44-11e8-9d6d-d744c0db5a1d.png)


For single relation asset there is plus button: 
Click to that to add new asset or search to change asset but not able to delete it :)

@Uafinder please try check this and ping me if you can see any error. I can provide sample asset content type xml if you like

**Comment by anhnt** [comment]
https://github.com/Kademi/kademi-dev/commit/87daf0616d50f7f4599b98b4b36e659a1869cff6

https://github.com/Kademi/kademi-dev/commit/95c95066f4312dd76c264bb8722175532e22e079

**Comment by Uafinder** [comment]
Looks like no errors, fine for me
