### ISSUE TITLE
Optimise css and js resource loading in admin

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6370]

**Comment by bradmac** [comment]
@anhnt please search for all references to glyphicons and replace them with fa, and remove the glyphicon css and font files.

**Comment by bradmac** [comment]
Note that JS and CSS dependencies are now collected and merged.

JS: has been moved to admin-lib dependencies.json

CSS: currently still in normal.html, but the templater has been updated to push them into the list of CSS files to be merged.

**Comment by Uafinder** [comment]
I seeing errors on fresh account
http://vladtest55ddd.admin.kademi-ci.co/websites/vladtest55dddweb/version1/#panel_details-tab
![image](https://user-images.githubusercontent.com/1945230/49570807-4d020000-f940-11e8-83bf-22517ba0eb03.png)

**Comment by anhnt** [comment]
Fixed

**Comment by anhnt** [comment]
@Uafinder please amend any issue which is related here

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/49579034-e71f7380-f953-11e8-944a-0c443c485ec2.png)
Admin console login window Js issue
http://vladtest55e.admin.kademi-ci.co/

**Comment by bradmac** [comment]
The JS files were being generated in an incorrect order.

Fixed.

**Comment by bradmac** [comment]
Also fixed password reset page

**Comment by Uafinder** [comment]
seems to be ok so far, will keep an eye on it
