### ISSUE TITLE
K-theme: upper menu buttons should be cetrered vertically (like logo)

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6373]
![image](https://user-images.githubusercontent.com/1945230/49575629-d9fe8680-f94b-11e8-8993-e6cfdf62da2a.png)
http://vladtest55eweb-vladtest55e.kademi-ci.co/
http://vladtest55e.admin.kademi-ci.co/manageUsers/18294169

**Comment by trungjc** [comment]
Done

**Comment by Uafinder** [comment]
Looks good
