### ISSUE TITLE
admin login js sources are loaded random ordering

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#6374]
Source

![image](https://user-images.githubusercontent.com/735555/49577449-fca79400-f979-11e8-953f-2bed32fa9a3e.png)

![image](https://user-images.githubusercontent.com/735555/49577487-1943cc00-f97a-11e8-8257-a80661f36b0e.png)

Reproducible here when in login page 

http://rootorg.admin.kademi-ci.co/

**Comment by bradmac** [comment]
Fixed.

https://github.com/Kademi/kademi-dev/issues/6370#issuecomment-445025136
