### ISSUE TITLE
Keditor font increase cause some visual degrade

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6376]
![image](https://user-images.githubusercontent.com/1945230/49586927-358c3c80-f96b-11e8-83aa-97074f0c0544.png)
http://vladtest55e.admin.kademi-ci.co/pages/vladtest55eweb/version1/
http://vladtest55e.admin.kademi-ci.co/pages/vladtest55eweb/version1/?contenteditor=page2.html

![image](https://user-images.githubusercontent.com/1945230/49586957-4b99fd00-f96b-11e8-9f50-7c64ccd04284.png)
![image](https://user-images.githubusercontent.com/1945230/49586966-55236500-f96b-11e8-8802-42dc0f4b9aab.png)

**Comment by bradmac** [comment]
Yep, lets lock font size styles for the editor panel. I've seen layout break due to button styles too.

**Comment by anhnt** [comment]
Done

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/49861468-7a621880-fe2e-11e8-876c-c0d3c5d591a2.png)

**Comment by Uafinder** [comment]
YEah, looks much better
