### ISSUE TITLE
Blog content editor uploading issues

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6377]
Issue when Press edit button on image container in blog article
![image](https://user-images.githubusercontent.com/1945230/49587455-894b5580-f96c-11e8-9b39-d6fb2a6d354a.png)

and as a result file structure is not loading
![image](https://user-images.githubusercontent.com/1945230/49587495-ad0e9b80-f96c-11e8-9199-3b16669ccf32.png)
http://vladtest55e.admin.kademi-ci.co/blogs/blog1/c19935/#bodyCopy-tab

**Comment by bradmac** [comment]
> First there are a bunch of thumb missed errors when accessing article edit page

This should be treated on its own issue related to kcom2 components

**Comment by bradmac** [comment]
> Issue when Press edit button on image container in blog article

@anhnt the browse resource isnt available on a blog repo, only on websites

But, i think in this case it makes sense to restrict file browser to only assets. The blog content itself is held outside the webstie, so it should not depend on assets in the website. 

So please apply the option for assets only.

**Comment by anhnt** [comment]
Fixed, requires contentEditor-lib 1.3.7 and mtree-lib 1.1.0

**Comment by Uafinder** [comment]
Fresh account
Looks same for me
![image](https://user-images.githubusercontent.com/1945230/49736297-697ca000-fc92-11e8-807e-4192676bd3ed.png)
http://vladtest55g.admin.kademi-ci.co/blogs/blog1/article1/#bodyCopy-tab

**Comment by bradmac** [comment]
Looks good to me:

![image](https://user-images.githubusercontent.com/826458/49758407-b5c3f080-fd23-11e8-8e53-fbabefed7e26.png)

**Comment by bradmac** [comment]
@Uafinder can you recheck please?

**Comment by Uafinder** [comment]
Hmm... yeah, it looks good
