### ISSUE TITLE
Playing video for the first time causes error message

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#638]
After a video has been uploaded i.e. into a blog page, then you preview the page and click play, you get the below error:

![video](https://cloud.githubusercontent.com/assets/2201340/9402663/cdb6f340-4822-11e5-8055-a89330cf2f84.png)

If you refresh the page, then click play, the video broadcasts live and plays for the first time.

**Comment by bradmac** [comment]
Can you just let me know if you can reliably reproduce this error? Then we can sort it
