### ISSUE TITLE
Font color for price should be improved

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6380]
![image](https://user-images.githubusercontent.com/1945230/49588375-3757ff00-f96f-11e8-8899-32767b77c6df.png)
http://vladtest55eweb-vladtest55e.kademi-ci.co/vladtest55eweb-ecomstore/ip7000

**Comment by anhnt** [comment]
Done 
![image](https://user-images.githubusercontent.com/735555/49720483-726d7180-fc92-11e8-981a-046c255f07dd.png)

**Comment by Uafinder** [comment]
looks good
