### ISSUE TITLE
Cart icon and text should be same aligned as whole menu

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6381]
![image](https://user-images.githubusercontent.com/1945230/49588452-63738000-f96f-11e8-95b0-39cecd39609e.png)
http://vladtest55eweb-vladtest55e.kademi-ci.co/vladtest55eweb-ecomstore/ip7000

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/49720190-c2980400-fc91-11e8-809d-e43842aaf852.png)
 Done

**Comment by Uafinder** [comment]
looks good
