### ISSUE TITLE
Layout for checkout form bad a little (delete button not in place)

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6382]
![image](https://user-images.githubusercontent.com/1945230/49588508-8bfb7a00-f96f-11e8-8760-03663e2abdc7.png)
http://vladtest55eweb-vladtest55e.kademi-ci.co/vladtest55eweb-ecomstore/cart

**Comment by bradmac** [comment]
This layout problem occurs when the old and deprecated shoppingcart-lib is used:

![image](https://user-images.githubusercontent.com/826458/49612527-d7fafd00-fa09-11e8-8d9b-d68cd1a44fc0.png)

Note that these are required for Reward Store app, which is also now deprecated.

I've disabled these apps and the layout is correct:

![image](https://user-images.githubusercontent.com/826458/49612557-ed702700-fa09-11e8-9923-7101871de7da.png)

Please ensure you do not use KCom2 with reward stores. KCom2 now has its own components to support reward stores, so the Reward Store app is not needed anymore (although is still supported for existing clients)

**Comment by Uafinder** [comment]
Ok, looks good
