### ISSUE TITLE
KCom2: you may also like modal using incorrect image display function

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6384]
It uses a function called fill in. E.g. when your image is small or not square system tries to multiply it to fill a square.
![image](https://user-images.githubusercontent.com/1945230/49588843-76d31b00-f970-11e8-8481-05273cb4b093.png)
http://vladtest55eweb-vladtest55e.kademi-ci.co/vladtest55eweb-ecomstore/ip7000

**Comment by bradmac** [comment]
Please ensure the background does not repeat.

**Comment by anhnt** [comment]
Done

**Comment by Uafinder** [comment]
looks good
