### ISSUE TITLE
kCom2: multiply tax rules while click save more than once (same for shipping)

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6385]
![image](https://user-images.githubusercontent.com/1945230/49588937-c0236a80-f970-11e8-8be8-ea80b8cb3a1a.png)
![image](https://user-images.githubusercontent.com/1945230/49588947-c44f8800-f970-11e8-9cdd-521fb8a30339.png)
Click add tax rule, fill some settings, save, then edit something and save again and you will see more than one rule (which could be deleted only via file)
http://vladtest55e.admin.kademi-ci.co/websites/vladtest55eweb/version1/store-vladtest55eweb-ecomstore/#tax-tab

**Comment by bradmac** [comment]
Fixed

**Comment by Uafinder** [comment]
ok, looks better

**Comment by Uafinder** [comment]
Same issue with shipping providers
![image](https://user-images.githubusercontent.com/1945230/49791464-36411c00-fd39-11e8-9e16-dc73926e3a4a.png)
http://vladtest55h.admin.kademi-ci.co/websites/vladtest55hweb/version1/store-vladtest55hweb-ecomstore/#shipping-tab

**Comment by Uafinder** [comment]
Ok, looks good
