### ISSUE TITLE
kCom2: image alignment incorrect

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6386]
![image](https://user-images.githubusercontent.com/1945230/49589198-6d967e00-f971-11e8-8a53-b01ba1e507e2.png)
http://vladtest55eweb-vladtest55e.kademi-ci.co/vladtest55eweb-ecomstore/ip7000

**Comment by bradmac** [comment]
I think we should reduce or remove the top margin on the price under the picture, that gap is too large. And probably add some margin above the image.

**Comment by trungjc** [comment]
![screenshot_9](https://user-images.githubusercontent.com/704946/52766341-7edac580-3059-11e9-91d6-8ae621cce959.png)
![screenshot_10](https://user-images.githubusercontent.com/704946/52766342-7edac580-3059-11e9-82a2-dd0f4b56a9ad.png)

Update in 1.9.2

**Comment by Uafinder** [comment]
ok, looks good
