### ISSUE TITLE
manual payments: issue with invoice button

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6387]
![image](https://user-images.githubusercontent.com/1945230/49590477-aab03f80-f974-11e8-8811-651ee0e23144.png)
http://vladtest55eweb-vladtest55e.kademi-ci.co/vladtest55eweb-ecomstore/cart

**Comment by bradmac** [comment]
It wasnt a "button", just an image to indicate the payment type.

But has been removed now
![image](https://user-images.githubusercontent.com/826458/49613921-b7cd3d00-fa0d-11e8-8246-0d78cfdbd659.png)

**Comment by bradmac** [comment]
Note that manual payments app is **only for testing**

It is currently not intended for production usage for any client
