### ISSUE TITLE
KCom2: Component thumbnails

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6388]
First there are a bunch of thumb missed errors when accessing article edit page
http://vladtest55e.admin.kademi-ci.co/blogs/blog1/c19935/#activity-tab
![image](https://user-images.githubusercontent.com/1945230/49587401-602ac500-f96c-11e8-9221-78343582eddc.png)

**Comment by trungjc** [comment]
@bradmac The components, which inside website folder, will not be loaded in blog content editor. Should we move them to common folder ?
![screenshot_17](https://user-images.githubusercontent.com/704946/52846700-e3228580-313c-11e9-98cd-046a67398e7e.png)

![screenshot_18](https://user-images.githubusercontent.com/704946/52846751-fc2b3680-313c-11e9-96d5-912de8446187.png)

**Comment by bradmac** [comment]
Yep, good idea.

**Comment by trungjc** [comment]
Move kcom2 conponents in website to common folder

**Comment by Uafinder** [comment]
kcom2 fixed
