### ISSUE TITLE
Clear time value when saved

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#639]
When a use un-ticks the timer check box, we need to clear the value when it is saved.  If this is not done, and if the user clicks save on another tab, the timer gets activated again.

![timer](https://cloud.githubusercontent.com/assets/2201340/9421753/ecd74c80-48bc-11e5-84e8-0f906e34b465.png)

**Comment by tuzzmaniandevil** [comment]
@paddyow When the checkbox is unticked then the user saves this already clears the timer time for that job so the timer is disabled.

**Comment by tuzzmaniandevil** [comment]
The input defaults to 12:00AM when to value is specified by the user or no value it saved.
