### ISSUE TITLE
Issue with loyalty points - points disappear

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6391]
![image](https://user-images.githubusercontent.com/1945230/49646902-48fddd00-fa29-11e8-939a-00f648644726.png)
Push next
![image](https://user-images.githubusercontent.com/1945230/49646921-54e99f00-fa29-11e8-9824-ab52049129c0.png)
http://vladtest55fweb-vladtest55f.kademi-ci.co/vladtest55fweb-ecomstore/cart

**Comment by bradmac** [comment]
Looks ok now, probably resolved by https://github.com/Kademi/kademi-dev/issues/6394

**Comment by Uafinder** [comment]
yup, looks fine now
