### ISSUE TITLE
EDM js error in console

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6392]
When open EDM
http://vladtest55f.admin.kademi-ci.co/funnels/first-journey/version1/emailAction-c47504/#message-tab
![image](https://user-images.githubusercontent.com/1945230/49649870-1bb62c80-fa33-11e8-90ed-bc4f88113e05.png)

**Comment by bradmac** [comment]
Mostly fixed in another issue, but i've seen another JS init error..

**Comment by Uafinder** [comment]
Looks good
