### ISSUE TITLE
EDM error when edit image container

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6393]
![image](https://user-images.githubusercontent.com/1945230/49650093-d3e3d500-fa33-11e8-9138-6f8cd15d2500.png)
http://vladtest55f.admin.kademi-ci.co/funnels/first-journey/version1/emailAction-4b144d/#message-tab

Also this one
![image](https://user-images.githubusercontent.com/1945230/49650172-10173580-fa34-11e8-97af-0c62fc31851a.png)

**Comment by bradmac** [comment]
@anhnt this one's for you! I cant see whats going on, maybe something to do with keditor's iframe?

**Comment by anhnt** [comment]
Fixed in edmEditor-lib 1.2.4

**Comment by Uafinder** [comment]
Ok, looks good
