### ISSUE TITLE
Checkout Js error while accessing payment details

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6394]
![image](https://user-images.githubusercontent.com/1945230/49650488-fde9c700-fa34-11e8-978b-7f297580a32b.png)
http://vladtest55fweb-vladtest55f.kademi-ci.co/vladtest55fweb-ecomstore/cart

**Comment by bradmac** [comment]
Fixed. Required KCom2 1.4.7

**Comment by bradmac** [comment]
Updated the CI account above:
http://vladtest55fweb-vladtest55f.kademi-ci.co/vladtest55fweb-ecomstore/cart

**Comment by Uafinder** [comment]
looks good
