### ISSUE TITLE
Attachment is not a mandatory field (but validation works)

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6395]
![image](https://user-images.githubusercontent.com/1945230/49650689-c92a3f80-fa35-11e8-9f53-a8bb1fe11f5b.png)
http://vladtest55f.admin.kademi-ci.co/funnels/first-journey/version1/emailAction-c47504/#summary-tab

**Comment by bradmac** [comment]
Fixed

**Comment by Uafinder** [comment]
Looks good
