### ISSUE TITLE
KTheme: input text colour is too light

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6399]
The text colour for text in an input is very light, and seems to be the same as placeholder text, so a user cant easily tell what fields have been entered and what hasnt.

Please make the input text colour (not placeholder) darker.

![image](https://user-images.githubusercontent.com/826458/49707045-549e0d80-fc8e-11e8-8d00-f16879d58aea.png)

**Comment by Uafinder** [comment]
Looks good
