### ISSUE TITLE
Improve storeProductListEDM component

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6400]
- when not configured (ie store is not selected) it should display representative content and layout. Currently just says "Sorry, we couldnt find any products for you"
- the layout appears to be broken:

![image](https://user-images.githubusercontent.com/826458/49706980-0983fa80-fc8e-11e8-85d4-1f6bcd25b574.png)

**Comment by anhnt** [comment]
there is new component called kcom2ProductListEDM under KCom2 category

![image](https://user-images.githubusercontent.com/735555/49792211-baf55f80-fd64-11e8-8b65-35871b943c15.png)

**Comment by Uafinder** [comment]
Hmmm... i don't think that product called "please select store" is good (appears when no store selected)
![image](https://user-images.githubusercontent.com/1945230/49802955-246e7180-fd57-11e8-8423-de31ecb0ed06.png)

Also, when grid layout is selected - it says View detail for each product description, when list layout appears - it says read more... which is not good
![image](https://user-images.githubusercontent.com/1945230/49803047-6a2b3a00-fd57-11e8-89b5-7ff3f7b47300.png)
http://vladtest55hh.admin.kademi-ci.co/funnels/first-journey/version1/emailAction-4e3b1f/#message-tab

**Comment by bradmac** [comment]
> Hmmm... i don't think that product called "please select store" is good (appears when no store selected)

Thats fine, its indicating to the user they need to configure the component

> Also, when grid layout is selected - it says View detail for each product description, when list layout appears - it says read more... which is not good

Thats fine, its not worth keeping this issue open for.
