### ISSUE TITLE
EDM upload image to regular plaholder issue

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6402]
![image](https://user-images.githubusercontent.com/1945230/49733588-93ca5f80-fc8a-11e8-9673-b0c98cf0e503.png)
http://vladtest55g.admin.kademi-ci.co/funnels/first-journey/version1/emailAction-d612ca/#message-tab
Click on some folder and try to upload an image

**Comment by bradmac** [comment]
That is correct. You're attempting to upload an image to an ecommerce store, which isnt possible.

The error message should be better, but the fact that you cant upload is correct and not a bug.

**Comment by Uafinder** [comment]
Ok, got it
