### ISSUE TITLE
kcom2: weird layout for products

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6403]
![image](https://user-images.githubusercontent.com/1945230/49733766-12270180-fc8b-11e8-8232-5f86ff0b1c7b.png)
http://vladtest55g.admin.kademi-ci.co/websites/vladtest55gweb/version1/store-vladtest55gweb-ecomstore/?goto

**Comment by bradmac** [comment]
@anhnt i think we need to be able to fix product height so they're all consistent.

Maybe have a default height which allows room for 3 lines of text, but also make this a setting on the component?

**Comment by anhnt** [comment]
heights are all equal now

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/49865237-fe200300-fe36-11e8-8778-ba8d47bf27c6.png)
![image](https://user-images.githubusercontent.com/735555/49865246-06783e00-fe37-11e8-8dd3-7c44ea404586.png)

**Comment by Uafinder** [comment]
Looks good

**Comment by bradmac** [comment]
This works for the first page of products, but when another page is laoded the layout is bad:

Resizing the screen causes the layout to be corrected

![image](https://user-images.githubusercontent.com/826458/50938184-f27a3780-14db-11e9-889a-5e6c2cd2167b.png)

**Comment by bradmac** [comment]
Also, it looks as though when no sort order is selected in component settings, no sort order is applied.

I think default behaviour should be:
- if no search words, sort by position
- if search words are provided, do not set a sort field so relevancy is applied (this is current behaviour)

**Comment by anhnt** [comment]
> This works for the first page of products, but when another page is laoded the layout is bad:

Fixed

**Comment by anhnt** [comment]
>I think default behaviour should be:

> * if no search words, sort by position
> * if search words are provided, do not set a sort field so relevancy is applied (this is current behaviour)

Default sort by setting is now `position`
When has search word, sort by field setting will be removed

**Comment by anhnt** [comment]
requires kcom 1.9.5

**Comment by Uafinder** [comment]
Looks good
