### ISSUE TITLE
Ability to change the 'wall' a post is attached to

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6407]
Required for vaya

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/49906871-9ae6ad00-fed8-11e8-88f2-0e767991f94d.png)

**Comment by bradmac** [comment]
@anhnt you can please finish this off by making the post detail page?

See forums.managePost.html

There is a controller which will simply databind to the Post. See ManagePostPage line 47

Note that this page will be used for the 3 types of Post - Comment, ForumPost and ForumReply, and they have different fields.

This form should
- allow changing the wall entity (use entity selector, either profile or org)
- editing the comment text ("notes" property)

**Comment by anhnt** [comment]
@bradmac i created the form which posts
- wallEntityId as kademi id of either org or profile
- notes

**Comment by bradmac** [comment]
@anhnt that is now saving.

However, the current value isnt being displayed in the entity select box.

Also, can you display this information on the page (non editable)
    private Website website;
    private Profile poster;
    private Date postDate;
    private Integer votesTotal;
    private List<Vote> votes;
    private List<PostReport> postReports;
    private Post parent;
    private String relatedAppName;
    private String relatedId;

**Comment by anhnt** [comment]
Done, tested here http://vayability.admin.kademi-ci.co/managePosts/18339410

**Comment by anhnt** [comment]
https://github.com/Kademi/kademi-dev/commit/46d4ef45f064b0c9801058bcc600db1a53420055
https://github.com/Kademi/kademi-dev/commit/0c64e6c524fc97061dfcd5949f7a280ba50a32b4
https://github.com/Kademi/kademi-dev/commit/ad605dc5473b374e3ddffba9c5ae3797a2240ec4
https://github.com/Kademi/kademi-platform/commit/d3cd9f8adbf16db8f3213a41eb942c722bc642c2

**Comment by bradmac** [comment]
OK, i think that might be because we're not updating the wall index.

**Comment by bradmac** [comment]
I've added re-indexing logic.

When the post is assigned to profile wall userqa04 it does not display on kademiqa68 (ie when logged in as that user)

However, when the post is assigned to profile wall kademiqa57 it does appear when logged in as kademiqa68

My guess is the logic of the wall on the profile page is to include posts from all cohorts, and users in cohorts, that the curretn user is associated with.

**Comment by Uafinder** [comment]
Ok, looks good
