### ISSUE TITLE
Unable to update contact fields in KCRM

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#6408]
http://kcrm-kademi.kademi.us/leads/65213096/?view=contact

Entering first name or last name, then clicking save does not update the contact.

![image](https://user-images.githubusercontent.com/2201340/49767814-2a039180-fd2e-11e8-84be-6127bedc24ef.png)

**Comment by bradmac** [comment]
This problem occurs when there is no profile linked to the lead, and no email address has been entered

**Comment by bradmac** [comment]
requires leadman-lib 3.3.0

**Comment by Uafinder** [comment]
If i correctly understand a case:
- Create a lead without entering a user connected
- go to a lead and try to enter some contact data
- push save
- refresh
http://vladtest55jjjweb-vladtest55jjj.kademi-ci.co/leads/18336673/?view=contact
If so, it doesn't work
![image](https://user-images.githubusercontent.com/1945230/49868144-344c8b00-fe15-11e8-996e-9b98e49e8502.png)
![image](https://user-images.githubusercontent.com/1945230/49868160-3b739900-fe15-11e8-9a09-07e6ae09232e.png)
after refresh
![image](https://user-images.githubusercontent.com/1945230/49868171-41697a00-fe15-11e8-957c-674b5ace11de.png)

**Comment by bradmac** [comment]
I just added some logging, and then checked and seems ok now.

![image](https://user-images.githubusercontent.com/826458/49898987-58fd3d00-febf-11e8-9648-bf454d7c3371.png)

**Comment by Uafinder** [comment]
ok, it works partially
some fields are saving, some are not
look here
i had an empty contact fields
then i enter some values
![image](https://user-images.githubusercontent.com/1945230/49947494-10af4080-fefa-11e8-9df3-0a2337c13349.png)
and push save
and two fields become empty after refresh
![image](https://user-images.githubusercontent.com/1945230/49947532-27ee2e00-fefa-11e8-8510-c5602cbda9e2.png)
http://vladtest55kkweb-vladtest55kk.kademi-ci.co/leads/18341099/?view=contact

**Comment by bradmac** [comment]
> and two fields become empty after refresh

Fixed

**Comment by Uafinder** [comment]
Yup, looks good
