### ISSUE TITLE
user profile kcom order is not clickable 

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6410]
I think it should have a link to an appropriate order
cursor changing form to a hand (clickable) but no link connected
![image](https://user-images.githubusercontent.com/1945230/49792146-a603d680-fd3a-11e8-930f-f4dd74f4ab8d.png)
http://vladtest55h.admin.kademi-ci.co/manageUsers/18331472/#ecommerceAppTab-tab

**Comment by anhnt** [comment]
done

**Comment by Uafinder** [comment]
Looks good
