### ISSUE TITLE
Dependencies for kcom2

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6414]
When you install KCom2 one lib is not installing automatically
bootstrap-upcrop-image-lib
Should be added as dependency
![image](https://user-images.githubusercontent.com/1945230/49801420-d0618e00-fd52-11e8-844b-b4f97aac507b.png)
http://vladtest55h.admin.kademi-ci.co/websites/vladtest55hweb/version1/#panel_apps-tab

**Comment by bradmac** [comment]
> Should be added as dependency

The reason for it displaying is because it is a dependency of user-lib. But new dependencies arent (currently) installed when you apply updates.

So i think the real problem is that something is depending on an old version of user-lib

**Comment by bradmac** [comment]
I've updated a bunch of dependencies which should solve the problem for fresh accounts

**Comment by Uafinder** [comment]
Looks good
