### ISSUE TITLE
Orders EDM component not showing brief sample when edit component

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6416]
With brief selected
![image](https://user-images.githubusercontent.com/1945230/49866507-a66ea100-fe10-11e8-819a-6f468d646ba5.png)
Without brief selected
![image](https://user-images.githubusercontent.com/1945230/49866539-b8504400-fe10-11e8-9f15-8cdd9cc45655.png)
Nothing changed
http://vladtest55jj.admin.kademi-ci.co/funnels/first-journey/version1/emailAction-ccf745/#message-tab

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/49915607-09237380-fec9-11e8-8bdc-fe140d13bcd8.png)

**Comment by Uafinder** [comment]
Yup, looks good
