### ISSUE TITLE
Bunch errors when accessing products page

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6417]
http://vladtest55jj.admin.kademi-ci.co/products/18335671/#panel_details-tab
![image](https://user-images.githubusercontent.com/1945230/49868426-0fa4e300-fe16-11e8-96c8-71934ff49e0c.png)

**Comment by anhnt** [comment]
Hey Vlad,

These are component thumbs missing of Kcom2 app. See here
https://github.com/Kademi/kademi-dev/issues/6388

**Comment by bradmac** [comment]
Closing this issue as duplicate of #6388
