### ISSUE TITLE
Allow selecting users, orgs, groups and org types on blogs and emails - Part 1

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6420]
required for Vaya
Amber want to show some blog articles to one org and some others to another... we could control appear only by user group, not by org

From: Amber Pye [mailto:apye@vayapath.com] 
Sent: Wednesday, December 12, 2018 1:45 AM
To: Vlad Bayrak <vlad@kademi.co>; Brad McEvoy <brad@kademi.co>
Cc: Tiffany Hiscock <tmhiscock@vayapath.com>
Subject: Resources

Hi Vlad, 

In the resources section we have added blogs/articles to habit track groups.  There are a couple articles that should only show for Gilead.  How do we make articles/blogs visible to only specific company’s and habit tracks? 

Thanks, Amber

**Comment by bradmac** [comment]
OK, seems reasonable

**Comment by bradmac** [comment]
@anhnt as discussed please create a jquery plugin which provides a UI for selecting (and deselecting)
- individual users
- user groups
- individusal orgs
- org types 

This plugin will have options for which types to support, and callbacks for saving changes

This will initially be used in group emails and blog articles.

**Comment by anhnt** [comment]
i added plugin called jquery-kselector-lib and applied to group email page

![image](https://user-images.githubusercontent.com/735555/50094085-edabc600-0244-11e9-8bf0-29799f8d6c73.png)


@bradmac please add backend support for org types and individuals recipients

**Comment by bradmac** [comment]
@anhnt i think we need that to be a bit tidier
- have a single list of items, not in seperate sections. Use icons to indicate the type (user, org, group, orgtype) and colour to indicate mode (inclusion vs exclusion)
- orgs and profiles should be added together, just use entity finder
- groups and orgtypes should be handled seperately
- just have a single button to add an item. This will open a modal with 3 tabs to search for entities, groups, and org types. There should be a selection for whether this is an inclusion or exclusion

**Comment by anhnt** [comment]
https://github.com/Kademi/kademi-dev/commit/69e93b00bb112a4e795bc5c4fac7e963486be5d4
https://github.com/Kademi/kademi-dev/commit/13c28a3daf874f4d99e5d33bcc1d66be10003ccd

![image](https://user-images.githubusercontent.com/735555/50139511-8ccbce80-02d4-11e9-83c2-91bdff5d4921.png)

![image](https://user-images.githubusercontent.com/735555/50139528-95240980-02d4-11e9-9834-43132a190aa3.png)

sample code

```
$('.kselector').kselector({
                    dataSource: [
                        {type: 'org', filterType: 'inclusive', id: 1, text: 'Org1'},
                        {type: 'user', filterType: 'inclusive', id: 2, text: 'Anh Nguyen'},
                        {type: 'group', filterType: 'inclusive', id: 3, name: 'learners', text: 'Learners'},
                        {type: 'group', filterType: 'exclusive', id: 4, name: 'learners', text: 'Learners'},
                        {type: 'orgType', filterType: 'exclusive', id: 5, name: 'type1', text: 'Type 1'},
                    ],
                    onSelected: function (data) {
                        if (data.type == 'org'){
                            // save org
                        } else if (data.type == 'group'){
                            // save group
                        } else if (data.type == 'orgType'){
                            // save org type
                        } else if (data.type == 'user'){
                            // save user
                        }
                    },
                    onRemoved: function (data) {
                        
                    }
                });

**Comment by anhnt** [comment]
note that i pushed the code to this branch https://github.com/Kademi/kademi-dev/tree/kselector

**Comment by bradmac** [comment]
@anhnt I've integrated with the backend to save, but a couple of things for you..
- clicking the X to remove isnt working, it just links to the page
- when adding an item its being saved, but not added to the displayed list in the UI. I think the plugin can handle this rather then doing a reloadfragment .. that ok?

**Comment by anhnt** [comment]
@Uafinder this is done but in different branch so we will test once this is merged to master. @bradmac will merge

**Comment by bradmac** [comment]
This is working now for group emails for orgs + groups only
![image](https://user-images.githubusercontent.com/826458/50317673-b299e300-0521-11e9-8fb4-414947ebbf84.png)

@anhnt as above please update the plugin so the support types can be configured, and then the plugin only allows selecting those types.

**Comment by bradmac** [comment]
@anhnt also, i noticed that removing only works once, then after that its just a link. So i think you need to re-initialise event handlers after updating the UI

**Comment by bradmac** [comment]
Merged to master

**Comment by anhnt** [comment]
> please update the plugin so the support types can be configured, and then the plugin only allows selecting those types.

Done
```
$('.kselector').kselector({
        dataSource: selectors,
        types : ['group', 'org'],
        ....
```

>instead of using a modal, it would be better for the add selection UI to be a panel

Done

Applied to group email page

![image](https://user-images.githubusercontent.com/735555/50389879-5540a480-0762-11e9-9eb0-82bf4613514a.png)

**Comment by anhnt** [comment]
Done for blog article and fixed some bugs on that page

![image](https://user-images.githubusercontent.com/735555/50390956-60023600-0770-11e9-9416-604393364b2e.png)

**Comment by Uafinder** [comment]
As discussed with @anhnt, backend should be upgraded first, so reassign to @bradmac

**Comment by bradmac** [comment]
@Uafinder and @anhnt this issue is "part 1" which is to integrate the selector framework with the existing functionality. This issue is not to add selection options, that is covered in part2 and part3

**Comment by bradmac** [comment]
@anhnt please fix..
![image](https://user-images.githubusercontent.com/826458/50665065-2b199d00-1014-11e9-8bc1-1545860d5e1d.png)

**Comment by bradmac** [comment]
@anhnt also there is an error on the group email page when sending, its checking for selected recipients..

![image](https://user-images.githubusercontent.com/826458/50670302-8dcc6200-102f-11e9-94bb-8b79caa51855.png)

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/50671341-d66e2600-1003-11e9-928d-e1d7a17d6934.png)

Done

**Comment by anhnt** [comment]
Also fixed email group page for that validation msg

**Comment by anhnt** [comment]
requires kselector 1.0.1 and email-lib 1.1.3

**Comment by bradmac** [comment]
Tiffany has reported an error affecting vayabiulity prod:
![image](https://user-images.githubusercontent.com/826458/50790103-dda67400-1322-11e9-902e-805252386ce7.png)

This stack trace:
```
class java.lang.UnsupportedOperationException::Not supported yet.
- io.milton.cloud.server.db.utils.UserDao.toItemIds(UserDao.java:1123)
- io.milton.cloud.server.db.utils.UserDao.selectorTypeListMatches(UserDao.java:1107)
- io.milton.cloud.server.db.utils.UserDao.selectorsMatch(UserDao.java:1097)
- io.milton.cloud.server.db.utils.UserDao.selectorsMatch(UserDao.java:1081)
- io.milton.cloud.server.manager.UserManager.selectorsMatch(UserManager.java:496)
- com.fuselms.apps.blogs.BlogArticleFolder.isInTargetGroup(BlogArticleFolder.java:666)
- com.fuselms.apps.blogs.BlogFolder.getArticles(BlogFolder.java:586)
- com.fuselms.apps.blogs.BlogFolder.getArticles(BlogFolder.java:551)
- com.fuselms.apps.blogs.BlogFolder.getArticles(BlogFolder.java:522)
- com.fuselms.apps.blogs.BlogsFolder.getArticles(BlogsFolder.java:258)
```

**Comment by bradmac** [comment]
Fixed, requires platform update.

**Comment by Uafinder** [comment]
Looks good

**Comment by Uafinder** [comment]
Well, weird thing spotted
![image](https://user-images.githubusercontent.com/1945230/50907942-3d8b4080-1431-11e9-94d0-88bb593f8484.png)
http://vladtest55x.admin.kademi-ci.co/groupEmails/18503722/#send-tab
![image](https://user-images.githubusercontent.com/1945230/50907952-45e37b80-1431-11e9-8db3-d10fd29d7842.png)

**Comment by bradmac** [comment]
I just clicked "Send" and that sent ok.

I know this problem did previously exist and was fixed, so possibly was a caching thing.

**Comment by Uafinder** [comment]
Yup, looks fine
