### ISSUE TITLE
Add logout button to permission denied page

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6421]
Currently when the permission denied page is shown there is no logout button, so users are forced to clear their cookies if they need to login with different credentials.

Please add a logout button to the admin and front end pages displayed when permission is denied.

![image](https://user-images.githubusercontent.com/826458/49896228-99f15380-feb7-11e8-8f89-4cbb0f4a5e68.png)

**Comment by anhnt** [comment]
Done

![image](https://user-images.githubusercontent.com/735555/49916965-c618ce80-fecf-11e8-9b07-1a521abe0412.png)


![image](https://user-images.githubusercontent.com/735555/49916971-cb761900-fecf-11e8-9cdb-3f6971e008a4.png)

**Comment by Uafinder** [comment]
Looks good
