### ISSUE TITLE
KPIs: New component to show list of previous results

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6423]
- for the current user, find all KPIs available 
- for each available KPI, show a row with for each assessed result
- columns should include normal kpi result stuff, ie achieved value, target value, achieved level, etc
- have an option to show results for current user only, or for all users. Note that if current user, if the current page is a lead or profile page the profile on that page should be considered the current user. This is show we can add this component to the lead page to see the results for a different user

**Comment by anhnt** [comment]
Done, component called KPI previous results

**Comment by Uafinder** [comment]
Looks good
