### ISSUE TITLE
Journey builder: Update the decision action to have default rules

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6424]
If a decision node has an output link to another node, but that link has no rules associated with it, the journey cannot be parsed and several errors occur in the editor.

```
        {
            "decision": {
                "nodeId": "decision-074a1e",
                "nodeType": "decision",
                "x": 30,
                "y": 560,
                "choices": {
                    "taskGoal-ed1956": {}
                },
                "nextNodeId": "end-aa27c4",
                "title": "Check Happy/Sad"
            }
        },
```

results in this error:

```
WARN - com.fuselms.apps.funnels.FunnelCache  - Could not load mappings from repo=checkout branch=version1 path=/funnel.json
WARN - com.fuselms.apps.funnels.FunnelCache  - Mapping exception
com.fasterxml.jackson.databind.JsonMappingException: Unexpected token (END_OBJECT), expected FIELD_NAME: need JSON String that contains type id (for subtype of com.fuselms.apps.funnels.Expression)
 at [Source: {
```

To prevent this from happening please update the decision action handler so that a decision choice gets a default rule of true == false

![image](https://user-images.githubusercontent.com/826458/49915803-5836cc00-fefc-11e8-9250-65b436fa397d.png)

Add validation so if the user attempts to save without any rules that will be rejected.

**Comment by anhnt** [comment]
Fixed

**Comment by Uafinder** [comment]
Looks good
