### ISSUE TITLE
Hello world appears in EDM

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6425]
![image](https://user-images.githubusercontent.com/1945230/49931179-f744cf00-fece-11e8-8436-322a428b43f3.png)
http://vladtest55k.admin.kademi-ci.co/funnels/first-journey/version1/email1/#message-tab
And no possibility to delete it

**Comment by bradmac** [comment]
oops

**Comment by anhnt** [comment]
cant find it anywhere neither java nor frontend :-)

**Comment by Uafinder** [comment]
Looks good now

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/50217190-b8ac8a00-0390-11e9-90f2-b1e818192c9b.png)
http://vladtest55o.admin.kademi-ci.co/funnels/journey1/version1/email1/#message-tab
I think it appears when you install Kleadman app

**Comment by bradmac** [comment]
Not appearing now..

![image](https://user-images.githubusercontent.com/826458/50245700-06c89880-0438-11e9-928b-07f4ee5a170f.png)

**Comment by Uafinder** [comment]
Appears when you edit first email block for the first time... when you add some block , save and refresh it will not appear anymore...
