### ISSUE TITLE
KCom2: orders component fixups

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6430]
- create a keditor thumbnail
- fix error
- ALSO add a new page and component for viewing an order details

![image](https://user-images.githubusercontent.com/826458/50057947-940cb280-01d6-11e9-92cc-e00dce4c3590.png)

**Comment by bradmac** [comment]
New order history component:
![image](https://user-images.githubusercontent.com/826458/50059044-c45c4d00-01e6-11e9-9475-2e1b3d45ecb4.png)

**Comment by bradmac** [comment]
Order details and shipping status page:
![image](https://user-images.githubusercontent.com/826458/50059050-d63df000-01e6-11e9-9c6d-3f6d2c9d80e5.png)

**Comment by bradmac** [comment]
In the editor..
![image](https://user-images.githubusercontent.com/826458/50059070-17ce9b00-01e7-11e9-8629-4971f582e8d0.png)

**Comment by bradmac** [comment]
From client:
> How will this look when there are multiple items on the order?

See above on order details

> Each item on the order could potentially have a different Tracking Number, How is this handled?

Yes, each line item has its own status

> There is also the potential for items, which are shipped from a vendor other than Hinda, to be shipped but not have a tracking number. How is this handled?

as above, each line item can have its own tracking information

> Populating the trackingCode is a good idea, as long as multiple tracking numbers can be read easily.

As shown above, the tracking code can actually be a mixture of text and URLs, and URLs are converted to links to be clickable.

**Comment by bradmac** [comment]
Requires kcom2 1.5.2

**Comment by bradmac** [comment]
@anhnt can you backport these to rewardstore-lib? these are needed by a client who cant upgrade to kcom2.

we need the 2 components and also the website controller for the view-order page.

**Comment by anhnt** [comment]
Done

**Comment by anhnt** [comment]
Default to use Pts in rewardstore lib

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/50073351-eec00180-020a-11e9-91d0-1a7f92cb4a52.png)

**Comment by Uafinder** [comment]
Code appears when adding order details component
![image](https://user-images.githubusercontent.com/1945230/50079379-28d0d980-01f2-11e9-89fc-d0d82c49bd54.png)
http://vladtest55m.admin.kademi-ci.co/pages/vladtest55mweb/version1/?contenteditor=order.html

When user accessing order details page it gives not permission error
![image](https://user-images.githubusercontent.com/1945230/50079575-a1379a80-01f2-11e9-86dc-0cafe2464c5c.png)
http://vladtest55mweb-vladtest55m.kademi-ci.co/order.html
http://vladtest55mweb-vladtest55m.kademi-ci.co/view-order/18350045

**Comment by anhnt** [comment]
@bradmac please have a look at permission stuff

**Comment by faithtek** [comment]
This is now working in the Reward Store. Looks good guys. Great Job!!!

**Comment by bradmac** [comment]
@anhnt can you please copy this change over to rewardstore?

```
controllerMappings
        .websiteController()
        .enabled(true)
        .path('/view-order/(?<cart>[^/]*)')
        .isPublic(true)
        .addPathResolver('cart', 'resolveCartId')
        .addMethod('GET', 'renderOrderView')
        //.defaultView(views.templateView('/theme/apps/KCommerce2/viewOrder.html'))
        .build();

function renderOrderView(page, params) {
```

**Comment by bradmac** [comment]
Permissions updated in kcom2 1.5.5

**Comment by anhnt** [comment]
done, rewardstore-lib 1.7.1

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/50219193-117f2100-0397-11e9-9deb-607b9860169f.png)
Code appears when cart is in pending state (e.g. when cart is full but order not placed)
http://vladtest55oo.admin.kademi-ci.co/pages/vladtest55ooweb/version1/?contenteditor=index.html
uesr: adminqa

**Comment by bradmac** [comment]
> still no permissions to view order details

Fixed. Strange error with equality check in JS.

**Comment by Uafinder** [comment]
Ok, permissions are good
One thing
When order is not placed - e.g. cart is full but checkout is not completed:
1. Order details page leads to error
![image](https://user-images.githubusercontent.com/1945230/50328871-8bc9b580-04fd-11e9-83e0-f4ecc8e263cc.png)
![image](https://user-images.githubusercontent.com/1945230/50328877-8ff5d300-04fd-11e9-8b43-752224e64c31.png)
http://vladtest55ppweb-vladtest55pp.kademi-ci.co/

2. Order cost shows 0, i dunno if this is correct (also when order is not completed yet)
![image](https://user-images.githubusercontent.com/1945230/50328910-b0be2880-04fd-11e9-82f9-0d4fa3ff24c2.png)

**Comment by bradmac** [comment]
Shopping carts which havent been submitted should not be shown, because this component should only be showing orders, and if a cart hasnt been submitted it hasnt been ordered.

Fixed.

**Comment by bradmac** [comment]
Oops, i applied the update to rewardstore-lib/orderHistoryComponent

Applied that change to KCom2/orderHistoryEComComponent

**Comment by bradmac** [comment]
see KCom2 1.5.6

**Comment by bradmac** [comment]
Note that as above, pending orders should not be shown on this component. Only orders which have been placed.

**Comment by Uafinder** [comment]
Now it shows error
![image](https://user-images.githubusercontent.com/1945230/50482666-7f0efb00-09f0-11e9-8b5b-356245c09b51.png)
http://vladtest55rrr.admin.kademi-ci.co/pages/vladtest55rrrweb/version1/?contenteditor=orders.html

**Comment by bradmac** [comment]
should be fixed now

**Comment by Uafinder** [comment]
Well, error fixed

But now there is no info in orders table
![image](https://user-images.githubusercontent.com/1945230/50509941-66eeb880-0a90-11e9-9e64-d4bf1adec62d.png)
http://vladtest55sweb-vladtest55s.kademi-ci.co/orders.html

but here order completed
http://vladtest55s.admin.kademi-ci.co/shopping-carts/?fulfillment=&cartState=COMPLETED
![image](https://user-images.githubusercontent.com/1945230/50509963-7cfc7900-0a90-11e9-9a0f-ed4acd1b9210.png)

**Comment by bradmac** [comment]
Fixed

![image](https://user-images.githubusercontent.com/826458/50543027-00ec6780-0c2f-11e9-9975-2824ae91ba81.png)

**Comment by bradmac** [comment]
in kcom2 1.6.3

**Comment by Uafinder** [comment]
Finally looks good
