### ISSUE TITLE
KCRM: Remove redundant component

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6431]
We currently have 2 task list components which are almost identical,which could be confusing for users

- leadDashTasks
- taskList

Please ensure we only have a single component, which should be the latest one.

**Comment by anhnt** [comment]
taskList should be removed

**Comment by bradmac** [comment]
Also, please update the new component so the add lead panel is not shown for "unassigned tasks" mode:
![image](https://user-images.githubusercontent.com/826458/50065872-980ff300-021d-11e9-9eb6-afab7a8d6665.png)

**Comment by bradmac** [comment]
Also, when the user takes an incoming task, this will assign its lead to the current user. Since the list of leads is often on the same page, it needs to be refreshed. Please refresh the leads list after taking a task:

![image](https://user-images.githubusercontent.com/826458/50065999-300ddc80-021e-11e9-8f7b-b228cd4aff32.png)

**Comment by anhnt** [comment]
@bradmac taskList is declared in LeadManApp.java so if we remove this component there is old account like insured will be affected

**Comment by bradmac** [comment]
@anhnt ok, please move the new component to taskList, and then remove leadDashTasks

**Comment by anhnt** [comment]
done

**Comment by bradmac** [comment]
@Uafinder what you're seeing there is a portlet. You need to remove that container and add a new one.

**Comment by Uafinder** [comment]
Looks good
