### ISSUE TITLE
Video Content preview does not show when user add Video Component in Blog content editor

### ISSUE THREAD

**Issue by trungjc** [Kademi/kademi-dev#6433]
![screenshot_5](https://user-images.githubusercontent.com/704946/50077250-74957a00-0216-11e9-881a-d888baa5145f.png)

Video content preview is not stable, sometimes it show, sometimes it does not show in blog content editor

**Comment by anhnt** [comment]
fixed in https://github.com/Kademi/kademi-dev/issues/6453

**Comment by Uafinder** [comment]
Looks good
