### ISSUE TITLE
KPIs periods appears twice

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6435]
![image](https://user-images.githubusercontent.com/1945230/50092002-95a99b00-0215-11e9-9bd0-6106f240a270.png)
I noticed that when i push process KPI period it processing each period twice. Why?
http://vladtest55m.admin.kademi-ci.co/sales/data/kpis/kpi/#results-tab

**Comment by bradmac** [comment]
it shouldnt!

**Comment by bradmac** [comment]
OK, this occured because you processed KPI's, and then processed them again before the first was complete.

This KPI screen doesnt provide progress information.

I think we should just update the screen to click through to the main data series page so the user can use the normal screen:

1. 
![image](https://user-images.githubusercontent.com/826458/50182436-34e4a480-0374-11e9-9037-f8692fde5c7f.png)

2.
![image](https://user-images.githubusercontent.com/826458/50182474-48900b00-0374-11e9-9bc2-87d8aa244a70.png)

**Comment by anhnt** [comment]
done

**Comment by Uafinder** [comment]
1. http://vladtest55oo.admin.kademi-ci.co/sales/data/kpis/kpi-name/#results-tab
![image](https://user-images.githubusercontent.com/1945230/50220919-49d52e00-039c-11e9-8cda-f31c05aa8c39.png)
When you click on process KPI button you accessing page, process KPI section appears and then collapsing

2. http://vladtest55oo.admin.kademi-ci.co/sales/data/kpis/kpi-name/#results-tab
Then click process KPI
This page has incorrect link to data series details... 
![image](https://user-images.githubusercontent.com/1945230/50221183-09c27b00-039d-11e9-9fad-76d6cb318cb9.png)
![image](https://user-images.githubusercontent.com/1945230/50221190-0e872f00-039d-11e9-9c2e-0ac4720b7b67.png)

**Comment by bradmac** [comment]
> This page has incorrect link to data series details...

Fixed.

**Comment by bradmac** [comment]
> When you click on process KPI button you accessing page, process KPI section appears and then collapsing

@anhnt i'm seeing that too. Something is doing a reload without showProcess.

Can you please also refactor the inline JS code into a seperate JS file?

Also, i prefer to not have conditionally generated inline JS code. It gets messy and will be hard to handle as a dependency (when we move to dependencies).

Instead, just use pure JS and the URI.js to parse query string params.
```
                #if ($params.showProcess == "true")
                    $('.btn-process-select-kpi').trigger('click');
                    history.pushState(null, '', '/sales/')
                #end
```

**Comment by anhnt** [comment]
Done

**Comment by Uafinder** [comment]
looks good
