### ISSUE TITLE
Product Search on Kademi

### ISSUE THREAD

**Issue by yrsengar** [Kademi/kademi-dev#6436]
If you search for part of a product code no products show up.
Full code: 04-1063
Search for: 04-10

**Comment by bradmac** [comment]
Can you give me a link to where this problem occurs?

**Comment by yrsengar** [comment]
Oopps...
Here it is:
http://hazero-hazero.kademi.com.au/

**Comment by bradmac** [comment]
Fixed. 

Required kcom2 1.5.4

**Comment by Uafinder** [comment]
Can't find affected component
http://vladtest55nweb-vladtest55n.kademi-ci.co
Any of those not worked
![image](https://user-images.githubusercontent.com/1945230/50160966-28643b80-02e3-11e9-9f8f-ce5bbf347fc5.png)
this user
http://vladtest55n.admin.kademi-ci.co/manageUsers/18354394
help needed

**Comment by bradmac** [comment]
@Uafinder you're using the search component on the home page, so not within any store. That usage should be supported with a setting on the search component but currently isnt, ie so the user can select a store when the component isnt already inside a store (which is the default behaviour)

I'll create a separate issue to add that setting

however, to test this issue you should simply use the default store page:

to make things clearer i've removed the search components you added to the theme template.

1. From the store management page:
http://vladtest55n.admin.kademi-ci.co/websites/vladtest55nweb/version1/store-vladtest55nweb-ecomstore/#products-tab

2. Click view:
![image](https://user-images.githubusercontent.com/826458/50181135-796e4100-0370-11e9-87c2-78ceada7c263.png)

3. Then search for a full product code:
![image](https://user-images.githubusercontent.com/826458/50181254-b9cdbf00-0370-11e9-89bc-5d7520271ca4.png)

4. And also search for a partial product code to verify this change is correct:
![image](https://user-images.githubusercontent.com/826458/50181317-e1bd2280-0370-11e9-9141-782342dc9009.png)

**Comment by Uafinder** [comment]
Yup, looks fine
