### ISSUE TITLE
Feature products Component

### ISSUE THREAD

**Issue by yrsengar** [Kademi/kademi-dev#6437]
Feature products component was created by Kademi as a feature request. This component shows a list of products of a particular category from a selected catalog.

The component does not show products anymore.
just above the footer: http://hazero-hazero.kademi.com.au/

**Comment by bradmac** [comment]
@yrsengar that component was removed in this issue:
https://github.com/Kademi/kademi-dev/issues/6295

because its redundant, the standard component (storeProductList) does the same thing now.

**Comment by bradmac** [comment]
So please change to use storeProductList
