### ISSUE TITLE
cant upload photo when edit group email

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#6440]
It's ok when no file is selected
![image](https://user-images.githubusercontent.com/735555/50141853-24ccb680-02db-11e9-8635-ef5294f5aeee.png)

When a file is selected the form action url is wrong

![image](https://user-images.githubusercontent.com/735555/50141894-4168ee80-02db-11e9-8a9a-9a08e68007e3.png)

**Comment by Uafinder** [comment]
When file selected now error appears
![image](https://user-images.githubusercontent.com/1945230/50155862-da950680-02d5-11e9-85a3-d5266be0f488.png)
http://vladtest55n.admin.kademi-ci.co/groupEmails/18354733/edmeditor?fileName=index.html&useHash=true

**Comment by anhnt** [comment]
Looks ok to me 
![image](https://user-images.githubusercontent.com/735555/50159428-3e84f280-0309-11e9-823c-d3e9c7c9cd61.png)

**Comment by Uafinder** [comment]
1. Open upload window
![image](https://user-images.githubusercontent.com/1945230/50161062-6bbeaa00-02e3-11e9-836e-7e9c788d5e51.png)

2. Click on any image
![image](https://user-images.githubusercontent.com/1945230/50161076-75481200-02e3-11e9-8366-f85ae9947622.png)

3. click upload
![image](https://user-images.githubusercontent.com/1945230/50161095-7c6f2000-02e3-11e9-92c7-8b7d4508fe8b.png)

4. select image
![image](https://user-images.githubusercontent.com/1945230/50161120-8db82c80-02e3-11e9-9cb0-1e7549d46819.png)

5. error appears
![image](https://user-images.githubusercontent.com/1945230/50161146-9dd00c00-02e3-11e9-8fa9-ec62838dd84d.png)

**Comment by Uafinder** [comment]
It works
