### ISSUE TITLE
Search box not in line with other menu items

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6441]
![image](https://user-images.githubusercontent.com/1945230/50158416-c0aaf200-02dc-11e9-8a4f-1c78d6cedded.png)
http://vladtest55nweb-vladtest55n.kademi-ci.co/

**Comment by trungjc** [comment]
![screenshot_4](https://user-images.githubusercontent.com/704946/51834482-0d96d500-232d-11e9-8528-ea6556998289.png)

Update in bootstrap-base version 2.0.6

**Comment by Uafinder** [comment]
ok, looks good
