### ISSUE TITLE
KCRM: issue when check assigned to nobody tasks

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6442]
![image](https://user-images.githubusercontent.com/1945230/50159987-c6a2d200-02e0-11e9-8608-1effdc6acda2.png)
http://vladtest55nnweb-vladtest55nn.kademi-ci.co/tasks/?assignedTo=NONE
http://vladtest55nn.admin.kademi-ci.co/manageUsers/18355584/#summary-tab

**Comment by anhnt** [comment]
Done

**Comment by Uafinder** [comment]
Looks good
