### ISSUE TITLE
Error in search component

### ISSUE THREAD

**Issue by joelatfuel** [Kademi/kademi-dev#6443]
We are in the design phase with a new client; they are asking to add a blog search, but I cannot see an existing component. Can we please have one created?

**Comment by bradmac** [comment]
This is part of the standard search tool. Ie the normal content search components search page content and blog content.

Is that what you need?

**Comment by joelatfuel** [comment]
I added this component to our test website but encountered an error. The search result component does not have jQuery scope, so we get Uncaught ReferenceError: $ is not defined.

**Comment by bradmac** [comment]
> I added this component to our test website but encountered an error. 

OK, I'll update this issue to reflect the actual problem which is the standard search component not working..

**Comment by bradmac** [comment]
```
ReferenceError: $ is not defined[Learn More] blogs:229:5
<anonymous>
http://defaultcomponents-fueldemo.kademi.com.au/blogs/:229:5
```

**Comment by bradmac** [comment]
@anhnt please create a marketplace app KSearch which depends on both Search app and search-lib

**Comment by bradmac** [comment]
I can see the default searchResults page template needs to be updated to components

**Comment by bradmac** [comment]
Also, blog articles are not being indexed when published.

**Comment by bradmac** [comment]
So in summary..
@anhnt 
[ ] - create KSearch marketplace app
[ ] - create searchPage template in search-lib

@bradmac 
[ ] - ensure blog articles are updated in the index when published

**Comment by anhnt** [comment]
Done

**Comment by Uafinder** [comment]
Just one result text appears without search at all
![image](https://user-images.githubusercontent.com/1945230/50219439-e517d480-0397-11e9-87b0-53f8f9e21bc0.png)
http://vladtest55ooweb-vladtest55oo.kademi-ci.co/contentSearch

Content search doesn't work as case search, only a whole word - e.g. page word shows nothing, page1 shows ok.
![image](https://user-images.githubusercontent.com/1945230/50219607-75eeb000-0398-11e9-8646-bc63512fea18.png)
![image](https://user-images.githubusercontent.com/1945230/50219614-79823700-0398-11e9-9b45-808acbc86a67.png)

Blog articles showing by default without search something
![image](https://user-images.githubusercontent.com/1945230/50219899-4e4c1780-0399-11e9-99f9-fb1050463cad.png)
http://vladtest55ooweb-vladtest55oo.kademi-ci.co/contentSearch

**Comment by bradmac** [comment]
> Just one result text appears without search at all

I dont see that

![image](https://user-images.githubusercontent.com/826458/50247304-61fc8a00-043c-11e9-96e8-14913e06f0ae.png)

> Content search doesn't work as case search, only a whole word - e.g. page word shows nothing, page1 shows ok.

This is correct, we dont do prefix search, otherwise searching for "sea" would match "search" which would be incorrect.

> Blog articles showing by default without search something

Correct, the page displays initial pages (blogs and other pages)

![image](https://user-images.githubusercontent.com/826458/50247478-da634b00-043c-11e9-8815-a91d6b12158f.png)

**Comment by Uafinder** [comment]
Ok
