### ISSUE TITLE
Image size selection in email editing

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6444]
When selecting an image through the mselect browser, the full size image is loaded into the preview area. This should only load a medium sized image, eg 800x800

And images used in emails should either be sized automatically (ie selecting an appropriate alt-format) or allow the user to select a size.

**Comment by bradmac** [comment]
What i think is in mselect just default the altformat image size so large images arent loaded (its slow)

And in the photoEDM settings panel add a max size selection box, with options from altformat generation which will just append the alt format suffix to down size.

**Comment by bradmac** [comment]
@anhnt sound ok?

**Comment by anhnt** [comment]
Done, requires edmEditor-lib 1.2.5, mselect-lib 1.1.4, content-lib 1.5.1

However there is issue with static image which doenst get generated by alt-format

http://testkcom2.admin.kademi-ci.co/static/images/yenbai_vietnam.jpg/alt-640-480.png

Sample edm http://testkcom2.admin.kademi-ci.co/groupEmails/18356805/edmeditor?fileName=index.html&useHash=true

**Comment by bradmac** [comment]
the altformat only works for repo resources. We canput those sample images inside whichever lib uses them (eg edmeditor-lib or keditor-lib), in a location accessible from admin and website, and then change the sample path to it

eg /common/theme/apps/edmeditor-lib/samples/yenbai...

**Comment by anhnt** [comment]
thanks, that works

**Comment by bradmac** [comment]
Updated in 1.5.2

**Comment by bradmac** [comment]
Looks good now
![image](https://user-images.githubusercontent.com/826458/50247165-03371080-043c-11e9-8cd0-37ea1ce86694.png)

**Comment by Uafinder** [comment]
Yup, looks good
