### ISSUE TITLE
users manager page sorting by default weird

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6448]
http://vladtest55oo.admin.kademi-ci.co/manageUsers/
![image](https://user-images.githubusercontent.com/1945230/50221344-79386a80-039d-11e9-8a93-7a3088f3677a.png)

**Comment by bradmac** [comment]
Fixed.

The default sort order is surname, firstname, email

**Comment by Uafinder** [comment]
Looks good
