### ISSUE TITLE
editing course details problem

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#6449]
http://waysphone.admin.kademi.com.au/websites/test%20module/version1/programs/Test123/NS1/

- Cant upload to files system
- Uploaded to asset success but cant select
- Mselect modal doesnt show second time

**Comment by anhnt** [comment]
Fixed, now admin console is fully using ckeditor-lib instead of static version

**Comment by anhnt** [comment]
@Uafinder please test this today as Liam needs this tomorrow

**Comment by Uafinder** [comment]
When uploading to assets
![image](https://user-images.githubusercontent.com/1945230/50285836-15c63f80-0466-11e9-9b6e-8ae4be8633c5.png)
http://vladtest55pp.admin.kademi-ci.co/websites/vladtest55ppweb/version1/programs/p1/c1/

**Comment by bradmac** [comment]
Fixed

![image](https://user-images.githubusercontent.com/826458/50311377-db15e300-0509-11e9-946f-e11f0f709dcf.png)

**Comment by anhnt** [comment]
Just fixed some issues with mtree and mselect

**Comment by Uafinder** [comment]
Ok, looks good
