### ISSUE TITLE
admin payment app invoices items are not saving

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#6450]
![image](https://user-images.githubusercontent.com/735555/50263034-82314680-0446-11e9-8c77-b943969dfbab.png)

**Comment by anhnt** [comment]
Fixed, applied hot patch to OTM account, needs to remove after next deployment http://otm.admin.kademi.com.au/repositories/otm-app/version1/admin/theme/apps/payment/#files-tab

**Comment by Uafinder** [comment]
Looks good now
