### ISSUE TITLE
Can't make search component work on homepage

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6452]
![image](https://user-images.githubusercontent.com/1945230/50293300-efab9a00-047b-11e9-9c3e-0d18cd0043fc.png)
![image](https://user-images.githubusercontent.com/1945230/50293348-0e119580-047c-11e9-8433-f557ddf0f4ca.png)
http://vladtest55pp.admin.kademi-ci.co/pages/vladtest55ppweb/version1/?contenteditor=index.html

**Comment by bradmac** [comment]
Seems to work fine. I just added a page to the website:
![image](https://user-images.githubusercontent.com/826458/50309533-085f9280-0504-11e9-88a3-e7d1f0f4db67.png)

And that appears correctly in search results:
![image](https://user-images.githubusercontent.com/826458/50309552-18777200-0504-11e9-9ad0-31876072f2d6.png)

**Comment by bradmac** [comment]
And searching for the blog article works:
![image](https://user-images.githubusercontent.com/826458/50309583-37760400-0504-11e9-89c9-6f5fa28caa6d.png)

**Comment by Uafinder** [comment]
Ahhr... i get how it works...
When you press enter in redirect you to content search page which is work well
