### ISSUE TITLE
Adding video component to blog article cause JS error

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6453]
![image](https://user-images.githubusercontent.com/1945230/50293433-3b5e4380-047c-11e9-9169-4f8835d92336.png)
http://vladtest55pp.admin.kademi-ci.co/blogs/blogsite1/article-3/#bodyCopy-tab

**Comment by bradmac** [comment]
ok, that didnt help. Over to you @anhnt

**Comment by bradmac** [comment]
Note that i dont see this error locally

**Comment by anhnt** [comment]
jwplayer doesnt support initialise player from element inside an iframe. So i build native video player fallback to preview video

![image](https://user-images.githubusercontent.com/735555/50326592-cba09500-051d-11e9-878a-a0d18e7f06c5.png)

**Comment by anhnt** [comment]
needs to fix audio component as well

**Comment by anhnt** [comment]
done, requires keditor 1.3.0, 6.12.0.4

**Comment by Uafinder** [comment]
Fine now
