### ISSUE TITLE
Invoice management page, total is not including tax

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6454]
http://otm.admin.kademi.com.au/invoices/137457930/

![image](https://user-images.githubusercontent.com/826458/50314492-e66e0c00-0513-11e9-9594-dc51e7e1c5ab.png)

Note that the generated PDF does show the correct total, so need to ensure any fix for the main issue does not result in correct values in the generated pdf

**Comment by bradmac** [comment]
Fixed

**Comment by Uafinder** [comment]
Looks good now
