### ISSUE TITLE
Uploading to course image doesn't show alt image but fullsize

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6458]
![image](https://user-images.githubusercontent.com/1945230/50338081-eb36be00-051b-11e9-8f8b-bfc88fb3e1e7.png)
http://vladtest55q.admin.kademi-ci.co/websites/vladtest55qweb/version1/programs/p1/c1/
SAme problem as here
https://github.com/Kademi/kademi-dev/issues/6444

**Comment by anhnt** [comment]
Looks ok to me with latest libs 

![image](https://user-images.githubusercontent.com/735555/50393143-b9755f80-0786-11e9-9598-55a7630963be.png)

**Comment by Uafinder** [comment]
fresh account - doesn't work!
http://vladtest55r.admin.kademi-ci.co/websites/vladtest55rweb/version1/programs/p1/c1/

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/50450371-1e37e200-0960-11e9-86cf-8973acc09236.png)

![image](https://user-images.githubusercontent.com/735555/50450373-2728b380-0960-11e9-9099-248e93cd513f.png)

Both files system and assets worked for me

**Comment by Uafinder** [comment]
1. Create a fresh account
2. Update libs
3. Install KLearning
4. Update libs
5. Create a program
6. Create a course
7. Try to edit a course and upload a large image

**Comment by anhnt** [comment]
cant reproduce again sorry

**Comment by Uafinder** [comment]
Well, looks fine now... anyway - it's very low priority
