### ISSUE TITLE
Video not loaded when flash disabled in jwplayer610

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#646]

**Comment by paddyow** [comment]
What was the outcome of this?
For example this video is not showing on my Android: http://www.kademi.co/blogs/kb/creating-your-first-email-trigger/

**Comment by bradmac** [comment]
I think we just couldnt reproduce it. Worked on my android phone and tablet.

If you can reliably reproduce the problem then give me a call and i'll have to watch the logs while you load it on your phone to try to see whats happening.
