### ISSUE TITLE
Add thumbs for search components

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6461]
![image](https://user-images.githubusercontent.com/1945230/50374743-f3fec100-05fb-11e9-8ce1-db6f21bcd26d.png)
http://vladtest55q.admin.kademi-ci.co/pages/vladtest55qweb/version1/?contenteditor=index.html

**Comment by trungjc** [comment]
![screenshot_12](https://user-images.githubusercontent.com/704946/52780740-7bf1cc00-307d-11e9-8fd9-ba782dba8a9d.png)

Search thumbs added in search-lib

**Comment by bradmac** [comment]
@trungjc please change the preview that says "search result bucket" to a thumbnail of the component

**Comment by trungjc** [comment]
![screenshot_1](https://user-images.githubusercontent.com/704946/52849861-a0fd4200-3144-11e9-8cd6-0094202c110c.png)

That image still is the thumbnail of searchResultBucketComponent

**Comment by trungjc** [comment]
Change search bucket preview image

**Comment by bradmac** [comment]
@trungjc please use an image which shows the user what this component is

**Comment by trungjc** [comment]
![screenshot_4](https://user-images.githubusercontent.com/704946/52999492-8da9e980-3458-11e9-8a28-c2ff52a892c4.png)
 
I think it is better than old image

**Comment by Uafinder** [comment]
Ok, looks good
