### ISSUE TITLE
Find expiring points api

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#6462]
Atm calling this api thru RewardStoreApp. Should be in PointsManager instead

**Comment by bradmac** [comment]
Done. Just changed pointsBucket from a string (name of the Reward) to a Reward

**Comment by trungjc** [comment]
`#set ($p = $services.pointsManager.findPointsBucket('trade'))`
`#set( $points = $services.pointsManager.findExpiring($p , $membership.org, $pEndDate ) )`

I am trying this one but It don't return anything. Is it correct?

**Comment by anhnt** [comment]
it worked as trung confirmed
