### ISSUE TITLE
Sort in Users & Groups

### ISSUE THREAD

**Issue by faithtek** [Kademi/kademi-dev#6464]
Sorting in Users & Groups > Users no longer works - System Wide

![image1](https://user-images.githubusercontent.com/7914822/50498802-a924e500-0a11-11e9-93c7-568ad0290033.png)

**Comment by anhnt** [comment]
@bradmac looks like ES server on this account is sick. I can see there are 169 records in profile index but there are just 3 in users table

**Comment by anhnt** [comment]
https://allstarrewards.admin.kademi.us/manageUsers/

**Comment by bradmac** [comment]
@anhnt no, its just that most users have been deleted (ie disabled)

![image](https://user-images.githubusercontent.com/826458/50543041-6e989380-0c2f-11e9-8ae3-e7fb29080aa1.png)

**Comment by bradmac** [comment]
So it looks like there is a real problem with sorting

**Comment by anhnt** [comment]
This bug occurs only on US instance. CI, Au and local look good. 
@bradmac please check if we need to deploy something

**Comment by bradmac** [comment]
Looks ok now in US prod
