### ISSUE TITLE
Missed icons for calendar month changing

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6468]
![image](https://user-images.githubusercontent.com/1945230/50517909-6fa8b400-0abb-11e9-820f-160b324d17e6.png)
http://vladtest55s.admin.kademi-ci.co/Calendars/rsvp/

**Comment by anhnt** [comment]
Fixed in new admin-lib version

**Comment by anhnt** [comment]
please update latest fontawesome-lib that contains fallback fix for this

**Comment by Uafinder** [comment]
Ok, cools
