### ISSUE TITLE
Code appears when accessing plain text editor

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6471]
![image](https://user-images.githubusercontent.com/1945230/50536087-6f5ef600-0b59-11e9-961c-fa163ace717a.png)
to reproduce click here
![image](https://user-images.githubusercontent.com/1945230/50536112-adf4b080-0b59-11e9-8282-24a9e3b487b4.png)
then click here
![image](https://user-images.githubusercontent.com/1945230/50536124-bc42cc80-0b59-11e9-9828-f9cb2935554f.png)
http://vladtest55ss.admin.kademi-ci.co/asset-manager/

**Comment by anhnt** [comment]
Fixed, code edit button should not be displayed when in creating new asset screen, at least asset should be saved then user can edit source code

**Comment by Uafinder** [comment]
Looks good
