### ISSUE TITLE
Edit image or video component cause error in console

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6472]
![image](https://user-images.githubusercontent.com/1945230/50536177-5145c580-0b5a-11e9-80a3-31c1e337e21a.png)
http://vladtest55ss.admin.kademi-ci.co/asset-manager/daee0dbd-7109-407f-a386-d4584d4593e9

I think that's results in filesystem inaccessible

**Comment by anhnt** [comment]
We should disable filesystem in asset content

**Comment by anhnt** [comment]
Fixed both text/html and text/edm asset

Requires `content-lib 1.5.6`, `contentEditor-lib 1.4.0`, `edmEditor-lib 1.2.7`, 'ckeditor-lib 4.5.6.8` and 'admin-lib 1.2.5`

**Comment by Uafinder** [comment]
Fresh account
Same for me
![image](https://user-images.githubusercontent.com/1945230/50688285-768c7500-102d-11e9-96c2-68fc65056919.png)
http://vladtest55u.admin.kademi-ci.co/asset-manager/new-text?format=text/html

**Comment by anhnt** [comment]
Looks ok after updating all libs

**Comment by Uafinder** [comment]
looks good
