### ISSUE TITLE
Kcom2: error in checkout page console  when user has not set up Address in profile page

### ISSUE THREAD

**Issue by trungjc** [Kademi/kademi-dev#6479]
Reference to https://github.com/Kademi/projects/issues/923

![screenshot_2](https://user-images.githubusercontent.com/704946/50556766-eccc6700-0d0f-11e9-98c1-ece0c03dd017.png)

If user ser has not set up Adress in profile page. Console will get error `TypeError: address is undefined`

btw, I think address should be saved (if empty) in checkout first time.

**Comment by bradmac** [comment]
I havent seen the error above yet, but i have seen this..

![image](https://user-images.githubusercontent.com/826458/50620724-0830af80-0f66-11e9-9382-43a253aa7b91.png)

**Comment by bradmac** [comment]
Fixed that error..

**Comment by bradmac** [comment]
> btw, I think address should be saved (if empty) in checkout first time.

Done

**Comment by bradmac** [comment]
> If user ser has not set up Adress in profile page. Console will get error TypeError: address is undefined

@trungjc I wasnt able to reproduce that error locally.

Can you provide a link to an account on kademi-ci where i can see it?

**Comment by trungjc** [comment]
Could you try it http://carters.admin.kademi-ci.co/manageUsers/17063383/# ?

**Comment by bradmac** [comment]
OK, the problem occurs when using the points only checkout form

See storeCheckout.js line 536
```
populateAddress(addresses[addresses.index[0]], addresses.readonly);
```

**Comment by trungjc** [comment]
Fixed. Waiting for deployment

**Comment by trungjc** [comment]
Updated

**Comment by Uafinder** [comment]
Looks good
