### ISSUE TITLE
Hinda: No longer available (NLA) products are still listed in store

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6482]
Example:
https://owenscorningbrookville.admin.kademi.us/shopping-carts/65137675/

**Comment by bradmac** [comment]
SKU: HN78915
Product: 17639698

**Comment by bradmac** [comment]
This product is no longer in the store:

![image](https://user-images.githubusercontent.com/826458/50613631-fa1d6780-0f42-11e9-9a8f-abd87e4d43a4.png)

**Comment by faithtek** [comment]
The Product was removed from the Kademi Store shortly after the order was processed with Hinda and discovered the product was no longer available at Hinda. That was to prevent anyone else from ordering it only to find out that it was no longer available.

**Comment by bradmac** [comment]
Troy's order also is no longer in the reward store:

![image](https://user-images.githubusercontent.com/826458/50613748-86c82580-0f43-11e9-911c-4c8ad3459a94.png)

**Comment by bradmac** [comment]
In order to investigate i need to be able to see the problem. Ie i need to be able to see a product which is in the reward store but is no longer available in Hinda.

Can you show me an example of that?

**Comment by faithtek** [comment]
We had this product error/show up inactive at Hinda yesterday. Product is still in the store.

https://asrjmsmucker.admin.kademi.us/shopping-carts/65422728/

**Comment by bradmac** [comment]
Thanks, i'll check

**Comment by bradmac** [comment]
I'm seeing this in the logs:
```
ERROR- 03-01-2019T22:13:47,701 - co.kademi.processors.ProductImportProcessor  - ProductImportProcessor.doProcess :: OrgId: 20019752 - CatalogId: 2218 - Exception code: 50000 - Message: There was an error on the server
```

That error message is being returned from Hinda

**Comment by bradmac** [comment]
hinda asked us to re-test. I've re-run the sync, which has completed without error:

![image](https://user-images.githubusercontent.com/826458/50718196-fc71f400-10f1-11e9-85a4-05e128cdf3b9.png)

**Comment by bradmac** [comment]
So 345 products were removed, but the specific product mentioned earlier was not removed:

https://asrjmsmucker.admin.kademi.us/products/46850351/#panel_details-tab

This is because that product is not in the "Hinda" category.

The sync process was updated a few months ago to allow hinda and non-hinda products together. To ensure the hinda sync process doesnt affect non-hinda products we use a hinda tracking category, and only products in that category are removed when they are not found in the hinda product list.
