### ISSUE TITLE
Users Can't Login to Nutra Blend Site

### ISSUE THREAD

**Issue by faithtek** [Kademi/kademi-dev#6483]
Don't know how to explain this one or what is causing the issue.

https://nutrablend.myrewardsstore.com/

Nutra Blend Users are not able to login in using the link above. I have not changed anything. And this seems to just have happened today or over the past few days. Users on other accounts are able to log into their respective sites.

Here's the admin location:

https://nutrablend.admin.kademi.us/

**Comment by bradmac** [comment]
Please provide an example user account that cant login (just a link to their profile page is fine)

And what you see when user attempts to login (eg error message?)

**Comment by bradmac** [comment]
Note that i've just checked this user - https://nutrablend.admin.kademi.us/manageUsers/51126394/#general-tab

Using 'login as' I'm able to login with no problem

**Comment by faithtek** [comment]
The "Login As" for everyone seems to work fine. But when I try to login using that user's credentials through the actual front end login page -- in other words, how the user would login -- I don't get an error or anything, but it won't continue logging the user in and just returns to the login page.

**Comment by bradmac** [comment]
I can see some JS errors which would explain that..

![image](https://user-images.githubusercontent.com/826458/50619093-12e64700-0f5c-11e9-82ba-fcbc3a120af0.png)

**Comment by bradmac** [comment]
Have you updated libs recently? If so i think probably conflicts with some of your overrides.

Note that it is expected that updated libs will sometimes be incompatible with overrides. So its important to always create a new version of your website, and then apply updates, and then test before publishing.

**Comment by faithtek** [comment]
I haven't changed anything in the past few days, which is when this started happening.

**Comment by bradmac** [comment]
I can see that all libs are up to date, but k-theme is an old version 1.6.5

![image](https://user-images.githubusercontent.com/826458/50619225-cc451c80-0f5c-11e9-9c20-4c0af79717f2.png)

The current versions of libs all depend on an update made to ktheme in 1.6.7:
https://github.com/Kademi/kademi-dev/issues/6176

So it looks like you updated libs but not the theme. This might have appeared to work for some time because users would have continued to use the cached JS.

**Comment by bradmac** [comment]
So just update to the latest ktheme.

**Comment by faithtek** [comment]
I tried that earlier and it didn't correct anything. I'm on Version 1.6.5 because the newest version breaks the rewards store.

**Comment by bradmac** [comment]
The apps you are using are not compatible with ktheme 1.6.5

**Comment by faithtek** [comment]
Ok. That did indeed fix the problem. My bad.
