### ISSUE TITLE
Container padding settings dont get re-displayed after saving

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6486]
Edited this page
http://kcom22w1-kcom22.kademi-ci.co/contenteditor?fileName=index.html

I've set padding of 50px on the container and saved, which you can see in source:
![image](https://user-images.githubusercontent.com/826458/50668464-fb729100-1023-11e9-9771-14c0affd1c21.png)

However, after reloading the page the padding does not display:
![image](https://user-images.githubusercontent.com/826458/50668477-0fb68e00-1024-11e9-8960-562fe91218e6.png)

**Comment by anhnt** [comment]
Fixed, requires contentEditor-lib 1.3.9

**Comment by Uafinder** [comment]
Fresh account - same for me
![image](https://user-images.githubusercontent.com/1945230/50688510-70e35f00-102e-11e9-8c48-58749eafd732.png)
http://vladtest55u.admin.kademi-ci.co/pages/vladtest55uweb/version1/?contenteditor=page1.html

**Comment by anhnt** [comment]
as discussed please try again. sync issue

**Comment by Uafinder** [comment]
Cools
