### ISSUE TITLE
kfeedbackapp: error JS when submitting feedback

### ISSUE THREAD

**Issue by trungjc** [Kademi/kademi-dev#6487]
Reference to https://github.com/Kademi/projects/issues/911

![screenshot_7](https://user-images.githubusercontent.com/704946/50673344-9876ff00-100f-11e9-9a44-b4422662a0c7.png)

Cause: Kfeedback js load before dependencies has loaded

**Comment by trungjc** [comment]
Fixed in kfeedbackapp version 1.3.0

**Comment by Uafinder** [comment]
Redirect doesn't work
![image](https://user-images.githubusercontent.com/1945230/50833758-f6cb1700-135a-11e9-81a5-214d2b515eb4.png)
http://vladtest55vv.admin.kademi-ci.co/manageUsers/19657/

**Comment by trungjc** [comment]
Please update kfeedback to version 1.3.1

**Comment by Uafinder** [comment]
Cools
