### ISSUE TITLE
Update Icons

### ISSUE THREAD

**Issue by trungjc** [Kademi/kademi-dev#6488]
Some Kcom2 components are using Bootstrap Glyphicon, it should be converted to font awesome icon

https://github.com/Kademi/projects/issues/925

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/50687880-8efb9000-102b-11e9-8e23-479acad47198.png)
Fresh account
http://vladtest55uweb-vladtest55u.kademi-ci.co/profile/

**Comment by trungjc** [comment]
Updated bootstrap-upcrop-image-lib

**Comment by Uafinder** [comment]
ok, looks good
