### ISSUE TITLE
Vaya CI JS errors

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6489]
http://vayability.admin.kademi-ci.co/manageApps/
![image](https://user-images.githubusercontent.com/1945230/50689269-a6d61280-1031-11e9-9323-0b3738f5ada1.png)

http://vayability.admin.kademi-ci.co/funnels/vayability-training-journey/version1/
![image](https://user-images.githubusercontent.com/1945230/50689290-ba817900-1031-11e9-8b28-e9df2416f380.png)

**Comment by anhnt** [comment]
Fixed by updating all libs

**Comment by Uafinder** [comment]
Ok
