### ISSUE TITLE
Move admin resources to repos

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6491]

**Comment by bradmac** [comment]
There are still a lot of dependencies on resources in /static/

Eg admin-lib is using moment js files in static. Remove them and add a dependency to moment-lib

And please update to use existing libs where we have them, or create new libs (eg kademi-msg should be a lib)

The end result should be that nothing in admin depends on resources in /static

BUT do not remove anything in static, because we still have customer sites which use those resources

**Comment by anhnt** [comment]
moved to libs, needs to recheck on whole admin screens..

**Comment by anhnt** [comment]
@Uafinder please test if there is any js error

**Comment by Uafinder** [comment]
http://vladtest55yy.admin.kademi-ci.co/manageContacts/
![image](https://user-images.githubusercontent.com/1945230/51029889-5a925180-15a0-11e9-8da4-8a688a91fd02.png)

**Comment by anhnt** [comment]
Fixed in contactus-lib 1.1.2

**Comment by Uafinder** [comment]
Looks good
