### ISSUE TITLE
Kcom2: Add decimal number place to components

### ISSUE THREAD

**Issue by trungjc** [Kademi/kademi-dev#6492]
Reference to https://github.com/Kademi/projects/issues/927

> ensure standard components have an option to show decimal points or not (i think some have an option for number of decimal places?)

**Comment by trungjc** [comment]
![screenshot_5](https://user-images.githubusercontent.com/704946/50754526-99669580-1288-11e9-8aeb-e5590d30d97f.png)


Add "Number of decimal places" setting to:

ecomProductComponent
storeProductListComponent
ecomCheckoutCartComponent
pointsTransactionsComponent
recentlyViewedProductsComponent

**Comment by trungjc** [comment]
Ready for test

**Comment by Uafinder** [comment]
1. Product list
Doesn't show preview for changing decimal places number
![image](https://user-images.githubusercontent.com/1945230/50831928-37c02d00-1355-11e9-96a1-320730f28d79.png)
http://vladtest55vv.admin.kademi-ci.co/pages/vladtest55vvweb/version1/?contenteditor=page1.html

2. Same for product tile
![image](https://user-images.githubusercontent.com/1945230/50831986-69d18f00-1355-11e9-8233-850ee854897f.png)

3. Same for points transaction
![image](https://user-images.githubusercontent.com/1945230/50832154-01cf7880-1356-11e9-884f-6c983c7cf601.png)

**Comment by anhnt** [comment]
@trungjc please fix this as well https://github.com/Kademi/kademi-dev/issues/6465#issuecomment-452287092

**Comment by trungjc** [comment]
recentlyViewedProductsComponent
![screenshot_6](https://user-images.githubusercontent.com/704946/50896803-c8256d00-143c-11e9-82d7-b543aa6dafa3.png)

storeProductListComponent
![screenshot_7](https://user-images.githubusercontent.com/704946/50896804-c8256d00-143c-11e9-95c7-41347ac10cb3.png)

ecomProductComponent
![screenshot_8](https://user-images.githubusercontent.com/704946/50896805-c8be0380-143c-11e9-9e9d-1540d7b84a9b.png)

pointsTransactionsComponent
![screenshot_9](https://user-images.githubusercontent.com/704946/50896806-c8be0380-143c-11e9-997f-2d1a216dd526.png)

**Comment by trungjc** [comment]
Please wait for deploy version 1.7.1

**Comment by trungjc** [comment]
Please Kcom2 to version 1.7.2

**Comment by Uafinder** [comment]
Good
