### ISSUE TITLE
KJourney: issue on lead page

### ISSUE THREAD

**Issue by trungjc** [Kademi/kademi-dev#6495]
Reference to : https://github.com/Kademi/projects/issues/888

**Comment by trungjc** [comment]
Fixed on http://trung.admin.kademi-ci.co/manageUsers/18488192/#funnelsTab-tab

**Comment by trungjc** [comment]
![screenshot_13](https://user-images.githubusercontent.com/704946/50774610-735fe600-12c6-11e9-901b-9fd43ace28c0.png)

@bradmac Currently, I have fixed SMS issue on lead page. Only small point, at "From" column, I try to get provider ($funnelEdm.smsItem.providerName) or website. But It returns nothing.

**Comment by bradmac** [comment]
OK, we need a clear and obvious indicator of emails vs SMS.

I'll look into it.

**Comment by bradmac** [comment]
Done

![image](https://user-images.githubusercontent.com/826458/50800942-6e8f4680-1347-11e9-8ff5-18bda064b682.png)

**Comment by bradmac** [comment]
> . Only small point, at "From" column, I try to get provider ($funnelEdm.smsItem.providerName) or website. But It returns nothing.

@trungjc  this works:
```
                    <td>
                    	#if( $funnelEdm.emailItem )
                    		$funnelEdm.emailItem.fromAddress
                		#else
                		    $funnelEdm.smsItem.providerAppId
                    	#end
                    </td>
```

So you were close!

**Comment by bradmac** [comment]
Requires KJourneys 1.0.4, and I've applied as a patch to the trung account

**Comment by Uafinder** [comment]
Ok, looks great
