### ISSUE TITLE
Show timezone in eventForm component

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6497]
Users currently dont know what timezone the displayed times are for. Please display the timezone.

![image](https://user-images.githubusercontent.com/826458/50804378-88825680-1352-11e9-8118-05d9324df41d.png)

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/50811105-9bd7f680-133f-11e9-9e9b-44f203afdf23.png)

**Comment by bradmac** [comment]
hey @anhnt i think it should show the timezone name instead of the hours offset. I dont know anyone who really understands hour offsets

**Comment by anhnt** [comment]
Done
![image](https://user-images.githubusercontent.com/735555/50816999-ffb8ea00-1354-11e9-8f06-b77ced54668f.png)

**Comment by Uafinder** [comment]
Cools
