### ISSUE TITLE
calendar-lib: Create event registration form component

### ISSUE THREAD

**Issue by trungjc** [Kademi/kademi-dev#6500]
Create event registration form component in calendar-lib

Reference to https://github.com/Kademi/projects/issues/885#issuecomment-449223540

**Comment by trungjc** [comment]
Updated in calender-lib 1.2.5
When this issue is complete, I will apply to Minda

**Comment by Uafinder** [comment]
There are too many options
![image](https://user-images.githubusercontent.com/1945230/50974401-d6829000-14f3-11e9-9c22-6b5e1ddbfb68.png)
http://vladtest55xx.admin.kademi-ci.co/pages/vladtest55xxweb/version1/?contenteditor=page5.html

provide a day of week in event selector (or make it optional)
![image](https://user-images.githubusercontent.com/1945230/50974525-15184a80-14f4-11e9-8be8-b7f703bb160b.png)
E.g. to be 01/01/2019 - Friday - Eventname

**Comment by trungjc** [comment]
![screenshot_4](https://user-images.githubusercontent.com/704946/51012378-61fd2f00-158f-11e9-8168-73d7659ceeba.png)
![screenshot_5](https://user-images.githubusercontent.com/704946/51012380-6295c580-158f-11e9-8e0f-119e5f3c5b09.png)

**Comment by trungjc** [comment]
@Uafinder  Please update to 1.7.3

**Comment by Uafinder** [comment]
Fine
