### ISSUE TITLE
Fresh account href=#xx issues

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6501]
http://vladtest55v.admin.kademi-ci.co/marketPlace/KCommerce2/?websiteBranch=version1&websiteName=vladtest55vweb
![image](https://user-images.githubusercontent.com/1945230/50822256-efdfdc80-1339-11e9-9a98-b45a23624e21.png)

According to Anh
thats unsafe way of using jquery selector
so we upgraded jquery to higher version that doesnt allow this

**Comment by Uafinder** [comment]
Also here
![image](https://user-images.githubusercontent.com/1945230/50834004-9be5ef80-135b-11e9-90d0-302efe4dd2eb.png)
http://vladtest55vv.admin.kademi-ci.co/groupEmails/18495531/#send-tab

**Comment by anhnt** [comment]
All sorted

**Comment by Uafinder** [comment]
Cools
