### ISSUE TITLE
Display lead controls always, no matter of current node

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6502]
![image](https://user-images.githubusercontent.com/1945230/50822662-edca4d80-133a-11e9-9939-d4cc7e29d8de.png)
http://vayability.admin.kademi.us/leads/60011973/#information-tab

Like here
![image](https://user-images.githubusercontent.com/1945230/50822680-fb7fd300-133a-11e9-974c-16d22c28196b.png)

**Comment by anhnt** [comment]
Done and applied to vaya us

**Comment by Uafinder** [comment]
looks good
