### ISSUE TITLE
Issue on nav arrows of date range picker

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6503]
![image](https://user-images.githubusercontent.com/1945230/50823813-83ff7300-133d-11e9-978c-74bceae34517.png)
http://vladtest55v.admin.kademi-ci.co/funnels/first-journey/version1/#journeyBuilder-tab
For example here

**Comment by anhnt** [comment]
already fixed https://github.com/Kademi/kademi-dev/issues/6504

**Comment by Uafinder** [comment]
Looks good
