### ISSUE TITLE
Date range picker on admin console looks not nice

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#6504]
![image](https://user-images.githubusercontent.com/735555/50825131-d440fa00-136a-11e9-9359-09526bb303c7.png)

**Comment by anhnt** [comment]
Done 
![image](https://user-images.githubusercontent.com/735555/50826919-98f4fa00-136f-11e9-94f8-0e16d1ecf996.png)

**Comment by Uafinder** [comment]
Looks good
