### ISSUE TITLE
Node group selector list not in alphabet order

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6505]
![image](https://user-images.githubusercontent.com/1945230/50831228-dbf4a480-1352-11e9-8740-d2df16392d08.png)
http://vladtest55vv.admin.kademi-ci.co/funnels/first-journey/version1/#journeyBuilder-tab

**Comment by anhnt** [comment]
done, requires 1.4.6

**Comment by Uafinder** [comment]
Looks good
