### ISSUE TITLE
No permission for email details for administrator

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6507]
![image](https://user-images.githubusercontent.com/1945230/50833844-30038700-135b-11e9-803b-2a7530f69b40.png)
http://vladtest55vv.admin.kademi-ci.co/manageUsers/19657/
user: adminqa

**Comment by bradmac** [comment]
This is correct, that profile is in the rootorg account, so shouldnt be edited in a subaccount:

http://rootorg.admin.kademi-ci.co/manageUsers/19657/#general-tab

**Comment by Uafinder** [comment]
ok
