### ISSUE TITLE
Asset management page not showing

### ISSUE THREAD

**Issue by joelatfuel** [Kademi/kademi-dev#6509]
On Hazero, we have a PDF asset called Hazero_Product_Catalogue_v1_web.pdf. When we open [this asset's management page](https://hazero.admin.kademi.com.au/asset-manager/700d23e3-456f-4a3c-9061-06de03d16979), we see this error.

<img width="824" alt="screen shot 2019-01-09 at 10 52 32 am" src="https://user-images.githubusercontent.com/41346338/50861161-c0de6f00-13fc-11e9-8be5-fea76d52a573.png">

**Comment by bradmac** [comment]
Done:

![image](https://user-images.githubusercontent.com/826458/50870958-fb590380-141e-11e9-9a73-8e36dfd48610.png)

**Comment by bradmac** [comment]
requires content-lib 1.5.7

**Comment by Uafinder** [comment]
looks cool
