### ISSUE TITLE
KBlog: Duplicated posts add - copy when saved

### ISSUE THREAD

**Issue by joelatfuel** [Kademi/kademi-dev#6510]
Pravina has been duplicating blog posts, changing the title, and then saving. It appears to be adding - copy on save.

See her video here.
https://drive.google.com/file/d/1Vg5R5GhVQhGrHobZAAI4I-19iFyTAhxd/view?usp=sharing

**Comment by bradmac** [comment]
@joelatfuel can you please provide a link to the account?

**Comment by bradmac** [comment]
OK, the problem occurs when changing the title and the path at the same time.

**Comment by bradmac** [comment]
Fixed. Requires platform update.

**Comment by Uafinder** [comment]
Looks good
