### ISSUE TITLE
EDM editor issue - some screen editor cropped

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6513]
![image](https://user-images.githubusercontent.com/1945230/50907802-e8e7c580-1430-11e9-93d2-566baec53ecc.png)
http://vladtest55x.admin.kademi-ci.co/groupEmails/18503722/edmeditor?fileName=index.html&useHash=true

**Comment by anhnt** [comment]
edmEditor-lib 1.2.8

**Comment by Uafinder** [comment]
looks good
