### ISSUE TITLE
KCRM: Add setting to leadsListComponent for the number of leads to display

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6515]
This is currently hardcoded to 10:

```
#foreach($leadRanked in $leadsPage.leadsRanked(0, 10))
```

But it should be editable in component settings

**Comment by anhnt** [comment]
Done!
Note that leads component on default dashboard is loaded via portlet so we cant set that lead number.


![image](https://user-images.githubusercontent.com/735555/50964297-7d215d80-1501-11e9-99d4-ac06463e4f30.png)

**Comment by bradmac** [comment]
> Note that leads component on default dashboard is loaded via portlet so we cant set that lead number.

Its expected that users will remove portlets when they want to customise.

**Comment by Uafinder** [comment]
Looks fine
