### ISSUE TITLE
KCRM: When clicking "more" on a lead note, the container should expand so the content is visible

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6516]
Notes are initially collapsed to make the timeline comprehensible, which is good:

![image](https://user-images.githubusercontent.com/826458/50931196-d28c4900-14c6-11e9-9d24-97d8da625879.png)

But when the user clicks "more" the content is expanded, but the container isnt, so the user must scroll the little comment box to read it which is very hard:
![image](https://user-images.githubusercontent.com/826458/50931247-ec2d9080-14c6-11e9-9af5-bf0290419dc2.png)

Instead, when "more" is clicked the comment container should expand to contain the entire content, ie remove the height restriction so there is no scrolling

**Comment by anhnt** [comment]
Done, applied to kcrm us. Click to button more will show all content, click to button Less will collapse

**Comment by Uafinder** [comment]
It works for text, but would be great have an image handling somehow
![image](https://user-images.githubusercontent.com/1945230/51020855-738f0880-1588-11e9-94ab-f9a81075eaff.png)
http://vladtest55yweb-vladtest55y.kademi-ci.co/leads/18512718/
http://vladtest55y.admin.kademi-ci.co/manageUsers/18512707/#summary-tab

**Comment by anhnt** [comment]
Fixed

**Comment by Uafinder** [comment]
Ok, looks good
