### ISSUE TITLE
KCom2: Products lose their position when loaded by infinite scrolling

### ISSUE THREAD

**Issue by joelatfuel** [Kademi/kademi-dev#6517]
We have an all products page on Hazero. The products initially loaded have the correct order and position, but products loaded by infinite scrolling lose their order and position.

Here are some useful links:
[viewCategory.html](https://www.hazero.co.nz//theme/apps/KCommerce2/contenteditor?fileName=viewCategory.html)
[All Products Page](https://www.hazero.co.nz/products/)

**Comment by yrsengar** [comment]
Hello Brad,

We did some testing this feature today.
We have created a test version and replaced the customised code with the stock code. The stock component and the customised one shows the similar list of products in the same order.

customised: http://hazero-hazero.kademi.com.au/products/
Stock: http://version1-test.hazero-hazero.kademi.com.au/products/

Please have a look and let us know your thoughts on it.

**Comment by bradmac** [comment]
Sorry, i dont understand. Are you saying there is a defect with the stock component?

If so, can you attach screenshots showing the problem?

**Comment by bradmac** [comment]
No information from @yrsengar so closing
