### ISSUE TITLE
EDM assset add link to file issue

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6524]
![image](https://user-images.githubusercontent.com/1945230/50968674-7506f500-14e4-11e9-80ba-94ccf9eea115.png)
![image](https://user-images.githubusercontent.com/1945230/50968684-7d5f3000-14e4-11e9-914d-706dfb508b53.png)
![image](https://user-images.githubusercontent.com/1945230/50968690-83eda780-14e4-11e9-8180-06396254246e.png)
Null appears in link
http://vladtest55xx.admin.kademi-ci.co/asset-manager/ec6c7db4-58ba-4005-9183-a8ab38f9ea8f

**Comment by anhnt** [comment]
Fixed

**Comment by anhnt** [comment]
requires ckeditor-lib 4.5.6.9

**Comment by Uafinder** [comment]
Ok, looks good
