### ISSUE TITLE
Calendar: event's from coming month doesn't show

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6525]
![image](https://user-images.githubusercontent.com/1945230/50973812-75a68800-14f2-11e9-9ede-b30a51972916.png)
http://vladtest55xx.admin.kademi-ci.co/Calendars/calendar%20123/
![image](https://user-images.githubusercontent.com/1945230/50973846-8d7e0c00-14f2-11e9-9193-d1df7f770880.png)
As a result component doesn't show coming events from other months
![image](https://user-images.githubusercontent.com/1945230/50973878-a686bd00-14f2-11e9-8a03-4b1a1c60a91a.png)
http://vladtest55xxweb-vladtest55xx.kademi-ci.co/page5.html

**Comment by bradmac** [comment]
Hey guys, the admin screen is fine, its just giving a quick summary of events coming soon

For the component, its using this code:
```
        #set ($upcomingEvents = $calendars.child($calendar).upcomingEvents)
        #set ($eventPath = "/Calendars/$calendar/")
    #else
        #set ($upcomingEvents = $calendars.getUpcomingAfter(30))
        #set ($eventPath = "/Calendars/$calendar/")
```

Please update so it always uses a number of days ahead, and make that number of days a setting on the component.

So for Minda you can set 365 days to get events for the year ahead.

The default should be 30

**Comment by trungjc** [comment]
![1](https://user-images.githubusercontent.com/704946/51014478-7e529900-159a-11e9-9778-23d1f9eaeaf8.png)
![2](https://user-images.githubusercontent.com/704946/51014479-7e529900-159a-11e9-8860-6ad30a99ebf1.png)

**Comment by trungjc** [comment]
@Uafinder  Please update to 1.2.6

**Comment by Uafinder** [comment]
Looks good
