### ISSUE TITLE
Change expiry date on voucher does not work

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#6528]
https://airnz.admin.kademi.com.au/voucher-type/chcgeorgeacco/bfc3c

Clicking the link does nothing
![image](https://user-images.githubusercontent.com/2201340/51007625-4f3d2700-159c-11e9-838f-8130bc2197fe.png)

**Comment by anhnt** [comment]
Fixed and applied to airnz

**Comment by Uafinder** [comment]
Looks good
