### ISSUE TITLE
signup org type filter should allow multiple types

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#6530]
When signing up to a group, there is ajax request to get list of orgs to join 
ie /Private/signup?jsonQuery=&where-ResellerGroup=Private

Atm the query filter by single org type. Should allow multiple types

![image](https://user-images.githubusercontent.com/735555/51018705-2708f480-15ab-11e9-9a11-029ad900451f.png)

**Comment by bradmac** [comment]
Note this issue occured when no search text was provided. This doesnt happen with standard components because we use type ahead.

**Comment by Uafinder** [comment]
looks ok
