### ISSUE TITLE
Product list component  shows error

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6531]
![image](https://user-images.githubusercontent.com/1945230/51028502-2fa5fe80-159c-11e9-8db2-4eebd1b9ddc0.png)
http://vladtest55yyweb-vladtest55yy.kademi-ci.co/vladtest55yyweb-ecomstore/
adminqa

Component added to separate page works good

**Comment by anhnt** [comment]
already fixed in other issue, requires kcom 1.7.4

**Comment by Uafinder** [comment]
Looks good
