### ISSUE TITLE
Edit voucher issues

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6532]
![image](https://user-images.githubusercontent.com/1945230/51028675-d12d5000-159c-11e9-9be3-04854f0141cf.png)
![image](https://user-images.githubusercontent.com/1945230/51028691-d8545e00-159c-11e9-89f9-80c960fcc478.png)
http://vladtest55yy.admin.kademi-ci.co/voucher-type/type1/#voucherContent-tab

**Comment by anhnt** [comment]
Fixed, requires edmEditor-lib 1.3.5

**Comment by Uafinder** [comment]
Ok
