### ISSUE TITLE
Multiple click on save cause doubling of polls

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6533]
![image](https://user-images.githubusercontent.com/1945230/51029302-9cba9380-159e-11e9-93a9-c0a0737a543e.png)
http://vladtest55yy.admin.kademi-ci.co/kpoll/managePolls/

**Comment by trungjc** [comment]
Fixed in version 1.2.0.

**Comment by Uafinder** [comment]
Yup, looks good
