### ISSUE TITLE
Editing promo content - upload image issue

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6534]
![image](https://user-images.githubusercontent.com/1945230/51029602-7f39f980-159f-11e9-8dba-bf3f09e3aa31.png)
http://vladtest55yy.admin.kademi-ci.co/rewards/promo1/#rewardContent-tab

regular placeholder doesn't work

**Comment by Uafinder** [comment]
Same as here

https://github.com/Kademi/kademi-dev/issues/6538#issuecomment-453991742

http://vladtest55z.admin.kademi-ci.co/rewards/promo1/#rewardContent-tab

**Comment by anhnt** [comment]
works for me. please try again or ping me if need a hand

**Comment by Uafinder** [comment]
ok, container added
but still regular placeholder appears
![image](https://user-images.githubusercontent.com/1945230/51247291-5649a800-1995-11e9-91bf-a5e92ef04e94.png)
http://vladtest56a.admin.kademi-ci.co/rewards/promo1
Fresh account

Why learner lib? That should be a rewards-lib i suppose

**Comment by bradmac** [comment]
> Why learner lib? That should be a rewards-lib i suppose

rewards were originally part of elearning, but we do need to seperate rewards out of elearning.

@anhnt let me know if you want to talk about how to do that

**Comment by anhnt** [comment]
moved templates to rewards-lib, requires rewards-lib 1.2.7

**Comment by Uafinder** [comment]
Looks good
