### ISSUE TITLE
Scheduled email content editing menus look poor

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6535]
![image](https://user-images.githubusercontent.com/1945230/51029794-04bda980-15a0-11e9-9fdc-a07ae7ad2b6d.png)
![image](https://user-images.githubusercontent.com/1945230/51029804-0e471180-15a0-11e9-8326-5be474c4273d.png)
http://vladtest55yy.admin.kademi-ci.co/scheduledEmails/sch1/#configuration-tab

**Comment by anhnt** [comment]
fixed, requires admin-lib 1.3.0, email-lib 1.1.6, edmEditor-lib 1.3.1

**Comment by Uafinder** [comment]
ok, looks good
