### ISSUE TITLE
Scheduled emails content image upload issue

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6536]
regular placeholder doesn't work
![image](https://user-images.githubusercontent.com/1945230/51029845-346cb180-15a0-11e9-97ac-6be0a285b96a.png)
http://vladtest55yy.admin.kademi-ci.co/scheduledEmails/sch1/#configuration-tab

**Comment by anhnt** [comment]
fixed, requires admin-lib 1.3.0, email-lib 1.1.6, edmEditor-lib 1.3.1

**Comment by Uafinder** [comment]
Ok, looks good
