### ISSUE TITLE
manage rewards cancel button does nothing

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6537]
![image](https://user-images.githubusercontent.com/1945230/51030029-d2607c00-15a0-11e9-9b1f-feb5d3d13f84.png)
http://vladtest55yy.admin.kademi-ci.co/points-buckets/points1/#rewardContent-tab

**Comment by bradmac** [comment]
i think we just remove it.

**Comment by bradmac** [comment]
@trungjc please just remove the button

**Comment by trungjc** [comment]
![screenshot_9](https://user-images.githubusercontent.com/704946/51899860-79894400-23e6-11e9-8744-1c7fcebd8fa0.png)

Remove Cancel button in point-bucket detail page in verstion 1.7.5

**Comment by bradmac** [comment]
looks good

**Comment by Uafinder** [comment]
Yup, fine now
