### ISSUE TITLE
Products brief content regular plaholder doesn't work

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6538]
![image](https://user-images.githubusercontent.com/1945230/51030120-2703f700-15a1-11e9-8d68-2595e8292f3c.png)
http://vladtest55yy.admin.kademi-ci.co/products/18514261/#panel-brief-tab

**Comment by anhnt** [comment]
Done in products-lib 1.1.3

**Comment by Uafinder** [comment]
no possilility to add any container now
![image](https://user-images.githubusercontent.com/1945230/51113309-46ea2380-180a-11e9-8795-ce6b7cb561db.png)
no placeholder
![image](https://user-images.githubusercontent.com/1945230/51113333-59645d00-180a-11e9-9c63-2b4eee25cb4d.png)
both Brief and content tabs
http://vladtest55z.admin.kademi-ci.co/products/18584892/#panel-brief-tab

**Comment by bradmac** [comment]
@Uafinder i was able to add a container:

![image](https://user-images.githubusercontent.com/826458/51134081-6da46a80-189b-11e9-8efb-178c5d6014c2.png)

I think its initially just a bit fiddly because the initial content is not keditor, but it gets wrapped in keditor a moment after loading.

**Comment by Uafinder** [comment]
ok, looks good now
