### ISSUE TITLE
Survey image content regular plaholder doesn't work

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6539]
![image](https://user-images.githubusercontent.com/1945230/51030918-8c58e780-15a3-11e9-9af2-cfdc0263272e.png)
http://vladtest55yy.admin.kademi-ci.co/ksurvey/survey-151b7801-2705-4586-bebe-bf098aadafcd/#questions-tab

**Comment by anhnt** [comment]
ksurveyapp 1.4.5

**Comment by anhnt** [comment]
Should be using assets only

**Comment by Uafinder** [comment]
looks good
