### ISSUE TITLE
EDM doesn't react on container background color

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6541]
![image](https://user-images.githubusercontent.com/1945230/51032142-9da3f300-15a7-11e9-94b4-b7df4a76799e.png)
http://vladtest55yy.admin.kademi-ci.co/funnels/first-journey/version1/emailAction-afab37/#message-tab

**Comment by anhnt** [comment]
edmEditor 1.3.0

**Comment by Uafinder** [comment]
Cools
