### ISSUE TITLE
Images in Kademi should be optimised with srcset

### ISSUE THREAD

**Issue by joelatfuel** [Kademi/kademi-dev#6543]
We need the default components to serve the right image to the device or browser window. This will greatly improve the page load, and increase our score in [Google Page Speed Insights](https://developers.google.com/speed/pagespeed/insights). Here's [some documentation](https://developers.google.com/web/fundamentals/design-and-ux/responsive/images#images_in_markup) from Google and below is a code snippet of an image using srcset.

```
<img src="lighthouse-200.jpg" sizes="50vw"
     srcset="lighthouse-200.jpg 200w,
             lighthouse-400.jpg 400w, lighthouse-800.jpg 800w,
             lighthouse-1000.jpg 1000w, lighthouse-1400.jpg 1400w,
             lighthouse-1800.jpg 1800w" alt="a lighthouse">
```

**Comment by joelatfuel** [comment]
We need to load the correct alternate format depending on your device or screen size - so it needs to be dynamic

**Comment by joelatfuel** [comment]
Also, we could use some bigger alt formats - perhaps 1500px and 2500px wide. We can then reference these as the largest size and prevent clients from loading massive images.

**Comment by bradmac** [comment]
Added support for webp, and 2 new sizes 1500x500 and 2500x500

**Comment by joelatfuel** [comment]
I have a question about the image alt formats. If I have an image at 2500x1500, will the image be scaled down proportionally to a height of 500 pixels?

**Comment by bradmac** [comment]
images are scaled down proportionally to fit inside a bounding box of the given dimensions.

Eg if we have 100x100 and an image of 800x400, it will be scaled so its width is 100 and height will be 50

For an image of 400x800 it will have a height of 100 and width of 50.

**Comment by bradmac** [comment]
@anhnt can you please finish this off
- add an option to the component for whether to enable webp (on by default)
- ensure the image styles are applied correctly to the picture element
- add a breakpoint at 1170 to correspond to bootstrap's large device breakpoint

Note that bootstrap has 4 sizes but i think just 3 image sizes is ideal.

**Comment by bradmac** [comment]
And i think webp conversions arent working on CI, so when you need to test with webp enabled that will need to be done in prod

**Comment by bradmac** [comment]
This issue should just be for the photo component. We'll look at other components after this is complete.

**Comment by anhnt** [comment]
i got some error with newly added format eg
```
getResource: unrecognised format: 2500-2500.png
getResource: pre-generated alt format not found: 2bbd6ac497de9f964b2534104056b4614d999990 - alt-2500-2500.png

**Comment by anhnt** [comment]
example http://s-testpicture.kademi-ci.co/

**Comment by bradmac** [comment]
> i got some error with newly added format eg

The project was depending on an old version of the kademi jar, so changes werent applied.

Fixed

**Comment by anhnt** [comment]
Done

**Comment by anhnt** [comment]
@Uafinder ping me if you need a hand how to test this

**Comment by bradmac** [comment]
BTW, the reason this is important is because Google has started penalising sites heavily (in terms of page rank) for not having webp images, and for not having mobile optimised size images.

So this is affecting the google page rank of client sites, although its also affecting sites on other platforms.

What we've got here is a first class solution, so should put us ahead of the others :)

**Comment by Uafinder** [comment]
Looks good
