### ISSUE TITLE
Filtering tags not working

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#6544]
http://kademi.admin.kademi.us/manageUsers/?filter-tags=&filter-orgs=

Adding a filter by typing the name of the tag/group does not refine the list, however it does seem to do something as the focus on the input is lost, but the list does not refine.

![image](https://user-images.githubusercontent.com/2201340/51095635-418cd900-180a-11e9-95eb-14cc480107d2.png)

**Comment by anhnt** [comment]
Those tags come from blog tags which are to be added to profile interests http://kademi.admin.kademi.us/blogs/kb/
![image](https://user-images.githubusercontent.com/735555/53073921-fdcd7380-351b-11e9-9d5e-b658c0dbcf35.png)

But backend doesnt support atm
See ElasticUserDataSource.java line 110
![image](https://user-images.githubusercontent.com/735555/53073957-189fe800-351c-11e9-886e-2bcbeb3db77a.png)

**Comment by bradmac** [comment]
yeah, that blog tag preferences stuff is old, not really used. 

"Tags" are always done with groups now.

So i'll remove the feature from the blogs app which shows tags in the user search page

**Comment by bradmac** [comment]
Done

**Comment by Uafinder** [comment]
ok, looks good
