### ISSUE TITLE
Scheduled email details JS errors

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6546]
Some JS errors appears when access email details
http://vladtest55z.admin.kademi-ci.co/scheduledEmails/123/
![image](https://user-images.githubusercontent.com/1945230/51112988-3f764a80-1809-11e9-988b-feb7a1dace28.png)
![image](https://user-images.githubusercontent.com/1945230/51112999-4604c200-1809-11e9-9624-aee8293a3ad4.png)

**Comment by anhnt** [comment]
fixed, requires admin-lib 1.3.1 and email-lib 1.1.7

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/51185589-415f0d00-18e0-11e9-8c6a-cf18b351eaa8.png)
http://vladtest55zz.admin.kademi-ci.co/scheduledEmails/sched1/#configuration-tab

**Comment by bradmac** [comment]
I'm seeing this on page load

![image](https://user-images.githubusercontent.com/826458/51204266-099ba800-1968-11e9-9ed6-3d418cee43a7.png)

**Comment by anhnt** [comment]
fixed

**Comment by Uafinder** [comment]
ok, looks good
