### ISSUE TITLE
multiple click on save cause doublin of surveys

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6547]
![image](https://user-images.githubusercontent.com/1945230/51113087-86fcd680-1809-11e9-8fa0-b96ebf3e9601.png)
![image](https://user-images.githubusercontent.com/1945230/51113089-8cf2b780-1809-11e9-98da-e04836537fc8.png)
http://vladtest55z.admin.kademi-ci.co/ksurvey/

same on questions create page
http://vladtest55z.admin.kademi-ci.co/ksurvey/survey-09ac2e5a-56b4-4443-92a3-8c9cd0cc00fb/#questions-tab
![image](https://user-images.githubusercontent.com/1945230/51113182-df33d880-1809-11e9-9b5e-896910160162.png)

**Comment by trungjc** [comment]
Update in version 1.4.7

**Comment by Uafinder** [comment]
Looks good
