### ISSUE TITLE
EDM asset issues

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6549]
1. No possibility to drag and drop container
2. Default left side margin missed
![image](https://user-images.githubusercontent.com/1945230/51113811-0c818600-180c-11e9-8ebd-c0f62ffa25db.png)
http://vladtest55z.admin.kademi-ci.co/asset-manager/new-text?format=text/html/edm

**Comment by bradmac** [comment]
> No possibility to drag and drop container

@Uafinder looks to me:

![image](https://user-images.githubusercontent.com/826458/51134404-5ade6580-189c-11e9-87fd-cf548e5ebdfc.png)

**Comment by bradmac** [comment]
> Default left side margin missed

Yep, also saw this on scheduled email page

**Comment by anhnt** [comment]
I've seen issue with edm editor which doesnt let user drag/drop container. Checking now

**Comment by anhnt** [comment]
https://github.com/Kademi/kademi-dev/issues/6486

**Comment by anhnt** [comment]
>No possibility to drag and drop container

This problem cant be reproduced if cache is not being disabled. @Uafinder please try with that and this is often enabled on all browsers

**Comment by anhnt** [comment]
>Default left side margin missed
Fixed in edmEditor 1.3.2

**Comment by Uafinder** [comment]
Same on fresh account
![image](https://user-images.githubusercontent.com/1945230/51183100-f1c91300-18d8-11e9-80c2-9a6393a7061e.png)
http://vladtest55zz.admin.kademi-ci.co/asset-manager/e3f40af5-3dd3-40ed-8f92-e0a2b4e94df8

**Comment by Uafinder** [comment]
Also doesn't work with Browserstack
![image](https://user-images.githubusercontent.com/1945230/51185550-1eccf400-18e0-11e9-9086-6659c3f19ab3.png)

**Comment by bradmac** [comment]
Works fine for me

![image](https://user-images.githubusercontent.com/826458/51204102-a7db3e00-1967-11e9-8e0a-7feb14f8701a.png)

**Comment by bradmac** [comment]
@anhnt and @Uafinder i suggest you guys chat to get this resolved

**Comment by Uafinder** [comment]
Looks much better
