### ISSUE TITLE
Add a Role for External IT Consultants

### ISSUE THREAD

**Issue by joelatfuel** [Kademi/kademi-dev#6552]
Some of our customers have external IT companies that need access to modify and add new DNS information. We need a new role that gives access to the Domains and Websites panel.

**Comment by bradmac** [comment]
Done.

![image](https://user-images.githubusercontent.com/826458/51221389-26eb6900-199e-11e9-9fe2-8928ddbab93e.png)

Example logged in user

![image](https://user-images.githubusercontent.com/826458/51221372-10451200-199e-11e9-8a61-5517cdbf3d3b.png)

Note some custom apps might still display in the menu, but cant be accessed

**Comment by Uafinder** [comment]
ok, looks good
