### ISSUE TITLE
Points importer creates negative points credits instead of debits

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6556]
Related: https://github.com/Kademi/kademi-dev/issues/5303

**Comment by bradmac** [comment]
should be fixed now

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/51186330-11186e00-18e2-11e9-9078-672976ee165a.png)
http://vladtest55zz.admin.kademi-ci.co/points-buckets/points/#points-tab

**Comment by bradmac** [comment]
@Uafinder CI wasnt updating yesterday because it was on the wrong version of kademi-server

please test again

**Comment by Uafinder** [comment]
Yup, looks better
