### ISSUE TITLE
Import SCORM modules: Phase 1

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#656]
https://en.wikipedia.org/wiki/Sharable_Content_Object_Reference_Model

Get a trial copy of articulate and create and export a scorm module:
http://www.articulate.com/support/presenter-5/how-do-i-publish-to-scorm-or-aicc-817

Just need to be able to import that into a kademi module

**Comment by tuzzmaniandevil** [comment]
http://scorm.com/scorm-explained/technical-scorm/run-time/

**Comment by tuzzmaniandevil** [comment]
http://scorm.com/scorm-explained/technical-scorm/run-time/run-time-reference/

**Comment by tuzzmaniandevil** [comment]
Phase 1 done
