### ISSUE TITLE
Scheduled email image issue

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6561]
1. Create new EDM
2. Edit content
3. Add photo component, upload some image
4. Save
![image](https://user-images.githubusercontent.com/1945230/51241712-0237c700-1987-11e9-8cbd-f0ddc050bcb5.png)
5. make sure it appears on preview
![image](https://user-images.githubusercontent.com/1945230/51241727-0d8af280-1987-11e9-8df7-85ba12e3b1aa.png)
6. Refresh
7. Press edit content
![image](https://user-images.githubusercontent.com/1945230/51241743-21ceef80-1987-11e9-9ed3-da19b598d3d4.png)
http://vladtest56a.admin.kademi-ci.co/scheduledEmails/newone/#configuration-tab

**Comment by anhnt** [comment]
email-lib 1.1.8

**Comment by anhnt** [comment]
Done in edmEditor-lib 1.3.4

**Comment by Uafinder** [comment]
Looks good
