### ISSUE TITLE
Forums: feature to enable notifications for admins of new comments

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6566]
This is so we dont need to create journeys for a simple notification

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/51445479-53baca00-1d6a-11e9-8158-6de6df9c58c9.png)

**Comment by bradmac** [comment]
Note that this uses the new admin notifications service. The notification is not customisable, and will only be sent to the administrator (or administrators) group.

**Comment by Uafinder** [comment]
Doesn't work for me
http://vladtest56cweb-vladtest56c.kademi-ci.co/page1.html
http://vladtest56c.admin.kademi-ci.co/manageUsers/18616601
And no emails came

**Comment by Uafinder** [comment]
So, this one is tell us that admin notification is ok?
![image](https://user-images.githubusercontent.com/1945230/51516751-16fdda00-1e21-11e9-8612-2b7806122f6b.png)

**Comment by Uafinder** [comment]
ok, cools now
