### ISSUE TITLE
media component should dynamically set image source based on current files system/ assets

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#6568]
![image](https://user-images.githubusercontent.com/735555/51290772-47b3cd00-1a37-11e9-9c1b-ffbb24d1b961.png)

**Comment by anhnt** [comment]
Fixed

**Comment by Uafinder** [comment]
hey @anhnt 
any influence? is it frontend?

**Comment by bradmac** [comment]
i can see this requires keditor-lib 1.3.4

@Uafinder the problem was that when using the media component, asset images would not display

**Comment by Uafinder** [comment]
looks good
