### ISSUE TITLE
Ability to log work right on the lead details page

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#6575]
![image](https://user-images.githubusercontent.com/735555/51364068-5bc9fe00-1b0d-11e9-9ce0-fcfcd2abf8a5.png)

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/51365294-6d7ac800-1b44-11e9-8518-96f0632cd1ff.png)

**Comment by anhnt** [comment]
Done, requires leadman-lib 3.4.1

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/52992827-8c6ec180-3444-11e9-84f6-ce3b414fc0f0.png)

**Comment by anhnt** [comment]
added task select box to allow specifying task to log work

**Comment by Uafinder** [comment]
Doesn't give a possibility to enter value with comma... e.g. 0.5, 1.5 and so on is not allowed
![image](https://user-images.githubusercontent.com/1945230/53011853-11a8a500-344a-11e9-8b9e-dfc8cfe04d90.png)

Task is a mandatory field
![image](https://user-images.githubusercontent.com/1945230/53011904-313fcd80-344a-11e9-89ff-dded57ebdd17.png)
Should be possibility to log hours to the lead himself
Like here
![image](https://user-images.githubusercontent.com/1945230/53011943-4c124200-344a-11e9-8593-fc5772035e32.png)

Also note, that there is no message when you place a value and this value is not empty
For example you log some hours previously (say 2 hours)
And then at the end of the day you logged 1 hours (for example you forget that you logged something before) and those 2 hours logged before will gone without warning.

**Comment by anhnt** [comment]
Done, requires leadman-lib 3.4.2 and rebuild CI

You are now able log hour with step = 0.5 and multiple timesheet entry, and also can delete entry

![image](https://user-images.githubusercontent.com/735555/53064760-8d165f00-34fb-11e9-876c-4b9432773bf3.png)

**Comment by anhnt** [comment]
also can select lead or task to log 

![image](https://user-images.githubusercontent.com/735555/53064817-bfc05780-34fb-11e9-844e-43061a9dd39c.png)

**Comment by Uafinder** [comment]
Fresh account:
Month are not matching
![image](https://user-images.githubusercontent.com/1945230/53160019-b6a0ba80-35cf-11e9-8e5a-fd232a463b24.png)
![image](https://user-images.githubusercontent.com/1945230/53160050-c3251300-35cf-11e9-9897-7055d5477eff.png)
http://vladtest56vvweb-vladtest56vv.kademi-ci.co/leads/18824065/?view=activities

**Comment by anhnt** [comment]
Fixed, requires KTimesheets 1.0.7

**Comment by Uafinder** [comment]
Looks good
