### ISSUE TITLE
Keditor: baloon flight image missed (as well as other static images)

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6576]
![image](https://user-images.githubusercontent.com/1945230/51383240-8a51d400-1b21-11e9-9c48-e932f57f594c.png)
http://vladtest56bb.admin.kademi-ci.co/asset-manager/80ac188e-bbb5-4505-afbd-3bb908a1b43f

as well as other static images
![image](https://user-images.githubusercontent.com/1945230/51385479-136c0980-1b28-11e9-9674-20147e9893d1.png)

**Comment by bradmac** [comment]
This is because of a 404 on this path:
http://vladtest56bb.admin.kademi-ci.co/static/images/ballon_flight.jpg/alt-800-800.png

@anhnt i think we decided to move all sample images into the editor or content libs, right?

**Comment by anhnt** [comment]
That was edm snippets. Copied all images to content lib

**Comment by Uafinder** [comment]
Still bad
![image](https://user-images.githubusercontent.com/1945230/51730848-ae616800-2081-11e9-888f-ef50a0fc24df.png)
http://vladtest56e.admin.kademi-ci.co/asset-manager/e9b48bbf-7bbb-4cfc-a1f3-422597a04828

And that wasn't EDM issue, regular keditor in assets

**Comment by anhnt** [comment]
requires contentEditor-lib 1.4.2 as well

**Comment by Uafinder** [comment]
Looks good now
