### ISSUE TITLE
Unable to edit a membership from the profile page

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#6578]
http://swimart.admin.kademi.com.au/manageUsers/139274006/#

Clicking the 3 dotted menu item does nothing.

![image](https://user-images.githubusercontent.com/2201340/51447437-4275bb80-1d72-11e9-9947-409509d8ba3a.png)

Also clicking other tabs does not render the data.

![image](https://user-images.githubusercontent.com/2201340/51447446-591c1280-1d72-11e9-91bb-2b37f6b03cea.png)

**Comment by bradmac** [comment]
updated libs and thats ok now
