### ISSUE TITLE
Calendars: Do not show "Add guest" button when guests are disabled

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6580]
![image](https://user-images.githubusercontent.com/826458/51455454-72db4b00-1dae-11e9-86bc-8881b7bfafd4.png)

...

![image](https://user-images.githubusercontent.com/826458/51455470-85558480-1dae-11e9-9fd3-f83f790388e0.png)

**Comment by trungjc** [comment]
http://trung.admin.kademi-ci.co/Calendars/rspv/event-3-1#confirmation-tab

![1](https://user-images.githubusercontent.com/704946/51455717-6b4f7e00-1d7d-11e9-9b5d-a97a1c524d98.png)
![screenshot_2](https://user-images.githubusercontent.com/704946/51455718-6b4f7e00-1d7d-11e9-92db-e768d2e9df16.png)

Update on version 1.2.7

**Comment by Uafinder** [comment]
Ok, looks good.
