### ISSUE TITLE
Calendars: Use user's timezone to display times if possible

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6581]
For browsers which support it, please display calendar event date/times using the user's own timezone

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat

![image](https://user-images.githubusercontent.com/826458/51455659-77ecca00-1daf-11e9-8eda-c1dfd7f632db.png)

ALSO .. change so that the timezone is only displayed once, its silly showing it for both times.

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/52853317-d6f2f400-314d-11e9-8917-adcb91eeed22.png)

requires calendar-lib 1.3.4

**Comment by anhnt** [comment]
note that when geoip based timezone exists and equal browser timezone, this section will be hidden

**Comment by Uafinder** [comment]
Hmmm...
ok, it works. but  i'm seeing that it's not hide when timezone is the same
![image](https://user-images.githubusercontent.com/1945230/52946499-d2f8e900-337c-11e9-907a-77b2d046671f.png)
http://vladtest56sweb-vladtest56s.kademi-ci.co/Calendars/cal1/test1/
http://vladtest56s.admin.kademi-ci.co/Calendars/cal1/test1#details-tab

**Comment by anhnt** [comment]
Should be fixed now

**Comment by Uafinder** [comment]
ok, looks good
