### ISSUE TITLE
Calendars: when tick disable guests checkbox custom calendars component still show guests

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6583]
https://github.com/Kademi/kademi-dev/issues/6580
Comes from here
So we should either check guests checkbox or we should add option to component
http://vladtest56cweb-vladtest56c.kademi-ci.co/page5.html
![image](https://user-images.githubusercontent.com/1945230/51473136-23802500-1d84-11e9-9ef1-17aa750d3efd.png)
http://vladtest56c.admin.kademi-ci.co/Calendars/cal1/test1#confirmation-tab

**Comment by bradmac** [comment]
I think it should be pretty easy to store whether guests are allowed in the event list (a data attribute on the option ?) and check that when selected, and hide the 'add guest'  button if appropriate

**Comment by trungjc** [comment]
![screenshot_4](https://user-images.githubusercontent.com/704946/51731817-b5eb3600-20ae-11e9-91ea-5280a559c7b9.png)
![screenshot_5](https://user-images.githubusercontent.com/704946/51731819-b5eb3600-20ae-11e9-935e-7e0701d043ce.png)
![screenshot_6](https://user-images.githubusercontent.com/704946/51731820-b5eb3600-20ae-11e9-986c-f09e9ab9f37f.png)
![screenshot_7](https://user-images.githubusercontent.com/704946/51731822-b683cc80-20ae-11e9-9e32-e8f2bc86f183.png)

Hidden add guest button when user un-check Allow users to register guests in admin side

**Comment by Uafinder** [comment]
looks ok
