### ISSUE TITLE
Blog: group access not showing when article is published

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6584]
![image](https://user-images.githubusercontent.com/1945230/51474377-bcfd0600-1d87-11e9-9511-3489ad9b7a55.png)
http://vladtest56c.admin.kademi-ci.co/blogs/myblog1/art2/#groups-tab
Should be shown as read-only
Comes from here
https://github.com/Kademi/kademi-dev/issues/6456

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/53138708-cdd4ad80-35b9-11e9-913a-d0092cfb2dcc.png)

blogs-lib 1.2.2 and jquery-kselector-lib 1.0.2

**Comment by Uafinder** [comment]
ok, looks good
