### ISSUE TITLE
Blog: tile component images bad

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6585]
![image](https://user-images.githubusercontent.com/1945230/51476055-06038900-1d8d-11e9-99d9-12fa7b0d5fae.png)
http://vladtest56c.admin.kademi-ci.co/blogs/blog%203/art4/#bodyCopy-tab
- Create article
- add tile component
- click change photo and upload some image
- click ok

**Comment by bradmac** [comment]
@anhnt the background image style is badly formed

![image](https://user-images.githubusercontent.com/826458/51496626-6b0abd80-1e25-11e9-8c70-f76b9d7b1f5f.png)

**Comment by anhnt** [comment]
Looks ok with latest libs

**Comment by Uafinder** [comment]
Still bad
![image](https://user-images.githubusercontent.com/1945230/51741701-5b4add80-20a0-11e9-8915-65ccf9f6b2b9.png)
http://vladtest56ee.admin.kademi-ci.co/blogs/blog1/article1/#bodyCopy-tab

**Comment by anhnt** [comment]
fixed requires content-lib 1.6.9

**Comment by Uafinder** [comment]
Looks better
