### ISSUE TITLE
blogs: image not showing when article published

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6586]
![image](https://user-images.githubusercontent.com/1945230/51476541-7a8af780-1d8e-11e9-8133-18a13a0a8cf2.png)
http://vladtest56c.admin.kademi-ci.co/blogs/blog%203/art5/#bodyCopy-tab

**Comment by bradmac** [comment]
@Uafinder this is already covered on another issue. Components are not rendered in this view, so come up as blank

This is not a priority issue right now
