### ISSUE TITLE
Incorrect encoding of <> symbols

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6589]
![image](https://user-images.githubusercontent.com/1945230/51478414-0a7f7000-1d94-11e9-8a77-fc184b2c0a31.png)
![image](https://user-images.githubusercontent.com/1945230/51478433-1408d800-1d94-11e9-9bd9-c48963a8fc7a.png)
http://vladtest56c.admin.kademi-ci.co/asset-manager/8fbde57c-494a-4b98-9e64-227d1f388592
To reproduce, create new page, add new text component, and try to add <> of this symbols.
Then try to switch to source view

**Comment by bradmac** [comment]
@Uafinder that appears to be correct encoding. Why do you think there is a problem?

**Comment by Uafinder** [comment]
got it
