### ISSUE TITLE
Survey: re-order answers doesn't work

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6590]
![image](https://user-images.githubusercontent.com/1945230/51478983-ac538c80-1d95-11e9-99a6-fa264061dc76.png)
http://vladtest56c.admin.kademi-ci.co/ksurvey/survey-690fee6d-058e-4339-aa12-8c67a91f9dcf/

**Comment by bradmac** [comment]
p1

**Comment by trungjc** [comment]
Fix sortable do not init after ajax call

**Comment by bradmac** [comment]
Nice

**Comment by Uafinder** [comment]
Still doesn't work
http://vladtest56h.admin.kademi-ci.co/ksurvey/

Vlad 1:23 PM
hmm
so it looks like happends only while creating


trung 1:24 PM
aha
I got it
when we create new question

**Comment by trungjc** [comment]
You should update ksurvey to 1.4.8
https://github.com/Kademi/kademi-dev/commit/d59a58182187edbd8a3683fe80bd01169f3e9fa4
![screenshot_4](https://user-images.githubusercontent.com/704946/51982310-3bfce780-24c8-11e9-8253-12b8d3858440.png)

**Comment by Uafinder** [comment]
Yup... i seeing issue with update lib will check

**Comment by Uafinder** [comment]
it works
