### ISSUE TITLE
User notification email error when submit to calendar

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6595]
![image](https://user-images.githubusercontent.com/1945230/51480925-fbe88700-1d9a-11e9-9886-342341c2b729.png)
http://vladtest56c.admin.kademi-ci.co/manageUsers/18617342/#emailAppTab-tab

**Comment by bradmac** [comment]
Thats because the confirmation subject is blank:

![image](https://user-images.githubusercontent.com/826458/51495356-e61da500-1e20-11e9-8612-01418d5269ae.png)

I've added a default subject

**Comment by Uafinder** [comment]
ok, looks good
