### ISSUE TITLE
Recognition: Badge nomination

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6598]
Required for https://github.com/Kademi/client-vaya-vayability/issues/148

**Comment by bradmac** [comment]
Please update manageBadge.html in KRecognition ..
- allow awarding a badge to a user (use entityFinder). There is a partially built controller method for this in app.js
- allow nominating a user for a badge.  There is a partially built controller method for this in app.js
- display a list of awarded badges in a tab

**Comment by anhnt** [comment]
Done 

![image](https://user-images.githubusercontent.com/735555/52702191-547ffe00-2fae-11e9-92ce-e42d845952cf.png)

**Comment by anhnt** [comment]
@bradmac when an user has been nominated do we have button to award badge for that user

**Comment by anhnt** [comment]
added reason field and Accept/Reject button

![image](https://user-images.githubusercontent.com/735555/52705785-5a79dd00-2fb6-11e9-8aff-f69f58c48e66.png)

**Comment by bradmac** [comment]
Next step is to build front end components

**Comment by bradmac** [comment]
@anhnt I've got 2 kselectors on the page, but clicking the second opens the first..

![image](https://user-images.githubusercontent.com/826458/54066923-55e6d280-429d-11e9-8bb1-1cc49cdd6443.png)

Can you check if thats an issue with the kseletvor plugin?

Also, I cant get list reloading to work

**Comment by anhnt** [comment]
Fixed in kselector 1.0.3

**Comment by bradmac** [comment]
I've added a method in RecognitionManager to get badges available for nomination by the current user:
```
public List<RecognitionBadge> findBadgesForNomination(Profile nominator, RecognitionTopic topic) {
```

**Comment by bradmac** [comment]
@Uafinder for this issue to pass we only need it to be functional enough for use with vaya.

If you find any issues which are not blockers, please log them as seperate issues.

**Comment by Uafinder** [comment]
Nomination rules doesn't work at all... 
http://vladtest57f.admin.kademi-qa.co/recognition/192076/badges/193213/#award-tab
Should not be able to nominate by adminqa as he has participation in ecommerce group per this rule
http://vladtest57f.admin.kademi-qa.co/recognition/192076/badges/193213/#panel_details-tab

Badge without any rules are available for nomination
![image](https://user-images.githubusercontent.com/1945230/54109473-6c00aa00-43e7-11e9-8dd3-af3faa3cffa1.png)
![image](https://user-images.githubusercontent.com/1945230/54110983-74f37a80-43eb-11e9-863d-46c2e6bfbe46.png)
http://vladtest57f.admin.kademi-qa.co/recognition/192076/badges/192087/#award-tab

**Comment by bradmac** [comment]
@Uafinder to clarify, we're not expecting any of these rules to be applied in the admin.

The nomination rules are intended to apply in the front end where end users will nominate users.

**Comment by Uafinder** [comment]
ok, got it
looks good
