### ISSUE TITLE
KCom2: Remove price range on variants  product if min price is equal to max price

### ISSUE THREAD

**Issue by trungjc** [Kademi/kademi-dev#6599]
![screenshot_12](https://user-images.githubusercontent.com/704946/51509967-aad5a300-1e2d-11e9-85f3-f30846f1ed47.png)

Variants  product which has min price is equal to max price should be only showed one price.

**Comment by trungjc** [comment]
http://trung.admin.kademi-ci.co/products/18618668/#panel_details-tab
http://trungtestsite-trung.kademi-ci.co/trungtestsite-ecomstore/carbootgift

Fixed in version 1.7.5

**Comment by Uafinder** [comment]
Looks like several issues appears:
1. When edit template this code appears
![image](https://user-images.githubusercontent.com/1945230/51527776-de202e00-1e3d-11e9-833d-451cf1824588.png)
http://vladtest56ccc.admin.kademi-ci.co/websites/vladtest56cccweb/version1?editTemplate=theme/apps/KCommerce2/viewProduct

2. Should be 2 decimals by default
![image](https://user-images.githubusercontent.com/1945230/51527811-eed0a400-1e3d-11e9-89cb-244ddca18efd.png)
http://vladtest56cccweb-vladtest56ccc.kademi-ci.co/vladtest56cccweb-ecomstore/p4

3. Should rounded correctly - price is 149.95, so without decimals it should be 150

**Comment by bradmac** [comment]
@trungjc this is using some horrible code to do something very simplle. I'll refactor.

**Comment by bradmac** [comment]
Related - https://github.com/Kademi/kademi-dev/issues/6672

**Comment by bradmac** [comment]
I've removed the getDecimals function in app.js and replaced it with a formatter function

@trungjc please check components are working correctly.

**Comment by trungjc** [comment]
Reference to https://github.com/Kademi/kademi-dev/issues/6677

**Comment by trungjc** [comment]
> I've removed the getDecimals function in app.js and replaced it with a formatter function

Reference to #6677

**Comment by Uafinder** [comment]
looks good
