### ISSUE TITLE
Auction Window changes 

### ISSUE THREAD

**Issue by Keegan01** [Kademi/kademi-dev#660]
Hi Brad, 

I was wondering if you might be able to make some tweaks to the way the Auctions Finish. 

What we are wanting is - as soon as an Auction Finishes to display the CONGRATS messaging to the winner over the image. We would like this to appear in the Auction Window, were the bidding takes place.

 
![1](https://cloud.githubusercontent.com/assets/12854986/9537636/182bd782-4d7e-11e5-9586-0eb33cb51e8b.jpg)

To all other people the Sorry message: 
 
![2](https://cloud.githubusercontent.com/assets/12854986/9537638/1fc991f0-4d7e-11e5-8aaa-f9a075a24025.jpg)

PLUS perhaps where the messaging currently says “ This Auction is Live but you have not yet placed a bid” / “well done you are currently the highest bidder” – as highlighted below.  AS soon as it has finished it should say: 

This Auction has now finished. 

![3](https://cloud.githubusercontent.com/assets/12854986/9537642/2e43fe78-4d7e-11e5-8a6f-e8cbbb0a0c17.png)
![4](https://cloud.githubusercontent.com/assets/12854986/9537644/317f7432-4d7e-11e5-97d1-f7dfec5d7ebc.png)

**Comment by bradmac** [comment]
Moving to merc issues list
