### ISSUE TITLE
Group list bad in user visit journey node

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6607]
![image](https://user-images.githubusercontent.com/1945230/51533253-ee8ad580-1e4a-11e9-8b22-3148a3971bc1.png)
http://vladtest56ccc.admin.kademi-ci.co/funnels/first-journey/version1/#journeyBuilder-tab

**Comment by bradmac** [comment]
Done

**Comment by Uafinder** [comment]
Cools
