### ISSUE TITLE
Badge image uploading enhancements

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6608]
1. Aspect ratio for image when uploading is bad 
![image](https://user-images.githubusercontent.com/1945230/51534220-dc5e6680-1e4d-11e9-92a5-88460606b107.png)
http://vladtest56ccc.admin.kademi-ci.co/recognition/18629199/

2. When low quality image appears - it looks very huge and ugle on screen
![image](https://user-images.githubusercontent.com/1945230/51534270-fd26bc00-1e4d-11e9-863a-5081e5ed3e1a.png)
Badge images are small usually.

**Comment by bradmac** [comment]
> When low quality image appears - it looks very huge and ugle on screen

This is ok

**Comment by bradmac** [comment]
> Aspect ratio for image when uploading is bad

If this only affects how the image looks when uploading then we can ignore it

Its only an issue if the image itself is saved with the incorrect aspect ratio

**Comment by Uafinder** [comment]
Nah, ok ignoring
