### ISSUE TITLE
Can't select asset type to create new asset for badge

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6609]
![image](https://user-images.githubusercontent.com/1945230/51534823-84c0fa80-1e4f-11e9-9b7c-3f49f22e0de8.png)
http://vladtest56ccc.admin.kademi-ci.co/recognition/18629199/badges/18629569/#attributes-tab
http://vladtest56ccc.admin.kademi-ci.co/content-types/

Needed for bagdes in Vaya
https://github.com/Kademi/client-vaya-vayability/issues/147

**Comment by Uafinder** [comment]
Doesn't help
http://vladtest56ccc.admin.kademi-ci.co/content-types/recognition/
Here is a type
And same no possibility to select
http://vladtest56ccc.admin.kademi-ci.co/recognition/18629199/badges/18629569/#attributes-tab

**Comment by Uafinder** [comment]
Also pls note that in Vaya there is no such possibility too, but there was such possibility earlier

**Comment by bradmac** [comment]
Fixed

**Comment by Uafinder** [comment]
Looks good
