### ISSUE TITLE
KCom2: points only checkout should set an appropriate reason text on the debit

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6611]
Eg, should be soemthing like "Purchase 1 x Sharp R395YS Inverter Sensor Microwave with Stainless Steel Fascia"

This should appear in the admin where debits are displayed, and in transactions components

**Comment by Uafinder** [comment]
Missed here
![image](https://user-images.githubusercontent.com/1945230/51742435-6acb2600-20a2-11e9-9abb-dd3575a86fcd.png)
http://vladtest56ee.admin.kademi-ci.co/manageUsers/18696866/#summary-tab

And here
http://vladtest56ee.admin.kademi-ci.co/manageUsers/18696866/#pointsBucketTab-tab
![image](https://user-images.githubusercontent.com/1945230/51742487-90582f80-20a2-11e9-85c2-9da9192d5b0d.png)

And here
![image](https://user-images.githubusercontent.com/1945230/51742507-a36aff80-20a2-11e9-8d19-f19f69c61ca2.png)
http://vladtest56ee.admin.kademi-ci.co/points-buckets/points-1/?startDate=19%2F01%2F2019&finishDate=25%2F01%2F2019&dataQuery=&startPos=0#debits-tab

And here
![image](https://user-images.githubusercontent.com/1945230/51742535-b2ea4880-20a2-11e9-817d-bc11b4bc21aa.png)
http://vladtest56ee.admin.kademi-ci.co/points-buckets/points/#points-tab

And here
![image](https://user-images.githubusercontent.com/1945230/51742618-fba20180-20a2-11e9-872d-2331da6e2620.png)
http://vladtest56eeweb-vladtest56ee.kademi-ci.co/profile/

So where you changed that?

**Comment by bradmac** [comment]
@Uafinder the reason is stored on the debit record, so you will see the same text in every location which displays it.

**Comment by bradmac** [comment]
@Uafinder note this issue refers to "points only checkout"

But your site is using the normal checkout form:

![image](https://user-images.githubusercontent.com/826458/51794106-ac89d700-2230-11e9-901f-d12998307f13.png)

Please update your checkout page to use the points only checkout component;

![image](https://user-images.githubusercontent.com/826458/51794114-c9bea580-2230-11e9-978c-91c05dbb1e8c.png)

**Comment by Uafinder** [comment]
Ok, looks good
