### ISSUE TITLE
EDM richtext editor issue

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#6614]
http://kcrm.kademi.us/leads/67151445/

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/51585308-76d0af80-1f0b-11e9-9f66-785e078f2e1f.png)

**Comment by anhnt** [comment]
Requires admin-lib 1.3.3

**Comment by Uafinder** [comment]
Looks good
