### ISSUE TITLE
Error when uploading and updating profiles

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#6616]
This is the user who was uploaded but had an existing profile http://kademi.admin.kademi.us/manageUsers/15870465/#summary-tab

This is the group they should have been added to, and whcih would have started a journey.
http://kademi.admin.kademi.us/groups/67185238/members/

Result from the error file:
"Exception - failed to lazily initialize   a collection of role: io.milton.vfs.db.Group.groupMemberships, could not   initialize proxy - no   Session","kademi","XXXXX@XXXXXXX","XXX","XXXXXXX","XXXXXXXXX"

This happened to around 52 profiles in the same upload.

--

**Comment by bradmac** [comment]
Closing as duplicate
