### ISSUE TITLE
Kcom2: Create singleProductEDMComponent

### ISSUE THREAD

**Issue by trungjc** [Kademi/kademi-dev#6618]
Create singleProductEDMComponent in Kcom2

**Comment by anhnt** [comment]
We will allow user to enter product code manually ie with simple text box atm

**Comment by anhnt** [comment]
https://github.com/Kademi/kademi-dev/issues/6621

**Comment by trungjc** [comment]
![screenshot_4](https://user-images.githubusercontent.com/704946/51660409-38f18b00-1fe0-11e9-9c5e-88bcde52eb1f.png)

kcom2SingleProductEDMComponent was created

**Comment by Uafinder** [comment]
There are two components for single product
![image](https://user-images.githubusercontent.com/1945230/51682693-b1604800-1ff0-11e9-8cdc-5c3b4f385127.png)
http://vladtest56dd.admin.kademi-ci.co/groupEmails/18662504/edmeditor?fileName=index.html&useHash=true

**Comment by trungjc** [comment]
The components are duplicated because they exist in Kcom2 and rewardstore-lib, and both libs are enabled.

![screenshot_8](https://user-images.githubusercontent.com/704946/51724705-21bea600-2091-11e9-8e5f-c2ffe3b7c926.png)
![screenshot_9](https://user-images.githubusercontent.com/704946/51724706-22573c80-2091-11e9-8176-e87e1e82c9e7.png)

**Comment by Uafinder** [comment]
Ok, looks good
