### ISSUE TITLE
Asset content editor container background error

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#6619]
![image](https://user-images.githubusercontent.com/735555/51651229-bb1c8800-1fbd-11e9-978d-c53c7275cc20.png)

**Comment by anhnt** [comment]
https://spinsurance.admin.kademi.com.au/asset-manager/064d4b19-bad4-4a8d-873f-b9dc69d90560

**Comment by anhnt** [comment]
Fixed and applied to Au

**Comment by anhnt** [comment]
requires keditor-lib 1.3.5

**Comment by Uafinder** [comment]
Looks good
