### ISSUE TITLE
Create new asset from badge success message bad

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6623]
![image](https://user-images.githubusercontent.com/1945230/51680712-2d579180-1feb-11e9-9c7b-4d9d4514fef7.png)
![image](https://user-images.githubusercontent.com/1945230/51680750-419b8e80-1feb-11e9-869a-22801f0692f6.png)
http://vladtest56dd.admin.kademi-ci.co/recognition/18661962/badges/18661972/#attributes-tab

**Comment by bradmac** [comment]
Fixed

Required KRecognition 1.1.2

**Comment by Uafinder** [comment]
looks good
