### ISSUE TITLE
Create leads from admin console success message bad

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6624]
![image](https://user-images.githubusercontent.com/1945230/51681517-7dcfee80-1fed-11e9-9399-69f595607be9.png)
http://vladtest56dd.admin.kademi-ci.co/manageUsers/18662257/#funnelsTab-tab
![image](https://user-images.githubusercontent.com/1945230/51681524-86282980-1fed-11e9-9323-380b0aa7d108.png)
![image](https://user-images.githubusercontent.com/1945230/51681532-8b857400-1fed-11e9-84bc-ab6f0a379bac.png)

**Comment by anhnt** [comment]
Fixed this on 1.0.9 and requires admin-lib 1.4.3
Also fixed same issue in email tab, requires email-lib 1.1.9
Also fixed this in products-lib 1.1.7

@Uafinder please try on some other tabs if you can see this similar issue please post here

**Comment by Uafinder** [comment]
Looks good
