### ISSUE TITLE
Error when edit storeCheckout component

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6625]
http://vladtest56dd.admin.kademi-ci.co/websites/vladtest56ddweb/version1?editTemplate=theme/apps/KCommerce2/storeCheckout
![image](https://user-images.githubusercontent.com/1945230/51681982-e8cdf500-1fee-11e9-96d1-86af95c08ee0.png)

**Comment by trungjc** [comment]
Update on version 1.8.0

**Comment by Uafinder** [comment]
looks good
