### ISSUE TITLE
Event registration page should show dates/times in user's current timezone based on their Geo IP

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6627]

**Comment by Uafinder** [comment]
Can see this change
![image](https://user-images.githubusercontent.com/1945230/51746584-52153d00-20af-11e9-9ed4-2cecae8492ee.png)
http://vladtest56eeeweb-vladtest56eee.kademi-ci.co/Calendars/cal1/test3/

**Comment by bradmac** [comment]
Works for me..
![image](https://user-images.githubusercontent.com/826458/51794133-2ae67900-2231-11e9-8e51-a0730f4a7586.png)

I think we've seen that previously, that the Geo IP service doesnt always pickup your location

**Comment by bradmac** [comment]
Here's what i get on browserstack

![image](https://user-images.githubusercontent.com/826458/51794150-6123f880-2231-11e9-8264-0a433019f6ea.png)

**Comment by Uafinder** [comment]
ok
