### ISSUE TITLE
Duplicate calendar events

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6628]
Also, should show a past events panel on the calendar management page, so the user can duplicate past events

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/51714664-db6e4480-209a-11e9-88cd-e55973669e4d.png)

**Comment by bradmac** [comment]
Done. Requires platform update and calendar-lib 1.2.9

**Comment by Uafinder** [comment]
Past events area shows incorrect event inside
![image](https://user-images.githubusercontent.com/1945230/51737309-e625db00-2094-11e9-8f72-74c63bc091b3.png)
http://vladtest56ee.admin.kademi-ci.co/Calendars/cal1/

organisor is not copying when duplicate
![image](https://user-images.githubusercontent.com/1945230/51737572-9b589300-2095-11e9-9b5e-cc48176ad812.png)
http://vladtest56ee.admin.kademi-ci.co/Calendars/cal1/event-1548409014855#details-tab

confirmation tab is not copying when duplicate
![image](https://user-images.githubusercontent.com/1945230/51737607-b2978080-2095-11e9-8196-fb73aca948a2.png)
http://vladtest56ee.admin.kademi-ci.co/Calendars/cal1/event-1548409014855#details-tab

**Comment by bradmac** [comment]
> But seeing that Past events show only recently ended events

The common date range selector is used for past events:

![image](https://user-images.githubusercontent.com/826458/51866412-cd2b6b80-23ad-11e9-89c4-fb653c49eb33.png)

**Comment by bradmac** [comment]
> (duplicating) Still doesn't work for me

Looks good to me:

http://vladtest56f.admin.kademi-ci.co/Calendars/calendar%20name/event-1548709789727#confirmation-tab

![image](https://user-images.githubusercontent.com/826458/51866562-298e8b00-23ae-11e9-9a4c-3355df530495.png)

If you see a problem please tell me which fields are empty, on which event, and which event you duplicated from

**Comment by Uafinder** [comment]
yup, looks good now
