### ISSUE TITLE
4 columns with content conponent two images bad

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6629]
![image](https://user-images.githubusercontent.com/1945230/51734586-9f80b280-208d-11e9-9d9d-445fdfad4041.png)
http://vladtest56ee.admin.kademi-ci.co/asset-manager/e6ced9d8-0cfe-4d88-9c27-33a2ae4b25a7

**Comment by anhnt** [comment]
i think this should be closed as we have this clearer one https://github.com/Kademi/kademi-dev/issues/6709
