### ISSUE TITLE
There is a possibility to pass quiz with incorrect answers when quiz in the middle of the module

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#663]
There is a possibility to pass quiz with incorrect answers when quiz in the middle of the module.
http://asmi-demo.olhub.com/programs/VWAG_1/C2_test/TEST/
Steps to reproduce:
1. Read the pages until the quiz page
2. On quiz page click submit or next (no matter of answers selected or not)
3. There will be an error about incorrect answers
4. On the botton pages listing link to the next after quiz page will become available.
5. Click on it.
6. You passed the quiz.
![image](https://cloud.githubusercontent.com/assets/1945230/9566802/a82907c6-4f1b-11e5-95a8-d9de88a4350b.png)

**Comment by tuzzmaniandevil** [comment]
This has now been fixed

**Comment by Uafinder** [comment]
No, it's not. Tested on Deloitte site on prod!

**Comment by tuzzmaniandevil** [comment]
Please note that the milestone 2015-08-m3 hasn't been released yet. So this fix isnt on prod or beta yet.
