### ISSUE TITLE
Badge asset layout page bad

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6631]
![image](https://user-images.githubusercontent.com/1945230/51735669-ab21a880-2090-11e9-82bb-b74099e28ea0.png)
http://vladtest56ee.admin.kademi-ci.co/recognition/18698377/badges/18698378/#attributes-tab
Field headers are "how to earn" and ''description"

**Comment by Uafinder** [comment]
Looks bad for me
![image](https://user-images.githubusercontent.com/1945230/51821648-92a8cc80-22e2-11e9-9c90-9aef2ac29fc5.png)
http://vladtest56f.admin.kademi-ci.co/recognition/18712208/badges/18712225/#attributes-tab

to reproduce
- Fresh account
- install krecog app
- create asset type
- create badge
- create asset for it
- check badge asset tab layout

**Comment by bradmac** [comment]
@trungjc can you please look into the layout issue?

**Comment by bradmac** [comment]
and @trungjc please assign to me to review when done

**Comment by trungjc** [comment]
![screenshot_1](https://user-images.githubusercontent.com/704946/51884893-b429b700-23bb-11e9-9d1e-598447bf41f2.png)

Fixed

**Comment by bradmac** [comment]
code review done, looks good.

**Comment by Uafinder** [comment]
Looks fine
