### ISSUE TITLE
Joruneys page bad when only journey app installed

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6632]
![image](https://user-images.githubusercontent.com/1945230/51737115-7adc0900-2094-11e9-85b3-07aad44608c2.png)
http://vladtest56ee.admin.kademi-ci.co/leads/
![image](https://user-images.githubusercontent.com/1945230/51737157-97784100-2094-11e9-9cb0-ef27560fd056.png)

**Comment by anhnt** [comment]
When using journey and leadman, the only app which needs to install is KLeadman app from store

**Comment by Uafinder** [comment]
If so, we could remove kJourney app from marketplace?

**Comment by bradmac** [comment]
> If so, we could remove kJourney app from marketplace?

Apps should **only** be installed from the marketplace. If you're installing apps by enabling them directly ... please dont!

> So looks like we need to disable this menu item for kjourney install

If you install KJourneys from the marketplace as intended you wont see any problem.

What would be a bug is if some app installed Funnels and not KJourneys. If you see that somewhere please create an issue related for that app.

**Comment by Uafinder** [comment]
Steps to reproduce
1. Fresh account
2. Create website
3. Install Kjourneys via marketplace
![image](https://user-images.githubusercontent.com/1945230/51821333-748e9c80-22e1-11e9-8500-d39eb2071772.png)
4. This process adds two menu items
![image](https://user-images.githubusercontent.com/1945230/51821382-a0aa1d80-22e1-11e9-8885-5018366e6970.png)
5. journeys menu leads here
![image](https://user-images.githubusercontent.com/1945230/51821389-a6076800-22e1-11e9-8aca-4ae03a0399f2.png)
http://vladtest56f.admin.kademi-ci.co/leads/

**Comment by bradmac** [comment]
Fixed. I've added leadman-lib as a dependency of KJourneys

**Comment by Uafinder** [comment]
Looks good
