### ISSUE TITLE
Kproducts app depends on deprecated rewardstore-lib

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6633]
KProducts app depends on rewardstore lib
and KCom2 depends on KProducts 😃
so as a result, installing KCom2 will install KProducts and will install rewardstore lib
Which is incorrect
![image](https://user-images.githubusercontent.com/1945230/51742102-723dff80-20a1-11e9-98fe-513480a74d1f.png)

**Comment by bradmac** [comment]
Hey @anhnt it looks like these dependencies were added by you in the move of admin resources to admin-lib

Do you know why that was? This app definitely should not depend on reward stores. Its the other way around, apps like KCom2 and KRewardStore which need product management will depend on KProducts.

**Comment by anhnt** [comment]
Updated KProducts as below. Rewardstore-lib was added by mistake i think

![image](https://user-images.githubusercontent.com/735555/52778326-5ca47000-3078-11e9-8478-163285c9b2dd.png)

**Comment by Uafinder** [comment]
Ok, looks good
