### ISSUE TITLE
Auction date tips are showing incorrect timezone

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6634]
Pls note that tips on dashboard shows incorrect date/time timezone
![image](https://user-images.githubusercontent.com/1945230/51745720-73c0f500-20ac-11e9-95d1-e1ad7303dd03.png)
http://vladtest56eeeweb-vladtest56eee.kademi-ci.co/dashboard
http://vladtest56eee.admin.kademi-ci.co/edit/

Same here
![image](https://user-images.githubusercontent.com/1945230/51745781-a1a63980-20ac-11e9-9b07-5a14ef947fc4.png)
http://vladtest56eeeweb-vladtest56eee.kademi-ci.co/auctions/auc1-1/

comes from here
https://github.com/Kademi/kademi-dev/issues/6602

**Comment by bradmac** [comment]
Moved to p2

**Comment by trungjc** [comment]
![screenshot_14](https://user-images.githubusercontent.com/704946/51959025-4053e100-2485-11e9-97cc-ea222fd12379.png)
![screenshot_15](https://user-images.githubusercontent.com/704946/51959026-40ec7780-2485-11e9-8c37-215efaf53bea.png)

http://trungtestsite-trung.kademi-ci.co/dashboard
http://trung.admin.kademi-ci.co/auctions/auction-2/#details-tab
http://trungtestsite-trung.kademi-ci.co/auctions/auction-2/

Timezone was added

**Comment by Uafinder** [comment]
Yup, looks good
