### ISSUE TITLE
Event label bad on dashboard

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6635]
![image](https://user-images.githubusercontent.com/1945230/51746644-812bae80-20af-11e9-8a32-c6c805d83cfd.png)
http://vladtest56eeeweb-vladtest56eee.kademi-ci.co/dashboard

**Comment by bradmac** [comment]
@trungjc can you make this look nicer?

**Comment by trungjc** [comment]
![screenshot_3](https://user-images.githubusercontent.com/704946/51825036-7c1c6880-2316-11e9-8397-cea34e5efce2.png)

Update in version 1.3.1

**Comment by bradmac** [comment]
@trungjc just overriding a bootstrap semantic class to change its colour is not cool. 

Other developers who need to customise the site wont know about your special rule, so you'll cause them headaches.

Instead, please apply normal, correct, bootstrap semantic classes.

**Comment by trungjc** [comment]
![screenshot_3](https://user-images.githubusercontent.com/704946/51885427-feac3300-23bd-11e9-981b-d5e5f7d7adc8.png)

Replace alert to panel

**Comment by bradmac** [comment]
@trungjc i think that looks a bit too heavy. instead of a box around each event, how about we just have a hr between them?

**Comment by trungjc** [comment]
![screenshot_7](https://user-images.githubusercontent.com/704946/51891901-032f1680-23d3-11e9-9a52-ae9a62a3c569.png)

**Comment by bradmac** [comment]
looks good, thanks

**Comment by Uafinder** [comment]
Cools
