### ISSUE TITLE
Journeys with forks appear to not get indexed correctly

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6636]
Needed for https://github.com/Kademi/client-vaya-vayability/issues/411

**Comment by bradmac** [comment]
Pushed a fix ... need to see if it solves the problem in prod

**Comment by Uafinder** [comment]
I spot that issue again today on Vaya account. Looks like it happened after regular lead node change
![image](https://user-images.githubusercontent.com/1945230/52336682-347c9780-2a0e-11e9-8bb2-252f89f1c90e.png)
![image](https://user-images.githubusercontent.com/1945230/52336706-45c5a400-2a0e-11e9-85a2-c5eb019f0d69.png)
As a result manager user didin't see his regular assignee's.
http://vayability.admin.kademi.us/manageUsers/63428702/#summary-tab
![image](https://user-images.githubusercontent.com/1945230/52336821-9a691f00-2a0e-11e9-98f5-56a271c87992.png)
I will re-index account, to fix that issue for Vaya.

**Comment by bradmac** [comment]
Pushed a change which might resolve it. Lets try it out.

**Comment by bradmac** [comment]
OK, couple of weird things seen and fixed
- there was a custom field "leadId" which was overwriting the standard field with the same name. I'm not sure what consequence this will have if any. It was being set to the source lead, but there is actually a property on the lead to refer to the source lead so this might be leftovers from the first version
- the main issue was that custom app indexers were not being run correctly. This was not obvious, because  there was a field with the same name, and for reasons which arent clear sometimes that was set and other times not. But in all cases the custom app indexer wasnt working. Fixing the custom app indexer appears to have resolved it

**Comment by Uafinder** [comment]
Looks good now
i will keep an eye on it
