### ISSUE TITLE
Icon bad when add field to a query

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6637]
![image](https://user-images.githubusercontent.com/1945230/51821956-70637e80-22e3-11e9-94f5-9f3671b45ea4.png)
http://vladtest56f.admin.kademi-ci.co/queries/test1/#queryResult-tab

**Comment by bradmac** [comment]
fixed needs reporting-lib 1.4.5

**Comment by bradmac** [comment]
This is low priority, but a quick update.

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/51903049-0d95e400-23c4-11e9-91eb-f3ec053e442b.png)

Issue appears but now with a different case
![image](https://user-images.githubusercontent.com/1945230/51903020-fd7e0480-23c3-11e9-8084-dc96cebcfad9.png)
http://vladtest56g.admin.kademi-ci.co/queries/query1/#queryResult-tab

**Comment by trungjc** [comment]
![screenshot_10](https://user-images.githubusercontent.com/704946/51905786-c8d67100-23f4-11e9-89ef-615927acb5fb.png)

Missing fontwaesome class. Fix in version 1.4.6

**Comment by Uafinder** [comment]
good
