### ISSUE TITLE
JS error when add field to a query

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6638]
![image](https://user-images.githubusercontent.com/1945230/51822005-925d0100-22e3-11e9-8c1a-8ea2fb550421.png)
http://vladtest56f.admin.kademi-ci.co/queries/test1/#queryResult-tab

To rerpoduce
![image](https://user-images.githubusercontent.com/1945230/51822017-9e48c300-22e3-11e9-8305-42201db69d1f.png)
Add some field and push save

**Comment by bradmac** [comment]
There was some logic to set the tab on page reload which i've commented out

**Comment by bradmac** [comment]
needs reporting-lib 1.4.5

**Comment by Uafinder** [comment]
Looks good
