### ISSUE TITLE
Decimal places option doesn't work in checkout cart component by default

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6639]
![image](https://user-images.githubusercontent.com/1945230/51824719-ba506280-22eb-11e9-997c-074a594f0e81.png)
http://vladtest56eeweb-vladtest56ee.kademi-ci.co/vladtest56eeweb-ecomstore/cart
![image](https://user-images.githubusercontent.com/1945230/51824738-c3d9ca80-22eb-11e9-9c95-597b48720740.png)
http://vladtest56ee.admin.kademi-ci.co/websites/vladtest56eeweb/version1?editTemplate=theme/apps/KCommerce2/storeCheckout

**Comment by bradmac** [comment]
@trungjc please fix this, then assign to me to review before vlad tests it.

**Comment by trungjc** [comment]
It is a display issue. So I changed default decimal place to 2. I think 2 is more general than 0.

**Comment by Uafinder** [comment]
looks good
