### ISSUE TITLE
points only component success message missed username

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6640]
![image](https://user-images.githubusercontent.com/1945230/51824861-17e4af00-22ec-11e9-9297-c1680268cc8c.png)
http://vladtest56eeweb-vladtest56ee.kademi-ci.co/vladtest56eeweb-ecomstore/cart
http://vladtest56ee.admin.kademi-ci.co/manageUsers/18696866

**Comment by bradmac** [comment]
I've jsut removed the first name part of the template, its not needed, i'm sure the customer knows who the message is for!

**Comment by bradmac** [comment]
needs kcom2 1.8.1

**Comment by Uafinder** [comment]
Looks good
