### ISSUE TITLE
Updating the Notes for a Group overwrites all other Groups’ notes

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#6644]
Waterware is using the notes section quite a lot.

https://waterware.admin.kademi.com.au/groups/

**Comment by bradmac** [comment]
There is a bug, but its actually not overwriting anything. I've checked and what i can see is the browser is restoring user input to that field. Doing a hard refresh and then opening another group shows whatever notes it had before, if any.

**Comment by bradmac** [comment]
@trungjc this looks like a simply client side JS issue. 

Please assign to me for review when done.

**Comment by trungjc** [comment]
@bradmac please check it http://trung.admin.kademi-ci.co/groups/

**Comment by bradmac** [comment]
Looks good, thanks.

**Comment by Uafinder** [comment]
Looks good
