### ISSUE TITLE
Constraint violation problem in Vaya CI when submit form with journey attached

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6645]
To reproduce
Enable this journey
http://vayability.admin.kademi-ci.co/funnels/example-request-coach-badge/version1/#journeyBuilder-tab
this user
http://vayability.admin.kademi-ci.co/manageUsers/18327516
this page
http://vayability-vayability.kademi-ci.co/request-coaching-session.html
This error
[error-vaya.txt](https://github.com/Kademi/kademi-dev/files/2806830/error-vaya.txt)

**Comment by bradmac** [comment]
I disabled the journey, but have now also removed the constraint from CI that was the source of the problem
