### ISSUE TITLE
Make queries feature available by default in account (move to admin-lib)

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6646]
I've created a new account and install several apps:
- blogs, journeys, krecognition, calendar
And trying to use queries, but can't access queries page
![image](https://user-images.githubusercontent.com/1945230/51900037-fa334a80-23bc-11e9-815b-776829dc59e0.png)
http://vladtest56g.admin.kademi-ci.co/queries/
Those link will work most like because i will continue testing

**Comment by bradmac** [comment]
requires admin-lib 1.3.6

**Comment by Uafinder** [comment]
Looks good
