### ISSUE TITLE
Issue with points only checkout component

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6647]
![image](https://user-images.githubusercontent.com/1945230/51905332-a1b67a00-23c9-11e9-80b8-206063c7a6bf.png)
This user
http://vladtest56g.admin.kademi-ci.co/manageUsers/18719695/#summary-tab
He has 1000 points
kCom2 setup

**Comment by trungjc** [comment]
The cause in from "Order Summary" in left block. Please don't enable "Allow customers to use points against their total" in checkout point only

![screenshot_10](https://user-images.githubusercontent.com/704946/52834763-fc640b80-3115-11e9-825b-1d8b4c405f47.png)

**Comment by Uafinder** [comment]
looks good
