### ISSUE TITLE
icon issue for search box in keditor

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6648]
![image](https://user-images.githubusercontent.com/1945230/51905771-d971f180-23ca-11e9-8bca-9634d371ee2c.png)
http://vladtest56g.admin.kademi-ci.co/websites/vladtest56gweb/version1?editTemplate=theme/defaultThemeTemplate

**Comment by trungjc** [comment]
![screenshot_17](https://user-images.githubusercontent.com/704946/51959689-2e277200-2488-11e9-8610-727b41224261.png)

Gyphicon font-family was override to Font Awesome in [migration.css](http://trung.admin.kademi-ci.co/repositories/fontawesome-lib/5.5.0.2/common/theme/apps/fontawesome-lib/#files-tab). Should we remove it?

**Comment by bradmac** [comment]
@trungjc yes, we've standardised on fontawesome so we dont need to maintain support for Gyphicon

**Comment by trungjc** [comment]
![screenshot_5](https://user-images.githubusercontent.com/704946/52054402-f8b97c00-258e-11e9-9224-8214e2922a70.png)

Replaced Gyphicon by Font awesome in search-lib version 1.2.0

**Comment by Uafinder** [comment]
looks good
