### ISSUE TITLE
KFeedback fixups

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6651]
Seen here - http://vayability.admin.kademi.us/kfeedback/#!/surveys/list

- remove date range selectors, all pages should use the common date range selector (BM: see @trungjc's comment that we cant remove for the one chart)

![image](https://user-images.githubusercontent.com/826458/52021554-86c73f80-255a-11e9-9cea-b7fab85ec7bd.png)

![image](https://user-images.githubusercontent.com/826458/52021567-947cc500-255a-11e9-87ca-2d8bb768952c.png)

- note the report page doesnt seem to work currently, but should be fixed by the above task

- add a CSV export for responses

**Comment by trungjc** [comment]
@bradmac 
I have added CSV Export button and replace Daterange picker to common date range selector in [feedback report page](http://trung.admin.kademi-ci.co/kfeedback/#!/surveys/testfeedback/report)

But date range picker at [Analytic](http://trung.admin.kademi-ci.co/kfeedback/#!/surveys/testfeedback) is a part of higchart. It seem that they does not public a API to set this range

**Comment by bradmac** [comment]
> But date range picker at [Analytic](http://trung.admin.kademi-ci.co/kfeedback/#!/surveys/testfeedback) is a part of higchart. It seem that they does not public a API to set this range

OK, we can leave that for now then.

**Comment by Uafinder** [comment]
Feedback export weird date
![image](https://user-images.githubusercontent.com/1945230/52786042-6c18be80-3062-11e9-9213-669dfddb30de.png)
http://vladtest56p.admin.kademi-ci.co/kfeedback/#!/surveys/feed1/report

Also, processed checkbox doesn't work
When you select checkbox
![image](https://user-images.githubusercontent.com/1945230/52786230-0547d500-3063-11e9-9c76-d72b98f469e5.png)
http://vladtest56p.admin.kademi-ci.co/kfeedback/#!/surveys/feed1/report
But when you refresh processed not appear (both page and CSV)
![image](https://user-images.githubusercontent.com/1945230/52786278-290b1b00-3063-11e9-9796-2a551d6bee5e.png)

**Comment by trungjc** [comment]
Updated in v1.3.2

**Comment by bradmac** [comment]
@trungjc comment here:
https://github.com/Kademi/kademi-dev/commit/ed93f6ba9d8e531a8427dc3540f48f37c23060ca#r32351003

**Comment by trungjc** [comment]
Updated on v1.3.3

**Comment by bradmac** [comment]
Comments
https://github.com/Kademi/kademi-dev/commit/d0d026d204c4f5b286799a5c983d6e0afbcba07a#r32363110

https://github.com/Kademi/kademi-dev/commit/d0d026d204c4f5b286799a5c983d6e0afbcba07a#r32363088

**Comment by trungjc** [comment]
Remove comma and add sort clause

**Comment by Uafinder** [comment]
Ok, looks good.
Two different issues moved to another issues.
