### ISSUE TITLE
Carousel next and previous icons preview bad

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6652]
![image](https://user-images.githubusercontent.com/1945230/52043726-1d8b0080-2549-11e9-8a61-0b5d5cd148c2.png)
http://vladtest56j.admin.kademi-ci.co/pages/vladtest56jweb/version1/?contenteditor=index.html
Frontend is ok

**Comment by trungjc** [comment]
![screenshot_6](https://user-images.githubusercontent.com/704946/52067311-e9e1c200-25ac-11e9-845e-b50f48469745.png)

Fixed in version 5.5.0.3 font-awesome-lib

**Comment by trungjc** [comment]
Because the carousel in bootstrap use glyphicon icon class to make style.
So I will add some style it will make the same for Font Awesome

**Comment by trungjc** [comment]
![screenshot_4](https://user-images.githubusercontent.com/704946/52121539-8dd17900-2652-11e9-88e6-bcce233a8c7d.png)
![screenshot_5](https://user-images.githubusercontent.com/704946/52121541-8dd17900-2652-11e9-8a12-c1313aa2d7b8.png)

Update in keditor-lib v1.3.7 and bootstrap-base-lib v2.0.7

**Comment by Uafinder** [comment]
looks good
