### ISSUE TITLE
rewardstore-lib discuss

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6653]
Hey Brad
should we change app dependencies to avoid install rewardstore-lib as it's deprecated?
Because when i install kCom2 or kAuctions it enable this deprecated lib and make a mess with selecting components and configuring options.
what do you think?

**Comment by bradmac** [comment]
The only thing which should depend on rewardstore-lib is KRewardStore ... anything else is a bug

**Comment by bradmac** [comment]
removed from KPRoducts

**Comment by bradmac** [comment]
Looks like that was the only incorrect one.

This was added to KProducts by Anh as part of the move to admin-lib. I guess he did that for some reason, so removing it will probably cause some problem. But we'll solve that problem by moving or copying files into the correct libs, so we dont need everything to depend on rewardstore-lib

**Comment by Uafinder** [comment]
Fresh account.
![image](https://user-images.githubusercontent.com/1945230/52121052-fc004680-2626-11e9-8b34-15cf52e03bb0.png)
I've installed Kcom2 from marketplace and it installed rewardstore-lib to me
http://vladtest56k.admin.kademi-ci.co/manageApps/#installed-tab

Also KAuctions
http://vladtest56kk.admin.kademi-ci.co/websites/vladtest56kkweb/version1/#panel_apps-tab
![image](https://user-images.githubusercontent.com/1945230/52121974-2273b100-262a-11e9-9a0a-933215a0d9b3.png)

**Comment by bradmac** [comment]
Auctions had a dependency on rewardstore, which is removed now

**Comment by bradmac** [comment]
KAuctions now depends on rewards app and rewards-lib.

Moved admin menu items from rewardstore to rewards app

**Comment by Uafinder** [comment]
Ok, looks good
