### ISSUE TITLE
Org Search on users page not working

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#6655]
http://kcrm.kademi.us/leads/67543233/?view=detail

Hi Guys, 

In Swimart Academy, the org function from the individual profile screen doesn't work. When entering orgs, it fails to recognise anything. Screen grab to follow.

Link: http://swimart.admin.kademi.com.au/manageUsers/139289208/#summary-tab

**Comment by bradmac** [comment]
Fixed, needs platform update
