### ISSUE TITLE
KCom2: Add configuration option to product parameters to choose display as image or text

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6656]
Needed for https://github.com/Kademi/client-carters/issues/360

**Comment by bradmac** [comment]
Requires a platform update (db change) and kcom2 1.8.3

**Comment by bradmac** [comment]
Added management option:
![image](https://user-images.githubusercontent.com/826458/52184618-94dad000-287a-11e9-90b0-0f6867d664c2.png)

And front end like..
![image](https://user-images.githubusercontent.com/826458/52184634-afad4480-287a-11e9-9daf-e45a9b1c7060.png)

**Comment by Uafinder** [comment]
Looks good
