### ISSUE TITLE
Export Utility for Addresses

### ISSUE THREAD

**Issue by faithtek** [Kademi/kademi-dev#6657]
Need to create an export utility for the new Address Component found under Profile (as seen below).

![image3](https://user-images.githubusercontent.com/7914822/52183571-082b0600-27d7-11e9-8e77-032ff94f3e42.png)

Export should include the following:
- UserId
- Kademi ID
- First Name
- Surname/Last Name
- Phone
- Email
.
- Address Type Name for First Address ("Home")
- "Home" Address Line 1
- "Home" Address Line 2
- "Home" City
- "Home" State
- "Home" Postcode
- "Home" Country
.
- Address Type Name for Second Address ("Work")
- "Work" Address Line 1
- "Work" Address Line 2
- "Work" City
- "Work" State
- "Work" Postcode
- "Work" Country

Would also be nice to be able to export "Work" addresses as a separate file, "Home" addresses as a separate file, and then both as a combined file.

**Comment by faithtek** [comment]
Also, need an Elastic Index for Addresses.

**Comment by bradmac** [comment]
Added to profile app indexer:

![image](https://user-images.githubusercontent.com/826458/53272475-4ec8ac00-3756-11e9-8910-a093dbb511d3.png)


And created report:
![image](https://user-images.githubusercontent.com/826458/53272259-a0bd0200-3755-11e9-85d8-25adea8326be.png)


Requires user-lib 1.4.8 and platform update

Also requires reindexing "profile"

**Comment by Uafinder** [comment]
Looks good
