### ISSUE TITLE
Add dependency to show points bucket and other points features when install Kcom2

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6661]
Add dependency to show points bucket and other points features when install Kcom2
![image](https://user-images.githubusercontent.com/1945230/52206415-d1122e80-2882-11e9-9a2f-ad81f6861aec.png)
http://vladtest56l.admin.kademi-ci.co/manageApps/#installed-tab

**Comment by bradmac** [comment]
OK, we do not want to show reward stores, but we do want Reward Points and Points Buckets

**Comment by bradmac** [comment]
Fixed by other issues.

Points buckets etc (but not reward stores) are available by installing KPromotions

**Comment by Uafinder** [comment]
Ok, looks good
