### ISSUE TITLE
Button link settings dont work in chrome

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6664]
![image](https://user-images.githubusercontent.com/826458/52251741-9633f780-2963-11e9-8fc1-b49e9df58b7f.png)

**Comment by anhnt** [comment]
works ok on chrome atm 

![image](https://user-images.githubusercontent.com/735555/52546841-1095c900-2df5-11e9-8c0b-b84270541f74.png)

**Comment by Uafinder** [comment]
Reproduced here
http://vladtest56n.admin.kademi-ci.co/pages/vladtest56nweb/version1/?contenteditor=page1.html

**Comment by anhnt** [comment]
seems good after updating all libs

**Comment by Uafinder** [comment]
Looks good
