### ISSUE TITLE
Multiple click issue when create page

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6665]
http://vladtest56l.admin.kademi-ci.co/websites/vladtest56lweb/version1/programs/p1/c1/m1/#files-tab
![image](https://user-images.githubusercontent.com/1945230/52260182-eb551680-292d-11e9-9323-bd8c459ee473.png)
![image](https://user-images.githubusercontent.com/1945230/52260685-8b5f6f80-292f-11e9-8474-26691be4a816.png)

**Comment by anhnt** [comment]
fixed in learner-lib 1.4.7

**Comment by Uafinder** [comment]
Ok, looks good
