### ISSUE TITLE
Placeholder text doesn't match in orgtype additional field

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6668]
Orgtype additional field has specified placeholder text here
![image](https://user-images.githubusercontent.com/1945230/52280279-32f69500-2964-11e9-8eb8-90dabf67ec29.png)
But when you go to organizations page it looks like this way
![image](https://user-images.githubusercontent.com/1945230/52280387-794bf400-2964-11e9-9760-1de034d8cb21.png)
http://vladtest56l.admin.kademi-ci.co/organisations/18752664/edit/

**Comment by bradmac** [comment]
This behaviour is correct

In the first screen the text box is for entering field options such as 'required', 'text', etc

In the second screen the text box is for entering the value, and if no 'text' attribute is provided it will use the field id

**Comment by Uafinder** [comment]
ok
