### ISSUE TITLE
Queries Not Keeping Sorting

### ISSUE THREAD

**Issue by faithtek** [Kademi/kademi-dev#6670]
Queries seem to forget sorting. When adding a specific sort into queries, they keep the sort for a couple days, then after a few days revert back to the non-specific sort/random sort.

**Comment by bradmac** [comment]
@faithtek they definitely will not change without you making an edit. You can see every file change in repository history by going to the "queries" repository

Please provide an example of a query which appears to have lost its sorting. We can then look at the repository history to see what changes have occured to that file.

**Comment by faithtek** [comment]
This is done through the Query Creator Interface. I just tried updating that query again. The sort is keeping so far, but I'll keep you updated. The change I made through the interface does not appear to have changed any of the files in the queries folder. Could that be the reason Sort is being lost? Is it being saved in a cache/memory somewhere, but never being saved to a file -- hence when cache/memory is cleared, the sort is also cleared?

**Comment by bradmac** [comment]
If you can see a situation where a query is 'saved' but the file is not changed, then that is a bug and please provide steps to reproduce that problem.

**Comment by faithtek** [comment]
This is in Nutra Blend. Although, I've seen the sort not save in other sites as well.

https://nutrablend.admin.kademi.us

I updated this query today. This query is also connected to the PointBalancesParticipants querytable.

![image1](https://user-images.githubusercontent.com/7914822/52369323-744b7b00-2a1e-11e9-865f-941bd8348337.png)

But as you can see here, even though I have saved the query, none of the current query files have changed.

![image2](https://user-images.githubusercontent.com/7914822/52369477-ce4c4080-2a1e-11e9-8939-e830c2b8b59d.png)

And if you were to look at query now, it would be sorted. But look at the same query tomorrow and it's no longer sorted and no longer has the sort field data in the query.

**Comment by bradmac** [comment]
I can see a slightly different problem. When i press the Save button with no changes, the query then does not appear:

![image](https://user-images.githubusercontent.com/826458/52383286-91934e80-2add-11e9-89ae-7e4e2755ed17.png)

after save..

![image](https://user-images.githubusercontent.com/826458/52383310-a1ab2e00-2add-11e9-95fc-02e86e904fc6.png)

I can then restore through the text editor to get back to the initial state

**Comment by bradmac** [comment]
Updated libs to fix the problem saving

**Comment by bradmac** [comment]
There were a few problems
- errors when saving were not reported to the UI, fixed
- there was a serialisation error with order by fields, fixed
- the cached object was being updated directly so the cache was being poisoned, fixed

**Comment by Uafinder** [comment]
Looks good
