### ISSUE TITLE
KCom2: Add delivery notes field

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6671]
we have an "orderNotes" field, but this is being used for internal uses. So we need a new field to capture delivery instructions

**Comment by bradmac** [comment]
this is now shown on the order detail page

![image](https://user-images.githubusercontent.com/826458/52307947-e7de8f80-2a00-11e9-9f18-04d6b9f37556.png)

**Comment by bradmac** [comment]
Requires platform update and kcom2 1.8.3

**Comment by Uafinder** [comment]
ok, looks good
