### ISSUE TITLE
KCom2: update storeProductList component to allow configuring currency symbol and position

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6672]

**Comment by bradmac** [comment]
I've removed the getDecimals function in app.js, this is not needed and we should instead use the appropriate formatter function

**Comment by bradmac** [comment]
I've removed the getDecimals function in app.js, this is not needed and we should instead use the appropriate formatter function

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/52313941-54638980-2a15-11e9-9e01-e5aa4f4fbd93.png)

**Comment by bradmac** [comment]
requires kcom2 1.8.4

**Comment by bradmac** [comment]
@Uafinder says..
----
![image](https://user-images.githubusercontent.com/1945230/52338013-e2d60c00-2a11-11e9-8bff-bcfbbb2b7884.png)
http://vladtest56mweb-vladtest56m.kademi-ci.co/vladtest56mweb-ecomstore/p4
![image](https://user-images.githubusercontent.com/1945230/52338054-f8e3cc80-2a11-11e9-80b2-d11aed13eb1b.png)
http://vladtest56mweb-vladtest56m.kademi-ci.co/vladtest56mweb-ecomstore/cart

**Comment by bradmac** [comment]
fixed, requires kcom2 1.8.5

**Comment by Uafinder** [comment]
Ok, looks better
