### ISSUE TITLE
kcom2: no price appears here

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6674]
![image](https://user-images.githubusercontent.com/1945230/52338013-e2d60c00-2a11-11e9-8bff-bcfbbb2b7884.png)
http://vladtest56mweb-vladtest56m.kademi-ci.co/vladtest56mweb-ecomstore/p4
![image](https://user-images.githubusercontent.com/1945230/52338054-f8e3cc80-2a11-11e9-80b2-d11aed13eb1b.png)
http://vladtest56mweb-vladtest56m.kademi-ci.co/vladtest56mweb-ecomstore/cart

**Comment by bradmac** [comment]
Moving issue here - https://github.com/Kademi/kademi-dev/issues/6672
