### ISSUE TITLE
kCom2: when postcode empty validation works on state field as well

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6676]
![image](https://user-images.githubusercontent.com/1945230/52420114-14c29d80-2afa-11e9-9c5d-c5506b66ac4f.png)
http://vladtest56mm-vladtest56mm.kademi-ci.co/vladtest56mm-ecomstore/cart

**Comment by bradmac** [comment]
the problem is that both inputs are in the same form-group

@trungjc please update so that they are in sepereate form-group divs, but keep the same layout

**Comment by trungjc** [comment]
ecomCheckoutFormComponent

![screenshot_8](https://user-images.githubusercontent.com/704946/52548978-5c4f6f00-2e03-11e9-9b09-08ba3349705f.png)
![screenshot_9](https://user-images.githubusercontent.com/704946/52548979-5ce80580-2e03-11e9-8298-2012425bc04a.png)

ecomCheckoutFormPointsOnlyComponent

![screenshot_10](https://user-images.githubusercontent.com/704946/52548986-68d3c780-2e03-11e9-9851-b7eb978d5a39.png)
![screenshot_11](https://user-images.githubusercontent.com/704946/52548987-68d3c780-2e03-11e9-888b-46ac2a529ae8.png)

Updated on version 1.8.8

**Comment by trungjc** [comment]
Remove css important rule in v1.8.9

**Comment by Uafinder** [comment]
Looks good
