### ISSUE TITLE
kCom2: decimal place attribute doesn't match default config

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6677]
![image](https://user-images.githubusercontent.com/1945230/52420384-ab8f5a00-2afa-11e9-89d3-e07865893192.png)
When you open component yo edit it shows 2 decimal places in options but actually no decimals in component
http://vladtest56mm.admin.kademi-ci.co/websites/vladtest56mm/version1?editTemplate=theme/apps/KCommerce2/viewProduct

Same here
![image](https://user-images.githubusercontent.com/1945230/52420489-d9749e80-2afa-11e9-8962-8bc58cc2e50a.png)
http://vladtest56mm.admin.kademi-ci.co/websites/vladtest56mm/version1?editTemplate=theme/apps/KCommerce2/storeCheckout

Should be 2 by default

**Comment by trungjc** [comment]
Update in version 1.8.8

**Comment by Uafinder** [comment]
Ok, looks good
