### ISSUE TITLE
Postcode not saving when first address creating for account

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6678]
![image](https://user-images.githubusercontent.com/1945230/52420631-19d41c80-2afb-11e9-9ebe-eb803120a364.png)
To reproduce
Create a user
Create an order with some address while checkout
![image](https://user-images.githubusercontent.com/1945230/52420752-54d65000-2afb-11e9-89bd-8735d8a8fe30.png)
Complete checkout
This will create an address
![image](https://user-images.githubusercontent.com/1945230/52420791-6ae41080-2afb-11e9-8119-57151ffd711f.png)
But it will be without postcode
http://vladtest56mm.admin.kademi-ci.co/manageUsers/18755260/#general-tab

**Comment by bradmac** [comment]
Fixed. Requires platform update.

**Comment by Uafinder** [comment]
Looks good
