### ISSUE TITLE
Bug in content type asset

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6681]
http://vladtest56mmm.admin.kademi-ci.co/asset-manager/new?type=testcontent
You have a new asset of following content type:
Upload some image
![image](https://user-images.githubusercontent.com/1945230/52465023-ca86fe00-2b85-11e9-9bb6-dc9cae5580b3.png)
Then push edit
![image](https://user-images.githubusercontent.com/1945230/52465038-d672c000-2b85-11e9-9ec2-58997b03cdd7.png)
Verify image and push close
![image](https://user-images.githubusercontent.com/1945230/52465090-01f5aa80-2b86-11e9-95c8-02d04092bf4a.png)
Then try to add EDM content
![image](https://user-images.githubusercontent.com/1945230/52465107-0de16c80-2b86-11e9-8f3d-cd3b48df50ad.png)
Screen will freeze but EDM editor will not appear
![image](https://user-images.githubusercontent.com/1945230/52465122-1df94c00-2b86-11e9-9d77-e2d676991c0e.png)

**Comment by anhnt** [comment]
Fixed in content-lib 1.7.1

**Comment by Uafinder** [comment]
ok, looks good
