### ISSUE TITLE
EDM content type asset doesn't expand body elements to fit content

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6683]
![image](https://user-images.githubusercontent.com/1945230/52466790-248ac200-2b8c-11e9-99f4-5ad1f0e04a7f.png)
http://vladtest56mmm.admin.kademi-ci.co/asset-manager/new?type=testcontent2

**Comment by bradmac** [comment]
hey @anhnt i think we change the UI here so we just edit related assets in a new window, instead of a full screen modal. It looks like this is too hard to get working reliably

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/52611570-bd854a00-2eb8-11e9-9869-19486c362a30.png)

![image](https://user-images.githubusercontent.com/735555/52611580-cbd36600-2eb8-11e9-80f7-e6ca7d0d52e8.png)

Now create new simple asset ie with name and then edit in new tab

**Comment by Uafinder** [comment]
Good now
