### ISSUE TITLE
EDM text edition panel doesn't appear when you try to edit text

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6684]
![image](https://user-images.githubusercontent.com/1945230/52466864-5bf96e80-2b8c-11e9-9a6f-2308c649886a.png)
http://vladtest56mmm.admin.kademi-ci.co/asset-manager/new?type=testcontent2

**Comment by anhnt** [comment]
Looks ok when editing edm in its own new tab as we changed the UI to get rid off full screen modal

**Comment by Uafinder** [comment]
Looks good
