### ISSUE TITLE
SMS journey node doesn't save parameters

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6687]
![image](https://user-images.githubusercontent.com/1945230/52472848-07122400-2b9d-11e9-817d-b40f659d2768.png)
http://vladtest56mmm.admin.kademi-ci.co/funnels/first-journey/version1/smsAction-37ec4a
![image](https://user-images.githubusercontent.com/1945230/52472868-142f1300-2b9d-11e9-89b9-358590a1da71.png)

Wrong email subject field

**Comment by anhnt** [comment]
Requires KJourneys 1.0.7

**Comment by Uafinder** [comment]
looks good
