### ISSUE TITLE
Additionally group add doesn't work on custom signup form

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6690]
http://vladtest56mmm.admin.kademi-ci.co/pages/vladtest56mmmweb/version1/?contenteditor=page1signup.html
![image](https://user-images.githubusercontent.com/1945230/52477213-d5ec2080-2ba9-11e9-92de-aaa3dc6d2c1a.png)
![image](https://user-images.githubusercontent.com/1945230/52477198-ce2c7c00-2ba9-11e9-8bd9-bc26017ff52d.png)
http://vladtest56mmm.admin.kademi-ci.co/manageUsers/18757676/#summary-tab

**Comment by bradmac** [comment]
Please add logic to handle this parameter in KSignup/APP-INF/app.js

Should be simple in immediate rego mode, but let me know if you need a hand with admin approval rego mode.

**Comment by anhnt** [comment]
requires KSignup 1.1.1

Note1: Additional group must be set as optin group in main group settings
Note2: when main group is approval mode, new profile still gets created and added to the optin group but still requires approval to be added to main group

**Comment by Uafinder** [comment]
Still doesn't work for me
![image](https://user-images.githubusercontent.com/1945230/52940807-11d47200-3370-11e9-8315-c2e26579681f.png)
![image](https://user-images.githubusercontent.com/1945230/52940819-1862e980-3370-11e9-861e-4c8057a307de.png)
http://vladtest56sweb-vladtest56s.kademi-ci.co//theme/apps/signup/contenteditor?fileName=register.html
http://vladtest56sweb_vladtest56s.kademi-ci.co/ecommerce-users/signup

**Comment by anhnt** [comment]
please try ticking to extra group in optins section

**Comment by Uafinder** [comment]
Yup, it works
