### ISSUE TITLE
Kcom2: add option for whether to show promotions on ecomCheckoutCart component

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6691]
Needed for https://github.com/Kademi/client-carters/issues/360#issuecomment-460826740

**Comment by trungjc** [comment]
![screenshot_4](https://user-images.githubusercontent.com/704946/52544908-69aa3080-2de6-11e9-9aa5-3f6c5a8686bd.png)

Updated in Kcom2 version 1.8.6

**Comment by trungjc** [comment]
Change "Currency symbol" option, allow user remove currency symbol in Kcom2 version 1.8.7

**Comment by Uafinder** [comment]
Ok, looks good
