### ISSUE TITLE
SMS issues on CI

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6695]
1. SMS send job sitting in Preparing state and doesn't go further
![image](https://user-images.githubusercontent.com/1945230/52560660-af282700-2e01-11e9-8d40-8462e3171467.png)
http://vladtest56n.admin.kademi-ci.co/groupSmss/

2. When no phone specified in user profile it shows code in on SMS details page
![image](https://user-images.githubusercontent.com/1945230/52560818-35dd0400-2e02-11e9-8fdb-af84a2376a86.png)
http://vladtest56n.admin.kademi-ci.co/smsHistory/18760936

3. Also code appears here
![image](https://user-images.githubusercontent.com/1945230/52560920-7b99cc80-2e02-11e9-9041-c45cb36410d8.png)
http://vladtest56n.admin.kademi-ci.co/manageUsers/18760959/#funnelsTab-tab

4. When you use fixed number in SMS journey node, SMS will not fire
![image](https://user-images.githubusercontent.com/1945230/52561035-df23fa00-2e02-11e9-8c7d-2f25f23fb4d0.png)
http://vladtest56n.admin.kademi-ci.co/funnels/first-journey/version1/#journeyBuilder-tab
http://vladtest56n.admin.kademi-ci.co/manageUsers/18761008/#funnelsTab-tab

**Comment by bradmac** [comment]
>    2\. When no phone specified in user profile it shows code in on SMS details page

Fixed here https://github.com/Kademi/kademi-dev/issues/6689

>     3\. Also code appears here

Fixed. Requires KJourneys 1.0.8

**Comment by bradmac** [comment]
>     4\. When you use fixed number in SMS journey node, SMS will not fire

This is a rare edge case, should be moved to its own low priority issue

**Comment by bradmac** [comment]
>     1. SMS send job sitting in Preparing state and doesn't go further

It has been sent:

![image](https://user-images.githubusercontent.com/826458/52590453-3202bd80-2ea6-11e9-8cd3-a76cd04876d9.png)

Note that it can take a while to complete because of retries.

**Comment by bradmac** [comment]
I'm seeing this error when trying to send:
```
23:38:51 [Fatal Error] :1:1: Content is not allowed in prolog.
23:38:51 Failed to communicate with the ClickSend Server
23:38:51 ERROR co.kademi.server.sms.SmsItemQueueStore  - Exception sending SMS: 18757368
23:38:51 java.lang.RuntimeException: Failed to send message 18757368
23:38:51 	at co.kademi.server.sms.clicksend.ClickSendApp.sendSms(ClickSendApp.java:224)
23:38:51 	at co.kademi.server.sms.SmsApp.sendSms(SmsApp.java:428)
23:38:51 	at co.kademi.server.sms.SmsItemQueueStore.next(SmsItemQueueStore.java:187)
23:38:51 	at co.kademi.server.sms.SmsItemQueueStore.doProcess(SmsItemQueueStore.java:50)
23:38:51 	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor.lambda$_runProcessable$9(LocalAsynchProcessor.java:308)
23:38:51 	at io.milton.context.RootContext.execute(RootContext.java:90)
23:38:51 	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor._runProcessable(LocalAsynchProcessor.java:283)
23:38:51 	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor.runProcessable(LocalAsynchProcessor.java:274)
23:38:51 	at io.milton.cloud.server.queue.impl.LocalAsynchProcessor$1.run(LocalAsynchProcessor.java:95)
23:38:51 	at java.util.TimerThread.mainLoop(Timer.java:555)
23:38:51 	at java.util.TimerThread.run(Timer.java:505)
```

**Comment by bradmac** [comment]
Probably because credentials are empty
![image](https://user-images.githubusercontent.com/826458/52590597-93c32780-2ea6-11e9-88d9-d8c19a2232b7.png)
http://vladtest56n.admin.kademi-ci.co/manageApps/#installed-tab

**Comment by Uafinder** [comment]
Ok, looks good
