### ISSUE TITLE
Missed some components and functions when create asset from other asset

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6696]
Comes from here
https://github.com/Kademi/kademi-dev/issues/6240
problem appears when you try to create asset from another asset
http://vladtest56mmm.admin.kademi-ci.co/asset-manager/new?type=testcontent
![image](https://user-images.githubusercontent.com/1945230/52564076-d552c480-2e0b-11e9-961c-6e8fed452c3f.png)
![image](https://user-images.githubusercontent.com/1945230/52564095-e3084a00-2e0b-11e9-95b2-fcefb225454e.png)

**Comment by anhnt** [comment]
Fixed in content-lib 1.7.1

**Comment by Uafinder** [comment]
ok, looks good
