### ISSUE TITLE
kcom2: allow user to provide empty currency symbol in store list and productview components

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6698]
http://vladtest56nweb-vladtest56n.kademi-ci.co//theme/apps/KCommerce2/contenteditor?fileName=viewStore.html
http://vladtest56nweb-vladtest56n.kademi-ci.co//theme/apps/KCommerce2/contenteditor?fileName=viewProduct.html
![image](https://user-images.githubusercontent.com/1945230/52565520-b5bd9b00-2e0f-11e9-8233-d2dfa86959a5.png)
![image](https://user-images.githubusercontent.com/1945230/52565530-bd7d3f80-2e0f-11e9-98a0-7700d8bd0e8d.png)

**Comment by trungjc** [comment]
![111111](https://user-images.githubusercontent.com/704946/52620610-95591380-2ed7-11e9-9cfe-871265f77b02.png)

![screenshot_14](https://user-images.githubusercontent.com/704946/52620873-6000f580-2ed8-11e9-9afd-1fcef2c5164d.png)

Updated on version 1.9.0

**Comment by Uafinder** [comment]
Fresh account
Editor doesn't match selected options by default
![image](https://user-images.githubusercontent.com/1945230/52634700-920e5980-2ed0-11e9-83b7-60cc783c2464.png)
http://vladtest56oweb-vladtest56o.kademi-ci.co//theme/apps/KCommerce2/contenteditor?fileName=viewStore.html

**Comment by trungjc** [comment]
![screenshot_30](https://user-images.githubusercontent.com/704946/52706326-b5f89a80-2fb7-11e9-97ea-9a60ac4b84e4.png)

@Uafinder  Could you check again?

**Comment by Uafinder** [comment]
Looks good now
