### ISSUE TITLE
KCom2 - search function to show "Products not assigned to a category"

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#6700]
feature request

**Comment by bradmac** [comment]
I've added a new search criteria .. category:NONE

Also added help text for advanced search:

![image](https://user-images.githubusercontent.com/826458/52594214-ccb3ca00-2eaf-11e9-8325-ba7f7c451eed.png)

**Comment by bradmac** [comment]
Done. Requires platform update and products-lib 1.1.4

**Comment by Uafinder** [comment]
ok, looks good
