### ISSUE TITLE
Linkedin share button not working

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6704]
Example user:
https://cisco.admin.kademi.com.au/manageUsers/130807080/#summary-tab

When viewing this page:
https://ingramciscoengage.com.au/blogs/blog/cisco-start-digital-catalogue/

Click the linked share button, and i see this JS error in Firefox (probably other browsers too)

<img class="img-responsive" src="/assets/ca07661b-6669-4949-ae80-f4566500b972"/>

The IN.js file appears to be missing. This should be loaded here:

<img class="img-responsive" src="/assets/10a73534-e933-47d9-a01f-109b4db1dbef"/>

**Comment by tuzzmaniandevil** [comment]
Should be fixed now
