### ISSUE TITLE
KCRM: error when add some time to timesheet

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6708]
![image](https://user-images.githubusercontent.com/1945230/52620491-6463e900-2ead-11e9-9915-c093540a6c2a.png)
http://kcrm.kademi.us/timesheets/

**Comment by bradmac** [comment]
Fixed by removing the locale setting on the org

Proper fix will be done here - https://github.com/Kademi/kademi-dev/issues/6710
