### ISSUE TITLE
Create asset from another asset multiclick should not be allowed

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6711]
![image](https://user-images.githubusercontent.com/1945230/52630874-0a235200-2ec6-11e9-82aa-ad6e8fe1c4c8.png)
http://vladtest56o.admin.kademi-ci.co/asset-manager/new?type=content1
![image](https://user-images.githubusercontent.com/1945230/52630899-1c9d8b80-2ec6-11e9-96bf-a5d1de89a79f.png)

**Comment by anhnt** [comment]
done

**Comment by Uafinder** [comment]
Ok, looks good
