### ISSUE TITLE
Blog article url is empty when title is in chinese

### ISSUE THREAD

**Issue by anhnt** [Kademi/kademi-dev#6713]
![image](https://user-images.githubusercontent.com/735555/52684099-993c7280-2f77-11e9-9f7c-f98f27eb6374.png)

![image](https://user-images.githubusercontent.com/735555/52684103-a35e7100-2f77-11e9-8577-57bde8dc3a5c.png)

**Comment by bradmac** [comment]
This occured when editing the path field on an existing blog, and entering chinese chars.

I've updated this to now report a validation error if the path field contains characters which not not valid in urls

**Comment by Uafinder** [comment]
Looks good
