### ISSUE TITLE
Order confirmation EDM component fixes

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6714]
From here:
https://github.com/Kademi/client-carters/issues/363

The orders EDM component should
- allow controlling number of decimal places
-  display the product SKU title (instead of product title) and SKU options (eg size and colour) similar to the checkout page

Checkout page:
![image](https://user-images.githubusercontent.com/826458/52684962-dff88f80-2fac-11e9-9771-8cdfd0ae3c17.png)

Current EDM:
![image](https://user-images.githubusercontent.com/826458/52685012-0caca700-2fad-11e9-862c-9713ddd8cd9b.png)

**Comment by trungjc** [comment]
![screenshot_18](https://user-images.githubusercontent.com/704946/52688237-212a7880-2f88-11e9-9e00-3a81a175f04d.png)


Add number decimal, currency symbol, and position in purchasedProductsListComponent settings.
Also show SKU title and sku option when it is avaiable

![screenshot_20](https://user-images.githubusercontent.com/704946/52688661-eb868f00-2f89-11e9-8096-6a9bec97c348.png)

**Comment by trungjc** [comment]
Update in v1.9.1

**Comment by Uafinder** [comment]
ok, looks good
