### ISSUE TITLE
Points number with star icon

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6717]
![image](https://user-images.githubusercontent.com/1945230/52693702-1ebc2480-2f70-11e9-83e5-0ae5d1622fdf.png)
Earlier we have a points count on top panel when there was active points for user, or user is a member of point bucket group. Now it's missed.
Looks like we forget to move it from deprecated rewardstore-lib
Also would be great to add possibility to enable\disable it via menu component in default template.
![image](https://user-images.githubusercontent.com/1945230/52693856-9ab66c80-2f70-11e9-8f26-7030a30550ce.png)
For example here
Login as this user
http://vladtest56o.admin.kademi-ci.co/manageUsers/18764340/#pointsBucketTab-tab

**Comment by bradmac** [comment]
> Also would be great to add possibility to enable\disable it via menu component in default template.

We cant have options specific for every app in the menu component .. that would be nuts.

But what we can do is have options controlling whether the 3 portlet sections are enabled. If disabled then apps will never inject portlets

menuComponent.html already has an option for the search portlet:
```
                #if ($showSearch == true)
                    <li class="navbar-search">
                        #portlets("searchInput")
                    </li>
                #end
```

We should also add an option to control the shoppingCart portlet (note that portlets can be used by any app, ie this is not specifically for shopping carts)

```
                #portlets("shoppingCart")
```

And also an option to control the social login portlet:

```
#portlets("socialLoginForm")
```

**Comment by trungjc** [comment]
![screenshot_5](https://user-images.githubusercontent.com/704946/52764007-c4df5b80-3050-11e9-9aae-ef6e68d324bb.png)

update on v1.2.6

**Comment by bradmac** [comment]
@trungjc as well as what you've done please also add options to the menu component to control whether portlets are rendered, see my comment above

**Comment by trungjc** [comment]
![screenshot_11](https://user-images.githubusercontent.com/704946/52779793-73989180-307b-11e9-8cfe-e2749f9e7a40.png)

Update portlet show/hide option to menuComponent, menu2Component, menu3Component

**Comment by Uafinder** [comment]
Ok, looks good
