### ISSUE TITLE
Videoe asset not playing on module page

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#6718]
See this module http://kademi.admin.kademi.us/websites/kademi-dev/v10-paddy/programs/admin/cxfundamentals/customers/#files-tab

View the module 'Creating and uploading organizations'
Playback of video gives this error
![image](https://user-images.githubusercontent.com/2201340/52693821-f2c69080-2fbb-11e9-84e2-8dcb7693c105.png)

However the video is an asset and plays from the assets page http://kademi.admin.kademi.us/asset-manager/c24fa1d2-d5a4-424a-ab22-ce6ea6c197a6

**Comment by anhnt** [comment]
It will take some time to generate videos after uploading to kademi. Looks good to me atm
