### ISSUE TITLE
create new component called RecognitionWall in KRecognition

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6720]
We need a new component within KRecognition which will be something like Vaya social wall
It should show such things within user org:
- awarded badges
- learning activity
- awarded points
- give possibility to comment activities
![image](https://user-images.githubusercontent.com/1945230/52694243-b1a98e80-2f71-11e9-8f4a-7a3e47309c8f.png)

**Comment by bradmac** [comment]
We have this component already, although probably not ready for production

App: KForums - ID: socialWall

**Comment by bradmac** [comment]
Duplicate of https://github.com/Kademi/kademi-dev/issues/5460
