### ISSUE TITLE
More details for points awarded record when module completed

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6723]
![image](https://user-images.githubusercontent.com/1945230/52714307-34e2d880-2fa2-11e9-835c-e341d872a0a2.png)
http://vladtest56o.admin.kademi-ci.co/manageUsers/18764340/#pointsBucketTab-tab
Should provide module name or code which was completed.

**Comment by bradmac** [comment]
Done

**Comment by Uafinder** [comment]
ok, looks good
