### ISSUE TITLE
Blogs: tile component, image with some different aspect ratio case multipliying image accross one tile

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6728]
![image](https://user-images.githubusercontent.com/1945230/52785073-c06e6f00-305f-11e9-98d4-c94fe39d0ca6.png)
http://vladtest56p.admin.kademi-ci.co/blogs/blog1/art1/#bodyCopy-tab
Should be option to select image apply type ("Stretched, centered. fit by duplicates")

**Comment by bradmac** [comment]
I dont think we ever want multiple images. But an option to cover or fill would be good.

**Comment by trungjc** [comment]
![screenshot_16](https://user-images.githubusercontent.com/704946/52844662-a902b500-3137-11e9-9805-de1b34b0dd9b.png)

Add options which control background image options in content-lib v1.7.0

**Comment by Uafinder** [comment]
ok, it works now
