### ISSUE TITLE
points bucket inaccessible when Kcom2, promotions installed

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6729]
http://vladtest56p.admin.kademi-ci.co/points-buckets
http://vladtest56p.admin.kademi-ci.co/websites/vladtest56pweb/version1/#panel_details-tab
looks like it related or placed in old rewardstore-lib
![image](https://user-images.githubusercontent.com/1945230/52787499-b2701c80-3066-11e9-86e2-a6ce6ead27b4.png)
This apps installed
![image](https://user-images.githubusercontent.com/1945230/52787524-ca47a080-3066-11e9-806f-890d9d42fec6.png)

**Comment by bradmac** [comment]
> points bucket inaccessible when Kcom2, promotions installed

These pages are now provided by the rewards app (from this issue - https://github.com/Kademi/kademi-dev/issues/6653)

Pages should be ok now.

**Comment by Uafinder** [comment]
looks good
