### ISSUE TITLE
Admin compose email form doesnt work

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6732]
![image](https://user-images.githubusercontent.com/826458/52825399-72ba3b00-3121-11e9-895d-a5f032ac7c19.png)

Looks like its sending as a GET request instead of a POST.

**Comment by anhnt** [comment]
Fixed on other issue

**Comment by anhnt** [comment]
https://github.com/Kademi/kademi-dev/issues/6624

**Comment by Uafinder** [comment]
looks good
