### ISSUE TITLE
KCom2: Pricing rules should allow multiple products and categories, and allow exclusions

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6733]

**Comment by bradmac** [comment]
KCom2 1.9.3

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/52829356-56be9580-3131-11e9-965f-fc47d5268cc1.png)


Can now specify multiple codes, seperated with commas. And using ! as a prefix makes it an exclusion

**Comment by Uafinder** [comment]
Looks fine
