### ISSUE TITLE
JS error on manage point bucket page

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6734]
![image](https://user-images.githubusercontent.com/1945230/52841457-15b08c00-3105-11e9-8bee-005e01316201.png)
http://vladtest56r.admin.kademi-ci.co/points-buckets/points1/#details-tab

**Comment by anhnt** [comment]
this is because rewardstore-lib is disabled which contains templates for managing points
@bradmac should we move them to rewards-lib?

![image](https://user-images.githubusercontent.com/735555/52842358-6e961980-3131-11e9-8b1a-93a9a5cef9c0.png)

**Comment by bradmac** [comment]
Generally, points management resources should be in rewards-lib

Note that there are pages here specific to rewardstore (eg manageRewardStores) which should not be copied.

**Comment by anhnt** [comment]
done, requires rewardstore-lib 1.7.6 and rewards-lib 1.3.0

**Comment by Uafinder** [comment]
looks good
