### ISSUE TITLE
user profile tab for points is absent after moving points bucket to rewards-lib

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6735]
![image](https://user-images.githubusercontent.com/1945230/52842007-6b396880-3106-11e9-94d8-bc7f6d4254bf.png)
http://vladtest56r.admin.kademi-ci.co/manageUsers/18773866/#summary-tab

**Comment by bradmac** [comment]
Fixed. Requires rewards-lib 1.2.8 and platform update

**Comment by Uafinder** [comment]
ok, tab appears now, but it doesn't show any points
![image](https://user-images.githubusercontent.com/1945230/52938136-8fe14a80-3369-11e9-9556-b884d36e0818.png)
http://vladtest56s.admin.kademi-ci.co/manageUsers/18779209/#pointsBucketTab-tab
However user has necessary access and points already
![image](https://user-images.githubusercontent.com/1945230/52938177-a5567480-3369-11e9-8ffa-e4de9033e6bb.png)

**Comment by bradmac** [comment]
> ok, tab appears now, but it doesn't show any points

should be fixed with latest rewards-lib

**Comment by Uafinder** [comment]
Ok, bucket appears now, but still no points in it
![image](https://user-images.githubusercontent.com/1945230/53403773-ed564680-39bc-11e9-8a80-42c50b5e49a1.png)
http://vladtest56x.admin.kademi-ci.co/manageUsers/19002840/#pointsBucketTab-tab
![image](https://user-images.githubusercontent.com/1945230/53403790-f8a97200-39bc-11e9-8409-aa6b91855a04.png)
http://vladtest56x.admin.kademi-ci.co/rewards/points/#points-tab

Looks like they are not falls into index

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/53403939-7a2eed80-3a19-11e9-9cfe-6e71e5c6b663.png)

**Comment by bradmac** [comment]
But there is still an issue after updating libs.

**Comment by bradmac** [comment]
OK, fixed and patched into that test account:

![image](https://user-images.githubusercontent.com/826458/53404335-4f916480-3a1a-11e9-9a20-03021de1690b.png)

**Comment by Uafinder** [comment]
ok, looks good
