### ISSUE TITLE
JS error on dashboard for auctions

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6736]
![image](https://user-images.githubusercontent.com/1945230/52842217-13e7c800-3107-11e9-8898-bcac5dff6410.png)
http://vladtest56rweb-vladtest56r.kademi-ci.co/dashboard
this user
http://vladtest56r.admin.kademi-ci.co/manageUsers/18773866/#summary-tab

**Comment by anhnt** [comment]
Done

**Comment by Uafinder** [comment]
Looks good
