### ISSUE TITLE
KCom2: Add default country in ecomCheckoutFormComponent and ecomCheckoutFormPointsOnlyComponent

### ISSUE THREAD

**Issue by trungjc** [Kademi/kademi-dev#6746]
Add default country in ecomCheckoutFormComponent and ecomCheckoutFormPointsOnlyComponent

Reference to: https://github.com/Kademi/client-carters/issues/365

**Comment by trungjc** [comment]
Updated on kcom2 v1.9.4

**Comment by Uafinder** [comment]
Should it hide preselected country?
I thought it should just have prepopulated value and field should be disabled for edit?
@trungjc

**Comment by bradmac** [comment]
No, it should not be displayed.

Eg for Carters Advantage this is for a specific country, and it would be weird to show a country

**Comment by Uafinder** [comment]
Ok, looks good
