### ISSUE TITLE
EDM: missed thumb for storeproductListEDM component

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6751]
![image](https://user-images.githubusercontent.com/1945230/53005675-61806f80-343c-11e9-8042-942c2b293439.png)
http://vladtest56t.admin.kademi-ci.co/voucher-type/vtyp1/edmeditor?useHash=true&uploadProviders=assets

**Comment by trungjc** [comment]
@Uafinder this component is from Ecommerce App, it is deprecated

Should we move it to kcom2 @bradmac

**Comment by bradmac** [comment]
No, i think kcom2ProductListEDMComponent provides that capability

I think the problem is the ECommerce app is defining these componnts in java, but their resources are not accessible.

These components are not in use by any client so please delete component definitions from ECommerceApp.java

**Comment by anhnt** [comment]
Deleted

**Comment by Uafinder** [comment]
Ok, looks good
