### ISSUE TITLE
Kfeedback: sorting issue

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6753]
http://vladtest56t.admin.kademi-ci.co/kfeedback/#!/surveys/test1/report
![image](https://user-images.githubusercontent.com/1945230/53006734-765e0280-343e-11e9-8ea4-cca61af9c897.png)
![image](https://user-images.githubusercontent.com/1945230/53006739-7c53e380-343e-11e9-958d-e90e118cb5e7.png)
Change back to No filter
And no feedbacks appears
![image](https://user-images.githubusercontent.com/1945230/53006790-955c9480-343e-11e9-82fa-351042fd8319.png)
Comes from here
https://github.com/Kademi/kademi-dev/issues/6651

**Comment by anhnt** [comment]
Done in kfeedback 1.3.4

**Comment by Uafinder** [comment]
ok, looks good
