### ISSUE TITLE
Kfeedback: timezone issue

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6754]
I've setup timezone on org
![image](https://user-images.githubusercontent.com/1945230/53006848-bfae5200-343e-11e9-9c50-a692820efb0e.png)
![image](https://user-images.githubusercontent.com/1945230/53006859-c76df680-343e-11e9-928d-e1414df05434.png)
But when i check submit times in report it shows that it will be submitted in 11 hours (looks like NZ time)
![image](https://user-images.githubusercontent.com/1945230/53006931-ee2c2d00-343e-11e9-8eec-83e6754bb31b.png)
http://vladtest56t.admin.kademi-ci.co/kfeedback/#!/surveys/test1/report

**Comment by anhnt** [comment]
There was a bug with formatDateWithPattern api. Looks good now
![image](https://user-images.githubusercontent.com/735555/53078203-4c800b00-3526-11e9-9579-bd4b6862008d.png)

**Comment by Uafinder** [comment]
Ok, looks better
