### ISSUE TITLE
new component which shows learning activity board (KCRM org page)

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6758]
![image](https://user-images.githubusercontent.com/1945230/53019602-c3050600-345d-11e9-9f4c-1cff54f1e2b8.png)
- Should be user/org based
- should show learning activity by (user/ all users in org) - started, completed and expired actions
- should show user avatar
- should show timestamp 

should depends on time range selector

**Comment by Uafinder** [comment]
https://github.com/Kademi/client-zoetis/issues/351
https://github.com/Kademi/client-zoetis/issues/350

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/54328188-8a60e280-463f-11e9-995d-5ce562848f2b.png)

**Comment by anhnt** [comment]
learning-lib 1.5.1

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/54344332-48d53500-4649-11e9-8f25-e41f21df5ba2.png)
This link leads to error
http://vladtest57jweb-vladtest57j.kademi-qa.co/companies/225879

Sorting should be from recent to oldest
![image](https://user-images.githubusercontent.com/1945230/54345039-e5e49d80-464a-11e9-8a4c-19fe1e8fa552.png)

**Comment by anhnt** [comment]
Done, learner-lib 1.5.8

**Comment by Uafinder** [comment]
ok, looks good
