### ISSUE TITLE
new component which will show user web activity like histogram

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6759]
Should be like report
![image](https://user-images.githubusercontent.com/1945230/53022467-e632b400-3463-11e9-95be-82ca772c8493.png)
Web activity (beta) Report
Should be sensitive to the common date time range
Should be user/org related for KCRM user/org pages

**Comment by Uafinder** [comment]
https://github.com/Kademi/client-zoetis/issues/351

**Comment by anhnt** [comment]
![useractivity](https://user-images.githubusercontent.com/735555/53480034-ead31a00-3aac-11e9-8663-95173fb54c64.png)

**Comment by anhnt** [comment]
requires amcharts-lib (new) and reporting-lib 1.4.8

**Comment by anhnt** [comment]
restrict result for users who belong to current org when on org page ie lead company

**Comment by Uafinder** [comment]
it works perfectly on separate page and on user page
but looks like not on org page
http://vladtest56zweb-vladtest56z.kademi-ci.co/companies/19098499
same as users page filtered by user
this user is a part of those org
http://vladtest56z.admin.kademi-ci.co/manageUsers/19098490/#userAppTab-tab

**Comment by anhnt** [comment]
done, also added org selector filterable

**Comment by Uafinder** [comment]
Hmmm
![image](https://user-images.githubusercontent.com/1945230/53724387-6c8ec300-3e72-11e9-8972-a91bf4154045.png)
http://vladtest57bweb-vladtest57b.kademi-qa.co/companies/49808
http://vladtest57b.admin.kademi-qa.co/manageUsers/40411/#summary-tab

Still bad for me

**Comment by anhnt** [comment]
@bradmac this chart uses a query from `log` index. but this lacks of field called `parentOrgs` so we cant filter by user's all org ids. Can you check please

**Comment by bradmac** [comment]
Done. Requires platform update

**Comment by anhnt** [comment]
@Uafinder and please reindex log

**Comment by Uafinder** [comment]
seeing weird behavior
when i re-index account, all visits index gone
http://vladtest57c.admin.kademi-qa.co/manageSearch/


anh 1:06 PM
hey
that is log index
i can see 2k records


Vlad 1:09 PM
Hmmm
But now i m not seeing any activity in your component


anh 1:10 PM
show me that page
lol
parentOrgs has no value


Vlad 1:13 PM
http://vladtest57cweb-vladtest57c.kademi-qa.co/custs/5f133386-94ca-4300-a4ca-0fd7b109d5a5/
So Brad did not fix it?


anh 1:14 PM
brad didnt push value to that field on log index
i wll check
did you rebuild?
this requires rebuild and reindex
if you did them then i will check with brad tomorrow


Vlad 1:19 PM
Yup
Fresh account?
Oops
Not a question
It's a fresh account


anh 1:20 PM
ok
i will check that tonight

**Comment by bradmac** [comment]
> when i re-index account, all visits index gone

@Uafinder that is expected. Currently visits is not reindexable.

**Comment by bradmac** [comment]
Fixed

**Comment by Uafinder** [comment]
It works like a charm now!
