### ISSUE TITLE
Users search is not locating by name

### ISSUE THREAD

**Issue by DimitryNechaev** [Kademi/kademi-dev#676]
I'm searching for the highlighted user:
image
![image](https://cloud.githubusercontent.com/assets/12892631/9603327/574b0a5a-50f3-11e5-9bd3-3b5290f52d5b.png)

Search returns nothing:
image
![image](https://cloud.githubusercontent.com/assets/12892631/9603330/5c633ff8-50f3-11e5-85e9-87d51c350c54.png)

This behaviour was observed in original users page as well. Search stopped working by name for some time ago

**Comment by DimitryNechaev** [comment]
hi @bradmac  I can't assign you

**Comment by bradmac** [comment]
Search for "Wayne" works, but not "Wayne Hollingworth" or just "Hollingworth"

**Comment by bradmac** [comment]
Problem is that its case sensitive. Searching for "wayne hollingworth" works
