### ISSUE TITLE
Kcom2: Add decimal number place setting to ecomCheckoutFormPointsOnlyComponent

### ISSUE THREAD

**Issue by trungjc** [Kademi/kademi-dev#6762]
Add decimal number place setting to ecomCheckoutFormPointsOnlyComponent

https://github.com/Kademi/client-carters/issues/368

**Comment by trungjc** [comment]
![screenshot_2](https://user-images.githubusercontent.com/704946/53065522-8dfcc000-34fe-11e9-92bc-dce312b8246f.png)

update on kcom2 v1.9.6

**Comment by Uafinder** [comment]
Ok, looks good
