### ISSUE TITLE
KCom2 -  position field missing from import and export CSVs.

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#6763]
When client does an an import they cannot map to the "position" column.
Important for ordering/sorting products in a precise order.

Mapping position field is most important on import though. Export will be good for bulk editing the product positions.

 This request has come through from Farmgard and now Waterware and is a priority for Waterware.

**Comment by Uafinder** [comment]
What exact import doing this?

**Comment by stephen-fueldesign** [comment]
Hi @Uafinder it's for product import and export, specifically.

So client can have fine grain control of ordering/sorting their numerous products.

Thanks!

**Comment by Uafinder** [comment]
Looks good
