### ISSUE TITLE
Assets - asset name not rendering when editing a related asset from within an asset.

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#6764]
Product code: **HS2319** https://waterware.admin.kademi.com.au/products/125777209/#attributes-tab

**Attribute > Edit asset** https://waterware.admin.kademi.com.au/asset-manager/cce88e8e-ff8a-46b1-8c29-1a4b43143ad8

When you click edit icon on Product Videos field, the resulting dropdown asset has issues.
Video Embed code is not rendering the english name.

<img width="608" alt="missing name fields" src="https://user-images.githubusercontent.com/39784677/53126089-404a8b00-35c4-11e9-92bd-181cc68bbc8b.png">

**Comment by bradmac** [comment]
@stephen-fueldesign looks ok to me

![image](https://user-images.githubusercontent.com/826458/53130006-fb2b5680-35cd-11e9-9d88-4e81ff1f0db7.png)

How do i reproduce the problem?

**Comment by stephen-fueldesign** [comment]
You need to click the edit icon on "Video Embed code" field.

**Comment by anhnt** [comment]
@stephen-fueldesign we've changed the code to open new tab when editing asset (ie get rid off editing modal) and i deployed content-lib  1.7.1. Can you please update that lib on account and see if it works?

**Comment by stephen-fueldesign** [comment]
Perfect Anh, thanks!
