### ISSUE TITLE
Products & Stores Admin Issues

### ISSUE THREAD

**Issue by faithtek** [Kademi/kademi-dev#6765]
With some of my sites and all new sites I create, I get the following errors with several pages of the "Product & Stores" admin tools.

![image1](https://user-images.githubusercontent.com/7914822/53134586-c378cc00-3545-11e9-8e4a-323618a80901.png)

![image2](https://user-images.githubusercontent.com/7914822/53134594-c83d8000-3545-11e9-8708-1175cd20dbc1.png)

So far I have found the following pages that throw the above errors:

- Products: https://arvoswellsville.admin.kademi.us/products/
- Categories: https://arvoswellsville.admin.kademi.us/categories/
- Product SKU's: https://arvoswellsville.admin.kademi.us/skus/
- Inventory: https://arvoswellsville.admin.kademi.us/inventory/

**Comment by bradmac** [comment]
@faithtek this account seems to be missing the products-lib

You can install that into your account (not website level) as follows

![image](https://user-images.githubusercontent.com/826458/53136138-c2e24300-35e2-11e9-95db-7a3e9cce608b.png)

**Comment by faithtek** [comment]
That's really weird. :| Not sure why that wasn't already in the site. Could an update have done this? Removed the product-lib from the site?

**Comment by bradmac** [comment]
Sorry, that was my bad.

We're removing static assets which have been moved to marketplace delivered libs, but i thought everyone had products-lib already installed. But not in this case!

**Comment by faithtek** [comment]
Are there any other libraries like this that I need to know about?

**Comment by bradmac** [comment]
You can see all of our available libs here:
https://github.com/Kademi/kademi-dev/tree/master/src/main/marketplace/libs

And you can see all of your installed libs from your apps page:
https://arvoswellsville.admin.kademi.us/manageApps/#installed-tab

But generally libs are installed automatically when apps are installed so you shouldnt need to manually install them.

**Comment by faithtek** [comment]
Thanks.
