### ISSUE TITLE
KCom2: purchasedProductListComponent show wrong grand total inclusive tax

### ISSUE THREAD

**Issue by trungjc** [Kademi/kademi-dev#6767]
Reference to https://github.com/Kademi/client-carters/issues/368

**Comment by trungjc** [comment]
Add inclusive tax in component setting page

Update in v1.9.7

**Comment by Uafinder** [comment]
Should this component price also include freight?
![image](https://user-images.githubusercontent.com/1945230/53165958-b529bf00-35dc-11e9-8635-74e33afa1b7a.png)
![image](https://user-images.githubusercontent.com/1945230/53165967-bd81fa00-35dc-11e9-9486-410e9db2abeb.png)
http://vladtest56v.admin.kademi-ci.co/emails/18842539

**Comment by bradmac** [comment]
> Should this component price also include freight?

No, i dont think so. I think it should match the cost of the item they saw on the checkout page.

**Comment by Uafinder** [comment]
Ok, so looks good
