### ISSUE TITLE
Kfeedback: answers don't appear with default time range

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6768]
![image](https://user-images.githubusercontent.com/1945230/53151218-48ea9380-35bb-11e9-9fba-15fec18ef649.png)
![image](https://user-images.githubusercontent.com/1945230/53151232-53a52880-35bb-11e9-8c21-11829394b1af.png)
http://vladtest56v.admin.kademi-ci.co/kfeedback/#!/surveys/feedback1/report

**Comment by anhnt** [comment]
fixed in kfeedback app 1.3.5

**Comment by Uafinder** [comment]
looks good
