### ISSUE TITLE
Blog renaming does not support spaces.

### ISSUE THREAD

**Issue by DimitryNechaev** [Kademi/kademi-dev#677]
![image](https://cloud.githubusercontent.com/assets/12892631/9603508/5f0e6b6e-50f4-11e5-90f5-0a32a0c9a740.png)

When renaming editor pops up with html-encoded caption
![1](https://cloud.githubusercontent.com/assets/12892631/9603621/3d8158d4-50f5-11e5-94cc-11678d483232.jpg)

and when editing it as it, it just breaks the blog name on saving
![2](https://cloud.githubusercontent.com/assets/12892631/9603619/3981c656-50f5-11e5-9c84-5487e3c13e7d.jpg)

**Comment by DimitryNechaev** [comment]
@bradmac can't assign you

**Comment by tuzzmaniandevil** [comment]
This issue has been fixed.
