### ISSUE TITLE
Accordion component issue/question 

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6772]
![image](https://user-images.githubusercontent.com/1945230/53169793-ea3b0f00-35e6-11e9-81a5-2043482a63e7.png)
![image](https://user-images.githubusercontent.com/1945230/53169797-ee672c80-35e6-11e9-824c-2ec5e1ca6e51.png)
When expand it gives you a lot more empty space and then reduce it to suitable size
Starts from 19th question
http://vladtest56vweb-vladtest56v.kademi-ci.co/page2.html
I copied HTML from Vaya site
But can't reproduce it with sample accordion
http://vladtest56vweb-vladtest56v.kademi-ci.co/page1.html

Please advice
Needed for Vaya
https://github.com/Kademi/client-vaya-vayability/issues/447

**Comment by bradmac** [comment]
@anhnt please take a look

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/53329738-50919b80-391f-11e9-9f06-a99253c87849.png)

I guess someone who added that content was using grammarly chrome extension so it added some extra html to the content. keditor captured them as static html and saved so it shows extra space

**Comment by Uafinder** [comment]
ok, got it
