### ISSUE TITLE
Images in email template forced full width

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#6773]
http://test123.admin.kademi.com.au/groupEmails/142235329/#messages-tab

When deselecting the full width option, the image is still being forced full width and does not display actual size.

The red box is the size the image should get displayed.

![image](https://user-images.githubusercontent.com/2201340/53208494-15773a00-368b-11e9-9b2e-a72b22b8b1ba.png)

**Comment by anhnt** [comment]
fixed in content-lib 1.7.2

**Comment by Uafinder** [comment]
Looks good
