### ISSUE TITLE
SKUs not showing after upload

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#6776]
I uploaded products here http://rewardstore1234.admin.kademi-ci.co/products/

I then went to SKUs and uploaded this file [skus (5).zip](https://github.com/Kademi/kademi-dev/files/2892315/skus.5.zip)

Refreshing the SKUs page, the SKUs don't seem to have updated.

![image](https://user-images.githubusercontent.com/2201340/53219129-de1c8380-36b2-11e9-8e56-2be4cb5cece1.png)

I reindex products thinking this might fix it, but it did not.

I go back to the SKUs page and download the SKUs CSV, only the file contains all the SKUs I uploaded so not sure why the SKUs do not show as being updated in the admin console?

**Comment by bradmac** [comment]
Looks ok now

![image](https://user-images.githubusercontent.com/826458/53305799-21f9cd80-38eb-11e9-9389-fbc9ff937650.png)

**Comment by bradmac** [comment]
Might have been server side caching

@Uafinder can you please try to reproduce the problem? ie just upload a CSV to create SKUs and see whether they appear on the SKUs page

**Comment by Uafinder** [comment]
Ha! Saw that problem as well...
https://github.com/Kademi/kademi-dev/issues/5604

**Comment by Uafinder** [comment]
Closed as duplicate
