### ISSUE TITLE
Auctions showing dollars not points

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#6777]
http://rewardstore1234.admin.kademi-ci.co/auctions/

Why do auctions show a dollar sign now?  I only recall auctions show points as points are used to bid on auctions. 

![image](https://user-images.githubusercontent.com/2201340/53219790-8a5f6980-36b5-11e9-912c-d5389c97ff60.png)

**Comment by anhnt** [comment]
this has been using dollar sign for years :) 
https://github.com/Kademi/kademi-demos/issues/172

**Comment by bradmac** [comment]
Done here - https://github.com/Kademi/kademi-dev/issues/6908
