### ISSUE TITLE
blogs-lib: Add options to blogPageCategoriesComponent and blogPageTagsComponent

### ISSUE THREAD

**Issue by trungjc** [Kademi/kademi-dev#6779]
Add panel heading and count options to blogPageCategoriesComponent and blogPageTagsComponent

**Comment by trungjc** [comment]
Updated on v1.2.3

**Comment by Uafinder** [comment]
When deselect a heading option it's become to hard pickup that component again
![image](https://user-images.githubusercontent.com/1945230/53236549-36488b00-369d-11e9-8a63-5a3f9f05cd4d.png)
http://vladtest56wweb-vladtest56w.kademi-ci.co//theme/apps/blogs/contenteditor?fileName=viewBlogs.html

**Comment by bradmac** [comment]
Yep, components must always be visible in the editor.

Show fake/representative content when there is no real content to make sure the component doesnt collapse.

**Comment by trungjc** [comment]
![screenshot_4](https://user-images.githubusercontent.com/704946/53427995-8a949780-3a1c-11e9-8747-218eae24081c.png)


Fake content was added

**Comment by Uafinder** [comment]
Ok, looks good
