### ISSUE TITLE
Users Profile page in admin portal doesn't load using safari

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#678]
Manage users page works fine but when trying to access the users details in Safari the page doesn't load. Works fine in firefox and chrome.
Reported by Marie from Bartercard.

Please notify Marie the outcome of this issue.

**Comment by bradmac** [comment]
Tested on Max Mavericks, with Safari 7 using browserstack and its fine.

I suggest clearing the cache and trying again.

**Comment by tuzzmaniandevil** [comment]
I can't reproduce this. Tested on OSX Mavericks 0.9.5 and Safari 7.0.6 (9537.78.2) using a Virtual Machine
