### ISSUE TITLE
Sales data record management page, does not apply timezone when saving, and promotion dates dont apply correctly

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6781]
Eg in an account with a US timezone, save a record and refresh and you'll see the date change

https://dixie.admin.kademi.us/sales/sales-transactions/68066771

![image](https://user-images.githubusercontent.com/826458/53305778-54ef9180-38ea-11e9-916a-95555c1cbfcd.png)

**Comment by bradmac** [comment]
I can no longer reproduce this issue

**Comment by bradmac** [comment]
Fixed.

Requires DB update and platform update.

rewards-lib update is optional, just adds some debugging to the manage reward page.

**Comment by Uafinder** [comment]
Looks good
