### ISSUE TITLE
Enhance asset query expression to have access to rootfolder etc

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6782]
required for https://github.com/Kademi/client-vaya-vayability/issues/446

so what i think we do is
- update ContentTypes.init to call TemplatingContextService.addStandardSingletonParams
- create a new manager class to wrap CurrentDefaultFolderService (but hides dangerous methods)
- then you can do this

**Comment by tuzzmaniandevil** [comment]
No longer needed.

There was already a method on securityManager
