### ISSUE TITLE
Cannot add a module thumbnail

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#6785]
https://zoetis.admin.kademi.com.au/websites/zoetis-reps/version1/programs/admintuts/fundamentals/training/#details-tab

Have updated root APPs
Have cleared cache

![image](https://user-images.githubusercontent.com/2201340/53312568-b2470b00-3909-11e9-8193-5af0be0b06ca.png)

**Comment by bradmac** [comment]
Works fine in standard code.
