### ISSUE TITLE
Registration form component not hiding ORG fields

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#6787]
This page http://consumer-program_moblix.kademi-ci.co/contenteditor?fileName=signup.html

This is the form font end page http://consumer-program_moblix.kademi-ci.co/signup.html

Un-ticking the ORG sections then saving does not remember the selection and the check boxes become ticked again.  As a result the form will fail when submitted as it's looking for ORG fields to be completed.

NOTE THIS needs to be updated on the new CI and the old CI for presentation in the morning.

![image](https://user-images.githubusercontent.com/2201340/53318795-8422f480-3924-11e9-91e3-42a34d6caff5.png)

**Comment by anhnt** [comment]
@trungjc this code will be always set the checkbox setting checked

```
form.find('.showOrgs').prop('checked', dataAttributes['data-show-orgs'] === 'true' || true);
```

Im going to update this

**Comment by anhnt** [comment]
@trungjc when a setting you want to be checked by default please use this
```
form.find('.showOrgs').prop('checked', dataAttributes['data-show-orgs'] !== 'false');
```
I've also updated sociallogin-lib to get rid off js error. 
Also KSignup must be installed as we need that for backend handler at the moment

**Comment by Uafinder** [comment]
looks good
