### ISSUE TITLE
Kcom2 - unable to delete redundant categories.

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#6791]
I'm getting an error message when trying to delete all 4th level categories here:
https://waterware.admin.kademi.com.au/categories/

Here's a list of some categories I'm trying to remove:

- Liberty Chrome
- Flint
- tune-Liberty Chrome
- tune-Liberty Chrome
- tune-Liberty Chrome
- tune-Liberty Chrome
- tune-Liberty Chrome
- tune-Liberty Chrome
- tune-Liberty Chrome
- tune-Liberty Chrome
- Scarab
- Liberty Oil Rubbed Bronze
- Urban
- Loft

Here is the error message I get in logs.
<img width="759" alt="errormsg" src="https://user-images.githubusercontent.com/39784677/53380072-f18c5f00-39d0-11e9-8d6d-48bd915560c9.png">

**Note**: There are no products associated to these categories. And no products have any brand items associated to them.

Let me know how you debug this so I can learn too :)

Thanks!

**Comment by bradmac** [comment]
I think this is already fixed. But added a defensive check, so will check again afte next prod deploy

**Comment by Uafinder** [comment]
Looks good now
