### ISSUE TITLE
Broken account created on new QA server

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6795]
when i create new account on new QA it become broken without subscription
http://vladtest56xx.admin.kademi-qa.co

BM: ok, looks like wes hasnt set up the base domain properly
![image](https://user-images.githubusercontent.com/1945230/53408886-52fc0000-39c8-11e9-906a-0c4f0baa458f.png)

**Comment by bradmac** [comment]
@tuzzmaniandevil looks like the server isnt quite configured correctly, can you take a look?

**Comment by tuzzmaniandevil** [comment]
Fixed
