### ISSUE TITLE
Error when install kCom2

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6796]
![image](https://user-images.githubusercontent.com/1945230/53411439-1bdd1d00-39cf-11e9-9f50-67a407de93c3.png)
![image](https://user-images.githubusercontent.com/1945230/53411519-5941aa80-39cf-11e9-86b7-08d0134d68b3.png)
after that website disappears
![image](https://user-images.githubusercontent.com/1945230/53410074-6e1c3f00-39cb-11e9-8110-4801eaa09616.png)
![image](https://user-images.githubusercontent.com/1945230/53410119-8ab87700-39cb-11e9-9ac4-cf33551463e4.png)
http://vladtest56xx.admin.kademi-ci.co/marketPlace/KCommerce2/?websiteBranch=version1&websiteName=vladtest56xxweb

**Comment by bradmac** [comment]
should be fixed now

**Comment by Uafinder** [comment]
looks good
