### ISSUE TITLE
KRedirect: Unable to enter Source URL with a plus

### ISSUE THREAD

**Issue by joelatfuel** [Kademi/kademi-dev#6797]
All of Hazero's 301s use a + to separate words; for example, /Contact+Us.html. When I enter this kind of URLs, I get this error.

<img width="600" alt="screen shot 2019-02-27 at 8 35 35 am" src="https://user-images.githubusercontent.com/41346338/53440986-b179ba80-3a6a-11e9-9543-cf383ca7aada.png">

**Comment by bradmac** [comment]
@joelatfuel can you please provide the url where you see this problem?

**Comment by joelatfuel** [comment]
https://hazero.admin.kademi.com.au/kredirect/

**Comment by anhnt** [comment]
Fixed

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/53490665-f9193a00-3a9c-11e9-900c-747659683f76.png)
![image](https://user-images.githubusercontent.com/1945230/53490684-033b3880-3a9d-11e9-9a6b-dda36370dc85.png)
this one on CI

on Hazero looks good

**Comment by bradmac** [comment]
@Uafinder that error is because jsondb hasnt been installed. This should be automatially installed as a dependency, so its a bug, but a different issue.

So will close this.
