### ISSUE TITLE
KCom2: Enhance checkout confirmation modal

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6799]
Our standard checkout confirmation modal currently lacks text explaining what the user is seeing.

Please add configurable options for
- top text, eg "A new item has been added.."
- middle text, eg "Other items you might like"
- a green tick at top left to indicate success

Current - no explanatory text
![image](https://user-images.githubusercontent.com/826458/53455352-08918680-3a8f-11e9-8aff-abf5a66abc41.png)

Example from a site with explanatory text:
![image](https://user-images.githubusercontent.com/826458/53455373-15ae7580-3a8f-11e9-9fd6-34eadc234589.png)

**Comment by trungjc** [comment]
![screenshot_10](https://user-images.githubusercontent.com/704946/53466876-4938d200-3a86-11e9-9e09-8b016d82d44d.png)
![screenshot_11](https://user-images.githubusercontent.com/704946/53466877-49d16880-3a86-11e9-9fe5-8ba2f42f0f6c.png)

Add the settings to productComponent in Kcom2 v2.0.0

**Comment by Uafinder** [comment]
looks fine
