### ISSUE TITLE
Implement product categories

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#68]
The existing products app must be extended to allow products to be placed in categories

Note the requirement in - https://github.com/Kademi/kademi-dev/issues/52

There is no requirement in this issue for products to be browsable in categories, only that they can be managed on the admin side

**Comment by Uafinder** [comment]
Should be more wider.
![image](https://cloud.githubusercontent.com/assets/1945230/5874199/4ee3737e-a307-11e4-8307-6cd1addae5e7.png)

**Comment by Uafinder** [comment]
Resuming:
3. Base cost of category is empty while it already contains products which have base cost
![image](https://cloud.githubusercontent.com/assets/1945230/5892293/46eed304-a4c2-11e4-8adf-269c86953d9c.png)
4.

**Comment by bradmac** [comment]
Oops, that column should be removed. There should be no cost attributed to the category

**Comment by bradmac** [comment]
1. There is a problem with the toggle plugin, but fixing it is out of scope. Users are actually not affected.
2. Fixed
3. Fixed. Added numberof products and category image

**Comment by Uafinder** [comment]
1. Understood
2. Yeah, the photo is uploading ok, but when you're uploading it for the first time for this product category - you should refresh page to see changes.
3. Incorrect columns, code column shows photo, no photo column at all.
![image](https://cloud.githubusercontent.com/assets/1945230/5947738/2f2d3a66-a748-11e4-8542-76d2d9590f89.png)
4. When you are creating a product category it asks you for product code and title. But when it created, code field ignored, and code became a lowercase "Title" field.
![image](https://cloud.githubusercontent.com/assets/1945230/5947811/b5f66e0a-a748-11e4-8154-f9de2e830707.png)

**Comment by bradmac** [comment]
"Yeah, the photo is uploading ok, but when you're uploading it for the first time for this product category - you should refresh page to see changes." - Cant reproduce. Seems to display immediately after uploading. Can you confirm?

**Comment by bradmac** [comment]
"Incorrect columns, code column shows photo, no photo column at all." -- The code is not very relevant for categories, so we only display it if there is no photo. I've removed the "code" column header

**Comment by bradmac** [comment]
"When you are creating a product category it asks you for product code and title. But when it created, code field ignored, and code became a lowercase "Title" field. " - Fixed

**Comment by Uafinder** [comment]
Yeap, Looks ok!
