### ISSUE TITLE
Cannot send test email from Group emails

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#680]
http://admin.kademi.olhub.com/groupEmails/kademi-email-2-9-15-prospect/#messages-tab

Click send test.  Fails to send.

Note exact same email can be test sent from an triggered email.

**Comment by bradmac** [comment]
appears due to "No MimeMessage found"

**Comment by bradmac** [comment]
Problem is that the email does not have a valid from email address: "Kademi Newsletter"

**Comment by bradmac** [comment]
@tuzzmaniandevil can you add a validation to check the format of the from email address. Note that it must allow a textual part as well as email part, eg:

"Bob Smith <bob@smith.com>"

**Comment by bradmac** [comment]
@ducdhm can you take this?

**Comment by ducdhm** [comment]
@bradmac The `parse` method is in class `MailboxAddress`. And I dont have permission for editing this class

**Comment by ducdhm** [comment]
@bradmac How about this issue? Maybe i'll convert something like `Kademi Newsletter updates@kademi.co` to `Kademi Newsletter <updates@kademi.co>` before using `parse` of `MailboxAddress` class?

**Comment by bradmac** [comment]
You dont need to make any changes to MailboxAddress. All we need is some validation in the form to check the format is correct. It should allow either a plain email address, or an email address and display name

**Comment by ducdhm** [comment]
@bradmac So we don't support format like "Bob Smith bob@smith.com" without `<` before email address and `>` after email address, right?

**Comment by bradmac** [comment]
Correct. We only need to make sure the user has entered an email address is a correct standard form. I think there is an example address shown

**Comment by ducdhm** [comment]
Okay. I got it

**Comment by ducdhm** [comment]
jQuery.forms v1.0.10 will support new type of email https://github.com/Kademi/kademi-dev/issues/836

**Comment by bradmac** [comment]
No, we cant do it by making that format generally allowed for email inputs. Because for most forms email addresses must be strictly only email addresses, for example on a registration form.

Its only on these 2 particular screens that we support combined email address and name components

**Comment by ducdhm** [comment]
@bradmac Ok. I got it!

**Comment by bradmac** [comment]
The automation page layout is currently completely broken. I've reverted to the version prior to this issue. 

@ducdhm can you please re-do your changes, but make sure the page still works correctly?
