### ISSUE TITLE
KCom2: Add default state option to ecomCheckoutFormPointsOnlyComponent and ecomCheckoutFormComponent

### ISSUE THREAD

**Issue by trungjc** [Kademi/kademi-dev#6800]
Depend on https://github.com/Kademi/client-carters/issues/365#issuecomment-467680127

**Comment by trungjc** [comment]
![screenshot_12](https://user-images.githubusercontent.com/704946/53467870-8010e700-3a8a-11e9-93fb-18a83263fa00.png)
![screenshot_13](https://user-images.githubusercontent.com/704946/53467871-80a97d80-3a8a-11e9-9f37-28c9341da281.png)

**Comment by trungjc** [comment]
Updated on kcom2 v2.0.0

**Comment by Uafinder** [comment]
Ok, but note that this is not default state, it's just hide it from form
