### ISSUE TITLE
kSurvey: success message bad

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6803]
![image](https://user-images.githubusercontent.com/1945230/53482171-4f7b7e00-3a87-11e9-9f6f-836c16835de8.png)
http://vladtest56w.admin.kademi-ci.co/ksurvey/survey-43f53cce-c44e-454b-960d-e48ee9a79be5/#detail-tab
Clear cache

**Comment by bradmac** [comment]
Worked ok for me

**Comment by Uafinder** [comment]
Hmmm... probably due the page slow load
