### ISSUE TITLE
Error when open viewprofile template from leadman

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6804]
![image](https://user-images.githubusercontent.com/1945230/53497051-fd008880-3aab-11e9-81f7-c7db3d09a835.png)
http://vladtest56yweb-vladtest56y.kademi-ci.co//theme/apps/leadman/contenteditor?fileName=viewProfile.html
http://vladtest56y.admin.kademi-ci.co/pages/vladtest56yweb/version1/

**Comment by bradmac** [comment]
OK, should be fixed

**Comment by Uafinder** [comment]
looks better
