### ISSUE TITLE
Create separate template for ViewKCRMCompany

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6805]
![image](https://user-images.githubusercontent.com/1945230/53497590-31287900-3aad-11e9-9271-a3fdb28bcc67.png)
http://vladtest56y.admin.kademi-ci.co/pages/vladtest56yweb/version1/

**Comment by bradmac** [comment]
Fixed

Requires leadman-lib 3.4.4

**Comment by Uafinder** [comment]
Looks good
