### ISSUE TITLE
Improve background task handling

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6806]

**Comment by bradmac** [comment]
See AsyncJob, DbClientAsyncProcessor

**Comment by bradmac** [comment]
@Uafinder certain background tasks use this new framework. please focus on:
- importing lead contacts
- manually triggering integration pipelines (via upload and re-trigger)
- re-indexing search indexes
- table uploaders, ie import wizards
- running points allocations on data series

**Comment by bradmac** [comment]
For each task, please check that progress information is displayed appropriately

Note the "Background tasks" page has been updated:
![image](https://user-images.githubusercontent.com/826458/53688092-52d27a80-3da3-11e9-8fe9-a336c2bd6596.png)

**Comment by bradmac** [comment]
Note that this is high priority because once in production any defects will have a serious impact on our clients. So we cant do a production update until this has been tested.

**Comment by Uafinder** [comment]
ok, looks good
