### ISSUE TITLE
Kcom2 - Pricing rules to have an association with SKU code

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#6809]
Either Product Code becomes SKU Code, or can you add SKU Code an a new option.

This is important for Waterware as they have set up a product look up table that specifies an exact cost on a customer group per product (referencing product code).

This needs to be per SKU Code because some products have a Variant type.

**Comment by bradmac** [comment]
Example:

For this SKU:
![image](https://user-images.githubusercontent.com/826458/53538206-980f6600-3b71-11e9-8b12-d63eb90b076e.png)

I have this rule to match on the SKU and apply a fixed value:
![image](https://user-images.githubusercontent.com/826458/53538235-ac536300-3b71-11e9-9402-cd23f41cf626.png)

Which is shown here: (i have a multiplier)
![image](https://user-images.githubusercontent.com/826458/53538249-c3925080-3b71-11e9-9a3d-ec2d922b0cca.png)

And when the actual SKU is selected
![image](https://user-images.githubusercontent.com/826458/53538269-d9a01100-3b71-11e9-9edb-ac494e1fb1c4.png)

**Comment by bradmac** [comment]
This change includes a small update to kcom2 2.0.1 - but this is only display text, is not functionally needdd

**Comment by Uafinder** [comment]
Ok, looks good

**Comment by stephen-fueldesign** [comment]
@bradmac does this require a deploy by Kademi before I can see the results? #

**Comment by bradmac** [comment]
yep
