### ISSUE TITLE
kCom2 install: NPE error

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6812]
![image](https://user-images.githubusercontent.com/1945230/53572468-f63d4880-3b73-11e9-9c98-ad83d5d5bee8.png)
http://vladtest56zz.admin.kademi-ci.co/marketPlace/KCommerce2/?websiteBranch=version1&websiteName=vladtest56zzweb
Because of it, kcom index not create properly
![image](https://user-images.githubusercontent.com/1945230/53572527-1a992500-3b74-11e9-8b1c-025fd8498f6f.png)
![image](https://user-images.githubusercontent.com/1945230/53572560-3270a900-3b74-11e9-978a-97f049ba105b.png)

**Comment by bradmac** [comment]
strange, not quite sure whats causing that, but i've pushed a defensive check which should prevent it

**Comment by Uafinder** [comment]
Looks good
