### ISSUE TITLE
recently viewed products and you may also like components prices no matter of price rules

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6816]
![clipboard - march 1 2019 9-29 am](https://user-images.githubusercontent.com/1945230/53624066-9c865e00-3c07-11e9-9c16-9a66406ed6f6.png)
![clipboard - march 1 2019 9-41 am](https://user-images.githubusercontent.com/1945230/53624074-a14b1200-3c07-11e9-9b02-119ca97dd6b0.png)
http://carters-test_carterstest.kademi.com.au/carters-test-ecomstore/750-compact-white-20l-microwave-sharp

**Comment by trungjc** [comment]
![screenshot_5](https://user-images.githubusercontent.com/704946/53625677-509edd80-3c36-11e9-9fc4-f3e808f89784.png)
![screenshot_6](https://user-images.githubusercontent.com/704946/53625679-51377400-3c36-11e9-85f8-ea87deb6e9bb.png)

Updated product price
Also add Currency symbol and Symbol position

**Comment by Uafinder** [comment]
ok, looks good
