### ISSUE TITLE
kcom2: view store cause 500 error (new QA)

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6817]
![image](https://user-images.githubusercontent.com/1945230/53634150-19becc80-3c22-11e9-99e2-b94923bffeed.png)
![image](https://user-images.githubusercontent.com/1945230/53634163-217e7100-3c22-11e9-896a-23b832294291.png)
http://vladtest57a.admin.kademi-qa.co/websites/vladtest57aweb/version1/store-vladtest57aweb-ecomstore/#products-tab

fresh account
install kcom2
try to view store

**Comment by bradmac** [comment]
Fixed. There was a server initialisation problem due to https://github.com/Kademi/kademi-dev/issues/6806

**Comment by Uafinder** [comment]
looks good
