### ISSUE TITLE
Error in console when accessing page in editor

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6818]
![image](https://user-images.githubusercontent.com/1945230/53644228-bc854400-3c3e-11e9-8d02-27514b9ee976.png)
http://vladtest57aaweb-vladtest57aa.kademi-ci.co//theme/apps/KCommerce2/contenteditor?fileName=viewProduct.html
http://vladtest57aaweb-vladtest57aa.kademi-ci.co//theme/apps/KCommerce2/contenteditor?fileName=viewStore.html
http://vladtest57aa.admin.kademi-ci.co/pages/vladtest57aaweb/version1/

![image](https://user-images.githubusercontent.com/1945230/53644365-184fcd00-3c3f-11e9-9ead-546dece05bcf.png)

**Comment by bradmac** [comment]
Same cause as https://github.com/Kademi/kademi-dev/issues/6817

**Comment by Uafinder** [comment]
Ok, looks good
