### ISSUE TITLE
KRecognition: New component to show horizontal progress bar of levels

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6822]
Please create a component in the KRecognition app to visually represent progress through levels. This will show 
- a progress bar
- level names
- the configured amount to reach each level

Similar to this:
![image](https://user-images.githubusercontent.com/826458/53709714-8cd47700-3e9e-11e9-9153-2b46f9a060f6.png)

Component settings should allow 
- selecting the topic

An example topic is:
![image](https://user-images.githubusercontent.com/826458/53709732-a7a6eb80-3e9e-11e9-99ad-4dc1275b8239.png)

**Comment by anhnt** [comment]
![horzlevelprogresspanel](https://user-images.githubusercontent.com/735555/53712327-fc377000-3e78-11e9-82ca-001e99ab1226.png)

Requires KRecognition 1.1.5

**Comment by Uafinder** [comment]
Looks good... one thing
![image](https://user-images.githubusercontent.com/1945230/53724444-93e59000-3e72-11e9-815a-8476ef255100.png)
http://vladtest57bweb-vladtest57b.kademi-qa.co/profile/
http://vladtest57b.admin.kademi-qa.co/manageUsers/40411/#summary-tab

Vlad 11:03 AM
is it intended to have some space after last level?
anh 11:07 AM
it says 99%
i will add some round

**Comment by anhnt** [comment]
please try now

-------- RESULTS -------------
Published KRecognition version 1.1.6 with hash
df8baf8aab278a8c42a89991660719fa4b55b405

**Comment by Uafinder** [comment]
Looks good
