### ISSUE TITLE
Import points error

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6825]
![image](https://user-images.githubusercontent.com/1945230/53716870-ffbdfd80-3e5e-11e9-8739-4cf87d0a0cc9.png)
http://vladtest57b.admin.kademi-qa.co/points-buckets/points/#points-tab
![image](https://user-images.githubusercontent.com/1945230/53716876-08163880-3e5f-11e9-97af-5c8f021ea742.png)

probably something didn't move from old rewardstore-lib...

**Comment by bradmac** [comment]
Moved to Rewards app, which is available

**Comment by Uafinder** [comment]
Looks good
