### ISSUE TITLE
500 errors in console when accessing reindex page

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6827]
![image](https://user-images.githubusercontent.com/1945230/53717539-22511600-3e61-11e9-800f-6982d91e36bb.png)
![image](https://user-images.githubusercontent.com/1945230/53717564-31d05f00-3e61-11e9-9b7d-845297285163.png)
http://vladtest57b.admin.kademi-qa.co/manageSearch/

**Comment by bradmac** [comment]
Fixed on other issue

**Comment by Uafinder** [comment]
Looks good
