### ISSUE TITLE
Backgound tasks old processes issue

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6828]
![image](https://user-images.githubusercontent.com/1945230/53718861-18311680-3e65-11e9-807d-91faa76b65a8.png)
http://vladtest57b.admin.kademi-qa.co/tasks/
Old processes have no PID
However sorting looks like appears by PID, so tasks without PID will be always on top, which is bad

The simple way to solve that is to make sorting by creation date.

https://github.com/Kademi/kademi-dev/issues/6806

**Comment by bradmac** [comment]
This is ok. This page is rarely used by users, so will not have much impact.

The old processes will be upgraded to the new framework in time to resolve the issue

**Comment by Uafinder** [comment]
ok, got it
