### ISSUE TITLE
NPE appears on module results import when modified date not specified

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6831]
![image](https://user-images.githubusercontent.com/1945230/53719714-8ecf1380-3e67-11e9-8775-ae9c1fbb8bba.png)
![image](https://user-images.githubusercontent.com/1945230/53719729-97bfe500-3e67-11e9-882d-908478bce7c9.png)
![image](https://user-images.githubusercontent.com/1945230/53719737-9c849900-3e67-11e9-998b-faa7bf64dff6.png)
http://vladtest57b.admin.kademi-qa.co/tableUploaders/moduleStatusUploader
[trainingResults (9).zip](https://github.com/Kademi/kademi-dev/files/2924846/trainingResults.9.zip)

**Comment by bradmac** [comment]
Fixed

**Comment by Uafinder** [comment]
looks good
