### ISSUE TITLE
Constaint violation error when try to delete level which has awarded users

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6832]
![image](https://user-images.githubusercontent.com/1945230/53721629-60076c00-3e6c-11e9-9066-a2f11bbe7f18.png)
![image](https://user-images.githubusercontent.com/1945230/53721651-6a296a80-3e6c-11e9-9980-712188f69e18.png)
http://vladtest57b.admin.kademi-qa.co/recognition/77872/

**Comment by bradmac** [comment]
Fixed. Now deletes related awards.

**Comment by Uafinder** [comment]
Yup, looks good
