### ISSUE TITLE
Action column in level recognition

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6833]
![image](https://user-images.githubusercontent.com/1945230/53721746-a5c43480-3e6c-11e9-8f4f-adb052f42983.png)
http://vladtest57b.admin.kademi-qa.co/recognition/77872/

Why it's appear and what is this? Is it always empty?

**Comment by bradmac** [comment]
Good question!

**Comment by bradmac** [comment]
ok, thats just the heading for the toolbar column. Removed in 1.1.7

**Comment by Uafinder** [comment]
Looks good
