### ISSUE TITLE
Nominee user link leads to manage users page

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6836]
![image](https://user-images.githubusercontent.com/1945230/53735310-2b58dc00-3e8f-11e9-8d17-e538a713880b.png)
http://vladtest57b.admin.kademi-qa.co/recognition/78981/badges/78982/#award-tab

**Comment by bradmac** [comment]
Fixed. Requires 1.1.7

**Comment by Uafinder** [comment]
Looks good
