### ISSUE TITLE
rejecting nominee cause to incorrect message

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6837]
![image](https://user-images.githubusercontent.com/1945230/53735382-59d6b700-3e8f-11e9-90a2-8a23efd5e397.png)
![image](https://user-images.githubusercontent.com/1945230/53735392-60fdc500-3e8f-11e9-85bf-eb0953d13849.png)
http://vladtest57b.admin.kademi-qa.co/recognition/78981/badges/78982/#award-tab

**Comment by bradmac** [comment]
Fixed. Requires 1.1.7

**Comment by Uafinder** [comment]
Looks good
