### ISSUE TITLE
KRedirect - a valid Target URL producing validation errors.

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#6842]
I created a whole bunch of URL redirects.

However a lot are not editable for some reason, even though the Target URL is a valid resource.

<img width="590" alt="screen shot 2019-03-05 at 12 24 01 pm" src="https://user-images.githubusercontent.com/39784677/53769855-fce80900-3f41-11e9-85f0-ff983c4eca60.png">

Here is where I'm trying to edit redirects:
https://hazero.admin.kademi.com.au/kredirect/

It's a valid URL.
https://www.hazero.co.nz/products/control-cleanup/

**Comment by anhnt** [comment]
Fixed that and deployed to hazero
I also found some wrong urls
try this code in console

```
var a = []; $('#redirectsTableBody tr').each(function(){a.push($(this).find('td').first().text().trim())})
ar c = []; 
var b = a.map(function(item){var t = /^[a-zA-Z0-9_/%:/.\-\+]+$/.test(item); if (!t) c.push(item); return t;});
c.join('    ');
```

So for example this is wrong:
`/shop/Control+%26+Cleanup/Spill+Response+Kits/Sp ecialty+Spill+Kits/Biohazard+Spillkit-13-2001.html`
