### ISSUE TITLE
Issue with KForums doWallSearch

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#6843]
Calling Kforums `doWallSearch` with no wall entity doesn't return any results.
It should return walls the profile has access to, Below is the query it uses, The contentId array is empty. It should at least have: wall-p-17754269 and wall-17754189 which is the users own wall and he's orgs wall.

Using version 1.1.1 on CI

This is the user: http://vayability.admin.kademi-ci.co/manageUsers/17754269/#summary-tab

```json
{
  "_source": true,
  "from": 0,
  "size": "8",
  "sort": [
    {
      "postDate": {
        "order": "DESC"
      }
    }
  ],
  "query": {
    "bool": {
      "should": [
        {
          "terms": {
            "taggedProfileIds": [
              17754269
            ]
          }
        },
        {
          "terms": {
            "contentId": []
          }
        }
      ],
      "minimum_should_match": 1
    }
  }
}
```

**Comment by bradmac** [comment]
@tuzzmaniandevil here's your problem:
```
          "terms": {
            "contentId": []
          }
```

There are no wall ID's in the query.

The list comes from here:

```
        var availContentIds = findAvailWallContentIds(profile);
        queryBody.should.push({
            "terms": {
                "contentId": availContentIds
            }
        });
```

which uses this..

```
function findAvailWallContentIds(profile) {
    var orgs = findTeamOrgs(profile);
    log.info("findAvailWallContentIds: orgs={}", orgs.size());
    var wallContentIds = [];
    formatter.foreach(orgs, function(org) {
        wallContentIds.push( services.forumManager.wallContentId(org) );
    });
    return wallContentIds;
}
```

So i suggest you do some debugging and check to see whether the configuration has been applied correctly, ie in findTeamOrgs

**Comment by tuzzmaniandevil** [comment]
From Brad

> here's what I'm thinking
> 
> Dashboard aggregates:
> - posts from all available walls
> - all posts made by the currently logged in user
> - all posts made to the private wall of the currently logged in user

**Comment by bradmac** [comment]
@tuzzmaniandevil are you planning to do that? or want me to?

**Comment by tuzzmaniandevil** [comment]
I was going to do it, But happy for you to do it.

**Comment by bradmac** [comment]
Done.

**Comment by tuzzmaniandevil** [comment]
@bradmac Is this on CI and/or Vaya CI?

**Comment by bradmac** [comment]
I've just pushed to KForums, havent deployed anything

**Comment by tuzzmaniandevil** [comment]
@bradmac I seem to be getting an error:
`class org.apache.velocity.exception.MethodInvocationException::Invocation of method 'call' in class io.milton.cloud.server.repoapps.RepositoryApp threw exception ParsingException[[terms] query does not support [profileId]] `

**Comment by tuzzmaniandevil** [comment]
Pushed a fix
