### ISSUE TITLE
Organisations Uploader: Error when uploading CSV

### ISSUE THREAD

**Issue by joelatfuel** [Kademi/kademi-dev#6844]
I tried to upload a CSV of Organisations to the Farmgard AU website. I was about to set my destination fields (I used the Dealer Spreadsheet Import configuration) and as I clicked import now nothing happened.

Here's the console error log: `Form submission failed, as the <SELECT> element named 'col0' was implicitly closed by reaching the end of the file. Please add an explicit end tag ('</SELECT>')`

Here's a [link](https://farmgard.admin.kademi.com.au/tableUploaders/organisationsUploader) to the URL, and the file I used is below.

[Australian Dealers Import.xlsx](https://github.com/Kademi/kademi-dev/files/2929034/Australian.Dealers.Import.xlsx)

**Comment by bradmac** [comment]
I just followed those steps and it worked fine:

![image](https://user-images.githubusercontent.com/826458/53777332-e2bc2400-3f5d-11e9-8c27-3beec0c1d2c0.png)

**Comment by bradmac** [comment]
@joelatfuel can you provide any more information? eg what browser are you using?

**Comment by joelatfuel** [comment]
I'm using Chrome Version 72.0.3626.119 on Mac OS 10.14

**Comment by bradmac** [comment]
@Uafinder could you take a look?

**Comment by Uafinder** [comment]
Looks good for me as well... is it reproducible? @joelatfuel

**Comment by Uafinder** [comment]
Also tried both Win and Mac upload - everything seems to be fine

**Comment by joelatfuel** [comment]
Hi Brad,

I'm still getting this error. Could you please upload this file on my behalf?
[Org Import.xlsx](https://github.com/Kademi/kademi-dev/files/2932574/Org.Import.xlsx)

**Comment by bradmac** [comment]
@joelatfuel can you jump onto partner-support chat? I want to know what error you're seeing
