### ISSUE TITLE
Adding class SM XS causes container to disappear in Keditor

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#6847]
http://kademi-2019_kademi.kademi.us//theme/contenteditor?fileName=page.html

When you add the class visible-lg and visible-md the container shows in Keditor.

![image](https://user-images.githubusercontent.com/2201340/53785737-a264a200-3f6d-11e9-91ee-134f8b3d97b8.png)

When you add the classes visible-sm and visible-xs the container hides in Keditor but the section still appears in the source code and renders correctly in the front end.

![image](https://user-images.githubusercontent.com/2201340/53785801-dcce3f00-3f6d-11e9-8d26-38c4cda7086f.png)

**Comment by bradmac** [comment]
@Uafinder please check if this is a platform issue. If not, then it can be closed.

**Comment by anhnt** [comment]
FYI we have to follow bootstrap docs

![image](https://user-images.githubusercontent.com/735555/53785989-c663bb80-3f4c-11e9-8296-1effded9be79.png)

**Comment by paddyow** [comment]
Note adding the class **hidden**-sm for example, causes the container to hide.

**Comment by bradmac** [comment]
@anhnt says this is normal, expected behaviour. just dont add the 2 classes, just one
