### ISSUE TITLE
When approve badge nomination this not cause badge to be awarded

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6848]
![image](https://user-images.githubusercontent.com/1945230/53786492-8dafec00-3f24-11e9-9f41-77c21cbc1d87.png)
![image](https://user-images.githubusercontent.com/1945230/53786516-9b657180-3f24-11e9-932f-0621e50e5b3b.png)
http://vladtest57b.admin.kademi-qa.co/recognition/78981/badges/78983/#award-tab
I'm expecting that when user is nominated and nomination approved badge should appear in awarded sections and on the frontend. This not happening.

**Comment by bradmac** [comment]
This was actioned in another issue, should be working now

**Comment by Uafinder** [comment]
looks good
