### ISSUE TITLE
Badge Nominated, Approved and Rejected actions should appears in user timeline 

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6849]
http://vladtest57b.admin.kademi-qa.co/manageUsers/40465/#summary-tab
![image](https://user-images.githubusercontent.com/1945230/53786668-1038ab80-3f25-11e9-964e-f38b9c75cb88.png)

**Comment by bradmac** [comment]
Done previously

**Comment by Uafinder** [comment]
It only shows information when badge awarded, not when nominated or nomination cancelled.
Also when nomination approved it doesn't show that badge was nominated and not earned and who nominate user to it
![image](https://user-images.githubusercontent.com/1945230/54427392-10098e80-4723-11e9-9199-d008ea781af7.png)
![image](https://user-images.githubusercontent.com/1945230/54427405-1435ac00-4723-11e9-8918-f904679a39ab.png)
http://vladtest57l.admin.kademi-qa.co/recognition/255425/badges/255426/#award-tab

**Comment by bradmac** [comment]
Done

![image](https://user-images.githubusercontent.com/826458/54468368-bd96a380-47f0-11e9-8ddb-2cfa0e68127c.png)

**Comment by bradmac** [comment]
Requires KRecognition 1.1.9

**Comment by Uafinder** [comment]
Ok, looks good
One improvement moved to another issue
https://github.com/Kademi/kademi-dev/issues/6942
