### ISSUE TITLE
Cannot add a user

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#685]
http://developer.admin.olhub.com/manageUsers/

This was a sub org of Kademi created a while back. You cannot add a user and it shows template code in the overview stats.

**Comment by bradmac** [comment]
Problem is because the new user index hasnt been created, so just reindex to fix.
Probably should check for a missing index

**Comment by bradmac** [comment]
@tuzzmaniandevil can add a check to make sure that if the index hasnt been created there's no exception?

**Comment by bradmac** [comment]
Done
