### ISSUE TITLE
Manage SKUs: Tool to create all missing SKUs

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6852]
- option to choose whether the sku code should be combination of base product code and variants, or just variant code(s)
- option to choose default stock quantities
- should restore deleted SKU if there is one.

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/53841706-557edb00-4002-11e9-9b82-5a0ae12284ca.png)

![image](https://user-images.githubusercontent.com/826458/53841727-60397000-4002-11e9-83ae-9670e78fed8f.png)

**Comment by bradmac** [comment]
Requires platform update and products-lib 1.1.8

**Comment by Uafinder** [comment]
Ok, looks good
One thing would be great to add:
- option where take SKU cost (base cost or variant cost)

Also when you click to create on modal after modal closes all Stock values disappear and appears only after refresh
