### ISSUE TITLE
Add option to badges to allow or not nomination feature

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6855]
We need this to Vaya to allow or not badge for nomination. Probably just a boolean switch inside badge options which will enable this feature for some current badge. Should be disabled by default.
https://github.com/Kademi/client-vaya-vayability/issues/386

Also need to select
- who can make nominations
- who can be a nominee

**Comment by bradmac** [comment]
Closing as duplicate of https://github.com/Kademi/kademi-dev/issues/6598
