### ISSUE TITLE
Add some tip text which will describe what Brand is

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6859]
Please add something like:
"Brand is also a category to filter products"

i've forgot that this is a category and sitting some time and thinking what is it
even tried to create org with org type "brand"
then Anh helped me
could not be obvious for user

**Comment by bradmac** [comment]
Done. Requires products-lib 1.1.9

Also added help text to other fields

**Comment by Uafinder** [comment]
ok, looks good
