### ISSUE TITLE
Selecting path in menu component cause Undefined to appear

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6860]
![image](https://user-images.githubusercontent.com/1945230/53876993-b1e8f700-4010-11e9-834a-36b0a7bcc8e5.png)
![image](https://user-images.githubusercontent.com/1945230/53877011-bad9c880-4010-11e9-970d-ee3eda084048.png)
![image](https://user-images.githubusercontent.com/1945230/53877019-bf9e7c80-4010-11e9-9ba5-e0c4c5ebbde4.png)
http://vladtest57dweb-vladtest57d.kademi-qa.co//theme/contenteditor?fileName=defaultThemeTemplate.html

**Comment by bradmac** [comment]
This is a critical part of using keditor, so high priority.

**Comment by anhnt** [comment]
Fixed in contentEditor 1.4.5

**Comment by Uafinder** [comment]
looks good
