### ISSUE TITLE
Email tile leads to incorrect page (shopping cart page)

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6872]
http://vladtest57d.admin.kademi-qa.co/
![image](https://user-images.githubusercontent.com/1945230/53887067-25e3c900-402a-11e9-87d2-195d91cde4be.png)

**Comment by bradmac** [comment]
Fixed.

Requires email-lib 1.2.0

**Comment by Uafinder** [comment]
Yup, seems to be fine now
