### ISSUE TITLE
WebP images do not load on multilingual sites

### ISSUE THREAD

**Issue by joelatfuel** [Kademi/kademi-dev#6873]
SP Insurance uses assets to display content for the English and Chinese versions. The webp image loads on the English asset, but on the Chinese version it won't load. It will load if I uncheck the webp checkbox on the Chinese version.

- [Chinese Asset](https://spinsurance.admin.kademi.com.au/asset-manager/bae5c696-1e3d-4f4b-828c-18be03d981d1)

**Comment by bradmac** [comment]
@joelatfuel can you give me a link to an image URL that doesnt load?

**Comment by joelatfuel** [comment]
Here's the image URL: https://spinsurance.kademi.com.au/assets/57b8d7c8-d93e-47ec-93b8-4aa9469ab64f

**Comment by bradmac** [comment]
That loads ok for me. What is an image url that doesnt load?

**Comment by joelatfuel** [comment]
That's the asset that's being referenced, but in the live Chinese version there is no source.
<img width="658" alt="screen shot 2019-03-07 at 10 23 35 am" src="https://user-images.githubusercontent.com/41346338/53914715-23817d80-40c3-11e9-9c87-715a062cadd5.png">

**Comment by joelatfuel** [comment]
The page is https://www.spinsurance.co.nz/, but you'll need to use the language selector and change to the Chinese version.

I've attached a photo of the missing image
<img width="1280" alt="screen shot 2019-03-07 at 12 15 00 pm" src="https://user-images.githubusercontent.com/41346338/53920977-c510cb00-40d3-11e9-95a2-c9f0e28cd50c.png">

**Comment by bradmac** [comment]
Ok, so this is the image asset:
https://www.spinsurance.co.nz/assets/47025f71-507a-4483-8b20-eb33c2c054b6

**Comment by bradmac** [comment]
Problem was that the trans-lookup class was on the picture element

**Comment by bradmac** [comment]
Fixed
