### ISSUE TITLE
Sales data claimer: various admin improvements

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6874]
- fix status filtering
- allow entering the entered by user for the claim
- fix ordering of results

**Comment by bradmac** [comment]
@anhnt can you please integrate the profile selector here ... should submit the profile ID (not user name)

![image](https://user-images.githubusercontent.com/826458/53915875-aacff080-40c5-11e9-8a56-95b88f5c0fef.png)

**Comment by anhnt** [comment]
done in salesDataClaimer 1.6.2

**Comment by Uafinder** [comment]
Few more fixes needed
![image](https://user-images.githubusercontent.com/1945230/53955048-951bf480-40e0-11e9-8973-3d9829542f11.png)
This link leads to incorrect page, should lead to edit org page
http://vladtest57e.admin.kademi-qa.co/manageSaleDataClaimer/#claims-list-tab

Also when i creating claim and specify claim by and sold by users
![image](https://user-images.githubusercontent.com/1945230/53955181-f5ab3180-40e0-11e9-8858-a9cf17e02507.png)
Sold by still remains current user
![image](https://user-images.githubusercontent.com/1945230/53955230-1b383b00-40e1-11e9-95fa-ee5d65401d8a.png)
http://vladtest57e.admin.kademi-qa.co/manageSaleDataClaimer/#claims-list-tab

Also no chance to edit claimed by field after creation
![image](https://user-images.githubusercontent.com/1945230/53955294-4d499d00-40e1-11e9-8163-94cd01866d54.png)
http://vladtest57e.admin.kademi-qa.co/manageSaleDataClaimer/#claims-list-tab

**Comment by bradmac** [comment]
> This link leads to incorrect page, should lead to edit org page

Fixed

**Comment by bradmac** [comment]
Another issue: the sold by user for each claim item was not being saved. Fixed

**Comment by bradmac** [comment]
> Also no chance to edit claimed by field after creation
> also claims date using incorrect timezone to display date time

This should be done in a separate issue, its a relatively low priority.

**Comment by bradmac** [comment]
Requires salesDataClaimer 1.6.5

**Comment by Uafinder** [comment]
Ok, looks good
