### ISSUE TITLE
MSelect: Files browser doesnt work from ckeditor when in a subfolder

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6875]
- When editing a page in a website sub-folder
- Add a html component
- Click the image button to insert an image
- the Files tab doesnt load:

![image](https://user-images.githubusercontent.com/826458/53925237-14f78e00-40e4-11e9-9058-928240bdf0d7.png)

Note this DOES work correctly when editing a page in the root of the website

The problem is the _browse resource is loaded from a relative path, should be the root of the website

Eg: /folder1/_browse?browseHref=

Should be /_browse?browseHref=/folder1

If getting the current folder path is tricky just loading the root is  fine

**Comment by anhnt** [comment]
fixed in fuse-image ckeditor plugin so it wont affect admin console

**Comment by Uafinder** [comment]
Looks fine
