### ISSUE TITLE
Auction-lib: add some settings to auctionBidHistoryComponent

### ISSUE THREAD

**Issue by trungjc** [Kademi/kademi-dev#6877]
Add title and no bid message to the component settings

**Comment by trungjc** [comment]
![screenshot_4](https://user-images.githubusercontent.com/704946/53943717-51c98200-40f0-11e9-9b9b-09d4acb4e57f.png)

**Comment by trungjc** [comment]
Updated in v1.2.4

**Comment by Uafinder** [comment]
Ok, looks cool
