### ISSUE TITLE
Auction-lib: add bid form to auction item list

### ISSUE THREAD

**Issue by trungjc** [Kademi/kademi-dev#6878]
Add bid form, auction status to item

**Comment by trungjc** [comment]
![screenshot_5](https://user-images.githubusercontent.com/704946/53953845-0b335200-4107-11e9-9b43-dfdcb5c6d299.png)

**Comment by trungjc** [comment]
update in v1.2.4

**Comment by bradmac** [comment]
@trungjc has this been done, or are you going to do it?

**Comment by bradmac** [comment]
I think its ready for test

**Comment by Uafinder** [comment]
not seeing outbid label
![image](https://user-images.githubusercontent.com/1945230/54114718-b1c36f80-43f3-11e9-9393-02e4e30be9f7.png)
http://vladtest57fweb-vladtest57f.kademi-qa.co/page1.html

Also not seeing any date
![image](https://user-images.githubusercontent.com/1945230/54114905-1b437e00-43f4-11e9-832c-978fa0d8dac5.png)
![image](https://user-images.githubusercontent.com/1945230/54114913-21d1f580-43f4-11e9-81a9-7ba179893245.png)

Also initial bid showing with default pre-selected currency symbol 
![image](https://user-images.githubusercontent.com/1945230/54115075-75dcda00-43f4-11e9-9d88-8d873d839465.png)

Also i think should be space between image and panel which showing Status
![image](https://user-images.githubusercontent.com/1945230/54115136-960c9900-43f4-11e9-9364-d5ee2bc2cc11.png)

**Comment by trungjc** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/704946/54119532-27493300-4428-11e9-8503-77d4a5b1b5fa.png)

Updated new fake content to auction item list

**Comment by trungjc** [comment]
![Screenshot_4](https://user-images.githubusercontent.com/704946/54119891-08976c00-4429-11e9-9079-40a2465946bd.png)

**Comment by Uafinder** [comment]
Ok, looks better
