### ISSUE TITLE
Web activity report shows nothing

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6881]
http://vladtest57e.admin.kademi-qa.co/reporting/esWebsiteAccess?startDate=05%2F03%2F2019&finishDate=09%2F03%2F2019
However there are a lot of visits by users into site

**Comment by bradmac** [comment]
Fixed

![image](https://user-images.githubusercontent.com/826458/53996656-2ac98980-419e-11e9-8510-d01a3ce1ef76.png)

**Comment by Uafinder** [comment]
ok, looks good
