### ISSUE TITLE
Indexing on AU and US not working

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#6887]
http://trisys.admin.kademi.com.au/manageSearch/

http://trisys.admin.kademi.us/manageSearch/

Both indexes say there are more than 1 profile, from the manage users page only 1 profile shows.

Have re-indexed.

**Comment by bradmac** [comment]
this says there is one profile,, which appears correct

![image](https://user-images.githubusercontent.com/826458/54060121-6dec3100-4260-11e9-9c3f-5db84fa97f28.png)

**Comment by bradmac** [comment]
same on US server

![image](https://user-images.githubusercontent.com/826458/54060161-95db9480-4260-11e9-8fe1-771c91c637c0.png)
