### ISSUE TITLE
Waterware - Contactus default app not showing in Contact Request

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#6892]
Hi,

Here is the frontend.
http://waterware-waterware.kademi.com.au/contactus

Non of these enquiries are showing Contact Requests.
https://waterware.admin.kademi.com.au/manageContacts/

Admin email sends.
Journey is triggered correctly.

**Contact form path** is correctly set up too:
http://waterware-waterware.kademi.com.au//theme/apps/contactus/contenteditor?fileName=contactForm.html

Thanks!

**Comment by bradmac** [comment]
```
INFO - 11-03-2019T12:56:24,289 - io.milton.cloud.server.search.DefaultElasticSearchManager  - Bulk response: failure(s) failure in bulk execution:
[0]: index [syd1-profile-114532092.1552259754680], type [contactRequest], id [143234373], message [java.lang.IllegalArgumentException: Mapper for [subject.keyword] conflicts with existing mapping in other types:
[mapper [subject.keyword] has different [store] values]]

```

**Comment by bradmac** [comment]
The problem is occuring because of the use of a standard field name "subject"

**Comment by bradmac** [comment]
I've added a check when indexing to see if a custom field name is a standard field, and if so prefixes it with contact-field-

This should prevent naming conflicts in future

For now delete existing contact requests, and change the form to not use the keyword "subject"
