### ISSUE TITLE
OAuth screens need to be updated to work with components

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6894]
What we need is
- create a new lib oauth2server-lib with assets from templates/apps/oauth2server/
- create a template theme/apps/oauth2server-lib/authorization.html containing a single new component oauth2AuthComponent
- this component will be based on the current template templates/apps/oauth2server/authorization.html

The please publish to AU and install here https://carterstest.admin.kademi.com.au/websites/carters-test/carters-dev/

**Comment by anhnt** [comment]
new app: KOauth2server
new lib: oauth2server-lib

**Comment by anhnt** [comment]
installed to carterstest

**Comment by anhnt** [comment]
example admin https://carterstest.admin.kademi.com.au/apiApps/

**Comment by Uafinder** [comment]
Is this expected?
![image](https://user-images.githubusercontent.com/1945230/54276765-d441be00-4596-11e9-9d6c-cf120416acbb.png)
![image](https://user-images.githubusercontent.com/1945230/54276781-dad03580-4596-11e9-9fc3-a97062148e18.png)
Empty success message
![image](https://user-images.githubusercontent.com/1945230/54276814-eae81500-4596-11e9-85a0-f2a71671ed9c.png)
http://vladtest57hweb-vladtest57h.kademi-qa.co/contenteditor?fileName=page2.html

**Comment by bradmac** [comment]
@Uafinder looks like the component editor rendering can be improved, but thats not a blocker on this issue.

So I'll copy that to a new issue and close this one.
