### ISSUE TITLE
auction link text bad

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6898]
![image](https://user-images.githubusercontent.com/1945230/54111438-7d988080-43ec-11e9-951d-7d5b58bd50e6.png)
Only on hover
![image](https://user-images.githubusercontent.com/1945230/54111450-86895200-43ec-11e9-97a8-f98e86a9126e.png)
http://vladtest57fweb-vladtest57f.kademi-qa.co/auctions/

**Comment by Uafinder** [comment]
Same on custom component
![image](https://user-images.githubusercontent.com/1945230/54114574-64df9900-43f3-11e9-8368-8e967d9a57a7.png)
http://vladtest57fweb-vladtest57f.kademi-qa.co/page1.html

**Comment by trungjc** [comment]
![Screenshot_5](https://user-images.githubusercontent.com/704946/54120071-61ff9b00-4429-11e9-8089-1c5133ae8677.png)

updated in v 1.2.5

**Comment by Uafinder** [comment]
ok, looks good
