### ISSUE TITLE
pointsTransactions component does not show the balance when there are no transactions within the date range

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6899]
Eg when logged in as this user:
https://carters.admin.kademi.com.au/manageUsers/8244334/#summary-tab

Select a date range of 3 months and no transactions are shown, and no balance:
![image](https://user-images.githubusercontent.com/826458/54161239-6d4cd800-44b6-11e9-8520-9b09c18a340f.png)

But select a date range of 1 year and you can see the points balance:
![image](https://user-images.githubusercontent.com/826458/54161293-92d9e180-44b6-11e9-82ab-fbc8f50a9ec2.png)

Please ensure the points balance is always shown

**Comment by trungjc** [comment]
Update current balance to always show
![Screenshot_3](https://user-images.githubusercontent.com/704946/54172897-47bdcf80-44b2-11e9-8113-1876b4bbb928.png)

Also add currency settings to component. Not that Show item currency don't affect to **Current Balance**

![Screenshot_2](https://user-images.githubusercontent.com/704946/54172917-5c9a6300-44b2-11e9-86f0-451d518ef672.png)

**Comment by Uafinder** [comment]
Looks good
