### ISSUE TITLE
KFeedback form component just doesnt work

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6900]
I just tried to use the KFeedback app with a component in a page, but it appears that it just does not work

Instead of displaying the feedback choices it says "submitting your feedback"

![image](https://user-images.githubusercontent.com/826458/54169420-87e37900-44d7-11e9-9dbe-04ade9606afa.png)

**Comment by anhnt** [comment]
as discussed we need a separate component for allowing submitting feedback manually ie not from email

**Comment by anhnt** [comment]
![image](https://user-images.githubusercontent.com/735555/54210235-b2eabe80-4511-11e9-922b-f69b1b9ddca4.png)

This form will be auto submitted when on default page ie view from email link

**Comment by Uafinder** [comment]
ok
