### ISSUE TITLE
claim list improvements

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6901]
- Add search box to find a claim by claim id
- add claim id as a column
![image](https://user-images.githubusercontent.com/1945230/54188385-3b3c7580-44b8-11e9-93ad-a8ce0cca3835.png)
https://mhiaainstaller.admin.kademi-qa.co/manageSaleDataClaimer/#claims-list-tab

**Comment by bradmac** [comment]
I think it would be best if the search box searched a few key fields
- userid
- product sku
- anything else that makes sense.

**Comment by tuzzmaniandevil** [comment]
Will search the following fields:
- recordId
- claimItems.productSku
- claimItems.soldBy

**Comment by tuzzmaniandevil** [comment]
PR: https://github.com/Kademi/kademi-dev/pull/6936

**Comment by bradmac** [comment]
Merged. Current version is 1.6.6

**Comment by Uafinder** [comment]
Looks good
