### ISSUE TITLE
New standard report which will export all bids, including winning and non-widding bids

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#6905]

**Comment by tuzzmaniandevil** [comment]
QueryTable has been created called auctionsBidsTable.

Waiting on issue https://github.com/Kademi/kademi-dev/issues/6910 to create the report

**Comment by tuzzmaniandevil** [comment]
Done

**Comment by Uafinder** [comment]
Report is empty
![image](https://user-images.githubusercontent.com/1945230/54431914-587b7900-4730-11e9-8a9d-c734aa294457.png)
http://vladtest57l.admin.kademi-qa.co/reporting/auctionsBidsReport

Also CSV gives an error
![image](https://user-images.githubusercontent.com/1945230/54431940-6a5d1c00-4730-11e9-82ba-40e5a74b9f8a.png)

**Comment by tuzzmaniandevil** [comment]
PR: https://github.com/Kademi/kademi-dev/pull/6933

**Comment by Uafinder** [comment]
- ok, userqa07 is a part of org1 organisation, but nothing showing in org title field
- also i don't think that POINTS_PROFILE correct value for orgid field
![image](https://user-images.githubusercontent.com/1945230/54525699-7984d980-497d-11e9-858e-68f3fb8ed9ca.png)
http://vladtest57m.admin.kademi-qa.co/reporting/auctionsBidsReport

Also i dont know if this a req, but report is not sensitive to date time range selector

**Comment by bradmac** [comment]
> ok, userqa07 is a part of org1 organisation, but nothing showing in org title field

@Uafinder this example is an individual based points program, so i would not expect it to show an organisation. 

To test the org feature use an organisation based points bucket (like for OTM)

> also i don't think that POINTS_PROFILE correct value for orgid field

Yes, this value looks incorrect. @tuzzmaniandevil is there any reason for displaying POINTS_PROFILE here?

**Comment by tuzzmaniandevil** [comment]
> > also i don't think that POINTS_PROFILE correct value for orgid field
> 
> Yes, this value looks incorrect. @tuzzmaniandevil is there any reason for displaying POINTS_PROFILE here?

Just a bug :-) Removed.

**Comment by tuzzmaniandevil** [comment]
PR: https://github.com/Kademi/kademi-dev/pull/6949

**Comment by Uafinder** [comment]
ok, looks good
