### ISSUE TITLE
Auction: Group auction

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#6909]
we set up a group of items for the same specified time period. As the auction function as a group, members can then hold the winning bid on a maximum of one item at a time from the group of items.

**Comment by tuzzmaniandevil** [comment]
https://github.com/Kademi/kademi-dev/pull/6921
https://github.com/Kademi/kademi-platform/pull/53

**Comment by Uafinder** [comment]
I was able to make a highest bid for all auctions in of set of auctions.
![image](https://user-images.githubusercontent.com/1945230/54431405-02f29c80-472f-11e9-8597-2e512a085477.png)
http://vladtest57l.admin.kademi-qa.co/auctions/#panel_auctions-tab

**Comment by tuzzmaniandevil** [comment]
Fixed

**Comment by tuzzmaniandevil** [comment]
PR: https://github.com/Kademi/kademi-platform/pull/54

**Comment by Uafinder** [comment]
Ok, looks good
