### ISSUE TITLE
Video playback res

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#691]
Am I correct in thinking the options for playback do not go as high as 720p?  

![video-res](https://cloud.githubusercontent.com/assets/2201340/9704071/704b1df0-54dc-11e5-8077-b4f7f30473f2.jpg)

**Comment by bradmac** [comment]
We generate in 3 resolutions up to and including 720p

**Comment by bradmac** [comment]
But can have a look sometime
