### ISSUE TITLE
JS error when opening keditor

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6915]
![image](https://user-images.githubusercontent.com/1945230/54274039-cccae680-458f-11e9-8a88-e30a7ff40e35.png)
http://vladtest57h.admin.kademi-qa.co/pages/vladtest57hweb/version1/
http://vladtest57h.admin.kademi-qa.co/pages/vladtest57hweb/version1/?contenteditor=page1.html

**Comment by anhnt** [comment]
fixed on other issue

**Comment by Uafinder** [comment]
looks good
