### ISSUE TITLE
Add templates for auction app

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6916]
![image](https://user-images.githubusercontent.com/1945230/54276030-e589cb00-4594-11e9-9c7b-718bbfedc234.png)
http://vladtest57h.admin.kademi-qa.co/websites/vladtest57hweb/version1/#panel_controllers-tab

**Comment by bradmac** [comment]
Done. Requires auctions-lib 1.2.6

**Comment by Uafinder** [comment]
Looks good
