### ISSUE TITLE
Sales Data Claimer App: Enhance manual claim component

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#6929]
Enhance manual claim component to improve useability for many claims (ie more then 5) - currently the standard sales
claim component allows entering multiple transactions, but the UI is only suitable for a few transactions. Needs to be more
tabular for handling 10 or more.

**Comment by bradmac** [comment]
Currently the fields are vertical, so a single claim is about half a laptop screen height.

We just want either a new component, or an option on the existing component, so that fields for each claim item are arranged horizontally, so we can fit several on a screen.

**Comment by tuzzmaniandevil** [comment]
Added an option to the existing component

**Comment by tuzzmaniandevil** [comment]
![image](https://user-images.githubusercontent.com/3378330/54499903-10509680-497c-11e9-993c-a05f5ffb578b.png)

**Comment by tuzzmaniandevil** [comment]
PR: https://github.com/Kademi/kademi-dev/pull/6937

**Comment by bradmac** [comment]
Merged. Requires 1.6.6

**Comment by Uafinder** [comment]
Looks great!
