### ISSUE TITLE
Rename badge error

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6930]
![image](https://user-images.githubusercontent.com/1945230/54413322-ec801d00-46fd-11e9-8e37-fda8160ab02e.png)
http://vladtest57j.admin.kademi-qa.co/recognition/252076/
![image](https://user-images.githubusercontent.com/1945230/54413358-0a4d8200-46fe-11e9-845e-68d203792600.png)

**Comment by bradmac** [comment]
Fixed

KRcog 1.1.9

**Comment by Uafinder** [comment]
Looks good
