### ISSUE TITLE
Manage users: add to group button not clickable

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6932]
![image](https://user-images.githubusercontent.com/1945230/54433836-7a2b2f00-4735-11e9-96cc-48905e63f56e.png)
http://vladtest57l.admin.kademi-qa.co/manageUsers

To reproduce:
Go to page
Select some org from right side filter
Select some checkbox for users
Try to click add to group

**Comment by bradmac** [comment]
Closing as duplicate - https://github.com/Kademi/kademi-dev/issues/6924
