### ISSUE TITLE
JS error on manage promotion page

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6935]
Eg:
https://mhiaainstaller.admin.kademi-qa.co/rewards/rugby/#details-tab

![image](https://user-images.githubusercontent.com/826458/54498654-cdd48d00-496e-11e9-8864-5abbb8fb9893.png)

Note formBuilder lib is installed

**Comment by anhnt** [comment]
keditor-lib 1.4.1 and rewards-lib 1.3.6

**Comment by Uafinder** [comment]
![image](https://user-images.githubusercontent.com/1945230/54513757-ffdef280-4960-11e9-8502-62611d34eceb.png)
https://mhiaainstaller.admin.kademi-qa.co/rewards/rugby/#details-tab

**Comment by bradmac** [comment]
If this is something to do with having keditor in the same page, we can just have it open a new tab like we do for web pages

**Comment by anhnt** [comment]
Looks ok now. keditor was failed to sync

**Comment by Uafinder** [comment]
Yeah, looks good now
