### ISSUE TITLE
Error when save badge details

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6941]
![image](https://user-images.githubusercontent.com/1945230/54513250-872b6680-495f-11e9-8356-6c9fb28e3786.png)
http://vladtest57m.admin.kademi-qa.co/recognition/302550/badges/302552/#panel_details-tab
![image](https://user-images.githubusercontent.com/1945230/54513277-990d0980-495f-11e9-8a40-097d93e59658.png)

**Comment by bradmac** [comment]
Requires KRecognition 1.2.0

**Comment by Uafinder** [comment]
Looks good
