### ISSUE TITLE
group auction place highest bid on two or more auction enhance error message

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6944]
![image](https://user-images.githubusercontent.com/1945230/54519204-a8478380-496e-11e9-86e4-e1062c08bd3d.png)
When you leading one auction in auction set and try to bid to the second one incorrect error message appears.
Should be something like "you're already leading the other auction in auction group"
http://vladtest57mweb-vladtest57m.kademi-qa.co/auctions/2/
http://vladtest57m.admin.kademi-qa.co/auctions/#panel_auctions-tab

**Comment by bradmac** [comment]
@tuzzmaniandevil please use "You are already leading an auction in this set of auctions"

**Comment by tuzzmaniandevil** [comment]
Done

**Comment by tuzzmaniandevil** [comment]
PR: https://github.com/Kademi/kademi-platform/pull/56

**Comment by bradmac** [comment]
Merged. Requires platform update.

**Comment by Uafinder** [comment]
Ok, looks good
