### ISSUE TITLE
content-lib: Support image content in showHideButtonComponent

### ISSUE THREAD

**Issue by trungjc** [Kademi/kademi-dev#6945]
https://github.com/Kademi/projects/issues/964

**Comment by trungjc** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/704946/54541643-df4c8200-49cc-11e9-8d75-7725e9ffc31c.png)

Note that if user add image, they will cannot see the text

**Comment by Uafinder** [comment]
Looks good
