### ISSUE TITLE
add engagement score history feature for user

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6946]
We need that feature urgently because it's very hard to track what added, what removed and why.
I tried to test Vaya score interventions and but this is a nightmare.
Simple table needed for user:
date | added/removed | total | what rule (source) it came from

needed for this one
https://github.com/Kademi/client-vaya-vayability/issues/440

**Comment by bradmac** [comment]
A score history would be very difficult. But what i think we can do is show a break-down on the current score

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/54569686-a4843180-4a40-11e9-806c-e51df2c29e4c.png)

**Comment by bradmac** [comment]
Requires
- platform update
- KJourneys 1.1.2
- leadman-lib 3.4.5

**Comment by Uafinder** [comment]
It doesn't change current  value or keep it different
![image](https://user-images.githubusercontent.com/1945230/54601166-119ac580-4a47-11e9-864a-4e784db7ee6a.png)
http://vladtest57n.admin.kademi-qa.co/leads/344852/#information-tab
![image](https://user-images.githubusercontent.com/1945230/54601196-224b3b80-4a47-11e9-9ee8-e41d05ca8c7f.png)
http://vladtest57n.admin.kademi-qa.co/leads/343472/#information-tab

**Comment by Uafinder** [comment]
Got it... it should be recalculated manually?

**Comment by bradmac** [comment]
> Got it... it should be recalculated manually?

Correct. There is currently no feature implemented to recalculate automatically

**Comment by Uafinder** [comment]
ok, thanks... it will help a little
