### ISSUE TITLE
KRedirects not working - waterware

### ISSUE THREAD

**Issue by stephen-fueldesign** [Kademi/kademi-dev#6953]
http://waterware-waterware.kademi.com.au/about should redirect to http://waterware-waterware.kademi.com.au/aboutus/

As per https://waterware.admin.kademi.com.au/kredirect/

<img width="584" alt="Screen Shot 2019-03-19 at 6 37 56 PM" src="https://user-images.githubusercontent.com/39784677/54582583-2c386300-4a76-11e9-9a79-c131c47f4ab7.png">

I checked console.log() and I checked Data > Logs, nothing came up... _accept for a crazy amount of pricing rule lookups on a 404 page that is not even a product page, but that's a story for another day_.

Please let me know if you get the redirects to work.

**Comment by bradmac** [comment]
KRedirect app is not enabled for that site

![image](https://user-images.githubusercontent.com/826458/54583060-d5cc2400-4a77-11e9-8b45-ddc79d9d3e9a.png)

**Comment by stephen-fueldesign** [comment]
Working. thanks!
