### ISSUE TITLE
Journey designer doesn't work on VAya CI

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#6961]
![image](https://user-images.githubusercontent.com/1945230/54692294-73cdf600-4b2d-11e9-9981-cf85bafd4979.png)
http://vayability.admin.kademi-ci.co/funnels/participant-registration-journey/version1/#journeyBuilder-tab

**Comment by anhnt** [comment]
working just fine for me

**Comment by bradmac** [comment]
Looks good to me

**Comment by Uafinder** [comment]
Hmmm... looks restart helped
