### ISSUE TITLE
Social Media component not working in emails

### ISSUE THREAD

**Issue by joelatfuel** [Kademi/kademi-dev#6963]
Waterware are preparing to send out an internal email communication. They have dragged the social media component into the email, and it is visible when you are editing in the editor, but disappears when an email is sent.

Here's the link: http://waterware.admin.kademi.com.au/groupEmails/143944722/edmeditor?fileName=index.html

**Comment by bradmac** [comment]
as discussed, please enable email-lib for the website the email is connected to
