### ISSUE TITLE
Impossible to create & configure points bucket and rewards store

### ISSUE THREAD

**Issue by DimitryNechaev** [Kademi/kademi-dev#705]
we had rewards store assigned to wrong bucket and wrong site 
![image](https://cloud.githubusercontent.com/assets/12892631/9760567/95ef9df6-5739-11e5-96f4-f7d398bb0737.png)

I created new rewards store in Mercedes rewards instead. 
![image](https://cloud.githubusercontent.com/assets/12892631/9760553/754066f8-5739-11e5-9865-8ec7371f96ca.png)

It created it in wrong site again and there is no way to update the site.
![image](https://cloud.githubusercontent.com/assets/12892631/9760583/a8d9f268-5739-11e5-827b-c02121336fe0.png)

Moreover, there is no way to specify the groups inside the store.
So I opened the points bucket instead. I created the bucket right before and assigned the required groups. And when opened I saw there are no these groups.
When I tried to add the groups again I saw the error
![image](https://cloud.githubusercontent.com/assets/12892631/9760638/29ab5b0c-573a-11e5-9267-e8ad938af4e1.png)

Guys, how long you are going to make admin changes without any further testing?
I need this functionality ASAP. Please fix it URGENTLY.

@bradmac i'm assigning this to you.

**Comment by tuzzmaniandevil** [comment]
I've fixed the group assignment issue and have also added the ability to change the points bucket and website of a reward store.
Also renames "Stores" to "Reward stores"
