### ISSUE TITLE
Manage groups page drag/drop support should use drag handles

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#710]
Currently, on the manage groups page, you can drag groups to move them between group folders.You can drag on anything in the title area. But often you drag and drop accidentally when you only meant to click.

To solve this we should have up/down drag handles like on the manage courses page

**Comment by ducdhm** [comment]
@bradmac: The manage courses page has the same problem but I added the delay time for that page so click event still ok. I do the same thing with Manage groups page. Beside that, I also fixed some bugs related to the behavior when you drag some a group, but don't drop it in other folder or outside of current folder, the save progress still works
