### ISSUE TITLE
Improve text editor

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#712]
The text editor used ACE editor and can use a few enhancements
 - keyboard shortcuts 
 - better save progress integration
 - maybe load formatting options based on file type?

**Comment by ducdhm** [comment]
Will show message `We found a version of this file in your local. Do you want to restore it?` if have local storage!

**Comment by anhnt** [comment]
@ducdhm shortcut setting needs to be saved when it is changed. currently it always uses ace as default shortcut

**Comment by ducdhm** [comment]
@anhnt Fixed! Will deploy soon!

**Comment by anhnt** [comment]
@ducdhm local change restore may be optional since it asks me each time I open a file to edit

**Comment by bradmac** [comment]
Yeah, that popup message is not cool. Maybe just have a little history/clock icon in the toolbar, click on that to see a list that can be restored?
