### ISSUE TITLE
Creating immediate 2nd calednar event does not clear form fields

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#72]
If you create a calendar event, then once it's generated create a 2nd, the form fields contain the previous event details.

**Comment by bradmac** [comment]
Just need to reset the form after saving

**Comment by tuzzmaniandevil** [comment]
Fixed

**Comment by Uafinder** [comment]
No, create event form looks like doesn't reset to initial state - still active.

**Comment by tuzzmaniandevil** [comment]
Sorry I fixed wrong page. Fixed Now

**Comment by Uafinder** [comment]
Yeap. Works ok!
