### ISSUE TITLE
Dashboard enhancements 2

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#724]
Extension to https://github.com/Kademi/kademi-dev/issues/713

Please make the website panels at the top of the admin dashboard col-6 for large resolutions, and use a split panel design as below. The left half should be an image, either a default image or the website image as the current layout users.

The right half should be summary info of the website
 - title (ie display name)
 - domain name if present
 - live branch
- icon links to config and tools as in the current layout

![webpanel](https://cloud.githubusercontent.com/assets/826458/9839914/7dcca660-5adb-11e5-8195-d00dc13845e8.png)

**Comment by ducdhm** [comment]
Done!

**Comment by bradmac** [comment]
Tried it out with my sites and i think needs a couple of changes
 - aspect ratio of 1x1 for images seems too high. I think 4:3 might be better
 - currently the title and version are the same font, we need the website title to be more prominent, the version could be small font, italic, etc. Something to differentiate it

**Comment by bradmac** [comment]
Also, i had to do a hard refresh to get the updated css. Make sure anytime you update the css to increment the version number on the css link so that it downloads immediately

**Comment by bradmac** [comment]
Also, on medium resolution the image is absolutely massive, it goes full width and occupies similar amount of height. Really, the image should never be more then 150 high. I'm not sure you'll be able to achieve good fluidity with a fixed aspect ratio

**Comment by bradmac** [comment]
And i was thinking that on smaller resolution we drop the image, and just keep the details part of the panel. That might help the issue above.

**Comment by bradmac** [comment]
Just added some quick and dirty updates to prepare for release.
