### ISSUE TITLE
Add SMS action to email triggers

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#73]
On email triggers page, add a panel to send SMS. The text should be processed through a templater to allow personalisation
 - Allow apps to provide SMS gateways
 - Have a single default SMS gateway configured to use Kademi account
 - Customers can provide their own credentials to use their own gateway account
 - SMS management page to provide history of SMS sends, including status

**Comment by tuzzmaniandevil** [comment]
This is now done.
Currently we support ClickSend as an SMS gateway.
SMS history can be found under Talk & Connect.

**Comment by paddyow** [comment]
Make the SMS message field a text field vs. input field

Validate when the user adds more than 160 characters.  Would be nice to do this real-time as they type.  This is important because if the the end user is sending 2000 SMS messages, and the message is over 160 characters, the system will send x2 (4000 messages) at a greater cost to the customer.

**Comment by Uafinder** [comment]
1. SMS History page is bad
![image](https://cloud.githubusercontent.com/assets/1945230/5807249/09e1a6ae-a02a-11e4-9f74-4ac38dcb0372.png)
2. SMS app looks like haven't preferences to configure SMS gateway.
3. Should be a symbol counter i think for give understanding to user how much symbols he has. Validation on 160 in real-time doesn't work. Static validation doesn't work as well.

**Comment by tuzzmaniandevil** [comment]
"Should be a symbol counter i think for give understanding to user how much symbols he has. Validation on 160 in real-time doesn't work. Static validation doesn't work as well." -> Fixed

**Comment by tuzzmaniandevil** [comment]
" Static validation doesn't work as well." -> Can't reproduce.

**Comment by Uafinder** [comment]
" Static validation doesn't work as well." -> Can't reproduce
Just fill up "message to send" and "SMS provides" fields. "Message to send" - entering a lot more than 160 symbols. Push save changes. Saved ok. No validation message appears.

**Comment by paddyow** [comment]
Created a ClickSend account
Added user name and API key
Setup a trigger here - http://admin.asmidemo.olhub.com/autoEmails/sms/
Fired the trigger by adding myself to a group
2x results were added to the SMS queue as IDLE - http://admin.asmidemo.olhub.com/smsHistory/

Can you advise why they are not firing.

**Comment by bradmac** [comment]
And @tuzzmaniandevilcould you update the method which formats trigger descriptions to include outputting the sms action

**Comment by paddyow** [comment]
1x sms just came through.

**Comment by paddyow** [comment]
Keen to understand delay time and if a lengthy wait is expected.

**Comment by tuzzmaniandevil** [comment]
Overlooked some error handling, I have restructured the app to be more reliable and faster.

**Comment by tuzzmaniandevil** [comment]
Deployed to QA
