### ISSUE TITLE
Text Editor: Add formatting capabilities for Html/XML and Javascript

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#732]
Auto indent and format HTML/XML and JavaScript .
Would be nice to have it mapped to a keyboard shortcut like SHIFT+ALT+F (Netbeans mapping)

**Comment by bradmac** [comment]
I thought that was standard with ace?

**Comment by ducdhm** [comment]
@bradmac Cloud9 Editor has but ACE Editor not. We need add formatter for it if we wanna suport this feature :)

**Comment by ducdhm** [comment]
https://github.com/c9/c9.ide.format

**Comment by bradmac** [comment]
Could we integrate something like this?
https://github.com/victorporof/Sublime-HTMLPrettify

**Comment by bradmac** [comment]
the C9 lib looks cool, license is friendly

**Comment by ducdhm** [comment]
Yep, if we have nodejs server for run it :) I can help you set it up!

**Comment by tuzzmaniandevil** [comment]
We have a NodeJS server already (it runs our LESS compiler) but wouldn't we want to keep the formatting in browser?

**Comment by bradmac** [comment]
Ideally it would be in the browser, but if its easier to do in Node then thats ok.

**Comment by ducdhm** [comment]
I found this plugin (https://github.com/beautify-web/js-beautify). I'll apply when have free time

**Comment by ducdhm** [comment]
Done!
