### ISSUE TITLE
KPI - Delete by period 

### ISSUE THREAD

**Issue by Keegan01** [Kademi/kademi-dev#741]
We need to be able to delete ALL KPIs for a single period.
This will allow us to make changes to users and their data in case there are errors and allow us to just re-run the KPIs for the single month. 
Thanks

**Comment by Keegan01** [comment]
Hey @bradmac Can you you have a look at this today? We NEED this. We had some problems seeing results for August and it looks like it has already been processed for this period (Unsure why)

**Comment by bradmac** [comment]
Thats a significant feature, not something that can be done in a day. We've scheduled it for delivery next week which is the best we can do.

**Comment by Keegan01** [comment]
Okay thanks @bradmac

**Comment by bradmac** [comment]
Ability to do this from the new manage KPI screen
