### ISSUE TITLE
Admin omni-search: phase 1, user search only

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#746]
Hey Brad, how about adding a textbox above `Dashboard` item with feature is search the navigation item?

![search](https://cloud.githubusercontent.com/assets/1289631/9928086/9ca779a6-5d4d-11e5-9bd4-36af7bbe87fb.png)

**Comment by bradmac** [comment]
Love it :+1: 

We can easily do an omni-search on users, products and blogs. Including repository content is trickier because of the branching, many customers might have 10 live branches so they would see content items 10 times. Although i guess we might be able to do some intelligient collapsing.

**Comment by ducdhm** [comment]
As @paddyow's comment in #734, we will remove the Collapse button. So let make the search panel's width is full

**Comment by bradmac** [comment]
Hey, just one problem with having the search there is that the menu gets collapsed down to icons for tablet view. 
![search](https://cloud.githubusercontent.com/assets/826458/9946970/d3f26928-5dea-11e5-8752-b66f74d7d29b.png)

**Comment by bradmac** [comment]
We will make this an omnisearch, but for first phase just use user search. I've made the /manageUsers page able to generate output as JSON, so use handlebars and a template to format that into a nice output in a popup div.
