### ISSUE TITLE
Improve automation page layout: 2

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#748]
- provider better visibility of activity
- clearer enabled/disabled status
- plain english explanation of what it will do
- clearer understanding that selecting options will filter events

 extension to - https://github.com/Kademi/kademi-dev/issues/747

**Comment by tuzzmaniandevil** [comment]
End result:
![nimbus-image-1445573478739](https://cloud.githubusercontent.com/assets/3378330/10684400/1be49a24-79a9-11e5-9d3a-9570d9770426.png)
