### ISSUE TITLE
Polls app

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#749]
Please create a custom app to allow Kademi account owners to publish polls on their sites. This will be added to the market place.
- allow admins to create polls, where each poll has
 - a list of questions
 - a list of groups to target the poll to
 - text for the poll
 - optional rich content
 - start and end dates (optional)
 - enabled/disabled
 - a points system and number of points to award for submission (optional)
- the poll should be displayed on dashboards using a standard portlet, if active (ie is between start and end dates and enabled)
- when a user submits an answer that should be stored as a json record
- user's should not be allowed to submit, if they have already
- the poll should be able to generate a bar graph showing answers which is shown on the dashboard for users who have submitted previously
- the poll should have a page where users can see full poll content and results, and comment

**Comment by ducdhm** [comment]
@Uafinder Hi Vlad, please kindly help me testing Kademi Poll ap (kpoll). 
The test link is here http://ducdhm.admin.olhub.com/kpoll/managePolls/
The login details:
 * User: ducdhm-tester
 * Password: test123
The frontend site: http://test-kpoll.olhub.com/

**Comment by bradmac** [comment]
Hey @paddyow, Vlad is off fishing, would you like to have a crack at @ducdhm s app?

**Comment by paddyow** [comment]
Suggested Feedback:

When first adding a poll:
- Show a question field and 2 answer fields as this would be the minimal required fields to run a poll
- The button 'Add question' should be 'Add answer' or 'Add response' as the admin is configuring the answers for the question
- The button 'Add answer' feels like it should sit below any newly created answer field

Question:
Answer #1:
Answer #2:
(Add answer)

Configuring the Poll screen:
- The field 'Name' should be called 'Poll question'
- Felt the from and to dates should not be mandatory for users who want a poll permanently 
- Add question button should be 'Add answer' or 'Add response'
- Should points system be "Points bucket"?
- Point should be "Reward points"
- Option to download CSV of answers

**Comment by Uafinder** [comment]
1. Doubling polls on the frontend
![image](https://cloud.githubusercontent.com/assets/1945230/10478109/dd266f0c-7263-11e5-9ea7-4ccaf3ef8628.png)

2. When there no enabled poll "You don't have any poll for now" text is doubling too. 
![image](https://cloud.githubusercontent.com/assets/1945230/10478115/eb018e86-7263-11e5-8a9d-738abd631671.png)

3. The polls are visible only for members of administrators group. If i have a user which is part of Learners and assign a poll to Learners group user doesn't see it. This is possible connected to absent appropriate security role for group.
![image](https://cloud.githubusercontent.com/assets/1945230/10478176/54b6c65c-7264-11e5-9704-51c96dde8817.png)
![image](https://cloud.githubusercontent.com/assets/1945230/10478182/613863e0-7264-11e5-8941-100809b9d381.png)
![image](https://cloud.githubusercontent.com/assets/1945230/10478191/6a91d5e8-7264-11e5-8439-06447729457c.png)

**Comment by ducdhm** [comment]
Please move to https://github.com/ducdhm/kpoll/issues for checking issues

**Comment by Uafinder** [comment]
It's not ready for test. Most of issues are still active.

**Comment by ducdhm** [comment]
Let's move to https://github.com/ducdhm/kpoll/issues for tracking issues
