### ISSUE TITLE
Additional auction notifications

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#75]
- Auction Closes - event triggered for each person who has placed a bid or is watching
- Participant has been outbid

**Comment by bradmac** [comment]
yes, please. i think we should be able to notify people who bidded that the auction closed. So a trigger will need to fire for each bidder

**Comment by tuzzmaniandevil** [comment]
Adjusted AuctionClosedEvent:
Fired when an auction closes, it has the following actions:
- CLOSED_WITH_WINNER - Fired when there is a winner, the source profile is the winner
- CLOSED_WITHOUT_WINNER - Fired when there is no winner
- CLOSED_BIDDER - Fired for every user that has placed a bid on the auction. Exludes the winner
