### ISSUE TITLE
Implement OAuth2 login and profile linking

### ISSUE THREAD

**Issue by jaredburgess** [Kademi/kademi-dev#750]
Implement platform support for OAuth authentication:
 - profile linking: an existing user should be able to connect to their social media account from the profile page
 - login: an existing user with a linked social media account should be able to login with that social media account

Each organisation should have a list of configured OAuth providers. When adding a provider should be able to choose a pre-configured one for twitter, facebook, google, etc. Or add a new custom one, such as a self managed ADFS server

Original post
Particularly thinking about this for Bartercard Academy where all staff should effectively be in there. This will remove access to staff when they leave automatically and remove the need for remembering another password. Could be optional per site?

**Comment by bradmac** [comment]
Yes, we have partially implemented support for OAuth2, which i think is compatible with ADFS. 

https://social.technet.microsoft.com/Forums/office/en-US/7d6f91e8-7bdb-4a6e-a9e9-9e90e858cf7a/does-adfs-2-support-oauth-20?forum=winserverDS
