### ISSUE TITLE
Improvement for User Management screen

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#758]
This screen is quite messy. I think we should improve for this screen. @bradmac What do you think about this?

![user_manager](https://cloud.githubusercontent.com/assets/1289631/9986613/ed6c6504-6068-11e5-960e-2ea685e918a6.png)

**Comment by bradmac** [comment]
I think that screen is actually quite good!!!

**Comment by ducdhm** [comment]
I think just re-arrange the section above of table list. It looks not well. But it's depend on you. I can spend my free time for making some variants for this screen.

**Comment by bradmac** [comment]
its ok for now, we've got other pages more in need of help!
