### ISSUE TITLE
New templating engine for greater dev control of output html

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#759]
This introduces a new templating engine available for theme bootstrap335 and up which changes the template rendering process to give developers more control. Previous themes are unchanged.

See example 1 below for an example of a page template

A couple of notes
 - there is no required theme template as there was in the old templater. The convention shown above is to parse a theme template and then to invoke themeHeader and themeBody macros.
 - these macros use velocity's #@ syntax which allows a bodyContent argument to be provided to the macro
 - the themeHeader template will merge less source files into a single compiled path which are added with $templater.pushLess as shown above. The developer can choose not to use this process
 - all page templates need to be modified to use the new templating process
 - html pages still indicate their template with a link element as previously, ie 
````
<link rel="template" href="/theme/home.html" />
````
 - a html page may itself be a template by using the special href of "." as its template. See example 2 below
 - there is no default page template, so if a page does not provide a template it does not get templated
 - there is no requirement to have a doctype or not, unlike the previous engine that has no effect on the templating process

**Example 1: Canonical page template**
````
<html>
    #parse("/theme/masterTemplate.html")
    <head>
        #@themeHeader( "Hello world" )
         $templater.pushLess("/theme/my-extra-styles.less", "all")
        <link href="/theme/otherstyles.css" rel="stylesheet" media="all"/>
        #end
    </head>
    <body>
        #@themeBody()
            <p>content blah blah blah</p>
        #end
    </body>
</html>
````

**Example 2: Page being its own template**
````
<html>
	<head>
		<title>Self template example</title>
		<link rel="template" href="." />
	</head>
	<body>
        <p>This page is called $page.name</p>
	</body>
</html>
````

**Comment by bradmac** [comment]
I think having a doctype on a page is a well established way of indicating that templating should not be applied, and i dont think we should change that.

But we could allow doc types on page templates, and preserve that in the output.

**Comment by bradmac** [comment]
@ducdhm I've integrated a few page templates in bs335
 - user/profile.html
 - user/dashboard.html
 - user/passwordReset.html
 - learner/myLearning.html


But we need every template from every app to be copied across to this theme and integrated with the new process. Could you please finish this off as a top priority?

Note that portlet templates should not need to change at all

**Comment by ducdhm** [comment]
@bradmac blogs/viewBlogs.html is error when using new templater

**Comment by ducdhm** [comment]
@bradmac relative links to js or css is failed when using new templater

**Comment by bradmac** [comment]
@ducdhm yeah, the new one templater doesnt re-write markup so js and css links are rendered exactly as they are in the template.

Fixed the view blogs problem, the templater was being invoked with the admin theme.

**Comment by ducdhm** [comment]
@bradmac In Learning page, the content of module page is not loaded :(

**Comment by ducdhm** [comment]
@bradmac Done. Just need you check the module page
