### ISSUE TITLE
Search feature works incorrectly

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#766]
Please access this link: http://oceanyouthplatform.olhub.com/contentSearch?q=ocean+youth
At result "Youth 20 (Y20)", please click the link. You'll see the error page. If you change `oceanyouthplatform` to `oceanyouth`, you'll see the blog page of other website.

**Comment by bradmac** [comment]
Note that re-indexing will be required

**Comment by bradmac** [comment]
Appears to still be affecting OY
https://github.com/Kademi/Ocean-Youth/issues/70#issuecomment-144643702
