### ISSUE TITLE
Using double quotes in a subject line causes issues when saving

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#768]
If you have a subject in an email i.e.

Blah blah "Ra Ra"

....click save then navigate away and back again the subject line can omit the "Ra Ra" part which means if the user clicks saves, the subject will update and permanently delete the "Ra Ra" part.

**Comment by bradmac** [comment]
Duplicate of https://github.com/Kademi/kademi-dev/issues/765
