### ISSUE TITLE
Tags for points sources and debits report

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#77]
Anything which can allocate points (ie a points source) must allow the administrator to add tags.
Each debit against points (eg a purchase from a reward store) is linked to the points records required to make up the debit amount

A report shows debits against the points records and their tags.

This is to allow invoicing of points to multiple funding sources.

**Comment by tuzzmaniandevil** [comment]
Ready for initial release.

**Comment by Uafinder** [comment]
https://github.com/Kademi/kademi-dev/issues/189

**Comment by Uafinder** [comment]
![image](https://cloud.githubusercontent.com/assets/1945230/6356680/bd66c5de-bc67-11e4-9d26-f1bf3f4053f0.png)

**Comment by Uafinder** [comment]
![image](https://cloud.githubusercontent.com/assets/1945230/24324659/254b3680-1193-11e7-8bdb-c52b5f4ceacc.png)
Incorrect sorting
It's sorted by the last changes date...
