### ISSUE TITLE
Implement Server Name Indication in grizzly

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#78]
This task is to allow Kademi customers to add SSL security to their Kademi hosted websites through the administration console.

Kademi is a multi-tenanted application, meaning that many different customers are served from the same instance and same cluster. Kademi customers all use their own domain names, and they use DNS to direct them to our servers IP. For example these sites are hosted on kademi:
http://www.rbhealthhub.com.au
http://www.pet-ed.com.au

We would like our customers to be able to use SSL (or TLS) but the traditional approach only allows a single SSL certificate per network interface, which is a problem because we use a single IP for all our customers.

All multi-tenanted sites have this problem, and the new mechanism to solve it is called Server Name Indication - http://en.wikipedia.org/wiki/Server_Name_Indication

Tomcat does not support SNI, which is one of the main reasons for switching to the grizzly framework.

To add SNI support to Kademi using grizzly you need to:
 - modify the Website class to allow storing SSL certificates in the database, associated with a website
 - modify ManageWebsiteBranchFolder and its template manageWebsite.html to allow uploading and/or editing the certificate
 - edit the SNIServerConfigResolver in Kademi to lookup the certificate

Also, please provide detailed instructions for setting up the keystore etc for development environment.

**Comment by YOULee** [comment]
In processing on #78:

changed html/classes as below:
1) manageWebsite.html
2) ManageWebsiteBranchFolder.java

3) Website.java,  
the added fields as below:
    keyStoreFile;
    keyStorePass; 
    trustStoreFile;
    trustStorePass;   
    securityProtocol;
