### ISSUE TITLE
Editor removing <i> tag in blogs

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#786]
When opening a blog article, the editor is removing the <i> class.  
```
<li class="list-group-item"><i class="icon-email3"></i>&nbsp;&nbsp;Email</li>
```
After opening in editor becomes:
```
<li class="list-group-item">&nbsp;&nbsp;Email</li>
```

**Comment by ducdhm** [comment]
@bradmac About this issue, I think it's depend on what's your config for toolbar of CKEditor. Example: with basic config, all your class, id will be removed.

**Comment by tuzzmaniandevil** [comment]
CKEditor removes empty tags by default, This is a simple config change :-)
