### ISSUE TITLE
Link is incorrect in comments

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#787]
The link "http://docs.kademi.co/programs/dev/d3/app-2/phandling-file-uploads.html" will be converted to "//http://docs.kademi.co/programs/dev/d3/app-2/phandling-file-uploads.html"

**Comment by bradmac** [comment]
I couldnt reproduce that, but i could see that:
````
have a look at http://google.com vvv
````

Is converted to
````
have a look at <a rel="nofollow" target="_blank" href="//http://google.com">http://google.com</a> vvv
````
