### ISSUE TITLE
Pasting content into the Brief section of blogs breaks template

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#789]
If you past content directly into the Brief section of a Blog article on a Kademi blog, the template breaks slightly where the content appears at the top of the page:

![rspca lead generation](https://cloud.githubusercontent.com/assets/2201340/10128713/681a3de0-65f9-11e5-8868-ec55aa536bed.png)

The remedy is to clean the content in Notepad first, then past it into the Brief field.

**Comment by bradmac** [comment]
Cant reproduce. Got a link?

**Comment by paddyow** [comment]
Admin: http://kademi.admin.olhub.com/blogs/kb/paddy-test/#bodyCopy-tab
Version: http://version28.kademi-www.olhub.com/blogs/kb/paddy-test/#.VgoYkXqqpBc

I pasted the following content from a Google Doc:
See how Reckitt Benckiser built a world class pharmacy channel engagement program

Note the top of the screen here: http://version28.kademi-www.olhub.com/blogs/kb/paddy-test/#.VgoYkXqqpBc

**Comment by bradmac** [comment]
The problem is due to the og tags in the custom template. Its producing this, which is invalid:
````
<meta property="og:url" content="http://version28.kademi-www.olhub.com/blogs/kb/paddy-test/" />
<meta property="og:description" content="<span id="docs-internal-guid-2578d794-176f-d524-9ec9-f5e56d7214c3"><span style="font-size: 14.6667px; font-family: Arial; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">See how Reckitt Benckiser built a world class pharmacy channel engagement program.</span></span>
" />
<meta property="og:site_name" content="Kademi.co"/>
<meta property="og:image" content="http://version28.kademi-www.olhub.com$img" />
````

**Comment by bradmac** [comment]
Depends on https://github.com/Kademi/kademi-dev/issues/792
