### ISSUE TITLE
Admin page "revert to version" function is crushing Kademy

### ISSUE THREAD

**Issue by DimitryNechaev** [Kademi/kademi-dev#794]
I was editing site pages
http://admin.mercedes.olhub.com/repositories/mercedes-reward-program/version20/theme/apps/components/#files-tab

I located the file 
![image](https://cloud.githubusercontent.com/assets/12892631/10163358/bfa98302-66f5-11e5-8222-b022a29f2e8f.png)

And on history clicked on Restore to the version, made 20 minutes ago by another person
![image](https://cloud.githubusercontent.com/assets/12892631/10163373/d6faa41e-66f5-11e5-821e-e8b63a20c7b7.png)

After that page refreshed and the directory displayed empty.
![image](https://cloud.githubusercontent.com/assets/12892631/10163335/97ab829c-66f5-11e5-9308-103a9a331ac7.png)

And because EVERY ENTIRE PAGE is using code from the /theme/apps/ all site is now ruined:
![image](https://cloud.githubusercontent.com/assets/12892631/10163417/3dbc7736-66f6-11e5-90a9-264aae6a3b7b.png)

**Comment by DimitryNechaev** [comment]
Now the directory lost ALL files, the site IS DEAD and this is when using the Kademy's admin function.
This was reported to you @bradmac by Skype.
Now this is reported here. Please be so kind to revert our site to life and fix this functionality, because it is needed.

**Comment by DimitryNechaev** [comment]
Please also revert lost files in ~\Version20\theme\apps\components\

**Comment by bradmac** [comment]
@DimitryNechaev that problem was resolved some time ago. Please clear your cache or do a refresh on the manage files page to get the updated js file.
