### ISSUE TITLE
Generic profile image not displaying in stream

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#796]
There are certain stream items that are being displayed with no generic profile image.  In Chrome there is a broken image, in FF there is a blank space.

http://admin.rspca.olhub.com/

![rspca australia dashboard](https://cloud.githubusercontent.com/assets/2201340/10180974/eff43ab0-6755-11e5-83f1-2860434e1fd8.png)

![rspca australia dashboard1](https://cloud.githubusercontent.com/assets/2201340/10180977/f2a88f04-6755-11e5-9e72-003635dd1b51.png)

**Comment by ducdhm** [comment]
@paddyow Can you provide me the default image?
