### ISSUE TITLE
Deleting multiple contact requests invoke error message

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#797]
http://admin.rspca.olhub.com/manageContacts/

When you select more than 1 contact request, hit delete, the contact requests are deleted but you still get the error.

![error](https://cloud.githubusercontent.com/assets/2201340/10181372/6c1b87b6-675a-11e5-80f1-1356d7b03593.png)

**Comment by tuzzmaniandevil** [comment]
Contact request wasn't being removed from the index.
