### ISSUE TITLE
Improve users CSV upload

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#800]
Allow CSV and excel files to be uploaded and be able to set custom mappings.

Work flow:
- Upload file - Returns file hash and returns the first 2 lines on the file and available extra fields
- Start the wizard to map columns to profile fields or extra fields
- Submit wizard to a background process that returns a progress status

This API should be avaible to other apps, and should also be able to specify a specific group to add the users to

**Comment by bradmac** [comment]
:+1: would be good to get this moving

**Comment by bradmac** [comment]
And it would be good if we can save the import configuration, so the user can upload again without remapping fields

**Comment by bradmac** [comment]
@tuzzmaniandevil please implement java side, hand over to @anhnt to complete

**Comment by tuzzmaniandevil** [comment]
Added support for excel files to TableService, so the customer import in leadman also now supports excel files as well as CSV files :-)

**Comment by tuzzmaniandevil** [comment]
Basic implementation is done, I will add support for custom fields once anh has done the front end

**Comment by anhnt** [comment]
Hey @tuzzmaniandevil, can you please continue with custom fields support? The wizard will appear when you click Upload Users CSV  button
![user](https://cloud.githubusercontent.com/assets/735555/14380284/df4b7446-fda8-11e5-824f-8ac1bd3a0b88.PNG)

**Comment by tuzzmaniandevil** [comment]
Custom fields integrated :-)

**Comment by Uafinder** [comment]
1. I've upload file
2. Choose fields, most of them, username is absent (but it looks like should be absent)
3. Next, it shows me that 3 profiles will be created
4. Next, uploading
5. 0 profiles is created

File: https://drive.google.com/file/d/0B9V2ZH-h_cR2Y0dnQlVSOFRMS3c/view?usp=sharing
Why?

**Comment by tuzzmaniandevil** [comment]
There was a bug when an orgId wasn't provided. It's now fixed
