### ISSUE TITLE
Ensure email queue processing cannot process multiple times

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#801]
It appears that its possible for an email item to be sent multiple times if database connectivity is lost during processing.

Items to be sent are marked as pending (EmailItem.STATUS_PENDING) when returned from EmailItemQueueStore for sending. Emails are only loaded if their state is null or retry and the retry period has expired, so this should prevent multiple sends.

So please investigate and try to see how a loss of database connection (possibly an intemittent loss) can result in multiple sends

**Comment by tuzzmaniandevil** [comment]
The loss of the database caused the queue store to throw an exception, which in turn caused a loop in Aspring mail sender.
