### ISSUE TITLE
Add support for eCommerce stores

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#803]
This should work similar to reward stores except have a selectable currency like cash(credit cards), crypto currency and so on.

The store should use the existing shopping cart but the shopping cart should be extended to show a different checkout depending on the currency on the items in the cart,
The app that provides that currency will then generate a portlet for the checkout process.

**Comment by tuzzmaniandevil** [comment]
@ducdhm Can you give me a hand with this?
The checkout page should have the following layout.

![ecomcheckout](https://cloud.githubusercontent.com/assets/3378330/10327480/2f7898d0-6d04-11e5-8c11-d58e3d94d20d.png)

**Comment by ducdhm** [comment]
Let's bring it out!
