### ISSUE TITLE
Trigger source not referencing trigger name

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#805]
http://admin.rspca.olhub.com/autoEmails/97863739/#triggers-tab

Should the drop down not show the trigger name that the user gives the previous trigger?  Currently it is referencing the old way which is to pull in the trigger name in the URL.

![untitled-1](https://cloud.githubusercontent.com/assets/2201340/10210439/62061ce8-682a-11e5-8ff7-2b646ef3910b.png)

**Comment by bradmac** [comment]
I think its showing the name property, but should be the title
