### ISSUE TITLE
Option to send to either SMS or Email

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#81]
The new SMS feature allows triggers to send an email and/or SMS.

However, it would be unusual to want to send someoone both. But a user might want the system to send to which ever is available.

So please add an input to the manage auto email page which is displayed if both email and sms are enabled "Prefer SMS", which means to send an SMS if the user has a phone number, otherwise send email.

**Comment by tuzzmaniandevil** [comment]
Done :-)
