### ISSUE TITLE
Create new theme for bootstrap 3.3.5

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#810]
@bradmac What do you think about Update Bootstrap theme to version 3.3.5? I mean new theme "Bootstrap 3.3.5"

**Comment by bradmac** [comment]
yep, sounds good. Go for it! But prioritise issues which are affecting users first

**Comment by ducdhm** [comment]
Gotcha. Let me bring it on!

@bradmac Can I remove the redundant theme attributes only in this theme (https://github.com/Kademi/kademi-dev/issues/811) ?

**Comment by bradmac** [comment]
@ducdhm yep, with a new theme we can do anything :)
