### ISSUE TITLE
Redundant theme attributes

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#811]
@bradmac As you know, we have 2 theme attribute which user never can not change it: `navbarItemsStyle` and `navItemsDiv`. So I want to suggest remove them in `normal.html` file of Bootstrap 3.2.0 themes such bootstrap320, bootstrap320.zion... and make the default class for navbar is `nav navbar-nav navbar-right`.

```
#if( $formatter.isNull($website.themeAttributes.navbarItemsStyle) )
#set($navItemsType = "nav navbar-nav")
#else
#set($navItemsType = $website.themeAttributes.navbarItemsStyle)
#end

#if( $formatter.isNull($website.themeAttributes.navItemsDiv) )
#set($navItemsDiv = "nav-right")
#else
#set($navItemsDiv = $website.themeAttributes.navItemsDiv)
#end

<div class="navbar-collapse collapse navbar-main-collapse">
    #portlets("shoppingCart")
    <ul class="$navItemsType $navItemsDiv navbar-right">
        ...
    </ul>
</div>
```

**Comment by bradmac** [comment]
@ducdhm , remember we cant change themes once they are used by clients!

**Comment by ducdhm** [comment]
@bradmac I mean I just remove them in normal.html file (or just adding some comments about the redundant or deprecate). Clients always overwrite this file, right?

**Comment by ducdhm** [comment]
Let me remove them in new theme `bootstrap335`
