### ISSUE TITLE
Module thumbnail images not showing correctly 

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#821]
http://version18.idhealth-training.olhub.com/myLearning

Note how (Management of mental disorders) is show the image with a number 4.  It should show the image 8 - Copy.png 

http://admin.3dn.olhub.com/websites/idhealth-training/version18/programs/prof/pmh1/mod8/#details-tab

**Comment by ducdhm** [comment]
@bradmac We have problem with `/alt-...` request. Problem happens with file have space and `-` character in file name.

Example:
Original: http://version18.idhealth-training.olhub.com/programs/prof/pmh1/mod8/8%20-%20Copy.png
Alt file: http://version18.idhealth-training.olhub.com/programs/prof/pmh1/mod8/8%20-%20Copy.png/alt-300-300.png

**Comment by bradmac** [comment]
I dont think its a problem with space. I just forced a regeneration and its fine:

http://version18.idhealth-training.olhub.com/programs/prof/pmh1/mod8/8 - Copy.png/alt-300-300.png

**Comment by ducdhm** [comment]
@paddyow But the first version of `http://version18.idhealth-training.olhub.com/programs/prof/pmh1/mod8/8 - Copy.png/alt-300-300.png` is showed 4. What happened?

**Comment by bradmac** [comment]
i dont know. I would like to know, but it doesnt appear to be anything to do with the space. Might be something to do with how the file was copied. Can you reproduce the problem?

**Comment by ducdhm** [comment]
@bradmac I can't reproduct this problem again. I think we'll close this issue and will create other for this if it happens again.
