### ISSUE TITLE
Org colours on dashboard panel

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#827]
Red looks like an error.  Suggestion the coloring of the org slices does not include red.

![color](https://cloud.githubusercontent.com/assets/2201340/10354894/f2fd7ac6-6db0-11e5-9887-1f7cf6cb3b9f.png)

**Comment by ducdhm** [comment]
@paddyow  Here is new schema color for chart. It's ok for you? ![untitled](https://cloud.githubusercontent.com/assets/1289631/10386828/c63cbe5e-6e85-11e5-8b50-e71fa42a5e44.png)

**Comment by ducdhm** [comment]
Patrick said "Cools!" for this:

![bbbbb](https://cloud.githubusercontent.com/assets/1289631/10386980/237107fa-6e87-11e5-897b-7311481ff5af.png)
