### ISSUE TITLE
Changing a website name, the choose group access causes error page

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#833]
http://admin.developer.olhub.com/websites/campaign%202015/version1/#panel_details-tab

Rename the website ID and Display Name, then go to group access and choose a new group.

**Comment by bradmac** [comment]
We should make renaming a website a seperate action, ie not part of the edit form.

**Comment by tuzzmaniandevil** [comment]
Because the website name has changed the url needs to change as well so the groups sends the request to the updated URL. This is an easy fix.

**Comment by bradmac** [comment]
See above. Best thing is just to make it a seperate rename action. Could be a action on drop down on the list page.

**Comment by tuzzmaniandevil** [comment]
the URL will still need to be updated or the page redirected to the new URL.

**Comment by bradmac** [comment]
If you do a rename on the list page, then you can just do a reload fragment on the list page. No change to the detail page, except to remove the edit field

**Comment by tuzzmaniandevil** [comment]
Done :-)
