### ISSUE TITLE
Comments enhancements: notification

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#835]
The comments system currently have no means of users following a thread or being notified when there is another comment, and there is no way to reply to a comment. This reduces potential engagement.

So what we want is
 - users can follow discussions
 - users are sent an email notification of there is a comment in a discussion they're following
 - users can un-follow a discussion
 - users can choose to follow a discussion (ie they dont have to comment to follow it)

**Comment by tuzzmaniandevil** [comment]
- users can mention, or tag, other users in a similar way as facebook or twitter. (i think facebook is better, but harder) has been moved into a seperate issue See #843
