### ISSUE TITLE
Survey App

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#837]
Requirements:
- allow admins to create survey, where each survey has
 - a list of questions
 - a list of groups to target the survey to
 - Introduction or brief for survey
 - rich content for question
 - start and end dates (optional)
 - enabled/disabled
 - a points system and number of points to award for submission (optional)
- the survey should be displayed on dashboards using a standard portlet, if active (ie is between start and end dates and enabled)
- when a user submits an answers that should be stored as a json record
- user's should not be allowed to submit, if they have already
- the survey should be able to generate a bar graph showing answers which is shown on the dashboard for users who have submitted previously
- the survey should have a page where users can see full poll content and results, and comment

**Comment by anhnt** [comment]
This app is done except following which needs to be implemented later:

- a points system and number of points to award for submission (optional)

@Uafinder can you please test it by go to this http://admin.anhnt.olhub.com/ksurvey
Survey list on frontend site should be here http://anh.olhub.com/ksurvey

**Comment by Uafinder** [comment]
https://github.com/anhnt/ksurvey/issues

**Comment by anhnt** [comment]
just created new few issues for this one
