### ISSUE TITLE
Installing and finding Apps

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#838]
After installing an App, it was not self explanatory to go to Applications then switch it on in order to start using it. 

Suggestion:  An alert saying go to Applications to switch it on, or have a balloon popup over the LHS nav prompting the using to switch on the App.

**Comment by bradmac** [comment]
Really we need a rebuild of the apps screen. Currently all kademi apps are shown even when not enabled, which makes for a very long list, instead we should only show enabled apps. 

Users should have a seemless experience for finding and installing/enabling apps regarldless of whether they are standard or custom.

**Comment by ducdhm** [comment]
IMHO, I think we should display app in grid instead of list view or maybe 2 options for viewing apps

**Comment by ducdhm** [comment]
And more information for app such as description, screenshot, link to app, etc.

**Comment by bradmac** [comment]
We can have a concise and simple view of installed apps (like android does) but have a more comprehensive UI for finding and installing apps from the marketplace. Wes has added screenshots to marketplace items, so that should be there already.
