### ISSUE TITLE
Add/remove group button does not work

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#841]
http://thewholeofbusiness.admin.olhub.com/websites/thewholeofbusiness/version1/#panel_groups-tab

Modal does not popup.

**Comment by ducdhm** [comment]
@bradmac I have tested on this site and seem likes `getTitle` method of `io.milton.cloud.server.apps.website.ManageWebsiteBranchFolder` class is error. 

You can see it at bottom of application list http://thewholeofbusiness.admin.olhub.com/websites/thewholeofbusiness/version1/#panel_apps-tab

**Comment by bradmac** [comment]
Should be fixed now
