### ISSUE TITLE
Allows users to opt-in to groups from contactUsApp

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#85]
This will allows users to opt-in to groups from the contact us page the same way users can from the signup page.

**Comment by Uafinder** [comment]
Is it this feature?
https://github.com/Kademi/kademi-dev/issues/102

**Comment by bradmac** [comment]
No, that configuration is what contact requests are automatically added to, but this new feature is to allow users to choose to be added to additional groups to receive communications. This might require a developer to test, so will assign to Wesley for testing and signoff

**Comment by bradmac** [comment]
@tuzzmaniandevil could you please test this in production (ie on your mum's site) and then close if it works properly

**Comment by Uafinder** [comment]
What exactly should i test here?

**Comment by bradmac** [comment]
- configure contactus app to add contacts to some group, eg "CustomerContacts"
 - create a group which will be an option mailing list, eg "PromotionsEmailList"
 - configure CustomerContacts group to have PromotionsEmailList as an opt-in group
 - now go to the front end contact us page, you should see a checkbox for the Promotions email list
 - select it and complete the form and submit it
 - a profile should be created and added to both CustomerContacts and PromotionsEmailList groups
 - submitting the form without checking the box the profile should not be added to the promotions group

**Comment by Uafinder** [comment]
Works perfect!
