### ISSUE TITLE
Comment email notifications fixes

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#859]
1. You should never be notified of your own comment, thats a bug
2. A user should be able to turn on/off email notifications in their profile screen, so need a profile page option to control this

Note that the existing unfollow function should be used to allow the user to turn off notifications for particular posts.

----
@bradmac After I added param unfollow for request to `_comment`, I can not add comment or reply 
anymore

**Comment by tuzzmaniandevil** [comment]
Are you sending the "unfollow" parameter when someone comments?

**Comment by ducdhm** [comment]
@tuzzmaniandevil Yes

**Comment by tuzzmaniandevil** [comment]
That is why the comment is not working, the "follow" & "unfollow" needs to be seperate ajax calls
