### ISSUE TITLE
contactus page

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#86]
http://asmi-demo.olhub.com/contactus

**Comment by tuzzmaniandevil** [comment]
Fixed

**Comment by Uafinder** [comment]
Is it deployed to prod?

**Comment by bradmac** [comment]
Yep. Just got missed

**Comment by Uafinder** [comment]
contact us page is ok now
Small buG
![image](https://cloud.githubusercontent.com/assets/1945230/5873344/ff6488f0-a2fd-11e4-8ddf-ea47451906cd.png)

**Comment by tuzzmaniandevil** [comment]
"contact us page is ok now
Small buG" - Fixed

**Comment by bradmac** [comment]
@tuzzmaniandevil seeing as you're not going to close this i will...
