### ISSUE TITLE
Comment notifications

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#861]
Websites which have comments and forums should provide a web based notifications capability.

- A notification should tell a user about activity occuring on a post they're following.
- There should be a maximum of one notification per post per user.
- The notification should give the user a description of the activity which has occured. Eg 
 - "Bob Jones and 3 others have replied to your comment"
 - "Bob Jones commented on *How to build a hotrod*"
 - "Bob Jones replied to your comment on *Jow to build a hotrod*"
- if a user is viewing a post they should not receive notifications for it

I suggest we might want to trigger notification emails when new notifications are added

**Comment by tuzzmaniandevil** [comment]
Woohoo!
On 20/10/2015 7:30 pm, Brad McEvoy <notifications@github.com> wrote:Closed #861.
