### ISSUE TITLE
Split page editing out of file manager, into seperate edit website pages section

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#875]
Switching between tabs "Edit pages" and "Files and folders" is confusing for users. 

Instead, the file manage should only have the files and folders view. A seperate page in the Manage Content menu should be for editing website pages (currently under website manager). 

The page manager should be optimised for editing html pages, and allow easy jumping to the file manager. 

The file manager should be optimised for file management, and allow easy jumping to the page manager if in a website.

**Comment by ducdhm** [comment]
:+1:
