### ISSUE TITLE
Rich text editor is broken

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#880]
Take a look at this http://alcon.admin.olhub.com/groupEmails/confirmation/#messages-tab

**Comment by mamun4343** [comment]
still same.

**Comment by ducdhm** [comment]
@bradmac I have no idea why `getEditTemplateLink` is not available. Can you double-check it?

**Comment by mamun4343** [comment]
also, i see error uploading images using rich text editor.
