### ISSUE TITLE
Store state of sidebar in admin console

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#881]
Request from @anhnt

**Comment by anhnt** [comment]
:+1: nice feature

**Comment by tuzzmaniandevil** [comment]
:+1:  I've been wanting this as well :-)

**Comment by tuzzmaniandevil** [comment]
Just tested it, The page loads with the side bar expanded then it collapses which looks bad. Maybe check the cookie in templating and adjust the class instead of doing it after the page loads in JavaScript

**Comment by ducdhm** [comment]
@tuzzmaniandevil Big deal in here is class for toggle sidebar is in body. Any template codes outside of body is not compiled. Do you have any idea?
