### ISSUE TITLE
High performance blob persistence

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#884]
Create a new class which will wrap Parser, called FastParser

This will take a blobstore and hashstore, but internally it will wrap the blobstore with a multi threaded one.

The multi-threaded blobstore will wrap an underlying blobstore. Blobs added to it go into a bounded queue with size X and will be processed asyncronously by X threads. The queue should block when full.

The FastParser's parse method will block waiting for all the queue to be empty before its parse method returns.

Using this approach the persistence is still syncronous (which is needed for transactional integrity) but data should be saved X times faster then using the current single threaded approach. 

Probably use a value of 10 for X. Assuming the blob stores are not IO or cpu bound this should make saving 10 times faster then present.

FastParser is intended to be used the same as Parser, ie it is created for each usage and then released.

**Comment by bradmac** [comment]
Should solve the problem of slow saving of large videos

**Comment by tuzzmaniandevil** [comment]
First basic implementation done.
