### ISSUE TITLE
New admin omni search breaks layout on tablet/phone

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#899]
LG G3:
![screenshot_2015-10-27-18-10-19](https://cloud.githubusercontent.com/assets/3378330/10750084/041aa516-7cd6-11e5-930c-5cab7564d6be.png)

Samsung Galaxy Tab S2 8":
![screenshot_2015-10-27-18-12-04](https://cloud.githubusercontent.com/assets/3378330/10750118/7af96302-7cd6-11e5-976c-81084f86ef29.png)

**Comment by tuzzmaniandevil** [comment]
Any update on this?

**Comment by ducdhm** [comment]
It's your @tuzzmaniandevil ;)

![untitled](https://cloud.githubusercontent.com/assets/1289631/10932357/a5914850-8302-11e5-9cf6-cace0ebaafbf.png)

**Comment by ducdhm** [comment]
And tablet 
![untitled](https://cloud.githubusercontent.com/assets/1289631/10932381/d342a884-8302-11e5-9bc2-ff40a74a8bb5.png)
