### ISSUE TITLE
Rewards preview version bad

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#90]
![image](https://cloud.githubusercontent.com/assets/1945230/5835760/e7099474-a174-11e4-96fd-ae6f4412c644.png)

**Comment by bradmac** [comment]
That would be expected if there were no websites in that account. @Uafinder can you confirm if that account has websites?

**Comment by Uafinder** [comment]
Yes. This account has websites.
1. QA. Sporg1. It has one website. But preview look like on the screenshot:
![image](https://cloud.githubusercontent.com/assets/1945230/6217285/124c5be8-b61b-11e4-872f-9fad3a497ef4.png)

2. Prod. Asmi-demo. It has two websites, but it shows one of them.
![image](https://cloud.githubusercontent.com/assets/1945230/6217295/2e8ad46a-b61b-11e4-8cf1-69bb0f2dda22.png)
