### ISSUE TITLE
Contact us to allow templated assign to group field

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#91]
The meta tag assignToGroup now accepts MVEL template expressions. Eg:

<script title="assignToGroup" type="data/parameter" >@{referer.name}</script>

**Comment by tuzzmaniandevil** [comment]
@bradmac Works on QA Server when I put the meta data in a non templated and in a templated site. I assume this has not been deployed to production yet.

**Comment by tuzzmaniandevil** [comment]
Tested and working on my site
