### ISSUE TITLE
Error when removing item in Cart screen of E-Commerce App

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#914]
It works if you're logged-in and not works when you're anonymous

![untitled-1](https://cloud.githubusercontent.com/assets/1289631/10836968/c947bd8a-7ee6-11e5-85f1-8fc43aa0a40d.png)

But it works when I set quantity is 0

**Comment by ducdhm** [comment]
@tuzzmaniandevil It does not work. Please double-check at http://ecommerce-demo.kademi-beta.co/storeCheckout/

**Comment by tuzzmaniandevil** [comment]
Fixed :-)
