### ISSUE TITLE
Automation details screen is broken after creating

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#927]
![fireshot capture 4 - automation_ after a p_ - http___samsungnz admin olhub com_autoemails_114159940_](https://cloud.githubusercontent.com/assets/1289631/10877755/7db21b80-817b-11e5-9941-ad751c2913b0.png)

**Comment by bradmac** [comment]
Thats not really broken, its just that the sizing of the panels doesnt work very well at that resolution, same problem with the dashboard stats panel. At the resolution when they break down to the 2 cols they're enormous.
