### ISSUE TITLE
Treeview in File Manager screen

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#928]
Something like that:
![untitled-1](https://cloud.githubusercontent.com/assets/1289631/10880025/6be519de-818a-11e5-893d-81c84912b244.png)
- Default will show sub-folder of current folder
- When expanding sub-folder will load the content of sub-folder lazy

@bradmac What do you think about this?

**Comment by bradmac** [comment]
I've used tree views before, and i really dont like them myself.

:-1:

**Comment by ducdhm** [comment]
@bradmac I think user can quick access with treeview. Or maybe we can add the breadcrumb bar like edit webpage.

![untitled](https://cloud.githubusercontent.com/assets/1289631/10900230/e26c8c92-820f-11e5-8c36-7478e2168232.png)
