### ISSUE TITLE
Html editor breaking templating code

### ISSUE THREAD

**Issue by tuzzmaniandevil** [Kademi/kademi-dev#951]
The HTML Editor replaces `"` with `&quote;` and `'` with `&#39;` which causes the templated to throw an exception. Even whe edited from the "source" tab.

For example when trying to edit Certificates and use templating it stops users from completing modules and the certificate can't be generated.

**Comment by ducdhm** [comment]
@tuzzmaniandevil Why do you use HTML Editor instead of text editor? CKEditor always convert " and ' to HTML Entity for security reason.

**Comment by tuzzmaniandevil** [comment]
@ducdhm The manage certificate page uses the html editor. Not all our customers know html syntax so they need a WYSIWYG editor

**Comment by tuzzmaniandevil** [comment]
So we need something like this http://docs.ckeditor.com/#%21/api/CKEDITOR.config-cfg-protectedSource or http://docs.ckeditor.com/#%21/guide/dev_advanced_content_filter

**Comment by tuzzmaniandevil** [comment]
Actually I can sort it out :-)

**Comment by bradmac** [comment]
:+1:

**Comment by tuzzmaniandevil** [comment]
Added a basic fix to the certificates page, Will need to find a better solution though.
