### ISSUE TITLE
Kademi change color of image after uploading

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#957]
@bradmac We have interesting issue. 

Left is original image and right is uploaded one

![aaaaa](https://cloud.githubusercontent.com/assets/1289631/11085171/d7cca558-8875-11e5-8734-7f723ff30292.png)

**Comment by bradmac** [comment]
Cannot reproduce. @ducdhm sent me the original file and it appeared as green, same as on the server

**Comment by ducdhm** [comment]
Won't fix
