### ISSUE TITLE
Could not add a profile with a domain suffix of .digital

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#958]
Validation on the form would not allow .digital

http://kademi.admin.olhub.com/manageUsers/

Click add new user

Enter a user i.e. bob@bob.digital and submit

**Comment by tuzzmaniandevil** [comment]
The regex limited domains between 2 & 6 characters, changed it to 2-63 to match DNS standards
@ducdhm This has been applied to jquery.forms-1.0.9.js, can you make the same change to 1.1.0 when you commit it please?

**Comment by tuzzmaniandevil** [comment]
Changed the regex to match according to the DNS standards. see here: http://www.regular-expressions.info/email.html

**Comment by tuzzmaniandevil** [comment]
Created a new version of the forms plugin. 1.1.0
