### ISSUE TITLE
Manage reward points enhancements

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#965]
Ability to sort by multiple column headers

**Comment by bradmac** [comment]
hey @diegoperezn does sorting by "Tag/Reason Code"? Note that is foreign key in Points but a text field in PointsDebit, so would be tricky to sort on.

The simplest thing might be to just not have a sort on that column

**Comment by diegoperezn** [comment]
Done! Added 2 new Select to filter by "Tag" and "Reason Code" and remove the sort by "Tag/Reason Code" column.

**Comment by hoanglinhlan** [comment]
1: why can I see many un row in list reason code? 
![image](https://cloud.githubusercontent.com/assets/20508726/25699561/fe3b802a-30ed-11e7-8302-0fbaad42b795.png)
Where can I control my list reason code? 
2: I have one record with tag A and some record with reason code "P" but when I filter with tag A and reason code "P". the system dont show anything 
![image](https://cloud.githubusercontent.com/assets/20508726/25699649/51894d48-30ee-11e7-848d-0cd7b3300de0.png)

**Comment by bradmac** [comment]
1. This list is found by querying the database. But i think the problem is that query is not being restricted to the current org, it appears to be querying the whole db!

**Comment by diegoperezn** [comment]
1. Yes, I was retrieving all the reasons, Added the restriction to show just the ones in the current organisation.
2. This page shows the credit and debit points, reason code is for debit and tag is for credit. If you select both is an in and its ok that the result is empty. We can change it to use and "Or" between those filters if you want.

**Comment by diegoperezn** [comment]
Changed the reason and tag to an "Or" condition.

**Comment by hoanglinhlan** [comment]
hi @diegoperezn 
https://lan-test.admin.kademi.com.au/rewards/points/
I still can see the record what is a creadit with tag A
here is image before filter 
![image](https://cloud.githubusercontent.com/assets/20508726/25794634/0accb87a-33fc-11e7-8c90-0ed414034e7f.png)

after filtered
![image](https://cloud.githubusercontent.com/assets/20508726/25794643/11ca2982-33fc-11e7-956a-de88d8e0a665.png)

**Comment by hoanglinhlan** [comment]
passed
