### ISSUE TITLE
Cannot see blog status when managing blog

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-dev#97]
![blog](https://cloud.githubusercontent.com/assets/2201340/5854003/45937a74-a27d-11e4-85d7-9dbf65b72d8d.png)

Need to be able to see if the blog is published or not from the manage blog screen.

**Comment by bradmac** [comment]
Hey @tuzzmaniandevil, is this what you did today? If so can you assign to Vlad and make ready for test in prod

**Comment by tuzzmaniandevil** [comment]
I did, It's already in prod and working.

**Comment by Uafinder** [comment]
Yeap, works fine
