### ISSUE TITLE
Strange thing with RB search: fail

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#98]
Weird thing is happen in RB site when i try to search "Gaviscon" word.
![image](https://cloud.githubusercontent.com/assets/1945230/5862434/88c17254-a27a-11e4-8706-91515c2c2160.png)
Any other words is ok. All browsers, all pages.

**Comment by bradmac** [comment]
Appears to be an issue where the search term is found in a field which is not displayed, so there is no "highlighted" field. Fixed.

**Comment by Uafinder** [comment]
Looks like you've applied this fix on prod too. Seems fine for me.
