### ISSUE TITLE
Can't not upload image in CKEditor when using custom app

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#988]
I got this error message:

```
<html><body><h1>/kpoll/managePolls/_DAV/PUT Not Found (404)</h1></body></html>
```

**Comment by ducdhm** [comment]
@bradmac Can you help me check this issue? It happen on custom apps

**Comment by bradmac** [comment]
I've added the ability for custom apps to declare resources as collections, and associate them with a repository. The repo will be auto-created when needed. 

Eg:

```
controllerMappings
    .adminController()
    .path('/ksurvey/')
    .enabled(true)
    .defaultView(views.templateView('ksurveyapp/manageSurveys.html'))
    .addMethod('GET', 'getSurveys')
    .addMethod('POST', 'saveSurvey', 'saveSurvey')
    .addMethod('POST', 'deleteSurvey', 'deleteSurvey')
    .addMethod('POST', 'clearSurveyResult', 'clearSurveyResult')
    .build();

controllerMappings
    .adminController()
    .path('/ksurvey')
    .enabled(true)
    .addMethod("GET", "checkRedirect")
    .build();



controllerMappings
    .adminController()
    .path('/ksurvey/(?<surveyId>[^/]*)/')
    .enabled(true)
    .addPathResolver('surveyId', 'findSurvey')
    .isCollection("survey-content")
    .defaultView(views.templateView('ksurveyapp/surveyDetail.html'))
    .addMethod('GET', 'getSurvey')
    .addMethod('POST', 'saveSurvey')
    .addMethod('POST', 'saveSurvey')
    .title('generateTitle')
    .build();

controllerMappings
    .adminController()
    .path('/ksurvey/(?<surveyId>[^/]*)')
    .enabled(true)
    .isCollection("survey-content")
    .addMethod("GET", "checkRedirect")
    .build();
```

This then allows files to be uploaded via the _DAV gateway:

![screenshot from 2017-10-04 16-29-10](https://user-images.githubusercontent.com/826458/31158848-3315dc18-a921-11e7-9ce6-6436f12822a7.png)

And this is then uploaded to the newly created repo "survey-content"
![image](https://user-images.githubusercontent.com/826458/31158859-46158be2-a921-11e7-95d3-cf57da57fbf2.png)

**Comment by bradmac** [comment]
And is also available as json via the ajax gateway:
![image](https://user-images.githubusercontent.com/826458/31158899-8dfb6c4c-a921-11e7-9fe7-560faae6d232.png)

**Comment by bradmac** [comment]
Actually that approach isnt going to work :(

**Comment by bradmac** [comment]
--- Take 2 ---

**Comment by bradmac** [comment]
OK, so we now have 3 new methods which allow representing a true hierarchy:
- .pathSegmentName('ksurvey')
- .pathSegmentResolver('surveyId', 'findSurvey')
- .child(..)

The 2 pathSegment methods allow you to specify that a controller resource should be located based on a single path segment only, rather then applying  regex to a path.

pathSegmentName just locates on exact text matching. pathSegmentResolver uses a JS function to locate an object, and the segment only matches if an item is found.

The child method allows chaining controllers so path segments are progressively resolved, eg /a/b/c

Here is an example:

```
controllerMappings
    .adminController()
    .pathSegmentName('ksurvey')
    .enabled(true)
    .defaultView(views.templateView('ksurveyapp/manageSurveys.html'))
    .addMethod('GET', 'getSurveys')
    .addMethod('POST', 'saveSurvey', 'saveSurvey')
    .addMethod('POST', 'deleteSurvey', 'deleteSurvey')
    .addMethod('POST', 'clearSurveyResult', 'clearSurveyResult')
    .child(
        controllerMappings
            .adminController()
            .pathSegmentResolver('surveyId', 'findSurvey')
            .mountRepository("survey-content")
            .enabled(true)
            .defaultView(views.templateView('ksurveyapp/surveyDetail.html'))
            .addMethod('GET', 'getSurvey')
            .addMethod('POST', 'saveSurvey')
            .addMethod('POST', 'saveSurvey')
            .title('generateTitle')
    )
    .build();
```
