### ISSUE TITLE
Reload Fragment supports multi-elements

### ISSUE THREAD

**Issue by ducdhm** [Kademi/kademi-dev#989]

**Comment by bradmac** [comment]
Already does, just provide a callback which gets called with the new dom, and replace whatever element you want :)

**Comment by ducdhm** [comment]
Thank @bradmac for suggestion. Btw, with new version of reloadFragment, you can add multi-selectors like `$('#header, #content, #footer')`. If your selector does not contain `id`, will ignore this element. And `whenComplete` callback has 4 arguments are `newDom, resp, status, xhr`. With `newDom` is jQuery object which contains HTML content of reloading request.
