### ISSUE TITLE
Searches (in-module and global) works with problems

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#99]
1. Waterco in-module search looks like doesn't work at all. try to search anything - no reaction.
2. ASMI demo:
- try to search "spain" for example - no results
- try to search "Spain.[3]" - error 500
![image](https://cloud.githubusercontent.com/assets/1945230/5863285/164345c0-a281-11e4-97ca-66673e37d7be.png)
- try to search "Barcelona" in seat module, first page - all pages are displayed.
- try to search "Martorell" - no results
and so on...

**Comment by bradmac** [comment]
I've fixed #98, which should also fix this issue. If there is still a problem can you please provide URL's for the pages you've seen problems on?

**Comment by Uafinder** [comment]
![image](https://cloud.githubusercontent.com/assets/1945230/5992498/07845630-aa35-11e4-8772-ddfe9560885b.png)

https://github.com/Kademi/kademi-dev/issues/126

**Comment by bradmac** [comment]
I've re-indexed the search database here - http://admin.waterco.olhub.com/repositories/waterco/waterco88/manageSearch

Seems to be necessary sometimes

**Comment by Uafinder** [comment]
Most of problems gone. There are leave some questions but i think we can leave them for now
